import type { ArtistArchive, ArchiveRelation } from './archiveData';
const rel=(kind:ArchiveRelation['kind'],label:string,detail?:string):ArchiveRelation=>({kind,label,detail});

export const archiveBatch206:Record<string,ArtistArchive>={
  'taryn-simon':{
    artistId:'taryn-simon',
    projectCoverage:'纵向深化：The Innocents → An American Index of the Hidden and Unfamiliar → A Living Man Declared Dead and Other Chapters；重点补足摄影、文字、分类系统与制度性“可见/不可见”之间的关系。',
    imageCoverage:'Whitney 官方艺术家、展览与馆藏页面提供作品与 installation views。本站保留官方入口与馆藏信息，不复制未确认再发布许可的图像。',
    note:'Simon 的关键不是把罕见对象拍得漂亮，而是把摄影放进档案、调查、文字说明和分类系统里，持续测试图像究竟是在证明事实，还是在制造一种看似可信的秩序。',
    projects:[
      {title:'The Innocents',cluster:'photography / wrongful conviction / eyewitness identification / DNA exoneration',period:'2002',summary:'早期系列聚焦因暴力犯罪被定罪、后来通过 DNA 证据洗清罪名的人。Whitney 对 Larry Mayes 的馆藏说明指出，他曾因受害者依据照片进行身份识别而被判罪并服刑近二十年，而没有生物证据将其与犯罪联系起来。系列因此直接研究摄影既作为司法证据又可能参与误认的双重角色。',actions:['具体方法：不是抽象讨论“摄影会骗人”，而是寻找已经发生司法错误的个案，让被平反者重新站到与案件、逮捕、误认或自由相关的地点中被摄影。','结构：肖像与案件文字共同工作；观众必须在人物面孔、司法叙述和后来出现的 DNA 证据之间来回校正判断。','重要性：系列把 photographic identification 从中性的识别工具转成需要被审查的制度技术，为 Simon 后来对 archive、access 与 classification 的长期研究建立起点。'],sourceUrl:'https://whitney.org/artists/9743',images:[],relations:[rel('机构','Whitney Museum of American Art','馆藏与艺术家研究页；The Innocents 个案说明')]},
      {title:'An American Index of the Hidden and Unfamiliar',cluster:'large-format photography / access / taxonomy / hidden institutions',period:'2007',summary:'Simon 对美国境内通常不可见、难以进入或受制度控制的场所和对象进行调查式摄影，题材跨越 science、government、medicine、entertainment、nature、security 与 religion。Whitney 2007 个展明确把项目描述为对“谁拥有 access”这一分界的研究。',actions:['具体动作：通过申请、谈判和制度许可进入普通公众通常无法进入的地点，再尽可能使用 large-format view camera 制作高度清晰、冷静的图像。','分类机制：不同领域被放进统一 index；核废料、冬眠黑熊等彼此无关对象因共同的“被隐藏/受控访问”条件而形成国家制度肖像。','观看悖论：作品把不可见对象变得诱人、清晰，却同时用文字提醒观众——一张清楚的照片并不等于真正获得制度内部的知识。'],sourceUrl:'https://whitney.org/exhibitions/taryn-simon',images:[],relations:[rel('机构','Whitney Museum of American Art','2007 solo exhibition, Mar 9–Jun 24')]},
      {title:'A Living Man Declared Dead and Other Chapters I–XVIII',cluster:'bloodlines / photography-text panels / genealogy / political systems',period:'2008–2011',summary:'该项目以全球不同血缘关系为调查单位，把人物肖像、缺席者位置、文字和 contextual images 编排成章节式系统。Whitney 收藏的 Chapter XIV 为五部分 inkjet prints with dry-transfer type，整体超过六米宽，显示作品不是单张肖像而是大型信息架构。',actions:['制作逻辑：以 bloodline 为基础逐人摄影，同时记录无法或拒绝参与者留下的空缺，使“缺席”也成为可读数据。','展陈：肖像网格、文字说明与补充图像并置；观众面对的是近似档案/科学分类表的界面，而不是传统纪实摄影 sequence。','方法演变：从 The Innocents 的单一制度错误与 American Index 的地点访问，推进到 genealogy 本身如何与国家、宗教、领土、暴力和偶然事件交叉。'],sourceUrl:'https://whitney.org/collection/works/44570',images:[],relations:[rel('机构','Whitney Museum of American Art','Chapter XIV collection')]}
    ],awards:[],exhibitions:['Whitney Museum — An American Index of the Hidden and Unfamiliar, 2007'],sources:[{label:'Whitney · Taryn Simon artist page',url:'https://whitney.org/artists/9743'},{label:'Whitney · An American Index of the Hidden and Unfamiliar',url:'https://whitney.org/exhibitions/taryn-simon'},{label:'Whitney · Chapter XIV',url:'https://whitney.org/collection/works/44570'}]
  },
  'walid-raad':{
    artistId:'walid-raad',
    projectCoverage:'纵向深化：The Atlas Group → My neck is thinner than a hair: Engines → Scratching on things I could disavow / Walkthrough；补足虚构档案、真实史料、表演叙事与阿拉伯艺术基础设施研究。',
    imageCoverage:'MoMA 官方馆藏与 2015–16 survey 页面保存大量作品图、展陈图和 artist audio。本站记录官方入口与作品规格，不复制受版权保护图像。',
    note:'Raad 并非简单“伪造历史”。他的关键操作是让真实档案、虚构人物、重新扫描的新闻图像、记忆和 lecture-performance 互相污染，从而迫使观众检查历史证据的权威是怎样被建立的。',
    projects:[
      {title:'The Atlas Group',cluster:'fictional archive / photography / video / notebooks / lecture-performance',period:'1989–2004',summary:'持续十五年的项目研究 Lebanon 当代历史与战争。MoMA 明确指出，Raad 制作 fictionalized photographs、videotapes、notebooks 与 lectures，但它们又与真实事件及 Lebanon 等地真实 audio/film/photo archives 的研究相连；档案还把文件归于真实或虚构人物。',actions:['具体机制：建立一个看似真实的研究机构/档案名义，为文件设计来源、作者、编号与叙事，使 institutional authority 本身成为作品材料。','材料并非纯虚构：新闻照片、街头摄影、真实历史研究与艺术家制造的文本/图像共同出现，因此观众不能用简单“真/假”二分完成判断。','展示方式：archive 不只放墙上，也通过 video screening、lecture 与 storytelling 被重新激活；艺术家本人作为讲述者不断改变文件的可信语境。'],sourceUrl:'https://www.moma.org/calendar/exhibitions/1493',images:[],relations:[rel('机构','MoMA','2015–16 first comprehensive American survey'),rel('项目','The Atlas Group','1989–2004 long-term archive')]},
      {title:'My neck is thinner than a hair: Engines',cluster:'newspaper archive / car-bomb aftermath / evidentiary photography',period:'1996–2001',summary:'作品由100张 inkjet prints 构成。Raad 从 Lebanon newspaper archives 收集内战期间汽车炸弹爆炸后发动机的新闻照片，扫描照片正反面，并附上爆炸日期、摄影者姓名（如可知）及背面注记的英文翻译。发动机原本被当作司法线索，却常因车辆为赃车而缺乏真正 juridical value。',actions:['档案动作：收集并重新扫描新闻机构已经赋予证据权威的照片，而不是重新拍摄爆炸现场。','信息层：保留照片背面注记并翻译，让新闻图像的流通、编辑和档案劳动进入作品表面。','政治机制：Raad 注意到政客反复在发动机旁被摄影；作品因此把“调查证据”翻转成 media photo opportunity，揭示新闻影像如何生产行动中的国家权威。'],sourceUrl:'https://www.moma.org/collection/works/91530',images:[],relations:[rel('机构','MoMA','collection; Fund for the Twenty-First Century')]},
      {title:'Scratching on things I could disavow / Walkthrough',cluster:'art infrastructure / Gulf museums / performance / speculative art history',period:'2007–ongoing',summary:'The Atlas Group 之后，Raad 把研究尺度从 Lebanon wars 推向 Arab world 新兴的 art fairs、biennials、museums 与 galleries，并把这些文化基础设施与地区 geopolitical、economic、military conflicts 并置。2015 MoMA survey 以 Walkthrough lecture-performance 强调 storytelling 在这一阶段的中心位置。',actions:['研究对象变化：不再主要问战争如何被摄影记录，而是追问战争、资本与文化投资怎样共同改变“Arab art history”能够被收藏、展示和叙述的条件。','形式变化：雕塑、装置、数字图像与 lecture-performance 互相嵌套；解释作品的故事本身成为作品，不再只是 wall text。','关系网络：MoMA survey 把 The Atlas Group 与 Scratching…并列为两条长期主线，使网站可直接建立“war archive → art infrastructure”的实践演变轴。'],sourceUrl:'https://www.moma.org/calendar/exhibitions/1493',images:[],relations:[rel('机构','MoMA','2015 survey and recurring Walkthrough performances'),rel('议题','Arab art infrastructure','museums / fairs / biennials / galleries')]}
    ],awards:[],exhibitions:['MoMA — Walid Raad, Oct 12 2015–Jan 31 2016','MoMA PS1 — Greater New York 2005'],sources:[{label:'MoMA · Walid Raad survey',url:'https://www.moma.org/calendar/exhibitions/1493'},{label:'MoMA · My neck is thinner than a hair: Engines',url:'https://www.moma.org/collection/works/91530'},{label:'MoMA · Atlas Group/Walid Raad',url:'https://www.moma.org/artists/27369-the-atlas-group-walid-raad'}]
  },
  'trevor-paglen':{
    artistId:'trevor-paglen',
    projectCoverage:'纵向深化：long-distance surveillance photography → Autonomy Cube → Behold These Glorious Times! → ImageNet Roulette；补足从“让秘密基础设施可见”到“研究机器视觉如何看人”的方法转折。',
    imageCoverage:'SFMOMA、KW、Paglen Studio 与 Barbican 均提供官方作品/installation views。本站记录稳定官方入口、规格与 credit，不复制版权状态未确认的图像。',
    note:'Paglen 的演变非常适合网站的方法谱系：早期用摄影技术逼近国家秘密基础设施的可见性极限；中期直接制造 Tor 基础设施；随后转向训练数据、computer vision 与分类政治——研究对象从“谁在看我们”推进到“机器究竟被训练成怎样看我们”。',
    projects:[
      {title:'Long-distance surveillance landscapes',cluster:'long-distance photography / military secrecy / satellites / drones',period:'2000s–2010s',summary:'Paglen 以 geographer 与 investigative researcher 的方法寻找远距离军事禁区、侦察卫星、无人机与通信基础设施，再用极端长距离摄影把本来位于公众视野之外的“black world”留下可见痕迹。SFMOMA 收藏包括 They Watch the Moon、Untitled (Reaper Drone) 与 KEYHOLE-IMPROVED CRYSTAL 等。',actions:['具体方法：先通过公开资料、地理研究和技术知识定位对象，再选择能从公共地点观测的视线与时间窗口。','摄影结果常因大气、距离和光学极限而失去细节；这种“看不清”不是失败，而是把国家保密制度与物理视觉极限同时记录进照片。','与普通调查摄影的差异：照片不是调查终点，而是证明一个庞大不可见系统确实与日常景观共存的微弱证据。'],sourceUrl:'https://www.sfmoma.org/artist/Trevor_Paglen/',images:[],relations:[rel('机构','SFMOMA','collection: satellites, drones, surveillance sites')]},
      {title:'Autonomy Cube',cluster:'functional sculpture / Tor / privacy infrastructure / institutional critique',period:'2014–',summary:'透明 Plexiglas cube 内装实际运行的 computer components / motherboards，并建立名为 Autonomy Cube 的开放 Wi‑Fi；用户流量通过 Tor network，装置本身也成为 Tor relay。SFMOMA 于2016年购藏；KW 说明其曾在第9届 Berlin Biennale 展出后于2017–18安装于机构入口。',actions:['作品必须“被使用”：观众连接 Wi‑Fi 后，网络流量实际进入 Tor；隐私不只是雕塑象征，而成为展馆提供的一项基础设施。','institutional critique：博物馆不再只展示关于 surveillance 的图像，而要承担运行匿名网络节点的技术与制度责任。','形式引用：KW 将透明 cube 与 Hans Haacke 的 Condensation Cube 联系，但内部系统从物理凝结过程换成真实的数据路由。'],sourceUrl:'https://www.sfmoma.org/artwork/2016.73.A-C/',images:[],relations:[rel('机构','SFMOMA','collection, acquired 2016'),rel('机构','KW Institute for Contemporary Art','2017–18 installation after 9th Berlin Biennale'),rel('双年展','9th Berlin Biennale','presentation')]},
      {title:'Behold These Glorious Times!',cluster:'AI training images / neural networks / machine vision / video installation',period:'2017',summary:'单频道影像把用于训练 AI 识别 objects、faces、gestures、relationships 与 emotions 的图像，与 deep neural network 对这些图像进行拆解时的内部视觉并置。Paglen Studio 记录作品约10分钟；声音由 Holly Herndon 创作，并部分使用 neural networks 与 speech-recognition training libraries。',actions:['材料不是“AI生成漂亮图像”，而是直接使用 machine-learning training libraries 与网络内部 feature-like visualizations，把机器学习的训练过程本身变成影像材料。','观看结构：人类先看到熟悉的脸和动作，随后图像分裂成机器处理的网格/部件，使 human-readable image 与 machine-readable representation 的差异可视化。','跨媒介：Holly Herndon 的声音同样调用 neural-network / auditory training logic，让 machine perception 同时进入视觉与听觉。'],sourceUrl:'https://paglen.studio/2020/04/09/behold-these-glorious-times/',images:[],relations:[rel('合作','Holly Herndon','sound composition using neural-network / training-library processes')]},
      {title:'ImageNet Roulette',cluster:'interactive AI / ImageNet / classification bias / public experiment',period:'2019',summary:'Paglen 从 ImageNet 的 people categories 训练分类模型，允许公众上传肖像并获得机器标签。Barbican 对谈记录项目走红后一度每天处理约120万张图像，并促使 ImageNet 团队宣布删除大量 people categories、展开更大的去偏工作。',actions:['具体动作：不是在文章里批评 dataset，而是把其 people categories 训练成公众可直接试用的 classifier，让分类体系的 racist、misogynistic 和荒谬输出即时反馈给被分类者。','方法转折：从拍摄不可见 surveillance infrastructure，转向拆解“看”本身的训练材料——权力从远处的秘密基地进入 dataset labels。','公共影响：项目成为 dataset politics 的大众实验；其价值不在模型准确率，而在暴露 category design 已经预装的社会判断。'],sourceUrl:'https://www.barbican.org.uk/s/trevorpaglen',images:[],relations:[rel('机构','Barbican Centre','artist discussion documenting ImageNet Roulette and dataset critique'),rel('数据集','ImageNet','people-category classification critique')]}
    ],awards:['Deutsche Börse Photography Foundation Prize 2016 — awarded for The Octopus exhibition'],exhibitions:['Frankfurter Kunstverein — The Octopus, 2015','9th Berlin Biennale — Autonomy Cube','KW Institute for Contemporary Art — Autonomy Cube, 2017–18'],sources:[{label:'SFMOMA · Trevor Paglen collection',url:'https://www.sfmoma.org/artist/Trevor_Paglen/'},{label:'SFMOMA · Autonomy Cube',url:'https://www.sfmoma.org/artwork/2016.73.A-C/'},{label:'KW · Autonomy Cube',url:'https://www.kw-berlin.de/en/projects/trevor-paglen-autonomy-cube-2015'},{label:'Paglen Studio · Behold These Glorious Times!',url:'https://paglen.studio/2020/04/09/behold-these-glorious-times/'},{label:'Barbican · Trevor Paglen / ImageNet Roulette',url:'https://www.barbican.org.uk/s/trevorpaglen'},{label:'Frankfurter Kunstverein · The Octopus',url:'https://www.fkv.de/en/exhibition/trevor-paglen-the-octopus/'}]
  }
};
