import type { ArtistArchive, ArchiveRelation } from './archiveData';

const rel=(kind:ArchiveRelation['kind'],label:string,detail?:string):ArchiveRelation=>({kind,label,detail});
const moma='https://www.moma.org/calendar/exhibitions/5099';
const bark='https://www.moma.org/magazine/articles/219';
const curfew='https://www.moma.org/audio/playlist/298/4603';
const whitecube='https://www.whitecube.com/artists/michael-armitage';
const chapel='https://www.whitecube.com/news/michael-armitage-at-south-london-gallery';
const norval='https://www.whitecube.com/news/michael-armitage-at-norval-foundation-cape-town';

export const archiveBatch157:Record<string,ArtistArchive>={
'venice-michael-armitage':{
 artistId:'venice-michael-armitage',
 projectCoverage:'6 个 material-support / election-rally / folklore-social-consensus / parallel-art-history / pandemic-policing / postcolonial-memory 节点深化 · 2010–2022',
 imageCoverage:'0 / 6',
 note:'把 Michael Armitage 从 Venice 2019 的单一 narrative-painting 条目扩成一条“材料改变绘画逻辑”的实践史。核心不是把 East Africa 当作题材，而是让 Ugandan lubugo bark cloth、Kenyan news/social media/personal memory、European avant-garde 与 East African modernism 在同一画面发生摩擦。与一般 history painting 不同，他让支撑物本身的孔洞、缝线、粗糙纤维和修补痕迹主动决定构图；与纯新闻绘画不同，他又持续把现场观察、媒体图像、梦境、民间叙事和旧绘画构图混合，使事件无法被还原成单一 reportage。',
 projects:[
 {title:'Lubugo as painting support / material protocol',cluster:'Ugandan bark cloth / holes / seams / scraping / repainting',period:'2010–ongoing',summary:'Armitage 2010 年在 Nairobi tourist market 接触 lubugo 后逐渐用它取代 canvas。材料由 fig-tree bark 经捶打制成，天然存在孔洞、粗糙凹痕和不规则边缘；艺术家把这些缺陷保留下来，并通过分层上色、scrape、revise、repaint，让 support 不只是承载图像，而实际参与构图。',actions:['以 lubugo bark cloth 替代标准 Western canvas，主动改变绘画的历史/文化支撑','保留 bark cloth 天然 holes、coarse indents 与不规则边缘，不把材料修整成中性平面','需要大画幅时缝接多块 cloth，并允许 seam 成为画面线条','以 thin oil layers 建立透明/半透明色层','反复 scrape、revise、repaint，使前一层图像留下残影','根据孔洞和缝线调整 figure / landscape，而不是让图像完全覆盖材料','把 Ugandan ceremonial material 与 European oil-painting language 放进同一对象'],sourceUrl:bark,images:[],relations:[rel('展览','Projects 110: Michael Armitage — MoMA','2019–20 · material process foregrounded'),rel('机构','Nairobi / Uganda material route','lubugo encountered in Nairobi; material originates in Uganda')]},
 {title:'The Fourth Estate / 2017 Kenyan election cycle',cluster:'opposition rally / body politic / press observation / carnival-to-violence',period:'2017–2020',summary:'围绕 2017 Kenyan General Elections，Armitage 与当地 press team 到 Uhuru Park opposition rally 观察现场；狂欢式服装、wigs、masks、slings 与随后 teargas、stone throwing、live rounds 的暴力进入同一绘画循环。这里 history painting 不再处理遥远英雄事件，而是处理当代群众政治如何被亲历、新闻和记忆同时重写。',actions:['跟随 local press team 进入 political rally，获得现场观察而非只依赖二手新闻','记录 crowd costume、gesture、mask、sling 等微观视觉细节','把亲历记忆与随后 news reports 并置','通过多人物 tableau 把 individual gesture 与 body politic 同时组织','让 celebratory/carnivalesque atmosphere 与 police violence 在同一画面共存','以 ink drawings 先测试人物和运动，再推进 large oil paintings'],sourceUrl:whitecube,images:[],relations:[rel('展览','Accomplice — Norval Foundation','2020 · first exhibition in Africa; eight paintings + preparatory ink drawings'),rel('展览','May You Live In Interesting Times — Venice Biennale','2019')]},
 {title:'The Chapel',cluster:'religion / folklore / mental health / social consensus',period:'2017–2018',summary:'South London Gallery 的首个 London public-gallery solo show 为 chapel-like main space 制作七幅大型绘画，研究 East Africa 语境中 religion、folklore 与 social consensus 的模糊边界，尤其牵涉 mental health。作品把 news、internet gossip、个人经验与 Western art-history compositions 混成心理和政治强度很高的场景。',actions:['针对 SLG chapel-like architecture 组织七幅 large-scale paintings','从 historical/current news、internet gossip 与 personal Kenyan experience 同时取材','把 religion / folklore / mental-health discourse 放进同一社会图景','借用 Western master compositions 但改变人物、地点和权力关系','用 vivid dream-like colour 先吸引观看，再让不稳定社会内容逐渐显现'],sourceUrl:chapel,images:[],relations:[rel('展览','The Chapel — South London Gallery','2017–18 · first solo exhibition in a London public gallery'),rel('策展','Margot Heller / South London Gallery','exhibition development and catalogue conversation')]},
 {title:'Projects 110: Michael Armitage',cluster:'parallel cultural histories / East African modernism / Western modernism',period:'2019–2020',summary:'MoMA 与 Studio Museum in Harlem 合作的 Projects 110 把八幅绘画组织为“parallel cultural histories”。除 European avant-garde 外，Armitage 明确连接 Meek Gichugu、Chelenge、Jak Katarikawe 等 East African modernists，使现代主义不再只从 Western canon 单向流向 Africa。',actions:['选择八幅作品建立跨文化 painting genealogy','把 European avant-garde 与 East African modernists 放在平行而非主从关系','通过 lubugo support 让材料本身继续抵抗 neutral museum painting surface','把 personal memory 与 media depictions of East Africa 叠合','追踪 African bodies / political reportage 如何进入 global-capital image circulation'],sourceUrl:moma,images:[],relations:[rel('展览','Projects 110 — Museum of Modern Art','2019–20'),rel('策展','Thelma Golden','Director and Chief Curator, Studio Museum in Harlem'),rel('策展','Legacy Russell','Associate Curator, Studio Museum in Harlem')]},
 {title:'Curfew (Likoni March 27 2020)',cluster:'pandemic / police violence / distorted perspective / stitched support',period:'2022',summary:'作品依据 2020-03-27 Kenya curfew 后 Likoni ferry crossing 的真实事件：大量通勤者因运输压力无法及时回家，警方随后强迫人群排队并殴打他们。Armitage 没有采用纪实透视，而让 ferry roof / floor 的色块越往远处越扩大，使画面像向观看者折叠；lubugo 缝线又被直接转成 whip 等构图元素。',actions:['从 Likoni ferry curfew / police violence 的具体事件建立大型群像','故意反转常规 perspective，让远处结构扩大而非缩小','用相互振动的高饱和色维持持续视觉 agitation','把多块 lubugo 缝接成大画幅','直接利用 stitching 形成 whip / contour 等画面线条','把 traumatic-time 的主观减速感转换为空间畸变，而不是写实再现'],sourceUrl:curfew,images:[],relations:[rel('收藏','Museum of Modern Art, New York','Curfew (Likoni March 27 2020) · Gift of Ronnie Heyman in honor of Ann Temkin')]},
 {title:'Head of Koitalel / The Perfect Nine / Dandora sequence',cluster:'colonial memory / oral-literary source / urban waste / magic realism',period:'2021–2022',summary:'2021–22 的作品把实践从即时新闻继续推向更长的 East African historical/literary memory：Head of Koitalel 处理反英 Nandi leader Koitalel Arap Samoei 被诱杀斩首的历史；The Perfect Nine 转译 Ngũgĩ wa Thiong’o 的 Gĩkũyũ epic；Dandora 则把 Nairobi dump、foragers、animals 与 Ousmane Sembène 的电影记忆压入近似 classical history-painting 的尺度。',actions:['从 colonial history、East African literature 与 African cinema 扩展 source archive','让历史人物不以纪念碑式 heroic portrait 出现，而保持受伤/不稳定身体','利用 lubugo stitching 与裂痕回应 beheading / bodily division','把 Ngũgĩ narrative 转为 painterly scene，而非文学插图','将 Dandora waste landscape 放大到 classical history-painting scale','以 superimposition、multiple viewpoints、translucent wash 混合真实与 imagined time'],sourceUrl:whitecube,images:[],relations:[rel('收藏','Museum of Modern Art, New York','Head of Koitalel · 2021'),rel('展览','White Cube Bermondsey','2022'),rel('机构','Nairobi Contemporary Art Institute','Armitage founded NCAI to support growth and preservation of contemporary art in East Africa')]}
 ],
 awards:['Royal Academician (Painting) — Royal Academy of Arts, elected 2022'],
 exhibitions:['The Chapel — South London Gallery, 2017–18','May You Live In Interesting Times — Venice Biennale, 2019','Projects 110 — MoMA / Studio Museum in Harlem, 2019–20','Accomplice — Norval Foundation, 2020','Royal Academy, London, 2021','Kunsthalle Basel, 2022','Kunsthaus Bregenz, 2023'],
 sources:[{label:'MoMA · Projects 110: Michael Armitage',url:moma},{label:'MoMA Magazine · Bark Cloth',url:bark},{label:'MoMA · Curfew artist audio',url:curfew},{label:'White Cube · Michael Armitage',url:whitecube},{label:'South London Gallery / White Cube · The Chapel',url:chapel},{label:'Norval Foundation / White Cube · Accomplice',url:norval}]
}
};
