import type { ArtistArchive, ArchiveRelation } from './archiveData';
const rel=(kind:ArchiveRelation['kind'],label:string,detail?:string):ArchiveRelation=>({kind,label,detail});

export const archiveBatch211:Record<string,ArtistArchive>={
  'taryn-simon':{
    artistId:'taryn-simon',
    projectCoverage:'作品级纵向深化：The Innocents → An American Index → A Living Man Declared Dead → Paperwork and the Will of Capital；本批重点把 Paperwork 从系列总述拆成具体外交事件、摄影/植物标本/混凝土压花器的制作链，以及 Venice—Gagosian—UN 不同版本。',
    imageCoverage:'Whitney 与 Gagosian 官方页面均提供作品图/installation views。Gagosian 明确标注 artwork © Taryn Simon；纽约展 installation photography 为 Rob McKeever，London 2019 为 Lucy Dawkins，Athens 2018 为 Celia Psychi。本站记录官方图像入口、摄影 credit 与版权状态；未取得再发布许可的原图不复制，作品 images 留空而非用无关替代图。',
    note:'Simon 的作品不是“研究主题+漂亮照片”。她反复把调查、制度准入、分类、摄影、文字和实体展示装置锁在一起。Paperwork 尤其清楚：历史签约照里的背景花束被重新识别、采购、搭建、摄影、拆解、压制并封存；政治舞台的装饰物因此变成一套可老化的物质档案。',
    projects:[
      {title:'The Innocents',cluster:'photography / wrongful conviction / eyewitness identification / DNA exoneration',period:'2002',summary:'系列聚焦因暴力犯罪被定罪、后来通过 DNA 证据洗清罪名的人。Simon 让被平反者重新进入与案件、逮捕、误认或获释有关的地点拍摄，并把肖像与案件文字并置，使摄影既作为司法识别工具、又作为可能制造误认的技术受到审查。',actions:['寻找已发生司法错误且后来被平反的个案，而非聘请模特重演抽象主题。','让人物回到与其案件历史有关系的地点，以现实空间重新触碰司法叙事。','最终观看依赖肖像与文字互证：观众不能只凭面孔判断，而必须在照片、证词、DNA 与制度程序之间来回校正。'],sourceUrl:'https://whitney.org/artists/9743',images:[],relations:[rel('机构','Whitney Museum of American Art','artist/collection research'),rel('媒介','photography + case text','image and legal narrative read together')]},
      {title:'An American Index of the Hidden and Unfamiliar',cluster:'large-format photography / institutional access / taxonomy',period:'2007',summary:'Simon 寻找美国境内普通公众难以进入或不可见的科学、政府、医学、安全、宗教与自然对象，通过申请、谈判和制度许可进入现场，再以大画幅摄影和说明文字把这些彼此无关的对象编入统一 index。',actions:['实际动作包括确定隐藏对象、寻找负责机构、争取准入、进入受限空间并进行高解析摄影。','作品把“access”变成方法：核设施、医学设施或受保护对象之所以被放在一起，不因视觉相似，而因它们都处在被制度控制的可见性边界。','展陈中清晰照片与说明文字并列；图像越清楚，观众越能意识到可见并不等于真正拥有制度知识。'],sourceUrl:'https://whitney.org/exhibitions/taryn-simon',images:[],relations:[rel('机构','Whitney Museum of American Art','2007 solo exhibition'),rel('技术','large-format photography','high-detail institutional/site photography')]},
      {title:'A Living Man Declared Dead and Other Chapters I–XVIII',cluster:'bloodlines / portrait grids / text / contextual images',period:'2008–2011',summary:'以全球不同 bloodline 为调查单位，逐人摄影并记录拒绝、失踪或无法参与者留下的空缺，再把肖像网格、文字和 contextual images 组织成章节。Whitney 的 Chapter XIV 为五部分 inkjet prints with dry-transfer type，整体超过六米宽。',actions:['沿血缘关系寻找并逐个拍摄成员；缺席者不由替代肖像补齐，而作为空位留在分类系统中。','把肖像、文字和补充图像压进近似科学/行政档案的展示界面，使观众横向移动阅读。','作品把 genealogy 与国家、宗教、领土、暴力及偶然事件并置，分类形式本身成为被研究对象。'],sourceUrl:'https://whitney.org/collection/works/44570',images:[],relations:[rel('机构','Whitney Museum of American Art','Chapter XIV collection'),rel('材料','inkjet prints + dry-transfer type','five-part large information structure')]},
      {title:'Paperwork and the Will of Capital — reconstructed diplomatic bouquets',cluster:'archival research / botanical reconstruction / archival inkjet / herbarium paper / mahogany-style framing',period:'2015',summary:'Simon 从外交协议签署的历史新闻照片出发，注意到权力人物之间反复出现的花束。她研究36场与治理和经济有关的签约事件，辨认照片中的植物，从荷兰 Aalsmeer 花卉市场取得对应花材，在工作室重建花束并重新摄影。大型成品把重建静物与解释具体协议的文字结合。',actions:['先搜集协议签署的 archival images，并把通常被视为背景装饰的花束当成主要证据对象。','与植物学知识结合辨认品种；再采购花材并依据历史照片重建 arrangement。由于原照片常无法给出完整空间/色彩信息，重建不是“复制现场”，而是以档案证据制造新的摄影对象。','重建完成后以大尺幅静物摄影呈现；Gagosian 记录典型单件为 archival inkjet print and text on archival herbarium paper in wood frame，215.9 × 186.1 × 7 cm，edition 3 + 2 AP。','定制木框以 mahogany/boardroom furniture 的视觉语法强化政府和企业权力的舞台感；花束因此从背景道具变成画面中心。'],sourceUrl:'https://gagosian.com/exhibitions/2016/taryn-simon-paperwork-and-the-will-of-capital-new-york/',images:[],relations:[rel('材料','archival inkjet + archival herbarium paper + wood frame','documented photograph format'),rel('供应链','Aalsmeer flower market','flowers sourced for reconstructions'),rel('版权','© Taryn Simon','official Gagosian work credit')]},
      {title:'Paperwork — Bratislava Declaration, Bratislava, August 3, 1968',cluster:'specific photograph + botanical sculpture / preserved specimens',period:'2015',summary:'系列中的具体事件版本。摄影成品为 archival inkjet print and text on archival herbarium paper in wood frame，215.9 × 186.1 × 7 cm。对应雕塑把该签约花束中的植物标本压制、干燥并封存进 stylized concrete flower press；Gagosian 记录实例含 Dianthus caryophyllus（康乃馨，Colombia）。',actions:['花束在被重建并摄影后并未丢弃：选定植物被 dried、pressed，并缝到 archival herbarium paper 上。','雕塑规格记录为 pigmented concrete press、dried plant specimens、archival inkjet prints、text on archival herbarium paper、steel brace，109.2 × 72.4 × 52.1 cm。','2016 press release 说明：36组 arrangement 的选定标本形成完整36件 botanical collages；每一个12件 concrete presses 内都放入完整一套36 collages，并与同数量照片和 narrative texts 一起封存。','因此摄影与雕塑拥有不同时间性：照片冻结花束重建完成时的鲜艳状态；压制标本则会随时间发生物理变化。'],sourceUrl:'https://gagosian.com/exhibitions/2016/taryn-simon-paperwork-and-the-will-of-capital-new-york/',images:[],relations:[rel('材料','pigmented concrete / dried specimens / steel brace','109.2 × 72.4 × 52.1 cm documented sculpture'),rel('植物','Dianthus caryophyllus','documented specimen: Colombia'),rel('结构','36 botanical collages per press','sealed archive repeated across 12 unique sculptures')]},
      {title:'Paperwork — Agreement Establishing the International Islamic Trade Finance Corporation',cluster:'specific diplomatic reconstruction / photograph + flower press',period:'2015',summary:'对应2006年5月30日 Kuwait City Al-Bayan Palace 的协议签署。摄影版本同样为215.9 × 186.1 × 7 cm archival inkjet print/text/herbarium paper/wood frame；对应混凝土 press 明确记录 Rosa × hybrida（Ecuador）、Gerbera × hybrida（Netherlands）、Hydrangea macrophylla（Netherlands）与 Dendrobium hybrid（Thailand）。',actions:['同一外交花束被拆成两种档案：一张高度控制的彩色重建照片，以及植物干燥后进入混凝土 press 的实体残余。','植物来源国被保留下来，使一个国际金融协议旁的“装饰”自身也暴露全球商品与物流网络。','观众在大照片前先看到近乎广告/官方形象般的完美花束，再面对压平、脱水、会继续老化的 specimens；权力表演与物质衰败被放进同一作品系统。'],sourceUrl:'https://gagosian.com/exhibitions/2016/taryn-simon-paperwork-and-the-will-of-capital-new-york/',images:[],relations:[rel('植物','rose / gerbera / hydrangea / dendrobium','documented species/origins in official work record'),rel('材料','archival inkjet + concrete press + herbarium specimens','paired photographic/sculptural archive')]},
      {title:'Paperwork — exhibition versions: Venice 2015 → New York 2016 → UN Treaty Event 2016',cluster:'version history / spatial adaptation / institutional feedback loop',period:'2015–2016',summary:'同一项目在不同制度空间发生关键变化：12件雕塑先于第56届 Venice Biennale 2015 preview；2016 Gagosian New York 首次把雕塑与36张大型 annotated photographs 作为完整 body of work 一起展出；同年联合国 Treaty Event 又把三张照片放回真实 treaty-signing area。',actions:['Venice 版本首先让 concrete flower presses 作为雕塑出现；New York 版本把12件 unique sculptures 与36张 editioned photographs 放在同一展览体系中，观众可比较鲜花图像和压制标本的时间差。','UN Headquarters 2016 Treaty Event 展出 Maastricht Treaty、Convention on Cluster Munitions 与 TRIPS 三张作品；它们进入真正进行 treaty signing 的区域，与外交礼物共同出现。','在 UN 版本中 Simon 获准以 press photographer 身份记录现场，角色反转为当年制造她所研究 archival signing images 的新闻摄影者。作品因此形成“历史新闻照片→艺术家重建→艺术照片→返回签约制度→再次新闻摄影”的反馈回路。','官方 installation image credit：Gagosian New York 2016 photo Rob McKeever；UN 2016 installation photo Taryn Simon。版权均标 Artwork © Taryn Simon，本站仅记录来源/credit，不复制未授权图像。'],sourceUrl:'https://gagosian.com/quarterly/2016/10/05/obscuring-index/',images:[],relations:[rel('展览','56th Venice Biennale','sculptures previewed 2015'),rel('展览','Gagosian New York','complete sculptures + photographs, 2016'),rel('机构','United Nations Headquarters','2016 Treaty Event, treaty-signing area'),rel('摄影','Rob McKeever / Taryn Simon','documented installation credits')]}
    ],
    awards:[],
    exhibitions:['Whitney Museum — An American Index of the Hidden and Unfamiliar, 2007','56th Venice Biennale — Paperwork sculptures preview, 2015','Gagosian New York — Paperwork and the Will of Capital, Feb 18–Mar 26 2016','United Nations Headquarters — 2016 Treaty Event, Sep 19–23 2016','Gagosian Athens — Paperwork and the Will of Capital, 2018','Gagosian London — Paperwork and the Will of Capital, 2019'],
    sources:[{label:'Whitney · Taryn Simon artist page',url:'https://whitney.org/artists/9743'},{label:'Whitney · An American Index',url:'https://whitney.org/exhibitions/taryn-simon'},{label:'Whitney · A Living Man Declared Dead, Chapter XIV',url:'https://whitney.org/collection/works/44570'},{label:'Gagosian · Paperwork and the Will of Capital, New York 2016',url:'https://gagosian.com/exhibitions/2016/taryn-simon-paperwork-and-the-will-of-capital-new-york/'},{label:'Gagosian · Obscuring the Index / institutional versions',url:'https://gagosian.com/quarterly/2016/10/05/obscuring-index/'},{label:'Gagosian · Paperwork, Athens 2018',url:'https://gagosian.com/exhibitions/2018/taryn-simon-paperwork-and-the-will-of-capital/'},{label:'Gagosian · Paperwork, London 2019',url:'https://gagosian.com/exhibitions/2019/taryn-simon-paperwork-and-the-will-of-capital/'}]
  }
};
