import type { ArtistArchive, ArchiveRelation } from './archiveData';

const rel = (kind: ArchiveRelation['kind'], label: string, detail?: string): ArchiveRelation => ({ kind, label, detail });

export const archiveBatch155: Record<string, ArtistArchive> = {
  'venice-vera-molnar': {
    artistId: 'venice-vera-molnar',
    projectCoverage: '6 个 rule-system / computer drawing / controlled disorder / line-to-space 节点深化 · 1950s–2024',
    imageCoverage: '0 / 6',
    note: '把 Molnar 从“早期计算机艺术家”进一步还原成规则艺术的方法史：她在真正接触计算机以前已经用 machine imaginaire 手工执行组合规则；1968 后电脑成为高速试验参数的工具，而不是替代作者判断的自动作者。她最稳定的研究对象始终是简单几何、重复、微小偏差、order/disorder 与 human intuition 的关系。与 Harold Cohen 的 AARON 相比，她并不试图把完整的绘画知识编码成自主生成者，而更像把机器当作制造大量可比较变体的实验装置。',
    projects: [
      { title:'Machine imaginaire / combinatory protocol', cluster:'pre-computer algorithm / exhaustive permutation / rule-based abstraction', period:'1959–1968', summary:'在获得真实计算机之前，Molnar 已先写规则、设定有限参数，再像机器一样逐步执行组合。重要性在于 generative logic 先于 hardware：电脑后来只是把既有研究方法加速。', actions:['选择 square / line / grid 等极简形式','预先定义位置、方向、数量等变量','以手工方式逐步执行 permutation','保留系列而非只挑单幅“构图”','通过相邻变体观察极小参数变化如何改变视觉判断'], sourceUrl:'https://mnbarts.hu/en/muveszek/molnar-vera/', images:[], relations:[] },
      { title:'Computer as experimental assistant', cluster:'mainframe / generative variation / artist selection', period:'1968–1970s', summary:'1968 后开始使用真实计算机生成图形。机器负责快速执行与变异，艺术家仍决定规则、扰动幅度、保留与舍弃，因此 computer 是研究工具而非 autonomous author。', actions:['把此前 imaginary-machine rules 转译到真实计算环境','让程序快速产生大量 variants','主动加入 random / pseudo-random deviation','比较输出并以视觉判断筛选','把 code、plotter output 与后续手工判断保持在同一 workflow'], sourceUrl:'https://mnbarts.hu/en/muveszek/molnar-vera/', images:[], relations:[rel('展览','Thinking Machines — MoMA','2017–2018 · computer-age historical context')] },
      { title:'Déambulation entre ordre et chaos', cluster:'computer-assisted drawing / order-disorder continuum / superposition', period:'1975', summary:'Centre Pompidou 收藏的一组二十幅 computer-assisted ink drawings。系列把规则与扰动处理成连续谱，而不是“秩序/混乱”二选一；每张输出都像同一系统在不同参数位置的实验截面。', actions:['建立可重复的 line / geometric rule','在系列中逐步改变 disorder 参数','以 computer-assisted plotting 形成二十幅关联 drawings','保留 superposition 与局部偏移造成的密度变化','让 viewer 横向比较系统状态而非只阅读单张图像'], sourceUrl:'https://www.centrepompidou.fr/fr/ressources/oeuvre/cdLnpz', images:[], relations:[rel('收藏','Centre Pompidou / Musée national d’art moderne','AM 2011-179 · ensemble of 20 drawings')] },
      { title:'1% Disorder', cluster:'minimal perturbation / square-grid system / controlled randomness', period:'1976', summary:'以极小比例的 disorder 干扰严格几何秩序，说明 Molnar 的“随机”不是追求 chaos，而是用最低剂量的偏差测试视觉何时开始感到结构发生变化。', actions:['先建立高度规则的 square/grid field','只允许极少量参数偏移','把 random operation 控制在有限阈值','通过 series 比较秩序感何时松动','将 intuition 转译为可反复测试的 perturbation'], sourceUrl:'https://mnbarts.hu/en/muveszek/molnar-vera/', images:[], relations:[] },
      { title:'M comme Malevitch / Molndrian and art-history perturbations', cluster:'art-history citation / letter-form / geometric mutation', period:'1960s–1970s', summary:'MoMA 馆藏的 2 Letter Ms 与 Molndrian 显示她并非只研究无来源几何：Malevich、Mondrian 等现代主义语言也会被压缩成字母、方形与结构规则，再接受 permutation / distortion。', actions:['提取 modernist composition 的基本 geometric grammar','把 M / square / orthogonal grid 作为可编码 signs','通过 repetition 与 displacement 改变熟悉结构','让 homage 与 algorithmic misreading 同时发生'], sourceUrl:'https://www.moma.org/artists/37083-vera-molnar', images:[], relations:[rel('收藏','Museum of Modern Art, New York','Untitled 1952 · 2 Letter Ms 1961 · Molndrian 1974')] },
      { title:'OTTWW / line translated into architecture', cluster:'in-situ line / thread-and-nail drawing / variable architecture', period:'late practice', summary:'Centre Pompidou 收藏的 OTTWW 把黑线从纸面和 plotter 输出继续推到墙体：黑线由黑色线绳和钉子在一个或多个白墙上连续展开，尺寸随场地变化。规则因此从 image generator 变成 architectural instruction。', actions:['把 continuous line 作为基本 rule','以 black thread / black nails 取代 ink/plotter mark','依据具体墙面重新实现','允许 dimensions variable','让算法式 drawing 与 site-specific installation 汇合'], sourceUrl:'https://www.centrepompidou.fr/en/ressources/oeuvre/cqpGk6d', images:[], relations:[rel('收藏','Centre Pompidou','artist gift · 2011'),rel('展览','Vera Molnár: Speak to the Eye — Centre Pompidou','2024 retrospective context')] }
    ],
    awards: [],
    exhibitions:['Thinking Machines — MoMA 2017–2018','The Milk of Dreams — Venice Biennale 2022','Vera Molnár: Speak to the Eye — Centre Pompidou 2024'],
    sources:[{label:'Centre Pompidou · Déambulation entre ordre et chaos',url:'https://www.centrepompidou.fr/fr/ressources/oeuvre/cdLnpz'},{label:'Centre Pompidou · OTTWW',url:'https://www.centrepompidou.fr/en/ressources/oeuvre/cqpGk6d'},{label:'MoMA · Vera Molnar',url:'https://www.moma.org/artists/37083-vera-molnar'},{label:'MNB Arts · Vera Molnar archive / 1% Disorder',url:'https://mnbarts.hu/en/muveszek/molnar-vera/'}]
  },

  'venice-lillian-schwartz': {
    artistId:'venice-lillian-schwartz',
    projectCoverage:'5 个 responsive sculpture / Bell Labs animation / hybrid analogue-digital / computational art-history 节点深化 · 1968–1980s',
    imageCoverage:'0 / 5',
    note:'进一步把 Schwartz 与同时代 generative artists 区分开：她并不只让程序输出几何图，而持续把 slide、ripple tank、pressure mat、hand tinting、photography、computer animation、optical printing 与 art-historical image analysis 接成混合流程。她的重要性因此既在“早”，也在于 analogue / electronic / computational media 之间没有硬边界。Whitney 将其列为 computer-mediated art pioneer，并在 Programmed 2018–19 中把她放入 rules/codes/choreographies 的历史链。',
    projects:[
      {title:'Proxima Centauri',cluster:'E.A.T. / responsive environment / projector-ripple-tank-electronics',period:'1968',summary:'MoMA 1968 文献记录得非常具体：自动 projector 将 81 张 abstract slides 经 ripple tank 投向磨砂 globe；水槽每分钟被扰动五秒。viewer 接近时地垫 switches 触发 motor，使 globe 下沉并亮起 red glow，离开后复位。作品因此不是单纯 kinetic sculpture，而是一套 viewer-position → switch → motor → optics → image-state 的反馈链。',actions:['准备 81 张 abstract slides 作为 image bank','让 slide projector 经 ripple tank 投射到 frosted globe','以定时机械扰动改变水面折射','把 floor pressure mats 作为 viewer sensor','用 motor 改变 globe 高度并同步 red light state','viewer 离开后让系统自动恢复初始位置','与 Bell Labs engineer Per Biorn 协作完成电子/机械结构'],sourceUrl:'https://assets.moma.org/documents/moma_press-release_326596.pdf',images:[],relations:[rel('展览','The Machine as Seen at the End of the Mechanical Age — MoMA','1968')]},
      {title:'Pixillation / Bell Labs film workflow',cluster:'computer animation / analogue painting / electronic image synthesis',period:'1970',summary:'Schwartz 在 Bell Labs 把 computer-generated imagery 与传统绘画、摄影及电影后期结合。这里的 computer 不承担全部画面，而是进入一个跨媒介 pipeline；这种混合生产方式比“纯数字输出”更接近她长期实践。',actions:['与 Bell Labs researchers / programmers 协作','生成 computer animation / geometric image sequences','把电子生成图像与 analogue visual material 并置','通过 film editing 控制节奏和连续性','把技术实验最终压回可观看的 moving-image work'],sourceUrl:'https://whitney.org/artists/2373',images:[],relations:[rel('展览','Programmed: Rules, Codes, and Choreographies in Art — Whitney','2018–2019 · historical computational-art context')]},
      {title:'Googolplex / Enigma / Mis-Takes',cluster:'algorithmic geometry / hand-tinted photography / optical hybrid',period:'1970s',summary:'算法几何与 hand-tinted photographic layer 被叠合后再进入电影流程，说明她一直主动保留手工痕迹。计算机负责产生一种图像材料，而不是规定最终作品必须具有“computer look”。',actions:['生成 algorithmic geometric drawings','准备并 hand-tint photographic imagery','superimpose digital/algorithmic 与 photographic layers','通过 frame sequence 建立持续 mutation','用 soundtrack 强化视觉运动的 temporal structure'],sourceUrl:'https://www.labiennale.org/en/art/2022/milk-dreams/lillian-schwartz',images:[],relations:[rel('展览','The Milk of Dreams — Venice Biennale','2022')]},
      {title:'Bell Labs as collaborative production ecology',cluster:'artist-engineer network / computational infrastructure / shared laboratory',period:'late 1960s–1970s',summary:'Schwartz 的作品不能只以单一作者理解。Bell Labs 提供 mainframe、图像输出设备、程序知识和 engineer network；同一环境也孕育 Stan VanDerBeek / Ken Knowlton 等早期 computational moving-image experiments。她的实践因此是 artist-engineer institution network 的产物，同时又以个人的绘画和色彩判断不断改写实验室输出。',actions:['把 laboratory hardware 当作 studio infrastructure','与 programmers / engineers 交换技术知识','将机器输出继续进行手工、摄影或电影处理','在 engineering constraint 内寻找 aesthetic variation','把 collaboration 本身纳入作品生产机制'],sourceUrl:'https://whitney.org/artists/2373',images:[],relations:[rel('展览','Thinking Machines — MoMA','2017–2018 · Bell Labs computational-art genealogy')]},
      {title:'Computer-assisted art-historical image analysis',cluster:'image comparison / computational perception / art-history research',period:'1980s',summary:'后期 Schwartz 还把 computation 从“生成新图像”转向“分析既有图像”：通过数字化、比例与结构比较研究 canonical artworks。这个转向很关键，因为计算机从画笔/动画工具变成一种 visual hypothesis machine，连接艺术创作与 art-historical argument。',actions:['digitize / align canonical artwork images','比较比例、轮廓与构图结构','使用 image manipulation 测试视觉相似性假设','把分析结果重新组织为可传播的 visual argument','让 computational imaging 同时服务 creation 与 art-history research'],sourceUrl:'https://whitney.org/artists/2373',images:[],relations:[]}
    ],
    awards:[],
    exhibitions:['The Machine as Seen at the End of the Mechanical Age — MoMA 1968','Programmed: Rules, Codes, and Choreographies in Art — Whitney 2018–2019','The Milk of Dreams — Venice Biennale 2022'],
    sources:[{label:'MoMA · Proxima Centauri 1968 documentation',url:'https://assets.moma.org/documents/moma_press-release_326596.pdf'},{label:'Whitney · Lillian Schwartz',url:'https://whitney.org/artists/2373'},{label:'Whitney · Programmed',url:'https://whitney.org/exhibitions/programmed'},{label:'La Biennale · Lillian Schwartz 2022',url:'https://www.labiennale.org/en/art/2022/milk-dreams/lillian-schwartz'}]
  }
};
