import type { ArtistArchive, ArchiveImage, ArchiveRelation } from './archiveData';

const img = (url: string, title: string, credit: string, sourceUrl: string, sourceLabel: string): ArchiveImage => ({ url, title, credit, sourceUrl, sourceLabel });
const rel = (kind: ArchiveRelation['kind'], label: string, detail?: string): ArchiveRelation => ({ kind, label, detail });

export const circuitArtistArchives: Record<string, ArtistArchive> = {
  'lubaina-himid': {
    artistId: 'lubaina-himid', projectCoverage: '4 个关键作品群已完成第一轮 · 持续补全', imageCoverage: '',
    note: '先建立 Turner Prize / Tate / Venice 路径中最关键的作品群。后续继续按艺术家官网与博物馆档案补齐全部系列和单件作品；当前不把“关键项目索引”冒充完整 oeuvre。',
    projects: [
      { title: 'A Fashionable Marriage', cluster: 'Black Arts / institutional satire', period: '1986–87', summary: '真人尺寸 cut-out 与 Hogarth 式剧场构图结合，对艺术机构、政治和种族权力进行讽刺。', actions: ['绘制真人尺寸人物', '把绘画切出墙面', '空间化讽刺叙事'], sourceUrl: 'https://lubainahimid.com/', images: [], relations: [rel('展览', 'Pentonville Gallery', '1987')] },
      { title: 'Naming the Money', cluster: 'slavery / naming / installation', period: '2004', summary: '100 个真人尺寸 painted cut-outs，每个人都有姓名、职业、故事和声音，反向处理欧洲宫廷绘画中被匿名化的黑人仆役。', actions: ['制作100个真人尺寸cut-out', '为人物命名与写传记', '制作约80分钟声音层', '让观众在人物之间行走'], sourceUrl: 'https://lubainahimid.com/portfolio/naming-the-money/', images: [img('https://ychef.files.bbci.co.uk/976x549/p0b51xf3.jpg', 'Naming the Money — installation', '© Lubaina Himid', 'https://lubainahimid.com/portfolio/naming-the-money/', 'Artist website / BBC')], relations: [rel('展览', 'Hatton Gallery, Newcastle', '2004'), rel('收藏', 'International Slavery Museum, Liverpool')] },
      { title: 'Le Rodeur', cluster: 'painting / colonial history', period: '2016–18', summary: '以1819年法国奴隶船 Le Rodeur 的历史为入口，用重复人物关系讨论观看、恐惧和殖民暴力。', actions: ['历史研究', '系列绘画', '重复构图变体'], sourceUrl: 'https://lubainahimid.com/portfolio/le-rodeur/', images: [img('https://www.uni-potsdam.de/fileadmin/_processed_/e/b/csm_2022-05-18-online-lecture-trauma-transgenerational_da5edbabd1.jpg', 'Le Rodeur: The Exchange', '© Lubaina Himid', 'https://lubainahimid.com/portfolio/le-rodeur/', 'Artist website')], relations: [rel('奖项', 'Turner Prize', 'winner 2017')] },
      { title: 'British Pavilion 2026', cluster: 'late-career institutional context', period: '2026', summary: '进入英国馆这一国家代表机制，成为研究她从 Black Arts Movement 到国际大型机构位置变化的重要节点。', actions: ['新作发展', '国家馆空间组织'], sourceUrl: 'https://lubainahimid.com/', images: [], relations: [rel('展览', 'British Pavilion, Venice Biennale', '2026')] }
    ], awards: ['Turner Prize 2017 — winner', 'Royal Academician', 'British Pavilion Venice 2026'], exhibitions: ['Invisible Strategies — Modern Art Oxford 2017', 'Tate / major collection and exhibition context', 'British Pavilion — Venice Biennale 2026'], sources: [{ label: 'Official artist archive', url: 'https://lubainahimid.com/' }, { label: 'Naming the Money', url: 'https://lubainahimid.com/portfolio/naming-the-money/' }]
  },
  'steve-mcqueen': {
    artistId: 'steve-mcqueen', projectCoverage: '5 个关键项目已索引 · 1997–2025', imageCoverage: '', note: 'McQueen 同时有 gallery film、feature film、公共摄影项目和长期电影作品；本档案优先收录塑造其当代艺术位置的作品，商业电影作品将另分支处理。',
    projects: [
      { title: 'Deadpan', cluster: 'body / cinema history', period: '1997', summary: '重演 Buster Keaton 房屋正面倒塌镜头，以多个视角反复拆解危险、身体与电影观看。', actions: ['重演电影动作', '多机位 / 多视角', '16mm循环'], sourceUrl: 'https://www.moma.org/artists/8048-steve-mcqueen', images: [img('https://www.moma.org/wp/inside_out/wp-content/uploads/2015/03/Image_5_McQueen_.jpg', 'Deadpan', '© Steve McQueen', 'https://www.moma.org/artists/8048-steve-mcqueen', 'MoMA')], relations: [rel('收藏', 'MoMA', 'collection'), rel('奖项', 'Turner Prize', 'winner 1999')] },
      { title: 'Caribs’ Leap / Western Deep', cluster: 'colonial history / labour', period: '2002', summary: '格林纳达殖民历史与南非深矿劳动被并列为身体、重力和制度暴力的两种空间。', actions: ['location filming', '历史研究', '双作品并置'], sourceUrl: 'https://www.tate.org.uk/art/artists/steve-mcqueen-2678', images: [], relations: [rel('展览', 'documenta 11 context', '2002')] },
      { title: 'Giardini', cluster: 'Venice / duration', period: '2009', summary: '英国馆时期围绕 Venice Giardini 闭馆后的空旷时间工作。', actions: ['夜间 / 非开放时段拍摄', '双屏影像', '持续时间'], sourceUrl: 'https://venicebiennale.britishcouncil.org/history/2000s/2009-steve-mcqueen', images: [], relations: [rel('展览', 'British Pavilion, Venice Biennale', '2009')] },
      { title: 'Year 3', cluster: 'collective portrait / London', period: '2019', summary: '3,000多张伦敦小学班级照构成一代儿童的城市集体肖像，同时进入Tate Britain和公共广告牌。', actions: ['全市学校协作', '班级集体照', '墙面网格安装', '公共空间传播'], sourceUrl: 'https://www.tate.org.uk/whats-on/tate-britain/steve-mcqueen-year-3', images: [img('https://cdn.sanity.io/images/cxgd3urn/production/d7be4d268ba94583e9fdee786e4133330ff67599-931x620.jpg?auto=format&fit=crop&h=1279&q=85&w=1920', 'Year 3 — Tate Britain', '© Steve McQueen', 'https://www.tate.org.uk/whats-on/tate-britain/steve-mcqueen-year-3', 'Tate')], relations: [rel('展览', 'Tate Britain', '2019–2020'), rel('策展', 'Artangel collaboration')] },
      { title: 'Grenfell', cluster: 'memory / evidence', period: '2019–23', summary: '围绕 Grenfell Tower 灾难的长时间影像，处理纪念、证据、距离和观看伦理。', actions: ['长时段航拍', '地面移动镜头', '延迟公开'], sourceUrl: 'https://www.serpentinegalleries.org/whats-on/steve-mcqueen-grenfell/', images: [], relations: [rel('展览', 'Serpentine', '2023')] }
    ], awards: ['Turner Prize 1999 — winner', 'Academy Award / film career', 'Knighthood'], exhibitions: ['Projects 62 — MoMA 1997', 'British Pavilion — Venice 2009', 'Year 3 — Tate Britain 2019', 'Tate Modern survey 2020'], sources: [{ label: 'MoMA artist archive', url: 'https://www.moma.org/artists/8048-steve-mcqueen' }, { label: 'Tate artist archive', url: 'https://www.tate.org.uk/art/artists/steve-mcqueen-2678' }]
  },
  'mark-leckey': {
    artistId: 'mark-leckey', projectCoverage: '4 个关键项目已索引 · 1999–2019', imageCoverage: '', note: '第一轮集中在决定 Leckey 方法的四个节点：club archive、物件/声音、网络自传、Tate沉浸装置。后续继续补 individual works 与声音项目。',
    projects: [
      { title: 'Fiorucci Made Me Hardcore', cluster: 'found footage / subculture', period: '1999', summary: '采样数十年英国舞厅与club录像，把亚文化影像重组为一条不存在但极具身体感的共同记忆。', actions: ['VHS / found footage采样', '剪辑', '声音重构'], sourceUrl: 'https://www.tate.org.uk/art/artists/mark-leckey-6877', images: [img('https://static.frieze.com/files/styles/frieze_teaser/public/article/thumbnail/mark-leckey-fiorucci-made-me-hardcore-1999-t.jpg?VersionId=h7D1spvcWeeV64i4pFjB5X_GMxxzM.Cn&itok=yPtsbRdS', 'Fiorucci Made Me Hardcore', '© Mark Leckey', 'https://www.frieze.com/tags/mark-leckey', 'Frieze')], relations: [] },
      { title: 'Industrial Light and Magic', cluster: 'sound / commodity / technology', period: '2008', summary: 'Turner Prize时期将消费物件、声音、影像与技术迷恋并置。', actions: ['声音系统', '雕塑', '影像'], sourceUrl: 'https://www.tate.org.uk/art/artists/mark-leckey-6877', images: [], relations: [rel('奖项', 'Turner Prize', 'winner 2008')] },
      { title: 'Dream English Kid, 1964–1999 AD', cluster: 'internet autobiography', period: '2015', summary: '用互联网找到的公共影像和声音替代自己缺失的童年记忆，制作“found memory”自传。', actions: ['网络搜集', '档案剪辑', '声音编辑'], sourceUrl: 'https://shop.tate.org.uk/mark-leckey-o-magic-power-of-bleakness-exhibition-book/23034.html', images: [img('https://contemporaryartsociety.org/sites/default/files/images/2025-JSF-ML-088.jpg', 'Dream English Kid / exhibition context', '© Mark Leckey', 'https://contemporaryartsociety.org/artists/mark-leckey', 'Contemporary Art Society')], relations: [] },
      { title: 'O’ Magic Power of Bleakness', cluster: 'memory / immersive installation', period: '2019', summary: '围绕高速公路桥与青少年记忆，把影像、声音、剧场和雕塑压成可进入的环境。', actions: ['场景搭建', '声音', '影像', 'performance'], sourceUrl: 'https://shop.tate.org.uk/mark-leckey-o-magic-power-of-bleakness-exhibition-book/23034.html', images: [], relations: [rel('展览', 'Tate Britain', '2019')] }
    ], awards: ['Turner Prize 2008 — winner'], exhibitions: ['Tate Britain — O’ Magic Power of Bleakness 2019'], sources: [{ label: 'Tate exhibition archive', url: 'https://shop.tate.org.uk/mark-leckey-o-magic-power-of-bleakness-exhibition-book/23034.html' }]
  },
  'laure-prouvost': {
    artistId: 'laure-prouvost', projectCoverage: '4 个关键项目 / 展览节点已索引', imageCoverage: '', note: 'Prouvost 的作品标题和展览常互相衍生，第一轮按决定职业轨迹的作品/国家馆节点归档，继续补影片与雕塑单件。',
    projects: [
      { title: 'The Wanderer', cluster: 'translation / fiction', period: '2011', summary: '从错误翻译生成新的影像叙事，把语言失误变成创作机制。', actions: ['错误翻译', '录像', '虚构叙事'], sourceUrl: 'https://www.laureprouvost.com/', images: [], relations: [] },
      { title: 'Wantee', cluster: 'fictional family archive', period: '2013', summary: '虚构祖父、茶会、家具与影像共同组成不可靠家庭神话。', actions: ['录像', '家具布景', '文本 / voice-over'], sourceUrl: 'https://www.tate.org.uk/art/artists/laure-prouvost-21175', images: [img('https://cdn.artobserved.com/artimages/2013/11/Laure-Prouvost-Wantee-Installation-View-via-Turner-Prize-1.jpg', 'Wantee — installation', '© Laure Prouvost', 'https://www.tate.org.uk/art/artists/laure-prouvost-21175', 'Tate / Turner Prize')], relations: [rel('奖项', 'Turner Prize', 'winner 2013')] },
      { title: 'Deep See Blue Surrounding You', cluster: 'Venice / migration / language', period: '2019', summary: '法国馆被改造成海洋色、物件、影像与语言混合的旅程，处理边界、迁移与身份流动。', actions: ['国家馆整体布景', '多屏影像', '雕塑', '文本'], sourceUrl: 'https://www.labiennale.org/en/art/2019/national-participations/france', images: [img('https://images.are.na/eyJidWNrZXQiOiJhcmVuYV9pbWFnZXMiLCJrZXkiOiI1MjgyNjc3L29yaWdpbmFsX2FjNzRhZTQ2YjYyZGUyNTRlMDM1YzYyMTczMTYxNjRlLmpwZyIsImVkaXRzIjp7InJlc2l6ZSI6eyJ3aWR0aCI6MTIwMCwiaGVpZ2h0IjoxMjAwLCJmaXQiOiJpbnNpZGUiLCJ3aXRob3V0RW5sYXJnZW1lbnQiOnRydWV9LCJ3ZWJwIjp7InF1YWxpdHkiOjc1fSwianBlZyI6eyJxdWFsaXR5Ijo3NX0sInJvdGF0ZSI6bnVsbH19', 'Deep See Blue Surrounding You', '© Laure Prouvost', 'https://www.are.na/block/5282677', 'Venice documentation')], relations: [rel('展览', 'French Pavilion, Venice Biennale', '2019')] },
      { title: '36th São Paulo Biennial', cluster: 'biennial context', period: '2025', summary: '进入 Not All Travellers Walk Roads 语境，继续发展语言、身体和共同生活的非线性叙事。', actions: ['空间装置', '双年展语境重组'], sourceUrl: 'https://36.bienal.org.br/en/participants/', images: [], relations: [rel('展览', 'São Paulo Biennial', '2025')] }
    ], awards: ['Turner Prize 2013 — winner'], exhibitions: ['French Pavilion — Venice 2019', 'São Paulo Biennial 2025'], sources: [{ label: 'Artist website', url: 'https://www.laureprouvost.com/' }]
  },
  'jesse-darling': {
    artistId: 'jesse-darling', projectCoverage: '4 个关键项目已索引 · 2018–2022', imageCoverage: '', note: '第一轮围绕导致 Turner Prize 2023 的主要展览脉络补档，同时保留 Venice / Sharjah 等群展关系。',
    projects: [
      { title: 'The Ballad of Saint Jerome', cluster: 'body / institution', period: '2018', summary: 'Art Now 项目把身体支撑、宗教和制度结构压进雕塑空间。', actions: ['雕塑', '场域安装', '现成物'], sourceUrl: 'https://www.tate.org.uk/art/artists/jesse-darling-22019', images: [], relations: [rel('展览', 'Tate Britain — Art Now', '2018')] },
      { title: 'Gravity Road', cluster: 'steel / failure', period: '2020', summary: '巨型钢结构像损坏的过山车和骨架，工程材料失去可靠性。', actions: ['钢材弯折', '大型空间雕塑'], sourceUrl: 'https://www.modernartoxford.org.uk/whats-on/jesse-darling-no-medals-no-ribbons', images: [], relations: [] },
      { title: 'No Medals No Ribbons', cluster: 'survey / fragility', period: '2022', summary: '十年作品被重新组织为政府、宗教、技术、帝国与脆弱身体之间的关系。', actions: ['survey编辑', '雕塑', '绘画', '文本'], sourceUrl: 'https://www.modernartoxford.org.uk/whats-on/jesse-darling-no-medals-no-ribbons', images: [img('https://images.ctfassets.net/my3e36632gpy/7IElLnyj67bxQsHaywO0A1/c9b17bc7c569dbda1f58a6c8e6cb7c5e/JD_MAO_Installation_52.jpg?q=80&w=800', 'No Medals No Ribbons', '© Jesse Darling / Ben Westoby', 'https://www.modernartoxford.org.uk/whats-on/jesse-darling-no-medals-no-ribbons', 'Modern Art Oxford')], relations: [rel('奖项', 'Turner Prize', 'nomination basis / winner 2023')] },
      { title: 'Enclosures', cluster: 'clay / extraction / body', period: '2022', summary: '围绕 clay、extraction 和身体边界展开的研究型委托。', actions: ['陶土研究', '雕塑', '装置'], sourceUrl: 'https://camdenartcentre.org/whats-on/jesse-darling-2', images: [img('https://static.frieze.com/files/inline-images/jesse-darling-enclosures.jpeg', 'Enclosures', '© Jesse Darling', 'https://camdenartcentre.org/whats-on/jesse-darling-2', 'Camden Art Centre')], relations: [rel('展览', 'Camden Art Centre', '2022')] }
    ], awards: ['Turner Prize 2023 — winner'], exhibitions: ['Art Now — Tate Britain 2018', 'Venice Biennale 2019', 'No Medals No Ribbons — Modern Art Oxford 2022', 'Enclosures — Camden Art Centre 2022'], sources: [{ label: 'Modern Art Oxford', url: 'https://www.modernartoxford.org.uk/whats-on/jesse-darling-no-medals-no-ribbons' }, { label: 'Camden Art Centre', url: 'https://camdenartcentre.org/whats-on/jesse-darling-2' }]
  },
  'jasleen-kaur': {
    artistId: 'jasleen-kaur', projectCoverage: '4 个关键项目已索引 · 2019–2025', imageCoverage: '', note: '按艺术家职业路径与 Turner Prize 2024 获奖项目先建立项目骨架，后续继续拆单件动力雕塑、声音和出版。',
    projects: [
      { title: 'Be Like Teflon', cluster: 'oral histories / publication', period: '2019', summary: '通过女性与非二元者的口述、物件和出版组织多声部身份经验。', actions: ['口述史', '编辑', '出版'], sourceUrl: 'https://jasleenkaur.com/', images: [], relations: [] },
      { title: 'Gut Feelings Meri Jaan', cluster: 'food / sound / memory', period: '2021', summary: '从食物、身体和家庭语言进入迁移与记忆。', actions: ['声音', '物件', '家庭研究'], sourceUrl: 'https://jasleenkaur.com/', images: [], relations: [] },
      { title: 'Alter Altar', cluster: 'kinetic / sonic installation', period: '2023–24', summary: '地毯、Irn Bru、足球围巾、政治传单、家庭照片和动力雕塑构成一个临时共同体空间。', actions: ['动力雕塑', '声音', '家庭档案', '现成物改造'], sourceUrl: 'https://www.tramway.org/news/tramway-hosts-first-major-scottish-exhibition-from-jasleen-kaur/', images: [img('https://hollybushgardens.co.uk/files/img-9199-large-2560x1707.jpg', 'Alter Altar', '© Jasleen Kaur', 'https://www.tramway.org/news/tramway-hosts-first-major-scottish-exhibition-from-jasleen-kaur/', 'Tramway')], relations: [rel('展览', 'Tramway, Glasgow', '2023'), rel('奖项', 'Turner Prize', 'winner 2024')] },
      { title: 'Boomerang', cluster: 'return / migration', period: '2025', summary: '继续从物件运动、迁移和回返理解离散身份。', actions: ['装置', '声音', '物件编排'], sourceUrl: 'https://jasleenkaur.com/', images: [], relations: [rel('展览', '18th Istanbul Biennial', '2025')] }
    ], awards: ['Turner Prize 2024 — winner'], exhibitions: ['Alter Altar — Tramway 2023', 'Turner Prize — Tate Britain 2024', 'Istanbul Biennial 2025'], sources: [{ label: 'Artist website', url: 'https://jasleenkaur.com/' }, { label: 'Tramway — Alter Altar', url: 'https://www.tramway.org/news/tramway-hosts-first-major-scottish-exhibition-from-jasleen-kaur/' }]
  },
  'john-akomfrah': {
    artistId: 'john-akomfrah', projectCoverage: '5 个核心影像项目已索引 · 1986–2024', imageCoverage: '', note: 'Akomfrah 作品量巨大，第一轮覆盖 Black Audio Film Collective 到 Venice 2024 的五个关键节点；后续继续补单屏/多屏作品、commission 与 filmography。',
    projects: [
      { title: 'Handsworth Songs', cluster: 'Black Audio Film Collective', period: '1986', summary: '新闻、档案与社区影像重组1985年英国城市骚乱及其历史条件。', actions: ['档案搜集', 'essay-film montage', '声音与文本'], sourceUrl: 'https://www.lissongallery.com/artists/john-akomfrah', images: [], relations: [] },
      { title: 'Vertigo Sea', cluster: 'ocean / migration / violence', period: '2015', summary: '三屏并置海洋自然史、鲸捕、战争和迁移。', actions: ['三屏剪辑', '档案影像', '新拍景观', '声音'], sourceUrl: 'https://www.lissongallery.com/artists/john-akomfrah', images: [], relations: [rel('展览', 'Venice Biennale', '2015 International Exhibition context')] },
      { title: 'Purple', cluster: 'climate / memory', period: '2017', summary: '六频道影像在多个国家处理气候变化、工业史和个人记忆。', actions: ['多地拍摄', '六屏安装', '档案蒙太奇'], sourceUrl: 'https://www.lissongallery.com/artists/john-akomfrah', images: [img('https://images.e-flux-systems.com/195727_15b246f346b891565025c84c7abe6f51.jpg%2C2000x2000', 'Purple', '© John Akomfrah', 'https://www.lissongallery.com/artists/john-akomfrah', 'Lisson Gallery')], relations: [] },
      { title: 'Four Nocturnes', cluster: 'ecology / colonialism', period: '2019', summary: '非洲象、狩猎、生态与殖民历史在夜色和多屏结构中交织。', actions: ['location filming', '三屏影像', '生态档案'], sourceUrl: 'https://www.lissongallery.com/artists/john-akomfrah', images: [], relations: [] },
      { title: 'Listening All Night To The Rain', cluster: 'British Pavilion', period: '2024', summary: '八个互相连接的多屏 sound/time-based works 用水和“倾听”连接五大洲殖民历史与离散经验。', actions: ['八部分多屏系统', '档案', '声音', '全馆空间设计'], sourceUrl: 'https://www.labiennale.org/en/art/2024/great-britain', images: [img('https://media.showstudio.com/images/John_Akomfrah_Canto_V_Listening_All_Night_To_.width-2880_SX3JwgNJtYT4rzpD.jpg', 'Listening All Night To The Rain', '© John Akomfrah', 'https://www.labiennale.org/en/art/2024/great-britain', 'Venice Biennale')], relations: [rel('展览', 'British Pavilion, Venice Biennale', '2024')] }
    ], awards: ['Knight Bachelor 2023'], exhibitions: ['Venice Biennale 2015', 'Sharjah Biennial 15 — Arcadia 2023', 'British Pavilion — Venice 2024'], sources: [{ label: 'British Council — Venice 2024', url: 'https://venicebiennale.britishcouncil.org/history/2020s/2024-sir-john-akomfrah-ra' }, { label: 'Lisson artist archive', url: 'https://www.lissongallery.com/artists/john-akomfrah' }]
  },
  'archie-moore': {
    artistId: 'archie-moore', projectCoverage: '4 个关键作品群已索引 · 2013–2026', imageCoverage: '', note: '第一轮围绕 Black Dog、Dwelling 与 kith and kin 建立方法谱系；后续继续补 Les Eaux d’Amoore、语言项目和绘画单件。',
    projects: [
      { title: 'Black Dog', cluster: 'self-portrait / racial language', period: '2013', summary: '以黑狗形象替代直接自画像，让种族化语言、动物形象和自我观看发生冲突。', actions: ['雕塑 / taxidermy-like object', '自画像替代'], sourceUrl: 'https://thecommercialgallery.com/artist/archie-moore/exhibition/394/black-dog/installation_view/6862', images: [img('https://thecommercialgallery.com/images/thumbed/780_650_r_f6542107ce4a283ad6b1109ff85b2bf6.jpg', 'Black Dog', '© Archie Moore / Carl Warner', 'https://thecommercialgallery.com/artist/archie-moore/exhibition/394/black-dog/installation_view/6862', 'The Commercial')], relations: [rel('收藏', 'National Gallery of Australia', 'acquired')] },
      { title: 'Dwelling', cluster: 'immersive memory architecture', period: '2010–22', summary: '持续多次重建童年居所，每个版本根据地方与记忆改变。', actions: ['建筑重建', '生活物件', '气味 / 声音', '个人档案'], sourceUrl: 'https://gertrude.org.au/article/archie-moore-in-discussion-with-paris-lettau/', images: [img('https://www.datocms-assets.com/36179/1663637502-22-8_gertrude_preston_4.jpg?auto=format', 'Dwelling (Victorian Issue)', 'Photo Christian Capurro / © Archie Moore', 'https://gertrude.org.au/article/archie-moore-in-discussion-with-paris-lettau/', 'Gertrude Contemporary')], relations: [rel('展览', 'Gertrude Contemporary', 'Victorian Issue, 2022')] },
      { title: 'kith and kin', cluster: 'genealogy / state archive', period: '2024', summary: '巨大黑墙上的手绘家谱与中央桌上的原住民拘押死亡国家档案并置。', actions: ['族谱研究', '墙面手绘', '国家档案', '全馆空间安装'], sourceUrl: 'https://www.labiennale.org/en/art/2024/australia', images: [img('https://creative.gov.au/sites/creative-australia/files/styles/hd/public/images/2025-03/Archie-kith-and-kin-yoast-2-1200x630-1-997x523.jpg.webp?itok=8B3o0aGZ', 'kith and kin', '© Archie Moore', 'https://creative.gov.au/advocacy-and-research/events/archie-moore-kith-and-kin/', 'Creative Australia')], relations: [rel('奖项', 'Golden Lion — Best National Participation', 'Venice 2024')] },
      { title: 'Remnants of My Father', cluster: 'family memory', period: '2026', summary: '继续从父亲、残留物与记忆推进个人史和殖民历史的交叉。', actions: ['家庭材料', '空间装置'], sourceUrl: 'https://thecommercialgallery.com/artist/archie-moore', images: [], relations: [] }
    ], awards: ['Golden Lion — Best National Participation, Venice Biennale 2024'], exhibitions: ['Dwelling — Gertrude Contemporary 2022', 'Australia Pavilion — Venice Biennale 2024'], sources: [{ label: 'Creative Australia — kith and kin', url: 'https://creative.gov.au/advocacy-and-research/events/archie-moore-kith-and-kin/' }, { label: 'Gertrude — Dwelling', url: 'https://gertrude.org.au/article/archie-moore-in-discussion-with-paris-lettau/' }]
  },
  'mataaho-collective': {
    artistId: 'mataaho-collective', projectCoverage: '6 / 14 个官网 Works 已完成深度条目 · 其余继续补', imageCoverage: '', note: 'Mataaho 官网当前作品目录至少覆盖 2013–2025 的14件/组作品。第一轮先做6个关键节点并保留明确完成度，下一轮继续把其余官网 Works 逐件补齐。',
    projects: [
      { title: 'Te Whare Pora', cluster: 'early textile installation', period: '2013', summary: '以毯、satin、cotton 等材料建立女性编织空间与当代安装的联系。', actions: ['缝合', '悬挂', '纺织材料研究'], sourceUrl: 'https://mataahocollective.com/artworks', images: [img('https://www.tepapa.govt.nz/assets/76067/1691036815-slideshow-te-whare-pora.jpg', 'Te Whare Pora', '© Mataaho Collective', 'https://mataahocollective.com/artworks', 'Mataaho / Te Papa')], relations: [] },
      { title: 'Kiko Moana', cluster: 'ocean / fibre', period: '2017', summary: '蓝色工业材料形成巨大水体般悬挂结构。', actions: ['工业纤维编织', '大型悬挂', '场域适配'], sourceUrl: 'https://mataahocollective.com/artworks', images: [], relations: [rel('展览', 'documenta 14 context', '2017')] },
      { title: 'Atapō', cluster: 'mesh / steel / muka', period: '2020', summary: '网、钢、羊毛与muka的张力形成共同承重结构。', actions: ['网结构', '钢材', '传统纤维知识'], sourceUrl: 'https://mataahocollective.com/artworks', images: [], relations: [rel('奖项', 'Walters Prize', '2021 context')] },
      { title: 'Takapau', cluster: 'ceremony / cargo tie-downs', period: '2022–24', summary: '反光货运绑带构成巨型 takapau 图案，2024 在 Venice Arsenale 以极大尺度覆盖空间。', actions: ['货运绑带编织', '巨大悬挂', '利用建筑光影'], sourceUrl: 'https://www.labiennale.org/en/art/2024/nucleo-contemporaneo/mataaho-collective', images: [img('https://media.rnztools.nz/rnz/image/upload/s--xK7cXYK8--/t_kt-lifestyle-article-photo/w_7008/f_auto/q_auto%3Aeco/4KRKDAG_EP_06_NZatVenice_Mataaho_Collective_Takapau_ep_5_jpg', 'Takapau — Venice', '© Mataaho Collective / Ben Stewart', 'https://www.labiennale.org/en/art/2024/nucleo-contemporaneo/mataaho-collective', 'Venice Biennale')], relations: [rel('奖项', 'Golden Lion — Best Participant', 'Venice 2024')] },
      { title: 'Tuakirikiri', cluster: 'Gwangju / interdependence', period: '2023', summary: '为第14届光州双年展发展的大型纤维空间。', actions: ['结 / 拉力结构', '场域安装'], sourceUrl: 'https://mataahocollective.com/artworks', images: [img('https://images.squarespace-cdn.com/content/v1/658220e996f1885a5bb3dac0/ecda1ed3-028a-4414-aeb0-a960f02f028f/gwang1.JPG', 'Tuakirikiri — Gwangju', '© Mataaho Collective', 'https://mataahocollective.com/artworks', 'Mataaho Collective')], relations: [rel('展览', '14th Gwangju Biennale', '2023')] },
      { title: 'Hautāmiro', cluster: 'later fibre work', period: '2025', summary: '延续四人共同制作、结构互依和工业材料的长期方法。', actions: ['集体编织', '大型空间结构'], sourceUrl: 'https://mataahocollective.com/artworks', images: [], relations: [] }
    ], awards: ['Golden Lion — Best Participant, Venice Biennale 2024'], exhibitions: ['documenta 14 — 2017', 'Biennale of Sydney 2022', 'Gwangju Biennale 2023', 'Venice Biennale 2024'], sources: [{ label: 'Official works index', url: 'https://mataahocollective.com/artworks' }, { label: 'Official exhibitions', url: 'https://mataahocollective.com/exhibitions' }]
  },
  'lorna-simpson': {
    artistId: 'lorna-simpson', projectCoverage: '4 个关键作品群已索引 · 1989–现在', imageCoverage: '', note: '第一轮覆盖 photo-text、无身体档案、录像和 found-image collage 四条方法线；MoMA 当前馆藏/在线档案继续作为后续单件补图入口。',
    projects: [
      { title: 'Guarded Conditions', cluster: 'photo-text / fragmented body', period: '1989', summary: '重复的黑人女性背部图像被切分，与文字共同制造身份判断的不稳定。', actions: ['重复肖像', '分格安装', '文字并置'], sourceUrl: 'https://www.moma.org/collection/artists/6602', images: [img('https://d7hftxdivxxvm.cloudfront.net/?height=1431&quality=80&resize_to=fit&src=https%3A%2F%2Fd32dm0rphc51dk.cloudfront.net%2FUZlRYWd5xCxXtngW-4DnYQ%2Flarge.jpg&width=1919', 'Guarded Conditions', '© Lorna Simpson', 'https://www.moma.org/collection/artists/6602', 'MoMA')], relations: [] },
      { title: 'Wigs', cluster: 'object archive / identity', period: '1994', summary: '假发图像以档案网格出现，身体缺席但种族和性别编码仍被强烈激活。', actions: ['物件摄影', '网格', '文字'], sourceUrl: 'https://www.moma.org/collection/artists/6602', images: [img('https://www.moma.org/d/c/installation_images/W1siZiIsIjUzMjgyMCJdLFsicCIsImNvbnZlcnQiLCItcXVhbGl0eSA3MCAtcmVzaXplIDU5NHgzOTleIC1ncmF2aXR5IENlbnRlciAtY3JvcCA1OTR4Mzk5KzArMCJdXQ.jpg?sha=b6e3c10044632ba5', 'Wigs — installation', '© Lorna Simpson', 'https://www.moma.org/collection/artists/6602', 'MoMA')], relations: [rel('收藏', 'MoMA', 'collection')] },
      { title: 'Easy to Remember', cluster: 'voice / fragmented body', period: '2001', summary: '15个嘴部特写共同哼唱，身份从可见身体转向声音、重复与记忆。', actions: ['单频道录像', '嘴部特写网格', '声音循环'], sourceUrl: 'https://lsimpsonstudio.com/films/easy-to-remember-2001', images: [img('https://static.livebooks.com/a5fe42e308a84253b5c69b5cb36cbd24/i/d84d73252bb64353814be722b9a38075/1/GCuCv726gZycFxatXh9yJ4/EasyToRemember_2001_LSimpson_UndergroundMuseumInstallation_Wide_PhotoCredit_JamesWang_72dpi_2560px.jpg', 'Easy to Remember', '© Lorna Simpson / James Wang', 'https://lsimpsonstudio.com/films/easy-to-remember-2001', 'Lorna Simpson Studio')], relations: [] },
      { title: 'Ebony / Jet archive collages', cluster: 'found image / recomposed body', period: '2010s–', summary: '黑人杂志档案、头发、地质和宇宙图像被切割重组，制造新身体。', actions: ['杂志档案搜集', '拼贴', '再摄影 / print'], sourceUrl: 'https://lsimpsonstudio.com/', images: [], relations: [rel('展览', 'Sharjah Biennial 16', '2025')] }
    ], awards: [], exhibitions: ['Whitney Biennial context', 'Sharjah Biennial 16 — 2025'], sources: [{ label: 'MoMA collection', url: 'https://www.moma.org/collection/artists/6602' }, { label: 'Artist studio', url: 'https://lsimpsonstudio.com/' }]
  },
  'martha-rosler': {
    artistId: 'martha-rosler', projectCoverage: '4 个奠基性作品群已索引 · 1967–1989', imageCoverage: '', note: '先完成 Rosler 对摄影/媒体史影响最大的四条线；MoMA 当前有59件在线作品，可继续逐件扩充后期录像、机场/战争项目和社会实践。',
    projects: [
      { title: 'House Beautiful: Bringing the War Home', cluster: 'photomontage / media war', period: '1967–72', summary: '越战新闻照片被剪进美国理想家居广告，让战争和消费生活在同一图像平面冲突。', actions: ['杂志剪贴', '新闻图像挪用', 'photomontage'], sourceUrl: 'https://www.moma.org/artists/6833-martha-rosler', images: [img('https://images.squarespace-cdn.com/content/v1/5eca6d601a267019b81cfd61/1630404611937-KABEBQT8IWQBQT7MZ0UN/Screenshot%2B2021-08-31%2B11.05.35.png', 'Red Stripe Kitchen', '© Martha Rosler', 'https://www.moma.org/artists/6833-martha-rosler', 'MoMA')], relations: [rel('收藏', 'MoMA', 'series represented')] },
      { title: 'The Bowery in two inadequate descriptive systems', cluster: 'documentary critique', period: '1974–75', summary: '空店面照片与表示醉酒的文字并置，拒绝直接拍摄并“代表”Bowery边缘人群。', actions: ['街道摄影', '文字分类', '24组面板'], sourceUrl: 'https://smarthistory.org/martha-rosler-the-bowery-in-two-inadequate-descriptive-systems/', images: [img('https://smarthistory.org/wp-content/uploads/2022/01/95.117.A-X_01_a02-Large-TIFF_4000-pixels-long-scaled.jpg', 'The Bowery in two inadequate descriptive systems', '© Martha Rosler', 'https://smarthistory.org/martha-rosler-the-bowery-in-two-inadequate-descriptive-systems/', 'Smarthistory')], relations: [] },
      { title: 'Semiotics of the Kitchen', cluster: 'video / feminist performance', period: '1975', summary: '以烹饪示范格式按字母展示工具，动作逐渐变成攻击性身体语言。', actions: ['固定机位录像', '字母顺序', 'performance'], sourceUrl: 'https://www.moma.org/artists/6833-martha-rosler', images: [img('https://www.moma.org/d/c/installation_images/W1siZiIsIjQ3NDEwNSJdLFsicCIsImNvbnZlcnQiLCItcXVhbGl0eSA3MCAtcmVzaXplIDU5NHgzOTleIC1ncmF2aXR5IENlbnRlciAtY3JvcCA1OTR4Mzk5KzArMCJdXQ.jpg?sha=25c6c6fe42f9caa5', 'Semiotics of the Kitchen — installation context', '© Martha Rosler', 'https://www.moma.org/artists/6833-martha-rosler', 'MoMA')], relations: [] },
      { title: 'If You Lived Here…', cluster: 'housing / social practice', period: '1989', summary: '展览、活动者、社区组织和城市住房材料被组织成公共讨论基础设施。', actions: ['策展 / 邀请', '社会研究', '论坛', '文件展示'], sourceUrl: 'https://www.e-flux.com/announcements/33153/martha-roslerif-you-lived-here/', images: [], relations: [] }
    ], awards: [], exhibitions: ['MoMA collection / repeated exhibition history'], sources: [{ label: 'MoMA artist archive', url: 'https://www.moma.org/artists/6833-martha-rosler' }]
  },
  'walid-raad': {
    artistId: 'walid-raad', projectCoverage: '4 个核心作品群已索引 · 1989–现在', imageCoverage: '', note: '第一轮覆盖 The Atlas Group 到 Scratching on things I could disavow 的方法转折；MoMA 的49件在线作品继续作为 individual-work 补档入口。',
    projects: [
      { title: 'The Atlas Group', cluster: 'fictional archive', period: '1989–2004', summary: '虚构研究机构、人物和档案与真实战争资料混合，测试我们相信历史的格式。', actions: ['虚构机构', '摄影档案', '笔记本', '录像', 'lecture'], sourceUrl: 'https://www.moma.org/artists/8193-walid-raad', images: [img('https://www.christies.com/img/LotImages/2023/CKS/2023_CKS_22002_0036_000%28walid_raad_traders_81090011207%29.jpg?mode=max', 'Traders 8.10.90 — Missing Lebanese Wars', '© Walid Raad', 'https://www.moma.org/artists/8193-walid-raad', 'MoMA / Atlas Group documentation')], relations: [rel('收藏', 'MoMA', 'multiple works')] },
      { title: 'My Neck Is Thinner Than a Hair', cluster: 'car-bomb archive', period: '2001', summary: '以照片、技术资料和笔记形式重建黎巴嫩内战汽车炸弹记录。', actions: ['档案搜集', '分类', '照片 + 技术文本'], sourceUrl: 'https://www.moma.org/calendar/exhibitions/1493', images: [img('https://www.moma.org/d/assets/W1siZiIsIjIwMTUvMTEvMTkvMnA1aTdjc3d5bF8xMjg3NDEuanBnIl0sWyJwIiwiY29udmVydCIsIi1xdWFsaXR5IDkwIC1yZXNpemUgMjAwMHgyMDAwXHUwMDNlIl1d/128741.jpg?sha=5f84644622183fcb', 'Atlas Group archive — MoMA', '© Walid Raad', 'https://www.moma.org/calendar/exhibitions/1493', 'MoMA')], relations: [] },
      { title: 'Oh God, he said, talking to a tree', cluster: 'war image / abstraction', period: '2004/08', summary: '从爆炸新闻照片中切出烟尘云，移除其余现场。', actions: ['新闻图像挪用', '数字切割', '31件print series'], sourceUrl: 'https://www.moma.org/collection/works/146814', images: [], relations: [rel('收藏', 'MoMA', 'series')] },
      { title: 'Scratching on things I could disavow', cluster: 'museum / Arab art history', period: '2007–', summary: '建筑模型、颜色、物件和lecture-performance研究海湾博物馆、艺术市场与“阿拉伯现代艺术”制度化。', actions: ['机构研究', 'lecture-performance', '模型', '装置'], sourceUrl: 'https://www.icaboston.org/exhibitions/walid-raad/', images: [img('https://www.icaboston.org/wp-content/uploads/2023/03/160223icawalidraad-850.png', 'Scratching on things I could disavow', '© Walid Raad', 'https://www.icaboston.org/exhibitions/walid-raad/', 'ICA Boston')], relations: [rel('展览', 'MoMA solo exhibition', '2015')] }
    ], awards: [], exhibitions: ['MoMA solo exhibition 2015'], sources: [{ label: 'MoMA artist archive', url: 'https://www.moma.org/artists/8193-walid-raad' }]
  },
  'boris-mikhailov': {
    artistId: 'boris-mikhailov', projectCoverage: '4 个核心系列已索引 · 1960s–1998', imageCoverage: '', note: '第一轮先补影响摄影史最明显的四个系列；MoMA 当前43件在线作品与大量摄影书将在后续继续拆分。',
    projects: [
      { title: 'Red Series', cluster: 'Soviet everyday / color taxonomy', period: '1968–75', summary: '在苏联日常场景中持续追踪红色，让国家意识形态和普通生活在颜色上重叠。', actions: ['街头摄影', '色彩分类', '长期积累'], sourceUrl: 'https://www.moma.org/artists/8168-boris-mikhailov', images: [], relations: [] },
      { title: 'Yesterday’s Sandwich', cluster: 'slide superimposition', period: '1960s–70s', summary: '两张彩色幻灯片叠投，私人身体、街道与社会图像互相污染。', actions: ['双幻灯片叠加', '偶然组合', '投影 / 再输出'], sourceUrl: 'https://www.juliet-artmagazine.com/en/boris-mikhailovs-ukraine/', images: [img('https://www.juliet-artmagazine.com/wp-content/uploads/2022/12/3_Yesterdays-Sandwich-1-1-scaled.jpeg', 'Yesterday’s Sandwich', '© Boris Mikhailov', 'https://www.juliet-artmagazine.com/en/boris-mikhailovs-ukraine/', 'Juliet Art Magazine')], relations: [] },
      { title: 'Unfinished Dissertation', cluster: 'book / handwritten text', period: '1984–85', summary: '照片与手写笔记像未完成论文一样排列，普通生活被不断注释和推翻。', actions: ['照片编辑', '手写文字', '书籍结构'], sourceUrl: 'https://www.moma.org/artists/8168-boris-mikhailov', images: [], relations: [] },
      { title: 'Case History', cluster: 'post-Soviet body / ethics', period: '1997–98', summary: '与Kharkiv边缘和无家者合作拍摄，直接肖像与明确表演/交易关系并存。', actions: ['合作肖像', '编排姿势', '社会纪实', '大型彩色print'], sourceUrl: 'https://www.moma.org/artists/8168-boris-mikhailov', images: [img('https://www.moma.org/d/c/installation_images/W1siZiIsIjIxNTY0NCJdLFsicCIsImNvbnZlcnQiLCItcXVhbGl0eSA5MCAtcmVzaXplIDIwMDB4MjAwMFx1MDAzZSJdXQ.jpg?sha=fa1472f0507ec054', 'Case History — MoMA installation', '© Boris Mikhailov', 'https://www.moma.org/artists/8168-boris-mikhailov', 'MoMA'), img('https://www.christies.com/img/LotImages/2016/CKS/2016_CKS_13794_0055_000%28boris_mikhailov_case_history_1998013056%29.jpg?mode=max', 'Case History — work', '© Boris Mikhailov', 'https://www.moma.org/calendar/exhibitions/1165', 'MoMA / Christie’s documentation')], relations: [rel('展览', 'MoMA — Case History', '2011')] }
    ], awards: ['Hasselblad Award 2000'], exhibitions: ['New Photography 9 — MoMA 1993', 'Case History — MoMA 2011'], sources: [{ label: 'MoMA artist archive', url: 'https://www.moma.org/artists/8168-boris-mikhailov' }]
  },
  'armin-linke': {
    artistId: 'armin-linke', projectCoverage: '5 个关键研究项目已索引 · 1999–2025', imageCoverage: '', note: 'Linke 的实践由长期研究项目和不断变化的展览版本组成；第一轮先覆盖 Alpi、Appearance、Prospecting Ocean、Image Capital 与 Berlin Biennale 2025。',
    projects: [
      { title: 'Alpi', cluster: 'landscape / infrastructure', period: '1999–2004', summary: '横跨阿尔卑斯地区记录旅游、国家、工程和景观管理。', actions: ['跨地域摄影', '录像', '长期档案'], sourceUrl: 'https://www.arminlinke.com/', images: [], relations: [] },
      { title: 'The Appearance of That Which Cannot Be Seen', cluster: 'archive / expert reading', period: '2015–17', summary: '邀请不同专家重新阅读其照片档案，同一图像因此生成互不相同的知识版本。', actions: ['档案重编', '专家访谈', '展陈板 / 影像'], sourceUrl: 'https://www.arminlinke.com/', images: [img('https://www.studiointernational.com/images/articles/l/060-linke-armin-2021/AL_Appearance_1387.jpg', 'The Appearance of That Which Cannot Be Seen', '© Armin Linke', 'https://www.studiointernational.com/index.php/armin-linke-interview-we-have-to-look-at-different-categories-of-photography-artistic-practice-reframing-them', 'Studio International')], relations: [] },
      { title: 'Prospecting Ocean', cluster: 'deep sea / extraction', period: '2017–25', summary: '从联合国、科研机构、ROV、深海采矿和行动者网络研究海洋如何被科学、经济与法律制度化。', actions: ['机构进入', '摄影', '多屏录像', '档案', '访谈'], sourceUrl: 'https://www.arminlinke.com/', images: [img('https://d37vpt3xizf75m.cloudfront.net/api/file/zuHEXECdQoSNnOTvZCEP/convert?compress=true&fit=max&w=750', 'Prospecting Ocean — Columbia GSAPP', '© Armin Linke', 'https://www.arch.columbia.edu/exhibitions/147-prospecting-ocean', 'Columbia GSAPP')], relations: [rel('展览', 'Columbia GSAPP', '2025')] },
      { title: 'Image Capital', cluster: 'images / industry / computation', period: '2022–24', summary: '与 Estelle Blaschke 研究图像在工业、科学和自动化中的存储、测量和经济价值。', actions: ['历史档案', '摄影', '科学合作', '展览研究'], sourceUrl: 'https://www.arminlinke.com/', images: [img('https://medienwissenschaft.philhist.unibas.ch/fileadmin/user_upload/medienwissenschaft/Aktuelles/Image_Capital_im_Centre_Pompidou__2023_.jpeg', 'Image Capital — Centre Pompidou', '© Armin Linke / Estelle Blaschke', 'https://www.arminlinke.com/', 'Centre Pompidou / University of Basel')], relations: [rel('展览', 'Centre Pompidou', '2023–24')] },
      { title: 'Negotiation Tables', cluster: 'Berlin Biennale', period: '2025', summary: '进入第13届柏林双年展，把谈判空间、制度与图像调查继续转成装置。', actions: ['研究', '摄影', '空间装置'], sourceUrl: 'https://13.berlinbiennale.de/en/artists/list', images: [], relations: [rel('展览', '13th Berlin Biennale', '2025')] }
    ], awards: [], exhibitions: ['Centre Pompidou — Image Capital 2023–24', '13th Berlin Biennale 2025', 'Prospecting Ocean — Columbia GSAPP 2025'], sources: [{ label: 'Artist website', url: 'https://www.arminlinke.com/' }, { label: 'Berlin Biennale artist list', url: 'https://13.berlinbiennale.de/en/artists/list' }]
  }
};
