import type { ArtistArchive, ArchiveImage, ArchiveRelation } from './archiveData';

const img = (url: string, title: string, credit: string, sourceUrl: string, sourceLabel: string): ArchiveImage => ({ url, title, credit, sourceUrl, sourceLabel });
const rel = (kind: ArchiveRelation['kind'], label: string, detail?: string): ArchiveRelation => ({ kind, label, detail });

export const archiveBatch9: Record<string, ArtistArchive> = {
  'joachim-schmid': { artistId: 'joachim-schmid', projectCoverage: '5 个 found photography / 网络图像项目已完成第一轮 · 1982–现在', imageCoverage: '', note: '从街头捡照片到 Flickr 海量图像，补出“找到—分类—出版”如何取代拍摄。', projects: [
    { title: 'Bilder von der Straße / Pictures from the Street', cluster: 'found photographs / street archive', period: '1982–2012', summary: '长期收集公共空间中被丢弃或遗失的照片，以编号和时间顺序建立非作者摄影档案。', actions: ['街头捡拾照片', '编号', '保存', '按时间出版'], sourceUrl: 'https://www.macba.cat/en/actor/joachim-schmid/', images: [img('https://files.ocula.com/anzax/5e/5ed8d679-aa73-427d-ac88-7eac0367b2ee_1200_1200.jpg', 'Found-image work', '© Joachim Schmid', 'https://www.macba.cat/en/actor/joachim-schmid/', 'MACBA / secondary documentation')], relations: [] },
    { title: 'Archiv', cluster: 'vernacular image taxonomy', period: '1986–1999', summary: '按大众照片中反复出现的视觉模式进行分类，让普通图像习惯变成可比较的结构。', actions: ['大量现成照片收集', '主题分类', '网格 / 组图'], sourceUrl: 'https://www.macba.cat/en/actor/joachim-schmid/', images: [], relations: [] },
    { title: 'The Face in the Desert', cluster: 'newspaper archive / public project', period: '1999', summary: '进入地方报纸档案重新组织肖像和故事，使被遗忘的新闻照片形成新的公共记忆。', actions: ['报社档案研究', '照片重选', '文本重编'], sourceUrl: 'https://www.macba.cat/en/actor/joachim-schmid/', images: [], relations: [] },
    { title: 'Other People’s Photographs', cluster: 'Flickr / 96 artist books', period: '2008–2011', summary: '从 Flickr 下载大量大众图片，按“生日、食物、自拍”等重复模式制作96册书。', actions: ['Flickr 搜集', '关键词 / 模式分类', '96册按需出版'], sourceUrl: 'https://everydayphotography.org/journal/from-other-peoples-photographs-2008-2011', images: [], relations: [rel('出版', 'Other People’s Photographs', '96 volumes')] },
    { title: 'Picture Library', cluster: 'internet archive / individual obsession', period: '2010s–', summary: '使用与 Other People’s Photographs 相同来源，转而强调个体独特的拍摄执念。', actions: ['网络图像再分类', '图像库编辑'], sourceUrl: 'https://archivopapersjournal.com/ojs/index.php/apj/article/view/55', images: [], relations: [] }
  ], awards: [], exhibitions: [], sources: [{ label: 'MACBA bibliography', url: 'https://www.macba.cat/en/actor/joachim-schmid/' }] },
  'lucas-blalock': { artistId: 'lucas-blalock', projectCoverage: '4 个 Photoshop / 3D / AR 节点已完成第一轮 · 2010s–2019', imageCoverage: '', note: '把“数字修图痕迹”拆成具体工具，而不是笼统写成后期处理。', projects: [
    { title: 'Early Photoshop works', cluster: 'clone stamp / visible retouching', period: '2010s', summary: '使用 clone stamp、重复、拉伸等工具，但故意不把修改痕迹抹平。', actions: ['拍摄日常物', 'clone stamp', '复制 / 拉伸', '保留错误感'], sourceUrl: 'https://whitney.org/exhibitions/2019-biennial/art?section=10', images: [], relations: [] },
    { title: 'The Nonconformist', cluster: 'Photoshop 3D / inflated image surface', period: '2017–2019', summary: '使用 Photoshop 3D 工具虚拟“吹起”照片局部，让平面和伪三维冲突。', actions: ['摄影', 'Photoshop 3D inflation', '大尺幅打印'], sourceUrl: 'https://whitney.org/exhibitions/2019-biennial/art?section=10', images: [img('https://www.christies.com/img/LotImages/2022/AMS/2022_AMS_21972_0325_001%28lucas_blalock_rocking_chair120319%29.jpg?mode=max', 'Rocking Chair', '© Lucas Blalock', 'https://whitney.org/exhibitions/2019-biennial/art?section=10', 'Whitney / Christie’s documentation')], relations: [rel('展览', 'Whitney Biennial', '2019')] },
    { title: '2019 Biennial works', cluster: 'bananas / eggs / virtual volume', period: '2019', summary: '香蕉、鸡蛋和办公室人物都被3D工具“鼓起”，将软件动作当成摄影手工。', actions: ['3D Photoshop', '局部变形', '大尺幅输出'], sourceUrl: 'https://whitney.org/media/42369', images: [], relations: [] },
    { title: 'Donkeys Crossing the Desert', cluster: 'public billboard / AR', period: '2019', summary: '将摄影、变形图像、CG驴和增强现实放入街头广告牌，使真实空间与虚拟摄影空间叠加。', actions: ['数字合成', '公共广告牌', 'AR app'], sourceUrl: 'https://whitney.org/exhibitions/2019-biennial/blalock-donkeys', images: [], relations: [] }
  ], awards: [], exhibitions: ['Whitney Biennial 2019'], sources: [{ label: 'Whitney 2019', url: 'https://whitney.org/exhibitions/2019-biennial/art?section=10' }] },
  'mishka-henner': { artistId: 'mishka-henner', projectCoverage: '5 个卫星 / Street View / 数据图像项目已完成第一轮 · 2010–现在', imageCoverage: '', note: '按平台图像来源拆分 Google Street View、Google Earth、卫星农业与监控。', projects: [
    { title: 'No Man’s Land', cluster: 'Google Street View / sex work / platform gaze', period: '2011–2012', summary: '通过网络论坛线索在 Street View 中定位欧洲道路旁的性工作者，作品同时暴露平台自动采集的伦理。', actions: ['网络线索搜集', 'Street View 浏览', '截图 / 编辑', '摄影书'], sourceUrl: 'https://edcat.net/item/no-mans-land/', images: [img('https://cdn.edcat.net/media/items/MH-NML_Ia.jpg', 'No Man’s Land', '© Mishka Henner', 'https://edcat.net/item/no-mans-land/', 'edcat')], relations: [] },
    { title: 'Dutch Landscapes', cluster: 'Google Earth / censorship / abstraction', period: '2011', summary: '收集荷兰政府在 Google Earth 上以彩色几何块遮盖敏感地点的卫星图。', actions: ['Google Earth 搜索', '敏感地点定位', '平台截图', '打印 / 书'], sourceUrl: 'https://mishkahenner.com/Dutch-Landscapes', images: [], relations: [] },
    { title: 'Feedlots', cluster: 'satellite / industrial agriculture', period: '2012–2013', summary: '从 Google Earth 发现美国大型牛只育肥场，以高空图像研究工业化肉类生产。', actions: ['卫星影像搜索', '农业系统研究', '高分辨率打印'], sourceUrl: 'https://mishkahenner.com/feedlots', images: [], relations: [] },
    { title: '51 U.S. Military Outposts', cluster: 'military / satellite atlas', period: '2010s', summary: '从公开卫星图像整理美国海外军事基地，将全球军事基础设施转成图像目录。', actions: ['卫星影像', '地理定位', '分类出版'], sourceUrl: 'https://mishkahenner.com/', images: [], relations: [] },
    { title: 'Fields / extraction landscapes', cluster: 'infrastructure / overhead image', period: '2010s–', summary: '继续用卫星视角处理油井、蒸发池和工业地表，使平台图像变成基础设施研究。', actions: ['平台图像采集', '工业地景分类', '大尺幅输出'], sourceUrl: 'https://mishkahenner.com/', images: [], relations: [] }
  ], awards: ['Deutsche Börse Photography Prize 2013 shortlist'], exhibitions: [], sources: [{ label: 'Mishka Henner official works', url: 'https://mishkahenner.com/' }] },
  'anouk-kruithof': { artistId: 'anouk-kruithof', projectCoverage: '4 个网络图像 / 摄影雕塑节点已完成第一轮 · 2010s–现在', imageCoverage: '', note: '重点补“屏幕图像如何被打印、弯折、堆叠成实体”的转换链。', projects: [
    { title: 'Automagic', cluster: 'book / archive / image association', period: '2010s', summary: '把个人与既有图像按联想而非传统主题整理成复杂摄影书。', actions: ['档案整理', '图像关联', '摄影书编辑'], sourceUrl: 'https://www.anoukkruithof.com/', images: [], relations: [] },
    { title: '#EVIDENCE', cluster: 'internet images / photographic sculpture', period: '2017', summary: '使用网络现成图像和柔性打印材料，将图片拉伸、堆叠并变成立体对象。', actions: ['网络图像搜集', '大幅打印', '折叠 / 拉伸', '雕塑安装'], sourceUrl: 'https://casemoregallery.com/exhibitions/26-evidence-anouk-kruithof/installation_shots/', images: [img('https://static-assets.artlogic.net/w_1200%2Cc_limit%2Cf_auto%2Cfl_lossy%2Cq_auto/ws-artlogicwebsite0019/usr/exhibitions/images/exhibitions/26/evidence-highresjpg-8.jpg', '#EVIDENCE', '© Anouk Kruithof', 'https://casemoregallery.com/exhibitions/26-evidence-anouk-kruithof/installation_shots/', 'Casemore Gallery')], relations: [] },
    { title: 'Universal Tongue', cluster: 'YouTube / dance / video archive', period: '2018–2021', summary: '从互联网收集世界各地舞蹈视频，研究身体动作在平台上的全球流通。', actions: ['YouTube 研究', '视频分类', '多屏影像', '出版'], sourceUrl: 'https://www.anoukkruithof.com/', images: [], relations: [] },
    { title: 'Trans Human Nature', cluster: 'ecology / digital image / installation', period: '2020s', summary: '把环境图像、数字处理与塑料性材料结合，继续研究网络图像的物质后果。', actions: ['数字图像', '打印材料', '空间装置'], sourceUrl: 'https://www.anoukkruithof.com/', images: [], relations: [] }
  ], awards: [], exhibitions: [], sources: [{ label: 'Artist website', url: 'https://www.anoukkruithof.com/' }] },
  'alma-haser': { artistId: 'alma-haser', projectCoverage: '4 个肖像 / 折纸 / 复制项目已完成第一轮 · 2012–现在', imageCoverage: '', note: '围绕“拍摄—打印—手工变形—再摄影”的转译链继续补全。', projects: [
    { title: 'Cosmic Surgery', cluster: 'portrait / origami / rephotography', period: '2012–', summary: '先拍标准肖像，再将脸部打印成纸、复杂折叠后放回原肖像并再次摄影。', actions: ['肖像拍摄', '打印', '折纸', '拼回面部', '再摄影'], sourceUrl: 'https://printsales.thephotographersgallery.org.uk/artists/43-alma-haser/series/cosmic-surgery/', images: [img('https://static-assets.artlogic.net/w_1200%2Cc_limit%2Cf_auto%2Cfl_lossy%2Cq_auto/artlogicstorage/tpgallery/images/view/9819c7b76a8b5ecb56988a43fb5d0cc4j/printsalesgallery-thephotographers-gallery-alma-haser-patient-no.-31-2017.jpg', 'Patient No.31', '© Alma Haser', 'https://printsales.thephotographersgallery.org.uk/artists/43-alma-haser/series/cosmic-surgery/', 'The Photographers’ Gallery')], relations: [] },
    { title: 'Twins', cluster: 'genetic similarity / paired portrait', period: '2010s', summary: '以双胞胎作为复制和差异问题的肖像材料，通过并置和纸面处理强化细小差别。', actions: ['双人肖像', '并置', '纸面加工'], sourceUrl: 'https://www.almahaser.com/', images: [], relations: [] },
    { title: 'Pseudo', cluster: 'identity / synthetic face', period: '2010s', summary: '继续使用实体裁切和重组让真实肖像接近“人工生成”的脸。', actions: ['肖像', '打印', '切割 / 拼贴', '再摄影'], sourceUrl: 'https://www.almahaser.com/', images: [], relations: [] },
    { title: 'Recent paper portrait works', cluster: 'paper object / portrait', period: '2020s', summary: '把折叠、切割和纸雕塑进一步从图像表面扩展为独立物件。', actions: ['纸张雕塑', '摄影', '装置展示'], sourceUrl: 'https://www.almahaser.com/', images: [], relations: [] }
  ], awards: ['Taylor Wessing Portrait Prize 2012 shortlist'], exhibitions: ['The Photographers’ Gallery 2016'], sources: [{ label: 'Artist website', url: 'https://www.almahaser.com/' }] },
  'corinne-vionnet': { artistId: 'corinne-vionnet', projectCoverage: '4 个网络重复 / 集体观看项目已完成第一轮 · 2005–现在', imageCoverage: '', note: '从叠加游客照片到让复制本身腐蚀国旗图像，补出她如何研究“重复观看”。', projects: [
    { title: 'Photo Opportunities', cluster: 'tourism / crowd-sourced image / layering', period: '2005–2014', summary: '在线搜集同一地标的数百张游客照片，将它们透明叠加成一个幽灵般的共同视点。', actions: ['关键词搜索', '游客图像收集', '透视对齐', '数百层数字叠加'], sourceUrl: 'https://corinnevionnet.com/Photo-Opportunities', images: [], relations: [rel('展览', 'SFMOMA — snap+share', '2019')] },
    { title: 'ME Here Now', cluster: 'selfie / landmark / presence', period: '2010s', summary: '研究游客自拍与“我在这里”的图像证明如何改变地标摄影。', actions: ['网络图像收集', '分类', '重组'], sourceUrl: 'https://corinnevionnet.com/', images: [], relations: [] },
    { title: 'TOTAL Flag', cluster: 'reproduction / screen / image decay', period: '2018', summary: '将美国国旗反复显示在屏幕上再拍摄、再显示，直到复制噪声使原图逐渐消失。', actions: ['屏幕显示', '数字相机翻拍', '反复再显示 / 再拍', 'Risograph出版'], sourceUrl: 'https://corinnevionnet.com/TOTAL-Flag', images: [], relations: [rel('出版', 'TOTAL Flag', 'self-published, 2018')] },
    { title: 'Recent network-image works', cluster: 'collective image / platform repetition', period: '2020s', summary: '继续使用网络图像的重复、重叠和再生产讨论共享视觉模板。', actions: ['网络搜集', '数字合成', '打印 / 装置'], sourceUrl: 'https://corinnevionnet.com/', images: [], relations: [] }
  ], awards: [], exhibitions: ['SFMOMA snap+share 2019'], sources: [{ label: 'Corinne Vionnet official archive', url: 'https://corinnevionnet.com/Photo-Opportunities' }] },
  'max-pinckers': { artistId: 'max-pinckers', projectCoverage: '5 个实验纪实 / 表演 / 摄影书项目已完成第一轮 · 2012–2018', imageCoverage: '', note: '重点补他如何故意把闪光、导演和重演暴露出来，以此质疑“透明纪实”。', projects: [
    { title: 'The Fourth Wall', cluster: 'India / cinema / staged documentary', period: '2012', summary: '在印度把电影工业、现实人物和导演式摄影混在一起，让现实与表演不断互换。', actions: ['田野摄影', '闪光', '编排 / 重演', '自出版摄影书'], sourceUrl: 'https://tique.art/features/max-pinckers/', images: [], relations: [rel('出版', 'The Fourth Wall', '2012')] },
    { title: 'Will They Sing Like Raindrops or Leave Me Thirsty', cluster: 'love / social convention / India', period: '2014', summary: '通过爱情、婚姻与社会规范，将真实事件、演员和可见闪光组织在同一纪实结构。', actions: ['采访', '编排摄影', '闪光', '摄影书'], sourceUrl: 'https://tique.art/features/max-pinckers/', images: [], relations: [rel('出版', 'Will They Sing Like Raindrops...', '2014')] },
    { title: 'Two Kinds of Memory and Memory Itself', cluster: 're-enactment / photo history', period: '2015', summary: '引用 Hokusai 与 Jeff Wall 等图像，把摄影史中的“瞬间”重新表演。', actions: ['图像引用', '场景重演', '大型闪光'], sourceUrl: 'https://tique.art/features/max-pinckers/', images: [], relations: [] },
    { title: 'Margins of Excess', cluster: 'US media / disputed stories / documentary', period: '2018', summary: '研究美国媒体中被质疑、夸大或无法证实的个人故事，避免简单裁决真假。', actions: ['长期采访', '肖像与场景编排', '文本 / 档案', '摄影书'], sourceUrl: 'https://www.maxpinckers.be/', images: [], relations: [] },
    { title: 'Red Ink', cluster: 'North Korea / constrained documentary', period: '2017–2018', summary: '在严格导览条件下拍摄朝鲜，以强闪光和明显摄影介入承认“只能在被安排的现实里工作”。', actions: ['受控访问', '直闪', '系列编辑', '摄影书'], sourceUrl: 'https://www.maxpinckers.be/', images: [img('https://images.lensculture.com/image/9cc30883-77c6-4ff7-027b-9ce13e1abd00/large', 'Red Ink', '© Max Pinckers', 'https://www.maxpinckers.be/', 'Artist website / LensCulture documentation')], relations: [rel('出版', 'Red Ink', '2018')] }
  ], awards: [], exhibitions: ['Rencontres d’Arles', 'FOMU Antwerp'], sources: [{ label: 'Artist website', url: 'https://www.maxpinckers.be/' }, { label: 'Tique project overview', url: 'https://tique.art/features/max-pinckers/' }] },
  'harley-weir': { artistId: 'harley-weir', projectCoverage: '4 个身体 / 时尚 / 私人出版节点已完成第一轮', imageCoverage: '', note: '把商业时尚与个人作品分开看，同时追踪闪光、近距离和材料感如何跨两个领域迁移。', projects: [
    { title: 'Bodies / close-up practice', cluster: 'skin / fragment / fashion-art crossover', period: '2010s–', summary: '大量使用极近距离、强闪光和裁切，把皮肤、口腔、布料与物件拍成难以迅速识别的表面。', actions: ['近距离摄影', '直闪 / 强光', '身体裁切', '编辑混合商业与私人图像'], sourceUrl: 'https://harleyweir.com/', images: [], relations: [] },
    { title: 'Homes', cluster: 'Calais / migration / traces', period: '2016', summary: '在 Calais “Jungle” 被拆除前后拍摄居住痕迹、墙面和临时结构，避免以人物苦难作为唯一图像。', actions: ['现场拍摄', '空间痕迹', '摄影书 / 慈善出版'], sourceUrl: 'https://harleyweir.com/', images: [], relations: [] },
    { title: 'Function / Paintings', cluster: 'material surface / image abstraction', period: 'late 2010s', summary: '从摄影表面、污痕、身体和物质细节出发，让时尚影像逐渐接近抽象。', actions: ['材料特写', '颜色 / 颗粒控制', '跨媒介编辑'], sourceUrl: 'https://harleyweir.com/', images: [], relations: [] },
    { title: 'The Garden', cluster: 'body / plants / installation', period: '2020s', summary: '把身体、植物、表面伤痕与私人图像编成松散而触觉化的展览环境。', actions: ['身体与植物摄影', '不同尺寸打印', '空间编排'], sourceUrl: 'https://www.thisispaper.com/mag/the-garden-harley-weir-hannah-barry-gallery', images: [img('https://cdn.prod.website-files.com/5d70caf362d15d860bedae09/69c77edd3104062c1cf06071_6846eef048b97a969e3a6f4d_thisispaper-the-garden-harley-weir-hannah-barry-gallery-london-guide-art-09.webp', 'The Garden — installation', '© Harley Weir', 'https://www.thisispaper.com/mag/the-garden-harley-weir-hannah-barry-gallery', 'Thisispaper')], relations: [] }
  ], awards: [], exhibitions: ['The Garden — Hannah Barry Gallery'], sources: [{ label: 'Artist website', url: 'https://harleyweir.com/' }] }
};
