import type { ArtistArchive, ArchiveRelation } from './archiveData';
const rel = (kind: ArchiveRelation['kind'], label: string, detail?: string): ArchiveRelation => ({ kind, label, detail });

const steyerl='https://www.serpentinegalleries.org/whats-on/hito-steyerl-power-plants/';
const steyerlAR='https://hitosteyerl.serpentinegalleries.org/';
const douglas='https://www.davidzwirner.com/exhibitions/2020/stan-douglas-2020';
const douglasVenice='https://www.davidzwirner.com/news/2019/58th-international-art-exhibition--la-biennale-di-venezia-njideka-akunyili';
const kang='https://www.labiennale.org/en/art/2019/partecipants/suki-seokyeong-kang';
const nkanga='https://www.castellodirivoli.org/comunicato/otobong-nkanga-of-cords-curling-around-mountains/';
const nkangaKub='https://shop.kunsthaus-bregenz.at/de/otobong-nkanga-ausstellungskatalog';
const epaminonda='https://www.labiennale.org/en/art/2019/partecipants/haris-epaminonda';
const awards='https://www.labiennale.org/en/news/biennale-arte-2019-official-awards';
const darling='https://www.labiennale.org/en/art/2019/partecipants/jesse-darling';

export const archiveBatch106: Record<string, ArtistArchive> = {
  'venice-hito-steyerl': {
    artistId:'venice-hito-steyerl', projectCoverage:'2 个 2019 AI / AR 项目已建立作品级长档案', imageCoverage:'0 / 2 项目：官方页面有展览图，但当前不复制不稳定 CDN 地址；入口保留到 Serpentine 官方图集', note:'本轮把抽象的“AI critique”拆成可研究的具体作品：Power Plants 与 Actual Reality OS。重点记录神经网络、AR、数据、LED 标记、iPad、声音和研究伙伴如何真正进入作品，而不是只写“讨论人工智能”。',
    projects:[
      {title:'Power Plants',cluster:'AI-generated moving image / AR / video sculpture / sound',period:'2019',summary:'Steyerl 为 Serpentine 制作一组以人工智能预测“未来植物”的视频雕塑。算法把输入图像变形成位于当下约 0.04 秒之后的预测帧；展览把这些运动图像放入一个受 ruderal garden（废墟地带自发生长植物群落）启发的空间。观众不仅看屏幕，还使用悬挂在展厅中的 iPad 扫描 15 个动态 LED sigil，通过 Power PlantsOS 叠加看到未来植物的虚构植物学描述、未来日期引语以及研究伙伴的真实证词。中央房间另有四段视频呈现 Power Walks 的研究伙伴，让数据背后的社区、住房、残障和劳动议题回到作品内部。',actions:['训练 / 使用神经网络生成不断形变的“预测植物”运动图像，并把预测时间设定在约 0.04 秒之后','把生成影像制作成 video sculptures，而不是仅作为单屏影片播放','以 ruderal garden 为展览空间概念，把技术未来与受扰动环境中的植物生长联系起来','在展厅布置 15 个 animated LED sigils，作为 AR 内容的触发标记','让观众使用悬挂 iPad 扫描 sigils，读取 Power PlantsOS 中的预测、植物描述和研究伙伴引语','把 Power Walks 社区研究制作成四段视频置于中央房间','与 Kojey Radical 合作声音部分；墙面 vinyl text 被设计为需要数字钥匙解码的加密文字'],sourceUrl:steyerl,images:[],relations:[rel('展览','Hito Steyerl: Power Plants — Serpentine Galleries','11 Apr–6 May 2019'),rel('出版','Power Plants exhibition guide','Serpentine Galleries official resource')]},
      {title:'Actual Reality OS / Actual Reality$',cluster:'open-source AR / community data visualisation / site-specific research',period:'2019',summary:'这是与 Power Plants 同期发展的集体研究型 AR 工具。Steyerl 与 The Voice of Domestic Workers、Architects for Social Housing、Unite Hotel Workers、Disabled People Against Cuts、Reclaiming Our Futures Alliance 等伙伴共同收集当地社会数据与证词。观众在 Serpentine 外找到三枚 concrete sigils，用手机或平板扫描后进入 AR 数据层，再继续扫描虚拟 sigil 展开住房、劳动、残障与政策资料。项目被明确设计为 open source，可被公众替换数据集、地点和建筑后重新使用，因此“作品”同时是软件、标记物、数据结构、研究协作与现场路径。',actions:['与社区组织共同收集数据与 testimony，而不是由艺术家单向生成内容','开发可调用设备 camera / location 的 AR application','在画廊外制作三枚 concrete sigils 作为实体入口','让观众按地图寻找 sigil，再扫描进入分层数据可视化','把研究报告与合作组织资料嵌入 app，允许离开现场后继续访问','将工具开放为 open source，使其他人能够替换 dataset / location / architecture 重新部署'],sourceUrl:steyerlAR,images:[],relations:[rel('展览','Actual Reality OS — Serpentine Galleries','11 Apr 2019–31 Jan 2020 · digital commission'),rel('展览','Power Walks','13 Apr–4 May 2019 · guided neighbourhood walks')]}
    ], awards:[], exhibitions:['Hito Steyerl: Power Plants — Serpentine Galleries 2019','Actual Reality OS — Serpentine Galleries 2019–2020'], sources:[{label:'Serpentine · Power Plants',url:steyerl},{label:'Serpentine · Hito Steyerl digital project archive',url:steyerlAR}]
  },

  'venice-stan-douglas': {
    artistId:'venice-stan-douglas', projectCoverage:'2 个 2019 Venice 项目节点已建立作品级档案', imageCoverage:'0 / 2 项目：David Zwirner 官方页提供 installation views / stills，本地不复制其动态媒体地址', note:'从“cinematic restaging”进一步落到具体作品。Doppelgänger 的关键不是科幻题材，而是两块可从正反两面观看的半透明方形屏幕如何把两个平行世界同时组织进观众身体周围。Blackout 则作为 Venice 2019 同期摄影节点保留。',
    projects:[
      {title:'Doppelgänger',cluster:'two-channel video installation / speculative history / cinematic production',period:'2019',summary:'作品在 2019 Venice Biennale 首展，设定于一个 alternative present：两个相距光年的世界同时发射宇宙飞船，叙事以并置的小场景展开。Douglas 不把影片放在传统正面银幕上，而使用两块 square-format translucent screens，每块都可以从正反两侧观看。于是同一空间里形成多个观看方向：观众移动到屏幕后方时仍能看到影像，同时会不断改变两个世界、两个屏幕和自身位置之间的关系。这个装置结构把“doppelgänger / 平行版本”的主题直接变成空间经验。',actions:['从 alternative-present 的剧本结构出发，制作两个彼此呼应但并非完全相同的世界','以演员、布景、摄影和后期制作完成 cinematic scenes，而不是使用现成科幻素材','把 looped narrative 切成 side-by-side vignettes，让两个世界持续互相比较','制作两块 square-format translucent projection screens','允许每块屏幕从正反两面观看，使四个观看面同时存在','通过观众绕行改变叙事的空间关系：作品没有唯一“正确正面”','在 Venice 2019 首展后，于 New York / London 版本继续以双屏空间结构呈现'],sourceUrl:douglas,images:[],relations:[rel('展览','May You Live In Interesting Times — Venice Biennale','2019 · debut'),rel('展览','David Zwirner, New York','16 Jan–22 Feb 2020'),rel('展览','Victoria Miro, London','2020')]},
      {title:'Blackout',cluster:'staged photography / social tension / cinematic lighting',period:'2017; Venice presentation 2019',summary:'Venice 2019 的 Douglas 展示语境同时包含 Blackout 系列摄影。与 Doppelgänger 一样，这些照片应从“电影制作逻辑进入单张照片”来理解：Douglas 的摄影不是街头即时抓拍，而是通过研究、场景控制、人物调度与电影式照明制造一个看似已经发生的历史瞬间。官方 Venice viewing-room 将 Blackout 与 Doppelgänger 并置，使静态摄影和时间影像之间的共同生产方法变得清楚。',actions:['以社会 / 历史情境研究作为 staged photograph 的前置工作','组织人物、环境与 lighting，使照片具有电影场景的密度','把单张摄影当作没有运动时间的 cinema frame 来生产','在 Venice 语境中与 Doppelgänger 并置，让 still image 与 moving image 的媒介差异成为观看内容'],sourceUrl:douglasVenice,images:[],relations:[rel('展览','58th Venice Biennale / David Zwirner Venice presentation','2019 · photographs shown alongside Doppelgänger context')]}
    ], awards:[], exhibitions:['May You Live In Interesting Times — Venice Biennale 2019','Stan Douglas: Doppelgänger — David Zwirner 2020'], sources:[{label:'David Zwirner · Doppelgänger',url:douglas},{label:'David Zwirner · Venice 2019',url:douglasVenice}]
  },

  'venice-suki-seokyeong-kang': {
    artistId:'venice-suki-seokyeong-kang', projectCoverage:'1 个 painting-sculpture-video / activation corpus 已建立深档案 · 2010s–2019', imageCoverage:'0 / 1 项目暂不使用不稳定外链图像', note:'Kang 的 practice 同时包含 painting、sculpture、video 与她称为 activation 的现场动作；重点不是媒介并列，而是用 Korean cultural heritage 与 personal history 重构 individual agency 的空间。',
    projects:[{title:'Activation / politicised-arena corpus — Venice 2019',cluster:'painting + sculpture + video / activation / individual agency',period:'2010s–2019',summary:'作品把不同媒介组织成可被身体激活的场域，借 Korean cultural heritage 与个人历史重新想象 ideological structure，使 individual stakeholder 能在 present space-time 中表达和执行 agency。',actions:['将 painting、sculpture、video 作为同一 spatial system 组织','设计需要 bodily activation / movement 才完整的观看关系','从 Korean cultural heritage 提取 structure 而非做传统图像复刻','将 personal history 与 collective ideological structure 并置','让 individual agency 通过站位、移动、关系和尺度被空间化'],sourceUrl:kang,images:[],relations:[rel('展览','May You Live In Interesting Times — Venice Biennale 2019','Central Pavilion / Arsenale')]}], awards:[], exhibitions:['May You Live In Interesting Times — Venice Biennale 2019'], sources:[{label:'La Biennale · Suki Seokyeong Kang 2019',url:kang}]
  },

  'venice-otobong-nkanga': {
    artistId:'venice-otobong-nkanga', projectCoverage:'3 个材料 / 土地 / 资源项目节点已建立作品级长档案', imageCoverage:'0 / 3 项目：机构档案含 installation views；当前不复制不稳定媒体地址，均保留官方图集入口', note:'本轮不再只写“土地、身体、贸易”。档案拆到具体材料和空间：大型 tapestry 如何贯穿楼层、clay / water / glass 如何形成景观，以及 kolanut 项目如何把植物、贸易与时间连在一起。',
    projects:[
      {title:'Unearthed',cluster:'four-part monumental tapestry / vertical architecture',period:'2021',summary:'为 Kunsthaus Bregenz 创作的 Unearthed 是四件各约 6 × 3.5 米的大型 tapestry；四件组成一个连续 motif，并分别进入建筑的四层，使图像在垂直方向上像穿过整栋楼。KUB 对展览的描述还指出，现场同时出现一个仿佛贯穿楼层的 tree trunk，以及由 clay、water 和 glass objects 构成的 landscapes。这里材料不是装饰：石头、织物、黏土、植物和水被用来追问它们来自哪里、经过谁的劳动和土地、又如何被迁移和占有。',actions:['设计四件 6 × 3.5 m tapestry，使四层展厅共享一个连续图像 motif','利用 KUB 垂直建筑结构，把 tapestry 变成跨楼层的视觉连接','在展览中设置仿佛穿透楼层的 tree-trunk form，加强上下空间的连续感','以 clay、water、glass objects 组成地景式装置，而不是把材料放进中性展柜','把 stones、textiles、clay、plants 等材料的来源和流通史作为作品内容','让观众逐层移动，在身体上经历同一图像 / 材料系统被建筑切分又重新连接'],sourceUrl:nkangaKub,images:[],relations:[rel('展览','Otobong Nkanga — Unearthed, Kunsthaus Bregenz','2021–2022'),rel('出版','Otobong Nkanga — Unearthed','Kunsthaus Bregenz catalogue · 2022')]},
      {title:'Kolanut Tales: Slow Stain',cluster:'plant / trade / colonial history / material research',period:'2012–2017',summary:'Castello di Rivoli 明确记录该作曾于 2017 年在 Manica Lunga 展出，随后进入馆藏。项目以 kola nut 为材料与历史入口：重要的不只是植物图像，而是沿着植物、商品交换、殖民贸易和文化使用追踪“物”如何在土地、身体与经济网络之间移动。它代表 Nkanga 很典型的工作方法——从一种具体物质出发，逐渐展开跨地域关系，而不是先给出抽象生态主题。',actions:['选择 kola nut 这一具体植物 / 商品作为研究入口','追踪其使用、交换与跨地域流通所携带的社会历史','把植物材料与 colonial / trade history 放进同一叙事网络','在展览空间中把“物质本身”与其不可见的经济、文化关系同时呈现','让项目随多年研究延展，而非一次性完成单一图像'],sourceUrl:nkanga,images:[],relations:[rel('展览','L’emozione dei COLORI nell’arte — Castello di Rivoli / GAM','2017'),rel('收藏','Castello di Rivoli collection','entered collection after 2017 presentation')]},
      {title:'Of Cords Curling around Mountains — exhibition constellation',cluster:'installation / extraction / repair / ecological materiality',period:'2021–2022',summary:'Castello di Rivoli 的个展把 Nkanga 对 extraction、natural resources、colonial history 与 repair 的研究组织成多房间环境。机构档案保存大量 installation views，并列出 2021 年现场作品 Leaving Trails in the Distance 等。观看方式不是逐件孤立看雕塑，而是在空间里追踪材料、绳索般关系、地景和身体之间的连接；展览把“照料材料”本身作为对数字化世界与资源开采逻辑的回应。',actions:['把多个时期作品与新作组织成连续空间，而不是按媒介分区','使用 material care 作为展陈逻辑，强调物质的来源、损耗和修复','通过 installation distance / adjacency 建立作品之间像 cords 一样的关系','让 extraction 与 colonial history 通过具体材料而不是说明文字单独承担','要求观众在展厅移动中逐步拼出资源、土地、身体和贸易之间的网络'],sourceUrl:nkanga,images:[],relations:[rel('展览','Of Cords Curling around Mountains — Castello di Rivoli','25 Sep 2021–2022'),rel('出版','Of Cords Curling around Mountains catalogue','Castello di Rivoli')]}
    ], awards:['Special Mention — Venice Biennale 2019'], exhibitions:['May You Live In Interesting Times — Venice Biennale 2019','Of Cords Curling around Mountains — Castello di Rivoli 2021–2022','Unearthed — Kunsthaus Bregenz 2021–2022'], sources:[{label:'Castello di Rivoli · exhibition / press archive',url:nkanga},{label:'Kunsthaus Bregenz · Unearthed',url:nkangaKub},{label:'La Biennale · Official Awards 2019',url:awards}]
  },

  'venice-haris-epaminonda': {
    artistId:'venice-haris-epaminonda', projectCoverage:'1 个 found-object constellation / compressed-memory installation 核心方法节点已建立深档案 · 2019', imageCoverage:'0 / 1 项目暂不使用不稳定外链图像', note:'Epaminonda 的方法不是“旧物拼贴”这么简单：sculpture、pottery、book、photograph 被按 qualia 选择，原本历史并不被解释清楚，而是在新的 constellation 中以 fragment memory 的方式继续作用。',
    projects:[{title:'Found-object constellations — Venice 2019 corpus',cluster:'found sculpture / pottery / book / photograph / loose meaning-web',period:'2019',summary:'各种 found objects 被极度克制地组合，历史与 personal meaning 不被说明，而通过 material presence、距离、colour 与形式关系形成 loose web。',actions:['搜集 sculpture、pottery、book、photograph 等既有 objects','优先根据 object qualia / experiential quality 选择而非完整 provenance story','用距离、scale、colour 与空白组织 constellation','保留 historical / personal meaning 的不完整和未知','让 objects 在 installation 中被轻微 shift，既保留旧痕迹又变成新关系'],sourceUrl:epaminonda,images:[],relations:[rel('奖项','Silver Lion for a Promising Young Participant — Venice Biennale 2019','jury cited constellations of images, objects, text, forms and colours'),rel('展览','May You Live In Interesting Times — Venice Biennale 2019','Central Pavilion / Arsenale')]}], awards:['Silver Lion — Venice Biennale 2019'], exhibitions:['May You Live In Interesting Times — Venice Biennale 2019'], sources:[{label:'La Biennale · Haris Epaminonda 2019',url:epaminonda},{label:'La Biennale · Official Awards 2019',url:awards}]
  },

  'venice-jesse-darling': {
    artistId:'venice-jesse-darling', projectCoverage:'1 个 non-macho / wounded-assemblage sculpture 方法节点已建立深档案 · 2010s–2019', imageCoverage:'0 / 1 项目暂不使用不稳定外链图像', note:'Darling 的低价材料、摇晃结构和受伤般身体感并非“poor material aesthetic”，而是对 monument、hard labour、heroic gesture 与 ableist machismo 的系统反写。',
    projects:[{title:'Non-macho wounded assemblages — Venice 2019 corpus',cluster:'low-cost material / unstable body / anti-monument',period:'2010s–2019',summary:'小型日常物件被收集并组成 wounded、skittish、unsteady 的 assemblages，既像受伤身体又坚持活着。neurological disease 限制右臂后，Darling 更明确放弃 macho sculpture 对力量与“大手势”的依赖。',actions:['收集 low-cost everyday materials 与 small objects','以 narrative formulation 组合而非追求 monumental single form','故意保留 bent / wounded / unstable structural condition','在右臂功能受限后学习用 left hand drawing 并改变制作方式','将 hard work / heroic gesture / monumentality 作为需要被拆解的 sculptural ideology','让脆弱结构承担 bodily poignancy，而不把 disability 变成说明性主题'],sourceUrl:darling,images:[],relations:[rel('展览','May You Live In Interesting Times — Venice Biennale 2019','Central Pavilion / Arsenale')]}], awards:[], exhibitions:['May You Live In Interesting Times — Venice Biennale 2019'], sources:[{label:'La Biennale · Jesse Darling 2019',url:darling}]
  }
};
