import type { ArtistArchive, ArchiveProject, ArchiveRelation } from './archiveData';
const rel=(kind:ArchiveRelation['kind'],label:string,detail?:string):ArchiveRelation=>({kind,label,detail});
const project=(p:ArchiveProject)=>p;

export const archiveBatch290:Record<string,ArtistArchive>={
'walid-raad':{
artistId:'walid-raad',
projectCoverage:'继续深化 Walid Raad：不增加新艺术家，重点把 The Atlas Group、Scratching on Things I Could Disavow、Walkthrough 与 Sweet Talk 串成“战争档案→艺术基础设施→表演/展陈→城市委托”的方法演变，并补机构、双年展、奖项网络。',
imageCoverage:'本批以 MoMA 与 Sfeir-Semler 官方页面交叉核对；官方页面有作品及安装图，但版权状态受限，因此不复制图像文件，只保存研究入口。',
note:'Raad 的关键不只是“虚构档案”。他从真实历史事实、真实档案研究和战争经验出发，制造可能存在的文献、人物与叙述，再用档案、讲座、展览设计和表演让观众进入一个事实层级不断滑动的系统。2007年后，他把同样的方法从黎巴嫩战争史扩展到阿拉伯世界新建的博物馆、双年展、艺博会、画廊与艺术资本基础设施。',
projects:[
project({title:'The Atlas Group — archive as an authored historical machine',cluster:'archive / Lebanon wars / fiction / photography / video / lecture',period:'1989–2004',summary:'The Atlas Group 是 Raad 持续十五年的核心项目，研究黎巴嫩当代史及1975–1990战争。MoMA 明确指出，他在真实事件与黎巴嫩及其他地区真实音频、电影、摄影档案研究基础上，生产 fictionalized photographs、videotapes、notebooks 与 lectures。Sfeir-Semler 则把它描述为一个会“locate, preserve, study and produce documents”的档案项目。关键因此不是把虚构与事实二分，而是模拟历史机构如何通过文献、归档、命名、作者身份和讲述方式制造可被相信的历史。',actions:['研究黎巴嫩战争相关真实事件及既有影音/摄影档案。','生产照片、录像、笔记本、雕塑与讲座等异质文献。','把部分材料归给虚构或历史人物，使作者身份本身成为档案结构的一部分。','以 The Atlas Group Archive 的名义保存、分类、展示材料，让艺术家同时扮演作者、研究者和档案管理员。','通过讲座与现场叙述不断改变文献被理解的方式。'],sourceUrl:'https://www.moma.org/calendar/exhibitions/1493',images:[],relations:[rel('机构','MoMA — Walid Raad, 2015–16','回顾展集中呈现 The Atlas Group 与 Scratching on things I could disavow，并强调 performance、narrative、storytelling。'),rel('画廊','Sfeir-Semler Gallery','官方艺术家档案把项目定义为1989–2004、研究黎巴嫩当代史的长期档案计划。'),rel('双年展','Documenta 11 / Venice Biennale / Whitney Biennial','艺术家官方履历记录 Documenta 11、13；2003 Venice Biennale；2000与2002 Whitney Biennial 等。'),rel('方法','fact → document → attribution → archive → narration','真实研究不是虚构的反面，而是虚构文献获得历史摩擦力的起点。')]}),
project({title:'Scratching on Things I Could Disavow — art infrastructure becomes the subject',cluster:'museum infrastructure / Arab art / geopolitics / market / installation',period:'2007–ongoing',summary:'2007年起，Raad 把研究范围从黎巴嫩战争扩大到阿拉伯世界现代与当代艺术基础设施。MoMA 将项目核心概括为：新出现的 art fairs、biennials、museums 与 galleries，如何与区域内地缘政治、经济和军事冲突同时发生。Sfeir-Semler 早期展览进一步显示，Raad 并非只评论这些机构，而是直接把艺术家名单、博物馆、展览结构和艺术流通系统当作作品的构成材料。项目因此研究“艺术史怎样被基础设施生产”。',actions:['追踪阿拉伯世界博物馆、双年展、艺博会、画廊等新基础设施。','把艺术家姓名、展览、收藏、建筑与制度语言转译成图像、物件、文本和空间结构。','把艺术市场与文化机构的增长和战争、资本及地缘政治放在同一研究框架。','继续使用事实与虚构交叠的叙述，使制度研究不能被简化成信息图或调查报道。'],sourceUrl:'https://www.moma.org/calendar/exhibitions/1493',images:[],relations:[rel('展览','Sfeir-Semler Hamburg — Scratching on Things I Could Disavow, 2009–10','早期项目展览；包含 Index XXVI: Artists 等章节。'),rel('机构','MoMA','2015–16展览把该项目与 The Atlas Group 并置，明确其艺术基础设施研究方向。'),rel('谱系','Lebanese war archive → Arab art infrastructure','研究对象从战争如何影响记忆，扩展到战争、资本和制度如何影响艺术本身。')]}),
project({title:'Walkthrough — research becomes a performed museum',cluster:'lecture-performance / museum floor / storytelling / spatial protocol',period:'2011–ongoing',summary:'Walkthrough 把 Scratching 的研究从墙上作品推进成55分钟 lecture-performance。MoMA 记录 Raad 为表演设计五个 platform stages，每个平台地面引用不同艺术空间的材质，从 contemporary gallery 的 poured concrete 到 Metropolitan Museum of Art 的 herringbone parquet。观众因此不是只听一场关于博物馆的讲座，而是在被压缩、重组的“机构地面”上观看艺术家讲述艺术基础设施、战争、文化与传统。展陈建筑本身成为论证的一部分。',actions:['把长期研究编辑成约55分钟现场讲述。','制作五个不同平台舞台，让不同艺术机构的地面语言进入表演。','在摄影、雕塑、文本之外使用身体、声音、时间与观众共同在场。','让同一材料在作品展示与艺术家口述之间来回切换，暴露博物馆叙事如何依赖展示协议。'],sourceUrl:'https://www.moma.org/calendar/events/1465',images:[],relations:[rel('表演','MoMA Marron Atrium','2015–16展期内多次现场演出；MoMA记录54场 past events。'),rel('机构引用','Metropolitan Museum of Art / contemporary gallery floors','五个平台地面复制/引用不同艺术空间的展示材质。'),rel('方法演变','archive → installation → lecture-performance','档案不再只是被观看，而是由艺术家在时间中重新执行。')]}),
project({title:'Sweet Talk: Commissions (Beirut) — the city as a recurring commission',cluster:'Beirut / urban image / commission / war / memory',period:'ongoing',summary:'Sweet Talk 是 Raad 与 The Atlas Group、Scratching 并列的另一长期项目。Sfeir-Semler 2024年资料把 Sweet Talk: Commissions (Beirut) 列为他持续处理战争及其可见/可说条件的三条长期线之一；早在2005年 Beirut Gallery 开幕展 FLIGHT 405 中，The Atlas Group / Walid Raad 已呈现新的 Sweet Talk 作品。近年的 Sweet Talk: Commissions (Beirut)_Solidere 1994–97 则使用多频道录像重新处理贝鲁特战后城市与重建语境。它把“委托”从一次性的客户任务变成持续回看城市、图像和战后重建的结构。',actions:['长期返回 Beirut 作为图像、城市史和委托关系的研究现场。','把既有城市影像与战后重建材料重新编排成摄影/录像作品。','使用 commissions 这一制度词汇，使谁要求图像、谁拥有城市叙述权成为作品问题。','与 The Atlas Group 的战争档案及 Scratching 的艺术制度研究形成城市尺度的第三条线。'],sourceUrl:'https://sfeir-semler.com/artists/artists/walid-raad',images:[],relations:[rel('展览','FLIGHT 405 — Sfeir-Semler Beirut, 2005','画廊开幕展记录 The Atlas Group / Walid Raad 呈现新的 Sweet Talk body of work。'),rel('作品','Sweet Talk: Commissions (Beirut)_Solidere 1994–97','艺术家官方页记录2019多频道录像版本，5分10秒循环。'),rel('城市机构','Solidere / postwar Beirut','作品标题直接把1994–97战后重建阶段纳入城市影像研究。')]}),
project({title:'Institution, biennial and award network — why Raad matters beyond “fictional archive”',cluster:'institution network / biennials / awards / historiography',period:'2000–present',summary:'Raad 的国际网络说明其影响横跨摄影、当代艺术、表演和中东艺术史，而不只是档案摄影。官方履历记录其个展机构包括 Louvre、MoMA、ICA Boston、Museo Jumex、Kunsthalle Zürich、Whitechapel 与 Hamburger Bahnhof；参与 Documenta 11/13、Venice Biennale、Whitney Biennial 2000/2002、São Paulo 与 Istanbul Biennial、Home Works Beirut。奖项包括 Hasselblad Award 2011、Deutsche Börse Photography Prize 2007、Guggenheim Fellowship 2009、ICP Infinity Award 2016 与 Aachener Kunstpreis 2018。收藏网络包括 MoMA、Guggenheim、British Museum、Tate Modern、Centre Pompidou 等。这个网络也对应他的媒介跨界：摄影机构认可其图像实践，而大型当代艺术机构同时接纳其档案、装置与表演方法。',actions:['把展览、双年展、奖项和收藏关系作为研究网络记录，而非仅列履历。','区分摄影制度认可、当代艺术双年展网络与博物馆收藏三种不同合法化机制。','用机构网络反向解释其作品为何能同时进入摄影史、档案艺术、表演和中东当代艺术讨论。'],sourceUrl:'https://sfeir-semler.com/artists/artists/walid-raad',images:[],relations:[rel('个展机构','Louvre / MoMA / ICA Boston / Museo Jumex / Kunsthalle Zürich / Whitechapel / Hamburger Bahnhof','Sfeir-Semler官方履历列出的重要个展机构。'),rel('双年展','Documenta 11 & 13 / Venice / Whitney / São Paulo / Istanbul / Home Works','构成其国际当代艺术与中东区域网络。'),rel('奖项','Hasselblad 2011 / Deutsche Börse 2007 / Guggenheim Fellowship 2009 / ICP Infinity 2016 / Aachener Kunstpreis 2018','显示其跨摄影、视觉艺术与研究型实践的认可。'),rel('收藏','MoMA / Guggenheim / British Museum / Tate Modern / Centre Pompidou','官方履历列出的主要公共收藏。')]})
],
awards:['Hasselblad Award — 2011','Deutsche Börse Photography Prize — 2007','John Simon Guggenheim Memorial Foundation Fellowship — 2009','ICP Infinity Award — 2016','Aachener Kunstpreis — 2018','Camera Austria Award — 2005','Alpert Award in Visual Arts — 2007'],
exhibitions:['Documenta 11 — Kassel — 2002','Whitney Biennial — New York — 2000, 2002','Venice Biennale — 2003','Walid Raad — MoMA — 2015–2016','Scratching on Things I Could Disavow — Sfeir-Semler Hamburg — 2009–2010','Another Festival of (In)gratitude — Sfeir-Semler Beirut — 2024–2025'],
sources:[{label:'MoMA — Walid Raad exhibition',url:'https://www.moma.org/calendar/exhibitions/1493'},{label:'MoMA — Walkthrough',url:'https://www.moma.org/calendar/events/1465'},{label:'Sfeir-Semler — Walid Raad profile',url:'https://sfeir-semler.com/artists/artists/walid-raad'},{label:'Sfeir-Semler — The Atlas Group',url:'https://sfeir-semler.com/artists/artists/the-atlas-group'},{label:'Sfeir-Semler — Scratching on Things I Could Disavow',url:'https://sfeir-semler.com/exhibitions/walid-raad-8932'},{label:'Sfeir-Semler — Another Festival of (In)gratitude',url:'https://sfeir-semler.com/exhibitions/walid-raad-another-festival-of-in-gratitude-10832'}]
}
};
