import type { ArtistArchive, ArchiveImage, ArchiveRelation } from './archiveData';

const img = (url: string, title: string, credit: string, sourceUrl: string, sourceLabel: string): ArchiveImage => ({ url, title, credit, sourceUrl, sourceLabel });
const rel = (kind: ArchiveRelation['kind'], label: string, detail?: string): ArchiveRelation => ({ kind, label, detail });

export const archiveBatch5: Record<string, ArtistArchive> = {
  'wolfgang-tillmans': {
    artistId: 'wolfgang-tillmans', projectCoverage: '5 个关键作品群 / 展览节点已完成第一轮 · 1986–2022', imageCoverage: '',
    note: 'Tillmans 的作品量极大，MoMA 当前即有大量在线作品。本轮先把“亲密/夜生活—墙面编排—无相机抽象—照片物质性—大型回顾”五条主线串起来，后续继续补 individual works。',
    projects: [
      { title: 'MoMA installation (1986–1998)', cluster: 'intimacy / nightlife / non-hierarchical display', period: '1986–1998 / installed 2012', summary: '多张 chromogenic prints 与 inkjet print 被作为完整安装收藏，青年文化、朋友、身体、日常物与政治图像不分等级地共处。', actions: ['拍摄朋友、夜生活、身体与日常场景', '跨尺寸输出', '无框粘贴与框装并置', '把墙面本身当作 sequence'], sourceUrl: 'https://www.moma.org/collection/works/162687', images: [img('https://www.crousel.com/media/uploads/artists/Wolfgang-Tillmans/exhibitions/Wolfgang-Tillm/web/Wolfgang-Tillmans-To-look-_vIYIu1h.jpg', 'Installation view / To look without fear', '© Wolfgang Tillmans', 'https://www.moma.org/calendar/exhibitions/5440', 'MoMA / exhibition documentation')], relations: [rel('收藏', 'MoMA', 'multi-part installation'), rel('展览', 'Wolfgang Tillmans: To look without fear', 'MoMA, 2022–2023')] },
      { title: 'paper drop', cluster: 'paper / still life / photographic object', period: '2001–', summary: '把相纸弯成弧面再拍摄，使纸张同时作为被摄物、图像载体和雕塑性对象出现。', actions: ['弯折 / 卷曲相纸', '工作室静物布置', '摄影', '把纸的边缘与反光保留为画面结构'], sourceUrl: 'https://www.moma.org/calendar/exhibitions/5440', images: [], relations: [] },
      { title: 'Freischwimmer', cluster: 'camera-less abstraction', period: '2000s–', summary: '在暗房中直接操控光与感光材料生成流动、烟雾般的抽象形态，不依赖外部被摄对象。', actions: ['无相机曝光', '暗房光源移动', '大尺幅输出'], sourceUrl: 'https://www.moma.org/collection/works/164471', images: [img('https://artblart.files.wordpress.com/2013/01/2004-freischwimmer_93-web.jpg?w=1300', 'Freischwimmer 93', '© Wolfgang Tillmans', 'https://www.moma.org/collection/works/164471', 'MoMA / secondary image documentation')], relations: [rel('收藏', 'MoMA', 'Freischwimmer work in collection')] },
      { title: 'Lighter', cluster: 'folded photographic surface', period: '2005–', summary: '感光纸在暗房中被折叠、压弯或以光模拟折叠，摄影表面本身变成立体对象。', actions: ['折叠感光纸', '暗房曝光', '透明亚克力框装', '让折痕和反光参与观看'], sourceUrl: 'https://press.moma.org/wp-content/uploads/2022/09/MoMA_Tilllmans_Exhibition-Brochure_FINAL.pdf', images: [], relations: [rel('展览', 'To look without fear', 'MoMA 2022')] },
      { title: 'To look without fear', cluster: 'survey / installation as editing', period: '2022–2023', summary: 'MoMA 回顾展把三十多年间的夜生活、肖像、政治、静物、天文图像、无相机抽象和视频重新放进一个连续的安装系统。', actions: ['跨年代重编作品', '墙面与房间级编辑', '不同尺寸 / 框装方式并置', '加入声音与视频'], sourceUrl: 'https://www.moma.org/calendar/exhibitions/5440', images: [], relations: [rel('展览', 'MoMA', '2022–2023'), rel('策展', 'Roxana Marcoci', 'MoMA Photography')] }
    ], awards: ['Turner Prize 2000 — winner'], exhibitions: ['Freedom from the Known — MoMA PS1 2006', 'To look without fear — MoMA 2022–2023'], sources: [{ label: 'MoMA artist archive', url: 'https://www.moma.org/artists/8044-wolfgang-tillmans' }, { label: 'MoMA — To look without fear', url: 'https://www.moma.org/calendar/exhibitions/5440' }]
  },
  'sophie-calle': {
    artistId: 'sophie-calle', projectCoverage: '5 个奠基性项目已完成第一轮 · 1980–2007', imageCoverage: '',
    note: 'Calle 的 oeuvre 横跨数十个规则型项目、书籍和展览。本轮先补最能说明她方法变化的五个核心项目，后续继续补 Blind、Ghosts、Rachel Monique、Because 等。',
    projects: [
      { title: 'Suite Vénitienne', cluster: 'following / rule-based performance', period: '1980', summary: '跟随一名陌生男子从巴黎到威尼斯，以伪装、尾随、笔记和摄影构成一套自定规则的行动。', actions: ['设定跟踪规则', '伪装', '街头摄影', '日记式文本记录'], sourceUrl: 'https://www.paulacoopergallery.com/artists/sophie-calle', images: [], relations: [rel('出版', 'Suite Vénitienne', 'artist book')] },
      { title: 'The Hotel', cluster: 'surveillance / traces / text-photo', period: '1981', summary: '在威尼斯酒店担任房务员，进入客房记录床铺、衣物、信件与私人物件，用照片和日记从“痕迹”想象陌生人的生活。', actions: ['进入客房', '拍摄私人物件与空间', '记录房客痕迹', '照片与日记并置'], sourceUrl: 'https://www.newyorker.com/books/under-review/sophie-calle-and-the-art-of-leaving-a-trace', images: [img('https://wahooart.com/media/artworks/images/full/e3/30/e3302a075bd0419296364fd721d83449.jpg', 'The Hotel, Room 47', '© Sophie Calle', 'https://www.newyorker.com/books/under-review/sophie-calle-and-the-art-of-leaving-a-trace', 'Project documentation')], relations: [rel('出版', 'The Hotel', 'Siglio edition 2021')] },
      { title: 'The Address Book', cluster: 'portrait through others / privacy', period: '1983', summary: '拾到一本通讯录后复印联系人信息，通过访问通讯录中的人来拼出通讯录主人的间接肖像。', actions: ['复制既有私人档案', '逐一访谈联系人', '把他人描述编辑成连续文本', '报刊连载 / 后出版'], sourceUrl: 'https://www.walkerart.org/collections/artwork/the-address-book/', images: [img('https://walker-col.imgix.net/wac_43774.tif?fit=fit&fm=jpg&h=1800&w=1800', 'The Address Book — artist book spread', '© Sophie Calle', 'https://www.walkerart.org/collections/artwork/the-address-book/', 'Walker Art Center')], relations: [rel('出版', 'Libération serial / The Address Book', '1983 / later book editions')] },
      { title: 'Exquisite Pain', cluster: 'breakup / repetition / embroidered text', period: '1984–2003', summary: '把一次失恋前后的旅行照片、倒计时与反复讲述的痛苦故事编排成双向叙事；随着重复，自己的痛苦逐渐缩短，他人的痛苦故事逐渐进入。', actions: ['旅行档案', '倒计时结构', '照片 + 刺绣文字', '收集他人痛苦故事', '重复讲述作为方法'], sourceUrl: 'https://www.paulacoopergallery.com/exhibitions/sophie-calle4', images: [img('https://static-assets.artlogic.net/w_1800%2Ch_1000%2Cc_limit/exhibit-e/5f5a43b313a837455d8b4567/da5236d2ba9b8b49d10398943b07abac.jpeg', 'Exquisite Pain (Day 5)', '© Sophie Calle', 'https://www.paulacoopergallery.com/exhibitions/sophie-calle4', 'Paula Cooper Gallery')], relations: [rel('出版', 'Douleur Exquise / Exquisite Pain', '2003–2004')] },
      { title: 'Take Care of Yourself', cluster: 'breakup email / delegated interpretation', period: '2007', summary: '把一封分手邮件交给 107 位不同职业的女性，从语言学、法律、舞蹈、歌唱、精神分析等角度回应，再把结果组织为摄影、文字与录像装置。', actions: ['把私人邮件转成规则', '委托 107 位女性回应', '摄影肖像', '录像表演', '大型空间编排'], sourceUrl: 'https://www.paulacoopergallery.com/exhibitions/take-care-of-yourself', images: [img('https://cdn.tatlerasia.com/tatlerasia/i/2024/02/11011439-e000061-014_cover_1600x698.jpg', 'Take Care of Yourself — installation', '© Sophie Calle', 'https://www.paulacoopergallery.com/exhibitions/take-care-of-yourself', 'Paula Cooper Gallery / exhibition documentation')], relations: [rel('展览', 'French Pavilion — Venice Biennale', '2007'), rel('出版', 'Take Care of Yourself', 'Actes Sud, 2007')] }
    ], awards: ['Hasselblad Award 2010'], exhibitions: ['French Pavilion — Venice Biennale 2007', 'Talking to Strangers — Whitechapel Gallery 2009'], sources: [{ label: 'Paula Cooper Gallery', url: 'https://www.paulacoopergallery.com/artists/sophie-calle' }, { label: 'Fraenkel Gallery CV', url: 'https://fraenkelgallery.com/wp-content/uploads/2015/10/Calle_CV_2024-4.pdf' }]
  },
  'hito-steyerl': {
    artistId: 'hito-steyerl', projectCoverage: '5 个核心影像 / 装置项目已完成第一轮 · 2013–2020', imageCoverage: '',
    note: '第一轮集中在 Steyerl 最能说明“图像政治—机器视觉—沉浸式空间—实时模拟”的五个节点；后续继续补 November、Liquidity Inc. 之后的研究和 Duty Free Art 等。',
    projects: [
      { title: 'How Not to Be Seen: A Fucking Didactic Educational .MOV File', cluster: 'resolution / visibility / machine vision', period: '2013', summary: '模仿教学视频和分辨率测试图，讨论在卫星、监控和数字图像系统中如何“消失”。', actions: ['教学视频结构', '绿幕', '分辨率测试图', 'found footage', '数字合成'], sourceUrl: 'https://www.pacegallery.com/hiding-in-plain-sight-hito-steyerl-1/', images: [img('https://www.pacegallery.com/media/images/897903keyUBiV5QfnSEM_ANkgPPBs6w.width-2000.jpg', 'How Not to Be Seen / Hiding in Plain Sight installation context', '© Hito Steyerl', 'https://www.pacegallery.com/hiding-in-plain-sight-hito-steyerl-1/', 'Pace Gallery')], relations: [] },
      { title: 'Liquidity Inc.', cluster: 'finance / weather / image circulation', period: '2014', summary: '金融危机、气象图、武术与流动性概念被剪辑成一套关于资本和图像流动的空间化 essay film。', actions: ['访谈', 'found footage', '数字动画', '沉浸式观看平台'], sourceUrl: 'https://www.hito-steyerl.de/', images: [], relations: [] },
      { title: 'Factory of the Sun', cluster: 'game space / labour / data', period: '2015', summary: '把游戏、YouTube舞蹈、无人机、劳工与虚构数据生产系统合成大型沉浸装置。', actions: ['视频游戏视觉语法', '舞蹈 / motion capture', 'found footage', '蓝色网格空间', '躺椅式观看'], sourceUrl: 'https://www.ngv.vic.gov.au/media_release/hito-steyerl-factory-of-the-sun/', images: [img('https://content.ngv.vic.gov.au/col-images/api/EXHI052764/1280', 'Factory of the Sun — installation', '© Hito Steyerl', 'https://www.ngv.vic.gov.au/media_release/hito-steyerl-factory-of-the-sun/', 'National Gallery of Victoria')], relations: [rel('展览', 'German Pavilion context — Venice Biennale', '2015')] },
      { title: 'Hell Yeah We Fuck Die', cluster: 'AI / robotics / disaster image', period: '2016', summary: '把流行歌曲中高频英文词、机器人测试影像和灾难 / 技术图像组织成关于机器身体与暴力的装置。', actions: ['文本统计 / 采样', '机器人测试影像', '多屏装置', '空间结构'], sourceUrl: 'https://www.hito-steyerl.de/', images: [], relations: [] },
      { title: 'SocialSim', cluster: 'simulation / police data / live computation', period: '2020', summary: '实时模拟与录像根据社会数据生成不断变化的群体动作，把统计、警察暴力和“社会模拟”做成镜面空间中的动态图像。', actions: ['实时计算模拟', '数据输入', '双空间投影', '反射地面', '角色动画'], sourceUrl: 'https://www.estherschipper.com/artists/102-hito-steyerl/works/24095-hito-steyerl-socialsim-2020/', images: [img('https://static-assets.artlogic.net/w_2000%2Ch_2000%2Cc_limit%2Cf_auto%2Cfl_lossy%2Cq_auto%3Abest/artlogicstorage/estherschipper/images/view/e1564bbd243c4be9bed928ad7dd93af3j.jpg', 'SocialSim', '© Hito Steyerl', 'https://www.estherschipper.com/artists/102-hito-steyerl/works/24095-hito-steyerl-socialsim-2020/', 'Esther Schipper')], relations: [] }
    ], awards: [], exhibitions: ['German Pavilion context — Venice Biennale 2015', 'Hiding in Plain Sight — Pace Gallery'], sources: [{ label: 'Pace Gallery', url: 'https://www.pacegallery.com/artists/hito-steyerl/' }, { label: 'Esther Schipper', url: 'https://www.estherschipper.com/artists/102-hito-steyerl/' }]
  },
  'thomas-demand': {
    artistId: 'thomas-demand', projectCoverage: '5 个关键模型 / 摄影 / 影像项目已完成第一轮 · 1997–2012', imageCoverage: '',
    note: 'Demand 的核心方法高度稳定：以媒体或记忆中的场所为起点，制作 1:1 纸模型，摄影 / 动画后销毁模型。本轮先补五个关键节点，后续继续扩展 oeuvre。',
    projects: [
      { title: 'Bathroom', cluster: 'model / media image / absence', period: '1997', summary: '根据公共媒介中的浴室图像重建一处近乎真实却没有可读细节的纸质空间，再拍摄成大尺幅照片。', actions: ['图像研究', '1:1纸与卡纸模型', '去除文字 / 细碎痕迹', '大尺幅摄影', '销毁模型'], sourceUrl: 'https://matthewmarks.com/artists/thomas-demand/lightbox/works/badezimmer-bathroom', images: [img('https://mmg.nyc3.cdn.digitaloceanspaces.com/online/badezimmer-bathroom/_1600x1600_fit_center-center_none/Demand_Badezimmer-Bathroom_1997.jpg', 'Badezimmer / Bathroom', '© Thomas Demand', 'https://matthewmarks.com/artists/thomas-demand/lightbox/works/badezimmer-bathroom', 'Matthew Marks Gallery')], relations: [] },
      { title: 'Poll', cluster: 'political image / reconstructed room', period: '2001', summary: '从美国总统选举计票相关媒介图像出发，把政治事件压缩为一个空无人物的纸模型空间。', actions: ['新闻图像搜集', '纸模型重建', '摄影', '删除人物'], sourceUrl: 'https://www.thomasdemand.info/', images: [], relations: [] },
      { title: 'Kitchen', cluster: 'news image / domestic reconstruction', period: '2004', summary: '根据媒体广泛传播的藏身处厨房图像进行纸模型重建，让“新闻证据”重新变成可疑的人工场景。', actions: ['媒体图像研究', '1:1纸模型', '灯光控制', '摄影'], sourceUrl: 'https://www.thomasdemand.info/', images: [], relations: [] },
      { title: 'Control Room', cluster: 'Fukushima / mediated memory', period: '2011', summary: '重建福岛第一核电站控制室图像，把一个高度政治化、灾难化的新闻空间转成无人、无可读信息的纸质模型。', actions: ['新闻图像取样', '纸板 / 彩纸模型', '删除可读文本', '大尺幅摄影'], sourceUrl: 'https://ocula.com/magazine/art-news/thomas-demand-to-build-house-of-card-at-moca/', images: [img('https://files.ocula.com/anzax/80/80b4c4c7-f114-45aa-b7e0-ba52347c57c3_720_720.jpg', 'Control Room', '© Thomas Demand', 'https://ocula.com/magazine/art-news/thomas-demand-to-build-house-of-card-at-moca/', 'Ocula')], relations: [] },
      { title: 'Pacific Sun', cluster: 'stop-motion / viral video / paper model', period: '2012', summary: '根据游轮遭遇风暴的监控视频搭建等比例纸质船舱，并用逐格移动数百件纸物件的方法重建其摇摆运动。', actions: ['分析网络监控视频', '制作 1:1 纸模型', '为数百物件编写运动脚本', '逐格动画', '销毁模型'], sourceUrl: 'https://collections.lacma.org/object/184289', images: [], relations: [rel('收藏', 'LACMA', 'single-channel video projection')] }
    ], awards: [], exhibitions: ['MoMA retrospective context', 'House of Card — MOCA Toronto'], sources: [{ label: 'Artist website', url: 'https://www.thomasdemand.info/' }, { label: 'LACMA — Pacific Sun', url: 'https://collections.lacma.org/object/184289' }]
  },
  'walead-beshty': {
    artistId: 'walead-beshty', projectCoverage: '4 个核心材料 / 物流项目已完成第一轮 · 2006–2015', imageCoverage: '',
    note: 'Beshty 的单件作品常以系列和运输记录扩张。本轮先覆盖机场 X-ray、折叠感光纸、FedEx 玻璃与大型制度化展示四条方法线。',
    projects: [
      { title: 'Travel Pictures', cluster: 'airport X-ray / film as travel record', period: '2006–2008', summary: '胶片随艺术家跨境旅行并反复经过机场 X-ray，安检设备造成的色带与损伤直接进入最终照片。', actions: ['携带未冲洗胶片跨境', '让机场X-ray重复作用于胶片', '冲洗放大', '把物流 / 安检变成曝光过程'], sourceUrl: 'https://www.actionstakenunderthefictitiousnamewaleadbeshtystudiosinc.com/', images: [], relations: [] },
      { title: 'Black and White Directional Folds', cluster: 'folding / photogram', period: '2006–2014', summary: '折叠大幅感光纸并从多个方向曝光，展开后折痕和不同角度的光形成几何结构。', actions: ['折叠感光纸', '多方向曝光', '展开', '保留折痕与光学梯度'], sourceUrl: 'https://www.actionstakenunderthefictitiousnamewaleadbeshtystudiosinc.com/black-and-white-directional-folds-2006-2014', images: [img('https://images.squarespace-cdn.com/content/v1/5614520ce4b0241f53ed4809/1462491876849-8JIX86S2NFQ3UHDW4WK3/WB23208.jpg?format=750w', 'Black and White Directional Folds', '© Walead Beshty', 'https://www.actionstakenunderthefictitiousnamewaleadbeshtystudiosinc.com/black-and-white-directional-folds-2006-2014', 'Artist studio archive')], relations: [] },
      { title: 'FedEx Glass Works', cluster: 'logistics / damage / sculpture', period: '2007–', summary: '把玻璃制作成标准 FedEx 箱体尺寸，在没有保护的情况下通过商业快递运输；每次裂纹、标签和运单都成为作品累积的一部分。', actions: ['按标准快递箱尺寸制作玻璃', '真实 FedEx 运输', '不隐藏运输损伤', '保留运单与标签', '重复运输累积痕迹'], sourceUrl: 'https://www.actionstakenunderthefictitiousnamewaleadbeshtystudiosinc.com/fedex-glass-works-2007', images: [img('https://images.squarespace-cdn.com/content/v1/5614520ce4b0241f53ed4809/1485213714037-TJZV945RWPAEVOEX5BKD/large-art1-shipped.jpg', 'FedEx Glass Works', '© Walead Beshty', 'https://www.actionstakenunderthefictitiousnamewaleadbeshtystudiosinc.com/fedex-glass-works-2007', 'Artist studio archive')], relations: [rel('展览', 'Whitney Biennial', '2008 context')] },
      { title: 'Great Hall Exhibition', cluster: 'production / labour / institutional display', period: '2015', summary: '大量摄影、玻璃、金属与运输痕迹在一个机构空间中同时出现，把制作、劳务和展览物流一起暴露。', actions: ['跨系列集中展示', '保留运输痕迹', '将生产与安装信息纳入作品阅读'], sourceUrl: 'https://www.actionstakenunderthefictitiousnamewaleadbeshtystudiosinc.com/', images: [], relations: [rel('展览', 'Great Hall Exhibition', '2015')] }
    ], awards: [], exhibitions: ['Whitney Biennial 2008', 'Venice Biennale 2015 context'], sources: [{ label: 'Walead Beshty Studios archive', url: 'https://www.actionstakenunderthefictitiousnamewaleadbeshtystudiosinc.com/' }]
  },
  'carmen-winant': {
    artistId: 'carmen-winant', projectCoverage: '4 个核心档案 / 墙面项目已完成第一轮 · 2018–2024', imageCoverage: '',
    note: 'Winant 的作品常由成千上万张 found images 与合作档案构成。本轮先补生育、女性主义档案、家暴幸存者与堕胎照护四个核心节点。',
    projects: [
      { title: 'My Birth', cluster: 'birth / found image / wall installation', period: '2018', summary: '数千张分娩、生产与照护相关既有照片用普通胶带密集覆盖通道墙面，把私人出生经验转成集体身体档案。', actions: ['收集 found photographs', '大规模编辑', '普通胶带直接上墙', '以数量制造集体经验'], sourceUrl: 'https://www.moma.org/collection/works/222741', images: [img('https://patrongallery.com/media/PatronGallery-13075-1749666079.jpg', 'My Birth — installation', '© Carmen Winant', 'https://patrongallery.com/press/item751/Carmen-Winants-Embodied-Archives', 'Patron Gallery / MoMA installation documentation')], relations: [rel('展览', 'Being: New Photography 2018 — MoMA', '2018')] },
      { title: 'Notes on Fundamental Joy', cluster: 'feminist / queer archive / publication', period: '2019', summary: '从女性主义与酷儿社群档案出发，以书籍和图像组合重新阅读身体、共同生活与自我表征。', actions: ['档案研究', 'found image editing', '摄影书 sequence', '文字编排'], sourceUrl: 'https://www.carmenwinant.com/', images: [], relations: [rel('出版', 'Notes on Fundamental Joy', 'Printed Matter, 2019')] },
      { title: 'A Brand New End: Survival and Its Pictures', cluster: 'domestic violence / collaborative archive', period: '2022', summary: '使用 Women In Transition 与 NCADV 档案和新制作材料，研究家暴幸存、女性自我表征与视觉证据如何被组织。', actions: ['机构档案合作', '照片与印刷品再编排', '公共介入', '研究展览'], sourceUrl: 'https://printcenter.org/a-brand-new-end/', images: [], relations: [rel('展览', 'The Print Center, Philadelphia', '2022')] },
      { title: 'The Last Safe Abortion', cluster: 'abortion care / clinic archive / wall installation', period: '2023–2024', summary: '从美国中西部与南部诊所、大学和地方档案收集约 2,500 张照片，并补充艺术家新拍图像，聚焦堕胎照护中日常而不戏剧化的劳动。', actions: ['跨诊所 / 档案馆收集照片', '与照护者建立许可关系', '2,500张商业尺寸照片编排', '整墙安装', '拒绝使用患者图像制造猎奇'], sourceUrl: 'https://whitney.org/media/59081', images: [img('https://news.artnet.com/app/news-upload/2023/09/230804_miaCONT_9496-2048x1189.jpeg', 'The Last Safe Abortion — installation', '© Carmen Winant / installation view', 'https://new.artsmia.org/press/installation-the-last-safe-abortion-by-carmen-winant-will-explore-the-work-of-womens-health-clinics-abortion-providers-in-the-midwest', 'Minneapolis Institute of Art / Artnet documentation')], relations: [rel('展览', 'Minneapolis Institute of Art', '2023'), rel('展览', 'Whitney Biennial', '2024')] }
    ], awards: ['Guggenheim Fellowship 2019'], exhibitions: ['Being: New Photography — MoMA 2018', 'A Brand New End — Print Center 2022', 'Whitney Biennial 2024'], sources: [{ label: 'Whitney — The Last Safe Abortion', url: 'https://whitney.org/media/59081' }, { label: 'The Print Center', url: 'https://printcenter.org/a-brand-new-end/' }]
  },
  'sara-cwynar': {
    artistId: 'sara-cwynar', projectCoverage: '6 个摄影 / 电影 / 出版节点已完成第一轮 · 2014–2021', imageCoverage: '',
    note: '本轮把 Cwynar 从“Tracy 一组照片”扩展为书籍、工作室物件、16mm 电影和多屏装置的连续方法线。',
    projects: [
      { title: 'Kitsch Encyclopedia', cluster: 'artist book / image taxonomy', period: '2014', summary: '以字母表和收集图像组织“kitsch”视觉材料，把设计师式分类、广告图像与摄影史做成书籍结构。', actions: ['搜集既有图像', '分类', '再设计 / 排版', '艺术家书出版'], sourceUrl: 'https://www.saracwynar.com/', images: [], relations: [rel('出版', 'Kitsch Encyclopedia', 'Blonde Art Books, 2014')] },
      { title: 'Soft Film', cluster: 'consumer objects / 16mm film', period: '2016', summary: '把 eBay 购买的过时消费品按颜色、材质和年代收集、摆放与拍摄，讨论商品价值如何循环。', actions: ['网络购买 / 收集', '工作室分类', '静物布置', '16mm拍摄', 'voice-over'], sourceUrl: 'https://iffr.com/en/person/sara-cwynar', images: [], relations: [] },
      { title: 'Rose Gold', cluster: 'color / technology / desire', period: '2017', summary: '以 Rose Gold iPhone 为中心，把颜色、商品、女性主义文本和技术欲望压进教育片式叙事。', actions: ['16mm电影', '文本引用', '商品图像采样', '声音叙事'], sourceUrl: 'https://iffr.com/en/person/sara-cwynar', images: [], relations: [] },
      { title: 'Tracy', cluster: 'rephotography / image layers', period: '2017–', summary: '透明板、复制图、商品和模特 Tracy Ma 在同一画面被层层重拍，摄影表面保留图像来源与再生产痕迹。', actions: ['工作室拼贴', '再摄影', '透明板叠层', '商品 / 旧图像并置'], sourceUrl: 'https://ago.ca/artist-residence-sara-cwynar', images: [img('https://ago.ca/sites/default/files/styles/max_2600x2600/public/2018-01/Tracy%28Cezanne%29-web.jpg?itok=lcaW02cU', 'Tracy (Cezanne)', '© Sara Cwynar', 'https://ago.ca/artist-residence-sara-cwynar', 'Art Gallery of Ontario')], relations: [] },
      { title: 'Red Film', cluster: 'capitalism / persuasion / montage', period: '2018', summary: '红色商品、女性身体、化妆品生产线和多重声音高速叠加，讨论消费文化如何塑造欲望与自我。', actions: ['16mm转视频', '广告 / 商品图像', '多声部文本', '蒙太奇'], sourceUrl: 'https://iffr.com/en/person/sara-cwynar', images: [], relations: [rel('展览', '33rd São Paulo Biennial', '2018')] },
      { title: 'Glass Life', cluster: 'multi-screen / image overload', period: '2021', summary: '六频道影像把广告、艺术史、自拍、政治、手机界面与艺术家私人图像档案做成高速但不断自我注释的视觉流。', actions: ['六频道视频', '个人数字档案', '网络图像', '多屏同步', '出版脚本注释'], sourceUrl: 'https://foxyproduction.com/exhibitions/sara-cwynar-2021-09-01/', images: [img('https://cdn.sanity.io/images/y7df71pe/production/027a13f342a7ec8688b2273bbba9cc3da07efe00-3500x2333.jpg', 'Glass Life — installation', '© Sara Cwynar', 'https://foxyproduction.com/exhibitions/sara-cwynar-2021-09-01/', 'Foxy Production')], relations: [rel('出版', 'Glass Life', 'Aperture, 2021')] }
    ], awards: [], exhibitions: ['Image Model Muse — Minneapolis Institute of Art 2018', '33rd São Paulo Biennial 2018', 'Glass Life — Foxy Production 2021'], sources: [{ label: 'Artist website', url: 'https://www.saracwynar.com/' }, { label: 'Aperture — Glass Life', url: 'https://store.aperture.org/products/sara-cwynar-glass-life' }]
  },
  'deana-lawson': {
    artistId: 'deana-lawson', projectCoverage: '5 个作品 / 展览节点已完成第一轮 · 2010–2022', imageCoverage: '',
    note: 'Lawson 很少把实践切成封闭“系列”，许多单件作品在不同展览中形成更大的宇宙。本轮因此按作品节点与重要展览群建立档案，而不是强行制造不存在的系列名。',
    projects: [
      { title: 'Roxie and Raquel, New Orleans, Louisiana', cluster: 'staged domestic portrait', period: '2010', summary: '两位女性在酒店 / 卧室式空间中以高度对称姿态坐在床上，家庭快照般的亲密感来自精确布置而非抓拍。', actions: ['寻找 / 邀请陌生人合作', '安排服装与姿势', '整理室内物件', '大画幅摄影'], sourceUrl: 'https://www.moma.org/collection/works/143022', images: [img('https://www.moma.org/media/W1siZiIsIjM4MjE3NSJdLFsicCIsImNvbnZlcnQiLCItcXVhbGl0eSA5MCAtcmVzaXplIDIwMDB4MjAwMFx1MDAzZSJdXQ.jpg?sha=f82146ceb1da01b4', 'Roxie and Raquel, New Orleans, Louisiana', '© Deana Lawson', 'https://www.moma.org/collection/works/143022', 'MoMA')], relations: [rel('收藏', 'MoMA', 'collection')] },
      { title: 'Sons of Cush / Ring Bearer', cluster: 'family image syntax / staged kinship', period: '2016', summary: '把陌生人组织成父子、家庭或照护关系，让家庭相册的视觉语法与黑人身体的公共刻板印象正面冲突。', actions: ['街头 casting', '家庭关系式编排', '大画幅摄影', '直视镜头'], sourceUrl: 'https://whitney.org/artists/17261', images: [], relations: [rel('展览', 'Whitney Biennial', '2017'), rel('收藏', 'Whitney — Sons of Cush', 'collection')] },
      { title: 'Planes', cluster: 'exhibition constellation / diaspora', period: '2018–2019', summary: '在 Underground Museum 展览中，跨地域肖像与室内图像共同构造黑人离散、身体和灵性之间的关系。', actions: ['跨作品重新编辑', '展览空间编排', '把个体肖像放进更大 diasporic constellation'], sourceUrl: 'https://www.davidkordanskygallery.com/public-exhibitions/deana-lawson5', images: [], relations: [rel('展览', 'The Underground Museum, Los Angeles', '2018–2019')] },
      { title: 'Centropy', cluster: 'photography / holography / spiritual cosmology', period: '2020–2021', summary: '大型摄影与全息图围绕 torus 形态组织，作品从家庭式肖像扩张到祖先史、黑人生态与物理学隐喻。', actions: ['大型摄影打印', '全息图', '密集墙面 constellation', '电影', '档案与访谈'], sourceUrl: 'https://www.guggenheim.org/exhibition/the-hugo-boss-prize-2020-deana-lawson', images: [img('https://images.squarespace-cdn.com/content/v1/5702ab9d746fb9634796c9f9/1621267802664-GLY6MDGBA0FRNU8B0F2U/gen-press-hugo-boss-prize-2020-chief.jpg?format=2500w', 'Chief', '© Deana Lawson', 'https://www.guggenheim.org/exhibition/the-hugo-boss-prize-2020-deana-lawson', 'Guggenheim / exhibition documentation'), img('https://news.artnet.com/app/news-upload/2021/05/gen-press-hugo-boss-prize-2020-barrington-and-father-804x1024.jpg', 'Barrington and Father', '© Deana Lawson', 'https://www.guggenheim.org/exhibition/the-hugo-boss-prize-2020-deana-lawson', 'Guggenheim / Artnet documentation')], relations: [rel('奖项', 'Hugo Boss Prize', 'winner 2020'), rel('展览', 'Guggenheim Museum', '2021')] },
      { title: 'Deana Lawson — survey', cluster: 'museum survey / long-term practice', period: '2021–2022', summary: 'ICA Boston 与 MoMA PS1 的 survey 将长期摄影放在同一时间线上，让编排、灵性、家庭语法与黑人自我表征被作为持续方法观看。', actions: ['长期作品再编辑', 'museum-scale installation', '跨年代并置'], sourceUrl: 'https://warholfoundation.org/grants/archive/deana-lawson/', images: [], relations: [rel('展览', 'ICA Boston', '2021–2022'), rel('展览', 'MoMA PS1', '2022')] }
    ], awards: ['Hugo Boss Prize 2020 — winner', 'Guggenheim Fellowship 2013'], exhibitions: ['Whitney Biennial 2017', 'Planes — Underground Museum 2018–19', 'Centropy — Guggenheim 2021', 'ICA Boston / MoMA PS1 survey 2021–22'], sources: [{ label: 'Guggenheim — Centropy', url: 'https://www.guggenheim.org/exhibition/the-hugo-boss-prize-2020-deana-lawson' }, { label: 'Whitney artist archive', url: 'https://whitney.org/artists/17261' }]
  },
  'zanele-muholi': {
    artistId: 'zanele-muholi', projectCoverage: '5 个核心长期项目已完成第一轮 · 2002–现在', imageCoverage: '',
    note: 'Muholi 的实践是持续扩张的 living archive。本轮先覆盖早期亲密与暴力记录、Faces and Phases、Being、Brave Beauties、Somnyama Ngonyama 五条主线。',
    projects: [
      { title: 'Only Half the Picture', cluster: 'early visual activism / intimacy and violence', period: '2002–2006', summary: '早期项目把黑人酷儿亲密生活、身体与针对 LGBTQIA+ 社群的暴力现实并置，不让“受害”成为唯一视觉身份。', actions: ['社区长期拍摄', '亲密肖像', '社会暴力记录', '黑白摄影'], sourceUrl: 'https://www.tate.org.uk/whats-on/tate-modern/zanele-muholi', images: [], relations: [] },
      { title: 'Faces and Phases', cluster: 'living queer archive', period: '2006–', summary: '以相对稳定的黑白肖像格式持续拍摄黑人女同性恋、跨性别、非二元与酷儿参与者，形成不断增长的共同体档案。', actions: ['长期回访', '参与者命名与自我呈现', '统一肖像格式', '大型网格安装'], sourceUrl: 'https://www.muholiart.institute/gallery/facesandphases', images: [img('https://cdn.sanity.io/images/33elzic6/production/4e332b20bc9495d84609699f4b8183233c69f2b7-4480x2524.jpg?auto=format&q=100&w=1920', 'Faces and Phases 19 — installation', '© Zanele Muholi', 'https://southernguild.com/exhibitions/faces-and-phases-19', 'Southern Guild')], relations: [rel('展览', 'Faces and Phases 19 — Southern Guild', '2025')] },
      { title: 'Being', cluster: 'queer intimacy / domestic life', period: '2006–2011', summary: '把伴侣关系、裸体、拥抱和日常空间作为黑人酷儿生活的普通组成部分，而不是只在抗争或暴力框架中出现。', actions: ['亲密关系摄影', '居家空间', '合作肖像'], sourceUrl: 'https://www.tate.org.uk/whats-on/tate-modern/zanele-muholi', images: [], relations: [] },
      { title: 'Brave Beauties', cluster: 'beauty pageant / trans visibility', period: '2014–', summary: '与跨性别女性和 gender non-conforming 参与者合作，以姿态、服装与选美文化处理美、尊严和自我定义。', actions: ['合作肖像', '服装 / pose', '社群长期关系'], sourceUrl: 'https://www.tate.org.uk/whats-on/tate-modern/zanele-muholi', images: [], relations: [] },
      { title: 'Somnyama Ngonyama', cluster: 'self-portrait / colonial visual codes', period: '2012–', summary: 'Muholi 亲自进入镜头，把清洁用品、工业材料、劳动工具等日常物件转成头饰和服装，并在后期强化肤色反差，反向控制黑人身体的观看方式。', actions: ['自我表演', '日常物件造型', '黑白摄影', '强化 tonal contrast', '逐地点回应历史语境'], sourceUrl: 'https://www.tate.org.uk/whats-on/tate-modern/zanele-muholi', images: [img('https://image-cdn.hypb.st/https%3A/hypebeast.com/wp-content/blogs.dir/20/files/2024/05/zanele-muholi-tate-modern-2024-survey-5.jpg?cbr=1&q=90', 'Somnyama Ngonyama — self-portrait', '© Zanele Muholi', 'https://www.tate.org.uk/whats-on/tate-modern/zanele-muholi', 'Tate survey / Hypeart documentation'), img('https://fadmagazine.com/wp-content/uploads/Zanele-Muholi-at-Tate-Modern-Installation-view-Photo-Mark-Westall-2-800x600.jpg', 'Zanele Muholi — Tate Modern installation', '© Zanele Muholi / photo Mark Westall', 'https://www.tate.org.uk/whats-on/tate-modern/zanele-muholi', 'Tate / installation documentation')], relations: [rel('展览', 'Tate Modern survey', '2020 / 2024')] }
    ], awards: [], exhibitions: ['Tate Modern major survey 2020 / 2024', 'Faces and Phases 19 — Southern Guild 2025'], sources: [{ label: 'Tate Modern', url: 'https://www.tate.org.uk/whats-on/tate-modern/zanele-muholi' }, { label: 'Muholi Art Institute — Faces and Phases', url: 'https://www.muholiart.institute/gallery/facesandphases' }]
  },
  'dayanita-singh': {
    artistId: 'dayanita-singh', projectCoverage: '6 个摄影书 / 档案 / 移动博物馆节点已完成第一轮 · 1986–2023', imageCoverage: '',
    note: 'Singh 的作品不能只按“系列照片”理解。本轮把摄影书、档案房间、移动博物馆和回顾展连成一条“照片如何被编辑、携带与重新展出”的时间线。',
    projects: [
      { title: 'Zakir Hussain', cluster: 'early photobook / portrait', period: '1986', summary: '早期围绕 tabla 演奏家 Zakir Hussain 的项目以书的形式确立了摄影、编辑和出版之间的关系。', actions: ['长期跟拍', '肖像', '编辑 sequence', '摄影书出版'], sourceUrl: 'https://dayanitasingh.in/about/', images: [], relations: [rel('出版', 'Zakir Hussain', '1986')] },
      { title: 'Myself Mona Ahmed', cluster: 'long-term relationship / book', period: '1989–2001', summary: '与 Mona Ahmed 的长期关系从摄影逐渐变成书信、文字与共同生活记录，挑战传统“摄影师—被摄者”单向关系。', actions: ['长期关系式拍摄', '肖像', '书信 / 文本', '摄影书编辑'], sourceUrl: 'https://dayanitasingh.in/about/', images: [], relations: [rel('出版', 'Myself Mona Ahmed', '2001')] },
      { title: 'Sent a Letter', cluster: 'accordion books / portable exhibition', period: '2008', summary: '以一组小型 accordion books 把旅行中的摄影编辑成可展开、可携带的“展览”，为后来 Museum Bhavan 的书—空间关系奠基。', actions: ['旅行摄影', '小型序列编辑', 'accordion book', '把书当成可展开展览'], sourceUrl: 'https://dayanitasingh.in/about/', images: [], relations: [rel('出版', 'Sent a Letter', '2008')] },
      { title: 'File Room', cluster: 'archive rooms / institutional memory', period: '2012–2013', summary: '持续拍摄印度不同档案室、文件柜和纸张堆积，把行政档案的物理空间转成关于知识、遗忘和保存的视觉结构。', actions: ['进入档案空间', '黑白摄影', '重复空间类型', '编辑成书与展览'], sourceUrl: 'https://dayanitasingh.in/about/', images: [], relations: [rel('出版', 'File Room', '2013')] },
      { title: 'Museum of Chance / Museum Bhavan', cluster: 'mobile museum / photo-architecture', period: '2013–', summary: '手工木制可折叠结构内部存放大量照片，每次展览都能改变打开方式、图片组合与空间路径；博物馆本身是不断重编的作品。', actions: ['设计木制模块', '从自身档案重新选片', '不断重排照片', '把储藏与展示合一', '让观众绕行 / 进入结构'], sourceUrl: 'https://dayanitasingh.in/museums/museum-bhavan/', images: [img('https://artlogic-res.cloudinary.com/w_2400%2Ch_2400%2Cc_limit%2Cf_auto%2Cfl_lossy%2Cq_auto/artlogicstorage/frithstreetgallery/images/view/9745bba7d108388d2f13db5dc148c611j/frithstreetgallery-dayanita-singh-museum-of-chance-2013.jpg', 'Museum of Chance', '© Dayanita Singh', 'https://www.frithstreetgallery.com/artworks/8645-dayanita-singh-museum-of-chance-2013/', 'Frith Street Gallery'), img('https://assets.gqindia.com/photos/5cdc2db7700a77e493aa17db/master/w_1024%2Cc_limit/GQ-India-musuem-bhavan-dayanti-singh.jpg', 'Museum Bhavan', '© Dayanita Singh', 'https://dayanitasingh.in/museums/museum-bhavan/', 'Artist website / exhibition documentation')], relations: [rel('展览', 'Hayward Gallery', '2013'), rel('展览', 'Art Institute of Chicago', '2014'), rel('出版', 'Museum Bhavan', 'Steidl, 2017')] },
      { title: 'Dancing with my Camera', cluster: 'survey / archive in motion', period: '2022–2023', summary: '大型巡回展把早期摄影书、档案系列、移动博物馆和新结构放到一起，强调她不是把照片固定下来，而是让档案持续被重新编辑。', actions: ['跨年代重编', '书籍与装置并置', '移动博物馆重新配置'], sourceUrl: 'https://dayanitasingh.in/about/', images: [], relations: [rel('展览', 'Gropius Bau', '2022'), rel('展览', 'MUDAM / Serralves', '2023')] }
    ], awards: ['Hasselblad Award 2022'], exhibitions: ['Go Away Closer — Hayward Gallery 2013', 'Museum Bhavan — Tokyo Photographic Art Museum 2017', 'Dancing with my Camera — Gropius Bau / MUDAM / Serralves 2022–23'], sources: [{ label: 'Dayanita Singh — official archive', url: 'https://dayanitasingh.in/about/' }, { label: 'Museum Bhavan', url: 'https://dayanitasingh.in/museums/museum-bhavan/' }]
  }
};
