import type { ArtistArchive, ArchiveRelation } from './archiveData';
const rel=(kind:ArchiveRelation['kind'],label:string,detail?:string):ArchiveRelation=>({kind,label,detail});
const jamie='https://www.labiennale.org/en/art/2019/partecipants/cameron-jamie';
const hernandez='https://www.labiennale.org/en/art/2019/partecipants/anthony-hernandez';
const yin='https://www.labiennale.org/en/art/2019/partecipants/yin-xiuzhen';
const gill='https://www.labiennale.org/en/art/2019/partecipants/gauri-gill';
const yu='https://www.labiennale.org/en/art/2019/partecipants/yu-ji';
const singer='https://www.labiennale.org/en/art/2019/partecipants/avery-singer';
const singerAsac='https://asac.labiennale.org/persone/500097';
export const archiveBatch113:Record<string,ArtistArchive>={
'venice-cameron-jamie':{artistId:'venice-cameron-jamie',projectCoverage:'1 个 ritual-violence ethnographic-video 核心节点已建立深档案 · 2002–2003',imageCoverage:'0 / 1 项目暂不使用不稳定外链图像',note:'这是对 batch 109 中错误 key 的覆盖修正。Jamie 横跨 photo/video/drawing/ceramic/zine，但这里先把官方重点作品 Kranky Klaus 做深：他不解释 Krampuslauf，而让 culturally sanctioned violence 在夜间 ritual 中自己显形。',projects:[{title:'Kranky Klaus',cluster:'Krampuslauf / documentary video / choreographed-real violence',period:'2002–2003',summary:'影片记录奥地利乡村 Christmas Krampuslauf：男性穿 horned-beast costume 夜间巡游并殴打被认定 naughty 的儿童和年轻女性，violence 同时被 ritual choreography 和真实身体冲击组织。',actions:['进入 rural Austrian village 跟随真实 Krampuslauf','在夜间环境中记录 costumed participants 与 victims','保留 ritual choreography 与 apparently real assault 的矛盾','不把民俗处理成 quaint tradition，而让 sanctioned violence 直接成为影像结构','以 observational video 而非 staged reenactment 建立观看张力'],sourceUrl:jamie,images:[],relations:[rel('展览','May You Live In Interesting Times — Venice Biennale 2019','Central Pavilion / Arsenale')]}],awards:[],exhibitions:['May You Live In Interesting Times — Venice Biennale 2019'],sources:[{label:'La Biennale · Cameron Jamie 2019',url:jamie}]},
'veice-anthony-hernandez':{artistId:'venice-anthony-hernandez',projectCoverage:'1 个 urban-defeat / unsentimental landscape corpus 已建立深档案 · c.1980s–2019',imageCoverage:'0 / 1 项目暂不使用不稳定外链图像',note:'Hernandez 三十多年持续追问如何拍摄城市当代废墟以及 urban life 对资源更少者的冲击；他的照片拒绝浪漫化 homelessness / neglect，也拒绝 nostalgic ruin aesthetic。',projects:[{title:'Landscapes of the defeated',cluster:'urban periphery / homeless camp / unemployment office / neglected space',period:'c.1980s–2019',summary:'homeless camps、unemployment offices、auto-wrecking yards、bus shelters 与城市边缘被当成 capitalism promise 失效后的空间证据。',actions:['长期步行/观察 Los Angeles 等城市边缘和被忽略空间','把 homeless camp、job office、wrecking yard、bus shelter 等纳入同一 urban landscape vocabulary','保持 hard / unsentimental framing，避免 picturesque ruin','不以人物苦难特写替代社会空间分析','通过 repeated typology 追踪 capitalism happiness promise 如何在空间上“变酸”'],sourceUrl:hernandez,images:[],relations:[rel('展览','May You Live In Interesting Times — Venice Biennale 2019','Central Pavilion / Arsenale')]}],awards:[],exhibitions:['May You Live In Interesting Times — Venice Biennale 2019'],sources:[{label:'La Biennale · Anthony Hernandez 2019',url:hernandez}]},
'veice-yin-xiuzhen':{artistId:'venice-yin-xiuzhen',projectCoverage:'1 个 recycled-textile / post-1989 consumption corpus 已建立深档案 · early 1990s–2019',imageCoverage:'0 / 1 项目暂不使用不稳定外链图像',note:'Yin Xiuzhen 从 1990s 起持续使用 recycled materials，把 post-1989 China 的 development、consumption、globalisation 压进旧 textile 与 suitcase、concrete、debris、metal、industrial object 的质感冲突。',projects:[{title:'Recycled-material social sculpture corpus',cluster:'used textile / suitcase-concrete-debris / consumption-globalisation',period:'early 1990s–2019',summary:'soft textile 与 suitcase、concrete fragment、debris、metal、industrial object 被组装成 ambitious sculpture；材料自身既带身体记忆，也带 rapid urbanisation 的残余。',actions:['持续回收 used textile / clothing 作为柔软身体性材料','并置 suitcase、concrete fragment、debris、metal、industrial object 等硬质城市材料','保留 radically contrasting textures 而不统一 finish','将 personal-use trace 与 mass development / consumption 关联','以 assemblage / large-scale sculpture 让 globalisation 从抽象概念变成可触物质冲突'],sourceUrl:yin,images:[],relations:[rel('展览','May You Live In Interesting Times — Venice Biennale 2019','Central Pavilion / Arsenale')]}],awards:[],exhibitions:['May You Live In Interesting Times — Venice Biennale 2019'],sources:[{label:'La Biennale · Yin Xiuzhen 2019',url:yin}]},
'veice-gauri-gill':{artistId:'venice-gauri-gill',projectCoverage:'1 个 suburban-architecture / development-fantasy photography 系列已建立深档案 · 2010s–2019',imageCoverage:'0 / 1 项目暂不使用不稳定外链图像',note:'Gill 在 Venice 2019 的重点是 Deadpan：她把城市扩张边缘的新“colonies”当作建筑荒诞剧拍摄，development advertising、migrant labour、fake nature 与 demolition 同时存在。',projects:[{title:'Deadpan',cluster:'suburban colony / developer hoarding / fake architecture / migrant-labour periphery',period:'2010s–2019',summary:'系列包括 developers hoardings 兜售不可企及的理想生活、仿 English castle、migrant labour makeshift homes、fake palms、aircon 上方 goddess、被塑料布覆盖且正遭 demolition 的新楼，以及公路旁腐烂垃圾与 featureless high-rises。',actions:['远离既有村庄项目，转向 new suburban colonies / wasteland fringe','拍摄 developer hoarding 与 real built environment 的落差','把 imitation architecture、fake palm 与 real tree 同画面比较','记录 migrant labourers makeshift housing 与 luxury-development fantasy 的邻接','用 deadpan frontal observation 抑制讽刺说明，让荒谬关系自行显现','将 construction / demolition / rubbish 同时纳入“发展”图像'],sourceUrl:gill,images:[],relations:[rel('展览','May You Live In Interesting Times — Venice Biennale 2019','Central Pavilion / Arsenale')]}],awards:[],exhibitions:['May You Live In Interesting Times — Venice Biennale 2019'],sources:[{label:'La Biennale · Gauri Gill 2019',url:gill}]},
'veice-yu-ji':{artistId:'venice-yu-ji',projectCoverage:'1 个 site-dialogue / second-hand-building-material sculpture 方法节点已建立深档案 · 2010s–2019',imageCoverage:'0 / 1 项目暂不使用不稳定外链图像',note:'Yu Ji 虽跨 installation / performance 并运营 Shanghai experimental art space，但 sculpting process 始终居中；她先“走出去看”，再让 site、second-hand building material 与 physical labour 决定作品。',projects:[{title:'Second-hand material / site-dialogue sculpture corpus',cluster:'building salvage / bodily fragment / physical labour / minimal material',period:'2010s–2019',summary:'Yu Ji 常用来自建筑的 second-hand material，以很少材料把 time、space、movement 这些 immaterial condition 压成实体；结果常像 body fragment / abstraction，并保留制作劳动的痕迹。',actions:['不在 studio 内预先封闭完成作品，而先进入具体 site 观察','优先使用 second-hand materials，尤其 building salvage','把现场观察理解为 dialogue，而非只做 location research','以 minimal material 将 time / space / movement 物质化','在 sculpture 中保留 cutting、casting、lifting 等 physical labour traces','让 body fragment / abstraction 从材料过程产生，而不是先画概念图再照做'],sourceUrl:yu,images:[],relations:[rel('展览','May You Live In Interesting Times — Venice Biennale 2019','Central Pavilion / Arsenale')]}],awards:[],exhibitions:['May You Live In Interesting Times — Venice Biennale 2019'],sources:[{label:'La Biennale · Yu Ji 2019',url:yu}]},
'veice-avery-singer':{artistId:'venice-avery-singer',projectCoverage:'2 个 3D-model-to-airbrush / gender-neutral geometry 节点已建立深档案 · 2017–2019',imageCoverage:'0 / 2 项目暂不使用不稳定外链图像',note:'Singer 不用传统 brush 起稿，而先在 SketchUp 中构造 3D composition，再投影到 canvas 并 airbrush；2017–19 又从 grisaille 引入 candy colour，同时用 gender-neutral face / non-sexualised shape 抵抗对艺术家性别的简化期待。',projects:[{title:'SketchUp → projection → airbrush painting system',cluster:'3D modelling / projected composition / airbrush on canvas',period:'2010s–2019',summary:'architect / engineer 常用的 SketchUp 被拿来建立 digital composition，再投影到 canvas 上并 airbrush，painting 的空间与光线先在虚拟模型里生成。',actions:['使用 SketchUp 建立 3D scene / geometric figure','从 digital model 选择 camera / perspective','将 composition 投影到 canvas','以 airbrush 而非 brush rendering projected form','利用线、grid、geometry 保留 computer-modelled surface 感'],sourceUrl:singer,images:[],relations:[]},{title:'Calder (Saturday Night) + gender-ambiguous portrait group',cluster:'candy colour / grisaille contrast / gender-neutral visage',period:'2017–2019',summary:'Arsenale 的 Calder (Saturday Night) 与彩色 paintings 对照 Central Pavilion 的 muted semi-abstract works；gender-neutral visages 与 non-sexualised shapes 被压成 line/grid/geometric forms。',actions:['在原有 grisaille palette 中逐步加入 candy colour','让同一 digital-airbrush method 在 colour / muted group 中形成 venue contrast','减少 sexualised anatomical cue','把 facial feature 转译为 line、grid、geometric shape','用 identity ambiguity 抵抗 gender-based interpretation of authorship'],sourceUrl:singerAsac,images:[],relations:[rel('展览','May You Live In Interesting Times — Venice Biennale 2019','Calder (Saturday Night), Self-portrait and related works')]}],awards:[],exhibitions:['May You Live In Interesting Times — Venice Biennale 2019'],sources:[{label:'La Biennale · Avery Singer 2019',url:singer},{label:'ASAC · Avery Singer 2019 works',url:singerAsac}]}
};
