import type { ArtistArchive, ArchiveProject, ArchiveRelation } from './archiveData';
const rel=(kind:ArchiveRelation['kind'],label:string,detail?:string):ArchiveRelation=>({kind,label,detail});
const p=(x:ArchiveProject)=>x;
export const archiveBatch324:Record<string,ArtistArchive>={
'taryn-simon':{artistId:'taryn-simon',projectCoverage:'深化 Image Atlas、Black Square、The Conversation Machine。',imageCoverage:'使用艺术家官网与机构入口，不复制未确认授权图像。',note:'Simon持续把分类、搜索、档案与对话系统本身变成作品。',projects:[
p({title:'Image Atlas',cluster:'search engine / algorithmic geography',period:'2012',summary:'Simon与Aaron Swartz建立Image Atlas，将同一搜索词在不同国家本地搜索引擎中的顶部图像并置比较。官网记录覆盖57个国家，并可按GDP或字母排序。',actions:['建立跨地域搜索系统','抓取各地顶部图像','按国家比较和排序','暴露算法与文化差异'],sourceUrl:'https://tarynsimon.com/works/image_atlas/',images:[],relations:[rel('策展','Aaron Swartz / Taryn Simon','共同创作者')]}),
p({title:'Black Square',cluster:'collection / classification / art history',period:'2006–',summary:'持续项目：在一个尺寸严格等同Malevich 1915年Black Square的黑色区域内收集物件、文件与人物。固定尺度成为长期档案的分类协议。',actions:['复制Malevich作品的精确尺寸协议','持续收集异质对象','以固定边界建立分类关系','通过不同展览重新编排档案'],sourceUrl:'https://tarynsimon.com/works/black_square/',images:[],relations:[rel('展览','Albertinum Dresden','艺术家官网安装档案'),rel('展览','Garage Museum Moscow','艺术家官网安装档案')]}),
p({title:'The Conversation Machine',cluster:'neuroscience / philosophy / multi-screen',period:'2022',summary:'为Fondazione Prada制作的32屏系统，组织五大洲神经科学家、心理学家、神经语言学家与哲学家的访谈，讨论神经科学实验及其哲学和伦理问题。',actions:['邀请跨学科研究者','拍摄与编辑访谈','编排32屏同步系统','让不同学科语言并置'],sourceUrl:'https://tarynsimon.com/works/cm/',images:[],relations:[rel('机构','Fondazione Prada','制作/展览语境')]}),
],awards:[],exhibitions:['Image Atlas — C/O Berlin','Black Square — Albertinum Dresden / Garage Moscow','The Conversation Machine — Fondazione Prada'],sources:[{label:'Taryn Simon — Image Atlas',url:'https://tarynsimon.com/works/image_atlas/'},{label:'Taryn Simon — Black Square',url:'https://tarynsimon.com/works/black_square/'},{label:'Taryn Simon — The Conversation Machine',url:'https://tarynsimon.com/works/cm/'}]},
'walid-raad':{artistId:'walid-raad',projectCoverage:'深化 My neck is thinner than a hair: Engines 与 The Atlas Group 档案协议。',imageCoverage:'使用MoMA作品与安装入口，不复制未确认授权图像。',note:'Raad通过真实照片、虚构机构、档案分类与展览制度叠加，挑战照片作为透明证据的默认地位。',projects:[
p({title:'My neck is thinner than a hair: Engines',cluster:'war archive / found photography / evidence',period:'1996–2004',summary:'MoMA记录100张喷墨照片，来自黎巴嫩报纸档案，拍摄汽车炸弹爆炸后被抛出的发动机。Raad扫描照片正背面并加入日期、摄影者和背面注记翻译；发动机看似证据黑匣子，却通常无法真正追溯肇事者。',actions:['从黎巴嫩报纸档案寻找照片','扫描正面与背面','记录日期与摄影者','建立100件序列','重新编排新闻摄影的证据姿态'],sourceUrl:'https://www.moma.org/collection/works/91530',images:[],relations:[rel('收藏','MoMA','100 inkjet prints；24 × 34 cm'),rel('展览','Walid Raad — MoMA','2015–2016'),rel('档案','The Atlas Group','研究黎巴嫩战争的虚构档案机构')]}),
p({title:'The Atlas Group archive protocol',cluster:'fictional institution / metadata / authorship',period:'1989–2004',summary:'The Atlas Group以研究黎巴嫩1975–1991战争为名建立虚构档案。MoMA记录文件分为Type A、Type FD、Type AGP，使作者身份、来源与机构认证成为作品内部的技术问题。',actions:['建立虚构研究机构','规定文件归属类型','并置found与fabricated documents','通过展览与录像呈现档案'],sourceUrl:'https://www.moma.org/artists/35285-walid-raad',images:[],relations:[rel('机构','MoMA','收藏与展览网络'),rel('方法关系','found document ↔ fabricated document','共同质询历史真实性')]}),
],awards:[],exhibitions:['Walid Raad — MoMA — 2015–2016','Signals — MoMA — 2023'],sources:[{label:'MoMA — Engines',url:'https://www.moma.org/collection/works/91530'},{label:'MoMA — Walid Raad',url:'https://www.moma.org/artists/35285-walid-raad'},{label:'MoMA — Atlas Group selected works',url:'https://www.moma.org/slideshows/1/30'}]},
'laia-abril':{artistId:'laia-abril',projectCoverage:'补充新闻学、FABRICA/Colors与研究型摄影方法，并深化On Rape的方法对话。',imageCoverage:'使用艺术家官网与Foam入口，不复制未确认授权图像。',note:'Abril把新闻调查、档案、证词、物件、概念肖像、声音与摄影书组织成跨媒介证据系统。',projects:[
p({title:'Research-to-evidence method',cluster:'journalism / editorial / research',period:'2009–present',summary:'艺术家官网记录Abril受新闻学训练，2009–2014年在FABRICA驻留并作为研究者、编辑和COLORS摄影师工作；The Epilogue在此阶段形成。',actions:['建立调查问题','采访与收集档案','在FABRICA进行研究与编辑','把材料转译成摄影、文字、视频和声音'],sourceUrl:'https://www.laiaabril.com/about/long-bio/',images:[],relations:[rel('机构','FABRICA / COLORS Magazine','2009–2014'),rel('出版','The Epilogue','2014')]}),
p({title:'On Rape — institutional structure',cluster:'A History of Misogyny / institutional violence',period:'2020–',summary:'Foam将On Rape描述为概念肖像、证词与visual/audio metaphors构成的研究系统，重点追踪rape culture与制度性免责，而非把受害身体当成视觉奇观。',actions:['研究证词与制度','分析法律、宗教与社会结构','制作概念肖像','使用文字与声音建立证据链'],sourceUrl:'https://www.foam.org/events/laia-abril-on-rape-a-history-of-misogyny-chapter-two',images:[],relations:[rel('奖项','Foam Paul Huf Award','2020 winner'),rel('展览','Foam Amsterdam','2020–2021'),rel('合作','Tim Hetherington Trust / Magnum Foundation / Galerie Les Filles du Calvaire','展览支持')]}),
p({title:'Method dialogue with Carmen Winant',cluster:'research-based feminism / mixed media / ethics',period:'2021',summary:'Foam组织Abril与Carmen Winant讨论深入研究、混合媒介、艺术家与对象的关系以及艺术与activism边界。',actions:['交换研究方法','讨论艺术家与对象的权力关系','比较摄影、装置与文字','反思艺术与activism边界'],sourceUrl:'https://www.foam.org/events/hidden-realities-a-conversation-between-laia-abril-and-carmen-winant',images:[],relations:[rel('策展','Claartje van Dijk','Foam展览与对话语境'),rel('出版','Foam Magazine #58: Talent','书面交流')]}),
],awards:['Foam Paul Huf Award — 2020','RPS Hood Medal — 2019','National Photography Award of Spain — 2023'],exhibitions:['On Rape — Foam — 2020–2021','On Mass Hysteria — Photo Elysée — 2023','On Mass Hysteria — Finnish Museum of Photography — 2024'],sources:[{label:'Laia Abril — long biography',url:'https://www.laiaabril.com/about/long-bio/'},{label:'Foam — Laia Abril',url:'https://www.foam.org/artists/laia-abril'},{label:'Foam — On Rape',url:'https://www.foam.org/events/laia-abril-on-rape-a-history-of-misogyny-chapter-two'},{label:'Foam — Abril / Winant conversation',url:'https://www.foam.org/events/hidden-realities-a-conversation-between-laia-abril-and-carmen-winant'}]}
}
};