import type { ArtistArchive, ArchiveRelation } from './archiveData';
const rel=(kind:ArchiveRelation['kind'],label:string,detail?:string):ArchiveRelation=>({kind,label,detail});

export const archiveBatch210:Record<string,ArtistArchive>={
  'pierre-huyghe':{
    artistId:'pierre-huyghe',
    projectCoverage:'继续深化既有档案：UUmwelt → Variants → Liminal；把2018之后实践从“活体生态”推进到脑成像、深度神经网络、实时模拟、环境传感、生成突变与展览级学习系统。',
    imageCoverage:'Serpentine、Kistefos、Pinault Collection / Punta della Dogana 均提供官方 installation views 与作品图；本站记录官方入口和 credit，不复制未确认可再发布的原图。',
    note:'这一阶段最重要的变化不是Huyghe“开始使用AI”，而是作品的自治单位进一步扩大：Untilled 中生物与场地自行变化；UUmwelt 把人的脑活动交给神经网络重建；Variants 让真实岛屿和数字模拟互相反馈；Liminal 则把整座展览组织成持续感知、学习、变异的敏感环境。',
    projects:[
      {title:'UUmwelt',cluster:'fMRI / deep neural network / LED screens / biological agents / contingent exhibition',period:'2018–2019',summary:'Serpentine South Gallery 个展的核心系统。Huyghe 先选择一组图像与描述，让参与者在脑中重构这些图像，同时用 fMRI 捕捉脑活动；所得数据交给 deep neural network，网络从自身图像库中反复尝试重建被想象的内容。数千次机器重建结果在展厅大型 LED 屏幕持续出现。',actions:['输入不是普通文字 prompt，而是人观看/想象指定图像时记录的 fMRI brain activity；机器因此面对的是神经活动与图像之间并不透明的映射。','deep neural network 不负责恢复一张唯一“正确图像”，而产生大量 reconstruction attempts；失败、混合和不稳定性本身成为可见内容。','Serpentine 将整个展览描述为 porous and contingent environment；现场还包含 live flies，使机器 cognition、biological reproduction 与 instinctual behaviour 同处一个环境。','展览不是固定视频循环：Huyghe 有意让场地变化在展期内继续发生，因此 exhibition state 不可逆且不可完全预测。','策展网络：Rebecca Lewin（Curator, Exhibitions and Design）与 Natalia Grabowska（Assistant Curator）。'],sourceUrl:'https://www.serpentinegalleries.org/whats-on/pierre-huyghe-uumwelt/',images:[],relations:[rel('机构','Serpentine Galleries','UUmwelt, London, 3 Oct 2018–10 Feb 2019'),rel('策展人','Rebecca Lewin','Curator, Exhibitions and Design'),rel('策展人','Natalia Grabowska','Assistant Curator'),rel('技术','fMRI + deep neural network','brain activity translated into machine reconstruction attempts'),rel('生物','live flies','biological agents within contingent environment')]},
      {title:'Variants',cluster:'scanned landscape / real-time simulation / AI / environmental sensors / living island / materialized mutations',period:'2021–ongoing',summary:'Kistefos 的永久 site-specific project，2022 对外开放。Huyghe 选择一座此前不可进入、会被 Randselva 河周期性淹没的岛屿；团队先由生物学家、测量人员系统记录物种、地形、水位、水流、石头、植物、树木、昆虫、动物、垃圾、声音和气味，再在2021年以 point-cloud technology 扫描全岛，建立实时数字模拟。',actions:['数字环境并非岛屿的静态3D复制：artificial neural network 按独立规则生成树木、垃圾、动物、人类、声音等对象的不可预测 mutations。','岛上的 climate/environmental sensors 把现实环境变化送入 simulation；地球化学、生物活动与洪水等事件因此持续改变生成系统行为。','数字 mutation 偶尔被实体化到真实岛屿，并被放置在与 simulation 中发生位置对应的现实地点；它们随后在真实环境里维持、衰败或继续改变。','作品因此不是“屏幕+自然景观”的并置，而是 physical milieu 与 digital milieu 双向渗透：现实提供数据，模拟生成可能性，生成结果又返回现实。','通往屏幕的小径把观众带到实时模拟前；模拟中的视点由 autonomous / anxious eye 导航。即使洪水使岛屿不可进入，系统仍继续运行。','Kistefos 将其称为Huyghe迄今最大的永久项目；材料清单包括 scanned forest、real-time simulation、generative mutations and sounds、intelligent camera、environmental sensors、animals、plants、micro-organisms，以及 synthetic / biological material aggregate。'],sourceUrl:'https://www.kistefosmuseum.com/sculptur/variants',images:[],relations:[rel('机构','Kistefos','permanent site-specific commission; unveiled 2022'),rel('策展/制作','Anne Stenne','producer and curator'),rel('技术','Point-cloud scan + real-time simulation','2021 island scan forms digital milieu'),rel('技术','Artificial neural network / machine learning','generates unpredictable mutations'),rel('技术','Environmental sensors','physical island conditions inform simulation'),rel('场域','Randselva River island','periodically flooded living site')]},
      {title:'Liminal',cluster:'exhibition-as-sensitive-milieu / speculative fiction / human-nonhuman cognition / learning systems',period:'2024',summary:'Punta della Dogana 大型个展（17 Mar–24 Nov 2024），由Huyghe与 Anne Stenne 紧密合作构想。展览把过去十年的作品与重要新作放进同一个动态、敏感且持续演化的 milieu，而不是把单件作品按回顾展时间线并列。',actions:['Pinault Collection 将展览描述为 human / non-human creatures 共处的环境，其中 subjectivities 持续 learning、changing、hybridizing；因此展览本身承担系统层级，而不是中性的作品容器。','不同主体的 memories 会吸收展览内可感与不可感事件的信息；观看者面对的不是预设叙事终点，而是不断形成的状态。','Huyghe 把 speculative fiction 定位为进入 possible / impossible 的载体；虚构不只是影像内容，而成为生成现实条件的规则层。','展览强调无 hierarchy、无 determinism 的 coexistence；这与早期以单件事件/影片为单位的实践相比，把自治和不确定性推进到整座展览的尺度。','官方页面列出 UUmwelt—Annlee (2018–2024)、Offspring (2018)、De-extinction (2014)、Untitled (Human Mask) (2014) 等作品，使2010年代的生物、机器视觉与非人主体线索在同一制度空间中重新关联。'],sourceUrl:'https://www.pinaultcollection.com/palazzograssi/en/pierre-huyghe-liminal',images:[],relations:[rel('机构','Pinault Collection / Punta della Dogana','Venice exhibition, 17 Mar–24 Nov 2024'),rel('策展人','Anne Stenne','exhibition conceived in close collaboration with Huyghe'),rel('概念','speculative fiction','vehicle for possible / impossible worlds'),rel('作品关系','UUmwelt—Annlee / Offspring / De-extinction / Untitled (Human Mask)','works from the preceding decade assembled into a learning milieu')]}
    ],
    awards:[],
    exhibitions:['Serpentine Galleries — Pierre Huyghe: UUmwelt, 2018–2019','Kistefos — Variants, 2021–ongoing / unveiled 2022','Punta della Dogana / Pinault Collection — Pierre Huyghe: Liminal, 2024'],
    sources:[{label:'Serpentine Galleries · Pierre Huyghe: UUmwelt',url:'https://www.serpentinegalleries.org/whats-on/pierre-huyghe-uumwelt/'},{label:'Kistefos · Variants',url:'https://www.kistefosmuseum.com/sculptur/variants'},{label:'Kistefos · Pierre Huyghe artist of the year 2022',url:'https://www.kistefosmuseum.com/news/pierre-huyghe-is-the-artist-of-the-year-2022'},{label:'Pinault Collection · Pierre Huyghe: Liminal',url:'https://www.pinaultcollection.com/palazzograssi/en/pierre-huyghe-liminal'},{label:'Pinault Collection · Liminal works',url:'https://lesoeuvres.pinaultcollection.com/en/exhibition/pierre-huyghe-liminal'}]
  }
};
