import type { ArtistArchive, ArchiveProject, ArchiveRelation } from './archiveData';
const rel=(kind:ArchiveRelation['kind'],label:string,detail?:string):ArchiveRelation=>({kind,label,detail});
const project=(p:ArchiveProject)=>p;
export const archiveBatch294:Record<string,ArtistArchive>={
'hito-steyerl':{artistId:'hito-steyerl',projectCoverage:'继续深化既有 Hito Steyerl：补 Duty-Free Art、Abstract、In Free Fall、SocialSim 与 Eye Explosion，把“战争影像→全球物流/金融→博物馆基础设施→AI模拟”的演变接起来。',imageCoverage:'本批以 Museo Reina Sofía 官方馆藏、展览与2024放映研究页为主；官方页面有对应图像/安装图，但未确认仓库再发布许可，故不复制。',note:'Steyerl 的关键不只是“谈数字图像”。她反复把图像背后的生产和流通基础设施变成作品：军工、飞机拆解、金融/物流、freeport、显示器、sandbox、3D avatar、数据集与博物馆。',projects:[
project({title:'Duty-Free Art — museum / freeport / war-zone infrastructure',cluster:'museum / freeport / financialization / three-channel installation',period:'2015',summary:'Reina Sofía 馆藏将作品明确登记为38分21秒、三路高清录像与 sandbox 构成的装置。作品把博物馆、免税仓储/freeport、资本流动与战争空间放入同一分析框架：艺术品可以在高度安全、低税或免税的物流空间中移动和增值，而现实中的公共空间与文化基础设施却可能在战争、私有化和财政压力中被摧毁。这里“艺术市场”不只是主题，三通道影像、沙箱和展厅本身共同构成一种制度模型。',actions:['制作三路高清录像而非单屏论文式影片。','在展厅加入实体 sandbox，使屏幕论述与可进入的物质环境发生关系。','把 freeport、博物馆、战争与资本流通并置为同一基础设施问题。','通过多屏并行让不同地点、图像与论证不必被压缩成单一线性叙事。'],sourceUrl:'https://www.museoreinasofia.es/en/collections/artwork/duty-free-art/',images:[],relations:[rel('收藏','Museo Reina Sofía','2018入藏；AD08427；three HD videos + sandbox；38:21。'),rel('展览','Duty-Free Art — Reina Sofía — 2015–16','João Fernandes策展；展览共13件视听作品。'),rel('方法','museum as infrastructure','把艺术机构从中性展示容器改写为资本、物流、安全和战争网络中的节点。')]}),
project({title:'Abstract — shot / reverse-shot between battlefield and arms industry',cluster:'two-screen video / war / Lockheed Martin / Andrea Wolf',period:'2012',summary:'Reina Sofía 2024研究项目把 Abstract 描述为 Steyerl 从纪录片语言转向当代图像语法的重要节点：两个屏幕以电影的 shot/reverse-shot 结构形成“对话”。一边回到 Andrea Wolf 1998年被土耳其军队杀害的地点，另一边拍摄军火制造商 Lockheed Martin 的办公室。形式不是给战争补充说明，而是把相隔甚远的死亡现场与军工企业通过剪辑语法强制建立视觉关系。',actions:['回到 Andrea Wolf 遇害地点拍摄。','拍摄 Lockheed Martin 办公空间。','以双屏 shot/reverse-shot 而非单线纪录片连接两个地理空间。','让私人历史、战争现场和军工生产链在观看结构中彼此回应。'],sourceUrl:'https://www.museoreinasofia.es/en/activity/hito-steyerl/',images:[],relations:[rel('人物','Andrea Wolf','Steyerl私人记忆与战争政治持续交叉的核心人物。'),rel('公司','Lockheed Martin','军工生产端被放到战争死亡现场的视觉反面。'),rel('方法','shot / reverse-shot as political relation','经典电影语法被改造成供应链/责任关系的空间模型。')]}),
project({title:'In Free Fall — Boeing 707 as material circulation',cluster:'aircraft / scrapyard / recycling / capitalism / essay film',period:'2010',summary:'Reina Sofía 2024项目将影片概括为追踪一架 Boeing 707 的毁坏、再利用与回收循环，以此研究资本主义中对象如何被消费、转换并再次出售。飞机在这里不是交通题材，而是一个可以沿材料、影像、商品与历史不断拆解的研究对象；它把 Steyerl 后来的“图像也像商品和碎片一样流通”变成极具体的物质模型。',actions:['选择 Boeing 707 的生命周期作为叙事骨架。','追踪毁坏、拆解、再利用和再销售，而不是只拍完整飞机。','把物质循环与影像循环并置，使废料、商品与媒体图像共享同一价值转换逻辑。','以 essay-film 结构把对象史、经济史与影像史交叉剪辑。'],sourceUrl:'https://www.museoreinasofia.es/en/activity/hito-steyerl/',images:[],relations:[rel('媒介','colour video with sound','Reina Sofía 2024放映记录时长33:43。'),rel('谱系','material recycling → image circulation','为后来的流动性、poor image与数字资本研究提供物质模型。')]}),
project({title:'SocialSim — police-violence data choreographs 3D avatars',cluster:'AI / simulation / police violence / 3D avatars / choreography',period:'2020',summary:'Reina Sofía 2024资料把 SocialSim 描述为对AI生成的沉浸美学和世界的研究：警察与工人以3D avatars出现，其动作/编舞由警察暴力数据驱动。作品因此不是简单“用AI生成视频”，而是把现实世界暴力统计转换为模拟世界中的身体动作，让 dataset → rule → avatar → choreography 的转换链成为观看对象。',actions:['把警察与工人建模为3D avatars。','以警察暴力相关数据作为模拟/编舞的驱动条件。','让统计数据转译成可见身体动作，而不是只以图表展示。','用故意过度、荒诞的模拟美学暴露预测与建模系统如何抽象真实暴力。'],sourceUrl:'https://www.museoreinasofia.es/en/activity/hito-steyerl/',images:[],relations:[rel('媒介','colour video','Reina Sofía 2024放映记录18:19。'),rel('方法','data → avatar → choreography','把数据处理链直接转成运动图像。'),rel('谱系','Factory of the Sun → SocialSim','从动作捕捉/游戏空间推进到AI与社会模拟。')]}),
project({title:'Eye Explosion — post-human documentary / machine vision lineage',cluster:'performance lecture / machine vision / Harun Farocki / missile camera',period:'2015–2016',summary:'Reina Sofía 保存的 Eye Explosion 讲座从 Harun Farocki 对海湾战争“suicide cameras”的分析出发：安装在导弹上的摄像机记录飞向目标的轨迹，图像并非主要为人的观看而生产。Steyerl由此讨论一种 post-human documentary：高速在网络与机器系统间流通、携带数据，却可能对人类观看者不可见的图像。该节点把她与 Farocki 的方法谱系明确接入网站。',actions:['以 performance lecture 而非固定录像作品展开理论。','从导弹摄像机这一具体机器视觉装置进入论证。','追踪机器生产/机器读取的图像如何改变纪录片的“观看者”概念。','把讲座、艺术史谱系与自身作品中的监控/AI图像问题连接。'],sourceUrl:'https://www.museoreinasofia.es/en/radio/hito-steyerl/',images:[],relations:[rel('人物','Harun Farocki','Eye/Machine 与 operational / machine images 构成重要方法谱系。'),rel('机构','Museo Reina Sofía','2015展览开幕期performance lecture；2016发布音频/转录。'),rel('概念','post-human documentary','纪录影像的接收者不再预设为人类观看者。')]})],awards:[],exhibitions:['Hito Steyerl: Duty-Free Art — Museo Reina Sofía — 11 Nov 2015–21 Mar 2016','German Pavilion — 56th Venice Biennale — 2015','Documenta 12 — Kassel — 2007','13th Istanbul Biennial — 2013'],sources:[{label:'Museo Reina Sofía — Duty-Free Art collection',url:'https://www.museoreinasofia.es/en/collections/artwork/duty-free-art/'},{label:'Museo Reina Sofía — Hito Steyerl: Duty-Free Art exhibition',url:'https://www.museoreinasofia.es/en/exhibition/hito-steyerl/'},{label:'Museo Reina Sofía — Digital Times, Feudal Times (2024)',url:'https://www.museoreinasofia.es/en/activity/hito-steyerl/'},{label:'Museo Reina Sofía — Eye Explosion',url:'https://www.museoreinasofia.es/en/radio/hito-steyerl/'}]}
};