import type { ArtistArchive, ArchiveRelation } from './archiveData';
const rel=(kind:ArchiveRelation['kind'],label:string,detail?:string):ArchiveRelation=>({kind,label,detail});

export const archiveBatch153: Record<string, ArtistArchive> = {
'venice-ian-cheng': {
 artistId:'venice-ian-cheng', projectCoverage:'5 个 live-simulation / worlding / AI-agent / viewer-feedback 节点深化 · 2015–2022', imageCoverage:'0 / 5',
 note:'把 Cheng 从 BOB 单点式理解扩成 Emissaries → Bad Corgi → BOB → Life After BOB → 3FACE 的方法链。关键不是“AI 做动画”，而是先写 behavioral drives / rules，再允许 agents 在实时系统中产生作者无法完全预演的行为；随后又逐渐把无限 simulation 与有限 narrative、viewer psychology 和 personality model 接起来。其 cognitive-science 背景、Industrial Light & Magic 经历、game design 与 emergence 共同构成方法来源。',
 projects:[
 {title:'Emissaries trilogy',cluster:'live simulation / emergent narrative / worlding',period:'2015–2017',summary:'三部 live simulations 把 flora、fauna 与人物放入持续运行的虚拟生态。角色拥有 behavioural drives，但事件不是固定影片时间线；系统会 build、regress、recombine，因此每次观看都只是世界运行中的一个截面。',actions:['用 game-engine logic 建立 agents 与环境','为角色设置 drives 而非逐镜头 animation','让 emergence 与 causal interaction 生成开放叙事','以 life-size projection 把 simulation 变成可观察 habitat','通过 Twitch 让作品同时存在于 museum 与 network stream'],sourceUrl:'https://www.moma.org/calendar/exhibitions/3656',images:[],relations:[rel('展览','Ian Cheng: Emissaries — MoMA PS1','2017'),rel('收藏','Museum of Modern Art, New York','Emissaries trilogy')]},
 {title:'Bad Corgi',cluster:'mobile app / mindfulness / player distraction',period:'2015',summary:'Serpentine digital commission 把 simulation logic 压缩成手机中的 demon-corgi herding game：玩家一边试图完成任务，一边被系统制造的混乱牵走注意力。它把 Cheng 对不可预测系统的兴趣直接转成用户自己的 attention experiment。',actions:['把 user input 纳入实时系统','以 herding task 建立简单目标','用环境干扰测试注意力与冲动','把 simulation 从 gallery projection 转成 everyday mobile interaction'],sourceUrl:'https://www.serpentinegalleries.org/whats-on/ian-cheng-emissaries/',images:[],relations:[rel('展览','Serpentine digital commission','2015')]},
 {title:'BOB (Bag of Beliefs)',cluster:'AI creature / belief system / reciprocal spectatorship',period:'2018–2019',summary:'BOB 不是循环播放的 avatar，而是持续成长的 artificial creature。访客可能永久改变其 behaviour、beliefs 与 emotional life；Serpentine 因而把 gallery 描述成近似 artificial-life sanctuary，观众不只是观看 BOB，也成为被它感知和响应的环境变量。',actions:['组合多个 AI / logic models','让每个 BOB 持续发展不同 behavioural history','把 visitor interaction 写回 creature state','让作品在闭馆后仍保持持续演化的时间观','反转 exhibition gaze：viewer 同时成为 creature 的 stimulus'],sourceUrl:'https://www.serpentinegalleries.org/whats-on/ian-cheng-bob/',images:[],relations:[rel('展览','Ian Cheng: BOB — Serpentine Gallery','2018'),rel('展览','May You Live In Interesting Times — Venice Biennale','2019')]},
 {title:'Life After BOB',cluster:'real-time animation / narrative constraint / human-AI family',period:'2019–2021',summary:'这一阶段开始处理一个长期矛盾：无限 simulation 很擅长产生意外，却不一定形成可记忆的 narrative。Cheng 因此把 autonomous-system logic 与更明确的 character / story architecture 接合，让 AI 不只是生态 agent，也进入家庭、意识与未来社会叙事。',actions:['保留 real-time computational world','增加较明确 protagonist 与 story arc','让 simulation 与 cinematic framing 共存','把 AI agency 从生态行为推进到 human psychology / social relation'],sourceUrl:'https://www.labiennale.org/en/art/2019/partecipants/ian-cheng',images:[],relations:[rel('展览','May You Live In Interesting Times — Venice Biennale','2019 · First Tract')]},
 {title:'3FACE',cluster:'personality model / generative portrait / psychological system',period:'2022',summary:'MoMA 馆藏中的 3FACE 把 Cheng 的系统思维进一步推向 personality：作品不再只问虚拟生态怎样演化，而开始把人的人格、选择和可计算模型本身当作生成对象。与 Emissaries 相比，worlding 从外部生态逐渐折回 psychological architecture。',actions:['把 personality / decision model 作为生成结构','延续 rules-first 而非 fixed-image 的创作方式','把 portrait 从 likeness 转成 dynamic system','连接 cognitive science 与 computational art'],sourceUrl:'https://www.moma.org/artists/49573-ian-cheng',images:[],relations:[rel('收藏','Museum of Modern Art, New York','3FACE · 2022')]}
 ], awards:[], exhibitions:['MoMA PS1 · Emissaries — 2017','Serpentine · BOB / Emissaries — 2018','Venice Biennale — 2019'], sources:[{label:'MoMA · Ian Cheng',url:'https://www.moma.org/artists/49573-ian-cheng'},{label:'MoMA PS1 · Emissaries',url:'https://www.moma.org/calendar/exhibitions/3656'},{label:'Serpentine · Emissaries',url:'https://www.serpentinegalleries.org/whats-on/ian-cheng-emissaries/'},{label:'Serpentine · BOB',url:'https://www.serpentinegalleries.org/whats-on/ian-cheng-bob/'}]
},
'venice-zhanna-kadyrova': {
 artistId:'venice-zhanna-kadyrova', projectCoverage:'6 个 Soviet-public-material / commodity / war-evidence / displaced-monument 节点深化 · 2013–2026', imageCoverage:'0 / 6',
 note:'Kadyrova 的核心材料逻辑从 Soviet mosaic / tile 的公共空间遗产出发：建筑表面被切成 commodity、clothing、food；2022 后同样的“材料携带原地点历史”原则被战争彻底改写——river stone、missile shell、被撤离的 concrete monument 不再模拟别的物，而直接成为战争证据、募资工具与 displacement carrier。2026 Ukraine Pavilion 使这条演变达到新的 institutional scale。',
 projects:[
 {title:'Monumental Propaganda',cluster:'Soviet mosaic / public image / displaced architecture',period:'2013',summary:'Kadyrova 恢复前苏联公共空间 mosaic 的材料语言，却把它从原本教育、宣传和建筑整合的场域移入 gallery。作品因此同时保存一种公共视觉技术，并暴露其原有意识形态功能在制度迁移后的变化。',actions:['研究 former-Soviet public mosaics','沿用 mosaic material / monumental syntax','把公共建筑语言迁入 white cube','让 material heritage 与 ideological afterlife 同时可见'],sourceUrl:'https://pinchukartcentre.org/en/persons-pac/artist-en/zhanna-kadyrova-2',images:[],relations:[rel('奖项','PinchukArtCentre Prize — Main Prize','2013')]},
 {title:'Second Hand',cluster:'salvaged tile / clothing / architecture-memory',period:'2014–ongoing',summary:'从具体建筑回收 ceramic tiles，再切割拼成衣服、linen 和悬挂形态。建筑的“皮肤”变成人体的第二层皮肤，second hand 同时指向二手材料、手工劳动和材料此前的社会生命。',actions:['从拆除/改造建筑回收 used tiles','保留 previous-site provenance','将硬质 tile 转成 soft-clothing silhouette','让 architecture / body / labour 三层意义叠加'],sourceUrl:'https://www.labiennale.org/en/art/2019/partecipants/zhanna-kadyrova',images:[],relations:[rel('展览','Venice Biennale','2019')]},
 {title:'Market',cluster:'construction material / food commodity / street economy',period:'2017–ongoing',summary:'concrete、natural stone 和 mosaic tile 被做成 sausage、fruit 与 vegetables，并按街市逻辑陈列。她不是追求 trompe-l’oeil，而是利用 construction hardness 与 food perishability 的冲突，把劳动、价格和消费制度重新压回材料。',actions:['用 concrete / stone 模拟肉类','以 mosaic tile 拼成水果蔬菜','采用真实 market-stall display','让 sculpture 保留可交易商品的社会语境'],sourceUrl:'https://www.labiennale.org/en/art/2019/partecipants/zhanna-kadyrova',images:[],relations:[rel('展览','Venice Biennale','2019')]},
 {title:'Palianytsia',cluster:'river stone / bread form / wartime fundraising',period:'2022–ongoing',summary:'俄乌全面战争后，Kadyrova 在 Carpathians 使用当地 river stones 制作形似乌克兰面包的对象并出售募资。材料不再来自被拆建筑，而来自临时避难地；“面包”也从商品雕塑变成语言身份、战争处境和实际资金流的交叉点。',actions:['收集当地 river stones','切割石材使其接近 bread-loaf silhouette','利用 palianytsia 的语言/身份含义','通过销售把 symbolic object 转成直接援助资金'],sourceUrl:'https://pinchukartcentre.org/en/exhibitions/kadyrova',images:[],relations:[rel('展览','Flying Trajectories — PinchukArtCentre','2023 · curated by Björn Geldhof')]},
 {title:'Instrument',cluster:'missile shell / organ / Russian classical music / war evidence',period:'2024',summary:'从 Kyiv region 收集俄军使用过的 missile shells，将其接入 organ pipes，并安排音乐家演奏俄罗斯古典音乐。文化 canon 与战争物证被迫进入同一声学机器，使“文化是否能与国家暴力分离”成为实际可听的结构。',actions:['收集 fired missile remnants','将 shells 与 organ mechanism 组合','以 Russian classical repertoire 激活装置','让 weapon evidence 与 cultural prestige 发生物理连接'],sourceUrl:'https://pinchukartcentre.org/en/exhibitions/from-ukraine-dare-to-dream-at-venice-2024',images:[],relations:[rel('展览','From Ukraine: Dare to Dream — Venice','2024')]},
 {title:'Security Guarantees / Deer journey',cluster:'evacuated public sculpture / Budapest Memorandum / displacement',period:'2019–2026',summary:'2019 为 Pokrovsk 公园制作的 concrete Origami Deer 原本位于被拆除 Soviet jet 的位置。2024 前线逼近后作品被拆卸撤离，2025 在敞篷卡车上跨越 3,000 多公里抵达 Venice；2026 Ukraine Pavilion 将 Deer 与记录旅程的多频道影像分置呈现，并以 Budapest Memorandum 失效的 security assurance 为政治框架。',actions:['从 active-war zone 撤离既有 public sculpture','保留撤离和跨境运输作为作品 history','让 concrete 的重量与 origami-paper illusion 形成脆弱/坚固矛盾','将 object 与 multi-channel journey documentation 分置','把单件公共雕塑重新置入 nuclear disarmament / failed-security-guarantee 历史'],sourceUrl:'https://www.labiennale.org/en/art/2026/ukraine',images:[],relations:[rel('展览','Ukraine Pavilion — Security Guarantees','Venice Biennale 2026 · curators Ksenia Malykh + Leonid Marushchak')]}
 ], awards:['PinchukArtCentre Prize Special Prize — 2011','Kazimir Malevich Artist Award — 2012','PinchukArtCentre Prize Main Prize — 2013','Taras Shevchenko National Prize of Ukraine — 2025'], exhibitions:['Venice Biennale — 2013 / 2015 / 2019 contexts','Flying Trajectories — PinchukArtCentre 2023–2024','From Ukraine: Dare to Dream — Venice 2024','Ukraine Pavilion: Security Guarantees — Venice Biennale 2026'], sources:[{label:'PinchukArtCentre · artist archive',url:'https://prize.pinchukartcentre.org/en/artists/zhanna-kadyrova'},{label:'PinchukArtCentre · Flying Trajectories',url:'https://pinchukartcentre.org/en/exhibitions/kadyrova'},{label:'La Biennale · Ukraine 2026',url:'https://www.labiennale.org/en/art/2026/ukraine'}]
},
'venice-jill-mulleady': {
 artistId:'venice-jill-mulleady', projectCoverage:'3 个 historical-painting remix / paired-world / architectural-fiction 节点深化 · 2019', imageCoverage:'0 / 3',
 note:'Mulleady 不宜只归为 figurative painter。她把 art-history quotation、street observation、popular image 与 private life 编成彼此污染的 temporal layers；2019 Venice 又用两个场地制造 paired realities，同年 Swiss Institute 则让建筑自身的银行历史成为 speculative fiction 的叙事发动机。核心方法是让 painting 不再对应一个稳定时空，而成为多个时代和心理状态互相穿透的场。',
 projects:[
 {title:'Frieze of Life-derived paired series',cluster:'painting cycle / Munch structure / parallel reality',period:'2019',summary:'以 Edvard Munch 的 Frieze of Life 为结构起点，但不是复制单幅名作，而是制作两套分别位于 Arsenale 与 Central Pavilion 的新系列。某些 motif 在两处重复，使观众只能依赖记忆把两个物理分离的空间拼成一个 unstable world。',actions:['借用 historical painting cycle 的组织方式','混合 popular culture / personal-life imagery','为两个 venue 制作不同系列','让特定 motif 跨场地重复','把 exhibition itinerary 变成作品的 montage mechanism'],sourceUrl:'https://www.labiennale.org/en/art/2019/partecipants/jill-mulleady',images:[],relations:[rel('展览','May You Live In Interesting Times — Venice Biennale','2019 · Central Pavilion + Arsenale')]},
 {title:'Fight-or-Flight',cluster:'site history / speculative allegory / painting + woodcut',period:'2019',summary:'Swiss Institute 首个美国机构个展从 38 St Marks Place 曾作为银行的建筑历史出发，以 monumental painting 和一组互相关联作品制造关于 polarization、crisis、fear 与 survival response 的神话性景观。site history 在这里不是背景资料，而被改写成 fictional pressure system。',actions:['调查 exhibition building 的 prior institutional use','从 bank architecture / hidden history 建立 speculative fiction','用 monumental painting 作为叙事中心','以 woodcuts 和相关作品扩展角色网络','让 fight / flight physiological response 转成不同人物的生存姿态'],sourceUrl:'https://swissinstitute.net/exhibitions/jill-mulleady',images:[],relations:[rel('展览','Fight-or-Flight — Swiss Institute, New York','2019 · first US institutional solo exhibition')]},
 {title:'Historical painting as unstable time-machine',cluster:'quotation / everyday observation / merged temporality',period:'2010s–',summary:'Venice 官方文本把她的方法概括为 close observation of everyday reality 与 highly elaborated imaginary worlds 之间的移动。关键不是 citation 数量，而是让 historical painting、popular culture 与 personal life 彼此通信，使一个画面同时属于几个时间层。',actions:['从 museum painting / art history 提取 compositional memory','把 contemporary street / everyday observation 混入历史语法','加入 popular-culture 与 autobiographical fragments','避免把 citation 处理成可逐项解码的 iconography','用 merged temporality 让 figurative painting 保持心理和叙事不稳定'],sourceUrl:'https://www.labiennale.org/en/art/2019/partecipants/jill-mulleady',images:[],relations:[]}
 ], awards:[], exhibitions:['May You Live In Interesting Times — Venice Biennale 2019','Fight-or-Flight — Swiss Institute 2019'], sources:[{label:'La Biennale · Jill Mulleady 2019',url:'https://www.labiennale.org/en/art/2019/partecipants/jill-mulleady'},{label:'Swiss Institute · Fight-or-Flight',url:'https://swissinstitute.net/exhibitions/jill-mulleady'}]
}
};
