import type { ArtistArchive, ArchiveRelation } from './archiveData';
const rel = (kind: ArchiveRelation['kind'], label: string, detail?: string): ArchiveRelation => ({ kind, label, detail });

const wertheim='https://www.labiennale.org/en/art/2019/partecipants/christine-and-margaret-wertheim';
const joseph='https://www.labiennale.org/en/art/2019/partecipants/kahlil-joseph';
const hamilton='https://www.labiennale.org/en/art/2019/partecipants/anthea-hamilton';
const favaretto='https://www.labiennale.org/en/art/2019/partecipants/lara-favaretto';
const talks='https://www.labiennale.org/en/art/2019/clandestine-talks';
const dacorte='https://www.labiennale.org/en/art/2019/partecipants/alex-da-corte';
const gaillard='https://www.labiennale.org/en/art/2019/partecipants/cyprien-gaillard';

export const archiveBatch107: Record<string, ArtistArchive> = {
  'venice-christine-and-margaret-wertheim': {
    artistId:'venice-christine-and-margaret-wertheim', projectCoverage:'1 个 hyperbolic-crochet / distributed-collaboration 长期项目已建立深档案 · 2005–2019', imageCoverage:'0 / 1 项目暂不使用不稳定外链图像', note:'Crochet Coral Reef 同时是 sculpture、数学模型、生态寓言与非等级协作平台。它的重要性不只是“钩针很像珊瑚”，而是把 hyperbolic geometry 变成可用双手理解、并可由上万人共同扩张的 material knowledge system。',
    projects:[{title:'Crochet Coral Reef',cluster:'hyperbolic geometry / crochet / citizen collaboration / ecological model',period:'2005–ongoing；Venice 2019',summary:'项目从姐妹二人在客厅制作 woolly forms 开始，随后公开邀请参与者邮寄 crocheted organisms。yarn、thread、wire、old videotape、beads 被一针针累积成 reef；全球超过一万人共同生成四十多个 Satellite Reefs。',actions:['以 crochet stitches 生成 hyperbolic surfaces，把抽象数学转为 tactile model','混合 yarn、thread、wire、old videotape、beads 等材料','通过 online invitation 开放参与，而非由 studio 独占生产','将不同参与者的小型 forms 聚合成 large reef installation','让制作耗时本身成为 ecological growth / collective time 的可见尺度','把 scientific learning、craft labour 与 coral-reef ecological crisis 连接'],sourceUrl:wertheim,images:[],relations:[rel('展览','May You Live In Interesting Times — Venice Biennale 2019','Central Pavilion / Arsenale')]}], awards:[], exhibitions:['May You Live In Interesting Times — Venice Biennale 2019'], sources:[{label:'La Biennale · Christine and Margaret Wertheim 2019',url:wertheim}]
  },

  'venice-kahlil-joseph': {
    artistId:'venice-kahlil-joseph', projectCoverage:'1 个 cinema-museum / high-low culture hybrid corpus 已建立深档案 · 2010s–2019', imageCoverage:'0 / 1 项目暂不使用不稳定外链图像', note:'官方 2019 页面强调 Joseph 横跨 cinema、visual art 与 cultural media 的 hybrid practice，没有给出单件标题。这里按方法 corpus 建档，避免假造 Venice project title。',
    projects:[{title:'Hybrid cinema / immersive video-installation corpus — Venice 2019',cluster:'cinema / visual art / cultural media / immersive installation',period:'2010s–2019',summary:'Joseph 的 moving-image practice 同时面向 mainstream circulation 与 museum installation，主动打乱 high / low culture、cinema / contemporary art 的边界。',actions:['以 cinematic production language 制作 moving image','将 film 从 conventional screen 迁入 immersive installation','吸收 popular music / cultural-media rhythm，而不将 museum context 视为“高文化净化器”','让 mainstream circulation 与 art-world exhibition 形成双向通道','通过 editing / scale / spatial presentation 改变观众对 cinematic image 的身体关系'],sourceUrl:joseph,images:[],relations:[rel('展览','May You Live In Interesting Times — Venice Biennale 2019','Central Pavilion / Arsenale')]}], awards:[], exhibitions:['May You Live In Interesting Times — Venice Biennale 2019'], sources:[{label:'La Biennale · Kahlil Joseph 2019',url:joseph}]
  },

  'venice-anthea-hamilton': {
    artistId:'venice-anthea-hamilton', projectCoverage:'1 个 vintage-reference / immersive-estrangement corpus 已建立深档案 · 2010s–2019', imageCoverage:'0 / 1 项目暂不使用不稳定外链图像', note:'Hamilton 并非怀旧地引用 fashion / design history，而是把已经因年代距离显得 harmless、kitsch 或 neutral 的 visual reference 再度扭转，使其内部 desire、power 和 exclusion 重新暴露。',
    projects:[{title:'Fashion-design citation / immersive estrangement corpus — Venice 2019',cluster:'popular culture / fashion / design / repetition + blankness',period:'2010s–2019',summary:'vintage popular culture、fashion 与 design reference 被带入 immersive environment 和 uncanny object；原始意义被抽空，再通过 repetition、blankness 与 surface 变成近 claustrophobic 的新结构。',actions:['从 historic designer、celebrity、iconic fashion trend 搜集 reference','把引用从原年代/context 中抽离','通过 repetition 放大 reference 中被忽视的 implication','利用 blankness / empty surface 中断直接叙事','把 familiar fashionable object 重组为 uncanny sculpture / environment','让 viewer 感到 attraction 与 oppression 同时存在'],sourceUrl:hamilton,images:[],relations:[rel('展览','May You Live In Interesting Times — Venice Biennale 2019','multiple locations / Central Pavilion + Arsenale')]}], awards:[], exhibitions:['May You Live In Interesting Times — Venice Biennale 2019'], sources:[{label:'La Biennale · Anthea Hamilton 2019',url:hamilton}]
  },

  'venice-lara-favaretto': {
    artistId:'venice-lara-favaretto', projectCoverage:'2 个 decaying-monument / clandestine-knowledge 节点已建立深档案 · 2009–2019', imageCoverage:'0 / 2 项目暂不使用不稳定外链图像', note:'Favaretto 用黑色幽默处理 monument 与 knowledge production：一个方向是投入巨大劳动建造注定腐烂的纪念物；另一个方向是把讨论藏进 bunker，不让观众直接进入，只让不确定、失败和批评以记录形式溢出。',
    projects:[
      {title:'Momentary Monuments',cluster:'anti-monument / rot-collapse-dissolve / futility',period:'2009–ongoing',summary:'这些“monuments”不歌颂国家、历史或英雄，而被设计成会 rot、collapse、dissolve 的 temporary structures。巨大建造劳动最终只纪念 human endeavour 本身的徒劳。',actions:['采用 monument scale / monumental effort 建造 temporary structure','选择会腐败、坍塌或消失的 material / mechanism','不绑定 national identity 或 historic heroic event','让 degradation 在展期/时间中成为作品真实变化','把“最稳定的 monument 最终也会消失”作为 material joke 而非文本宣言'],sourceUrl:favaretto,images:[],relations:[rel('展览','May You Live In Interesting Times — Venice Biennale 2019','Central Pavilion / Arsenale')]},
      {title:'Thinking Head / Clandestine Talks',cluster:'steam installation / hidden bunker / recorded roundtable',period:'2019',summary:'Central Pavilion 的 Thinking Head 产生 steam clouds；与之对应的 Clandestine Talks 在不公开地点的 bunker 进行，观众不能现场进入，不同领域参与者每次只围绕一个关键词讨论，之后才以 stream / recording 形式传播。',actions:['将 visible steam cloud 与 hidden knowledge-production event 配对','在 undisclosed bunker location 举办 closed-door roundtable','每场只指定一个 keyword 作为 discussion trigger','邀请跨学科参与者而非只由艺术家讲话','拒绝现场 audience，让 discussion 通过 stream / recording 延迟公开','将 uncertainty、failure、criticism 设为 desired outcome，而非达成结论'],sourceUrl:talks,images:[],relations:[rel('展览','Clandestine Talks / Thinking Head — Venice Biennale 2019','series of closed-door discussions')]}
    ], awards:[], exhibitions:['May You Live In Interesting Times — Venice Biennale 2019','Clandestine Talks — 2019'], sources:[{label:'La Biennale · Lara Favaretto 2019',url:favaretto},{label:'La Biennale · Clandestine Talks',url:talks}]
  },

  'venice-alex-da-corte': {
    artistId:'venice-alex-da-corte', projectCoverage:'2 个 oversized-TV / miniature-neighbourhood world-building 节点已建立深档案 · 2019', imageCoverage:'0 / 2 项目暂不使用不稳定外链图像', note:'Da Corte 的 world-making 通过尺度反转工作：在 Arsenale viewer 被 oversized TV characters 缩小；在 Central Pavilion viewer 又被 miniature suburb 放大。appropriated Americana、dollar-store object 与 high/low references 被统一进高度 choreographed environment。',
    projects:[
      {title:'Rubber Pencil Devil',cluster:'neon video environment / oversized TV / slow choreography',period:'2018–2019',summary:'neon-lit video installation 让 familiar television programmes 变成 oversize、oversaturated 的 adult version；characters 进行异常缓慢、近催眠的 choreography，坐在 benches 的 viewers 因尺度对比像被缩小。',actions:['挪用 familiar TV-character / programme vocabulary','重新 staged / crafted 成 adult uncanny versions','使用 oversaturated colour 与 neon lighting 建立 artificial environment','放大 screen / character scale 让 seated viewer 感到 miniaturised','以 hypnotically slow movement 替代 conventional TV pacing'],sourceUrl:dacorte,images:[],relations:[rel('展览','May You Live In Interesting Times — Venice Biennale 2019','Arsenale')]},
      {title:'The Decorated Shed',cluster:'miniature suburb / Mister Rogers replica / corporate-signage insertion',period:'2019',summary:'作品精确复制 Mister Rogers’ Neighborhood 的 miniature American town，置于 Federal-style mahogany table 上，又插入 corporate restaurant chain signage。viewer 因 miniature scale 成为俯视 suburb 的巨人。',actions:['精确 replicate television miniature neighbourhood','以 Federal-style mahogany table 作为 display architecture','保持 domestic miniature 的 reassuring visual code','加入 corporate restaurant-chain signage 打破纯 nostalgia','通过 miniature scale 将 viewer position 反转成 giant observer'],sourceUrl:dacorte,images:[],relations:[rel('展览','May You Live In Interesting Times — Venice Biennale 2019','Central Pavilion')]}
    ], awards:[], exhibitions:['May You Live In Interesting Times — Venice Biennale 2019'], sources:[{label:'La Biennale · Alex Da Corte 2019',url:dacorte}]
  },

  'venice-cyprien-gaillard': {
    artistId:'venice-cyprien-gaillard', projectCoverage:'1 个 entropy / visual-archaeology corpus 已建立深档案 · 2000s–2019', imageCoverage:'0 / 1 项目暂不使用不稳定外链图像', note:'Gaillard 的核心不是浪漫化 ruin，而是把 destruction / reconstruction、renewal / degradation 放在 cyclical time 里看；urban fragment 与 natural landscape 都成为“progress 其实不断制造废墟”的证据。',
    projects:[{title:'Entropy / visual archaeology corpus — Venice 2019',cluster:'urban archaeology / decay / cyclical time',period:'2000s–2019',summary:'Gaillard 在城市和自然 landscape 中寻找 deep-time traces，把外部世界 fragment 带回 installation / photo / video / collage，使 destruction 与 reconstruction、renewal 与 degradation 同时出现。',actions:['在 urban environment 与 natural landscape 中进行 nomadic observation','寻找 architecture / geology 中嵌入的 deep-time trace','把 outside-world fragment 搬入 exhibition context','并置 destruction / reconstruction 与 renewal / degradation images','跨 video、sculpture、photography、collage、public art 保持 entropy 主题','拒绝 picturesque ruin romanticism，以 cyclical-time framework 读取残余'],sourceUrl:gaillard,images:[],relations:[rel('展览','May You Live In Interesting Times — Venice Biennale 2019','Central Pavilion / Arsenale')]}], awards:[], exhibitions:['May You Live In Interesting Times — Venice Biennale 2019'], sources:[{label:'La Biennale · Cyprien Gaillard 2019',url:gaillard}]
  }
};
