import type { ArtistArchive, ArchiveRelation } from './archiveData';

const rel=(kind:ArchiveRelation['kind'],label:string,detail?:string):ArchiveRelation=>({kind,label,detail});

export const archiveBatch254:Record<string,ArtistArchive>={
  'zanele-muholi':{
    artistId:'zanele-muholi',
    projectCoverage:'继续深化 Faces and Phases：从“LGBTQ+肖像系列”下钻为持续视觉档案的生产逻辑，并以 Brooklyn Museum 具体馆藏作品核对材料、尺度、正面凝视和制度语境；同步连接 Isibonelo/Evidence 与 Tate 2024–25大型回顾展。',
    imageCoverage:'Brooklyn Museum 提供馆藏对象图与版权说明；Tate 提供2024–25展览出版物与作品入口。未复制受版权限制图像。',
    note:'Muholi 的关键不只是替被忽视群体“拍肖像”，而是持续制造一个原本缺席的公共视觉档案。Faces and Phases 的重复格式让每位参与者既保持个体性，又进入可以长期增长、跨城市展示和被机构收藏的共同历史。',
    projects:[{title:'Faces and Phases',cluster:'visual activism / portraiture / counter-archive / Black LGBTQIA+ life',period:'2006–ongoing',summary:'Muholi 自2006年开始 Faces and Phases，把南非及其 diaspora 中 Black lesbian、transgender 与 queer 参与者持续纳入一个不断扩张的肖像档案。Brooklyn Museum 对 Sunday Francis Mdlankomo, Vosloorus, Johannesburg (2011) 的馆藏记录显示其为 gelatin silver print，纸张86 × 60.6 cm，并强调系列以直接、正面的凝视抵抗把人物仅仅观看为“边缘身份”的方式。作品回应一个具体矛盾：南非法律层面的 LGBTQ+ 权利与现实中的性别/性暴力、歧视之间存在巨大落差。因此“phase”不仅指人物生命阶段，也使同一社群能够被持续记录，而不是只在危机新闻中短暂出现。',actions:['长期寻找并与 Black LGBTQIA+ 社群参与者合作，而非一次性完成固定名单。','使用相对稳定的肖像格式，让不同人物之间可以形成连续视觉档案。','保留姓名、地点和拍摄年份，使照片具有可追踪的历史坐标。','通过正面凝视和身体姿态强化参与者的自我呈现，而不是把他们处理成社会问题的插图。','让系列持续增长并进入展览、出版和公共收藏，使私人肖像逐渐形成制度可保存的反档案。'],sourceUrl:'https://www.brooklynmuseum.org/opencollection/objects/210212',images:[],relations:[rel('收藏','Brooklyn Museum','Sunday Francis Mdlankomo, Vosloorus, Johannesburg, 2011; gelatin silver print.'),rel('展览','Zanele Muholi: Isibonelo/Evidence — Brooklyn Museum','1 May–8 Nov 2015; institutional presentation connecting portraiture and visual activism.'),rel('方法','portrait repetition → living counter-archive','Stable portrait conventions allow individual lives to accumulate into a durable public record.')] }],
    awards:['ICP Infinity Award for Documentary and Photojournalism, 2016','Prince Claus Award, 2013'],
    exhibitions:['Zanele Muholi: Isibonelo/Evidence — Brooklyn Museum, 2015','Zanele Muholi — Tate Modern, London, 6 Jun 2024–26 Jan 2025'],
    sources:[{label:'Brooklyn Museum · Sunday Francis Mdlankomo / Faces and Phases',url:'https://www.brooklynmuseum.org/opencollection/objects/210212'},{label:'Brooklyn Museum Archives · Isibonelo/Evidence',url:'https://archives.brooklynmuseum.org/repositories/2/archival_objects/52668'},{label:'Tate · Zanele Muholi exhibition publication',url:'https://shop.tate.org.uk/zanele-muholi-hardback-exhibition-book/29361.html'}]
  },
  'anicka-yi':{
    artistId:'anicka-yi',
    projectCoverage:'把 Life Is Cheap 与 In Love With The World 连接成“感官政治→活体/微生物系统→机器自然史”的演变链，补入 Hugo Boss Prize 与 Tate Hyundai Commission 的机构关系。',
    imageCoverage:'Guggenheim 提供 Life Is Cheap 官方艺术家访谈；Tate 提供 Hyundai Commission 出版与项目资料入口。',
    note:'Yi 的实践不是简单使用“奇怪材料”。她持续把嗅觉、细菌、昆虫与机器放进艺术机构，迫使以视觉和静态物件为中心的展览制度处理难以稳定保存、分类和控制的行动者。',
    projects:[{title:'Life Is Cheap',cluster:'bacteria / ants / scent / sensory politics / installation',period:'2017',summary:'Yi 获得2016 Hugo Boss Prize 后在 Guggenheim 展出 Life Is Cheap。Guggenheim 的官方访谈明确列出培养细菌、蚂蚁群落和定制气味等材料，并把作品核心指向感官、权力与文化之间的关系。作品的重要性不在于把生物材料当视觉奇观，而在于让嗅觉、微生物繁殖和活体昆虫进入通常依赖稳定物件与视觉观看的美术馆空间。',actions:['培养并展示细菌，使不可见微生物成为作品实际材料。','把活体蚂蚁群落纳入装置，使作品状态受到非人行为影响。','调制并扩散特定气味，让观众以嗅觉而非只以视觉进入作品。','把实验室、昆虫系统与展览建筑组合成一个持续运行的环境。'],sourceUrl:'https://www.guggenheim.org/video/the-hugo-boss-prize-2016-anicka-yi-life-is-cheap',images:[],relations:[rel('奖项','Hugo Boss Prize 2016','Yi won the 2016 prize; Life Is Cheap followed at Guggenheim in 2017.'),rel('机构','Solomon R. Guggenheim Museum','Life Is Cheap, 21 Apr–5 Jul 2017.'),rel('方法谱系','Life Is Cheap → In Love With The World','Sensory/biological politics expands toward a speculative ecosystem in which machines behave like organisms.')]},{title:'In Love With The World',cluster:'machine ecosystem / aerobe / scent / Turbine Hall',period:'2021–2022',summary:'为 Tate Modern 第六届 Hyundai Commission 创作。Tate 的项目出版将其描述为在 Turbine Hall 中建立“new ecosystem”，并以“natural history of machines”为核心问题。与 Life Is Cheap 中真实细菌和昆虫相比，这里机器被进一步当作具有行为、环境关系和潜在生命史的存在来处理，因此 Yi 的问题从“非人生命如何进入博物馆”扩展为“机器是否也能被理解成生态行动者”。',actions:['把 Turbine Hall 当作生态空间而不是中性展厅。','设计可在巨大空间中移动/行为的机器实体，使作品不再固定于单一观看位置。','把机器行为、空气、气味与观众身体放入同一感知环境。','用“natural history of machines”替代单纯的人机工具关系，测试机器作为生态参与者的想象。'],sourceUrl:'https://shop.tate.org.uk/hyundai-commission-2021-anicka-yi/26145.html',images:[],relations:[rel('委任','Hyundai Commission — Tate Modern','Sixth Hyundai Commission, 2021.'),rel('机构','Tate Modern Turbine Hall','Large-scale ecosystem installation.'),rel('研究问题','natural history of machines','Machine life is framed through ecology and natural history rather than only automation.')] }],
    awards:['Hugo Boss Prize, 2016'],exhibitions:['Anicka Yi: Life Is Cheap — Guggenheim, 2017','Hyundai Commission: Anicka Yi: In Love With The World — Tate Modern, 2021–22'],sources:[{label:'Guggenheim · Life Is Cheap artist interview',url:'https://www.guggenheim.org/video/the-hugo-boss-prize-2016-anicka-yi-life-is-cheap'},{label:'Tate · Hyundai Commission: Anicka Yi publication',url:'https://shop.tate.org.uk/hyundai-commission-2021-anicka-yi/26145.html'}]
  },
  'trevor-paglen':{
    artistId:'trevor-paglen',
    projectCoverage:'补深 Autonomy Cube：从“监控主题雕塑”下钻为真正工作的网络基础设施，连接 Paglen 从观看秘密系统到直接建造替代通信基础设施的方法变化。',
    imageCoverage:'SFMOMA 馆藏资料记录 Plexiglas、两块功能主板与 WLAN server；仅保留机构入口，不复制版权图。',
    note:'Autonomy Cube 是理解 Paglen 的转折点：他不再只是远距离摄影秘密基础设施，而是把基础设施本身做成作品。透明外壳让网络硬件可见，而真正的作品同时发生在观众设备、无线网络和通信路由中。',
    projects:[{title:'Autonomy Cube',cluster:'network infrastructure / surveillance / sculpture / privacy',period:'2014',summary:'Autonomy Cube 外观看似极简主义透明雕塑，但其内部是实际工作的网络设备。SFMOMA 馆藏媒介记录为 Plexiglas cube with two functional motherboards, W-lan server，约34.3 × 34.3 cm。它因此把 Paglen 长期研究的不可见基础设施倒转：此前他用长焦、天文学和地理研究让秘密军事/监控系统变得可见；这里则主动搭建一套观众能够连接的通信基础设施，让“观看监控”转成“进入另一种网络关系”。',actions:['以透明 Plexiglas 制作可直接看见内部硬件的立方体外壳。','安装两块实际工作的主板与 WLAN server，而非使用道具电子元件。','让展览中的网络功能成为作品组成部分，使雕塑同时是基础设施。','把网络隐私/监控问题从图像再现转成观众设备真正参与的数据路径问题。'],sourceUrl:'https://www.sfmoma.org/artwork/2016.73.a-c/',images:[],relations:[rel('收藏','San Francisco Museum of Modern Art','Autonomy Cube, 2014; Plexiglas cube, two functional motherboards and WLAN server.'),rel('方法谱系','secret infrastructure photography → Autonomy Cube','From making hidden systems visible to constructing an operational alternative infrastructure.'),rel('差异','vs. Hito Steyerl','Paglen often materializes or technically accesses infrastructures themselves; Steyerl more often builds essayistic/image systems that expose how visibility and computation govern subjects.')] }],
    awards:[],exhibitions:[],sources:[{label:'SFMOMA · Autonomy Cube',url:'https://www.sfmoma.org/artwork/2016.73.a-c/'}]
  }
};