import type { ArtistArchive, ArchiveRelation } from './archiveData';
const rel=(kind:ArchiveRelation['kind'],label:string,detail?:string):ArchiveRelation=>({kind,label,detail});

const durham='https://www.labiennale.org/en/art/2019/partecipants/jimmie-durham';
const durhamAward='https://www.labiennale.org/en/news/jimmie-durham-golden-lion-lifetime-achievement';
const mehretu='https://www.labiennale.org/en/art/2019/partecipants/julie-mehretu';
const taylor='https://www.labiennale.org/en/art/2019/partecipants/henry-taylor';
const margolles='https://www.labiennale.org/en/art/2019/partecipants/teresa-margolles';
const awards='https://www.labiennale.org/en/news/biennale-arte-2019-official-awards';
const sunPeng='https://www.labiennale.org/en/art/2019/partecipants/sun-yuan-and-peng-yu%C2%A0';
const vo='https://www.labiennale.org/en/art/2019/partecipants/dahn-vo';

export const archiveBatch112:Record<string,ArtistArchive>={
'venice-jimmie-durham':{artistId:'venice-jimmie-durham',projectCoverage:'2 个 rejected-object / nonhuman-monument 节点已建立深档案 · 2019',imageCoverage:'0 / 2 项目暂不使用不稳定外链图像',note:'Durham 将制作称为“illegal combinations with rejected objects”：日常废弃物、自然材料、家具部件与工业表面被强行接到一起。2019 两处作品一边挑战 human/nature 分离，一边以半吨黑色岩石测试 monument 与物质重量。',projects:[{title:'Europe’s largest mammals sculptures',cluster:'rejected objects / furniture + clothes / human-nature entanglement',period:'2019',summary:'Arsenale 系列以欧洲大型哺乳动物为标题和尺度参照，但并不制作写实动物肖像；家具零件、光滑工业材料和旧衣被拼成近等身的诗性纠缠。',actions:['以欧洲大型哺乳动物的真实体量作为 sculpture scale 参照','搜集 furniture parts、slick industrial materials、used clothes 等被排斥/低价值材料','不复制 animal anatomy，而通过 loose assemblage 暗示身体存在','保留材料原本的 use-history 与人工/自然冲突','用 hybrid form 反驳 Enlightenment 式 human/nature 二分'],sourceUrl:durham,images:[],relations:[rel('展览','May You Live In Interesting Times — Venice Biennale 2019','Arsenale')]},{title:'Black Serpentine',cluster:'black stone / stainless-steel frame / weight as monument',period:'2019',summary:'Central Pavilion 中，一块约半吨的黑色 serpentinite slab 被 stainless-steel frame 围住。作品几乎不靠叙事，而让岩石重量、地质时间与人工框架正面对峙。',actions:['选择大体量 black serpentinite 作为主体材料','保留 rock slab 的天然 mass 与表面，不把它雕成具象形象','制作 stainless-steel frame 形成精确人工边界','让半吨重量和框架承载关系本身成为观看内容','把“monument”从纪念某个人/事件转成 material fortitude'],sourceUrl:durham,images:[],relations:[rel('展览','May You Live In Interesting Times — Venice Biennale 2019','Central Pavilion'),rel('奖项','Golden Lion for Lifetime Achievement — Venice Biennale 2019','awarded during opening week')]}],awards:['Golden Lion for Lifetime Achievement — Venice Biennale 2019'],exhibitions:['May You Live In Interesting Times — Venice Biennale 2019'],sources:[{label:'La Biennale · Jimmie Durham 2019',url:durham},{label:'La Biennale · Lifetime Achievement',url:durhamAward}]},

'venice-julie-mehretu':{artistId:'venice-julie-mehretu',projectCoverage:'2 个 map-grid / blurred-news underpainting 方法阶段已建立深档案 · 2000s–2019',imageCoverage:'0 / 2 项目暂不使用不稳定外链图像',note:'Mehretu 的转变不是从“抽象”走向“更抽象”，而是从可辨识 maps / architecture / planning grids，转向先以现实新闻照片建立 underpainting，再通过 blur、airbrush、screen-print 与 erase 让来源退入情绪底层。',projects:[{title:'Maps / architectural diagrams / urban-planning grids',cluster:'map notation / architecture / global mobility + inequality',period:'2000s–early 2010s',summary:'早期大型 canvases 将 maps、architectural diagrams、urban-planning grids 与大量 vectors / notations 叠加，画面同时制造巨大速度感、全球流动和不平等结构。',actions:['搜集 map、architectural diagram、urban-planning grid 等空间图式','将不同地理/建筑线层叠到同一 canvas','加入 vector、notation 与 gestural marks 形成多层 movement','利用大尺幅和 negative space 调节 density / velocity','让 global mobility 与 global inequality 在同一抽象结构里并存'],sourceUrl:mehretu,images:[],relations:[]},{title:'Blurred news-image underpaintings — Venice 2019 corpus',cluster:'news photograph / blur / airbrush + screen-print / erasure',period:'2010s–2019',summary:'后期 paintings 的 underpainting 来自 Texas migrant detention centre、Grenfell Tower 火灾、Bolsonaro rally 等照片；来源图被模糊到无法直接辨认，再覆盖 airbrushed strokes、screen-printed elements，并不断添加/擦除。',actions:['从当代 political / disaster news photographs 建立 underpainting source layer','对 source image 进行 blur / spatial diffusion，使具体事件失去可读图像细节','叠加 airbrushed marks 与 screen-printed elements','反复 add / erase，使 image 在出现与消散之间保持不稳定','让来源不再作为 illustration，却仍通过 colour / density / atmosphere 留下 emotional register'],sourceUrl:mehretu,images:[],relations:[rel('展览','May You Live In Interesting Times — Venice Biennale 2019','Central Pavilion / Arsenale')]}],awards:[],exhibitions:['May You Live In Interesting Times — Venice Biennale 2019'],sources:[{label:'La Biennale · Julie Mehretu 2019',url:mehretu}]},

'venice-henry-taylor':{artistId:'venice-henry-taylor',projectCoverage:'2 个 intimate portrait / political group-scene 方法节点已建立深档案 · 2000s–2019',imageCoverage:'0 / 2 项目暂不使用不稳定外链图像',note:'Taylor 的“voracious painting”从最亲近的 family/friend portrait 一直覆盖陌生人、贫困者、名人和政治群像；关键是让 art history、Black everyday life 与 American inequality 同时保持可读，而不牺牲画面的直接性。',projects:[{title:'Family / friends / encountered-subject portraits',cluster:'intimate portrait / everyday sitter / bold block colour',period:'2000s–2019',summary:'Taylor 画家人、朋友以及社会地位完全不同的人，把 destitute 与 dazzlingly successful 都放进同一 portrait practice；人物首先作为具体的人存在，而不是社会学类型。',actions:['从 family、friends 与日常 encounter 中选择 sitter','以直接观察和记忆快速建立 portrait','使用 bold forms / block colours 保持 image immediacy','保留衣着、姿态、室内外环境等 social clues','避免把 sitter 仅作为“议题代表”，维持个体 presence'],sourceUrl:taylor,images:[],relations:[]},{title:'Politically inflected group scenes',cluster:'Black American life / spliced geography-history / art-historical reference',period:'2000s–2019',summary:'群像会把不同 geography / history 拼到同一画面，用 art-historical quotation 与当代 Black life 的不平等现实互相碰撞。',actions:['将不同地点/历史时刻的人物与事件压进同一 group scene','引用 art-historical composition 但更换其社会主体','以日常 clothing / gesture 将历史结构拉回当下','把 racial injustice / American inequality 放进人物关系而非说明性文字','保持 humour、colour 与 visual immediacy，避免议题压垮 painting'],sourceUrl:taylor,images:[],relations:[rel('展览','May You Live In Interesting Times — Venice Biennale 2019','Central Pavilion / Arsenale')]}],awards:[],exhibitions:['May You Live In Interesting Times — Venice Biennale 2019'],sources:[{label:'La Biennale · Henry Taylor 2019',url:taylor}]},

'venice-teresa-margolles':{artistId:'venice-teresa-margolles',projectCoverage:'1 个 forensic-material / narcoviolence feminist corpus 已建立深档案 · 1990s–2019',imageCoverage:'0 / 1 项目暂不使用不稳定外链图像',note:'Margolles 具有 forensic-medicine 背景并共同创立 SEMEFO。她不把死亡当 symbolic theme，而持续使用与暴力现场、遗体处理和城市痕迹相关的 texture、smell、physical remains，使 governmental negligence 与 narcoviolence 的社会成本通过材料进入展场。',projects:[{title:'Forensic materiality / narcoviolence corpus — Venice 2019',cluster:'forensic research / physical remains / smell-texture / feminist violence analysis',period:'1990s–2019',summary:'实践围绕 Mexico narcoviolence、drug criminalisation、government negligence 与 gendered violence；死亡通过物理残留、气味、表面和现场材料被呈现，而不是由戏剧化尸体图像替代。',actions:['利用 forensic-medicine knowledge 理解 death scene / bodily-remain materiality','从 narcoviolence 与城市暴力现实中追踪 physical traces','把 texture、smell、residue 等非视觉信息带入作品','避免将死者身体直接消费为 spectacle，转而呈现其留下的 material consequence','从 feminist lens 分析 violence 对不同身体/社会位置的不均衡影响','将 government negligence 与 drug criminalisation 的 socioeconomic cost 接到具体物质上'],sourceUrl:margolles,images:[],relations:[rel('奖项','Special Mention — Venice Biennale 2019','International Jury'),rel('展览','May You Live In Interesting Times — Venice Biennale 2019','Central Pavilion / Arsenale')]}],awards:['Special Mention — Venice Biennale 2019'],exhibitions:['May You Live In Interesting Times — Venice Biennale 2019'],sources:[{label:'La Biennale · Teresa Margolles 2019',url:margolles},{label:'La Biennale · Official Awards 2019',url:awards}]},

'venice-sun-yuan-and-peng-yu':{artistId:'venice-sun-yuan-and-peng-yu',projectCoverage:'2 个 mechanical-alliance / intimidating-spectacle 方法节点已建立深档案 · 2009–2019',imageCoverage:'0 / 2 项目暂不使用不稳定外链图像',note:'Sun Yuan & Peng Yu 的装置经常让 viewer 的“看”本身成为作品部件。机械动作、重复冲突和 intimidating spectacle 不只提供戏剧性，而测试共同创作、权力和窥视的结构。',projects:[{title:'Sun Yuan Peng Yu',cluster:'mechanical arm / smoke ring / collaborative self-portrait',period:'2009',summary:'一圈烟不断重新出现，机械臂上的扫帚则持续将其打散；两个元素每次相遇都以其中一方暂时消失结束。艺术家把这种重复碰撞理解为双方合作关系的 self-portrait。',actions:['用 smoke circle 作为会不断生成又消散的 ephemeral element','安装机械臂与 broom 形成自动重复 sweeping motion','精确设定两者反复 encounter 的时间关系','让烟每次被打散后重新出现，形成 endless conflict loop','把“双人共同创作”转成两个系统互相生成/消解的机械隐喻'],sourceUrl:sunPeng,images:[],relations:[]},{title:'Intimidating spectacle / spectator-looking corpus — Venice 2019 context',cluster:'spectacle / surveillance-like looking / viewer as constitutive element',period:'2010s–2019',summary:'近期 installations 往往制造令人紧张的 spectacle；观众观看甚至“偷看”的行为不是外部反应，而是作品成立的 constitutive element。',actions:['搭建具有威胁感 / tension 的 mechanical or staged spectacle','预先考虑 spectator 可站立、窥看、绕行的位置','让 viewer act of looking 成为 installation 运行逻辑的一部分','通过 repeated mechanical event 维持 attention 与不安','拒绝让观众保持安全的 detached-observer position'],sourceUrl:sunPeng,images:[],relations:[rel('展览','May You Live In Interesting Times — Venice Biennale 2019','Central Pavilion / Arsenale')]}],awards:[],exhibitions:['May You Live In Interesting Times — Venice Biennale 2019'],sources:[{label:'La Biennale · Sun Yuan and Peng Yu 2019',url:sunPeng}]},

'venice-danh-vo':{artistId:'venice-danh-vo',projectCoverage:'1 个 biography-history / distributed-collaboration corpus 已建立深档案 · 2019',imageCoverage:'0 / 1 项目暂不使用不稳定外链图像',note:'Vo 的 installations 经常让历史进入私人 biography：family member、lover、former teacher 不只是幕后协作者，而成为作品实际生产/书写/选择链的一部分；charged cultural icon 与 damaged religious image 因此不断改变作者归属。',projects:[{title:'Biography-history / family collaboration corpus — Venice 2019',cluster:'charged object / family labour / cultural icon / distributed authorship',period:'2019',summary:'Biennale 2019 的 collaborator circle 包括 boyfriend、nephew、father 与 former professor。历史性 object、文化 icon、损坏宗教图像与亲友的实际参与被放在同一 installation system 中，使宏大历史与私人 biography 相互污染。',actions:['选择带有 political / religious / cultural charge 的 existing objects','将 damaged religious imagery 等 history-bearing fragments 重新置入 installation','邀请 father、nephew、partner、former teacher 等参与书写/制作/选择','保留 collaborator 的实际手迹或劳动，不把其隐藏为 studio production','让 family biography 与 colonial / national / religious history 发生直接 material contact','通过分散 authorship 破坏“艺术家单一创作者”的默认结构'],sourceUrl:vo,images:[],relations:[rel('展览','May You Live In Interesting Times — Venice Biennale 2019','Central Pavilion / Arsenale')]}],awards:[],exhibitions:['May You Live In Interesting Times — Venice Biennale 2019'],sources:[{label:'La Biennale · Danh Vo 2019',url:vo}]}
};
