import type { ArtistArchive, ArchiveRelation } from './archiveData';
const rel=(kind:ArchiveRelation['kind'],label:string,detail?:string):ArchiveRelation=>({kind,label,detail});
const roster='https://www.labiennale.org/en/art/2017/artists';
const latham='https://www.lissongallery.com/news/john-latham-included-in-viva-arte-viva-at-the-venice-biennale';
const lathamReview='https://www.rtve.es/play/noticias/20170614/bienal-venecia-2017-viva-arte-viva/1564823.shtml';
const lee='https://bonnierskonsthall.se/en/the-mending-project/';
const leeVenice='https://www.irenebrination.com/2017/06/27/lee-mingwei-mending-project-venice-biennale/';
const leibovici='https://www.editions-mf.com/auteur/91/franck-leibovici';
const leiboviciInterview='https://www.switchonpaper.com/geopolitique/justice/bogoro-autres-manieres-de-faire-de-art-du-droit-des-sciences-sociales/';
const lewitt='https://miguelabreugallery.com/artists/lewitt/works/';
const lewittFiller='https://www.galeriebuchholz.de/exhibitions/sam-lewitt-berlin-2017';
const liu='https://www.pacegallery.com/exhibitions/liu-jianhua/';
const liuAsac='https://asac.labiennale.org/attivita/arti-visive/367535';

export const archiveBatch132:Record<string,ArtistArchive>={
'venice-2017-john-latham':{artistId:'venice-2017-john-latham',projectCoverage:'1 个 book-destruction / knowledge-object historical corpus 已建立方法档案 · 1960–1992; Venice 2017',imageCoverage:'0 / 1 项目暂不使用不稳定外链图像',note:'Venice 2017 展出 17 件 Latham 作品，集中于 Pavilion of Artists and Books。公开资料确认年代跨 1960–1992，但未在单一稳定来源完整列出 17 件逐件清单；因此这里按明确可验证的 skoob / book-object 方法建档，不伪造全目录。',projects:[{title:'Skoob / book-object works — Venice 2017 selection',cluster:'burned book / spray paint / assemblage / knowledge-system critique',period:'1960–1992; selected in 2017',summary:'Latham 将 books 直接嵌入 painting / assemblage，使用 burning、spray-gun painting、stacking、cutting 等方式破坏“书是稳定知识容器”的默认地位。2017 Pavilion of Artists and Books 展出 17 件作品，现场可见被烧灼、变形并固定于画面上的书。',actions:['选择真实 printed books 作为 physical material，而不是仅绘制书的图像','把 book 从 reading object 转成可切割、堆叠、烧灼、粘接的 sculptural unit','使用 spray gun 将 pigment 喷射到 canvas / book surface，减少传统 brush authorship','在部分 skoob works 中让 fire 直接改变纸张边缘、厚度与可读性','把受损 books 嵌入/固定到 painting or relief support，使文字知识与物质毁损同时存在','通过 stacking / tower form 把 book collection 转成临时 architecture','保留 burning / deformation 的事件痕迹，不修复回“完整书”','以 destruction / transformation 测试 creation 与 knowledge authority 的关系'],sourceUrl:latham,images:[],relations:[rel('展览','Viva Arte Viva — Venice Biennale 2017','17 works · Pavilion of Artists and Books'),rel('展览','A World View: John Latham — Serpentine Galleries','2017 concurrent major exhibition')]}],awards:[],exhibitions:['Viva Arte Viva — Venice Biennale 2017','A World View — Serpentine Galleries 2017'],sources:[{label:'Lisson Gallery · John Latham at Venice 2017',url:latham},{label:'RTVE · Venice 2017 / Latham book sculptures',url:lathamReview},{label:'La Biennale · Artists 2017',url:roster}]},

'venice-2017-lee-mingwei':{artistId:'venice-2017-lee-mingwei',projectCoverage:'1 个 visible-mending / stranger-dialogue participatory system 已建立深档案 · 2009–2017',imageCoverage:'0 / 1 项目暂不使用不稳定外链图像',note:'The Mending Project 的核心不是“艺术家帮人补衣服”，而是完整规则系统：访客交出有私人历史的破损衣物；mender 用故意显眼的彩线修补；双方在半小时左右的劳动中交谈；衣物可暂留现场并与墙上的线轴保持不断线连接。',projects:[{title:'The Mending Project',cluster:'visible repair / 400 spools / table-conversation / participatory accumulation',period:'2009–ongoing; Venice 2017',summary:'长桌、椅子、约数百个彩色线轴与不断累积的 repaired garments 构成 process-based installation。访客带来破损 textile，mender 在交谈中用亮色 thread 修补，且刻意不隐藏 repair；部分衣物留到展览结束，线仍连接到墙上 spool，形成越来越密的 social map。',actions:['预先制作 table / chairs / wall-spool display，建立 mender 与 visitor 面对面的 conversation geometry','准备约数百个不同颜色 thread spools，让 repair 可被主动强调','邀请 visitor 自愿带来 damaged garment / textile，而不是由艺术家事先选择 object','让 visitor 坐在 mender 对面，在 repair 所需时间内进行自由 conversation','使用 bright contrasting thread 做 visible mending，拒绝 tailor-style invisible repair','根据破口和对话即兴决定 stitch / embroidery，而不套用统一 decorative pattern','修补后询问 participant 是否愿意把 garment 留在展览期间','若留下，则不剪断 thread，让 garment 与 wall spool 保持物理连接','随着数量增加，把个人 clothing histories 累积成 room-scale web，同时仍允许每件在展览结束后归还 owner'],sourceUrl:lee,images:[],relations:[rel('展览','Viva Arte Viva — Venice Biennale 2017','Pavilion of the Common / Arsenale')]}],awards:[],exhibitions:['Viva Arte Viva — Venice Biennale 2017'],sources:[{label:'Bonniers Konsthall · The Mending Project / rules',url:lee},{label:'Irenebrination · Lee Mingwei Venice 2017 interview',url:leeVenice},{label:'La Biennale · Artists 2017',url:roster}]},

'venice-2017-franck-leibovici':{artistId:'venice-2017-franck-leibovici',projectCoverage:'1 个 artwork-ecology / reactivation-training installation 标题与方法已确认 · 2017 · 现场组件清单仍待补',imageCoverage:'0 / 1 项目暂不使用不稳定外链图像',note:'这是诚实的“部分深档案”：The training — an artwork for later / and after 的 Venice 2017 标题和方法论位置有多源确认，但目前公开可稳定检索资料没有足够完整的现场 component inventory，因此不虚构材料、尺寸或件数。',projects:[{title:'the training — an artwork for later / and after',cluster:'artwork ecology / training device / document-practice reactivation / future use',period:'2017',summary:'项目延续 Leibovici 对“作品生态”的研究：作品不是只由一个被观看的 artefact 构成，而由其使用方式、conversation、notation、document、professional gesture 和未来 reactivation 共同构成。其所谓 training 指让 visitor / user 练习不熟悉的观看和知识操作，而非被动接受作者解释。',actions:['从“作品有哪些实际 usages / practices”而不是“作者想表达什么”开始组织材料','把 document 视为会产生行动效果的 artefact，而非中性的事实容器','借用 experimental music、dance、linguistics 的 score / notation 思维，将复杂实践转成可重复执行的 instructions / diagrams','设计 viewer 需要 actively read / compare / reactivate 的路径，而不是单一 frontal viewing','把 conversation / evaluation / professional gesture 纳入作品 ecology，承认它们会改变作品存在方式','将 installation 理解为 training apparatus：参与者练习新的 reading / seeing，而非追求统一 interpretation','让 knowledge 潜藏于可再次处理的材料和动作中，为 exhibition 之后的 later / after 使用保留空间'],sourceUrl:leiboviciInterview,images:[],relations:[rel('展览','Viva Arte Viva — Venice Biennale 2017','the training — an artwork for later / and after'),rel('展览','Open Table with franck leibovici — Venice Biennale','3 Nov 2017')]}],awards:['ADAGP × Bétonsalon / Villa Vassilieff research grant — 2017'],exhibitions:['Viva Arte Viva — Venice Biennale 2017'],sources:[{label:'Éditions MF · Franck Leibovici works',url:leibovici},{label:'Switch (on Paper) · artwork ecology / training methodology',url:leiboviciInterview},{label:'La Biennale · Franck Leibovici 2017',url:'https://www.labiennale.org/en/biennale-channel/biennale-arte-2017-franck-leibovici'}]},

'venice-2017-sam-lewitt':{artistId:'venice-2017-sam-lewitt',projectCoverage:'1 个 decommissioned-power-plant / fly-ash reproduction installation 已建立深档案 · 2017',imageCoverage:'0 / 1 项目暂不使用不稳定外链图像',note:'Stranded Assets 是非常具体的 site/material research：Lewitt 不是泛泛讨论“能源”，而是进入刚停运的 Porto Marghera Giuseppe Volpi power plant，借来楼梯间 1920s decorative lamps，再用燃煤副产品 fly/fuel ash 复制它们。',projects:[{title:'Stranded Assets',cluster:'decommissioned power plant / original industrial lamps / compressed fuel ash / Murano glass',period:'2017',summary:'项目源自 recently decommissioned Giuseppe Volpi thermoelectric plant。原始 iron wall lamps 从 Marghera 被借出并带入 Arsenale，为展区提供真实照明；旁边的复制品则以 pure compressed fuel ash、metal hardware、Murano glass 等制成，把发电产生的 waste 重新压成曾服务发电厂建筑的 decorative form。',actions:['前往 Porto Marghera 已停运 Giuseppe Volpi power plant 做 site research','识别 stairwell 中 early-20th-century book-shaped decorative lamps，并调查 plant 被私有化/转物流中心的资产状态','安排原始 lamps 的 loan / relocation 到 Venice Biennale，而非只拍照复制','测量/记录 iron housing 与约数百根 Murano-glass-rod shade 的结构','收集 fuel/fly ash——coal refinement 的 particulate by-product——作为复制材料','以 water / pressure 利用 ash 自身 cementitious property 将其压铸为 lamp carapace reproduction','加入 metal / electrical hardware 与 clear/black Murano glass rods，保持复制品与原件的结构对应','让 original lamps 实际点亮展区，并照亮由其工业 waste “翻模”出来的 replicas','在部分 variants 中加入 ENEL environmental-protection manuals、ash buckets、hazard mask、fish bones 等 material residue，把能源、废物、物流/私有化接进同一 assemblage'],sourceUrl:lewittFiller,images:[],relations:[rel('展览','Viva Arte Viva — Venice Biennale 2017','Corderie / Arsenale · Stranded Assets'),rel('展览','FILLER — Galerie Buchholz, Berlin','2017 extension of Stranded Assets')]}],awards:[],exhibitions:['Viva Arte Viva — Venice Biennale 2017','FILLER — Galerie Buchholz 2017'],sources:[{label:'Miguel Abreu Gallery · Stranded Assets works',url:lewitt},{label:'Galerie Buchholz · FILLER / Venice process',url:lewittFiller},{label:'La Biennale · Sam Lewitt 2017',url:'https://www.labiennale.org/en/biennale-channel/biennale-arte-2017-sam-lewitt'}]},

'venice-2017-liu-jianhua':{artistId:'venice-2017-liu-jianhua',projectCoverage:'1 个 gold-glazed porcelain / steel-sheet liquid illusion project 已建立深档案 · 2014–2017',imageCoverage:'0 / 1 项目暂不使用不稳定外链图像',note:'Square 的 ASAC 记录明确：2014，gold-glazed porcelain on steel sheets，variable dimensions。Liu 以 Jingdezhen 出身的 ceramic expertise 把坚硬、易碎的 porcelain 做成像刚刚流淌/凝固的金色液体。',projects:[{title:'Square',cluster:'gold-glazed porcelain / steel sheets / liquid-pool illusion / ceramic material inversion',period:'2014; Venice 2017',summary:'一组 gold-glazed porcelain pools 静置于 flat steel sheets 上。高光 glaze 和不规则边缘让 porcelain 看似 molten gold / viscous liquid，却实际上经过高温烧制成为硬脆 ceramic；steel 则像 industrial tray / neutral ground。',actions:['根据不同 puddle silhouettes 制作 porcelain forms，而不是标准 vessel / figurine','利用陶瓷成型经验控制薄、扁、不规则边缘在 firing 中仍能成立','施加 gold glaze，使 ceramic surface 获得金属般反射','进行 kiln firing，将视觉上“液态”的形状永久固定为 brittle solid','把每个 porcelain pool 放置在 separate flat steel sheet 上，强化 precious/industrial 对比','不使用 pedestal，让 work 保持接近 floor / material sample 的水平关系','以多个 units 分布形成 installation，使 viewer 从不同角度比较 glaze reflection 和不规则轮廓','通过“fragile porcelain 看似 heavy liquid metal”的错觉主动反转材料常识'],sourceUrl:liuAsac,images:[],relations:[rel('展览','Viva Arte Viva — Venice Biennale 2017','Pavilion of Time and Infinity · Artiglierie')]}],awards:[],exhibitions:['Transfer — The Dowse Art Museum 2016','Viva Arte Viva — Venice Biennale 2017'],sources:[{label:'ASAC · Square, Liu Jianhua',url:liuAsac},{label:'Pace Gallery · Liu Jianhua / Square',url:liu},{label:'La Biennale · LIU Jianhua 2017',url:'https://www.labiennale.org/en/biennale-channel/biennale-arte-2017-liu-jianhua'}]}
};
