import type { ArtistArchive, ArchiveRelation } from './archiveData';
const rel = (kind: ArchiveRelation['kind'], label: string, detail?: string): ArchiveRelation => ({ kind, label, detail });

const norbu='https://www.labiennale.org/en/art/2019/partecipants/khyentse-norbu';
const lehulere='https://www.labiennale.org/en/art/2019/partecipants/kemang-wa-lehulere';
const lolis='https://www.labiennale.org/en/art/2019/partecipants/andreas-lolis';
const catala='https://www.labiennale.org/en/art/2019/partecipants/antoine-catala';
const gonzalez='https://www.labiennale.org/en/art/2019/partecipants/dominique-gonzalez-foerster';
const ikeda='https://www.labiennale.org/en/art/2019/partecipants/ryoji-ikeda';
const ikedaAsac='https://asac.labiennale.org/collezioni/fototeca/387964';

export const archiveBatch108: Record<string, ArtistArchive> = {
  'venice-khyentse-norbu': {
    artistId:'venice-khyentse-norbu', projectCoverage:'1 个 context-shift / Buddhist-philosophical film-art corpus 已建立深档案 · 2019', imageCoverage:'0 / 1 项目暂不使用不稳定外链图像', note:'官方 2019 页面没有给出单件 Venice 标题，因此按其明确的 philosophical-context 方法建档。Norbu 同时是 filmmaker、artist 与 Dzongsar Khyentse Rinpoche；作品重点不是为 Buddhism 做图解，而是测试 context 如何改变理解。',
    projects:[{title:'Context / interpretation corpus — Venice 2019',cluster:'film-art / context shift / Buddhist philosophical inquiry',period:'2019',summary:'Norbu 将 context 作为核心问题：理解与解释永远可能因位置、背景、观看框架而变化，因此作品不提供唯一正确 reading，而持续打开更宽的视角。',actions:['以具体 situation / image 的 contextual shift 作为意义变化的起点','让 film / visual-art form 与 philosophical question 同时工作','避免把 Buddhist teaching 直接转成 illustration','通过 framing / sequence 改变 viewer 对同一现象的 interpretation','把 uncertainty / broader view 保留为作品结构的一部分'],sourceUrl:norbu,images:[],relations:[rel('展览','May You Live In Interesting Times — Venice Biennale 2019','Central Pavilion / Arsenale')]}],awards:[],exhibitions:['May You Live In Interesting Times — Venice Biennale 2019'],sources:[{label:'La Biennale · Khyentse Norbu 2019',url:norbu}]
  },
  'venice-kemang-wa-lehulere': {
    artistId:'venice-kemang-wa-lehulere', projectCoverage:'1 个 salvaged-school / biography-history installation corpus 已建立深档案 · 2019', imageCoverage:'0 / 1 项目暂不使用不稳定外链图像', note:'Wa Lehulere 的 2019 两处 installation 都使用 salvaged school-desk / chair wood and metal。教育制度的废弃材料、个人 biography 与 collective South African history 被压进同一 association web。',
    projects:[{title:'Salvaged school furniture installations — Venice 2019',cluster:'school desk / salvaged wood-metal / collective memory',period:'2019',summary:'Arsenale 与 Central Pavilion 的装置均由旧 school desks / chairs 的木材和金属构成；这些材料被重新组合成围绕式场域，鼓励 visitors gather around in shared contemplation。',actions:['回收 school desks / chairs 的 wood 与 metal','拆解原 educational furniture 的正常功能','把 fragment 重组为 sculptural installation 而非修复成家具','通过 circular / gathering-oriented arrangement 强调 collective viewing','将 activist background、personal biography 与 post-apartheid collective history 连成 association network'],sourceUrl:lehulere,images:[],relations:[rel('展览','May You Live In Interesting Times — Venice Biennale 2019','Central Pavilion + Arsenale')]}],awards:[],exhibitions:['May You Live In Interesting Times — Venice Biennale 2019'],sources:[{label:'La Biennale · Kemang Wa Lehulere 2019',url:lehulere}]
  },
  'venice-andreas-lolis': {
    artistId:'venice-andreas-lolis', projectCoverage:'1 个 marble-detritus / value-reversal sculpture corpus 已建立深档案 · 2010s–2019', imageCoverage:'0 / 1 项目暂不使用不稳定外链图像', note:'Lolis 整个 career 只用 marble，却专门雕出最“不值得被雕”的街头垃圾：trash bag、cardboard box、wooden crate。high-classical medium 与 disposable object 的冲突就是作品机制。',
    projects:[{title:'Marble detritus / trompe-l’œil floor sculptures',cluster:'marble carving / trash-object mimicry / value inversion',period:'2010s–2019',summary:'life-size marble sculptures 几乎完全模仿街角、park bench 上的 ephemeral detritus，并连 crushed、stained、chipped、broken 的使用痕迹都雕出。',actions:['在街头观察 bin bag、cardboard box、wood crate 等 temporary objects','以单一 marble medium 做 life-size carving','精确复制 crease、chip、stain、crushed edge 等 wear traces','将 sculpture 直接放在 floor / corner 等接近垃圾原位置的地点','利用 marble 的 prestige 与 garbage 的 low status 反转 conventional value system','通过 trompe-l’œil detail 让 viewer 先误认 material 再发现雕刻劳动'],sourceUrl:lolis,images:[],relations:[rel('展览','May You Live In Interesting Times — Venice Biennale 2019','Central Pavilion')]}],awards:[],exhibitions:['May You Live In Interesting Times — Venice Biennale 2019'],sources:[{label:'La Biennale · Andreas Lolis 2019',url:lolis}]
  },
  'venice-antoine-catala': {
    artistId:'venice-antoine-catala', projectCoverage:'2 个 rebus-sign / pneumatic-message 节点已建立深档案 · 2018–2019', imageCoverage:'0 / 2 项目暂不使用不稳定外链图像', note:'Catala 把 communication platform 的问题做成有物理身体的 signs：message 本身可能简单，但传输方式、界面、充气/放气、emoji / rebus 才真正改变我们如何被影响。',
    projects:[
      {title:'The Heart Atrophies',cluster:'contemporary rebus / sign-language sculpture / platform communication',period:'2018–2019',summary:'Arsenale installation 被官方描述为 contemporary equivalent of a medieval rebus，说明人始终与周围 signs 保持 adaptive / flexible relationship。',actions:['把 word / sign / emoji logic 转成 spatial rebus','让 meaning 依赖 viewer 对多个 visual clue 的组合','用 sculptural installation 替代 flat text-message interface','把 miscommunication 与 interpretation gap 保留为作品体验'],sourceUrl:catala,images:[],relations:[rel('展览','May You Live In Interesting Times — Venice Biennale 2019','Arsenale')]},
      {title:'It’s Over',cluster:'coloured silicone / pneumatic relief / ambiguous reassurance',period:'2019',summary:'Central Pavilion 入口九块 coloured-silicone panels 缓慢排出空气，原本隐藏的 embossed text 才逐渐显现：“Don’t worry”“It’s over”“Everything is ok”“Hey, Relax”，或两只 teddy bears kissing。',actions:['制作九块 large silicone-covered pneumatic panels','通过 pumping / air-release 控制表面形态变化','让 embossed message 在放气过程中逐渐 revealed','选择 reassuring phrases 与 cute image 作为语言材料','让 comfort-message 的 delivery mechanism 本身产生 anxiety / ambiguity'],sourceUrl:catala,images:[],relations:[rel('展览','May You Live In Interesting Times — Venice Biennale 2019','Central Pavilion entrance')]}
    ],awards:[],exhibitions:['May You Live In Interesting Times — Venice Biennale 2019'],sources:[{label:'La Biennale · Antoine Catala 2019',url:catala}]
  },
  'venice-dominique-gonzalez-foerster': {
    artistId:'venice-dominique-gonzalez-foerster', projectCoverage:'2 个 Mars-diorama / VR-trance speculative-world 节点已建立深档案 · 2018–2019', imageCoverage:'0 / 2 项目暂不使用不稳定外链图像', note:'Gonzalez-Foerster 用 speculative fiction 不是为了预测未来，而是作为 escape technology：museum / gallery 被变成 simulated world，让观众暂时进入别的 past / present / future。',
    projects:[
      {title:'Cosmorama',cluster:'Mars diorama / speculative fiction / climate-escape model',period:'2018',summary:'与 Joi Bittle 合作的玻璃罩 diorama 受 Ray Bradbury、Leigh Brackett 的 Mars fiction 启发，以 painted background、rock、sand 等 carefully tinted sculptural elements 建出殖民火星景观。',actions:['从 Martian Chronicles 与 Leigh Brackett fiction 提取 imagined-Mars vocabulary','与 Joi Bittle 合作制作 diorama','组合 painted backdrop 与 sculpted rocks / sand','精细 tint landscape elements 统一 artificial atmosphere','以 glass enclosure 强化 museum-model / inaccessible-world 双重感','让 viewer 从外部想象自己进入 climate-crisis 后的 escape landscape'],sourceUrl:gonzalez,images:[],relations:[rel('展览','May You Live In Interesting Times — Venice Biennale 2019','Central Pavilion')]},
      {title:'Endodrome',cluster:'VR / trance encounter / mutable self-environment',period:'2019',summary:'Arsenale project 用 VR 打开 temporal、spatial、mental dimensions，使 viewer 进入 trance-like encounter，并能改变自己与 surroundings。',actions:['使用 VR headset 把 viewer 从 shared gallery 转入 individual simulated environment','设计 trance-like encounter 而非 linear game narrative','允许 participant 改变 self / surroundings 的 perceived relation','将 escape 从观看 fictional world 推进为 embodied virtual transition'],sourceUrl:gonzalez,images:[],relations:[rel('展览','May You Live In Interesting Times — Venice Biennale 2019','Arsenale')]}
    ],awards:[],exhibitions:['May You Live In Interesting Times — Venice Biennale 2019'],sources:[{label:'La Biennale · Dominique Gonzalez-Foerster 2019',url:gonzalez}]
  },
  'venice-ryoji-ikeda': {
    artistId:'venice-ryoji-ikeda', projectCoverage:'2 个 algorithmic-data / monumental-minimal audio-visual 节点已建立深档案 · 2019', imageCoverage:'0 / 2 项目暂不使用不稳定外链图像', note:'Ikeda 的“数据美学”不是把数字做成酷炫壁纸，而是用 mathematics / algorithm 把 sparse sound 与 vast digital information fields 精确同步，将自然世界转译成 perception threshold 上的 audio-visual structure。',
    projects:[
      {title:'Algorithmic monumental-minimal practice',cluster:'mathematics / sparse sound / data-field visualisation',period:'2010s–2019',summary:'Ikeda 以 sparse acoustic composition 与 vast digitally rendered information fields 共同构成 monumental minimalism，并把 mathematics 当作捕捉 / 映照 natural world 的方法。',actions:['以 numerical / algorithmic procedure 组织 sound 与 visual data','减少 melodic / figurative content，强调 frequency、pulse、scale','将 large digital-information field 与 sparse acoustic event 精确同步','利用 extreme brightness / darkness / density 测试 human perception threshold','把 mathematics 用作 translation system 而非仅视觉主题'],sourceUrl:ikeda,images:[],relations:[]},
      {title:'data-verse 1',cluster:'digital video / data universe / algorithmic audiovisual field',period:'2019',summary:'Biennale ASAC 档案确认 data-verse 1 为 2019 展出的 digital / virtual video work，是 Ikeda 将大量数据、科学观测和数学结构压缩成沉浸式 audiovisual field 的代表节点。',actions:['以 digital / virtual moving-image format 呈现','组织 massive data sets / numeric patterns 为视觉序列','将 micro-scale data 与 cosmic-scale image logic 并置','通过 precision sound 与 high-density visual rhythm 建立身体性观看'],sourceUrl:ikedaAsac,images:[],relations:[rel('展览','May You Live In Interesting Times — Venice Biennale 2019','Arsenale · data-verse 1')]}
    ],awards:[],exhibitions:['May You Live In Interesting Times — Venice Biennale 2019'],sources:[{label:'La Biennale · Ryoji Ikeda 2019',url:ikeda},{label:'ASAC · data-verse 1',url:ikedaAsac}]
  }
};
