import type { ArtistArchive, ArchiveRelation } from './archiveData';
const rel=(kind:ArchiveRelation['kind'],label:string,detail?:string):ArchiveRelation=>({kind,label,detail});

const roster='https://www.labiennale.org/en/art/2017/artists';
const guanAsac='https://asac.labiennale.org/collezioni/fototeca/368393';
const guanKadist='https://kadist.org/work/david/';
const guarneri='https://www.artribune.com/arti-visive/arte-contemporanea/2017/05/intervista-riccardo-guarneri-biennale-venezia-pittura-analitica/';
const gutierrez='https://www.galeriacurro.mx/artistas/cynthiagutierrez';
const gutierrezText='https://cynthiagutierrez.com/2024/';
const hainsPompidou='https://www.centrepompidou.fr/en/ressources/oeuvre/cq979X';
const hainsAch='https://www.centrepompidou.fr/en/ressources/oeuvre/caj5E7e';
const hajasAperture='https://aperture.org/editorial/venice-biennale-problem-photography/';
const hajasGallery='https://www.einspach.com/tibor-hajas-janos-veto';

export const archiveBatch128:Record<string,ArtistArchive>={
'venice-2017-guan-xiao':{artistId:'venice-2017-guan-xiao',projectCoverage:'1 个 internet-image / tourist-recording / three-channel video 核心节点已建立深档案 · 2013; Venice 2017',imageCoverage:'0 / 1 项目暂不使用不稳定外链图像',note:'Guan Xiao 的 David 不是简单“挪用网络视频”：她专门抓取游客在 Accademia 拍 Michelangelo《David》的低质量 home videos，再把 icon、旅游打卡、商品复制与自制歌曲压进三屏节奏。作品研究的正是“记录太多，是否反而不再观看”。',projects:[{title:'David',cluster:'three-channel video / YouTube-tourist footage / cultural-icon saturation / artist song',period:'2013; shown Venice 2017',summary:'五分钟三屏 video 主要由游客在 Florence Galleria dell’Accademia 拍摄并上传的 Michelangelo David 影像组成。mass reproduction、tourist recording 与 artist/Yu Honglei 的轻快 duet 共同把经典雕塑从“唯一原作”拆成网络时代无数低清复制品。',actions:['以 Michelangelo David 这一过度熟悉的 canonical image 作为检索锚点','从 internet / tourist-uploaded home videos 搜集大量不同角度、不同质量的 David footage','保留 handheld、poor-quality、遮挡、游客视角等“无价值影像”的原始摩擦，而不统一成高清素材','将 footage 分配到 three-channel montage，使相似图像在同时性中互相比较','与 Yu Honglei 制作/演唱 upbeat soundtrack，使歌词直接反讽“只记录、不记忆”的观看习惯','并置 original sculpture、tourist spectacle 与商品化 likeness，让 icon 的意义被消费循环主动磨平','让三屏观看迫使 viewer 不可能同时完整掌握全部图像，复制“信息过载导致看不见”的状态'],sourceUrl:guanKadist,images:[],relations:[rel('展览','Viva Arte Viva — Venice Biennale 2017','Pavilion of Traditions; ASAC records David (2013) at Corderie / Arsenale')]}],awards:[],exhibitions:['Viva Arte Viva — Venice Biennale 2017'],sources:[{label:'ASAC · Guan Xiao / David (2013)',url:guanAsac},{label:'KADIST · David',url:guanKadist},{label:'La Biennale · Artists 2017',url:roster}]},

'venice-2017-riccardo-guarneri':{artistId:'venice-2017-riccardo-guarneri',projectCoverage:'2 个 prismatic-light / pencil-micro-sign painting 方法节点已建立深档案 · 1962–2017',imageCoverage:'0 / 2 项目暂不使用不稳定外链图像',note:'Guarneri 的淡白绘画不是“极简留白”这么简单。他从家中 prismatic lamp 投出的分段光开始，逐段捕捉到 canvas，再用很小的 pencil marks 一厘米一厘米处理 surface。2017 Venice 是这套长期方法的重要晚期节点。',projects:[{title:'White-ground / prismatic-light paintings',cluster:'white ground / projected light segment / pale colour / surface analysis',period:'1962–ongoing',summary:'1962 后 Guarneri 放弃此前较暗的 informal painting，转向白底、极浅色、光段和细小符号。其起点之一是一盏 prismatic lamp：灯把碎片化光线投在室内，他将这些光段“捕捉”到 canvas 上，再继续处理。',actions:['把 canvas 建立在 white / very pale ground 上，降低传统 figure-ground contrast','在 studio 使用 prismatic lamp 投射 segmented light','观察投影光段的位置、密度和相互关系，并转译成 painted structure','避免强烈色块，使用近白、浅灰、淡色使 light 本身成为主角','不以单一 gesture 完成画面，而逐小区域推进 surface','保留大量 breathing space，让微小 tonal difference 需要近距离观看'],sourceUrl:guarneri,images:[],relations:[]},{title:'Centimetre-by-centimetre pencil-sign method',cluster:'micro mark / pencil / analytic surface / slow painting',period:'1960s–2017',summary:'Guarneri 把“painting piece by piece”理解为极慢的 surface construction：在浅色底上加入 small pencil marks / grids / interruptions，使每厘米都经过注意，但最终仍保持近乎消散的整体。',actions:['在 painted light-field 上加入 small pencil marks，而不是用强轮廓锁定图形','将 surface 拆成局部，一厘米一厘米观察并推进','让 mark density 根据底层 light / tone 调整，而非机械均匀铺满','利用 pencil 与 paint 的 material difference 制造极细微层级','主动拒绝快速、宏大的 heroic gesture，让 attention/time 成为作品实际投入','在完成时保留低对比和不确定边界，使 viewer 必须改变距离才能读出结构'],sourceUrl:guarneri,images:[],relations:[rel('展览','Viva Arte Viva — Venice Biennale 2017','international exhibition; late-career return to Venice')]}],awards:[],exhibitions:['Viva Arte Viva — Venice Biennale 2017'],sources:[{label:'Artribune · Riccardo Guarneri interview, Venice 2017',url:guarneri},{label:'La Biennale · Artists 2017',url:roster}]},

'venice-2017-cynthia-gutierrez':{artistId:'venice-2017-cynthia-gutierrez',projectCoverage:'1 个 quarry-stone / backstrap-textile / colonial-memory installation 已建立深档案 · 2014; Venice 2017',imageCoverage:'0 / 1 项目暂不使用不稳定外链图像',note:'Venice 2017 的确切作品是 Cántico del descenso I–XI。资料对件数有 10/11 的展示口径差异；本站按作品标题 I–XI 记录系列，同时明确材料与制作方法，不假装解决所有 catalogue discrepancy。',projects:[{title:'Cántico del descenso I–XI',cluster:'quarry-stone base / backstrap-loom textile / impossible flag / colonial layering',period:'2014; shown Venice 2017',summary:'石材基座与手工 textile 被做成“不可能飘扬的旗”：cantera / limestone 关联殖民时期 monument / building stone，织物则来自 pre-Hispanic backstrap-loom tradition。沉重短矮的“旗杆/旗面”让 conquest、mestizaje、传统技术消失与历史覆盖变成具体物理关系。',actions:['从家中一块被搁置、积灰的 backstrap-loom textile 触发项目，把 personal memory 连接到更长历史层','选择 cantera / limestone 作为基座材料，利用其 colonial monument / architecture association','将 stone 进行 turning / shaping，形成低矮、近 pedestal/column 的基座','与使用 telar de cintura / backstrap loom 制成的 textiles 结合，而不是把传统图案仅复制成印刷表面','把 textile 直接嵌入 / 插入 stone groove，使柔软织物像从石头中长出','故意让 textile 太重、pole/base 太低，破坏传统 flag 应该高举飘扬的功能','将多个 units 组织为 procession / ensemble，让不同历史层不是一件 symbol，而是连续结构','保留 stone-hard / textile-soft、colonial/pre-Hispanic、monument/domestic craft 的材料冲突'],sourceUrl:gutierrez,images:[],relations:[rel('展览','Viva Arte Viva — Venice Biennale 2017','Pavilion of Traditions / Arsenale')]}],awards:[],exhibitions:['Viva Arte Viva — Venice Biennale 2017'],sources:[{label:'CURRO · Cynthia Gutiérrez / Cántico del descenso',url:gutierrez},{label:'Cynthia Gutiérrez · Cántico del descenso',url:gutierrezText},{label:'La Biennale · Artists 2017',url:roster}]},

'venice-2017-raymond-hains':{artistId:'venice-2017-raymond-hains',projectCoverage:'2 个 ripped-poster / street-coauthorship 历史节点已建立深档案 · 1949–1990; Venice 2017',imageCoverage:'0 / 2 项目暂不使用不稳定外链图像',note:'Hains 的关键不是“把广告撕碎做拼贴”，而是把城市路人已经撕坏的 posters 当成 collective production。艺术家更多在寻找、截取、搬移和重组，因此他用“inaction painter”描述自己的位置。2017 属历史性纳入。',projects:[{title:'Ach Alma Manetro (with Jacques Villeglé)',cluster:'found torn posters / accidental text-poem / urban co-authorship',period:'1949',summary:'Hains 与 Jacques Villeglé 在 Paris 街头发现已被撕裂的 concert posters，取下长条碎片后重新拼接成横向“Bayeux tapestry”。标题直接来自残留字母形成的 accidental phrase。这里还不是后来完整 décollage，但已经把 passers-by 的破坏动作纳入作者链。',actions:['在 public street / hoarding 上寻找已被 passers-by 撕裂的 poster field','不从完整广告开始设计，而选择已经发生随机缺损的 fragments','把较长 poster sections 从城市表面取下','与 Jacques Villeglé 分工重组 fragments，而非隐去 collaboration','保留残字/断句，并从可见 letters 生成 accidental title','把 anonymous passers-by 的 tearing 视为前置共同创作，而非需修复的 damage','用 relocation 把街头信息废料转成可在 exhibition 中重新阅读的长卷结构'],sourceUrl:hainsAch,images:[],relations:[rel('收藏','Centre Pompidou','Ach Alma Manetro, 1949')]},{title:'Décollage / lacerated-poster panels',cluster:'torn posters / galvanized-zinc panel / urban abrasion / found abstraction',period:'1950s–1990',summary:'成熟 décollage 直接使用街头被撕扯的 posters。Centre Pompidou 1989–90《Décollage》由五块 galvanized-sheet panels 上的 lacerated posters 构成；urban advertising、anonymous tearing 与 weathering 共同制造接近 abstract painting 的表面。',actions:['持续巡视城市 advertising surfaces，寻找已经具有层叠和 lacération 的区域','选择有足够 chromatic / textual friction 的现成 poster skin，而不是自己模拟撕裂效果','连同支撑/大块 poster layer 搬入作品，保留 street provenance','不恢复广告原 message，让 torn typography 保持 fragmentary','让 galvanized/zinc-type display support 与纸张残片的工业来源保持可见','将选择/截取/移置而非手工画笔作为主要 authorship gesture'],sourceUrl:hainsPompidou,images:[],relations:[rel('收藏','Centre Pompidou','Décollage, 1989–1990'),rel('展览','Viva Arte Viva — Venice Biennale 2017','posthumous historical inclusion')]}],awards:[],exhibitions:['Viva Arte Viva — Venice Biennale 2017 · posthumous'],sources:[{label:'Centre Pompidou · Ach Alma Manetro',url:hainsAch},{label:'Centre Pompidou · Décollage',url:hainsPompidou},{label:'La Biennale · Artists 2017',url:roster}]},

'venice-2017-tibor-hajas':{artistId:'venice-2017-tibor-hajas',projectCoverage:'2 个 camera-only body-action / photographic-sequence 节点已建立深档案 · 1978–1979; Venice 2017',imageCoverage:'0 / 2 项目暂不使用不稳定外链图像',note:'必须把 János Vető 记为关键合作者/摄影者。Hajas 会设计并执行动作，但很多 1978–79 photo-actions 由 Vető 拍摄；摄影不是事后 documentation，而是 performance 的必要构件。2017 Venice 展示这组作品时恰好引发了署名层级争议。',projects:[{title:'Surface Torture',cluster:'photo-action / body / camera-specific performance / gelatin silver sequence',period:'1978; shown Venice 2017',summary:'Hajas 为 camera 安排极端身体动作，Vető 负责拍摄。Surface Torture 常以 gridded / sequential photographs 出现：深色背景、白色物质、身体弯曲或受损暗示让单张照片像 film still，而 sequence 则构成动作推进。',actions:['由 Hajas 预先设计 performance situation / body action，而非在公共现场随意纪录','把动作直接朝 camera 执行，使 photograph 的曝光时刻成为 action timing 的一部分','由 János Vető 担任关键 photographic collaborator / photographer','使用 high-contrast black-and-white / gelatin-silver image 强化身体与背景分离','以 sequence / grid 组织多张 image，生成近 cinematic progression','使用 white goo/paint/mask-like substances 与身体接触，制造皮肤被撕裂/覆盖的错觉','把 physical limit、pain / vulnerability 与 photographic proof 绑定：没有拍摄，动作逻辑不完整'],sourceUrl:hajasAperture,images:[],relations:[rel('展览','Viva Arte Viva — Venice Biennale 2017','Surface Torture presented; Aperture discussed attribution to Vető')]},{title:'Tumo / Flesh Painting / Image Whipping photo-actions',cluster:'ritual action / wounded body / photographic collaboration',period:'1978–1979',summary:'Tumo、Flesh Painting、Image Whipping 等系列延续 camera-specific ritual：Hajas 的身体被 bandage、paint、light 或伤痕式 gesture 强化；Vető 的摄影决定 sequence、contrast 和最终可流通的作品形态。',actions:['让 body 成为唯一不可替换的 primary medium','通过 bandaging、painting、binding、light 等动作改变 body surface','精细安排 dark background / spotlight / body orientation，使 action 为 photograph 而发生','由 Vető 捕捉 decisive moments，并将 performance 压缩成 serial still images','在不同 photo-actions 中重复“身体极限—影像证据”结构，而非追求稳定角色叙事','将 resulting prints 当作作品本体的一部分，而不只是 performance residue'],sourceUrl:hajasGallery,images:[],relations:[rel('展览','Viva Arte Viva — Venice Biennale 2017','1970s photographic actions shown posthumously')]}],awards:[],exhibitions:['Viva Arte Viva — Venice Biennale 2017 · posthumous'],sources:[{label:'Aperture · Venice 2017 / Surface Torture and János Vető',url:hajasAperture},{label:'Einspach · Tibor Hajas – János Vető',url:hajasGallery},{label:'La Biennale · Artists 2017',url:roster}]}
};
