import type { ArtistArchive, ArchiveRelation } from './archiveData';

const rel=(kind:ArchiveRelation['kind'],label:string,detail?:string):ArchiveRelation=>({kind,label,detail});

export const archiveBatch257:Record<string,ArtistArchive>={
'richard-mosse':{
artistId:'richard-mosse',
projectCoverage:'作品级深化：将 The Enclave、Incoming、Heat Maps 与 Broken Spectre 拆成可研究的制作节点，重点记录红外胶片、军用热成像、机器人扫描、定制多光谱航空摄影、紫外显微、剪辑与多屏空间版本。',
imageCoverage:'National Gallery of Victoria 与 Barbican 提供作品图及安装图，并明确 © Richard Mosse；NGV Incoming 安装图摄影 Sean Fennessy。机构页面提供 reproduction request，未确认开放再发布许可，因此不把受限图片复制进仓库，保留官方作品图入口与版权信息。',
note:'这组档案显示 Mosse 的核心并非简单用特殊滤镜拍冲突，而是不断借用原本服务于军事侦察、边境监控、卫星遥感与科学测量的成像系统，再改变它们的观看尺度、剪辑结构和展览空间。',
projects:[
{title:'The Enclave',cluster:'conflict / colour infrared film / six-channel installation',period:'2013',summary:'为第55届威尼斯双年展爱尔兰馆制作的六通道沉浸式录像装置。Mosse 在刚果民主共和国东部持续拍摄冲突地区，使用已经停产、原为军事侦察开发的 16mm 彩色红外胶片；这种胶片记录可见光之外的部分光谱，使植被从通常的绿色转为紫红/洋红。NGV 馆藏版本为 six-channel colour infrared film transferred to digital video, sound，39分25秒循环。展览时六幅大型投影悬置于空间，观众不是坐在单一正面银幕前，而是在屏幕之间移动，战争影像因此不断改变方向和邻接关系。',actions:['在刚果民主共和国东部 North/South Kivu 冲突地区进行长期实地拍摄。','使用原为军事侦察用途开发、后停产的 16mm colour infrared film 记录人物、武装力量与热带景观。','将胶片素材转为数字录像，并与声音共同剪辑为39分25秒循环。','把最终影像分配到六个大型悬置屏幕，而非传统单屏纪录片。','依据展场重新组织六屏关系，使观众在屏幕之间行走并不断重新组合战争叙事。'],sourceUrl:'https://www.ngv.vic.gov.au/explore/collection/work/116205/',images:[],relations:[rel('收藏','National Gallery of Victoria','2013; six-channel colour infrared film transferred to digital video, sound; 39 min 25 sec loop; artist proof, ed. 1/2.'),rel('展览版本','55th Venice Biennale → NGV','2013爱尔兰馆委任；NGV 2015–16展览以六幅大型悬置投影形成 maze-like installation。'),rel('版权','© Richard Mosse','Courtesy of the artist and Jack Shainman Gallery; official image available through NGV reproduction request.')]},
{title:'Incoming',cluster:'migration / military thermal imaging / three-channel video / sound',period:'2014–2017',summary:'Mosse 与摄影/剪辑 Trevor Tweeten、作曲/声音设计 Ben Frost 合作，反向使用军用长距离热成像系统拍摄叙利亚战争及迁徙路线。该系统可在全黑条件下从数十公里外读取相对温差，本来属于武器/边境监控技术；影像不记录普通可见光肤色，而把人体转成发亮的热迹。团队在爱琴海、利比亚外海、叙利亚、撒哈拉、波斯湾以及欧洲迁徙节点拍摄，再将60fps素材放慢至24fps。NGV馆藏版本为三通道黑白数字录像、有声、52分10秒循环；Barbican The Curve 版本则把三路影像投到约8米宽的三块屏幕，并使用高亮度投影、warp/blending 适配弧形建筑。',actions:['取得并操作受出口控制体系约束的军用级长距离热成像摄影系统。','沿难民迁徙与战争路线拍摄海上穿越、营地、边境和人物身体热迹。','将原本用于识别目标的热数据转换为黑白活动影像。','把60fps素材减速到24fps，使动作和热流获得更长观看时间。','Trevor Tweeten 参与摄影/剪辑，Ben Frost 将定向麦克风现场录音与合成声音重新设计。','制作三通道52分10秒循环版本；Barbican 2017版本在弧形空间使用三块约8米宽屏幕及投影几何校正。'],sourceUrl:'https://www.ngv.vic.gov.au/explore/collection/work/131226/',images:[],relations:[rel('收藏','National Gallery of Victoria','2015–16; three-channel black and white digital video, sound; 52 min 10 sec loop.'),rel('合作','Trevor Tweeten / Ben Frost','Cinematographer-editor / composer-sound designer.'),rel('空间版本','Barbican The Curve, 2017','Three c.8m screens; Christie HD projectors with image warping/blending adapted to curved walls.'),rel('版权','© Richard Mosse','NGV installation view credit includes photographer Sean Fennessy; reproduction request required.')]},
{title:'Heat Maps — Hellinikon Olympic Arena',cluster:'refugee camp / thermal panorama / robotic motion control / composite image',period:'2016',summary:'Heat Maps 与 Incoming 使用同一套热成像研究，但把活动影像转为极高细节的静态全景。Mosse 将热成像摄像机固定到机器人 motion-control tripod，以较高视点逐格扫描难民营等大型场所；单幅成品由接近一千个小画面构成，每个小画面拥有自己的消失点，再被无缝拼接为一张巨大热成像全景。Hellinikon Olympic Arena 记录雅典旧奥运设施被改造成临时难民空间后的围栏、安检门、扩音器、食物队伍、帐篷和临时建筑。',actions:['把长距离热成像摄像机安装到机器人运动控制三脚架。','从高视点按网格逐格扫描难民营建筑和人员活动。','获取接近一千个具有各自透视/消失点的小画面。','在后期将这些热成像帧无缝拼接成超高细节大型全景。','把通常短暂的视频热信号转换成可以缓慢检查围栏、帐篷、队伍和运动痕迹的静态观看对象。'],sourceUrl:'https://www.barbican.org.uk/read-watch-listen/barbican-meets-richard-mosse',images:[],relations:[rel('方法','robotic motion-control scan','Artist interview: almost a thousand smaller thermal frames are blended into one panorama.'),rel('系列关系','Incoming / Heat Maps','Mosse explicitly describes them as the same body of work, divided into moving-image and reflective panoramic modes.'),rel('官方图像','NGV / Barbican','Institutional pages reproduce Heat Maps/Incoming context; local republication clearance not established.')]},
{title:'Broken Spectre',cluster:'Amazon / multispectral remote sensing / infrared film / ultraviolet microscopy / panoramic installation',period:'2018–2022',summary:'历时三年在巴西亚马孙偏远地区拍摄的74分12秒大型影像装置。Mosse 不用单一摄影系统解释毁林，而按尺度切换三类成像：从空中使用与工程师共同设计的多光谱数字摄像机，模拟卫星遥感，以窄波段反射显示大尺度生态破坏；在人类尺度使用35mm黑白红外胶片拍摄火烧森林、农业前线与人物；在非人类微观尺度使用紫外显微摄影显示林地极小范围中的生物多样性。Trevor Tweeten 参与拍摄与剪辑，Ben Frost 将亚马孙现场录音与音乐构成声音层。NGV首展将其展开为20米宽沉浸式全景，影像会在 diptych、quadriptych 与单一 panorama 之间改变。',actions:['连续三年进入巴西亚马孙不同区域拍摄毁林、采矿、农业扩张与森林生态。','与机器视觉/光谱工程人员开发定制 multispectral video camera，并安装到航空平台进行遥感式拍摄。','用 beam splitters / multi-sensor array 分离约10–20nm的窄光谱反射带，将生态信息编码为假色。','在人类尺度改用35mm黑白红外胶片，以不同波段处理燃烧、人物与开发前线。','用 ultraviolet microscopy 拍摄森林地表极小范围的非人类生命。','由 Tweeten 协作摄影/剪辑，Frost 把生物圈 field recordings 与音乐组合成声音。','将74分12秒影像在20米宽空间中编排为双联、四联和单一全景等不断变化的屏幕结构。'],sourceUrl:'https://www.ngv.vic.gov.au/exhibition/richard-mosse-broken-spectre/',images:[],relations:[rel('收藏','National Gallery of Victoria','Colour digital video projection, sound; 74 min 12 sec; accession 2023.259.'),rel('技术','custom multispectral camera','Custom digital multi-sensor array with beam splitters, emulating environmental remote-sensing satellites.'),rel('展陈','NGV International, 2022–23','World premiere on an immersive 20-metre widescreen panorama.'),rel('版权','© Richard Mosse','Courtesy artist and Jack Shainman Gallery; official institutional images retained as source links only.')]}
],
awards:['Deutsche Börse Photography Prize 2014','Prix Pictet 2017'],
exhibitions:['55th Venice Biennale — Ireland Pavilion, 2013','Richard Mosse: The Enclave — NGV, 2015–16','Richard Mosse: Incoming — Barbican, 2017','NGV Triennial, 2017','Richard Mosse: Broken Spectre — NGV, 2022–23'],
sources:[{label:'NGV · The Enclave collection record',url:'https://www.ngv.vic.gov.au/explore/collection/work/116205/'},{label:'NGV · The Enclave exhibition',url:'https://www.ngv.vic.gov.au/exhibition/richard-mosse/'},{label:'NGV · Incoming collection record',url:'https://www.ngv.vic.gov.au/explore/collection/work/131226/'},{label:'Barbican · Incoming',url:'https://www.barbican.org.uk/whats-on/2017/event/richard-mosse-incoming'},{label:'Barbican · Richard Mosse interview / Heat Maps',url:'https://www.barbican.org.uk/read-watch-listen/barbican-meets-richard-mosse'},{label:'NGV · Broken Spectre',url:'https://www.ngv.vic.gov.au/exhibition/richard-mosse-broken-spectre/'},{label:'NGV · Broken Spectre collection record',url:'https://www.ngv.vic.gov.au/explore/collection/work/149921/'},{label:'Jack Shainman Gallery · Broken Spectre',url:'https://ftp.jackshainman.com/exhibitions/richard_mosse_broken_spectre'}]
}
};
