import type { ArtistArchive, ArchiveImage, ArchiveRelation } from './archiveData';

const img = (url: string, title: string, credit: string, sourceUrl: string, sourceLabel: string): ArchiveImage => ({ url, title, credit, sourceUrl, sourceLabel });
const rel = (kind: ArchiveRelation['kind'], label: string, detail?: string): ArchiveRelation => ({ kind, label, detail });

export const archiveBatch11Existing: Record<string, ArtistArchive> = {
  'alessandra-sanguinetti': { artistId: 'alessandra-sanguinetti', projectCoverage: '5 个长期 / 家庭 / 地方项目已完成第一轮 · 1996–2023', imageCoverage: '', note: '把她从 Guille 与 Belinda 单一系列扩展到动物、家庭、委托旅行与 Wisconsin 死亡记忆，重点追踪长期关系和摄影书编辑。', projects: [
    { title: 'On the Sixth Day', cluster: 'humans / domestic animals / rural Argentina', period: '1996–', summary: '在布宜诺斯艾利斯省乡村拍人与家畜之间的复杂关系，死亡、劳动、游戏和照料并置。', actions: ['乡村长期拍摄', '人与动物同等进入画面', '中画幅 / 色彩摄影', '摄影书编辑'], sourceUrl: 'https://store.magnumphotos.com/products/on-the-sixth-day', images: [], relations: [rel('出版', 'On the Sixth Day', 'first book 2005 / expanded edition 2023')] },
    { title: 'The Adventures of Guille and Belinda and the Enigmatic Meaning of Their Dreams', cluster: 'childhood / collaborative staging / long-term portrait', period: '1999–2010', summary: '从两个九岁表姐妹开始，女孩们会主动提出婚礼、死亡、动物、成年角色等场景，纪实时间与游戏表演持续混合。', actions: ['长期回访', '与被摄者共同构想场景', '服装 / 道具', '家庭与乡村日常拍摄'], sourceUrl: 'https://store.magnumphotos.com/collections/alessandra-sanguinetti-1', images: [img('https://storage.googleapis.com/fellowship-2022/hr/Alessandra%20Sanguinetti%2C%20AGBEMD%2C%20053_The%20models%2C%202001%20%C2%A9%20Alessandra%20Sanguinetti.jpg', 'The Models', '© Alessandra Sanguinetti', 'https://www.henricartierbresson.org/en/expositions/alessandra-sanguinetti/', 'Fondation HCB')], relations: [rel('出版', 'The Adventures of Guille and Belinda...', '2010')] },
    { title: 'The Illusion of an Everlasting Summer', cluster: 'adulthood / lifelong collaboration', period: '2010s–2020', summary: '继续拍 Guille 与 Belinda 进入成年、婚姻和母职，使童年角色扮演与真实人生变化发生反向呼应。', actions: ['持续十年以上回访', '家庭关系摄影', '跨年代 sequence'], sourceUrl: 'https://store.magnumphotos.com/collections/alessandra-sanguinetti-1', images: [], relations: [rel('出版', 'The Illusion of an Everlasting Summer', '2020')] },
    { title: 'Sorry, Welcome / Le Gendarme sur la colline', cluster: 'family life / commission / travel', period: '2013–2017', summary: '一条线回到家庭生活，另一条来自 Hermès / Aperture 委托；两者都保留偶然、地方和私人叙事的交叉。', actions: ['家庭日常摄影', '旅行委托', '摄影书编辑'], sourceUrl: 'https://store.magnumphotos.com/collections/alessandra-sanguinetti-1', images: [], relations: [rel('出版', 'Sorry, Welcome', '2013'), rel('出版', 'Le Gendarme sur la colline', '2017')] },
    { title: 'Some Say Ice', cluster: 'Black River Falls / mortality / return', period: '2014–2022', summary: '反复返回 Wisconsin 的 Black River Falls 拍人物、动物与地方仪式，回应童年曾读到的 Wisconsin Death Trip 和摄影保存生命的欲望。', actions: ['八年反复返回', '人物 / 动物 / 地方并置', '寒冬拍摄', '摄影书 sequence'], sourceUrl: 'https://www.magnumphotos.com/arts-culture/some-say-ice-at-the-magnum-gallery-in-paris/', images: [], relations: [rel('出版', 'Some Say Ice', 'MACK, 2022')] }
  ], awards: ['Guggenheim Fellowship', 'Hasselblad Foundation Grant', 'Rencontres d’Arles Discovery Award'], exhibitions: ['Fondation HCB', 'Magnum Gallery Paris'], sources: [{ label: 'Magnum biography / books', url: 'https://store.magnumphotos.com/collections/alessandra-sanguinetti-1' }] },
  'paz-errazuriz': { artistId: 'paz-errazuriz', projectCoverage: '6 个长期社群 / 身体 / 合作项目已完成第一轮 · 1979–现在', imageCoverage: '', note: '从睡眠、拳击、跨性别社群、精神病院伴侣到视力研究，强调她长期关系、距离伦理与合作形式的变化。', projects: [
    { title: 'Dormidos', cluster: 'sleep / public vulnerability', period: '1979', summary: '拍摄睡眠状态中的人物，使平时受控制的公共身体进入失去自我防备的状态。', actions: ['黑白摄影', '近距离观察', '系列编辑'], sourceUrl: 'https://www.pazerrazuriz.com/dormidos.html', images: [], relations: [] },
    { title: 'Boxeadores', cluster: 'boxing / working-class body', period: '1980s–1998', summary: '长期接近拳击手及训练空间，身体上的损耗、等待和男性气质比“胜负瞬间”更重要。', actions: ['拳馆长期进入', '黑白肖像', '身体近摄'], sourceUrl: 'https://www.pazerrazuriz.com/', images: [], relations: [rel('展览', 'Boxeador I', 'Galería Muro Sur, 1998')] },
    { title: 'La manzana de Adán / Adam’s Apple', cluster: 'trans community / dictatorship / intimacy', period: '1980s', summary: '在智利独裁时期长期拍摄跨性别性工作者社群，通过亲密黑白肖像建立关系，而不是把人物当社会问题的匿名例子。', actions: ['长期建立信任', '家居 / 工作环境摄影', '黑白肖像', '共同体叙事'], sourceUrl: 'https://www.pazerrazuriz.com/', images: [img('https://www.pazerrazuriz.com/images/manzana-12.jpg', 'La Manzana de Adán', '© Paz Errázuriz', 'https://www.pazerrazuriz.com/', 'Artist website')], relations: [rel('出版', 'La Manzana de Adán', '1990 / expanded edition 2014')] },
    { title: 'El infarto del alma / The Infarct of the Soul', cluster: 'psychiatric hospital / couples / collaboration', period: '1990s', summary: '在精神病院拍摄伴侣关系，让被制度定义为患者的人以爱情、身体接触和共同姿势出现。', actions: ['长期机构进入', '伴侣肖像', '与作家 Diamela Eltit 合作出版'], sourceUrl: 'https://www.pazerrazuriz.com/el-infarto-del-alma_en.html', images: [], relations: [rel('出版', 'El infarto del alma', '1994 and later editions')] },
    { title: 'Los nómades del mar', cluster: 'Kawésqar / southern Chile / long-term portrait', period: '1990s', summary: '围绕 Kawésqar 社群与南部地域长期工作，避免把原住民经验压缩成消失文化的民族志标本。', actions: ['地方长期摄影', '肖像', '出版 / 巡展'], sourceUrl: 'https://www.pazerrazuriz.com/exhibitions.html', images: [], relations: [rel('展览', 'Museo Nacional de Bellas Artes, Santiago', '1996')] },
    { title: 'La luz que me ciega', cluster: 'achromatopsia / co-authored perception', period: '2010', summary: '与先天性色盲 / 全色盲参与者合作，跨摄影与多媒体追问“看见”是否能被单一视觉标准定义。', actions: ['参与者合作', '跨媒介实验', '视觉经验访谈'], sourceUrl: 'https://www.pazerrazuriz.com/la-luz-que-me-ciega.html', images: [], relations: [rel('出版', 'La Luz que Me Ciega', '2010')] }
  ], awards: [], exhibitions: ['Venice Biennale Chile Pavilion context 2015', 'MAPFRE retrospective contexts'], sources: [{ label: 'Paz Errázuriz official works', url: 'https://www.pazerrazuriz.com/' }, { label: 'Official books', url: 'https://www.pazerrazuriz.com/books.html' }] },
  'graciela-iturbide': { artistId: 'graciela-iturbide', projectCoverage: '5 个墨西哥社群 / 仪式 / 私人空间项目已完成第一轮 · 1978–2012', imageCoverage: '', note: '从 Seri 与 Juchitán 的长期社群摄影到 Frida Kahlo 私人物件，强调象征图像如何从实际关系和地方经验中生长。', projects: [
    { title: 'Seri Indians / Sonora Desert', cluster: 'commission / indigenous community / desert', period: '1978–1979', summary: '受邀进入 Sonora 沙漠 Seri 社群拍摄，人物、荒漠、现代物件和传统生活同时出现。', actions: ['社群长期停留', '黑白摄影', '环境肖像', '仪式与日常并置'], sourceUrl: 'https://www.gracielaiturbide.org/en/about/', images: [], relations: [] },
    { title: 'Juchitán de las Mujeres', cluster: 'Juchitán / women / rituals / everyday life', period: '1979–1988', summary: '长期在 Juchitán 与当地女性相处，市场、节庆、死亡、动物与肖像共同形成一套地方视觉关系。', actions: ['多年返回', '黑白摄影', '市场 / 仪式观察', '人物关系'], sourceUrl: 'https://www.gracielaiturbide.org/en/about/', images: [img('https://d7hftxdivxxvm.cloudfront.net/?height=800&quality=80&resize_to=fit&src=https%3A%2F%2Fd32dm0rphc51dk.cloudfront.net%2FvaAKCWhF4oRIrODgA-dVug%2Fnormalized.jpg&width=666', 'Juchitán de las Mujeres', '© Graciela Iturbide', 'https://www.moma.org/collection/artists/2844', 'MoMA')], relations: [rel('出版', 'Juchitán de las Mujeres', '1989')] },
    { title: 'Fiesta y Muerte', cluster: 'ritual / death / symbolic observation', period: '1980s', summary: '围绕墨西哥节庆、死亡与宗教仪式持续拍摄，鸟、祭祀与身体反复出现，但象征性始终来自现场观察。', actions: ['仪式现场摄影', '跨地点长期观察', '象征图像编辑'], sourceUrl: 'https://www.gracielaiturbide.org/en/about/', images: [], relations: [rel('奖项', 'Guggenheim Fellowship', '1988 project Fiesta y Muerte')] },
    { title: 'Naturata', cluster: 'nature / animals / poetic sequence', period: '2000s–2013', summary: '将植物、动物、景观和残留物组织成较少社会叙事、更多形态和生命循环的序列。', actions: ['黑白摄影', '跨地域收集图像', '形态 / 象征 sequence'], sourceUrl: 'https://www.gracielaiturbide.org/exhibitions/', images: [], relations: [rel('展览', 'Chobi Mela VII', '2013')] },
    { title: 'El baño de Frida / Frida’s Bathroom', cluster: 'Frida Kahlo / private objects / absence', period: '2005–2012', summary: '进入 Casa Azul 长期封闭的 Frida Kahlo 浴室，拍摄支具、药物、衣物与空间痕迹，以物件代替名人肖像。', actions: ['档案 / 私人空间许可', '物件摄影', '黑白摄影', '系列出版 / 展览'], sourceUrl: 'https://www.gracielaiturbide.org/exhibitions/', images: [], relations: [rel('展览', 'Museo Frida Kahlo', '2012')] }
  ], awards: ['Hasselblad Award 2008', 'W. Eugene Smith Award 1987'], exhibitions: ['Centre Pompidou 1982', 'SFMOMA 1990', 'Getty 2007', 'Tate Modern retrospective context 2013'], sources: [{ label: 'Official biography', url: 'https://www.gracielaiturbide.org/en/about/' }, { label: 'Official exhibitions', url: 'https://www.gracielaiturbide.org/exhibitions/' }] },
  'claudia-andujar': { artistId: 'claudia-andujar', projectCoverage: '5 个 Yanomami / 实验摄影 / 政治行动节点已完成第一轮 · 1971–现在', imageCoverage: '', note: '把摄影形式实验、医疗身份照片、政治倡议和后期档案再编辑分开，避免只把她概括成“原住民纪实摄影”。', projects: [
    { title: 'Yanomami — early field work / A Floresta', cluster: 'forest / intimacy / experimental photography', period: '1971–1970s', summary: '自 1971 起长期进入 Yanomami 社群，使用长曝光、闪光、滤镜与近距离身体摄影寻找不同于新闻纪实的观看方式。', actions: ['长期共同生活', '长曝光', '闪光', '滤镜', '黑白 / 彩色实验'], sourceUrl: 'https://www.fondationcartier.com/en/exhibitions/claudia-andujar-the-yanomami-struggle', images: [img('https://cdn.sanity.io/images/cxgd3urn/production/baedf935f0af64cf453ed976d49117f1ad31d0ec-1600x1077.jpg?auto=format&fit=crop&h=1292&q=85&w=1920', 'The Yanomami Struggle', '© Claudia Andujar', 'https://www.fondationcartier.com/en/exhibitions/claudia-andujar-the-yanomami-struggle', 'Fondation Cartier / press documentation')], relations: [] },
    { title: 'A Casa / communal life', cluster: 'house / collective body / daily life', period: '1970s', summary: '围绕 communal house、火、身体和日常关系建立更靠近内部生活节奏的摄影，而非只描述“族群特征”。', actions: ['居住空间长期拍摄', '室内弱光', '身体 / 建筑并置'], sourceUrl: 'https://www.fondationcartier.com/en/exhibitions/claudia-andujar-the-yanomami-struggle', images: [], relations: [] },
    { title: 'Marcados', cluster: 'vaccination / numbered portrait / identity', period: '1981–1983', summary: '在医疗接种行动中为参与者制作编号肖像；号码原本是医疗识别工具，后来被重新编辑成关于分类、存活与国家系统的系列。', actions: ['医疗行动合作', '正面肖像', '号码牌', '档案再编辑'], sourceUrl: 'https://www.artic.edu/artworks/249641/marcados-marked', images: [], relations: [rel('收藏', 'Art Institute of Chicago', 'Marcados works')] },
    { title: 'CCPY / Yanomami political advocacy', cluster: 'activism / land / health / image circulation', period: 'late 1970s–1990s', summary: '摄影同时进入 Yanomami 土地、健康和权利倡议，不再只是展览材料。', actions: ['政治组织', '图像公共传播', '档案 / 报告', '权利倡议'], sourceUrl: 'https://www.fondationcartier.com/en/exhibitions/claudia-andujar-the-yanomami-struggle', images: [], relations: [] },
    { title: 'Genocide of the Yanomami: Death of Brazil / The Yanomami Struggle', cluster: 'archive re-edit / survey / installation', period: '1989–2020s', summary: '重新处理早期档案并加入滤色、重拍和展览编排，把几十年的影像、Yanomami drawing 和政治历史组织为大型机构叙事。', actions: ['旧档案重拍 / 重新着色', '跨年代编辑', '大规模展览装置', '与 Yanomami drawings 并置'], sourceUrl: 'https://www.fondationcartier.com/en/exhibitions/claudia-andujar-the-yanomami-struggle', images: [], relations: [rel('展览', 'Fondation Cartier — The Yanomami Struggle', '2020')] }
  ], awards: [], exhibitions: ['Fondation Cartier 2020', 'Barbican / international tour contexts'], sources: [{ label: 'Fondation Cartier', url: 'https://www.fondationcartier.com/en/exhibitions/claudia-andujar-the-yanomami-struggle' }] },
  'santu-mofokeng': { artistId: 'santu-mofokeng', projectCoverage: '5 个 apartheid / 精神性 / 家庭档案项目已完成第一轮 · 1986–2013', imageCoverage: '', note: '从通勤火车教会、农村劳工到黑人家庭工作室档案与精神景观，补出他为何反对把南非黑人生活压缩成新闻冲突。', projects: [
    { title: 'Train Church', cluster: 'commuter train / spirituality / everyday apartheid', period: '1986', summary: '拍摄 Soweto—Johannesburg 通勤列车上自发进行的教会服务，宗教、通勤和 apartheid 城市结构发生在同一个车厢。', actions: ['通勤列车长期拍摄', '黑白摄影', '礼拜动作观察'], sourceUrl: 'https://santumofokengfoundation.com/santu-mofokeng-photography-train-church', images: [], relations: [] },
    { title: 'Labour Tenants / Going Home', cluster: 'rural labour / migration / home', period: 'late 1980s–1990s', summary: '处理农场劳工、城乡迁移和“回家”经验，让 apartheid 不只以示威和警察图像出现。', actions: ['乡村田野', '家庭 / 劳动摄影', '摄影散文'], sourceUrl: 'https://santumofokengfoundation.com/santu-mofokeng-bibliography', images: [], relations: [] },
    { title: 'The Black Photo Album / Look at Me: 1890–1950', cluster: 'family archive / commissioned studio portrait / reprocessing', period: '1997', summary: '收集南非黑人家庭主动委托的历史工作室肖像，调查人物、阶级和家族叙事；原照被扫描、数字修复后再通过网片制作接触印相。', actions: ['家庭档案征集', '人物 / 家族研究', '扫描', 'Photoshop 修复', 'screen negative / contact print', '80幅黑白幻灯投影'], sourceUrl: 'https://santumofokengfoundation.com/santu-mofokeng-photography-black-photo-album', images: [img('https://www.moma.org/media/W1siZiIsIjU5NDU3NiJdLFsicCIsImNvbnZlcnQiLCItcXVhbGl0eSA5MCAtcmVzaXplIDIwMDB4MjAwMFx1MDAzZSJdXQ.jpg?sha=fd0b0bcb35c1d085', 'The Black Photo Album', '© Santu Mofokeng', 'https://santumofokengfoundation.com/santu-mofokeng-photography-black-photo-album', 'Santu Mofokeng Foundation / MoMA documentation')], relations: [rel('展览', '2nd Johannesburg Biennale', '1997'), rel('收藏', 'MoMA', 'acquired works')] },
    { title: 'Chasing Shadows', cluster: 'spiritual landscape / cave / community', period: '1990s–2008', summary: '长期拍摄 Motouleng 等宗教地点的祈祷、洞穴、仪式和景观，把精神经验作为真实社会生活的一部分。', actions: ['长期返回宗教地点', '黑白摄影', '景观 / 仪式 / 肖像并置'], sourceUrl: 'https://santumofokengfoundation.com/santu-mofokeng-photography-chasing-shadows', images: [], relations: [rel('展览', 'Chasing Shadows — Thirty Years of Photographic Essays', 'Jeu de Paume 2011 and tour')] },
    { title: 'German Pavilion — Venice', cluster: 'cross-national pavilion / retrospective context', period: '2013', summary: '与 Ai Weiwei、Romuald Karmakar、Dayanita Singh 共同进入 German Pavilion，使南非摄影与“国家馆”制度发生非国籍化关系。', actions: ['跨项目选片', '国家馆语境重编'], sourceUrl: 'https://santumofokengfoundation.com/about', images: [], relations: [rel('展览', '55th Venice Biennale — German Pavilion', '2013')] }
  ], awards: ['Ernest Cole Scholarship 1991', 'Mother Jones Award for Africa 1992', 'Fondazione Fotografia Modena International Photography Prize 2016'], exhibitions: ['Jeu de Paume 2011', 'German Pavilion — Venice 2013'], sources: [{ label: 'Santu Mofokeng Foundation', url: 'https://santumofokengfoundation.com/about' }, { label: 'Black Photo Album', url: 'https://santumofokengfoundation.com/santu-mofokeng-photography-black-photo-album' }] },
  'yee-i-lann': { artistId: 'yee-i-lann', projectCoverage: '5 个 photomedia / 殖民档案 / 纺织合作节点已完成第一轮 · 2005–2024', imageCoverage: '', note: '从数字 photomontage 逐渐进入 Sabah 社群织席合作，重点看“table / mat”如何把殖民行政权力转换成实际制作关系。', projects: [
    { title: 'Sulu Stories', cluster: 'colonial archive / photomontage / regional history', period: '2005', summary: '使用 photomedia 与历史视觉材料重新构造 Sulu、边界与殖民历史，数字拼贴让官方图像的权力关系被重新排列。', actions: ['殖民档案研究', '数字拼贴', 'photomedia print', '跨图像叙事'], sourceUrl: 'https://www.mori.art.museum/en/collection/2384/index.html', images: [img('https://www.mori.art.museum/assets_c/2019/05/063_yeeilann_sulu_highnoon-thumb-1000x999-4829.jpg', 'Sulu Stories related work', '© Yee I-Lann', 'https://www.mori.art.museum/en/collection/2384/index.html', 'Mori Art Museum')], relations: [rel('收藏', 'Mori Art Museum', 'multiple Sulu Stories works')] },
    { title: 'Picturing Power', cluster: 'colonial visual codes / staged photomontage', period: '2013', summary: '把殖民行政、人物姿态和摄影权力变成一套可被重新编排的视觉语法。', actions: ['历史图像研究', '数字 montage', '人物编排', '大型打印'], sourceUrl: 'https://www.singaporeartmuseum.sg/Art-Events/Exhibitions/Yee-I-Lann-Mansau-Ansau', images: [], relations: [] },
    { title: 'Measuring Project / Untitled Self-Portrait', cluster: 'measurement / body / return to Sabah', period: '2017–2018', summary: '通过桌子、身体、地图与测量逻辑思考殖民治理中的标准化，同时标记艺术家从 Kuala Lumpur 返回 Sabah 的转折。', actions: ['自我表演', '物件搭建', '摄影合成', '测量作为概念规则'], sourceUrl: 'https://borneoheart.yeeilann.com/essay-tikar-tamu-bahasa/', images: [], relations: [] },
    { title: 'Tikar / Meja', cluster: 'woven mat / table / collective production', period: '2018–2023', summary: '与 Sabah 多个织席社群合作，把象征殖民、父权与行政权力的“桌子”织进 60 张 communal mats，以地面平台对抗桌面的等级关系。', actions: ['与织工长期合作', '图像转换成编织图案', '60张 woven mats', '社区生产 / 署名'], sourceUrl: 'https://www.ngv.vic.gov.au/triennial-2023/artists-designers/yee-i-lann/', images: [], relations: [rel('展览', 'NGV Triennial', '2023–2024')] },
    { title: 'Borneo Heart / Mansau-Ansau', cluster: 'community / weaving / living exhibition', period: '2021–2024', summary: 'Borneo Heart 不只是单个展览，而是以 tikar 和 tamu 为核心的合作网络；Mansau-Ansau 继续把“游走路径”变成新的编织语法。', actions: ['社区协作', '织席', '工作坊 / tamu', '录像 / 摄影', '跨场地展览'], sourceUrl: 'https://borneoheart.yeeilann.com/borneo-heart-in-kl/', images: [], relations: [rel('展览', 'Singapore Art Museum — Mansau-Ansau', '2024')] }
  ], awards: [], exhibitions: ['Borneo Heart 2021–', 'Aichi Triennale 2022', 'NGV Triennial 2023', 'Singapore Art Museum 2024'], sources: [{ label: 'Borneo Heart', url: 'https://borneoheart.yeeilann.com/' }, { label: 'Mori Art Museum collection', url: 'https://www.mori.art.museum/en/collection/2384/index.html' }] }
};
