import type { ArtistArchive, ArchiveProject, ArchiveRelation } from './archiveData';
const rel=(kind:ArchiveRelation['kind'],label:string,detail?:string):ArchiveRelation=>({kind,label,detail});
const project=(p:ArchiveProject)=>p;
export const archiveBatch284:Record<string,ArtistArchive>={
'carrie-mae-weems':{
artistId:'carrie-mae-weems',
projectCoverage:'继续深化 Carrie Mae Weems：不重复既有 Kitchen Table / Sea Islands 总述，重点补足 From Here I Saw What Happened and I Cried 的档案挪用生产链、Coming Up for Air 的录像转向，以及 Guggenheim 2014 回顾展所呈现的三十年媒介演变与机构网络。',
imageCoverage:'登记 MoMA、National Gallery of Art 与 Guggenheim 权威页面作为图像入口；MoMA 明确要求作品及安装图复制许可，因此不复制受限图片到仓库。',
note:'Weems 的关键不只是“黑人女性身份摄影”。她不断改变谁在说话、谁被观看、图像从哪里来以及观看发生在什么制度里：自传/家庭摄影→导演式自拍→民俗与历史研究→挪用殖民/科学档案→录像、声音与装置。',
projects:[
project({title:'From Here I Saw What Happened and I Cried — archival images re-authored through framing, tint and text',cluster:'appropriation / archive / race / text-image installation',period:'1995–1996',summary:'Weems 回到19、20世纪既有摄影档案，研究非裔美国人如何被科学、民族志、新闻和摄影史塑造成“类型”而不是拥有主体性的人。MoMA 说明项目源于 Getty 1994年的委托，她使用 Jackie Napoleon Wilson 收藏、博物馆与大学档案、National Geographic 以及 Walker Evans、Robert Frank、Garry Winogrand 等既有图像。她并非原样展示档案，而是裁切、统一尺度、染成红/蓝色调，以圆形遮罩强化“镜头/观看”结构，再在玻璃上加入文字。',actions:['检索并选择历史上由他人生产的黑人身体图像，而不是重新拍摄新的“受害者肖像”。','放大、裁切并统一异质档案图像的尺度与格式。','加入红色和蓝色色调，使历史照片脱离所谓中性档案外观。','以圆形/椭圆形遮罩强调摄影镜头和观看行为。','在玻璃表面加入文字，让被观看的历史主体与当代观看者之间形成新的叙述声音。'],sourceUrl:'https://www.moma.org/artists/7177-carrie-mae-weems',images:[],relations:[rel('委托','J. Paul Getty Museum','MoMA 记录项目由 Getty 于1994年委托 Weems 回应19世纪非裔美国人历史摄影。'),rel('收藏','Museum of Modern Art, New York','MoMA 保存该系列重要作品；媒介为 chromogenic print with sand-blasted text on glass。'),rel('档案','Jackie Napoleon Wilson collection / museum and university archives','历史照片并非单一来源，而是跨私人收藏、机构档案与摄影史图像重新编排。')] }),
project({title:'From Here I Saw What Happened and I Cried — 34-part installation as a counter-history of looking',cluster:'installation / sequence / witnessing / counter-archive',period:'1995–1996; MoMA gallery 2020–2021',summary:'MoMA 将完整作品登记为34幅图像。系列首尾以一位 Mangbetu 女性作为见证者框住叙事，中间包含 Louis Agassiz 为种族主义理论而委托 Joseph T. Zealy 拍摄的1850年被奴役者照片等材料。Weems 让“档案证据”反过来成为关于摄影自身暴力的证据：作品讨论的不只是照片里发生了什么，而是谁有权命名、分类和传播照片中的人。',actions:['把34件作品组织成具有开端、推进与结尾的长序列，而非独立墙面照片。','让一位历史图像中的女性承担观看/见证整个叙事的结构角色。','把原本服务于种族分类的摄影重新放入批判摄影制度的语境。','用连续文字把“你被怎样定义”变成贯穿系列的第二叙事层。'],sourceUrl:'https://www.moma.org/calendar/galleries/5255',images:[],relations:[rel('展览','MoMA Collection 1980–Today, Gallery 211','2020–2021以完整专题空间重新展示；由 Roxana Marcoci 与 Dana Ostrander 组织。'),rel('研究','photography and racial pseudoscience','Joseph T. Zealy 1850影像原本由 Louis Agassiz 委托，用于支持种族主义理论；Weems 将其制度目的纳入作品批判。')] }),
project({title:'Coming Up for Air — narrative photography expands into moving image, music and montage',cluster:'video / narrative / music / history / relationships',period:'2003–2004',summary:'Guggenheim 将 Coming Up for Air 视为 Weems 第一件重要录像作品。它不是单一纪录片故事，而由彼此独立又互相呼应的诗性片段组成：包括内战前 New Orleans 的黑人男性与白人女性关系、试图和解的姐妹、孩子与父亲，以及令人联想到 Winnie 与 Nelson Mandela 的年轻恋人。录像使她原本依靠照片＋文字完成的叙事进入时间、声音、音乐和剪辑。',actions:['把多个并非线性因果关系的短叙事并置为录像结构。','继续处理种族、亲密关系、家庭与政治历史，但让人物在时间中出现而非凝固为单张照片。','将音乐和声音纳入叙事方法；Guggenheim 明确指出 video 为她提供了引入音乐的机会。','以 montage 让私人关系与更大的历史/政治记忆互相映照。'],sourceUrl:'https://www.guggenheim.org/press-release/guggenheim-presents-carrie-mae-weems-three-decades-of-photography-and-video',images:[],relations:[rel('展览','Guggenheim New Media Theater','2014回顾展期间在 Sackler Center 放映 Coming Up for Air。'),rel('媒介','photography → video / sound / music','Guggenheim 将录像描述为她叙事摄影实践的自然延伸。')] }),
project({title:'Three Decades of Photography and Video — institutional map of a changing practice',cluster:'retrospective / institutional network / practice evolution',period:'24 Jan–14 May 2014',summary:'Guggenheim 的大型回顾展把 Weems 三十余年实践放在近乎时间顺序中：从 Family Pictures and Stories 的家庭/自传纪录，到 Kitchen Table 的导演式照片＋文本、Sea Islands/Africa/Slave Coast 的语言与历史研究、From Here I Saw What Happened 的档案挪用，再到 Dreaming in Cuba、Louisiana Project、Roaming 的地点/建筑研究以及录像。这个机构节点很适合作为网站关系图的主枢纽，因为它显示 Weems 的题材持续围绕历史、身份与权力，但媒介和作者位置不断改变。',actions:['以回顾展结构把早期纪录摄影、自拍表演、文本、档案挪用、地点研究、录像和声音放进同一演变链。','将不同系列按照方法变化而非仅按“race/gender”主题重新关联。','建立 Weems 与 Guggenheim、MoMA、Whitney、ICA Boston、New Museum 等机构的长期展示网络。'],sourceUrl:'https://www.guggenheim.org/exhibition/carrie-mae-weems-three-decades-of-photography-and-video',images:[],relations:[rel('展览','Solomon R. Guggenheim Museum','24 Jan–14 May 2014；综合摄影、文字、audio recordings 与 video。'),rel('策展','Jennifer Blessing / Susan Thompson','Guggenheim摄影与策展团队构成回顾展的重要机构关系。'),rel('双年展','Whitney Biennial 1991','Guggenheim履历记录的重要早期国际/机构节点。'),rel('双年展','2nd Johannesburg Biennale 1997','将 Weems 的机构网络从美国扩展至国际双年展系统。')] })
],
awards:[],
exhibitions:['Whitney Biennial — 1991','2nd Johannesburg Biennale — 1997','Carrie Mae Weems: Three Decades of Photography and Video — Guggenheim — 2014','Carrie Mae Weems: Kitchen Table Series — National Gallery of Art — 2017–18','Carrie Mae Weems’s From Here I Saw What Happened and I Cried — MoMA — 2020–21'],
sources:[{label:'MoMA — Carrie Mae Weems artist / From Here I Saw What Happened and I Cried',url:'https://www.moma.org/artists/7177-carrie-mae-weems'},{label:'MoMA — Gallery 211 complete installation',url:'https://www.moma.org/calendar/galleries/5255'},{label:'Guggenheim — Three Decades of Photography and Video',url:'https://www.guggenheim.org/exhibition/carrie-mae-weems-three-decades-of-photography-and-video'},{label:'Guggenheim — retrospective press / chronology',url:'https://www.guggenheim.org/press-release/guggenheim-presents-carrie-mae-weems-three-decades-of-photography-and-video'},{label:'National Gallery of Art — Kitchen Table Series',url:'https://www.nga.gov/exhibitions/carrie-mae-weems-kitchen-table-series'}]
}
};
