import type { ArtistArchive, ArchiveProject, ArchiveRelation } from './archiveData';
const rel=(kind:ArchiveRelation['kind'],label:string,detail?:string):ArchiveRelation=>({kind,label,detail});
const project=(p:ArchiveProject)=>p;

export const archiveBatch312:Record<string,ArtistArchive>={
 'sophie-calle':{
  artistId:'sophie-calle',
  projectCoverage:'作品级深化 Sophie Calle：Suite Vénitienne、The Hotel、The Address Book、Last Seen… / What Do You See?、Exquisite Pain、Take Care of Yourself。重点补齐规则设定、跟踪/调查、文本—照片结构、缺席与记忆、私人经验向多人解释系统的转化。',
  imageCoverage:'Mudam、SFMOMA、Walker、Gardner Museum、Hara Museum、Whitechapel Gallery 等官方页面提供作品或展览图；本站保存官方研究入口，未确认自由再发布权利时 images 留空。',
  note:'Calle 的核心不是简单“把私生活变成艺术”，而是先设计一条行为规则，再让现实中的陌生人、房间、失窃物、分手邮件和他人的证词进入规则。摄影常常不是终点，而是证据、线索或叙事部件；文本、采访、地图、录像、物件和展陈共同决定作品。她从自己跟踪别人，逐渐发展到让他人替自己观看、回忆、解释和处理经验。',
  projects:[
   project({title:'Suite Vénitienne',cluster:'following / rule-based action / photography + text / surveillance',period:'1979–1980; later reconfigured',summary:'Calle 在巴黎开始随机跟随陌生人，后来偶然再次遇见其中一名男子并得知他将去威尼斯，于是前往威尼斯继续寻找和跟踪他。Mudam 将其列为她早期关键作品，并说明作品以大量偷拍式照片、路线地图与侦探笔记般的文字共同构成；图像并不独立证明事实，而是与第一人称想法、时间记录和追踪路线一起制造一种介于调查报告、日记和虚构叙事之间的可信度。项目因此建立了 Calle 后来反复使用的基本协议：先给自己一条行动规则，再把规则产生的现实遭遇编辑成照片—文字系统。',actions:['把“跟随一个陌生人”设为行为规则，而不是先寻找传统摄影题材。','从巴黎的偶遇延伸到威尼斯的实际追踪，让城市路线成为作品结构。','以隐蔽、远距离的照片作为行动痕迹，同时记录时间、地点、路线和个人判断。','将照片、地图和侦探笔记式文本重新编排，使证据与主观叙述互相支持又互相怀疑。'],sourceUrl:'https://www.mudam.com/fr/collection/sophie-calle',images:[],relations:[rel('收藏/研究','Mudam Luxembourg — Suite Vénitienne','官方馆藏将其视为 Calle 早期关键作品，并说明照片、地图和侦探式文字的组合。'),rel('方法关系','rule → action → trace → narrative','艺术家的主要控制点不是单幅照片，而是行动协议及其后续编辑。')]}),
   project({title:'The Hotel',cluster:'hotel room / chambermaid / forensic observation / private-public boundary',period:'1981–1983',summary:'Calle 为进入陌生人的私人空间而在威尼斯酒店担任客房服务员。SFMOMA 馆藏保存 L’hôtel, chambre 25 等作品。方法的关键不是偷拍住客本人，而是在合法工作身份允许进入房间的时间窗口里观察床铺、行李、衣物、垃圾、照片和其他遗留痕迹，再以摄影和文字重建一个从未真正认识的人。作品把酒店房间变成一种临时档案：住客离开后，物件排列仍然泄露生活习惯，但这种“认识”始终建立在片段证据与艺术家的推断之上。',actions:['通过成为酒店 chambermaid 获得进入客房的制度性权限。','在住客不在场时观察并摄影房间、行李和日常物件，而非直接制作人物肖像。','记录日期、房号、物件状态与自己的判断，把客房转化为短暂的证据现场。','将文字和照片并列，使观众同时看到物质痕迹与艺术家如何解释这些痕迹。'],sourceUrl:'https://www.sfmoma.org/artist/Sophie_Calle/',images:[],relations:[rel('收藏','SFMOMA — L’hôtel, chambre 25','SFMOMA 在线馆藏列出 1981–1983 的 The Hotel / Room 25。'),rel('方法关系','portrait without sitter','人物缺席时，以其留下的物件、空间和文字推断建立“肖像”。')]}),
   project({title:'The Address Book',cluster:'social network reconstruction / interview / privacy / publication',period:'1983; book 2012',summary:'Calle 在巴黎街头捡到一本通讯录，复制其中信息后归还原主，并联系通讯录中的熟人，通过他们的描述间接拼出通讯录主人 Pierre D. 的形象。作品最初于1983年8月2日至9月4日在 Libération 连载，后来因隐私争议长期停止再版，2012年才完整英译成书。Walker Art Center 收藏2012年版本；作品最重要的结构是“一个人不在场，但他的关系网络替他发声”：身份不由正面肖像提供，而由联系人、访谈、照片、编辑与出版机制共同生成。',actions:['复制偶然拾得的通讯录，把联系人名单转换成调查路径。','逐一联系通讯录中的熟人，通过访谈收集对主人不同甚至冲突的描述。','不以主人本人作为主要视觉中心，而让关系网络拼出间接肖像。','把调查结果连续发表在报纸，使私人网络进入公共媒介，并让隐私伦理成为作品不可分割的一部分。'],sourceUrl:'https://www.walkerart.org/collections/artwork/the-address-book/',images:[],relations:[rel('收藏','Walker Art Center Library — The Address Book','2012；offset print on paper；Rosemary Furtak Collection。'),rel('出版','Libération — 1983 serial','书目记录确认原作于1983-08-02至09-04在日报连续发表。'),rel('方法关系','person → contacts → testimonies → constructed portrait','从直接观看个人转向通过社会关系网络间接建构身份。')]}),
   project({title:'Last Seen… / What Do You See?',cluster:'absence / museum memory / interview / institutional collaboration',period:'1991; revisited 2013',summary:'1990年 Isabella Stewart Gardner Museum 发生艺术品失窃后，Calle 与馆方合作研究“缺席如何被看见”。她采访策展人、保安、修复师和其他工作人员，让他们描述记忆中的失窃作品，再把这些文字与原来挂画位置的空缺照片配对，形成 Last Seen…。2013年她回到 Gardner：部分空画框已经重新挂回墙上，于是她不再主动告诉受访者那里曾有失窃作品，而是询问观众和员工“你看见什么？”，形成 What Do You See?。两次调查相隔二十多年，方法从回忆一个明确缺失物，推进到测试空框是否仍能让后来者意识到缺席。',actions:['进入真实博物馆失窃事件现场，但不重演犯罪或寻找赃物。','采访与失窃作品共同工作过的馆员、保安、修复师，让记忆替代已经消失的图像。','拍摄作品原先所在的空位，并与不同人的描述并置。','2013年改变提问协议：面对重新安装的空框，不提示失窃背景，只问人们实际看见什么。'],sourceUrl:'https://www.gardnermuseum.org/experience/contemporary-art/artists/calle-sophie',images:[],relations:[rel('机构','Isabella Stewart Gardner Museum — Boston','馆方支持1990–91项目，并于2013邀请 Calle 回访；官方页面保存两阶段方法说明。'),rel('机构人物','Anne Hawley — museum director','Gardner 官方记录她支持 Calle 在失窃后进入馆内开展项目。'),rel('方法关系','missing object → remembered image → empty frame','从缺失作品的集体记忆，推进到缺席本身是否还能被观看。')]}),
   project({title:'Exquisite Pain',cluster:'breakup / countdown-countup / testimony exchange / installation',period:'1984–2003; Hara Museum 1999–2000',summary:'Exquisite Pain 将一次私人分手转成严格的时间与叙事结构。Hara Museum 把作品分成两部分：Count down 由抵达分手发生之日前的照片、书信等材料组成；Count up 则让 Calle 反复讲述自己的痛苦，同时听取陌生人或他人生命中“最痛苦的经历”。随着重复，自己的故事逐渐发生变化并与他人的叙述形成比较。作品因此不是单纯展示失恋日记，而是把痛苦转换为可重复讲述、交换和编辑的社会协议。Hara Museum 1999–2000首次举办该作展览并在展后收藏，2019再次以整馆规模完整呈现。',actions:['把私人旅行与分手前的时间材料组织成倒数结构 Count down。','固定并反复讲述自己的分手故事，而不是只写一次自传。','邀请他人讲述各自最痛苦的经历，建立双向交换而非单向倾诉。','用照片、书信与文字的重复/变化让“恢复”通过叙事结构被观看。'],sourceUrl:'https://www.haramuseum.or.jp/en/hara/exhibition/413/',images:[],relations:[rel('展览/收藏','Hara Museum of Contemporary Art — Tokyo','1999–2000展出后收藏；2019-01-05至03-28再次完整呈现。'),rel('结构','Count down / Count up','官方说明明确区分分手前倒数与通过交换痛苦经验逐渐恢复的第二部分。'),rel('方法关系','private pain → repeated narration → exchanged testimony','私人经验通过规则化重复和他人证词被转成集体叙事机制。')]}),
   project({title:'Take Care of Yourself / Prenez soin de vous',cluster:'delegated interpretation / email / professions / polyphonic installation',period:'2007',summary:'Calle 收到伴侣以“Prenez soin de vous / Take care of yourself”结束的分手邮件后，没有独自解释，而是把邮件交给107位女性，请她们依据各自职业、专业或实践方式进行分析和回应。Whitechapel Gallery 记录参与者从芭蕾舞者到律师，最终形成大型装置；作品也是2007年第52届威尼斯双年展法国馆的重要项目。这里艺术家把作者位置进一步外包：同一封私人文本被法律、语言、舞蹈、表演等不同知识体系反复处理，个人伤害被转成一个多声部解释机器。',actions:['把收到的真实分手邮件设为固定输入，而不是自己重新写一封文学文本。','邀请107位女性按自己的职业技能和知识框架解释同一文本。','允许分析、朗读、表演和其他专业回应并存，不追求唯一正确解释。','将大量异质回应组织成大型展览装置，使观看者面对的是解释系统而非单一私人叙事。'],sourceUrl:'https://www.whitechapelgallery.org/exhibitions/sophie-calle-talking-to-strangers/',images:[],relations:[rel('双年展','52nd Venice Biennale — French Pavilion — 2007','Take Care of Yourself 是 Calle 代表法国参展的核心项目。'),rel('展览','Whitechapel Gallery — Talking to Strangers — 2009-10-16–2010-01-03','英语版 Take Care of Yourself 在该展首展，并与1980年代以来作品并置。'),rel('方法关系','self interpretation → delegated interpretation','从艺术家讲自己的故事推进到让107个专业位置共同生产作品。')]})
  ],
  awards:['Hasselblad Award — 2010'],
  exhibitions:['52nd Venice Biennale — French Pavilion — 2007','Sophie Calle: Talking to Strangers — Whitechapel Gallery — 2009-10-16–2010-01-03','Sophie Calle, Exquisite Pain — Hara Museum of Contemporary Art — 1999–2000; restaged 2019','Last Seen / What Do You See? — Isabella Stewart Gardner Museum — 2013'],
  sources:[{label:'Mudam — Sophie Calle / Suite Vénitienne',url:'https://www.mudam.com/fr/collection/sophie-calle'},{label:'SFMOMA — Sophie Calle collection',url:'https://www.sfmoma.org/artist/Sophie_Calle/'},{label:'Walker Art Center — The Address Book',url:'https://www.walkerart.org/collections/artwork/the-address-book/'},{label:'Isabella Stewart Gardner Museum — Sophie Calle',url:'https://www.gardnermuseum.org/experience/contemporary-art/artists/calle-sophie'},{label:'Hara Museum — Exquisite Pain',url:'https://www.haramuseum.or.jp/en/hara/exhibition/413/'},{label:'Whitechapel Gallery — Talking to Strangers',url:'https://www.whitechapelgallery.org/exhibitions/sophie-calle-talking-to-strangers/'}]
 }
};