import type { ArtistArchive, ArchiveProject, ArchiveRelation } from './archiveData';

const rel=(kind:ArchiveRelation['kind'],label:string,detail?:string):ArchiveRelation=>({kind,label,detail});
const project=(p:ArchiveProject)=>p;

export const archiveBatch272:Record<string,ArtistArchive>={
  'hito-steyerl':{
    artistId:'hito-steyerl',
    projectCoverage:'本批新增 3 个关键节点，补足从 essay film、可见性政治到数据化劳动/沉浸装置的演变。',
    imageCoverage:'3 / 3 均建立 MoMA / MOCA 权威图像与展览入口；未确认开放许可的图像不复制。',
    note:'重点不是重复“数字图像批判”标签，而是把每件作品的素材来源、剪辑动作、展陈机制和制度关系拆开。',
    projects:[
      project({title:'November — image afterlife as political method',cluster:'essay film / memory / militancy / circulation',period:'2004',summary:'《November》把 Steyerl 青少年时期与朋友 Andrea Wolf 合作拍摄的业余武打片，与 Wolf 后来参加库尔德解放运动、死亡后在新闻和政治传播中出现的图像重新剪接。MoMA 将作品确认为25分钟彩色有声录像，并指出它混合 Kurdish television 的纪录素材、两人少年时期的电影片段、Bruce Lee 电影和 Steyerl 第一人称旁白。作品的核心因此不是为 Wolf 建立线性传记，而是追踪同一个身体如何从朋友、演员变成政治行动者，再变成记忆和传播中的图像。',actions:['取回艺术家与 Andrea Wolf 青少年时期共同制作的业余武打影像。','并置 Kurdish television 新闻/纪录素材与流行武打电影片段。','加入第一人称旁白，使私人记忆与公共政治图像相互校正。','通过剪辑追踪人物身份如何随图像传播发生变化，而不是把影像当作稳定证据。'],sourceUrl:'https://www.moma.org/collection/works/179811',images:[],relations:[rel('收藏','Museum of Modern Art','Video (color, sound), 25 min；Committee on Media and Performance Art Funds。'),rel('展览','Scenes for a New Heritage — MoMA','2015–2016；MoMA gallery label 将本作视为其后续影像政治实践的重要早期节点。')]}),
      project({title:'How Not to Be Seen — resolution target as stage',cluster:'visibility / surveillance / instructional parody / resolution',period:'2013',summary:'这件14分钟单屏 .MOV 并非抽象讨论“监控”。Steyerl 实际在美国沙漠中废弃的航空摄影 calibration targets 上拍摄：这些巨大线条/标记曾用于测试飞机相机分辨率。她把这个军事—摄影基础设施改造成荒诞教学片舞台，以自动化男声、绿幕/无脸数字人物、桌面界面和身体示范讲解“如何不被看见”。作品由此把 resolution 从技术参数翻转成政治问题：谁能被成像、谁能消失、谁在屏幕后观看和行动。',actions:['选择真实航空摄影 calibration target 作为外景，而非搭建中性摄影棚。','借用 how-to instructional video 的章节和自动化旁白语法。','让艺术家、无脸人物与数字/绿幕角色示范缩小、隐藏、消失等动作。','把电脑桌面和虚拟图层覆盖到真实沙漠，使物理空间与界面空间合并。','以幽默教学格式连接摄影分辨率、无人机观看、隐私与政治性消失。'],sourceUrl:'https://www.moma.org/explore/inside_out/2014/06/18/hito-steyerls-how-not-to-be-seen-a-fucking-didactic-educational-mov-file/',images:[],relations:[rel('收藏','Museum of Modern Art','2013 single-screen 1080p .mov；14 min；2014进入 MoMA collection。'),rel('展览','Cut to Swipe — MoMA','2014–2015；被置于电子媒体图像挪用、操纵与数字传播技术的谱系中。')]}),
      project({title:'Factory of the Sun — motion capture as labor regime',cluster:'motion capture / data labor / surveillance / game space',period:'2015–2016',summary:'《Factory of the Sun》把展厅改造成近似 motion-capture / game grid 的沉浸环境。MOCA 说明作品最初在2015 Venice Biennale German Pavilion亮相，随后于2016年在洛杉矶举行美国首展。影片在新闻报道、纪录片、电子游戏与网络舞蹈视频之间高速切换，并讲述工人的动作在 motion-capture studio 中被强制捕获、转化成“人工阳光”的超现实故事。这里身体不只是被摄像机代表，而是直接成为可提取的数据和生产资料。',actions:['混合 news reportage、documentary、video-game aesthetics 与 internet dance videos。','把 motion capture 设定为故事中的劳动机制，让身体动作被转换成数据/光。','用蓝色发光网格延伸银幕空间，使观众站进类似捕捉/游戏坐标系。','通过高速剪辑把娱乐、监控、资本和集体抵抗压进同一视觉系统。'],sourceUrl:'https://www.moca.org/exhibitions/hito-steyerl-factory-of-the-sun',images:[],relations:[rel('展览','German Pavilion — Venice Biennale','2015；作品首次亮相的重要国际节点。'),rel('展览','MOCA Grand Avenue, Los Angeles','21 Feb–12 Sep 2016；U.S. premiere；organized by Lanka Tattersall。'),rel('策展','Lanka Tattersall','MOCA Assistant Curator；组织洛杉矶个展。')]})
    ],
    awards:[],
    exhibitions:['German Pavilion, Venice Biennale — 2015','Hito Steyerl: Factory of the Sun — MOCA Los Angeles — 2016','Cut to Swipe — MoMA — 2014–2015'],
    sources:[{label:'MoMA — Hito Steyerl / November',url:'https://www.moma.org/collection/works/179811'},{label:'MoMA — How Not to Be Seen',url:'https://www.moma.org/explore/inside_out/2014/06/18/hito-steyerls-how-not-to-be-seen-a-fucking-didactic-educational-mov-file/'},{label:'MOCA — Factory of the Sun',url:'https://www.moca.org/exhibitions/hito-steyerl-factory-of-the-sun'}]
  },
  'anicka-yi':{
    artistId:'anicka-yi',projectCoverage:'本批新增 2 个核心装置节点，重点补足实验室协作、活体材料、气味与机器生态的制作机制。',imageCoverage:'2 / 2 建立 Guggenheim / Tate 权威入口；不复制未确认开放授权图像。',note:'把 Yi 从“奇异材料艺术家”改写为研究感知、生命政治与机器生态的系统型实践。',
    projects:[
      project({title:'Life Is Cheap — museum as microbial / ant laboratory',cluster:'bacteria / ants / scent / sensory politics',period:'2017',summary:'作为2016 Hugo Boss Prize获奖后的 Guggenheim 个展，《Life Is Cheap》把微生物、蚂蚁与气味真正带入美术馆生产链。Guggenheim 的制作记录显示，一组大型玻璃结构容纳活蚂蚁群落；另一组冷藏面板保存从曼哈顿 Chinatown 与 Koreatown 地点采集、培养的细菌样本。展览还使用定制气味。这里“实验室美学”不是装饰：科学家、策展人、艺术家和美术馆技术团队共同维持活体/低温材料，使洁净、外来物、种族化焦虑和感官判断成为作品的物质条件。',actions:['从 Chinatown 与 Koreatown 的现实地点采集并培养微生物样本。','把培养后的细菌置入需要制冷维持的展示面板。','在大型镜面玻璃结构中引入并维持活蚂蚁群落。','设计定制气味，使嗅觉与视觉材料同时参与观看。','与科学家、策展人和 art handlers 协作，把博物馆转成需要持续维护的生命系统。'],sourceUrl:'https://www.guggenheim.org/articles/checklist/the-making-of-anicka-yis-artwork-at-the-guggenheim',images:[],relations:[rel('奖项','Hugo Boss Prize 2016','Yi 为2016获奖者；奖项展于2017年举行。'),rel('展览','Life Is Cheap — Solomon R. Guggenheim Museum','21 Apr–5 Jul 2017；organized by Katherine Brinson and Susan Thompson。'),rel('策展','Katherine Brinson / Susan Thompson','Guggenheim contemporary art curators；共同组织展览。')]}),
      project({title:'In Love With the World — aerobes as machine ecology',cluster:'AI / robotics / scent / post-industrial ecology',period:'2021–2022',summary:'Tate Hyundai Commission 把 Turbine Hall 原本的发电机器空间重新交给机器生命。Yi 制作会漂浮的“aerobes”，让它们依据环境因素表现个体与群体行为；作品由此不把机器人当作执行固定动作的雕塑，而把 AI/机器行为放进空气、建筑、观众和群体运动组成的生态。气味同样被释放到空气中，并连接场地跨越长期历史的不同气味记忆。作品把她早期微生物与嗅觉研究推进到“机器是否也能成为生态行动者”。',actions:['为 Turbine Hall 制作可在巨大空间中漂浮运动的 aerobe 机器实体。','设计个体与群体行为，使其响应环境而非只重复固定编舞。','让观众与机器共享同一空气和运动空间，观看关系变成共处关系。','制作并释放与场地历史相关的气味层，使建筑的时间通过嗅觉进入装置。','把生物、AI、机器人和空气政治组织为同一生态问题。'],sourceUrl:'https://shop.tate.org.uk/hyundai-commission-2021-anicka-yi/26145.html',images:[],relations:[rel('展览','Hyundai Commission: Anicka Yi — Tate Modern Turbine Hall','2021；大型委任项目。'),rel('出版','Hyundai Commission: Anicka Yi — Tate','与艺术家密切合作出版，包含既往实践综述与 aerobe 摄影。')]})
    ],awards:['Hugo Boss Prize — Winner — 2016'],exhibitions:['Life Is Cheap — Guggenheim — 2017','Hyundai Commission: Anicka Yi — Tate Modern — 2021'],sources:[{label:'Guggenheim — Life Is Cheap',url:'https://www.guggenheim.org/video/the-hugo-boss-prize-2016-anicka-yi-life-is-cheap'},{label:'Guggenheim — Making of Anicka Yi',url:'https://www.guggenheim.org/articles/checklist/the-making-of-anicka-yis-artwork-at-the-guggenheim'},{label:'Tate — Hyundai Commission publication',url:'https://shop.tate.org.uk/hyundai-commission-2021-anicka-yi/26145.html'}]
  },
  'zanele-muholi':{
    artistId:'zanele-muholi',projectCoverage:'本批新增 2 个媒介/机构节点：大型Tate调查展与雕塑扩展，补足从摄影视觉行动主义到公共纪念物的变化。',imageCoverage:'2 / 2 记录 Tate 官方入口；版权未开放的摄影不复制。',note:'此前已有 Faces and Phases / Somnyama Ngonyama 深化；本批避免重复，重点补机构网络和摄影之外的媒介演变。',
    projects:[
      project({title:'Zanele Muholi — Tate Modern survey as activist archive',cluster:'survey / LGBTQIA+ archive / institutional network',period:'2024–2025',summary:'Tate Modern 于2024年6月6日至2025年1月26日举行 Muholi 大型调查展。Tate资料称展览呈现超过260幅摄影，覆盖其二十余年的摄影与行动主义实践；配套出版物把早期为南非 Black lesbian、gay、bisexual、trans、queer 与 intersex 社群建立非污名化视觉表述的工作，与后来强烈自画像并置。这个机构节点的重要性在于：Faces and Phases 等长期参与式档案不再作为单系列阅读，而与自画像、亲密关系、酷儿公共可见性和视觉行动主义共同形成跨二十年的连续系统。',actions:['从二十余年项目中重新编辑超过260幅摄影进入大型调查展。','把他者肖像、社群档案与艺术家自画像放入同一长期实践框架。','通过出版物的六篇委约论文、glossary 与 chronology 建立可继续研究的文本档案。','让摄影史、美术馆收藏体系与南非 LGBTQIA+ 行动主义形成明确机构连接。'],sourceUrl:'https://shop.tate.org.uk/zanele-muholi-hardback-exhibition-book/29361.html',images:[],relations:[rel('展览','Zanele Muholi — Tate Modern','6 Jun 2024–26 Jan 2025；展览超过260幅摄影。'),rel('出版','Zanele Muholi — Tate exhibition book','Sarah Allen / Yasufumi Nakamori 编辑；包含六篇委约论文、glossary、chronology。')]}),
      project({title:'Muholi V — bronze monument to rest',cluster:'bronze / public monument / rest / Black queer body',period:'2023–2024',summary:'《Muholi V》显示 Muholi 的实践已不局限于摄影。Tate 为2024展览制作的 maquette 资料确认原作为2023年的大型 bronze sculpture：一个独自躺卧的人体由垫枕支撑并被毯子轻柔覆盖。Muholi 借用传统公共纪念雕塑常见的青铜，却不纪念英雄行动，而把“休息、自我保存”变成值得被永久化的 Black queer 公共形象。这个媒介变化与 Somnyama Ngonyama 的自我表演形成反差：前者用镜头、道具和强烈凝视夺回观看权，这里则以重量、耐久材料和静止姿态争取公共空间中的休息权。',actions:['从摄影中的身体表演扩展到三维人体雕塑。','选择青铜这一与公共纪念物和永久性高度关联的材料。','让人物采取躺卧、被毯子保护的静止姿态，而非传统英雄纪念姿态。','把 Black queer self-care / rest 转换成可占据公共空间的纪念形式。','2024为 Tate 展览制作 polished bronze 小型 maquette，使作品进入版本与收藏传播系统。'],sourceUrl:'https://shop.tate.org.uk/zanele-muholi-muholi-v-maquette-2024/ed1111.html',images:[],relations:[rel('展览','Zanele Muholi — Tate Modern','2024–2025调查展语境。'),rel('收藏','Muholi V maquette — Tate edition','2024 polished bronze；25 × 12.7 × 6.5 cm；edition of 50。')]})
    ],awards:['ICP Infinity Award for Documentary and Photojournalism — 2016','Prince Claus Award — 2013','Fine Prize — Carnegie International — 2013'],exhibitions:['Zanele Muholi — Tate Modern — 2024–2025'],sources:[{label:'Tate — Zanele Muholi exhibition book',url:'https://shop.tate.org.uk/zanele-muholi-hardback-exhibition-book/29361.html'},{label:'Tate — Muholi V maquette',url:'https://shop.tate.org.uk/zanele-muholi-muholi-v-maquette-2024/ed1111.html'}]
  }
};
