import type { ArchiveProject, ArchiveRelation } from './archiveData';

const rel=(kind:ArchiveRelation['kind'],label:string,detail?:string):ArchiveRelation=>({kind,label,detail});

export const archiveExtensions266:Record<string,ArchiveProject[]>={
  'allan-sekula':[
    {title:'Aerospace Folktales',cluster:'family / class / military-industrial economy / photo-text-audio',period:'1973',summary:'Sekula 的第一件大型成熟作品已经把后来 Fish Story 的方法压缩在家庭尺度里。作品源自父亲——Lockheed 航空工程师——失业后的家庭处境。Columbus Museum of Art 保存的完成版由142张照片、一篇书面 commentary 与4段 audio interviews 组成；父亲的失业、母亲的家庭劳动、住宅空间和艺术家自身的阶级位置被并置。它不是“拍失业父亲”的家庭纪实，而是把一个家庭当作军事—航空工业经济波动如何进入日常生活的具体剖面。',actions:['从自己家庭内部开始研究阶级，而不是寻找一个外部“社会问题”作为题材。','持续拍摄住宅、家庭成员和日常物件，建立142张照片的序列。','分别录制家庭成员声音，使他们不只作为被摄影对象出现。','加入书面 commentary，把图像、声音与经济/阶级分析连接起来。','把父亲从 Lockheed 被裁员这一私人事件放回美国军工—航空产业结构中阅读。'],sourceUrl:'https://www.columbusmuseum.org/allan-sekula-aerospace-folktales-and-other-stories/',images:[],relations:[rel('收藏','Columbus Museum of Art','2015 acquisition；完成版含142 photographs、written commentary、4 audio interviews。'),rel('主题','family ↔ political economy','父亲作为 Lockheed aerospace engineer 的失业把家庭叙事直接连接军事工业经济。'),rel('方法','Aerospace Folktales → Fish Story','早期已经建立 photo + text + testimony 的复合纪录结构，后来扩展到全球港口与海运。')]}
  ],
  'latoya-ruby-frazier':[
    {title:'Flint Is Family In Three Acts',cluster:'environmental justice / collaboration / photography as intervention',period:'2016–21',summary:'Frazier 最初因 Elle 委托于2016年前往 Flint，随后把一次媒体任务扩展成与诗人、活动者、母亲 Shea S. Cobb 及其家庭长达五年的合作。Act I 从 Cobb 一家在铅污染水危机中的日常生活出发；Act II 跟随 Cobb 与女儿 Zion 反向迁往 Mississippi 的家族土地和淡水泉；Act III 回到 Flint，记录社区获得 atmospheric water generator。作品由照片、文字、诗歌、访谈与录像构成，摄影不只“见证危机”，还进入筹资、公共传播和实际取得净水资源的行动链。',actions:['把一次杂志委托延长为五年合作，而不是在新闻周期结束时离开。','让 Shea Cobb、Amber Hasan 等社区成员以合作者、诗人和行动者身份进入作品，而非匿名受害者。','用三幕结构连接 Flint 家庭生活、Mississippi 家族土地与返回 Flint 后的社区行动。','把照片与第一人称文本、诗歌、访谈和录像并置，持续保留当地人的语言。','在第三幕把艺术资源转成现实基础设施：围绕 atmospheric water generator 的取得、安装和社区使用继续工作。'],sourceUrl:'https://latoyarubyfrazier.com/news/flint-is-family-in-three-acts/',images:[],relations:[rel('合作','Shea S. Cobb / Amber N. Hasan','Flint 社区成员、艺术家与行动者；项目共同叙事核心。'),rel('展览','Flint Institute of Arts / Eli and Edythe Broad Art Museum / Stamps Gallery','三家 Michigan 机构分别呈现 Acts I–III；2022–23形成跨机构展示网络。'),rel('出版','The Gordon Parks Foundation / Steidl','2022 book；Gordon Parks Foundation / Steidl Book Prize 项目。'),rel('方法','witness → resource','摄影从记录污染危机推进到公共倡议与实际净水资源的获得。')]},
    {title:'Monuments of Solidarity — survey as counter-monument',cluster:'labor / solidarity / installation / institutional reframing',period:'2024',summary:'MoMA 2024 调查展把 Frazier 二十余年的系列重新组织为她所谓面向劳动者思想的“monuments”。这一框架把 Braddock、Flint、Lordstown、Baltimore、Delano 等地点连接起来：纪念碑不再首先纪念国家英雄，而让工人、社区健康工作者、女性与家庭以姓名、肖像和第一人称经验进入公共记忆。策展人 Roxana Marcoci 的文本特别强调，她长期与通常不会被艺术制度承认为艺术家的女性合作，并把她们的创作与声音带入机构空间。',actions:['把不同时期项目重新设计为具有建筑感和公共纪念功能的 multimedia installations。','保留人物姓名、职业、家庭关系和第一人称叙述，拒绝把“工人”抽象成社会类型。','把多个美国工业/环境正义地点组织成跨地域劳动史网络。','借大型博物馆调查展反转纪念碑逻辑：公共记忆由普通劳动者的言语与行动建立。'],sourceUrl:'https://www.moma.org/magazine/articles/1075',images:[],relations:[rel('展览','Museum of Modern Art — Monuments of Solidarity','2024 survey；organized by Roxana Marcoci with Caitlin Ryan and Antoinette D. Roberts。'),rel('方法','series → monument','既有摄影/文字项目被重新组织为面向工人、家庭和社区的反纪念碑。')]}
  ],
  'an-my-le':[
    {title:'Viêt Nam',cluster:'return / exile / landscape / memory',period:'1994–98',summary:'Lê 在1975年离开越南约二十年后首次返回，并由此开始 Viêt Nam。她没有把返回故乡处理成直接自传或战争遗址清单，而使用大画幅黑白摄影观察正在现代化的日常地景、家庭、农业与仍留有战争痕迹的建筑。Carnegie 的项目资料指出，她会主动要求人物停下并看向镜头，因此这些图像也并非纯粹抓拍。系列把“故乡”变成一个必须在现实越南、流亡记忆和战争历史之间重新建构的视觉概念。',actions:['在离开约二十年后返回出生地，以长期观看代替即时新闻式报道。','使用大画幅相机和相对缓慢的工作方式，使地景、人物与历史痕迹同时保持细节。','必要时主动安排人物停下/看向相机，不把纪录摄影等同于完全不介入。','把战争留下的建筑痕迹与稻田、城市广告、家庭生活等当代变化并置。','通过系列而非单张“故乡照片”建立流亡者对 home / heritage 的重新想象。'],sourceUrl:'https://carnegieart.org/resource/an-my-les-viet-nam/',images:[],relations:[rel('展览','An-My Lê: On Contested Terrain — Carnegie Museum of Art','2020–21；首个美国博物馆综合调查展，Dan Leers 策展。'),rel('出版','Aperture + Carnegie Museum of Art','2020 同名调查展图录；Dan Leers 编辑。'),rel('方法','Viêt Nam → Small Wars → 29 Palms','从个人返回与战争记忆，逐步转向战争重演和军事训练的制度化生产。')]},
    {title:'On Contested Terrain — seven-series survey',cluster:'career map / landscape / conflict / institutional network',period:'2020–21',summary:'Carnegie Museum of Art 的 On Contested Terrain 是 Lê 在美国博物馆的首个综合调查展，展出100余幅照片并横跨七个系列，由摄影策展人 Dan Leers 组织。它把 Viêt Nam、Small Wars、29 Palms、Events Ashore 与持续中的 Silent General 放到同一条线上：Lê 的核心并非“战争摄影”，而是借景观传统研究冲突如何通过训练、重演、军队非战斗活动、电影片场、边境和历史纪念持续塑造空间。',actions:['以七个系列建立三十年实践的连续地图，而非把每个战争相关项目孤立展示。','把军训、战争重演、电影制作、边境与历史纪念视为同一“冲突如何被生产/记忆”的问题。','通过100余幅作品保持大画幅景观观看的连续性，同时展示题材从越南记忆扩展到美国政治地景。'],sourceUrl:'https://carnegieart.org/exhibition/an-my-le/',images:[],relations:[rel('策展','Dan Leers','Carnegie Museum of Art photography curator；organizing curator。'),rel('出版','Aperture','与 Carnegie Museum of Art 联合出版调查展图录。'),rel('对话','Viet Thanh Nguyen','图录收录 Lê 与 Nguyen 的对谈，将战争、流散和美国身份问题接入文学/文化研究网络。')]}
  ]
};