import type { ArtistArchive, ArchiveProject, ArchiveRelation } from './archiveData';
const rel=(kind:ArchiveRelation['kind'],label:string,detail?:string):ArchiveRelation=>({kind,label,detail});
const project=(p:ArchiveProject)=>p;

export const archiveBatch309:Record<string,ArtistArchive>={
 'carrie-mae-weems':{artistId:'carrie-mae-weems',projectCoverage:'作品级继续深化 Carrie Mae Weems：Kitchen Table Series、Family Pictures and Stories / Mom at Work、Run, Nigger, Run。重点补齐实际拍摄/制作动作、印刷材料、尺寸、版本和观看结构。',imageCoverage:'National Gallery of Art 的对应馆藏页均提供逐件作品图/缩略图与视觉描述，但明确标注媒体不可下载并要求联系机构处理 image usage；因此本批保存官方图像入口和版权/使用状态，不复制受限图像，images 留空而非使用替代图。',note:'本批专门补足此前总体档案里最容易被主题化概括的早期摄影：把“家庭、黑人女性、种族历史”重新落到布光、演员调度、文本页、铂/钯印相、银盐照片、丝网印刷和作品组合方式上。',projects:[
 project({title:'Kitchen Table Series',cluster:'staged photography / domestic theatre / text-image sequence',period:'1990; portfolio printed 2003',summary:'Weems 把一个极简厨房场景变成连续摄影舞台：同一张桌子、同一盏悬挂灯、基本固定的正面机位，艺术家本人扮演核心人物，恋人、朋友与女儿等演员依次进入。她不是抓拍家庭生活，而是反复安排人物位置、身体姿态、桌面物件与关系距离，让20幅照片像戏剧场次一样推进；14张文字页与照片交错，把画面无法直接说明的欲望、争执、母职、独处和自我定义继续写出来。NGA 馆藏的2003 portfolio 将1990图像制作成20张 platinum/palladium prints 与14张 screenprints：摄影图像每张50.8×50.8cm，文字页27.94×27.94cm；版本为 edition of 10 + 2 AP。题页还记录摄影由 John Marcy / Northampton Photographic 印制，文字由 Peter Kruty Editions 印制，Pamela Vanderzwan 参与设计。观看时它不是一张“经典照片”，而是需要沿20幅影像与14块文字阅读一个被精确导演的时间序列。',actions:['在小房间内固定厨房桌、单盏顶灯和基本稳定的拍摄方向，建立可重复使用的舞台。','由 Weems 自己担任主角，并让恋人、朋友、女儿等角色按不同关系进入场景；通过坐姿、对视、距离和桌面物件改变每一幕。','把20张舞台化摄影与14张文本页编排成连续叙事，而不是把单幅照片当作独立纪实图像。','2003 portfolio 将照片以 platinum/palladium 工艺重新制作，文字以 screenprint 输出，并以统一尺度形成可按序阅读的作品组。'],sourceUrl:'https://www.nga.gov/artworks/209288-kitchen-table-series',images:[],relations:[rel('材料','20 platinum/palladium prints + 14 screenprints','NGA 2017.4.1.1-34；摄影图像50.8×50.8cm，文字页27.94×27.94cm。'),rel('制作','John Marcy / Northampton Photographic + Peter Kruty Editions','2003 portfolio 题页记录摄影与文字印刷分工。'),rel('展陈','NGA East Building — 2017–2018','完整系列作为连续组照与文本被观看，而非抽出单张代表图。'),rel('图片权利','National Gallery of Art media','官方页有逐件图像，但标注 media is not available for download；需联系 NGA 处理 image usage，因此本站不复制。')]}),
 project({title:'Mom at Work — Family Pictures and Stories',cluster:'family archive / documentary / self-authored history',period:'1978–1984',summary:'Family Pictures and Stories 是 Weems 早期把家庭相册、社会纪录与自我叙事结合的核心项目。与后来 Kitchen Table 的完全舞台化不同，这一阶段她把镜头转向自己的家庭与波特兰黑人社区，让亲属劳动、亲密关系和日常空间进入一套由家庭内部自行生产的视觉历史。具体作品 Mom at Work 以母亲劳动为对象；NGA 馆藏确认最终形式为 gelatin silver print，画面可见尺寸60.96×92.71cm，装框66.68×97.79×2.54cm。这里重要的不只是“拍母亲”：Weems 把通常不会进入官方历史档案的家庭劳动放大到大型银盐照片尺度，使私人家庭照片承担公共历史记录功能。',actions:['长期拍摄自己的家庭成员及其生活、劳动和关系，而不是从外部把社区当作社会学样本。','从家庭内部建立照片序列，使私人相册的观看位置转化为作者主动书写黑人家庭历史的位置。','Mom at Work 以传统 gelatin silver print 制作，把日常劳动场景变成可进入美术馆收藏和公共观看的实体摄影。','通过系列而非单张新闻式“决定性瞬间”累积家庭内部的时间、身份与叙事。'],sourceUrl:'https://www.nga.gov/artworks/225085-mom-work',images:[],relations:[rel('系列','Family Pictures and Stories','NGA 将 Mom at Work 明确列入该系列。'),rel('材料','gelatin silver print','NGA 馆藏；visible image 60.96×92.71cm。'),rel('图片权利','National Gallery of Art media','作品图可在线研究，但官方标注不可下载并要求联系机构处理 image usage；本站记录入口而不复制。'),rel('方法关系','family archive → counter-history','先从自己的家庭建立可见性，后来才进一步挪用、改写殖民/制度档案。')]}),
 project({title:'Run, Nigger, Run',cluster:'appropriation / racist archive / text-image diptych',period:'1992',summary:'这件作品把一幅风景/历史图像与一张旧乐谱、歌词和文字材料并置成双联结构。Weems 的动作不是单纯“引用种族主义历史”，而是把带有侮辱性标题和文化记忆的既有材料重新带入当代展示环境，让观看者必须在摄影图像与印刷语言之间移动。NGA 馆藏明确记录媒介为 gelatin silver print and screenprint on paper，两幅图像各48.58×48.58cm，装框后各53.02×53.02×3.81cm，版次5/10。它因此是摄影与印刷文本被物理并置的作品，而不是给照片附上一段墙签。',actions:['选择带有美国种族主义历史与流行文化记忆的既有文字/乐谱材料。','把摄影图像与印刷材料处理为相邻的双联观看单元，使图像与语言互相改变意义。','使用 gelatin silver photographic print 与 screenprint on paper 两种不同印刷机制，让“摄影证据”与“复制传播的文字/歌曲”在材料上也保持差异。','以相同方形尺度和相邻装框迫使观众同时阅读、观看，而不能只消费一张视觉上完整的照片。'],sourceUrl:'https://www.nga.gov/artworks/170436-run-nigger-run',images:[],relations:[rel('材料','gelatin silver print + screenprint on paper','每幅图像48.58×48.58cm；两部分构成 diptych。'),rel('版次','5/10','NGA 馆藏页记录作品背面签名及版次。'),rel('来源/馆藏','Corcoran Collection → National Gallery of Art','1995进入 Corcoran，2014转入 NGA。'),rel('图片权利','National Gallery of Art media','官方作品图用于在线研究但不可直接下载；本站不复制受限媒体。')]}),
 project({title:'Untitled — seven-part text-on-glass work',cluster:'archive / text / framing / photographic authority',period:'1996; printed 2020',summary:'NGA 的这件七联作品为理解 Weems 如何把“文字写到照片观看表面”提供了非常具体的物质证据：七张 inkjet prints 各自装入木框，文字不是数字叠在图像文件里，而是 sandblasted 到覆盖照片的 glass 上。每张图像/纸张76.2×58.42cm，单框83.19×67.63×2.86cm，七件总体横向延伸约474.5cm。观众因此同时面对三个层次：历史/摄影图像、实体玻璃、刻在玻璃上的语言；文字真正占据观看者与照片之间的物理界面。该结构也能反向解释 From Here I Saw What Happened and I Cried 中“重写档案”并非纯粹概念，而是一套具体的裁切、打印、玻璃刻字与连续墙面安装技术。',actions:['将七幅图像制作成 inkjet prints。','分别置入木框，并在照片前方玻璃表面进行 sandblasted text 处理。','保持七件统一尺度，横向连续安装，使语言成为跨图像推进的阅读节奏。','让文字处于观众与照片之间的真实物理表面，而不是作为说明文字退到墙签。'],sourceUrl:'https://www.nga.gov/artworks/222916-untitled',images:[],relations:[rel('材料','7 inkjet prints + sandblasted text on glass + wood frames','NGA 馆藏数据。'),rel('尺寸','overall 83.03 × 474.5 × 2.86 cm','七联横向安装形成接近4.75米的连续观看带。'),rel('版本','1996 / printed 2020','明确区分图像作品年份与馆藏印制年份。'),rel('图片权利','National Gallery of Art media','官方提供多张逐件图像但不可下载；本站仅记录官方入口。')]})
 ],exhibitions:['Carrie Mae Weems: Kitchen Table Series — National Gallery of Art — Washington — 2017–2018'],sources:[{label:'NGA — Kitchen Table Series object record',url:'https://www.nga.gov/artworks/209288-kitchen-table-series'},{label:'NGA — Kitchen Table Series exhibition',url:'https://www.nga.gov/exhibitions/carrie-mae-weems-kitchen-table-series'},{label:'NGA — Mom at Work',url:'https://www.nga.gov/artworks/225085-mom-work'},{label:'NGA — Run, Nigger, Run',url:'https://www.nga.gov/artworks/170436-run-nigger-run'},{label:'NGA — Untitled (1996, printed 2020)',url:'https://www.nga.gov/artworks/222916-untitled'}]}
};
