import type { ArtistArchive, ArchiveProject, ArchiveRelation } from './archiveData';
const rel=(kind:ArchiveRelation['kind'],label:string,detail?:string):ArchiveRelation=>({kind,label,detail});
const project=(p:ArchiveProject)=>p;
export const archiveBatch292:Record<string,ArtistArchive>={
'walid-raad':{artistId:'walid-raad',projectCoverage:'深化既有 Walid Raad：补 The Atlas Group 分类协议、My Neck Is Thinner Than a Hair 与 Cotton Under My Feet，把“战争档案→证据制度→博物馆收藏史”的方法演变做实。',imageCoverage:'使用 MoMA 与 Sfeir-Semler/TBA21 官方研究入口；不复制版权图像。',note:'Raad 并非任意制造虚构。他通常先进入真实档案、新闻系统、收藏或机构史，再设计分类、作者归属、章节与现场讲述，使事实、推论和虚构在同一制度格式中发生摩擦。',projects:[
project({title:'The Atlas Group — A / FD / AGP archive protocol',cluster:'archive taxonomy / authorship / institutional fiction',period:'1989–2004',summary:'MoMA 记录 The Atlas Group Archive 有三种文件类别：[cat. A] 为归属于具体个人的文献，[cat. FD] 为归属于匿名个人或机构的文献，[cat. AGP] 为归属于 The Atlas Group 自身的文献。这说明 Raad 不只制造内容，也设计“谁提供文献、谁授权历史”的元数据结构；作者身份本身就是作品。',actions:['按 A / FD / AGP 设计文献归属。','让真实人物、虚构人物、匿名机构和 Atlas Group 占据不同证据位置。','模拟研究机构的分类语言，使观众先进入制度形式，再发现其不稳定。'],sourceUrl:'https://www.moma.org/slideshows/41/748',images:[],relations:[rel('方法','A / FD / AGP taxonomy','作者归属不是附注，而是历史可信度的生产机制。'),rel('机构','MoMA — Walid Raad, 2015–16','官方展览资料明确记录三类文件协议。')]}),
project({title:'My Neck Is Thinner Than a Hair: Engines — evidence without explanation',cluster:'car bombs / newspaper archive / forensic evidence / photojournalism',period:'1996–2004',summary:'MoMA 记录该研究围绕黎巴嫩战争汽车炸弹展开，展出部分由100张历史新闻摄影组成，来自 Beirut 的 An-Nahar Research Center 与 Arab Documentation Center。爆炸后发动机常被抛离现场却相对完整，记者争相寻找并拍摄；发动机编号理论上可追车主，但炸弹车辆往往是赃车，因此证据的司法解释力有限。Raad 注意到媒体最终告诉公众大量汽车信息，却仍无法解释爆炸的政治动机。',actions:['进入报纸与文献中心寻找既有战争图像。','选择发动机照片而非重新拍摄遗址。','把100张图像编排成比较序列。','并置 forensic-looking evidence 与其有限的解释力。'],sourceUrl:'https://www.moma.org/slideshows/41/749',images:[],relations:[rel('档案','An-Nahar Research Center / Arab Documentation Center','100张新闻照片来源。'),rel('媒介','100 pigmented inkjet prints','MoMA馆藏记录每张约24×34cm。'),rel('方法','forensic trace ≠ historical explanation','证据可以精确，却不能自动解释政治因果。')]}),
project({title:'Cotton Under My Feet — museum collection as labyrinth',cluster:'museum collection / Thyssen-Bornemisza / conservation / fiction / walkthrough',period:'2018–2021',summary:'TBA21 邀请 Raad 在 Museo Nacional Thyssen-Bornemisza 构思项目后，他从 Baron Hans Heinrich Thyssen-Bornemisza、家族与收藏以及 Béhague-Sanguszko 波斯地毯进入研究，再把真实收藏史与虚构修复师 Lamia Antonova、画作背面的云、会吸引特定节肢动物的金银器、可自我修复的天使等叙事交织。官方项目页将这些描述为不断分叉的 historical and fictional spaces。研究对象由战争档案推进到博物馆的收藏、修复、家族财富与知识制度。',actions:['从真实委托与收藏史开始研究。','沿具体藏品扩展至家族史、商业史和博物馆史。','把真实藏品、历史人物和虚构修复史置于同一展示层。','用摄影、墙纸、木结构、录像、剪纸人物及真实藏品构成装置。','以 walkthrough 让研究成为可继续分叉的现场叙事。'],sourceUrl:'https://sfeir-semler.com/artists/artists/walid-raad/exhibitions/cotton-under-my-feet-tba21',images:[],relations:[rel('机构','TBA21 / Museo Nacional Thyssen-Bornemisza','2018委托触发研究，2021形成展览。'),rel('藏品','Béhague-Sanguszko carpet','16世纪末或17世纪初波斯地毯成为研究入口。'),rel('人物','Lamia Antonova — fictional restorer','虚构修复师让 conservation 这种隐藏劳动进入叙事中心。'),rel('谱系','war archive → art infrastructure → collection history','持续追问制度如何制造历史与对象意义。')]})],awards:['Hasselblad Award — 2011','Deutsche Börse Photography Prize — 2007','Guggenheim Fellowship — 2009','ICP Infinity Award — 2016'],exhibitions:['Walid Raad — MoMA — 2015–2016','Cotton Under My Feet — Museo Nacional Thyssen-Bornemisza / TBA21 — 2021','Documenta 11 — 2002','Documenta 13 — 2012','Venice Biennale — 2003'],sources:[{label:'MoMA — Atlas Group file protocol',url:'https://www.moma.org/slideshows/41/748'},{label:'MoMA — Engines',url:'https://www.moma.org/slideshows/41/749'},{label:'MoMA — artist audio on Engines',url:'https://www.moma.org/audio/playlist/20/420'},{label:'Sfeir-Semler / TBA21 — Cotton Under My Feet',url:'https://sfeir-semler.com/artists/artists/walid-raad/exhibitions/cotton-under-my-feet-tba21'}]}
};
