import type { ArtistArchive } from './archiveData';
export const archiveBatch331:Record<string,ArtistArchive>={
'sophie-calle':{artistId:'sophie-calle',projectCoverage:'深化 The Sleepers、Suite Vénitienne、The Hotel、Exquisite Pain。',imageCoverage:'MoMA 官方作品入口。',note:'Calle 以规则、跟踪、重复、交换和文本编排制造亲密关系，而非单纯记录私人生活。',projects:[
{title:'The Sleepers (Les dormeurs)',cluster:'rules / intimacy / photography',period:'1979',summary:'连续八天邀请29人轮流占据她的床，每人约八小时；每小时拍摄、问卷并录音，把陌生人进入私人空间变成可重复的社会实验结构。',actions:['邀请参与者','规定轮班','每小时拍摄','问卷与录音','组织重复肖像与文字'],sourceUrl:'https://www.moma.org/collection/works/421055',images:[],relations:[{kind:'展览',label:'Biennale des Jeunes, Paris',detail:'早期展出节点'},{kind:'收藏',label:'Museum of Modern Art, New York',detail:'installation in collection'}]},
{title:'Suite Vénitienne',cluster:'following / surveillance / artist book',period:'1979–1980',summary:'跟踪一名偶然遇见的男子到威尼斯，通过酒店、电话、警察局和陌生人的帮助寻找行踪，并以日记和黑白照片保存追踪过程。',actions:['选择对象','前往威尼斯','跟踪路线','联系酒店与陌生人','拍摄与写日记','艺术家书编排'],sourceUrl:'https://www.moma.org/collection/artists/6655',images:[],relations:[{kind:'出版',label:'Suite Vénitienne',detail:'1983 artist book'}]},
{title:'The Hotel',cluster:'role-play / inventory / privacy',period:'1981',summary:'以酒店女服务员身份进入客房，在房客离开时拍摄房间、物件和痕迹，并以库存清单式文字建立私人生活的间接档案。',actions:['取得服务员身份','进入客房','拍摄物件','记录痕迹','建立房间档案'],sourceUrl:'https://www.moma.org/collection/artists/6655',images:[],relations:[]},
{title:'Exquisite Pain',cluster:'memory / repetition / exchange',period:'1984–2003',summary:'将一次关系破裂转成长期重复结构，把自己的失恋与陌生人的痛苦故事并置，文字逐渐淡出，使重复成为记忆消退和公共化的机制。',actions:['记录个人事件','询问他人痛苦经历','并置叙事','重复展示','让文字淡出'],sourceUrl:'https://www.moma.org/collection/artists/6655',images:[],relations:[{kind:'出版',label:'Exquisite Pain',detail:'artist book and installation'}]}
],awards:[],exhibitions:['Biennale des Jeunes, Paris','MoMA — The Sleepers'],sources:[{label:'MoMA artist profile',url:'https://www.moma.org/collection/artists/6655'},{label:'MoMA The Sleepers',url:'https://www.moma.org/collection/works/421055'},{label:'MoMA 2026 research',url:'https://production-gcp.moma.org/magazine/articles/1420'}]},
'trevor-paglen':{artistId:'trevor-paglen',projectCoverage:'深化 An English Landscape、Autonomy Cube、Training Humans。',imageCoverage:'Whitney / SFMOMA / Fondazione Prada 官方入口。',note:'Paglen 从秘密军事设施到网络基础设施再到机器视觉训练集，持续研究不可见的视觉与技术系统。',projects:[
{title:'An English Landscape (American Surveillance Base near Harrogate, Yorkshire)',cluster:'surveillance / landscape',period:'2014',summary:'用远距摄影把美国监视基础设施嵌入英国乡村景观语法，让军事监听以平静景观的形式出现。',actions:['远距离定位设施','长焦摄影','在景观中隐藏军事基础设施','制作大幅照片'],sourceUrl:'https://whitney.org/collection/works/47025',images:[],relations:[{kind:'收藏',label:'Whitney Museum of American Art',detail:'2015.110'}]},
{title:'Autonomy Cube',cluster:'network infrastructure / institutional critique',period:'2014–2018',summary:'与 Jacob Appelbaum 合作的可使用雕塑：Plexiglas 立方体内置计算机主板和 Wi‑Fi server，提供 Tor 网络热点并成为 Tor relay，把美术馆变成真实运行的隐私基础设施。',actions:['透明硬件设计','安装主板与服务器','建立 Wi‑Fi','连接 Tor relay','让机构成为网络节点'],sourceUrl:'https://www.sfmoma.org/artwork/2016.73.A-C/',images:[],relations:[{kind:'展览',label:'9th Berlin Biennale',detail:'2016'},{kind:'展览',label:'KW Institute for Contemporary Art',detail:'2017–2018'}]},
{title:'Training Humans',cluster:'machine vision / datasets',period:'2019–2020',summary:'与 Kate Crawford 共同研究训练图像，从1960年代至当代追踪机器学习如何通过被选择、标记和分类的图像学习“看见”。',actions:['收集训练图像','追踪标签与数据集','比较历史训练集合','把数据集展示为制度史材料','建立研究框架'],sourceUrl:'https://www.fondazioneprada.org/project/training-humans/',images:[],relations:[{kind:'展览',label:'Osservatorio Fondazione Prada, Milan',detail:'12 Sep 2019–24 Feb 2020'},{kind:'出版',label:'Excavating AI',detail:'Kate Crawford & Trevor Paglen, 2019'}]}
],awards:[],exhibitions:['9th Berlin Biennale','Fondazione Prada Osservatorio — Training Humans'],sources:[{label:'Trevor Paglen Studio',url:'https://paglen.studio/2020/04/09/autonomy-cube/'},{label:'SFMOMA',url:'https://www.sfmoma.org/artwork/2016.73.A-C/'},{label:'Whitney',url:'https://whitney.org/collection/works/47025'},{label:'Fondazione Prada',url:'https://www.fondazioneprada.org/project/training-humans/'}]},
'mishka-henner':{artistId:'mishka-henner',projectCoverage:'深化 Feedlots、Less Américains、Eighteen Pumpjacks。',imageCoverage:'艺术家官网作品档案入口。',note:'Henner 把网络既有图像变成生产工具：卫星截图、数字擦除和图像拼接重新定义摄影作者与证据。',projects:[
{title:'Feedlots',cluster:'satellite / industrial landscape',period:'2012–2013',summary:'从 Google Earth 发现美国中西部大型养牛场，以数百张公开卫星软件截图拼接出超大尺度图像；地面摄影受限制时，卫星视角反而揭示工业农业整体结构。',actions:['搜索场址','截取卫星图像','拼接数百张截图','制作超大 archival pigment prints','研究工业生产系统'],sourceUrl:'https://mishkahenner.com/feedlots',images:[],relations:[{kind:'展览',label:'Precious Commodities, Open Eye Gallery',detail:'2013'},{kind:'展览',label:'Consumption, Victoria & Albert Museum',detail:'2014'}]},
{title:'Less Américains',cluster:'appropriation / erasure',period:'2012',summary:'对 Robert Frank《The Americans》进行数字擦除，只保留局部轮廓和碎片，并重新输出为银盐照片和限量艺术家书，挑战摄影经典的神圣性。',actions:['获取经典图像','数字擦除','保留碎片','重新输出银盐照片','制作83张银盐照片盒装书'],sourceUrl:'https://mishkahenner.com/Less-Americains',images:[],relations:[{kind:'出版',label:'Less Américains',detail:'180-page hardback / editioned box'}]},
{title:'Eighteen Pumpjacks',cluster:'satellite / extraction / machine portrait',period:'2010s',summary:'从卫星视角分离美国油田中的单个抽油机，把工业机器重新构造成肖像，并与 Barnett Newman《18 Cantos》建立形式关联。',actions:['卫星定位','裁切机器','肖像式构图','archival pigment prints','连接抽象绘画史'],sourceUrl:'https://mishkahenner.com/Eighteen-pumpjacks',images:[],relations:[]}
],awards:['Prix Pictet exhibition participation — Consumption, Victoria & Albert Museum, 2014'],exhibitions:['Precious Commodities — 2013','Consumption — Victoria & Albert Museum, 2014','The Edge of the Earth — Ryerson Image Centre, 2016'],sources:[{label:'Biography',url:'https://mishkahenner.com/Biography'},{label:'Feedlots',url:'https://mishkahenner.com/feedlots'},{label:'Less Américains',url:'https://mishkahenner.com/Less-Americains'},{label:'Eighteen Pumpjacks',url:'https://mishkahenner.com/Eighteen-pumpjacks'}]},
'carrie-mae-weems':{artistId:'carrie-mae-weems',projectCoverage:'深化 Kitchen Table Series、Sea Island Series、From Here I Saw What Happened and I Cried。',imageCoverage:'MoMA / Met 官方收藏入口。',note:'Weems 不是把摄影当透明记录，而是主动制造观看场景，再让个人叙事与黑人历史和档案制度发生关系。',projects:[
{title:'The Kitchen Table Series',cluster:'domestic space / staged photography',period:'1990',summary:'20幅明胶银盐照片与14个丝网文字面板围绕同一张厨房桌展开。Weems 自己扮演中心人物，让朋友、孩子、恋人和物件进入固定场景，讨论女性主体性、亲密关系与自我形象。',actions:['在自家厨房搭景','使用单一悬挂光源','反复安排人物道具','自拍式扮演','照片与文字并置'],sourceUrl:'https://www.moma.org/artists/7177-carrie-mae-weems',images:[],relations:[{kind:'出版',label:'The Kitchen Table Series',detail:'20 gelatin silver prints + 14 silkscreen text panels'}]},
{title:'Sea Island Series',cluster:'place / vernacular history / Gullah',period:'1992–1993',summary:'以民俗学训练为背景研究 Georgia 与 South Carolina 海岸外 Sea Islands 的 Gullah 社群文化痕迹，让建筑、物件和景观承担历史记忆。',actions:['田野研究','拍摄建筑与遗留物件','观察文化痕迹','以景观作为历史证据'],sourceUrl:'https://www.metmuseum.org/art/collection/search/283770',images:[],relations:[{kind:'收藏',label:'The Metropolitan Museum of Art',detail:'Untitled, 1992 / printed 2000'}]},
{title:'From Here I Saw What Happened and I Cried',cluster:'archive / colonial photography / recontextualization',period:'1995–1996',summary:'从历史图像档案中重新处理黑人身体的摄影再现，通过染红图像、玻璃喷砂文字和重新排序，把殖民与科学观看转成反档案。',actions:['选择历史档案图像','重新着色与放大','玻璃喷砂文字','改变观看语境','序列化历史批判'],sourceUrl:'https://www.moma.org/collection/works/91850',images:[],relations:[{kind:'展览',label:'From Here I Saw What Happened and I Cried',detail:'MoMA exhibition history 2020–2021'}]}
],awards:[],exhibitions:['From Here I Saw What Happened and I Cried — MoMA, 2020–2021'],sources:[{label:'MoMA — Carrie Mae Weems',url:'https://www.moma.org/artists/7177-carrie-mae-weems'},{label:'MoMA — From Here I Saw What Happened',url:'https://www.moma.org/collection/works/91850'},{label:'Met — Sea Island Series',url:'https://www.metmuseum.org/art/collection/search/283770'}]}
};