import type { ArtistArchive, ArchiveImage, ArchiveRelation } from './archiveData';

const img = (url: string, title: string, credit: string, sourceUrl: string, sourceLabel: string): ArchiveImage => ({ url, title, credit, sourceUrl, sourceLabel });
const rel = (kind: ArchiveRelation['kind'], label: string, detail?: string): ArchiveRelation => ({ kind, label, detail });

export const archiveBatch6: Record<string, ArtistArchive> = {
  'jeff-wall': {
    artistId: 'jeff-wall', projectCoverage: '6 个关键编排摄影节点已完成第一轮 · 1978–2000', imageCoverage: '',
    note: '本轮先覆盖摄影史最关键的六个制作节点，以看清“观察—搭景—演员—大画幅—灯箱”的方法如何形成。',
    projects: [
      { title: 'The Destroyed Room', cluster: 'constructed scene / lightbox', period: '1978', summary: '参考绘画和橱窗语法搭建被破坏的卧室，把摄影明确推向人工场景与大型灯箱。', actions: ['搭建室内场景', '人为制造破坏', '绘画构图转译', '大型透明片灯箱'], sourceUrl: 'https://gagosian.com/artists/jeff-wall/', images: [img('https://gagosian.com/media/images/artists/jeff-wall/_CPSOTL-EvBm_2400x2400.jpg', 'The Destroyed Room', '© Jeff Wall', 'https://gagosian.com/artists/jeff-wall/', 'Gagosian')], relations: [] },
      { title: 'Picture for Women', cluster: 'gaze / studio construction', period: '1979', summary: '通过镜子、相机与人物位置重新组织观看关系，让相机本身进入权力结构。', actions: ['镜面布置', '人物定位', '大画幅摄影', '灯箱展示'], sourceUrl: 'https://www.jeff-wall.com/', images: [], relations: [] },
      { title: 'Mimic', cluster: 'street observation / reenactment', period: '1982', summary: '从街头观察到的种族手势出发，之后以演员在类似环境中重新排演事件。', actions: ['街头观察', '选角', '重演', '自然光控制'], sourceUrl: 'https://www.tate.org.uk/art/artworks/wall-mimic-t07173', images: [], relations: [rel('收藏', 'Tate', 'Mimic')] },
      { title: 'Dead Troops Talk', cluster: 'war / cinematic tableau', period: '1992', summary: '以演员、化妆、道具和大型布景制造死去士兵互相交谈的超现实场面。', actions: ['历史研究', '大规模布景', '演员排练', '特殊化妆', '分段拍摄 / 合成'], sourceUrl: 'https://www.jeff-wall.com/', images: [], relations: [] },
      { title: 'A Sudden Gust of Wind (after Hokusai)', cluster: 'art history / digital montage', period: '1993', summary: '依据葛饰北斋版画构造现代田野场景，并通过多次拍摄和数字合成完成看似瞬间的风。', actions: ['艺术史转译', '多次拍摄', '演员与道具编排', '数字合成'], sourceUrl: 'https://www.tate.org.uk/art/artworks/wall-a-sudden-gust-of-wind-after-hokusai-t06951', images: [], relations: [rel('收藏', 'Tate', 'A Sudden Gust of Wind')] },
      { title: 'After “Invisible Man” by Ralph Ellison, the Prologue', cluster: 'literature / full-scale set', period: '1999–2000', summary: '依据 Ellison 小说序章搭建地下室，把文字中大量灯具与生活细节转成可拍摄的实体空间。', actions: ['文学细读', '1:1场景搭建', '大量灯具与道具', '制作团队', '大型灯箱'], sourceUrl: 'https://www.moma.org/collection/works/88085', images: [img('https://www.moma.org/media/W1siZiIsIjM4ODkwNiJdLFsicCIsImNvbnZlcnQiLCItcXVhbGl0eSA5MCAtcmVzaXplIDIwMDB4MjAwMFx1MDAzZSJdXQ.jpg?sha=9f9e6bddd7ff4639', 'After “Invisible Man” by Ralph Ellison, the Prologue', '© Jeff Wall', 'https://www.moma.org/collection/works/88085', 'MoMA')], relations: [rel('收藏', 'MoMA', 'collection')] }
    ], awards: ['Hasselblad Award 2002'], exhibitions: ['Jeff Wall — MoMA 2007'], sources: [{ label: 'MoMA', url: 'https://www.moma.org/artists/7826-jeff-wall' }, { label: 'Gagosian', url: 'https://gagosian.com/artists/jeff-wall/' }]
  },
  'rineke-dijkstra': {
    artistId: 'rineke-dijkstra', projectCoverage: '6 个长期肖像 / 录像项目已完成第一轮 · 1992–2009', imageCoverage: '', note: '按“身份转换”主题补六个关键项目；方法变化主要来自拍摄规则、等待时间和重复回访。',
    projects: [
      { title: 'Beach Portraits', cluster: 'adolescence / large-format portrait', period: '1992–1996', summary: '在不同国家海滩以正面大画幅肖像拍摄青少年，让不确定姿势成为核心。', actions: ['大画幅相机', '正面站姿', '自然背景简化', '等待人物决定姿势'], sourceUrl: 'https://www.guggenheim.org/exhibition/rineke-dijkstra-a-retrospective', images: [img('https://www.guggenheim.org/wp-content/uploads/2016/03/installation-rineke-dijkstra-retrospective-srgm-2012-2.jpg', 'Beach Portraits — retrospective installation', '© Rineke Dijkstra / installation view', 'https://www.guggenheim.org/exhibition/rineke-dijkstra-a-retrospective', 'Guggenheim')], relations: [] },
      { title: 'New Mothers', cluster: 'postpartum / bodily transition', period: '1994', summary: '在女性生产后很短时间内拍摄正面身体肖像。', actions: ['医院 / 居家合作', '正面大画幅肖像', '极简背景'], sourceUrl: 'https://www.sfmoma.org/artist/Rineke_Dijkstra/', images: [], relations: [] },
      { title: 'Almerisa', cluster: 'migration / repeated portrait', period: '1994–2008', summary: '长期回访同一位从波黑迁往荷兰的女孩，记录儿童到成年过程。', actions: ['长期回访', '统一拍摄规则', '时间比较'], sourceUrl: 'https://www.sfmoma.org/artist/Rineke_Dijkstra/', images: [], relations: [] },
      { title: 'The Buzzclub, Liverpool / Mysteryworld, Zaandam', cluster: 'nightclub / video portrait', period: '1996–1997', summary: '把夜店青年放到白色背景前，让他们面对固定摄影机跳舞或停顿。', actions: ['夜店 casting', '白背景录像', '固定机位', '长镜头'], sourceUrl: 'https://www.guggenheim.org/exhibition/rineke-dijkstra-a-retrospective', images: [], relations: [] },
      { title: 'Olivier', cluster: 'military identity / repeated portrait', period: '2000–2003', summary: '长期拍摄一名加入法国外籍军团的青年，追踪训练如何改变身体姿态。', actions: ['长期回访', '统一肖像形式', '军旅阶段比较'], sourceUrl: 'https://www.sfmoma.org/artist/Rineke_Dijkstra/', images: [], relations: [] },
      { title: 'Ruth Drawing Picasso', cluster: 'video / absorbed attention', period: '2009', summary: '录像一个女孩临摹 Picasso，观察她在观看和绘画中的集中状态。', actions: ['固定录像', '简化背景', '持续观察'], sourceUrl: 'https://www.guggenheim.org/exhibition/rineke-dijkstra-a-retrospective', images: [], relations: [] }
    ], awards: ['Hasselblad Award 2017'], exhibitions: ['Guggenheim retrospective 2012'], sources: [{ label: 'Guggenheim', url: 'https://www.guggenheim.org/exhibition/rineke-dijkstra-a-retrospective' }, { label: 'SFMOMA', url: 'https://www.sfmoma.org/artist/Rineke_Dijkstra/' }]
  },
  'moyra-davey': {
    artistId: 'moyra-davey', projectCoverage: '5 个摄影 / 邮寄 / 影像节点已完成第一轮 · 1990s–2016', imageCoverage: '', note: '从拍摄日常表面发展到“折叠—邮寄—展出”的流通系统，并与 essay film / 写作交织。',
    projects: [
      { title: 'Copperheads', cluster: 'close-up / circulation / money', period: '1990s–2000s', summary: '极近距离拍摄流通中的一美分硬币，让磨损、污迹和头像成为时间和交换的表面。', actions: ['微距摄影', '类型化重复', '网格展示'], sourceUrl: 'https://www.moma.org/artists/39770-moyra-davey', images: [], relations: [] },
      { title: 'Mailers', cluster: 'fold / mail / photographic object', period: '2000s–', summary: '把摄影打印直接折叠、贴胶带、写地址并通过邮政寄给展览空间。', actions: ['打印照片', '折叠', '胶带封合', '真实邮寄', '带运输痕迹展出'], sourceUrl: 'https://www.moma.org/artists/39770-moyra-davey', images: [], relations: [] },
      { title: 'The Coffee Shop, The Library', cluster: 'reading / grid / mailed photographs', period: '2011', summary: '书、咖啡馆和阅读空间被组织成网格，并以邮寄痕迹强调图像流通。', actions: ['拍摄书与阅读空间', '网格编辑', '折叠邮寄', '墙面重组'], sourceUrl: 'https://www.moma.org/collection/works/147668', images: [img('https://www.moma.org/media/W1siZiIsIjIzNjcxNyJdLFsicCIsImNvbnZlcnQiLCItcXVhbGl0eSA5MCAtcmVzaXplIDIwMDB4MjAwMFx1MDAzZSJdXQ.jpg?sha=33185a6f21ed5d2a', 'The Coffee Shop, The Library', '© Moyra Davey', 'https://www.moma.org/collection/works/147668', 'MoMA')], relations: [rel('收藏', 'MoMA', 'collection')] },
      { title: 'Les Goddesses', cluster: 'essay film / family / literature', period: '2011', summary: '把 Mary Wollstonecraft、家庭经验和阅读笔记编织成 essay film。', actions: ['写作', 'voice-over', '静态影像', '家庭与文学史并置'], sourceUrl: 'https://www.moyradavey.com/', images: [img('https://bendowabooks.com/cdn/shop/files/Moyra-Davey-1.jpg?v=1757252311', 'Les Goddesses / Hemlock Forest publication context', '© Moyra Davey', 'https://bendowabooks.com/', 'Publication documentation')], relations: [] },
      { title: 'Hemlock Forest', cluster: 'essay film / illness / reading', period: '2016', summary: '以身体、疾病、文学和日常影像构成自我反思的 essay film。', actions: ['第一人称写作', '录像', '文学引用', '日常图像'], sourceUrl: 'https://www.moyradavey.com/', images: [], relations: [] }
    ], awards: ['Scotiabank Photography Award 2018'], exhibitions: ['Camden Art Centre', 'National Gallery of Canada'], sources: [{ label: 'MoMA', url: 'https://www.moma.org/artists/39770-moyra-davey' }]
  },
  'thomas-ruff': {
    artistId: 'thomas-ruff', projectCoverage: '6 个图像系统节点已完成第一轮 · 1981–现在', imageCoverage: '', note: '从类型化肖像到互联网 JPEG、天文图和新闻图，重点是图像来源与技术条件如何决定摄影。',
    projects: [
      { title: 'Interieurs', cluster: 'domestic interiors / early typology', period: '1979–1983', summary: '冷静拍摄普通室内空间，为后来杜塞尔多夫式类型化观看建立基础。', actions: ['固定机位', '室内摄影', '重复规则'], sourceUrl: 'https://www.davidzwirner.com/artists/thomas-ruff', images: [], relations: [] },
      { title: 'Porträts', cluster: 'portrait / typology / scale', period: '1981–1991', summary: '以近似证件照的规则拍摄同代人，再以巨大尺幅输出。', actions: ['中性背景', '正面照明', '无表情要求', '大尺幅放大'], sourceUrl: 'https://www.davidzwirner.com/artists/thomas-ruff', images: [], relations: [] },
      { title: 'Häuser', cluster: 'architecture / digital cleanup', period: '1987–1991', summary: '拍摄平凡建筑，并开始以数字方式删除干扰元素。', actions: ['建筑摄影', '数字删除', '大尺幅输出'], sourceUrl: 'https://www.davidzwirner.com/artists/thomas-ruff', images: [], relations: [] },
      { title: 'Sterne', cluster: 'appropriated astronomy', period: '1989–1992', summary: '使用欧洲南方天文台的负片而非自己拍摄，将科学图像重新放进艺术摄影尺度。', actions: ['科学档案挪用', '选取底片', '大尺幅放大'], sourceUrl: 'https://www.davidzwirner.com/artists/thomas-ruff', images: [], relations: [] },
      { title: 'nudes', cluster: 'internet image / blur', period: '1999–', summary: '从互联网色情图像取样并降低细节、模糊放大，讨论数字观看和欲望。', actions: ['网络图像采集', '低分辨率处理', '模糊', '大尺幅打印'], sourceUrl: 'https://www.davidzwirner.com/artists/thomas-ruff', images: [], relations: [] },
      { title: 'jpegs', cluster: 'compression / media image', period: '2004–', summary: '把网络新闻和灾难图像的 JPEG 压缩像素放大到可见，令格式本身成为画面结构。', actions: ['网络图像挪用', 'JPEG压缩', '极端放大', '大型打印'], sourceUrl: 'https://www.davidzwirner.com/artists/thomas-ruff', images: [img('https://yeux-coccinelle.fr/wp-content/uploads/2020/01/Thomas_Ruff_jpeg_mn01_2007.jpg', 'jpeg series', '© Thomas Ruff', 'https://www.davidzwirner.com/artists/thomas-ruff', 'Artist / gallery documentation')], relations: [] }
    ], awards: [], exhibitions: ['Major international museum surveys'], sources: [{ label: 'David Zwirner', url: 'https://www.davidzwirner.com/artists/thomas-ruff' }]
  },
  'hiroshi-sugimoto': {
    artistId: 'hiroshi-sugimoto', projectCoverage: '6 个核心长期系列已完成第一轮 · 1976–现在', imageCoverage: '', note: '把“时间如何被摄影记录”拆成剧院、海平线、蜡像、建筑与电放电等不同实验。',
    projects: [
      { title: 'Dioramas', cluster: 'museum display / reality effect', period: '1976–', summary: '拍摄自然史博物馆的动物模型与布景，让假景在照片中重新获得真实感。', actions: ['博物馆取景', '黑白大画幅', '重新构图展示景观'], sourceUrl: 'https://www.sugimotohiroshi.com/', images: [], relations: [] },
      { title: 'Theaters', cluster: 'long exposure / cinema time', period: '1976–', summary: '让相机在整部电影放映期间保持曝光，银幕最终变成纯白光。', actions: ['整场电影长曝光', '大画幅相机', '建筑与光同时记录'], sourceUrl: 'https://www.sugimotohiroshi.com/', images: [], relations: [] },
      { title: 'Seascapes', cluster: 'horizon / deep time', period: '1980–', summary: '以近乎一致的海天分界拍摄全球海域，把地点差异压缩成原始视觉结构。', actions: ['统一水平线', '长曝光', '黑白大画幅', '全球多地重复'], sourceUrl: 'https://www.sugimotohiroshi.com/', images: [img('https://artblart.files.wordpress.com/2022/03/sugimoto-seascapes-hayward-gallery-installation-view-web.jpg', 'Seascapes — installation view', '© Hiroshi Sugimoto', 'https://www.sugimotohiroshi.com/', 'Exhibition documentation')], relations: [] },
      { title: 'Portraits', cluster: 'wax figure / historical portrait', period: '1999–', summary: '拍摄蜡像历史人物，并以肖像摄影的布光让复制品重新像“真人”。', actions: ['蜡像选择', '工作室式布光', '黑白摄影'], sourceUrl: 'https://www.sugimotohiroshi.com/', images: [], relations: [] },
      { title: 'Architecture', cluster: 'modernism / defocus', period: '1997–', summary: '有意失焦拍摄现代主义建筑，把细节消掉只留下理念轮廓。', actions: ['建筑取景', '主动失焦', '黑白大画幅'], sourceUrl: 'https://www.sugimotohiroshi.com/', images: [], relations: [] },
      { title: 'Lightning Fields', cluster: 'camera-less / electricity', period: '2006–', summary: '让高压电直接作用在感光材料上，生成树枝般放电痕迹。', actions: ['高压放电', '无相机感光', '暗房处理'], sourceUrl: 'https://www.sugimotohiroshi.com/', images: [], relations: [] }
    ], awards: ['Hasselblad Award 2001'], exhibitions: ['Major museum retrospectives'], sources: [{ label: 'Artist website', url: 'https://www.sugimotohiroshi.com/' }]
  },
  'latoya-ruby-frazier': {
    artistId: 'latoya-ruby-frazier', projectCoverage: '5 个家庭 / 劳动 / 环境正义项目已完成第一轮 · 2001–2024', imageCoverage: '', note: '从家庭自拍和 Braddock 去工业化逐渐扩展到 Flint 水危机、工人和公共纪念。',
    projects: [
      { title: 'The Notion of Family', cluster: 'family / deindustrialization / self-portrait', period: '2001–2014', summary: '长期拍摄自己、母亲和祖母，并把家庭身体与 Braddock 钢铁工业衰退、污染和医疗现实并置。', actions: ['家庭合作', '自画像', '长期纪实', '家庭档案', '黑白摄影'], sourceUrl: 'https://www.moma.org/artists/38342', images: [img('https://d7hftxdivxxvm.cloudfront.net/?height=800&quality=80&resize_to=fit&src=https%3A%2F%2Fd32dm0rphc51dk.cloudfront.net%2FK41r6sTTN3kFfqNqg_zRLA%2Flarge.jpg&width=800', 'The Notion of Family', '© LaToya Ruby Frazier', 'https://www.moma.org/artists/38342', 'MoMA / collection documentation')], relations: [] },
      { title: 'Flint Is Family', cluster: 'water crisis / collaboration', period: '2016–', summary: '与 Flint 家庭合作记录水危机，并持续追踪社区自救和基础设施问题。', actions: ['长期社区合作', '肖像 / 日常记录', '环境正义研究'], sourceUrl: 'https://www.latoyarubyfrazier.com/', images: [], relations: [] },
      { title: 'On the Making of Steel Genesis', cluster: 'labour / worker history', period: '2017', summary: '围绕工人和钢铁生产记忆建立照片、文字与口述关系。', actions: ['工人口述史', '工作环境摄影', '文本'], sourceUrl: 'https://www.latoyarubyfrazier.com/', images: [], relations: [] },
      { title: 'More Than Conquerors', cluster: 'health / community monument', period: '2020–2022', summary: '围绕 Baltimore 社区健康工作者制作大型摄影纪念结构。', actions: ['社区合作', '肖像', '大型装置', '公共健康研究'], sourceUrl: 'https://www.latoyarubyfrazier.com/', images: [], relations: [] },
      { title: 'Monuments of Solidarity', cluster: 'museum survey / social practice', period: '2024', summary: 'MoMA 大展将家庭、劳动、环境和公共健康项目组织成“solidarity”方法史。', actions: ['跨项目重编', '大型空间展示', '档案 / 文字 / 摄影并置'], sourceUrl: 'https://www.moma.org/calendar/exhibitions/5568', images: [], relations: [rel('展览', 'MoMA', '2024'), rel('策展', 'Roxana Marcoci', '2024')] }
    ], awards: ['MacArthur Fellow 2015'], exhibitions: ['LaToya Ruby Frazier: Monuments of Solidarity — MoMA 2024'], sources: [{ label: 'MoMA', url: 'https://www.moma.org/calendar/exhibitions/5568' }, { label: 'Artist website', url: 'https://www.latoyarubyfrazier.com/' }]
  },
  'yuko-mohri': {
    artistId: 'yuko-mohri', projectCoverage: '4 个系统 / 声音 / 国家馆项目已完成第一轮 · 2009–2024', imageCoverage: '', note: '先围绕漏水系统、电路、腐烂水果与 2024 日本馆展开。',
    projects: [
      { title: 'Moré Moré (Leaky)', cluster: 'water / bricolage / kinetic system', period: '2009–', summary: '从东京地铁应急漏水装置出发，以泵、桶、软管与 found objects 搭建持续循环的动态系统。', actions: ['观察城市维修', '收集日常物', '水泵循环', '现场适配'], sourceUrl: 'https://venezia-biennale-japan.jpf.go.jp/e/art/2024', images: [], relations: [] },
      { title: 'I/O', cluster: 'electromagnetic / sound / movement', period: '2011–', summary: '把环境中的电磁和机械变化转换成声音与运动反馈。', actions: ['传感 / 电路', '声音输出', '机械运动'], sourceUrl: 'https://mohrizm.net/', images: [], relations: [] },
      { title: 'Decomposition', cluster: 'fruit / electricity / decay', period: '2021–', summary: '电极插入水果，把湿度变化转换成声音和灯光；腐败持续改写作品。', actions: ['水果采集', '电极', '模拟电路', '声音 / 灯光实时反馈'], sourceUrl: 'https://mohrizm.net/works/decomposition/', images: [img('https://images.squarespace-cdn.com/content/v1/5d18a9c55ad346000147679d/92f50dfd-e655-46d6-bf13-5adff7900f37/L1120294.JPG?format=2500w', 'Decomposition', '© Yuko Mohri', 'https://mohrizm.net/works/decomposition/', 'Artist website')], relations: [] },
      { title: 'Compose', cluster: 'Japan Pavilion / site-specific ecosystem', period: '2024', summary: '把日本馆建筑当作现场工作室，使用威尼斯当地材料重制 Leaky 与 Decomposition。', actions: ['当地采购', '馆内现场制作', '漏水循环', '腐烂水果发声'], sourceUrl: 'https://venezia-biennale-japan.jpf.go.jp/e/art/2024', images: [img('https://assets.st-note.com/img/1735284454-TJpVQHNDBPslnqxw38udFk01.jpg?width=1200', 'Compose — Japan Pavilion', '© Yuko Mohri / installation documentation', 'https://venezia-biennale-japan.jpf.go.jp/e/art/2024', 'Japan Foundation')], relations: [rel('展览', 'Japan Pavilion — Venice Biennale', '2024'), rel('策展', 'Sook-Kyung Lee', '2024')] }
    ], awards: [], exhibitions: ['14th Gwangju Biennale 2023', 'Japan Pavilion — Venice Biennale 2024'], sources: [{ label: 'Japan Pavilion', url: 'https://venezia-biennale-japan.jpf.go.jp/e/art/2024' }]
  },
  'inuuteq-storch': {
    artistId: 'inuuteq-storch', projectCoverage: '4 个家庭 / 日记 / 国家馆项目已完成第一轮 · 2018–2024', imageCoverage: '', note: '覆盖家庭档案、私人日记式摄影、长期地方拍摄和丹麦馆。',
    projects: [
      { title: 'Porcelain Souls', cluster: 'family archive / letters', period: '2018', summary: '以父母留下的照片和信件构成家庭内部史。', actions: ['家庭档案整理', '书信编辑', '摄影书'], sourceUrl: 'https://www.inuuteqstorch.com/', images: [], relations: [] },
      { title: 'Flesh', cluster: 'personal diary / body', period: '2019', summary: '以朋友、身体和私人生活构成来自格陵兰内部的青年视觉日记。', actions: ['日常拍摄', '朋友肖像', '摄影书编辑'], sourceUrl: 'https://www.inuuteqstorch.com/', images: [], relations: [] },
      { title: 'Keepers of the Ocean', cluster: 'Sisimiut / everyday life', period: '2022', summary: '长期拍摄 Sisimiut 的生活和年轻人，以普通日常抵抗外部异域化视角。', actions: ['长期拍摄', '地方关系', '出版'], sourceUrl: 'https://www.inuuteqstorch.com/', images: [], relations: [] },
      { title: 'Rise of the Sunken Sun', cluster: 'Denmark Pavilion / Greenlandic perspective', period: '2024', summary: '个人摄影与格陵兰视觉史共同进入丹麦馆。', actions: ['跨系列编辑', '档案与当代照片并置', '国家馆空间编排'], sourceUrl: 'https://www.inuuteqstorch.com/', images: [img('https://images.squarespace-cdn.com/content/v1/57867c3203596edb2dc8e554/94584a23-4c3f-46a4-932c-f1ea6d3eff4a/07_Danish_Pavilion_Biennale_2024_inst_views_ph_%C2%A9_Ugo_Carmeni.jpg', 'Rise of the Sunken Sun', '© Inuuteq Storch / photo Ugo Carmeni', 'https://www.inuuteqstorch.com/', 'Artist website')], relations: [rel('展览', 'Denmark Pavilion — Venice Biennale', '2024')] }
    ], awards: [], exhibitions: ['Sharjah Biennial 15 — 2023', 'Denmark Pavilion — Venice Biennale 2024'], sources: [{ label: 'Artist website', url: 'https://www.inuuteqstorch.com/' }]
  },
  'kapwani-kiwanga': {
    artistId: 'kapwani-kiwanga', projectCoverage: '3 个研究 / 材料 / 国家馆项目已完成第一轮 · 2013–2024', imageCoverage: '', note: '覆盖 Flowers for Africa、Greenbook 与 Trinket。',
    projects: [
      { title: 'Flowers for Africa', cluster: 'archive / independence / living material', period: '2013–', summary: '根据非洲独立仪式档案照片重新制作花束，让它们在展厅自然衰败。', actions: ['档案检索', '识别花材', '花艺重建', '自然衰败'], sourceUrl: 'https://www.kapwanikiwanga.org/', images: [], relations: [] },
      { title: 'Greenbook', cluster: 'segregation / mobility / archive', period: '2019', summary: '从 Green Book 和种族隔离旅行史研究空间、安全与移动权。', actions: ['历史研究', '档案图像', '空间装置'], sourceUrl: 'https://www.kapwanikiwanga.org/', images: [], relations: [] },
      { title: 'Trinket', cluster: 'Canada Pavilion / beads / colonial trade', period: '2024', summary: '以约七百万颗 Venetian seed beads 形成穿过加拿大馆的珠帘。', actions: ['珠子采购 / 编织', '建筑介入', '观众穿行'], sourceUrl: 'https://www.labiennale.org/en/art/2024/canada', images: [img('https://images.squarespace-cdn.com/content/v1/55fb5ba0e4b0f81e4e52f39a/d1b78380-024b-4bda-893e-a346f141709a/Trinket_press_edited_high-10.jpg', 'Trinket', '© Kapwani Kiwanga', 'https://www.labiennale.org/en/art/2024/canada', 'La Biennale di Venezia')], relations: [rel('展览', 'Canada Pavilion — Venice Biennale', '2024')] }
    ], awards: ['Prix Marcel Duchamp 2020'], exhibitions: ['Canada Pavilion — Venice Biennale 2024'], sources: [{ label: 'Venice Canada Pavilion', url: 'https://www.labiennale.org/en/art/2024/canada' }]
  },
  'gulsun-karamustafa': {
    artistId: 'gulsun-karamustafa', projectCoverage: '3 个迁徙 / 影像 / 国家馆节点已完成第一轮 · 1992–2024', imageCoverage: '', note: '先以迁徙材料、男性气质和 2024 Türkiye Pavilion 建立主线。',
    projects: [
      { title: 'Mystic Transport', cluster: 'migration / bedding / installation', period: '1992', summary: '彩色缎面被褥装在金属篮中，像被打包又无法安置的家庭物。', actions: ['纺织物', '金属篮', '重复排列'], sourceUrl: 'https://gulsunkaramustafa.com/', images: [], relations: [] },
      { title: 'Men Crying', cluster: 'gender / video', period: '2001', summary: '男性哭泣的表演录像拆解强硬男性气质。', actions: ['表演', '录像', '序列'], sourceUrl: 'https://gulsunkaramustafa.com/', images: [], relations: [] },
      { title: 'Hollow and Broken: A State of the World', cluster: 'Türkiye Pavilion / world condition', period: '2024', summary: '通过材料、空洞与破裂的整体空间回应当代世界的不稳定。', actions: ['大型空间装置', '跨材料组合', '国家馆整体编排'], sourceUrl: 'https://turkiyepavilion24.iksv.org/', images: [img('https://turkiyepavyonu24.iksv.org/images/content/Gulsun-Karamustafa-Stoic-City-2021-1.jpg', 'Stoic City', '© Gülsün Karamustafa', 'https://turkiyepavilion24.iksv.org/', 'Türkiye Pavilion / IKSV')], relations: [rel('展览', 'Türkiye Pavilion — Venice Biennale', '2024')] }
    ], awards: [], exhibitions: ['31st São Paulo Biennial 2014', 'Türkiye Pavilion — Venice Biennale 2024'], sources: [{ label: 'Türkiye Pavilion', url: 'https://turkiyepavilion24.iksv.org/' }]
  },
  'gliceria-tupinamba': {
    artistId: 'gliceria-tupinamba', projectCoverage: '3 个 mantle / 社群 / 国家馆节点已完成第一轮 · 长期–2024', imageCoverage: '', note: '把研究、制作、流通和 Hãhãwpuá Pavilion 连在一起。',
    projects: [
      { title: 'Manto Tupinambá', cluster: 'indigenous knowledge / restitution', period: '长期', summary: '研究欧洲博物馆中的历史 mantle，并与 Tupinambá 社群恢复制作知识。', actions: ['博物馆档案研究', '社群知识', '天然材料', '共同制作'], sourceUrl: 'https://bienal.org.br/', images: [], relations: [] },
      { title: 'Manto em Movimento', cluster: 'movement / community / return', period: '2023–2024', summary: '让 mantle 的制作与移动成为文化复归和公共讨论的一部分。', actions: ['制作', '移动 / 展示', '社群活动'], sourceUrl: 'https://bienal.org.br/', images: [], relations: [] },
      { title: 'Ka’a Pûera: we are walking birds', cluster: 'Hãhãwpuá Pavilion / indigenous nationhood', period: '2024', summary: '把 mantle、鸟、土地与原住民政治主体性组织在一起。', actions: ['国家馆重命名 / 策展语境', 'mantle展示', '社群知识'], sourceUrl: 'https://bienal.org.br/', images: [img('https://riff.media/cdn-cgi/image/width%3D3840%2Cquality%3D75/images/gliceria-tupinamba-federmantel-brasilianischer-pavillon-biennale-venezia-2024.jpg?s=a36a7700f4eecd00aa4d99eb48390dd9&w=1701', 'Manto Tupinambá — Hãhãwpuá Pavilion', '© Glicéria Tupinambá', 'https://bienal.org.br/', 'Fundação Bienal de São Paulo')], relations: [rel('展览', 'Hãhãwpuá Pavilion — Venice Biennale', '2024')] }
    ], awards: [], exhibitions: ['Hãhãwpuá Pavilion — Venice Biennale 2024'], sources: [{ label: 'Fundação Bienal de São Paulo', url: 'https://bienal.org.br/' }]
  },
  'doruntina-kastrati': {
    artistId: 'doruntina-kastrati', projectCoverage: '4 个劳动 / 声音 / 双年展项目已完成第一轮 · 2020–2025', imageCoverage: '', note: '从公共记忆、Manifesta 到 Venice/Sharjah/Istanbul，追踪工业劳动研究如何持续扩展。',
    projects: [
      { title: 'Public Heroes and Secrets', cluster: 'public memory', period: '2020', summary: '研究公共记忆中的英雄化与被隐藏经验。', actions: ['社会研究', '雕塑 / 空间'], sourceUrl: 'https://doruntinakastrati.com/', images: [], relations: [] },
      { title: 'Ring the Bells My Land', cluster: 'Manifesta / sound / place', period: '2022', summary: '通过声音与空间处理地方经验和被压抑叙事。', actions: ['声音', '场域研究', '装置'], sourceUrl: 'https://manifesta14.org/', images: [], relations: [rel('展览', 'Manifesta 14', '2022')] },
      { title: 'The Echoing Silences of Metal and Skin', cluster: 'Kosovo Pavilion / industrial labour', period: '2024', summary: '以女性工业工人的口述、金属、声音和身体损耗构成国家馆。', actions: ['口述史', '金属雕塑', '声音', '影像'], sourceUrl: 'https://2024.pavilionofkosovo.com/', images: [img('https://resources.koha.net/images/2024/April/19/c24abd6a-dda4-4797-b478-4ef494ee040b.webp?h=550&q=90&r=fill&w=860', 'The Echoing Silences of Metal and Skin', '© Doruntina Kastrati', 'https://2024.pavilionofkosovo.com/', 'Kosovo Pavilion')], relations: [rel('展览', 'Kosovo Pavilion — Venice Biennale', '2024'), rel('奖项', 'Special Mention for National Participation', '2024')] },
      { title: 'A Horn That Swallows Songs', cluster: 'Istanbul Biennial / continuing labour research', period: '2025', summary: '以声音与雕塑继续处理劳动、身体和工业结构。', actions: ['声音', '雕塑', '空间编排'], sourceUrl: 'https://bienal.iksv.org/', images: [], relations: [rel('展览', '18th Istanbul Biennial', '2025'), rel('展览', 'Sharjah Biennial 16', '2025')] }
    ], awards: ['Special Mention — Venice Biennale 2024 National Participation'], exhibitions: ['Kosovo Pavilion — Venice 2024', 'Sharjah Biennial 16 — 2025', '18th Istanbul Biennial — 2025'], sources: [{ label: 'Kosovo Pavilion', url: 'https://2024.pavilionofkosovo.com/' }]
  },
  'rosana-paulino': {
    artistId: 'rosana-paulino', projectCoverage: '4 个档案 / 身体 / Venice 节点已完成第一轮 · 1997–2026', imageCoverage: '', note: '把早期缝纫、殖民科学档案、艺术家书和 2026 巴西馆连接起来。',
    projects: [
      { title: 'Bastidores', cluster: 'family portrait / sewing / violence', period: '1997', summary: '黑人女性肖像被转到刺绣框织物上，再用粗重缝线遮挡与刺穿。', actions: ['家庭照片', '转印', '刺绣框', '缝纫'], sourceUrl: 'https://www.moma.org/artists/42174-rosana-paulino', images: [], relations: [rel('收藏', 'MoMA', 'works in collection')] },
      { title: 'Assentamento', cluster: 'racial science / cut and stitch', period: '2012–2014', summary: '切开殖民科学中的黑人身体图像并重新缝合，使分类影像出现真实裂痕。', actions: ['档案挪用', '放大打印', '切割', '缝合'], sourceUrl: 'https://www.moma.org/artists/42174-rosana-paulino', images: [], relations: [] },
      { title: '¿História Natural?', cluster: 'artist book / natural history critique', period: '2016', summary: '把植物、科学分类、奴隶制与黑人身体压进一本伪“自然史”。', actions: ['版画', '档案图像', '艺术家书', '分类结构挪用'], sourceUrl: 'https://www.moma.org/artists/42174-rosana-paulino', images: [], relations: [] },
      { title: 'Comigo ninguém pode', cluster: 'Brazil Pavilion / colonial histories', period: '2026', summary: '与 Adriana Varejão 共同代表巴西，把长期殖民身体和历史研究带入国家馆。', actions: ['跨系列重编', '国家馆展示', '档案 / 植物 / 身体关系'], sourceUrl: 'https://www.labiennale.org/en/art/2026/national-participations', images: [img('https://static.labiennale.org/files/styles/seo_thumbnail/public/arte/2022/600x600/rosana_paulino_biennale_arte_2022_600x600.jpg?itok=s7J4sDzn', 'Rosana Paulino — Venice context', '© Rosana Paulino / La Biennale di Venezia', 'https://www.labiennale.org/en/art/2022/milk-dreams/rosana-paulino', 'La Biennale di Venezia')], relations: [rel('展览', 'Brazil Pavilion — Venice Biennale', '2026')] }
    ], awards: [], exhibitions: ['Venice International Exhibition 2022', 'Brazil Pavilion — Venice Biennale 2026'], sources: [{ label: 'MoMA', url: 'https://www.moma.org/artists/42174-rosana-paulino' }]
  },
  'abbas-akhavan': {
    artistId: 'abbas-akhavan', projectCoverage: '4 个纪念 / 花园 / 国家馆项目已完成第一轮 · 2013–2026', imageCoverage: '', note: '以植物纪念物、建筑复制、花园和 2026 加拿大馆串起场域特定方法。',
    projects: [
      { title: 'Study for a Monument', cluster: 'plants / war / memorial', period: '2013–', summary: '把伊拉克等地植物重制成断裂的青铜“标本”，以生态替代英雄纪念。', actions: ['植物研究', '铸造', '分散陈列'], sourceUrl: 'https://www.guggenheim.org/artwork/artist/abbas-akhavan', images: [img('https://dza2a2ql7zktf.cloudfront.net/binaries-cdn/dqzqcuqf9/image/fetch/q_auto%2Ch_920%2Cw_920%2Cdpr_auto%2Cc_fit/https%3A/d2u3kfwd92fzu7.cloudfront.net/catalog/artwork/gallery/1663/THETHRIDLINE_BASEL15_026-1.jpg', 'Study for a Monument', '© Abbas Akhavan', 'https://www.guggenheim.org/artwork/artist/abbas-akhavan', 'Guggenheim')], relations: [] },
      { title: 'cast for a folly', cluster: 'architectural copy / heritage', period: '2019–2023', summary: '复制建筑与装饰碎片，处理文化遗产、破坏和离开原址后的意义。', actions: ['建筑研究', '铸模 / 复制', '空间布置'], sourceUrl: 'https://walkerart.org/', images: [], relations: [] },
      { title: 'Variations on a Folly', cluster: 'garden / site-specific installation', period: '2021–', summary: '围绕花园和建筑遗迹发展多个变化版本，作品随场地而重新组成。', actions: ['场地研究', '植物 / 建筑材料', '版本化安装'], sourceUrl: 'https://walkerart.org/', images: [], relations: [] },
      { title: 'Entre chien et loup', cluster: 'Canada Pavilion / Wardian case / water lilies', period: '2026', summary: '把加拿大馆转成类似 Wardian case 的植物运输容器，以 Victoria 巨型睡莲连接英国帝国植物贸易。', actions: ['建筑改造', '定制水池', 'grow lights', '活体睡莲', '殖民植物史研究'], sourceUrl: 'https://www.labiennale.org/en/art/2026/canada', images: [], relations: [rel('展览', 'Canada Pavilion — Venice Biennale', '2026'), rel('策展', 'Kim Nguyen', '2026')] }
    ], awards: [], exhibitions: ['Canada Pavilion — Venice Biennale 2026', 'Walker Art Center survey 2026'], sources: [{ label: 'Venice Canada Pavilion', url: 'https://www.labiennale.org/en/art/2026/canada' }]
  }
};
