import type { ArtistArchive, ArchiveProject, ArchiveRelation } from './archiveData';
const rel=(kind:ArchiveRelation['kind'],label:string,detail?:string):ArchiveRelation=>({kind,label,detail});
const project=(p:ArchiveProject)=>p;

export const archiveBatch307:Record<string,ArtistArchive>={
  'trevor-paglen':{
    artistId:'trevor-paglen',
    projectCoverage:'作品级深化第三批：Limit Telephotography、Drones、The Last Pictures、KEYHOLE IMPROVED CRYSTAL、NSA-Tapped Fiber Optic Cable Landing Site。重点补远距离光学方法、具体焦距/距离、输出媒介尺寸、卫星追踪协作、海底光缆调查与太空长期保存工艺。',
    imageCoverage:'Trevor Paglen Studio 与 Metropolitan Museum of Art 均提供对应作品图。Met 对两件馆藏明确标注版权限制/不可下载或 © Trevor Paglen；艺术家官网图亦未确认自由再发布。本批保存官方作品图入口、机构、版权与 image-request 状态，images 保持暂缺，不以无关图替代。',
    note:'这一批补 Paglen 从地面秘密基地、无人机、秘密卫星、海底光缆到地球同步轨道的五种“看不见基础设施”生产方法，重点记录他到底如何取得图像，而非只概括 surveillance 主题。',
    projects:[
      project({title:'Limit Telephotography — Chemical and Biological Weapons Proving Ground / NRO Ground Station',cluster:'long-distance landscape photography / telescope / classified sites',period:'2006–2012',summary:'Limit Telephotography 是 Paglen 为拍摄被大面积军事禁区包围、肉眼根本无法辨认的秘密设施发展出的远距离摄影方法。他不是进入基地偷拍，而是在合法可到达的位置架设类似天文摄影的望远镜系统，以约1300–7000mm焦距穿过几十英里的大气拍摄。Chemical and Biological Weapons Proving Ground; Dugway, UT 从约42英里外拍摄，最终为40 × 40 in C-print；National Reconnaissance Office Ground Station (ADF-SW), Jornada del Muerto 从约16英里外拍摄，为37 1/2 × 48 1/4 in C-print。超长空气路径造成热扰动、雾化和低对比度，因此图像的模糊不是风格滤镜，而是政治地理距离实际进入摄影材料的结果。',actions:['调查 classified military bases / weapons ranges 的地理位置与公共土地边界。','选择不闯入禁区但能获得视线的远距离观察点。','使用约1300–7000mm望远镜焦距，把天文摄影技术转向地面秘密设施。','让几十英里大气造成的热浪、散射和失真保留在最终图像中，而不是数字修复成清晰监控照。','将结果制作成大尺幅 C-print，使观众在展厅中仍需主动寻找远处微小设施。'],sourceUrl:'https://paglen.studio/2020/04/22/limit-telephotography/',images:[],relations:[rel('具体作品','Chemical and Biological Weapons Proving Ground; Dugway, UT — 2006/2007','Distance approx. 42 miles；C-Print；40 × 40 in。'),rel('具体作品','National Reconnaissance Office Ground Station (ADF-SW) — 2012','Distance ~16 miles；C-Print；37 1/2 × 48 1/4 in。'),rel('技术','Trevor Paglen Studio — Limit Telephotography','艺术家明确记录 telescopes focal lengths 1300–7000mm，并将方法类比 astrophotography。'),rel('版权','Paglen Studio official images','保存官方作品图入口；未确认自由再发布，本站不复制。')]}),
      project({title:'Drones — Untitled (Reaper Drone) / Untitled (Sentinel Drone)',cluster:'military drone photography / Nevada sky / C-print & pigment print',period:'2010–2015',summary:'Drones 系列把相机对准 Nevada 沙漠上空，而不是无人机执行任务的海外战区。Creech Air Force Base、Area 52 等地点的飞行员通过卫星链路远程操控美军和情报无人机；Paglen 在这些训练/控制基础设施附近等待并拍摄天空，让 Predator、Reaper、Sentinel 只以极小黑点进入广阔云层。Untitled (Reaper Drone) 有2010、2013等48 × 60 in C-print版本，2015版本改为48 × 60 in pigment print；Untitled (Sentinel Drone), 2014 为20 × 25 in C-print。作品的观看动作因此与拍摄动作对应：摄影师必须在天空中寻找几乎不可见的机器，观众也必须在大幅风景中重新定位那个微小军事对象。',actions:['前往 Nevada 军事航空/远程无人机控制基础设施周边可合法观察的地点。','持续观察并识别 Predator、Reaper、Sentinel 等机型进入天空的时刻。','以大面积天空构图保留无人机在真实视觉尺度中的微小状态，而不是裁切成新闻式特写。','按不同年份制作 C-print，并在2015 Reaper 版本使用 pigment print。','通过48 × 60 in等大幅输出，让观众靠近图像搜索无人机。'],sourceUrl:'https://paglen.studio/2020/01/21/untitled-drones/',images:[],relations:[rel('具体作品','Untitled (Reaper Drone) — 2010/2013','C-Print；48 × 60 in。'),rel('版本','Untitled (Reaper Drone) — 2015','Pigment print；48 × 60 in；同一母题出现输出工艺变化。'),rel('具体作品','Untitled (Sentinel Drone) — 2014','C-Print；20 × 25 in。'),rel('版权','Trevor Paglen Studio','官方作品页提供系列图与 detail；未确认自由再发布。')]}),
      project({title:'The Last Pictures — EchoStar XVI orbital artifact',cluster:'space artifact / micro-etched archive / gold-plated shell / satellite',period:'2012–2013',summary:'The Last Pictures 的最终作品不是一张卫星照片，而是一件真正被送入地球同步轨道的图像档案。Paglen 与 Creative Time 合作，并与 MIT 材料科学家开发可承受太空环境、目标寿命以十亿年计的微蚀刻圆盘：圆盘写入100张经过多年与科学家、艺术家、人类学家、哲学家讨论后选择的图像，再封装进镀金外壳。2012年11月，它被固定在通信卫星 EchoStar XVI 背向地球的一侧，从哈萨克斯坦 Baikonur 发射并进入约36,000 km高的 geosynchronous orbit；卫星完成约15年通信任务后计划进入 graveyard orbit。艺术家工作室另记录2013地面 Artifact 为 golden disc，8 × 8 × 1/2 in。作品的主要“观众”因此不是当下美术馆访客，而是假设中的遥远未来发现者；当下观众看到的是100图 mosaic、圆盘实体、制造/发射文档和出版物。',actions:['通过多年访谈与研究从人类历史、技术、生态和政治图像中编辑100张图片。','与 MIT 材料科学家共同开发 micro-etched disc，而非使用普通纸质或硬盘存储。','把微蚀刻图像圆盘封装进 gold-plated shell，以应对长期太空环境。','将档案真实安装到 EchoStar XVI anti-earth deck，并随卫星从 Baikonur 发射。','同时制作地面 golden-disc artifact、100图 mosaic、项目网站和书籍，使无法直接观看的轨道作品留下可研究接口。'],sourceUrl:'https://paglen.studio/2020/01/21/the-last-pictures/',images:[],relations:[rel('委托','Creative Time — The Last Pictures','公共艺术机构委托；项目与 MIT 合作生产。'),rel('工程','EchoStar XVI — November 2012','作品安装在卫星 anti-earth deck；进入约36,000 km geosynchronous orbit。'),rel('物件','The Last Pictures Artifact — 2013','Golden disc；8 × 8 × 1/2 in。'),rel('版权','Paglen Studio / project documentation','官网提供圆盘、图像 mosaic、火箭准备等记录；未确认自由再发布。')]}),
      project({title:'KEYHOLE IMPROVED CRYSTAL from Glacier Point (Optical Reconnaissance Satellite; USA 186)',cluster:'secret satellite tracking / astrophotography / chromogenic print',period:'2008',summary:'这件作品把19世纪美国西部风景摄影与21世纪秘密侦察卫星压进同一张长曝光图像。Paglen 在 Yosemite Glacier Point 面对 Half Dome 架设相机，并利用业余卫星观察者建立的轨道数据库预测 USA 186 / KEYHOLE IMPROVED CRYSTAL 经过的位置和时间；这些观察者的历史可追溯到冷战时期由美国政府训练寻找苏联 Sputnik 的民间天文网络。曝光期间星体形成弧形 star trails，侦察卫星则以一条幽灵般的白色轨迹切过 Half Dome。Met 馆藏版本为2008 chromogenic print，image 95.3 × 76.2 cm，frame 96.5 × 77.5 cm。它的制作核心不是后期画一条线，而是轨道情报、现场选址、时间预测与长曝光共同让秘密航天器留下光学痕迹。',actions:['与/利用业余天文观察者网络追踪官方不公开的侦察卫星轨道。','计算 USA 186 从 Yosemite / Glacier Point 可见的过境时间与方位。','把相机朝向 Half Dome，以美国风景摄影史中的经典地标作为地面参照。','进行长曝光，使恒星运动形成 star trails，同时让卫星过境留下独立白色轨迹。','制作 chromogenic print；Met 馆藏图像尺寸95.3 × 76.2 cm。'],sourceUrl:'https://www.metmuseum.org/art/collection/search/296323',images:[],relations:[rel('收藏','The Metropolitan Museum of Art — 2011.77','Chromogenic print；Image 95.3 × 76.2 cm；Frame 96.5 × 77.5 cm。'),rel('方法','Amateur satellite observers','Met 记录 Paglen 使用由业余天文学家建立的数据库追踪 spacecraft。'),rel('版权','The Met artwork image','馆藏页明确 image cannot be enlarged/full-screen/downloaded；受版权限制，本站不复制。')]}),
      project({title:'NSA-Tapped Fiber Optic Cable Landing Site, Keawaula, Hawaii, United States',cluster:'undersea cable investigation / diptych / photograph + Snowden-document collage',period:'2016',summary:'这件作品来自 Paglen 对全球海底光缆“choke points”的调查：NSA 等情报系统会在大量跨洋通信汇聚的登陆点实施截取。他先实地定位 Hawaii Keawaula 的光缆/数据收集基础设施并拍摄地表景观，再取得同一地点的航海/导航图，在第二幅图上拼贴 Snowden archive 中与监控系统有关的材料。最终作品不是单张风景，而是一组 unique diptych：一边让基础设施藏在普通海岸景观中，另一边以地图和泄密文件显露不可见的数据路径。Met 登记媒介为 inkjet print；mixed media on inkjet print，每幅48 × 65 in（121.9 × 165.1 cm），每框49 1/2 × 66 1/2 in；© Trevor Paglen。',actions:['研究海底光缆登陆点与 NSA intelligence-gathering choke points 的地理位置。','前往 Keawaula, Hawaii 拍摄登陆点上方看似普通的海岸景观。','取得同地点 navigational chart，建立地表摄影与海底网络的空间对应。','把 Snowden archive 中的监控文件材料拼贴到地图/喷墨输出上。','以两幅并置的 unique diptych 展示：一幅是地景，一幅是被文件标注出来的通信/监控结构。'],sourceUrl:'https://www.metmuseum.org/art/collection/search/725680',images:[],relations:[rel('收藏','The Metropolitan Museum of Art — 2016.400a, b','Inkjet print；mixed media on inkjet print；each image 121.9 × 165.1 cm。'),rel('档案','Snowden archive','Met 明确记录导航图上拼贴来自 Snowden archive 的材料。'),rel('版权','The Met / © Trevor Paglen','馆藏页明确 Rights and Reproduction: © Trevor Paglen；受限图像需另行申请，本站不复制。')]})
    ],
    awards:[],
    exhibitions:['Trevor Paglen: Sites Unseen — Smithsonian American Art Museum — 2018'],
    sources:[
      {label:'Trevor Paglen Studio — Limit Telephotography',url:'https://paglen.studio/2020/04/22/limit-telephotography/'},
      {label:'Trevor Paglen Studio — Drones',url:'https://paglen.studio/2020/01/21/untitled-drones/'},
      {label:'Trevor Paglen Studio — The Last Pictures',url:'https://paglen.studio/2020/01/21/the-last-pictures/'},
      {label:'The Last Pictures project archive',url:'https://paglen.studio/lastpictures/index.html'},
      {label:'The Met — KEYHOLE IMPROVED CRYSTAL from Glacier Point',url:'https://www.metmuseum.org/art/collection/search/296323'},
      {label:'The Met — NSA-Tapped Fiber Optic Cable Landing Site, Keawaula',url:'https://www.metmuseum.org/art/collection/search/725680'}
    ]
  }
};
