import type { ArtistArchive, ArchiveRelation } from './archiveData';
const rel=(kind:ArchiveRelation['kind'],label:string,detail?:string):ArchiveRelation=>({kind,label,detail});

export const archiveBatch264:Record<string,ArtistArchive>={
  'thomas-ruff':{
    artistId:'thomas-ruff',
    projectCoverage:'作品级深化：把 Ruff 从大幅肖像一路连接到天文档案、网络色情与 JPEG 压缩图像，突出其核心不是固定题材，而是持续更换图像生产制度来测试摄影真实性。',
    imageCoverage:'Guggenheim 与 Metropolitan Museum 提供 Portrait、Stars、Nudes、jpeg 等官方作品页；本批只保存官方入口，不复制版权受限图像。',
    note:'Ruff 的重要性在于他很早就把摄影从“摄影师面对世界按快门”扩展成对既有图像系统的再加工。肖像看似极度清晰却无法提供心理真相；Stars 直接采用天文机构图像；Nudes 下载网络色情；jpeg 则把压缩与像素化本身放大成画面结构。',
    projects:[
      {title:'Portraits / Portrait (A. Siekmann)',cluster:'portrait / scale / photographic opacity',period:'1980s–',summary:'Ruff 在杜塞尔多夫时期由小幅黑白肖像转向彩色、纯色背景与巨幅输出。Met 收藏的 A. Siekmann（1987）约210×165厘米：极高细节让皮肤、毛发几乎像标本一样可读，但人物思想和情绪仍不可进入。清晰度因此不等于心理真实性。',actions:['使用正面、克制的肖像结构减少戏剧性线索。','把彩色肖像放大到接近广告/公共图像尺度。','让观看者获得过量表面细节，却不给稳定的人格解释。'],sourceUrl:'https://www.metmuseum.org/art/collection/search/282757',images:[],relations:[rel('收藏','The Metropolitan Museum of Art','Portrait (A. Siekmann), 1987。'),rel('展览','Guggenheim artist archive','将 Portraits 放入 Ruff 从学院摄影转向多种图像制度的实践脉络。')]},
      {title:'Stars',cluster:'appropriation / astronomy / institutional image',period:'1989–90',summary:'Ruff 没有自己拍摄星空，而从 Ruhr-Universität Bochum 的天文研究图像取得材料并转化为大型摄影作品。Met 的 Stars, 05h, 08m / -45 degrees（1990）达到约257.7×186.6厘米。作者性从“拍到星星”转向选择、裁切、尺度与展示。',actions:['从科学机构取得既有天文摄影。','把科学记录重新裁切/选择并转成艺术展示尺度。','保留坐标式标题，让科学分类语言与美术馆观看并置。'],sourceUrl:'https://www.metmuseum.org/art/collection/search/266350',images:[],relations:[rel('收藏','The Metropolitan Museum of Art','Stars, 05h, 08m / -45 degrees, 1990。'),rel('展览','Guggenheim artist archive','记录 Stars 来源于 Ruhr-Universität Bochum 天文研究图像。')]},
      {title:'Nudes → jpeg',cluster:'internet image / digital manipulation / compression',period:'1999–2007',summary:'Nudes 从互联网色情图像下载材料，再通过电脑强化颜色、模糊轮廓并大幅放大；随后 jpeg 更进一步，把网络传播图像的压缩、低分辨率和像素结构直接变成作品形式。Met 的 Nudes ree07（2000）与 jpeg ny02（2004）分别提供这两阶段的具体馆藏节点。',actions:['把互联网既有图像作为原始材料而非现场拍摄。','在 Nudes 中使用模糊、色彩调整与尺度改变，使网络私密/公共观看问题进入美术馆。','在 jpeg 中主动放大低分辨率与压缩痕迹，使图像传输损耗成为可见结构。'],sourceUrl:'https://www.guggenheim.org/artwork/artist/thomas-ruff',images:[],relations:[rel('收藏','The Metropolitan Museum of Art','Nudes ree07 (2000)；jpeg ny02 (2004)。'),rel('展览','Venice Biennale','Guggenheim档案记录 Ruff 参加1995与2005 Venice Biennale。')]}
    ],awards:[],exhibitions:['documenta 9, 1992','Venice Biennale, 1995 / 2005','Tate Liverpool solo exhibition, 2003'],sources:[{label:'Guggenheim · Thomas Ruff',url:'https://www.guggenheim.org/artwork/artist/thomas-ruff'},{label:'Met · Portrait (A. Siekmann)',url:'https://www.metmuseum.org/art/collection/search/282757'},{label:'Met · Stars',url:'https://www.metmuseum.org/art/collection/search/266350'},{label:'Met · Nudes ree07',url:'https://www.metmuseum.org/art/collection/search/284212'},{label:'Met · jpeg ny02',url:'https://www.metmuseum.org/art/collection/search/287237'}]
  },
  'joan-fontcuberta':{
    artistId:'joan-fontcuberta',projectCoverage:'实践深化：把 Fontcuberta 的伪科学/伪档案方法与其摄影理论、编辑工作和 Sputnik 的出版—展览制度连接起来，强调他制造的不是单张假照片，而是完整可信机制。',imageCoverage:'MACBA 保存艺术家档案及 Sputnik 1997 展览出版物记录；本批保存官方研究入口。',note:'Fontcuberta 的关键不只是“摄影会撒谎”，而是模拟科学、博物馆、出版、档案与新闻的权威语法，让虚构先获得制度可信度，再迫使观众反思自己为何相信。',projects:[
      {title:'Sputnik',cluster:'fictional archive / institutional credibility / media literacy',period:'1997',summary:'Sputnik 围绕苏联太空史建立伪档案叙事，并以照片、文本、出版物和展览语法制造历史可信感。MACBA 保存的同名1997出版物明确对应 Fundación Arte y Tecnología 1997年5月21日至7月20日展览，并记录 Telefónica / Fundación Arte y Tecnología 的机构合作。作品因此应被理解为“可信系统设计”，而非孤立的伪造照片。',actions:['模仿历史档案与航天资料的视觉语言。','把摄影、文字、出版和展览共同组织成可验证感很强的证据链。','借真实机构展示/出版环境强化观众最初的信任，再让虚构暴露这种信任的制度来源。'],sourceUrl:'https://www.macba.cat/en/obra/a14280-sputnik--/',images:[],relations:[rel('展览','Fundación Arte y Tecnología, Madrid','21 May–20 Jul 1997；Sputnik 展览。'),rel('出版','Sputnik, 1997','MACBA Centre d’Estudis i Documentació 保存展览出版物。'),rel('收藏','MACBA documentation collection','保存多个 Sputnik 文献版本。')]},
      {title:'Photography as constructed truth',cluster:'theory / editorial practice / image credibility',period:'1980s–',summary:'MACBA 将 Fontcuberta 同时定位为摄影家、摄影理论家与编辑，并指出他1980年共同创办双语摄影杂志 PhotoVision。他的艺术与理论持续研究摄影图像的真实性、公共使用、信息污染以及图像如何替代现实；这解释了为什么他的伪档案作品与写作不能拆开阅读。',actions:['通过理论写作直接分析摄影真实性与公共图像机制。','通过 PhotoVision 等编辑实践介入摄影话语生产。','在艺术项目中把理论问题转化成观众会实际误信/怀疑的叙事装置。'],sourceUrl:'https://www.macba.cat/en/actor/joan-fontcuberta/',images:[],relations:[rel('出版','PhotoVision','1980共同创办；西班牙语/英语摄影杂志。'),rel('奖项','Hasselblad Award','MACBA档案记录2013年获奖。')]}
    ],awards:['Hasselblad Award, 2013'],exhibitions:['MoMA, New York, 1989','Fundación Arte y Tecnología: Sputnik, 1997'],sources:[{label:'MACBA · Joan Fontcuberta',url:'https://www.macba.cat/en/actor/joan-fontcuberta/'},{label:'MACBA · Sputnik',url:'https://www.macba.cat/en/obra/a14280-sputnik--/'}]
  },
  'carrie-mae-weems':{
    artistId:'carrie-mae-weems',projectCoverage:'继续深化：在 Kitchen Table / From Here... 之外补入 Sea Islands Series 与早期家庭—民俗学路径，使其从家庭自我表述到黑人历史、语言与视觉制度的演变更完整。',imageCoverage:'Met、National Gallery of Art 与 Guggenheim 提供馆藏/展览官方入口；版权图像不做未经许可复制。',note:'Weems 的摄影不是单纯从私人走向公共，而是不断改变“谁来讲历史”的尺度：家庭成员、厨房中的虚构女性主体、Gullah 社群的口述/物质文化，再到博物馆和殖民档案中的种族化图像。',projects:[
      {title:'Sea Islands Series',cluster:'folklore / Gullah history / image-text narrative',period:'1991–92',summary:'Weems 受过民俗学训练，Sea Islands Series 在 Georgia 与 South Carolina 沿海追踪 Gullah 社群保存的非洲文化痕迹。Met 馆藏 Untitled（1992）拍摄悬挂在树中的床垫弹簧：它并非纯形式主义景观，而与阻挡邪灵的文化用途相关。Guggenheim 回顾展资料同时指出 Sea Islands、Africa 与 Slave Coast 把图像与地方语言、词源和叙事结合。',actions:['进入 Sea Islands 社群研究物质文化、地方知识与历史记忆。','把看似普通/神秘的物件放回其民俗和历史语境，而非只作为诗意形式。','将摄影与口述、方言文字和词源研究并置，让语言成为历史证据的一部分。'],sourceUrl:'https://www.metmuseum.org/art/collection/search/283770',images:[],relations:[rel('收藏','The Metropolitan Museum of Art','Untitled, Sea Island Series, 1992 / printed 2000。'),rel('展览','Guggenheim retrospective','2014回顾展把 Sea Islands 与 Africa、Slave Coast 连成语言/叙事研究线。')]},
      {title:'Kitchen Table Series — institutional afterlife',cluster:'staged narrative / domestic space / museum canon',period:'1990 / 2003 print',summary:'National Gallery of Art 保存的完整 portfolio 由20幅 platinum/palladium photographs 与14张 screenprints 构成。稳定的桌子与吊灯把厨房变成舞台，人物、关系和文本不断变化。2017–18 NGA 专展进一步确认该系列已从早期私人/性别叙事进入美国摄影与当代艺术经典化过程。',actions:['固定厨房桌与单灯作为重复舞台。','由艺术家本人承担中心角色，并通过不同人物进入/离开制造关系变化。','用20幅摄影与14张文字页形成完整叙事，而非把最著名的单张照片当成全部作品。'],sourceUrl:'https://www.nga.gov/exhibitions/carrie-mae-weems-kitchen-table-series',images:[],relations:[rel('收藏','National Gallery of Art','完整34件 portfolio；20 photographs + 14 screenprints。'),rel('展览','NGA: Carrie Mae Weems: Kitchen Table Series','12 Sep 2017–18 May 2018。')]}
    ],awards:[],exhibitions:['Carrie Mae Weems: Three Decades of Photography and Video — Guggenheim, 2014','Carrie Mae Weems: Kitchen Table Series — National Gallery of Art, 2017–18'],sources:[{label:'Met · Sea Island Series',url:'https://www.metmuseum.org/art/collection/search/283770'},{label:'NGA · Kitchen Table Series',url:'https://www.nga.gov/exhibitions/carrie-mae-weems-kitchen-table-series'},{label:'Guggenheim · Three Decades of Photography and Video',url:'https://www.guggenheim.org/press-release/guggenheim-presents-carrie-mae-weems-three-decades-of-photography-and-video'}]
  }
};
