import type { ArtistArchive, ArchiveRelation } from './archiveData';

const rel = (kind: ArchiveRelation['kind'], label: string, detail?: string): ArchiveRelation => ({ kind, label, detail });

const piriciVenice = 'https://www.labiennale.org/en/art/2022/milk-dreams/alexandra-pirici';
const grosvenorVenice = 'https://www.labiennale.org/en/art/2022/milk-dreams/robert-grosvenor';
const zephirinVenice = 'https://www.labiennale.org/en/art/2022/milk-dreams/frantz-z%C3%A9phirin';
const mukherjeeVenice = 'https://www.labiennale.org/en/art/2022/milk-dreams/mrinalini-mukherjee';
const fattalVenice = 'https://www.labiennale.org/en/art/2022/milk-dreams/simone-fattal';
const johannessonVenice = 'https://www.labiennale.org/en/art/2022/milk-dreams/charlotte-johannesson';

export const archiveBatch89: Record<string, ArtistArchive> = {
  'venice-alexandra-pirici': {
    artistId: 'venice-alexandra-pirici',
    projectCoverage: '1 个 collective-live-sculpture 核心节点已建立深档案 · 2022',
    imageCoverage: '0 / 1 项目暂不使用不稳定外链图像',
    note: '当前先把 Venice 2022 的核心项目做深。Pirici 把 performer 当成可持续重组的 live sculpture，不把表演理解为一次性的舞台事件；动作规则、群体关系与长时段 presence 才是作品结构。',
    projects: [
      {
        title: 'Encyclopedia of Relations',
        cluster: 'live sculpture / choreography / symbiosis + parasitism',
        period: '2022',
        summary: '一组 performer 按照可组合的动作规则不断重组，借生物学中的 symbiosis、parasitism 以及 human / technology、rock / wave、plant / animal 等关系建立持续变化的身体网络。作品没有线性开头和结尾，而像活体数据库一样不断生成新组合。',
        actions: [
          '以 trained / instructed performers 组成集体，而不是以单一主角推进 narrative',
          '预先设计一组 possible actions / relations，让 performer 在现场不断选择和组合',
          '从 symbiotic / parasitic biological relations 提取动作逻辑，而不是直接模仿具体动物',
          '让 human / technology、rock / wave、plant / animal 等关系通过身体姿态进入同一 action vocabulary',
          '以 long-duration activation 取代单次 performance event，使作品在观众不同到场时刻都处于中间状态',
          '通过类似 exquisite-corpse 的 recombination，让自然、fantastic image 与 collective body 不断互相改写',
        ],
        sourceUrl: piriciVenice,
        images: [],
        relations: [rel('展览', 'The Milk of Dreams — 59th Venice Biennale', '2022 · Central Pavilion · ongoing performative action')],
      },
    ],
    awards: [],
    exhibitions: ['The Milk of Dreams — Venice Biennale 2022'],
    sources: [{ label: 'La Biennale · Alexandra Pirici 2022', url: piriciVenice }],
  },

  'venice-robert-grosvenor': {
    artistId: 'venice-robert-grosvenor',
    projectCoverage: '3 个 architecture-without-function / industrial-handmade / perceptual-trick 节点已建立深档案 · 1987–2019',
    imageCoverage: '0 / 3 项目暂不使用不稳定外链图像',
    note: '精选项目档案，尚非作品全集。Grosvenor 经常手工制造看似工业生产的结构，让 garage、shed、container、pool 等熟悉建筑类型只保留外观线索却失去正常功能，形成“好像知道它是什么、但又无法使用”的认知错位。',
    projects: [
      {
        title: 'Untitled',
        cluster: 'corrugated iron / trailer fragment / architecture without use',
        period: '1987–1988',
        summary: '作品由 corrugated iron 组成，材料来自艺术家工作室储存工具的 trailer sides。它看起来像灾后残留的 shed / trailer，却没有 ceiling、floor 或 wheels，因此只保留 architecture 的暗示而失去实用结构。',
        actions: [
          '直接取用 studio tool trailer 的 corrugated-iron side panels',
          '保留工业建筑表面，但去除 ceiling / floor / wheels 等功能部件',
          '以 hand-built construction 伪装成可能由工业流程制造的 object',
          '把观众对 shed / trailer 的识别维持在“几乎成立”状态',
          '通过缺失功能制造 post-apocalyptic remnant 与 absurd sculpture 的双重阅读',
        ],
        sourceUrl: grosvenorVenice,
        images: [],
        relations: [rel('展览', 'The Milk of Dreams — Venice Biennale', '2022 · Arsenale')],
      },
      {
        title: 'Untitled — steel container with red scooter',
        cluster: 'industrial container / gold interior / isolated scooter',
        period: '2018',
        summary: '一个 steel industrial container 的内部被涂成金色，里面单独放置一辆 red scooter。容器、车辆与金色内壁都可识别，却没有形成正常 garage / transport function，更像一个无法解释用途的私人 shrine。',
        actions: [
          '采用真实 industrial-container-like steel enclosure 作为外壳',
          '把内部表面整体处理成 gold colour，制造 exterior / interior 的强烈语义反差',
          '在内部孤立放置 red scooter，不提供可驾驶或展示商品的正常使用语境',
          '通过 viewer distance 让 scooter 可见但处于被隔离状态',
          '让 container 在 storage、garage、reliquary 与 stage set 之间保持不确定',
        ],
        sourceUrl: grosvenorVenice,
        images: [],
        relations: [],
      },
      {
        title: 'Block of Water',
        cluster: 'concrete-block pool / water / solidity vs ephemerality',
        period: '2019',
        summary: '用 concrete blocks 做出矩形 pool 并注水。坚硬 masonry 与最不稳定的水被放在同一个极简结构里，既像防御工事又像临时水池，实体与短暂性互相抵消。',
        actions: [
          '以 ordinary concrete blocks 砌出 rectangular enclosure',
          '向结构内部真实注水，使作品依赖 fluid material 而非纯 solid sculpture',
          '保留低技术、handmade construction 的视觉痕迹',
          '让 form 同时接近 pool、bunker、foundation，却不完全执行任何一种建筑功能',
          '利用水的 evaporation / reflection 与 concrete mass 建立 material contradiction',
        ],
        sourceUrl: grosvenorVenice,
        images: [],
        relations: [rel('展览', 'The Milk of Dreams — Venice Biennale', '2022 · Arsenale')],
      },
    ],
    awards: [],
    exhibitions: ['The Milk of Dreams — Venice Biennale 2022'],
    sources: [{ label: 'La Biennale · Robert Grosvenor 2022', url: grosvenorVenice }],
  },

  'venice-frantz-zephirin': {
    artistId: 'venice-frantz-zephirin',
    projectCoverage: '2 个 colonial-history / Vodou / allegorical painting 节点已建立深档案 · 2000–2007',
    imageCoverage: '0 / 2 项目暂不使用不稳定外链图像',
    note: '精选项目档案，尚非作品全集。Zéphirin 用高密度图案、鲜艳色彩和 allegorical reversal 把 Haitian slavery、colonisation、rebellion、Vodou 与 spiritual endurance 压进同一画面；动物 / 人类角色的交换本身就是政治叙事装置。',
    projects: [
      {
        title: 'Les Esprits Indien en face Colonisation',
        cluster: 'Taíno / mermaid / anti-colonial allegory',
        period: '2000',
        summary: '画面中心是 half-Taíno woman / half-fish 的 mermaid figure，远处出现 Spanish vessel；女性身体内部还包含 African male figure。两者都直视观众，把 Indigenous genocide 与 African enslavement 叠成同一个 moral confrontation。',
        actions: [
          '把 Taíno woman 与 fish body 融合成 hybrid central figure',
          '在远景加入 Spanish colonial vessel 建立具体历史方向',
          '将 African male figure 嵌入 central body，使 Indigenous / African histories 不是并排插图而是身体内部关系',
          '使用 frontal gaze 强迫 viewer 成为被质问对象',
          '以 dense pattern / bright colour 抵消西方历史画常用的沉重写实语气',
        ],
        sourceUrl: zephirinVenice,
        images: [],
        relations: [rel('展览', 'The Milk of Dreams — Venice Biennale', '2022 · Arsenale')],
      },
      {
        title: 'The Slave Ship Brooks',
        cluster: 'slave ship / animalised slavers / Haitian Revolution prehistory',
        period: '2007',
        summary: '作品借著名 slave ship Brooks 形象处理跨大西洋奴隶贸易。slavers 被画成 animals，被囚禁的 Africans 仍以 human figures 出现；船外被锁住的 rebels 则被设定为后来 Haitian Revolution 的先声。',
        actions: [
          '以 Brooks slave ship 的历史形象为 compositional anchor',
          '故意将 enslavers animalise，而不是把被奴役者去人化',
          '让 Africans 从船舱 / dungeon-like structure 向外凝视，保持主体性',
          '在 ship exterior 加入 chained rebels，把 captivity 与 future revolution 连接',
          '用 allegory 重写 colonial visual hierarchy，而非复刻 abolitionist diagram',
        ],
        sourceUrl: zephirinVenice,
        images: [],
        relations: [rel('展览', 'The Milk of Dreams — Venice Biennale', '2022 · Arsenale')],
      },
    ],
    awards: [],
    exhibitions: ['The Milk of Dreams — Venice Biennale 2022'],
    sources: [{ label: 'La Biennale · Frantz Zéphirin 2022', url: zephirinVenice }],
  },

  'venice-mrinalini-mukherjee': {
    artistId: 'venice-mrinalini-mukherjee',
    projectCoverage: '2 个 rope-macramé / vegetal-divinity 阶段已建立深档案 · 1970s–1994',
    imageCoverage: '0 / 2 项目暂不使用不稳定外链图像',
    note: '精选项目档案，尚非作品全集。Mukherjee 不是把 fibre 当“soft sculpture 的替代材料”，而是从 New Delhi 市场购买、挑选、分类沉重 rope bundles，再用 hand-knotting/macramé 把 rope 生长成近植物、性器官、神像与抽象体之间的 monument。',
    projects: [
      {
        title: 'Early natural-rope wall hangings',
        cluster: 'natural fibre / macramé / botanical abstraction',
        period: 'early 1970s',
        summary: '早期作品以 natural rope 制作 botanic-inspired wall hangings。Mukherjee 采用古老 macramé hand-knotting 技术，但不遵循传统 textile pattern，而是让 knot density、rope weight 与悬挂方式直接生成有机形体。',
        actions: [
          '从 New Delhi markets 采购 heavy rope bundles 并自行挑选 / 分类',
          '以 hand-knotting/macramé 而非 loom weaving 作为主要 construction method',
          '通过 knot repetition 调节 thickness、fold、bulge 与 hanging tension',
          '从 botanical form 出发但保持 abstraction，不制作植物写实复制品',
          '让作品可悬挂、贴墙或 later become freestanding，使 fibre 从 textile surface 转向 sculpture',
        ],
        sourceUrl: mukherjeeVenice,
        images: [],
        relations: [],
      },
      {
        title: 'Rudra / Devi / Vanshree',
        cluster: 'monumental fibre deity / sensual organic body',
        period: '1982–1994',
        summary: 'Rudra、Devi 与 Vanshree 把 rope sculpture 推到接近 deity-scale 的 monumental body。vegetal orange/yellow/purple、folds、bulges 与垂坠结构同时让作品像植物、神像与 sexual organ，形成 abstraction / figuration 之间的高张力。',
        actions: [
          '继续以 hand-knotted rope 为主体，但显著扩大 vertical scale',
          '通过 fold、bulge、loop 与 hanging weight 塑造 near-anthropomorphic body',
          '使用 vegetal oranges、yellows、purples 等色调强化 organic / botanical association',
          '让 sculpture 可悬挂、freestanding 或靠墙，按 exhibition architecture 改变身体姿态',
          '把 ancient Indian sculpture、local craft、modern design 与 erotic body language 融入同一 material form',
        ],
        sourceUrl: mukherjeeVenice,
        images: [],
        relations: [rel('展览', 'The Milk of Dreams — Venice Biennale', '2022 · Central Pavilion historical presentation')],
      },
    ],
    awards: [],
    exhibitions: ['The Milk of Dreams — Venice Biennale 2022'],
    sources: [{ label: 'La Biennale · Mrinalini Mukherjee 2022', url: mukherjeeVenice }],
  },

  'venice-simone-fattal': {
    artistId: 'venice-simone-fattal',
    projectCoverage: '2 个 archaeological-figure / minimal-body 节点已建立深档案 · 1988–2022',
    imageCoverage: '0 / 2 项目暂不使用不稳定外链图像',
    note: '精选项目档案，尚非作品全集。Fattal 的 ceramic / bronze figures 看起来像刚从 archaeological site 被挖出，但她用极少形体信息建立人物：两根柱状腿、一个 clay connector、轻微倾斜就足以成为 body / gesture。作品同时寻找并拒绝“人的本质形态”。',
    projects: [
      {
        title: 'Archaeological figures',
        cluster: 'ceramic / reduced human form / excavated-object fiction',
        period: '1988–ongoing',
        summary: '1988 返回艺术实践后，Fattal 长期制作看似古代出土物的 ceramic figures。人物被缩减到最少细节：wide columns 成为腿，一块 clay 连接成为 torso / head，轻微倾斜就是动作。',
        actions: [
          '以 hand-modelled ceramic 建立粗粝、非精修的人形 surface',
          '主动减少 facial / anatomical detail，避免 portrait specificity',
          '用 column-like legs、connector torso/head 和 slight lean 构成最小 human grammar',
          '保留 clay 的 handmade irregularity，使物件像 archaeological fragment 而非 polished figurine',
          '通过近 archetype 的 figure 处理 human spirit 与 material form 之间的矛盾',
        ],
        sourceUrl: fattalVenice,
        images: [],
        relations: [],
      },
      {
        title: 'Adam and Eve + Venice 2022 sculpture garden installation',
        cluster: 'bronze cast / ceramic + bronze / Scarpa garden',
        period: '2021–2022',
        summary: 'Venice 2022 中，Fattal 在 Carlo Scarpa 设计的 Central Pavilion sculpture garden 安装 Adam and Eve（2021，早期 ceramic sculpture 的 bronze cast）以及三件新作，其中两件 ceramic、一件 bronze。作品把 abstract motif 与 human form 放进真实 garden / architecture 中。',
        actions: [
          '将一件 earlier ceramic form 转译为 bronze cast，比较 clay / bronze 的时间感与重量',
          '为 Venice 新制作两件 ceramic 与一件 bronze，而非只调用旧作',
          '把 minimal human / abstract motif 维持在同一 sculptural vocabulary',
          '依据 Carlo Scarpa sculpture garden 的 outdoor architecture 布置作品间距与视线',
          '让 apparent archaeological objects 与 modernist garden architecture 形成跨时代并置',
        ],
        sourceUrl: fattalVenice,
        images: [],
        relations: [rel('展览', 'The Milk of Dreams — Venice Biennale', '2022 · Central Pavilion sculpture garden')],
      },
    ],
    awards: [],
    exhibitions: ['The Milk of Dreams — Venice Biennale 2022'],
    sources: [{ label: 'La Biennale · Simone Fattal 2022', url: fattalVenice }],
  },

  'venice-charlotte-johannesson': {
    artistId: 'venice-charlotte-johannesson',
    projectCoverage: '3 个 counterculture weaving / loom-to-code / cyber-map 节点已建立深档案 · 1960s–2019',
    imageCoverage: '0 / 3 项目暂不使用不稳定外链图像',
    note: '精选项目档案，尚非作品全集。Johannesson 的关键不是从 textile“转行”computer art，而是发现 loom 的 vertical / horizontal grid 与 pixel / program language 本来就可以互译；counterculture weaving 与 early personal computing 因此属于同一套政治图像实践。',
    projects: [
      {
        title: 'Cannabis studio / socio-political tapestries',
        cluster: 'hemp fibre / weaving / counterculture image',
        period: '1960s–1970s',
        summary: '在 Malmö 建立 Cannabis studio 后，Johannesson 使用 hemp-derived fibre 与 textile craft 处理社会政治不公。studio 名称同时指向 hemp material 与 1960s counterculture，使 craft practice 从一开始就带有明确政治语境。',
        actions: [
          '接受 formal weaving training 后保留 loom / textile craft 作为主要图像技术',
          '以 hemp / fibre 作为 material basis，并以 Cannabis 为 studio identity',
          '将 slogan / political image / counterculture reference 编入 textile surface',
          '把 craft labour 当成 contemporary political image production，而不是 decorative domestic work',
          '建立 grid-based visual thinking，为后来的 computer translation 准备结构',
        ],
        sourceUrl: johannessonVenice,
        images: [],
        relations: [],
      },
      {
        title: 'Computer Mind',
        cluster: 'Apple II / plotter / loom-code translation',
        period: '1981–1986',
        summary: '1978 Johannesson 用 tapestry 换得 Apple II，随后把 loom 的经纬线逻辑转译到 early computer programming。Computer Mind 画出人物 nervous system 与 computer 相连，是她对 micro-computer 作为新身体/新织机的直接图像化。',
        actions: [
          '用一件 tapestry 交换 Apple II，实际进入 early personal-computer production',
          '把 loom vertical / horizontal grid 理解为可转译成 pixel / programming coordinate 的结构',
          '使用 computer 与 plotter 生成图像，而不是仅以计算机为绘画题材',
          '在 Computer Mind 中把 nervous system 与 machine connection 画成同一 network',
          '让 craft knowledge 直接进入 code-based image making，不把 digital / handmade 二分',
        ],
        sourceUrl: johannessonVenice,
        images: [],
        relations: [rel('展览', 'The Milk of Dreams — Venice Biennale', '2022 · Central Pavilion')],
      },
      {
        title: 'Take Me To Another World / The Target Is Destroyed',
        cluster: 'world map / space image / slogan + digital textile logic',
        period: '1981–1986；2019 reactivations',
        summary: '这组作品把 world maps、Earth-from-space imagery 与 popular-culture slogans 合并，使早期 computer utopianism、Cold War image 和 counterculture desire 在同一 grid 中并存。2019 的再制作/延伸说明她把早期 digital language 当成可持续更新的 archive。',
        actions: [
          '调用 world map / Earth-from-space imagery 作为可被 grid 化的 global icon',
          '加入 popular-culture slogans，使 technological image 与 desire / propaganda language 发生摩擦',
          '延续 early computer graphic 的 hard-edged pixel / plotter logic',
          '在 2019 重新制作或延伸早期 compositions，让 historical digital aesthetics 回到 contemporary display',
          '持续在 weaving / print / digital image 之间交换同一 visual code',
        ],
        sourceUrl: johannessonVenice,
        images: [],
        relations: [rel('展览', 'The Milk of Dreams — Venice Biennale', '2022 · Central Pavilion')],
      },
    ],
    awards: [],
    exhibitions: ['The Milk of Dreams — Venice Biennale 2022'],
    sources: [{ label: 'La Biennale · Charlotte Johannesson 2022', url: johannessonVenice }],
  },
};
