import type { ArtistArchive, ArchiveProject, ArchiveRelation } from './archiveData';
const rel=(kind:ArchiveRelation['kind'],label:string,detail?:string):ArchiveRelation=>({kind,label,detail});
const project=(p:ArchiveProject)=>p;

export const archiveBatch305:Record<string,ArtistArchive>={
  'trevor-paglen':{
    artistId:'trevor-paglen',
    projectCoverage:'作品级深化第二批：Autonomy Cube、Orbital Reflector、Behold these Glorious Times!、They Took the Faces from the Accused and the Dead…。重点补实际硬件/网络功能、航天工程、训练数据处理、输出尺寸、声音与展陈机制。',
    imageCoverage:'艺术家官网、SFMOMA、Nevada Museum of Art、Carnegie Museum of Art 与 Thoma Foundation 均提供对应作品/安装图；作品图明确涉及 © Trevor Paglen 或机构摄影版权。本批保存官方图像入口、credit 与限制，未确认可再发布的图片不复制入仓库并明确暂缺。',
    note:'本批把 Paglen 的“监控/AI/基础设施”进一步拆成四种真实生产机制：能被观众实际连接的 Tor 网络雕塑；真正发射进入轨道但未成功展开的航天器；把训练数据与神经网络内部表征剪辑成录像；以及把早期人脸识别训练库中的囚犯/被告照片重新打印为墙面摄影。',
    projects:[
      project({title:'Autonomy Cube',cluster:'network sculpture / Tor relay / functional hardware',period:'2014–2018',summary:'Autonomy Cube 不是把“匿名网络”象征性做成雕塑，而是一台在展览期间实际工作的网络设备。透明 Plexiglas/Lucite 立方体内部安装两块功能主板与无线网络服务器；接入互联网后，它在博物馆或画廊现场广播名为 Autonomy Cube 的开放 Wi‑Fi。观众可以用自己的手机或电脑连接，流量随后经 Tor 网络转发。作品本身同时加入 Tor relay 网络，为世界其他位置的 Tor 用户转发匿名流量。因此机构一旦展出它，就不只是陈列一件关于监控的对象，而是在自己的建筑与网络基础设施中运行一个匿名通信节点。SFMOMA 馆藏将其登记为 installation，媒介为 Plexiglas cube with two functional motherboards, W-lan server，立方体尺寸 13 1/2 × 13 1/2 in (34.3 × 34.3 cm)，并另有 custom pedestal 与 power brick 组件。',actions:['制作透明 Plexiglas/Lucite 立方体，使内部网络硬件保持可见。','在内部安装两块功能主板与无线服务器，并要求展览现场提供互联网和电力。','建立开放 Wi‑Fi hotspot，让观众用自己的设备实际加入网络。','把所有访问流量路由进 Tor，而不是提供普通公共 Wi‑Fi。','让雕塑同时作为 Tor relay 工作，使展览机构成为全球匿名通信基础设施中的一个真实节点。'],sourceUrl:'https://www.sfmoma.org/artwork/2016.73.A-C/',images:[],relations:[rel('收藏','SFMOMA — Autonomy Cube — 2014','Installation；Plexiglas cube with two functional motherboards, W-lan server；34.3 × 34.3 cm；2016 acquired。'),rel('技术','Trevor Paglen Studio — Autonomy Cube','艺术家说明作品既供现场观众使用，也会 relay Tor traffic；安装因此依赖真实联网。'),rel('版权','SFMOMA artwork image','© Trevor Paglen；本站仅记录官方图片入口，不复制受限图。')]}),
      project({title:'Orbital Reflector',cluster:'space sculpture / CubeSat / inflatable polyethylene reflector',period:'2016–2019',summary:'Orbital Reflector 把 Paglen 对不可见基础设施的研究推进到真实航天工程。作品与 Nevada Museum of Art 及航天工程公司 Global Western 合作：一件轻质、高反射的聚乙烯充气雕塑折叠收纳在小型 CubeSat 中，计划由 SpaceX Falcon 9 搭载进入约350英里高的低地球轨道。进入轨道后，CubeSat 原计划打开并释放结构，雕塑自充气形成细长菱形反射体；Nevada Museum 的项目说明记录其内侧覆 titanium dioxide reflective powder，艺术家官网则描述最终设计约100米长，目标是把太阳光反射回地面，使肉眼看到一颗缓慢移动、亮度接近北斗七星成员的“人工星”。它不是航天功能卫星：无通信、观测或商业任务，工程目的本身就是让一个非功能性艺术对象短暂成为天空中的可见事件。2018发射成功，但2018–19美国政府停摆使部署许可/通信流程中断，反射结构最终没有展开；作品因此留下实际进入轨道的 CubeSat、地面原型、技术图、生产文件和完整项目档案，而预定的天空观看方式没有实现。',actions:['与博物馆和航天工程团队把雕塑设计成可折叠进入 CubeSat 的轻质反射结构。','在聚乙烯结构内部加入高反射材料，使展开后能够把太阳光反射到地面。','安排 Spaceflight Industries / SpaceX Falcon 9 的真实发射，而不是用CG模拟卫星进入太空。','设计在轨释放与自充气流程，使雕塑原计划展开成约100米长的菱形反射体。','把原型、技术图、制造与发射文档保存在 Nevada Museum Center for Art + Environment；同时记录因政府停摆导致未成功展开这一作品历史。'],sourceUrl:'https://www.nevadaart.org/art/exhibitions/trevor-paglen-orbital-reflector/',images:[],relations:[rel('机构','Nevada Museum of Art — Orbital Reflector','博物馆为联合制作方；项目档案进入 Center for Art + Environment。'),rel('工程','Global Western / Spaceflight Industries / SpaceX','Global Western 参与设计制造；Spaceflight Industries 安排 Falcon 9 发射。'),rel('版本','Ground prototype / orbital object','展厅曾展示 prototype；真正发射的 CubeSat 已入轨，但 inflatable reflector 未成功部署。'),rel('版权','Nevada Museum official images','设计渲染 courtesy Trevor Paglen and Nevada Museum of Art；原型图 courtesy Nevada Museum；未确认自由再发布。')]}),
      project({title:'Behold these Glorious Times!',cluster:'AI training images / neural-network visualization / single-channel projection / algorithmic sound',period:'2017',summary:'这件录像把两类机器视觉材料高速剪辑在一起。第一类来自用于训练人工智能识别人脸、物体、动作、关系和情绪的图像库；第二类不是普通照片，而是深度神经网络摄入这些训练图像后形成的内部特征/激活表征。Paglen 将训练样本与黑白网格、碎裂结构等网络内部视觉化结果并置，让人类观众同时看到“机器被喂了什么”和“机器如何拆解图像”。艺术家官网登记为 single-channel color video projection，约10分钟；Thoma Foundation 馆藏记录为 digital video with sound，投影尺寸约108 1/2 × 121 1/2 in。声音由 Holly Herndon 制作，并部分使用神经网络、语音识别训练库以及用于合成声音/乐器的机器学习方法，使听觉层也对应视觉层的训练机制。',actions:['从真实机器学习训练库提取用于教算法识别人、物、动作、情绪等类别的图像。','取得/生成深度神经网络处理同类图像时的内部表征，把特征拆解结果转成可观看画面。','把训练样本与网络内部视觉化结果高速剪辑为单频道数字录像，而不是展示静态数据库截图。','邀请 Holly Herndon 制作声音；声音同样使用语音识别训练材料与神经网络合成方法。','以大尺度单频道投影循环播放，使观众身体面对机器训练图像的高速流。'],sourceUrl:'https://paglen.studio/2020/04/09/behold-these-glorious-times/',images:[],relations:[rel('收藏','Thoma Foundation — Behold these Glorious Times!','2017；Digital video with sound；10 min loop；108 1/2 × 121 1/2 in projection dimensions。'),rel('声音','Holly Herndon','音乐部分使用 neural networks 与 speech-recognition / auditory machine-learning training libraries。'),rel('展览','Metro Pictures, New York — 2017','艺术家官网保存单频道投影安装图。'),rel('版权','Official stills / installation views','作品图 © Trevor Paglen；Thoma Foundation/Metro Pictures 提供图源，未确认自由再发布。')]}),
      project({title:'They Took the Faces from the Accused and the Dead…',cluster:'facial-recognition dataset / pigment prints / installation',period:'2019',summary:'Paglen 从早期人脸识别技术的训练史出发，重新处理曾被算法研发机构作为测试/训练材料使用的 mugshots。艺术家指出，在社交媒体提供海量人脸之前，研究者需要大型标准化面孔集合，美国 National Institute of Standards 体系曾向相关研究提供被告、囚犯等来源的人脸照片。Paglen 没有把这些图像继续留在数据库中，而是将它们重新输出为实体 pigment prints，使原本作为计算机视觉“原料”的脸重新进入美术馆观看关系。2019 Pace Geneva 的 The Shape of Clouds 版本包含一组14张 pigment prints，每张约11 1/2 × 13 1/2 in；艺术家同时制作更大的单幅版本，例如 #00520_1_F 为50 × 42 in。2020 de Young Museum 的 Uncanny Valley 又将训练图像组织成大型墙面作品，空间尺度和密度因此发生变化。',actions:['追踪早期 facial-recognition 研究使用的人脸数据库及其 mugshot 来源。','从原本用于算法训练/benchmark 的图像集合中重新选择具体面孔。','把低层级数据库图像重新制作成 pigment print，使其从机器输入转成需要被人观看的实体摄影。','在 Pace Geneva 以14张小幅组照形成序列，同时制作50 × 42 in等大型单幅输出。','在 de Young Museum 版本中扩大为墙面训练图像集合，使观看从逐张肖像转成面对数据集规模。'],sourceUrl:'https://paglen.studio/2020/04/09/they-took-the-faces-from-the-accused-and-the-dead/',images:[],relations:[rel('展览','The Shape of Clouds — Pace Gallery Geneva — 2019','Set of 14 pigment prints；each 11 1/2 × 13 1/2 in。'),rel('具体作品','#00520_1_F — 2019','Pigment print；50 × 42 in；艺术家官网提供作品图。'),rel('展览','Uncanny Valley: Being Human in the Age of AI — de Young Museum — 2020','大型墙面 training-image 版本；installation photography by Randy Dodson。'),rel('版权','Carnegie / Pace / artist studio images','相关作品图标注 © Trevor Paglen；仅记录官方来源与摄影 credit。')]})
    ],
    awards:[],
    exhibitions:['The Shape of Clouds — Pace Gallery Geneva — 2019','Uncanny Valley: Being Human in the Age of AI — de Young Museum — 2020','Trevor Paglen: Orbital Reflector — Nevada Museum of Art'],
    sources:[
      {label:'Trevor Paglen Studio — Autonomy Cube',url:'https://paglen.studio/2020/04/09/autonomy-cube/'},
      {label:'SFMOMA — Autonomy Cube',url:'https://www.sfmoma.org/artwork/2016.73.A-C/'},
      {label:'Nevada Museum of Art — Orbital Reflector',url:'https://www.nevadaart.org/art/exhibitions/trevor-paglen-orbital-reflector/'},
      {label:'Trevor Paglen Studio — Orbital Reflector',url:'https://paglen.studio/2020/04/09/orbital-reflector/'},
      {label:'Trevor Paglen Studio — Behold these Glorious Times!',url:'https://paglen.studio/2020/04/09/behold-these-glorious-times/'},
      {label:'Thoma Foundation — Behold these Glorious Times!',url:'https://thomafoundation.org/artwork/behold-these-glorious-times/'},
      {label:'Trevor Paglen Studio — They Took the Faces...',url:'https://paglen.studio/2020/04/09/they-took-the-faces-from-the-accused-and-the-dead/'},
      {label:'Carnegie Museum of Art — Trevor Paglen: Opposing Geometries',url:'https://carnegieart.org/exhibition/trevor-paglen/'}
    ]
  }
};
