import type { ArtistArchive, ArchiveRelation } from './archiveData';

const rel=(kind:ArchiveRelation['kind'],label:string,detail?:string):ArchiveRelation=>({kind,label,detail});

export const archiveBatch263:Record<string,ArtistArchive>={
  'trevor-paglen':{
    artistId:'trevor-paglen',
    projectCoverage:'作品级深化：从机器视觉的抽象讨论下钻到 From Apple to Anomaly、ImageNet Roulette 与 Sight Machine 三个具体生产系统，记录数据集来源、分类/训练动作、软件、实体打印劳动、实时摄像与投影如何真正构成作品。',
    imageCoverage:'Barbican 官方展览页与艺术家访谈保存 From Apple to Anomaly 安装图（部分传播图 credit: Tim P. Whitby / Getty Images），Sight Machine 页面提供现场/说明图。相关图像未确认开放本地再发布许可，因此本批保存官方图像入口与 credit，不复制受限图片；图片字段明确保持暂缺。',
    note:'这一批重点把 Paglen 的 AI 项目从“批判算法偏见”落实到实际工作流程：他不仅谈论 ImageNet，而是读取其分类体系、抽取并打印训练图像、训练特定神经网络、制作可供公众上传照片的应用，并在现场把计算机视觉算法接到摄像机和实时投影系统。',
    projects:[
      {title:"From 'Apple' to 'Anomaly' — The Curve installation",cluster:'machine vision / dataset archaeology / site-specific installation',period:'2019–20',summary:'Barbican 为 The Curve 委托的场域特定装置以 ImageNet 为主要材料。Paglen 从这个超过1400万张图像、约2万分类的训练数据库出发，沿着弧形展厅组织约3万张单独打印的训练图像。作品不是把数据库投影到墙上：图像被真正打印、逐张钉墙，分类从较稳定的物体词汇逐渐进入对人的判断性标签，使观众以步行方式穿过机器分类世界。Paglen 在 Barbican 访谈中特别指出，安装约35000张图像时由10人连续工作约2.5周；这种人工打印和钉挂劳动有意对应训练集背后通常不可见的 click-work / Mechanical Turk 标注劳动。',actions:['读取并研究 ImageNet 的 taxonomy，尤其追踪约2800个人物相关类别及其中带有阶级、性别、种族和道德判断的标签。','从训练集抽取大量具体图像，转成可在展厅观看的独立实体打印件。','由团队逐张打印并钉装到 The Curve 墙面；Paglen称约35000张的安装劳动由10人持续约2.5周完成。','利用 Barbican 弧形空间把 taxonomy 转换成观众必须沿墙行走才能阅读的线性/空间序列。','以 Magritte 的苹果图像和 The Treachery of Object Recognition 等节点追问“谁有权决定图像是什么意思”，让人类表述与机器分类直接冲突。'],sourceUrl:'https://www.barbican.org.uk/whats-on/2019/event/trevor-paglen-from-apple-to-anomaly',images:[],relations:[rel('展览','Barbican, The Curve','26 Sep 2019–16 Feb 2020；Barbican commission；官方页保存3张 installation views。'),rel('材料','约30,000–35,000张 individually printed images','主要来自 ImageNet；艺术家访谈描述安装阶段约35,000张。'),rel('制作','10人 / 约2.5周','逐张打印、逐张钉墙；用可见体力劳动映射训练数据背后的隐形标注劳动。'),rel('图片版权','Barbican installation imagery','官方传播图可见 credit: Tim P. Whitby / Getty Images；未确认开放再发布许可，本地图片暂缺。')]},
      {title:'ImageNet Roulette',cluster:'machine learning / public web application / dataset intervention',period:'2019',summary:'ImageNet Roulette 把数据集批判变成公众可直接触发的分类机器。Paglen 从 ImageNet 的人物类别中取出训练数据，训练一个只针对这些人物分类的神经网络，再制作上传照片即可运行分类的应用。参与者把自拍或人物照片送入系统后，会收到诸如职业、性格乃至侮辱性社会类型的标签。Paglen 并不把错误结果包装成准确 AI；项目页面明确警告系统会持续产生种族主义、厌女和冒犯性输出，目的正是让训练集内置的分类暴力以第一人称方式返回给使用者。项目在网络传播后曾达到约120万张图像/日的处理规模，随后 ImageNet 创建者宣布删除大量人物类别并开展去偏工作。',actions:['从 ImageNet 中分离人物类别及其对应训练图像。','以这些类别训练专门的 neural network / classifier。','制作公众可上传自身图像的应用界面，让模型即时返回分类标签。','保留系统令人不适的判断结果，并以明确警告把错误/偏见本身作为作品内容，而不是修饰成可靠识别。','通过大规模公众使用把后台 taxonomy 转换成用户亲身遭遇的分类事件。'],sourceUrl:'https://www.barbican.org.uk/s/trevorpaglen',images:[],relations:[rel('数据集','ImageNet','人物类别被用于训练 ImageNet Roulette 的模型。'),rel('参与','public upload → machine classification','观众/网络用户上传图像，系统返回训练类别中的人物标签。'),rel('传播','约1.2 million images/day','Paglen 在 Barbican 对谈中描述项目病毒式传播阶段的处理量。'),rel('后续','ImageNet people categories','Paglen称项目传播后 ImageNet 团队宣布删除大量人物类别并展开更大范围去偏工作。')]},
      {title:'Sight Machine — Kronos Quartet live version',cluster:'real-time computer vision / performance / projection',period:'2019',summary:'Sight Machine 把“机器如何看”从静态训练集转成实时表演基础设施。Kronos Quartet 演奏时，现场摄像机持续拍摄四位演奏者；画面进入运行多种 computer-vision algorithms 的软件系统，包括与 object detection、自驾车和 guided-missile vision 相关的识别/分析方式。算法不是只在后台给出数字结果，而把边缘、物体框、追踪或其他机器视觉中间表征转换成抽象动态图像，并实时投影到乐手背后的屏幕。观众因此同时看到人类演奏、摄像机采样、算法变换和机器版本的“同一现场”。',actions:['在现场架设摄像机持续捕获 Kronos Quartet 的演奏。','把实时视频流送入不同 computer-vision algorithms，而不是预先剪好视觉素材。','截取/可视化通常只供机器读取的分析结果，将其转成可被人观看的动态图像。','把处理结果实时投影在乐团背后，使算法延迟、误认和抽象化与音乐表演同时发生。','通过音乐这种难以被简单量化的交流形式，对照机器视觉把复杂现场压缩成可操作数据的机制。'],sourceUrl:'https://www.barbican.org.uk/kronos-quartet-trevor-paglen-sight-machine',images:[],relations:[rel('合作','Kronos Quartet','现场弦乐表演成为实时机器视觉输入。'),rel('技术','cameras + computer-vision software + real-time projection','Barbican明确描述摄像机监控演奏，并由 object detection / autonomous vehicle / guided-missile 等相关算法实时处理。'),rel('观看','human performance ↔ machine-readable image','观众同时面对身体演奏和算法生成的机器视图。'),rel('图片','Barbican official event imagery','官方页面提供现场/项目图；未确认开放再发布许可，本地图片暂缺。')]}
    ],
    exhibitions:["Trevor Paglen: From 'Apple' to 'Anomaly' — Barbican, The Curve, 2019–20",'Sight Machine — Kronos Quartet / Trevor Paglen, Barbican'],
    sources:[{label:"Barbican · From 'Apple' to 'Anomaly'",url:'https://www.barbican.org.uk/whats-on/2019/event/trevor-paglen-from-apple-to-anomaly'},{label:'Barbican · Paglen on From Apple to Anomaly',url:'https://www.barbican.org.uk/s/trevorpaglen'},{label:'Barbican · Sight Machine',url:'https://www.barbican.org.uk/kronos-quartet-trevor-paglen-sight-machine'}]
  }
};
