import type { ArtistArchive, ArchiveRelation } from './archiveData';
const rel=(kind:ArchiveRelation['kind'],label:string,detail?:string):ArchiveRelation=>({kind,label,detail});

const roster='https://www.labiennale.org/en/art/2017/artists';
const korina='https://irinakorina.com/works/';
const korinaGarage='https://garagemca.org/en/news/2017-04-29-garage-supports-irina-korina-s-project-at-the-57th-international-art-exhibition-la-biennale-di-venezia';
const kwadeWelten='https://alicjakwade.com/exhibitions/viva-arte-vica-curated-by-christine-macel';
const kwadePars='https://alicjakwade.com/works/pars_pro_toto_maersk';
const laiSothebys='https://www.sothebys.com/en/auctions/ecatalogue/2020/contemporary-art-evening-sale-hk0927/lot.1103.html';
const laiBiennale='https://www.labiennale.org/en/biennale-channel/biennale-arte-2017-firenze-lai';
const mariaTreccani='https://www.treccani.it/enciclopedia/maria-lai/';
const mariaLegarsi='https://cultura.gov.it/evento/maria-lai-che-lego-ulassai-alla-montagna';
const textileForum='https://www.textile-forum-blog.org/2017/06/biennale-arte-2017-in-venice/';
const lanceta='https://www.teresalanceta.com/en/writings/other-writings/dont-buy-the-hours_218';
const lancetaPub='https://www.teresalanceta.com/biografia/publicaciones/adios-al-rombo_116';

export const archiveBatch131:Record<string,ArtistArchive>={
'venice-2017-irina-korina':{artistId:'venice-2017-irina-korina',projectCoverage:'1 个 state-memory / kitsch-architecture immersive installation 已建立深档案 · 2017',imageCoverage:'0 / 1 项目暂不使用不稳定外链图像',note:'当前集中覆盖 Venice 2017 的 Good Intentions，尚非 Korina 全部 installation oeuvre。作品由 Garage Museum 支持制作；重点是把官方纪念、军国象征、人工花环与廉价建筑表面压缩成需要身体进入的两层环境。',projects:[{title:'Good Intentions',cluster:'corrugated metal / false-brick architecture / neon insignia / artificial funeral wreath',period:'2017',summary:'为 Arsenale 制作的 site-specific installation 以两层 corrugated-metal / temporary-architecture logic 构成压缩空间；假砖柱、霓虹/LED 符号、人工花环与官方纪念美学共同制造介于 shrine、stage set 与国家宣传残片之间的环境。',actions:['先依据 Arsenale 尺度设计 two-storey enclosure，而不是把独立雕塑放入场地','使用 corrugated metal 等廉价施工材料搭建外壳','加入仿砖/柱等表面语言，使临时结构与 Arsenale 历史建筑发生错位模仿','设置 steel staircase / vertical passage，迫使 viewer 通过攀爬和转身进入内部','使用 neon / LED-like insignia 与 artificial floral wreaths 调用官方纪念和军国视觉语言','保留材料的 theatrical / stage-set 人工感，不追求真实 monument finish','项目在 Moscow 制作支持体系下完成后运输至 Venice 并现场组装','通过狭窄 interior、视线遮挡和高度变化，让政治 kitsch 不只是被“看”，而成为身体环境'],sourceUrl:korinaGarage,images:[],relations:[rel('展览','Viva Arte Viva — Venice Biennale 2017','Arsenale · main exhibition'),rel('策展','Garage Museum of Contemporary Art production support','Good Intentions, 2017')]}],awards:[],exhibitions:['Viva Arte Viva — Venice Biennale 2017'],sources:[{label:'Irina Korina · Works',url:korina},{label:'Garage Museum · Good Intentions',url:korinaGarage},{label:'La Biennale · Artists 2017',url:roster}]},

'venice-2017-alicja-kwade':{artistId:'venice-2017-alicja-kwade',projectCoverage:'2 个 mirror-perception / planetary-stone 节点已建立深档案 · 2017',imageCoverage:'0 / 2 项目暂不使用不稳定外链图像',note:'Kwade 2017 两件作品互补：WeltenLinie 用镜面把 architecture / object 的真假关系打乱；Pars pro Toto 则把不同地质来源的石头全部加工为同一种球体，让“世界的部分”看起来像多个小行星。',projects:[{title:'WeltenLinie',cluster:'powder-coated steel / mirror / doubled object / walk-through labyrinth',period:'2017',summary:'约 6 m 高、15.4 m 长的 steel-and-mirror structure 将 stone、bronze、aluminium、wood、petrified wood、rusted iron 分布在真实与反射空间中。镜面让线框似乎继续延伸，objects 也不断出现真假双胞胎。',actions:['以 powder-coated steel 建立大尺度 rectilinear framework','把 mirror panels 嵌入线框，使 architecture 在反射中形成虚假延伸','在结构两侧布置 stone、bronze、aluminium、wood、petrified wood、rusted iron 等不同物性 objects','精确利用 mirror line 让某些 object 看似 duplicated / replaced','让 viewer 必须穿过/绕行 structure，以身体位置不断更新真假判断','不隐藏镜面边缘和物质差异，使 illusion 与 construction 同时可见'],sourceUrl:kwadeWelten,images:[],relations:[rel('展览','Viva Arte Viva — Venice Biennale 2017','WeltenLinie, 2017')]},{title:'Pars pro Toto',cluster:'13 natural-stone spheres / geology / planet-model / scale shift',period:'2017',summary:'13 个 natural-stone spheres 以同一几何形式呈现不同地质材料；“part for the whole”让一块地球岩石既是具体矿物，也可被读成整颗 planet / celestial body 的缩影。',actions:['选择不同来源/性质的 natural stones，保留各自纹理与颜色','将不规则原石加工为统一 spherical geometry','保持 spheres 尺寸/石种差异，使“同形”不抹平 material specificity','在 exhibition landscape 中分散布置，而不是全部放上 pedestal','利用 human body 与 sphere 的尺度关系制造 boulder / planet 双重读取','把 geology 的巨大时间压缩进人工完成的标准几何体'],sourceUrl:kwadePars,images:[],relations:[rel('展览','Viva Arte Viva — Venice Biennale 2017','Pars pro Toto · 13 natural stone spheres')]}],awards:[],exhibitions:['Viva Arte Viva — Venice Biennale 2017'],sources:[{label:'Alicja Kwade · Viva Arte Viva / WeltenLinie',url:kwadeWelten},{label:'Alicja Kwade · Pars pro Toto',url:kwadePars},{label:'La Biennale · Artists 2017',url:roster}]},

'venice-2017-firenze-lai':{artistId:'venice-2017-firenze-lai',projectCoverage:'2 个 urban-body / anonymous-figuration painting 节点已建立深档案 · 2013–2017',imageCoverage:'0 / 2 项目暂不使用不稳定外链图像',note:'Lai 明确说自己画的是 figurative work 而非 portraits；人物匿名、身体扭曲，经常源于 Hong Kong 中人与城市空间的细微摩擦。当前覆盖 Venice 展出的 Happily Ever After 与同期 The Hollow Passage 方法节点。',projects:[{title:'Happily Ever After',cluster:'oil on canvas / anonymous figure / psychological compression',period:'2013; exhibited 2017',summary:'100.3 × 80 cm oil on canvas。匿名人物被拉长、折叠、挤压成不自然姿势；不是特定人物肖像，而是将 social unease、dislocation 与身体感觉压成近梦境的 figurative image。',actions:['以 oil on canvas 建立 compact single-figure / interpersonal field','取消明确 portrait identity，让人物成为情绪和身体关系的载体','主动夸张 head、limb、torso 比例，拒绝自然主义 anatomy','使用不稳定 pose 表现身体似乎无法舒服占据空间','用色彩与空白环境削弱具体地点，让心理状态比事件叙事更突出','保留 painterly simplicity，使怪异感来自比例/姿态而非复杂象征'],sourceUrl:laiSothebys,images:[],relations:[rel('展览','Viva Arte Viva — Venice Biennale 2017','Central Pavilion')]},{title:'The Hollow Passage',cluster:'oil on canvas / MTR observation / curved architecture / constrained body',period:'2017',summary:'作品由 Hong Kong Causeway Bay MTR platform 的 curved wall 触发：城市建筑细节会在不被意识到的情况下限制站姿、距离与群体行为；Lai 将这种微小 spatial pressure 转成扭曲的人体。',actions:['长期观察 MTR / street / interior 中 people 如何被 architecture 迫使改变 posture','从 Causeway Bay platform curved wall 读取身体与墙面之间的空间压迫','不直接画 architectural diagram，而把 constraint 转译为 figure deformation','以 oil painting 保留日常观察与心理投射之间的模糊地带','通过人物在画面中不自然地靠近/弯曲，表现 city design 对身体的隐性塑形','让 everyday title / scene 保持普通，使结构性不适从细节慢慢浮现'],sourceUrl:laiBiennale,images:[],relations:[rel('展览','Viva Arte Viva — Venice Biennale 2017','Firenze Lai participation')]}],awards:[],exhibitions:['Viva Arte Viva — Venice Biennale 2017'],sources:[{label:'Sotheby’s · Happily Ever After',url:laiSothebys},{label:'La Biennale · Firenze Lai 2017',url:laiBiennale}]},

'venice-2017-maria-lai':{artistId:'venice-2017-maria-lai',projectCoverage:'3 个 stitched-book / bread-book / community-ribbon 历史节点已建立深档案 · 1981–2008; Venice 2017',imageCoverage:'0 / 3 项目暂不使用不稳定外链图像',note:'Maria Lai 2017 为 posthumous inclusion。这里不把“织物”概括成风格，而分别记录 thread-as-writing、bread-as-book 与 community ribbon 三种生产逻辑。',projects:[{title:'Libri cuciti / sewn books',cluster:'cloth page / pierced textile / thread-as-writing / unreadable book',period:'1970s–2000s; c.1996 example shown 2017',summary:'布页被线反复穿刺、缝合，threads 形成类似文字却无法按通常语言解读的 dense traces；Treccani 强调厚钢针有时也保留在作品上，使 sewing labour 与“书写”不可分。',actions:['切割/折叠 cloth or fabric-like pages 建立 book structure','以 needle 穿刺页面，让 holes 成为 writing 的物理前提','用 thread 在 page surface 形成连续、纠缠、类似文字的线性痕迹','不把线整理成可读 alphabet，保持 language / image 之间的不确定','在部分作品保留 needle / loose thread，使制作动作没有被最终装帧完全抹去','将 traditionally feminised sewing labour 直接转成 knowledge / book-making method'],sourceUrl:mariaTreccani,images:[],relations:[rel('展览','Viva Arte Viva — Venice Biennale 2017','Libro cucito, c.1996, posthumous presentation')]},{title:'Enciclopedia Pane',cluster:'17 bread books / bread + paper / edible knowledge-object',period:'2008; shown 2017',summary:'由 17 个 bread books 构成的“百科全书”，把面包这种日常、会老化的食物与纸、书、知识权威相接；知识对象因此不再永久，而会干燥、脆裂、衰变。',actions:['将 bread 直接塑造成 book-like units，而不是制作面包图像','把 paper 与 bread 并置，使 page / food 两种日常物同时成立','制作 17 个 units 形成 encyclopedia-like sequence','保留 bread 的重量、裂纹、老化与可腐败属性','用 serial arrangement 调用 institutional knowledge format，却以最日常食物破坏其永久性'],sourceUrl:textileForum,images:[],relations:[rel('展览','Viva Arte Viva — Venice Biennale 2017','Enciclopedia Pane, 2008 · 17 bread books')]},{title:'Legarsi alla montagna',cluster:'10+ km blue ribbon / whole-town participation / social relation score',period:'1981',summary:'Ulassai 全镇参与的三日行动，以超过十公里蓝色 ribbon 将 houses、居民关系与 Mount Tisiddu 连在一起。不同邻里关系用直线、结、蝴蝶结甚至面包被编码在同一 ribbon 上。',actions:['从 Ulassai local legend 中提取“蓝色带子救人”这一共同记忆作为 action trigger','与居民协商，让整座 town 而非专业 performers 成为参与者','准备长达十公里以上的 blue ribbon 并沿 houses / streets 延伸','允许每户自行决定与邻居如何连接：关系疏远时拉直，友谊用 knot，爱情/亲密以 bow 等形式表达','在部分结点把 local decorated bread 系到 ribbon 上','最终将 village ribbon 延伸至 mountain，使 social map 与 landscape physically connected','让关系差异直接决定 material configuration，而不是先设计统一美观效果'],sourceUrl:mariaLegarsi,images:[],relations:[rel('展览','Legarsi alla montagna — Ulassai','8 Sep 1981; three-day community action'),rel('展览','Viva Arte Viva — Venice Biennale 2017','posthumous historical context')] }],awards:[],exhibitions:['Legarsi alla montagna — Ulassai 1981','Viva Arte Viva — Venice Biennale 2017 · posthumous'],sources:[{label:'Treccani · Maria Lai',url:mariaTreccani},{label:'Italian Ministry of Culture · Legarsi alla montagna',url:mariaLegarsi},{label:'Textile Forum · Venice 2017 Maria Lai works',url:textileForum}]},

'venice-2017-teresa-lanceta':{artistId:'venice-2017-teresa-lanceta',projectCoverage:'2 个 Middle-Atlas open-code / sewn-painted-cloth 节点已建立深档案 · 1985–2017',imageCoverage:'0 / 2 项目暂不使用不稳定外链图像',note:'Lanceta 从 1970s 中期决定以 weaving 作为艺术媒介；Mid-1980s 开始 Middle Atlas 项目。她不把 Berber/Amazigh textiles 当匿名“民族图案库”，而追踪具体 women weavers 如何在 inherited rules 内做个人决定。Venice 2017 属第三阶段 Adiós al rombo。',projects:[{title:'Middle Atlas research → Adiós al rombo',cluster:'weaving / original-source textile / women weavers / open-code tradition',period:'1985–2017',summary:'项目从一件具体 original Middle Atlas weave 出发，经历 La alfombra roja (1989)、Tejidos marroquíes (2000) 与 Adiós al rombo (2016–2017) 三阶段。Lanceta 保留 technique/material/format 等 inherited constraints，同时研究 individual weaver 如何在规则中改变 motif、void、rhythm。',actions:['从 1985 起长期进入 Middle Atlas textile tradition，而非短期采样图案','每一阶段选择具体 original weave 作为 guide / nexus，并在展览或出版中与自己的 work 建立可追踪关系','研究 handira、hanbel、cushion 等具体 textile formats 与用途','在继承的 technique、material、format 范围内重新组织 motif / void / rhythm，而不是复制 source design','与地区 women / relatives / migrants 访谈，记录 weaving 与迁移、个人生活的关系','拒绝“anonymous tribal art”概括，强调每位 weaver 在 inherited code 中的 individual decisions','在 Adiós al rombo 中加入 tapestry、painting、drawing、text、video interviews 和 digital pattern collaboration，使 research 不被单一媒介垄断','2017 Venice 延续第三阶段，把 tradition 理解为可被继续修改的 open code'],sourceUrl:lanceta,images:[],relations:[rel('展览','Adiós al rombo — La Casa Encendida / Azkuna Zentroa','2016'),rel('展览','Viva Arte Viva — Venice Biennale 2017','Adiós al rombo continuation')]},{title:'Rosablancas III',cluster:'sewn + painted cloth / textile-painting hybrid / hand-made rhythm',period:'2014–2016; shown 2017',summary:'Venice 展出的 Rosablancas III 被记录为 sewn and painted cloth；它把 painting 的色面与 sewing 的接缝、布料边界放在同一 surface，使“画”和“织物”无法分开。',actions:['选择 cloth 作为基础 surface 而不是传统 stretched canvas','对 cloth 进行切分/拼接，使 seam 成为 composition line','在布面直接 painting，而不把 textile 当单纯底材','让 sewn joins、edge irregularity 与 painted marks 同时可见','利用 repetition / stripe / geometric relation 建立接近 weaving rhythm 的视觉秩序','保留 hand-made material difference，避免把 textile finish 伪装成无缝绘画'],sourceUrl:textileForum,images:[],relations:[rel('展览','Viva Arte Viva — Venice Biennale 2017','Rosablancas III, 2014–2016')]}],awards:[],exhibitions:['Adiós al rombo — 2016','Viva Arte Viva — Venice Biennale 2017'],sources:[{label:'Teresa Lanceta · Don’t buy the hours / Middle Atlas project',url:lanceta},{label:'Teresa Lanceta · Adiós al rombo publication',url:lancetaPub},{label:'Textile Forum · Venice 2017 / Rosablancas III',url:textileForum},{label:'La Biennale · Teresa Lanceta 2017',url:'https://www.labiennale.org/en/biennale-channel/biennale-arte-2017-teresa-lanceta'}]}
};
