import type { ArtistArchive, ArchiveProject, ArchiveRelation } from './archiveData';
const rel=(kind:ArchiveRelation['kind'],label:string,detail?:string):ArchiveRelation=>({kind,label,detail});
const project=(p:ArchiveProject)=>p;
export const archiveBatch296:Record<string,ArtistArchive>={
  'thomas-demand':{artistId:'thomas-demand',projectCoverage:'继续深化既有 Thomas Demand，不新增艺术家：补 Room 的“图像→模型→图像”认识论，并以 Presidency、Embassy、Clearing 扩展其政治空间、系列叙事与自然/人工边界。',imageCoverage:'本批只记录 MoMA 与 National Gallery of Art 官方作品页和机构参数；版权受限图像不复制进仓库。',note:'Demand 的稳定方法不是“把现实做成纸模型”，而是把已经成为图像的现实再次物质化，再重新摄影。1993年前后摄影从雕塑记录工具反转成最终作品，纸模型成为一次性中介。这个双重转译使他与直接纪录摄影拉开距离：他研究的不是事件现场本身，而是事件如何以图像形式进入公共记忆。',projects:[
project({title:'Room (Zimmer) — image → life-size model → photograph',cluster:'source image / paper reconstruction / mediated memory',period:'1996',summary:'MoMA 对 Demand 方法的关键描述是：他先从一张既有照片出发，以纸重新制作 L. Ron Hubbard 1972–73年居住和工作的酒店房间，再拍摄模型。钟面没有数字、打字机没有按键等缺失并非制作失败，而是提醒观众这不是可使用的真实空间。MoMA 同时指出 Demand 最初以摄影记录短暂纸雕塑，到1993年左右反转关系，开始专门为最终摄影而建模型。因此 Room 应被理解为“现实空间→既有照片→纸模型→最终照片”的多级中介，而非单纯布景摄影。',actions:['选择已经存在的房间照片作为来源，而不是进入原现场。','把二维来源重新推导成近真人尺度纸/纸板空间。','删除数字、按键等功能细节，让物体保持可辨识却不可使用。','以均匀工作室光线拍摄模型，使成片在可信与人工之间摆动。','最终保留大型 chromogenic print；模型承担中介而非永久雕塑角色。'],sourceUrl:'https://www.moma.org/collection/works/57201',images:[],relations:[rel('收藏','Museum of Modern Art, New York','Room (Zimmer), 1996；chromogenic print；172 × 232 cm。'),rel('展览','Thomas Demand — MoMA','2005年3月4日–5月30日；MoMA回顾其从雕塑记录转向“为摄影建模型”的方法。')]}),
project({title:'Presidency — political interior as five-image sequence',cluster:'political architecture / serial photography / chromogenic prints',period:'2008',summary:'National Gallery of Art 将 Presidency 登记为五张 chromogenic prints，而不是单张决定性图像；整体尺度约310 × 1071.88 cm。这个系列节点适合用于区分 Demand 与新闻摄影：政治权力不必通过领导人肖像来表现，办公空间、家具、门、桌面和建筑秩序本身即可成为权力的视觉代理。五联结构又把观看从单一“证据照片”变成沿空间连续移动的阅读。',actions:['把政治权力转译为室内与制度空间，而非依赖人物肖像。','以多张图像组成横向序列，让观众在空间细节之间移动。','维持纸模型去文字化、去使用痕迹的表面，使政治现场呈现为熟悉却失真的制度舞台。','以超大整体尺度把原本来自媒介的政治图像重新变成身体尺度的展览经验。'],sourceUrl:'https://www.nga.gov/artworks/143461-presidency',images:[],relations:[rel('收藏','National Gallery of Art, Washington','2008；5 chromogenic prints；整体约310 × 1071.88 cm；2009入藏。'),rel('出版','New York Times Magazine','NGA bibliography记录作品于2008年11月9日相关报道中刊载。')]}),
project({title:'Embassy — diplomacy reconstructed as image system',cluster:'embassy / diplomacy / architecture / nine-print sequence',period:'2007',summary:'NGA 馆藏将 Embassy 登记为九张 chromogenic prints。与 Presidency 一样，它说明 Demand 并不只生产孤立的“假现场照片”：当题材涉及制度建筑时，他可以通过系列化让建筑外观、室内和视觉线索共同构成叙事。大使馆这一地点尤其强化了他的核心问题——公共事件往往通过少量新闻图像被记忆，而模型重建把这种图像记忆的选择性和空缺重新暴露出来。',actions:['围绕外交机构而不是人物建立系列。','将来源图像转译为纸模型，再摄影为九张最终图像。','以系列而非单幅组织制度空间，使观看接近档案/调查式阅读。','利用纸模型的无痕表面削弱地点的日常性，让建筑显露为政治图像的舞台。'],sourceUrl:'https://www.nga.gov/artworks/218618-embassy',images:[],relations:[rel('收藏','National Gallery of Art, Washington','Embassy, 2007；9 chromogenic prints；Heather Podesta Collection捐赠，2019入藏。')]}),
project({title:'Clearing — constructed nature',cluster:'nature / artificiality / monumental photograph',period:'2003',summary:'Clearing 把 Demand 的纸模型逻辑从室内、犯罪或政治现场推进到“自然”。MoMA 馆藏最终 chromogenic print 尺寸约192 × 495 cm，接近全景壁面。作品的重要性在于：纸和纸板通常容易被理解为建筑模型材料，但当树叶、枝条和林间空地也被重新制作时，“人工模型/真实自然”的直觉对立失效。观众面对的不是自然现场，而是一个先被建造、再被摄影自然化的环境。',actions:['把通常用于建筑/室内重建的纸模型方法转向植物和林地。','大量重复制作叶片、枝条与空间层次，使手工劳动模拟自然复杂度。','通过摄影重新压平三维模型，让纸制植物在最终图像中获得自然主义可信度。','以约五米宽的大幅输出让人工自然超过普通照片尺度，形成身体性的观看。'],sourceUrl:'https://www.moma.org/collection/works/90063',images:[],relations:[rel('收藏','Museum of Modern Art, New York','Clearing, 2003；chromogenic print；192 × 495 cm。'),rel('展览','Thomas Demand — MoMA','2005回顾展展出；MoMA保存对应安装图。'),rel('展览','A World of Its Own: Photographic Practices in the Studio — MoMA','2014；Demand被放入摄影棚/建构型摄影的历史语境。')]})],awards:[],exhibitions:['Thomas Demand — Museum of Modern Art, New York — 4 Mar–30 May 2005','A World of Its Own: Photographic Practices in the Studio — MoMA — 8 Feb–2 Nov 2014'],sources:[{label:'MoMA — Thomas Demand exhibition (2005)',url:'https://www.moma.org/calendar/exhibitions/116'},{label:'MoMA — Room (Zimmer)',url:'https://www.moma.org/collection/works/57201'},{label:'MoMA — Clearing',url:'https://www.moma.org/collection/works/90063'},{label:'National Gallery of Art — Thomas Demand',url:'https://www.nga.gov/artists/34349-thomas-demand'},{label:'National Gallery of Art — Presidency',url:'https://www.nga.gov/artworks/143461-presidency'},{label:'National Gallery of Art — Embassy',url:'https://www.nga.gov/artworks/218618-embassy'}]}
};