import type { ArtistArchive, ArchiveRelation } from './archiveData';

const rel=(kind:ArchiveRelation['kind'],label:string,detail?:string):ArchiveRelation=>({kind,label,detail});

export const archiveBatch261:Record<string,ArtistArchive>={
  'laia-abril':{
    artistId:'laia-abril',
    projectCoverage:'作品级深化：继续把 A History of Misogyny 从系列总述下钻到具体物件、图像与展览版本；本批重点记录 On Abortion 的 Illegal Instrument Kit、2019 Foto Colectania / 2020 Museum of Sex 版本，以及 On Rape 的 Chastity Belt、Shrinky Recipe 与 2020–21 Foam / 2024 C/O Berlin 空间版本。',
    imageCoverage:'Foto Colectania、Foam、C/O Berlin/艺术家官网、Museum of Sex 均提供对应作品或安装图。图片版权标注为 © Laia Abril / Courtesy Laia Abril & Galerie Les filles du calvaire，未确认开放再发布许可，故不复制受限文件；在作品节点中保留官方图像入口与版权说明。',
    note:'这一批重点避免把 Abril 写成“拍摄女性议题”的摄影师：她实际把采访、历史资料、医学物件、概念摄影、声音、视频和文本设计成可在空间中重新编排的证据系统。不同展览并不是固定照片墙的巡展，而会依据场地重新组合照片、文字、音视频与历史物件。',
    projects:[
      {title:'Illegal Instrument Kit — On Abortion',cluster:'A History of Misogyny / On Abortion / object study',period:'2016',summary:'《Illegal Instrument Kit》是 On Abortion 中被多家机构作为代表图像展示的具体作品节点。Abril 并不以手术现场的直接暴力图像制造冲击，而是把非法或危险终止妊娠所涉及的器具作为证据对象来拍摄和编排。Foto Colectania 2019 展览将它作为主视觉并明确标注“Kit de instrumentos ilegal”；Foto Arsenal Wien 2023–24 亦以同一作品作为展览图像。它与衣架、被固定在床架上的手铐、模糊肖像等图像一起工作：单件照片本身保持克制，暴力通过物件的用途、文字证词及其与其他证据的邻接关系逐渐显现。',actions:['调查历史与当代不安全堕胎方法，并把医学/非法器具纳入视觉证据库。','对器具进行控制性的物件摄影，而不是重演伤害过程。','将器具照片与采访、历史材料、地图、科学/法医图像、文字和音视频并置。','在不同展览中重新编排证据关系，使观众必须在图像与说明之间往返阅读。'],sourceUrl:'https://fotocolectania.org/en/exhibition/126/laia-abril-on-abortion',images:[],relations:[rel('展览','Foto Colectania, Barcelona','2019；官方页面以 Illegal Instrument Kit 作为展览代表图，credit: Courtesy Laia Abril / Les Filles du Calvaire。'),rel('展览','Foto Arsenal Wien','15 Dec 2023–10 Mar 2024；官方展览传播再次使用 Illegal Instrument Kit, 2016，© Laia Abril。')]},
      {title:'On Abortion — Foto Colectania installation version',cluster:'A History of Misogyny / installation / evidence architecture',period:'2019',summary:'Foto Colectania 明确把这一版本称为“installation project”而非传统摄影展。Abril 把超过五十个故事组织成概念地图：摄影只是基础层，图像来源同时包括她拍摄的肖像与物件、vernacular photographs、科学/法医照片和地图；这些图像再与采访、研究文本、声音和视频安装结合。观众因此不是顺着单一照片序列观看，而是在墙面图像、说明、证词和时间媒介之间移动，逐渐拼合缺乏安全合法堕胎渠道所造成的强迫生育、刑事追诉、医疗伤害与死亡。黑白摄影是 Abril 有意选择的视觉策略：她希望材料保持严厉，但避免依赖显而易见的血腥图像。',actions:['从全球案例中累积五十余个故事，并进行历史与当代交叉研究。','混合作者摄影、民间照片、科学/法医影像、地图等不同证据等级的图像。','为图像配套采访与研究文字，并加入声音/视频装置。','依据展厅重新组织墙面、文本与时间媒介，使项目从摄影书结构转换为空间证据网络。'],sourceUrl:'https://fotocolectania.org/en/exhibition/126/laia-abril-on-abortion',images:[],relations:[rel('展览','Foto Colectania, Barcelona','2019；机构明确称其为 installation project。'),rel('出版','On Abortion — Dewi Lewis','2018；摄影书版本与展览版共享研究材料但以书页次序重新组织。'),rel('奖项','Paris Photo–Aperture PhotoBook of the Year','Winner 2018')]},
      {title:'On Abortion — Museum of Sex version',cluster:'A History of Misogyny / institutional adaptation / historical objects',period:'2020',summary:'纽约 Museum of Sex 的美国首个展版本进一步改变了项目的物质结构：除 Abril 自身的摄影、文本、视频和声音研究外，展览加入 The Burns Archive & Collection 提供的古董 abortion-related medical tools。也就是说，同一项目在这里不只是复制既有照片墙，而是把历史医学实物与 Abril 的当代视觉调查放在同一观看环境中。观众面对的是“图像证据 + 口述/文本 + 时间媒介 + 历史器具”的复合档案，从而把过去的医疗技术与当代法律、社会强制之间建立时间连续性。',actions:['将既有 On Abortion 视觉/声音/文本档案适配纽约展厅。','与 The Burns Archive & Collection 合作，引入古董医学器具作为历史实物证据。','让历史物件与当代案例、摄影和证词共同构成空间叙事，而非只作说明性道具。'],sourceUrl:'https://www.museumofsex.com/exhibitions/laia-abril-on-abortion/',images:[],relations:[rel('展览','Museum of Sex, New York','7 Feb–15 Oct 2020；Abril 美国首次个展。'),rel('收藏','The Burns Archive & Collection','为该版本提供与 abortion 相关的 antique medical tools。')]},
      {title:'Chastity Belt — On Rape',cluster:'A History of Misogyny / On Rape / conceptual photograph',period:'2019',summary:'《Chastity Belt》是 Foam 在 On Rape 展览页面明确列出的具体作品。Abril 的第二章不是以单一受害者肖像说明强奸，而是研究制度、法律、宗教与文化如何制造和保护 rape culture；她据此制作“conceptual portraits and testimonies”，并把研究转译成文字隐喻和 audiovisual installations。Chastity Belt 作为具体视觉隐喻，把控制女性身体、所谓“保护”与将责任转嫁给潜在受害者的制度逻辑压缩到一个可辨识对象中。',actions:['从 rape culture 的制度史与当代案例中提取身体控制机制。','把研究命题转译为概念性物件/肖像图像，而不是复演暴力事件。','与证词、文本隐喻和音视频材料共同编排，使单张照片进入更大的制度研究结构。'],sourceUrl:'https://www.foam.org/nl/events/laia-abril-on-rape-a-history-of-misogyny-chapter-two',images:[],relations:[rel('展览','Foam, Amsterdam','6 Nov 2020–27 Jun 2021；官方页面刊载 Chastity Belt, 2019，credit: Courtesy Laia Abril & Galerie Les filles du calvaire。')]},
      {title:'Shrinky Recipe — On Rape',cluster:'A History of Misogyny / On Rape / text-image metaphor',period:'2019',summary:'《Shrinky Recipe》同样由 Foam 作为 On Rape 的具体作品刊出。它属于 Abril 将研究材料转换为“metaphors of texts and audiovisual installations”的方法：文本不只是照片旁的解释标签，而被处理为作品构成部分。与 Chastity Belt 并置时，可以看到 On Rape 如何在物件隐喻、概念摄影、证词和语言材料之间切换，避免把性暴力再次变成供观看的受害者身体。',actions:['从制度性强奸与 rape culture 研究中提取语言材料。','把文本/配方式结构转化为视觉隐喻，使语言本身成为作品媒介。','与概念肖像、证词和音视频装置共同进入展览序列。'],sourceUrl:'https://www.foam.org/nl/events/laia-abril-on-rape-a-history-of-misogyny-chapter-two',images:[],relations:[rel('展览','Foam, Amsterdam','2020–21；Foam 官方页面提供 Shrinky Recipe, 2019 作品图与版权 credit。')]},
      {title:'On Rape — C/O Berlin spatial version',cluster:'A History of Misogyny / installation adaptation / exhibition version',period:'2024',summary:'C/O Berlin 版本由 Sophia Greiff 策展。艺术家官网保存多张 David von Becker 拍摄的 installation views，因此这一节点专门记录 On Rape 从研究档案到具体空间的变化：照片、文字与其他媒介并非一个永久固定版式，而会随展厅重新形成观看路径。这个版本应与 Foam 2020–21 版分开记录，因为安装摄影能够用于比较墙面密度、作品间距、文本位置及观众移动方式，而不是把巡展误认为同一套静态陈列。',actions:['将 On Rape 的照片、证词、文本与音视频材料重新适配 C/O Berlin 展厅。','通过墙面分区和观看路径建立材料之间的因果/历史关系。','用 installation views 保存这一空间版本，便于与 Foam 等早期版本比较。'],sourceUrl:'https://www.laiaabril.com/exhibition/on-rape-coberlin/',images:[],relations:[rel('展览','C/O Berlin','27 Jan–21 May 2024；curated by Sophia Greiff。'),rel('展览','Installation photography','David von Becker；艺术家官网保存多张展览现场图。')]}
    ],
    awards:['Paris Photo–Aperture PhotoBook of the Year 2018 — On Abortion','Foam Paul Huf Award 2020'],
    exhibitions:['On Abortion — Foto Colectania, 2019','On Abortion — Museum of Sex, New York, 2020','On Rape — Foam, Amsterdam, 2020–21','On Rape — C/O Berlin, 2024'],
    sources:[{label:'Foto Colectania · On Abortion',url:'https://fotocolectania.org/en/exhibition/126/laia-abril-on-abortion'},{label:'Museum of Sex · On Abortion',url:'https://www.museumofsex.com/exhibitions/laia-abril-on-abortion/'},{label:'Foam · On Rape',url:'https://www.foam.org/nl/events/laia-abril-on-rape-a-history-of-misogyny-chapter-two'},{label:'Laia Abril · On Rape C/O Berlin',url:'https://www.laiaabril.com/exhibition/on-rape-coberlin/'},{label:'Laia Abril · exhibitions',url:'https://www.laiaabril.com/about/exhibitions/'}]
  }
};
