import type { ArtistArchive, ArchiveRelation } from './archiveData';
const rel=(kind:ArchiveRelation['kind'],label:string,detail?:string):ArchiveRelation=>({kind,label,detail});

export const archiveBatch205:Record<string,ArtistArchive>={
'hito-steyerl':{
 artistId:'hito-steyerl',
 projectCoverage:'作品级深化：Factory of the Sun；补足影像来源、动作捕捉叙事、沉浸式空间与 Venice→MOCA 展览版本。',
 imageCoverage:'MOCA Los Angeles 官方展览页提供多张 2016 installation views，credit 为 The Museum of Contemporary Art, Los Angeles，摄影 Justin Lubliner 与 Carter Seddon。本站记录官方图集与 credit；未确认可再发布的稳定原图直链，因此不复制网页图像。',
 note:'Factory of the Sun 不是单独播放的一条“互联网影像”，而是把游戏、动作捕捉、新闻、纪录片与舞蹈影像放进一个让观众身体进入的显示空间。作品的政治性来自影像内容与观看装置同时运作。',
 projects:[{title:'Factory of the Sun',cluster:'immersive video installation / motion capture / game-space / surveillance',period:'2015–2016',summary:'作品于 2015 Venice Biennale 德国馆首次呈现，2016 MOCA Los Angeles 举行美国首展。影片把新闻报道、纪录片、电子游戏视觉和互联网舞蹈影像交叉剪辑；核心虚构情节是一群工人在 motion-capture studio 中被迫运动，其身体动作被转换为“人工阳光”。作品因此把身体劳动、数据采集、娱乐和监控压在同一条生产链上。',actions:['具体动作：Steyerl 将新闻、纪录片、游戏界面和网络舞蹈等不同影像语法剪进同一 moving-image work，并以 motion-capture workers 的虚构故事组织这些材料。','叙事机制：工人的动作被记录、数据化并转成“人工阳光”；动作捕捉不只是视觉特效，而是作品讨论身体如何被计算、商品化和监控的具体技术模型。','展陈：作品以 immersive video installation 呈现，观众不是站在传统影院外观看，而是进入由屏幕、光线和数字网格感组织的环境；MOCA 官方页面保存多张完整 installation views，可用于核对空间版本。','版本：作品 2015 首展于 Venice Biennale German Pavilion，2016 在 MOCA Grand Avenue 呈现美国首展。网站将 Venice 首版与 MOCA 版本视为同一作品在不同建筑中的展陈版本，不把 installation view 当成独立作品。','观看：作品让观众一边消费高密度娱乐影像，一边意识到娱乐、监控与劳动使用相同的数据基础设施；观看者身体进入装置后也被置于类似“界面空间”。','图像 / 版权：MOCA 展览页明确标注 installation views courtesy of The Museum of Contemporary Art, Los Angeles，摄影 Justin Lubliner and Carter Seddon；本站仅记录官方图集入口与 credit。'],sourceUrl:'https://www.moca.org/exhibitions/hito-steyerl-factory-of-the-sun',images:[],relations:[rel('展览','German Pavilion, Venice Biennale 2015','作品首次呈现'),rel('机构','MOCA Los Angeles','2016 US premiere；官方 installation views')] }],awards:[],exhibitions:['German Pavilion, Venice Biennale 2015','MOCA Grand Avenue 2016'],sources:[{label:'MOCA Los Angeles · Hito Steyerl: Factory of the Sun',url:'https://www.moca.org/exhibitions/hito-steyerl-factory-of-the-sun'}]
},
'stan-douglas':{
 artistId:'stan-douglas',
 projectCoverage:'作品级深化：Luanda-Kinshasa / ISDN；补足摄影棚重建、音乐表演、循环时长、双频道结构与跨地域协作机制。',
 imageCoverage:'David Zwirner 官方项目页提供 Luanda-Kinshasa 与 ISDN 的作品/installation stills 和展览图。本站保留官方图像入口与已公开 credit，不复制未确认再发布许可的画廊图片。',
 note:'Douglas 的影像经常看起来像历史纪录，但制作方法恰恰高度人工：重建场景、选择表演者、组织音乐事件，再用复杂剪辑/显示结构制造“可能发生过”的历史。',
 projects:[{title:'Luanda-Kinshasa',cluster:'single-channel video / reconstructed recording studio / improvised music / generative-duration logic',period:'2013',summary:'Douglas 在纽约搭建了一套精确指向 Columbia Records 30th Street Studio 的摄影棚——这座传奇录音棚原本位于废弃 Armenian church 中，1949–1981 年运营。作品让音乐家在这个历史空间的重建版本里演奏，并以纪录片式摄影把一个并未真正发生于 1970s 的跨文化音乐会拍得像历史档案。David Zwirner 登记作品为 single-channel video projection，6 hours 1 min loop，color, sound，尺寸随安装变化。',actions:['具体动作：不是进入保存下来的老录音棚拍摄，而是重新搭建 Columbia 30th Street Studio 的历史空间；布景因此是作品的第一层“历史制造”。','表演：邀请音乐家在重建录音棚中真实演奏，以 documentary-like camera language 拍摄，使 staged event 获得历史纪录片的表面可信度。','材料 / 技术：官方作品记录为 single-channel video projection，color, sound；完整循环 6 hours 1 min，overall dimensions vary with installation。','观看：六小时以上的循环拒绝传统电影从头看到尾的要求；观众更像进入一个持续发生的 recording session，在任意时刻截取一段“历史”。','空间版本：2014 David Zwirner New York 首展后作品曾进入不同机构/展览；每次投影尺度可随空间变化，但长循环与录音棚影像结构保持核心一致。','图像：David Zwirner 官方展览页保存作品与 installation views；本站记录来源，不抓取画廊图像文件。'],sourceUrl:'https://www.davidzwirner.com/exhibitions/2014/luanda-kinshasa',images:[],relations:[rel('画廊','David Zwirner','2014 New York presentation；作品规格与 installation views')]},{title:'ISDN',cluster:'two-channel video installation / rap performance / remote audio-network / Venice Biennale',period:'2022',summary:'ISDN 为大型双频道影像装置，最初为第59届 Venice Biennale 构思。Douglas 组织 London 与 Cairo 的 rappers 进行虚构的跨地域音乐表演，标题来自 1980s 引入、可经铜电话线传输高质量数字音频的 Integrated Services Digital Network 技术。作品把“远距离同时表演”本身变成形式，而不是只把音乐当 soundtrack。',actions:['具体动作：分别组织 London 与 Cairo 的 rappers 进行表演，通过作品设定把两个城市的声音文化放进一次跨地域 exchange。','显示：官方作品记录为 two-channel video installation；两个影像通道使观众必须在并置画面之间分配注意力，而不是把跨地域关系压成单一 montage。','材料 / 版本：2022，two-channel video installation，overall dimensions variable，edition of 4 + 1 AP；作品已进入 MoMA 与 SFMOMA collections。','技术概念：标题 ISDN 指向一种用于传输高质量 digital audio 的通信技术；网络传输因此不是背景知识，而是作品把 London / Cairo 音乐文化想象成实时连接的技术骨架。','展览版本：作品最初与 Venice Biennale 2022 项目相关，2023 David Zwirner Los Angeles 与相关 photographs 一同展出，2024–2025 又成为 Serralves 展览核心。','图像 / 版权：David Zwirner 官方作品页和展览页提供 still / installation images；本站保留官方入口。'],sourceUrl:'https://www.davidzwirner.com/artworks/stan-douglas-isdn-4a03c',images:[],relations:[rel('双年展','La Biennale di Venezia 2022','作品初始语境'),rel('机构','MoMA','collection'),rel('机构','SFMOMA','collection')] }],awards:[],exhibitions:['David Zwirner New York 2014 — Luanda-Kinshasa','La Biennale di Venezia 2022 — ISDN','David Zwirner Los Angeles 2023 — ISDN'],sources:[{label:'David Zwirner · Luanda-Kinshasa',url:'https://www.davidzwirner.com/exhibitions/2014/luanda-kinshasa'},{label:'David Zwirner · ISDN',url:'https://www.davidzwirner.com/artworks/stan-douglas-isdn-4a03c'},{label:'David Zwirner · Venice 2022 / Stan Douglas',url:'https://www.davidzwirner.com/venice-2022/stan-douglas'}]
},
'anicka-yi':{
 artistId:'anicka-yi',
 projectCoverage:'作品级深化：You Can Call Me F；补足100位女性样本、合成生物学协作、活体细菌材料与展厅作为 forensic site 的结构。',
 imageCoverage:'The Kitchen 官方 archive 保存 2015 展览 press release 与项目档案。因档案图片再发布条件和稳定原图地址未确认，本批次不复制图片；作品页明确标注官方档案入口。',
 note:'Yi 的关键不是“用细菌做艺术”这一奇观，而是把社交网络真实转成生物材料：人的职业关系、捐赠样本、实验室培养与展览卫生焦虑被串成同一系统。',
 projects:[{title:'You Can Call Me F',cluster:'living bacteria / synthetic biology / collective female network / forensic installation',period:'2015',summary:'2015 年在 The Kitchen 展出。Yi 邀请自己职业网络中的 100 位女性——包括 artists、curators、critics、dealers 与 collectors——捐赠 biological information samples，并在 synthetic biologist Tal Danino 指导下将这些样本用于形成 collective bacteria。The Kitchen 的 gallery 被设定为 forensic site：活体细菌既是实际材料，也把女性网络被父权文化想象为“contagion / pathogen”的恐惧物质化。',actions:['具体动作：不是购买标准实验菌株作为象征，而是向 100 位现实女性协作者征集 biological information samples，把职业/社会关系转译为可培养的生物材料。','协作：在 synthetic biologist Tal Danino 指导下处理 collective bacteria；科学合作因此进入作品制作链，而不是展览后的解释文本。','材料：living / collective bacteria 是作品核心材料之一。官方 press release 明确把 bacteria 描述为 living material，并将其与 contagion、hygiene 和 female networks 联系。','空间：The Kitchen gallery 被设计/叙述为 forensic site；观众面对的不是中性的 white cube，而是一个让培养、污染、证据和卫生管理同时进入想象的现场。','观看：观众无法只从视觉造型判断作品；知道样本来自100位具体女性后，作品的尺度从一个生物对象扩展为社会网络、照护、恐惧和制度控制。','来源 / 图像：The Kitchen 官方 archive PDF 保存展览日期（2015-03-05—04-11）、制作逻辑和合作信息；本站记录该官方档案，不把 PDF/网页预览图直接复制为作品图。'],sourceUrl:'https://archive.thekitchen.org/wp-content/uploads/2017/03/Anicka-Yi-PR-Final-FOR-GALLERY.pdf',images:[],relations:[rel('机构','The Kitchen','2015 solo exhibition / gallery as forensic site'),rel('合作','Tal Danino','synthetic biologist；collective bacteria 制作指导')] }],awards:[],exhibitions:['The Kitchen — You Can Call Me F, 2015'],sources:[{label:'The Kitchen Archive · Anicka Yi: You Can Call Me F press release',url:'https://archive.thekitchen.org/wp-content/uploads/2017/03/Anicka-Yi-PR-Final-FOR-GALLERY.pdf'}]
}
};
