import type { ArtistArchive, ArchiveRelation } from './archiveData';
const rel=(kind:ArchiveRelation['kind'],label:string,detail?:string):ArchiveRelation=>({kind,label,detail});

const roster='https://www.labiennale.org/en/art/2017/artists';
const awards='https://www.labiennale.org/en/art/2017/awards-biennale-arte-2017';
const halilaj='https://www.mennour.com/exhibition/do-you-realise-there-is-a-rainbow-even-if-it-s-night';
const halilajWork='https://chertluedde.com/work/do-you-realise-there-is-a-rainbow-even-if-its-night-2023/';
const halprin='https://static1.squarespace.com/static/62cb6c4f3dd8c74a52efdb24/t/632a83fbfcd87c13d01e40c6/1663730685535/4-ANZJAT-2017-AL.pdf';
const halprinGrant='https://www.metalocus.es/en/news/72-projects-received-graham-foundation-awards-2017-grants';
const hao='https://ucca-group.com/en/exhibition/eight-views-of-xiaoxiang-1-2/';
const heraclito='https://inresidence.videobrasil.org.br/2015/08/24/os-sacudimentos-a-reuniao-das-margens-atlanticas-projeto-finalizado-durante-o-premio-de-residencia-sesc_videobrasil-na-raw-material-company-dacar-senegal/';
const heraclitoBio='https://pivo.org.br/en/participantes/ayrson-heraclito/';
const hicks='https://alisonjacques.com/artists/sheila-hicks';
const hicksProcess='https://www.irenebrination.com/2017/11/21/sheila-hicks-venice-biennale/';
const hicksAsac='https://asac.labiennale.org/collezioni/fototeca/370107';

export const archiveBatch129:Record<string,ArtistArchive>={
'venice-2017-petrit-halilaj':{artistId:'venice-2017-petrit-halilaj',projectCoverage:'1 个 mother-son textile / wearable-moth / Kosovo-memory installation 已建立深档案 · 2016–2017',imageCoverage:'0 / 1 项目暂不使用不稳定外链图像',note:'Halilaj 的 moths 不是“童年回忆做成漂亮动物”：他与母亲 Shkurte 共同切割/缝合 Kosovo 传统 qilim、dyshek、jan carpets，把 refugee childhood、lost home、craft memory 与 metamorphosis 做成既能穿戴又能攀附建筑的大型 sculpture。2017 获主展 Special Mention。',projects:[{title:'Do you realise there is a rainbow even if it’s night!?',cluster:'Kosovar carpets / giant moth / mother-son collaboration / wearable sculpture',period:'2016–2017',summary:'大型 moth sculptures 使用来自 Kosovo 的传统 rugs / fabrics、flokati、polyester、chenille wire、stainless steel、brass 等材料。最初 moth costume 与母亲共同制作，随后在 Venice 中扩展为一群躺地、爬墙、藏进 Arsenale rafters 的巨大昆虫。',actions:['从 childhood memory 中反复出现的 moth / light-bulb encounter 选择核心形象','与母亲 Shkurte 共同切割 Kosovo traditional qilim / dyshek / jan carpets','保留 carpet 的 weaving history / domestic association，而不把 textile 只当表面图案','使用 wire / metal support 将软 textile 扩展为大尺度 wing / insect body','让部分 moth 保持 wearable / costume logic，使 sculpture 可被 human body 激活','根据 Arsenale architecture 将 moth 分散到 floor、wall、rafters 等不同高度','故意让部分作品半隐藏，要求 viewer 抬头/寻找，模拟 childhood chasing / discovery','把 exile / war history 通过 intimate domestic material 和 metamorphosis metaphor 间接出现，而非图解战争'],sourceUrl:halilaj,images:[],relations:[rel('展览','Viva Arte Viva — Venice Biennale 2017','Arsenale / Central Pavilion'),rel('奖项','Special Mention — Venice Biennale 2017','jury cited Kosovo history + childhood memories + imaginative architectural interventions')]}],awards:['Special Mention — Venice Biennale 2017'],exhibitions:['Viva Arte Viva — Venice Biennale 2017'],sources:[{label:'Mennour · Do you realise there is a rainbow even if it’s night!?',url:halilaj},{label:'ChertLüdde · moth work / materials',url:halilajWork},{label:'La Biennale · Awards 2017',url:awards},{label:'La Biennale · Artists 2017',url:roster}]},

'venice-2017-anna-halprin':{artistId:'venice-2017-anna-halprin',projectCoverage:'2 个 community-score / concentric-circle peace ritual 节点已建立深档案 · 1981–2017',imageCoverage:'0 / 2 项目暂不使用不稳定外链图像',note:'Halprin 的作品要按 score / participation protocol 建档，而不是只写“舞蹈”。Planetary Dance 的真正材料是 running pattern、circle geometry、spoken dedication、drumming、共同节奏和 local adaptation。2017 Venice 既展出录像/score，也在 Biennale 语境中重新强调它作为公共和平仪式。',projects:[{title:'Circle the Earth / Earth Run',cluster:'movement score / concentric circles / collective ritual',period:'1981–1980s',summary:'Circle the Earth 中的 Earth Run 要求参与者在 concentric circles 中以不同速度跑动，形成 moving mandala。参与前每人可公开说出 dedication；个人表达随后让位给全体执行同一简单 pattern。',actions:['以 written / drawn score 明确 circle、speed、entry 等 movement rule','把 participants 分布为 concentric circles 而非 front-facing stage formation','为 outer/middle/inner circles 设置不同 running intensity','允许每位参与者在开始前说出 personal dedication','用 repetition 让 individual rhythm 逐渐进入 group organism','把 audience/performance boundary 降低，让非专业舞者也可加入','让 group geometry 本身成为可从外部观看的空间图像'],sourceUrl:halprin,images:[],relations:[]},{title:'Planetary Dance — Venice 2017 presentation / call for peace',cluster:'global participatory dance / filmed performance / score archive / peace ritual',period:'1981–2017',summary:'Planetary Dance 将 Earth Run 发展为全球可移植的 community ritual。Venice 2017 展示 1981–2017 performances / scores，并以“Call for Peace”强调人与人、人与环境的和解；不同社区可改变 preparation/theme，但保留共同 circle-run 核心。',actions:['保留 Earth Run concentric-circle core，使不同地点版本仍有共享结构','允许各地 groups 自行选择 local theme / preparation，使 score 可适应 context','以 drumming / collective rhythm 支撑非专业参与者保持 movement','将 performances 通过 film / video archive 跨时间汇聚，而不要求一个“原版”','在 exhibition 中同时呈现 score、documentation 与 ritual history','把 dance 视为可由 community 重复执行的 social technology，而非一次性 choreography','2017 在 Venice 艺术语境中明确以 peace / environment 作为集体 dedication'],sourceUrl:halprinGrant,images:[],relations:[rel('展览','Viva Arte Viva — Venice Biennale 2017','Planetary Dance scores/videos; call for peace'),rel('展览','documenta 14','2017 dance / political-body context')]}],awards:[],exhibitions:['Viva Arte Viva — Venice Biennale 2017','documenta 14 — 2017'],sources:[{label:'ANZJAT · Anna Halprin / Planetary Dance at Venice',url:halprin},{label:'Graham Foundation grant summary · Call for Peace',url:halprinGrant},{label:'La Biennale · Artists 2017',url:roster}]},

'venice-2017-hao-liang':{artistId:'venice-2017-hao-liang',projectCoverage:'1 个 research-based ink-on-silk / canonical-landscape reprogramming cycle 已建立深档案 · 2014–2016; Venice 2017',imageCoverage:'0 / 1 项目暂不使用不稳定外链图像',note:'Eight Views of Xiaoxiang 不是“古法水墨画当代化”的泛称，而是一组 8 幅 387×184 cm ink-on-silk paintings：Hao Liang 先研究古代文学、画史与 scholarship，再通过时空置换、文本引用和 contemporary ecological sublime 改写一个已有千年传播史的母题。',projects:[{title:'Eight Views of Xiaoxiang',cluster:'ink on silk / eight-painting cycle / literary-art-historical research / temporal displacement',period:'2014–2016; shown Venice 2017',summary:'八幅大尺幅 silk paintings 分别为 Evanescence、Myriads of Transformations、Relics、Dazzle、Snowscape、Cosmos、Scholar’s Traveling、Mind Travel。它们沿用 Xiaoxiang “八景”这一古老框架，却把古代视觉/文学研究、现代知识和 ecological unease 重新编排。',actions:['长期研究 Chinese antiquity 的 literature、aesthetics、painting scholarship，而不是仅模仿古画笔触','选择 Eight Views of Xiaoxiang 这一 historically repeated canonical motif 作为 comparative framework','在 silk 上以 ink 完成每幅 387×184 cm 的大型 painting，维持传统材料的高技术要求','把 mountain/tree/water/cloud 等 shanshui vocabulary 与不属于原时代的 contemporary perception / symbolic structure 混合','通过 spatio-temporal shifts 让古典地景不再对应单一真实地点/年代','使用 textual appropriation / literary association 建立 image 之外的 research layer','将八幅作为 cycle 而非孤立单张组织，使 viewer 比较 motif 的不同“变体”','在 UCCA 展示中采用 recessed vitrines，借古代脆弱作品的 museum-display grammar 加强与传统的对话；Venice 再进入 contemporary biennial context'],sourceUrl:hao,images:[],relations:[rel('展览','Hao Liang: Eight Views of Xiaoxiang — UCCA','2016–2017 first institutional solo'),rel('展览','Viva Arte Viva — Venice Biennale 2017','central international exhibition')]}],awards:[],exhibitions:['UCCA — Eight Views of Xiaoxiang, 2016–2017','Viva Arte Viva — Venice Biennale 2017'],sources:[{label:'UCCA · Eight Views of Xiaoxiang',url:hao},{label:'La Biennale · Artists 2017',url:roster}]},

'venice-2017-ayrson-heraclito':{artistId:'venice-2017-ayrson-heraclito',projectCoverage:'1 个 transatlantic cleansing / sacred-leaf / video-photo diptych 已建立深档案 · 2015; Venice 2017',imageCoverage:'0 / 1 项目暂不使用不稳定外链图像',note:'Venice 2017 的关键项目是 Sacudimentos，而不是常被一并提到的 Transmutação da Carne。Sacudimentos 在 Bahia 与 Gorée 两岸各进行一次 Afro-Brazilian cleansing ritual，再把两次 action 以 video / photo 作为跨大西洋镜像呈现。',projects:[{title:'Sacudimentos / The Shakings: The Meeting of the Atlantic Margins',cluster:'Afro-Brazilian cleansing ritual / sacred leaves / slave-trade architecture / video-photo diptych',period:'2015; shown Venice 2017',summary:'两次 performance 分别发生在 Bahia 的 Casa da Torre dos Garcia d’Ávila 与 Senegal Gorée Island 的 Maison des Esclaves。两座建筑处于 Atlantic slave trade 的相对两岸；Heráclito 用 sacred leaves 进行“sacudimento”驱除负面/亡灵能量，并把两处 action 作为 diptych。',actions:['先选择两座在 Atlantic slavery/colonial system 中具有具体历史位置的 architecture，构成 Africa–Brazil 对岸结构','把两次 performance 预先设计为 diptych，而不是独立 ritual documentation','依据 Afro-Brazilian sacudimento tradition 准备 dense bunches of sacred leaves / branches','以“扫/击/shaking”动作反复触碰 architecture corners / surfaces，利用 leaf friction / heat / movement 执行 cleansing','让 performer body 沿建筑空间移动，使 history 通过 site-specific physical route 被重新经过','在 Gorée 与 Bahia 复制核心 ritual grammar，同时保留两地建筑和历史差异','以 film / photography 记录 performance，但把 image 理解为更大 action 的 index，而不是替代现场','在展览中将两岸 images / videos 镜像组织，使 Atlantic separation 变成观看结构','把“exorcise”指向 colonial/slavery legacy，但明确保留 remembrance：不是抹去历史，而是通过 ritual confront its continuation'],sourceUrl:heraclito,images:[],relations:[rel('展览','Viva Arte Viva — Venice Biennale 2017','Sacudimentos presented through video and photography'),rel('奖项','Sesc_Videobrasil / Raw Material Company residency','project developed in Dakar, 2015')]}],awards:['Sesc_Videobrasil / Raw Material Company residency award — Dakar'],exhibitions:['Viva Arte Viva — Venice Biennale 2017'],sources:[{label:'Videobrasil In Residence · The Shakings',url:heraclito},{label:'Pivô · Ayrson Heráclito biography / Venice relation',url:heraclitoBio},{label:'La Biennale · Artists 2017',url:roster}]},

'venice-2017-sheila-hicks':{artistId:'venice-2017-sheila-hicks',projectCoverage:'1 个 architecture-first / fibre-bale chromatic avalanche 核心节点已建立深档案 · 2016–2017',imageCoverage:'0 / 1 项目暂不使用不稳定外链图像',note:'Hicks 的 Escalade 不是“彩色毛球墙”。她明确以 architecture first：先读 Arsenale 的高度、角落、光，再组织 natural/synthetic fibres、cloth、slate、bamboo、sunbrella 和巨型 fibre bales。安装持续十天以上，最后才临场加入 Guatemala woven anchor panels。',projects:[{title:'Escalade Beyond Chromatic Lands / Scalata al di là dei terreni cromatici',cluster:'natural-synthetic fibre / monumental bales / architecture-first installation / colour field',period:'2016–2017',summary:'约 6×16×4 m 的 installation 占据 Arsenale 大尺度 wall/corner；bright fibre bales 像 avalanche 向上堆叠，natural/synthetic fibres、cloth、slate、bamboo、sunbrella 与两块 woven panels 共同构成触觉性的 chromatic architecture。',actions:['先测量/阅读 exhibition architecture，再决定 material scale 与 composition，而不是把 studio sculpture 原样搬入','准备大量 pigmented cotton / natural and synthetic fibre bundles / bales','颜色并非简单后染统一色，而通过 fibres 与 pigment / material selection 建立多色块','逐层把 giant soft bales stack / wedge 到 Arsenale wall/corner，利用重力和互相挤压形成 avalanche silhouette','在十余天 installation 中持续调整 density、height、colour adjacency，而非一次按图施工','临近完成时打开剩余 crate，将两块 Guatemala-woven cotton/linen panels 加入，作为“anchor panels”稳定构图','加入 bamboo / slate / cloth / sunbrella 等硬软材料，避免作品只剩同质 fluffy surface','最后重新检查 subtle lighting，让 fibres 的 shadow / colour saturation 与 architecture 协调','让 viewer 从远处先读 monumental colour field，靠近后再读 individual fibre、knot、bundle 的触觉差异'],sourceUrl:hicksProcess,images:[],relations:[rel('展览','Viva Arte Viva — Venice Biennale 2017','Pavilion of Colors / Corderie, Arsenale')]}],awards:[],exhibitions:['Viva Arte Viva — Venice Biennale 2017'],sources:[{label:'ASAC · Sheila Hicks / Escalade',url:hicksAsac},{label:'Alison Jacques · Sheila Hicks / materials and dimensions',url:hicks},{label:'Sheila Hicks interview · Venice installation process',url:hicksProcess},{label:'La Biennale · Artists 2017',url:roster}]}
};
