import type { ArtistArchive, ArchiveProject, ArchiveRelation } from './archiveData';
const rel=(kind:ArchiveRelation['kind'],label:string,detail?:string):ArchiveRelation=>({kind,label,detail});
const project=(p:ArchiveProject)=>p;

export const archiveBatch311:Record<string,ArtistArchive>={
 'carrie-mae-weems':{artistId:'carrie-mae-weems',projectCoverage:'作品级继续深化 Carrie Mae Weems：From Here I Saw What Happened and I Cried、其中具体单件、Roaming、Sea Island Series、Shape of Things。重点记录再摄影、裁切/染色、玻璃喷砂文字、身体表演、田野调查和具体印相材料。',imageCoverage:'MoMA、Met、Guggenheim 均提供对应作品或展览图；MoMA 明确 © Carrie Mae Weems 且 reproduction 需 Art Resource/Scala，Met 两件亦标记 © Carrie Mae Weems、图像不可下载。因此保存官方图像入口与权利状态，本站不复制受限图像；未确认自由授权时 images 留空。',note:'本批把 Weems 从早期家庭摄影继续推进到档案再摄影、身体/建筑表演和民俗田野摄影，并把 From Here 的34件整体结构与若干具体单件分开记录。',projects:[
 project({title:'From Here I Saw What Happened and I Cried',cluster:'archive appropriation / re-photography / text on glass',period:'1995–1996',summary:'Weems 从博物馆和大学档案中选择19、20世纪非洲人与非裔美国人的既有照片，其中包括 Louis Agassiz 1850年委托 Joseph T. Zealy 拍摄、原本被用于种族分类理论的被奴役者肖像。她不是原样展示档案，而是重新摄影、放大、裁切并通过彩色滤镜印制：主体序列大量转为红色，两端以蓝调图像形成书挡式结构；红色照片使用圆形/椭圆形开窗，模拟相机镜头。最终每张 chromogenic print 前覆盖玻璃，Weems 自己的文字以 sand-blasting 直接刻在玻璃上。MoMA 完整作品共34件：28件67.9×55.8cm、4件55.8×67.9cm、2件约110.4×85cm。观看者沿墙移动时，必须同时穿过文字、玻璃、染色档案照片三个层次阅读；作品因此不是“给旧照片加说明”，而是重做档案照片的尺度、颜色、框取方式和发声位置。',actions:['从博物馆/大学档案筛选已有的黑人历史影像，包括1850年 Agassiz/Zealy 奴隶肖像。','重新摄影并放大、裁切原始档案图像，使来源不同的照片进入统一视觉系统。','用彩色滤镜将主体序列印成红调，并以两张蓝调大型图像首尾包围；红色图像使用圆/椭圆开窗。','在覆盖 chromogenic prints 的玻璃上以 sand-blasting 刻入作者文本，使语言成为照片前方真实的物质层。','将34件按序安装成可沿墙阅读的长序列，而非把单幅当作独立摄影。'],sourceUrl:'https://www.moma.org/collection/works/45579',images:[],relations:[rel('材料','chromogenic prints + sand-blasted text on glass','MoMA：28件67.9×55.8cm；4件55.8×67.9cm；2件约110.4×85cm。'),rel('来源','museum/university archives; Agassiz/Zealy daguerreotypes','作品主动处理摄影史中图像被用于种族分类和权力生产的机制。'),rel('展陈版本','MoMA Gallery 211, 2020–2021','MoMA 保留完整墙面安装图，可研究34件作品的序列与空间节奏。'),rel('图片权利','© Carrie Mae Weems / MoMA licensing','MoMA 明确作品及安装图 reproduction 需 Art Resource（北美）或 Scala Archives（其他地区）；本站不复制。')]}),
 project({title:'Drivers / & A Photographic Subject / Some Laughed Long & Hard & Loud / And I Cried',cluster:'From Here — individual works / sequence mechanics',period:'1995–1996',summary:'为避免只把 From Here 当成一个总系列，本节点记录其中具体单件如何形成尺度与节奏差异。Drivers、& A Photographic Subject 等纵向作品均为 chromogenic print + sand-blasted text on glass，约60.7×50.7cm；Some Laughed Long & Hard & Loud 为横向约50.6×60.6cm；结尾 And I Cried 则突然扩大到约110.5×85.1cm。由此可见完整安装并非34张同尺寸图片的机械排列：方向、尺寸、圆形框取、红/蓝色调与文字长度共同调节观看速度。And I Cried 作为大型端点与开端的蓝调皇室女性图像形成结构性书挡，使“见证者”位置包围中间的历史分类影像。',actions:['将不同来源档案统一转成 chromogenic prints，但保留纵向/横向及端点大型图像的尺度差异。','逐件为玻璃喷砂文字，让每幅的语言与被再摄影的历史图像建立特定关系。','用中等尺度红色主体作品形成连续带，再用明显更大的端点作品改变观看节奏。'],sourceUrl:'https://www.moma.org/collection/works/91858',images:[],relations:[rel('具体作品','Drivers','60.7×50.7cm；MoMA 70.1997.22。'),rel('具体作品','Some Laughed Long & Hard & Loud','50.6×60.6cm；横向单件。'),rel('具体作品','And I Cried','约110.5×85.1cm；完整序列的大型结尾作品。'),rel('图片权利','MoMA / © Carrie Mae Weems','具体单件均有官方图像，但 reproduction 受版权与机构授权限制。')]}),
 project({title:'Roaming',cluster:'self-performance / architecture / black-and-white photography',period:'2006',summary:'Roaming 中 Weems 把自己的身体当作一种反复出现的表演工具：她穿长黑裙，背对镜头，站在罗马及周边的纪念性建筑、台阶、拱门和广场前。动作看似极少，但关键在尺度关系——人物被放在巨大国家/宗教建筑之前，以背影占据画面中的观看位置。Guggenheim 对该系列的说明明确指出，她把自己的身体作为进入并挑战这些权力空间的方法。因此摄影不是旅行纪实，而是先选择具有政治/历史权威的建筑空间，再进行身体定位和面向建筑的现场表演，最后以大型黑白摄影让观众从她背后共享同一视线。',actions:['在罗马及周边选择具有国家、宗教和历史权力象征的纪念性建筑。','艺术家本人穿长黑裙进入现场，通常背对镜头、面对建筑，形成重复的身体姿态。','通过人物与宏大建筑的尺度差制造“个体面对制度性空间”的视觉结构。','把现场身体行为转化为大型黑白摄影；观众从人物背后观看，近似被带入她的位置。'],sourceUrl:'https://www.guggenheim.org/articles/checklist/challenging-edifice-carrie-mae-weems-discusses-series-roaming',images:[],relations:[rel('方法','artist body as performance device','Weems 明确谈到用自己的身体带领观众进入并挑战建筑空间。'),rel('展览','Carrie Mae Weems: Three Decades of Photography and Video — Guggenheim — 2014','官方回顾展展示 Roaming 大型黑白照片。'),rel('图片权利','Guggenheim / artist copyright','官方文章含作品/展览图；未确认可自由再发布，本站仅保存入口。')]}),
 project({title:'Untitled — Sea Island Series',cluster:'folklore fieldwork / landscape / vernacular trace',period:'1992; printed 2000',summary:'Sea Island Series 来自 Weems 对 Georgia 与 South Carolina 海岸 Gullah 社群的田野关注。她具有民俗学训练，拍摄的是当地仍可见的非洲文化痕迹，而非把人物当作异域肖像对象。Met 收藏的这张 Untitled 拍到悬挂在树间的床垫弹簧：第一眼像人为介入风景的雕塑，但馆方说明其用途与捕捉/阻挡邪灵的民间实践有关。作品最终以 gelatin silver print 制作，71.1×71.8cm，1992拍摄、2000印制。这里摄影动作是寻找并记录日常景观中不容易被外来观看者识读的物质痕迹，再通过系列与民俗研究把物件从“奇怪景物”重新放回文化实践。',actions:['在美国东南沿海 Gullah 社群进行与民俗、历史记忆相关的现场观察和摄影。','不搭建弹簧装置，而是记录已经存在于当地环境中的文化性物件/痕迹。','以方形构图和 gelatin silver print 把树木、弹簧与环境压缩成可细看物质关系的摄影对象。','通过系列语境解释外来观众可能误读为“艺术干预”的景观痕迹。'],sourceUrl:'https://www.metmuseum.org/art/collection/search/283770',images:[],relations:[rel('材料','gelatin silver print','Met：71.1×71.8cm；1992，printed 2000。'),rel('田野对象','Gullah community / Sea Islands','关注非洲文化在隔离地理环境中保留下来的可见痕迹。'),rel('图片权利','© Carrie Mae Weems / The Met','Met 明确图像不可放大、全屏或下载；版权受限，本站不复制。')]}),
 project({title:'Shape of Things (female)',cluster:'Africa / architectural study / gendered form',period:'1993; printed 2000',summary:'Weems 1993年首次前往非洲期间在 Mali 的 Djenné 拍摄这件建筑研究。她把当地古老建筑/粮仓立面正面化、平面化地收入画面，并从立面的形体联想到女性身体。与 Roaming 中让自己的身体进入建筑前方不同，这里人物消失，建筑本身成为身体隐喻。Met 馆藏为 gelatin silver print，71.1×71.8cm，1993拍摄、2000印制。它显示 Weems 的“建筑与权力/身体”兴趣并非突然出现在2006年：更早的非洲摄影已经通过正面取景、方形银盐输出和形式类比，把建筑作为文化身体来观看。',actions:['在 Mali Djenné 实地拍摄古老建筑/粮仓立面。','通过正面、集中式取景强调建筑表面的凸起、孔洞和整体轮廓，而非把建筑作为城市风景背景。','以 gelatin silver print 制作方形实体照片，后于2000年印制馆藏版本。'],sourceUrl:'https://www.metmuseum.org/art/collection/search/283769',images:[],relations:[rel('材料','gelatin silver print','Met：71.1×71.8cm；frame 72.4×72.4cm。'),rel('地点','Djenné, Mali','1993年 Weems 首次非洲旅行期间制作。'),rel('实践关系','architecture as body / later Roaming','从建筑形体的身体隐喻延伸到后来艺术家身体与纪念性建筑的直接对峙。'),rel('图片权利','© Carrie Mae Weems / The Met','馆藏页明确版权受限且图像不可下载，本站仅记录官方入口。')]})
 ],exhibitions:['Carrie Mae Weems: Three Decades of Photography and Video — Solomon R. Guggenheim Museum — 2014','Carrie Mae Weems’s From Here I Saw What Happened and I Cried — MoMA Gallery 211 — 2020–2021'],sources:[{label:'MoMA — From Here I Saw What Happened and I Cried',url:'https://www.moma.org/collection/works/45579'},{label:'MoMA — Drivers',url:'https://www.moma.org/collection/works/91858'},{label:'MoMA — Some Laughed Long & Hard & Loud',url:'https://www.moma.org/collection/works/91866'},{label:'MoMA — And I Cried',url:'https://www.moma.org/collection/works/91870'},{label:'Guggenheim — Challenging the Edifice / Roaming',url:'https://www.guggenheim.org/articles/checklist/challenging-edifice-carrie-mae-weems-discusses-series-roaming'},{label:'The Met — Untitled, Sea Island Series',url:'https://www.metmuseum.org/art/collection/search/283770'},{label:'The Met — Shape of Things (female)',url:'https://www.metmuseum.org/art/collection/search/283769'}]}
};
