import type { ArtistArchive, ArchiveRelation } from './archiveData';
const rel = (kind: ArchiveRelation['kind'], label: string, detail?: string): ArchiveRelation => ({ kind, label, detail });

const steyerl='https://www.labiennale.org/en/art/2019/partecipants/hito-steyerl';
const douglas='https://www.labiennale.org/en/art/2019/partecipants/stan-douglas';
const kang='https://www.labiennale.org/en/art/2019/partecipants/suki-seokyeong-kang';
const nkanga='https://www.labiennale.org/en/art/2019/partecipants/otobong-nkanga';
const epaminonda='https://www.labiennale.org/en/art/2019/partecipants/haris-epaminonda';
const awards='https://www.labiennale.org/en/news/biennale-arte-2019-official-awards';
const darling='https://www.labiennale.org/en/art/2019/partecipants/jesse-darling';

export const archiveBatch106: Record<string, ArtistArchive> = {
  'venice-hito-steyerl': {
    artistId:'venice-hito-steyerl', projectCoverage:'1 个 AI / military-industry / speculative-future corpus 已建立深档案 · 2019', imageCoverage:'0 / 1 项目暂不使用不稳定外链图像', note:'官方 2019 页面重点不是单件标题，而是 Steyerl 对 AI 应用、corporate power 与 military industry 的批判语境。这里按 Venice 2019 corpus 建档，避免把未核实作品名强行塞入。',
    projects:[{title:'AI / corporate-military future — Venice 2019 corpus',cluster:'AI critique / corporate power / speculative future',period:'2019',summary:'Steyerl 将当时迅速被艺术市场合法化的 AI 放回 corporation、military industry 与缺乏伦理/法律框架的现实中讨论，并借 Jules Verne、Philip K. Dick、Leonardo 等历史想象把“未来”变成政治问题。',actions:['把 AI art hype 放回 corporate / military infrastructure 中分析','追踪 technology development 与 economic interest 的关系','将 legal / ethical vacuum 作为作品问题而非技术背景','并置 science fiction literary references 与 art-history references','让 speculative future 指向已经改变当下生活条件的技术现实'],sourceUrl:steyerl,images:[],relations:[rel('展览','May You Live In Interesting Times — Venice Biennale 2019','Central Pavilion / Arsenale')]}], awards:[], exhibitions:['May You Live In Interesting Times — Venice Biennale 2019'], sources:[{label:'La Biennale · Hito Steyerl 2019',url:steyerl}]
  },

  'venice-stan-douglas': {
    artistId:'venice-stan-douglas', projectCoverage:'1 个 speculative-history / cinematic-restaging 方法节点已建立深档案 · 2010s–2019', imageCoverage:'0 / 1 项目暂不使用不稳定外链图像', note:'当前先把 Douglas 在 Venice 2019 官方页明确的核心方法做深：照片和电影都从长期 research、set、actor、lighting 与 restaging 出发，把历史“如果当时走了另一条路”变成可见场景。',
    projects:[{title:'Speculative histories / cinematic restaging practice',cluster:'historical research / staged photography / alternate history',period:'2010s–2019',summary:'Douglas 选择历史关键节点，研究其现实细节后重新搭景、选角和布光，再通过 film / video / photograph 想象事件本可采取的另一种路径。',actions:['从具体 historical turning point 开始长期 archival / contextual research','重建 set 与 period details，而非只使用 found image','选择 actors 重新表演 historical situation','以 meticulous cinematic lighting 构成 photograph / film scene','将 photograph 理解为“没有运动图像的电影”并使用同样 production logic','让 alternate possibility 与 documented history 同时存在'],sourceUrl:douglas,images:[],relations:[rel('展览','May You Live In Interesting Times — Venice Biennale 2019','Central Pavilion / Arsenale')]}], awards:[], exhibitions:['May You Live In Interesting Times — Venice Biennale 2019'], sources:[{label:'La Biennale · Stan Douglas 2019',url:douglas}]
  },

  'venice-suki-seokyeong-kang': {
    artistId:'venice-suki-seokyeong-kang', projectCoverage:'1 个 painting-sculpture-video / activation corpus 已建立深档案 · 2010s–2019', imageCoverage:'0 / 1 项目暂不使用不稳定外链图像', note:'Kang 的 practice 同时包含 painting、sculpture、video 与她称为 activation 的现场动作；重点不是媒介并列，而是用 Korean cultural heritage 与 personal history 重构 individual agency 的空间。',
    projects:[{title:'Activation / politicised-arena corpus — Venice 2019',cluster:'painting + sculpture + video / activation / individual agency',period:'2010s–2019',summary:'作品把不同媒介组织成可被身体激活的场域，借 Korean cultural heritage 与个人历史重新想象 ideological structure，使 individual stakeholder 能在 present space-time 中表达和执行 agency。',actions:['将 painting、sculpture、video 作为同一 spatial system 组织','设计需要 bodily activation / movement 才完整的观看关系','从 Korean cultural heritage 提取 structure 而非做传统图像复刻','将 personal history 与 collective ideological structure 并置','让 individual agency 通过站位、移动、关系和尺度被空间化'],sourceUrl:kang,images:[],relations:[rel('展览','May You Live In Interesting Times — Venice Biennale 2019','Central Pavilion / Arsenale')]}], awards:[], exhibitions:['May You Live In Interesting Times — Venice Biennale 2019'], sources:[{label:'La Biennale · Suki Seokyeong Kang 2019',url:kang}]
  },

  'venice-otobong-nkanga': {
    artistId:'venice-otobong-nkanga', projectCoverage:'1 个 mineral-energy-body exchange 核心方法节点已建立深档案 · 2010s–2019', imageCoverage:'0 / 1 项目暂不使用不稳定外链图像', note:'Nkanga 的 2019 核心不是单一材料，而是追踪 mineral、energy、goods、people 如何跨土地与身体移动；每个 object/action 都被放进 extraction、trade、colonial impact 与 identity change 的关系网。',
    projects:[{title:'Land / body / trade exchange corpus — Venice 2019',cluster:'mineral movement / colonial trade / relational installation',period:'2010s–2019',summary:'Nkanga 把矿物、能源、商品和人的流动看成同一 network，强调没有任何 object / action 是孤立的；African identity 也因此必须连同 colonial impact、trade 与 cultural exchange 一起理解。',actions:['从 mineral / raw material 的 extraction 与 circulation 路径出发研究','把 energy、goods 与 human migration 放在同一 exchange network 中','追踪 colonial history 如何留在 contemporary material circulation','跨 drawing / textile / installation / performance 等媒介保持关系逻辑','避免把 identity 处理为静态民族标签，转而呈现不断交换与变化的状态'],sourceUrl:nkanga,images:[],relations:[rel('奖项','Special Mention — Venice Biennale 2019','for ongoing exploration of land, body and time'),rel('展览','May You Live In Interesting Times — Venice Biennale 2019','Central Pavilion / Arsenale')]}], awards:['Special Mention — Venice Biennale 2019'], exhibitions:['May You Live In Interesting Times — Venice Biennale 2019'], sources:[{label:'La Biennale · Otobong Nkanga 2019',url:nkanga},{label:'La Biennale · Official Awards 2019',url:awards}]
  },

  'venice-haris-epaminonda': {
    artistId:'venice-haris-epaminonda', projectCoverage:'1 个 found-object constellation / compressed-memory installation 核心方法节点已建立深档案 · 2019', imageCoverage:'0 / 1 项目暂不使用不稳定外链图像', note:'Epaminonda 的方法不是“旧物拼贴”这么简单：sculpture、pottery、book、photograph 被按 qualia 选择，原本历史并不被解释清楚，而是在新的 constellation 中以 fragment memory 的方式继续作用。',
    projects:[{title:'Found-object constellations — Venice 2019 corpus',cluster:'found sculpture / pottery / book / photograph / loose meaning-web',period:'2019',summary:'各种 found objects 被极度克制地组合，历史与 personal meaning 不被说明，而通过 material presence、距离、colour 与形式关系形成 loose web。',actions:['搜集 sculpture、pottery、book、photograph 等既有 objects','优先根据 object qualia / experiential quality 选择而非完整 provenance story','用距离、scale、colour 与空白组织 constellation','保留 historical / personal meaning 的不完整和未知','让 objects 在 installation 中被轻微 shift，既保留旧痕迹又变成新关系'],sourceUrl:epaminonda,images:[],relations:[rel('奖项','Silver Lion for a Promising Young Participant — Venice Biennale 2019','jury cited constellations of images, objects, text, forms and colours'),rel('展览','May You Live In Interesting Times — Venice Biennale 2019','Central Pavilion / Arsenale')]}], awards:['Silver Lion — Venice Biennale 2019'], exhibitions:['May You Live In Interesting Times — Venice Biennale 2019'], sources:[{label:'La Biennale · Haris Epaminonda 2019',url:epaminonda},{label:'La Biennale · Official Awards 2019',url:awards}]
  },

  'venice-jesse-darling': {
    artistId:'venice-jesse-darling', projectCoverage:'1 个 non-macho / wounded-assemblage sculpture 方法节点已建立深档案 · 2010s–2019', imageCoverage:'0 / 1 项目暂不使用不稳定外链图像', note:'Darling 的低价材料、摇晃结构和受伤般身体感并非“poor material aesthetic”，而是对 monument、hard labour、heroic gesture 与 ableist machismo 的系统反写。',
    projects:[{title:'Non-macho wounded assemblages — Venice 2019 corpus',cluster:'low-cost material / unstable body / anti-monument',period:'2010s–2019',summary:'小型日常物件被收集并组成 wounded、skittish、unsteady 的 assemblages，既像受伤身体又坚持活着。neurological disease 限制右臂后，Darling 更明确放弃 macho sculpture 对力量与“大手势”的依赖。',actions:['收集 low-cost everyday materials 与 small objects','以 narrative formulation 组合而非追求 monumental single form','故意保留 bent / wounded / unstable structural condition','在右臂功能受限后学习用 left hand drawing 并改变制作方式','将 hard work / heroic gesture / monumentality 作为需要被拆解的 sculptural ideology','让脆弱结构承担 bodily poignancy，而不把 disability 变成说明性主题'],sourceUrl:darling,images:[],relations:[rel('展览','May You Live In Interesting Times — Venice Biennale 2019','Central Pavilion / Arsenale')]}], awards:[], exhibitions:['May You Live In Interesting Times — Venice Biennale 2019'], sources:[{label:'La Biennale · Jesse Darling 2019',url:darling}]
  }
};
