import type { ArtistArchive, ArchiveRelation } from './archiveData';

const rel=(kind:ArchiveRelation['kind'],label:string,detail?:string):ArchiveRelation=>({kind,label,detail});

export const archiveBatch260:Record<string,ArtistArchive>={
  'sophie-calle':{
    artistId:'sophie-calle',
    projectCoverage:'继续把“规则—调查—文本/摄影—空间化”的方法拆到 L’Hôtel 与 Douleur exquise：补齐进入现场的实际身份、记录结构、装置组成、时间延迟与 Centre Pompidou 收藏/策展关系。',
    imageCoverage:'Centre Pompidou 为 L’Hôtel 与 Douleur exquise 提供官方馆藏图、安装信息和详细组件记录；图像版权为 ADAGP/相关摄影者，故只保留官方入口，不复制受限图像。',
    note:'Calle 的作品不是把私人生活直接展示出来，而是先设计一个可执行的协议，再让现实在协议中产生材料。L’Hôtel 把“他人的缺席”变成调查对象；Douleur exquise 则把自己的痛苦先存档、延迟近二十年，再通过重复叙述和他人证词重新加工。',
    projects:[
      {title:'L’Hôtel',cluster:'rule-based investigation / hotel / absence / text-photography / archive',period:'1981–1983',summary:'Calle 为进入私人空间并非偷偷潜入，而是在等待约一年后取得威尼斯一家酒店三周的临时女佣工作。她利用清扫客房的合法工作时间观察住客离开后的痕迹：床铺、衣物、行李、垃圾、浴室用品和其他私人遗留物，并以彩色房间照片、黑白细节照片和近似调查报告的文字共同记录。Centre Pompidou 馆藏版本由15个元素组成：7组双联结构加一段艺术家文本；每组上部结合1张彩色照片与文字，下部则由不同数量的黑白照片构成。作品因此并不是“偷窥照片”集合，而是一套关于缺席者的证据编排：物件看似提供大量信息，却始终无法真正抵达陌生人的主体。',actions:['经过长期申请取得威尼斯酒店三周替班女佣身份，以工作制度获得进入客房的实际权限。','在住客外出、房间等待清扫时观察床铺、衣物、行李和生活用品留下的痕迹。','同时制作房间整体彩色照片与物件/细节黑白照片。','以带有警方调查报告语气、同时夹杂个人判断的文字记录每天观察。','把图像和文字重新编排为7组双联结构与说明文本，使“证据很多但仍无法认识他人”成为作品结构。'],sourceUrl:'https://www.centrepompidou.fr/en/ressources/oeuvre/cqr9Md',images:[],relations:[rel('收藏','Centre Pompidou / MNAM-CCI','Purchased 2000; Cabinet de la photographie; inventory AM 2000-9 (1-8).'),rel('策展/研究','Christine Macel','Centre Pompidou collection analysis situates L’Hôtel within Calle’s rule-based investigations, surveillance and the recurring motif of the bed.'),rel('方法谱系','Les Dormeurs → Suite vénitienne → L’Hôtel','bed/sleep observation → following a stranger → entering strangers’ absent rooms: progressively different protocols for approaching an unknowable other.')]},
      {title:'Douleur exquise',cluster:'autobiographical archive / delayed narration / testimony / installation / repetition',period:'1984–2003',summary:'作品源于1984年的一次分手，却直到近二十年后才形成成熟装置。Centre Pompidou 记录的完整版本分三段空间：第一部分用92件框装照片、信件与文件重构艺术家赴中国旅行以及与恋人分离的倒计时；第二部分重建她原计划与恋人在新德里会面的酒店房间——她在那里通过红色小电话得知分手；第三部分用72组双联把 Calle 反复讲述自己的痛苦，与她向其他人征集的“你最痛苦的时刻”并置。文字被绣在亚麻布上，随着重复逐渐淡化，叙述本身成为一种计量痛苦消退的形式。Centre Pompidou 所藏部分为第三段的9组可拆分 polyptychs。',actions:['把1984年旅行期间的照片、信件、文件等保存为尚未立即转化为作品的个人档案。','以“痛苦发生前多少天”的倒计时结构重新组织旅途材料。','把新德里酒店房间作为创伤发生地点重新空间化，并保留红色电话这一叙事物件。','向不同的人询问其最痛苦经历，把私人分手与他人的痛苦证词并列。','让自己的同一段叙述在72组双联中重复，并通过刺绣文字色彩/强度的逐渐消退把时间和心理变化转成视觉结构。','直到2003年前后才把近二十年前事件正式组织为大型展览作品，使“延迟处理”本身成为方法。'],sourceUrl:'https://www.centrepompidou.fr/en/ressources/oeuvre/crb55Bq',images:[],relations:[rel('机构/首个法语大型版本','Centre Pompidou · M’as-tu vue ?, 2003–04','The French version was developed for Calle’s major Centre Pompidou exhibition after an earlier Japanese version.'),rel('收藏','Centre Pompidou','Donation by Caisse des dépôts et consignations, 2004; collection contains nine polyptych groups from the third section.'),rel('方法','event → archive → long delay → reconstruction → repeated narration','Unlike immediate diary confession, the event is stored, revisited and transformed through formal repetition and comparison with other people’s testimony.')]}
    ],
    awards:[],
    exhibitions:['Sophie Calle: M’as-tu vue ? — Centre Pompidou, Paris, 2003–04','Sophie Calle — Centre Pompidou Málaga, 2021–22'],
    sources:[{label:'Centre Pompidou · L’Hôtel',url:'https://www.centrepompidou.fr/en/ressources/oeuvre/cqr9Md'},{label:'Centre Pompidou · Douleur exquise',url:'https://www.centrepompidou.fr/en/ressources/oeuvre/crb55Bq'},{label:'Centre Pompidou · M’as-tu vue ?',url:'https://www.centrepompidou.fr/fr/programme/agenda/evenement/ck46ojq'}]
  },
  'taryn-simon':{
    artistId:'taryn-simon',
    projectCoverage:'深化 An American Index of the Hidden and Unfamiliar 与 The Innocents：补齐“获得进入权—大画幅摄影—长说明文本—制度分类”的工作机制，并把早期误判研究与后来制度/档案项目接成演变链。',
    imageCoverage:'Whitney Museum 提供 An American Index 展览档案、艺术家页及具体馆藏作品图；作品版权归艺术家，故记录官方入口而不复制受限图像。',
    note:'Simon 的“冷静分类学”并不是形式先行。她经常先面对一个制度问题——谁能进入、谁能被看见、什么能作为证据——再建立极度整齐的摄影与文字系统。越整齐的分类，越容易暴露现实中无法被分类、证明或控制的部分。',
    projects:[
      {title:'An American Index of the Hidden and Unfamiliar',cluster:'access / hidden institutions / large-format photography / text / taxonomy',period:'2007',summary:'Simon 把美国社会中通常不可见或难以进入的地点与对象整理成一个“索引”：题材跨越科学、政府、医疗、娱乐、自然、安全与宗教，包括核废料设施、冬眠黑熊、选择性近亲繁殖的白虎等。Whitney 将项目概括为对“有权进入者/无权进入者”之间差异的研究。她在条件允许时使用大画幅 view camera，以高度清晰、近乎行政记录般的视觉方式拍摄，并配以解释机构、地点和进入条件的文字。关键并非偷拍秘密，而是通过申请、协商和实际获准进入，把权限本身转成项目的隐形材料。',actions:['建立跨政府、科学、医疗、宗教、娱乐与安全系统的不可见对象清单。','联系相关机构、申请拍摄并处理拒绝/许可，使 access 成为生产过程的一部分。','在条件允许时使用 large-format view camera，保持高度清晰、正面和克制的视觉语言。','记录对象的精确名称、地点、机构背景及其为何通常不可见。','把摄影与长说明文字并置，使漂亮/陌生的图像不能脱离制度背景独立消费。','通过统一版式把异质对象转成“美国隐秘结构”的分类索引，同时暴露索引无法真正穷尽社会系统。'],sourceUrl:'https://whitney.org/exhibitions/taryn-simon',images:[],relations:[rel('个展','Whitney Museum of American Art','Mar 9–Jun 24, 2007; institutional presentation of An American Index.'),rel('收藏案例','White Tiger (Kenny)','Whitney collection: 2007 chromogenic print, from An American Index; selective inbreeding at Turpentine Creek Wildlife Refuge.'),rel('方法','access as medium','The project turns permission, institutional opacity and differential access into part of photographic production rather than treating location as a neutral subject.')]},
      {title:'The Innocents',cluster:'wrongful conviction / eyewitness identification / DNA exoneration / photography as evidence',period:'2002',summary:'早期项目聚焦因暴力犯罪被判刑、后来通过DNA证据平反的人。Whitney 以 Larry Mayes 为例：受害者依据照片指认他为袭击者之一，他因此入狱近二十年，尽管没有生物证据把他与犯罪联系起来；该作品属于由50件构成的 The Innocents。项目的重要性在于 Simon 不是只把相机当成替无辜者“重新作证”的工具，而是反过来调查摄影如何曾进入警察识别、目击证词和司法事实生产，并导致真实后果。',actions:['寻找已被判刑、后经DNA证据平反的案件与当事人。','研究案件中目击者、警方照片识别和其他视觉证据如何参与定罪。','重新拍摄平反者，使新的艺术摄影与曾参与司法识别的照片制度形成冲突。','通过人物信息和案件文本把肖像重新嵌回司法过程，而不是把被摄者抽象成“受害者形象”。','把50件个案累积成关于摄影、记忆、识别与证据可靠性的系统性问题。'],sourceUrl:'https://whitney.org/artists/9743',images:[],relations:[rel('作品关系','Larry Mayes / The Innocents','Whitney artist record identifies Mayes as one of the fifty works and recounts the photographic identification and later DNA exoneration.'),rel('演变','The Innocents → An American Index → A Living Man Declared Dead','misidentification/evidence → institutional access/hidden systems → bloodline taxonomy: Simon progressively expands from failures of a single evidentiary image to the larger systems that organize knowledge.')]}
    ],
    awards:[],
    exhibitions:['Taryn Simon: An American Index of the Hidden and Unfamiliar — Whitney Museum of American Art, 2007'],
    sources:[{label:'Whitney · Taryn Simon',url:'https://whitney.org/artists/9743'},{label:'Whitney · An American Index of the Hidden and Unfamiliar',url:'https://whitney.org/exhibitions/taryn-simon'},{label:'Whitney · White Tiger (Kenny)',url:'https://whitney.org/collection/works/29733'}]
  }
};
