import type { ArtistArchive, ArchiveImage, ArchiveRelation } from './archiveData';

const img = (url: string, title: string, credit: string, sourceUrl: string, sourceLabel: string): ArchiveImage => ({ url, title, credit, sourceUrl, sourceLabel });
const rel = (kind: ArchiveRelation['kind'], label: string, detail?: string): ArchiveRelation => ({ kind, label, detail });

export const additionalArtistArchives: Record<string, ArtistArchive> = {
  'daisuke-yokota': {
    artistId: 'daisuke-yokota',
    projectCoverage: '17 个主要作品 / 出版项目已索引 · 2010–2022',
    imageCoverage: '4 个项目已建立可追溯图像入口',
    note: 'Yokota 的作品经常在系列、摄影书、暗房实验、现场表演与装置之间变形，因此这里按“可辨认的作品 / 出版项目”归档，而不是假装每个唯一版 print 都能从公开网络完整列出。书目依据 Casemore Gallery bibliography，并用 Foam 展览资料校正重要节点。',
    projects: [
      { title: 'Water Side', cluster: 'Early books', period: '2010', summary: '早期自出版项目，已经显示他通过书籍组织摄影而不是只依靠单幅作品。', actions: ['自主编辑', '自出版', '以摄影书建立系列结构'], sourceUrl: 'https://casemoregallery.com/artists/45-daisuke-yokota/bibliography/', images: [], relations: [rel('出版', 'Water Side', 'self-published, 2010')] },
      { title: 'Back Yard', cluster: 'Early books', period: '2011', summary: '早期自出版摄影书之一，与 Site、Expanded Retina 等共同形成其反复处理既有图像的前史。', actions: ['拍摄日常环境', '编辑成书', '建立重复与颗粒语言'], sourceUrl: 'https://casemoregallery.com/artists/45-daisuke-yokota/bibliography/', images: [], relations: [rel('出版', 'Back Yard', 'self-published, 2011')] },
      { title: 'Site', cluster: 'Site / Cloud genealogy', period: '2011–2013', summary: 'Site 是后来 Site/Cloud 展览与书籍脉络的重要前身。', actions: ['重复使用早期图像', '暗房处理', '书籍化'], sourceUrl: 'https://casemoregallery.com/artists/45-daisuke-yokota/bibliography/', images: [], relations: [rel('出版', 'Site', 'self-published, 2011')] },
      { title: 'Nocturnes', cluster: 'Rephotography / darkroom', period: '2012–2013', summary: '通过重拍已有印相、改变显影时间、扫描并在 Photoshop 中叠加，制造梦境般的黑白图像。', actions: ['重拍已有照片', '改变胶片显影时间', '扫描', '数字叠加'], sourceUrl: 'https://www.foam.org/artists/daisuke-yokota', images: [img('https://www.foam.org/_next/image?q=80&url=https%3A%2F%2Fa.storyblok.com%2Ff%2F113697%2F1772x1181%2Fd1624c1bfc%2Flr_daisuke_yokota_foam_by_cvdk_01.jpg&w=1920', 'Daisuke Yokota at Foam — process / installation context', '© Daisuke Yokota / Foam', 'https://www.foam.org/artists/daisuke-yokota', 'Foam')], relations: [rel('出版', 'AM Projects: Nocturnes', 'Dienacht Publishing, 2012'), rel('奖项', 'Foam Talent', '2013')] },
      { title: 'Site / Cloud', cluster: 'Site / Cloud genealogy', period: '2013–2014', summary: '把强反差、幽灵般人物和近乎无时间感的云层并置；处理过程和图像干预成为观看重点。', actions: ['模拟 / 数字反复处理', '书籍编辑', '展览空间编排'], sourceUrl: 'https://www.foam.org/events/daisuke-yokota-site-cloud', images: [], relations: [rel('出版', 'site/cloud', 'Artbeat Publishers, 2013'), rel('奖项', 'Outset | Unseen Exhibition Fund', 'winner, 2013'), rel('展览', 'Foam, Amsterdam', 'solo exhibition, 2014')] },
      { title: 'Corpus', cluster: 'Books / body', period: '2014', summary: '2014 年集中出版期的重要摄影书之一，延续身体、颗粒、失真和重复处理。', actions: ['图像再处理', '摄影书 sequence'], sourceUrl: 'https://casemoregallery.com/artists/45-daisuke-yokota/bibliography/', images: [], relations: [rel('出版', 'Corpus', 'Artbeat Publishers, 2014')] },
      { title: 'Vertigo', cluster: 'Books / abstraction', period: '2014', summary: '把影像的不稳定、模糊与复制痕迹压缩进摄影书结构，是其国际出版脉络的重要节点。', actions: ['重复复制', '暗房 / 数字处理', '摄影书编辑'], sourceUrl: 'https://casemoregallery.com/artists/45-daisuke-yokota/bibliography/', images: [], relations: [rel('出版', 'Vertigo', 'Newfave Books, 2014'), rel('奖项', 'Paris Photo–Aperture PhotoBook Awards', 'nominated, 2014')] },
      { title: 'Linger', cluster: 'Books', period: '2014', summary: '与 Vertigo 同期出版，继续把摄影的意义放在图像之间的残留、迟滞和连续性上。', actions: ['摄影书 sequence', '图像再处理'], sourceUrl: 'https://casemoregallery.com/artists/45-daisuke-yokota/bibliography/', images: [], relations: [rel('出版', 'Linger', 'Akina Books, 2014')] },
      { title: 'Taratine', cluster: 'Color / transformed image', period: '2015', summary: '进入更明显的色彩实验阶段，同时保留处理链条留下的人工痕迹。', actions: ['色彩实验', '图像再加工', '书籍化'], sourceUrl: 'https://www.foam.org/events/winner-foam-paul-huf-award-2016', images: [], relations: [rel('出版', 'Taratine', 'Session Press 07, 2015'), rel('奖项', 'Foam Paul Huf Award jury presentation', '2016')] },
      { title: 'Color Photographs', cluster: 'Color / transformed image', period: '2015', summary: '把 Yokota 常见的颗粒、失真与重复处理带进彩色摄影。', actions: ['彩色材料实验', '模拟 / 数字处理', '摄影书'], sourceUrl: 'https://www.foam.org/events/winner-foam-paul-huf-award-2016', images: [], relations: [rel('出版', 'Color Photographs', 'Harper’s Books / Flying Books, 2015')] },
      { title: 'Immerse', cluster: 'Books / immersion', period: '2015', summary: '以书籍作为沉浸式观看结构，延续 Yokota 对连续视觉和物理出版物的重视。', actions: ['摄影书编辑', '印刷材料控制'], sourceUrl: 'https://casemoregallery.com/artists/45-daisuke-yokota/bibliography/', images: [], relations: [rel('出版', 'Immerse', 'Akina Books, 2015')] },
      { title: 'Cell A/B/C/D', cluster: 'Serial publishing', period: '2015', summary: '四册式出版项目，把重复、变体和分册结构本身作为作品组织方式。', actions: ['分册出版', '重复 / 变体', '系列编辑'], sourceUrl: 'https://casemoregallery.com/artists/45-daisuke-yokota/bibliography/', images: [], relations: [rel('出版', 'Cell A/B/C/D', 'Twelve Books & Daisuke Yokota, 2015')] },
      { title: 'Matter / Burn Out', cluster: 'Material photography', period: '2016–2017', summary: '摄影不再主要围绕“图像内容”，而是转向胶片、印相纸、化学处理、体积和现场制作。', actions: ['无相机曝光', '化学处理', '蜡封印相', '现场打印 / 投影', '空间装置'], sourceUrl: 'https://www.foam.org/events/daisuke-yokota', images: [img('https://www.foam.org/_next/image?q=80&url=https%3A%2F%2Fa.storyblok.com%2Ff%2F113697%2F1772x1181%2Fd1624c1bfc%2Flr_daisuke_yokota_foam_by_cvdk_01.jpg&w=1920', 'Matter — installation view', 'Photo Christian van der Kooy / Foam', 'https://www.foam.org/events/daisuke-yokota', 'Foam')], relations: [rel('出版', 'Matter / Burn Out', 'Artbeat Publishers, 2016'), rel('奖项', 'Foam Paul Huf Award', 'winner 2016'), rel('展览', 'Matter, Foam', '2017')] },
      { title: 'Inversion', cluster: 'Material / publication variants', period: '2016–2017', summary: '以不同城市版本持续出版，强调一个作品可在版本、材料和流通过程中发生变化。', actions: ['多版本出版', '图像反转 / 处理', '地域版变体'], sourceUrl: 'https://casemoregallery.com/artists/45-daisuke-yokota/bibliography/', images: [], relations: [rel('出版', 'Inversion — Arles / New York / Paris editions', 'Akio Nagasawa Publishing, 2016–2017')] },
      { title: 'Spew I–V', cluster: 'Collective / performance publishing', period: '2016', summary: '与 collective 实践相连的多册自出版项目，显示他的作品并不只存在于个人摄影书或白盒子展览。', actions: ['集体制作', '自出版', '连续版本'], sourceUrl: 'https://casemoregallery.com/artists/45-daisuke-yokota/bibliography/', images: [], relations: [rel('出版', 'Spew I/II/III/IV/V', 'self-published, 2016')] },
      { title: 'Sediments', cluster: 'Later material practice', period: '2022', summary: '后期展览节点之一，可与 Matter 之后摄影材料逐渐脱离传统平面图像的路径连续阅读。', actions: ['材料摄影', '空间展示'], sourceUrl: 'https://casemoregallery.com/artists/45-daisuke-yokota/exhibitions/', images: [], relations: [rel('展览', 'Daisuke Yokota: Sediments', 'Casemore Gallery, 2022')] },
      { title: 'Performance / Effect Twin collaborations', cluster: 'Collaborative performance', period: '2015', summary: '与 Hiroshi Takizawa 等人的现场合作把摄影制作推向 performance 和现场出版。', actions: ['合作表演', '现场制作', '自出版'], sourceUrl: 'https://casemoregallery.com/artists/45-daisuke-yokota/bibliography/', images: [], relations: [rel('出版', 'Effect Twin 1 / 2', 'performance publications, 2015')] }
    ],
    awards: ['2016 Foam Paul Huf Award — winner', '2015 Photo London John Kobal Residency Award — winner', '2014 Paris Photo–Aperture PhotoBook Awards — Vertigo nominated', '2013 Outset | Unseen Exhibition Fund — winner', '2013 Foam Talent', '2010 1_Wall — Grand Prix', '2008 Canon New Cosmos of Photography — Honorable Mention'],
    exhibitions: ['Site/Cloud — Foam, 2014', 'Matter — Foam, 2017', 'Shashin: Photography from Japan — New York, 2015', 'In the Wake: Japanese Photographers Respond to 3/11 — MFA Boston, 2015', 'Another Language — Rencontres d’Arles, 2015', 'Sediments — Casemore Gallery, 2022'],
    sources: [{ label: 'Foam artist archive', url: 'https://www.foam.org/artists/daisuke-yokota' }, { label: 'Foam — Site/Cloud', url: 'https://www.foam.org/events/daisuke-yokota-site-cloud' }, { label: 'Foam — Matter', url: 'https://www.foam.org/events/daisuke-yokota' }, { label: 'Casemore bibliography', url: 'https://casemoregallery.com/artists/45-daisuke-yokota/bibliography/' }, { label: 'Casemore biography', url: 'https://casemoregallery.com/artists/45-daisuke-yokota/biography/' }]
  },
  'lebohang-kganye': {
    artistId: 'lebohang-kganye',
    projectCoverage: '16 / 16 官网 Works 目录已收录',
    imageCoverage: '4 / 16 项目已建立图像档案入口',
    note: '项目目录严格按 Lebohang Kganye Studio 当前 Works 列表收录。她的大量作品本身包含多件 print、cut-out、film still 和 installation component，因此“项目全”不等于“每一件唯一物件都已入库”；图像层继续按官方页面逐件补。',
    projects: [
      { title: 'Ke Lefa Laka: Her-story', cluster: 'Family archive', period: '2013', summary: '母亲去世后，Kganye 回到家庭相册，以自己的身体进入母亲过去的照片，让“幽灵”成为和家族记忆共处的方法。', actions: ['家庭档案研究', '自我表演', '重新进入旧照片', '打印 / 叠置'], sourceUrl: 'https://www.lebohangkganye.co.za/ke-lefa-laka-herstory-2013-all', images: [img('https://www.designindaba.com/sites/default/files/styles/scaledlarge/public/node/news/23677/gallery/1lebohang-kganyenailcutter.jpg?itok=L1gD4aFD', 'Ke Lefa Laka: Her-story', '© Lebohang Kganye', 'https://www.lebohangkganye.co.za/ke-lefa-laka-herstory-2013-all', 'Lebohang Kganye Studio')], relations: [rel('出版', 'Ke Lefa Laka: Her-story, Vol. I & II', 'Nazraeli Press, 2021')] },
      { title: 'Ke Lefa Laka: Heir-story', cluster: 'Family archive / apartheid history', period: '2013', summary: '沿母系家族历史把私人迁移和南非 apartheid 土地法造成的强制迁移并置。', actions: ['家族档案', '剪影 / cut-out', '历史叙事重构'], sourceUrl: 'https://www.lebohangkganye.co.za/', images: [], relations: [] },
      { title: 'Pied Piper’s Voyage', cluster: 'Film / archive animation', period: '2014', summary: '把 Heir-story 的家庭剪影和场景转成动态影像，让家族历史像纸偶剧一样被重新表演。', actions: ['cut-out 动画', '家庭档案再表演', '影片'], sourceUrl: 'https://www.lebohangkganye.co.za/', images: [], relations: [] },
      { title: 'Ke Sale Teng', cluster: 'Film / memory', period: '2017', summary: '借鉴相册翻页和 pop-up book 的物质感，用电影继续讨论家庭档案如何被编排、保存与重新叙述。', actions: ['家庭照片 cut-out', 'pop-up book 结构', '动画电影'], sourceUrl: 'https://www.lebohangkganye.co.za/context-press', images: [], relations: [] },
      { title: 'Mohlokomedi wa Tora', cluster: 'Installation / oral history', period: '2018', summary: '把照片转化为可步入的雕塑 / 剪影装置，以家族女性口述和“守灯人”叙事组织空间。', actions: ['照片转成立体 cut-out', '口述史', '灯光与阴影', '可步入装置'], sourceUrl: 'https://www.lebohangkganye.co.za/context-press', images: [], relations: [] },
      { title: 'Tell Tale', cluster: 'Theatre / place', period: '2018', summary: '在 Nieu Bethesda 驻留期间受 Athol Fugard 戏剧启发，把当地故事、舞台性和摄影装置结合。', actions: ['地方故事采集', '戏剧化场景', '摄影装置'], sourceUrl: 'https://www.lebohangkganye.co.za/context-press', images: [], relations: [] },
      { title: 'In Search for Memory', cluster: 'Speculative memory', period: '2020', summary: '受 Muthi Nhlema 科幻小说 TA O’REVA 启发，把记忆、未来想象和摄影装置相连。', actions: ['文学转译', '摄影', '装置 / world-building'], sourceUrl: 'https://www.lebohangkganye.co.za/context-press', images: [], relations: [] },
      { title: 'Shadows of Re-Memory', cluster: 'Film / theatre', period: '2021', summary: '从 Athol Fugard 与 Lauren Beukes 的文本出发，以女性角色、影子与“幽灵舞台”组织电影。', actions: ['文学研究', '舞台搭建', '影子表演', '电影'], sourceUrl: 'https://www.lebohangkganye.co.za/context-press', images: [], relations: [] },
      { title: 'Dipina tsa Kganya', cluster: 'Film / oral tradition', period: '2021', summary: '三频道影像装置从 Sesotho clan names 和“光”的词源出发，通过命名与净化表演讨论疗愈和口述传统。', actions: ['三频道影像', '表演', '口述传统', '命名 / 净化仪式'], sourceUrl: 'https://www.lebohangkganye.co.za/context-press', images: [], relations: [rel('策展', 'Bristol Photo Festival commission', '2021')] },
      { title: 'In Search for Memory', cluster: 'Installation continuation', period: '2022', summary: '2020 项目的后续 / 变体继续把摄影、舞台和记忆物质化。', actions: ['摄影', '装置', '系列延展'], sourceUrl: 'https://www.lebohangkganye.co.za/', images: [], relations: [] },
      { title: 'Keep the Light Faithfully', cluster: 'Labour / gendered history', period: '2022', summary: '研究 19–20 世纪数百位 lighthouse keeper 的少见性别化叙事，以及劳动如何改变家庭结构。', actions: ['历史档案研究', '摄影', '场景重构', '装置'], sourceUrl: 'https://lebohangkganye.squarespace.com/keep-the-light-faithfully', images: [], relations: [] },
      { title: 'Mosebetsi wa Dirithi', cluster: 'Patchwork / family album', period: '2022–2023', summary: '将家庭相册、阴影与手工 patchwork 转成新的摄影物件，让照片既是图像也是布面结构。', actions: ['家庭档案', 'patchwork', '摄影物件化'], sourceUrl: 'https://www.lebohangkganye.co.za/context-press', images: [], relations: [rel('展览', 'Haufi nyana? I’ve come to take you home — Foam', '2023')] },
      { title: 'Two Stories of (Hi)stories', cluster: 'Colonial archive / Cameroon', period: '2023', summary: '把 Marie Pauline Thorbecke 在博物馆档案中的历史照片与 Bamum 王国和喀麦隆历史片段重新组合。', actions: ['博物馆档案研究', '殖民照片挪用', '历史重组', '摄影装置'], sourceUrl: 'https://www.lebohangkganye.co.za/context-press', images: [], relations: [] },
      { title: 'A Burden Consumed in Sips', cluster: 'Film / colonial archive', period: '2023', summary: '22 屏全景影像装置从 Thorbecke 1911 年殖民考察的喀麦隆风景墨绘出发，重新处理殖民观看。', actions: ['22 屏视频', '历史图像研究', '景观再演', '沉浸式安装'], sourceUrl: 'https://www.lebohangkganye.co.za/a-burden-consumed-in-sips-2023', images: [], relations: [] },
      { title: 'The Sea is History', cluster: 'Photo-sculpture', period: '2024', summary: '三组大型可步入 pop-up book 式 photo-sculpture，以钢材上的摄影图像重访南非海岸灯塔守护者的个人和集体历史。', actions: ['照片打印到钢材', '大型三维场景', 'pop-up book 空间化', '口述史'], sourceUrl: 'https://www.lebohangkganye.co.za/', images: [], relations: [] },
      { title: 'Le Sale ka Kgotso', cluster: 'Language / haunting / installation', period: '2025', summary: '从 Sesotho “stay in peace”的语义和误读切入，把语言本身处理成会被幽灵化、会变形的材料。', actions: ['语言研究', '摄影', '装置', '神话 / 口述叙事'], sourceUrl: 'https://lebohangkganye.squarespace.com/le-sale-ka-kgotso-2025', images: [], relations: [rel('展览', 'Le Sale ka Kgotso — Fotografiska Berlin', '2025')] }
    ],
    awards: ['2025 ICP Infinity Award', '2024 Deutsche Börse Photography Foundation Prize — winner', '2022 Foam Paul Huf Award', '2021/22 Grand Prix Images Vevey', '2019 Camera Austria Award'],
    exhibitions: ['South African Pavilion — Venice Biennale 2022', 'Haufi nyana? I’ve come to take you home — Foam 2023', 'Le Sale ka Kgotso — Fotografiska Berlin 2025', 'New Photography 2025 — MoMA', 'Recent presentations: Tate Modern, Art Institute of Chicago, LE BAL, Barnes Foundation'],
    sources: [{ label: 'Official Works index', url: 'https://www.lebohangkganye.co.za/' }, { label: 'Official context & press', url: 'https://www.lebohangkganye.co.za/context-press' }, { label: 'Official publications', url: 'https://www.lebohangkganye.co.za/publications' }, { label: 'Official biography', url: 'https://www.lebohangkganye.co.za/about' }]
  },
  'trevor-paglen': {
    artistId: 'trevor-paglen',
    projectCoverage: '18 个核心项目 / 项目群已索引 · 官网持续更新',
    imageCoverage: '5 个项目已建立图像入口',
    note: 'Paglen 的 studio archive 持续增加项目、研究文章、工程与合作，因此这里先完成最重要的 18 个作品群，不把博客文章数量当作品数量。下一层会继续拆每个项目的 individual works。',
    projects: [
      { title: 'Limit Telephotography', cluster: 'Other Landscapes', period: '2004–', summary: '使用约 1300–7000mm 望远镜拍摄肉眼无法看见的军事设施，把“不可见”转成由距离和大气造成的物理图像问题。', actions: ['调查机密军事地点', '超长焦 / 天文摄影技术', '记录拍摄距离'], sourceUrl: 'https://paglen.studio/2020/04/22/limit-telephotography/', images: [], relations: [] },
      { title: 'The Other Night Sky', cluster: 'Celestial Objects', period: 'ongoing', summary: '与业余卫星观察网络合作追踪和拍摄未公开的秘密卫星。', actions: ['卫星轨迹研究', '天文摄影', '民间观察网络协作'], sourceUrl: 'https://paglen.studio/posts/', images: [], relations: [] },
      { title: 'Drones', cluster: 'Other Landscapes', period: '2010s', summary: '在内华达沙漠天空中拍摄由当地基地远程操控的 Predator、Reaper 等无人机。', actions: ['远距离观察', '天空摄影', '军事基础设施研究'], sourceUrl: 'https://paglen.studio/posts/', images: [], relations: [] },
      { title: 'The Last Pictures', cluster: 'The Depths of Time', period: '2012', summary: '与 Creative Time 和 MIT 合作，把 100 张图像蚀刻在金属圆盘上并送上 EchoStar XVI 地球同步卫星，使其成为面向数十亿年尺度的图像档案。', actions: ['跨学科研究', '100 图像选择 / 编辑', '微蚀刻材料实验', '卫星发射'], sourceUrl: 'https://paglen.studio/lastpictures/', images: [], relations: [rel('策展', 'Creative Time commission', 'with MIT, launched 2012'), rel('出版', 'The Last Pictures', 'UC Press')] },
      { title: 'Code Names of the Surveillance State', cluster: 'Bureaucratic Sublime', period: '2014', summary: '把 4,000 多个 NSA / GCHQ 监控项目代号组织成无尽滚动的视频“found poem”。', actions: ['泄露资料研究', '代号收集', '文本影像装置'], sourceUrl: 'https://paglen.studio/category/pictures-words/', images: [], relations: [] },
      { title: '89 Landscapes', cluster: 'Citizenfour / surveillance infrastructure', period: '2015', summary: '使用为 Citizenfour 拍摄的 NSA 基础设施景观，形成双频道录像装置。', actions: ['调查拍摄', '基础设施景观', '双频道录像'], sourceUrl: 'https://paglen.studio/posts/', images: [], relations: [] },
      { title: 'Autonomy Cube', cluster: 'The Ocean / usable sculpture', period: '2014–', summary: '与 Tor 网络连接的 Wi‑Fi 热点被封装成博物馆雕塑，使作品同时是可观看物件和真实运行的网络节点。', actions: ['网络工程', '雕塑', 'Tor 基础设施', '公共 Wi‑Fi'], sourceUrl: 'https://paglen.studio/2020/04/09/', images: [], relations: [] },
      { title: 'Trinity Cube', cluster: 'Nuclear material / sculpture', period: '2016', summary: '将福岛禁区收集的受辐射玻璃与美国首次核试验形成的 Trinitite 联系起来，处理核历史的物质残留。', actions: ['材料采集', '核历史研究', '雕塑'], sourceUrl: 'https://paglen.studio/posts/', images: [], relations: [] },
      { title: 'It Began as a Military Experiment', cluster: 'Training Images', period: '2017', summary: '从 FERET 数据库选择、修整肖像，再通过面部关键点算法处理，追踪机器视觉的人脸训练史。', actions: ['FERET 数据库研究', '肖像筛选 / 修整', '人脸关键点算法'], sourceUrl: 'https://paglen.studio/2020/04/09/it-began-as-a-military-experiment/', images: [img('https://www.moma.org/d/c/installation_images/W1siZiIsIjQ1MjEwMiJdLFsicCIsImNvbnZlcnQiLCItcXVhbGl0eSA3MCAtcmVzaXplIDU5NHgzOTleIC1ncmF2aXR5IENlbnRlciAtY3JvcCA1OTR4Mzk5KzArMCJdXQ.jpg?sha=2cf9063de074fd7a', 'It Began as a Military Experiment — installation', '© Trevor Paglen', 'https://www.moma.org/collection/works/275173', 'MoMA')], relations: [] },
      { title: 'Behold these Glorious Times!', cluster: 'Machine Visions', period: '2017', summary: '把训练 AI 的图像与神经网络内部表征并置，让观众同时看到“机器吃进去什么”和“机器怎样拆解它”。', actions: ['训练集研究', '神经网络视觉化', '视频装置', '与 Holly Herndon 声音合作'], sourceUrl: 'https://paglen.studio/2020/04/09/behold-these-glorious-times/', images: [], relations: [rel('展览', 'Metro Pictures', 'New York, 2017')] },
      { title: 'Hallucinations', cluster: 'Machine Visions', period: '2017–', summary: '研究自动图像识别和 captioning 系统如何在错误分类中暴露训练逻辑。', actions: ['机器分类', '图像 captioning', '错误输出研究'], sourceUrl: 'https://paglen.studio/category/training-images/', images: [], relations: [] },
      { title: 'Fanon', cluster: 'Machine Visions / faceprints', period: '2010s', summary: '借 facial recognition 的 faceprint 技术测试人物识别与身份映射。', actions: ['人脸算法', '身份匹配', '机器视觉'], sourceUrl: 'https://paglen.studio/posts/', images: [], relations: [] },
      { title: 'They Took the Faces…', cluster: 'Training Images', period: '2019', summary: '追踪囚犯和被告 mugshot 如何被计算机视觉研究者当作人脸识别训练材料。', actions: ['数据集溯源', '监狱 / mugshot 档案研究', '大尺幅打印'], sourceUrl: 'https://paglen.studio/posts/', images: [], relations: [rel('展览', 'Uncanny Valley — de Young Museum', '2020')] },
      { title: 'From “Apple” to “Anomaly”', cluster: 'ImageNet / labels', period: '2019', summary: '从 ImageNet 超过 1,400 万图像、2 万多分类中抽取材料，制作约 30,000 张独立照片的装置，研究 image / label 之间的权力。', actions: ['ImageNet 数据研究', '约 30,000 张打印', '分类系统重编排'], sourceUrl: 'https://paglen.studio/2020/04/09/from-apple-to-anomaly-pictures-and-labels-selections-from-the-imagenet-dataset-for-object-recognition/', images: [], relations: [rel('展览', 'Barbican Curve Gallery commission', '2019')] },
      { title: 'ImageNet Roulette', cluster: 'ImageNet / public experiment', period: '2019', summary: '把 ImageNet person categories 的问题暴露为公众可直接体验的分类实验。', actions: ['数据集批判', '互动网站', '算法分类'], sourceUrl: 'https://paglen.studio/posts/', images: [], relations: [] },
      { title: 'Training Humans', cluster: 'AI history / curatorial research', period: '2019', summary: '与 Kate Crawford 共同策划，追踪 computer vision 用于“识别人类”的训练图像史，强调 AI 的物质性和政治性。', actions: ['长期档案研究', '数据集史', '展览策划', '与 Kate Crawford 合作'], sourceUrl: 'https://paglen.studio/2020/04/09/kate-crawford-trevor-paglen-training-humans/', images: [], relations: [rel('展览', 'Fondazione Prada', '2019')] },
      { title: 'Making Faces', cluster: 'Facial analysis history', period: '2020s', summary: '与 Kate Crawford 延续面部分析史研究，从 phrenology 到当代 facial recognition。', actions: ['法律文件研究', '历史档案', '摄影调查', '展览'], sourceUrl: 'https://paglen.studio/posts/', images: [], relations: [] },
      { title: 'Orbital Reflector', cluster: 'Celestial object / public art', period: '2018', summary: '与 Nevada Museum of Art 合作的轨道公共艺术计划，把卫星基础设施反过来变成可见的艺术对象。', actions: ['航天工程合作', '公共艺术', '轨道基础设施'], sourceUrl: 'https://americanart.si.edu/press/2018/11/trevor-paglen-sites-unseen-opens-june-21-smithsonian-american-art-museum', images: [], relations: [] }
    ],
    awards: ['2026 LG Guggenheim Award — winner', '2017 MacArthur Fellowship', '2016 Deutsche Börse Photography Prize — winner', '2014 Electronic Frontier Foundation Pioneer Award'],
    exhibitions: ['Sites Unseen — Smithsonian American Art Museum, 2018–2019 · 100+ works', 'Fondazione Prada — solo / Training Humans context', 'Barbican Centre — solo / commission', 'Carnegie Museum of Art — solo exhibition', 'Vienna Secession — solo exhibition', 'Group exhibitions: Tate Modern, The Met, SFMOMA'],
    sources: [{ label: 'Official studio — all posts', url: 'https://paglen.studio/posts/' }, { label: 'Official biography', url: 'https://paglen.studio/bio/' }, { label: 'Smithsonian — Sites Unseen', url: 'https://www.si.edu/newsdesk/releases/trevor-paglen-sites-unseen-opens-june-21-smithsonian-american-art-museum' }, { label: 'Guggenheim Art & Technology Initiative', url: 'https://www.guggenheim.org/initiatives/lg-guggenheim-art-and-technology-initiative' }]
  },
  'tyler-mitchell': {
    artistId: 'tyler-mitchell',
    projectCoverage: '9 个核心艺术项目 / 展览与公共委托已索引 · 2015–2026',
    imageCoverage: '3 个项目已建立图像入口',
    note: 'Mitchell 同时做艺术作品、时尚委托、editorial、影像与展览。这里优先收录塑造其艺术实践的独立项目 / 展览和关键公共委托，不把每一次商业拍摄都冒充成独立艺术系列。后续会再拆 Photography 页面里的 individual works。',
    projects: [
      { title: 'Wish This Was Real — early film / project', cluster: 'Film / youth culture', period: '2015–2016', summary: 'Mitchell 早期电影与青年文化项目，后来“Wish This Was Real”成为其近十年回顾展的标题，形成前后呼应。', actions: ['电影', '青年文化观察', '独立展示'], sourceUrl: 'https://gagosian.com/artists/tyler-mitchell/', images: [], relations: [rel('展览', 'Wish This Was Real, Brooklyn', '2016 / Afrofuturism Film Festival official selection')] },
      { title: 'Vogue — Beyoncé September issue', cluster: 'Editorial / representation', period: '2018', summary: 'Mitchell 为 Beyoncé 拍摄 American Vogue 2018 年 9 月刊，成为该刊当时 126 年历史中首位拍摄封面的黑人摄影师。', actions: ['editorial portraiture', '时尚影像', '黑人主体再现'], sourceUrl: 'https://gagosian.com/artists/tyler-mitchell/', images: [], relations: [rel('收藏', 'Smithsonian National Portrait Gallery', '2019 acquisition from the series')] },
      { title: 'I Can Make You Feel Good', cluster: 'Black utopia / exhibition', period: '2019–2021', summary: '通过肖像、群体、户外休息和游戏构造黑人生活中轻盈、自由、亲密与闲暇的视觉世界。', actions: ['编排式肖像', '自然环境', '时尚 / 日常动作混合', '展览 sequence'], sourceUrl: 'https://www.icp.org/exhibitions/tyler-mitchell-i-can-make-you-feel-good', images: [img('https://images.squarespace-cdn.com/content/v1/5702ab9d746fb9634796c9f9/1580248318573-NJ3T9K2NAGPKK45ZXG0I/IMG_0615.jpg?format=1000w', 'I Can Make You Feel Good — installation view', '© Tyler Mitchell / installation view', 'https://www.icp.org/exhibitions/tyler-mitchell-i-can-make-you-feel-good', 'ICP')], relations: [rel('展览', 'Foam, Amsterdam', '2019'), rel('展览', 'ICP, New York', '2020–2021'), rel('出版', 'I Can Make You Feel Good', 'Prestel monograph')] },
      { title: 'The New Black Vanguard context', cluster: 'Collective context / fashion-image crossover', period: '2019–2023', summary: 'Mitchell 的实践被放进 Antwaun Sargent 策划的 The New Black Vanguard 脉络，与新一代黑人摄影和时尚图像的制度转向并置。', actions: ['群展语境', '出版 / 展览流通'], sourceUrl: 'https://gagosian.com/artists/tyler-mitchell/', images: [], relations: [rel('策展', 'The New Black Vanguard — Antwaun Sargent / Aperture', '2019, touring through 2023')] },
      { title: 'Chrysalis', cluster: 'Black pastoral / nature', period: '2022', summary: '在纽约州北部和纽约 / 伦敦 studio 拍摄年轻黑人主体与自然，围绕 radiance、resistance、comfort、agency 展开。', actions: ['location + studio portraiture', '自然景观', '历史黑人影像参照'], sourceUrl: 'https://gagosian.com/exhibitions/2022/tyler-mitchell-chrysalis/', images: [], relations: [rel('展览', 'Gagosian Davies Street, London', '2022')] },
      { title: 'Wish This Was Real — survey exhibition', cluster: 'Survey / material display', period: '2024–2026', summary: '近十年实践回顾，三部分组织摄影和视频，并出现 fabric、mirror 等新型输出，把 portraiture、nature、social memory 连在一起。', actions: ['跨十年编辑', '摄影 + 视频', '布面 / 镜面输出', '展览空间组织'], sourceUrl: 'https://gagosian.com/news/museum-exhibitions/tyler-mitchell-wish-this-was-real-co-berlin/', images: [], relations: [rel('展览', 'C/O Berlin', '2024'), rel('展览', 'Maison Européenne de la Photographie, Paris', '2025–2026')] },
      { title: 'Ghost Images', cluster: 'Gallery exhibition', period: '2025', summary: '纽约 Gagosian 个展节点，继续推进摄影表面、记忆与黑人主体的展示形式。', actions: ['新作展览', '画廊空间编排'], sourceUrl: 'https://gagosian.com/artists/tyler-mitchell/', images: [], relations: [rel('展览', 'Gagosian, 541 West 24th Street, New York', '2025')] },
      { title: 'Portrait of the Modern Dandy', cluster: 'Fashion history / museum commission', period: '2024–2025', summary: '为 Met Costume Institute “Superfine: Tailoring Black Style” 图录发展的视觉 essay，将现代黑人 dandy、服装与肖像史相连。', actions: ['视觉 essay', '时尚史研究', '肖像摄影', '博物馆出版委托'], sourceUrl: 'https://gagosian.com/exhibitions/2025/tyler-mitchell/', images: [], relations: [rel('出版', 'Superfine: Tailoring Black Style catalogue', 'The Met, 2025'), rel('展览', 'Gagosian Burlington Arcade', '2025 public display')] },
      { title: 'Time for a New Sky II', cluster: 'Public commission', period: '2026', summary: '进入 High Line 的公共艺术委托，说明 Mitchell 的图像逐渐从摄影馆 / 画廊扩展到城市公共空间。', actions: ['公共委托', '大尺度展示'], sourceUrl: 'https://gagosian.com/media/artists/tyler-mitchell/Mitchell-Tyler-Bio-2026-06-15.pdf', images: [], relations: [rel('策展', 'High Line public commission', '2026')] }
    ],
    awards: ['2025 CPW Vision Award — Photographer of the Year', '2024 British Fashion Council Isabella Blow Award', '2020 Gordon Parks Foundation Fellowship', '2019 Forbes 30 Under 30 — Art & Style'],
    exhibitions: ['I Can Make You Feel Good — Foam 2019', 'I Can Make You Feel Good — ICP 2020–2021', 'Chrysalis — Gagosian London 2022', 'Wish This Was Real — C/O Berlin 2024', 'Ghost Images — Gagosian New York 2025', 'Wish This Was Real — MEP Paris 2025–2026', 'Time for a New Sky II — High Line 2026'],
    sources: [{ label: 'Tyler Mitchell official photography', url: 'https://www.tylermitchell.co/photography' }, { label: 'Gagosian artist archive', url: 'https://gagosian.com/artists/tyler-mitchell/' }, { label: 'Gagosian 2026 biography', url: 'https://gagosian.com/media/artists/tyler-mitchell/Mitchell-Tyler-Bio-2026-06-15.pdf' }, { label: 'ICP — I Can Make You Feel Good', url: 'https://www.icp.org/exhibitions/tyler-mitchell-i-can-make-you-feel-good' }]
  },
  'liz-deschenes': {
    artistId: 'liz-deschenes',
    projectCoverage: '8 / 8 Whitney 在线馆藏作品 + 主要系列脉络已索引',
    imageCoverage: '5 个核心系列已建立图像 / 馆藏入口',
    note: 'Deschenes 的实践更像连续实验而不是大量有标题的“项目”。因此这里以 Whitney 当前 8 件在线馆藏和 MoMA / SFMOMA 对应作品为骨架，逐步把 Green Screen、Black & White、Moiré、Tilt/Swing、Untitled 等技术 / 展示脉络补全。',
    projects: [
      { title: 'Green Screen', cluster: 'Color / screen / photographic surface', period: '2001', summary: '以纯绿色银盐打印逼近“屏幕”与“照片表面”之间的边界，削弱再现对象。', actions: ['银盐打印', 'plexiglass mounting', '色彩作为主体'], sourceUrl: 'https://whitney.org/collection/works/45788', images: [], relations: [rel('收藏', 'Whitney Museum — Green Screen #7', '2001')] },
      { title: 'Black & White', cluster: 'Photographic fundamentals', period: '2003', summary: '把摄影压缩到黑白、表面、材料和展示条件这些基本变量。', actions: ['模拟摄影材料实验', '系列化'], sourceUrl: 'https://whitney.org/artists/9359', images: [], relations: [rel('收藏', 'Whitney Museum', 'Black & White #1–#5 / Black and White #2')] },
      { title: 'Phototgraph #9', cluster: 'Medium reflexivity', period: '2004', summary: '标题本身就把“照片作为物件 / 概念”推到前台，延续她对摄影媒介自反性的研究。', actions: ['摄影材料实验', '媒介自指'], sourceUrl: 'https://whitney.org/artists/9359', images: [], relations: [rel('收藏', 'Whitney Museum', '2004')] },
      { title: 'Moiré', cluster: 'Pattern / reproducibility', period: '2007–2009', summary: '通过有孔纸、双重曝光和稍微错位的底片叠合产生 moiré pattern，把抽象与机械复制问题变成具体光学过程。', actions: ['有孔纸置于亮窗前', '两次 8×10 黑白底片曝光', '错位叠片', '彩色相纸输出'], sourceUrl: 'https://www.moma.org/collection/works/159172', images: [], relations: [rel('收藏', 'Whitney — Moiré #5', '2007'), rel('收藏', 'MoMA — Moiré #25', '2009'), rel('展览', 'XL: 19 New Acquisitions in Photography — MoMA', '2013–2014')] },
      { title: 'Left / Right', cluster: 'Viewing / orientation', period: '2008', summary: '继续研究摄影平面的方向、观看方式与图像结构，而非外部叙事对象。', actions: ['chromogenic print', 'aluminum mounting', '空间 / 方向关系'], sourceUrl: 'https://whitney.org/collection/works/40396', images: [], relations: [rel('收藏', 'Whitney Museum', '2008')] },
      { title: 'Tilt / Swing (360° field of vision)', cluster: 'Installation / extended vision', period: '2009–2011', summary: '受 Herbert Bayer 1935 年 extended vision diagram 启发，用六块月光 photogram 占据不同墙面，让摄影成为包围观众的空间装置。', actions: ['夜间 / 月光无相机曝光', '银色调处理', '六面空间安装', '利用反射与持续氧化'], sourceUrl: 'https://www.moma.org/collection/works/161348', images: [img('https://whitneymedia.org/assets/image/821813/small_deschenesweb_938.jpg', 'Tilt / Swing — installation view', '© Liz Deschenes', 'https://whitney.org/exhibitions/2012-biennial/liz-deschenes', 'Whitney Museum')], relations: [rel('收藏', 'MoMA — Tilt/Swing version 1', '2009'), rel('收藏', 'Whitney — Tilt / Swing #4C', '2011')] },
      { title: 'Untitled — Whitney Biennial', cluster: 'Site-specific photogram', period: '2012', summary: '四联 photogram 直接回应 Marcel Breuer 设计的 Whitney 建筑：形态对应建筑立面、相机 bellows 和窗体角度。', actions: ['户外环境光 photogram', '银色哑光 / 黑色光泽表面', '建筑尺度对应', '场域特定安装'], sourceUrl: 'https://whitney.org/media/796', images: [], relations: [rel('展览', 'Whitney Biennial', '2012')] },
      { title: 'Front / Side #9', cluster: 'Surface / orientation', period: '2012', summary: '延续摄影作为反光表面、空间方向与材料痕迹的研究。', actions: ['大型 photogram / surface experiment', '空间关系'], sourceUrl: 'https://www.sfmoma.org/artist/Liz_Deschenes/', images: [], relations: [rel('收藏', 'SFMOMA — Front / Side #9', '2012')] }
    ],
    awards: [],
    exhibitions: ['Whitney Biennial 2012', 'XL: 19 New Acquisitions in Photography — MoMA 2013–2014', 'Sites of Reason — MoMA 2014', 'Collected by Thea Westreich Wagner and Ethan Wagner — Whitney 2015–2016'],
    sources: [{ label: 'Whitney artist archive — 8 works', url: 'https://whitney.org/artists/9359' }, { label: 'MoMA artist archive', url: 'https://www.moma.org/artists/32768-liz-deschenes' }, { label: 'MoMA — Tilt/Swing', url: 'https://www.moma.org/collection/works/161348' }, { label: 'SFMOMA artist archive', url: 'https://www.sfmoma.org/artist/Liz_Deschenes/' }]
  }
};
