import type { ArtistArchive, ArchiveProject, ArchiveRelation } from './archiveData';
const rel=(kind:ArchiveRelation['kind'],label:string,detail?:string):ArchiveRelation=>({kind,label,detail});
const project=(p:ArchiveProject)=>p;

export const archiveBatch308:Record<string,ArtistArchive>={
 'carrie-mae-weems':{artistId:'carrie-mae-weems',projectCoverage:'继续深化 Carrie Mae Weems：From Here I Saw What Happened and I Cried、Roaming、Constructing History，并补齐回顾展、MacArthur 与 MoMA/Guggenheim 机构关系。',imageCoverage:'MoMA、Guggenheim、National Gallery of Art 等机构页提供作品及装置图研究入口；未确认自由再发布授权的图像不复制。',note:'Weems 的实践不能只归结为“黑人女性身份摄影”。她持续改变谁有权叙述历史：从家庭和日常场景的自我导演，到挪用殖民/人类学档案并重新写入声音，再到让自己的身体作为见证者进入权力建筑，最后通过表演、录像与历史重演把摄影扩展成一种反档案和公共记忆装置。与单纯纪录社会现实的摄影不同，她不断让文字、舞台化、档案来源、观看位置和制度空间本身成为作品结构。',projects:[
 project({title:'From Here I Saw What Happened and I Cried',cluster:'archive / race / photographic violence / counter-narrative',period:'1995–1996',summary:'应 J. Paul Getty Museum 1994 年邀请，Weems 回应19世纪非裔美国人历史照片，并继续从博物馆、大学档案、National Geographic 及摄影史图像中取材。她不是原样展示档案，而是统一放大、裁切，加入红/蓝色调、圆形遮罩，并在玻璃表面以喷砂文字重新书写图像。作品由34幅图像构成，首尾以一位 Mangbetu 女性作为见证者框住叙事。它把原本用于人类学分类、种族主义论证或新闻观看的照片重新变成对摄影自身暴力史的审判。',actions:['从19世纪种族人类学照片及不同摄影档案选择既有图像。','放大、裁切并统一尺度，使来源各异的照片进入同一视觉制度。','使用红/蓝色调与圆形遮罩强化“镜头/观看”结构。','在玻璃上加入喷砂文字，让被摄者不再只是被分类对象，而进入新的第一人称/见证叙事。'],sourceUrl:'https://www.moma.org/artists/7177-carrie-mae-weems',images:[],relations:[rel('委托','J. Paul Getty Museum — 1994','Getty 邀请 Weems 回应 Jackie Napoleon Wilson 收藏的19世纪非裔美国人照片，成为项目起点。'),rel('馆藏','Museum of Modern Art — New York','MoMA 收藏完整作品并于2020–2021设置专门展厅。'),rel('策展','Roxana Marcoci / Dana Ostrander — MoMA','2020–2021 MoMA collection gallery 的策展关系。'),rel('方法关系','archive → crop/tint/text → counter-archive','不是把档案当证据直接使用，而是暴露档案原有观看制度并重新编码。')]}),
 project({title:'Roaming',cluster:'architecture / body / power / witness',period:'2006',summary:'Roaming 把 Weems 自己的黑衣背影放入罗马历史建筑与纪念性空间。与 Kitchen Table Series 的室内自我导演不同，这里的身体不再主导画面，而以较小尺度面对巨大的柱廊、台阶、立面和古典秩序。她把建筑当作权力如何获得持久性与合法性的视觉语言，同时让自己的身体成为穿行其中的见证者。作品延续她反复使用的“艺术家作为 avatar/witness”策略：人物既是具体的黑人女性身体，又是带观众进入历史空间的观看代理。',actions:['选择具有历史、纪念性和制度权力含义的罗马建筑空间。','以背向镜头的黑衣人物反复进入构图，建立连续 avatar。','利用人物与建筑尺度差异，让身体和权力空间形成张力。','将旅行/建筑摄影转化为关于谁被历史空间容纳、谁能观看历史的提问。'],sourceUrl:'https://www.macfound.org/fellows/class-of-2013/carrie-mae-weems',images:[],relations:[rel('方法关系','Kitchen Table → Roaming','从控制室内舞台的主人公转为进入既有历史建筑的见证者。'),rel('方法关系','fictional documentary / avatar','MacArthur Foundation 将她反复以自身作为历史重构和当代空间中的引导性人物视为重要方法。')]}),
 project({title:'Constructing History: A Requiem to Mark the Moment',cluster:'reenactment / performance / history / moving image',period:'2008',summary:'Constructing History 将摄影里的“见证”推进到表演与历史重演。Weems 与学生/表演者共同重构20世纪政治暴力、抗议和公共记忆中的标志性场景，让参与者不是被动复制新闻照片，而是在舞台化空间中重新占据那些已经被媒体固定的历史姿态。项目由摄影与录像共同构成，强调所谓公共历史本身也是通过摄影、电视、姿态、纪念和重复观看被建构出来的。',actions:['选择已通过大众媒体成为集体记忆的政治历史场景。','与表演者共同重新搭建和占据历史姿态。','使用舞台化、摄影和录像让“历史照片”显露其被生产的结构。','把观看者从接受既成历史图像推进到意识到记忆如何被图像反复制造。'],sourceUrl:'https://www.guggenheim.org/press-release/guggenheim-presents-carrie-mae-weems-three-decades-of-photography-and-video',images:[],relations:[rel('方法关系','archive appropriation → reenactment','从重写既有档案进一步转向重新表演产生档案的历史场景。'),rel('机构','Solomon R. Guggenheim Museum — 2014 retrospective','Three Decades of Photography and Video 以120余件作品呈现摄影、文字、录像和声音的跨媒介发展。')]})
 ],exhibitions:['Carrie Mae Weems: Three Decades of Photography and Video — Solomon R. Guggenheim Museum — New York — 2014','Carrie Mae Weems: Kitchen Table Series — National Gallery of Art — Washington — 2017–2018','Carrie Mae Weems’s From Here I Saw What Happened and I Cried — Museum of Modern Art — New York — 2020–2021'],awards:['MacArthur Fellow — 2013'],sources:[{label:'MoMA — Carrie Mae Weems artist profile',url:'https://www.moma.org/artists/7177-carrie-mae-weems'},{label:'MoMA — From Here I Saw What Happened and I Cried gallery',url:'https://www.moma.org/calendar/galleries/5255'},{label:'Guggenheim — Carrie Mae Weems: Three Decades of Photography and Video',url:'https://www.guggenheim.org/press-release/guggenheim-presents-carrie-mae-weems-three-decades-of-photography-and-video'},{label:'National Gallery of Art — Kitchen Table Series',url:'https://www.nga.gov/exhibitions/carrie-mae-weems-kitchen-table-series'},{label:'MacArthur Foundation — Carrie Mae Weems',url:'https://www.macfound.org/fellows/class-of-2013/carrie-mae-weems'}]}
};