import type { ArtistArchive, ArchiveProject, ArchiveRelation } from './archiveData';
const rel=(kind:ArchiveRelation['kind'],label:string,detail?:string):ArchiveRelation=>({kind,label,detail});
const project=(p:ArchiveProject)=>p;
export const archiveBatch297:Record<string,ArtistArchive>={
  'thomas-demand':{
    artistId:'thomas-demand',
    projectCoverage:'作品级深化第二批：Presidency I–V、Embassy / Yellowcake、Clearing、Trick、Poll。重点补充具体来源图像、模型制作、输出规格、版本与观看方式。',
    imageCoverage:'MoMA 与 National Gallery of Art 均提供对应作品/安装图，但 Thomas Demand 作品仍受版权保护；NGA 明确标记媒体不可下载、MoMA 要求经 Art Resource / Scala Archives 授权。本批保存官方图片页与版权状态，不复制受限文件。',
    note:'这一批集中处理 Demand 如何把新闻图像、政治事件与动态图像翻译成纸模型：不是只记录“纸模型摄影”，而是追踪原始事件/媒体图像→真人尺度纸与纸板重建→删去文字和可识别细节→摄影/逐格动画→大型 chromogenic print 或35mm film 的完整链条。',
    projects:[
      project({title:'Presidency I–V',cluster:'political image / life-size paper reconstruction / five-panel photography',period:'2008',summary:'Presidency I–V 由《纽约时报杂志》委托，围绕白宫椭圆形办公室这一高度媒体化的权力空间展开。National Gallery of Art 的官方资料确认，Demand 以纸、纸板和 confetti 制作了一个真人尺度的 Oval Office 模型，再从模型中选择五个视点摄影。五张 chromogenic prints 不是纪录真实白宫，而是重新制造公众早已通过新闻摄影熟悉的总统空间。整组总尺寸 310 × 1071.88 cm；图像最初配合 2008 年11月9日《纽约时报杂志》封面故事刊出，即美国总统选举后数日，因此作品同时在杂志传播和美术馆墙面两种制度中运行。',actions:['接受《纽约时报杂志》委托，把椭圆形办公室作为需要重新制造的媒体空间。','以纸、纸板和 confetti 搭建真人尺度模型，而不是进入白宫直接拍摄。','从模型内部建立五个摄影视点，形成 Presidency I–V 五张连续但可独立观看的 chromogenic prints。','将作品首先置入杂志封面/报道语境，随后以总宽超过10米的五联摄影进入美术馆。'],sourceUrl:'https://www.nga.gov/artworks/143461-presidency',images:[],relations:[rel('收藏','National Gallery of Art — 2009.51.1.a-e','5 chromogenic prints；overall 310 × 1071.88 cm；Gift from Agnes Gund and Jo Carole and Ronald S. Lauder。'),rel('出版','The New York Times Magazine — 9 Nov 2008','NGA 新闻资料确认该组由杂志委托并用于选举后的封面故事。'),rel('展览','NGA East Building — 2009','NGA 资料记录这是作品首次在美国展出。')]}),
      project({title:'Embassy / Yellowcake',cluster:'political reconstruction / memory model / nine-part photographic sequence',period:'2007',summary:'Embassy 是 Yellowcake 项目的核心九联摄影，追踪导致伊拉克战争论证的一组伪造“尼日尔铀交易”文件所牵连的罗马尼日尔使馆。NGA 资料指出，这一次 Demand 面临一个反常问题：现场没有现成媒体图像可直接翻译。他亲自去罗马的尼日尔使馆，以手机拍少量照片并画草图，随后主要凭记忆在工作室重建模型。九张图从外立面、关闭的门和走廊推进到门缝光线与凌乱办公室，形成近似电影分镜的空间叙事。NGA 馆藏版本为9张 chromogenic prints，总体约228.66 × 1585.37 cm；作品因此把“缺失的新闻图像”本身转化为主题。',actions:['前往罗马尼日尔使馆实地观察，而不是完全依赖报刊照片。','用手机拍摄少量参考图并现场绘制草图；回工作室后结合记忆重建使馆空间。','用纸和纸板制造建筑外部、走廊、门和办公室等不同场景，再逐一摄影。','把九张照片排列成从外到内的电影式序列，让观众沿墙移动并逐步进入事件现场。'],sourceUrl:'https://www.nga.gov/artworks/218618-embassy',images:[],relations:[rel('收藏','National Gallery of Art — 2019.167.1.a-i','9 chromogenic prints；overall 228.66 × 1585.37 cm；馆方媒体标记不可下载。'),rel('展览','Thomas Demand: Yellowcake — 303 Gallery — 2007','NGA 馆藏记录展期 3 Nov–22 Dec 2007。'),rel('展览','Thomas Demand: Animations — Phi Foundation — 2013','NGA 展览史记录该组在蒙特利尔展出。')]}),
      project({title:'Clearing',cluster:'constructed nature / paper foliage / monumental chromogenic print',period:'2003',summary:'Clearing 把 Demand 常见的室内纸模型方法推到“自然环境”。最终图像看似一片繁密树林，但仍来自人工建造的纸质场景；观众面对的是一张宽近5米的 chromogenic print（192 × 495 cm），纸叶、枝条和均质化细节在巨大尺度上形成一种介于可信自然与舞台布景之间的视觉状态。MoMA 2005 回顾展把它与 Room、Studio 等室内重建并置，因此观看者可以直接比较 Demand 如何用相同的纸/纸板逻辑分别制造建筑空间和自然景观。',actions:['把自然景观而非室内新闻现场转译成工作室中的人工纸质环境。','以大量重复的纸质叶片、枝条和背景层建立树林深度，而不是在真实森林中摄影。','控制模型照明与相机位置，使纸制场景在照片中短暂获得自然景观的可信度。','输出为192×495cm超宽幅 chromogenic print，使观众必须在距离与近看细节之间移动。'],sourceUrl:'https://www.moma.org/collection/works/90063',images:[],relations:[rel('收藏','MoMA — 236.2004','Chromogenic print；192 × 495 cm。'),rel('展览','Thomas Demand — MoMA — 2005','MoMA 保存对应安装图；安装照 reproduction 需经 Art Resource / Scala Archives。')]}),
      project({title:'Trick',cluster:'35mm film / stop-motion-like paper animation / reconstructed historical trick',period:'2004',summary:'Trick 把 Demand 的纸模型从静态摄影推进到运动影像。MoMA 馆藏记录它是59秒、彩色、无声的35mm film；2005展览资料记录为约1分钟循环并使用 Dolby SR 展陈系统。画面中的桌、盘状物和器具不是自然发生运动的真实物体，而是被逐步调整后拍摄，使纸质布景获得一种短促、机械又不完全可信的运动。最终循环结构让观众没有明确开头或结尾，可以在展厅任意时刻进入这段“把静态模型变成事件”的实验。',actions:['搭建桌面与器具的纸质/模型化场景，使其延续 Demand 的人工空间语言。','在连续画格之间改变物件位置，以动画方式制造运动而非记录一次真实动作。','输出为35mm彩色无声电影，最终时长59秒。','以循环方式放映，使观看者进入展厅时可从任意画格开始观看。'],sourceUrl:'https://www.moma.org/collection/works/102486',images:[],relations:[rel('收藏','MoMA — 815.2006','35mm film (color, silent)，duration 0:59。'),rel('展览','Thomas Demand — MoMA — 2005','MoMA audio guide 记录35mm film loop、约1 minute、Dolby SR。')]}),
      project({title:'Poll',cluster:'Florida recount / accelerated model production / reportage overlap',period:'2001',summary:'Poll 来自2000年美国总统选举佛罗里达重新计票。Demand 在 MoMA 口述中强调，他通常需要两三个月完成从计划、建模到最终摄影的全过程，但为了让作品与仍在发生的新闻事件重叠，这次昼夜工作，仅三周完成，并在 George W. Bush 就职前展出。重新计票本身依赖纸质选票，因此“纸”在这里既是模型材料，也是政治事件中的真实技术媒介。最终 chromogenic color print 尺寸约180.3 × 259.1 cm；作品故意逼近 reportage 的时间速度，却仍然通过纸模型插入一道人工重建。',actions:['以佛罗里达重新计票的新闻图像为起点选择场景。','压缩通常两三个月的生产周期，连续工作约三周完成模型与摄影。','利用纸/纸板重建计票环境，使模型材料与事件中的纸质选票形成直接物质对应。','在布什正式就职前完成并展出，让缓慢的工作室重建短暂追上新闻报道。'],sourceUrl:'https://www.moma.org/audio/playlist/230/2954',images:[],relations:[rel('收藏','MoMA / promised and fractional gift record','Chromogenic color print；180.3 × 259.1 cm。'),rel('展览','early 2001 presentation','艺术家在 MoMA 口述中明确说明作品首次展出发生在 Bush 就职之前。')]}),
    ],
    awards:[],
    exhibitions:['Thomas Demand — MoMA — 4 Mar–30 May 2005','Thomas Demand: Yellowcake — 303 Gallery — 2007'],
    sources:[
      {label:'National Gallery of Art — Presidency',url:'https://www.nga.gov/artworks/143461-presidency'},
      {label:'National Gallery of Art — Embassy',url:'https://www.nga.gov/artworks/218618-embassy'},
      {label:'National Gallery of Art — Yellowcake acquisition / research release',url:'https://www.nga.gov/content/dam/ngaweb/research/gallery-archives/PressReleases/2029-2020/2020/14A10_137628_20201030.pdf'},
      {label:'MoMA — Clearing',url:'https://www.moma.org/collection/works/90063'},
      {label:'MoMA — Trick',url:'https://www.moma.org/collection/works/102486'},
      {label:'MoMA — Poll audio / artist account',url:'https://www.moma.org/audio/playlist/230/2954'},
      {label:'MoMA — Thomas Demand 2005 exhibition',url:'https://www.moma.org/calendar/exhibitions/116'}
    ]
  }
};
