import type { ArtistArchive, ArchiveProject, ArchiveRelation } from './archiveData';
const rel=(kind:ArchiveRelation['kind'],label:string,detail?:string):ArchiveRelation=>({kind,label,detail});
const p=(x:ArchiveProject)=>x;
export const archiveBatch323:Record<string,ArtistArchive>={
'wolfgang-tillmans':{artistId:'wolfgang-tillmans',projectCoverage:'继续深化 Wolfgang Tillmans：Neue Welt、展览编排/visual democracy、纸张作为材料与社会政治实践；与既有 Freischwimmer、Silver、paper drops、天文影像及 Tate Modern Edition 形成连续方法史。',imageCoverage:'优先保留 MoMA、Tate 等机构作品页与展览入口；版权未确认可复用的图像不直接搬运。',note:'Tillmans 的关键不只是“拍日常”或某一种青年文化风格，而是持续测试摄影如何在拍摄、暗房、数字传感器、纸张、复印、录像、出版和墙面编排之间改变。作品的意义往往由图像之间的尺度、距离、材料和观看顺序共同生成。',projects:[
p({title:'Neue Welt (New World)',cluster:'digital transition / global surface / circulation',period:'2008–2012',summary:'Tillmans 在2008至2012年前后展开 Neue Welt，主动观察“世界表面如何变化”。MoMA 回顾展指南把它描述为跨越肖像、静物、风景、街头与建筑摄影的全球性项目，关注金融、商品和人口流动塑造的当代条件。项目的开始也与他转用数字相机重合：新传感器提供更强低光细节，使一些过去难以拍摄的场景成为可能。数字技术在这里不是中性的升级，而改变了什么能够被看见、图像表面怎样被描述。',actions:['跨城市和国家持续拍摄而非围绕单一地点建立纪实系列','并置肖像、静物、建筑、街景和风景以观察全球化表面','把金融、商品与人口流动作为隐形结构而非直接图解对象','采用数字相机并利用低光与高细节能力扩展可拍摄范围','通过展览和出版重新组织异质图像，使“世界”由关系而非单张代表作构成'],sourceUrl:'https://www.moma.org/momaorg/shared/pdfs/docs/visitor-guide-wolfgang-tillmans-to-look-without-fear.pdf',images:[],relations:[rel('展览','Wolfgang Tillmans: To look without fear — MoMA','2022–2023；Room 8 专门梳理 Neue Welt'),rel('出版','Neue Welt','项目以书与展览系统传播'),rel('策展','Roxana Marcoci / Caitlin Ryan / Phil Taylor','MoMA 回顾展研究框架')] }),
p({title:'Exhibition constellations / visual democracy',cluster:'display system / editing / social space',period:'1990s–present',summary:'Tillmans 把展墙当作作品结构的一部分：无框照片可用胶带或夹子直接固定，框装作品、杂志页面、复印件、彩色与黑白照片、桌面材料和视频投影并置。MoMA 将这种展示描述为“visual democracy in action”。不同尺寸与不同物质状态的图像不服从传统摄影展逐张等距排列，而形成临时星座；因此同一照片进入不同展览时会获得新的邻接关系和阅读节奏。',actions:['混合无框、框装、杂志页、复印件与投影','通过尺寸差异制造身体距离：小图要求靠近，大图改变空间尺度','以胶带、图钉/夹具和桌面展示暴露图像的物质状态','每次展览重新编辑邻接关系而非复制固定挂法','把墙面看作社会空间，使私人、政治、抽象和日常图像处于同一观看等级'],sourceUrl:'https://www.moma.org/calendar/exhibitions/5440',images:[],relations:[rel('展览','Wolfgang Tillmans: To look without fear — MoMA','12 Sep 2022–1 Jan 2023'),rel('展览','Art Gallery of Ontario / SFMOMA','MoMA 展后巡展网络'),rel('策展','Roxana Marcoci','MoMA 回顾展组织者')] }),
p({title:'Paper as image, object and process',cluster:'paper drops / darkroom abstraction / photocopy',period:'2001–present',summary:'MoMA 的回顾展研究把纸张同时视为 Tillmans 的承载体与题材。2001年开始的 paper drops 拍摄摄影纸在自身重量下弯曲、卷起时的反光表面，使“照片”成为被摄影的物体；无相机暗房作品则让光、银盐、显影液和纸自身直接生成图像。2016 Tate Modern Edition 又把施工现场照片送入传统复印机，通过选择、分离和扭曲形成172件彼此不同的作品。三条路径共同把纸从透明图像载体变成具有重量、曲率、化学反应和复制误差的材料。',actions:['让摄影纸自然弯曲并把纸本身作为静物拍摄','在暗房直接以光和化学作用于感光纸','保留液体、银盐和偶发痕迹而非消除“错误”','把既有照片送入传统复印机重新选择、分离和扭曲','用原作、放大版本与不同输出方式改变观看者对纸张尺度的身体感受'],sourceUrl:'https://www.moma.org/momaorg/shared/pdfs/docs/visitor-guide-wolfgang-tillmans-to-look-without-fear.pdf',images:[],relations:[rel('出版','MoMA visitor guide — To look without fear','记录 paper drops 与暗房材料方法'),rel('展览','Tate Modern Edition','2016；172件 unique works'),rel('出版','Tate Modern Edition process','Tate 记录传统 photocopier 的选择、分离与扭曲过程')] }),
p({title:'Photography as social and political amplifier',cluster:'activism / publishing / public sphere',period:'1990s–present',summary:'Tillmans 的社会政治实践并非与“形式实验”分开的副线。MoMA 回顾展明确指出他把艺术家的角色理解为社会与政治议题的 amplifier，并将夜生活、亲密关系、社会运动、移民、身份政治等与抽象和静物放进同一展示系统。Tate 资料也长期强调其作品涉及 homelessness、racism 与 gay rights。这里摄影的政治性并不只来自拍摄抗议现场，而来自图像怎样进入杂志、海报、展览、出版和公共讨论。',actions:['持续记录朋友、夜生活、亲密关系与社会运动','把私人生活和公共政治放入同一图像等级','利用杂志页面、海报、出版和展墙扩大图像传播路径','拒绝把“政治照片”与抽象/形式实验严格分开','把艺术家定位为议题的放大器而非替社会运动发言的权威'],sourceUrl:'https://www.moma.org/calendar/exhibitions/5440',images:[],relations:[rel('奖项','Turner Prize','2000；首位获奖摄影家，亦为首位非英国获奖者'),rel('展览','Wolfgang Tillmans: 2017 — Tate Modern','实践扩展到录像、数字投影、出版与录制音乐'),rel('展览','To look without fear — MoMA','把社会运动文件、夜生活、裸体、抽象、建筑与天文现象纳入同一职业回顾')] })],awards:['Turner Prize — 2000'],exhibitions:['Wolfgang Tillmans: Freedom from the Known — MoMA PS1 — 2006','Wolfgang Tillmans: 2017 — Tate Modern — 2017','Wolfgang Tillmans: To look without fear — MoMA — 2022–2023','To look without fear — Art Gallery of Ontario / SFMOMA — subsequent tour'],sources:[{label:'MoMA — Wolfgang Tillmans: To look without fear',url:'https://www.moma.org/calendar/exhibitions/5440'},{label:'MoMA — Wolfgang Tillmans artist page',url:'https://www.moma.org/artists/8044-wolfgang-tillmans'},{label:'MoMA — To look without fear visitor guide',url:'https://www.moma.org/momaorg/shared/pdfs/docs/visitor-guide-wolfgang-tillmans-to-look-without-fear.pdf'},{label:'MoMA — Moon in Earthlight',url:'https://www.moma.org/collection/works/431169'},{label:'Tate — Tate Modern Edition 2016',url:'https://shop.tate.org.uk/wolfgang-tillmans-tate-modern-edition-2016/ed1000.html'}]}
};