import type { ArtistArchive, ArchiveRelation } from './archiveData';
const rel=(kind:ArchiveRelation['kind'],label:string,detail?:string):ArchiveRelation=>({kind,label,detail});
const atkins='https://www.labiennale.org/en/art/2019/partecipants/ed-atkins';
const atoui='https://www.labiennale.org/en/art/2019/partecipants/tarek-atoui';
const atouiGround='https://www.pinaultcollection.com/palazzograssi/en/tarek-atoui-ground-sessions';
const bader='https://www.labiennale.org/en/art/2019/partecipants/darren-bader';
const baderAsac='https://asac.labiennale.org/attivita/arti-visive/377831';
const baghramian='https://www.labiennale.org/en/art/2019/partecipants/nairy-baghramian';
export const archiveBatch114:Record<string,ArtistArchive>={
'venice-ed-atkins':{artistId:'venice-ed-atkins',projectCoverage:'2 个 Venice 2019 核心节点已建立深档案 · 2017–2019',imageCoverage:'0 / 2 项目暂不使用不稳定外链图像',note:'Atkins 的 2019 档案不能只写“CGI 艺术家”：关键是高度写实计算机身体、亲密自画像式写作与故意低俗/忧郁的历史意象如何互相污染。此条按 Venice 官方展出节点拆为 Old Food 与 Bloom。',projects:[{title:'Old Food',cluster:'CGI figure / self-portraiture / historicity-melancholy / psychic crisis',period:'2017–2019',summary:'Arsenale installation 以高度写实 computer-generated figures 承载不明原因的 psychical crisis，并把 autobiographical figuration 推向更广的 historical citation、melancholy 与 deliberately stupid imagery。',actions:['以 realistic computer-generated video 构造近似真人却持续暴露数字人工性的男性身体','把 self-portraiture 转译为替身式 CGI figure，而非直接纪录作者本人','将 intimate / elliptical writing 与 moving image 的情绪结构并置','用 historicity 与 broader citation 扩张 autobiographical material','让 melancholy 与 deliberately stupid / awkward elements 同时存在，避免单一崇高情绪'],sourceUrl:atkins,images:[],relations:[rel('展览','May You Live In Interesting Times — Venice Biennale 2019','Arsenale')]},{title:'Bloom I–X',cluster:'drawing / tarantula-body hybrid / grotesque self-portrait',period:'2019',summary:'十幅 drawings 把 tarantula 与 tentative hands / posed foot 结合，并将缩小的 Atkins 头像置换为蜘蛛腹部；自画像被压缩成 grotesque biological appendage。',actions:['制作编号一至十的 drawing sequence','将 tarantula 与 hand / foot 等身体局部组合','把自身头像缩小并置换蜘蛛 abdomen','以 arachnid hair 包围人脸，强化 tactile disgust','让直视观众的脸打破 fourth wall，并保持 ambivalent consciousness'],sourceUrl:atkins,images:[],relations:[rel('展览','May You Live In Interesting Times — Venice Biennale 2019','Central Pavilion')]}],awards:[],exhibitions:['May You Live In Interesting Times — Venice Biennale 2019'],sources:[{label:'La Biennale · Ed Atkins 2019',url:atkins}]},
'venice-tarek-atoui':{artistId:'venice-tarek-atoui',projectCoverage:'2 个 participatory-listening / instrument-system 节点已建立深档案 · 2019',imageCoverage:'0 / 2 项目暂不使用不稳定外链图像',note:'Atoui 的核心不是“做声音装置”而是重新设计 listening condition：自制 instruments、collaborators、audience movement 与 visual/aural/somatic channels 一起成为作品。',projects:[{title:'THE GROUND',cluster:'participatory sound environment / self-built instruments / multimodal listening',period:'2019',summary:'Venice 展出把音乐与 contemporary art 的 open-form tradition 接起来，以复杂 sound environment 让 listening 同时成为 visual、aural 与 somatic experience。',actions:['设计并协调可持续生成声音的 complex environment','使用 artist-designed instruments，而非把固定录音当唯一声源','把 performer 与 audience 的角色边界改写为参与式 listening relation','让声音通过身体、空间和视觉共同被感知','以 collaboration 使 composition 在现场关系中持续变化'],sourceUrl:atoui,images:[],relations:[rel('展览','May You Live In Interesting Times — Venice Biennale 2019','Central Pavilion / Arsenale')]},{title:'THE GROUND Sessions',cluster:'performance / collaborative composition / evolving instrument ecology',period:'2019',summary:'由 THE GROUND 延伸出的 performances 使用 Atoui 自制的不同 instruments，并由长期与新近 collaborators 共同构成递进的 sound environments。',actions:['从 Biennale installation 抽取 instrument system 进入 live performance','每个 movement 改用不同自制 instruments','邀请长期 collaborators 与近期合作艺术家共同演奏','让 successive performances 彼此累积而非重复固定 score','在 Palazzo Grassi / Teatrino 等不同空间重新组织 listening environment'],sourceUrl:atouiGround,images:[],relations:[rel('展览','THE GROUND Sessions — Palazzo Grassi / Teatrino, Venice','2019 performance extension')]}],awards:[],exhibitions:['May You Live In Interesting Times — Venice Biennale 2019','THE GROUND Sessions — Palazzo Grassi / Teatrino 2019'],sources:[{label:'La Biennale · Tarek Atoui 2019',url:atoui},{label:'Pinault Collection · THE GROUND Sessions',url:atouiGround}]},
'venice-darren-bader':{artistId:'venice-darren-bader',projectCoverage:'1 个 city-scale augmented-reality / app work 已建立深档案 · 2019',imageCoverage:'0 / 1 项目暂不使用不稳定外链图像',note:'Bader 在 2019 把 readymade / conceptual language 的问题推进到 smartphone AR：作品不是一个房间里的物，而是由 app、宣传 posters、城市既有视觉饱和度和用户移动共同产生。',projects:[{title:"Scott Mendes’s VENICE!",cluster:'augmented reality / smartphone app / city-scale conceptual layer',period:'2019',summary:'一件通过 mobile app 运作的 augmented-reality work，覆盖 Arsenale、Central Pavilion 及更广的 Venice；它不是向城市加入传统雕塑，而是在本已 aesthetic / historical / sensory saturation 的 Venice 上再叠一层 reality / unreality。',actions:['开发以 mobile app 为入口的 AR work','让作品不受单一 exhibition room 限制，跨 Arsenale、Central Pavilion 与城市运行','以 smartphone screen 将 virtual element 叠加到 physical Venice','在 Central Pavilion 使用五张 posters 宣传可下载 app，使 advertising language 成为作品接口','把 visitor movement 与 phone mediation 变成观看条件','借城市既有历史与旅游视觉饱和度测试“增加现实层”是否反而制造 unreality'],sourceUrl:bader,images:[],relations:[rel('展览','May You Live In Interesting Times — Venice Biennale 2019','Central Pavilion / Arsenale; ASAC records computer-art/app presentation')]}],awards:[],exhibitions:['May You Live In Interesting Times — Venice Biennale 2019'],sources:[{label:'La Biennale · Darren Bader 2019',url:bader},{label:'ASAC · Scott Mendes VENICE!',url:baderAsac}]},
'venice-nairy-baghramian':{artistId:'venice-nairy-baghramian',projectCoverage:'2 个 mechanical-corporeal sculpture 节点已建立深档案 · 2019',imageCoverage:'0 / 2 项目暂不使用不稳定外链图像',note:'Baghramian 的 2019 works 很适合 Practice Index：不是“抽象雕塑”四个字，而是通过 support、pressure、fragility 和 mechanical/body ambiguity 让 sculpture 看起来像随时会失效的 hybrid creature。',projects:[{title:'Dwindlers',cluster:'glass appendage / duct-intestine ambiguity / corridor intervention',period:'2019',summary:'沿 Arsenale exterior corridor 分布的 glass appendages 在 ventilation duct、monstrous intestine、ornament 与 ruined structure 之间摇摆，拒绝让观看者稳定分类。',actions:['以 glass 制作 appendage-like sculptural units','沿 exterior corridor 布置，使建筑 circulation 成为作品读取顺序','同时调用 mechanical duct 与 bodily intestine 的形态线索','保留 ornament / damage 两种相反判断','通过 hybrid morphology 延迟 object category 的确定'],sourceUrl:baghramian,images:[],relations:[rel('展览','May You Live In Interesting Times — Venice Biennale 2019','Arsenale exterior corridor')]},{title:'Maintainers',cluster:'cast aluminium / wax / cork / lacquered brace / structural dependency',period:'2019',summary:'raw cast aluminium 被紧压在 wax forms 上，wax 又由 cork bar 与 lacquered braces 支撑；“完整雕塑”其实由互相依赖的支撑关系临时成立，移除 cork / braces 即可能 collapse。',actions:['铸造 raw aluminium elements 并保留其坚硬表面感','将 aluminium 紧压到较脆弱的 wax forms','以 cork bar 支撑 wax','加入 lacquered braces 作为明确可见的 maintaining device','不隐藏结构依赖，而把 support 本身变成 sculpture vocabulary','用可能 collapse 的条件制造 support 与 attack 的动态张力'],sourceUrl:baghramian,images:[],relations:[rel('展览','May You Live In Interesting Times — Venice Biennale 2019','Central Pavilion')]}],awards:[],exhibitions:['May You Live In Interesting Times — Venice Biennale 2019'],sources:[{label:'La Biennale · Nairy Baghramian 2019',url:baghramian}]}
};
