import type { ArtistArchive, ArchiveRelation } from './archiveData';

const rel=(kind:ArchiveRelation['kind'],label:string,detail?:string):ArchiveRelation=>({kind,label,detail});

export const archiveBatch251:Record<string,ArtistArchive>={
  'walid-raad':{
    artistId:'walid-raad',
    projectCoverage:'作品级深化：把 The Atlas Group 的 My Neck Is Thinner Than A Hair: Engines 下钻为可核对的 100 件档案板、单件 MoMA 版本与 2003 威尼斯双年展 DVD/展览版本，记录报纸档案再利用、图像正反面、文字注记、喷墨输出与版本变化。',
    imageCoverage:'mumok、MoMA 与 2003 Venice Biennale 相关档案均提供对应作品或细节图。版权分别标记 The Atlas Group / © Walid Raad；未确认开放再发布许可，故 images 留空并保存官方图像入口、摄影/版权信息，不抓取搜索缩略图。',
    note:'这一节点的关键不是泛称“虚构档案”，而是 Raad 如何从真实新闻摄影档案抽取汽车炸弹发动机照片，再通过编号、日期、来源、正反面与档案式陈列，把历史证据的权威性本身变成作品材料。',
    projects:[
      {title:'My Neck Is Thinner Than A Hair: Engines — 100-panel installation',cluster:'The Atlas Group / archive / car bombs / photographs + text',period:'2000–2003',summary:'作品围绕 1975–1991 年黎巴嫩战争期间的汽车炸弹展开。Raad/The Atlas Group 从 Beirut 的新闻与文献档案中重新取得爆炸后被抛离车体的发动机照片；发动机在新闻报道中被当成可能追查车主与责任人的“证据”，但 Raad 指出炸弹车辆往往是赃车，因此这种编号证据并不真正导向司法真相。mumok 馆藏版本由 100 件彩色照片/文字档案板组成，每框约 25.2 × 35.3 × 3.2 cm；作品展示照片正反面、日期、摄影者/档案来源和文件编号，使新闻图片被重新编码成一个看似严谨却不断暴露历史叙述不稳定性的档案系统。',actions:['从 An-Nahar Research Centre、Arab Documentation Centre 等新闻/文献档案中寻找汽车炸弹爆炸后发动机的历史照片。','把照片从原新闻语境中抽离并重新制作成统一档案单元。','在图像旁/背面组织日期、摄影者、文件编号等元数据，让照片获得档案证物的外观。','将约 100 个单元密集并列在墙面，观众必须在重复发动机图像和细小文字之间移动、比较。','利用真实来源与 Atlas Group 的虚构/归档框架并置，使“照片来自真实档案”并不等同于“档案叙事透明可信”。'],sourceUrl:'https://www.mumok.at/onlinesammlung/detail/my-neck-is-thinner-than-a-hair-engines-10314',images:[],relations:[rel('收藏','mumok — Museum moderner Kunst Stiftung Ludwig Wien','100 photographs + text；frame 25.2 × 35.3 × 3.2 cm；acquired 2005；rights: The Atlas Group.'),rel('来源','Lebanese newspaper/documentation archives','MoMA artist audio confirms the images are historical photographs re-presented from newspaper archives in Lebanon.')]},
      {title:'My Neck Is Thinner Than A Hair: Engines — MoMA detail / inkjet object',cluster:'pigmented inkjet print / archive detail / evidentiary image',period:'1996–2004',summary:'MoMA 保存的具体细节版本把该系列落实到单件物体：pigmented inkjet print，24 × 34 cm。Raad 在 MoMA 口述中解释，照片中的发动机像飞机事故的 black box，被警员、政治人物和围观者围视；发动机编号理论上可追查车辆所有者，但赃车现实又让这种证据链失效。单件尺寸使观众可以像阅读档案卡一样近距离检查发动机、人物和编号，而当这些单元累积为墙面网格时，观看又从单个证据扩展为对整个证据制度的怀疑。',actions:['保留历史新闻照片中的发动机和围观/调查人物。','以 pigmented inkjet 工艺重新输出历史图像，使“旧新闻照片”成为新的当代艺术物件。','把单件控制在约档案/文件尺度 24 × 34 cm，要求近距离阅读。','通过大量同类图像的连续排列，让发动机从个别爆炸残骸变成重复出现的新闻视觉类型。'],sourceUrl:'https://www.moma.org/audio/playlist/280/3654',images:[],relations:[rel('收藏','Museum of Modern Art, New York','Pigmented inkjet print, 24 × 34 cm；Fund for the Twenty-First Century；© 2015 Walid Raad.')]},
      {title:'My Neck Is Thinner Than A Hair — Venice Biennale 2003 version',cluster:'biennale / DVD / archive translated into moving image',period:'2003',summary:'在第50届威尼斯双年展 “Dreams and Conflicts — The Viewer’s Dictatorship” 的 Contemporary Arab Representations 单元中，项目以 My Neck Is Thinner Than A Hair: A History of Car Bombs in the Lebanese Wars 1975–1991 (Volumes 1–245) / Engines 出现，并有 5分58秒 DVD 版本记录。这个版本说明同一研究并不固定为一堵照片墙：档案材料可以被重新组织成时间性的屏幕观看，观众不再自行决定在100张图像间移动的顺序，而由录像剪辑控制发动机图像与信息出现的节奏。',actions:['把长期汽车炸弹档案从静态照片/文本系统重新编排为 DVD 时间轴。','通过约 5分58秒的固定时长改变观众阅读档案的节奏。','在 Venice Biennale 的策展语境中把黎巴嫩战争档案放入跨区域当代艺术叙事。'],sourceUrl:'https://universes.art/en/venice-biennale/2003/contemporary-arab-representations/the-atlas-group-/-walid-raad',images:[],relations:[rel('展览','50th Venice Biennale — Contemporary Arab Representations','15 Jun–2 Nov 2003；curator Catherine David；overall artistic director Francesco Bonami.'),rel('媒介','DVD version','5:58；stills © The Atlas Group / Walid Raad；reproduction credit Haupt & Binder / Universes in Universe.')]}
    ],awards:[],exhibitions:['Venice Biennale — Contemporary Arab Representations, 2003','My Neck is Thinner Than a Hair: Engines — Sfeir-Semler Gallery, Hamburg, 2004','The Atlas Group — Hamburger Bahnhof, Berlin, 2006'],sources:[{label:'mumok · My Neck Is Thinner Than A Hair: Engines',url:'https://www.mumok.at/onlinesammlung/detail/my-neck-is-thinner-than-a-hair-engines-10314'},{label:'MoMA · Walid Raad artist audio / Engines detail',url:'https://www.moma.org/audio/playlist/280/3654'},{label:'Venice Biennale 2003 archive · The Atlas Group / Walid Raad',url:'https://universes.art/en/venice-biennale/2003/contemporary-arab-representations/the-atlas-group-/-walid-raad'}]
  },
  'zanele-muholi':{
    artistId:'zanele-muholi',
    projectCoverage:'作品级深化：继续拆解 Faces and Phases，加入 Fondation Louis Vuitton 十二张银盐/钡纸组合与 Centre Pompidou 的 Amogelang Senokwane 单件，明确拍摄规则、参与者能动性、长期重拍和网格展陈。',
    imageCoverage:'Fondation Louis Vuitton、Centre Pompidou、ICA Boston 与 Tate 均有官方/机构图像入口。明确版权 © Zanele Muholi；未发现开放再发布授权，因此不复制原图，保留来源与版权状态。',
    note:'Faces and Phases 不是一次性“拍摄黑人酷儿肖像”。它是持续近二十年的 living archive：参与者选择姿态、环境和服装，Muholi 与许多人维持长期关系并反复拍摄，同一人的不同 phase 会重新进入不断扩张的墙面网格。',
    projects:[
      {title:'Faces and Phases — Fondation Louis Vuitton twelve-print group',cluster:'portrait archive / gelatin silver / baryta paper / grid',period:'2011',summary:'Fondation Louis Vuitton 收藏的具体版本由十二张 gelatin silver prints on baryta paper 组成。Muholi 从 2006 年开始持续建立该系列，以相近距离拍摄人物，通常正面或略微侧身、室内或室外、黑白呈现。ICA Boston 的馆藏说明进一步指出，参与者可以选择自己的姿态、地点与服装，Muholi 又会在多年后重新拍摄愿意继续参与的人。因此十二张组合并非从“统一类型学”中抹去主体差异，而是把相似的摄影规则作为共同框架，让每个人的自我呈现、时间变化和观看者之间的目光关系更突出。',actions:['与 Black lesbian、trans、gender-nonconforming 等参与者建立合作关系，而非匿名街拍。','让参与者对姿态、拍摄环境和服装拥有选择权。','以黑白肖像、相近距离和直接/略侧的身体朝向建立系列内部视觉连续性。','使用 gelatin silver print，并在 Fondation Louis Vuitton 版本中落实为 baryta paper 上的十二张实体照片。','把多张肖像并列成群体结构；观众既逐张与人物对视，也从网格中读取社群、重复出现的人与时间变化。','持续回访并重新拍摄部分参与者，使“phase”成为真实时间跨度而非标题隐喻。'],sourceUrl:'https://www.fondationlouisvuitton.fr/en/collection/artworks/faces-and-phases',images:[],relations:[rel('收藏','Fondation Louis Vuitton','2011；twelve silver gelatin prints on baryta paper；© Zanele Muholi.'),rel('方法','ICA Boston collection text','Series begun 2006; sitters choose posture, setting and dress; Muholi often photographs participants across multiple years.')]},
      {title:'Amogelang Senokwane, District Six Cape Town — Faces and Phases',cluster:'specific portrait / gelatin silver print / visual activism',period:'2009',summary:'Centre Pompidou 馆藏的这件具体肖像把 Faces and Phases 从系列总述落实到单件：2009 年，gelatin-silver print，85.5 × 60.5 cm。它遵循系列的近距离黑白肖像原则，让人物以正面/近正面的身体与目光占据画面；作品不是进入参与者私人生活的纪实窥视，而是让被摄者以可控制的自我呈现面对公共观看。标题保存姓名与 District Six, Cape Town 地点，使人物不被缩减为抽象“身份类别”。当这张照片进入大型网格时，它同时保持个体姓名，又成为跨年份持续增长的社群档案中的一个节点。',actions:['在 Cape Town District Six 与 Amogelang Senokwane 合作完成肖像。','以黑白 gelatin-silver 工艺输出，而非彩色数字展示。','保留人物姓名与拍摄地点进入标题，让档案节点具有明确主体与地理信息。','制作 85.5 × 60.5 cm 实体照片，使人物接近身体尺度地面对观众。','在系列展陈中与其他 Faces and Phases 肖像并列，使单人目光与群体档案同时发生作用。'],sourceUrl:'https://www.centrepompidou.fr/en/ressources/oeuvre/cGb858',images:[],relations:[rel('收藏','Centre Pompidou, Paris','2009；gelatin-silver print；85.5 × 60.5 cm；acquired 2013；inventory AM 2013-259.'),rel('版权','Image rights','© Zanele Muholi; official museum image available but not copied without republication permission.')]},
      {title:'Faces and Phases — evolving grid / Tate survey version',cluster:'living archive / repeated portraits / installation grid / testimony',period:'2006–ongoing',summary:'Tate 对系列的展览说明强调它已经发展为数百件作品，并把 Faces 解释为被拍摄的人、Phases 解释为性别/性表达以及教育、工作、婚姻、年龄等生活阶段的变化。空间展示的关键因此是“增长”：大量肖像形成墙面网格，部分人物会在不同年份再次出现；空缺或中断也会让观众意识到档案并非封闭名单。观众必须在远处先面对一个规模庞大的集体肖像，再走近逐一读取面孔、姓名、地点与不同时间节点。',actions:['持续多年增加新肖像，而不是在某一年宣布系列完成。','回访同一参与者并把不同人生阶段纳入档案。','以墙面网格累积大量照片，使展陈规模成为作品意义的一部分。','在部分展示中结合 testimonies，使视觉肖像与第一人称经验并存。','让观看在“集体档案的总体规模”与“逐个主体的姓名/目光”之间来回切换。'],sourceUrl:'https://www.tate.org.uk/whats-on/tate-modern/zanele-muholi',images:[],relations:[rel('展览','Zanele Muholi — Tate Modern','Survey presentation; Tate describes Faces and Phases as an ongoing collective portrait and archive.'),rel('版权','Tate image credits','Official exhibition imagery credited © Zanele Muholi / courtesy artist and galleries; no local copy made.')]}
    ],awards:[],exhibitions:['Faces and Phases — ongoing since 2006','Zanele Muholi — Tate Modern, London','Faces and Phases — Fondation Louis Vuitton collection'],sources:[{label:'Fondation Louis Vuitton · Faces and Phases',url:'https://www.fondationlouisvuitton.fr/en/collection/artworks/faces-and-phases'},{label:'Centre Pompidou · Amogelang Senokwane, District Six Cape Town',url:'https://www.centrepompidou.fr/en/ressources/oeuvre/cGb858'},{label:'ICA Boston · From the series Faces and Phases',url:'https://www.icaboston.org/art/zanele-muholi/series-faces-and-phases/'},{label:'Tate · Zanele Muholi / Faces and Phases',url:'https://www.tate.org.uk/whats-on/tate-modern/zanele-muholi'}]
  }
};
