import type { ArtistArchive, ArchiveRelation } from './archiveData';
const rel = (kind: ArchiveRelation['kind'], label: string, detail?: string): ArchiveRelation => ({ kind, label, detail });

const venice='https://www.labiennale.org/en/art/2019/partecipants/nairy-baghramian';
const walker='https://www.walkerart.org/whats-on/nairy-baghramian-deformation-professionnelle/';
const privileged='https://www.walkerart.org/collections/artwork/privileged-points/';
const interview='https://www.walkerart.org/reader/surveying-the-survey-vincenzo-de-bellis-on-working-with-nairy-baghramian/';

export const archiveBatch158: Record<string, ArtistArchive> = {
  'venice-nairy-baghramian': {
    artistId:'venice-nairy-baghramian',
    projectCoverage:'6 个 body-proxy / support-structure / survey-critique / public-sculpture 节点深化 · 1999–2019',
    imageCoverage:'0 / 6 项目暂不使用不稳定外链图像',
    note:'深化既有艺术家，不新增目录人数。Baghramian 的核心不是一般意义上的 biomorphic sculpture，而是把 body extension、support、negative mould、museum threshold 与 exhibition format 本身变成雕塑问题。她经常让作品停在墙边、走廊、门口、室内/室外交界处，并把牙套、肩垫、裙撑、系船钩等“辅助身体或结构的东西”放大、失效或暴露出来。与强调完整人体形象的 figurative sculpture 不同，她通过缺席身体的 proxy 来讨论身体；与单纯 site-specific sculpture 不同，她还会反过来处理 retrospective、collection、commission 等制度框架。',
    projects:[
      {title:'Body-extension / support-object vocabulary',cluster:'dental retainer / shoulder pad / brace / body proxy',period:'1999–ongoing',summary:'Walker 对其长期实践的概括指出，她反复使用 dental retainer、shoulder pad 等容易被忽略的身体延伸物作为隐喻。作品往往介于 abstraction 与 figuration 之间：人体并不出现，但支撑、矫正、保护或约束身体的结构成为身体的替身。',actions:['从 everyday support / corrective object 提取形态而非直接塑造人体','改变 familiar object 的尺度，使功能性形态失去正常用途','并置 rubber / steel、wood / wax、cast element / photography 等不稳定材料关系','让 brace、joint、mould、appendage 同时具有 bodily 与 architectural reading','把 support 从隐藏工程结构提升为可见主题'],sourceUrl:walker,images:[],relations:[rel('机构','Walker Art Center','2017 survey + permanent public commission')]},
      {title:'Moorings',cluster:'oversized support / hidden infrastructure / dock hardware',period:'2006–2016',summary:'Moorings 放大用于固定船只的金属系船结构。Vincenzo de Bellis 对展览的说明特别强调：原本被忽略、只负责“支撑/固定”的对象被放大后，support 本身成为 sculpture；在 Déformation Professionnelle 中又出现表面仿佛被剥到骨架的版本。',actions:['选择 normally overlooked fastening hardware 作为起点','放大 hook / mooring scale 使功能对象失去服务角色','改变 surface treatment，让版本之间形成材料记忆','让 support object 从背景基础设施转成 foreground sculpture'],sourceUrl:interview,images:[],relations:[]},
      {title:'Déformation Professionnelle',cluster:'anti-retrospective / rejected ideas / institutional self-critique',period:'2016–2018',summary:'面对 retrospective / survey 邀请，Baghramian 没有按时间线重展旧作，而根据 1999–2016 的 18 组既有作品制造全新的对应物：被拒绝的方案、工作材料、变体与旧系列的负形重新进入展览。她称之为“surveying the survey”，把职业回顾机制本身变成创作材料。',actions:['拒绝 conventional chronological retrospective','从 18 组旧作中抽取 rejected idea、working material 与 formal residue','为过去作品制作新的 counterpart 而非复制原作','让 mould / leftover / negative / support 暴露制作过程中通常被隐藏的部分','根据 S.M.A.K. 与 Walker 两个场地重新组织 sculpture 与 architecture 的关系'],sourceUrl:walker,images:[],relations:[rel('策展人','Vincenzo de Bellis','Walker presentation curator'),rel('策展人','Victoria Sung','Walker presentation co-curator'),rel('策展人','Martin Germann','S.M.A.K. presentation curator'),rel('机构','S.M.A.K., Ghent','co-organizer · 2016–2017'),rel('机构','Walker Art Center','co-organizer · 2017–2018')]},
      {title:'Stay Downers',cluster:'excluded class / balancing body / retrospective counter-work',period:'2016',summary:'作为早期 Class Reunion 的反向回应，Stay Downers 以被留级、落在集体之后的人为标题逻辑。不同“characters”承担重量并保持近乎笨拙的平衡，使 social classification、volume、gravity 与 exclusion 同时进入雕塑。',actions:['把 earlier body of work 转写为反向 counterpart','以 school nickname / excluded student 建立 character system','使用 rounded forms 与实际重量制造视觉轻盈和结构负担的冲突','让 balancing act 成为 social belonging / exclusion 的空间隐喻'],sourceUrl:interview,images:[],relations:[rel('展览','Déformation Professionnelle','2016–2018')]},
      {title:'Privileged Points',cluster:'public sculpture / hillside threshold / bronze support-form',period:'2017',summary:'Walker 委托的三件式公共雕塑位于 Wurtele Upper Garden 山坡，以 bronze / paint 制作。它把 Baghramian 对 support、边界和身体延伸的研究推到永久公共空间，同时让“privileged point”既指观看位置，也打开制度、空间与 privilege 的语义。',actions:['将 multipart sculpture 分散在 hillside 而非集中 pedestal','以 bronze 固化原本带有 flexible / support-object 感的形态','让作品同时面对 museum architecture、garden 与城市观看','利用 vantage point 使作品标题与实际观看位置互相作用'],sourceUrl:privileged,images:[],relations:[rel('委托','Walker Art Center','commissioned 2017'),rel('收藏','Walker Art Center','permanent collection · accession 2017.19.1-.3')]},
      {title:'Maintainers / Dwindlers — Venice 2019',cluster:'support-failure / wax-cork-aluminium / glass appendage',period:'2019',summary:'Venice 2019 把她两条长期逻辑并置：Maintainers 中 aluminium、wax、cork 与 braces 形成既保护又压迫的真实支撑关系；Dwindlers 则把 glass appendage 沿建筑边缘铺开，在 duct、intestine、ornament 与 ruin 之间摇摆。',actions:['让支撑件承担真实 structural dependency 而非只做象征','把 fragile wax / cork 与 harder cast material 放入相互制约关系','沿 corridor / architectural edge 分散作品','保留 organ / machine / ruin 多重识别而不固定单一 figurative reading','把 potential failure / collapse 作为作品结构的一部分'],sourceUrl:venice,images:[],relations:[rel('展览','May You Live In Interesting Times — 58th Venice Biennale','2019 · Central Pavilion + Arsenale')]}
    ],
    awards:['Schering Stiftung Art Award — 2007','Hector Prize — 2012','Arnold Bode Prize — 2014'],
    exhibitions:['Déformation Professionnelle — S.M.A.K., Ghent, 2016–2017','Déformation Professionnelle — Walker Art Center, 2017–2018','documenta 14 — Kassel, 2017','Skulptur Projekte Münster — 2017','May You Live In Interesting Times — Venice Biennale 2019'],
    sources:[{label:'La Biennale · Nairy Baghramian 2019',url:venice},{label:'Walker Art Center · Déformation Professionnelle',url:walker},{label:'Walker Collection · Privileged Points',url:privileged},{label:'Walker · Surveying the Survey',url:interview}]
  }
};
