import type { ArtistArchive, ArchiveImage, ArchiveRelation } from './archiveData';

const img = (url: string, title: string, credit: string, sourceUrl: string, sourceLabel: string): ArchiveImage => ({ url, title, credit, sourceUrl, sourceLabel });
const rel = (kind: ArchiveRelation['kind'], label: string, detail?: string): ArchiveRelation => ({ kind, label, detail });

export const archiveBatch10Existing: Record<string, ArtistArchive> = {
  'rinko-kawauchi': { artistId: 'rinko-kawauchi', projectCoverage: '6 个核心摄影书 / 长期系列已完成第一轮 · 2001–2022', imageCoverage: '', note: '从 2001 年三本书到 M/E，重点补“微小日常—生命循环—土地火烧—宏观生态”的变化，同时把摄影书编辑作为方法。', projects: [
    { title: 'Utatane / Hanabi / Hanako', cluster: 'photobook / everyday fragments', period: '2001', summary: '同年推出三本摄影书，以微小日常、烟花、人物和偶然光线建立早期视觉语法。', actions: ['日常随身拍摄', '方形彩色画幅', '摄影书 sequence'], sourceUrl: 'https://rinkokawauchi.com/en/works/', images: [], relations: [rel('出版', 'Utatane / Hanabi / Hanako', '2001')] },
    { title: 'AILA / Cui Cui', cluster: 'life cycle / family / birth and death', period: '2004–2005', summary: '从动物出生、食物、家庭和死亡等非常轻的片段建立生命循环，不依赖单一叙事。', actions: ['近距离观察', '柔和自然光', '跨主题编辑'], sourceUrl: 'https://rinkokawauchi.com/en/works/', images: [], relations: [rel('出版', 'AILA / Cui Cui', '2004–2005')] },
    { title: 'Illuminance', cluster: 'light / everyday / photobook', period: '2011', summary: '通过光、颜色、形状和生命状态把彼此无关的瞬间编成连续视觉节奏。', actions: ['长期日常拍摄', '颜色 / 形状配对', '摄影书编辑'], sourceUrl: 'https://rinkokawauchi.com/en/publications/430/', images: [img('https://d7hftxdivxxvm.cloudfront.net/?height=1883&quality=80&resize_to=fit&src=https%3A%2F%2Fd32dm0rphc51dk.cloudfront.net%2FyeAdvef9-LtqEv3R85aqZQ%2Flarge.jpg&width=1920', 'Illuminance', '© Rinko Kawauchi', 'https://rinkokawauchi.com/en/publications/430/', 'Artist website')], relations: [rel('出版', 'Illuminance', 'Aperture / Kehrer / Xavier Barral, 2011')] },
    { title: 'Ametsuchi', cluster: 'controlled burn / land / ritual', period: '2013', summary: '以 4×5 相机拍摄阿苏传统烧畑 / 控制性烧荒，将火、土地恢复和祈祷并置。', actions: ['4×5 大画幅', '长期回访烧荒', '景观与仪式并置'], sourceUrl: 'https://rinkokawauchi.com/en/works/', images: [img('https://a.1stdibscdn.com/rinko-kawauchi-1972-japanese-photography-untitled-from-the-series-ametsuchi-rinko-kawauchi-landscape-fire-hill-for-sale/a_12801/a_68901921602582261546/Christophe_Guye_Galerie_Rinko_Kawauchi_RK_041_master.jpg', 'Ametsuchi', '© Rinko Kawauchi', 'https://rinkokawauchi.com/en/works/', 'Artist / gallery documentation')], relations: [rel('出版', 'Ametsuchi', '2013')] },
    { title: 'Halo', cluster: 'cycles / ritual / light', period: '2017', summary: '继续从自然循环与集体仪式寻找光、火和身体动作之间的节奏。', actions: ['摄影', '录像', '摄影书编辑'], sourceUrl: 'https://rinkokawauchi.com/en/works/', images: [], relations: [rel('出版', 'Halo', '2017')] },
    { title: 'M/E', cluster: 'micro / macro ecology', period: '2019–2022', summary: '从冰岛冰川、北海道雪地到疫情期间家庭和家中生命，把微观日常与行星尺度放进同一项目。', actions: ['跨地域拍摄', '家庭日常', '景观', '展览空间重编'], sourceUrl: 'https://rinkokawauchi-me.exhibit.jp/en/works/', images: [], relations: [rel('展览', 'Tokyo Opera City / Shiga Museum of Art', '2022–2023')] }
  ], awards: ['Kimura Ihei Award 2002', 'ICP Infinity Award 2009', 'Deutsche Börse Photography Prize shortlist 2012'], exhibitions: ['M/E — Tokyo Opera City 2022', 'At the Edge of the Everyday World — Arnolfini 2024'], sources: [{ label: 'Rinko Kawauchi official works', url: 'https://rinkokawauchi.com/en/works/' }] },
  'gauri-gill': { artistId: 'gauri-gill', projectCoverage: '5 个长期 / 合作 / 社区项目已完成第一轮 · 1999–现在', imageCoverage: '', note: '把 Notes from the Desert 内部子系列与两个重要合作项目拆开，突出共同作者和长期关系。', projects: [
    { title: 'Notes from the Desert', cluster: 'Rajasthan / long-term archive', period: '1999–', summary: '长期回访 Rajasthan 西部边缘化乡村社群，形成包含肖像、家庭、学校、墓地和生活仪式的庞大档案。', actions: ['长期回访', '黑白摄影', '朋友关系', '子系列持续累积'], sourceUrl: 'https://gaurigill.com/works/', images: [img('https://static-assets.artlogic.net/w_2400%2Ch_2400%2Cc_limit%2Cf_auto%2Cfl_lossy%2Cq_auto/artlogicstorage/vadehraart/images/view/610ac783f7fdb9ac3851985e1533c10dj/vadehraartgallery-gauri-gill-jannat-barmer-from-the-series-notes-from-the-desert-1999-ongoing.jpg', 'Jannat, Barmer', '© Gauri Gill', 'https://gaurigill.com/works/', 'Artist / Vadehra documentation')], relations: [] },
    { title: 'Balika Mela', cluster: 'tent studio / girls / self-presentation', period: '2003 / 2010', summary: '在女孩集市搭建临时摄影棚，让参与者自己决定朋友、道具和姿势，现场打印并回赠照片。', actions: ['临时照相馆', '参与者自选姿势 / 道具', '现场拍摄 / 回赠'], sourceUrl: 'https://gaurigill.com/works/', images: [], relations: [rel('出版', 'Balika Mela', 'Edition Patrick Frey, 2012')] },
    { title: '1984', cluster: 'memory / anti-Sikh violence / notebooks', period: '2014', summary: '回到 1984 年反锡克暴力的记忆空白，以采访、照片和文字建立可下载的纪念文件。', actions: ['历史回访', '采访', '摄影 / 文本', '开放下载'], sourceUrl: 'https://gaurigill.com/bio/', images: [], relations: [] },
    { title: 'Fields of Sight', cluster: 'photography + Warli drawing / collaboration', period: '2013–', summary: 'Gill 的黑白景观照片由 Warli 艺术家 Rajesh Vangad 直接绘入故事、记忆和不可见知识。', actions: ['共同选片', '摄影打印', 'Vangad 手绘覆盖', '双作者文本'], sourceUrl: 'https://gaurigill.com/works/', images: [img('https://d2w8mc4ffkqyzk.cloudfront.net/i/34/a3tqTZYs_EsVqtP.jpeg', 'Fields of Sight — book spread', '© Gauri Gill & Rajesh Vangad', 'https://gaurigill.com/works/', 'Project / publication documentation')], relations: [rel('出版', 'Fields of Sight', 'Edition Patrick Frey, 2023')] },
    { title: 'Acts of Appearance', cluster: 'Adivasi masks / collaborative staging', period: '2015–', summary: '与 Kokna 和 Warli 纸浆面具艺术家及村民共同创造现代人物面具，再在真实村庄环境中表演和拍摄。', actions: ['面具艺术家合作', '共同设计当代角色', '村庄场景表演', '彩色摄影'], sourceUrl: 'https://gaurigill.com/works/', images: [], relations: [rel('出版', 'Acts of Appearance', '2022'), rel('奖项', 'Prix Pictet', 'winner 2023')] }
  ], awards: ['Prix Pictet 2023', 'Grange Prize 2011'], exhibitions: ['The Photographers’ Gallery 2024', 'MoMA PS1 2018'], sources: [{ label: 'Gauri Gill official works', url: 'https://gaurigill.com/works/' }] },
  'samuel-fosso': { artistId: 'samuel-fosso', projectCoverage: '6 个自画像 / 历史角色项目已完成第一轮 · 1975–2017', imageCoverage: '', note: '从十几岁工作室自拍到历史人物重演，补出“身体作为图像模板”的发展。', projects: [
    { title: '70s Lifestyle', cluster: 'studio self-portrait / youth style', period: '1975–1978', summary: '商业照相馆工作结束后用剩余胶片自拍，以喇叭裤、厚底鞋和姿势测试男性气质与流行文化。', actions: ['自拍定时器', '服装造型', '工作室布景', '黑白摄影'], sourceUrl: 'https://www.barbican.org.uk/sites/default/files/documents/2020-08/Masculinities_Extended%20Captions.pdf', images: [], relations: [] },
    { title: 'Tati Series', cluster: 'commercial commission / invented personas', period: '1997', summary: '为 Tati 商场委托制作彩色自画像，扮演“酋长、商人、女性”等夸张人物，开始更明确的历史 / 类型角色扮演。', actions: ['服装与道具', '彩色工作室布景', '角色表演'], sourceUrl: 'https://www.tate.org.uk/art/artists/samuel-fosso-11850', images: [img('https://media.mutualart.com/Images/2022_10/25/18/182144225/samuel-fosso-the-chief-who-sold-africa-t-HAW9U.Jpeg', 'The Chief Who Sold Africa to the Colonialist', '© Samuel Fosso', 'https://www.tate.org.uk/art/artists/samuel-fosso-11850', 'Tate / secondary documentation')], relations: [] },
    { title: 'African Spirits', cluster: 'Pan-African history / reenactment', period: '2008', summary: '重演 Angela Davis、Patrice Lumumba、Martin Luther King Jr. 等黑人政治文化人物的经典肖像。', actions: ['档案肖像研究', '服装 / 发型 / 眼镜复刻', '大型黑白打印'], sourceUrl: 'https://www.moma.org/collection/works/214519', images: [img('https://www.moma.org/media/W1siZiIsIjU0MDM0NSJdLFsicCIsImNvbnZlcnQiLCItcXVhbGl0eSA5MCAtcmVzaXplIDIwMDB4MTQ0MFx1MDAzZSJdXQ.jpg?sha=dadc66e98553aabf', 'African Spirits', '© Samuel Fosso', 'https://www.moma.org/collection/works/214684', 'MoMA')], relations: [rel('收藏', 'MoMA', '14 works online in artist archive')] },
    { title: 'The Emperor of Africa', cluster: 'Mao / political iconography', period: '2013', summary: '以毛泽东的不同经典政治肖像为模板，通过同一身体讨论非洲与中国政治图像的传播。', actions: ['政治图像研究', '自我表演', '彩色摄影'], sourceUrl: 'https://www.jeanmarkpatras.com/artists/samuel-fosso', images: [], relations: [] },
    { title: 'SIXSIXSIX', cluster: 'Polaroid / serial self-portrait', period: '2015', summary: '以数百张即时成像自拍积累表情与身份变化，把同一面孔推向近乎档案式数量。', actions: ['Polaroid 自拍', '重复固定构图', '大规模序列'], sourceUrl: 'https://www.autograph.org.uk/exhibitions/samuel-fosso', images: [], relations: [] },
    { title: 'Black Pope', cluster: 'religion / authority / self-performance', period: '2017', summary: '以教皇视觉语言和黑人身体重构宗教权威图像。', actions: ['服装造型', '宗教肖像引用', '工作室摄影'], sourceUrl: 'https://www.autograph.org.uk/exhibitions/samuel-fosso', images: [], relations: [] }
  ], awards: [], exhibitions: ['Autograph / Barbican survey contexts', 'MoMA — Ideas of Africa 2025–2026'], sources: [{ label: 'MoMA Samuel Fosso', url: 'https://www.moma.org/artists/67095-samuel-fosso' }] },
  'ishiuchi-miyako': { artistId: 'ishiuchi-miyako', projectCoverage: '7 个战后城市 / 身体痕迹 / 遗物系列已完成第一轮 · 1976–现在', imageCoverage: '', note: '从城市粗颗粒黑白到皮肤和遗物近摄，补出她如何把“表面”持续当作时间的载体。', projects: [
    { title: 'Yokosuka Story', cluster: 'postwar city / memory', period: '1976–1977', summary: '回到童年生活、美国海军基地所在的横须贺，以强颗粒黑白摄影面对个人恐惧与战后占领记忆。', actions: ['城市徒步', '黑白胶片', '自设暗房', '高颗粒放大'], sourceUrl: 'https://www.getty.edu/art/exhibitions/ishiuchi/', images: [], relations: [rel('展览', 'Nikon Salon', '1977')] },
    { title: 'Apartment', cluster: 'interior / decay / postwar housing', period: '1977–1978', summary: '进入老旧公寓拍摄墙面、门窗和居住痕迹，把建筑表皮作为时间记录。', actions: ['室内黑白摄影', '墙面 / 结构近摄'], sourceUrl: 'https://www.getty.edu/art/exhibitions/ishiuchi/', images: [], relations: [] },
    { title: '1·9·4·7', cluster: 'body / same-age women', period: '1988–1989', summary: '拍摄与艺术家同年出生女性的身体表面，以出生年份和职业替代完整人物叙事。', actions: ['身体局部近摄', '同龄人选择', '黑白打印'], sourceUrl: 'https://www.getty.edu/art/exhibitions/ishiuchi/', images: [], relations: [] },
    { title: 'Scars', cluster: 'skin / wound / photographic trace', period: '1991–2003', summary: '极近距离拍摄伤疤，把身体上的旧伤理解成过去留下的“摄影式印记”。', actions: ['伤疤近摄', '黑白高反差', '匿名化'], sourceUrl: 'https://www.sfmoma.org/publication/focus-japanese-photography/', images: [], relations: [] },
    { title: 'Mother’s', cluster: 'mother / clothing / cosmetics / absence', period: '1999–2005', summary: '先拍母亲身体和伤痕；母亲去世后转而拍衣物、口红和内衣，使遗物替代身体。', actions: ['身体近摄', '遗物摄影', '彩色大尺幅'], sourceUrl: 'https://www.getty.edu/art/exhibitions/ishiuchi/', images: [img('https://images.squarespace-cdn.com/content/v1/57825361440243db4a4b7830/1712201463758-TM7QUOCR464AUF2IDM03/gm_35287401-web.jpg', 'Mother’s', '© Ishiuchi Miyako', 'https://www.metmuseum.org/art/collection/search/789567', 'The Met')], relations: [rel('展览', 'Japan Pavilion — Venice Biennale', '2005')] },
    { title: 'hiroshima', cluster: 'survivor clothing / lightbox', period: '2007–', summary: '拍摄广岛原爆后保存下来的衣物和个人物件，常将衣服放在 lightbox 上，使织物细节和穿着者缺席同时出现。', actions: ['博物馆藏品合作', '遗物摄影', '透射光 / lightbox', '彩色输出'], sourceUrl: 'https://www.getty.edu/art/exhibitions/ishiuchi/', images: [], relations: [] },
    { title: 'Frida by Ishiuchi', cluster: 'Frida Kahlo / personal belongings', period: '2012–2013', summary: '拍摄 Frida Kahlo 的衣物、鞋、药品和个人物件，以遗物而非肖像重新接近其身体。', actions: ['档案许可', '物件近摄', '颜色 / 磨损细节'], sourceUrl: 'https://www.ishiuchimiyako.com/', images: [], relations: [] }
  ], awards: ['Hasselblad Award 2014'], exhibitions: ['Japan Pavilion — Venice 2005', 'Getty — Postwar Shadows 2015–2016'], sources: [{ label: 'Getty — Postwar Shadows', url: 'https://www.getty.edu/art/exhibitions/ishiuchi/' }] },
  'lieko-shiga': { artistId: 'lieko-shiga', projectCoverage: '5 个闪光 / 社群 / 观看关系项目已完成第一轮 · 2002–2019', imageCoverage: '', note: '按官方 works 顺序补 Lilly、Canary、Rasen Kaigan、Blind Date、Human Spring。', projects: [
    { title: 'Lilly', cluster: 'early staged photography / body', period: '2002–2005', summary: '早期项目已经使用强灯光、身体动作和不稳定空间制造介于现实与梦境的摄影。', actions: ['编排人物', '强闪光', '暗环境'], sourceUrl: 'https://www.liekoshiga.com/works', images: [], relations: [rel('出版', 'Lilly', '2007')] },
    { title: 'CANARY', cluster: 'body / fear / constructed reality', period: '2007', summary: '高度人工的场景、夜间光线和身体状态被拍成近乎神话的现实。', actions: ['场景介入', '夜间摄影', '闪光', '摄影书编辑'], sourceUrl: 'https://www.liekoshiga.com/works', images: [], relations: [rel('展览', 'Foam Amsterdam', '2013')] },
    { title: 'RASEN KAIGAN', cluster: 'Kitakama / community / memory', period: '2008–2012', summary: '在宫城县北釜长期生活并担任社区摄影师，将居民关系、地方仪式、死亡记忆和海啸后的影像残片纳入同一项目。', actions: ['长期居住', '社区委托摄影', '夜间闪光', '地方叙事收集', '大型空间安装'], sourceUrl: 'https://www.liekoshiga.com/works', images: [img('https://i.pinimg.com/originals/64/8b/93/648b9332d110cdc33444a6ba7351c962.jpg', 'RASEN KAIGAN', '© Lieko Shiga', 'https://www.moma.org/artists/47214-lieko-shiga', 'MoMA / project documentation')], relations: [rel('展览', 'Sendai Mediatheque', '2012–2013'), rel('收藏', 'MoMA', 'multiple works')] },
    { title: 'Blind Date', cluster: 'seeing / being seen / portrait', period: '2017', summary: '围绕看与被看的关系组织摄影、文本和展览，继续让肖像成为不稳定的共同事件。', actions: ['肖像', '互动 / 关系设计', '摄影书'], sourceUrl: 'https://www.liekoshiga.com/works', images: [], relations: [rel('展览', 'Marugame Genichiro-Inokuma Museum', '2017')] },
    { title: 'Human Spring', cluster: 'crowd / body / social pressure', period: '2019', summary: '密集人群、身体堆叠、异常闪光和巨大图像共同制造社会身体像春季暴发般失控的经验。', actions: ['群体编排', '强闪光', '大型打印', '空间密集安装'], sourceUrl: 'https://tokyocontemporaryartaward.jp/en/winners/2021-2023/winner01.html', images: [img('https://www.artagenda.jp/img/event/3109/main_2.jpg', 'Human Spring', '© Lieko Shiga', 'https://tokyocontemporaryartaward.jp/en/winners/2021-2023/winner01.html', 'Tokyo Contemporary Art Award / exhibition documentation')], relations: [rel('展览', 'Tokyo Photographic Art Museum', '2019')] }
  ], awards: ['Tokyo Contemporary Art Award 2021–2023'], exhibitions: ['MoMA — Ocean of Images 2015', 'Human Spring — TOP Museum 2019'], sources: [{ label: 'Lieko Shiga official works', url: 'https://www.liekoshiga.com/works' }] },
  'nikki-s-lee': { artistId: 'nikki-s-lee', projectCoverage: '4 个身份表演 / 裁切 / 跨文化观看项目已完成第一轮 · 1997–2008', imageCoverage: '', note: '把 Projects 内的群体融入与之后 Parts、Layers 分开，避免只把她理解成“换装自拍”。', projects: [
    { title: 'Projects', cluster: 'subculture immersion / snapshot', period: '1997–2001', summary: '进入 punk、yuppie、lesbian、hip-hop、tourist、senior 等社群，数周或数月学习服装、姿态和行为，再让朋友或路人拍照。', actions: ['长期进入社群', '外观 / 行为学习', '傻瓜相机', '由他人按下快门'], sourceUrl: 'https://www.metmuseum.org/art/collection/search/284362', images: [img('https://d7hftxdivxxvm.cloudfront.net/?height=800&quality=80&resize_to=fit&src=https%3A%2F%2Fd32dm0rphc51dk.cloudfront.net%2FcA0zvoGnSLB1Z2msw-g2IA%2Fmain.jpg&width=800', 'The Yuppie Project (2)', '© Nikki S. Lee', 'https://www.metmuseum.org/art/collection/search/284362', 'The Met')], relations: [rel('收藏', 'The Met', 'Yuppie / Ohio project works')] },
    { title: 'The Ohio Project', cluster: 'working-class identity / immersion', period: '1999', summary: '在 Ohio trailer park 环境中融入居民生活，继续测试阶级身份如何通过外观、姿态和合影被读取。', actions: ['社区进入', '外观变化', '他人快照'], sourceUrl: 'https://www.metmuseum.org/art/collection/search/284363', images: [], relations: [] },
    { title: 'Parts', cluster: 'relationship / cropped partner', period: '2002–2004', summary: '摆拍亲密关系场景后，把男性伴侣大部分裁出画面，只留下手、肩或局部身体，使“缺席的另一半”成为结构。', actions: ['双人编排', '关系场景', '后期裁切', '保留男性局部'], sourceUrl: 'https://www.vsf.la/artworks/2809-nikki-s.-lee-part-2-2003/', images: [img('https://static-assets.artlogic.net/w_1600%2Ch_1600%2Cc_limit%2Cf_auto%2Cfl_lossy%2Cq_auto/artlogicstorage/vsf/images/view/32584596aeb06acb3b628a6d156e2888j/varioussmallfires-nikki-s.-lee-part-2-2003.jpg', 'Part (2)', '© Nikki S. Lee', 'https://www.vsf.la/artworks/2809-nikki-s.-lee-part-2-2003/', 'Various Small Fires')], relations: [] },
    { title: 'Layers', cluster: 'portrait drawing / cultural translation', period: '2008', summary: '在不同城市请街头肖像画家分别画她，再把多张透明肖像叠在 lightbox 上摄影，把“别人怎么看我”变成合成脸。', actions: ['委托街头肖像', '透明纸叠层', 'lightbox', '再摄影'], sourceUrl: 'https://www.vsf.la/artists/nikki-s.-lee/', images: [], relations: [] }
  ], awards: [], exhibitions: ['The Met collection', 'Projects series international exhibitions'], sources: [{ label: 'The Met — Nikki S. Lee', url: 'https://www.metmuseum.org/art/collection/search/284362' }] }
};
