import type { ArtistArchive, ArchiveProject, ArchiveRelation } from './archiveData';
const rel=(kind:ArchiveRelation['kind'],label:string,detail?:string):ArchiveRelation=>({kind,label,detail});
const project=(p:ArchiveProject)=>p;

export const archiveBatch286:Record<string,ArtistArchive>={
'wolfgang-tillmans':{
artistId:'wolfgang-tillmans',
projectCoverage:'深化 Wolfgang Tillmans：不把他缩减为1990年代青年文化摄影师，而是补足其反等级安装、无相机抽象摄影、纸张作为物体、图像尺度与传播载体，以及 Fondation Beyeler 2017 综合展所呈现的三十年方法演变。',
imageCoverage:'登记 MoMA 与 Fondation Beyeler 的作品、馆藏和展览入口。图像版权归艺术家及相应机构，仓库仅保存研究链接与作品结构信息，不复制受限展览图片。',
note:'Tillmans 的关键不是某一种题材，而是持续测试“什么可以成为照片、照片以什么尺度和物质状态存在、不同图像为什么能在同一面墙上共存”。人物、静物、政治现场、天文图像、复印件、暗房抽象和音乐因此不是互相割裂的阶段，而是一套关于观看与图像生产的长期实验。',
projects:[
project({title:'MoMA installation (1986–1998) — anti-hierarchical wall as a photographic syntax',cluster:'installation / display / scale / editorial logic',period:'works 1986–1998; acquired/installed as a series',summary:'MoMA 将30件作品作为一个 installation series 在线登记，从 Lacanau (Self)、me in the shower、AIDS, General Idea、Lutz & Alex、Smokin’ Jo 到 socks on radiator。其意义不只在单幅名作，而在异质图像被并置：肖像、朋友、夜生活、静物、新闻/政治痕迹与日常观察不依照传统“大作品/小作品”等级排序。MoMA 对 Tillmans 的介绍特别强调其墙面由巨幅 inkjet、杂志跨页到口袋尺寸照片共同组成，并且这种看似随意的墙面实际上经过精确构造。',actions:['把不同题材、尺寸、印刷方式和传播来源的照片置于同一观看场域。','拒绝只用统一画框与统一中心线组织摄影展，改以间距、尺度、视觉节奏建立关系。','把杂志工作、私人图像与美术馆作品放入同一作者语言，而非把编辑摄影视为低一级材料。','让“安装”成为作品意义的一部分：观众需要在远看整体和靠近小图之间不断移动。'],sourceUrl:'https://www.moma.org/collection/works/series/162687',images:[],relations:[rel('收藏','Museum of Modern Art, New York','MoMA 将1986–1998年的30件作品作为 installation series 登记，提供研究其早期墙面语法的机构入口。'),rel('媒介','magazine spread / small print / monumental inkjet','MoMA 强调 Tillmans 的装置横跨不同印刷尺度和传播形式。')] }),
project({title:'Cameraless abstractions — photographic paper becomes image, surface and object',cluster:'abstraction / darkroom / cameraless photography / materiality',period:'late 1990s onward',summary:'Fondation Beyeler 对 Tillmans 的实践概括指出，他自1990年代末越来越多地制作无相机抽象图像，直接在摄影纸上和摄影纸本身工作，其中一些作品获得近乎雕塑性的物体属性。这条线修正了“Tillmans=生活纪录”的常见印象：摄影不再必须先有外部对象，曝光、化学过程、纸张、折叠和表面本身都可以成为图像发生的现场。',actions:['取消相机作为必要中介，直接处理感光材料。','把摄影纸从透明的图像载体转化为可被观看的物质对象。','让偶然、化学反应和制作控制之间保持张力。','把抽象作品与人物、静物和风景共同安装，拒绝具象/抽象的媒介等级。'],sourceUrl:'https://www.fondationbeyeler.ch/en/exhibitions/wolfgang-tillmans',images:[],relations:[rel('展览','Fondation Beyeler — Wolfgang Tillmans','2017综合展明确把有相机与无相机作品、传统题材与抽象实验放在同一实践框架中。'),rel('方法','photographic paper as material','Beyeler 指出部分无相机作品发展出雕塑性、物体性的特征。')] }),
project({title:'Paper drop — paper photographs its own condition of becoming image',cluster:'still life / paper / self-reflexive photography / objecthood',period:'series; including Paper drop (reversed) II, 2011',summary:'Paper drop 系列把一张弯曲、卷起的纸置于摄影机前，使纸既是被摄对象，也指向照片最终赖以存在的物质表面。2017 Fondation Beyeler 展览资料列出 Paper drop (reversed) II (2011)，并把这类作品置于 Tillmans 对“made/fabricated picture”的长期研究中。它把一个极简单的静物变成摄影自指结构：二维纸张被弯曲成空间，再被摄影压回二维图像。',actions:['将纸张弯曲形成明暗、空间和内部/外部表面的变化。','拍摄纸这一摄影常见承载物，使载体反过来成为主体。','利用二维→三维→二维的转换暴露摄影的空间幻觉。','把形式实验保留在日常材料尺度，而不是依赖宏大题材。'],sourceUrl:'https://www.fondationbeyeler.ch/fileadmin/user_upload/Presse/Medienmitteilungen_E/E_Tillmans_Dossier.pdf',images:[],relations:[rel('展览','Fondation Beyeler 2017','官方媒体资料列出 Paper drop (reversed) II, 2011。'),rel('研究','image as made object','Beyeler 将 Tillmans 的核心描述为图像的制造，而非摄影对现实的忠实复制。')] }),
project({title:'Wolfgang Tillmans — Fondation Beyeler 2017 as a map of practice evolution',cluster:'retrospective / institutional network / photography expanded',period:'28 May–1 Oct 2017',summary:'Fondation Beyeler 2017大型个展展出约200件1986/1989至2017年的摄影作品及新的视听装置，是该馆首次对摄影媒介进行如此全面的专题讨论。展览把1990年代的世代肖像、肖像/静物/风景、无相机抽象、复印机实验以及视听作品放在一起，因此特别适合作为网站的关系网络枢纽：Tillmans 的演变不是离开摄影，而是不断扩大“摄影图像”可以如何被生产、安装和接收。',actions:['用约三十年的作品建立从生活观察到材料实验的连续谱，而不是分成互不相干的风格时期。','将传统摄影类型与抽象、复印和视听作品共同纳入“image making”。','让展览空间本身继续承担 Tillmans 的反等级安装逻辑。','把摄影与音乐/视听实践连接，显示其媒介边界持续扩张。'],sourceUrl:'https://www.fondationbeyeler.ch/en/exhibitions/wolfgang-tillmans',images:[],relations:[rel('展览','Fondation Beyeler, Riehen/Basel','28 May–1 Oct 2017；约200件摄影作品并包含新的视听装置。'),rel('策展','Theodora Vischer','Fondation Beyeler Senior Curator；官方展览指南记录其与艺术家密切合作策划。'),rel('收藏','Fondation Beyeler Collection','机构在展览前已收藏 Tillmans 的重要作品群，后续数字馆藏持续提供作品级入口。')] })
],
awards:['Turner Prize — 2000'],
exhibitions:['MoMA installation (1986–1998) — Museum of Modern Art collection series','Wolfgang Tillmans — Fondation Beyeler — 28 May–1 Oct 2017'],
sources:[{label:'MoMA — Wolfgang Tillmans artist page',url:'https://www.moma.org/artists/8044-wolfgang-tillmans'},{label:'MoMA — installation (1986–1998)',url:'https://www.moma.org/collection/works/series/162687'},{label:'Fondation Beyeler — Wolfgang Tillmans exhibition',url:'https://www.fondationbeyeler.ch/en/exhibitions/wolfgang-tillmans'},{label:'Fondation Beyeler — 2017 exhibition guide',url:'https://www.fondationbeyeler.ch/fileadmin/user_upload/Ausstellungen/Vergangene_Ausstellungen/Wolfgang_Tillmans/Saalheft_TILLMANS_EN.pdf'},{label:'Fondation Beyeler — 2017 press material',url:'https://www.fondationbeyeler.ch/fileadmin/user_upload/Presse/Medienmitteilungen_E/E_Tillmans_Dossier.pdf'}]
}
};
