import type { ArtistArchive, ArchiveRelation } from './archiveData';

const rel=(kind:ArchiveRelation['kind'],label:string,detail?:string):ArchiveRelation=>({kind,label,detail});

export const archiveBatch259:Record<string,ArtistArchive>={
  'thomas-ruff':{
    artistId:'thomas-ruff',
    projectCoverage:'作品级深化：以 jpeg 系列为核心，把“互联网图像”拆成来源选择、JPEG压缩结构、低分辨率放大、色块/像素显影与巨幅C-print输出等实际制作步骤，并落到两件具体馆藏作品。',
    imageCoverage:'MoMA、Smithsonian American Art Museum、Joslyn Art Museum 与艺术家官网均提供对应作品图；作品仍受 Thomas Ruff / VG Bild-Kunst / ARS 版权保护，故记录官方图像入口与版权，不复制受限文件。',
    note:'Ruff 的 jpeg 不是简单把网络图片打印出来。他把低分辨率压缩文件放大到接近建筑尺度，使观看距离成为作品结构：近看图像裂解为规则色块，退远后灾难、战争或风景才重新出现。',
    projects:[
      {title:'jpeg msh01',cluster:'jpeg / found image / digital compression / monumental C-print',period:'2004',summary:'MoMA馆藏作品。Ruff没有重新拍摄火山，而是使用既有低分辨率JPEG图像，将电子文件放大并输出为276.2 × 188 cm chromogenic print。作品名中的 msh 指 Mount St. Helens。巨幅输出把通常被屏幕尺寸掩盖的JPEG压缩/像素结构直接变成可见形式：靠近时画面近似几何色块，后退后才重新组织成喷发中的火山。系列由9·11网络图像触发，之后扩展到战争、灾难、风景与建筑等全球流通图像。',actions:['从互联网流通图像、扫描明信片及摄影出版物中选择既有图像，而非重新到现场拍摄。','保留低分辨率JPEG文件的数字结构，不以高分辨率重制消除压缩痕迹。','把小型电子图像大幅放大，使像素/压缩块从技术缺陷变成画面结构。','输出为巨幅 chromogenic print，使观众必须通过靠近与后退切换“色块结构”和“可辨认图像”。'],sourceUrl:'https://www.moma.org/collection/works/149384',images:[],relations:[rel('收藏','Museum of Modern Art','2004; chromogenic print; 276.2 × 188 cm; object 954.2011.'),rel('出版','Thomas Ruff: jpegs','Aperture / David Zwirner, 2009，系统整理该系列。'),rel('展览','Thomas Ruff: Photographs 1979–2017 — Whitechapel Gallery','2017–2018回顾展呈现其从模拟摄影到数字图像处理的方法谱系。')]},
      {title:'jpeg nt01',cluster:'jpeg / catastrophe image / Diasec / monumental print',period:'2004',summary:'Joslyn Art Museum记录该作尺寸为297 × 364 cm，媒介为 chromogenic print with Diasec。作品属于 jpeg 系列的灾难图像节点：网络/复制图像经过数字放大后，不再依赖原事件现场的“摄影者见证”，而让传播文件自身成为对象。Diasec装裱又把原本廉价、易复制的JPEG转化成巨大、平整、具有物理重量的展览对象，形成网络图像的低信息量与艺术品实体规模之间的冲突。',actions:['选择已在媒体/网络传播的灾难图像。','利用JPEG压缩结构与低分辨率作为视觉材料。','把文件放大到约3 × 3.64米。','以 chromogenic print 制作，并采用 Diasec 形成平整、硬质、近似无框玻璃面的展示结构。'],sourceUrl:'https://joslyn.org/art/collection/thomas-ruff/17291/jpeg-nt01/',images:[],relations:[rel('收藏','Joslyn Art Museum','2004; chromogenic print with Diasec; 297 × 364 cm.'),rel('出版','Thomas Ruff: jpegs','作品收入Aperture / David Zwirner 2009出版物。')]}
    ],awards:[],exhibitions:['Thomas Ruff: Photographs 1979–2017 — Whitechapel Gallery, 2017–18'],sources:[{label:'Thomas Ruff studio · jpeg',url:'https://www.thomasruff.com/werke/jpeg/'},{label:'MoMA · jpeg msh01',url:'https://www.moma.org/collection/works/149384'},{label:'Joslyn · jpeg nt01',url:'https://joslyn.org/art/collection/thomas-ruff/17291/jpeg-nt01/'},{label:'Smithsonian American Art Museum · jpeg de01',url:'https://americanart.si.edu/artwork/jpeg-de01-79247'}]
  },
  'joan-fontcuberta':{
    artistId:'joan-fontcuberta',
    projectCoverage:'作品级深化：从 Googlegrams 系列下钻到 Googlegram: Niépce，补齐搜索词、缩略图采集、photomosaic软件、色值匹配、万张小图拼合、实体C-print输出与近/远观看机制。',
    imageCoverage:'The Metropolitan Museum of Art 提供 Googlegram: Niépce 官方作品图并明确 © Joan Fontcuberta, 2005；作品受版权限制，因此保留馆藏页和版权记录，不复制图像文件。',
    note:'Googlegrams 的关键动作不是“用Google做艺术”，而是把搜索引擎产生的大规模图像结果作为原材料，再用软件按照色彩与密度重新排序，使网络检索、摄影史经典图像和实体照片三种图像制度叠在一起。',
    projects:[
      {title:'Googlegram: Niépce',cluster:'Googlegrams / search engine / photomosaic / photography history',period:'2005',summary:'Fontcuberta 以 Nicéphore Niépce 1826年的《View from the Window at Le Gras》作为最终宏观图像，但构成它的不是连续照片，而是约一万张Google图片搜索缩略图。他以“photo”和“foto”为搜索词取得网络图像，再通过 photomosaic software 按色彩值和密度排列这些缩略图，使它们在远距离重构摄影史最早期的标志性景象。The Met馆藏版本最终输出为120 × 160 cm chromogenic print，装框123.2 × 162.6 cm。观众靠近时阅读的是成千上万张异质网络图片，后退时才看见Niépce图像，因此作品把化学摄影的起点与搜索引擎时代的去物质化图像流压缩进同一张实体照片。',actions:['选择Niépce《View from the Window at Le Gras》作为宏观模板。','使用Google Image Search检索“photo”和“foto”，收集搜索结果缩略图。','将约一万张电子图像输入 photomosaic software。','由软件依据色彩值和图像密度重新排列小图，使其共同重构Niépce图像。','将数字拼图输出为120 × 160 cm chromogenic print，并装框展示。','利用观看距离制造双重阅读：近看网络缩略图，远看摄影史经典图像。'],sourceUrl:'https://www.metmuseum.org/art/collection/search/302283',images:[],relations:[rel('收藏','The Metropolitan Museum of Art','2005; chromogenic print; image 120 × 160 cm; frame 123.2 × 162.6 cm; object 2012.251.'),rel('展览','Through the Looking Glass — ACVic','2010–2011展览同时呈现 Googlegrams / Reflectograms，并设置观众生成图像后投影进展览的参与环节。')]}
    ],awards:['Hasselblad Award 2013'],exhibitions:['Through the Looking Glass — ACVic, 2010–11'],sources:[{label:'The Met · Googlegram: Niépce',url:'https://www.metmuseum.org/art/collection/search/302283'},{label:'MACBA · Joan Fontcuberta',url:'https://www.macba.cat/en/actor/joan-fontcuberta/'},{label:'ACVic · Through the Looking Glass',url:'https://www.acvic.org/en/exhibition-projects/272-through-the-looking-glass-joan-fontcuberta'}]
  },
  'mishka-henner':{
    artistId:'mishka-henner',
    projectCoverage:'作品级深化：补入 No Man’s Land 与 Eighteen Pumpjacks，把论坛检索、Google Street View/卫星图像导航、再取景、API编号命名、喷墨输出和录像安装拆成具体作者动作。',
    imageCoverage:'National Gallery of Art 为 Eighteen Pumpjacks 及19件Henner作品提供官方馆藏图；Blue Sky/Oregon Center for the Photographic Arts 提供 No Man’s Land 展览图与项目说明。版权未确认开放本地再发布，因此仅记录官方入口。',
    note:'Henner 的作者性常发生在“相机已经替他拍完之后”：他搜索论坛、坐标和数据库，再进入自动成像系统的巨大档案中导航、选择、裁切、命名和输出。',
    projects:[
      {title:'No Man’s Land',cluster:'Google Street View / online forums / sex work / found photography / video installation',period:'2011–2012',summary:'Henner没有亲自驾驶车辆寻找街头性工作者，而是先阅读男性用户在线论坛中分享的性工作者地点信息，再把这些地点转移到Google Street View中搜索。Street View车辆已经机械性地拍摄了道路和人物；Henner在这一自动档案里移动视角、选择时刻并重新框定画面，形成意大利与西班牙城乡边缘地带的系列。2012 Blue Sky 展览同时呈现 photographic prints 与 video installation，因此项目并非只存在为网页截图，而被重新组织成墙面静态照片和时间化的录像观看。',actions:['检索男性网络论坛中关于性工作者出现地点的文字信息。','把论坛地点转译为Google Street View中的具体道路/坐标。','在Street View既有全景影像中导航、旋转视角、选择并重新框定场景。','把机器拍摄的地图图像转成摄影作品，而不是重新到现场按快门。','在展览中同时制作墙面摄影输出和录像装置，使观众比较静态选择与连续地图导航。'],sourceUrl:'https://www.blueskygallery.org/gallery-exhibitions/2012/mishka-henner',images:[],relations:[rel('展览','Blue Sky / Oregon Center for the Photographic Arts','May 3–June 3, 2012；展览同时呈现 photographic prints 与 video installation。')]},
      {title:'Eighteen Pumpjacks',cluster:'satellite imagery / oil infrastructure / API identifiers / portfolio',period:'2012',summary:'National Gallery of Art馆藏为18幅 inkjet prints 的portfolio。Henner从高空/地图影像中寻找美国油田的pumpjack，把每个井点从周围道路、农田与荒地中重新取景，并使用API（American Petroleum Institute）井号与地点作为作品标题，例如 API 21930378 Slaughter, TX。机器生成的垂直俯视图消除了传统地平线，泵机被压缩成农业纹理或荒地几何中的小型基础设施节点。系列最终通过统一的喷墨输出和18张组合，把能源数据库中的编号系统与遥感视觉系统叠加。',actions:['进入在线航空/卫星地图影像寻找美国油田与单个pumpjack。','以垂直俯视方式重新框定井点及其周围农田、道路和荒地。','使用API井号与地点命名单件，使数据库标识成为作品标题的一部分。','把数字地图来源图像输出为 inkjet prints。','将18件作品组织成portfolio，使单个基础设施节点累积成能源开采的空间样本。'],sourceUrl:'https://www.nga.gov/artists/50037-mishka-henner/artworks',images:[],relations:[rel('收藏','National Gallery of Art','2012; portfolio of 18 inkjet prints; accession 2018.177.82.1–18.'),rel('收藏','National Gallery of Art · API 21930378 Slaughter, TX','2012; inkjet print; accession 2018.177.82.8，官方页面提供作品图。')]}
    ],awards:[],exhibitions:['No Man’s Land — Blue Sky, Portland, 2012'],sources:[{label:'National Gallery of Art · Mishka Henner works',url:'https://www.nga.gov/artists/50037-mishka-henner/artworks'},{label:'Blue Sky · No Man’s Land',url:'https://www.blueskygallery.org/gallery-exhibitions/2012/mishka-henner'}]
  }
};
