import type { ArtistArchive, ArchiveRelation } from './archiveData';
const rel=(kind:ArchiveRelation['kind'],label:string,detail?:string):ArchiveRelation=>({kind,label,detail});

export const archiveBatch207:Record<string,ArtistArchive>={
'hito-steyerl':{
 artistId:'hito-steyerl',
 projectCoverage:'纵向深化：November → In Free Fall → How Not to Be Seen → Factory of the Sun；从政治影像记忆、图像流通到监控/分辨率与沉浸式数据劳动。',
 imageCoverage:'MoMA 馆藏与展览页提供 November、In Free Fall、How Not to Be Seen 的作品资料和 installation views；MOCA 提供 Factory of the Sun 展陈图。本站保留官方入口，不复制版权未确认图像。',
 note:'Steyerl 的核心不是泛泛的“互联网批判”，而是追踪图像如何被生产、压缩、复制、武器化和重新解释。她把纪录片、第一人称叙述、教学片、游戏界面与沉浸装置连续改造成研究图像政治的工具。',
 projects:[
  {title:'November',cluster:'essay film / political memory / image circulation',period:'2004',summary:'25分钟彩色有声影像。MoMA 将其视为 Steyerl 后续实践的重要起点：作品讨论政治起义中的性别、抗议美学与影像记忆，显示同一人物/图像进入不同政治语境后会获得新的意义。',actions:['把个人记忆、政治历史与既有影像放在同一 essay-film 结构中，而不是维持传统纪录片的客观旁观位置。','把“影像后来怎样流通”纳入作品：图像不是事件的透明记录，而会在传播、再使用与政治叙事中改变身份。','方法意义：为后来研究 poor image、数字复制和网络流通建立早期模型——重点从图像拍了什么转向图像后来经历了什么。'],sourceUrl:'https://www.moma.org/collection/works/179811',images:[],relations:[rel('收藏','MoMA','Committee on Media and Performance Art Funds')]},
  {title:'In Free Fall',cluster:'essay video / circulation / material history of images',period:'2010',summary:'32分钟彩色有声录像，现藏 MoMA。作品把影像、物质和资本的循环放在同一运动逻辑中，是 Steyerl 从 essay documentary 向数字图像政治推进的重要节点。',actions:['使用 essayistic montage 而非线性纪录叙事，让不同来源的影像和解释互相碰撞。','把“流通”理解为物质过程：图像并非无重量的信息，而与载体、技术、商品和基础设施共同变化。','与 November 相比，研究尺度从具体政治记忆进一步扩大到全球化影像/商品循环。'],sourceUrl:'https://www.moma.org/collection/works/170626',images:[],relations:[rel('收藏','MoMA','Fund for the Twenty-First Century')]},
  {title:'How Not to Be Seen: A Fucking Didactic Educational .MOV File',cluster:'instructional-video parody / surveillance / resolution / military imaging',period:'2013',summary:'14分钟录像。作品借用 instructional film 形式，用荒诞“隐身教程”讨论 total over-visibility；大量段落拍摄于美国空军曾用于校准航空摄影分辨率的 California desert targets。',actions:['结构：用自动化男声分章节发布“如何不被看见”的指令，并由 Steyerl 与无脸数字人物示范。','动作语言借用 iPhone 的 swipe、point、take a picture 等手势，使人的身体动作直接受数字界面编排。','场地不是装饰：航空摄影 calibration targets 把 resolution 与军事侦察、无人机和目标识别的历史接入作品。','把真实沙漠、computer desktop、绿幕人物和虚拟住宅混合，故意取消 material / virtual 的稳定边界。','差异：作品并非简单赞美 invisibility；它同时指出被监控与被社会/政治抹除是两种完全不同的“不可见”。'],sourceUrl:'https://www.moma.org/collection/works/181784',images:[],relations:[rel('收藏','MoMA','2014 acquisition'),rel('展览','Cut to Swipe, MoMA','2014–2015')]},
  {title:'Factory of the Sun',cluster:'immersive video installation / motion capture / game-space / surveillance',period:'2015–2016',summary:'2015 Venice Biennale 德国馆首展，2016 MOCA Los Angeles 美国首展。新闻、纪录片、电子游戏和网络舞蹈影像被组织进 motion-capture workers 的虚构故事：身体动作被记录并转化为“人工阳光”。',actions:['把娱乐、数据采集、身体劳动和监控压进同一 motion-capture production chain。','让观众进入由屏幕、光线与数字网格组织的环境，因此观看装置本身也是论点。','从 How Not to Be Seen 的“如何逃离机器观看”推进到“身体如何成为机器视觉/娱乐系统的生产原料”。'],sourceUrl:'https://www.moca.org/exhibitions/hito-steyerl-factory-of-the-sun',images:[],relations:[rel('展览','German Pavilion, Venice Biennale','2015'),rel('展览','MOCA Los Angeles','2016 US premiere')]}
 ],awards:[],exhibitions:['Cut to Swipe — MoMA, 2014–2015','German Pavilion — Venice Biennale 2015','MOCA Los Angeles — Factory of the Sun, 2016'],sources:[{label:'MoMA · November',url:'https://www.moma.org/collection/works/179811'},{label:'MoMA · In Free Fall',url:'https://www.moma.org/collection/works/170626'},{label:'MoMA · How Not to Be Seen',url:'https://www.moma.org/collection/works/181784'},{label:'MOCA · Factory of the Sun',url:'https://www.moca.org/exhibitions/hito-steyerl-factory-of-the-sun'}]
},
'stan-douglas':{
 artistId:'stan-douglas',
 projectCoverage:'纵向深化：历史重建摄影 → Luanda-Kinshasa → The Secret Agent → Doppelgänger / Venice；强调 staged history、档案研究、多频道叙事与“未发生但可能发生”的历史。',
 imageCoverage:'David Zwirner 官方作品与展览页保存作品 stills、production views 和 installation views；本站保留官方入口与规格，不复制未确认许可图像。',
 note:'Douglas 与传统纪实摄影的根本差异在于：他常先研究真实历史，再重建空间、演员和技术条件，最后制造一份“像档案但从未存在过”的图像记录。历史在这里不是被发现，而是被重新排演。',
 projects:[
  {title:'Midcentury Vancouver reconstructions',cluster:'digital reconstruction / archival research / staged documentary',period:'2008–2016',summary:'Douglas 持续以 Vancouver 历史为材料。2016 David Zwirner 摄影调查说明，他依据 archival photographs 与 film footage 数字重建1948年战后城市中因房地产法律漏洞形成的临时居住空间，制作现实中已无法直接拍摄的场景。',actions:['先从 archival photographs / film footage 提取建筑、街道和社会历史信息。','用数字建模重建已经消失、且缺乏原有照明条件的城市空间。','最终图像采用 documentary realism 的表面语法，却记录一个由研究和技术重新制造的历史场景。','这一方法使“摄影=现场曾经存在”的索引关系发生断裂。'],sourceUrl:'https://www.davidzwirner.com/exhibitions/2016/photographs',images:[],relations:[rel('展览','Stan Douglas: Photographs, David Zwirner New York','2016 survey')]},
  {title:'Luanda-Kinshasa',cluster:'reconstructed studio / improvised music / long-loop video',period:'2013–2014',summary:'Douglas 重建 Columbia Records 30th Street Studio，让音乐家在并不存在于1970年代的跨文化 session 中真实演奏，再以纪录片语言拍摄。作品是6小时1分钟循环的单频道投影。',actions:['重建历史录音棚，而不是在保存现场取景。','让真实即兴表演进入人工历史布景，使事件同时“真实发生”又“历史上从未发生”。','长循环让观众以进入持续 session 的方式观看，而非按电影开头/结尾消费故事。'],sourceUrl:'https://www.davidzwirner.com/exhibitions/2014/luanda-kinshasa',images:[],relations:[rel('展览','David Zwirner New York','2014')]},
  {title:'The Secret Agent',cluster:'six-channel film / literary adaptation / political history / nonlinear installation',period:'2015–2016',summary:'Douglas 将 Joseph Conrad 1907 年小说从1886 London 移植到 Portugal 1975 “Hot Summer”，即 Carnation Revolution 后、民主宪法确立前的政治过渡期。官方规格为 six-channel video、eight audio channels、53:35 loop，并有六种音乐变化。',actions:['不是忠实复刻小说时代，而是把 terrorism plot 移植到另一真实历史断层，以比较不同现代化危机。','六个画面和八路声音拆开传统单屏电影的视点，让叙事必须在空间中被拼接。','把虚构人物嵌入经过研究的 Portugal 去殖民化/民主转型背景，延续 Douglas 的 counterfactual history 方法。','2015 WIELS / Museu Coleção Berardo 首展，2016 David Zwirner 举行美国首展。'],sourceUrl:'https://www.davidzwirner.com/exhibitions/2016/secret-agent',images:[],relations:[rel('展览','WIELS / Museu Coleção Berardo','2015 premiere context'),rel('展览','David Zwirner New York','2016 US premiere')]},
  {title:'Doppelgänger',cluster:'science fiction / parallel worlds / dual identity / Venice Biennale',period:'2019–2020',summary:'2019 第58届 Venice Biennale 首次呈现，之后成为2020 David Zwirner 个展核心。作品把 Douglas 长期的“历史可能性”推进到平行世界与双重身份：不再只重建过去，也用 speculative fiction 研究另一种现实如何与当下互相照见。',actions:['将历史重演的方法转入 science-fiction structure，用 parallel-world logic 制造两个版本的现实。','与 Blackout photographs 同期在 Venice 呈现，使 staged photography 与 moving-image fiction 继续并行。','方法演变：从“过去还可能怎样发生”推进到“现实是否可能拥有并行版本”。'],sourceUrl:'https://www.davidzwirner.com/exhibitions/2020/stan-douglas-2020/press-release',images:[],relations:[rel('展览','58th Venice Biennale','2019 debut'),rel('展览','David Zwirner New York','2020')]}
 ],awards:['2012 ICP Infinity Award','2013 Scotiabank Photography Award','2016 Hasselblad Foundation International Award','2024 appointed to the Order of Canada'],exhibitions:['58th Venice Biennale — Doppelgänger, 2019','David Zwirner — The Secret Agent, 2016','David Zwirner — Doppelgänger, 2020'],sources:[{label:'David Zwirner · Photographs',url:'https://www.davidzwirner.com/exhibitions/2016/photographs'},{label:'David Zwirner · The Secret Agent',url:'https://www.davidzwirner.com/exhibitions/2016/secret-agent'},{label:'David Zwirner · Doppelgänger',url:'https://www.davidzwirner.com/exhibitions/2020/stan-douglas-2020/press-release'},{label:'David Zwirner · Order of Canada',url:'https://www.davidzwirner.com/news/2024/stan-douglas-appointed-to-the-order-of-canada'}]
},
'anicka-yi':{
 artistId:'anicka-yi',
 projectCoverage:'纵向深化：You Can Call Me F → Life Is Cheap → In Love With The World；从女性社交网络/活体细菌，推进到嗅觉政治、昆虫社会与自主机器生态。',
 imageCoverage:'The Kitchen、Guggenheim 与 Tate 官方资料提供项目文本及作品/展览图入口。本站不复制版权状态未确认的图片文件。',
 note:'Yi 的重要性不在“奇怪材料”本身，而在她不断把感知权力重新分配给视觉以外的系统：细菌、气味、昆虫、空气和机器行为都能成为主体。她的作品经常要求科学家、工程师与展览机构共同完成。',
 projects:[
  {title:'You Can Call Me F',cluster:'living bacteria / synthetic biology / female network',period:'2015',summary:'The Kitchen 个展。Yi 邀请职业网络中的100位女性捐赠 biological information samples，并在 synthetic biologist Tal Danino 指导下形成 collective bacteria，把现实社会网络转译成活体材料。',actions:['向100位 artists、curators、critics、dealers、collectors 征集样本。','让实验室培养进入艺术制作链，而非仅用“细菌”作为隐喻。','把 gallery 组织为 forensic site，使 contagion、hygiene 与女性网络的社会恐惧同时进入观看。'],sourceUrl:'https://archive.thekitchen.org/wp-content/uploads/2017/03/Anicka-Yi-PR-Final-FOR-GALLERY.pdf',images:[],relations:[rel('展览','The Kitchen','2015 solo exhibition')]},
  {title:'Life Is Cheap',cluster:'bacteria / ants / scent / sensory politics / bio-social systems',period:'2017',summary:'Yi 获2016 Hugo Boss Prize 后于 Guggenheim 呈现新作展（2017-04-21—07-05）。官方资料明确指出展览把 microorganism forms、data collection 与 sensory perception 交织，并使用 cultivated bacteria、ant colonies 与 custom scent。',actions:['把培养细菌、蚂蚁群落和定制气味并置，拒绝让视觉成为唯一的信息入口。','将 biological、social、political、technological systems 视为互相嵌套的系统，而不是分别处理“自然”与“技术”。','气味不是氛围装饰，而是研究 power / culture / perception 关系的实际媒介。','机构关系：展览由 Guggenheim Katherine Brinson 与 Susan Thompson 组织，直接接续2016 Hugo Boss Prize。'],sourceUrl:'https://www.guggenheim.org/video/the-hugo-boss-prize-2016-anicka-yi-life-is-cheap',images:[],relations:[rel('奖项','Hugo Boss Prize','2016 winner'),rel('展览','Solomon R. Guggenheim Museum','Life Is Cheap, Apr 21–Jul 5 2017'),rel('策展','Katherine Brinson / Susan Thompson','Guggenheim exhibition')]},
  {title:'In Love With The World',cluster:'robotic aerobes / AI / scent / autonomous ecosystem / Turbine Hall',period:'2021',summary:'Tate Modern 第六届 Hyundai Commission。Yi 在 Turbine Hall 放入会漂浮的机器生命体“aerobes”；它们对环境因素表现个体与群体行为，同时空气中的气味连接场地跨越长期历史的不同气味记忆。',actions:['把 Turbine Hall 当成生态环境而不是巨大雕塑底座，让机器在其中移动、回应并形成群体行为。','aerobes 通过自主/半自主行为让 AI 不再只是屏幕算法，而获得近似动物群落的空间存在。','使用空气传播气味，把观众共享的呼吸环境变成作品材料，并把机器生态与场地历史连接。','方法演变：从 You Can Call Me F 的微生物社会网络、Life Is Cheap 的跨物种感知，推进到“机器是否也能成为生命史的一部分”。'],sourceUrl:'https://shop.tate.org.uk/hyundai-commission-2021-anicka-yi/26145.html',images:[],relations:[rel('展览','Tate Modern Turbine Hall','Hyundai Commission 2021')]}
 ],awards:['2016 Hugo Boss Prize'],exhibitions:['The Kitchen — You Can Call Me F, 2015','Guggenheim — Life Is Cheap, 2017','Tate Modern — Hyundai Commission: In Love With The World, 2021'],sources:[{label:'The Kitchen · You Can Call Me F',url:'https://archive.thekitchen.org/wp-content/uploads/2017/03/Anicka-Yi-PR-Final-FOR-GALLERY.pdf'},{label:'Guggenheim · Life Is Cheap',url:'https://www.guggenheim.org/video/the-hugo-boss-prize-2016-anicka-yi-life-is-cheap'},{label:'Guggenheim · Life Is Cheap press release',url:'https://www.guggenheim.org/wp-content/uploads/2017/03/gen-press-anicka-yi-hugo-boss-2016-exhibition-031517.pdf'},{label:'Tate · Hyundai Commission 2021',url:'https://shop.tate.org.uk/hyundai-commission-2021-anicka-yi/26145.html'}]
}
};