import type { ArtistArchive, ArchiveProject, ArchiveRelation } from './archiveData';

const rel=(kind:ArchiveRelation['kind'],label:string,detail?:string):ArchiveRelation=>({kind,label,detail});
const project=(p:ArchiveProject)=>p;

export const archiveBatch291:Record<string,ArtistArchive>={
  'laia-abril':{
    artistId:'laia-abril',
    projectCoverage:'作品级深化批次：把已有 Laia Abril 总体档案继续下钻到 Endometriosis、On Rape 的具体馆藏作品、On Abortion/Las17、Suyay 的具体物件与图像、On Mass Hysteria 展览版本以及 Harm Reduction 的现场研究与150件文献档案。',
    imageCoverage:'6 / 6 节点均核到艺术家官网、Photo Elysée、Reina Sofía、ICRC、MACBA 项目页的对应图像入口；Suyay 中 ICRC 影像档案明确标记 publication without restrictions 的图像可作为稳定研究图源，其余未确认再发布许可的图片不复制，并在关系字段中记录摄影/版权状态。',
    note:'Abril 的作品不能只归纳成“女性主义摄影”。她经常先做长期采访、制度史与档案研究，再决定哪些内容应被拍成照片、哪些保留为证词/声音/文件、哪些通过物件或出版物出现。作品级档案因此重点记录证据如何被生产、选择、排序和转译为展览。',
    projects:[
      project({title:'Endometriosis — The Silenced Pain',cluster:'chronic pain / portrait / installation / bodily material',period:'2026',summary:'Abril 邀请7位患有严重子宫内膜异位症的人参与，以“疼痛无法被直接看见”为出发点，不把医学影像当作唯一可见性标准。她在参与者疼痛暂时缓解的时刻拍摄身体，使身体以碎片、姿势和适应疼痛的方式出现，而不是形成临床式完整肖像。艺术家官网进一步说明，最终照片表面以艺术家自己的眼泪上清漆，使身体经验、摄影表面和艺术家的身体材料直接发生物质联系。项目以装置形式呈现，并被 Abril 明确视为 On Mass Hysteria 之后继续研究性别、制度权力与知识生产的作品。',actions:['与7位长期受 disabling endometriosis 影响的参与者合作。','不直接把疼痛“图解”为医学症状，而在短暂缓解时拍摄身体碎片、姿态和适应动作。','把摄影输出表面用艺术家自己的眼泪 varnish，令身体材料进入照片物质层。','把照片组织为装置，并与疾病长期被忽视、误诊及研究不足的制度历史并置。'],sourceUrl:'https://www.laiaabril.com/project/endometriosis/',images:[],relations:[rel('展览','Museo del Romanticismo / PhotoEspaña, Madrid','2026；艺术家官网列为该装置的展览版本。'),rel('展览','Annely Juda Fine Art, London','2026；第二个公开展览版本。')]}),
      project({title:'On Rape — Ala Kachuu / Church Rape / Military Rape',cluster:'institutional violence / conceptual portrait / pigment inkjet',period:'2020; collection display 2026',summary:'这组三件具体作品把 On Rape 从“受害者肖像”转向制度节点。Abril 以吉尔吉斯斯坦抢婚、阿根廷教会性侵与美国军队性侵为三个案例，通过研究法律、信仰和权力机制制作 conceptual portraits，再与证词、文件和历史材料构成项目网络。Reina Sofía 2026 馆藏展示明确给出三件作品名称，并确认媒介为 pigment inkjet print on Hahnemühle paper。观众面对的不是对暴力行为的再现，而是被设计成指向制度机制的图像节点。',actions:['从跨国制度性强暴案例而非单一受害者叙事建立研究节点。','研究法律、宗教、军队与社会规范如何保护、正常化或延续暴力。','制作 conceptual portraits，并让图像与证词、文件及历史材料共同承担叙事。','以 Hahnemühle 纸上的 pigment inkjet print 输出具体馆藏作品。'],sourceUrl:'https://www.laiaabril.com/exhibition/onrape-reinasofia/',images:[],relations:[rel('收藏','Museo Reina Sofía, Madrid','永久收藏展示；Ala Kachuu, Bride Kidnapping, Kyrgyzstan / Church Rape, Argentina / Military Rape, U.S.，均为2020。'),rel('展览','Museo Reina Sofía — Colección. Arte contemporáneo: 1975-presente','2026；curated by Manuel Segade。'),rel('展览','C/O Berlin','2024；installation views credited to David von Becker，版权未确认可仓库再发布，故不复制。')]}),
      project({title:'Las17 — El Salvador case study within On Abortion',cluster:'abortion law / prison / research / testimony',period:'2015–2017',summary:'Abril 在2015年11月开始研究萨尔瓦多17名女性：她们在流产或产科并发症后被控 homicide，并被判30至40年监禁。作品不是抽象谈“堕胎权”，而是围绕这些具体案件追踪刑法、医疗人员举报、监狱处境、家庭威胁与赦免运动。2017 CaixaForum 版本把该研究作为 Fotopress 项目呈现，使 On Abortion 中宏观的法律问题落到可核对的个案、时间线和制度文件。',actions:['锁定17名因流产/产科并发症而遭 homicide 指控的萨尔瓦多女性作为具体案例群。','研究1998年全面禁堕胎法律、医疗举报机制、审判与长期监禁。','追踪 Las17 赦免运动以及当事人与家庭在监禁中的持续处境。','把个案研究、图像和制度文本组织成展览节点，而不是以单一新闻照片概括问题。'],sourceUrl:'https://www.laiaabril.com/exhibition/las17-caixaforum-barcelona-2017/',images:[],relations:[rel('展览','CaixaForum Barcelona','28 Apr–30 Jul 2017；Fotopress grant project；mentored by Marta Ponsa。'),rel('展览','CaixaForum Madrid','2017；同一 Fotopress 研究的后续展览节点。')]}),
      project({title:'Suyay — missing-person belongings and family testimony',cluster:'Peru / disappearance / belongings / portrait / testimony',period:'2018–2019',summary:'Suyay 在秘鲁阿亚库乔等地处理1980–2000年武装冲突留下的失踪者家庭。Abril 没有只拍“悲伤的人”，而是把仍在等待的亲属肖像、失踪者留下的衣物与物件、儿童对失踪夜晚的绘画、墓地/寻找现场以及第一人称叙述组合起来。ICRC 影像档案保存了具体节点，例如失踪者 poncho、家庭遗留物以及一名女孩画下父亲失踪之夜的图画；这些对象让不可见的失踪通过仍被保存和触摸的物质痕迹进入展览。',actions:['在秘鲁与仍寻找失踪亲属的家庭合作，记录等待、寻找和无法完成的哀悼。','拍摄亲属肖像，同时拍失踪者留下的 poncho 等衣物和家庭物件。','纳入儿童关于亲人被带走当晚的绘画，使记忆材料与摄影并置。','把第一人称证词与图像配对，使观看从“人物肖像”转向具体失踪事件和长期等待。'],sourceUrl:'https://www.laiaabril.com/project/suyay/',images:[{url:'https://www.icrc.org/sites/default/files/styles/desktop_full/public/document_new/image/suyay1.jpg.webp?h=2413fafe&itok=DB52VdFI',title:'Suyay — families of the disappeared',credit:'Photograph: Laia Abril; copyright ICRC; ICRC audiovisual archive records related Suyay images as public / publication without restrictions',sourceUrl:'https://www.icrc.org/es/document/suyay-los-desaparecidos-los-que-esperan-los-afligidos',sourceLabel:'International Committee of the Red Cross'}],relations:[rel('展览','Centre de la Photographie Genève','7–25 Nov 2018；ICRC 合作语境。'),rel('展览','LUM Museum, Lima','2019。')]}),
      project({title:'On Mass Hysteria — Photo Elysée spatial version',cluster:'archive / photography / multimedia / installation',period:'2023',summary:'第三章研究群体性心因性症状如何在长期受压环境中成为一种身体语言。Abril 把 Salem、欧洲修女、瑞士/德国寄宿学校、坦桑尼亚女学生、阿富汗学校、墨西哥学校、柬埔寨制衣厂和美国啦啦队等历史与当代案例放入同一研究结构，以摄影、档案材料、文字和多媒体建立跨时空比较。Photo Elysée 2023 版本不是简单照片墙，而被机构明确描述为同时呈现 research 与 visual metaphors 的 installation；展览由 Photo Elysée、LE BAL 与 Finnish Museum of Photography 联合制作，因此后续巡展可作为同一研究在不同机构中的空间版本继续追踪。',actions:['收集跨国、跨历史时期的群体性心因性症状案例。','把医学/社会史档案与自己制作的摄影和视觉隐喻并置。','通过文字、档案、摄影和多媒体而非单一媒介组织研究。','在 Photo Elysée 将研究材料转成空间装置，并为后续 Helsinki / Paris 版本建立可变展陈框架。'],sourceUrl:'https://elysee.ch/en/exhibitions/laia-abril/',images:[],relations:[rel('展览','Photo Elysée, Lausanne','30 Jun–1 Oct 2023；curated by Nathalie Herschdorfer；与 LE BAL、Finnish Museum of Photography 联合制作。'),rel('展览','Finnish Museum of Photography','2024；联合制作巡展版本。'),rel('展览','LE BAL, Paris','2025；联合制作的后续版本。')]}),
      project({title:'Harm Reduction — MACBA / Raval commission',cluster:'field research / documentary photography / 150-document archive',period:'2024',summary:'这一项目把 Abril 的研究方法带到巴塞罗那 Raval。她深入观察 CAS Baluard 与 Metzineras 两个安全注射/庇护空间，从性别视角研究 harm reduction。视觉工作不仅拍摄受服务者，也记录热食、洗衣机、淋浴、电脑、网络和自我照护工具等经常被政策叙述忽略的基础设施；另一组黑白照片跟随社会工作者和行动者在街头收集针具、支援露宿者。项目同时建立约150件文献的研究档案，包括社会教育者、护士、分析人员和学者访谈、数据报告、宣传材料、文章与历史资料，并在 MACBA 2024 的城市研究展中呈现。',actions:['长期观察 CAS Baluard 与 Metzineras 的安全注射室、庇护与照护工作。','拍摄 harm-reduction 基础设施及日常照护工具，而非只把镜头对准药物使用。','以黑白摄影跟随社会工作者/行动者收集针具并支援街头露宿者。','建立约150件文件的研究档案：访谈、数据报告、campaign material、文章和历史资料。','把摄影与研究档案共同放进 MACBA 的 Raval/Barcelona 城市研究展览语境。'],sourceUrl:'https://www.laiaabril.com/exhibition/harm-reduction-macba-barcelona-2024/',images:[],relations:[rel('展览','MACBA — Una ciudad desconocida bajo la niebla','2024；curated by Jorge Ribalta and Blanca del Río。'),rel('策展','Pla de Barris / City of Barcelona commission','与 CAS Baluard、Metzineras 合作完成。')]})
    ],
    awards:['Prix Elysée nomination for early On Mass Hysteria research','Spain National Photography Award'],
    exhibitions:['On Mass Hysteria — Photo Elysée, 2023','On Rape — C/O Berlin, 2024','Harm Reduction — MACBA, 2024','On Mass Hysteria — LE BAL, 2025','On Rape — Museo Reina Sofía collection display, 2026','Endometriosis — Museo del Romanticismo / PhotoEspaña, 2026'],
    sources:[{label:'Laia Abril — Endometriosis',url:'https://www.laiaabril.com/project/endometriosis/'},{label:'Laia Abril — On Rape',url:'https://www.laiaabril.com/project/on-rape/'},{label:'Reina Sofía display — On Rape',url:'https://www.laiaabril.com/exhibition/onrape-reinasofia/'},{label:'Laia Abril — Las17',url:'https://www.laiaabril.com/exhibition/las17-caixaforum-barcelona-2017/'},{label:'Laia Abril — Suyay',url:'https://www.laiaabril.com/project/suyay/'},{label:'ICRC — Suyay',url:'https://www.icrc.org/es/document/suyay-los-desaparecidos-los-que-esperan-los-afligidos'},{label:'Photo Elysée — On Mass Hysteria',url:'https://elysee.ch/en/exhibitions/laia-abril/'},{label:'Laia Abril — Harm Reduction / MACBA',url:'https://www.laiaabril.com/exhibition/harm-reduction-macba-barcelona-2024/'}]
  }
};