import type { ArtistArchive, ArchiveRelation } from './archiveData';
const rel=(kind:ArchiveRelation['kind'],label:string,detail?:string):ArchiveRelation=>({kind,label,detail});

export const archiveBatch209:Record<string,ArtistArchive>={
  'walid-raad':{
    artistId:'walid-raad',
    projectCoverage:'作品级深化：My neck is thinner than a hair: Engines → Section 139: The Atlas Group (1989–2004) → Preface to the third edition；补齐单件尺寸、数字再制、装置硬件、档案来源、展览版本与观看机制。',
    imageCoverage:'MoMA 作品页、2015–16 survey installation views 与官方 slideshow 均提供对应作品图；installation photography credit 包括 Thomas Griesel。版权标注为 © Walid Raad / The Atlas Group，MoMA 明示展览图再利用需经 Art Resource 或 Scala Archives，因此本站不复制未获许可原图，保留官方图像入口、credit 与版权状态。',
    note:'本批把 Raad 从“虚构档案”概念进一步落实到具体物件：报纸照片如何被扫描和重印、档案如何变成带 LCD/iPad 的桌状装置、Louvre 文物如何经摄影与数字合成制造出虚构的未来变体。',
    projects:[
      {title:'My neck is thinner than a hair: Engines',cluster:'found press photographs / scanning / pigmented inkjet / archive installation',period:'1996–2004',summary:'由100张汽车炸弹爆炸后发动机照片组成。照片不是 Raad 在现场拍摄，而是黎巴嫩内战期间新闻摄影师制作、后来由艺术家从 Beirut 的 An-Nahar Research Center 与 Arab Documentation Center 档案中寻找出来。MoMA 馆藏版本为100张 pigmented inkjet prints，每张24 × 34 cm。',actions:['实际动作：Raad 在新闻档案中搜集发动机照片；扫描照片正面与背面；保留/转录背面档案注记，并在重新制作的图像上加入爆炸日期、摄影者姓名（如可知）以及注记的英文翻译。','对象机制：汽车炸弹爆炸后发动机可能被抛到屋顶、阳台或邻街，新闻摄影师会寻找并拍摄它；发动机号码理论上可以追溯车辆，但炸弹车辆多为赃车，使这种“证据”经常失去司法效力。','展陈与观看：100张小尺幅图像作为序列/档案阅读，而不是一张英雄式战争照片。观众需要近距离逐张查看发动机、围观者、政客与文字资料；重复结构使新闻摄影中的 photo opportunity 逐渐显形。','版本记录：MoMA 作品页标为1996–2001，2015展览资料常以1996–2004描述项目；网站保留这一机构记录差异，不强行合并成虚构的单一日期。'],sourceUrl:'https://www.moma.org/collection/works/91530',images:[],relations:[rel('机构','MoMA','100 pigmented inkjet prints; each 24 × 34 cm'),rel('档案','An-Nahar Research Center','Beirut newspaper archive source'),rel('档案','Arab Documentation Center','Beirut archive source'),rel('版权','The Atlas Group / Walid Raad','MoMA copyright record; reproduction not assumed')]},
      {title:'Section 139: The Atlas Group (1989–2004)',cluster:'archive interface / mixed-media installation / LCD / iPad / digital photographs',period:'1989–2004',summary:'MoMA 馆藏的一件大型档案型装置，把 The Atlas Group 长期项目从照片、录像与讲述转成一个实体信息界面。馆藏规格明确列出 Plexiglas、high-density foam、LCD panels、4台 iPad、digital photos、plastic、steel、MDF 与 electrical supply；整体31.8 × 280.4 × 104.1 cm。',actions:['实际制作：不是把“档案”仅做成网页或文件柜，而是把数字照片、显示面板、平板电脑、电源与结构材料整合为近2.8米宽的低矮装置。','材料逻辑：Plexiglas 与塑料形成展示/保护层，steel 与 MDF 提供结构，high-density foam 参与造型；LCD 和四台 iPad 让档案成为持续发光、需要设备供电的电子对象。','观看方式：观众面对的是横向展开的信息家具/展示台，需要移动身体、靠近屏幕和图像阅读；数字媒介与“博物馆展示柜”语法叠合，使档案权威本身成为可被观察的形式。','与实践关系：作品把 The Atlas Group 1989–2004 的摄影、录像、笔记与虚构机构身份压缩成一个物质化 archive interface，是理解 Raad 如何把研究机构的展示技术本身转成艺术材料的重要节点。'],sourceUrl:'https://www.moma.org/collection/works/170262',images:[],relations:[rel('机构','MoMA','Media and Performance collection'),rel('材料','Plexiglas / foam / LCD / iPads / steel / MDF','official medium list'),rel('尺寸','31.8 × 280.4 × 104.1 cm','MoMA collection record'),rel('版权','Walid Raad / Paula Cooper Gallery','© Walid Raad; courtesy Paula Cooper Gallery')]},
      {title:'Preface to the third edition — Édition française',cluster:'Louvre Islamic art / digital composite / pigmented inkjet / speculative museum history',period:'2012–2013',summary:'Raad 在 Louvre 研究 Islamic art collection 后，把真实文物摄影转化为一组虚构“未来变异”图像：叙事假设 Louvre 借往 Abu Dhabi 的294件作品中有28件在旅途中交换皮肤、肢体、面孔或器官。MoMA 收录的 Plate I/III 为 pigmented inkjet print，111.8 × 85.1 cm。',actions:['研究与制作：Raad 在 Louvre 约两年观察 Islamic art objects 与历史展示方式；他把不同文物的形体、表面纹样与细节进行摄影/数字层面的组合，制造现实馆藏中不存在的 hybrid objects。','展示研究：艺术家查阅19—20世纪 Islamic art 展柜的历史照片，并把约60层 display cases 叠加为黑白背景；在相关装置中，二维档案图、墙纸与近似“从照片三维化”的物件共同出现。','虚构版本机制：作品并不声称这些变形真实发生，而以2016—2046未来时间段、Louvre Abu Dhabi 的跨国借展与沙漠气候为叙事条件，让 conservation、全球博物馆扩张、劳工与文化资本进入同一 speculative archive。','展陈/观看：大型竖幅 print 以博物馆级精细摄影的可信外观呈现不可能存在的对象；观众先被物件的精致表面说服，再通过文本发现它是制度史、摄影和虚构叠合后的产物。','版本差异：2012 MoMA 记录的 Édition française plates 是平面 pigmented inkjet prints；2013 Louvre Pavilion 及后续 Footnote II 等安装版本进一步加入 wallpapered vitrines、模型/三维对象，使“照片中的变形”扩展到真实展厅空间。'],sourceUrl:'https://www.moma.org/audio/playlist/20/419',images:[],relations:[rel('机构','Musée du Louvre','Islamic art collection research / 2013 related installation'),rel('机构','MoMA','Plate I/III documentation and 2015 survey'),rel('材料','Pigmented inkjet print','111.8 × 85.1 cm for documented plates'),rel('版权','Walid Raad / Paula Cooper Gallery','official MoMA credit; image reproduction not assumed')]}
    ],
    awards:[],
    exhibitions:['MoMA — Walid Raad, Oct 12 2015–Jan 31 2016','Louvre / related Scratching… presentations, 2013'],
    sources:[{label:'MoMA · My neck is thinner than a hair: Engines',url:'https://www.moma.org/collection/works/91530'},{label:'MoMA · Engines exhibition slideshow',url:'https://www.moma.org/slideshows/41/748'},{label:'MoMA · Section 139: The Atlas Group',url:'https://www.moma.org/collection/works/170262'},{label:'MoMA · Preface to the third edition, Plate I',url:'https://www.moma.org/audio/playlist/20/419'},{label:'MoMA · Walid Raad survey',url:'https://www.moma.org/calendar/exhibitions/1493'}]
  }
};
