import type { ArtistArchive, ArchiveRelation } from './archiveData';

const rel = (kind: ArchiveRelation['kind'], label: string, detail?: string): ArchiveRelation => ({ kind, label, detail });

export const archiveBatch150: Record<string, ArtistArchive> = {
  'venice-maya-deren': {
    artistId: 'venice-maya-deren',
    projectCoverage: '6 个 time-space cinema / choreography / ritual / Haiti research 节点深化 · 1943–1959',
    imageCoverage: '0 / 6',
    note: '把 Maya Deren 从三部经典短片扩成“主观空间 → 摄影机编舞 → 社交仪式 → Haiti Vodou 田野研究 → 独立电影制度建设”的连续实践。她的重要性不只是 surreal / dream imagery，而是把电影定义为 time-space art：剪辑不负责解释故事，而负责让身体跨越不可能的地点、时间与身份状态。1946 Guggenheim grant 又把形式实验推进长期 Haiti research；未完成的 Haiti film 及后来由 Teiji Ito / Cherel Ito 整理的 Divine Horsemen 也保留了艺术、民族志与参与式观察之间至今仍有争议的边界。',
    projects: [
      { title:'Meshes of the Afternoon', cluster:'subjective montage / domestic loop / doubled self', period:'1943', summary:'与 Alexander Hammid 合作的早期核心作品。钥匙、刀、花、镜面人物、楼梯和重复动作把普通住宅折叠成循环心理空间；同一主体不断复制，使“角色”变成剪辑产生的状态而不是稳定人物。', actions:['以 repeated object motif 代替传统因果叙事','重复同一路径但改变细节，使时间形成 loop','通过 multiple selves 拆解稳定主体','用 montage 把 domestic architecture 转成 subjective space'], sourceUrl:'https://www.moma.org/artists/6912-maya-deren', images:[], relations:[rel('收藏','Museum of Modern Art, New York','Film collection')] },
      { title:'At Land', cluster:'continuous body / discontinuous geography / horizontal journey', period:'1944', summary:'Deren 的身体在海滩、餐桌、森林等不连续空间之间移动，动作却保持连续。作品把地理断裂隐藏在身体连续性中，使现实空间被电影重新组织。', actions:['让一个 physical gesture 跨不同地点接续','把 landscape 当成可被剪辑重新连接的材料','用 performer movement 保持跨镜头 continuity','弱化 narrative goal，强化身体穿越空间的感觉'], sourceUrl:'https://www.moma.org/artists/6912-maya-deren', images:[], relations:[] },
      { title:'A Study in Choreography for Camera', cluster:'choreocinema / match movement / camera as dance partner', period:'1945', summary:'Talley Beatty 的舞蹈动作从森林、公寓到博物馆连续发生；现实距离在 match-on-action 中消失。摄影机不再记录舞蹈，而与剪辑一起制造现实舞台无法出现的 choreography。', actions:['先以 dancer movement 设计 edit points','让同一动作跨不同 physical locations 连续','使用 match-on-action 压缩现实距离','把 camera / editing 视为 choreographic partner'], sourceUrl:'https://www.moma.org/collection/works/302825', images:[], relations:[rel('收藏','Museum of Modern Art, New York','Film collection')] },
      { title:'Ritual in Transfigured Time', cluster:'social ritual / dance / transformation / slow motion', period:'1946', summary:'社交聚会、舞蹈与身体姿态被处理成一种集体 ritual；slow motion、冻结式姿态与重复 movement 让日常社交礼仪显露出其编舞结构。', actions:['把 party / greeting 等 social behavior 观察为 choreography','用 slow motion 改变动作的情绪重量','通过 gesture repetition 建立 ritual structure','让个体 transformation 发生在群体运动内部'], sourceUrl:'https://www.moma.org/artists/6912-maya-deren', images:[], relations:[rel('收藏','Museum of Modern Art, New York','Film collection')] },
      { title:'Haiti footage / Divine Horsemen research', cluster:'Vodou / dance ethnography / participatory research / unfinished film', period:'1947–1953', summary:'获得 1946 Guggenheim motion-picture grant 后，Deren 多次前往 Haiti，拍摄和录制 Vodou dance / ritual，累积超过 20,000 feet 的 16mm footage；她生前没有把素材剪成计划中的电影，而在 1953 出版 Divine Horsemen: The Living Gods of Haiti。1977 的同名电影由 Teiji Ito 与 Cherel Ito 根据她的原始素材整理完成。', actions:['以长期 repeated field visits 取代一次性 exotic documentation','同步进行 film、photography、sound recording 与文字研究','从观察 dance 转向参与 ritual / religious world','保留未完成状态作为艺术方法与 ethnographic authority 冲突的重要案例'], sourceUrl:'https://www.moma.org/artists/6912-maya-deren', images:[], relations:[rel('奖项','Guggenheim grant for creative motion-picture work','1946 · first such grant'),rel('出版','Divine Horsemen: The Living Gods of Haiti','1953'),rel('收藏','Museum of Modern Art · Divine Horsemen film','1977 edit from Deren footage')] },
      { title:'Creative Film Foundation / self-distribution model', cluster:'artist-run distribution / experimental-film infrastructure', period:'1940s–1950s', summary:'Deren 不只制作电影，也自己组织放映、巡回讲座、写理论并成立 Creative Film Foundation。她把“如何让非商业电影存在”本身变成实践的一部分，为后来美国 avant-garde / artist film 建立可复制的独立生产与传播模型。', actions:['自行组织 screenings 并直接面对观众','以 lecture / writing 为作品建立理论语言','拒绝 Hollywood scale，强调 micro-budget autonomy','成立 Creative Film Foundation 支持其他 avant-garde filmmakers'], sourceUrl:'https://www.moma.org/calendar/exhibitions/1096', images:[], relations:[rel('展览','Maya Deren’s Legacy — MoMA','2010 retrospective context')] }
    ],
    awards:['Guggenheim Foundation grant for creative work in motion pictures — 1946'],
    exhibitions:['The Witch’s Cradle — Venice Biennale 2022','Maya Deren’s Legacy — MoMA 2010'],
    sources:[{label:'MoMA · Maya Deren',url:'https://www.moma.org/artists/6912-maya-deren'},{label:'MoMA · Maya Deren’s Legacy',url:'https://www.moma.org/calendar/exhibitions/1096'},{label:'MoMA · Divine Horsemen',url:'https://www.moma.org/collection/works/321746'},{label:'La Biennale · Maya Deren 2022',url:'https://www.labiennale.org/en/art/2022/witchs-cradle/maya-deren'}]
  },

  'venice-benedetta': {
    artistId:'venice-benedetta',
    projectCoverage:'4 个 abstract novel / tactile experiment / aeropainting / public mural 节点深化 · 1924–1934',
    imageCoverage:'0 / 4',
    note:'把 Benedetta Cappa 从两件 1924 graphic works 扩成文字、触觉实验、aeropittura 与公共建筑 mural 的连续实践。她的重要性不应被缩成“Marinetti 的妻子”：她把 Second Futurism 从机械速度推进到心理、宇宙、通信与多感官结构，并在 Palermo 邮政宫的大型壁画中把 aerial viewpoint 转成现代通信系统的视觉模型。',
    projects:[
      { title:'Le forze umane: romanzo astratto con sintesi grafiche', cluster:'abstract novel / free-word writing / graphic synthesis', period:'1924', summary:'小说让 autobiographical passages、抽象 pseudo-scientific language 与 19 幅 graphic syntheses 共存。图像不是插图，而是与文字平行的 force-diagram language。', actions:['让 narrative 与 abstract prose 交替','以 black ink lines 建立 force diagrams','用 graphic synthesis 表示 bodily / psychic energy','让文字与图像保持互译但不互相说明'], sourceUrl:'https://www.labiennale.org/en/art/2022/witchs-cradle/benedetta', images:[], relations:[rel('出版','Le forze umane','1924')] },
      { title:'Contatto di due nuclei potenti (femminile e maschile)', cluster:'gender-energy diagram / line collision', period:'1924', summary:'女性与男性不再被画成身体，而被压缩成两套方向、密度和节律不同的线性 force systems；gender relation 因而从 figure representation 转为能量接触。', actions:['以 minimal line systems 代替 figurative body','让两组 force 在 central zone 互相穿透','把 gender 转译为 nucleus / energy vocabulary','将 spiritual / rational、conscious / subconscious 关系压进 graphic structure'], sourceUrl:'https://www.labiennale.org/en/art/2022/witchs-cradle/benedetta', images:[], relations:[rel('展览','The Witch’s Cradle — Venice Biennale 2022','historical capsule')] },
      { title:'Aeropittura / aerial synthesis', cluster:'aerial perspective / cosmic interiority / Second Futurism', period:'late 1920s–1930s', summary:'随着 Futurism 转向 aeropittura，Benedetta 使用俯瞰、旋转和空间压缩来表现飞行经验，但她并不只赞美飞机速度，而把 aerial vision 与心理、宇宙和精神性的空间感结合。', actions:['使用 elevated / aerial viewpoint 破坏稳定 horizon','以 curved / radiating forms 表示 movement 与 transmission','把 mechanical flight 与 inner / cosmic perception 连接','弱化单一物体，强化空间中 forces 的关系'], sourceUrl:'https://www.guggenheim.org/teaching-materials/italian-futurism-1909-1944-reconstructing-the-universe/painting', images:[], relations:[rel('展览','Italian Futurism, 1909–1944: Reconstructing the Universe — Guggenheim','2014 institutional context')] },
      { title:'Synthesis of Communications murals — Palazzo delle Poste, Palermo', cluster:'public mural / communications infrastructure / aerial modernity', period:'1933–1934', summary:'Palermo 邮政宫壁画群把 marine、overland、aerial、radio、telegraphic 与 telephonic communication 作为同一现代基础设施系统处理。Guggenheim 特别收录 Synthesis of Aerial Communications；作品把 Futurist speed 从汽车/飞机单体扩大成信息如何跨空间传播的问题。', actions:['把 communication modes 分成互相关联的 mural panels','使用 monumental public scale 而非私人 easel painting','把 aerial movement 转成 radiating / directional composition','让 architecture 与 painting 共同表现国家级 communication infrastructure'], sourceUrl:'https://www.guggenheim.org/teaching-materials/italian-futurism-1909-1944-reconstructing-the-universe/painting', images:[], relations:[rel('展览','Palazzo delle Poste, Palermo','permanent architectural commission'),rel('展览','Italian Futurism, 1909–1944 — Guggenheim','2014 research / exhibition context')] }
    ],
    awards:[], exhibitions:['The Witch’s Cradle — Venice Biennale 2022','Italian Futurism, 1909–1944: Reconstructing the Universe — Guggenheim 2014'],
    sources:[{label:'Guggenheim · Italian Futurism / Benedetta',url:'https://www.guggenheim.org/teaching-materials/italian-futurism-1909-1944-reconstructing-the-universe/painting'},{label:'La Biennale · Benedetta 2022',url:'https://www.labiennale.org/en/art/2022/witchs-cradle/benedetta'}]
  },

  'venice-valentine-de-saint-point': {
    artistId:'venice-valentine-de-saint-point',
    projectCoverage:'3 个 manifesto / metachoric performance / cross-media body 节点深化 · 1912–1914',
    imageCoverage:'0 / 3',
    note:'保留 Saint-Point 在 Venice 2022 历史谱系中的位置，并把她从“女性 Futurist manifesto”扩成一套跨媒介身体理论：先在文本层面对 Futurism 的 misogyny 进行内部反转，再把 lust / force 从论述变成 public recital，最终在 Métachorie 中让舞蹈、诗、几何姿态、投影与气味组成 synaesthetic performance。与 Benedetta 的差异是：Benedetta 更倾向把 force 压进图像/建筑系统，Saint-Point 则把 force 直接落实为 performer body 与现场感官。',
    projects:[
      { title:'Manifeste de la Femme futuriste', cluster:'manifesto / gender polemic / public author-position', period:'1912', summary:'Saint-Point 从 Futurism 内部回应其 misogynistic rhetoric，并拒绝把 femininity 简化成 passivity。文本本身通过宣言体的攻击性语气把女性作者位置推入原本高度男性化的 avant-garde public sphere。', actions:['借用 Futurist manifesto 的 aggressive rhetorical form','从内部反转 gender hierarchy','把 authorial voice 作为 public performance','用 force / virility vocabulary 拒绝固定 femininity'], sourceUrl:'https://www.labiennale.org/en/art/2022/witchs-cradle/valentine-de-saint-point', images:[], relations:[rel('出版','Manifeste de la Femme futuriste','1912')] },
      { title:'Manifeste futuriste de la luxure', cluster:'lust / creative force / performed manifesto', period:'1913', summary:'进一步把 lust 从道德分类中抽离，重新定义成生命与创造的 force。重要的不是今天是否接受其政治语言，而是她把 sexuality 从被观看的女性身体转成女性作者主动定义的能量概念。', actions:['把 sexuality 从 moral category 改写为 creative energy','通过 manifesto / recital 连接 written voice 与 embodied author','延续 Futurist force vocabulary 同时改变其 gender ownership','把身体欲望转成 aesthetic / philosophical proposition'], sourceUrl:'https://www.labiennale.org/en/art/2022/witchs-cradle/valentine-de-saint-point', images:[], relations:[rel('出版','Manifeste futuriste de la luxure','1913')] },
      { title:'Métachorie', cluster:'dance / poetry / projection / perfume / synaesthetic performance', period:'1914', summary:'Métachorie 把 movement、poetry recital、projected images 与 perfume 同时组织进 performance。舞者身体不承担传统 ballet narrative，而成为线、角度、节奏和多感官信号的发生器；相关 black-ground etchings 又把现场姿态转回 graphic notation。', actions:['设计非叙事 movement / geometric pose sequence','让 spoken poetry 与身体动作同步或错位','加入 projected imagery 扩展 performer body','使用 perfume 把 smell 纳入作品结构','以 etching / graphic record 保存 pose 与 stage atmosphere'], sourceUrl:'https://www.labiennale.org/en/art/2022/witchs-cradle/valentine-de-saint-point', images:[], relations:[rel('展览','The Witch’s Cradle — Venice Biennale 2022','historical performance / archive context')] }
    ],
    awards:[], exhibitions:['The Witch’s Cradle — Venice Biennale 2022'],
    sources:[{label:'La Biennale · Valentine de Saint-Point 2022',url:'https://www.labiennale.org/en/art/2022/witchs-cradle/valentine-de-saint-point'}]
  }
};
