import type { ArtistArchive, ArchiveRelation } from './archiveData';
const rel=(kind:ArchiveRelation['kind'],label:string,detail?:string):ArchiveRelation=>({kind,label,detail});

const darling='https://www.labiennale.org/en/art/2019/partecipants/jesse-darling';
const darlingIcarus='https://news.artnet.com/art-world/see-works-giardini-venice-biennale-2019-1542052';
const douglas='https://www.labiennale.org/en/art/2019/partecipants/stan-douglas';
const douglasZwirner='https://www.davidzwirner.com/exhibitions/2019/stan-douglas';
const durham='https://www.labiennale.org/en/art/2019/partecipants/jimmie-durham';
const durhamAward='https://www.labiennale.org/en/news/jimmie-durham-golden-lion-lifetime-achievement';
const eisenman='https://www.labiennale.org/en/art/2019/partecipants/nicole-eisenman';
const eisenmanWhitney='https://whitney.org/exhibitions/2019-biennial/art?section=16';
const epaminonda='https://www.labiennale.org/en/art/2019/partecipants/haris-epaminonda';
const epaminondaAward='https://www.labiennale.org/en/news/biennale-arte-2019-official-awards';
const epaminondaVol='https://www.haramuseum.or.jp/jp/hara/event/728/';

export const archiveBatch118:Record<string,ArtistArchive>={
  'venice-jesse-darling':{artistId:'venice-jesse-darling',projectCoverage:'2 个 non-macho / injured-body sculpture 节点已建立深档案 · 2018–2019',imageCoverage:'0 / 2 项目暂不使用不稳定外链图像',note:'Darling 的关键不是“廉价材料美学”，而是把 sculpture 里默认的力量、耐久、垂直、英雄式 gesture 拆掉。神经系统疾病改变其右臂使用能力后，制作方法也主动转向小物件、左手 drawing、脆弱支撑与叙事 assemblage。当前为 Venice 2019 方法深档案，并非其全部 oeuvre。',projects:[{title:'Icarus drives it in (temporary relief)',cluster:'temporary support / wounded monument / low-cost assemblage',period:'2018; shown Venice 2019',summary:'作品在 Venice 2019 Giardini presentation 中作为 Darling 的 non-monumental vocabulary 之一出现：不是稳定的 heroic object，而是像临时支撑、受伤肢体或勉强维持姿态的结构。',actions:['以 low-cost everyday / hardware-like materials 代替传统“高贵”雕塑材料','让支撑、连接、临时固定件保持可见，而不是隐藏 fabrication weakness','主动保留倾斜、弯折、受伤般的 body analogy','拒绝 monument 的永久性与胜利姿态，把 temporary relief / assistance 变成形式逻辑','把 object 的脆弱状态和 viewer 对身体依赖、照护、失败的经验连接'],sourceUrl:darlingIcarus,images:[],relations:[rel('展览','May You Live In Interesting Times — Venice Biennale 2019','Central Pavilion / Giardini')]},{title:'Non-macho sculpture practice',cluster:'small-object gathering / left-hand drawing / disability-informed making',period:'late 2010s–2019',summary:'Darling 明确把“hard work”“gesture”等继承来的 ableist / macho sculpture ideology 作为需要拆解的制作条件；方法因此转向 gathering、small-object assemblage、narrative formulation 与 left-hand drawing。',actions:['在身体能力变化后重新评估原有 sculpture workflow','减少依赖单次强力 gesture / heavy fabrication 的英雄式制作模式','收集 small everyday objects 并以 narrative formulation 重新组合','让 wounded、skittish、unsteady 状态成为正面形式，而不是 fabrication defect','学习以左手 drawing，直接让身体限制重写 visual language','把 non-monumentality 设为伦理与形式双重约束'],sourceUrl:darling,images:[],relations:[rel('展览','May You Live In Interesting Times — Venice Biennale 2019','Central Pavilion / Arsenale')]}],awards:[],exhibitions:['May You Live In Interesting Times — Venice Biennale 2019'],sources:[{label:'La Biennale · Jesse Darling 2019',url:darling},{label:'Artnet · Venice 2019 installation reference',url:darlingIcarus}]},

  'venice-stan-douglas':{artistId:'venice-stan-douglas',projectCoverage:'2 个 speculative-history / cinematic-photo 节点已建立深档案 · 2017–2019',imageCoverage:'0 / 2 项目暂不使用不稳定外链图像',note:'Douglas 的照片不是“抓拍历史感”，而是按 cinema production 逻辑先研究、写设定、搭 set、找 actors、精确布光再拍。Venice 2019 具体覆盖 Doppelgänger 与 Blackout；更早 speculative-history 系列尚未展开。',projects:[{title:'Doppelgänger',cluster:'two-screen video / quantum-entanglement fiction / parallel social response',period:'2019',summary:'Venice 2019 首展的 video installation 以两个可从正反两面观看的 square translucent screens 同时展开两个平行世界。同一位 astronaut Alice 在两个现实里得到相反待遇：一边被当作归来的公民照护，另一边被视为危险 alien 隔离审讯。',actions:['从 quantum teleportation / entanglement 的科学概念建立 speculative-history premise','编写两条结构相似但社会反应相反的 parallel narratives','制作两块 square-format translucent screens，并允许观众从两侧观看','以 side-by-side vignette editing 同步推进两个 reality','通过 mirrored / reversed world rules 使“同一个人”被分别编码为 citizen 与 threat','把 science-fiction production 转成 migration / othering / objective-truth 的社会实验'],sourceUrl:douglasZwirner,images:[],relations:[rel('展览','May You Live In Interesting Times — Venice Biennale 2019','debut presentation'),rel('展览','Stan Douglas: Doppelgänger — David Zwirner / Victoria Miro','2020 follow-up presentation')]},{title:'Blackout',cluster:'staged photography / emergency scenario / researched cinematic set',period:'2017; shown Venice 2019',summary:'Blackout photographs 并非 documentary images，而是 Douglas script 后重演的 hypothetical present-day New York total-power-loss emergency。每一张照片按电影 scene 的逻辑制作，使“可能发生的历史”看起来具有档案可信度。',actions:['研究 urban infrastructure / blackout conditions，建立 plausible emergency scenario','先写 script / scene premise，而不是等待现实事件发生','搭建或选择可被完全控制的 sets / locations','使用 actors 重演具体社会场景','以 meticulous cinematic lighting 建立 believable non-documentary realism','把 photograph 处理成“没有 moving image 的电影”，让 viewer 对事实/记忆来源产生迟疑'],sourceUrl:douglasZwirner,images:[],relations:[rel('展览','May You Live In Interesting Times — Venice Biennale 2019','selection from Blackout series')]}],awards:['Hasselblad Foundation International Award in Photography — 2016','Audain Prize for Visual Art — 2019'],exhibitions:['May You Live In Interesting Times — Venice Biennale 2019'],sources:[{label:'La Biennale · Stan Douglas 2019',url:douglas},{label:'David Zwirner · Stan Douglas Venice 2019',url:douglasZwirner}]},

  'venice-jimmie-durham':{artistId:'venice-jimmie-durham',projectCoverage:'2 个 rejected-object / human-nature separation 节点已建立深档案 · 2019 presentation',imageCoverage:'0 / 2 项目暂不使用不稳定外链图像',note:'Durham 把制作称为“illegal combinations with rejected objects”。这里不把动物雕塑误写成拟真 portrait：官方强调它们只近似动物体量，真正对象是 furniture、industrial material、used clothes 与 natural material 之间不合法的结合。',projects:[{title:'European large-mammal sculpture constellation',cluster:'rejected object / furniture parts / industrial material / used clothing / animal scale',period:'2019 presentation',summary:'Arsenale 的一组 sculptures 指向欧洲大型哺乳动物：每件约接近 titular animal 的真实尺度，却拒绝再现其外形。动物名只是让 viewer 重新衡量人类物质残骸与 nonhuman life 的关系。',actions:['收集 furniture parts、slick industrial materials、used clothes 与 natural materials','以“rejected objects”作为 source pool，而非采购统一雕塑材料','按 titular animal 的大致身体尺度控制 assemblage volume','避免制作 literal anatomical portrait，只保留 scale / presence clue','把材料之间的冲突称为“illegal combinations”，拒绝整洁类别系统','通过 human-made refuse 与 animal reference 的纠缠挑战 Enlightenment human/nature separation'],sourceUrl:durham,images:[],relations:[rel('展览','May You Live In Interesting Times — Venice Biennale 2019','Arsenale')]},{title:'Black Serpentine',cluster:'half-tonne stone / stainless steel frame / mass and resistance',period:'2019 presentation',summary:'Central Pavilion 的 Black Serpentine 以约半吨黑色 serpentine rock 与 stainless-steel frame 形成极端 material encounter：石头既不是被雕刻成图像，也不是 decorative geology，而以自身重量和不服从性对抗“艺术家塑形一切”的预设。',actions:['选择大体量 black serpentine stone 作为作品核心','保留 rock 的 material identity 与 mass，而不把它加工成 mimetic figure','以 stainless-steel frame 包围/界定石体','让 industrial frame 与 geological body 形成 material opposition','将重量、不可移动感与 resisting form 作为观看经验'],sourceUrl:durham,images:[],relations:[rel('展览','May You Live In Interesting Times — Venice Biennale 2019','Central Pavilion'),rel('奖项','Golden Lion for Lifetime Achievement — Venice Biennale 2019','awarded 11 May 2019')]}],awards:['Golden Lion for Lifetime Achievement — 58th Venice Biennale, 2019'],exhibitions:['May You Live In Interesting Times — Venice Biennale 2019'],sources:[{label:'La Biennale · Jimmie Durham 2019',url:durham},{label:'La Biennale · Golden Lion for Lifetime Achievement',url:durhamAward}]},

  'venice-nicole-eisenman':{artistId:'venice-nicole-eisenman',projectCoverage:'2 个 contemporary-genre / grotesque-power 节点已建立深档案 · 2015–2019',imageCoverage:'0 / 2 项目暂不使用不稳定外链图像',note:'Eisenman 的 realism 不靠 photographic likeness，而靠“当下用品”把历史 genre scene 拉回现实：iPhone、hoodie、laptop、milk crate 等具体物决定时代感；sculpture 则把 power / greed / violence 扭成 monstrous body。当前覆盖 Venice 2019 官方点名作品与同年 sculptural logic。',projects:[{title:'Weeks on the Train / Morning Studio / Dark Light',cluster:'contemporary genre scene / everyday device / porous art-life realism',period:'2015–2017; shown Venice 2019',summary:'这组被 Biennale 官方点名的 paintings 把 private / public、historical genre scene 与 present-day everyday detail 接起来；iPhone、jeans、hoodies、laptops、baseball caps、milk crates 等不是装饰，而是社会时间戳。',actions:['沿用 portrait / genre-scene 的历史 painting structure','把 smartphone、laptop、hoodie、baseball cap 等 contemporaneous objects 写入人物关系','用 milk crate 等低等级家具替代 timeless studio props','让 private posture / public social type 同时存在于同一 scene','通过日常细节而不是新闻事件标题，把作品锚定在具体历史时刻','保持 figurative distortion，使 realism 是 social recognition 而非 photographic imitation'],sourceUrl:eisenman,images:[],relations:[rel('展览','May You Live In Interesting Times — Venice Biennale 2019','Central Pavilion')]},{title:'Arsenale distorted-power sculptures',cluster:'monstrous figure / mixed material / greed-power bodily distortion',period:'2019 presentation',summary:'Arsenale sculptural works 把权力、贪婪、暴力与 money-as-value 的社会力量转成 distorted、twisted、eviscerated、cancerous bodies；政治判断通过材料化身体而不是口号出现。',actions:['把抽象 social force 先转译成 bodily deformation / grotesque character','采用 figurative sculpture 保留可识别的人体线索','允许 body 呈现 twisted、eviscerated、cancerous 等不稳定状态','在 traditional sculptural body 与 cheap/contemporary material sensibility 之间制造落差','把“恶”从单一人物肖像扩成一种能寄生在社会身体上的结构'],sourceUrl:eisenman,images:[],relations:[rel('展览','May You Live In Interesting Times — Venice Biennale 2019','Arsenale'),rel('展览','Whitney Biennial 2019 — Procession','parallel 2019 sculptural ensemble using bronze/plaster with foam, clothing, sneakers, fog/fountain elements')] }],awards:[],exhibitions:['May You Live In Interesting Times — Venice Biennale 2019','Whitney Biennial 2019'],sources:[{label:'La Biennale · Nicole Eisenman 2019',url:eisenman},{label:'Whitney Museum · Nicole Eisenman / Procession',url:eisenmanWhitney}]},

  'venice-haris-epaminonda':{artistId:'venice-haris-epaminonda',projectCoverage:'1 个 found-object constellation 节点已建立深档案 · 2019',imageCoverage:'0 / 1 项目暂不使用不稳定外链图像',note:'Epaminonda 的 2019 presentation 可确认题名 VOL. XXVII，并获 Silver Lion。官方材料强调她按 object 的 qualia 选择 sculpture、pottery、book、photograph 等 found materials；其历史并未被解释清空，而是在重新并置后保持潜伏。更早 VOL. 系列尚未逐卷拆解。',projects:[{title:'VOL. XXVII',cluster:'found sculpture / pottery / book / photograph / image-object constellation',period:'2019',summary:'mixed-media installation 通过 carefully constructed constellations 把 found images、objects、text、forms、colours 压缩在一起。每件物的 personal / historical provenance 不被完整说明，反而以 fragmented memory 和 imagined connection 的方式在新组合里持续施力。',actions:['从 found sculptures、pottery、books、photographs 等异质物中选材','不是优先按 iconography 选，而按不可还原的 experiential qualia 判断 object 是否“发亮”','将具有不同 provenance 的物件重新组织成精确的 spatial constellation','不提供完整 provenance map，让历史意义保持 implicit','通过距离、颜色、形状、尺度与物件朝向建立 imagined connections','把 personal memory 与 historical residue 压缩成 loose but powerful network，而不追求单一 narrative closure'],sourceUrl:epaminonda,images:[],relations:[rel('展览','May You Live In Interesting Times — Venice Biennale 2019','Central Pavilion / Arsenale'),rel('奖项','Silver Lion for a Promising Young Participant — Venice Biennale 2019','jury cited constellations of images, objects, text, forms and colours')]}],awards:['Silver Lion for a Promising Young Participant — 58th Venice Biennale, 2019'],exhibitions:['May You Live In Interesting Times — Venice Biennale 2019'],sources:[{label:'La Biennale · Haris Epaminonda 2019',url:epaminonda},{label:'La Biennale · Official Awards 2019',url:epaminondaAward},{label:'Hara Museum · VOL. XXVII reference',url:epaminondaVol}]}
};
