import type { ArtistArchive, ArchiveRelation } from './archiveData';

const rel = (kind: ArchiveRelation['kind'], label: string, detail?: string): ArchiveRelation => ({ kind, label, detail });

export const archiveBatch154: Record<string, ArtistArchive> = {
  'venice-george-condo': {
    artistId: 'venice-george-condo',
    projectCoverage: '4 个 art-history recombination / psychological cubism / drawing-painting 节点深化 · 1980s–2019',
    imageCoverage: '0 / 4',
    note: '把 Condo 从“引用旧大师的怪诞肖像”推进成一条制作方法线：Fake Old Masters 先伪造历史合法性；Artificial Realism 再把既有绘画语法拆解重组；到 Rush Hour 一类 drawing-painting，人物、都市拥挤与 Cubist multiple viewpoints 被压进线性结构。重要之处不是 citation 数量，而是他把 Velázquez、Goya、Picasso、Gorky、de Kooning 等历史语法当作仍可实时运算的 visual vocabulary。',
    projects: [
      { title:'Fake Old Masters', cluster:'appropriation / false historicity / portrait', period:'early 1980s', summary:'Condo 早期故意制造似乎来自既有欧洲绘画传统、实际上并不存在于历史中的“旧大师”图像。方法不是复制单件名作，而是学习 pose、brushwork、portrait convention 后制造一种可信却错误的历史记忆。', actions:['拆解 Old Master portrait 的 pose、lighting、brushwork 与 social type','重新组合成没有真实原作的 pseudo-historical painting','保留 recognisable art-history syntax，同时让 anatomy / expression 出现不可能的错位','让观看者先产生 historical recognition，再发现来源无法被稳定定位'], sourceUrl:'https://www.labiennale.org/en/art/2019/partecipants/george-condo', images:[], relations:[] },
      { title:'Artificial Realism / reconstructed reality', cluster:'art-history syntax / grotesque anatomy / psychic portrait', period:'mid-1980s–2000s', summary:'Condo 将自己的方法概括为拆掉一种现实，再用同样部件建立另一种现实。人物因此同时具有 cartoon、Cubism、Old Master portrait 与心理崩解的痕迹；“变形”不是效果，而是不同视觉系统同时占据同一张脸的结果。', actions:['把 eyes / mouths / profiles / frontal views 当作可重排部件','允许多个视点同时存在于单一 portrait','把 cartoon vulgarity 与 museum painting authority 放在同一层级','以 repeated character types 建立跨作品的社会剧场'], sourceUrl:'https://www.labiennale.org/en/art/2019/partecipants/george-condo', images:[], relations:[rel('展览','May You Live In Interesting Times — Venice Biennale','2019')] },
      { title:'Study for The Jester', cluster:'drawing / character construction / disfiguration', period:'2003', summary:'MoMA 馆藏铅笔纸本说明 drawing 并非 Condo 绘画之前的次级草稿，而是其人物构造与 disfiguration 的独立实验场；该作后来进入 MoMA 2012 Exquisite Corpses: Drawing and Disfiguration 的展览史。', actions:['以 pencil line 快速测试 facial construction','让 character type 在少量线条中保持 recognizable identity','用 drawing 暴露 painting 中被颜料覆盖的结构决定','把 grotesque portrait 与 drawing/disfiguration 的更广历史连接'], sourceUrl:'https://www.moma.org/collection/works/95692', images:[], relations:[rel('收藏','Museum of Modern Art, New York','Judith Rothschild Foundation Contemporary Drawings Collection Gift'),rel('展览','Exquisite Corpses: Drawing and Disfiguration — MoMA','2012')] },
      { title:'Rush Hour', cluster:'drawing-painting / crowd / analytic-cubist viewpoints', period:'2010', summary:'Met 馆藏的 Rush Hour 把通勤人群压成高度拥挤的群像。馆方指出其中出现 Condo 长期角色 Rodrigo，破碎身体对应 analytic cubism 的 multiple viewpoints；艺术家自己称这类作品为 drawing painting。', actions:['以 graphite / charcoal / pastel 与 acrylic 同时构造 canvas','让 line 而非完整体积主导人物组织','重复既有 character Rodrigo，使单幅作品进入长期人物谱系','借 multiple viewpoints 把都市 crowd 变成心理和空间同时过载的结构'], sourceUrl:'https://www.metmuseum.org/art/collection/search/498256', images:[], relations:[rel('收藏','The Metropolitan Museum of Art, New York','Modern and Contemporary Art · acquired 2011')] }
    ],
    awards: [],
    exhibitions: ['May You Live In Interesting Times — Venice Biennale 2019','Exquisite Corpses: Drawing and Disfiguration — MoMA 2012'],
    sources: [{label:'La Biennale · George Condo 2019',url:'https://www.labiennale.org/en/art/2019/partecipants/george-condo'},{label:'MoMA · Study for The Jester',url:'https://www.moma.org/collection/works/95692'},{label:'The Met · Rush Hour',url:'https://www.metmuseum.org/art/collection/search/498256'}]
  },

  'venice-arthur-jafa': {
    artistId:'venice-arthur-jafa',
    projectCoverage:'5 个 cinematography / source-book archive / Black visual intonation / montage / institutional-network 节点深化 · 1991–2020',
    imageCoverage:'0 / 5',
    note:'把 Jafa 从“found-footage montage”扩回 cinematography 与长期 source-book archive。核心问题始终是：视觉媒介怎样获得 Black music 的 power、beauty、alienation。其方法并非只靠选取政治影像，而包括摄影机身体感、数十年图像采集、剪辑节奏、frame manipulation、guest/platform collaboration 与展览空间中的声音组织。',
    projects:[
      {title:'Daughters of the Dust — cinematography',cluster:'cinematography / Black independent cinema / visual rhythm',period:'1991',summary:'Jafa 在 Julie Dash 的 Daughters of the Dust 担任摄影指导，并凭摄影获得 Sundance recognition。这个电影训练解释了他后来为何持续把 framing、movement、rhythm 与 Black cultural form 放在一起思考，而不是把 found footage 当普通档案拼贴。',actions:['把 cinematography 作为身体、光线和节奏的组织问题','在 narrative cinema 内发展对 Black visual form 的长期兴趣','把摄影指导经验转化为后来 gallery moving-image practice 的技术基础'],sourceUrl:'https://www.serpentinegalleries.org/whats-on/arthur-jafa-series-utterly-improbable-yet-extraordinary-renditions/',images:[],relations:[rel('奖项','Sundance Film Festival — cinematography recognition','Daughters of the Dust')]},
      {title:'Source Books / image archive',cluster:'vernacular archive / image sampling / unwritten history',period:'1980s–ongoing',summary:'Serpentine 记录 Jafa 自 1980s 起持续积累 source books。新闻、vernacular portrait、music、网络图像与艺术史材料不是临时为某部影片搜集，而是形成长期可重复采样的私人视觉数据库。',actions:['跨数十年持续收集 printed / vernacular / media imagery','不按单一主题封闭 archive，而允许不同年代材料重新相遇','把 source book 当 montage 前的研究基础设施','通过重新排序图像追踪未被正式书写的 Black histories'],sourceUrl:'https://www.serpentinegalleries.org/whats-on/arthur-jafa-series-utterly-improbable-yet-extraordinary-renditions/',images:[],relations:[rel('展览','A Series of Utterly Improbable, Yet Extraordinary Renditions — Serpentine','2017')]},
      {title:'Love Is the Message, The Message Is Death',cluster:'found-footage montage / Black visual intonation / music-image relation',period:'2016',summary:'7分25秒影片把 civil-rights imagery、LA uprising、police violence、dance、sports、family material 与 viral media 放在 Ultralight Beam 上。Hirshhorn 对其“Black visual intonation”的解释尤其关键：通过轻微 slow/accelerated frame manipulation 强调动作内部的重音，使剪辑不只是内容 juxtaposition，也模拟 vocal/musical intonation。',actions:['从 YouTube、stock footage、新闻、家庭影像与既有电影抽取异质素材','保留 watermark / low-fi circulation traces，而非抹平来源','以 visual resemblance 与 affective resonance 代替线性历史叙事','用 subtle slow motion / acceleration 强调 gesture 内部重音','让 violence、joy、virtuosity 与 mourning 快速相邻，拒绝单一 Black-image category'],sourceUrl:'https://hirshhorn.si.edu/explore/arthur-jafa-love-is-the-message-the-message-is-death/',images:[],relations:[rel('收藏','MOCA Los Angeles','2017 acquisition'),rel('收藏','multi-museum international holdings','2020 coordinated screening included 13 collecting institutions')]},
      {title:'A Series of Utterly Improbable, Yet Extraordinary Renditions',cluster:'immersive assemblage / guest platforms / collaborative authorship',period:'2017',summary:'Serpentine 个展把 film、photography、found footage 与其他创作者的平台一起组织为空间 assemblage。Ming Smith、Frida Orupabo 的 Instagram feed 与 Missylanyus YouTube content 被明确作为 integral guests，而不是背景 reference；这使 Jafa 的 archive logic 从个人剪辑扩成关系网络。',actions:['把 still / moving image 分布为空间化 assemblage','邀请 Ming Smith、Frida Orupabo 与 Missylanyus 的平台进入 exhibition structure','把 influence 明示为作品组成，而非隐藏成 authorial source','通过 exhibition architecture 让不同 image regimes 并置'],sourceUrl:'https://www.serpentinegalleries.org/whats-on/arthur-jafa-series-utterly-improbable-yet-extraordinary-renditions/',images:[],relations:[rel('展览','Serpentine North Gallery','2017'),rel('策展','Serpentine exhibition network','included Ming Smith, Frida Orupabo, Missylanyus')]},
      {title:'The White Album',cluster:'whiteness / video essay / Black gaze',period:'2019',summary:'Venice 2019 获主展最佳参展者金狮奖。作品延续 sampling/montage，但把 whiteness 置于被观察位置，使 Black gaze 不再只是回应 Black representation，而主动分析 white subjectivity、attraction 与 violence 的纠缠。',actions:['混合 network footage、portrait 与 found image','让 whiteness 成为被观看和被分类的对象','维持 attraction / intimacy / threat 之间的不稳定关系','继续以 montage 而非 explanatory voice-over 生成论证'],sourceUrl:'https://www.labiennale.org/en/news/biennale-arte-2019-official-awards',images:[],relations:[rel('奖项','Golden Lion for Best Participant — Venice Biennale','2019'),rel('展览','May You Live In Interesting Times','2019')]}
    ],
    awards:['Golden Lion for Best Participant — Venice Biennale 2019','Sundance cinematography recognition — Daughters of the Dust'],
    exhibitions:['A Series of Utterly Improbable, Yet Extraordinary Renditions — Serpentine 2017','May You Live In Interesting Times — Venice Biennale 2019'],
    sources:[{label:'Serpentine · Arthur Jafa 2017',url:'https://www.serpentinegalleries.org/whats-on/arthur-jafa-series-utterly-improbable-yet-extraordinary-renditions/'},{label:'MOCA · Love Is The Message',url:'https://www.moca.org/artworks/love-is-the-message-the-message-is-death-2'},{label:'Hirshhorn · Love Is The Message / Black visual intonation',url:'https://hirshhorn.si.edu/explore/arthur-jafa-love-is-the-message-the-message-is-death/'},{label:'La Biennale · Arthur Jafa award 2019',url:'https://www.labiennale.org/en/news/biennale-arte-2019-official-awards'}]
  },

  'venice-jon-rafman': {
    artistId:'venice-jon-rafman',
    projectCoverage:'4 个 automated-camera / avatar ethnography / archive / CGI dystopian-futurity 节点深化 · 2008–2019',
    imageCoverage:'0 / 4',
    note:'把 Rafman 从 Venice 的“CGI dystopia”单点扩回 post-internet 方法源头。他的重要性在于持续改变作者位置：Nine Eyes 中作者变成从自动摄影系统里筛图的人；虚拟世界项目中变成 avatar ethnographer；随后把 network debris、memory 与 CGI 重新合成为越来越封闭、身体化的 digital environments。与 Ian Cheng 的 autonomous simulation 不同，Rafman 更关心已经存在的网络文化、平台图像与技术欲望如何留下心理废墟。',
    projects:[
      {title:'The Nine Eyes of Google Street View',cluster:'automated photography / platform archive / found image',period:'2008–ongoing',summary:'Rafman 从 Google Street View 的机器化街景数据库中持续筛选异常、暴力、荒诞、亲密或偶然具有构图感的画面。MAC Montréal 将该系列视为其国际关注的重要起点，并强调他作为 web-culture explorer / archivist 的角色。',actions:['把 Google Street View 当作全球自动摄影系统而非中性地图','不亲自拍摄，而在既有平台数据库中执行 selection / framing','寻找 algorithmic capture 无意记录的 social accident 与 visual coincidence','保留 platform gaze 的冷漠与被摄现实的情绪强度之间的冲突','通过长期 accumulation 把 navigation infrastructure 转成 photographic archive'],sourceUrl:'https://macm.org/publications/jon-rafman/',images:[],relations:[]},
      {title:'Virtual-world / avatar ethnography practice',cluster:'online subculture / avatar / virtual-real translation',period:'late 2000s–2010s',summary:'MAC Montréal 对 Rafman 的整体实践强调 virtual/real、historical/personal、memory/subjective 之间的边界。他进入网络文化并非只截屏，而把 avatar、virtual environment 与用户创造的次文化视为新的社会田野。',actions:['把 online world 当作具有自身 ritual / identity / social code 的 field site','通过 avatar position 模糊 observer 与 participant','收集 ephemeral digital behaviour 与 user-made imagery','把 virtual material 再转成 video、installation、sculpture、photography / painting','持续比较线上身份与 physical self-perception 如何互相塑造'],sourceUrl:'https://macm.org/publications/jon-rafman/',images:[],relations:[]},
      {title:'Web-culture archive / third-space practice',cluster:'memory / subjectivity / material-virtual hybrid',period:'2010s',summary:'2015 MAC Montréal monograph把 Rafman 描述为网络文化的 explorer and archivist；其作品跨 video、installation、sculpture、photography 与 painting，把 material / virtual elements 混在一起，形成既熟悉又无法稳定定位的“third space”。',actions:['从网络碎片建立非官方文化 archive','让 historical memory 与 personal / subjective memory 相互污染','把 screen-native material 转译成 physical exhibition object','拒绝把 online/offline 当作两个封闭世界，而研究两者之间持续翻译'],sourceUrl:'https://macm.org/publications/jon-rafman/',images:[],relations:[rel('出版','Jon Rafman — Musée d’art contemporain de Montréal monograph','2015')]},
      {title:'Dystopian futurity — Venice 2019',cluster:'moving image / CGI / failed technological utopia',period:'2019',summary:'La Biennale 将其 2019 实践概括为对 Modernist utopian future 与 late-capitalist postmodern dystopia 的比较。moving image 与 computer-generated graphics 不再展示新技术的“未来感”，而表现 technology 已经内化为 alienation、desire 与 decay 的心理环境。',actions:['以 moving image / CGI 建立人工 digital environments','主动回避 technology-as-progress 的 optimistic iconography','把 modernist utopia 与 late-capitalist dystopia 设为历史对照','让网络文化的既有碎片重新进入 synthetic future','把 digital environment 处理成心理空间而非 neutral interface'],sourceUrl:'https://www.labiennale.org/en/art/2019/partecipants/jon-rafman',images:[],relations:[rel('展览','May You Live In Interesting Times — Venice Biennale','2019 · Central Pavilion / Arsenale')]}
    ],
    awards:[],
    exhibitions:['May You Live In Interesting Times — Venice Biennale 2019'],
    sources:[{label:'Musée d’art contemporain de Montréal · Jon Rafman monograph',url:'https://macm.org/publications/jon-rafman/'},{label:'La Biennale · Jon Rafman 2019',url:'https://www.labiennale.org/en/art/2019/partecipants/jon-rafman'}]
  }
};
