import type { ArtistArchive, ArchiveProject, ArchiveRelation } from './archiveData';

const rel=(kind:ArchiveRelation['kind'],label:string,detail?:string):ArchiveRelation=>({kind,label,detail});
const project=(p:ArchiveProject)=>p;

export const archiveBatch287:Record<string,ArtistArchive>={
  'cao-fei':{
    artistId:'cao-fei',
    projectCoverage:'作品级深化批次：从此前 RMB City 扩展到工厂劳动与自动化物流两条关键线索，拆解 Whose Utopia 的影像/装置版本及 Asia One 的电影、复合装置和后续放映版本。',
    imageCoverage:'5 / 5 节点均核到 Guggenheim、M+、Blanton、Pinault Collection、Fondation Louis Vuitton 等机构的对应作品或安装图。图像均处于版权保护状态；本批不复制受限文件，images 保持暂缺，并在 relations 中记录图片入口、摄影 credit 与权利状态。',
    note:'本批特别记录曹斐如何从真实生产现场开始工作：驻厂、问卷、与工人共同排演，再到十余年后进入高度自动化物流中心拍摄，并把真实物流物件、品牌制服、包装、录像与虚构叙事重新组织成博物馆装置。',
    projects:[
      project({title:'Whose Utopia — single-channel video',cluster:'factory / labor / performance / video',period:'2006',summary:'曹斐在珠三角佛山 OSRAM 照明工厂驻留约六个月，不是从外部短暂拍摄工人。她先观察并记录灯泡生产线和日常劳动，又向工人发放问卷，询问背景、愿望与个人理想；随后与部分工人共同发展表演，让他们在仍然运转的工厂空间里暂时成为自己想成为的人：芭蕾舞者、吉他手、太极表演者等。最终单频道影片被组织为三个段落：生产与机器、工人的幻想性表演、以及回到现实后面对镜头的静态肖像。M+ 馆藏记录为 single-channel digital video, colour, sound，20分20秒；Blanton 版本记录为 single channel color video with sound，edition 8/12，约20分钟。',actions:['在 OSRAM China Lighting Ltd. 工厂进行约六个月驻留和现场观察。','拍摄灯泡生产、装配、机器与工人日常动作。','向工人发问卷，收集个人背景、愿望和未来想象。','与参与者共同设计并拍摄舞蹈、吉他、太极等表演，让表演发生在真实生产线旁。','把素材剪成生产—幻想表演—正面肖像三个段落，形成约20分钟单频道录像。'],sourceUrl:'https://www.mplus.org.hk/en/collection/objects/whose-utopia-201285/',images:[],relations:[rel('馆藏','M+ Sigg Collection','2006；single-channel digital video (colour, sound)，20 min 20 sec；© Cao Fei。'),rel('馆藏','Blanton Museum of Art','馆藏页面提供作品预览/IIIF；Rights Statement: IN COPYRIGHT，因此不复制进仓库。'),rel('图片','Fondation Louis Vuitton official images','官方作品页提供对应影像静帧/展示图，credit: Photo © Fondation Louis Vuitton / Martin Argyroglo；© Cao Fei。')]}),
      project({title:'Whose Utopia Installation — mixed-media version',cluster:'installation / worker archive / dormitory / video',period:'2006–2007',summary:'Whose Utopia 不只存在为20分钟录像。其装置版本把驻厂研究产生的材料重新组织为空间：核心 Whose Utopia 录像与较长的 Interview 录像并置，并在部分展览版本中加入工人宿舍里的金属双层床、个人纪念物和与调查相关的材料，使观众面对的不再只是剪辑后的电影，而是生产空间、居住空间、访谈与个人愿望组成的劳动档案。Pinault Collection 将馆藏明确登记为 video and mixed media installation，其中 Whose Utopia 20分9秒、Interview 35分29秒。不同场馆因此可以按照空间重新布置录像与实体材料。',actions:['保留主录像之外的工人访谈影像，使驻厂调查本身进入作品。','收集/调用与工人宿舍和日常生活相关的实体物件与展示材料。','把录像、访谈与 mixed media 组织成可随展厅重新配置的空间装置。','让观众从观看生产线进一步转向工人的居住条件、个人物件和口述愿望。'],sourceUrl:'https://lesoeuvres.pinaultcollection.com/en/artwork/whose-utopia-installation',images:[],relations:[rel('馆藏','Pinault Collection','2006–2007；video and mixed media installation；Whose Utopia 20:09 + Interview 35:29。'),rel('版本','Plateau 2008 / Garage Moscow 2009','Pinault 保存不同空间的安装现场；Plateau 图摄影 Martin Argyroglo，Garage 图摄影 Roman Suslov；均标 © Cao Fei，未确认开放再发布。')]}),
      project({title:'Asia One — central fictional film',cluster:'automation / logistics / science fiction / HD video',period:'2018',summary:'十余年后，曹斐把劳动研究从人工密集的灯泡厂推进到自动化物流系统。她实地访问中国先进工业设施，包括江苏昆山的高度自动化分拣中心，并把真实物流基础设施转成科幻叙事场景。影片把巨大仓库设定为近未来空间，只留下两名人类员工与高速运作的机器人/输送系统；两人的关系在高度标准化的效率环境中逐渐变化。影片还插入未来访客重新考察废弃设施以及带有样板戏视觉痕迹的集体舞蹈段落。Guggenheim 馆藏记录主片为 color video with sound，63 min 20 sec；Taikang 亦记录 single-channel HD video, 16:9, color, sound, 63分20秒。',actions:['实地进入并研究中国先进物流/自动化工业设施，包括昆山自动化分拣中心。','利用真实仓库、输送与机器人基础设施作为影片场景，而不是完全在摄影棚搭景。','安排两名主要人类角色在自动化系统中表演孤独、关系与对效率秩序的偏离。','加入未来考察者与带历史政治视觉语汇的舞蹈段落，把不同时间层叠在同一工业空间。','剪辑成63分20秒有声彩色主片，既可独立放映，也可嵌入完整装置。'],sourceUrl:'https://www.guggenheim.org/artwork/38191',images:[],relations:[rel('委任','Solomon R. Guggenheim Museum','Robert H. N. Ho Family Foundation Chinese Art Initiative 委任并进入馆藏，accession 2018.12。'),rel('馆藏','Taikang Art Museum','记录主片技术参数为 single channel HD video (16:9 color sound), 63’20’’。')]}),
      project({title:'Asia One — Guggenheim multimedia installation',cluster:'multimedia installation / found objects / logistics infrastructure',period:'2018',summary:'Guggenheim 馆藏的 Asia One 不是把63分钟电影挂在墙上播放，而是一套尺寸可变的复合装置。除主片外还有三段不同长度的彩色视频；墙面使用 inkjet-printed mural，并把喷墨图像输出到铝、画布、纸、缎面和透明胶片，再与亚克力、铝材、灯箱和木框组合。现场还放入一辆被重新绘制和改装的电动三轮车，附地毯、护符、照片、扫码器、手套、锁钥匙、塑料筐、邮政单据、绳索、圣诞老人服装、鞋、串灯和玩偶等；同时使用麻袋及大量带 JD.com 标识的真实物流物件，包括制服、工牌、头盔、包装箱、胶带、快递标签和工具。真实物流系统因此被搬进展厅，与虚构电影互相验证。',actions:['把主电影与三段附加录像组合为多通道/多节点影像环境。','制作喷墨墙画，并在铝、画布、纸、缎面、透明胶片等不同承载物上输出图像。','改装真实电动三轮车并附着物流、生活与节庆物件。','收集 JD.com 品牌制服、工牌、头盔、包装、标签、胶带、工具等真实物流材料。','使用灯箱、木框、铝材、亚克力和麻袋等把影像、商品流通物与展厅结构整合为尺寸可变装置。'],sourceUrl:'https://www.guggenheim.org/artwork/38191',images:[],relations:[rel('材料','Guggenheim collection specification','官方馆藏逐项列出4组视频、inkjet mural/prints、motorized tricycle、hemp sacks 与 JD.com branded objects；dimensions variable。'),rel('图片','Guggenheim official artwork image','官方作品页提供对应装置图；Copyright © Cao Fei，未标示自由再发布许可，故仅记录入口。')]}),
      project({title:'Asia One — MAXXI videogallery screening version',cluster:'film screening / spatial adaptation',period:'16 Dec 2021–30 Jan 2022',summary:'在 MAXXI 的 videogallery 版本中，Asia One 从 Guggenheim 的复杂复合装置被压缩为电影放映：机构以约63分钟影片为核心，并每天按11:30、12:45、14:00、15:15、16:30、17:45多个固定场次循环。这一版本的重要性在于它显示同一项目的观看机制可以发生根本变化：Guggenheim 版本要求观众在物流物件、墙画、附加录像和主片之间移动，而 MAXXI 版本把观看重新集中为有起止时间的单屏电影经验。',actions:['从完整 Asia One 复合装置中抽离63分钟主片作为独立展示对象。','在 videogallery 中按固定时刻循环放映，使观众按电影时间而不是自由游走进入作品。','保留自动化物流、两名工人与机器人关系的核心叙事，但取消大量实体物流物件和附属影像的空间层。'],sourceUrl:'https://www.maxxi.art/en/events/asia-one-caofei/',images:[],relations:[rel('版本','MAXXI videogallery','16 Dec 2021–30 Jan 2022；主片约63分钟；官方页面列出每日六个放映起始时间。'),rel('版本差异','Guggenheim installation → MAXXI screening','从尺寸可变、含真实物流物件与多段影像的环境，转为按固定场次观看的单片放映。')]} )
    ],
    exhibitions:['Whose Utopia — Blanton Museum of Art','One Hand Clapping — Guggenheim, 2018','Asia One — MAXXI, 2021–2022'],
    sources:[{label:'Guggenheim — Cao Fei / Asia One',url:'https://www.guggenheim.org/artwork/38191'},{label:'M+ — Whose Utopia',url:'https://www.mplus.org.hk/en/collection/objects/whose-utopia-201285/'},{label:'Blanton — Cao Fei: Whose Utopia',url:'https://blantonmuseum.org/exhibition/cao-fei-whose-utopia/'},{label:'Pinault Collection — Whose Utopia Installation',url:'https://lesoeuvres.pinaultcollection.com/en/artwork/whose-utopia-installation'},{label:'MAXXI — Asia One',url:'https://www.maxxi.art/en/events/asia-one-caofei/'}]
  }
};
