import type { ArchiveProject, ArchiveRelation } from './archiveData';
const rel=(kind:ArchiveRelation['kind'],label:string,detail?:string):ArchiveRelation=>({kind,label,detail});
export const archiveExtensions270:Record<string,ArchiveProject[]>={
'cao-fei':[
{title:'Whose Utopia — factory residency as collaborative production',cluster:'factory / labor / performance / Pearl River Delta',period:'2006',summary:'《谁的乌托邦》来自曹斐在珠三角佛山 OSRAM 照明工厂约六个月的驻留。MoMA 将影片明确分成三个部分：生产线的冷静记录、工人在同一厂房中实现个人幻想的表演，以及工厂现实与个人愿望之间的重新并置。重要之处在于她没有把工人仅仅当成被拍摄的劳动对象，而是与他们共同发展表演，让芭蕾、吉他、舞蹈等个人身份暂时进入标准化生产空间。作品因此把“工厂纪录”改造成一种参与式生产协议：先进入真实工业系统，再让系统中的人主动制造另一种自我形象。',actions:['以驻留方式长期进入 OSRAM 工厂，而非一次性外部拍摄。','记录真实生产线、机器、劳动节奏和工作环境。','与工人沟通个人愿望并共同发展在厂房内发生的表演。','把工业纪录、个人表演和群体肖像编辑成三段式影片。','让同一空间同时承担标准化生产与个人幻想两种互相冲突的功能。'],sourceUrl:'https://www.moma.org/calendar/galleries/5256',images:[],relations:[rel('机构','OSRAM lighting factory, Foshan','约六个月驻留构成作品的生产条件。'),rel('收藏/展示','Museum of Modern Art','2020–2021 Collection gallery 212 专门展示 Whose Utopia。'),rel('方法','field residency → collaboration → staged performance','从观察劳动转向与劳动者共同制造影像。')]},
{title:'RMB City — virtual city as social artwork',cluster:'Second Life / virtual urbanism / art market / participation',period:'2007–2011',summary:'RMB City 不是一段关于虚拟城市的视频，而是在 Second Life 中真正持续运行数年的城市型作品。Guggenheim 资料显示，曹斐以 China Tracy 身份活动，把天安门、鸟巢、东方明珠等中国城市符号重新拼装，并借当代艺术市场参与者购买虚拟土地来支持建设。城市建成后继续承载活动、展览、社交与 avatar 参与，因此作品同时包含数字拼贴、城市规划、角色扮演、社会关系和虚拟经济。它把《谁的乌托邦》中“现实工业空间里的个人幻想”推进成“直接搭建一个可供他人进入的社会空间”。',actions:['在 Second Life 内设计并建设完整虚拟城市。','从中国现实城市景观提取建筑与政治/消费符号并重新组合。','以 China Tracy avatar 作为城市内部的组织者与参与者。','借艺术市场的真实购买力支持虚拟土地与城市建设。','组织活动、展览和参与行为，使城市在建成后继续作为社会平台运行。'],sourceUrl:'https://www.guggenheim.org/teaching-materials/teaching-modern-and-contemporary-asian-art/cao-fei-%E6%9B%B9-%E6%96%90',images:[],relations:[rel('平台','Second Life','作品实际存在和运行的平台。'),rel('角色','China Tracy','曹斐在虚拟城市中的 avatar / organizer。'),rel('演变','Whose Utopia → RMB City → Asia One','从现实生产空间中的幻想，进入可参与虚拟社会，再回到高度自动化现实基础设施。')]}
],
'trevor-paglen':[
{title:'Untitled (Predators; Indian Springs, NV)',cluster:'military secrecy / drone infrastructure / landscape',period:'2010',summary:'这件60×48英寸 chromogenic print 把几乎不可见的 Predator 无人机压缩进传统天空/风景图像。Smithsonian 的说明强调，Paglen 处理的是军事与情报系统的秘密运作：画面首先像普通云层与天空，标题才迫使观众意识到远处存在 Predator drones。作品的方法不是取得官方内部影像，而是从公共地面位置、依靠距离摄影和精确地点知识，让秘密基础设施以“可见但难以辨认”的方式进入风景摄影。',actions:['研究军事设施与飞行活动的位置和公开可观察条件。','从公共地面位置对远距离目标进行摄影。','保留大面积天空和云层，使军事对象在视觉上保持微小。','用描述性地点/目标信息补充图像，使知识与肉眼观看之间产生张力。'],sourceUrl:'https://americanart.si.edu/artwork/untitled-predators-indian-springs-nv-82771',images:[],relations:[rel('收藏','Smithsonian American Art Museum','2010 chromogenic print；2012入藏。'),rel('方法','landscape + investigative research','风景摄影不再只是地貌，而成为军事基础设施的观察界面。')]},
{title:'NEMESIS Rocket Body in Orion',cluster:'classified satellites / orbital debris / astrophotography',period:'2009',summary:'Paglen 把秘密基础设施的观察尺度从地面军事基地推进到轨道空间。Smithsonian 馆藏记录确认作品拍摄的是与 Satellite Data System spacecraft 相关的 discarded rocket body，并以60×48英寸 chromogenic print 呈现。星空在这里不是浪漫天文景观，而是被卫星、火箭残骸和国家技术系统占据的基础设施空间；标题中的技术识别信息使肉眼几乎无法理解的光点获得政治和工程身份。',actions:['研究卫星、火箭体与轨道对象的公开追踪资料。','把天文摄影技术用于通常属于军事/情报研究的对象。','将极微小轨道目标置入大尺度星空图像。','以技术化标题提供对象身份，使图像与数据库知识共同构成作品。'],sourceUrl:'https://americanart.si.edu/artwork/nemesis-rocket-body-orion-discarded-rocket-satellite-data-system-spacecraft-usa-179rb-82772',images:[],relations:[rel('收藏','Smithsonian American Art Museum','2009 chromogenic print；Gift of Nion McEvoy。'),rel('演变','restricted landscape → orbital infrastructure','秘密地理从沙漠基地扩展到地球轨道。')]}
],
'carrie-mae-weems':[
{title:'Projects 52 — The Apple of Adam’s Eye',cluster:'gender / mythology / installation / Africa',period:'1993–1995 exhibition context',summary:'MoMA 的 Projects 52 标志着 Weems 从此前集中处理北美奴隶制遗产的 Sea Island / Africa 系列，进一步进入性别差异和权力关系。展览核心《The Apple of Adam’s Eye》并非单张摄影，而是 painted and embroidered screen，并与非洲建筑黑白照片、艺术家原创文字、经过处理的 fetish 图像、墙纸和雕塑物件共同构成环境。这个节点说明她的媒介演变并不是从“摄影”简单转向“装置”，而是开始让摄影、文字、装饰表面和物件共同承担叙事。',actions:['把性别权力作为新的叙事轴线，与此前种族/历史研究连接。','制作绘画与刺绣屏风作为展览空间核心。','拍摄带有性别联想的非洲建筑形式并配置原创文字。','改造男性/女性 fetish 图像并加入雕塑物件和墙纸。','把多个媒介编排成完整空间，而非让单张照片独立承担意义。'],sourceUrl:'https://www.moma.org/calendar/exhibitions/476',images:[],relations:[rel('展览','Projects 52: Carrie Mae Weems — MoMA','重要早期机构个展节点。'),rel('演变','Sea Island / Africa → gender mythology','从奴隶制历史与民俗研究扩展到性别、欲望与社会权力。'),rel('媒介','photography → installation ecology','照片、文本、刺绣屏风、墙纸和物件形成统一叙事环境。')]},
{title:'Three Decades of Photography and Video — retrospective network',cluster:'retrospective / institutional history / media expansion',period:'2014',summary:'Guggenheim 2014 回顾展是 Weems 在纽约的首个大型博物馆回顾展，汇集120余件作品，以摄影为主，同时纳入文字、录像和声音。机构的回顾结构把她从早期纪录/自传摄影，经 Kitchen Table、档案挪用和历史研究，一直连接到录像与全球范围的种族、帝国、平等问题。这个展览节点适合网站作为“机构网络枢纽”：它证明 Weems 的核心并非某一种固定视觉风格，而是持续改变媒介来研究历史如何塑造当下身份。',actions:['将三十年不同系列按历史与方法关系重新并置。','把摄影、文字、声音和录像纳入同一回顾结构。','通过跨地域项目连接美国种族史与更广泛的帝国、平等和历史记忆问题。'],sourceUrl:'https://www.guggenheim.org/exhibition/carrie-mae-weems-three-decades-of-photography-and-video',images:[],relations:[rel('展览','Carrie Mae Weems: Three Decades of Photography and Video — Guggenheim','24 Jan–14 May 2014；120余件作品。'),rel('机构','Solomon R. Guggenheim Museum','首个纽约大型博物馆回顾展。'),rel('方法','documentary/autobiography → conceptual archive → video/installations','机构回顾展清楚呈现媒介和研究尺度的长期扩张。')]}
]
};