import type { ArtistArchive, ArchiveRelation } from './archiveData';

const rel=(kind:ArchiveRelation['kind'],label:string,detail?:string):ArchiveRelation=>({kind,label,detail});

export const archiveBatch262:Record<string,ArtistArchive>={
  'allan-sekula':{
    artistId:'allan-sekula',
    projectCoverage:'作品级深化：把 Fish Story 从“港口纪录摄影”拆成跨港口田野、劳动者视角、基础设施/自动化、摄影序列与文字面板共同工作的政治经济学视觉研究，并落到 MoMA 馆藏 Chapter One 及具体图像节点。',
    imageCoverage:'MoMA 保存 Fish Story Chapter One 及 Lead Fish、Pancake、Rotterdam automated terminal 等具体作品图与安装记录；作品仍受 Estate of Allan Sekula 版权保护，因此仅保存官方图像入口，不复制受限文件。',
    note:'Sekula 的关键不是把码头拍得“社会纪实”，而是反对把全球化理解为抽象的资本流动。他持续把船员、码头工、拆船/维修、集装箱、自动化设备、港口住宅与企业设计放在同一叙事中，让海运重新显现为由劳动、技术和地理不平等维持的物质系统。',
    projects:[
      {title:'Chapter One, Fish Story',cluster:'Fish Story / political economy / photo-text sequence',period:'1988–95',summary:'MoMA 馆藏把 Chapter One 明确记录为 silver dye bleach prints and text panels，而不是单张摄影。Sekula 在世界不同港口与港口城市持续拍摄，将船舶、码头劳动、工业空间、货物流通和城市边缘组织成摄影—文字叙事。作品针对1990年代解除管制与全球生产扩张，把通常在消费端不可见的海运基础设施重新放回图像中心。',actions:['跨多个港口和港口城市进行长期田野拍摄，而非围绕一次新闻事件工作。','同时观察劳动者、船舶、工业设施、城市住宅和货物流通，使不同尺度进入同一序列。','将照片与文字面板共同编排，拒绝让单张照片承担“客观证据”的全部权威。','通过章节与序列建立政治经济关系，使观看从具体人物/地点移动到全球生产和消费结构。'],sourceUrl:'https://www.moma.org/collection/works/164247',images:[],relations:[rel('收藏','Museum of Modern Art','Chapter One, Fish Story, 1988–95；silver dye bleach prints and text panels。'),rel('方法','摄影 + 文字','文字不是照片说明，而与摄影共同构成论证和叙事结构。')]},
      {title:'Testing robot-truck, Maasvlakte, Port of Rotterdam',cluster:'Fish Story / automation / container logistics',period:'September 1992',summary:'Sekula 在鹿特丹 Maasvlakte 的 ECT/Sea-Land cargo terminal 拍摄用于搬运集装箱的测试 robot-truck。把这张图与船员、码头工图像并置后，Fish Story 不只记录传统海港劳动，也捕捉物流自动化开始重组港口劳动的节点：全球化既扩大货物流动，也通过集装箱标准化与自动化改变谁在系统中工作、工作如何被看见。',actions:['进入大型港口基础设施现场，寻找货物流通背后的技术装置。','把自动化设备与人工劳动放进同一系列，而不是把技术作为独立的未来主义题材。','通过地点、企业/码头信息和序列关系，将单台设备连接到全球物流网络。'],sourceUrl:'https://www.moma.org/collection/works/164242',images:[],relations:[rel('地点','Port of Rotterdam / Maasvlakte','1992；ECT/Sea-Land automated cargo terminal。'),rel('主题','automation ↔ labor','使 Fish Story 同时成为劳动史和物流技术史。')]},
      {title:'“Pancake,” former shipyard sandblaster',cluster:'Fish Story / labor / deindustrialization',period:'November 1992',summary:'Terminal Island, Los Angeles harbor。画面中的 Pancake 曾是造船厂喷砂工，照片拍摄时正在 waterfront scrapyard 搜寻铜。这个具体人物节点把“全球资本”压回身体和职业轨迹：港口不是无人的集装箱景观，而是产业变化如何落到个人生计上的现场。',actions:['记录人物的职业身份和地点，使肖像进入劳动史语境。','避免把失业/边缘劳动仅处理成匿名贫困图像，而让过去的工业岗位与当前谋生方式形成时间关系。','将人物图像与港口机器、船舶和货物流通图像并置，使宏观经济与个体经验互相解释。'],sourceUrl:'https://www.moma.org/collection/works/164241',images:[],relations:[rel('地点','Los Angeles Harbor / Terminal Island','1992。'),rel('主题','deindustrialization ↔ informal survival','前造船工与废料场劳动把产业结构变化具体化。')]}
    ],
    exhibitions:['Fish Story — documenta 11 / international circulation','MoMA collection: Chapter One, Fish Story','MoMA Gallery 208: Institutional Critiques, 2026'],
    sources:[{label:'MoMA · Allan Sekula',url:'https://www.moma.org/artists/31040-allan-sekula'},{label:'MoMA · Chapter One, Fish Story',url:'https://www.moma.org/collection/works/164247'},{label:'MoMA · Rotterdam robot-truck',url:'https://www.moma.org/collection/works/164242'},{label:'MoMA · Pancake',url:'https://www.moma.org/collection/works/164241'}]
  },
  'latoya-ruby-frazier':{
    artistId:'latoya-ruby-frazier',
    projectCoverage:'作品级深化：把 The Notion of Family 从“家庭纪录”下钻为家庭成员共同生产的自我表述、身体/医疗与去工业化城市之间的结构关系，并补入 Whitney Biennial 2012 对纪录摄影政治的艺术家自述。',
    imageCoverage:'Whitney Museum 保存 The Notion of Family、Landscape of the Body (Epilepsy Test)、2012 Biennial 展示与艺术家访谈入口；作品受版权保护，记录官方页面而不复制文件。',
    note:'Frazier 的决定性转向是把传统社会纪录摄影中“摄影师去观察他人的贫困”翻转成由经历结构性衰退的人自己生产图像。她本人、母亲与祖母既是被摄者也是叙事主体，因此家庭相册、医疗身体、住宅和钢铁城市不是私人/公共两条线，而是同一历史的不同尺度。',
    projects:[
      {title:'The Notion of Family',cluster:'family archive / collaborative documentary / deindustrialization',period:'2002–',summary:'Frazier 从本科阶段开始长期拍摄自己、母亲、祖母与 Braddock。Whitney 指出 Braddock 曾依赖 Andrew Carnegie 的钢铁工业，1970年代以后工业衰退带来经济崩塌、贫困与跨代家庭变化。Frazier 借用 FSA 纪录摄影的黑白视觉传统，却把相机从“外部社会调查”转回自己的家庭和故乡，从内部讨论工业衰退、环境和身体。',actions:['长期返回同一家庭与城镇，而不是以短期新闻项目完成叙事。','让自己、母亲和祖母反复进入画面，使摄影者/被摄者的权力位置不断交换。','把家庭内部、医院、身体和 Braddock 工业景观并置，建立微观身体与宏观政策/产业史的联系。','采用克制的黑白纪录语言，同时反思纪录摄影由外部机构代表弱势群体的传统。'],sourceUrl:'https://whitney.org/artists/13636',images:[],relations:[rel('机构','Whitney Museum of American Art','馆藏/艺术家档案及 Whitney Biennial 2012。'),rel('地点','Braddock, Pennsylvania','家庭史与钢铁工业衰退的长期现场。'),rel('方法','FSA documentary tradition → self-representation','借用 Lange / Evans / Gordon Parks 等纪录传统，但将观看权转回亲历者。')]},
      {title:'Landscape of the Body (Epilepsy Test)',cluster:'The Notion of Family / body-landscape diptych',period:'2002–',summary:'Whitney 将该双联作品置于 The Notion of Family 的核心：母亲裸露的背部在医院检查环境中被导线包围。这里“身体”不是孤立的疾病肖像，而与 Braddock 的社会、经济和环境衰退共同阅读；家庭成员的健康经验成为去工业化历史进入肉身的尺度。',actions:['在真实医疗情境中拍摄家庭成员身体。','以双联/序列关系让身体图像与城市/工业环境互相解释。','避免把母亲处理为匿名病例，通过长期家庭关系保留主体的历史位置。'],sourceUrl:'https://whitney.org/artists/13636',images:[],relations:[rel('系列','The Notion of Family','Whitney 将其作为该长期系列的重要作品讨论。'),rel('主题','body ↔ industrial landscape','疾病、环境与产业衰退不被拆成彼此无关的题材。')]},
      {title:'Whitney Biennial 2012 — documentary politics',cluster:'institutional context / artist statement / documentary ethics',period:'2012',summary:'在 Whitney Biennial 2012 的访谈中，Frazier明确说自己长期尝试平衡 documentary photography 的“poetics and politics”。她回看大萧条时期 FSA 图像时追问：如果这些照片不是由政府宣传系统生产，而是由真正经历危机的人拍摄，会是什么样？这个问题直接解释了她为什么坚持从自身家庭内部工作。',actions:['把摄影实践与纪录摄影史放在同一批判框架中。','公开说明政府/机构委托与被摄群体自我表述之间的权力差异。','将个人创作方法定位为对纪录摄影代表权问题的长期回应。'],sourceUrl:'https://whitney.org/media/799',images:[],relations:[rel('展览','Whitney Biennial 2012','作品与艺术家访谈共同提供方法论语境。'),rel('历史参照','Farm Security Administration photography','Frazier借用其视觉传统，同时批判谁拥有代表危机的权力。')]}
    ],
    exhibitions:['Whitney Biennial 2012'],
    sources:[{label:'Whitney · LaToya Ruby Frazier',url:'https://whitney.org/artists/13636'},{label:'Whitney Biennial 2012 · artist interview',url:'https://whitney.org/media/799'},{label:'Whitney Biennial 2012 · artist page',url:'https://whitney.org/exhibitions/2012-biennial/latoya-ruby-frazier'}]
  },
  'an-my-le':{
    artistId:'an-my-le',
    projectCoverage:'作品级深化：从早期返回越南、29 Palms 到 The Silent General，补齐“战争现场之外”这一核心方法如何从个人流散记忆扩展到军事训练、历史重演、电影片场、纪念碑与当下政治。',
    imageCoverage:'MoMA 与 Whitney 均提供具体作品、展览及音频访谈页面；作品受 An-My Lê 版权保护，故只保存官方入口与作品信息。',
    note:'Lê 与传统战地摄影的关键差异在于她经常不拍真实交火，而拍战争如何被预演、重演、拍成电影、写进纪念碑和地景。大画幅相机的冷静距离使“战争”从事件变成一种被制度和文化持续制造的空间。',
    projects:[
      {title:'29 Palms: Infantry Platoon (Machine Gunners)',cluster:'29 Palms / military rehearsal / landscape',period:'2003–04',summary:'Lê 在加州 Twentynine Palms 的 Marines 训练场拍摄准备部署到 Afghanistan/Iraq 的军事演习。MoMA 指出沙漠被用来模拟 Middle Eastern terrain；她以大画幅黑白摄影保持距离，使训练的表演性与“真正战斗的排练”显现。景观因此不是背景，而成为美国军事力量如何在本土预演海外战争的舞台。',actions:['进入军事训练场，而不是追随部队到真实交火现场。','使用大画幅相机制作高细节、远距离的黑白图像。','把士兵缩入更大的地景结构，让地形、军事部署和人的尺度共同工作。','通过“演习/排练”研究战争在发生前如何被制度化生产。'],sourceUrl:'https://www.moma.org/collection/works/94793',images:[],relations:[rel('收藏','Museum of Modern Art','29 Palms: Infantry Platoon (Machine Gunners), 2003–04。'),rel('地点','Marine Corps Air Ground Combat Center, Twentynine Palms','加州沙漠被用于模拟中东地形。'),rel('历史参照','American Civil War photography','MoMA 将其冷静大画幅地景与 Mathew Brady / Alexander Gardner 的战争景观传统联系。')]},
      {title:'29 Palms: Mortar Impact',cluster:'29 Palms / impact trace / landscape as stage',period:'2003–04',summary:'同系列作品把注意力从士兵转向训练在地表留下的爆炸/撞击痕迹。与 Machine Gunners 并读时可以看到 Lê 如何在“行动中的军人”和“承受行动的地景”之间切换：战争训练不只是一种表演，也实际改写本土地貌。',actions:['在同一训练体系内同时拍摄人员行动和地景痕迹。','维持系列一致的大画幅黑白语言，使不同对象可以被比较。','让爆炸结果留在广阔地景尺度中，避免依靠近距离冲击图像制造戏剧性。'],sourceUrl:'https://www.moma.org/collection/works/94794',images:[],relations:[rel('收藏','Museum of Modern Art','Gelatin silver print, 67.3 × 96.7 cm。'),rel('系列','29 Palms','与 Infantry Platoon 等作品共同构成战争预演的地景研究。')]},
      {title:'The Silent General — film set / monuments / present politics',cluster:'The Silent General / history loop / monuments',period:'2015–17',summary:'系列起点之一是 Lê 在电影 Free State of Jones 的 Civil War 战斗片场拍摄。随后 Charleston massacre 之后美国南方 Confederate monuments 的拆除争议使她继续拍摄新奥尔良纪念碑，并在2016美国大选期间返回。她在 Whitney 访谈中把片场、纪念碑和当下政治理解为互相连接的时间层：历史并没有留在过去，而通过娱乐工业、公共雕塑和政治争论不断返回现在。',actions:['从历史电影片场进入“历史如何被当代重新表演”的问题。','在 Confederate monuments 争议发生时持续返回 New Orleans 拍摄。','把电影片场、纪念碑与选举时期现实并列，而不是按事件类别分开。','通过序列制造 past / present / future 的循环关系，研究历史如何在当下重新获得政治效力。'],sourceUrl:'https://whitney.org/collection/works/56099',images:[],relations:[rel('展览','Whitney Biennial 2017','The Silent General 相关作品进入 Biennial。'),rel('地点','New Orleans, Louisiana','电影片场、Confederate monuments 与2016 election构成连续现场。'),rel('机构','MoMA · Between Two Rivers','2023–24大型调查展把其战争、流散与地景实践放入长期脉络。')]}
    ],
    awards:['John Simon Guggenheim Memorial Foundation Fellowship 1997','MacArthur Fellow 2012','National Science Foundation Antarctic Artists and Writers Program Award 2007'],
    exhibitions:['Whitney Biennial 2017','An-My Lê: Between Two Rivers — MoMA, 2023–24'],
    sources:[{label:'MoMA · An-My Lê',url:'https://www.moma.org/artists/7901-an-my-le'},{label:'MoMA · 29 Palms: Infantry Platoon',url:'https://www.moma.org/collection/works/94793'},{label:'MoMA · 29 Palms: Mortar Impact',url:'https://www.moma.org/collection/works/94794'},{label:'Whitney · The Silent General / Free State of Jones',url:'https://whitney.org/collection/works/56099'},{label:'Whitney · An-My Lê',url:'https://whitney.org/artists/9860'}]
  }
};