import type { ArtistArchive, ArchiveProject, ArchiveRelation } from './archiveData';
const rel=(kind:ArchiveRelation['kind'],label:string,detail?:string):ArchiveRelation=>({kind,label,detail});
const project=(p:ArchiveProject)=>p;
export const archiveBatch300:Record<string,ArtistArchive>={
  'trevor-paglen':{
    artistId:'trevor-paglen',
    projectCoverage:'深化 Trevor Paglen：Autonomy Cube、Sight Machine、They Took the Faces from the Accused and the Dead…、Orbital Reflector，以及 Sites Unseen 中期回顾展。重点补“研究—基础设施—图像—可运行系统”的方法链，而非只把他归为监控摄影。',
    imageCoverage:'优先记录 Trevor Paglen Studio、Smithsonian American Art Museum、Barbican、Nevada Museum of Art、Carnegie Museum of Art 的官方作品/展览页面。作品图像版权未确认自由再发布时不复制入仓库。',
    note:'Paglen 的关键不是单纯拍摄秘密基地，而是逐步把摄影从“揭露不可见对象”推进到“进入并重组不可见基础设施”：Tor 网络、机器视觉、训练数据、卫星与航天监管本身都成为作品材料。作品因此常同时具有图像、研究项目、软件/网络节点、表演或工程系统的身份。',
    projects:[
      project({title:'Autonomy Cube',cluster:'network infrastructure / sculpture / Tor / surveillance',period:'2015–',summary:'Autonomy Cube 是一件必须被使用才完整的网络雕塑。透明 Plexiglas 立方体内部装有联网计算机，在博物馆或公共空间建立名为 Autonomy Cube 的开放 Wi-Fi；访问者流量不是直接进入普通互联网，而是经由 Tor 网络路由。与此同时，装置自身成为 Tor relay，为世界其他 Tor 用户转发流量。因此博物馆不只是展示一个“关于隐私”的物体，而实际成为匿名通信基础设施中的一个节点。',actions:['制作透明 Plexiglas 立方体，将计算机与网络硬件作为可见结构而非隐藏后台。','在展览现场建立开放 Wi-Fi，使观众可直接连接作品。','把连接流量路由进 Tor 网络，改变观众实际的数据路径。','让装置本身运行 Tor relay，使作品同时服务于展场之外的匿名网络。'],sourceUrl:'https://paglen.studio/2020/04/09/autonomy-cube/',images:[],relations:[rel('技术网络','Tor network','作品既使用 Tor，也作为 relay 参与其全球志愿节点网络。'),rel('媒介','Plexiglas cube + computer components','艺术家官方资料：19 5/8 × 19 5/8 × 19 5/8 in；作品被设计为同时“seen”与“used”。')]}),
      project({title:'Sight Machine',cluster:'machine vision / live performance / AI / music',period:'2017–2019+',summary:'Sight Machine 与 Kronos Quartet 合作，把通常只在机器之间流通的 computer-vision 图像公开给现场观众。演奏过程中，摄像机持续拍摄乐手，影像进入一组从消费级人脸检测到高级监控/军事视觉的算法；算法产生的检测、分类与抽象结果被实时投影在乐手身后。作品让同一个现场同时存在两种观看：观众感受音乐、身体与情绪，机器则把这些复杂经验压缩成标签、概率和可操作数据。',actions:['让 Kronos Quartet 的现场演奏成为机器视觉的实时输入，而非使用预先准备好的测试图片。','摄像机把演奏者连续送入多套 computer-vision algorithms。','将机器生成的识别、分类与抽象图像实时投影，使原本不可见的 machine-to-machine image 可被人观看。','在不同演出版本持续调整软件与视觉流程，使作品不是固定录像，而是运行中的系统。'],sourceUrl:'https://paglen.studio/2019/07/01/sight-machine/',images:[],relations:[rel('合作','Kronos Quartet','2017 首演于 San Francisco Pier 70；之后在 Holland Festival 2018、Smithsonian American Art Museum 2018、Barbican 2019 演出。'),rel('机构','Cantor Arts Center, Stanford University','艺术家资料记载项目最初由 Cantor Arts Center / Allison Gass 资助。'),rel('展演','Barbican Hall — 11 Jul 2019','Barbican 明确记录摄像机、AI algorithms 与实时投影结构。')]}),
      project({title:'They Took the Faces from the Accused and the Dead…',cluster:'training images / facial recognition / dataset archaeology',period:'2019–2020',summary:'该系列追查人脸识别训练史中的图像来源，而不是重新拍摄被监控者。Paglen 指出，社交媒体出现前，研究者需要大量面孔测试早期 facial-recognition algorithms，其中一类重要来源是被告、囚犯等 mugshots；美国 National Institute of Standards 向研究者提供这类图像。Paglen 将训练系统中的面孔重新转成大型 pigment/inkjet prints，使原本作为算法原料、通常不面向公众观看的图像重新获得物质尺度和政治可见性。',actions:['研究早期 facial-recognition benchmark / training image 的制度来源。','从机器视觉数据体系中提取原本作为计算输入的面孔。','把低可见度的数据图像转成独立的大型打印作品或训练图像墙。','通过标题重新指出训练数据背后的具体身体与司法权力，而不是只讨论抽象的“AI偏见”。'],sourceUrl:'https://paglen.studio/2020/04/09/they-took-the-faces-from-the-accused-and-the-dead/',images:[],relations:[rel('机构','National Institute of Standards / NIST','艺术家官方说明将其指认为早期人脸识别研究中囚犯/被告面孔图像的重要供应体系。'),rel('展览','Uncanny Valley: Being Human in the Age of AI — de Young Museum — 2020','大型 training-images wall 被纳入该展。'),rel('展览','Opposing Geometries — Carnegie Museum of Art — 2020–21','Carnegie 展览资料展示该系列 2019 图像。')]}),
      project({title:'Orbital Reflector',cluster:'space infrastructure / nonfunctional satellite / unrealized deployment',period:'2013–2019; launch 2018',summary:'Orbital Reflector 是与 Nevada Museum of Art 长期研发的“nonfunctional satellite”雕塑：计划将可充气反射结构送入近地轨道，展开后像夜空中的亮星一样被肉眼看到，其目的不是通信、侦察或科学测量，而是把卫星这一通常功能化、军事化和商业化的基础设施暂时改写为公共视觉对象。2018年12月卫星随火箭成功进入轨道，但美国联邦政府停摆延误部署，之后团队失去通信能力，反射结构最终没有展开；博物馆因此把它记录为未实现的轨道雕塑。失败本身反而暴露作品对监管、通信、航天工程和国家行政系统的真实依赖。',actions:['与 Nevada Museum of Art、工程团队长期研发可进入轨道的非功能性艺术卫星。','把大型反射结构折叠进小型卫星并随商业火箭进入轨道。','设计展开后依靠反射太阳光而被地面肉眼观看，不承担通信或观测任务。','部署因政府停摆和后续通信失效未完成；保留工程档案与失败过程作为项目历史。'],sourceUrl:'https://www.nevadaart.org/finding-aids/trevor-paglen-orbital-reflector/',images:[],relations:[rel('合作机构','Nevada Museum of Art — Center for Art + Environment','馆方保存 2013–2019 Orbital Reflector 项目档案，4.5 cubic feet。'),rel('状态','Launched 3 Dec 2018; reflector not deployed','卫星进入轨道，但计划中的可见反射雕塑最终未展开。'),rel('制度关系','US federal government shutdown 2018–19','部署所需监管/通信流程受到政府停摆影响，使行政基础设施直接进入作品命运。')]}),
      project({title:'Trevor Paglen: Sites Unseen',cluster:'survey exhibition / institutional synthesis / early photography to AI',period:'2018–2019',summary:'Smithsonian American Art Museum 的 Sites Unseen 是把 Paglen 方法演变放到同一空间的重要中期回顾展：超过100件作品把早期秘密军事/监控地点摄影，与 The Last Pictures、非功能卫星原型和人工智能作品并置，并首展录像 Image Operations。这个策展结构清楚显示他的实践不是从“摄影”突然转去“AI”，而是持续追踪视觉、国家秘密、基础设施和机器观看，只是研究对象从远距离可见的设施逐渐进入数据与算法层。',actions:['将早期 photographic series 与后期雕塑、卫星、AI 项目并置，形成方法演变而非媒介分区。','通过超过100件作品建立“地理秘密设施→轨道基础设施→机器视觉”的连续研究路径。','以 The Last Pictures、non-functional satellite prototypes 与 Image Operations 等项目显示摄影如何扩展为工程、档案和计算系统。'],sourceUrl:'https://americanart.si.edu/press/2018/11/trevor-paglen-sites-unseen-opens-june-21-smithsonian-american-art-museum',images:[],relations:[rel('展览','Smithsonian American Art Museum — 21 Jun 2018–6 Jan 2019','馆方称其为首次把早期摄影系列与近期雕塑及 AI 新作并置的展览；超过100件作品。'),rel('巡展','Museum of Contemporary Art San Diego — 21 Feb–2 Jun 2019','Sites Unseen 后续巡展节点。')]}),
    ],
    awards:[],
    exhibitions:['Trevor Paglen: Sites Unseen — Smithsonian American Art Museum — 2018–19','Trevor Paglen: Opposing Geometries — Carnegie Museum of Art — 2020–21','From Apple to Anomaly — Barbican Centre — 2019–20'],
    sources:[{label:'Trevor Paglen Studio — Autonomy Cube',url:'https://paglen.studio/2020/04/09/autonomy-cube/'},{label:'Trevor Paglen Studio — Sight Machine',url:'https://paglen.studio/2019/07/01/sight-machine/'},{label:'Barbican — Sight Machine',url:'https://www.barbican.org.uk/kronos-quartet-trevor-paglen-sight-machine'},{label:'Trevor Paglen Studio — They Took the Faces from the Accused and the Dead…',url:'https://paglen.studio/2020/04/09/they-took-the-faces-from-the-accused-and-the-dead/'},{label:'Carnegie Museum of Art — Opposing Geometries',url:'https://carnegieart.org/exhibition/trevor-paglen/'},{label:'Nevada Museum of Art — Orbital Reflector archive',url:'https://www.nevadaart.org/finding-aids/trevor-paglen-orbital-reflector/'},{label:'Smithsonian American Art Museum — Sites Unseen',url:'https://americanart.si.edu/press/2018/11/trevor-paglen-sites-unseen-opens-june-21-smithsonian-american-art-museum'}]
  }
};
