import type { ArtistArchive, ArchiveProject, ArchiveRelation } from './archiveData';
const rel=(kind:ArchiveRelation['kind'],label:string,detail?:string):ArchiveRelation=>({kind,label,detail});
const project=(p:ArchiveProject)=>p;

export const archiveBatch310:Record<string,ArtistArchive>={
 'wolfgang-tillmans':{
  artistId:'wolfgang-tillmans',
  projectCoverage:'作品级继续深化 Wolfgang Tillmans：Freischwimmer、Silver / paper-drop 方法、astronomy / Transit of Venus、Moon in Earthlight，以及 Tate Modern Edition 的 photocopier 工作流。重点补齐无相机摄影、化学过程、天文观察、录像时长与复印机抽象的具体制作动作。',
  imageCoverage:'MoMA 与 Tate 官方页面提供作品图、展览图和研究说明；作品版权仍属 Wolfgang Tillmans，本站保存官方研究入口，不复制未确认自由再发布的图像。',
  note:'本批把 Tillmans 从“青年文化/亲密生活摄影师”的常见标签继续推向材料实验与观看机制：相机可以被拿掉，显影液污染可以成为图像发生器，望远镜可以把天文学并入摄影，复印机可以成为抽象工具，视频则把缓慢天体观看变成持续时间经验。与单纯后期制造抽象效果不同，他持续让纸张、化学、光、镜头、望远镜、打印与展墙本身承担图像意义。',
  projects:[
   project({title:'Freischwimmer — including Freischwimmer 199',cluster:'camera-less photography / photogram / chemistry / abstraction',period:'2000s–2012',summary:'Freischwimmer 把摄影推进到不需要相机的状态。MoMA 将 Freischwimmer 199（2012）登记为 chromogenic print，224.2 × 181 cm，并归入 photogram 传统；MoMA 2022 展览研究材料进一步说明，Tillmans 让感光相纸在暗房中直接受光，并利用未彻底清洁的显影液造成不可完全预测的化学反应，污迹、银盐与液体痕迹因此成为图像生成的一部分。最终的大幅作品看似数字绘图或烟雾/线条，实际上来自光、相纸与化学过程的直接接触。',actions:['取消相机与外部被摄对象，让感光纸本身成为工作现场。','在暗房中直接控制光对相纸的曝光。','保留显影液中的残留物和化学不稳定性，让污迹、银盐与液体运动参与成像。','把暗房中难以预判的小尺度过程制作成大型 chromogenic print，使材料痕迹变成空间性的抽象图像。'],sourceUrl:'https://www.moma.org/collection/works/164471',images:[],relations:[rel('收藏','Museum of Modern Art — Freischwimmer 199','2012；chromogenic print；224.2 × 181 cm；Gift of the artist。'),rel('展览','Wolfgang Tillmans: To look without fear — MoMA','2022-09-12–2023-01-01；回顾展将无相机抽象与肖像、夜生活、政治、天文和装置并置。')]}),
   project({title:'Silver / paper drops — darkroom material as subject',cluster:'darkroom process / photographic paper / chemistry / objecthood',period:'1990s–',summary:'Tillmans 的 Silver 与 paper-drop 工作把“摄影纸只是承载照片的平面”这一前提拆开。MoMA 为 To look without fear 制作的研究指南把 Silver、paper drops 与 Freischwimmer 放在同一材料实验脉络：图像由相纸、显影过程、银盐、折曲和表面状态产生，而不是先存在一个外部场景再被记录。这里摄影越来越接近对象：纸张会弯曲、悬挂、卷曲，化学痕迹不是需要清除的技术错误，而是作品本身。',actions:['把暗房化学过程从透明技术步骤提升为可见主题。','允许银盐、污迹与处理过程直接留下表面痕迹。','利用相纸折曲、悬挂或卷起后的物理状态改变观看方式。','在展墙上把具象照片、抽象暗房作品与纸张对象并置，使“照片是什么”成为安装层面的提问。'],sourceUrl:'https://www.moma.org/momaorg/shared/pdfs/docs/visitor-guide-wolfgang-tillmans-to-look-without-fear.pdf',images:[],relations:[rel('研究资料','MoMA visitor guide — To look without fear','官方指南专门解释 Silver、paper drops、Freischwimmer 与 astronomy 的制作方法。'),rel('方法关系','image → photographic object','摄影不再只是图像内容；纸张、表面、化学和悬挂方式共同构成作品。')]}),
   project({title:'Astronomy / Transit of Venus',cluster:'astronomy / telescope / limits of visibility',period:'1978–2012',summary:'天文学不是 Tillmans 偶尔使用的题材，而是一条从童年延续到成熟实践的观看训练。MoMA 研究指南记录他1978年约10岁时开始迷恋星空，用望远镜观察并画太阳黑子，有时把相机贴到望远镜目镜上摄影；2004和2012年，他再次使用同一台望远镜观察金星凌日，在数小时中拍摄金星黑色圆盘穿越太阳表面的过程。这个方法把摄影最基本的边界问题具体化：什么可以被肉眼看到，什么必须借助光学设备，仪器如何改变我们对尺度和时间的感觉。',actions:['从长期个人天文观察出发，而不是把宇宙图像当作现成视觉素材。','使用望远镜扩展肉眼可见范围，并把相机与望远镜光学系统连接。','在金星凌日持续数小时的过程中连续观察/摄影，而不是只寻找单个决定性瞬间。','把天体运动与摄影的曝光、序列和可见性问题连接起来。'],sourceUrl:'https://www.moma.org/momaorg/shared/pdfs/docs/visitor-guide-wolfgang-tillmans-to-look-without-fear.pdf',images:[],relations:[rel('展览','Wolfgang Tillmans: To look without fear — MoMA','展览把 astronomy 独立作为理解其“boundaries of the visible”研究的重要入口。'),rel('方法关系','telescope + camera','光学仪器不是中性工具，而是决定何种现实能够进入图像的观看装置。')]}),
   project({title:'Moon in Earthlight',cluster:'astronomy / moving image / duration / sound',period:'2021',summary:'Moon in Earthlight 把 Tillmans 的天文观看从静态摄影推进到持续时间。MoMA 馆藏记录作品为 high-definition video（color, sound），时长56分58秒。近一小时的时长意味着月球不再只是一个可迅速识别的符号或漂亮天文照片，而成为需要等待和持续注意的视觉事件；它也把艺术家长期的天文观察、摄影与音乐/声音实践接到同一件作品里。',actions:['以高清动态图像而非单幅照片处理月球观察。','保留56分58秒的持续时间，让观看者必须经历时间而非快速浏览。','使用彩色影像与声音共同构成作品，使天文图像进入空间化、时间化的展览经验。'],sourceUrl:'https://www.moma.org/collection/works/431169',images:[],relations:[rel('收藏','Museum of Modern Art — Moon in Earthlight','2021；HD video, color, sound；56:58 min；object no. 766.2022。'),rel('方法关系','astronomical photograph → durational moving image','从记录天体形态推进到让观看本身成为近一小时的时间经验。')]}),
   project({title:'Tate Modern Edition',cluster:'photocopier / construction site / abstraction / unique edition',period:'2016',summary:'2016年为支持 Tate Modern 新馆而制作的 Tate Modern Edition 展示了 Tillmans 如何把纪录摄影继续转译为机器抽象。Tate 记录他在新馆施工期间拍摄建筑现场、机械、人物与细节，随后回到工作室使用传统 photocopier 对这些照片进行选择、分离和扭曲。最终不是统一复制的版画，而是172件各不相同、由艺术家签名编号的 unique works。这里“摄影 → 复印”不是低成本复制，而是一套二次观看和形态变换程序。',actions:['在 Tate Modern 扩建施工现场拍摄地点、机械、人物与细节。','把已有摄影带回工作室，而不是直接把现场照片作为终点。','使用传统 photocopier 进行选择、分离与 distortion，让复制机器成为图像加工设备。','形成172件彼此不同的 unique works，并逐件签名编号。'],sourceUrl:'https://shop.tate.org.uk/wolfgang-tillmans-tate-modern-edition-2016/ed1000.html',images:[],relations:[rel('机构','Tate Modern — London','作品为支持 Tate Modern 新馆而制作，原始摄影也来自建设现场。'),rel('制作','traditional photocopier','Tate 明确记录 selection, separation and distortion 的复印机工作流。'),rel('版本','172 unique works','不是同图像的172份复制，而是172件独一作品。')]})
  ],
  awards:['Turner Prize — 2000 — first photographer to win the prize'],
  exhibitions:['Wolfgang Tillmans: To look without fear — Museum of Modern Art, New York — 2022-09-12–2023-01-01','Wolfgang Tillmans — Tate Modern — London — 2017'],
  sources:[{label:'MoMA — Wolfgang Tillmans artist profile',url:'https://www.moma.org/artists/8044-wolfgang-tillmans'},{label:'MoMA — To look without fear',url:'https://www.moma.org/calendar/exhibitions/5440'},{label:'MoMA — Freischwimmer 199',url:'https://www.moma.org/collection/works/164471'},{label:'MoMA — Moon in Earthlight',url:'https://www.moma.org/collection/works/431169'},{label:'MoMA — To look without fear visitor guide',url:'https://www.moma.org/momaorg/shared/pdfs/docs/visitor-guide-wolfgang-tillmans-to-look-without-fear.pdf'},{label:'Tate — Tate Modern Edition 2016',url:'https://shop.tate.org.uk/wolfgang-tillmans-tate-modern-edition-2016/ed1000.html'}]
 }
};