import type { ArtistArchive, ArchiveRelation } from './archiveData';
const rel=(kind:ArchiveRelation['kind'],label:string,detail?:string):ArchiveRelation=>({kind,label,detail});

export const archiveBatch149: Record<string, ArtistArchive> = {
'venice-lawrence-abu-hamdan': {
 artistId:'venice-lawrence-abu-hamdan', projectCoverage:'5 个 accent-politics / forensic acoustics / earwitness / architecture / live-audio-essay 节点深化 · 2012–2021', imageCoverage:'0 / 5',
 note:'把 Abu Hamdan 从笼统的 forensic listening 标签拆成方法演化：先研究 accent test 如何把声音变成边境治理工具；随后亲自参与枪声取证，把 acoustic analysis 转成反思证据制度的电影；Saydnaya 又从可测量声谱转向幸存者记忆中的 earwitness testimony；Walled Unwalled 把 hearing 与 architecture / law 连接；Air Pressure 最后把空域中的不可见暴力组织成 live audiovisual essay。核心不是“声音艺术”，而是研究谁有权把听见的东西宣布为 evidence。',
 projects:[
 {title:'The Freedom of Speech Itself / Conflicted Phonemes',cluster:'accent analysis / asylum border / voice cartography',period:'2012–2013',summary:'早期实践研究 asylum procedure 中的 language / accent analysis：国家把口音当作可定位 origin 的生物政治证据。作品把 voice 从身份表达转成边境技术，并反过来暴露这种听觉分类的不稳定。',actions:['收集并分析 language-analysis procedures','把 accent judgement 映射为可视/可听结构','比较个人语言史与国家假定的 geographic origin','将 speech 本身作为 border technology 研究'],sourceUrl:'https://lawrenceabuhamdan.com/',images:[],relations:[]},
 {title:'Rubber Coated Steel',cluster:'gunshot analysis / tribunal / spectrogram / strategic silence',period:'2016',summary:'作品源自对 2014 年约旦河西岸两名巴勒斯坦少年被枪杀事件的声学调查。影片设置为 firing-range tribunal，却刻意不播放核心枪声，只留下 spectrogram 与字幕，使“声音证据”同时成为关于司法可听性、压制和发言权的作品。',actions:['比较 live ammunition 与 rubber bullet 的 acoustic signature','把 forensic spectrogram 转成影像叙事材料','重构 tribunal / firing-range 空间','刻意移除枪声，使 silence 成为证据政治的一部分'],sourceUrl:'https://lawrenceabuhamdan.com/video-vault',images:[],relations:[rel('奖项','Tiger Short Film Award — International Film Festival Rotterdam','2017'),rel('奖项','Nam June Paik Award for New Media / Earshot context','2016')]},
 {title:'Saydnaya / Earwitness Inventory',cluster:'earwitness testimony / acoustic memory / prison reconstruction',period:'2016–2019',summary:'与 Saydnaya 军事监狱幸存者工作时，视觉证词因长期蒙眼和隔离而失效，听觉记忆反而成为重建空间、暴力和距离的重要入口。实践由“分析录音”转向帮助证人描述、比较和再生成曾经听见却缺少语言的声音。',actions:['采访 former detainees 的 auditory memories','用物件、频率、响度与空间回响帮助 witnesses 校准记忆','从声音推断 architecture / distance / event','建立 earwitness vocabulary，而不把记忆伪装成无误差测量'],sourceUrl:'https://lawrenceabuhamdan.com/',images:[],relations:[]},
 {title:'Walled Unwalled',cluster:'architecture / legal evidence / surveillance / monologue',period:'2018',summary:'20 分钟单频道作品在东柏林 Funkhaus 录制，把 Kyllo v. United States、Oscar Pistorius 案与 Saydnaya 幸存者叙述并置，研究墙体何时从隐私边界变成可被技术、人耳和法院穿透的信息介质。',actions:['把三个法律/政治案例写成连续 monologue','利用 Funkhaus 的玻璃与广播史制造 architecture-as-argument','比较 thermal surveillance、人耳与墙体传播','把 performance、sound research 与 legal narrative 压入同一镜头结构'],sourceUrl:'https://lawrenceabuhamdan.com/video-vault',images:[],relations:[rel('收藏','Museum of Modern Art, New York','2019 acquisition'),rel('展览','Lawrence Abu Hamdan: Walled Unwalled and Other Monologues — MoMA','2023')]},
 {title:'Air Pressure',cluster:'airspace / sonic archive / live audiovisual essay',period:'2021',summary:'方法进一步从封闭建筑转向空域：把 aircraft / drone 等难以稳定看见、却持续被居民听见的事件组织成声音档案与现场 essay，使 geopolitical airspace 通过 listening 获得可感知结构。',actions:['积累并编排 airspace-related recordings / testimony','把不可见 aircraft presence 转成 auditory timeline','以 live narration 连接 investigation 与艺术展示','让 listening 成为读取 territorial power 的方法'],sourceUrl:'https://lawrenceabuhamdan.com/',images:[],relations:[]}
 ],awards:['Nam June Paik Award — 2016','Tiger Short Film Award, IFFR — 2017','Turner Prize — 2019 · jointly awarded with Helen Cammock, Oscar Murillo and Tai Shani'],exhibitions:['Venice Biennale — 2019','MoMA — Walled Unwalled and Other Monologues, 2023'],sources:[{label:'Lawrence Abu Hamdan · official works archive',url:'https://lawrenceabuhamdan.com/'},{label:'La Biennale · Lawrence Abu Hamdan 2019',url:'https://www.labiennale.org/en/art/2019/partecipants/lawrence-abu-hamdan'}]
},
'venice-korakrit-arunanondchai': {
 artistId:'venice-korakrit-arunanondchai',projectCoverage:'5 个 autobiography / denim-painting / fictional artist / post-natural ecology / ghost-politics 节点深化 · 2012–2021',imageCoverage:'0 / 5',note:'把 Korakrit 的实践从“沉浸式泰国影像”改写为持续更新的 world-building system：family footage、Buddhist calendar、Thai television、denim、performance、animism、political protest 与 digital effects 不是题材拼贴，而是通过 recurring characters / collaborators / materials 形成跨作品记忆。2019 后 ghost 逐渐取代 fictional denim painter，成为连接个人丧失、被压抑政治史与非线性时间的媒介。',projects:[
 {title:'2012–2555',cluster:'autobiography / Buddhist calendar / family archive / practice reset',period:'2012',summary:'MoMA PS1 将其描述为 video-installation trilogy 的第一部：艺术家回看 2008–2011 的创作，同时记录祖父母把家庭花园改造成养老居所。公历/佛历双年份把个人职业阶段与循环时间并置。',actions:['重新剪辑个人旧作与生活影像','持续拍摄 grandparents / family garden','用 Buddhist calendar 双重标记时间','把 exhibition 当作旧实践死亡与新 persona 出现的转折'],sourceUrl:'https://www.moma.org/calendar/exhibitions/3707',images:[],relations:[rel('展览','MoMA PS1 — Korakrit Arunanondchai','2014 · first solo museum exhibition')]},
 {title:'Untitled (History Painting) / denim painter',cluster:'denim / Western painting / Thai youth culture / global commerce',period:'2013–2014',summary:'烧灼、漂白、绘画和表演处理 denim；材料同时指向全球消费、美国文化输入与艺术家自我塑造的“denim painter”角色。绘画不再是 video 的附属物，而是从 performance / television / commerce 中留下的物质残迹。',actions:['以 denim 替代传统 canvas','通过 fire / bleach / paint / body action 改写表面','把 Thai youth 与 Western modern-art imagery 并置','让 video、painting 与 performance 相互生成'],sourceUrl:'https://www.moma.org/calendar/exhibitions/3707',images:[],relations:[]},
 {title:'Painting with history in a room filled with people with funny names',cluster:'recurring fictional painter / family / belief / technology',period:'2013–ongoing',summary:'长期系列建立 recurring fictional Thai painter，并不断吸收 family、superstition、spirituality、politics 与 technology。作品因此更接近连续更新的 universe，而不是互不相干的单件录像。',actions:['维持 recurring artist-persona 与人物关系','让新 episode 回收此前 footage / motif','混合 documentary、fiction、performance 与 digital effects','把 gallery 扩成 video + painting + sculpture 的 social environment'],sourceUrl:'https://www.labiennale.org/en/art/2019/partecipants/korakrit-arunanondchai',images:[],relations:[]},
 {title:'Post-natural forest — Venice 2019',cluster:'Anthropocene habitat / three-screen environment / collaboration',period:'2019',summary:'Central Pavilion 的 post-natural tree-like forms 与 Arsenale 三屏影像把系列世界扩成生态 habitat；Alex Gvojic 等长期协作者使作者身份也呈网络化。',actions:['将 gallery 转成 uncanny forest','制作 tree-like sculptural forms','使用 three-screen moving image','把 ecological survival 与 spirituality / political history 并置'],sourceUrl:'https://www.labiennale.org/en/art/2019/partecipants/korakrit-arunanondchai',images:[],relations:[rel('展览','58th Venice Biennale — May You Live In Interesting Times','2019')]},
 {title:'Songs for dying',cluster:'ghost / suppressed history / grief / protest / animist knowledge',period:'2021',summary:'ghost 成为被压抑历史和非线性时间的结构：个人亲密经验、spirit medium、泰国政治抗议、animist belief 与 global narrative 同时出现。作品把“幽灵”处理为 alternative knowledge system，而非恐怖图像。',actions:['用 ghost 打断 linear historical time','连接 personal loss 与 public trauma','把 spirit-medium / animist knowledge 纳入 political montage','通过 film、installation、painting 共同建立 mourning environment'],sourceUrl:'https://kunsthalltrondheim.no/en/utstillinger/songs-for-dying',images:[],relations:[rel('展览','Kunsthall Trondheim — Songs for dying','2021 · world premiere'),rel('展览','13th Gwangju Biennale','2021 · co-commission'),rel('策展','Katrine Elise Agpalza Pedersen','Kunsthall Trondheim presentation')]}
 ],awards:[],exhibitions:['MoMA PS1 — 2014','Venice Biennale — 2019','Kunsthall Trondheim — 2021','13th Gwangju Biennale — 2021'],sources:[{label:'MoMA PS1 · Korakrit Arunanondchai 2014',url:'https://www.moma.org/calendar/exhibitions/3707'},{label:'La Biennale · Korakrit Arunanondchai 2019',url:'https://www.labiennale.org/en/art/2019/partecipants/korakrit-arunanondchai'},{label:'Kunsthall Trondheim · Songs for dying',url:'https://kunsthalltrondheim.no/en/utstillinger/songs-for-dying'}]
},
'venice-ovartaci': {
 artistId:'venice-ovartaci',projectCoverage:'5 个 institutional-life / creature cosmology / doll-body / gender-self-fashioning / escape-machine 节点深化 · 1929–1985',imageCoverage:'0 / 5',note:'不把 Ovartaci 简化成 psychiatric outsider biography。56 年住院当然是作品条件，但持续生产更接近一个完整 cosmology：动物—人类 creature、past-life narrative、dolls、costume、gender self-fashioning 与 helicopter plans 都在制造可替代现实身体和制度空间的世界。Museum Ovartaci 当前也将其定位为丹麦 Art Brut 研究核心，并同时保存 Risskov psychiatric history。',projects:[
 {title:'Risskov working-life / self-naming Ovartaci',cluster:'institution / self-authorship / art as lived system',period:'1929–1985',summary:'1929 起长期居住于 Risskov psychiatric hospital，并在其中持续工作。自取 Ovartaci 之名本身就是对 hospital hierarchy 的语言改写；艺术生产与居住、身份和制度日常无法分开。',actions:['在 institutional setting 中持续建立个人工作体系','以 self-naming 改写 patient identity','把绘画、物件、服装、模型组织为连续生活世界','在有限空间中维持数十年创作连续性'],sourceUrl:'https://www.ovartaci.dk/ovartaci',images:[],relations:[rel('收藏','Museum Ovartaci, Aarhus','collection centred on Ovartaci and psychiatric-history archive')]},
 {title:'Animal-human creature cosmology',cluster:'past lives / mythology / elongated figures / alternative ontology',period:'1930s–1980s',summary:'细长、动物化人物反复进入 Ancient Egypt、pagan circus 等场景，并与 reincarnation / past-life narratives 联系。它们不是零散幻想画，而是数十年持续出现的 alternative ontology。',actions:['发展稳定 elongated creature morphology','混合 human / animal anatomy','将 religion、myth 与 autobiographical past lives 连接','跨 decades 重复并修改同一 cosmology'],sourceUrl:'https://www.labiennale.org/en/art/2022/milk-dreams/ovartaci',images:[],relations:[rel('展览','The Milk of Dreams — 59th Venice Biennale','2022 · Central Pavilion')]},
 {title:'Large dolls and costumed surrogate bodies',cluster:'doll / costume / alternate body / spatial companion',period:'mid-20th century',summary:'大型 dolls 穿 painted 或真实织物服装，使二维 creature 获得可被摆放、穿衣并与真人共享空间的身体。它们把 image-world 推进 sculpture / costume / companionship。',actions:['制作 anthropomorphic doll bodies','结合 painted clothing 与 textile garments','通过 costume 改变 persona','让 surrogate body 从图像进入实际生活空间'],sourceUrl:'https://www.labiennale.org/en/art/2022/milk-dreams/ovartaci',images:[],relations:[]},
 {title:'Gender self-fashioning / changing embodied identity',cluster:'gender / dress / self-determination / body',period:'1950s–1970s',summary:'Museum Ovartaci 的当前传记明确记录：1957 年接受 gender-affirming surgery，随后以女性称谓、裙装和化妆生活；1975 起又重新以男性身份自称并改变衣着。档案因此避免把其性别史冻结成单一标签，而把身体身份视为长期变化的 lived process。',actions:['把 dress / make-up 与 self-identification 作为生活实践','持续争取对身体和称谓的决定权','允许 identity 在不同生命阶段发生变化','在研究数据中保留 pronoun / historiography 的复杂性'],sourceUrl:'https://www.ovartaci.dk/ovartaci',images:[],relations:[]},
 {title:'Helicopter drawings, plans and models',cluster:'escape machine / engineering fantasy / cardboard + wood',period:'mid-20th century–1970s',summary:'大量图纸以及 cardboard / wood 模型围绕能够越过 hospital walls 的 helicopter 展开。这里“逃离”被转成长期 engineering imagination：制度边界不只被叙述，而被反复设计成可以技术性穿越的问题。',actions:['反复绘制 helicopter plans','把 drawing 转成 cardboard / wood model','持续修改 body / propeller / flight mechanism','将 escape desire 转成 material engineering project'],sourceUrl:'https://www.labiennale.org/en/art/2022/milk-dreams/ovartaci',images:[],relations:[]}
 ],awards:[],exhibitions:['The Milk of Dreams — Venice Biennale 2022','Becoming Ovartaci — Cobra Museum, 2023','Jeg begyndte som paradisfugl — Kunstmuseum Brandts, 2025–2026'],sources:[{label:'Museum Ovartaci · artist biography',url:'https://www.ovartaci.dk/ovartaci'},{label:'Museum Ovartaci · institution and collection',url:'https://www.ovartaci.dk/om-museet'},{label:'La Biennale · Ovartaci 2022',url:'https://www.labiennale.org/en/art/2022/milk-dreams/ovartaci'},{label:'Kunstmuseum Brandts · Ovartaci retrospective',url:'https://brandts.dk/udstillinger/ovartaci/'}]
}
};
