import type { ArtistArchive, ArchiveProject, ArchiveRelation } from './archiveData';
const rel=(kind:ArchiveRelation['kind'],label:string,detail?:string):ArchiveRelation=>({kind,label,detail});
const project=(p:ArchiveProject)=>p;

export const archiveBatch316:Record<string,ArtistArchive>={
 'walid-raad':{
  artistId:'walid-raad',
  projectCoverage:'继续深化既有 Walid Raad 档案：My neck is thinner than a hair: Engines、The Atlas Group archive protocol、Mapping Sitting。重点从“虚构档案”推进到档案分类、新闻摄影、证据失效与机构保存机制。',
  imageCoverage:'MoMA 官方馆藏与2015–16回顾展提供作品和安装视图；版权归 The Atlas Group / Walid Raad，未确认自由再发布，故不复制受限图像。',
  note:'Raad 的关键并非简单混淆真实与虚构，而是把档案的分类、署名、证据链、重复展示和机构权威本身变成材料。作品经常避开暴力现场最戏剧性的瞬间，转而研究战争留下的次级物件、新闻惯例、照片用途与记忆机制。这样，“历史事实”不再只由图像内容决定，而由谁保存、怎样命名、如何分类和在哪里重新展示共同生产。',
  projects:[
   project({title:'My neck is thinner than a hair: Engines',cluster:'war archive / press photography / evidence / serial display',period:'1996–2004',summary:'作品研究1975–1991年黎巴嫩战争期间汽车炸弹及其新闻图像。MoMA 记录 Atlas Group 围绕245起汽车炸弹展开调查，其中这一组由100张来自 Beirut 的 An-Nahar Research Center 与 Arab Documentation Center 的新闻摄影构成。爆炸后汽车发动机往往被抛到远处却保持相对完整；摄影记者会争相寻找并拍摄发动机，因为发动机编号理论上可以追查车辆所有者。但 Raad 指出炸弹车辆通常为赃车，因此这种证据几乎没有司法价值。作品把政治暴力的中心从爆炸现场移到一个既被当成线索、又不断失效的机械残骸，并揭示媒体和政治人物如何围绕“证据”生产可见性。',actions:['在黎巴嫩报纸与文献机构档案中搜集汽车炸弹爆炸后发动机的新闻照片。','不以爆炸瞬间为中心，而追踪爆炸后被摄影记者寻找、编号和报道的机械残骸。','将100张历史新闻照片重新输出为统一尺寸的 pigmented inkjet prints，形成连续档案墙。','通过讲述发动机编号、赃车与司法证据失效之间的矛盾，拆解“照片＝事实线索”的直觉。','把政治人物在发动机旁合影、媒体竞争寻找残骸等行为纳入作品，使新闻生产机制成为战争史的一部分。'],sourceUrl:'https://www.moma.org/slideshows/1/30',images:[],relations:[rel('收藏','Museum of Modern Art, New York','100 pigmented inkjet prints；每张24 × 34 cm；Fund for the Twenty-First Century。'),rel('档案' as ArchiveRelation['kind'],'An-Nahar Research Center + Arab Documentation Center, Beirut','作品中的100张历史照片来自这两个新闻/文献档案。'),rel('展览','Walid Raad — MoMA','2015-10-12–2016-01-31 回顾展重新展示该系列；安装照由 Thomas Griesel 拍摄。')]}),
   project({title:'The Atlas Group — archive protocol',cluster:'fictional institution / classification / authorship / historiography',period:'1989–2004',summary:'Atlas Group 被 Raad 以“研究并记录黎巴嫩当代史”的档案机构形式提出。MoMA 对其分类结构有明确记录：Type A 文件归于已识别个人；Type FD 为匿名个人或机构的 found documents；Type AGP 则归于 Atlas Group 自身。Raad 同时说明，许多展示的文件实际上由他制作，再归给虚构或历史人物。作品因此不是简单制作假照片，而是先制造一个能够接收、命名、分类、保存和解释文件的机构框架，再让真实与虚构材料在框架中获得类似的档案权威。',actions:['建立名为 The Atlas Group 的研究/档案身份，并把项目描述为黎巴嫩战争史研究机构。','将文件按 Type A、Type FD、Type AGP 分类，模拟正式档案的来源学与编目系统。','同时使用找到的历史文件与艺术家制作的文件，并赋予不同人物/机构署名。','通过 lecture、摄影、录像、notebook、出版和后来的博物馆装置不断重新呈现同一档案。','让观众必须同时判断文件内容与档案制度本身，而不是只辨认单张图像真假。'],sourceUrl:'https://www.moma.org/slideshows/41/748',images:[],relations:[rel('收藏','Museum of Modern Art — Walid Raad collection','MoMA 当前在线记录49件作品，包含 Atlas Group 多种媒介与后续 Section 139。'),rel('展览','Walid Raad — MoMA — 2015–2016','大型回顾把 Atlas Group 与 Scratching on things I could disavow 并置，显示从战争档案到艺术制度研究的连续性。')]}),
   project({title:'Mapping Sitting: On Portraiture and Photography',cluster:'vernacular photography / studio archive / Arab Image Foundation',period:'2002',summary:'Raad 与 Akram Zaatari 共同整理和研究中东商业照相馆及民间肖像档案。MoMA 的 Raad 专题出版物把该项目与他作为 Arab Image Foundation 成员的工作并置：AIF 自1997年起收集、研究中东摄影，Mapping Sitting 则把商业照相馆、证件照、街头摄影和普通人的坐姿/观看方式作为摄影史材料。它和 Atlas Group 的关系很重要：Raad 不只制造虚构档案，也长期直接参与真实照片档案的收集、编目与再展示，因此他对“档案如何生产历史”的理解来自具体机构实践。',actions:['与 Akram Zaatari 合作研究商业照相馆与民间肖像档案。','从艺术摄影之外的证件照、工作室肖像和日常图像研究摄影的社会用途。','参与 Arab Image Foundation 的照片收集与研究，把保存、分类、复制和展示视为摄影实践。','将真实档案研究与 Atlas Group 的构造性档案并置，使两种方法互相检验。'],sourceUrl:'https://www.moma.org/momaorg/shared/pdfs/docs/publication_pdf/3227/MoMA_WalidRaad_PREVIEW.pdf',images:[],relations:[rel('展览','Mapping Sitting — Palais des Beaux-Arts, Brussels','2002-05-04–05-26；MoMA 专题出版物记录安装视图。'),rel('策展','Walid Raad + Akram Zaatari','两位艺术家共同研究并组织项目。'),rel('收藏','Arab Image Foundation, Beirut','Raad 曾为基金会成员；基金会自1997年起收集与研究中东摄影档案。')]})
  ],
  awards:[],
  exhibitions:['Walid Raad — Museum of Modern Art, New York — 2015–2016','Mapping Sitting — Palais des Beaux-Arts, Brussels — 2002'],
  sources:[{label:'MoMA — My neck is thinner than a hair: Engines',url:'https://www.moma.org/slideshows/1/30'},{label:'MoMA — Walid Raad artist collection',url:'https://www.moma.org/artists/35285-walid-raad'},{label:'MoMA — Walid Raad publication preview',url:'https://www.moma.org/momaorg/shared/pdfs/docs/publication_pdf/3227/MoMA_WalidRaad_PREVIEW.pdf'}]
 }
};