import type { ArtistArchive, ArchiveProject, ArchiveRelation } from './archiveData';
const rel=(kind:ArchiveRelation['kind'],label:string,detail?:string):ArchiveRelation=>({kind,label,detail});
const project=(p:ArchiveProject)=>p;
export const archiveBatch304:Record<string,ArtistArchive>={
 'taryn-simon':{artistId:'taryn-simon',projectCoverage:'深化 Taryn Simon：Paperwork and the Will of Capital、Birds of the West Indies、Image Atlas、Black Square。补外交仪式、分类学、搜索引擎与长期档案协议。',imageCoverage:'艺术家官网与 Gagosian 提供项目及安装图入口；未确认自由再发布授权的图像不复制。',note:'Simon 不只是揭露隐藏事物，而是寻找已经在生产事实的制度，再把制度规则变成作品形式。摄影常只是证据层，文字、分类、档案来源、雕塑、网页接口和机构现场同样承担意义。',projects:[
 project({title:'Paperwork and the Will of Capital',cluster:'diplomacy / archival reconstruction / botany / sculpture',period:'2015–',summary:'Simon 从历史外交签署照片中抽取常被忽略的花束：研究1968年以后、涉及1944 Bretton Woods Conference 参会国的协议，与植物学家合作识别花材，从荷兰 Aalsmeer 花卉市场取得植物，在纽约依据档案照片重建并重新摄影。完整系列包含36张版数照片与12件独一雕塑；混凝土压花装置、干燥植物、档案图和文字又保存花束的另一时间状态。项目把权力如何经由桌面、花束、摄影、签字和仪式被舞台化变成可见结构。',actions:['检索外交签署档案，把背景花束转为研究对象。','与植物学家识别花材并通过国际花卉供应链重新取得材料。','依据历史图像重建花束并重新摄影。','制作混凝土 flower presses 保存标本、档案照片与文字。','在 United Nations Headquarters 等制度现场展示，使作品返回其研究的权力空间。'],sourceUrl:'https://gagosian.com/exhibitions/2016/taryn-simon-paperwork-and-the-will-of-capital-new-york/',images:[],relations:[rel('历史节点','Bretton Woods Conference — 1944','项目所选事件涉及会议参会国；会议促成 IMF 与 World Bank 建立。'),rel('生产网络','botanist / Aalsmeer flower auction / New York reconstruction','艺术家访谈明确说明植物识别、采购与重建流程。'),rel('双年展','56th Venice Biennale — 2015','系列雕塑在2015威尼斯双年展期间预展。'),rel('机构现场','United Nations Headquarters — New York — 2016','作品返回真实外交制度空间展示。')]}),
 project({title:'Birds of the West Indies',cluster:'cinema archive / taxonomy / ornithology',period:'2013–2014',summary:'项目从鸟类学家 James Bond 与 Ian Fleming 借名的真实关系出发，反向进入24部 James Bond 电影。Simon 扮演分类研究者，寻找、识别、摄影并组织电影中出现的鸟，把自然史分类、电影工业和虚构人物名称连成闭环：真实科学家的名字进入虚构，艺术家又从虚构电影中抽取鸟类制造新的档案。',actions:['从 ornithologist James Bond 与 Ian Fleming 的命名关系建立入口。','系统观看24部 Bond 电影并定位鸟类视觉信息。','以自然史分类方式识别、摄影和组织鸟。','把时间码、地点、分类信息与图像连接。'],sourceUrl:'https://tarynsimon.com/',images:[],relations:[rel('展览','Carnegie International 56th Edition — Carnegie Museum of Art — 2013–14','Gagosian 艺术家资料记录该项目安装。'),rel('展览','Almine Rech — Paris — 2015','Birds of the West Indies 个展。')]}),
 project({title:'Image Atlas',cluster:'search engine / comparative interface / geopolitics',period:'2012',summary:'Image Atlas 把搜索引擎本身当成视觉文化对象：同一检索概念在不同地理/文化位置产生不同图像结果，统一界面让算法、语言、地域和信息基础设施如何组织视觉世界变得可比较。它把 Simon 的索引方法从实体调查推进到实时数字检索。',actions:['以同一概念触发不同地理语境的图像检索。','将结果并置于统一网页界面。','把研究对象从艺术家拍摄的照片推进到平台排序系统。'],sourceUrl:'https://tarynsimon.com/',images:[],relations:[rel('方法关系','search engine / geographic indexing','把 An American Index 的索引逻辑推进到平台化图像检索。')]}),
 project({title:'Black Square',cluster:'long-duration archive / invention / consequences',period:'2006–ongoing',summary:'Black Square 以稳定的黑色方形协议持续容纳与人类发明及其后果相关的对象、文件和图像。不同事件被形式上压平，但政治、技术、生态和伦理后果高度不同；项目因此是一套可以多年吸收新历史材料的开放档案协议，而非一次完成的摄影系列。',actions:['预设稳定方形展示协议。','持续寻找与人类发明及后果相关的材料。','利用统一形式与内容差异建立长期比较。'],sourceUrl:'https://tarynsimon.com/',images:[],relations:[rel('方法关系','long-duration archive','开放协议持续吸收新的技术与历史后果。')]})
 ],exhibitions:['The Innocents — MoMA PS1 — 2003','An American Index of the Hidden and Unfamiliar — Whitney Museum of American Art','A Living Man Declared Dead and Other Chapters I–XVIII — Tate Modern / Neue Nationalgalerie / MoMA','56th Venice Biennale — 2015','Paperwork and the Will of Capital — Gagosian New York / Rome — 2016','Paperwork and the Will of Capital — United Nations Headquarters — New York — 2016'],awards:[],sources:[{label:'Taryn Simon — official site',url:'https://tarynsimon.com/'},{label:'Gagosian — Paperwork and the Will of Capital',url:'https://gagosian.com/exhibitions/2016/taryn-simon-paperwork-and-the-will-of-capital-new-york/'},{label:'Gagosian Quarterly — Simon / Teju Cole interview',url:'https://gagosian.com/quarterly/2021/06/23/interview-taryn-simon-teju-cole/'},{label:'Gagosian — Taryn Simon',url:'https://gagosian.com/artists/taryn-simon/'}]}
};
