import type { ArtistArchive, ArchiveRelation } from './archiveData';

const rel=(kind:ArchiveRelation['kind'],label:string,detail?:string):ArchiveRelation=>({kind,label,detail});

export const archiveBatch258:Record<string,ArtistArchive>={
'carrie-mae-weems':{
 artistId:'carrie-mae-weems',
 projectCoverage:'深化 Kitchen Table Series 与 From Here I Saw What Happened and I Cried：补齐作品物质结构、档案来源、图像再处理步骤与“观看/见证”方法，使其从题材标签变成可追踪的制作机制。',
 imageCoverage:'MoMA 与 National Gallery of Art 均提供官方作品页和安装/馆藏图；版权属于 Carrie Mae Weems，故不复制受限图片，仅保留官方入口。',
 note:'Weems 的关键不是简单“表现黑人身份”，而是不断改变谁拥有叙述位置：Kitchen Table 通过自演、自导和固定室内舞台生产一个女性主体；From Here 则进入已经被殖民/科学制度制造过的旧图像，通过重新摄影、裁切、染色、文字和序列重新分配观看权。',
 projects:[
 {title:'Kitchen Table Series',cluster:'staged photography / domestic space / gender / text-image sequence',period:'1990',summary:'National Gallery of Art 馆藏版本由20幅 platinum/palladium prints 与14张 screenprinted text sheets 组成。所有主要摄影场景都围绕一张厨房桌和单一吊灯展开，Weems 自己出演核心女性角色；人物关系、独处、亲密、母女互动等变化发生在高度稳定的舞台中。因此厨房不是背景，而是控制变量：空间和光线基本不变，变化的是身体、关系与叙事。文字页又使系列不能被缩减为20张独立肖像，而更接近摄影与文学共同推进的章节结构。',actions:['把厨房桌、吊灯和固定机位建立为重复舞台。','由艺术家本人扮演核心角色，同时引入伴侣、朋友与孩子等人物关系。','通过姿态、座次、镜子、纸牌、化妆等细小动作推进关系变化。','把20幅摄影与14张文字页组合成完整portfolio，使图像与叙事互相补充而非说明关系。'],sourceUrl:'https://www.nga.gov/artworks/209288-kitchen-table-series',images:[],relations:[rel('收藏','National Gallery of Art','1990/printed 2003 portfolio: 20 platinum/palladium prints + 14 screenprints.'),rel('方法','fixed domestic stage → changing social relations','同一厨房结构被当成控制变量，让性别、亲密关系和主体位置成为真正发生变化的部分。')]},
 {title:'From Here I Saw What Happened and I Cried',cluster:'appropriation / archive / race science / text on glass / witnessing',period:'1995–1996',summary:'MoMA 记录作品由34件组成，使用美国南方被奴役者以及19、20世纪非洲/非裔美国人的既有照片，其中包括 Louis Agassiz 1850年为种族分类理论委托制作的 Joseph T. Zealy 达盖尔银版肖像。Weems 重新摄影、放大和裁切档案图像，以红色滤镜处理主体，用圆形/椭圆形遮罩强化“通过镜头观看”的感觉，再在覆盖照片的玻璃上喷砂文字。两端以蓝色调 Mangbetu 女性图像构成见证者框架。作品由此不是简单展示历史照片，而是逐层暴露原图的拍摄意图、分类暴力与后来的观看制度。',actions:['从博物馆、大学档案及既有摄影史中选择曾经分类/再现黑人身体的图像。','重新摄影、放大、裁切，使来源不同的历史图像进入统一视觉尺度。','用红色调与圆/椭圆遮罩削弱原照片作为中性纪录的权威。','在保护玻璃上喷砂加入第二人称/叙事文字，使观看者必须同时读图与读语言。','用蓝色调女性肖像在序列首尾建立“观看历史的见证者”。'],sourceUrl:'https://www.moma.org/collection/works/45579',images:[],relations:[rel('委托脉络','J. Paul Getty Museum','MoMA artist profile notes the 1994 Getty commission responding to historical African American photographs.'),rel('收藏','Museum of Modern Art','34-part installation; chromogenic prints with sand-blasted text on glass.'),rel('策展','Roxana Marcoci / Dana Ostrander','MoMA 2020–21 dedicated collection gallery.'),rel('方法','archive image → rephotograph → crop/tint → text/glass → sequence','The intervention makes the historical image’s framing and institutional use visible rather than treating appropriation as neutral reuse.')]}
 ],
 awards:[],exhibitions:['Carrie Mae Weems: Three Decades of Photography and Video — Guggenheim, 2014','Kitchen Table Series — National Gallery of Art, 2017–18','Carrie Mae Weems’s From Here I Saw What Happened and I Cried — MoMA, 2020–21'],
 sources:[{label:'MoMA · From Here I Saw What Happened and I Cried',url:'https://www.moma.org/collection/works/45579'},{label:'MoMA · Carrie Mae Weems',url:'https://www.moma.org/artists/7177'},{label:'NGA · Kitchen Table Series',url:'https://www.nga.gov/artworks/209288-kitchen-table-series'},{label:'Guggenheim · Three Decades',url:'https://www.guggenheim.org/press-release/guggenheim-presents-carrie-mae-weems-three-decades-of-photography-and-video'}]
},
'zanele-muholi':{
 artistId:'zanele-muholi',
 projectCoverage:'继续深化 Somnyama Ngonyama，把自画像从“身份表达”拆成具体的全球拍摄、日常材料转译、黑白影调控制与殖民/劳动历史再编码机制。',
 imageCoverage:'Autograph/Harvard 展览页与 Tate 官方影片提供系列图像和艺术家讲述；版权归 Zanele Muholi，保留官方入口而不复制。',
 note:'Somnyama Ngonyama 与 Faces and Phases 的差异不只是“别人/自己”：前者把艺术家自己的身体变成一个可反复改造的历史界面，日常物件在不同地点被重新编码为家务劳动、种族化观看、殖民史和性别政治的道具。',
 projects:[{title:'Somnyama Ngonyama: Hail the Dark Lioness',cluster:'self-portrait / visual activism / found materials / colonial visual archive',period:'2012–ongoing',summary:'该系列在欧洲、北美、亚洲和非洲多个城市拍摄，已形成80余幅黑白自画像。Muholi 以自己的身体作为持续画布，同时调用古典肖像、时尚摄影与民族志图像的视觉惯例；钢丝球、乳胶手套等普通材料被转成具有历史负荷的头饰或身体装置，指向家务劳动、性别政治和文化暴力。系列通过强化黑白影像中的肤色与直接凝视，使原本常被外部分类的黑人身体取得主动控制镜头和造型的权力。',actions:['在不同国家和城市利用旅行现场可获得的日常材料制作临时造型。','由艺术家本人持续面对镜头，把自画像建立成跨地点重复的表演结构。','把清洁用品、劳动工具和普通物件重新编码成与种族、劳动和殖民历史有关的道具。','借用古典绘画、时尚摄影和民族志摄影的构图惯例，再反转这些惯例原有的观看权。','以高反差黑白影调和直接凝视强化观看者与被摄主体之间的对峙。'],sourceUrl:'https://lockegallery.fas.harvard.edu/somnyama-ngonyama',images:[],relations:[rel('策展人','Renée Mussai','Autograph traveling exhibition; Harvard presentation identifies Mussai as curator.'),rel('机构','Autograph','Organized the traveling exhibition and its visual-activist framing.'),rel('机构网络','Tate Modern','2024 revised/expanded retrospective contextualized the self-portraits alongside early activism, Faces and Phases and sculpture.'),rel('方法差异','Faces and Phases ↔ Somnyama Ngonyama','community counter-archive of named sitters ↔ self-body as a repeatable site for rewriting historical visual codes.')] }],
 awards:[],exhibitions:['Somnyama Ngonyama — Autograph traveling exhibition','Zanele Muholi — Tate Modern, 2024–25'],sources:[{label:'Harvard · Somnyama Ngonyama',url:'https://lockegallery.fas.harvard.edu/somnyama-ngonyama'},{label:'Tate · Muholi on Somnyama Ngonyama',url:'https://www.tate.org.uk/art/artists/zanele-muholi-18840'}]
},
'laia-abril':{
 artistId:'laia-abril',
 projectCoverage:'深化 A History of Misogyny 的第二、第三章：补齐 On Rape 的叙事重心转换、机构传播与奖项脉络，并把 On Mass Hysteria 的跨学科案例研究机制写入档案。',
 imageCoverage:'艺术家官网、Photo Elysée 与 LE BAL 均提供官方安装图/项目图；版权未确认开放再发布，故只记录来源入口。',
 note:'Abril 的研究型摄影越来越少依赖“拍到事件现场”。On Rape 主动把视觉重心从受害者转向制度、法律、物件和证词；On Mass Hysteria 又把摄影、声音、历史档案与医学/人类学研究组合成案例系统。她真正持续发展的媒介其实是“研究结构”。',
 projects:[
 {title:'On Rape — and institutional rape culture',cluster:'A History of Misogyny II / law / testimony / institutional violence',period:'2016–ongoing; book 2022',summary:'Abril 将该项目作为 A History of Misogyny 第二章。起点之一是西班牙 La Manada 集体强奸案及其最初被判较轻“sexual abuse”罪名引发的争议。她明确决定避免继续生产以受害者为中心、可能重复 victim-blaming 的视觉叙事，转而调查保护、正常化和延续性暴力的法律、信念与权力机制。项目通过 conceptual portraits、历史材料、物件、文件、证词、声音与文字处理战争强奸、强迫受害者嫁给施暴者、处女检验、司法二次伤害等制度结构。2022年出版228页专书，由 Abril 与 Ramon Pez 共同艺术指导。',actions:['从具体司法案件出发，将问题从单次犯罪扩大到制度性 rape culture。','跨历史和国家比较法律、习俗、战争、宗教与司法程序。','主动把视觉叙事重心从受害者身体移向制度、施暴结构、物件和证据。','将 conceptual portrait、证词、声音、档案和文本组织为展览与书两种不同阅读结构。','通过长期巡展让同一研究在 Foam、V&A/Photoworks、C/O Berlin、Moderna Museet、Reina Sofía 等机构被重新语境化。'],sourceUrl:'https://www.laiaabril.com/project/on-rape/',images:[],relations:[rel('支持','Magnum Foundation / Visionary Award','Artist records both as project support; mentorship by Marta Gili.'),rel('机构','Foam','2020–21 presentation; Abril was Foam Paul Huf Award 2020 winner.'),rel('机构','V&A + Photoworks','2022 presentation under V&A Parasol Foundation Women in Photography Project.'),rel('策展人','Sophia Greiff','Curated C/O Berlin 2024 presentation.'),rel('收藏/展示','Museo Reina Sofía','On Rape works entered the permanent collection display in 2026, curated in the collection context by Manuel Segade.')]},
 {title:'On Mass Hysteria',cluster:'A History of Misogyny III / medical history / collective symptoms / multimedia research',period:'2019–2025',summary:'第三章研究历史上被命名为“collective hysteria”的群体现象。Photo Elysée 与 LE BAL 的资料显示，Abril 将其理解为在年轻女性群体面对高压、压抑或无法表达的环境时出现的集体身体症状，并把历史叙事与当代案例并置。LE BAL 版本集中研究三个案例，并与人类学家、社会学家、神经学家和精神科医生讨论成因，其中包括2007年墨西哥 Chalco 天主教女子寄宿学校的腿部瘫痪，以及2012–22年柬埔寨制衣厂女工集体昏厥。作品由摄影、档案、文字、声音和研究材料共同构成，而非用单一摄影类型解释身体。',actions:['从历史“附身/歇斯底里”叙事追踪到现代学校与工业劳动环境中的集体症状。','选择具体案例而非泛化“女性歇斯底里”概念。','与 anthropology、sociology、neurology、psychiatry 等不同学科专家交叉研究。','用摄影、档案材料、声音、文字和安装共同呈现不同解释之间的张力。','通过 Photo Elysée、Finnish Museum of Photography 与 LE BAL 的共同生产形成跨机构研究网络。'],sourceUrl:'https://elysee.ch/en/exhibitions/laia-abril/',images:[],relations:[rel('共同制作','Photo Elysée / Finnish Museum of Photography / LE BAL','Three-institution co-production across 2023–25.'),rel('研究方法','case study + interdisciplinary consultation','Specific collective-symptom events are tested against multiple disciplinary explanations rather than reduced to a single diagnosis.'),rel('演变','On Abortion → On Rape → On Mass Hysteria','legal access to bodies → institutional normalization of sexual violence → authority to diagnose and interpret women’s collective bodily distress.')]}
 ],
 awards:['Prix de la Photo Madame Figaro — Arles 2016','Paris Photo–Aperture PhotoBook of the Year 2018 (On Abortion)','Foam Paul Huf Award 2020','Hood Medal 2022','Shpilman Award 2023'],
 exhibitions:['On Rape — Foam, 2020–21','On Rape — V&A / Photoworks, 2022','On Mass Hysteria — Photo Elysée, 2023','On Rape — C/O Berlin, 2024','On Mass Hysteria — LE BAL, 2025','On Rape — Museo Reina Sofía permanent collection display, 2026'],
 sources:[{label:'Laia Abril · On Rape',url:'https://www.laiaabril.com/project/on-rape/'},{label:'Laia Abril · long biography',url:'https://www.laiaabril.com/about/long-bio/'},{label:'Photo Elysée · On Mass Hysteria',url:'https://elysee.ch/en/exhibitions/laia-abril/'},{label:'LE BAL · On Mass Hysteria',url:'https://www.le-bal.fr/en/2025/01/laia-abril-mass-hysteria-history-misogyny'},{label:'Laia Abril · On Rape at Reina Sofía',url:'https://www.laiaabril.com/exhibition/onrape-reinasofia/'}]
}
};
