import type { ArtistArchive, ArchiveRelation } from './archiveData';
const rel=(kind:ArchiveRelation['kind'],label:string,detail?:string):ArchiveRelation=>({kind,label,detail});

const roster='https://www.labiennale.org/en/art/2017/artists';
const dekyndt='https://edithdekyndt.be/one-thousand-and-one-night/';
const diaz='https://www.sebastiandiazmorales.com/mise_en_abyme-book/';
const downey='https://www.moma.org/collection/works/167193';
const eliasson='https://olafureliasson.net/greenlight/';
const eliassonTba='https://tba21.org/greenlight_workshop_venice';
const engsted='https://www.phileas.art/museum-donations/sorenengsted';

export const archiveBatch126:Record<string,ArtistArchive>={
'venice-2017-edith-dekyndt':{artistId:'venice-2017-edith-dekyndt',projectCoverage:'2 个 dust/light / oxidation-time site-specific 节点已建立深档案 · 2016–2017',imageCoverage:'0 / 2 项目暂不使用不稳定外链图像',note:'Dekyndt 把 humidity、light、dust、oxidation 和 hourly maintenance 当作真正材料。作品不是“极简外观”，而是让场地自身物质与时间持续改写形态。',projects:[{title:'One Thousand and One Nights',cluster:'site dust / rotating light / hourly sweeping / ephemeral cloud',period:'2016–2017',summary:'Venice 版本使用现场收集的 dust 铺成矩形，并从上方投射完全重合的光。projector 会缓慢偏移，attendant 每小时用 broom 把尘土重新扫回光的边界；每次动作都会扬起短暂云雾。',actions:['直接从 exhibition site 收集 dust，而不是带入预制雕塑材料','在 floor 上铺出明确 rectangular dust field','用 projector/light beam 与 dust contour 精确重合','让光源持续缓慢移动，使“对齐状态”必然失效','设定 attendant 每小时约十分钟的 sweeping protocol','扫动时接受 dust cloud、边缘误差和空气流动进入作品','把维护劳动写进作品结构，使“保持形状”本身变成永无完成的 performance'],sourceUrl:dekyndt,images:[],relations:[rel('展览','Viva Arte Viva — Venice Biennale 2017','Arsenale · Pavilion of Time and Infinity')]},{title:'Slow Object 08',cluster:'linen / silver foil / oxidation / visitor passage',period:'2017',summary:'入口处 linen curtain 覆盖 silver foils；银色最初像贵金属表面，却因 humidity、direct light 和 visitors passage 持续氧化、磨损，作品外观在展期内不可逆改变。',actions:['以 linen 制作 flexible curtain support','将 silver foil 覆盖在 textile 表面','把作品放置在高人流入口位置，让 passing bodies 改变表面','不隔绝 humidity / direct light，主动允许 oxidation','将 precious-looking shine 的退化作为时间可视化','接受每一版 installation 因环境不同产生不同老化轨迹'],sourceUrl:dekyndt,images:[],relations:[rel('展览','Viva Arte Viva — Venice Biennale 2017','Arsenale entrance')] }],awards:[],exhibitions:['Viva Arte Viva — Venice Biennale 2017'],sources:[{label:'Edith Dekyndt · One Thousand and One Night / Slow Object 08',url:dekyndt},{label:'La Biennale · Artists 2017',url:roster}]},

'venice-2017-sebastian-diaz-morales':{artistId:'venice-2017-sebastian-diaz-morales',projectCoverage:'1 个 reality-fiction / staged-light moving-image trilogy 已建立深档案 · 2015–2017',imageCoverage:'0 / 1 项目暂不使用不稳定外链图像',note:'Díaz Morales 的 Venice 节点可通过 Mise en Abyme / Ficcionario IV 语境读：不是纪录现实，而是用 controlled light、suspension、displaced time-space 把“现实本来就被构造”这件事显出来。',projects:[{title:'Insight / Suspension / The Lost Object — Mise en Abyme trilogy',cluster:'moving image / staged light / suspended time-space / reality-fiction',period:'mid-2010s; Venice 2017 context',summary:'三部作品建立近 dream-like、由光束控制的场景。人物与物体不再稳定嵌入现实环境，time / space 被暂停、重复或重组，使 viewer 意识到“自然现实”其实依赖 framing、lighting 与 narrative convention。',actions:['先设计可被灯光切割的 controlled set / darkened space','使用 directional beams 而非自然光建立 image logic','让 object / body 在画面中被 suspension、slow timing 或 isolated staging 剥离日常因果','通过 editing 重建 time-space continuity，而非忠实保留现场顺序','把 realistic surface 与明显 artificial construction 同时保留','让 viewer 在“看到现实”与“看到影像装置制造现实”之间不断切换'],sourceUrl:diaz,images:[],relations:[rel('出版','Sebastián Díaz Morales: Mise en Abyme','Bom Dia Books; publication linked to Venice 2017 and MGK Siegen'),rel('展览','Viva Arte Viva — Venice Biennale 2017','Pavilion of Joys and Fears')]}],awards:[],exhibitions:['Viva Arte Viva — Venice Biennale 2017'],sources:[{label:'Sebastián Díaz Morales · Mise en Abyme',url:diaz},{label:'La Biennale · Artists 2017',url:roster}]},

'venice-2017-juan-downey':{artistId:'venice-2017-juan-downey',projectCoverage:'2 个 transnational-video / map-network 节点已建立深档案 · 1973–1976',imageCoverage:'0 / 2 项目暂不使用不稳定外链图像',note:'Downey 的录像旅行不是 conventional ethnography：他在不同社区之间携带、播放前一站影像，让被拍摄者也成为 viewer / collaborator；video 因此被当作多向通信网络。2017 为历史性纳入，当前重点覆盖 Video Trans Americas 系统。',projects:[{title:'Video Trans Americas',cluster:'14-channel video / road journey / collaborative ethnography / network map',period:'1973–1976',summary:'Downey 从 New York 经 Mexico、Guatemala、Peru、Bolivia 到 Chile 等地旅行，拍摄当地 community，随后在下一站把之前拍到的录像播放给新 hosts。最终 footage 被组织为 14-channel black-and-white video，monitors 按地理位置排列在 vinyl map 上。',actions:['进行跨美洲长期 road journey 而非短期 studio production','在不同 community 中拍摄 everyday / cultural situations','到达新地点后立即向当地人播放前一站 footage，建立 feedback loop','把 subjects 视作 collaborators，削弱单向 ethnographic gaze','保留不同地点影像之间的差异，不剪成单一民族志叙事','最终将 14 monitors 按 geographic relation 排在 floor/wall map 上','让 viewer 的身体移动对应跨地域 network traversal'],sourceUrl:downey,images:[],relations:[rel('收藏','Museum of Modern Art, New York','Video Trans Americas, 1976'),rel('展览','Viva Arte Viva — Venice Biennale 2017','historical practice inclusion')]},{title:'Map of America',cluster:'hand-drawn map / border erasure / transnational identity',period:'1975',summary:'在与 Video Trans Americas 同一旅程中，Downey 用 coloured pencil、pencil 与 acrylic 改写现成地图，消除 national borders，以 swirling colour 把 continental map 转为 transnational communication image。',actions:['以 printed map 作为 base，而不是从空白纸构图','用 coloured pencil / acrylic 覆盖、弱化或取消 national border logic','让 hand-drawn gesture 与 cartographic authority 冲突','把 map 作为 video journey 的 conceptual diagram','将 geography 从 state division 改成 communication / circulation field'],sourceUrl:'https://www.moma.org/collection/works/164788',images:[],relations:[rel('收藏','Museum of Modern Art, New York','Map of America, 1975')]}],awards:[],exhibitions:['Viva Arte Viva — Venice Biennale 2017'],sources:[{label:'MoMA · Video Trans Americas',url:downey},{label:'MoMA · Map of America',url:'https://www.moma.org/collection/works/164788'},{label:'La Biennale · Artists 2017',url:roster}]},

'venice-2017-olafur-eliasson':{artistId:'venice-2017-olafur-eliasson',projectCoverage:'1 个 participatory-lamp / refugee shared-learning system 已建立深档案 · 2016–2017',imageCoverage:'0 / 1 项目暂不使用不稳定外链图像',note:'Green light 不是单一灯具作品，而是 fabrication + language course + legal/psychological advice + seminar + fundraising 的 social-production system。灯具几何只是共同劳动的接口。',projects:[{title:'Green light — An artistic workshop',cluster:'recycled lamp / fivefold geometry / refugee-public workshop / shared learning',period:'2016–2017',summary:'Venice 2017 Central Pavilion 邀请 refugees、asylum seekers 与 visitors 一起搭建 stackable green-light modules，同时参加 language classes、job training、legal advice、seminars、film workshops 等。模块用 recycled/sustainable materials 制作，几何源于 Eliasson 与 Einar Thorsteinn 对 fivefold symmetry 的长期研究。',actions:['与 Einar Thorsteinn 的 fivefold-symmetry research 发展 modular lamp geometry','选择 recycled / sustainable materials 设计可重复装配的 module','把 lamp 制作拆成参与者可以共同学习和完成的 assembly process','邀请 local refugees / asylum seekers 与 public 在同一 table 上共同生产','将 language courses、job training、legal / psychological support、seminars 与 art-making 并列进 project','为 Venice site 专门设计 tables / shelves，使工作坊空间也遵循 module geometry','通过 donation/fundraising 让部分 lamps 进入社会支持资金循环','允许参与者讨论 migration / integration 与项目自身 objectification 风险，使批评成为 social fabric 一部分'],sourceUrl:eliassonTba,images:[],relations:[rel('展览','Viva Arte Viva — Venice Biennale 2017','Central Pavilion'),rel('出版','Green light — An artistic workshop','Sternberg Press / TBA21, 2017')]}],awards:[],exhibitions:['Green light — Vienna 2016','Green light — Venice Biennale 2017'],sources:[{label:'Studio Olafur Eliasson · Green light',url:eliasson},{label:'TBA21 · Green light Venice workshop',url:eliassonTba},{label:'La Biennale · Artists 2017',url:roster}]},

'venice-2017-soren-engsted':{artistId:'venice-2017-soren-engsted',projectCoverage:'2 个 low-material sculpture / levitation-video 节点已建立深档案 · 2017',imageCoverage:'0 / 2 项目暂不使用不稳定外链图像',note:'Engsted 的方法强调 cheap materials、ready-made、intuition 与制作错误。2017 Venice 新作把极笨重的 cement seating objects 与题为 Levitation 的视频并置，重量与“漂浮”形成故意的不协调。',projects:[{title:'Levitation',cluster:'single-channel video / visual gag / gravity-impossibility',period:'2017',summary:'Phileas 记录作品为 looped single-channel colour video projection with stereo sound。它与现场 concrete seating objects 同期制作，把“levitation”作为 sculpture / gravity 的反向命题。',actions:['以 moving-image 而非实体雕塑测试重量/漂浮的悖论','制作 looped single-channel video，使动作没有明确开始/结束','使用大尺寸 projection 让 image 与观众身体尺度接近','以 stereo sound 强化 physical event 感','让 video 与旁边重型 cement objects 互相定义，而非独立观看'],sourceUrl:engsted,images:[],relations:[rel('展览','Viva Arte Viva — Venice Biennale 2017','Levitation, 2017'),rel('收藏','mumok, Vienna','Phileas donation, 2017')]},{title:'Chair I / Chair II / Stool I',cluster:'cement / steel / sitting-object / cheap-material sculpture',period:'2017',summary:'三件 sitting objects 使用 cement、acrylic、oxide pigment、steel 与 concrete sealer；它们介于 furniture 与 sculpture 之间，保留 heavy construction-material presence，同时邀请对“能否坐、为何像家具”的功能判断。',actions:['用 cement / steel 制作明显 heavy 的 furniture-like support','加入 oxide pigment / acrylic 改变 concrete surface','以 concrete sealer 保留工业材料直接感','把 object 维持在 functional furniture 与 autonomous sculpture 的边界','允许制作中的粗糙、误差和 intuitive combination 成为最终形式'],sourceUrl:engsted,images:[],relations:[rel('收藏','mumok, Vienna','Chair I, Chair II, Stool I — Phileas donation 2017')]}],awards:[],exhibitions:['Viva Arte Viva — Venice Biennale 2017'],sources:[{label:'Phileas · Søren Engsted / mumok donation',url:engsted},{label:'La Biennale · Artists 2017',url:roster}]}
};
