import type { ArtistArchive, ArchiveRelation } from './archiveData';
const rel=(kind:ArchiveRelation['kind'],label:string,detail?:string):ArchiveRelation=>({kind,label,detail});

const roster='https://www.labiennale.org/en/art/2017/artists';
const ciaccioferaAsac='https://asac.labiennale.org/attivita/arti-visive/367983';
const ciaccioferaSite='https://www.micheleciacciofera.com/portfolio/viva-arte-viva-57th-venice-biennale-2017/';
const cordiano='https://www.martincordiano.com/about';
const csorgo='https://www.glassyard.hu/artists/attila-csorgo';
const curnier='https://paulinecurnierjardin.com/grotta-profunda-approfundita-2017/';
const danz='https://www.museotamayo.org/en/thebackroom/mariechen-danz';
const danzInterview='https://www.ammodo-art.org/en/story/mariechen-danz';

export const archiveBatch125:Record<string,ArtistArchive>={
'venice-2017-michele-ciacciofera':{artistId:'venice-2017-michele-ciacciofera',projectCoverage:'1 个 Sardinian-memory / mixed-material research installation 已建立深档案 · 2016–2017',imageCoverage:'0 / 1 项目暂不使用不稳定外链图像',note:'Janas Code 不是“民族志物件陈列”，而是把 Sardinian textile、蜂巢、陶瓷、矿物、植物、旧家具与手绘/手工材料压进一个 memory-wunderkammer。ASAC 对材料清单记录非常完整，因此这里把具体制作动作写到材料层。',projects:[{title:'Janas Code',cluster:'Sardinian memory / mixed-media wunderkammer / archaic-contemporary bridge',period:'2016–2017',summary:'装置围绕 Sardinian “Janas” 神话与岛屿记忆展开。铁木雕塑、羊毛、plastilina、蜂巢、金属粉、Sardinian carpet、ceramic、Tibetan paper、watercolour、回收桌、terracotta、植物根系、化石等材料被并置，形成一种跨考古、民俗、个人记忆和自然史的开放档案。',actions:['搜集 Sardinian craft / domestic / natural materials，而不是统一采购标准化 sculpture stock','将 pibiones 工艺地毯等传统 textile 与 metal grid / table 等展示结构并置','把蜂巢、植物根、种子、化石等有机/自然材料保留为带时间性的证据','制作 ceramic / terracotta / raku elements，并与 found furniture 共同进入 installation','使用 watercolour / gouache / Tibetan paper 等二维材料补充 research / memory 层','让回收的九张桌子成为 archive-support，而不是 neutral plinth','通过密集异质材料制造“archaic 与 contemporary 同时存在”的视觉语法'],sourceUrl:ciaccioferaAsac,images:[],relations:[rel('展览','Viva Arte Viva — Venice Biennale 2017','Pavilion of Traditions / Janas Code')]}],awards:[],exhibitions:['Viva Arte Viva — Venice Biennale 2017'],sources:[{label:'ASAC · Janas Code',url:ciaccioferaAsac},{label:'Michele Ciacciofera · Venice 2017',url:ciaccioferaSite},{label:'La Biennale · Artists 2017',url:roster}]},

'venice-2017-martin-cordiano':{artistId:'venice-2017-martin-cordiano',projectCoverage:'1 个 room-within-room / trapped-volume installation 已建立深档案 · 2015–2017',imageCoverage:'0 / 1 项目暂不使用不稳定外链图像',note:'Common Places 的关键不是“建筑感”三个字，而是用 skirting boards、plywood enclosure 和 plaster balls 只给出房间的最低限度线索；空间因此像是被压缩成一个可移动的模型，同时球体又像被困在固定结构里。',projects:[{title:'Common Places',cluster:'plywood room / skirting board / plaster balls / spatial paradox',period:'2015–2017',summary:'作品由 plywood、skirting boards 与 plaster balls 构成。踢脚线让简单盒体瞬间被读取成“房间”，而彩色/白色石膏球被围困其中，形成流动世界与固定 architecture 之间的矛盾。2017 Venice 版本占据 Arsenale 独立空间，并重新组织观众行走。',actions:['使用 plywood 建立近似 room / box 的 enclosure，而不是完整仿真住宅','以 skirting boards 提供最小 architectural cue，使 viewer 自动把抽象体识别为 interior','浇铸/制作 plaster spheres 作为可滚动却被结构限制的动态潜能','通过 enclosure 高度与 opening 让 viewer 同时感觉位于作品内外','把安装位置直接用于 interrupt / redirect exhibition circulation','用 familiar construction materials 触发 domestic memory，而不提供具体叙事情境'],sourceUrl:cordiano,images:[],relations:[rel('展览','Viva Arte Viva — Venice Biennale 2017','Arsenale · Common Places')]}],awards:[],exhibitions:['Viva Arte Viva — Venice Biennale 2017'],sources:[{label:'Martin Cordiano · About / Common Places practice',url:cordiano},{label:'La Biennale · Artists 2017',url:roster}]},

'venice-2017-attila-csorgo':{artistId:'venice-2017-attila-csorgo',projectCoverage:'2 个 machine-optics / geometry-to-image 节点已建立深档案 · 2004–2017',imageCoverage:'0 / 2 项目暂不使用不稳定外链图像',note:'Csörgő 的 apparatus 不是为“科技感”服务。他先提出一个 geometry / time / optics 问题，再真正制造装置，让电机、镜面、光源、纸制相机或运动机构把抽象问题转成物理现象。',projects:[{title:'Orange Space',cluster:'custom camera / rotating mechanism / spherical photograph',period:'2004',summary:'艺术家自制由 lens、wooden frame、paper covering、rotating parts、AC motor 与 adapter 构成的特殊相机；相机通过运动把普通透视改写为 spiral / spherical photographic image。',actions:['从成像几何问题出发，自行设计 camera body 而不是购买现成设备','以 wood frame + paper covering 制作大体积 optical enclosure','加入 motor / rotating parts 改变曝光期间的 camera geometry','让机械运动直接写入 final photograph','将输出照片切/组织为 spiral / spherical image，使拍摄装置与图像结构可互相推导'],sourceUrl:csorgo,images:[],relations:[]},{title:'Clock Work',cluster:'kinetic construction / light-shadow / measured time',period:'2017',summary:'Venice 2017 展出的 kinetic installation 用电机驱动三维 infinity/Möbius-like structure 与 clock hand，再通过 reflector / light 产生移动影像，把标准钟表时间重新转译为空间中的抽象运动。',actions:['制作 motor-driven kinetic structure','将 clock-hand movement 与三维 infinity-like form 同步','使用 reflector / light source 把机械运动转成 projected moving image','以 electronics / controller 保持重复但连续的 motion','让 viewer 同时看到 physical mechanism 与 virtual shadow/image，避免隐藏装置原理','把“time”从数字/表盘重新变成可观察的物理运动'],sourceUrl:csorgo,images:[],relations:[rel('展览','Viva Arte Viva — Venice Biennale 2017','Arsenale · Clock Work')]}],awards:[],exhibitions:['Viva Arte Viva — Venice Biennale 2017'],sources:[{label:'Glassyards · Attila Csörgő works',url:csorgo},{label:'La Biennale · Artists 2017',url:roster}]},

'venice-2017-pauline-curnier-jardin':{artistId:'venice-2017-pauline-curnier-jardin',projectCoverage:'1 个 cave-womb / film-scenography installation 已建立深档案 · 2011–2017',imageCoverage:'0 / 1 项目暂不使用不稳定外链图像',note:'Grotta Profunda Approfundita 的核心是 film 与 scenography 互相塑造：不是把一个 25 分钟影片挂进洞穴布景，而是让 cave / womb / placenta-like environment 成为影片的身体。',projects:[{title:'Grotta Profunda Approfundita',cluster:'mixed-media cave / HD video / Bernadette-Lourdes burlesque / body cavity',period:'2011–2017',summary:'25 分钟 HD film 以 Bernadette Soubirous / Lourdes apparition 为远端起点，混入 monkey-siren、spiderwoman、walking hand 等 chimera。2017 Venice 版本将影片置入巨大 organic cave-like installation，形成从 exterior 到 interior、head 到 lower abdomen、religious vision 到 sexual/body fantasy 的通道。',actions:['把 2011 film 重新作为 2017 spatial installation 的核心，而不是独立 screening','与长期 set/costume collaborator Rachel Garcia 共同发展 scenography / costume logic','使用 foam、granulate 等材料构造 cave / placenta-like viewing chamber','让 viewer 必须进入有明确身体隐喻的 enclosure 才能观看影像','通过 burlesque performer / chimera 替换正统宗教 iconography','把 sacred/secular、male/female、body/spirit 等 binary 通过混合形象主动弄脏','让 installation morphology 呼应 cave cavity，使建筑空间成为影片叙事的一部分'],sourceUrl:curnier,images:[],relations:[rel('展览','Viva Arte Viva — Venice Biennale 2017','Arsenale · Grotta Profunda Approfundita')]}],awards:[],exhibitions:['Viva Arte Viva — Venice Biennale 2017'],sources:[{label:'Pauline Curnier Jardin · Grotta Profunda Approfundita',url:curnier},{label:'La Biennale · Artists 2017',url:roster}]},

'venice-2017-mariechen-danz':{artistId:'venice-2017-mariechen-danz',projectCoverage:'2 个 anatomy-map / performance-activation 节点已建立深档案 · 2014–2017',imageCoverage:'0 / 2 项目暂不使用不稳定外链图像',note:'Danz 把 anatomy 当作政治知识系统：body diagram、glyph、soil/ore sample、song、costume 和 performer 都是可传递知识的媒介。2017 Venice 的空间本身是一张可进入的 3D map。',projects:[{title:'Open Book: Vessel Veins / Anatomy Archive',cluster:'anatomical archive / Mixtec glyph / knowledge hierarchy',period:'2014–2017',summary:'多种 anatomies 被放进 Mixtec glyph-like figure 中，使 Western medical body 不再是唯一标准。作品把 anatomy image 当作不同文化如何组织知识与权力的证据。',actions:['收集不同历史/文化来源的 anatomical representations','将 Western anatomy 与 Mesoamerican glyphic systems 并置','把多套 body-knowledge 压入同一 sculptural / diagrammatic figure','保留不同图式之间的不兼容，而不统一成单一“正确身体”','把 archive source 转成可在 installation 中被观看/读取的 sculptural map'],sourceUrl:danz,images:[],relations:[]},{title:'Ore Oral Orientation / Knot in Arrow',cluster:'3D body-map / Venetian clay / thermochromic sculpture / song-performance',period:'2017',summary:'Venice installation 被 Danz 描述为展开在空间中的二维 map：walls 带有三维 footprints，路径连接 earth、sand、coal、cement；floor/podium/plinth 使用回收 Venetian clay。The Dig of No Body 由可移动 loose layers 构成，Womb Tomb 的 thermochromic skin 会因触摸/温度变化显露底层图案；performance 再用 song、movement 和 costume 激活这些结构。',actions:['把整间展场设计成可步行的 3D map，而不是独立 objects 的陈列','在 wall 上制作 footprints 建立路线与时间线','将 earth、sand、coal、cement 等 raw materials 作为知识地层','回收 2016 Architecture Biennale 建筑项目使用过的 Venetian clay 制作 floor / podium / plinth','把 The Dig of No Body 设计成可移动的 loose body-layers，使 anatomy 可被重新排序','为 Womb Tomb 使用 thermochromic surface，让 touch / room temperature 实际改变可见图案','编写 song / spoken material，并与 musicians / performers 合作现场 activation','让 costume 同时承担 script / map 功能，把信息写在可穿戴材料上'],sourceUrl:danzInterview,images:[],relations:[rel('展览','Viva Arte Viva — Venice Biennale 2017','Ore Oral Orientation / Knot in Arrow performance')]}],awards:[],exhibitions:['Viva Arte Viva — Venice Biennale 2017'],sources:[{label:'Museo Tamayo · Mariechen Danz / Anatomy Archive',url:danz},{label:'Ammodo · Mariechen Danz Venice interview',url:danzInterview},{label:'La Biennale · Artists 2017',url:roster}]}
};
