import type { ArchiveProject, ArchiveRelation } from './archiveData';

const rel=(kind:ArchiveRelation['kind'],label:string,detail?:string):ArchiveRelation=>({kind,label,detail});

export const archiveExtensions265:Record<string,ArchiveProject[]>={
  'trevor-paglen':[
    {title:'They Took the Faces from the Accused and the Dead… (00520 1 F)',cluster:'machine vision / face datasets / training-image archaeology',period:'2019',summary:'Paglen把机器视觉训练集中的人脸图像从后台数据环境重新带回可见的摄影对象。该系列追踪用于人脸识别与分类系统的图像来源、裁切和标准化方式，再将其中具体训练图像放大输出为实体喷墨照片。作品的关键动作不是重新拍摄人物，而是调查数据库、选择训练样本、保留其机器读取语境，再改变尺度与展示场所：原本作为算法输入的小型数据文件成为墙面上的大幅摄影作品。这样观众首先面对一张“肖像”，随后才意识到它曾作为识别系统的数据原料。',actions:['调查人脸识别/机器视觉训练数据及其中被抽取的人脸图像。','从数据集中选择具体训练样本，而非重新拍摄被摄者。','把原本服务于算法训练的小型数字图像转为实体 inkjet print。','通过放大和美术馆墙面展示，让机器数据重新进入人类肖像观看传统。','保留作品标题中的数据/文件编号，使数据库身份与人物身份并置。'],sourceUrl:'https://www.documentjournal.com/2020/09/trevor-paglen-wants-you-to-stop-seeing-like-a-human/',images:[],relations:[rel('展览','Trevor Paglen / machine-vision practice','2019–20；作品传播图明确标记 © Trevor Paglen，Courtesy artist / Pace Gallery。'),rel('收藏','图片版权状态','官方/画廊传播图未确认开放再发布许可；本地图片暂缺，保留可靠来源入口。')]}
  ],
  'taryn-simon':[
    {title:'Chapter I — A Living Man Declared Dead and Other Chapters I–XVIII',cluster:'bloodline / archive / classification',period:'2008–11 / work dated 2011',summary:'Simon在四年间跨国研究18条血缘链，并把每一章严格组织成三段式档案。Chapter I 围绕印度的 Shivdutt Yadav：他仍然活着，却在官方土地记录中被登记为死亡。Simon不是只拍一张人物肖像，而是追踪其血缘关系，按固定、近似证件照的方式逐一拍摄仍在世的亲属；拒绝拍摄、无法到场或已经死亡的人在网格中留下空位。中间 annotation panel 用文字解释土地、继承和“法律死亡”的事件，右侧 footnote panel 再放置她拍摄或收集的证据图像。MoMA 馆藏 Chapter I 为 inkjet prints，整体 213.4 × 301.6 cm。',actions:['围绕一个“point person”追踪完整血缘链，并研究与血缘纠缠的土地、法律和政治事件。','以一致背景、姿态和尺度逐一拍摄在世血缘成员，使人物进入可比较的分类网格。','把缺席、拒绝、死亡等情况保留为空位，而不是用替代肖像补齐。','制作 annotation panel，以文字重建事件和研究脉络。','制作 footnote panel，把相关地点、文件、物件和证据照片组织在肖像系统旁。','最终以 portrait panel + annotation panel + footnote panel 三段并列，使观众必须在脸、文字与证据之间往返阅读。'],sourceUrl:'https://www.moma.org/collection/works/155734',images:[],relations:[rel('收藏','Museum of Modern Art, New York','Chapter I：2011；inkjet prints；84 × 118 3/4 in (213.4 × 301.6 cm)；object 432.2012.a-c。'),rel('展览','Taryn Simon: A Living Man Declared Dead and Other Chapters I–XVIII','MoMA, 2 May–3 Sep 2012；展出18章中的9章。'),rel('出版','A Living Man Declared Dead and Other Chapters I–XVIII','项目在2008–11四年研究期形成，并以章节式档案结构出版/展出。'),rel('收藏','图片版权 / reproduction','MoMA 提供作品与安装图，但要求经 Art Resource / Scala Archives 授权；因此本地图片暂缺。')]}
  ],
  'cao-fei':[
    {title:'Asia One — Guggenheim collection installation',cluster:'automation / logistics / film + installation',period:'2018',summary:'曹斐进入中国高度自动化物流基础设施拍摄，并把真实工业系统转成虚构叙事：主片设定巨型自动分拣中心只剩两名人类员工，他们与机器人、传送系统共同工作并逐渐形成关系；影片还插入未来访客回看废弃设施，以及工人以样板戏式造型跳合成器迪斯科的超现实段落。Guggenheim 馆藏并非只有63分20秒主片，而是一个可变尺寸多媒体装置：另有三段录像、喷墨墙面图、印在铝/画布/纸/缎面/透明胶片上的图像、灯箱、木框、机动三轮车，以及大量真实 JD.com 包装、制服、工牌、扫描器、邮寄标签等物流现成物。观众因此不是坐下看完一部电影，而是进入一个由影片、品牌物、运输工具和仓储视觉语言共同构成的物流环境。',actions:['访问包括昆山全自动分拣中心在内的先进工业设施，把真实自动化物流空间作为影片场景。','编写并拍摄两名人类员工与机器人共处的虚构故事，同时加入未来考古式段落和编舞场景。','把63分20秒主片与三段附加录像组合，而非只保留单屏电影。','收集/使用 JD.com 的制服、包装箱、胶带、标签、工牌、头盔、包袋等真实物流物件。','加入 painted motorized tricycle、code scanner、chromogenic prints、灯串、玩具、麻袋等物件，把电影叙事延伸到展厅实体空间。','以墙面喷墨图、不同承印材料的 prints、light boxes 与木框构成环绕式视觉层，使观看在影像与真实物流物之间移动。'],sourceUrl:'https://www.guggenheim.org/artwork/38191',images:[],relations:[rel('收藏','Solomon R. Guggenheim Museum, New York','2018.12；The Robert H. N. Ho Family Foundation Collection；dimensions variable。'),rel('展览','One Hand Clapping — Guggenheim','2018；官方安装图显示多通道影像与实体物流物共同占据展厅。'),rel('收藏','图片版权','Guggenheim 作品页标记 © Cao Fei；未确认开放再发布许可，本地图片暂缺。')]},
    {title:'Nova — film / Blueprints installation context',cluster:'media archaeology / cinema / digitisation / VR research',period:'2019–20',summary:'Nova 建立在曹斐对北京红霞电影院及周边电子工业史数年的研究上。她先研究中国早期计算机与社会主义时期工厂历史，再亲自写剧本并组织接近专业电影规模的团队拍摄。影片在即将消失的红霞电影院语境中展开：她重建电影院 foyer 与 kitchen 等空间，并在建筑拆除前扫描整个电影院，建立数字数据库，使同一地点随后能够进入 VR 项目。Nova 最终作为约109分钟单通道彩色有声电影出现；在 Serpentine 的 Blueprints 中，它又与 Asia One、La Town、档案/物件和 The Eternal Wave VR 一起构成场域化展览，因此同一历史地点同时以实景遗迹、电影重建和数字扫描空间存在。',actions:['用约三至四年研究红霞电影院、附近计算机工业与社会主义时期技术史。','由曹斐本人写剧本，再以大型专业电影团队完成演员、场景、摄影与声音制作。','在电影中重建红霞电影院 foyer、kitchen 等历史空间，而非单纯纪录现存建筑。','在建筑拆除前扫描整个电影院并建立数字数据库，为后续 VR 空间保存其结构。','剪辑为约109分钟单通道彩色有声影片；相关资料记录6.1声道版本。','在 Serpentine Blueprints 中让电影与 VR、既有录像和场域装置并置，形成从实体建筑到数字替身的多层观看。'],sourceUrl:'https://www.serpentinegalleries.org/about/press/cao-fei-blueprints/',images:[],relations:[rel('展览','Cao Fei: Blueprints — Serpentine Gallery','4 Mar–13 Sep 2020；immersive, site-specific installation；官方提供 Nova still 与安装图下载入口。'),rel('展览','Nova','2019；Serpentine press material 标记 Video, 109 min；Courtesy artist, Vitamin Creative Space and Sprüth Magers。'),rel('收藏','图片版权状态','官方 press images 有明确 courtesy/摄影 credit，但未据此推定可任意再发布；本地图片暂缺。')]}
  ]
};
