import type { ArtistArchive, ArchiveProject, ArchiveRelation } from './archiveData';
const rel=(kind:ArchiveRelation['kind'],label:string,detail?:string):ArchiveRelation=>({kind,label,detail});
const project=(p:ArchiveProject)=>p;
export const archiveBatch282:Record<string,ArtistArchive>={
'sophie-calle':{artistId:'sophie-calle',projectCoverage:'深化 Sophie Calle：补足 The Sleepers、L’Hôtel、Douleur exquise、Prenez soin de vous，把“私人故事”拆成规则设计、访问协议、延迟档案和多人委托。',imageCoverage:'只登记 MoMA、Centre Pompidou、La Biennale 权威入口；不复制版权状态不明确作品图。',note:'Calle 的稳定方法不是单纯暴露隐私，而是先设计规则，让现实进入规则，再用照片、文字、时间表、证词、物件与表演保存规则产生的后果。',projects:[
project({title:'The Sleepers (Les dormeurs) — intimacy produced by a timetable',cluster:'rule-based action / photography / text / intimacy',period:'1979',summary:'1979年4月，Calle 邀请29个人轮流占据自己的床，在八天内按班次持续让床保持有人睡眠。参与者包括亲属，也包括通过面包店、保姆机构和市场等渠道找到的人。MoMA 收藏的完整装置由176张银盐照片与23块文字面板构成，因此睡眠只是素材，真正结构是邀请、轮班、观察、记录、文字与序列。',actions:['邀请亲属、熟人和陌生人进入自己的床。','以八天轮班制度把私人卧室变成临时社会实验场。','持续摄影并记录相遇与时间过程。','将176张照片与23块文字面板组织成长序列。'],sourceUrl:'https://www.moma.org/collection/works/399087',images:[],relations:[rel('收藏','MoMA','完整装置：176 gelatin silver prints + 23 text panels。'),rel('展览','Biennale de Paris','Centre Pompidou资料将1979年的展示视为 Calle 早期重要公开节点。')]}),
project({title:'L’Hôtel — employment as access protocol',cluster:'investigation / hotel / traces / text-photo archive',period:'1981–1983',summary:'Calle 在威尼斯一家酒店找到三周替班女服务员工作，借清扫客房的真实工作权限观察住客留下的衣物、床铺、行李和日常痕迹，以摄影与书面报告建立档案。Centre Pompidou强调其悖论：细节似乎不断揭露陌生人，却仍无法真正掌握对方。职业身份在这里是一套访问协议。',actions:['通过真实受雇取得进入客房的制度性权限。','观察住客暂时离开后的物件与空间状态。','摄影房间与个人痕迹并制作书面报告。','让“知道很多细节却仍不了解此人”成为作品张力。'],sourceUrl:'https://www.centrepompidou.fr/en/ressources/oeuvre/cqr9Md',images:[],relations:[rel('收藏','Centre Pompidou','2000年购藏，多块摄影/文字面板。'),rel('展览','Venice hotel fieldwork','1981年2月16日至3月6日三周替班工作构成现场。')]}),
project({title:'Douleur exquise (Exquisite Pain) — delayed archive and comparative suffering',cluster:'autobiography / archive / heartbreak / repetition',period:'1984 experience; developed later; 2003–04 French version',summary:'作品从1984年的分手经验出发，却没有立即把情绪变成作品。Centre Pompidou指出材料等待约二十年才形成成熟装置：第一部分以92件框装照片、信件和文件重建亚洲旅行及接近分手时刻的过程；第二空间重构新德里酒店房间；后续又通过反复讲述自己的分手并收集他人的痛苦叙事，把私人创伤转换成时间结构、重复机制和比较档案。',actions:['保存旅行照片、信件和文件等生活材料。','让事件与最终作品之间保持多年延迟。','用92件材料制造接近分手时刻的叙事过程。','重构酒店房间，把记忆地点转成展示空间。','以自己的痛苦与他人痛苦形成交换结构。'],sourceUrl:'https://www.centrepompidou.fr/fr/ressources/oeuvre/cdLKEda',images:[],relations:[rel('展览','Sophie Calle. M’as-tu vue','Centre Pompidou 2003–04大型个展的重要作品。'),rel('收藏','Centre Pompidou','官方档案记录三空间结构及92件旅行/通信材料。')]}),
project({title:'Prenez soin de vous (Take Care of Yourself) — delegation as interpretive machine',cluster:'delegation / breakup email / professional knowledge / multimedia',period:'2007',summary:'收到一封以“Take care of yourself”结束的分手邮件后，Calle 把它交给107位女性，依据各自职业与知识系统解释、分析、翻译或表演。La Biennale档案确认该作代表法国参加2007年第52届威尼斯双年展，并由信件、摄影、录像表演、笔记、剪报、乐谱、诗歌等构成。一个两人间的私人信息因此被扩张成107种专业阅读。',actions:['保留分手邮件作为共享原始文本。','选择107位不同职业女性处理同一文本。','让参与者按专业能力解释、翻译、演唱或表演。','并置摄影、录像、文字、乐谱、诗歌等异质结果。','将私人经验扩展成大型协作网络并进入国家馆。'],sourceUrl:'https://asac.labiennale.org/attivita/arti-visive/262917',images:[],relations:[rel('展览','52nd Venice Biennale — French Pavilion','2007法国国家参与项目。'),rel('策展','107 women / professional interpreters','作者结构由 Calle 的规则与107位参与者的解释共同形成。')]})],awards:[],exhibitions:['Biennale de Paris — 1979','Sophie Calle. M’as-tu vue — Centre Pompidou — 2003–04','52nd Venice Biennale, French Pavilion — 2007','Sophie Calle — Centre Pompidou Málaga — 2021–22'],sources:[{label:'MoMA — The Sleepers',url:'https://www.moma.org/collection/works/399087'},{label:'Centre Pompidou — L’Hôtel',url:'https://www.centrepompidou.fr/en/ressources/oeuvre/cqr9Md'},{label:'Centre Pompidou — Douleur exquise',url:'https://www.centrepompidou.fr/fr/ressources/oeuvre/cdLKEda'},{label:'La Biennale ASAC — Prenez soin de vous',url:'https://asac.labiennale.org/attivita/arti-visive/262917'}]}
};
