import type { ArtistArchive, ArchiveImage, ArchiveRelation } from './archiveData';

const img = (url: string, title: string, credit: string, sourceUrl: string, sourceLabel: string): ArchiveImage => ({
  url,
  title,
  credit,
  sourceUrl,
  sourceLabel,
});

const rel = (kind: ArchiveRelation['kind'], label: string, detail?: string): ArchiveRelation => ({
  kind,
  label,
  detail,
});

export const archiveBatch13: Record<string, ArtistArchive> = {
  'aida-muluneh': {
    artistId: 'aida-muluneh',
    projectCoverage: '5 个编排摄影 / 委托 / 文化基础设施节点已完成第一轮 · 2013–2025',
    imageCoverage: '',
    note: '从早期象征性肖像到 Water Life，再到她建立 Addis Foto Fest 的文化生产角色；档案把画面语言和艺术生态建设放在一起。',
    projects: [
      {
        title: 'The 99 Series',
        cluster: 'symbolic portrait / identity',
        period: '2013',
        summary: '以编排肖像、面部彩绘和受控色彩讨论身份、非洲经验与自我观看。',
        actions: ['人物编排', '面部与身体绘画', '服装 / 道具', '系列色彩控制'],
        sourceUrl: 'https://aidamuluneh.com/collections/',
        images: [],
        relations: [],
      },
      {
        title: 'The World is 9',
        cluster: 'memory / future / staged photography',
        period: '2016',
        summary: '系列标题来自祖母关于世界不完整的说法，以二十八幅图像把过去、当下与未来编成象征剧场。',
        actions: ['人物选角', '身体彩绘', '几何化服装与道具', '地点与颜色匹配', '系列编辑'],
        sourceUrl: 'https://aidamuluneh.com/collections/',
        images: [],
        relations: [rel('展览', 'David Krut Projects, New York', '2016')],
      },
      {
        title: 'The Memory of Hope',
        cluster: 'memory / displacement',
        period: '2017',
        summary: '继续使用高度控制的身体与色彩语法处理记忆、迁移和希望之间的不稳定关系。',
        actions: ['编排肖像', '服装造型', '颜色作为叙事结构', '连续组图'],
        sourceUrl: 'https://aidamuluneh.com/collections/',
        images: [],
        relations: [],
      },
      {
        title: 'Water Life',
        cluster: 'water scarcity / commission / women',
        period: '2018',
        summary: '为 WaterAid 与 H&M Foundation 制作的十二幅作品，在 Ethiopia Afar 地区把水资源匮乏转译成身体、容器、管道和颜色的场景。',
        actions: ['现场调研', '在 Dallol 盐地拍摄', '身体彩绘', '制作服装与管道 / 水桶道具', '十二幅系列编辑'],
        sourceUrl: 'https://www.wateraid.org/uk/articles/water-life-the-making-of-aida-mulunehs-striking-photo-series',
        images: [
          img('https://cdn.media.amplience.net/i/canon/canon-pro-aida-muluneh-wateraid-project-8?bg=rgb%28255%2C255%2C255%29&fmt=jpg&fmt.options=interlaced&w=1200', 'Access, Water Life', '© Aïda Muluneh', 'https://www.canon-europe.com/pro/stories/aida-muluneh-wateraid-project/', 'Canon Europe / WaterAid'),
          img('https://images.squarespace-cdn.com/content/v1/5534a426e4b0ed810ce8f891/1569416481059-9567J38BHCK7PB4H20NG/MED164_2500%2Bpx1_HEADER.jpg', 'Water Life — Afar location work', '© Aïda Muluneh', 'https://nataal.com/water-life', 'Nataal / WaterAid project'),
        ],
        relations: [rel('展览', 'Somerset House', '2019'), rel('策展', 'WaterAid commission', '2018')],
      },
      {
        title: 'Addis Foto Fest',
        cluster: 'institution building / African photography',
        period: '2010–',
        summary: '创办并持续推动摄影节，使实践从个人作品扩展到非洲摄影师的展示、教育和跨国网络。',
        actions: ['创办摄影节', '策展', '组织交流与教育项目', '建立国际网络'],
        sourceUrl: 'https://addisfotofest.com/',
        images: [],
        relations: [rel('策展', 'Addis Foto Fest', 'founder / director')],
      },
    ],
    awards: ['European Union Africa Photography Encounters Prize 2010'],
    exhibitions: ['Smithsonian National Museum of African Art', 'Water Life — Somerset House 2019'],
    sources: [
      { label: 'Aïda Muluneh Studio — collections', url: 'https://aidamuluneh.com/collections/' },
      { label: 'WaterAid — Water Life', url: 'https://www.wateraid.org/uk/articles/water-life-the-making-of-aida-mulunehs-striking-photo-series' },
    ],
  },
  'asako-narahashi': {
    artistId: 'asako-narahashi',
    projectCoverage: '5 个摄影书 / 水中景观 / 独立出版节点已完成第一轮 · 1990–2023',
    imageCoverage: '',
    note: '以身体位置为主线：从陆地快照、独立杂志到进入水中拍摄，再回到灾难之后的距离与地景。',
    projects: [
      {
        title: 'NU-E',
        cluster: 'Japanese landscape / uncanny snapshot',
        period: '1990s–1997',
        summary: '早期黑白作品从城市边缘和普通地点寻找难以命名的异样感，并形成首本摄影书。',
        actions: ['黑白快照', '城市与郊外步行', '摄影书编辑'],
        sourceUrl: 'https://thethirdgalleryaya.com/en/artists/narahashi_asako/',
        images: [],
        relations: [rel('出版', 'NU E', 'Sokyusha, 1997')],
      },
      {
        title: 'Funiculi Funicula',
        cluster: 'city / people / color snapshot',
        period: '1998–2003',
        summary: '以彩色快照穿行城市和人群，保留偶然、遮挡与难以稳定命名的日常气氛。',
        actions: ['彩色快照', '城市步行', '不稳定构图', '摄影书 sequence'],
        sourceUrl: 'https://03fotos.com/asako-narahashi/funiculi-funicula/',
        images: [],
        relations: [rel('出版', 'Funiculi Funicula', 'Sokyusha, 2003')],
      },
      {
        title: 'half awake and half asleep in the water',
        cluster: 'water-level landscape / Japan as island',
        period: '2001–2008',
        summary: '身体进入海水或湖水，从水面朝陆地拍熟悉城市、机场和山体，使地景在浪涌中忽近忽远。',
        actions: ['进入水中', '相机贴近水面', '等待浪涌决定前景', '从岸外面向陆地', '彩色 C-print'],
        sourceUrl: 'https://www.sfmoma.org/artist/Asako_Narahashi/',
        images: [
          img('https://static-assets.artlogic.net/w_1200%2Cc_limit%2Cf_auto%2Cfl_lossy%2Cq_auto/ws-ibashogallery/usr/images/exhibitions/main_image_override/55/045.jpg', 'Mount Fuji from the water', '© Asako Narahashi', 'https://ibashogallery.com/artists/65-asako-narahashi/', 'IBASHO Gallery'),
        ],
        relations: [rel('出版', 'half awake and half asleep in the water', 'Nazraeli Press, 2007'), rel('收藏', 'SFMOMA', 'multiple works')],
      },
      {
        title: 'Ever After',
        cluster: 'post-2011 landscape / distance',
        period: '2011–2013',
        summary: '东日本大地震之后暂时离开水中视点，拍摄陆地、过渡地带与受阻的前景，重新处理距离与不安。',
        actions: ['陆地景观摄影', '前景遮挡', '日本与荷兰地点并置', '书籍编辑'],
        sourceUrl: 'https://ibashogallery.com/artists/65-asako-narahashi/',
        images: [],
        relations: [rel('出版', 'Ever After', 'Osiris, 2013')],
      },
      {
        title: '03FOTOS / Main',
        cluster: 'self-organized publishing / exhibition platform',
        period: '1990–2001',
        summary: '开办 03FOTOS 展示空间，并与石内都共同创办摄影杂志 Main，使独立展示与编辑成为实践的一部分。',
        actions: ['自办画廊', '共同编辑杂志', '组织展览', '独立出版'],
        sourceUrl: 'https://www.sfmoma.org/artist/Asako_Narahashi/',
        images: [],
        relations: [rel('策展', '03FOTOS', '1990–2001'), rel('出版', 'Main magazine', '1996–2000')],
      },
    ],
    awards: ['Photography Society of Japan Newcomer Award 1998', 'Higashikawa New Photographer Award 2008'],
    exhibitions: ['Yossi Milo Gallery 2008', 'Tokyo Art Museum 2009', 'Images Vevey 2016'],
    sources: [
      { label: 'SFMOMA artist archive', url: 'https://www.sfmoma.org/artist/Asako_Narahashi/' },
      { label: 'Asako Narahashi / 03FOTOS', url: 'https://03fotos.com/asako-narahashi/' },
    ],
  },
  'kikuji-kawada': {
    artistId: 'kikuji-kawada',
    projectCoverage: '5 个摄影书 / 都市时间 / 天象节点已完成第一轮 · 1959–现在',
    imageCoverage: '',
    note: '以《地图》为核心但不把他停在1965年：继续追踪摄影书设计、都市符号、天象与长期日记式拍摄。',
    projects: [
      {
        title: 'Chizu / The Map',
        cluster: 'Hiroshima / war memory / photobook',
        period: '1959–1965',
        summary: '原爆圆顶馆污迹、战时遗物、堡垒、国旗与消费垃圾被压进高反差摄影书，历史作为物质表面出现。',
        actions: ['拍摄建筑污迹与遗物', '黑白高反差放大', '跨类型图像搜集', '与杉浦康平合作折页 / 版式', '摄影书 sequence'],
        sourceUrl: 'https://www.mfa.org/exhibition/kawada-kikuji-chizu-the-map',
        images: [
          img('https://d1hhug17qm51in.cloudfront.net/www-media/2018/08/25113730/2002.65.10_01_b02-Large-TIFF_4000-pixels-long-scaled.jpg', 'Hinomaru — The Japanese National Flag', '© Kikuji Kawada', 'https://www.sfmoma.org/artwork/2002.65.10/', 'SFMOMA'),
          img('https://cphmag.com/-/2021/11/Chizu02.jpg', 'The Map — photobook spread', '© Kikuji Kawada', 'https://cphmag.com/map-story/', 'Conscientious Photography Magazine'),
        ],
        relations: [rel('出版', 'Chizu / The Map', 'Bijutsu Shuppan-sha, 1965'), rel('收藏', 'MFA Boston', 'The Map archive acquired 2022')],
      },
      {
        title: 'The Last Cosmology',
        cluster: 'astronomy / private cosmology',
        period: '1979–1997',
        summary: '日食、彗星、云、月与城市光被组织为个人宇宙观，天象和日常观看互相进入。',
        actions: ['长期观察天象', '夜间摄影', '暗房放大', '跨年代 sequence'],
        sourceUrl: 'https://www.pgi.ac/en/artists/154/',
        images: [],
        relations: [rel('出版', 'The Last Cosmology', 'MACK, 2015')],
      },
      {
        title: 'The Globe Theater',
        cluster: 'city / spectacle / signs',
        period: '1990s',
        summary: '都市橱窗、雕像、广告和反射被拍成舞台，现实空间显得像不断更换布景的剧场。',
        actions: ['街头观察', '反射与橱窗摄影', '彩色 / 黑白图像编辑'],
        sourceUrl: 'https://www.pgi.ac/en/artists/154/',
        images: [],
        relations: [],
      },
      {
        title: 'World’s End',
        cluster: 'millennium / urban signs',
        period: '1990s–2000s',
        summary: '在世纪转换前后收集城市、新闻与天空中的不祥符号，延续他把历史读成表面痕迹的方法。',
        actions: ['跨城市拍摄', '标志与天象搜集', '时间性编辑'],
        sourceUrl: 'https://www.pgi.ac/en/artists/154/',
        images: [],
        relations: [],
      },
      {
        title: 'Los Caprichos / Last Things',
        cluster: 'ongoing diary / contemporary omen',
        period: '2010s–现在',
        summary: '以持续更新的日记式摄影回应政治、灾难、天空和都市碎片，旧照片与新图像不断重组。',
        actions: ['日常持续拍摄', '旧档案重编', '社交媒体 / 出版流通', '开放式 sequence'],
        sourceUrl: 'https://www.pgi.ac/en/artists/154/',
        images: [],
        relations: [],
      },
    ],
    awards: ['Higashikawa Domestic Photographer Award 2011'],
    exhibitions: ['Kawada Kikuji: Chizu — MFA Boston 2023'],
    sources: [
      { label: 'MFA Boston — Chizu', url: 'https://www.mfa.org/exhibition/kawada-kikuji-chizu-the-map' },
      { label: 'PGI artist archive', url: 'https://www.pgi.ac/en/artists/154/' },
    ],
  },
  'yinka-shonibare': {
    artistId: 'yinka-shonibare',
    projectCoverage: '5 个历史重演 / 图书馆 / 殖民档案节点已完成第一轮 · 1998–2018',
    imageCoverage: '',
    note: '重点拆出“历史图像—人体模型—蜡染布—空间装置”的转换，同时补入图书馆作品如何把命名和数据库变成观看动作。',
    projects: [
      {
        title: 'Diary of a Victorian Dandy',
        cluster: 'staged photography / art-historical tableau',
        period: '1998',
        summary: '艺术家本人扮演维多利亚时代 dandy，以五幅大型编排照片穿行一天中的权力、服务与欲望场景。',
        actions: ['艺术史与社会史研究', '大型人物选角', '服装 / 室内布景', '自我表演', '五幅时间序列'],
        sourceUrl: 'https://yinkashonibare.com/artwork/diary-of-a-victorian-dandy-1998/',
        images: [],
        relations: [],
      },
      {
        title: 'The Swing (after Fragonard)',
        cluster: 'Rococo remake / mannequin / colonial trade',
        period: '2001',
        summary: '把 Fragonard 绘画转成可进入的等身雕塑场景，无头人物穿荷兰蜡染布服装悬在人工花园中。',
        actions: ['经典绘画重演', '制作玻璃钢人体模型', '蜡染布裁制服装', '秋千与人工植物搭建'],
        sourceUrl: 'https://yinkashonibare.com/artwork/the-swing-after-fragonard-2001/',
        images: [
          img('https://cdn.kastatic.org/ka-perseus-images/b4d59520442a9b606fcbee9a274b3f8236694679.jpg', 'The Swing (after Fragonard)', '© Yinka Shonibare', 'https://yinkashonibare.com/artwork/the-swing-after-fragonard-2001/', 'Artist website / installation documentation'),
        ],
        relations: [rel('收藏', 'Tate', 'collection')],
      },
      {
        title: 'Scramble for Africa',
        cluster: 'Berlin Conference / historical tableau',
        period: '2003',
        summary: '十四个无头人体模型围桌重演1884–85年柏林会议，殖民者的服装全部由跨文化贸易的蜡染布制作。',
        actions: ['历史会议研究', '十四个等身模型', '会议桌与椅搭建', '蜡染服装制作', '群体姿势编排'],
        sourceUrl: 'https://yinkashonibare.com/artwork/scramble-for-africa-2003/',
        images: [],
        relations: [rel('策展', 'Museum of African Art commission', '2003')],
      },
      {
        title: 'Nelson’s Ship in a Bottle',
        cluster: 'public art / empire / maritime trade',
        period: '2010',
        summary: '把 HMS Victory 制成大型瓶中船，帆面改用蜡染纹样，将海军胜利、贸易网络与公共纪念物并置。',
        actions: ['船模制作', '蜡染帆面', '透明瓶体', '公共场地尺度调整'],
        sourceUrl: 'https://yinkashonibare.com/artwork/nelsons-ship-in-a-bottle-2010/',
        images: [],
        relations: [rel('展览', 'Fourth Plinth, Trafalgar Square', '2010'), rel('收藏', 'National Maritime Museum', 'collection')],
      },
      {
        title: 'The British Library / The American Library',
        cluster: 'migration / names / participatory archive',
        period: '2014–2018',
        summary: '数千本硬皮书以蜡染布包裹，书脊烫印移民及其后代姓名，并通过平板与网站把雕塑连接到可查询档案。',
        actions: ['搜集姓名与传记', '数千本书包覆蜡染布', '书脊金箔压字', '书架空间设计', '网站 / 平板交互'],
        sourceUrl: 'https://yinkashonibare.com/artwork/the-british-library-2014/',
        images: [
          img('https://sothebys-com.brightspotcdn.com/96/9a/1d675850494c9af80f224f524dd7/yinka-shonibare.jpg', 'The American Library — installation', '© Yinka Shonibare', 'https://yinkashonibare.com/artwork/the-american-library-2018/', 'Artist website / museum documentation'),
        ],
        relations: [rel('收藏', 'Tate', 'The British Library'), rel('展览', 'FRONT International / Cleveland Public Library', 'The American Library, 2018')],
      },
    ],
    awards: ['Turner Prize 2004 — shortlisted', 'CBE 2019'],
    exhibitions: ['documenta 11 — 2002', 'Venice Biennale African Pavilion — 2007', 'Fourth Plinth — 2010'],
    sources: [
      { label: 'Yinka Shonibare Studio — artworks', url: 'https://yinkashonibare.com/' },
      { label: 'Tate collection', url: 'https://www.tate.org.uk/art/artists/yinka-shonibare-cbe-1928' },
    ],
  },
};
