import type { ArtistArchive, ArchiveImage, ArchiveRelation } from './archiveData';

const img = (url: string, title: string, credit: string, sourceUrl: string, sourceLabel: string): ArchiveImage => ({ url, title, credit, sourceUrl, sourceLabel });
const rel = (kind: ArchiveRelation['kind'], label: string, detail?: string): ArchiveRelation => ({ kind, label, detail });

export const circuitArtistArchives2: Record<string, ArtistArchive> = {
  'jeremy-deller': {
    artistId: 'jeremy-deller', projectCoverage: '5 个关键项目已完成第一轮 · 1997–2013', imageCoverage: '',
    note: 'Deller 的 oeuvre 包含大量一次性事件、合作、电影、出版和公共项目。这里先把决定其方法与 Turner / Venice 路径的五个核心项目做深，后续继续补 Procession、Folk Archive、Everybody in the Place 等。',
    projects: [
      { title: 'Acid Brass', cluster: 'music / class / collaboration', period: '1997', summary: '把 acid house / rave 曲目改编给英国铜管乐队演奏，使两种工人阶级文化在真实表演中碰面。', actions: ['选择 rave 曲目', '委托铜管改编', '现场演出', '关系图 / 出版'], sourceUrl: 'https://www.themoderninstitute.com/artists/jeremy-deller', images: [], relations: [] },
      { title: 'The Battle of Orgreave', cluster: 'reenactment / labour history', period: '2001', summary: '约千人重演 1984 年矿工罢工中 Orgreave 冲突，并把仍在世的矿工、警察和 reenactment societies 放进同一个再演现场。', actions: ['历史研究', '组织约千人参与', '现场重演', '电影记录', '口述史'], sourceUrl: 'https://publicdelivery.org/jeremy-deller-the-battle-of-orgreave/', images: [img('https://publicdelivery.org/wp-content/uploads/2013/07/jeremy-deller-the-battle-of-orgreave-31.jpg', 'The Battle of Orgreave', '© Jeremy Deller / Martin Jenkinson', 'https://publicdelivery.org/jeremy-deller-the-battle-of-orgreave/', 'Public Delivery')], relations: [rel('策展', 'Artangel commission', '2001')] },
      { title: 'It Is What It Is', cluster: 'Iraq / public conversation', period: '2009', summary: '把伊拉克被炸毁汽车拖行美国，邀请伊拉克公民、美国退伍军人与公众持续对话。', actions: ['运输战争物件', '跨州 road trip', '公众讨论', '影像 / 文件'], sourceUrl: 'https://www.themoderninstitute.com/artists/jeremy-deller/about/', images: [], relations: [rel('展览', 'New Museum / Creative Time', '2009')] },
      { title: 'Sacrilege', cluster: 'heritage / public participation', period: '2012', summary: '真人尺度充气 Stonehenge 在英国各地巡回，观众可以直接进入和跳跃。', actions: ['充气结构设计', '巡回公共空间', '观众参与'], sourceUrl: 'https://www.themoderninstitute.com/artists/jeremy-deller/exhibitions/6-the-modern-institute-osborne-street2014-09-13/22/', images: [], relations: [rel('策展', 'Glasgow International + Mayor of London co-commission', '2012')] },
      { title: 'English Magic', cluster: 'British Pavilion / national self-image', period: '2013', summary: '电影、壁画、横幅和物件共同处理英国阶级、财富、军事、自然和流行文化。', actions: ['全馆展览设计', '电影', '委托壁画', 'Ed Hall 横幅', '音乐录制'], sourceUrl: 'https://www.themoderninstitute.com/artists/jeremy-deller/exhibitions/english-magic-british-pavillion-giardini-de-castello-30122-venice-biennale-venice-2013-06-01/621/', images: [img('https://www.themoderninstitute.com/img/66d88b79cd9db-large.jpg', 'I searched for form and land; For years and years I roamed', '© Jeremy Deller / Ed Hall', 'https://www.themoderninstitute.com/artists/jeremy-deller/works/i-searched-for-form-and-land-for-years-and-years-i-roamed-2013/1821/', 'The Modern Institute')], relations: [rel('展览', 'British Pavilion, Venice Biennale', '2013'), rel('出版', 'English Magic', 'British Council, 2013')] }
    ],
    awards: ['Turner Prize 2004 — winner'], exhibitions: ['British Pavilion — Venice Biennale 2013', 'Joy in People — Hayward Gallery 2012', 'Skulptur Projekte Münster 2017'], sources: [{ label: 'The Modern Institute — works / exhibitions', url: 'https://www.themoderninstitute.com/artists/jeremy-deller' }, { label: 'British Council — English Magic', url: 'https://www.britishcouncil.org/contact/press/jeremy-deller-english-magic' }]
  },
  'helen-marten': {
    artistId: 'helen-marten', projectCoverage: '4 个关键作品 / 展览节点已索引 · 2012–2016', imageCoverage: '', note: '第一轮围绕 Venice 2015 与 Turner Prize 2016 前后的关键作品建立材料谱系，后续继续按 Sadie Coles 作品目录补 2020s 项目和单件雕塑。',
    projects: [
      { title: 'No Borders in a Wok that Can’t Be Crossed', cluster: 'assemblage / object language', period: '2012', summary: '消费物件、机械和手工材料被组合成难以稳定命名的雕塑系统。', actions: ['现成物重组', '定制部件', '雕塑 assemblage'], sourceUrl: 'https://www.sadiecoles.com/artists/helen-marten/', images: [], relations: [] },
      { title: 'Lunar Nibs', cluster: 'Venice / material syntax', period: '2015', summary: '木、钢、陶瓷、橡胶、织物、鞋底等多种材料共同组成复杂的多部件结构。', actions: ['材料组合', '定制陶瓷', '金属 / 木加工', '空间编排'], sourceUrl: 'https://www.sadiecoles.com/artists/helen-marten/', images: [img('https://static.a-n.co.uk/wp-content/uploads/2016/03/FENT__1458544342_HQ18-HM11169S_Lunar_Nibs_01.jpg', 'Lunar Nibs', '© Helen Marten / Annik Wetter', 'https://www.a-n.co.uk/media/52443786/', 'a-n')], relations: [rel('展览', '56th Venice Biennale', '2015')] },
      { title: 'Drunk Brown House', cluster: 'house / unstable utility', period: '2015', summary: '建筑、家具、容器和半功能物件被压成类似工作台与住宅之间的环境。', actions: ['模型 / 家具', '现成物', '空间安装'], sourceUrl: 'https://www.sadiecoles.com/artists/helen-marten/', images: [], relations: [] },
      { title: 'Eucalyptus, Let Us In', cluster: 'Turner Prize', period: '2016', summary: 'Turner Prize 展场把雕塑、墙面图像和桌面 assemblage 组成一个信息密度极高的整体。', actions: ['雕塑', '绘画 / 图像', '展场编排'], sourceUrl: 'https://www.sadiecoles.com/artists/helen-marten/', images: [img('https://news.artnet.com/app/news-upload/2016/09/Helen-Marten-2016-1.jpg', 'Turner Prize 2016 — installation', '© Helen Marten', 'https://news.artnet.com/art-world/turner-prize-2016-exhibition-review-671120', 'Artnet News')], relations: [rel('奖项', 'Turner Prize', 'winner 2016'), rel('奖项', 'Hepworth Prize for Sculpture', 'winner 2016')] }
    ], awards: ['Turner Prize 2016 — winner', 'Hepworth Prize for Sculpture 2016 — winner'], exhibitions: ['56th Venice Biennale 2015', 'Turner Prize — Tate Britain 2016'], sources: [{ label: 'Sadie Coles HQ', url: 'https://www.sadiecoles.com/artists/helen-marten/' }]
  },
  'charlotte-prodger': {
    artistId: 'charlotte-prodger', projectCoverage: '4 个核心录像 / 展览节点已索引 · 2015–2019', imageCoverage: '', note: '重点先做 Stoneymollan Trail → BRIDGIT → SaF05 三部曲及 Subtotal 展览，后续继续补早期声音/雕塑和后续录像。',
    projects: [
      { title: 'Stoneymollan Trail', cluster: 'autobiographical trilogy I', period: '2015', summary: '通过地名、旅行、录像设备和私人叙述开始建立三部曲的自传地理。', actions: ['location video', 'voice-over', '多设备素材'], sourceUrl: 'https://scotlandandvenice.com/project/charlotte-prodger/', images: [], relations: [] },
      { title: 'BRIDGIT', cluster: 'autobiographical trilogy II', period: '2016', summary: '大量智能手机素材与 voice-over 连接 queer history、地质、亲密关系和命名。', actions: ['iPhone 摄影', 'voice-over', '声音编辑', '单频道放映'], sourceUrl: 'https://scotlandandvenice.com/project/charlotte-prodger/', images: [img('https://dailyartfair.com/upload/large/5727_5-Charlotte-Prodger-Hollybush-Gardens.jpg', 'BRIDGIT', '© Charlotte Prodger', 'https://dailyartfair.com/exhibition/5727/charlotte-prodger-hollybush-gardens', 'Hollybush Gardens / Daily Art Fair')], relations: [rel('奖项', 'Turner Prize', 'winner 2018')] },
      { title: 'Subtotal', cluster: 'survey / spatial video', period: '2017', summary: 'SculptureCenter 个展把多件录像与建筑、座椅和声音设备重新组织。', actions: ['录像选编', '屏幕 / 音箱布置', '展场空间'], sourceUrl: 'https://www.artsy.net/show/sculpturecenter-charlotte-prodger-subtotal', images: [img('https://d7hftxdivxxvm.cloudfront.net/?height=900&quality=80&resize_to=fill&src=https%3A%2F%2Fd32dm0rphc51dk.cloudfront.net%2FyK1-SfvypVdYnuEPgggJNg%2Flarger.jpg&width=1200', 'Subtotal', '© Charlotte Prodger', 'https://www.artsy.net/show/sculpturecenter-charlotte-prodger-subtotal', 'SculptureCenter / Artsy')], relations: [] },
      { title: 'SaF05', cluster: 'autobiographical trilogy III / Venice', period: '2019', summary: 'camera trap 中的长鬃母狮、手机/电影机/drone 影像和自传 voice-over共同处理 queer attachment、领地与时间。', actions: ['camera trap archive', 'drone', 'smartphone', 'film camera', 'voice-over'], sourceUrl: 'https://scotlandandvenice.com/project/charlotte-prodger/', images: [], relations: [rel('展览', 'Scotland + Venice official Collateral Event', '58th Venice Biennale 2019')] }
    ], awards: ['Turner Prize 2018 — winner'], exhibitions: ['Bergen Kunsthall — BRIDGIT / Stoneymollan Trail', 'SculptureCenter — Subtotal 2017', 'Scotland + Venice — SaF05 2019'], sources: [{ label: 'Scotland + Venice — SaF05', url: 'https://scotlandandvenice.com/project/charlotte-prodger/' }]
  },
  'lawrence-abu-hamdan': {
    artistId: 'lawrence-abu-hamdan', projectCoverage: '5 个核心声音 / 调查项目已索引 · 2012–现在', imageCoverage: '', note: '第一轮聚焦口音分类、Earshot、Saydnaya、Walled Unwalled 与 Earwitness Inventory；后续继续补 45th Parallel、Air Pressure 等近年调查。',
    projects: [
      { title: 'The Freedom of Speech Itself', cluster: 'accent / border technology', period: '2012', summary: '研究 asylum procedures 中如何通过口音分析判断申请者来源。', actions: ['语音档案研究', '声学分析', '影像 / 装置'], sourceUrl: 'https://lawrenceabuhamdan.com/', images: [], relations: [] },
      { title: 'Earshot', cluster: 'forensic listening', period: '2016', summary: '通过枪声声学分析调查两名巴勒斯坦青少年遭枪击案件中的弹药争议。', actions: ['field recording 分析', '弹道声音比对', '证据可视化'], sourceUrl: 'https://lawrenceabuhamdan.com/', images: [img('https://www.dreamideamachine.com/web/wp-content/uploads/2018/09/02.-Lawrence-Abu-Hamdan_Earshot_2016-1618x1080.jpg', 'Earshot', '© Lawrence Abu Hamdan', 'https://www.dreamideamachine.com/?p=40205', 'Dream Idea Machine')], relations: [] },
      { title: 'Saydnaya / The Missing 19db', cluster: 'prison / earwitness', period: '2016', summary: '与幸存者合作通过声音记忆重建无法拍摄的叙利亚监狱环境。', actions: ['幸存者访谈', '声音重演', '声压差研究'], sourceUrl: 'https://lawrenceabuhamdan.com/', images: [], relations: [rel('策展', 'with Amnesty International / Forensic Architecture research context')] },
      { title: 'Walled Unwalled', cluster: 'wall / legal evidence', period: '2018', summary: '在前冷战监听录音棚中讲述通过墙壁获得声学证据的法律案件。', actions: ['法律案例研究', 'performance-to-camera', '录音棚场景', '玻璃投影结构'], sourceUrl: 'https://ocula.com/magazine/conversations/lawrence-abu-hamdan/', images: [img('https://files.ocula.com/anzax/Content/Conversations/Abu%20Hamdan/WalledUnwalled2018LawrenceAbuHamdanAbraajGroupArtPrizeWinner2018CourtesyofPhotoSolutions_1200_0.jpg', 'Walled Unwalled', '© Lawrence Abu Hamdan', 'https://ocula.com/magazine/conversations/lawrence-abu-hamdan/', 'Ocula')], relations: [rel('奖项', 'Abraaj Group Art Prize', '2018'), rel('展览', 'Tate Modern', '2018'), rel('展览', '58th Venice Biennale', '2019')] },
      { title: 'Earwitness Inventory / After SFX', cluster: 'sonic object archive', period: '2018–', summary: '根据证词中描述声音的方式寻找和制造 95 类声音物件，建立可听的法证词典。', actions: ['证词整理', '物件搜集 / 定制', '声音录制', '档案展示'], sourceUrl: 'https://lawrenceabuhamdan.com/', images: [], relations: [rel('展览', 'Earwitness Theatre, Chisenhale Gallery', '2018'), rel('奖项', 'Turner Prize', 'joint winner 2019')] }
    ], awards: ['Turner Prize 2019 — joint winner', 'Abraaj Group Art Prize 2018'], exhibitions: ['Tate Modern — Walled Unwalled 2018', '58th Venice Biennale 2019', 'Turner Prize — Turner Contemporary 2019'], sources: [{ label: 'Artist website', url: 'https://lawrenceabuhamdan.com/' }, { label: 'Venice / Turner context', url: 'https://www.theartnewspaper.com/2019/06/14/interview-lawrence-abu-hamdana-self-styled-private-ear' }]
  },
  'tai-shani': {
    artistId: 'tai-shani', projectCoverage: '4 个核心世界建构项目已索引 · 2014–现在', imageCoverage: '', note: '第一轮覆盖 DC: Semiramis 到 The Neon Hieroglyph 的主要阶段；后续继续补表演章节、出版与 2020s 新作。',
    projects: [
      { title: 'DC: Semiramis', cluster: 'feminist world-building', period: '2014–19', summary: '从 Christine de Pizan 的女性之城发展多角色、雕塑、表演和文本构成的长期后父权世界。', actions: ['角色写作', '雕塑布景', '现场表演', '影像'], sourceUrl: 'https://www.rca.ac.uk/more/staff/tai-shani/', images: [img('https://rca-media2.rca.ac.uk/images/00_tai-shani-dc-semiramis-2019-ins.2ef68361.fill-880x660.png', 'DC: Semiramis', '© Tai Shani', 'https://www.rca.ac.uk/news-and-events/news/turner-prize-2019-rca-staff-and-alumni-create-bold-commentary-on-turbulent-times/', 'Royal College of Art')], relations: [rel('奖项', 'Turner Prize', 'joint winner 2019')] },
      { title: 'Our Fatal Magic', cluster: 'writing / world extension', period: '2019', summary: '把 DC: Semiramis 的角色与语气推进为独立写作。', actions: ['小说 / 文本', '世界设定'], sourceUrl: 'https://www.rca.ac.uk/more/staff/tai-shani/', images: [], relations: [rel('出版', 'Our Fatal Magic', '2019')] },
      { title: 'The Neon Hieroglyph', cluster: 'ergot / hallucination / ecology', period: '2021', summary: '五部影像、声音和雕塑把 ergot fungus、历史集体幻觉与生态危机连接。', actions: ['五部影片', '沉浸式布景', '声音', '雕塑'], sourceUrl: 'https://www.somersethouse.org.uk/whats-on/tai-shani-the-neon-hieroglyph', images: [img('https://media.somersethouse.org.uk/images/Installation_view_of_Tai_Shanis_The_Neon_Heiro.width-800_uCuKKcoBYUmv9ryE.jpg', 'The Neon Hieroglyph', '© Tai Shani', 'https://www.somersethouse.org.uk/whats-on/tai-shani-the-neon-hieroglyph', 'Somerset House')], relations: [rel('展览', 'Somerset House', '2021')] },
      { title: 'The Blue Figure', cluster: 'later world-building', period: '2023–', summary: '以蓝色身体、死亡、政治想象与绘画/装置继续发展其后父权世界。', actions: ['绘画', '雕塑', '文本', '装置'], sourceUrl: 'https://www.rca.ac.uk/more/staff/tai-shani/', images: [], relations: [] }
    ], awards: ['Turner Prize 2019 — joint winner'], exhibitions: ['Turner Prize — Turner Contemporary 2019', 'The Neon Hieroglyph — Somerset House 2021'], sources: [{ label: 'Royal College of Art profile', url: 'https://www.rca.ac.uk/more/staff/tai-shani/' }]
  },
  'tacita-dean': {
    artistId: 'tacita-dean', projectCoverage: '5 个关键胶片 / 舞台项目已索引 · 1996–2018', imageCoverage: '', note: 'Dean 的 filmography、drawing 与 print oeuvre 很大；第一轮先以 Disappearance at Sea、Banewl、FILM、Event for a Stage、Antigone 建立媒介方法谱系。',
    projects: [
      { title: 'Disappearance at Sea', cluster: 'sea / disappearance / film', period: '1996', summary: '从 Donald Crowhurst 的海上失踪故事出发，以灯塔和海岸空间建立极少叙事的16mm电影。', actions: ['16mm 拍摄', 'location light', 'optical sound'], sourceUrl: 'https://www.mariangoodman.com/artists/39-tacita-dean/works/39446/', images: [img('https://static-assets.artlogic.net/w_1680%2Ch_1680%2Cc_limit%2Cf_auto%2Cfl_lossy%2Cq_auto/artlogicstorage/mariangoodman/images/view/944ee30632d0d6d1155e77d570b82aeaj.jpg', 'Disappearance at Sea', '© Tacita Dean', 'https://www.mariangoodman.com/artists/39-tacita-dean/works/39446/', 'Marian Goodman')], relations: [] },
      { title: 'Banewl', cluster: 'eclipse / duration / chance', period: '1999', summary: '以真实日食当天的农场为现场，让天气、等待和偶然进入胶片。', actions: ['长时段16mm拍摄', '自然光', '保留偶发事件'], sourceUrl: 'https://www.mariangoodman.com/artists/39-tacita-dean/', images: [], relations: [] },
      { title: 'FILM', cluster: 'Turbine Hall / analogue film', period: '2011', summary: '为 Tate Modern Turbine Hall 制作巨型垂直35mm投影，直接回应建筑和数字化时代。', actions: ['35mm胶片', 'masking / exposure effects', '垂直投影', '场域设计'], sourceUrl: 'https://www.tate.org.uk/whats-on/tate-modern/tacita-dean-film', images: [], relations: [rel('策展', 'Unilever Series, Tate Modern', '2011')] },
      { title: 'Event for a Stage', cluster: 'theatre / camera / role', period: '2014', summary: '剧场演员在文本、角色、观众和摄影机之间反复切换。', actions: ['剧场表演', '现场摄影', '文本', '后续 film version'], sourceUrl: 'https://www.mariangoodman.com/artists/39-tacita-dean/', images: [], relations: [] },
      { title: 'Antigone', cluster: '35mm double projection / myth', period: '2018', summary: '双幅 anamorphic 35mm film 使用多重曝光和物理遮罩，把神话、风景和胶片工艺并列。', actions: ['35mm anamorphic', 'multiple exposure', 'masking', '双画面放映'], sourceUrl: 'https://www.frithstreetgallery.com/artworks/18315-tacita-dean-antigone-2018/', images: [img('https://static-assets.artlogic.net/w_1600%2Ch_1600%2Cc_limit%2Cf_auto%2Cfl_lossy%2Cq_auto/artlogicstorage/frithstreetgallery/images/view/031548a5dd2b12ac111b6dae3570d36dj/frithstreetgallery-tacita-dean-antigone-2018.jpg', 'Antigone', '© Tacita Dean', 'https://www.frithstreetgallery.com/artworks/18315-tacita-dean-antigone-2018/', 'Frith Street Gallery')], relations: [] }
    ], awards: ['Turner Prize 1998 — nominee', 'Hugo Boss Prize 2006', 'Benesse Prize 2005'], exhibitions: ['Tate Modern Turbine Hall — FILM 2011', 'Royal Academy / National Gallery / National Portrait Gallery trilogy 2018'], sources: [{ label: 'Marian Goodman artist archive', url: 'https://www.mariangoodman.com/artists/39-tacita-dean/' }]
  },
  'isaac-julien': {
    artistId: 'isaac-julien', projectCoverage: '5 个核心多屏项目已索引 · 1989–2022', imageCoverage: '', note: '先覆盖黑人酷儿历史、迁移、中国劳工、Frederick Douglass 与博物馆殖民史五条关键线；后续继续补 Young Soul Rebels、Baltimore 等 filmography。',
    projects: [
      { title: 'Looking for Langston', cluster: 'Black queer history', period: '1989', summary: '通过编排场景、档案和诗歌重想 Harlem Renaissance 的黑人酷儿欲望。', actions: ['黑白电影', '档案挪用', '编排表演', '诗歌声音'], sourceUrl: 'https://www.isaacjulien.com/', images: [], relations: [rel('收藏', 'MoMA', 'collection context')] },
      { title: 'Western Union: Small Boats', cluster: 'migration / Mediterranean', period: '2007', summary: '地中海迁移史和高度美学化的海岸影像并置。', actions: ['location film', 'multi-screen installation', '编排表演'], sourceUrl: 'https://www.isaacjulien.com/', images: [], relations: [] },
      { title: 'Ten Thousand Waves', cluster: 'Chinese migration / memory', period: '2010', summary: '从 Morecambe Bay 中国拾贝工人死亡事件出发，把中国神话、电影、当代城市和迁移历史组织成九屏作品。', actions: ['九屏拍摄 / 剪辑', '跨国拍摄', '演员重演', '档案'], sourceUrl: 'https://www.isaacjulien.com/', images: [img('https://www.domusweb.it/content/dam/domusweb/en/art/2012/02/09/ten-thousand-waves/big_373862_4615_02_web_3-TEN-THOUSAND-WAVES1.jpg.foto.rmedium.jpg', 'Ten Thousand Waves', '© Isaac Julien', 'https://www.domusweb.it/en/art/2012/02/09/ten-thousand-waves.html', 'Domus')], relations: [rel('收藏', 'MoMA', 'work in collection')] },
      { title: 'Lessons of the Hour', cluster: 'Frederick Douglass / photography / abolition', period: '2019', summary: '十屏重演 Douglass 的演说、肖像和旅行，同时研究19世纪摄影如何参与塑造公众人物。', actions: ['十屏影像', '历史重演', '档案研究', '声音'], sourceUrl: 'https://americanart.si.edu/artwork/lessons-hour-120652', images: [img('https://ids.si.edu/ids/deliveryService?id=SAAM-2023.42_3&max=640', 'Lessons of the Hour', '© Isaac Julien', 'https://americanart.si.edu/artwork/lessons-hour-120652', 'Smithsonian American Art Museum')], relations: [rel('展览', 'MoMA', '2024')] },
      {
        title: 'Once Again… (Statues Never Die)',
        cluster: '五屏影像 / 雕塑 / 收藏史',
        period: '2022；2024 惠特尼展出',
        summary: '以 Alain Locke 与 Albert Barnes 的对话，重新讨论非洲艺术收藏与黑人现代主义的解释权。',
        actions: [
          '由演员重演 Locke 与 Barnes 的交往及辩论。',
          '将叙事分配到五块屏幕，并与 Richmond Barthé 和 Matthew Angelo Harrison 的雕塑形成对话。',
          '通过声音和多屏编排，连接博物馆、艺术家遗产与酷儿欲望。'
        ],
        sourceUrl: 'https://whitney.org/exhibitions/2024-biennial/art?section=24',
        images: [
          {
            url: 'https://whitneymedia.org/assets/image/830045/large_RS78206_Copy-of-Iolaus-_In-the-Life-_Once-Again...-Statues-Never-Die__web.jpg',
            title: 'Iolaus/In the Life, 2022 · 与影像项目相关的喷墨摄影作品',
            credit: '© Isaac Julien / Courtesy the artist and Victoria Miro',
            sourceUrl: 'https://whitney.org/exhibitions/2024-biennial/art?section=24',
            sourceLabel: 'Whitney Museum of American Art'
          }
        ],
        relations: [
          {
            kind: '展览',
            label: 'Whitney Biennial',
            detail: '2024 · Even Better Than the Real Thing'
          }
        ]
      }
    ], awards: ['Turner Prize 2001 — nominee'], exhibitions: ['Tate Britain — What Freedom Is to Me 2023', 'MoMA — Lessons of the Hour 2024'], sources: [{ label: 'Isaac Julien Studio', url: 'https://www.isaacjulien.com/' }, { label: 'MoMA artist archive', url: 'https://www.moma.org/artists/2920-isaac-julien' }]
  },
  'zoe-leonard': {
    artistId: 'zoe-leonard', projectCoverage: '4 个长期作品群已索引 · 1992–2022', imageCoverage: '', note: '第一轮覆盖哀悼物件、412张 Analogue、明信片复制景观和边境河流；后续继续补 early aerial views、camera obscura 等作品。',
    projects: [
      { title: 'Strange Fruit', cluster: 'AIDS / mourning / repair', period: '1992–97', summary: '吃剩果皮被缝合、固定并允许继续腐败，把照护与不可逆失去同时物质化。', actions: ['收集果皮', '缝合 / 金属固定', '地面安装', '自然腐败'], sourceUrl: 'https://contemporary.burlington.org.uk/journal/journal/intent-in-the-making-the-life-of-zoe-leonards-strange-fruit', images: [img('https://burlington.org.uk/media/w1200/bc_general/quabeck-strangefruit-fig01.jpg?auto=format&fit=crop&ixid=eyJhcHBfaWQiOjEyMDd9&ixlib=rb-0.3.5&q=80&s=3566466d76117e29ffb4160a639748fb&w=1502', 'Strange Fruit', '© Zoe Leonard', 'https://contemporary.burlington.org.uk/journal/journal/intent-in-the-making-the-life-of-zoe-leonards-strange-fruit', 'Burlington Contemporary')], relations: [] },
      { title: 'Analogue', cluster: 'urban change / global circulation / analogue photography', period: '1998–2009', summary: '412张照片分25章，从纽约小店一路追踪旧货和图像在全球市场再流通。', actions: ['Rolleiflex 模拟摄影', '十年长期拍摄', '跨国追踪商品', '网格 / 章节编排'], sourceUrl: 'https://www.moma.org/collection/works/171309', images: [], relations: [rel('收藏', 'MoMA', '412 photographs / full installation'), rel('展览', 'Zoe Leonard: Analogue, MoMA', '2015')] },
      { title: 'You see I am here after all', cluster: 'postcard / mass image', period: '2008', summary: '数千张 Niagara Falls 明信片占据长墙，重复景观变成大众图像生产史。', actions: ['明信片收集', '分类', '超长墙面编排'], sourceUrl: 'https://www.girlfriendfund.org/exhibitions/zoe-leonard-exhibition', images: [img('https://images.squarespace-cdn.com/content/v1/68d15644d62f4574834551a4/ab62d869-6fb5-49a3-878a-e533517406d0/Screenshot%2B2025-10-02%2Bat%2B9.57.21%E2%80%AFAM.png', 'You see I am here after all', '© Zoe Leonard', 'https://www.girlfriendfund.org/exhibitions/zoe-leonard-exhibition', 'Exhibition documentation')], relations: [] },
      { title: 'Al río / To the River', cluster: 'border / landscape / duration', period: '2016–22', summary: '沿 Rio Grande / Río Bravo 长期工作，让河流同时作为生态系统、边界与国家政治存在。', actions: ['长期沿河拍摄', '黑白 / 彩色摄影', '录像', '多地点安装'], sourceUrl: 'https://www.hauserwirth.com/artists/2839-zoe-leonard/', images: [], relations: [] }
    ], awards: [], exhibitions: ['MoMA — Analogue 2015', 'Whitney Museum — Survey 2018'], sources: [{ label: 'MoMA — Analogue', url: 'https://www.moma.org/collection/works/171309' }, { label: 'Hauser & Wirth artist archive', url: 'https://www.hauserwirth.com/artists/2839-zoe-leonard/' }]
  },
  'an-my-le': {
    artistId: 'an-my-le', projectCoverage: '6 个核心摄影项目已索引 · 1994–现在', imageCoverage: '', note: '按 MoMA 2023–24 survey 的主要长期项目建立骨架，后续继续拆每组 individual works；MoMA 当前在线可确认15件作品。',
    projects: [
      { title: 'Viêt Nam', cluster: 'return / landscape', period: '1994–98', summary: '多年离开后重返越南，以大画幅拍摄故乡景观和城市。', actions: ['大画幅摄影', '多次返乡', '景观观察'], sourceUrl: 'https://www.moma.org/artists/7901-an-my-le', images: [], relations: [rel('收藏', 'MoMA', 'multiple works')] },
      { title: 'Small Wars', cluster: 'Vietnam War reenactment', period: '1999–2002', summary: '跟随美国越战 reenactors，战争史在美国本土地景中被重复表演。', actions: ['战争重演现场拍摄', '大画幅黑白摄影', '部分参与演练'], sourceUrl: 'https://www.moma.org/artists/7901-an-my-le', images: [img('https://d7hftxdivxxvm.cloudfront.net/?height=553&quality=50&resize_to=fit&src=https%3A%2F%2Fd32dm0rphc51dk.cloudfront.net%2F7drgwkbRBYWvms05SAo7WQ%2Fnormalized.jpg&width=800', 'Small Wars', '© An-My Lê', 'https://www.moma.org/artists/7901-an-my-le', 'MoMA / collection context')], relations: [] },
      { title: '29 Palms', cluster: 'military training / Iraq War', period: '2003–04', summary: '进入加州 Twentynine Palms 基地，拍摄美军如何在美国荒漠模拟伊拉克战场。', actions: ['基地准入', '大画幅摄影', '训练场景观察'], sourceUrl: 'https://www.moma.org/artists/7901-an-my-le', images: [], relations: [rel('收藏', 'MoMA', '29 Palms works')] },
      { title: 'Events Ashore', cluster: 'navy / logistics / landscape', period: '2005–14', summary: '长期跟随美国海军全球活动，军事力量通过港口、舰艇、救灾和基础设施出现。', actions: ['跨国拍摄', '海军准入', '长期项目'], sourceUrl: 'https://www.moma.org/artists/7901-an-my-le', images: [], relations: [] },
      { title: 'Silent General', cluster: 'American political landscape', period: '2015–', summary: '以章节式结构处理纪念碑、抗议、军事、边境和美国地方景观。', actions: ['大画幅摄影', '章节式编辑', '政治事件与景观并置'], sourceUrl: 'https://www.moma.org/artists/7901-an-my-le', images: [], relations: [] },
      { title: 'Fourteen Views / Between Two Rivers', cluster: 'MoMA survey / spatial editing', period: '2023', summary: 'MoMA survey 中通过14组大型墙面结构重新连接三十年项目。', actions: ['跨系列编辑', 'wallpaper / wood panel', '展览空间设计'], sourceUrl: 'https://anmyle.com/exhibitions', images: [img('https://images.squarespace-cdn.com/content/v1/5b918ae2ee1759aa80ba1ba5/1701801969977-V8W0K55JVAERRKPHBBT4/IN2544_014_CCCR-Press%2BSite.jpeg?format=1000w', 'Between Two Rivers — MoMA', '© An-My Lê', 'https://anmyle.com/exhibitions', 'An-My Lê Studio')], relations: [rel('展览', 'MoMA — Between Two Rivers', '2023–2024')] }
    ], awards: ['MacArthur Fellowship 2012'], exhibitions: ['MoMA — Between Two Rivers 2023–2024'], sources: [{ label: 'MoMA artist archive — 15 works online', url: 'https://www.moma.org/artists/7901-an-my-le' }, { label: 'Artist exhibition archive', url: 'https://anmyle.com/exhibitions' }]
  },
  'akram-zaatari': {
    artistId: 'akram-zaatari', projectCoverage: '5 个核心档案 / 录像项目已索引 · 2003–2013', imageCoverage: '', note: '第一轮覆盖 MoMA 当前六件在线作品中的主要录像/摄影项目与 Lebanon Pavilion；后续继续扩 Arab Image Foundation 相关长期项目。',
    projects: [
      { title: 'This Day (Al Yaoum)', cluster: 'war / media memory', period: '2003', summary: '私人记录、电视、战争影像和多年后的回访共同构成一个不断被改写的“今天”。', actions: ['录像档案', '重访素材', '剪辑'], sourceUrl: 'https://www.moma.org/artists/41278-akram-zaatari', images: [], relations: [rel('收藏', 'MoMA', 'collection')] },
      { title: 'In This House', cluster: 'buried letter / investigation', period: '2005', summary: '追踪战争时期埋在花园里的信，通过采访、现场与挖掘处理土地和记忆。', actions: ['访谈', '现场调查', '挖掘', '录像'], sourceUrl: 'https://www.moma.org/artists/41278-akram-zaatari', images: [], relations: [rel('收藏', 'MoMA', 'collection')] },
      { title: 'On Photography, People and Modern Times', cluster: 'photographic archive / preservation', period: '2010', summary: '重新组织 Arab Image Foundation 早期档案，讨论私人照片进入保存机构之后发生什么。', actions: ['档案选取', '双频道影像', '照片保存研究'], sourceUrl: 'https://www.moma.org/calendar/exhibitions/1278', images: [], relations: [rel('展览', 'Projects 100: Akram Zaatari, MoMA', '2013')] },
      { title: 'Tomorrow Everything Will Be Alright', cluster: 'typewriter / intimacy / time', period: '2010', summary: '老式打字机逐字打印一场关于分离与重逢的对话。', actions: ['typewriter performance', '单频道录像', '声音'], sourceUrl: 'https://listart.mit.edu/exhibitions/akram-zaatari-tomorrow-everything-will-be-alright', images: [img('https://listart.mit.edu/sites/default/files/styles/open_graph_image/public/media/images/exhibitions/2012_akram_zaatari_tomorrow_install.jpg.webp?h=5f675219&itok=aATD6Gww', 'Tomorrow Everything Will Be Alright', '© Akram Zaatari', 'https://listart.mit.edu/exhibitions/akram-zaatari-tomorrow-everything-will-be-alright', 'MIT List Visual Arts Center')], relations: [rel('收藏', 'MoMA', 'collection')] },
      { title: 'Letter to a Refusing Pilot', cluster: 'memory / rumor / Venice', period: '2013', summary: '从一位飞行员拒绝轰炸学校的传闻与艺术家童年记忆出发，录像、照片、建筑模型和阅读空间共同工作。', actions: ['历史 / 传闻研究', '双屏 / 单屏影像', '照片', '空间装置'], sourceUrl: 'https://www.moma.org/artists/41278-akram-zaatari', images: [img('https://www.klatmagazine.com/wp-content/uploads/2013/07/Klat_LEBANON_PAVILLION_259_2.jpg', 'Letter to a Refusing Pilot — Lebanon Pavilion', '© Akram Zaatari', 'https://www.klatmagazine.com/art/biennale-arte-2013-diario-06-libano/9472', 'Venice documentation / Klat')], relations: [rel('展览', 'Lebanon Pavilion, Venice Biennale', '2013'), rel('收藏', 'MoMA', 'collection')] }
    ], awards: [], exhibitions: ['Projects 100 — MoMA 2013', 'Lebanon Pavilion — Venice Biennale 2013'], sources: [{ label: 'MoMA artist archive — 6 works online', url: 'https://www.moma.org/artists/41278-akram-zaatari' }, { label: 'MoMA Projects 100', url: 'https://www.moma.org/calendar/exhibitions/1278' }]
  },
  'arthur-jafa': {
    artistId: 'arthur-jafa', projectCoverage: '5 个核心影像 / 策展项目已索引 · 2013–2026', imageCoverage: '', note: '第一轮覆盖 APEX、Love Is the Message、The White Album、AGHDRA 与 MoMA Artist’s Choice；后续继续补摄影 prints、binders、akingdoncomethas 等。',
    projects: [
      { title: 'APEX', cluster: 'found-image affect montage', period: '2013', summary: '数百张图像以高速序列连接黑人历史、流行文化、身体、宗教和暴力。', actions: ['图像搜集', '高速蒙太奇', '音乐 / 声音'], sourceUrl: 'https://gladstonegallery.com/artist/arthur-jafa/', images: [], relations: [rel('收藏', 'MoMA', 'collection')] },
      { title: 'Love Is the Message, The Message Is Death', cluster: 'Black visuality / montage', period: '2016', summary: '新闻、手机、体育、音乐、警察暴力和日常快乐在7分25秒中高速碰撞。', actions: ['found footage', 'montage', '音乐同步'], sourceUrl: 'https://gladstonegallery.com/artist/arthur-jafa/', images: [], relations: [] },
      { title: 'The White Album', cluster: 'whiteness / self-image / Venice', period: '2018', summary: '约30分钟录像收集网络自述、暴力和文化片段，研究 whiteness 如何通过自身影像出现。', actions: ['网络影像搜集', '长篇蒙太奇', '声音'], sourceUrl: 'https://gladstonegallery.com/artist/arthur-jafa/', images: [img('https://images.ctfassets.net/cmz556ev1x99/4T75gQuGV0wECrlEG2n4Jr/eb14a95aca492bd4af93de2513c468c7/AJ_TWA_Venice_Biennale_2019_p.jpg?fl=progressive&fm=jpg&h=1333&q=100&w=2000', 'The White Album — Venice Biennale installation', '© Arthur Jafa', 'https://gladstonegallery.com/artist/arthur-jafa/', 'Gladstone Gallery')], relations: [rel('奖项', 'Golden Lion — Best Participant', 'Venice Biennale 2019')] },
      { title: 'AGHDRA', cluster: 'CGI landscape / Black abstraction', period: '2021', summary: '黑色岩石海与数字落日形成缓慢 CGI 景观，将 Jafa 的视觉强度从 found footage 转向几乎抽象的时间。', actions: ['CGI', '长时段影像', '沉浸式声音'], sourceUrl: 'https://www.moma.org/artists/69635-arthur-jafa', images: [img('https://cdn.sanity.io/images/syotmk9q/production/1d625d5f12b2902b4dc166c14e4ed558222f2b2b-1280x853.jpg?auto=format&fit=clip&q=70&w=1080', 'AGHDRA', '© Arthur Jafa', 'https://www.spikeartmagazine.com/articles/the-downward-spiral-five-years', 'Spike Art Magazine')], relations: [rel('收藏', 'MoMA', 'collection')] },
      { title: 'Artist’s Choice: Less Is Morbid', cluster: 'museum collection as montage', period: '2025–26', summary: '从 MoMA 馆藏选择80多件作品，让其长期“并置产生情感电荷”的方法直接作用于博物馆艺术史。', actions: ['馆藏研究', '作品选择', '跨时期编排', '展览策划'], sourceUrl: 'https://www.moma.org/calendar/exhibitions/5825', images: [], relations: [rel('策展', 'MoMA Artist’s Choice', '2025–2026')] }
    ], awards: ['Golden Lion for Best Participant — Venice Biennale 2019'], exhibitions: ['58th Venice Biennale 2019', 'MoMA — Surrounds 2019–2020', 'MoMA — Artist’s Choice: Less Is Morbid 2025–2026'], sources: [{ label: 'MoMA artist archive — 6 works online', url: 'https://www.moma.org/artists/69635-arthur-jafa' }, { label: 'Gladstone Gallery', url: 'https://gladstonegallery.com/artist/arthur-jafa/' }]
  }
};
