import type { ArchiveProject, ArchiveRelation } from './archiveData';
const rel=(kind:ArchiveRelation['kind'],label:string,detail?:string):ArchiveRelation=>({kind,label,detail});
const project=(p:ArchiveProject)=>p;

export const archiveExtensions317:Record<string,ArchiveProject[]>={
  'laia-abril':[
    project({title:'Luto',cluster:'performance / photography / video / mourning politics',period:'2026',summary:'Abril 以 Federico García Lorca 的《Bernarda Alba之家》为出发点，把“哀悼”从私人情绪转成一种规定身体、性别与欲望的社会技术。她在 Lorca 遇害地点附近进行现场行为：把黑色丧服悬挂到风景中，让原本属于家庭内部的服饰规范进入公共空间；随后把行为转化成单频道录像与巨幅摄影三联画。官方记录明确给出录像时长 9分39秒；摄影为 Hahnemühle 纸上的 pigment inkjet prints，总体 230 × 389 cm，其中两幅 230 × 141 cm、一幅 230 × 107 cm。作品因此同时存在现场身体动作、时间性录像和大型静态图像三个层次。',actions:['在 Lorca 遇害地点附近实施现场行为。','把黑色服装悬挂于户外风景，使丧服从身体规范转成公共空间中的物质标记。','将行为拍摄为9分39秒单频道录像。','从行为/现场生成巨幅摄影三联画，并以 Hahnemühle 纸 pigment inkjet 输出。','在2026威尼斯双年展开幕周于 Conservatorio di Musica Benedetto Marcello 展示，使作品在历史地点、表演现场与展览空间之间迁移。'],sourceUrl:'https://www.laiaabril.com/project/luto/',images:[],relations:[rel('展览','Conservatorio di Musica Benedetto Marcello, Venezia','2026；The Art Hub Collective commission；威尼斯双年展开幕周。'),rel('展览','Image rights','艺术家官网提供作品与安装图；未确认自由再发布，本站记录入口但不复制。')]}),
    project({title:'Endometriosis — The Silenced Pain',cluster:'photography / bodily material / chronic pain / installation',period:'2026',summary:'Abril 与7位患有致残性子宫内膜异位症的人合作，尝试表现一种难以通过外观直接看见的慢性疼痛。她没有模拟临床影像，而是在疼痛暂时缓解的时刻拍摄身体，使人物以碎片化、非完整主体的方式出现；官方项目说明进一步指出，摄影表面被艺术家的眼泪上光。这个物质动作把摄影表面与身体分泌物连接起来，也把“疼痛不可见”转化成观看时实际面对的物质层。项目被艺术家明确视为 On Mass Hysteria 之后，对性别、制度权力与知识生产关系的继续研究。',actions:['与7位长期遭受严重子宫内膜异位症影响的人合作。','在疼痛暂时缓解时拍摄身体，避免把疼痛直接奇观化或临床化。','以碎片化构图抵抗医学图像要求身体清晰、完整、可诊断的观看方式。','用艺术家自己的眼泪为照片表面上光，使身体物质进入最终摄影对象。','把项目作为 On Mass Hysteria 的延续，转向医学知识与制度性忽视。'],sourceUrl:'https://www.laiaabril.com/project/endometriosis/',images:[],relations:[rel('展览','Museo del Romanticismo, Madrid','2026。'),rel('展览','Annely Juda Fine Art, London','2026。'),rel('展览','Official project images','Laia Abril 官网提供作品图；版权未确认自由再发布，暂不复制。')]}),
    project({title:'Silent Song: A Song I Cannot Hear',cluster:'sound / lightbox / translation / hearing',period:'2023',summary:'Abril 与荷兰作曲家 Ruben Samama 合作，把她自身听不到的频率作为作曲材料。Samama 围绕这些缺失频段创作音乐，而 Abril 再把不可听的声音转换为8件背光视觉作品，使“听觉缺口”被转译成可观看的光与图像。作品不是给听力损失做说明图，而是让一种感官缺席经过作曲、频率分析和视觉转换后成为空间装置；Gran Teatre del Liceu 与之后 Valencia 的版本也显示它能够在音乐剧院和画廊之间重新安装。',actions:['从 Abril 自身无法听见的频率出发建立合作规则。','与作曲家 Ruben Samama 将这些频率组织为音乐作品。','把不可听的频率进一步翻译成8件 retro-illuminated / 背光视觉作品。','在音乐剧院与画廊环境中重新组织声音和发光图像的观看关系。'],sourceUrl:'https://www.laiaabril.com/project/silent-song/',images:[],relations:[rel('展览','Gran Teatre del Liceu, Barcelona','项目最初围绕 Liceu “Obsession” season 形成。'),rel('展览','Set Espai d’Art, Valencia — On Healing','2023；画廊版本。'),rel('展览','Official images','艺术家官网提供两种场地版本图；未确认自由再发布。')]})
  ],
  'taryn-simon':[
    project({title:'Contraband',cluster:'systematic photography / customs / taxonomy',period:'2010',summary:'Simon 获准进入纽约 JFK 机场的 U.S. Customs and Border Protection Federal Inspection Site 与 U.S. Postal Service International Mail Facility，并连续驻留一个完整工作周。她不是挑选“最戏剧化”的违禁品，而是持续拍摄从国际旅客和邮件中被扣留或没收的物品，最终形成1,075张照片。生产过程把机场边检的日常分类机器转成摄影分类学：食物、药品、盗版物、植物、动物制品等在统一的摄影条件下被逐件记录，再以高密度网格式安装，让观众面对数量、重复和制度分类本身。',actions:['取得进入JFK海关检查区与国际邮件设施的许可。','连续驻留一个工作周，对被扣留或没收物品持续拍摄。','以系统性而非新闻式选择建立1,075张图像的庞大目录。','在展览中把大量单件照片并置为密集分类墙，使观看从单一物品转向边境制度如何筛选世界。'],sourceUrl:'https://tarynsimon.com/works/contraband/',images:[],relations:[rel('展览','Centre d’Art Contemporain, Geneva','2011。'),rel('展览','Multiple installation versions','艺术家官网保存 Seoul、Luzern、Dresden、Paris、Moscow、Milwaukee、Geneva、New York、Brussels 等安装视图。'),rel('展览','Image rights','官网作品/安装图版权未确认可自由再发布，本站不复制。')]}),
    project({title:'A Living Man Declared Dead and Other Chapters I–XVIII',cluster:'genealogy / portrait / text-image archive',period:'2008–2011',summary:'Simon 用四年时间在全球追踪18组血缘关系与相关事件。每一章都采用严格三段结构：左侧是一组按血缘顺序排列的正面肖像；中间是艺术家调查、编写的文字叙事；右侧是“footnote images”，即与故事有关的物件、地点或证据照片。无法拍摄的在世成员并不会被替换，而是保留为空白位置，并在文字中说明缺席原因，例如服兵役、入狱、登革热，或因宗教/社会规范不允许女性被拍摄。于是统一的视觉网格与不可控制的现实缺席发生直接冲突。',actions:['跨四年在全球研究18组血缘系统及其政治、宗教、领土与暴力背景。','逐个拍摄血缘成员，并按亲缘次序排列正面肖像。','为每章撰写中央文本板，记录调查所得的事件与人物关系。','拍摄物件、地点和证据作为右侧 footnote images。','对无法拍摄的在世成员保留空白肖像位，而不是补图，使缺席成为作品结构。'],sourceUrl:'https://tarynsimon.com/works/almdd/',images:[],relations:[rel('展览','Tate Modern, London','2011–2012。'),rel('展览','MoMA, New York','2012。'),rel('展览','UCCA, Beijing','2013–2014。'),rel('展览','Image rights','艺术家官网有逐章与安装图；未确认自由再发布。')]})
  ],
  'walid-raad':[
    project({title:'My neck is thinner than a hair: Engines',cluster:'found archive / car bombs / inkjet installation',period:'1996–2004',summary:'Raad 从贝鲁特 An-Nahar Research Center 与 Arab Documentation Center 的报刊档案中找到内战汽车炸弹爆炸后发动机的新闻照片。发动机常被爆炸抛到街道、屋顶或阳台，记者会争相寻找并拍摄它，因为发动机号码理论上能够追踪车辆所有者。Raad 重新组织其中100张历史照片，把新闻摄影从“爆炸现场证据”转化为一套关于证据、司法无效与媒体仪式的档案。MoMA 版本为100张 pigmented inkjet prints，每张24 × 34 cm；连续排列时，重复出现的发动机、围观者和政治人物形成视觉分类。',actions:['进入黎巴嫩报刊/文献机构档案寻找汽车炸弹发动机新闻照片。','选择并重新呈现100张由新闻摄影记者拍摄的历史照片。','把照片从原新闻语境抽离并纳入 Atlas Group 的档案分类。','制作100张24 × 34 cm pigmented inkjet prints，在展墙上形成连续档案阵列。'],sourceUrl:'https://www.moma.org/slideshows/1/30',images:[],relations:[rel('收藏','Museum of Modern Art, New York','100 pigmented inkjet prints；每张24 × 34 cm。'),rel('展览','MoMA installation, 2015–2016','安装照由 Thomas Griesel 拍摄；复制需联系 Art Resource / Scala Archives。'),rel('展览','Artwork rights','© Walid Raad / The Atlas Group；本站不复制受限图。')]}),
    project({title:'Cotton Under My Feet / Two Drops Per Heartbeat',cluster:'site-specific museum intervention / lecture-performance',period:'2021–2022',summary:'这是 Raad 受 TBA21 委托、为 Museo Thyssen-Bornemisza 特定场地制作的项目。他从博物馆自身的诞生、收藏、档案以及西班牙国家购买 Thyssen-Bornemisza Collection 的历史出发，把真实研究与虚构的保存协议、昆虫、钉子、隐藏人物和跨收藏联系混合起来，并直接干预博物馆多个地点。项目并非一组可独立搬运的静态作品：Raad 还设计 Two Drops Per Heartbeat，由本人带领观众在馆内移动约75分钟，通过现场 lecture-performance 激活不同空间和对象。',actions:['围绕 Thyssen 收藏的购买、转移、保存、展示和博物馆档案进行长期研究。','为博物馆多个具体地点制作场域干预，而非只占用单一白盒展厅。','把真实馆藏史与虚构保存协议、昆虫、钉子和人物叙事交织。','设计 Two Drops Per Heartbeat 约75分钟移动式 lecture-performance，由艺术家带观众穿越博物馆。','让观众在真实藏品、建筑空间和虚构叙事之间不断判断“史实”与“否则可能”。'],sourceUrl:'https://www.museothyssen.org/en/exhibitions/walid-raad-cotton-under-my-feet',images:[],relations:[rel('展览','Museo Nacional Thyssen-Bornemisza, Madrid','6 Oct 2021–23 Jan 2022；TBA21 commission。'),rel('展览','Two Drops Per Heartbeat','2021–2022；约75分钟；Raad 英语讲述或西语同传。'),rel('出版','Cotton Under My Feet catalogue','Verlag der Buchhandlung Walther König；174页。'),rel('展览','Image rights','博物馆提供展览图；未确认自由再发布，本站不复制。')]})
  ]
};