import type { ArtistArchive, ArchiveRelation } from './archiveData';
const rel = (kind: ArchiveRelation['kind'], label: string, detail?: string): ArchiveRelation => ({ kind, label, detail });
const abu='https://www.labiennale.org/en/art/2019/partecipants/lawrence-abu-hamdan';
const crosby='https://www.labiennale.org/en/art/2019/partecipants/njideka-akunyili-crosby';
const armitage='https://www.labiennale.org/en/art/2019/partecipants/michael-armitage';
const korakrit='https://www.labiennale.org/en/art/2019/partecipants/korakrit-arunanondchai';
export const archiveBatch101: Record<string, ArtistArchive> = {
'venice-lawrence-abu-hamdan': { artistId:'venice-lawrence-abu-hamdan', projectCoverage:'1 个 forensic-listening / voice-politics 核心实践节点已建立深档案 · 2010s–2019', imageCoverage:'0 / 1 项目暂不使用不稳定外链图像', note:'当前先把 Venice 2019 官方资料明确描述的核心方法做深，不把未核实的单件作品硬凑成目录。Abu Hamdan 自称“private ear”，把 listening、voice、silence 当作可被法律、国家与数据系统争夺的政治材料。', projects:[{ title:'Private Ear / forensic listening practice', cluster:'sound politics / voice evidence / live audio essay', period:'2010s–2019', summary:'实践横跨 film、audio-visual installation 与 live audio essay，重点不是“声音艺术”的形式实验本身，而是声音何时会变成证词、证据、身份识别与治理工具。', actions:['从具体 voice / silence / listening condition 出发，而不是先制造抽象 soundscape','追踪声音在 legal、religious、governmental 与 data-company systems 中如何被解释和占有','将 research 转译为 film、audio-visual installation 与现场 audio essay','把 spoken discourse 与它发生的空间、技术和权力条件同时纳入作品结构','避免把 voice 当透明事实，持续暴露 listening 本身的制度性与政治性'], sourceUrl:abu, images:[], relations:[rel('展览','May You Live In Interesting Times — 58th Venice Biennale','2019 · Central Pavilion / Arsenale')] }], awards:[], exhibitions:['May You Live In Interesting Times — Venice Biennale 2019'], sources:[{label:'La Biennale · Lawrence Abu Hamdan 2019',url:abu}] },
'venice-njideka-akunyili-crosby': { artistId:'venice-njideka-akunyili-crosby', projectCoverage:'1 个 diaspora-domestic painting 核心节点已建立深档案 · 2012–2019', imageCoverage:'0 / 1 项目暂不使用不稳定外链图像', note:'当前先把 Venice 2019 呈现的 domestic / diaspora painting 方法做深。Nigeria 与 US 的视觉线索在同一室内同时存在，不把迁移经验简化成二选一身份。', projects:[{ title:'Diasporic domestic interiors — Venice 2019 presentation', cluster:'portrait / domestic interior / Nigerian-US cultural overlap', period:'2012–2019', summary:'人物多为艺术家本人和家人，空间却故意保持地理上的不确定：冷气候住宅的 radiator 与来自 Nigeria 记忆的 paraffin lamp 可以同时出现；门窗又继续打开更深的 pictorial space。', actions:['以 self / family portrait 和 domestic interior 作为主要叙事场域','在同一空间并置 Nigeria memory 与 US everyday-life 的物件线索','利用 doorway / window 建立层层打开的 interior depth','让空间既具有 flat pictorial surface 又保留多重纵深','通过文化线索的 collision / misalignment 表达 diaspora identity 的内部摩擦'], sourceUrl:crosby, images:[], relations:[rel('展览','May You Live In Interesting Times — 58th Venice Biennale','2019 · Central Pavilion / Arsenale')] }], awards:[], exhibitions:['May You Live In Interesting Times — Venice Biennale 2019'], sources:[{label:'La Biennale · Njideka Akunyili Crosby 2019',url:crosby}] },
'venice-michael-armitage': { artistId:'venice-michael-armitage', projectCoverage:'1 个 Nairobi narrative-painting 核心节点已建立深档案 · 2010s–2019', imageCoverage:'0 / 1 项目暂不使用不稳定外链图像', note:'当前先把 Venice 2019 官方资料明确的 narrative-painting 方法做深。Armitage 用明亮、近乎 picturesque 的画面包裹 inequality 与 political uncertainty，让观看者先被颜色吸引，再进入更不安的社会结构。', projects:[{ title:'Nairobi narrative tableaux — Venice 2019 presentation', cluster:'narrative painting / social observation / political ambiguity', period:'2010s–2019', summary:'画面位于 fantastical reality 与 modern political chaos 之间，多条 narrative thread 同时出现；lush colour 与 sumptuous detail 并不缓和暴力和不平等，反而制造美感与社会现实之间的冲突。', actions:['观察 Nairobi everyday life 中复杂的 social dynamics','将多个事件 / figure / symbolic detail 编入同一 tableau','利用 vivid colour 与 picturesque composition 建立第一层吸引力','在美丽表面下嵌入 inequality、political uncertainty 与 sinister detail','通过 narrative painting 改写 conventional representation，而不是把社会议题做成说明图'], sourceUrl:armitage, images:[], relations:[rel('展览','May You Live In Interesting Times — 58th Venice Biennale','2019 · Central Pavilion / Arsenale')] }], awards:[], exhibitions:['May You Live In Interesting Times — Venice Biennale 2019'], sources:[{label:'La Biennale · Michael Armitage 2019',url:armitage}] },
'venice-korakrit-arunanondchai': { artistId:'venice-korakrit-arunanondchai', projectCoverage:'2 个 fictional-painter / post-natural forest 节点已建立深档案 · 2013–2019', imageCoverage:'0 / 2 项目暂不使用不稳定外链图像', note:'精选项目档案，尚非作品全集。Korakrit 把 family、superstition、spirituality、politics 与 technology 放进持续扩张的 fictional ecology；gallery 被处理成可聚集、可沉浸的环境，而不是单纯 video screening room。', projects:[{ title:'with history in a room filled with people with funny names', cluster:'interlinked video series / fictional Thai painter / changing Thailand', period:'2013–ongoing', summary:'长期系列以 fictional Thai painter 为 recurring character，把 traditional beliefs、natural environment 与 Thailand 的 technology / politics / culture 变化缠在一起。', actions:['建立 recurring fictional painter 作为跨作品人物','把 family / belief / political history 与 contemporary technology 混合进同一叙事','让每个新 episode 与此前作品互相回指','以 video、performance、installation 的组合扩展 narrative world'], sourceUrl:korakrit, images:[], relations:[] },{ title:'Post-natural forest / three-screen Venice installation', cluster:'tree-like sculpture / three-screen installation / Anthropocene ecology', period:'2019', summary:'Central Pavilion 出现 post-natural tree-like sculptural forms；Arsenale 则呈现与 Alex Gvojic 合作的 three-screen installation。uncanny forest 被想象为 Anthropocene 后 rat-like creatures 可能生存的 habitat。', actions:['将 gallery 转成 uncanny forest-like environment','制作 post-natural tree-like sculptural forms','在 Arsenale 使用 three-screen moving-image arrangement','与 Alex Gvojic 协作建立影像环境','让 ecological survival、spirituality 与 political history 在同一空间并置'], sourceUrl:korakrit, images:[], relations:[rel('展览','May You Live In Interesting Times — Venice Biennale','2019 · Central Pavilion + Arsenale')] }], awards:[], exhibitions:['May You Live In Interesting Times — Venice Biennale 2019'], sources:[{label:'La Biennale · Korakrit Arunanondchai 2019',url:korakrit}] }
};
