import type { ArtistArchive, ArchiveProject, ArchiveRelation } from './archiveData';
const rel=(kind:ArchiveRelation['kind'],label:string,detail?:string):ArchiveRelation=>({kind,label,detail});
const project=(p:ArchiveProject)=>p;
export const archiveBatch274:Record<string,ArtistArchive>={
 'taryn-simon':{artistId:'taryn-simon',projectCoverage:'新增 Contraband 与 Paperwork and the Will of Capital，补足边境分类制度与外交权力舞台两条方法线。',imageCoverage:'2/2 建立艺术家官网及重要美术馆入口；不复制未确认开放版权图像。',note:'重点是制度怎样通过分类、布景、文件和摄影制造可见知识。',projects:[
 project({title:'Contraband — border classification as image taxonomy',cluster:'border / customs / taxonomy / circulation',period:'2010',summary:'《Contraband》由1,075幅照片构成。Simon 在纽约 JFK 的 U.S. Customs and Border Protection Federal Inspection Site 与 U.S. Postal Service International Mail Facility 连续驻留一个工作周，持续拍摄从国际旅客及邮件中被扣留或没收的物品。最终图像按照官方分类体系索引和安装，因此作品把国家如何命名、分类并阻断物品流通的制度逻辑转成可见结构。',actions:['在JFK海关检查与国际邮件设施连续工作一周','持续拍摄扣留/没收物而非挑选少量猎奇案例','用统一摄影方式压低物品视觉等级差异','保留官方分类逻辑并组织1,075幅图像','比较物品外观与法律分类之间的不稳定关系'],sourceUrl:'https://tarynsimon.com/works/contraband/',images:[],relations:[rel('展览','Milwaukee Art Museum — Taryn Simon: Photographs and Texts','馆方确认1,075幅图像及官方分类安装。'),rel('展览','National Museum of Modern and Contemporary Art, Seoul','艺术家官网列出的重要后续展出节点。')]}),
 project({title:'Paperwork and the Will of Capital — diplomacy reconstructed through flowers',cluster:'diplomacy / archival reconstruction / political stagecraft / botany',period:'2015–2017',summary:'Simon 从政治协议、条约、合同和法令签署仪式的档案照片出发，研究权力人物身旁几乎总被忽视的花卉布置。她与植物学家合作辨认历史照片中的花材，从荷兰 Aalsmeer 全球花卉体系取得标本，在工作室重建花束，再按照原仪式环境色彩摄影。项目以1944 Bretton Woods会议及 George Sinclair 的十九世纪植物研究为双重历史入口，把花束从装饰物转成政治经济舞台的证人。',actions:['搜集国际协议签署仪式档案照片','与植物学家辨认历史花材','从Aalsmeer取得超过4,000件植物标本','在工作室重建政治签署现场花束','依据历史现场色彩重新布景摄影','把图像与协议文本及植物标本结构并置'],sourceUrl:'https://tarynsimon.com/works/pwc/',images:[],relations:[rel('展览','56th Venice Biennale — Arsenale','2015'),rel('展览','Tel Aviv Museum of Art','2016–2017；curated by Ruth Direktor，assistant curator Galit Landau Epstein。'),rel('展览','Musée d’art contemporain de Montréal','2017；加拿大首次 Simon 个展。'),rel('收藏','Musée d’art contemporain de Montréal','2015 acquisition from the series。')]})],awards:[],exhibitions:['56th Venice Biennale — 2015','Paperwork and the Will of Capital — Tel Aviv Museum — 2016–2017','Paperwork and the Will of Capital — MAC Montréal — 2017'],sources:[{label:'Taryn Simon — Contraband',url:'https://tarynsimon.com/works/contraband/'},{label:'Milwaukee Art Museum — Contraband',url:'https://mam.org/exhibitions/taryn-simon/'},{label:'Taryn Simon — Paperwork',url:'https://tarynsimon.com/works/pwc/'},{label:'MAC Montréal — Paperwork',url:'https://macm.org/en/press-release/taryn-simon-at-the-mac/'}]},
 'cao-fei':{artistId:'cao-fei',projectCoverage:'新增 Haze and Fog 与 Asia One，补足城市异化类型电影到自动化物流基础设施的演变。',imageCoverage:'2/2 建立 Centre Pompidou / Guggenheim 权威馆藏入口。',note:'此前 Whose Utopia / RMB City 已深化；本批追踪幻想如何从工人表演和虚拟城市推进到城市恐怖类型与真实自动仓储。',projects:[
 project({title:'Haze and Fog — zombie genre as urban social diagnosis',cluster:'urbanization / zombie film / class / alienation',period:'2013',summary:'《Haze and Fog》是46分30秒HD录像，也是 Centre Pompidou 馆藏新媒体作品。Cao Fei 把北京大型住宅区中的商人、保安、家政劳动者、性工作者、孕妇等日常人物放入僵尸类型片结构。雾霾既是现实城市环境，也成为消费、阶级分隔与社会联系断裂的视觉隐喻；活人机械执行日常、僵尸反而释放欲望和情绪，构成关键反转。',actions:['以北京住宅环境作为社会空间','用普通职业和居民建立阶级切片','借用zombie/horror类型语法','让雾霾兼具环境事实和心理隐喻','通过活人/僵尸反转讨论受压抑的欲望和联系'],sourceUrl:'https://www.centrepompidou.fr/en/ressources/oeuvre/cEBG7x6',images:[],relations:[rel('收藏','Centre Pompidou / MNAM','2014 donation；new media；inventory AM 2015-4。'),rel('展览','MoMA Documentary Fortnight','2015；与 i.Mirror 并置。'),rel('展览','MoMA PS1 — Cao Fei','2016美国首次综合性个人博物馆展。')]}),
 project({title:'Asia One — automated warehouse as near-future social laboratory',cluster:'automation / logistics / labor / human-machine relation',period:'2018',summary:'《Asia One》由 Guggenheim 委任并进入永久收藏。Cao Fei 进入中国先进工业设施，包括江苏昆山高度自动化分拣中心，把真实物流基础设施转成近未来叙事：巨大仓储中只剩两名人类员工，与高速机器人和持续流动的货物共处。63分钟主影片之外，装置包含多段录像、机动三轮车、邮政/物流物件及大量 JD.com 工作用品，使供应链从电影背景变成占据展厅的物质系统。',actions:['研究并进入先进物流/自动化设施','在真实自动分拣中心发展两名员工的虚构叙事','混合romance、science fiction与物流纪录观察','加入未来访客考察废弃设施的时间跳跃','并置11.11等配送劳动影像','把JD.com制服、包装、标签和设备带入装置'],sourceUrl:'https://www.guggenheim.org/artwork/38191',images:[],relations:[rel('收藏','Solomon R. Guggenheim Museum','Robert H. N. Ho Family Foundation Collection, 2018；accession 2018.12。'),rel('展览','One Hand Clapping — Guggenheim','2018'),rel('策展','Robert H. N. Ho Family Foundation Chinese Art Initiative','Guggenheim commission。')]})],awards:[],exhibitions:['Haze and Fog — Centre Pompidou collection','Cao Fei — MoMA PS1 — 2016','One Hand Clapping — Guggenheim — 2018'],sources:[{label:'Centre Pompidou — Haze and Fog',url:'https://www.centrepompidou.fr/en/ressources/oeuvre/cEBG7x6'},{label:'Guggenheim — Asia One',url:'https://www.guggenheim.org/artwork/38191'},{label:'Guggenheim — Cao Fei',url:'https://www.guggenheim.org/artwork/artist/cao-fei'}]},
 'laia-abril':{artistId:'laia-abril',projectCoverage:'补实践形成期与方法来源，建立早期饮食失调研究到后期制度研究之间的连续性。',imageCoverage:'以艺术家项目目录和机构资料为入口，不复制版权未明确开放图像。',note:'把 journalism、FABRICA 编辑经验和早期身体研究纳入方法谱系，避免只从 On Abortion 开始讲 Abril。',projects:[
 project({title:'FABRICA / COLORS period — editorial research as method formation',cluster:'journalism / editorial practice / research methodology',period:'2009–2014',summary:'Abril 完成 Journalism 学位后赴纽约学习摄影；2009至2014年进入意大利 FABRICA，兼任 researcher、editor 与 COLORS Magazine staff photographer。这解释了她后来为何不把摄影当成单一媒介：采访、文本编辑、资料搜集、图像选择与出版结构从职业训练阶段就同时存在，并在《The Epilogue》中形成重要摄影—文字研究作品。',actions:['以新闻学训练建立采访、核查和叙事编辑基础','在FABRICA同时承担researcher/editor/staff photographer','把杂志生产的文字、图片和编辑顺序转译为艺术方法','发展The Epilogue等早期大型摄影—文本项目'],sourceUrl:'https://www.laiaabril.com/about/long-bio/',images:[],relations:[rel('展览','FABRICA, Italy','2009–2014 artist-in-residence；同时任 COLORS researcher/editor/staff photographer。'),rel('出版','The Epilogue — Dewi Lewis','2014。')]}),
 project({title:'On Eating Disorders — representation ethics before institutional critique',cluster:'eating disorders / representation / counter-narrative',period:'early 2010s–2014',summary:'Abril 官网把 Thinspiration 与 The Epilogue 明确归入 On Eating Disorders。这个项目群是理解 A History of Misogyny 的方法前史：问题从“拍摄饮食失调身体”逐步转向如何避免再次消费脆弱身体，并通过文字、家庭记忆、网络图像文化和长期研究解释身体经验背后的社会机制。MACBA 对她整体实践所概括的 research、forensic aesthetics 与 counter-narratives，在这一阶段已有清晰雏形。',actions:['把eating disorders作为长期研究主题','分析网络thinspiration图像文化与身体表述','在The Epilogue中用家庭叙述、文本和摄影处理疾病后果','从直接身体表象逐步转向证词、档案、社会机制和反叙事'],sourceUrl:'https://www.laiaabril.com/',images:[],relations:[rel('出版','The Epilogue','Dewi Lewis, 2014。'),rel('出版','Thinspiration','艺术家官网列入 On Eating Disorders。'),rel('收藏','MACBA research profile','将其方法概括为 research、forensic aesthetics 与 counter-narratives。')]})],awards:['RPS Hood Medal — 2019','Foam Paul Huf Award — 2021','Spain National Photography Award — 2023'],exhibitions:['Musée de l’Elysée — 2015','Rencontres d’Arles — 2016','Le Bal — 2025'],sources:[{label:'Laia Abril — Long bio',url:'https://www.laiaabril.com/about/long-bio/'},{label:'Laia Abril — project index',url:'https://www.laiaabril.com/'},{label:'MACBA — Laia Abril',url:'https://www.macba.cat/en/actor/laia-abril-50c9/'}]}
};
