import type { ArtistArchive, ArchiveRelation } from './archiveData';
const rel=(kind:ArchiveRelation['kind'],label:string,detail?:string):ArchiveRelation=>({kind,label,detail});

const roster='https://www.labiennale.org/en/art/2017/artists';
const fishkinAsac='https://asac.labiennale.org/persone/378556';
const fishkinPompidou='https://www.centrepompidou.fr/fr/ressources/oeuvre/fvb5zst';
const uriburu='https://www.bellasartes.gob.ar/exhibiciones/venecia-en-clave-verde/';
const geng='https://ucca.org.cn/en/exhibition/who-is-he-a-geng-jianyi-retrospective/audios/';
const gilliamMet='https://www.metmuseum.org/art/collection/search/786826';
const gilliamVenice='https://www.mnuchingallery.com/artists/sam-gilliam';
const griffa='https://www.fondazionegiorgiogriffa.org/en/works';

export const archiveBatch127:Record<string,ArtistArchive>={
'venice-2017-vadim-fishkin':{artistId:'venice-2017-vadim-fishkin',projectCoverage:'1 个 two-channel threshold / inaccessible-light-space 节点已建立深档案 · 2015–2017',imageCoverage:'0 / 1 项目暂不使用不稳定外链图像',note:'Fishkin 常把 science / technology 转成很简洁的 perception trap。Doorway 不是“放一个门的影像”，而是用同步投影制造一个看起来可进入、实际永远不可穿过的空间阈限。',projects:[{title:'Doorway',cluster:'two synchronized projections / opening-closing door / virtual threshold',period:'2015; Venice 2017',summary:'空白墙面上，一扇门不断打开和关闭；打开时后方出现明亮空间。门看似具有 depth / passage，却只存在于 projection 中，因此 real wall、virtual room、inside/outside 被压到同一平面。',actions:['以 blank wall 作为 physical support，避免真实 door frame 提供实体入口','使用 two synchronized video projections 保持门体/后方光场的 coordinated movement','反复执行 opening / closing cycle，形成 perpetual threshold','让 projected light 在门打开时制造 believable spatial depth','故意不提供可穿越入口，使 viewer 的身体经验与视觉判断冲突','把 technological illusion 保持足够简单，让“看见却无法进入”成为主要认知事件'],sourceUrl:fishkinPompidou,images:[],relations:[rel('收藏','Centre Pompidou','Doorway, 2015; acquired 2021'),rel('展览','Viva Arte Viva — Venice Biennale 2017','Pavilion of Time and Infinity')]}],awards:[],exhibitions:['Viva Arte Viva — Venice Biennale 2017'],sources:[{label:'ASAC · Vadim Fishkin participation',url:fishkinAsac},{label:'Centre Pompidou · Doorway',url:fishkinPompidou},{label:'La Biennale · Artists 2017',url:roster}]},

'venice-2017-nicolas-garcia-uriburu':{artistId:'venice-2017-nicolas-garcia-uriburu',projectCoverage:'1 个 ecological-dye / clandestine public-water action 已建立深档案 · 1968; revisited 2017',imageCoverage:'0 / 1 项目暂不使用不稳定外链图像',note:'Uriburu 在 2017 主展中以历史文献回到 Venice；核心节点是 1968 Grand Canal action。它同时是 ecological intervention、painting-with-water 和 institution critique。',projects:[{title:'Coloration of the Grand Canal / Actions in Nature',cluster:'fluorescent dye / public water / ecological intervention / institutional disruption',period:'1968; documented in Venice 2017',summary:'1968 Biennale 期间，Uriburu 未受官方邀请，却在清晨乘 gondola 将约 30 kg non-toxic fluorescent substance 倒入 Grand Canal，使水面数小时变成亮绿色。行动经过数月研究，以“对生态无害、均匀、视觉强烈”为染料选择标准。',actions:['在行动前研究可用于大体量水域且不伤害 flora/fauna 的 fluorescent substance','选择 Venice Grand Canal 作为既是城市基础设施又是全球艺术展示背景的 site','以 gondola 进入水域并秘密倾倒约 30 kg dye','让 current / water circulation 自行扩散颜色，而非控制边界','把 canal 本身当作 painting surface，取消传统 canvas','利用 temporary transformation 让污染、人工化自然与城市 spectacle 同时可见','在后续以 photographs / prints / documents 记录并扩展该行动，而不把一次性事件伪装成可永久保存对象'],sourceUrl:uriburu,images:[],relations:[rel('展览','34th Venice Biennale context','clandestine Grand Canal intervention, 19 Jun 1968'),rel('展览','Viva Arte Viva — Venice Biennale 2017','documentation / historical inclusion')]}],awards:[],exhibitions:['Venice action — 1968','Viva Arte Viva — Venice Biennale 2017'],sources:[{label:'Museo Nacional de Bellas Artes Argentina · Venecia en clave verde',url:uriburu},{label:'La Biennale · Artists 2017',url:roster}]},

'venice-2017-geng-jianyi':{artistId:'venice-2017-geng-jianyi',projectCoverage:'2 个 communication-barrier / book-object 节点已建立深档案 · 1980s–2000; Venice 2017',imageCoverage:'0 / 2 项目暂不使用不稳定外链图像',note:'Geng 的方法一贯针对“观众如何理解作品”这一障碍：从把脸放大到失去安全观看距离，到把日常 form / certificate / book 变成艺术。他避免制造过度自我表达的风格，而更关心 interaction rule。',projects:[{title:'The Second State / communication-distance experiments',cluster:'enlarged face / viewer distance / anti-expression',period:'1980s',summary:'Geng 试图通过巨大面孔直接缩短 viewer 与 image 的心理/物理距离；他本人后来承认这种方法并没有真正消除理解障碍，却把“沟通失败”变成长期研究起点。',actions:['观察 exhibition viewer 与 painting 之间的理解距离','将 face 放大到超出普通 portrait scale','减少安全观看距离，使 viewer 无法轻松退回 detached position','把 failure of communication 本身视作结果而非作品失效','继续发展 forms / certificates / instructions 等低作者性媒介测试 audience response'],sourceUrl:geng,images:[],relations:[]},{title:'Book series',cluster:'dyed books / object without readable content / knowledge-form',period:'1990–2000; shown 2017',summary:'2017 Venice 展出其 Book 系列：书被染色/处理后，作为“知识与阅读的形式”而非透明文本载体出现。重点从书里写了什么转向“为什么我们把这个 object 当作可阅读权威”。',actions:['选择 standard bound-book format 作为 familiar cultural object','通过 dye / surface treatment 改变 pages / cover 的正常信息层级','削弱 readable content，让 binding、volume、page block 变成主要视觉事实','以 series accumulation 让 book 从单件文本变成 typology','借 object familiarity 测试 viewer 自动产生的 reading / knowledge expectation'],sourceUrl:'https://www.artasiapacific.com/news/obituary-geng-jianyi-1962-2017/',images:[],relations:[rel('展览','Viva Arte Viva — Venice Biennale 2017','Book series, 1990–2000')]}],awards:['CCAA Outstanding Achievement Award — 2012','AAC Art China Artist of the Year — 2016'],exhibitions:['Viva Arte Viva — Venice Biennale 2017','Art and China After 1989 — Guggenheim, 2017'],sources:[{label:'UCCA · Geng Jianyi retrospective audio',url:geng},{label:'La Biennale · Artists 2017',url:roster}]},

'venice-2017-sam-gilliam':{artistId:'venice-2017-sam-gilliam',projectCoverage:'2 个 stained-canvas / drape-painting 节点已建立深档案 · 1968–2017',imageCoverage:'0 / 2 项目暂不使用不稳定外链图像',note:'Gilliam 的关键不是“把画布从框上拿下来”这一个动作，而是让 soaking、folding、gravity、drying、hanging 决定 painting 的三维状态。2017 Venice 的 Yves Klein Blue 把这一逻辑放到 Central Pavilion 建筑入口。',projects:[{title:'Drape Paintings / Carousel State method',cluster:'raw canvas / diluted acrylic / folding / unstretched suspension',period:'1968–ongoing',summary:'Gilliam 在 raw canvas 上使用 diluted acrylic，随后折、皱、浸染，让 pigments 沿纤维扩散；最终不把 canvas 重新拉回 flat stretcher，而直接从 wall / ceiling 悬挂，使 folds、gravity、shadow 变成 painting 的实际组成。',actions:['在 unprimed/raw canvas 上倒入或浸入 diluted acrylic','趁材料湿润时用手 folding / creasing 改变 pigment path','允许 colour bleeding / soaking 产生不可完全预见的边界','让 canvas drying 时保留折痕和染色差异','跳过 traditional stretching，把整幅画布从 wall / ceiling 悬挂','根据具体建筑重新决定 drape points，因此每次 installation 形态都变化','让 floor / wall / ceiling 与 viewer movement 进入 painting composition'],sourceUrl:gilliamMet,images:[],relations:[rel('展览','U.S. Pavilion — Venice Biennale 1972','early international presentation of Drape paintings')]},{title:'Yves Klein Blue',cluster:'monumental drape / pavilion façade / architectural painting',period:'2017',summary:'2017 Venice 大型 drape 横跨 Central Pavilion 入口上方，以强烈 red/blue stained canvas 像 bunting / suspended banner 一样悬挂。它既是 painting，也是 façade-scale architectural intervention。',actions:['制作 monumental unstretched stained canvas','保留折叠/染色过程的随机色域','不使用 rigid frame，而在 pavilion exterior/entrance 上设置 suspension points','让 gravity 产生 scallop / fold / sagging silhouette','让 visitor 必须从作品下方进入建筑，使 painting 成为 passage condition','用 façade scale 把抽象绘画从室内 wall 扩展到公共 architecture'],sourceUrl:gilliamVenice,images:[],relations:[rel('展览','Viva Arte Viva — Venice Biennale 2017','Central Pavilion entrance')] }],awards:['U.S. Department of State Medal of Arts Lifetime Achievement — 2015'],exhibitions:['U.S. Pavilion — Venice Biennale 1972','Viva Arte Viva — Venice Biennale 2017'],sources:[{label:'The Met · Carousel State / Drape paintings',url:gilliamMet},{label:'Mnuchin Gallery · Sam Gilliam biography / Venice 2017',url:gilliamVenice},{label:'La Biennale · Artists 2017',url:roster}]},

'venice-2017-giorgio-griffa':{artistId:'venice-2017-giorgio-griffa',projectCoverage:'2 个 primary-sign / unfinished-painting method 节点已建立深档案 · 1967–2017',imageCoverage:'0 / 2 项目暂不使用不稳定外链图像',note:'Griffa 把 painterly authorship 降到最低：raw unstretched canvas、共享的 line/number signs、有限 brush rhythm，以及刻意在画面未填满时停止。折痕、空白和 unfinishedness 都不是缺失，而是作品结构。',projects:[{title:'Primary Signs',cluster:'raw canvas / repeated line / anonymous sign / unfinished field',period:'1967–ongoing',summary:'自 1967 起 Griffa 在 unstretched raw canvas 上重复 horizontal、vertical、diagonal marks，却始终不填满画面。signs 被刻意保持“任何人都能使用”的匿名性，painting 被理解成一段暂时停止的过程。',actions:['把 unprimed linen/cotton/hemp/jute 直接铺在 studio floor 或工作面','不先涂 gesso，让 diluted colour 直接渗入 textile weave','选择 line / stroke 等非个人专属基本符号','以 repeated hand rhythm 逐行推进 marks','在画面仍明显有空白时主动停止，而不追求 compositional closure','展出时将 canvas 直接钉/挂在 wall 上，不使用 stretcher','收纳时折叠 canvas，并接受 crease 作为下一次展示仍可见的历史'],sourceUrl:griffa,images:[],relations:[]},{title:'Unfinished / material-led painting — Venice 2017 context',cluster:'brush-width rule / dilution / canvas behaviour / open process',period:'2017',summary:'Griffa 强调 brush / sponge 的宽度、paint dilution、canvas fibre 本身会决定 mark behaviour；artist 不把形式先锁死，而让 material response 成为下一笔依据。2017 Venice 是他继 1978、1980 后再次进入 Biennale。',actions:['先确定有限工具与颜料条件，而不是完整预画 final composition','根据 brush width / sponge / dilution 调节 mark density','观察 raw canvas 吸水与扩散后再决定后续 rhythm','不修正渗色和 weave interaction，使材料行为保持可见','用 deliberately cut-short line 强调工作可继续却选择暂停','把 unfinished state 视作 painting 的开放时间结构'],sourceUrl:griffa,images:[],relations:[rel('展览','Viva Arte Viva — Venice Biennale 2017','third Venice Biennale participation after 1978 and 1980')]}],awards:[],exhibitions:['Venice Biennale 1978','Venice Biennale 1980','Viva Arte Viva — Venice Biennale 2017'],sources:[{label:'Fondazione Giorgio Griffa · Works / Primary Signs',url:griffa},{label:'La Biennale · Artists 2017',url:roster}]}
};
