import type { ArtistArchive, ArchiveRelation } from './archiveData';

const rel=(kind:ArchiveRelation['kind'],label:string,detail?:string):ArchiveRelation=>({kind,label,detail});

export const archiveBatch252:Record<string,ArtistArchive>={
  'sophie-calle':{
    artistId:'sophie-calle',
    projectCoverage:'方法与作品级深化：把 The Sleepers 从早期行为标签下钻为29位参与者、8天轮班占床、摄影/问卷/供餐的具体协议，并补入 Suite Vénitienne 与 2024–25 Walker 回顾展，建立“规则—跟踪—文本—失败/未完成”谱系。',
    imageCoverage:'MoMA 与 Walker Art Center 提供 The Sleepers、Suite Vénitienne 及 Overshare 官方图像/安装入口；版权未确认开放再发布，因此不复制原图。',
    note:'Calle 的作者性首先来自规则设计而非按快门。她把生活中的不确定关系转成一套可执行协议，再用照片、文字、书籍与装置保存执行过程中产生的偏差、尴尬和失败。',
    projects:[
      {title:'The Sleepers (Les dormeurs)',cluster:'rule-based action / photography / questionnaire / intimacy',period:'1979',summary:'1979年4月，Calle 邀请29个人在8天内轮班占据自己的床，其中既有家人、熟人，也有通过市场、面包店和机构临时找到的人。她并非只拍“睡觉的人”：参与者醒着和睡着时都被摄影，她为他们提供食物，并用一套很长的问卷持续提问。MoMA 馆藏安装整体约155.6 × 447 × 2.5 cm，并由大量单件照片组成。作品因此把私人卧室变成一套人为设定的社会观察协议：床保持不变，进入床的人不断替换，亲密关系被时间表、摄影和问答重新组织。',actions:['先设定“让不同人持续占据自己的床”的规则，而不是从既有题材出发。','主动招募熟人、陌生人和服务人员，使参与者来源本身成为作品结构。','连续8天按轮班方式维持床的占用。','同时记录参与者清醒与睡眠状态，并向他们提问、供餐。','把行动产生的照片与文字重新编辑为墙面安装，使一次生活事件获得可重复阅读的档案结构。'],sourceUrl:'https://www.moma.org/collection/works/399087',images:[],relations:[rel('收藏','Museum of Modern Art, New York','MoMA records The Sleepers as a large photographic installation; acquired 2019.'),rel('方法','rule → encounter → archive','A self-imposed rule produces encounters; photography and text subsequently stabilize the event as an artwork.')]},
      {title:'Suite Vénitienne',cluster:'following / surveillance / travel / photobook / text-image',period:'1980',summary:'Suite Vénitienne 延续 Calle 1979年在巴黎跟随陌生人的行动逻辑，但把规则推向更长距离：她跟随一名偶然遇见的男子前往 Venice，并以照片、时间记录和叙述保存追踪过程。作品的重要性不只是“偷窥”，而是作者主动把自己的行动自由压缩成一条外部规则——目的地、路线和等待都由被跟踪者的行动决定。Walker 收藏其书籍版本，并在 2024–25 首次北美大型调查展 Overshare 中把它与 The Sleepers、Cash Machine / Unfinished 等并置，使“跟踪—叙事—无法完成/无法掌握他人”的长期方法变得清楚。',actions:['从偶遇陌生人开始，而不是预先选择人物题材。','把“继续跟随”设为行动规则，让对方无意中决定艺术家的路线。','通过照片、时间与地点记录把追踪转换为可验证的叙事节点。','将行动重新编辑为图文书籍/作品，使跟踪行为在事后获得叙事顺序。'],sourceUrl:'https://www.walkerart.org/collections/artwork/suite-venitienne/',images:[],relations:[rel('收藏','Walker Art Center','Walker Library holds multiple Suite Vénitienne editions.'),rel('回顾展','Sophie Calle: Overshare — Walker Art Center','26 Oct 2024–26 Jan 2025; first North American survey spanning five decades.'),rel('方法谱系','The Sleepers → Suite Vénitienne → Cash Machine / Unfinished','Rule-based encounter expands from a controlled bedroom to pursuit in public space and later to the productive admission that a commission may remain unresolved.')]}
    ],awards:[],exhibitions:['Sophie Calle: Overshare — Walker Art Center, Minneapolis, 26 Oct 2024–26 Jan 2025','France Pavilion — 52nd Venice Biennale, 2007'],sources:[{label:'MoMA · Sophie Calle / The Sleepers',url:'https://www.moma.org/collection/works/399087'},{label:'MoMA · Sophie Calle artist overview',url:'https://www.moma.org/artists/6655-sophie-calle'},{label:'Walker Art Center · Suite Vénitienne',url:'https://www.walkerart.org/collections/artwork/suite-venitienne/'},{label:'Walker Art Center · Sophie Calle: Overshare',url:'https://www.walkerart.org/whats-on/sophie-calle-overshare/'}]
  },
  'hito-steyerl':{
    artistId:'hito-steyerl',
    projectCoverage:'系统级深化：补入 Serpentine 2019 Power Plants / Actual Reality OS / Power Walks 三联结构，明确神经网络“预测下一帧”、0.04秒未来、AR不平等数据与社区研究伙伴的生产链。',
    imageCoverage:'Serpentine 官方项目站提供视频雕塑、AR sigil、展览空间与研究伙伴图像；版权归艺术家/画廊及安装摄影者，未复制原图。',
    note:'Power Plants 说明 Steyerl 的 AI 不是独立的生成图像技巧，而是与社区数据、劳动/住房政策、AR界面、展览建筑和声音共同构成一个权力可视化系统。',
    projects:[
      {title:'Power Plants / Actual Reality OS / Power Walks',cluster:'AI prediction / AR / community research / inequality / installation',period:'2019',summary:'Serpentine 2019项目围绕“power”的多重含义展开：Power Plants 的神经网络通过计算视频的下一帧生成被称作处在0.04秒未来的植物；Power Plants OS 让观众扫描15个动画 sigil，在AR中读取未来植物描述、研究伙伴谈话与预测文本；Actual Reality OS 则与 The Voice of Domestic Workers、Architects for Social Housing、Unite Hotel Workers、Disabled People Against Cuts 等团体合作，把住房、紧缩政策、低薪劳动和城市可达性的资料/证词映射到展馆外部。Power Walks 再把数据重新转为真实城市行走。因此作品不是“AI植物影像”，而是预测模型、社区知识、空间移动和界面设计组成的多层研究系统。',actions:['训练/使用神经网络根据当前视频帧预测下一帧，把算法误差本身转成不断变形的植物图像。','把预测时间明确设定为约0.04秒之后，使“未来”被压缩成机器计算的极短时间尺度。','与当地住房、劳动、残障权利和社区组织共同收集数据与证词。','把不平等数据转换为 Actual Reality OS 的AR建筑模型，并让观众在展馆外部通过手机/平板读取。','设置15个动画 sigil，把视频雕塑与 Power Plants OS 中的文本、植物学描述和证词连接。','通过 Power Walks 把数字数据重新带回真实街区，让身体行走成为理解数据的一部分。'],sourceUrl:'https://www.serpentinegalleries.org/whats-on/hito-steyerl-power-plants/',images:[],relations:[rel('委任','Serpentine Galleries / The Store X','Power Plants video sculptures co-commissioned for the 2019 project.'),rel('研究伙伴','community organisations','Includes The Voice of Domestic Workers, Architects for Social Housing, Unite Hotel Workers, Disabled People Against Cuts and others.'),rel('合作','Kojey Radical','Soundtrack collaboration; audio integrated into the installation.'),rel('方法谱系','How Not to Be Seen → Factory of the Sun → Power Plants','Machine visibility → body/data extraction → predictive AI tied to social datasets and public-space research.')]}
    ],awards:[],exhibitions:['Hito Steyerl: Power Plants — Serpentine Galleries, London, 11 Apr–6 May 2019'],sources:[{label:'Serpentine · Hito Steyerl: Power Plants',url:'https://www.serpentinegalleries.org/whats-on/hito-steyerl-power-plants/'},{label:'Serpentine · Hito Steyerl project / OS documentation',url:'https://hitosteyerl.serpentinegalleries.org/'},{label:'Serpentine · Actual Reality OS',url:'https://www.serpentinegalleries.org/whats-on/hito-steyerl-actual-reality-os/'}]
  },
  'pierre-huyghe':{
    artistId:'pierre-huyghe',
    projectCoverage:'UUmwelt 深化：补足“给参与者图像→脑内重构→fMRI→深度神经网络→数千次重建→LED屏幕→活蝇/环境变化”的完整生产链及 Serpentine 策展关系。',
    imageCoverage:'Serpentine 提供 UUmwelt 安装图与策展视频，安装摄影版权 Ola Rindal / artist / Serpentine；未复制原图。',
    note:'UUmwelt 的关键并非“AI读脑”这个噱头，而是让人的想象、测量设备、训练数据、神经网络误差、屏幕与活体生物彼此成为环境中的行动者；最终图像没有一个单一作者能够完全控制。',
    projects:[
      {title:'UUmwelt — Serpentine environment',cluster:'fMRI / deep neural network / cognition / LED / living system',period:'2018–2019',summary:'Huyghe 先选择一组图像与描述交给参与者；当参与者在脑中重新构想这些图像时，以 fMRI 捕捉脑活动，再把数据交给深度神经网络尝试重建想象内容。网络产生的不是一张确定图，而是数千次不稳定尝试，并持续显示在散布展厅的大型 LED 屏幕上。Serpentine 同时把展馆改造成会随时间变化的 porous environment，并纳入活蝇等非人生命。于是观众面对的不是一件固定视频，而是人类想象、医学成像、机器推断、显示设备、昆虫和展览时间共同运行的环境。',actions:['由艺术家预先选择图像/描述，建立机器重建的认知目标。','让参与者在脑中重新想象这些内容，同时用 fMRI 记录脑活动。','把脑活动数据输入 deep neural network，让系统尝试从自己的图像资源中重建人类想象。','保留数千次不稳定、失败和变形的机器重建，而不是只挑选一个“正确答案”。','将生成结果分布在大型 LED 屏幕上，使图像成为空间环境而非单屏影片。','在展览中加入活蝇并允许环境发生不可逆、不可预测的变化，使生物行为与计算过程并列。'],sourceUrl:'https://www.serpentinegalleries.org/whats-on/pierre-huyghe-uumwelt/',images:[],relations:[rel('策展','Rebecca Lewin / Natalia Grabowska','Serpentine exhibition curated by Rebecca Lewin with Natalia Grabowska, 2018–19.'),rel('机构','Serpentine Galleries','UUmwelt ran 3 Oct 2018–10 Feb 2019.'),rel('方法','human imagination → measurement → machine reconstruction','Authorship is distributed across selected source images, participant cognition, fMRI measurement and neural-network inference.'),rel('方法谱系','Untilled → After ALife Ahead → UUmwelt','Multispecies ecology → architecture/biology/algorithm system → cognition/AI/biological environment.')]}
    ],awards:[],exhibitions:['Pierre Huyghe: UUmwelt — Serpentine Galleries, London, 3 Oct 2018–10 Feb 2019'],sources:[{label:'Serpentine · Pierre Huyghe: UUmwelt',url:'https://www.serpentinegalleries.org/whats-on/pierre-huyghe-uumwelt/'},{label:'Serpentine · UUmwelt curator film',url:'https://www.serpentinegalleries.org/watch/pierre-huyghe-uumwelt/'}]
  }
};