import type { ArchiveProject, ArchiveRelation } from './archiveData';
const rel=(kind:ArchiveRelation['kind'],label:string,detail?:string):ArchiveRelation=>({kind,label,detail});
export const archiveExtensions268:Record<string,ArchiveProject[]>={
'walid-raad':[
{title:'Scratching on things I could disavow',cluster:'art infrastructure / Gulf museums / war / speculative institution',period:'2007–ongoing',summary:'Raad 在 The Atlas Group 后把问题从黎巴嫩战争文件推进到阿拉伯世界新艺术基础设施本身。MoMA 2015 美国首次综合调查展把 Scratching 与 The Atlas Group 并列为两条长期主轴：前者研究艺术博览会、双年展、博物馆和画廊快速出现的同时，地缘政治、经济与军事冲突如何持续塑造该地区。收藏、展示、建筑、赞助和文化资本因此不再是作品外部背景，而成为 Raad 调查和虚构化处理的对象。',actions:['把研究对象从战争影像/文件扩展到博物馆、画廊、双年展和艺术市场基础设施。','追踪文化机构增长与资本、战争、区域政治之间的关系。','继续使用摄影、雕塑、建筑模型、文本和 lecture-performance，让研究材料在事实、推测与虚构之间移动。','通过 Walkthrough 等现场讲述让艺术家的叙事行为成为作品的一部分。'],sourceUrl:'https://www.moma.org/calendar/exhibitions/1493',images:[],relations:[rel('展览','Walid Raad — Museum of Modern Art','12 Oct 2015–31 Jan 2016；美国首个综合调查展。'),rel('项目','The Atlas Group → Scratching on things I could disavow','研究尺度从黎巴嫩战争档案转向阿拉伯世界艺术制度及其经济/军事条件。'),rel('媒介','Walkthrough / lecture-performance','表演、叙事与 storytelling 是 Raad 实践的重要组成。')]},
{title:'Appendix XVIII: Plates',cluster:'war / form / color / speculative conservation',period:'2009',summary:'Appendix XVIII 把 Raad 对战争的研究推进到一个比“战争如何伤害人和建筑”更怪也更重要的问题：战争是否也会影响艺术的颜色、线条、形状和形式。MoMA 保存的版本由23件 mounted digital prints 组成。在 Walkthrough 中，他从战争对居民、城市、建筑和街道的物理与心理影响转向视觉形式本身。作品因此不再只问文件是否真实，而让艺术史、保存与形式判断也进入不稳定状态。',actions:['从战争的人身/建筑损害出发，把问题转向视觉形式是否也可能受到战争影响。','制作23件数字输出，使颜色、线条、形状的异常成为可被观看和比较的“证据”。','通过现场 Walkthrough 为图像建立介于研究、记忆与推测之间的因果关系。'],sourceUrl:'https://www.moma.org/audio/playlist/21/431',images:[],relations:[rel('收藏','Museum of Modern Art','2009；set of 23 digital prints mounted on Sintra。'),rel('方法','document truth → perceptual truth','从 Atlas Group 的档案可信度问题推进到战争是否改变视觉形式与感知。')]}
],
'sophie-calle':[
{title:'Les Aveugles — asking what beauty looks like without sight',cluster:'protocol / testimony / portrait / visible vs interior image',period:'1986',summary:'Les Aveugles 把 Calle 的规则式方法从跟踪、进入私人空间转向“提问”。受到 Diderot 关于盲人的文本启发，她向失明者询问他们心中“美”的图像。Centre Pompidou 馆藏说明记录了18份 testimony；典型单元把参与者黑白肖像、回答文字与一张对应描述对象的彩色图像并置。摄影在这里不再证明“我看见了什么”，反而暴露视觉图像与他人内部经验之间无法被摄影跨越的距离。',actions:['制定固定问题，询问看不见的人什么是美。','收集18位参与者的语言证词，而不是替他们总结答案。','为参与者制作黑白肖像并保留具体身份。','把回答文字与对应彩色对象照片并置，形成 portrait + testimony + image 三元结构。'],sourceUrl:'https://www.centrepompidou.fr/fr/ressources/oeuvre/cgrXRM',images:[],relations:[rel('收藏','Centre Pompidou — Musée national d’art moderne','馆藏 Les Aveugles 相关装置；1986。'),rel('思想来源','Denis Diderot — Lettre sur les aveugles','由 Diderot 对盲人与镜子的描述出发设计询问协议。'),rel('方法','surveillance → interview protocol','从观察/追踪转向由固定问题生产图像—文本关系。')]},
{title:'Les Autobiographies / Le Mari',cluster:'autofiction / intimacy / text-image / self as material',period:'1988–2003 / series dated 1995',summary:'Centre Pompidou 将 Le Mari 说明为更大的 Histoires vraies / Les Autobiographies 项目的一部分：九个由文字与照片组成的 panels，以近似私人日记的方式讲述 Calle 与前夫关系的不同阶段。关键不是“真实私生活曝光”，而是 Calle 同时充当事件参与者、叙述者和编辑者，把已经发生的人生重新切割、命名、排序并发布。Pompidou 特别指出作品混合 autobiography 与 fiction、art 与 life，也迫使观众进入 voyeuristic accomplice 的位置。',actions:['从自己的婚姻与私人经历中选择片段，而不是完整连续记录人生。','用短文本重写事件，使回忆经过叙事、删减和标题化。','把文字与照片组成固定 panel，让照片既像证据又无法独立证明叙述。','以九个 panels 建立关系的阶段性结构，使私人时间变成可编辑的作品时间。'],sourceUrl:'https://www.centrepompidou.fr/en/ressources/oeuvre/cxgGoa',images:[],relations:[rel('收藏','Centre Pompidou','Les Autobiographies；艺术家2011年捐赠。'),rel('出版','Histoires vraies','1988–2003持续发展的更大项目，并以书籍形式出版。'),rel('方法','life → edit → autofiction','选择、文字重写和图像并置共同制造“自传”。')]}
]
};