import type { ArtistArchive, ArchiveProject, ArchiveRelation } from './archiveData';
const rel=(kind:ArchiveRelation['kind'],label:string,detail?:string):ArchiveRelation=>({kind,label,detail});
const project=(p:ArchiveProject)=>p;

export const archiveBatch302:Record<string,ArtistArchive>={
  'carrie-mae-weems':{
    artistId:'carrie-mae-weems',
    projectCoverage:'深化 Carrie Mae Weems：Kitchen Table Series、The Louisiana Project、The Usual Suspects。重点补固定场景如何变成叙事系统、委托如何进入地方历史研究，以及晚期作品如何把模糊、色块、文字、found footage、旁白与表演组织成反种族化观看机制。',
    imageCoverage:'National Gallery of Art、Guggenheim、Newcomb Art Museum/Tulane、LSU Museum of Art 与 Georgia Museum of Art 均有作品或展览页；本批只记录官方入口和作品结构，未确认自由再发布授权的图像不复制进仓库。',
    note:'Weems 的关键并非仅是“以黑人女性身份谈身份政治”。她不断改变谁有权进入画面、历史由谁叙述以及观看者如何被安排：Kitchen Table 以一个固定家庭场景制造虚构人物史；Louisiana Project 把委托纪念转成对购买、种族、权力与新奥尔良文化结构的反向历史阅读；The Usual Suspects 则把当代警务影像和司法语言重新编排为关于观看制度本身的作品。',
    projects:[
      project({title:'Kitchen Table Series',cluster:'staged photography / text / domestic theatre / self-representation',period:'1990; portfolio printed 2003',summary:'Kitchen Table Series 不是家庭生活抓拍，而是一套高度受控的室内剧场。Weems 让自己担任虚构女主人公，在同一张厨房桌、同一盏悬灯和基本固定机位下，与男性伴侣、孩子、女性朋友或独处状态形成连续场景。空间几乎不变，人物关系、身体姿态、桌面物件和文字却持续变化，因此“厨房”从传统女性家庭空间转成可以排演欲望、母职、友谊、权力与独处的叙事舞台。National Gallery of Art 馆藏组合明确为20张 platinum/palladium prints 与14张 screenprints/text sheets；2003版由 Pamela VanderZwan 参与设计，John Marcy 印制照片，Peter Kruty Editions 印制文字。',actions:['把自己的厨房桌设定为固定舞台，以稳定灯光、机位和空间形成可比较的连续结构。','由艺术家本人扮演中心人物，并邀请不同人物进入同一场景，使关系变化而空间不变。','通过桌面物件、坐姿、凝视、人物进出与顺序编排制造叙事，而不是依赖单张决定性瞬间。','将20张照片与14张文字页组合为完整作品，使图像和书写共同承担人物心理与社会位置的建构。'],sourceUrl:'https://www.nga.gov/artworks/209288-kitchen-table-series',images:[],relations:[rel('收藏','National Gallery of Art — 2017.4.1.1-34','馆藏为20张 platinum/palladium prints + 14 screenprints；1990创作，2003印制。'),rel('回顾展','Carrie Mae Weems: Three Decades of Photography and Video — Guggenheim — 2014','Guggenheim 将其作为Weems职业生涯的 landmark series，并放入从早期纪录/自传到概念性作品的演变中。')]}),
      project({title:'The Louisiana Project',cluster:'commission / historical research / photography / narrative / video',period:'2003–2005+',summary:'The Louisiana Project 源于2003年纪念 Louisiana Purchase 二百周年的委托，但 Weems 没有制作庆典式地方史。她以新奥尔良为中心，把购买事件之后延续的种族、性别、阶级与权力结构作为研究对象，并通过摄影、叙事和录像重新阅读 Mardi Gras、地方文化仪式和历史记忆。项目因此把“官方纪念”反转为对纪念对象自身的审问：谁获得土地与权力、谁被排除在历史主体之外，以及过去建立的文化模式怎样继续存在于当下。',actions:['接受 Louisiana Purchase 二百周年委托，但把纪念任务转化为批判性历史调查。','以新奥尔良为研究现场，把地方仪式、Mardi Gras、建筑/遗迹与历史叙事并置。','综合摄影、文字叙事和录像，而非用单一纪录摄影说明历史。','让作品进入 Louisiana 本地博物馆收藏与后续展览，使地方历史研究持续与当地制度语境发生关系。'],sourceUrl:'https://newcombartmuseumcollection.tulane.edu/artist-maker/info/1028',images:[],relations:[rel('委托','Newcomb Art Museum / Tulane University — 2003','馆方资料明确记录项目为纪念 Louisiana Purchase bicentennial 而委托。'),rel('展览','LSU Museum of Art — The Usual Suspects / Art in Louisiana — 2018','The Louisiana Project 与 Slave Coast、From Here I Saw What Happened and I Cried 等并置，重新进入 Louisiana 地方收藏叙事。')]}),
      project({title:'The Usual Suspects / All the Boys / People of a Darker Hue',cluster:'police violence / stereotype / photography / video / found footage',period:'2014–2018',summary:'这一组晚期作品研究把黑人身体预设为“嫌疑人”的视觉和制度语言。All the Boys 与 The Usual Suspects 使用模糊人物、色块遮挡、文字与案件事实，让观众意识到种族不是图像里天然可见的属性，而是被分类和观看制度不断制造的结果；People of a Darker Hue 则以录像、found footage、旁白和表演形成悼念结构，把个案死亡与更长的视觉暴力史连接起来。2018 LSU Museum of Art 展览由 Courtney Taylor 策展，并与 LSU School of Art 合作。',actions:['重新组织与警务暴力相关的人物图像和事实，而不是把暴力现场作为新闻摄影重新展示。','用模糊、色块遮脸与文字信息干扰快速种族识别，让“看见”本身成为问题。','在 People of a Darker Hue 中组合录像、found footage、旁白与表演，建立比单张照片更缓慢的纪念节奏。','通过展览把当代警务图像与 Weems 长期研究的档案、奴隶制、历史肖像和制度性观看接回同一谱系。'],sourceUrl:'https://www.lsumoa.org/carrie-mae-weems',images:[],relations:[rel('策展人','Courtney Taylor','Carrie Mae Weems: The Usual Suspects，LSU Museum of Art，2018。'),rel('巡展','Georgia Museum of Art — 2022','机构资料继续强调作品对 Black bodies 与 criminality stereotype、司法不作为的研究。')]}),
    ],
    awards:['MacArthur Fellowship — 2013','Rome Prize Fellowship — American Academy in Rome'],
    exhibitions:['Carrie Mae Weems: Three Decades of Photography and Video — Guggenheim — 2014','Carrie Mae Weems: Kitchen Table Series — National Gallery of Art — 2017–18','Carrie Mae Weems: The Usual Suspects — LSU Museum of Art — 2018'],
    sources:[{label:'National Gallery of Art — Kitchen Table Series',url:'https://www.nga.gov/artworks/209288-kitchen-table-series'},{label:'Guggenheim — Three Decades of Photography and Video',url:'https://www.guggenheim.org/exhibition/carrie-mae-weems-three-decades-of-photography-and-video'},{label:'Newcomb Art Museum — Carrie Mae Weems / Louisiana Project',url:'https://newcombartmuseumcollection.tulane.edu/artist-maker/info/1028'},{label:'LSU Museum of Art — The Usual Suspects',url:'https://www.lsumoa.org/carrie-mae-weems'}]
  },
  'joan-fontcuberta':{
    artistId:'joan-fontcuberta',
    projectCoverage:'深化 Joan Fontcuberta：Herbarium、Orogenesis/Landscapes without Memory、Googlegrams，并补 PhotoVision—策展—理论写作—Hasselblad 的机构网络。重点从“真假摄影”推进到伪科学档案、机器生成地景与网络图像检索三种不同知识生产机制。',
    imageCoverage:'Reina Sofía、Foam、MACBA、Hasselblad Foundation、Instituto Cervantes 与 Fundación María Cristina Masaveu Peterson 提供作品/展览资料；未确认自由再发布授权的图像不复制入仓库。',
    note:'Fontcuberta 的演变不是重复制造摄影骗局：Herbarium 模仿植物学证据；Orogenesis 把风景画交给原用于二维地图转三维地形的软件解释；Googlegrams 又把搜索引擎、关键词和海量网络图片变成单幅公共图像。他持续更换“相信图像”的技术制度，从摄影/科学权威推进到软件和搜索平台。',
    projects:[
      project({title:'Herbarium',cluster:'pseudo-science / botanical archive / staged objects / gelatin silver photography',period:'1982–1984+',summary:'Herbarium 借用植物学摄影和新客观主义式的中性描述外观，制造看似可分类、可命名的植物证据。作品中的“植物”并非自然史发现，而是艺术家以材料和对象构造后再以严肃黑白摄影、拉丁化命名和系列分类包装。关键不只是骗观众，而是证明可信度来自摄影形式、命名法、档案排列和科学机构语气共同生产。Reina Sofía 馆藏的 Philosifux Hyemale（1982）为银盐明胶照片，Giliandria Escoliforcia（1984）则为 selenium-toned gelatin silver print；Hasselblad 2013回顾展把 Herbarium 与 Fauna、Constellations、Sputnik、Sirens、Orogenesis 串成从植物学到地理学的伪科学谱系。',actions:['收集并组合材料，构造并不存在于标准植物学分类中的对象。','使用黑白银盐摄影和近似科学标本摄影的正面、清晰、去情境化语言。','为对象配置拟拉丁学名与系列分类，使摄影与命名共同模拟知识权威。','让作品进入博物馆/摄影展览语境，使“艺术机构中的伪科学档案”进一步测试观众的信任机制。'],sourceUrl:'https://www.museoreinasofia.es/colecciones/obra/philosifux-hyemale/',images:[],relations:[rel('收藏','Museo Reina Sofía — Philosifux Hyemale / Giliandria Escoliforcia','馆藏记录保存1982与1984 Herbarium 作品的银盐工艺、尺寸和版本。'),rel('奖项展览','Hasselblad Center — The Nature of Photography – The Photography of Nature — 2013–14','2013 Hasselblad Award 展览把 Herbarium 与 Fauna、Sputnik、Orogenesis 等放进同一“pseudo-scientific lens”脉络。')]}),
      project({title:'Orogenesis / Landscapes without Memory',cluster:'software-generated landscape / cartography / machine interpretation',period:'2002–2010+',summary:'在 Landscapes without Memory / Orogenesis 中，Fontcuberta 使用由美国空军开发、原本把二维地图数据转换成模拟三维地形的软件，却故意不给它地图，而输入 Gauguin、Van Gogh、Cézanne、Turner、Constable 等人的风景画。软件把绘画中的色块、明暗和轮廓误读为地形数据并生成新的虚拟山脉与地貌。于是作者不再伪造一份“摄影证据”，而是设置错误输入条件，让机器按照自身规则诚实地产生错误世界。Foam 2010–11 展览把这些结果称为 post-landscapes。',actions:['取得/使用原用于二维 cartographic data 转三维模拟地形的软件。','故意以艺术史中的风景画替代地图数据作为软件输入。','让软件依据自己的地形解释规则读取绘画，而不手工把结果修成传统风景。','输出并展览机器生成的 post-landscapes，使观看者同时面对原画、软件规则与虚拟地理之间的断裂。'],sourceUrl:'https://www.foam.org/events/joan-fontcuberta',images:[],relations:[rel('机构','Foam Fotografiemuseum Amsterdam — 26 Nov 2010–27 Feb 2011','Landscapes without Memory 展览明确记录软件来源、输入绘画和 post-landscape 方法。'),rel('方法关系','US Air Force cartographic software','军用/制图工具被重新用于解释绘画，技术的“客观性”因此成为作品材料。')]}),
      project({title:'Googlegrams',cluster:'internet images / search engine / photomosaic / post-photography',period:'2005–2008+',summary:'Googlegrams 把一张具有公共传播度的主图像重新拆成数千张网络搜索图片。Fontcuberta 使用 freeware photomosaic 软件在线连接 Google，并预先设定与主题有关的搜索关键词；程序抓取结果后以大量小图拼出远看可识别的整体图像。Instituto Cervantes 北京2008展览记录项目由12件 photomontage 构成，单件通常由约10,000张互联网图片组成；同系列 La Gran Muralla 则由8,400张 Google 搜索图片构成。这里的“摄影作者”已经被拆成原始公共图像、关键词选择、搜索引擎排序、软件拼贴和网络用户上传内容的共同结果。',actions:['选择已经进入公共视觉记忆的主图像作为远距离可读的整体结构。','为每件作品设计与主题相关的搜索词，把语言选择转化为图像采样规则。','让 freeware photomosaic 程序连接 Google，自动寻找并调用大量互联网图片。','用数千张搜索结果作为像素/马赛克单元重新生成主图像，使局部信息与整体政治图像发生冲突。'],sourceUrl:'https://pekin.cervantes.es/FichasCultura/Ficha49569_64_1.htm',images:[],relations:[rel('展览','Instituto Cervantes Beijing — 8 Jun–27 Jul 2008','官方记录12件作品、photomontage 技术及约10,000张互联网图片的生成方式。'),rel('作品','Googlegrama: La Gran Muralla — 2008','Fundación María Cristina Masaveu Peterson 记录作品由8,400张 Google 搜索图像构成，158×119 cm，edition 1/5。')]}),
    ],
    awards:['Hasselblad Foundation International Award in Photography — 2013'],
    exhibitions:['The Nature of Photography – The Photography of Nature — Hasselblad Center — 2013–14','Landscapes without Memory — Foam — 2010–11','Joan Fontcuberta: Googlegramas — Instituto Cervantes Beijing — 2008'],
    sources:[{label:'MACBA — Joan Fontcuberta',url:'https://www.macba.cat/en/actor/joan-fontcuberta/'},{label:'Museo Reina Sofía — Philosifux Hyemale',url:'https://www.museoreinasofia.es/colecciones/obra/philosifux-hyemale/'},{label:'Hasselblad Foundation — Joan Fontcuberta at Hasselblad Center',url:'https://www.mynewsdesk.com/se/hasselblad-foundation/pressreleases/joan-fontcuberta-at-the-hasselblad-center-920392'},{label:'Foam — Landscapes without Memory',url:'https://www.foam.org/events/joan-fontcuberta'},{label:'Instituto Cervantes Beijing — Googlegramas',url:'https://pekin.cervantes.es/FichasCultura/Ficha49569_64_1.htm'},{label:'Fundación María Cristina Masaveu Peterson — Googlegrama: La Gran Muralla',url:'https://www.fundacioncristinamasaveu.com/en/portfolio/googlegrama-la-gran-muralla/'}]
  }
};