import type { ArtistArchive, ArchiveProject, ArchiveRelation } from './archiveData';
const rel=(kind:ArchiveRelation['kind'],label:string,detail?:string):ArchiveRelation=>({kind,label,detail});
const project=(p:ArchiveProject)=>p;
export const archiveBatch299:Record<string,ArtistArchive>={
  'wolfgang-tillmans':{
    artistId:'wolfgang-tillmans',
    projectCoverage:'作品级深化第二批：Lutz & Alex sitting in the trees、Concorde Grid、paper drop fused I / Paper Drop (Star)、Neue Welt、Moon in Earthlight listening-room version。重点补输出版本、系列内部具体作品、纸张/打印工艺、出版与空间观看机制。',
    imageCoverage:'MoMA、ifa、Glenstone、Moderna Museet 等提供对应作品或展览图，但作品版权仍归 Wolfgang Tillmans/相关权利方。本批记录官方图片页面、尺寸和版权状态；未确认自由再发布授权的图像不复制进仓库，明确保持暂缺。',
    note:'这一批继续把 Tillmans 从“日常摄影+随意挂墙”的概括拆成作品级生产与流通：同一图像可以出现为不同尺寸/不同打印时间的 chromogenic print 或 inkjet；系列可以被编辑成网格、书页、展墙；纸本身也可以被卷曲后重新摄影；数字相机与高解析度则直接改变 Neue Welt 的观看逻辑。',
    projects:[
      project({title:'Lutz & Alex sitting in the trees',cluster:'portrait / youth culture / variable print formats',period:'1992; later prints',summary:'Tillmans 1992年拍摄朋友 Lutz 与 Alex 在树上的肖像。作品并非只有一个固定物质版本：ifa 档案记录同一图像存在 2080×1380 mm inkjet print，以及 610×508、406×305、215×150、150×100 mm 等 chromogenic prints；MoMA 馆藏版本则是2012年印制的 61×50.8 cm chromogenic print。图像因此既属于九十年代亲密朋友与青年文化的摄影语境，也通过后来不断变化的打印尺寸进入不同展墙结构。',actions:['1992年直接拍摄 Lutz 与 Alex 在树上的身体，而非搭景重演。','保留同一图像在不同时间重新打印的可能，使作品不是单一固定尺寸对象。','根据展览语境使用大型 inkjet 或较小 chromogenic print，使人物与观众身体的尺度关系发生变化。','在群组式挂墙中与其他朋友、俱乐部、静物和日常图像建立非线性关系。'],sourceUrl:'https://www.moma.org/collection/works/164451',images:[],relations:[rel('收藏','MoMA — 1254.2012.11.x1-x2','Chromogenic print, printed 2012；61 × 50.8 cm；页面明确标注 © 2026 Wolfgang Tillmans。'),rel('档案','ifa Agora — Fragile travelling exhibition','记录同图像 inkjet 与多种 chromogenic print 尺寸，证明其可变输出体系。')]}),
      project({title:'Concorde Grid',cluster:'serial observation / aviation / photographic grid',period:'1997',summary:'Concorde Grid 来自 Tillmans 对协和式客机反复观察形成的系列，而不是一次决定性的航空摄影。最终作品以多张照片组成规则网格，让飞机在远处天空、城市边缘和不同飞行阶段重复出现；观看重点从单张飞机照片转向时间、追踪和重复。Tate Britain 2013 的 Looking at the View 展示了该组，由 Zabludowicz Collection 赠予 Tate。网格结构要求观众既退后读取整体序列，又靠近逐张辨认飞机在天空中的尺度变化。',actions:['在不同地点和时刻持续追踪并拍摄 Concorde，而不是安排一次航空摄影。','从大量观察图像中编辑出系列，使飞机的重复出现成为时间结构。','把独立照片组织成规则 grid，取消单张图像作为唯一中心。','在展墙上以整体矩阵呈现，使观看者在总览和逐格阅读之间切换。'],sourceUrl:'https://www.zabludowiczcollection.com/loans/view/concorde-grid-by-wolfgang-tillmans-is-currently-on-display-at-tate-britain-in-looking-at-the-view',images:[],relations:[rel('收藏','Tate — gift from Zabludowicz Collection','2013 Tate Britain 展示资料确认作品进入 Tate。'),rel('展览','Looking at the View — Tate Britain — 12 Feb–2 Jun 2013','借展记录保存对应 installation view。')]}),
      project({title:'paper drop fused I / Paper Drop (Star)',cluster:'paper as subject / C-print / studio construction',period:'2006',summary:'Paper Drop 系列把纸本身变成被摄影对象：Tillmans 将纸张弯曲、卷起，使正反面、阴影和反光形成近乎抽象的空间，再把这一临时纸雕塑重新摄影并输出为大型 C-print。Glenstone 的 paper drop fused I 为2006年 C-print，213.36×144.78 cm；Paper Drop (Star) 的图像达到135×200 cm，并以艺术家框装呈现。纸同时承担工作室可塑材料、镜头前对象和最终摄影平面的多重身份。',actions:['在工作室中弯曲/卷起纸张，制造临时环状、折叠和阴影结构。','通过摄影把三维纸曲面再次压回二维图像。','将结果放大输出为大型 C-print，使轻薄纸获得接近建筑尺度的视觉重量。','部分版本使用 artist’s frame，使“纸的图像”再次成为有边界实体。'],sourceUrl:'https://www.glenstone.org/artworks/paper-drop-fused-i',images:[],relations:[rel('收藏','Glenstone — paper drop fused I','2006；C-print；84×57 in / 213.36×144.78 cm。'),rel('版本','Paper Drop (Star) — 2006','C-print in artist’s frame；image 135×200 cm；edition 1 + 1 AP。')]}),
      project({title:'Neue Welt',cluster:'digital photography / global circulation / book-to-wall editing',period:'2008–2012',summary:'Neue Welt 是 Tillmans 约四年的全球拍摄项目。Moderna Museet 指出标题既指市场、贸易、政治经济与“超现代”世界，也指他开始使用的新数字相机：相机捕捉的细节甚至超过裸眼即时感知。作品把商品、技术、建筑、街道、人物和资本流通并置。2012 Kunsthalle Zürich 展览与 Taschen 出版物构成重要成形节点；2013 Andrea Rosen 的 from Neue Welt 又从四年材料中重新选择作品，并加入 FESPA Digital / FRUIT LOGISTICA 的128页墙面。',actions:['跨地区持续拍摄市场、商品、人物、基础设施、政治经济和技术环境。','改用高解析数字相机，把过量细节本身变成观看问题。','从四年图像中编辑出版物和展览，而不是按旅行日志顺序排列。','在不同展览重新选择、缩放和组合图像；纽约版本另将128页印刷页面作为整墙材料加入。'],sourceUrl:'https://www.modernamuseet.se/en/stockholm/exhibitions/wolfgang-tillmans/',images:[],relations:[rel('展览','Kunsthalle Zürich — 2012','Neue Welt 项目的关键博物馆展示。'),rel('出版','Neue Welt — Taschen — 2012','摄影项目以书的编辑结构形成另一版本。'),rel('展览','from Neue Welt — Andrea Rosen Gallery — 4 May–22 Jun 2013','重新选择四年项目，并展示 FESPA Digital / FRUIT LOGISTICA 128页墙面。')]}),
      project({title:'Moon in Earthlight — audiovisual listening room',cluster:'sound / album / museum listening architecture',period:'2021; MoMA 2022–23',summary:'Moon in Earthlight 是 Tillmans 2021年的首张全长专辑，约53分钟，结合 spoken word、环境现场录音与电子节拍。到 MoMA 的 To look without fear，它不再只是可在家播放的音乐文件，而被转化为美国博物馆首次呈现的 audiovisual listening room：观众进入专门空间，把“听”作为与看摄影同等级的持续行为。这个版本使 Tillmans 长期拍摄俱乐部、舞池和共同聆听的实践反过来成为声音与空间本身。',actions:['在疫情时期为主制作并编辑 spoken word、field recordings 与 electronic beats，形成53分钟专辑。','不把音乐仅作为摄影展背景声，而为博物馆版本建立独立 listening room。','让观众停留并持续聆听，使观看路线出现一个以时间和声音为主的空间。','把早期对 rave、club、dance party 的摄影关注转换成直接声音生产与共同聆听。'],sourceUrl:'https://www.moma.org/calendar/exhibitions/5443',images:[],relations:[rel('展览','Wolfgang Tillmans: To look without fear — MoMA — 2022–23','展览资料将其描述为该 audiovisual listening room 的首次美国博物馆呈现。'),rel('媒介','Moon in Earthlight — 2021','约53分钟；spoken word、ambient field recordings、electronic beats。')]})
    ],
    awards:[],
    exhibitions:['Wolfgang Tillmans: Fragile — travelling exhibition','Wolfgang Tillmans: To look without fear — MoMA — 2022–23'],
    sources:[{label:'MoMA — Lutz & Alex sitting in the trees',url:'https://www.moma.org/collection/works/164451'},{label:'ifa Agora — Lutz & Alex sitting in the trees',url:'https://agora.ifa.de/en/work/lutz-alex-sitting-in-the-trees-93075'},{label:'Zabludowicz Collection — Concorde Grid at Tate Britain',url:'https://www.zabludowiczcollection.com/loans/view/concorde-grid-by-wolfgang-tillmans-is-currently-on-display-at-tate-britain-in-looking-at-the-view'},{label:'Glenstone — paper drop fused I',url:'https://www.glenstone.org/artworks/paper-drop-fused-i'},{label:'Moderna Museet — Wolfgang Tillmans / Neue Welt',url:'https://www.modernamuseet.se/en/stockholm/exhibitions/wolfgang-tillmans/'},{label:'MoMA — Wolfgang Tillmans: To look without fear',url:'https://www.moma.org/calendar/exhibitions/5443'}]
  }
};
