import type { ArtistArchive, ArchiveRelation } from './archiveData';
const rel=(kind:ArchiveRelation['kind'],label:string,detail?:string):ArchiveRelation=>({kind,label,detail});

const catala='https://www.labiennale.org/en/art/2019/partecipants/antoine-catala';
const catalaHeart='https://www.antoinecatala.com/projects/the-heart-atrophies';
const cheng='https://www.labiennale.org/en/art/2019/partecipants/ian-cheng';
const chengBob='https://iancheng.com/bob';
const condo='https://www.labiennale.org/en/art/2019/partecipants/george-condo';
const condoDouble='https://hyperallergic.com/navigating-the-overload-at-the-venice-biennale/';
const dacorte='https://www.labiennale.org/en/art/2019/partecipants/alex-da-corte';
const dacorteWhitney='https://whitney.org/collection/works/62947';
const dacorteLouisiana='https://louisiana.dk/en/exhibition/alex-da-corte/';

export const archiveBatch117:Record<string,ArtistArchive>={
  'venice-antoine-catala':{artistId:'venice-antoine-catala',projectCoverage:'2 个 Venice 2019 communication-system 节点已建立深档案 · 2018–2019',imageCoverage:'0 / 2 项目暂不使用不稳定外链图像',note:'Catala 不是简单把 emoji/文字做成雕塑，而是逐个拆解 message carrier：architecture、advertising、science、fashion、air pressure、silicone surface 都被当成“意义如何到达身体”的传输系统。当前覆盖 Venice 2019 两件核心装置；更早 communication-platform 项目尚未逐件展开。',projects:[{title:'The Heart Atrophies',cluster:'rebus / hologram / soft robotics / industrial knit / communication platform',period:'2018–2019',summary:'四组对象分别对应 THE / HEART / A / TROPHIES，并把 architecture、advertising、science、fashion 四个影响情绪习惯的领域压进一件 contemporary rebus。high-tech 与 lo-fi 制作并存，意义不是写出来而是经材料、动作与平台习惯被身体化。',actions:['以 stanchion banner 打印 “The”，借公共空间/非场所 architecture 作为第一组 sign carrier','在 human-scale plexiglass hood 内播放不断变化的 heart holograms，让 medical illustration 与 cartoon emoji 来回切换','制作 silicone soft-robot “A”，通过 air pump 的充放气让字母笨拙、不可预测地运动','制作三件带 trophy motif 的 wool sweaters，并以工业生产复制“手工瑕疵”','把四种互不相同的 transmission technology 排成可被解读但无法一次稳定解码的 rebus','把研究焦点从 message content 转向 platform / carrier 如何反过来塑造使用者'],sourceUrl:catalaHeart,images:[],relations:[rel('展览','May You Live In Interesting Times — Venice Biennale 2019','Arsenale')]},{title:"It's Over",cluster:'coloured silicone / pneumatic relief text / reassuring-message failure',period:'2019',summary:'Central Pavilion 入口的九块大型 coloured-silicone panels 通过缓慢抽走空气才显露 embossed phrases；“Don’t worry”“Everything is ok”等安慰性话语因此像由机械呼吸临时维持，安慰与焦虑发生反转。',actions:['制作九块大尺寸 coloured-silicone panels','在 silicone 表面预置 embossed text / image','以 pneumatic system 缓慢抽走空气，令文字逐渐显现','混用英语、意大利语 reassuring phrases 与 teddy-bear image','把 reading 变成一个需要等待 pressure change 的时间过程','利用 message 与 transmission mechanism 的矛盾，让安慰话语本身显得不稳定'],sourceUrl:catala,images:[],relations:[rel('展览','May You Live In Interesting Times — Venice Biennale 2019','Central Pavilion entrance')]}],awards:[],exhibitions:['May You Live In Interesting Times — Venice Biennale 2019'],sources:[{label:'La Biennale · Antoine Catala 2019',url:catala},{label:'Antoine Catala Studio · The Heart Atrophies',url:catalaHeart}]},

  'venice-ian-cheng':{artistId:'venice-ian-cheng',projectCoverage:'2 个 artificial-life / live-simulation 节点已建立深档案 · 2018–2019',imageCoverage:'0 / 2 项目暂不使用不稳定外链图像',note:'Cheng 的核心制作动作是“先设定可运作规则，再撤回固定结局”：live simulation 被允许在 exhibition time 中持续突变。BOB 进一步把 viewer tutoring 接到 AI architecture 上。当前覆盖 BOB 与 Life After BOB: First Tract；更早 Emissaries 系列尚未逐件补齐。',projects:[{title:'BOB (Bag of Beliefs)',cluster:'artificial life / live simulation / AI demons / viewer tutoring / iOS app',period:'2018–2019',summary:'BOB 是 branching-serpent 形态的 artificial lifeform。其 body、mind、personality 随 surprise 持续变化；内部由多个 motivating “demons” 与能从 sensory experience 学习 rule-based beliefs 的 neurosymbolic inductive engine 共同驱动。观众通过 BOB Shrine app 提供 offerings 与 parental lessons，因而真正介入行为发展。',actions:['以 Unity / real-time simulation 构建持续运行的 artificial life environment','将行为系统拆成多个 obsessively pursuing micro-story 的 motivating demons','加入能从 sensory experience 归纳 rule-based beliefs 的 neurosymbolic learning layer','不给 simulation 设定传统 narrative ending，让 BOB 在 lifetime 中经历 accident、failure、death 与再次出现','开发 BOB Shrine iOS app，让 viewer 选择 offering 并附上 parental lesson','把 app 输入转成持续 stimuli，使 audience influence 成为 creature development 的一部分'],sourceUrl:chengBob,images:[],relations:[rel('展览','May You Live In Interesting Times — Venice Biennale 2019','Central Pavilion'),rel('出版','Metis Suns production / BOB project documentation','2018–2019 production credits and project site')]},{title:'Life After BOB: First Tract',cluster:'narrative-universe preview / simulation-derived world building',period:'2019',summary:'Arsenale 展示的 First Tract 作为 BOB narrative universe 的 preview，不把 artificial life 当孤立技术演示，而把它扩成能够承载角色、社会关系与后续 narrative 的世界。',actions:['从 BOB artificial-life system 向 narrative universe 扩展','把 simulation-generated logic 转译为可被观众进入的 story-world preview','让 Central Pavilion 的 live creature 与 Arsenale 的 narrative tract 构成两种观看模式','保留开放性，使作品不是对 BOB 的最终解释而是后续 universe 的入口'],sourceUrl:cheng,images:[],relations:[rel('展览','May You Live In Interesting Times — Venice Biennale 2019','Arsenale')]}],awards:[],exhibitions:['May You Live In Interesting Times — Venice Biennale 2019'],sources:[{label:'La Biennale · Ian Cheng 2019',url:cheng},{label:'Ian Cheng Studio · BOB',url:chengBob}]},

  'venice-george-condo':{artistId:'venice-george-condo',projectCoverage:'2 个 painting-history / fractured-figuration 节点已建立深档案 · early 1980s–2019',imageCoverage:'0 / 2 项目暂不使用不稳定外链图像',note:'Condo 的 Venice 2019 档案目前以 Double Elvis 为具体作品锚点，再向回连到 fake Old Masters / Artificial Realism 的长期方法史。官方页面没有给出全部展出作品清单，因此不把此条标成 Venice presentation 全覆盖。',projects:[{title:'Double Elvis',cluster:'large-scale painting / Warhol citation / fractured social portrait',period:'2019',summary:'Arsenale 入口附近的大尺幅 painting 重新处理 Warhol 的 Elvis icon：两个相对人物被粗粝、破碎的人体与银色表面重写。作品把 recognizable art-historical reference 与不稳定、近躁狂的当代身体状态压在同一画面。',actions:['调用 Warhol Double Elvis 这一高度 recognizable art-historical image 作为结构记忆','以 acrylic、gesso、metallic paint 与 pigment stick 在 linen 上建立约四米级画面','保留银色/metallic ground 对 Warhol silkscreen visual memory 的暗示','用断裂、重叠、近 caricature 的 facial/body marks 破坏 icon 的稳定性','让两个人物既像 doubled celebrity 又像互相对饮/对峙的 ordinary unstable bodies','将 historical quotation 转成对 present social mania / ambiguity 的 painting device'],sourceUrl:condoDouble,images:[],relations:[rel('展览','May You Live In Interesting Times — Venice Biennale 2019','Arsenale')]},{title:'Fake Old Masters → Artificial Realism',cluster:'appropriation / art-history recombination / psychological cubism',period:'early 1980s–2019',summary:'Condo 早期从“fake Old Masters”入手，故意制造看似历史、却带现代错位的图像；在 1980s Paris 进一步形成 Artificial Realism，即拆散既有 reality，再用同一批视觉部件构造新的 reality。',actions:['研究 Old Master portrait / genre conventions，而不是直接复制单一名作','抽取既有 painting languages 中的 facial type、pose、brush vocabulary','通过错配、夸张、重组制造“像历史作品但不可能来自历史”的画面','把 cubist fragmentation、cartoon distortion 与 classical composition 放进同一人物','在 1995 返回 New York 后把 boom/bust、hysteria、paranoia 等社会情绪转译成人物心理形变','将 appropriation 从引用技巧转成长期 image-reconstruction system'],sourceUrl:condo,images:[],relations:[rel('展览','May You Live In Interesting Times — Venice Biennale 2019','Central Pavilion / Arsenale; official practice framing')]}],awards:[],exhibitions:['May You Live In Interesting Times — Venice Biennale 2019'],sources:[{label:'La Biennale · George Condo 2019',url:condo},{label:'Hyperallergic · Double Elvis at Venice 2019',url:condoDouble}]},

  'venice-alex-da-corte':{artistId:'venice-alex-da-corte',projectCoverage:'2 个 Venice 2019 world-building 节点已建立深档案 · 2018–2019',imageCoverage:'0 / 2 项目暂不使用不稳定外链图像',note:'Da Corte 的“appropriation”不是收集 reference 后拼贴，而是为 reference 重新造 scenography、身体、尺度与观看家具。当前覆盖 Venice 2019 两个核心节点；57 个 Rubber Pencil Devil chapter 尚未逐章拆解。',projects:[{title:'Rubber Pencil Devil',cluster:'57-chapter video / hand-built scenography / pop-TV embodiment / neon installation',period:'2018–2019 Venice presentation',summary:'长时段 colour/sound video 由 57 个 short-film chapters 组成。Da Corte 为每一段手工搭建独立 scenography，并亲自化妆扮演多个 TV / cartoon archetypes；Venice 以 neon-lit oversized viewing environment 让 seated viewer 相对屏幕与道具显得缩小。',actions:['为 57 个 film chapters 分别设计并 hand-build unique scenographies','从 Mister Rogers、Pink Panther、cartoon / children’s TV 与 camp Americana 抽取角色和 visual code','亲自穿 costume / makeup 扮演多种 recognizable figures，而不是只剪辑 archival footage','以故意缓慢 choreography 把熟悉娱乐形象拉入 melancholy / alienation','使用 aluminum、neon、rubber、automotive paint、velvet、glass、vinyl、foam、plexiglas、plywood、speakers、monitors、folding chairs 等材料构造 viewing installation','通过 oversized saturated environment 与 bench seating 改变观众身体尺度'],sourceUrl:dacorteLouisiana,images:[],relations:[rel('展览','57th Carnegie International — Carnegie Museum of Art','2018–2019'),rel('展览','May You Live In Interesting Times — Venice Biennale 2019','Arsenale')]},{title:'The Decorated Shed',cluster:'miniature suburb replica / Mister Rogers / corporate-sign contamination / scale inversion',period:'2019',summary:'Central Pavilion 中，Da Corte 精确复制 Mister Rogers’ Neighborhood 的 miniature suburban village，并放在 Federal-style mahogany table 上，再加入 corporate restaurant-chain signage。与 Arsenale 的 oversized world 相反，这里 viewer 被变成观察微缩家庭生活的“巨人”。',actions:['研究并复制 Mister Rogers’ Neighborhood 中 miniature suburban American village','按模型尺度重建 houses / domestic arrangement，而非仅展示 TV still','将 miniature village 放置在 Federal-style mahogany table 上，使 model 与 furniture history 发生碰撞','额外加入 corporate restaurant chain signage，污染原有 wholesome-neighborhood memory','安排 viewer 从上方/外部观看 miniature lives，主动制造 giant-viewer scale relation','用同一届展览中的 macro / micro 两种尺度反转，测试 nostalgia、consumer signage 与身份记忆'],sourceUrl:dacorte,images:[],relations:[rel('展览','May You Live In Interesting Times — Venice Biennale 2019','Central Pavilion')]}],awards:[],exhibitions:['57th Carnegie International — 2018–2019','May You Live In Interesting Times — Venice Biennale 2019'],sources:[{label:'La Biennale · Alex Da Corte 2019',url:dacorte},{label:'Whitney · Rubber Pencil Devil',url:dacorteWhitney},{label:'Louisiana Museum · Alex Da Corte / Rubber Pencil Devil',url:dacorteLouisiana}]}
};
