import type { ArtistArchive, ArchiveRelation } from './archiveData';

const rel = (kind: ArchiveRelation['kind'], label: string, detail?: string): ArchiveRelation => ({ kind, label, detail });

export const archiveBatch48: Record<string, ArtistArchive> = {
  'paz-errazuriz': {
    artistId: 'paz-errazuriz', projectCoverage: '6 个长期社群 / 身体 / 边缘空间节点已建立深档案 · 1979–现在', imageCoverage: '0 / 6 项目已有代表图像',
    note: 'Errázuriz 的方法不是“找边缘人群拍摄”，而是先建立长期关系，再用黑白肖像和持续返回抵抗新闻式猎奇。她在独裁时期长期进入拳击馆、精神病院、跨性别社群和老人生活空间。',
    projects: [
      { title: 'La Manzana de Adán / Adam’s Apple', cluster: 'trans community / dictatorship / long-term portrait', period: '1980s', summary: '在智利独裁时期长期拍摄跨性别性工作者社群。项目依靠持续往返、信任与近距离黑白肖像建立，而不是单次采访。', actions: ['长期进入同一社群', '与被摄者建立反复见面的关系', '在室内与街道使用黑白胶片', '保持近距离但不使用夸张广角猎奇', '让人物主动决定姿态与衣着', '以摄影书和系列而非新闻单图完成'], sourceUrl: 'https://www.pazerrazuriz.com/', images: [], relations: [rel('出版', 'La Manzana de Adán', '1990')] },
      { title: 'El Infarto del Alma', cluster: 'psychiatric hospital / affection / collaboration', period: '1990s', summary: '与 Diamela Eltit 合作，在 Putaendo 精神病院拍摄病患之间的情侣与亲密关系。摄影不以“病”为奇观，而把触摸、依靠和配对作为主体。', actions: ['长期进入医院', '与作家共同研究语境', '寻找已经存在的伴侣关系', '使用双人肖像和近距离构图', '让身体接触代替诊断标签', '以图文书共同完成'], sourceUrl: 'https://www.pazerrazuriz.com/', images: [], relations: [rel('出版', 'El Infarto del Alma', '1994')] },
      { title: 'Boxers', cluster: 'boxing gym / male body / serial portrait', period: '1980s', summary: '在拳击馆拍摄训练中的男性身体，关注疲惫、伤痕与职业化身体，而非比赛胜负。', actions: ['长期进入拳击馆', '在训练前后拍摄人物', '使用自然 / 场馆光线', '记录汗液、伤痕、等待状态', '以重复正面肖像形成类型比较'], sourceUrl: 'https://www.pazerrazuriz.com/', images: [], relations: [] },
      { title: 'Dormidos / Sleeping', cluster: 'sleep / vulnerability / public-private boundary', period: '1980s–1990s', summary: '拍摄睡眠中的人物，把警觉被撤下后的身体状态变成肖像。', actions: ['寻找愿意在睡眠状态被拍摄的人', '在真实居住 / 休息环境拍摄', '降低灯光与相机干预', '保留床铺和周围空间', '让人物失去“为镜头表演”的正面控制'], sourceUrl: 'https://www.pazerrazuriz.com/', images: [], relations: [] },
      { title: 'Old age / social invisibility', cluster: 'ageing / institutional life / body', period: '1990s–2000s', summary: '她持续拍老年人与被机构化身体，把衰老从抽象社会议题变成具体皮肤、姿态与生活空间。', actions: ['进入养老 / institutional spaces', '反复拍摄同一群体', '使用近距离黑白肖像', '让身体细节和环境同等重要', '避免“悲惨”式说明构图'], sourceUrl: 'https://www.pazerrazuriz.com/', images: [], relations: [] },
      { title: 'Long-term relation as method', cluster: 'meta-method / trust / anti-spectacle', period: '1979–现在', summary: '她最稳定的工作方法是时间：先建立关系、重复返回，再决定图像。', actions: ['选择长期可返回的社群', '把进入权限当作创作前提', '减少一次性事件摄影', '让被摄者逐渐熟悉相机', '通过摄影书和系列保存时间跨度'], sourceUrl: 'https://www.pazerrazuriz.com/', images: [], relations: [] }
    ], awards: ['Hasselblad Award 2017'], exhibitions: ['Venice Biennale — Chile Pavilion 2015', 'Fundación MAPFRE retrospective'], sources: [{ label: 'Paz Errázuriz', url: 'https://www.pazerrazuriz.com/' }, { label: 'Fundación MAPFRE', url: 'https://www.fundacionmapfre.org/en/art-and-culture/exhibitions/historical/year-2015/paz-errazuriz/' }]
  },

  'graciela-iturbide': {
    artistId: 'graciela-iturbide', projectCoverage: '6 个长期纪实 / 仪式 / 象征节点已建立深档案 · 1970s–现在', imageCoverage: '0 / 6 项目已有代表图像',
    note: 'Iturbide 的“象征性”不是预先设计符号。她通常长期生活 / 返回一个地方，让鸟、仪式、市场、衣服和身体关系从现实中自己长出来。',
    projects: [
      { title: 'Juchitán de las Mujeres', cluster: 'women / market / community / long-term documentary', period: '1979–1988', summary: '长期在 Juchitán 与当地女性、市场和仪式共同生活拍摄，形成她最重要的长期系列。', actions: ['长期居住 / 返回同一社群', '在市场与家庭环境拍摄', '使用黑白胶片', '让人物在熟悉环境中自主姿态', '把肖像、仪式、动物和日常劳动混编'], sourceUrl: 'https://www.getty.edu/art/collection/person/103KB9', images: [], relations: [] },
      { title: 'Nuestra Señora de las Iguanas', cluster: 'portrait / everyday object / emergent symbol', period: '1979', summary: 'Juchitán 系列中的经典肖像来自市场现实而非造型设定：鬣蜥成为头部冠饰般形态。', actions: ['在市场现场观察人物', '不另搭景', '选择正面机位', '让动物与人物共同构成轮廓', '以系列语境而非孤立“图标”理解'], sourceUrl: 'https://www.getty.edu/art/collection/person/103KB9', images: [], relations: [] },
      { title: 'Birds / Ojos para volar', cluster: 'birds / chance / mortality / recurring motif', period: '1970s–现在', summary: '鸟在其作品中反复出现，既来自现实观察，也逐渐成为自由、死亡和偶然的视觉母题。', actions: ['在不同旅行中持续记录鸟群 / 单鸟', '接受偶然进入画面的鸟', '通过后期编辑跨年份建立重复关系', '不把鸟固定为单一象征解释'], sourceUrl: 'https://www.gracielaiturbide.org/', images: [], relations: [] },
      { title: 'Frida Kahlo’s Bathroom', cluster: 'closed room / objects / absence / commission', period: '2006', summary: 'Casa Azul 封闭多年的浴室开放后，她拍摄 Kahlo 的衣物、义肢、药物和日常物件，以缺席身体建立肖像。', actions: ['进入长期封闭空间', '不拍完整“名人房间”全景', '逐件拍摄遗留物', '使用黑白压低博物馆综合色彩', '通过物件 sequence 形成 absent portrait'], sourceUrl: 'https://www.gracielaiturbide.org/', images: [], relations: [] },
      { title: 'India / landscape and ritual', cluster: 'travel / ritual / cross-cultural observation', period: '1990s–2000s', summary: '她在印度等地继续用同样的长期观察方法处理仪式与日常，不把异文化简化成“异国奇观”。', actions: ['长期旅行而非短期打卡', '优先观察生活关系和仪式结构', '使用相同黑白语言', '避免把综合色服饰作为主要猎奇点', '与墨西哥作品交叉编辑'], sourceUrl: 'https://www.gracielaiturbide.org/', images: [], relations: [] },
      { title: 'Observation before symbol', cluster: 'meta-method / chance / sequence', period: '1970s–现在', summary: '她的符号系统来自现场与编辑：先拍现实，再在多年图像中发现重复。', actions: ['不先写象征清单', '长时间待在同一环境', '允许偶发关系进入画面', '用 contact sheet / archive 回看重复母题', '通过摄影书建立跨项目共鸣'], sourceUrl: 'https://www.gracielaiturbide.org/', images: [], relations: [] }
    ], awards: ['Hasselblad Award 2008'], exhibitions: ['Getty retrospective and major international surveys'], sources: [{ label: 'Graciela Iturbide Studio', url: 'https://www.gracielaiturbide.org/' }, { label: 'Getty', url: 'https://www.getty.edu/art/collection/person/103KB9' }]
  },

  'oscar-munoz': {
    artistId: 'oscar-munoz', projectCoverage: '6 个图像生成 / 消失 / 观看装置节点已建立深档案 · 1980s–现在', imageCoverage: '0 / 6 项目已有代表图像',
    note: 'Muñoz 的关键不是“摄影装置”，而是让图像保持不稳定：呼吸才出现、水一干就消失、粉末漂散、热量改变表面。记忆因此被改写成一个物理过程。',
    projects: [
      { title: 'Narcisos', cluster: 'water / charcoal dust / self-portrait / evaporation', period: '1990s–', summary: '将自画像通过模板以炭粉撒在水面。水蒸发后图像会移动、裂开、沉积，肖像无法保持固定。', actions: ['制作自画像 stencil', '把水倒入透明容器', '将炭粉通过模板撒到水面', '允许水流 / 蒸发改变面部', '记录不同阶段', '把残留沉积作为作品状态'], sourceUrl: 'https://www.banrepcultural.org/oscar-munoz/protografias', images: [], relations: [] },
      { title: 'Aliento', cluster: 'breath / polished metal / latent portrait / viewer activation', period: '1995', summary: '在抛光金属圆盘上制作几乎不可见的已故 / 失踪者肖像；观众呼气后水汽短暂显像。', actions: ['选择报纸 / 档案中的肖像', '将图像转移到抛光金属表面', '平时让表面像镜子', '要求观众靠近并呼气', '利用 condensation 让图像短暂显现', '水汽消失后恢复镜面'], sourceUrl: 'https://www.tate.org.uk/art/artists/oscar-munoz-26755', images: [], relations: [] },
      { title: 'Biografías', cluster: 'screenprint / water / drain / image loss', period: '2000s', summary: '肖像被印在水面或湿表面，随后随水流向排水口而变形、消失。', actions: ['把肖像制成丝网版', '在可流动水面印刷', '让图像短暂保持', '释放水流', '让顔面被拉伸 / 冲散', '以视频或现场装置记录'], sourceUrl: 'https://www.banrepcultural.org/oscar-munoz/protografias', images: [], relations: [] },
      { title: 'Línea del destino', cluster: 'water held in hand / projection / impossible retention', period: '2006', summary: '把人脸影像投射到手掌中的水，水从指缝漏走时肖像同步消失。', actions: ['在手中盛水', '把肖像投影到水面', '让手保持短暂静止', '允许水自然从指缝流失', '把“无法保存”交给身体完成'], sourceUrl: 'https://www.jeudepaume.org/en/evenement/oscar-munoz-protographies/', images: [], relations: [] },
      { title: 'Protographies', cluster: 'retrospective / expanded photography / unstable image', period: '2010s', summary: '大型展览把其长期方法归纳为 protography：图像处于摄影之前 / 之后的生成状态。', actions: ['把摄影、视频、版画和装置放在同一谱系', '按图像显现 / 消失机制分组', '让作品在展期持续变化', '强调过程而非静态保存'], sourceUrl: 'https://www.jeudepaume.org/en/evenement/oscar-munoz-protographies/', images: [], relations: [rel('展览', 'Protographies — Jeu de Paume', '2014')] },
      { title: 'Viewer as image apparatus', cluster: 'meta-method / participation / material process', period: '1990s–现在', summary: '观众的呼吸、距离、等待和触摸经常成为显影装置的一部分。', actions: ['设计必须靠近才能读取的作品', '让呼吸 / 水汽参与成像', '让观看时间决定图像持续多久', '拒绝“永久照片”的稳定假设'], sourceUrl: 'https://www.tate.org.uk/art/artists/oscar-munoz-26755', images: [], relations: [] }
    ], awards: [], exhibitions: ['Protographies — Jeu de Paume 2014'], sources: [{ label: 'Tate — Oscar Muñoz', url: 'https://www.tate.org.uk/art/artists/oscar-munoz-26755' }, { label: 'Jeu de Paume — Protographies', url: 'https://www.jeudepaume.org/en/evenement/oscar-munoz-protographies/' }, { label: 'Banco de la República', url: 'https://www.banrepcultural.org/oscar-munoz/protografias' }]
  },

  'santu-mofokeng': {
    artistId: 'santu-mofokeng', projectCoverage: '6 个摄影散文 / 灵性 / 档案研究节点已建立深档案 · 1980s–2000s', imageCoverage: '0 / 6 项目已有代表图像',
    note: 'Mofokeng 反对把 apartheid 下的黑人生活压缩成冲突新闻。他通过通勤、宗教、家庭档案、乡村地景和“精神性”建立摄影散文。',
    projects: [
      { title: 'Train Church', cluster: 'commuter train / worship / everyday spirituality', period: '1986', summary: '在每日往返 Soweto—Johannesburg 的通勤列车上拍乘客自发歌唱、祈祷与集体礼拜。', actions: ['在自己日常通勤路线持续拍摄', '不额外搭建宗教场景', '在拥挤车厢用黑白快速摄影', '记录手势、唱歌和集体状态', '将交通空间读成临时教堂'], sourceUrl: 'https://santumofokengfoundation.com/santu-mofokeng-bibliography', images: [], relations: [] },
      { title: 'Chasing Shadows', cluster: 'spiritual landscape / caves / pilgrimage / essay', period: '1990s', summary: '把洞穴、宗教集会和地景作为精神经验与 apartheid 社会现实的交叉空间。', actions: ['长期访问宗教 / 朝圣地点', '拍摄地景与人群', '使用低调黑白综合色阶', '将信仰经验与社会空间并置', '以摄影散文和文字共同完成'], sourceUrl: 'https://santumofokengfoundation.com/santu-mofokeng-bibliography', images: [], relations: [] },
      { title: 'The Black Photo Album / Look at Me: 1890–1950', cluster: 'family archive / self-representation / slide projection', period: '1997', summary: '从南非黑人家庭收集殖民时期委托制作的工作室肖像，研究被摄者如何主动想象自己的阶级与身份。', actions: ['寻找家庭保存的历史肖像', '记录人物 / 家庭背景', '重新复制原照片', '保留服装、姿势、布景作为社会信息', '制作80张35mm幻灯片投影', '以文字说明恢复被摄者主体性'], sourceUrl: 'https://www.moma.org/collection/works/488818', images: [], relations: [rel('收藏', 'MoMA', 'Slide projection, 1997')] },
      { title: 'Trauma Landscapes', cluster: 'historical violence / ordinary landscape / caption', period: '1990s–2000s', summary: '拍看似普通的地景，但地点承载 apartheid 暴力、强制迁徙或历史创伤。', actions: ['研究具体历史地点', '拍摄当下普通景观', '避免灾难遗迹猎奇', '用标题 / 文字恢复事件层', '让“看不见”成为作品结构'], sourceUrl: 'https://santumofokengfoundation.com/', images: [], relations: [] },
      { title: 'Labour Tenants / Going Home', cluster: 'rural life / labour / migration / return', period: '1980s–1990s', summary: '通过乡村劳动租户和返乡经验拍城市化之外的黑人生活结构。', actions: ['长期访问家庭 / 乡村社区', '拍住宅、劳动与地景', '把人物和土地放在同一叙事', '以摄影散文而非单事件报道组织'], sourceUrl: 'https://santumofokengfoundation.com/santu-mofokeng-bibliography', images: [], relations: [] },
      { title: 'Photographic essay as counter-news', cluster: 'meta-method / slow documentary / text', period: '1980s–2000s', summary: '他的稳定方法是用多张、文字与长期关系反对“决定性新闻图像”垄断黑人经验。', actions: ['选择非新闻热点的生活结构', '持续返回', '保留安静画面', '用文字扩展图像而非解释图像', '按主题摄影散文编辑'], sourceUrl: 'https://santumofokengfoundation.com/', images: [], relations: [] }
    ], awards: [], exhibitions: [], sources: [{ label: 'Santu Mofokeng Foundation', url: 'https://santumofokengfoundation.com/' }, { label: 'Bibliography', url: 'https://santumofokengfoundation.com/santu-mofokeng-bibliography' }, { label: 'MoMA — Black Photo Album', url: 'https://www.moma.org/collection/works/488818' }]
  },

  'namsa-leuba': {
    artistId: 'namsa-leuba', projectCoverage: '6 个编排肖像 / 仪式再现 / 时尚凝视节点已建立深档案 · 2010–现在', imageCoverage: '0 / 6 项目已有代表图像',
    note: 'Leuba 的方法是把 documentary、fashion、performance 混合，用高度编排的人体重新测试“西方如何想象非洲”。她不是把传统元素直接搬进时尚，而是故意制造身份识别上的不稳定。',
    projects: [
      { title: 'Ya Kala Ben', cluster: 'Guinea / ritual object / staged portrait / crossed gaze', period: '2011', summary: '在 Guinea 研究仪式雕像与 cosmology，再让真人在自然环境中成为这些精神对象的当代化身。', actions: ['研究当地 ritual statues / cosmology', '与当地参与者合作', '设计包裹身体的综合色服装 / 道具', '在自然环境中搭建姿态', '使用时尚摄影式灯光与构图', '故意让 documentary 背景与虚构人物冲突'], sourceUrl: 'https://www.namsaleuba.com/', images: [], relations: [] },
      { title: 'Zulu Kids / South Africa', cluster: 'youth / costume / identity', period: '2010s', summary: '在南非驻留中继续处理青年、身体与传统视觉的重新编排。', actions: ['与年轻被摄者合作', '使用综合色服装 / 身体造型', '把传统引用放进当代青年姿态', '避免民族志式静态记录'], sourceUrl: 'https://www.namsaleuba.com/', images: [], relations: [] },
      { title: 'Weke', cluster: 'Benin / spirituality / fashion-performance', period: '2017', summary: '在 Benin 继续把 spiritual references 与 fashion / performance 交叉。', actions: ['进行地方视觉研究', '制作高度人工服装', '把人物放在真实环境', '用色彩与姿态增强异质感', '让作品同时像时尚广告和仪式图像'], sourceUrl: 'https://www.namsaleuba.com/', images: [], relations: [] },
      { title: 'Illusions', cluster: 'Tahiti / LGBTQ+ models / exoticism / staged nature', period: '2019', summary: '在 Tahiti 与 LGBTQ+ 模特合作，把 lush nature 与人工造型并置，直接测试“异域身体”的西方想象。', actions: ['邀请当地LGBTQ+被摄者', '共同设计服装 / 姿态', '使用热带自然作为真实背景', '故意放大综合色彩与身体装饰', '让 beauty 与 strangeness 同时出现'], sourceUrl: 'https://www.mbal.ch/en/expo/namsa-leuba/', images: [], relations: [] },
      { title: 'Crossed Looks', cluster: 'monograph / retrospective edit / five bodies of work', period: '2021', summary: '首本 monograph 把 Guinea、Benin、Nigeria、South Africa、Tahiti 等五大系列重新并置，明确把“crossed gaze”变成长期方法。', actions: ['跨十年重看不同系列', '按项目而非商业 / 艺术二分编辑', '保留黑白与综合色彩并置', '将 fashion editorial 与个人项目放入同一语境', '通过书籍建立跨地域比较'], sourceUrl: 'https://www.namsaleuba.com/resume', images: [], relations: [rel('出版', 'Crossed Looks — Damiani', '2021'), rel('展览', 'Halsey Institute solo exhibition', '2021')] },
      { title: 'Crossed gaze as method', cluster: 'meta-method / documentary + fashion + performance', period: '2011–现在', summary: 'Leuba 的稳定结构是“真实地点 + 人工身体 + 多重观看传统”。', actions: ['先研究地方 visual codes', '与真实人物合作', '主动制造服装 / 姿态', '保留现实环境', '用 commercial image polish 增加观看冲突', '通过系列比较不同文化语境'], sourceUrl: 'https://www.namsaleuba.com/', images: [], relations: [] }
    ], awards: ['Foam Paul Huf Award nominee', 'Prix Pictet nominee'], exhibitions: ['Crossed Looks — Halsey Institute 2021'], sources: [{ label: 'Namsa Leuba', url: 'https://www.namsaleuba.com/' }, { label: 'Resume', url: 'https://www.namsaleuba.com/resume' }, { label: 'MBAL', url: 'https://www.mbal.ch/en/expo/namsa-leuba/' }]
  },

  'yee-i-lann': {
    artistId: 'yee-i-lann', projectCoverage: '6 个 photomedia / 殖民档案 / 社群编织节点已建立深档案 · 1990s–现在', imageCoverage: '0 / 6 项目已有代表图像',
    note: 'Yee I-Lann 的变化很关键：早期通过 digital photomontage 拆解殖民视觉，后来逐步转向与 Sabah 女性编织者合作，让“图像重写”进入真实劳动、语言和社区关系。',
    projects: [
      { title: 'Sulu Stories', cluster: 'colonial archive / Sulu zone / digital photomontage', period: '2000s', summary: '使用殖民照片与 Sulu 区域历史材料，通过数字拼贴重新安排人物、海域与权力关系。', actions: ['搜集殖民时期图像 / 地图', '数字扫描历史照片', '切割人物与背景', '重新组合尺度和空间', '让档案原权力结构出现明显错位'], sourceUrl: 'https://www.silverlensgalleries.com/artists/yee-i-lann', images: [], relations: [] },
      { title: 'Picturing Power', cluster: 'colonial photography / staged archive / power choreography', period: '2013', summary: '以殖民摄影的站位、服装和等级关系为基础制作 photographic assemblages，直接处理谁坐、谁站、谁拥有中央位置。', actions: ['研究殖民摄影构图', '抽取人物 / 家具 / 建筑元素', '数字重排前后层级', '放大權力姿态的荒诞性', '用系列比较多种殖民观看机制'], sourceUrl: 'https://kunstmuseumthun.ch/wp-content/uploads/2025/08/kmt_2502_ausstellungyee_i_lann_saaltext_a4_en_gzd5.pdf', images: [], relations: [] },
      { title: 'Tikar / mat collaborations', cluster: 'woven mat / women’s labour / community authorship', period: '2010s–现在', summary: '与 Sabah 不同社群女性编织者长期合作，把 mat 从日用品转成水平、集体、非等级化的知识空间。', actions: ['与编织社群建立长期合作', '共同讨论文字 / 图案主题', '使用 pandanus / plastic 等地方材料', '由多位女性共同完成大型 mat', '在展览中让 mat 保持水平 / 可聚集属性', '明确共享作者与生产关系'], sourceUrl: 'https://www.silverlensgalleries.com/artists/yee-i-lann', images: [], relations: [] },
      { title: 'TIKAR/MEJA/PLASTIK', cluster: 'mat / table / plastic / installation', period: '2023', summary: '把 tikar（席）、meja（桌）、plastik（废弃塑料）三种日常物转成权力与共同体隐喻。', actions: ['选择三种具有社会象征的材料 / 物件', '将编织席与桌结构并置', '加入塑料废弃物 / 工业材料', '在墙面与地面同时安装', '让水平共享与垂直权力形成冲突'], sourceUrl: 'https://kunstmuseumthun.ch/wp-content/uploads/2025/08/kmt_2502_ausstellungyee_i_lann_saaltext_a4_en_gzd5.pdf', images: [], relations: [] },
      { title: 'Fluid World', cluster: 'batik / influence / resistance / fabric', period: '2020s', summary: '使用 batik wax 的“阻染”机制讨论文化影响与抵抗：蜡既阻止染料，又因裂纹让颜色渗入。', actions: ['与 textile makers 合作', '在布面上施 wax resist', '允许裂纹渗色', '把工艺物理机制当作政治隐喻', '以大尺幅织物进入展览空间'], sourceUrl: 'https://kunstmuseumthun.ch/wp-content/uploads/2025/08/kmt_2502_ausstellungyee_i_lann_saaltext_a4_en_gzd5.pdf', images: [], relations: [] },
      { title: 'From image appropriation to shared production', cluster: 'meta-method / community / decolonial authorship', period: '1990s–现在', summary: '她的长期转向是从“我如何重排殖民图像”变成“谁一起生产新的视觉 / 物质结构”。', actions: ['前期依靠摄影档案研究', '逐渐增加地方语言和材料', '与社群共同设计作品', '把作者关系写进生产过程', '让摄影不再是唯一最终媒介', '用 textile / mat / installation 扩展 photomedia'], sourceUrl: 'https://www.silverlensgalleries.com/artists/yee-i-lann', images: [], relations: [] }
    ], awards: [], exhibitions: ['Picturing Power 2013', 'Mansau-Ansau — Kunstmuseum Thun 2025'], sources: [{ label: 'Silverlens — Yee I-Lann', url: 'https://www.silverlensgalleries.com/artists/yee-i-lann' }, { label: 'Kunstmuseum Thun 2025', url: 'https://kunstmuseumthun.ch/wp-content/uploads/2025/08/kmt_2502_ausstellungyee_i_lann_saaltext_a4_en_gzd5.pdf' }]
  }
};
