import type { ArtistArchive, ArchiveProject, ArchiveRelation } from './archiveData';
const rel=(kind:ArchiveRelation['kind'],label:string,detail?:string):ArchiveRelation=>({kind,label,detail});
const project=(p:ArchiveProject)=>p;
export const archiveBatch298:Record<string,ArtistArchive>={
  'laia-abril':{
    artistId:'laia-abril',
    projectCoverage:'深化既有 Laia Abril，不新增艺术家：重点补 A History of Misogyny 第三章 On Mass Hysteria、2026 Endometriosis 与 Luto，并把 Photo Elysée / Finnish Museum of Photography / Le Bal / Foam / Aperture 的策展、出版和奖项关系串成研究网络。',
    imageCoverage:'艺术家官网、Foam、Aperture 与 Photo Elysée 均提供项目图像；本批保存权威来源页与作品结构，不把版权图像复制进仓库。',
    note:'Abril 的关键不是把“女性议题”拍成系列，而是先识别一个制度性失语区，再决定什么媒介能让不可见经验获得证据形式。她从新闻/编辑训练出发，把摄影、档案、证词、医学史、声音、录像、出版和空间安装组织成研究系统。On Mass Hysteria 进一步把身体症状理解为社会压力下的“原型语言”；Endometriosis 把不可见慢性疼痛转成拒绝临床式完整身体的碎片肖像；Luto 则把哀悼从私人情感重新定义为规范身体与欲望的公共制度。',
    projects:[
      project({title:'On Mass Hysteria — A History of Misogyny, Chapter Three',cluster:'functional symptoms / gendered medicine / research installation / proto-language of protest',period:'2016–2025',summary:'项目起点非常具体：Abril 2016年在尼泊尔研究 Menstruation Myths 时读到一篇2003年学校女生集体昏厥的报道，随后追踪全球及历史上的类似事件。她把通常被称作 possession、mysterious illness 或 mass psychogenic illness 的现象放回性别、劳动、殖民医学和社会压力中，而不是只把它们解释成个体病理。项目尤其借鉴人类学家 Aihwa Ong 对1970年代马来西亚女工昏厥事件的分析，将身体症状理解为在压迫结构中可能出现的非自觉抗议语言。Abril 有意保留“hysteria”这一带有子宫/厌女历史的词，并将其反向占用为一种集体表达痛苦与韧性的语言。',actions:['从一则尼泊尔学校集体昏厥报道建立研究入口，再扩展到跨地域、跨历史案例。','并置医学分类、社会学/人类学解释、灵性信仰、跨代创伤与当事人的梦、情绪和预感。','避免把症状仅作为奇观化的身体图像，而让文本、证词和研究材料承担解释结构。','把“hysteria”从历史性的贬损标签重新编码为身体在制度性失语中的表达机制。','将研究同时发展为展览、录像与2024年摄影书，使不同媒介承担不同证据功能。'],sourceUrl:'https://www.laiaabril.com/project/on-mass-hysteria/',images:[],relations:[rel('展览','Photo Elysée, Lausanne','30 Jun–1 Oct 2023；curated by Nathalie Herschdorfer；与 Le Bal、Finnish Museum of Photography、Les Filles du Calvaire 联合制作。'),rel('展览','Finnish Museum of Photography, Helsinki','2024；第三章机构联合制作网络。'),rel('展览','Le Bal, Paris','2025；第三章联合制作网络。'),rel('出版','On Mass Hysteria: A Proto-language of Protest','Dewi Lewis + Delpire &Co, 2024；design Nicola Poli；supported by Photo Elysée + Le Bal。'),rel('奖项','Prix Elysée','项目发展阶段入围；2019 Nominees’ Book 保存模型、图表、准备图像及艺术家/策展人交流。'),rel('奖项','Rencontres d’Arles PhotoBook Award','2025 shortlist — On Mass Hysteria。')]}),
      project({title:'Endometriosis — The Silenced Pain',cluster:'chronic pain / medical invisibility / fragmented portrait / institutional neglect',period:'2026',summary:'Endometriosis 是 On Mass Hysteria 的直接延伸，但把问题从集体症状转向长期、不可见的慢性疼痛。Abril 与七位患有致残性子宫内膜异位症的人合作，问题不是“怎样把疼痛拍出来”，而是当临床影像期待身体成为完整、清楚、可诊断对象时，艺术如何拒绝这种可读性。她在受访者暂时缓解疼痛的时刻拍摄碎片化身体，让 endurance、dissociation 和为了与疼痛共处而形成的身体适应取代完整肖像；官网同时明确记录照片被艺术家的眼泪 varnish。项目把生理疼痛、妇产科历史暴力、研究不足和制度忽视放进同一知识政治框架。',actions:['与七位长期遭受致残性 endometriosis 的参与者合作，而非以单一病例代表疾病。','在疼痛暂时缓解的时刻摄影，避免把发作中的身体直接奇观化。','通过碎片化构图抵抗临床影像要求身体“完整、清楚、可读”的观看逻辑。','以艺术家的眼泪为照片上光，把作者身体材料加入作品表面。','将疾病缺乏研究、无治愈方案与妇产科历史中的制度性忽视连接起来。'],sourceUrl:'https://www.laiaabril.com/project/endometriosis/',images:[],relations:[rel('展览','Museo del Romanticismo, Madrid','2026'),rel('展览','Annely Juda Fine Art, London','2026')]}),
      project({title:'Luto',cluster:'mourning / performance / Lorca / gendered social control',period:'2026',summary:'Luto 从 Federico García Lorca 的《The House of Bernarda Alba》出发，把 mourning 处理成一种社会控制技术，而不是私人情绪。Abril 将黑衣视为规定身体、可见性、欲望和行为的社会编码，并把表演放在 Lorca 遇害地点附近：黑色衣物被悬置于景观中，使原剧作中的家庭内部纪律重新进入公共空间和历史暴力现场。项目由现场表演、摄影与9分39秒单通道录像构成；摄影三联总体约230 × 389 cm。三个媒介分别组织身体、声音、景观与记忆，使“哀悼”成为仍在塑造当下的政治结构。',actions:['从 Lorca 剧作及其遇害历史建立文学—政治研究入口。','把黑色丧服视为社会规范身体与欲望的代码，而不是仅作为视觉符号。','在 Lorca 遇害地点附近进行表演，将私人/家庭哀悼移到公共景观。','悬置黑衣，使缺席身体通过服装、风景和动作被间接呈现。','将同一研究拆为 live performance、摄影三联与9:39单通道录像，让媒介差异参与叙事。'],sourceUrl:'https://www.laiaabril.com/project/luto/',images:[],relations:[rel('展览','Conservatorio di Musica Benedetto Marcello, Venice','2026 Venice Biennale opening week；The Art Hub Collective commissioned project。'),rel('策展','The Art Hub Collective','Commissioned Luto, 2026。')]}),
      project({title:'Research-to-institution network — journalism → FABRICA → photobook → museum co-production',cluster:'practice evolution / editorial method / institution network',period:'2009–2026',summary:'Abril 的方法演变与机构网络高度相关。她2009年完成 Journalism 学位后进入 FABRICA 驻留，并在 COLORS Magazine 担任 researcher、editor 与 staff photographer 至2014年前后；这解释了她为什么长期把编辑、事实核查、文字和图像序列视为同一作品系统。A History of Misogyny 之后又从单一作者研究转向机构共同生产：On Abortion 经 Arles、Aperture与Deutsche Börse体系扩散；On Rape 获 Magnum Foundation / Tim Hetherington Trust 支持并在 Foam 展出；On Mass Hysteria 则由 Photo Elysée、Finnish Museum of Photography、Le Bal 等共同生产。机构在这里不是履历装饰，而是研究、制作、出版和传播的基础设施。',actions:['以新闻学训练建立调查、采访、编辑和事实核查能力。','在 FABRICA / COLORS 的编辑环境中发展图像—文字并置与长篇视觉叙事。','把长期研究拆成章节，使每一章可以同时成为展览、书、声音/录像和公共讨论。','通过基金会、摄影机构和博物馆联合制作，让高成本研究跨多年推进。','利用摄影书保存高密度证据结构，同时让展览通过声音、物件与空间建立身体经验。'],sourceUrl:'https://www.laiaabril.com/about/long-bio/',images:[],relations:[rel('展览','Foam — On Rape','6 Nov 2020–27 Jun 2021；Foam Paul Huf Award exhibition。'),rel('奖项','Foam Paul Huf Award','2020 winner；A History of Misogyny。'),rel('奖项','Paris Photo–Aperture PhotoBook of the Year','2018 winner — On Abortion。'),rel('奖项','Deutsche Börse Photography Foundation Prize','2019 finalist — On Abortion。'),rel('奖项','RPS Hood Medal','2019。'),rel('奖项','Spain National Photography Award','艺术家官方长传记记录为最年轻获奖者。'),rel('收藏','Centre Pompidou / Moderna Museet / Reina Sofía / V&A / MACBA / MoCP / Photo Elysée / Fotomuseum Winterthur','艺术家官方长传记列出的主要公共收藏网络。')]}),
    ],
    awards:['Foam Paul Huf Award — 2020','Paris Photo–Aperture PhotoBook of the Year — On Abortion — 2018','Deutsche Börse Photography Foundation Prize — finalist — 2019','RPS Hood Medal — 2019','Spain National Photography Award — official biography records Abril as youngest recipient'],
    exhibitions:['On Mass Hysteria — Photo Elysée, Lausanne — 30 Jun–1 Oct 2023','On Mass Hysteria — Finnish Museum of Photography — 2024','On Mass Hysteria — Le Bal — 2025','Endometriosis — Museo del Romanticismo, Madrid — 2026','Endometriosis — Annely Juda Fine Art, London — 2026','Luto — Conservatorio di Musica Benedetto Marcello, Venice — 2026'],
    sources:[{label:'Laia Abril — On Mass Hysteria',url:'https://www.laiaabril.com/project/on-mass-hysteria/'},{label:'Laia Abril — Endometriosis',url:'https://www.laiaabril.com/project/endometriosis/'},{label:'Laia Abril — Luto',url:'https://www.laiaabril.com/project/luto/'},{label:'Laia Abril — long biography',url:'https://www.laiaabril.com/about/long-bio/'},{label:'Laia Abril — On Mass Hysteria at Photo Elysée',url:'https://www.laiaabril.com/exhibition/masshysteria-elyse/'},{label:'Foam — Laia Abril artist profile',url:'https://www.foam.org/artists/laia-abril'},{label:'Foam — On Rape exhibition',url:'https://www.foam.org/events/laia-abril-on-rape-a-history-of-misogyny-chapter-two'},{label:'Aperture — Laia Abril / On Abortion',url:'https://archive.aperture.org/article/2016/4/4/laia-abril'},{label:'Aperture — A Hidden History of Abortion',url:'https://aperture.org/editorial/pbr-14-abortion/'}]
  }
};
