import type { ArtistArchive, ArchiveProject, ArchiveRelation } from './archiveData';
const rel=(kind:ArchiveRelation['kind'],label:string,detail?:string):ArchiveRelation=>({kind,label,detail});
const p=(x:ArchiveProject)=>x;
export const archiveBatch324:Record<string,ArtistArchive>={
'thomas-ruff':{artistId:'thomas-ruff',projectCoverage:'4 个作品/具体节点：jpegs；jpegs ny；Nacht 2 I；jpeg ea01。',imageCoverage:'David Zwirner 与 MoMA 官方页面均提供对应作品/安装图；MoMA 明确要求通过 Art Resource / Scala 获得复制授权，Zwirner页面未确认第三方再发布许可，因此本站记录官方图像入口和版权状态，实体图片暂缺，不以替代图填充。',note:'重点补 Ruff 如何把互联网压缩图像、夜视技术和巨幅输出转化为摄影的物质结构，并记录2026纽约展览对2004–05 jpegs ny的重新编排。',projects:[
p({title:'jpegs — series',cluster:'internet-source image / digital manipulation / monumental chromogenic print',period:'2004–2009',summary:'Ruff 没有把网络图像当作需要恢复清晰度的低质量素材，而是先建立互联网图像档案，再从战争、自然灾害、技术景观和田园图像等类别中选择文件。他用数字方法改变文件结构：进一步提高压缩、降低每厘米像素数，并在部分图像中调整颜色；随后把原本适合屏幕观看的小型 JPEG 放大成接近十九世纪历史画尺度的巨幅摄影。放大并没有消除压缩痕迹，反而把方块状像素、模糊边缘和信息缺失变成观众首先看见的视觉材料。近看时图像趋向色块和网格，退远后原始新闻/风景主题重新变得可辨。David Zwirner记录多个具体版本使用chromogenic print与Diasec，因此“JPEG”并非只停留在数字文件，而最终被固定成大型实体摄影表面。',actions:['从互联网搜集并分类现成数字图像','选择战争、灾难、自然、城市与技术景观等题材','通过提高压缩、降低pixel-per-centimeter并调整颜色改变数字文件结构','把低分辨率源图放大到约2–3米尺度','以chromogenic print输出，多个版本使用Diasec装裱','利用观看距离使像素抽象与可辨图像之间发生转换'],sourceUrl:'https://www.davidzwirner.com/artists/thomas-ruff/survey/jpegs',images:[],relations:[rel('作品','jpeg ea01','2007；chromogenic print with Diasec；249.9 × 184.8 cm；edition 3 + 2 AP'),rel('作品','jpeg mo01','2009；chromogenic print with Diasec；247 × 185.1 cm'),rel('出版','Thomas Ruff: jpegs','Aperture，2009；132页、65幅彩色复制图'),rel('展览','Image rights','David Zwirner官方页面提供逐件作品图；未确认本站第三方再发布授权，图片暂缺')] }),
p({title:'jpegs ny — 2004/2005 works, 2026 New York installation',cluster:'appropriated 9/11 web imagery / compressed JPEG / large-format print',period:'2004–2005 / reinstalled 2026',summary:'Ruff 2001年9月11日在纽约并曾自行拍摄，但回德国后发现相机没有留下图像。2004年他转而从互联网寻找世贸中心袭击的流通图像。这里的关键动作不是简单“挪用新闻照片”：他重新改变文件结构，提高压缩、降低像素密度并加入颜色，再把这些本来作为网络信息快速流通的小图放大到历史画般尺度。2026年David Zwirner纽约展览重新集合12件jpegs ny，在事件25周年语境中让它们作为一个组被观看；近距离首先出现机械像素格，远距离才恢复燃烧建筑、烟云等事件图像。2005年画廊记录jpeg ny05为C-Print with Diasec，283 × 168 cm。',actions:['从互联网重新寻找9/11相关图像而非使用自己失败的现场底片','修改压缩率、pixel density和颜色','把网络小图放大成巨幅C-print/chromogenic print','部分作品使用Diasec形成平整高光表面','2026年把12件作品重新组合成纽约展览','通过近看像素/远看事件图像建立两种观看尺度'],sourceUrl:'https://www.davidzwirner.com/exhibitions/2026/thomas-ruff-jpegs-ny',images:[],relations:[rel('作品','jpeg ny05','2004；C-Print with Diasec；283 × 168 cm'),rel('展览','David Zwirner New York — jpegs ny','10 Sep–17 Oct 2026；12件作品'),rel('展览','Art Basel Unlimited','2026；该组作品此前在Unlimited展出'),rel('展览','Image rights','官方页面含逐件与2026安装图；版权/再发布许可未确认，本站图片暂缺')] }),
p({title:'Nacht 2 I',cluster:'night-vision photography / chromogenic print',period:'1992',summary:'Nacht系列把军事与监控技术中的夜视视觉转进艺术摄影。Ruff在低照度环境中拍摄城市/建筑场景，使通常依赖可见光的摄影转成绿色、低细节、带技术噪声感的夜视图像；作品不是把普通夜景后期染绿，而是以夜视设备的成像逻辑作为摄影条件。MoMA馆藏Nacht 2 I最终以chromogenic print呈现，尺寸138.7 × 144.6 cm，接近方形且远大于设备屏幕，使原本功能性的监控视觉成为需要在墙前停留观看的摄影对象。',actions:['在夜间/低照度条件中使用夜视成像技术拍摄','接受设备造成的绿色调、低细节和技术性视觉特征','把功能性监控/军事观看方式转译为静态摄影','最终制作大型chromogenic print并墙面展示'],sourceUrl:'https://www.moma.org/collection/works/177477',images:[],relations:[rel('收藏','MoMA','Chromogenic print；138.7 × 144.6 cm；Gift of Dr. Mathias Boehringer'),rel('展览','Image rights','© Thomas Ruff / ARS / VG Bild-Kunst；MoMA要求复制作品图联系Art Resource或Scala，本站图片暂缺')] }),
p({title:'jpeg ea01',cluster:'specific jpegs object / chromogenic print with Diasec',period:'2007',summary:'这件作品可作为jpegs系列的具体物质样本理解：数字源图经过Ruff的压缩/像素结构处理后，并没有停留在显示器，而被输出为249.9 × 184.8 cm的chromogenic print，再与Diasec结合。如此巨大的尺寸让压缩造成的方块不再是“图像缺陷”，而成为近距离可逐块观看的表面结构；观众后退时，色块才重新聚合成图像。画廊记录该作edition of 3 + 2 AP，并在背面签名、标题、日期和编号。',actions:['选择并数字处理互联网来源图像','保留/强化JPEG压缩与低像素结构','输出大型chromogenic print','使用Diasec装裱','以限量版摄影对象进入展览与收藏系统'],sourceUrl:'https://www.davidzwirner.com/artworks/thomas-ruff-jpeg-ea01-1102d',images:[],relations:[rel('作品','尺寸/版本','249.9 × 184.8 cm；edition 3 + 2 AP；verso signed/titled/dated/numbered'),rel('展览','Image rights','David Zwirner官方作品页有对应图像；未确认第三方再发布授权，本站图片暂缺')] })
],awards:[],exhibitions:['Thomas Ruff: New Work — David Zwirner New York — 2005','Thomas Ruff: jpegs ny — David Zwirner New York — 2026'],sources:[{label:'David Zwirner — jpegs survey',url:'https://www.davidzwirner.com/artists/thomas-ruff/survey/jpegs'},{label:'David Zwirner — jpegs ny 2026',url:'https://www.davidzwirner.com/exhibitions/2026/thomas-ruff-jpegs-ny'},{label:'MoMA — Nacht 2 I',url:'https://www.moma.org/collection/works/177477'},{label:'David Zwirner — jpeg ea01',url:'https://www.davidzwirner.com/artworks/thomas-ruff-jpeg-ea01-1102d'}]}
};