import type { ArtistArchive, ArchiveProject, ArchiveRelation } from './archiveData';

const rel=(kind:ArchiveRelation['kind'],label:string,detail?:string):ArchiveRelation=>({kind,label,detail});
const project=(p:ArchiveProject)=>p;

export const archiveBatch289:Record<string,ArtistArchive>={
  'thomas-demand':{
    artistId:'thomas-demand',
    projectCoverage:'作品级深化批次：从 Demand 的纸模型—摄影基本方法下钻到 Room、Control Room、Pacific Sun、Dailies 与其巡展空间版本，重点记录来源图像、1:1纸/纸板建模、拍摄/逐格动画、模型销毁、最终输出与观众尺度。',
    imageCoverage:'5 / 5 节点均核到 MoMA、MFAH、LACMA、Getty、NGV、UCCA 等机构的对应作品图或安装图。相关图像均仍受 Thomas Demand / VG Bild-Kunst / ARS 等版权保护，本批不复制受限图像，images 保持暂缺；官方图像入口与版权信息写入 relations。',
    note:'Demand 的关键不是简单“拍纸模型”，而是把已经被媒体、机构或个人影像中介过的场景重新做成接近实物尺度的无文字、无细节纸模型，再以摄影或逐格动画把模型重新压回二维图像。模型通常在拍摄后销毁，因此最终照片/影片既像档案，又没有直接拍摄原现场。',
    projects:[
      project({title:'Room (Zimmer)',cluster:'paper model / media image / chromogenic photograph',period:'1996',summary:'Demand 以一张既有照片为来源，重新搭建 L. Ron Hubbard 在1972–73年居住和工作的酒店房间。模型不是为了作为雕塑永久保存，而是作为摄影现场：纸材重做床、枕头、桌面、闹钟、打字机等对象，同时故意消除真实物件上的细部——例如钟面没有数字、打字机没有按键。完成模型后再以均匀棚灯摄影，使成片第一眼近似真实室内照片，但折痕、光滑表面和缺失细节暴露其人工性。MoMA 馆藏最终对象为 chromogenic color print，172 × 232 cm。',actions:['从既有房间照片而非真实酒店现场出发。','以纸和纸板重新制作房间、家具及桌面物件。','主动省略钟面数字、打字机按键等信息性细节，使模型处在“像真的但无法被使用”的状态。','布光并拍摄模型，把三维手工构造重新转成二维摄影。','最终保留大型 chromogenic print；纸模型不作为最终作品展示。'],sourceUrl:'https://www.moma.org/collection/works/57201',images:[],relations:[rel('馆藏','MoMA','1996；chromogenic color print；172 × 232 cm；Gift of the Nina W. Werblow Charitable Trust。'),rel('图片','MoMA artwork / installation views','官方页面提供作品/历史安装图入口；Copyright © Artists Rights Society (ARS), New York / VG Bild-Kunst, Bonn，故不复制。')]}),
      project({title:'Control Room (Kontrollraum)',cluster:'Fukushima / reconstruction / chromogenic print',period:'2011',summary:'作品源于2011年3月福岛第一核电站事故后流通的一张控制室照片。MFAH 说明该来源图由电力公司内部人员秘密拍摄并在媒体传播；Demand 没有去核电站做纪实摄影，而是根据这张已经政治化、媒体化的图像，以纸和纸板按接近真人尺度重建控制室，再拍摄模型。最终画面因此是“现实—内部快照—纸模型—摄影”的多重转译。MFAH 馆藏为 chromogenic print，图像/纸张均约200 × 300.4 cm；NGV 展览记录 C-Print / Perspex 版本为200 × 300 cm。',actions:['选择福岛事故后媒体传播的控制室内部快照作为来源。','根据二维来源图推回空间结构，以纸和纸板制作真人尺度控制台、屏幕、墙面与设备。','不进入真实事故现场，而是在工作室完成替代性现场。','完成模型后摄影，并以约2 × 3米的大型彩色摄影输出，使观看尺度接近建筑/现场。'],sourceUrl:'https://emuseum.mfah.org/objects/129930/control-room',images:[],relations:[rel('馆藏','Museum of Fine Arts Houston','2011；chromogenic print；200 × 300.4 cm；页面明确说明 life-size cardboard-and-paper model 与来源图像。'),rel('版本','NGV 2012–13','展览记录 Kontrollraum / Control Room 为 C-Print / Perspex，200 × 300 cm。'),rel('图片','MFAH / NGV official image','© Artists Rights Society (ARS), New York / VG Bild-Kunst, Bonn；NGV 亦标 VG Bild-Kunst/VISCOPY，未复制受限文件。')]}),
      project({title:'Pacific Sun',cluster:'stop-motion / life-size paper set / video projection',period:'2012',summary:'Demand 从 YouTube 上流传的邮轮 Pacific Sun 在南太平洋风暴中餐厅 CCTV 录像出发。与静态作品不同，他必须重做“运动”：团队花数月制作真人尺度纸/纸板餐厅，把桌椅、瓶子、餐具等物件逐格移动，删除原录像中的人，再逐帧拍摄。Getty 记录12人动画团队和约2,400帧；LACMA 馆藏记录作品为 single-channel video projection with sound，2944 frames，主体100秒并含黑场间隔，投影尺寸约374.65 × 500.38 cm。声音是在影片完成后制作，用来重新唤起滚动物件与海浪。',actions:['取得并研究邮轮餐厅监控录像中风暴造成的物体运动。','用纸和纸板按真人尺度重建餐厅及桌椅、瓶罐等大量对象。','删除原 CCTV 中的人，只保留物体受船体摇摆驱动的运动逻辑。','由动画团队逐次移动纸模型中的物件并逐帧摄影，形成 stop-motion。','影片完成后再制作声轨；最终以接近建筑尺度的单频道投影包围观众。'],sourceUrl:'https://collections.lacma.org/object/184289',images:[],relations:[rel('馆藏','LACMA / Israel Museum joint acquisition','2012；single-channel video projection with sound；约100秒主体、2944 frames，投影约374.65 × 500.38 cm。'),rel('制作','Getty Research Institute','Getty 记录作品历时数月、12人动画团队、纸/纸板真人尺度模型及逐格制作流程。'),rel('图片','LACMA official production still','官方展览页标 © Thomas Demand, VG Bild-Kunst, Bonn/ARS, New York；Courtesy Matthew Marks Gallery；不复制。')]}),
      project({title:'Dailies — small-scale dye-transfer series',cluster:'phone snapshot / everyday / paper reconstruction / dye transfer',period:'2008–2020',summary:'Dailies 把 Demand 通常与新闻史、灾难和政治现场相关的大型重建方法转向日常手机快照。他先用手机记录不起眼的临时场景——例如被塞进围栏的杯子、晾衣、邮件或街头残留物——再在工作室把这些微小场景重新做成纸模型并摄影。与大型历史题材不同，最终成品保持相对亲密的尺寸；公开展览资料记录 Daily #20 (2012) 为 framed dye transfer print，53.8 × 68.6 cm。系列因此把“媒体图像→模型→照片”的机制缩小到个人视觉记忆和随手拍。',actions:['先以手机拍摄城市/日常生活中容易被忽略的临时构图。','从手机照片重新制作纸模型，而不是直接把手机照片作为作品。','重新摄影模型，使偶然现场变成经过手工重构的图像。','采用较小尺幅和 dye-transfer 等精细摄影输出，使观看方式从远距离面对纪念碑式图像转向近距离阅读。'],sourceUrl:'https://ucca-group.com/en/exhibition/thomas-demand-the-stutter-of-history/',images:[],relations:[rel('系列','UCCA — The Stutter of History','UCCA 将 Dailies 与大型历史图像区分，说明其来源为日常手机照片，并在展览中与 Model Studies、Pacific Sun 并置。'),rel('作品参数','Daily #20','公开画廊展览资料记录 2012；Framed Dye Transfer Print；53.8 × 68.6 cm。'),rel('图片','UCCA / gallery installation and work images','对应作品图仍受 © Thomas Demand / VG Bild-Kunst 保护，本批仅记录入口。')]}),
      project({title:'The Stutter of History — UCCA spatial version',cluster:'exhibition architecture / wallpaper / temporary structure / moving image',period:'2022',summary:'Demand 的作品在回顾展中并非被动挂墙。UCCA 明确把展览设计视为其创作方法的一部分：艺术家利用纺织物、壁纸和临时建筑结构组织观众路径，把大型历史摄影、较小的 Dailies、Model Studies 与 moving-image 作品分成不同观看尺度。Pacific Sun 被放进四层专门搭建的 cinema-like intervention，使原本可作为单频道影片存在的作品在这里获得封闭、沉浸式的电影空间；观众由近距离观看小幅照片转向进入临时建筑观看大尺度投影。',actions:['参与整个回顾展空间设计，而非只交付单件作品。','用 wallpaper、textiles 与 temporary structures 区分作品群并控制观看距离。','为 Pacific Sun 在四层展厅专门搭建 cinema-like intervention。','通过空间尺度变化把手机快照来源的小型 Dailies、建筑模型研究与大型历史摄影/动画组织成一条观看路径。'],sourceUrl:'https://ucca-group.com/en/exhibition/thomas-demand-the-stutter-of-history/',images:[],relations:[rel('展览','UCCA Center for Contemporary Art','Thomas Demand: The Stutter of History；官方说明展览设计是其 conceptual approach 的组成部分。'),rel('版本差异','Pacific Sun — museum projection vs cinema-like intervention','LACMA 强调 full-scale projection；UCCA 则把影片放入四层专门建造的 cinema-like 空间，改变观众与投影的空间关系。'),rel('图片','UCCA official exhibition images','官方页面有展览/安装图；版权受限，未复制进仓库。')]})
    ],
    exhibitions:['Thomas Demand — MoMA, 2005','Thomas Demand — NGV, 2012–2013','Thomas Demand: Pacific Sun — LACMA, 2014–2015','Thomas Demand: The Stutter of History — UCCA, 2022'],
    sources:[{label:'MoMA — Room (Zimmer)',url:'https://www.moma.org/collection/works/57201'},{label:'MFAH — Control Room',url:'https://emuseum.mfah.org/objects/129930/control-room'},{label:'LACMA Collections — Pacific Sun',url:'https://collections.lacma.org/object/184289'},{label:'Getty Research Institute — Pacific Sun',url:'https://www.getty.edu/research/exhibitions_events/events/pacific_sun.html'},{label:'UCCA — Thomas Demand: The Stutter of History',url:'https://ucca-group.com/en/exhibition/thomas-demand-the-stutter-of-history/'},{label:'NGV — Thomas Demand',url:'https://www.ngv.vic.gov.au/exhibition/thomas-demand/'}]
  }
};
