import type { ArtistArchive, ArchiveRelation } from './archiveData';

const rel=(kind:ArchiveRelation['kind'],label:string,detail?:string):ArchiveRelation=>({kind,label,detail});

export const archiveBatch255:Record<string,ArtistArchive>={
'hito-steyerl':{artistId:'hito-steyerl',projectCoverage:'作品级深化：补入 November 与 Red Alert 两个早期关键节点，重点记录旧 Super-8 素材的再剪辑、新闻/示威/类型片素材的并置，以及三屏数字红色视频装置的硬件结构。',imageCoverage:'艺术家官网与 Centre Pompidou 均有对应作品/安装图。November still 标注 © Hito Steyerl；Red Alert 的 Pompidou 安装图为 © Adagp, Paris，摄影 Centre Pompidou, MNAM-CCI/Georges Meguerditchian/Dist. GrandPalaisRmn，图像编号 4N76548。未确认开放再发布许可，故不本地复制。',note:'这两件作品能看到 Steyerl 从 essay film 到“影像的极限状态”的两端：November 通过再剪辑让私人影像、政治图像和类型片互相污染；Red Alert 则把叙事压缩到只剩公共警报色与显示设备。',projects:[
{title:'November',cluster:'essay film / Super-8 archive / found footage / political image circulation',period:'2004',summary:'25分钟 DV 影像。Steyerl 从自己17岁时与 Andrea Wolf 拍摄的女权武打 Super-8 影片出发：Wolf 当时扮演穿皮衣、骑摩托的女性战士，后来真实加入库尔德武装并于1998年死亡。Steyerl 没有把旧片简单作为传记插图，而是把早期虚构打斗、Wolf 后来的电视采访、德国库尔德示威中流通的 Wolf 肖像、功夫片/类型片片段以及 Bruce Lee 葬礼相关影像重新剪接。于是同一张脸从朋友、演员、政治行动者变成可被复制的革命图标；观看者必须不断判断眼前材料究竟是私人记录、新闻证据、宣传图像还是虚构类型片。',actions:['重新取用1980年代与 Andrea Wolf 拍摄的 Super-8 女权武打片素材。','收集 Wolf 后来作为政治行动者出现的电视采访与其肖像在示威中的传播影像。','加入功夫/类型电影与 Bruce Lee 葬礼等既有电影材料。','通过剪辑让原先的虚构镜头在 Wolf 后来的真实经历之后反过来获得“文献”性质。','最终制作为25分钟 DV essay film，在单屏放映/展览语境中观看。'],sourceUrl:'https://www.hitosteyerl.net/works/november/',images:[],relations:[rel('技术','DV / 25 min','艺术家官网明确记录 2004, DV, 25 min；早期源素材包括 Super-8。'),rel('发行','sixpackfilm','Artist site lists sixpackfilm as distributor.'),rel('图像版权','© Hito Steyerl','Official film still available on artist site; no local copy without republication clearance.')]},
{title:'Red Alert',cluster:'three-screen installation / digital video / monochrome / emergency signal',period:'2007',summary:'Centre Pompidou 馆藏版本是三联数字录像装置：三个30英寸（76.2 cm）平板屏幕，各自循环30秒纯红色视频；三台 Mac mini、安装系统和连接设备共同构成作品，彩色、无声，版次2/3 + 2AP。Steyerl 把纪录影像削减到没有人物、地点或事件，只剩美国国土安全警报系统中“恐袭迫近”的红色，同时借用 Rodchenko 1921年纯色绘画的历史。观众面对的不是红色印刷面，而是持续通电、循环播放的显示设备，因此危机信号被做成一种常驻环境。',actions:['制作三个30秒纯红数字视频循环。','分别由三台 Mac mini 驱动三个30英寸平板显示器。','把三屏作为 triptych 并置，而不是单屏影像。','取消声音与叙事信息，把纪录片的信息量压缩到公共警报色本身。','在不同展场按三联屏的硬件关系重新安装；Pompidou 保存完整 mounting/connection system。'],sourceUrl:'https://www.centrepompidou.fr/en/ressources/oeuvre/coKMgGn',images:[],relations:[rel('收藏','Centre Pompidou','AM 2024-276; digital video for three screens; 30-inch screens; edition 2/3 + 2AP.'),rel('安装图','Centre Pompidou 2016–2017','Photo: Georges Meguerditchian; image ref. 4N76548.'),rel('版权','© Adagp, Paris','Official image route retained; not copied locally.')]}
],awards:[],exhibitions:['documenta 12, Kassel, 2007','Centre Pompidou collection presentation, Paris, 2016–2017'],sources:[{label:'Hito Steyerl studio · November',url:'https://www.hitosteyerl.net/works/november/'},{label:'Centre Pompidou · Red Alert',url:'https://www.centrepompidou.fr/en/ressources/oeuvre/coKMgGn'}]},
'cao-fei':{artistId:'cao-fei',projectCoverage:'作品级深化：补入 Whose Utopia、Haze and Fog、La Town 三个节点，从真实工厂驻留、北京实景僵尸片推进到微缩模型城市摄影。',imageCoverage:'Guggenheim、M+ 与 Mercedes-Benz Art Collection 均提供官方作品图；M+ 明确 © Cao Fei。未取得再发布授权的图像不复制到仓库。',note:'三个节点形成清楚的方法变化：进入真实生产现场并与工人协作；用演员和类型电影改写现实北京；再把整座城市缩成可完全控制的模型摄影棚。',projects:[
{title:'Whose Utopia',cluster:'factory residency / workers / performance / single-channel video',period:'2006',summary:'曹斐在佛山一家灯具工厂驻留并采访工人。影片先以冷静镜头记录生产线、机器和重复劳动，随后让真实工人在同一工业环境中表演自己的个人愿望：有人穿芭蕾服跳舞，有人弹摇滚吉他，有人练太极。关键不是请演员“扮工人”，而是让生产体系里的劳动者暂时把工厂地面变成个人舞台；机器继续存在，梦想动作被直接嵌进劳动空间。',actions:['进入佛山灯具工厂驻留并采访实际工人。','拍摄流水线、机器、照明产品和日常生产动作。','邀请工人在工厂内部实现/表演个人梦想身份。','把芭蕾、摇滚、太极等表演与仍在运作的工业背景并置。','剪辑成单通道录像，使生产纪录与舞台化愿望在同一作品内切换。'],sourceUrl:'https://www.guggenheim.org/artwork/artist/cao-fei',images:[],relations:[rel('研究/收藏来源','Solomon R. Guggenheim Museum','Guggenheim artist record documents factory residency and worker performances.'),rel('关系','Asia One (2018)','Guggenheim explicitly frames Asia One as a later return to industrial production/automation after Whose Utopia.')]},
{title:'Haze and Fog 霾',cluster:'zombie film / Beijing / staged narrative / digital video',period:'2013',summary:'一部46分30秒单通道彩色有声数字录像。曹斐在2013年的北京组织一组彼此断裂的城市人物场景：房地产中介、孕妇与丈夫、偷穿雇主高跟鞋的清洁工、使用助行器的老人等都被放进具体阶层化生活环境，随后部分人物转化为僵尸。她没有把僵尸作为纯粹恐怖片怪物，而是用化妆、表演、场面调度和类型片结构，把“活着但精神死亡”的都市状态物理化。',actions:['在北京城市环境中设置多个阶层不同的人物段落。','使用演员表演房地产、家务、家庭和老年生活等日常动作。','通过僵尸化妆与身体表演让部分人物发生类型片式转化。','把彼此断裂的日常段落剪成一部持续46分30秒的单通道影片。','以普通都市空间而非封闭摄影棚作为社会结构与僵尸隐喻相撞的现场。'],sourceUrl:'https://www.mplus.org.hk/en/collection/objects/haze-and-fog-2016438/',images:[],relations:[rel('收藏','M+ Collection','2013; single-channel digital video, colour, sound; 46 min 30 sec; Mandarin.'),rel('版权','© Cao Fei','M+ provides official image; not locally copied without republication permission.')]},
{title:'La Town',cluster:'miniature city / model railway / staged photography / single-channel video',period:'2014',summary:'41分56秒、16:9、彩色有声单通道录像。与 Haze and Fog 的北京实景不同，La Town 把城市变成可控制的微缩模型世界。镜头穿过黑暗街道、游乐场、喷泉、住宅内部以及最终出现火灾、伤者、抗议与警笛的灾难场景；人物是模型尺度的居民，摄影机则像真正城市电影一样在模型建筑间移动。作品因此把模型铁路式“完美世界”改造成灾后都市摄影棚。',actions:['搭建/组织模型铁路式的微缩城市、住宅、街道、游乐设施和人物。','通过布光把模型分别处理成夜景、白昼与灾难状态。','让摄影机在微缩街区与住宅内部移动，模拟真人尺度城市电影的镜头语言。','在后段加入火灾、伤者、抗议和警笛等灾难线索。','剪辑为41分56秒单通道16:9彩色有声录像。'],sourceUrl:'https://www.mercedes-benz.art/en/artwork/cao-fei-la-town-2014/',images:[],relations:[rel('收藏','Mercedes-Benz Art Collection','2014; one-channel video, 16:9, colour/sound; 41:56 min; acquired 2016.'),rel('版本关系','Haze and Fog → La Town','Collection text explicitly notes the apartment section refers back to Haze and Fog.')]}
],awards:[],exhibitions:['Whose Utopia — 2006','Haze and Fog — 2013','La Town — 2014'],sources:[{label:'Guggenheim · Cao Fei / Whose Utopia',url:'https://www.guggenheim.org/artwork/artist/cao-fei'},{label:'M+ · Haze and Fog',url:'https://www.mplus.org.hk/en/collection/objects/haze-and-fog-2016438/'},{label:'Mercedes-Benz Art Collection · La Town',url:'https://www.mercedes-benz.art/en/artwork/cao-fei-la-town-2014/'}]},
'taryn-simon':{artistId:'taryn-simon',projectCoverage:'作品级深化：将 Paperwork and the Will of Capital 拆成具体照片与雕塑节点，补足花束重建、植物标本、档案纸、桃花心木框与混凝土压花器的制作链。',imageCoverage:'Gagosian 提供完整作品图与安装图并明确 © Taryn Simon；纽约2016安装摄影 Rob McKeever。图像受版权保护，保留官方入口与 credit，不本地复制。',note:'这一批把“外交花束”从主题描述变成制作档案：历史签约照片只是起点，Simon 重新识别花材、重建花束、摄影、压制并保存真实植物，再把外交文件与植物标本并置。',projects:[
{title:'Paperwork and the Will of Capital — Memorandum of Understanding… Cambodia/Australia',cluster:'diplomacy / reconstructed bouquet / archival inkjet / herbarium paper',period:'2015',summary:'Simon 从外交协议签署现场的历史档案照片中寻找摆在政治人物之间的花束，重新识别并制作这些花艺，然后在控制背景前重新摄影。柬埔寨—澳大利亚难民安置谅解备忘录节点最终成为215.9 × 186.1 × 7 cm的大幅 archival inkjet print 与文字，文字印在 archival herbarium paper 上，并装入木框，edition 3 + 2 AP。作品不是展示原始新闻照片，而是把当时几乎被忽略的桌面装饰提升成比人物更大的历史“证人”。',actions:['检索国际协议签署的历史新闻/档案照片。','从照片中识别桌面花束并重新采购/重建对应花材。','在双色控制背景前重新拍摄重建花束。','把外交事件说明印在 archival herbarium paper 上。','制作大幅 archival inkjet print，并以接近董事会家具语汇的木框装裱。'],sourceUrl:'https://gagosian.com/exhibitions/2016/taryn-simon-paperwork-and-the-will-of-capital-new-york/',images:[],relations:[rel('展览','Gagosian New York, 2016','First complete presentation with photographs and sculptures; installation photos Rob McKeever.'),rel('尺寸/版次','215.9 × 186.1 × 7 cm','Edition of 3 + 2 AP.'),rel('版权','© Taryn Simon','Official Gagosian image retained as source; no local copy.')]},
{title:'Paperwork and the Will of Capital — International Islamic Trade Finance Corporation / flower press',cluster:'sculpture / pressed plants / concrete / steel / archival documents',period:'2015',summary:'这一节点把“重建花束”进一步变成实体标本保存装置。Simon 根据2006年科威特 Al-Bayan Palace 签署国际伊斯兰贸易金融公司协议时的花艺，涉及来自 Ecuador、Netherlands、Thailand 等地的玫瑰、非洲菊、绣球与石斛兰。最终雕塑不是花瓶，而是109.2 × 72.4 × 52.1 cm 的 pigmented concrete press：真实干燥植物标本与 archival inkjet prints、archival herbarium paper 上的文字被置入其中，并由 steel brace 构成压制/支撑结构。',actions:['从2006年协议签署照片中识别具体花卉种类与来源。','重新获得相应花材，并在摄影后把植物制作成干燥标本。','设计并浇筑带颜色的 concrete flower press。','把 dried plant specimens、archival inkjet photographs 与 herbarium-paper text 放入同一雕塑系统。','用 steel brace 形成实际压制/固定结构，使保存行为成为作品的一部分。'],sourceUrl:'https://gagosian.com/exhibitions/2016/taryn-simon-paperwork-and-the-will-of-capital-new-york/',images:[],relations:[rel('材料','Pigmented concrete / dried plant specimens / archival inkjet / herbarium paper / steel','Gagosian technical record.'),rel('尺寸','109.2 × 72.4 × 52.1 cm','43 × 28½ × 20½ in.'),rel('系列结构','12 unique sculptures + 36 editioned photographs','Gagosian records the complete body of work at this scale.')]}
],awards:[],exhibitions:['56th Venice Biennale, 2015 — sculpture preview','Gagosian New York, 2016 — complete body of work','Gagosian Rome, 2016','Tel Aviv Museum of Art, 2016–2017','Gagosian Athens, 2018'],sources:[{label:'Gagosian · Paperwork and the Will of Capital, New York',url:'https://gagosian.com/exhibitions/2016/taryn-simon-paperwork-and-the-will-of-capital-new-york/'},{label:'Gagosian · Paperwork and the Will of Capital, Athens',url:'https://gagosian.com/exhibitions/2018/taryn-simon-paperwork-and-the-will-of-capital/'}]}
};