import type { ArtistArchive, ArchiveRelation } from './archiveData';
const rel=(kind:ArchiveRelation['kind'],label:string,detail?:string):ArchiveRelation=>({kind,label,detail});
const beloufa='https://www.labiennale.org/en/art/2019/partecipants/ne%C3%AFl-beloufa';
const bircken='https://www.labiennale.org/en/art/2019/partecipants/alexandra-bircken';
const bove='https://www.labiennale.org/en/art/2019/partecipants/carol-bove';
const buchel='https://www.labiennale.org/en/art/2019/partecipants/christoph-b%C3%BCchel';
const buchelAsac='https://asac.labiennale.org/collezioni/fototeca/382696';
export const archiveBatch115:Record<string,ArtistArchive>={
'venice-neil-beloufa':{artistId:'venice-neil-beloufa',projectCoverage:'1 个 surveillance-viewing / installation-video 节点已建立深档案 · 2018–2019',imageCoverage:'0 / 1 项目暂不使用不稳定外链图像',note:'Beloufa 的 Global Agreement 重点不是视频内容单独成立，而是观看装置把 viewer 变成被观看对象：representation 的问题被直接写进身体姿势、座椅限制和空间 sightline。',projects:[{title:'Global Agreement',cluster:'video installation / gym-equipment seating / reciprocal surveillance',period:'2018–2019',summary:'观看者必须坐在类似 gym equipment 的不舒适结构上观看 videos；装置限制身体移动，同时让每个人都能看见别人正在看，于是 viewing 与 being watched 同时发生。',actions:['制作/组织 video material，但拒绝让 screen 成为唯一作品中心','搭建类似 gym equipment 的 seating structures','故意使座位不舒适并限制 viewer movement','配置 sightlines，使观众能互相观察','把观看者身体纳入 representation system','撤回作者权威解释，让 viewer 自己处理观看与被观看的矛盾'],sourceUrl:beloufa,images:[],relations:[rel('展览','May You Live In Interesting Times — Venice Biennale 2019','Arsenale')]}],awards:[],exhibitions:['May You Live In Interesting Times — Venice Biennale 2019'],sources:[{label:'La Biennale · Neïl Beloufa 2019',url:beloufa}]},
'venice-alexandra-bircken':{artistId:'venice-alexandra-bircken',projectCoverage:'2 个 body-machine / repurposed-material sculpture 节点已建立深档案 · 2016–2019',imageCoverage:'0 / 2 项目暂不使用不稳定外链图像',note:'Bircken 的方法值得按“材料原用途被剥离后如何重新变成身体”来读：silicon、nylon tights、weapons、machinery 与 wool、leather、branches、dried fruit 被迫进入同一 vulnerable body-machine grammar。',projects:[{title:'ESKALATION',cluster:'apocalyptic installation / human-form residue / body-machine tension',period:'2016',summary:'Arsenale 的 visceral、dynamic installation 将人类身体想象推向 dystopian endpoint；其冲突来自人工与有机材料被拆离原用途后重新组装。',actions:['收集 manufactured 与 organic materials','剥离 objects 原先 practical purpose','将不同材料重新 assemblage 为 uncomfortable bodily arrangement','利用 hard/soft、protective/vulnerable、machine/animal 的对立制造张力','以 installation scale 构造 humanity-after-humanity 的 dystopian reading'],sourceUrl:bircken,images:[],relations:[rel('展览','May You Live In Interesting Times — Venice Biennale 2019','Arsenale')]},{title:'Central Pavilion six-work constellation',cluster:'gender / power / vulnerability / animal-machine',period:'2019 presentation',summary:'六件作品把 gender、power、vulnerability 与 animal/machine 交织；身体既需要 protection tools，又会被这些工具的暴力逻辑反向定义。',actions:['并置 silicon、nylon tights、weapons、machinery 等 manufactured materials','并置 wool、leather、branches、dried fruit 等 organic materials','让 protective technology 与 exposed body 同时可读','以 assemblage 处理 gender / power 而非插图式叙事','通过 material opposition 保持 physical vulnerability'],sourceUrl:bircken,images:[],relations:[rel('展览','May You Live In Interesting Times — Venice Biennale 2019','Central Pavilion')]}],awards:[],exhibitions:['May You Live In Interesting Times — Venice Biennale 2019'],sources:[{label:'La Biennale · Alexandra Bircken 2019',url:bircken}]},
'venice-carol-bove':{artistId:'venice-carol-bove',projectCoverage:'1 个 collage-sculpture / pressure-softness 方法节点已建立深档案 · 2010s–2019',imageCoverage:'0 / 1 项目暂不使用不稳定外链图像',note:'Bove 的雕塑方法可以具体拆成 bend / dent / torque / kink / crumple / crease：工业钢材被强制表现得像柔软材料，再用 candy-colour finish 与 untreated found steel 拉开时间和触觉差异。',projects:[{title:'Collage sculptures',cluster:'industrial steel / found object / candy-colour finish / kinaesthetic viewing',period:'2010s–2019',summary:'所谓 collage sculptures 在 industrially formed 与 found、obsolete 与 newly minted 之间工作；粗糙 untreated steel 与 slick reds/yellows/pinks/greens 并置，使 steel tube 产生 soft / malleable illusion。',actions:['选择 industrially formed steel 与 found / obsolete objects','对钢材实施 bend、dent、torque、kink、crumple、crease 等变形','保留部分 rough untreated steel surface','对另一些结构施加 slick candy-coloured finish','通过 finish / raw material 冲突制造 soft-steel illusion','让 sculpture 的 twists/folds 强迫观众绕行，从身体移动读取 pressure / force'],sourceUrl:bove,images:[],relations:[rel('展览','May You Live In Interesting Times — Venice Biennale 2019','Central Pavilion / Arsenale')]}],awards:[],exhibitions:['May You Live In Interesting Times — Venice Biennale 2019'],sources:[{label:'La Biennale · Carol Bove 2019',url:bove}]},
'venice-christoph-buchel':{artistId:'venice-christoph-buchel',projectCoverage:'1 个 recovered-wreck / migration memorial 节点已建立深档案 · 2015–2019',imageCoverage:'0 / 1 项目暂不使用不稳定外链图像',note:'Barca Nostra 必须保留 provenance：它不是仿造船只。2015 shipwreck、2016 Italian Navy recovery / forensic identification、2018 Palermo petition 与 2019 Venice presentation 构成作品伦理与政治意义的一部分。',projects:[{title:'Barca Nostra',cluster:'recovered shipwreck / migration memorial / forensic-political object',period:'2015–2019',summary:'作品使用 2015 年 4 月 18 日地中海沉船事故中的真实 fishing boat wreck；事故仅 28 人生还、约 700–1,100 人失踪。船体 2016 被 Italian Navy 从海床打捞，随后进入遗体移除与身份识别流程，最终在 Venice 作为 contemporary migration 的 collective monument / memorial 出现。',actions:['不是复制事故对象，而是以真实 recovered wreck 作为作品核心','保留船体作为 mass-death event 的物证属性','将 forensic recovery / identification history 纳入 object biography','让 wreck 从 naval base / political debate 转入 art-exhibition context','不以纪念碑 pedestal 美化船体，而让其 physical scale 与损伤直接面对观众','将 individual tragedy 与 European migration policy / mobility politics 连接'],sourceUrl:buchel,images:[],relations:[rel('展览','May You Live In Interesting Times — Venice Biennale 2019','Arsenale; ASAC records Barca Nostra as 3D outdoor object')] }],awards:[],exhibitions:['May You Live In Interesting Times — Venice Biennale 2019'],sources:[{label:'La Biennale · Christoph Büchel 2019',url:buchel},{label:'ASAC · Barca Nostra 2019',url:buchelAsac}]}
};
