import type { ArtistArchive, ArchiveRelation } from './archiveData';

const rel=(kind:ArchiveRelation['kind'],label:string,detail?:string):ArchiveRelation=>({kind,label,detail});

export const archiveBatch249:Record<string,ArtistArchive>={
  'thomas-demand':{
    artistId:'thomas-demand',
    projectCoverage:'作品级深化：补入 Room (Zimmer)、Studio、Clearing 三个可由 MoMA 馆藏与展览档案交叉核对的具体节点，强调纸模型—摄影—销毁模型的工作链及不同尺度的观看方式。',
    imageCoverage:'MoMA 为三件作品提供官方作品页与 2005 个展安装图；版权标记为 Artists Rights Society / VG Bild-Kunst，安装摄影 Thomas Griesel。未确认开放再发布许可，因此不复制原图，保留官方图像入口与授权路径。',
    note:'这一批把 Demand 的“纸模型摄影”从方法标签下钻到具体作品：来源图像是什么、模型删掉了哪些现实信息、最终照片有多大，以及展览中为何会产生接近建筑尺度的观看经验。',
    projects:[
      {title:'Room (Zimmer)',cluster:'paper model / media image / reconstruction / chromogenic print',period:'1996',summary:'Demand 以一张既有照片为来源，重建 L. Ron Hubbard 在 1972–73 年生活和工作的酒店房间。他不是把真实房间复原成可长期保存的雕塑，而是用纸搭出一个只为摄影服务的替身空间：枕头、床、闹钟、打字机等物件被重新制造，但闹钟没有数字、打字机没有按键等信息被主动抽空。均匀的摄影棚光线和纸张折痕使照片在第一眼近似真实室内，靠近后却不断暴露模型属性。最终作品为 chromogenic print，172 × 232 cm；模型作为中间生产环节，观看对象最终仍是大型摄影图像。',actions:['从传播中的房间照片而非真实现场开始。','用纸和纸板重建房间、家具与桌面物件。','主动删除数字、按键等识别性细节，让模型只保留视觉轮廓。','在受控灯光下拍摄纸模型，把三维临时布景重新压回二维照片。','以 172 × 232 cm 大幅 chromogenic print 呈现，使观众先把它当作室内摄影，再从缺失细节识别人工性。'],sourceUrl:'https://www.moma.org/collection/works/57201',images:[],relations:[rel('收藏','Museum of Modern Art, New York','Object 869.1996；Gift of the Nina W. Werblow Charitable Trust'),rel('展览','Thomas Demand — MoMA, 2005','2005-03-04—05-30；官方安装图由 Thomas Griesel 摄影。')]},
      {title:'Studio',cluster:'paper model / television set / chromogenic print / installation scale',period:'1997',summary:'Studio 把电视演播室式空间转换为 Demand 的纸模型系统。作品最终不是模型本身，而是一张 183.5 × 349.5 cm 的 chromogenic print：接近 3.5 米宽的横向画面让观众面对一个几乎可身体进入的空间幻觉。纸模型中的表面、设备和结构被简化为无文字、无使用痕迹的几何外壳，因此它既像真实媒体空间，又像关于“媒体如何制造现实”的空壳。MoMA 2005 回顾展把它作为大型墙面摄影展示，安装档案可用于核对作品与观众尺度。',actions:['把演播室/媒体空间转译为纸制三维模型。','简化设备表面和信息层，使场景保留空间逻辑却失去日常使用痕迹。','在模型完成后进行受控摄影，而不是把模型作为最终雕塑陈列。','输出 183.5 × 349.5 cm chromogenic print。','在展墙上以接近建筑尺度观看，观众通过身体尺度感受“可信空间”与纸模型之间的冲突。'],sourceUrl:'https://www.moma.org/collection/works/111287',images:[],relations:[rel('收藏','Museum of Modern Art, New York','Object 601.2007'),rel('展览','Thomas Demand — MoMA, 2005','安装图 IN1937.13；Photograph by Thomas Griesel.')]},
      {title:'Clearing',cluster:'constructed nature / paper leaves / chromogenic print / panoramic scale',period:'2003',summary:'Clearing 把 Demand 通常用于办公室、房间和新闻现场的模型方法转向“自然”。最终 chromogenic print 达 192 × 495 cm，接近五米宽；树林/叶片不再是直接拍摄的自然景观，而是人工制造、重复组织的纸质植被。这个尺度非常关键：远看像沉浸式森林图像，靠近时叶片的重复、边缘和表面逐渐使“自然”显露为制造物。2005 MoMA 个展的安装档案进一步显示作品作为超宽墙面图像与展厅尺度的关系。',actions:['把树林和叶片转译成大量人工纸制形体。','通过重复制作和排列建立看似繁密的自然空间。','对完成的模型进行摄影，把纸制景观重新转为二维图像。','制作 192 × 495 cm chromogenic print。','利用近五米宽的横向尺度，让观众在远观的景观幻觉与近看的材料破绽之间移动。'],sourceUrl:'https://www.moma.org/collection/works/90063',images:[],relations:[rel('收藏','Museum of Modern Art, New York','Object 236.2004'),rel('展览','Thomas Demand — MoMA, 2005','2005-03-04—05-30；官方展览档案提供安装图。')]}
    ],awards:[],exhibitions:['Thomas Demand — Museum of Modern Art, New York, 4 Mar–30 May 2005'],sources:[{label:'MoMA · Room (Zimmer), 1996',url:'https://www.moma.org/collection/works/57201'},{label:'MoMA · Studio, 1997',url:'https://www.moma.org/collection/works/111287'},{label:'MoMA · Clearing, 2003',url:'https://www.moma.org/collection/works/90063'},{label:'MoMA · Thomas Demand installation view (Room), 2005',url:'https://www.moma.org/calendar/exhibitions/116/installation_images/5'}]
  },
  'laia-abril':{
    artistId:'laia-abril',
    projectCoverage:'作品级深化：补入 On Mass Hysteria 的研究—展览—摄影书链条，并加入 2026 Endometriosis 装置，记录摄影表面使用艺术家泪液上光这一具体材料动作。',
    imageCoverage:'两项目均由艺术家官网提供官方项目页与展览图。网页图像版权未声明为开放许可，因此不复制文件；保留项目/展览页作为图像入口并明确暂缺可再发布本地图片。',
    note:'Abril 的研究型摄影不能只写成“女性议题”。关键是她如何把医学文献、历史案例、口述经验、身体摄影、书籍设计和空间安装变成不同版本的证据结构。',
    projects:[
      {title:'On Mass Hysteria — Photo Elysée installation / book',cluster:'A History of Misogyny / research / testimony / installation / photobook',period:'2016–2024',summary:'Abril 从 2016 年研究尼泊尔月经禁忌时读到 2003 年学校女生集体昏厥报道开始，持续搜集不同地区被称作 possession、mysterious illness 或 mass psychogenic illness 的案例，并把医学解释与社会学、殖民史、性别权力和当事人的梦境/情绪并置。2023 Photo Elysée 版本把研究转为空间安装，由 Nathalie Herschdorfer 策展，并与 Le Bal、Finnish Museum of Photography、Les Filles du Calvaire 联合制作；2024 又转化为 Dewi Lewis + Delpire &Co 摄影书。也就是说，同一研究不是固定“照片系列”，而是在档案、文本、图像、空间与书页之间重编。',actions:['从具体新闻病例出发建立跨地域、跨历史时期的案例档案。','交叉阅读医学、社会学与人类学解释，并保留当事人的梦境、情绪和预感作为叙事材料。','把“集体症状”放回学校、工厂、宗教和父权制度等社会结构中，而不是只做病理图解。','在 Photo Elysée 将材料重新编排为空间展览，让观众以移动、阅读和比较的方式进入研究。','2024 与 Dewi Lewis + Delpire &Co 转为摄影书，由 Nicola Poli 设计，使材料再经历一次书页顺序和阅读节奏的重构。'],sourceUrl:'https://www.laiaabril.com/project/on-mass-hysteria/',images:[],relations:[rel('展览','On Mass Hysteria — Photo Elysée, Lausanne','30 Jun–1 Oct 2023；curated by Nathalie Herschdorfer；co-produced with Le Bal, Finnish Museum of Photography and Les Filles du Calvaire.'),rel('出版','On Mass Hysteria: A Proto-language of Protest','Dewi Lewis + Delpire&Co, 2024；design Nicola Poli；supported by Photo Elysée + Le Bal.')]},
      {title:'Endometriosis — The Silenced Pain',cluster:'chronic pain / installation / portraiture / bodily material',period:'2026',summary:'Abril 与七位患有致残性子宫内膜异位症的人合作，不试图用临床式影像“证明”不可见疼痛，而是在疼痛暂时缓解的时刻拍摄被切分、非完整化的身体。最具体的材料动作是：她用自己的泪液给照片上光，使作者身体产生的液体直接进入摄影表面。作品把身体姿态、疼痛适应、医学不可见性与妇产科历史中的制度暴力连在一起，并作为 On Mass Hysteria 之后对性别、医疗知识与制度权力研究的直接延伸。2026 分别在 Madrid Museo del Romanticismo 与 London Annely Juda Fine Art 展出，空间版本应继续追踪安装图以记录照片数量、尺度和墙面编排。',actions:['与七位长期经历致残性子宫内膜异位症的人合作。','不使用临床影像逻辑直接说明病灶，而在暂时缓解的时刻拍摄身体。','通过碎片化取景避免把身体组织成单一、可被医学读取的完整对象。','用艺术家自己的泪液给摄影作品表面上光，使身体液体成为作品材料。','把照片组织成装置，在观看身体图像的同时把注意力引向疾病长期被忽视的制度条件。'],sourceUrl:'https://www.laiaabril.com/project/endometriosis/',images:[],relations:[rel('展览','Endometriosis — Museo del Romanticismo, Madrid','2026'),rel('展览','Endometriosis — Annely Juda Fine Art, London','2026')]}
    ],awards:[],exhibitions:['On Mass Hysteria — Photo Elysée, Lausanne, 2023','On Mass Hysteria — Finnish Museum of Photography, Helsinki, 2024','Endometriosis — Museo del Romanticismo, Madrid, 2026','Endometriosis — Annely Juda Fine Art, London, 2026'],sources:[{label:'Laia Abril · On Mass Hysteria',url:'https://www.laiaabril.com/project/on-mass-hysteria/'},{label:'Laia Abril · Photo Elysée installation, 2023',url:'https://www.laiaabril.com/exhibition/masshysteria-elyse/'},{label:'Laia Abril · On Mass Hysteria book, 2024',url:'https://www.laiaabril.com/book/on-mass-hysteria-dewi-lewis-delpire-2024/'},{label:'Laia Abril · Endometriosis',url:'https://www.laiaabril.com/project/endometriosis/'}]
  },
  'taryn-simon':{
    artistId:'taryn-simon',
    projectCoverage:'作品级深化：补入 An American Index 的生产方法与 The Conversation Machine 的 32 屏具体装置结构，继续把“研究主题”落实为准入谈判、4×5 相机、文本和显示系统。',
    imageCoverage:'艺术家官网为两个项目提供官方作品/安装图入口；图像未标记为可自由再发布，因此不复制原图。保留官网入口与版权来源，避免以搜索缩略图替代。',
    note:'Simon 的关键不是“拍秘密地点”，而是把准入制度本身变成生产条件：长期通信、筛查、现场协议、4×5 大画幅摄影与说明文字共同决定最终作品。',
    projects:[
      {title:'An American Index of the Hidden and Unfamiliar — access / 4×5 production system',cluster:'restricted access / large-format photography / text / institutional research',period:'2007',summary:'该系列最终包含 57 个美国境内通常被隐藏、限制进入或不被公众注意的对象，横跨科学、政府、医学、娱乐、安全、自然与宗教。艺术家官网与项目论文显示，Simon 有时为一张照片研究超过一年：先确定机构和地点，再经历长期通信、许可与安全筛查；进入现场后通常使用 4×5 大画幅相机和灯光设备，且构图往往直到真正获准进入后才决定。Plum Island Animal Disease Center 的访问甚至要求进出淋浴，并因先前访问禽类检疫设施而延迟两周以避免交叉污染。最终照片与精确说明文字并置，使“谁能进入、谁能看见、机构如何命名自身”成为图像的一部分。',actions:['建立科学、政府、医学、宗教、安全等不可见机构/场所清单。','为单一地点进行数月甚至一年以上的通信、许可申请和筛查。','遵守各机构现场协议；例如生物安全设施要求淋浴与交叉污染隔离。','获准后携带 4×5 大画幅相机与灯光进入，现场决定最终构图。','把正式摄影与地点名称、制度说明等文字并置，使访问权限本身进入作品结构。'],sourceUrl:'https://tarynsimon.com/works/aihu/',images:[],relations:[rel('展览','Whitney Museum of American Art, New York','9 Mar–24 Jun 2007'),rel('展览','Tate Modern, London','17 Dec 2016–1 Dec 2017'),rel('出版','An American Index of the Hidden and Unfamiliar','项目出版物与艺术家官网收录 Salman Rushdie、Elisabeth Sussman / Tina Kukielski 等文本。')]},
      {title:'The Conversation Machine',cluster:'32-screen video installation / neuroscience / interviews / orchestration',period:'2022',summary:'这件作品不是单部访谈电影，而是由 32 块屏幕组成的广播式装置。Simon 采访来自五大洲的神经科学家、心理学家、神经语言学家与哲学家，讨论神经科学实验及其哲学、伦理含义；随后把录像、访谈和播放编排组织成一个多屏系统。艺术家把装置描述为类似大脑的 self-organizing system，因此观众面对的不是一条由头至尾的单线论证，而是同时存在、彼此打断和重新组合的专家声音。作品由 Fondazione Prada 为 Human Brains: It Begins with an Idea 制作。',actions:['跨五大洲选择神经科学、心理学、神经语言学与哲学研究者。','拍摄专家访谈，使实验事实与哲学/伦理问题同时进入素材库。','把素材分配到 32 块显示屏，而不是剪成单一线性纪录片。','通过播放编排制造多个声音同时出现、交错和重新组合的观看环境。','让观众在屏幕阵列前自行转向、选择和连接信息，使观看行为模拟复杂认知系统中的注意力分配。'],sourceUrl:'https://tarynsimon.com/works/cm/',images:[],relations:[rel('展览','Human Brains: It Begins with an Idea — Fondazione Prada, Venice','2022；The Conversation Machine produced by Fondazione Prada for the exhibition.')]}
    ],awards:[],exhibitions:['An American Index of the Hidden and Unfamiliar — Whitney Museum, 2007','An American Index of the Hidden and Unfamiliar — Tate Modern, 2016–17','Human Brains: It Begins with an Idea — Fondazione Prada, Venice, 2022'],sources:[{label:'Taryn Simon · An American Index of the Hidden and Unfamiliar',url:'https://tarynsimon.com/works/aihu/'},{label:'Taryn Simon · Index introduction by Elisabeth Sussman & Tina Kukielski',url:'https://tarynsimon.com/essays-videos/docs/Introduction%20from%20An%20American%20Index%20of%20the%20Hidden%20and%20Unfamiliar_Elisabeth%20Sussman%20%26%20Tina%20Kukielski.pdf'},{label:'Taryn Simon · The Conversation Machine',url:'https://tarynsimon.com/works/cm/'}]
  }
};
