import type { ArtistArchive, ArchiveProject, ArchiveRelation } from './archiveData';
const rel=(kind:ArchiveRelation['kind'],label:string,detail?:string):ArchiveRelation=>({kind,label,detail});
const project=(p:ArchiveProject)=>p;

export const archiveBatch314:Record<string,ArtistArchive>={
 'cao-fei':{
  artistId:'cao-fei',
  projectCoverage:'深化既有曹斐档案：Whose Utopia、RMB City、Asia One。重点补齐珠三角工业化—虚拟城市—自动化物流的连续方法谱系，以及 MoMA PS1、Guggenheim、威尼斯双年展等机构关系。',
  imageCoverage:'以 Guggenheim、MoMA PS1 等官方作品与展览页作为图像研究入口；未确认自由再发布权利的图片不直接复制。',
  note:'曹斐的重要性不只是“很早使用互联网/游戏的中国艺术家”。她持续把中国快速城市化和技术变迁中已经存在的现实推向半虚构状态：工厂工人的梦想、Second Life 中的城市、无人仓库中的人机关系都不是逃离现实，而是用角色扮演、世界建造和科幻叙事测试现实制度还能怎样生活。她的媒介从摄影与录像进入网络平台、虚拟建筑、电影和大型装置，但核心始终是现实基础设施与人的欲望如何互相塑形。',
  projects:[
   project({title:'Whose Utopia?',cluster:'factory / labor / fantasy / Pearl River Delta',period:'2006',summary:'作品产生于曹斐在广东佛山照明工厂的驻留。Guggenheim 对其结构的描述很关键：录像先以近乎冷静的方式记录生产线，随后让真实工人在同一个工业空间里实现自己的私人角色——芭蕾舞者、摇滚乐手、太极练习者等。作品因此没有把“工厂”与“梦想”拍成两个世界，而是让幻想直接发生在生产现场内部；劳动者既是流水线中的身体，也是拥有无法被岗位描述穷尽的主体。',actions:['进入真实照明工厂驻留，把生产线作为长期观察现场。','先记录重复、标准化的工业劳动，再让工人以自己选择的梦想身份进入同一空间。','利用表演而非采访，把私人欲望与生产制度放进同一个画面。','让纪实和幻想连续出现，使“乌托邦”不成为外部逃逸空间，而成为现实劳动内部短暂显形的可能性。'],sourceUrl:'https://www.guggenheim.org/artwork/artist/cao-fei',images:[],relations:[rel('收藏','Solomon R. Guggenheim Museum — Cao Fei artist research','Guggenheim 官方艺术家资料把 Whose Utopia 置于珠三角工业化、青年文化与全球化的实践脉络中。'),rel('展览','Tate Modern — Poetry and Dream','MoMA PS1 回顾资料记录 Whose Utopia 曾在 Tate Modern 放映。')]}),
   project({title:'RMB City',cluster:'Second Life / virtual city / avatar / participatory world-building',period:'2007–2011',summary:'RMB City 不是把一座现实城市做成数字模型，而是在 Second Life 中以 China Tracy 这一 avatar 建造可进入、交易和社交的虚拟城市。MoMA PS1 指出，这座城市把大量中国现实符号与对未来的快速想象压缩在一起：漂浮建筑、购物空间、毛泽东雕像等同时出现。项目把摄影/录像中的“观看城市”改成“运营一个世界”：观众不再只是观看图像，而能以 avatar 进入由艺术家设定但又会被参与者继续使用的社会空间。',actions:['以 China Tracy 作为艺术家在 Second Life 中的化身。','不是复制现实城市，而是重新混合中国城市化、政治符号、消费文化与未来想象。','让虚拟建筑、交易、社交和参与者行为共同构成作品，而不是只输出固定影像。','把项目持续数年，使虚拟城市具有时间、事件和使用史。'],sourceUrl:'https://www.moma.org/calendar/exhibitions/4945',images:[],relations:[rel('展览','MoMA PS1 — Cao Fei — 2016','Klaus Biesenbach 与 Jocelyn Miller 组织的回顾展示把 RMB City 与早期工厂、青年文化及后续虚拟实践并置。'),rel('展览','Deutsche Guggenheim — 2010','MoMA PS1 官方履历记录 RMB City 的机构展示。'),rel('展览','Serpentine Gallery — 2008','MoMA PS1 官方履历记录该项目在伦敦展示。'),rel('展览','Yokohama Triennale — 2008','MoMA PS1 官方履历记录该项目进入横滨三年展。')]}),
   project({title:'Asia One',cluster:'automation / logistics / science fiction / human-machine relation',period:'2018',summary:'Asia One 把曹斐早期的工厂问题推进到自动化物流时代。Guggenheim 委托项目进入江苏昆山的高度自动化分拣中心：核心电影长约63分钟，虚构一个巨大仓库中只剩两名人类员工的近未来。两人最初似乎与机器比彼此更亲近，后来开始对整洁、可预测和高效率的系统产生偏离。完整作品不是单通道电影：Guggenheim 馆藏记录还包括多路录像、墙面图像、灯箱、机动三轮车、邮政/包装物、JD.com 工作装备等，使真实物流物质文化进入科幻叙事。',actions:['实地进入中国先进工业设施与自动化分拣中心研究。','以真实自动化基础设施为场景，写入两名工人的虚构关系和未来考古段落。','把文化大革命样板戏式身体、合成器音乐与“人机携手”等历史/未来符号错置。','把电影扩展为大型装置，纳入 JD.com 包装、制服、标签、车辆和物流物件，使供应链本身成为作品材料。'],sourceUrl:'https://www.guggenheim.org/artwork/38191',images:[],relations:[rel('收藏','Solomon R. Guggenheim Museum — 2018.12','The Robert H. N. Ho Family Foundation Collection；Guggenheim 官方馆藏保存完整媒介清单。'),rel('展览','One Hand Clapping — Guggenheim — 2018','Asia One 为 Robert H. N. Ho Family Foundation Chinese Art Initiative 委托并在该展呈现。'),rel('展览','MAXXI Videogallery — 2021–2022','MAXXI 将影片作为关于自动化生产、分配系统与未来劳动的作品展映。')]}),
  ],
  awards:['Chinese Contemporary Art Awards (CCAA) — Best Young Artist — 2006','Hugo Boss Prize — finalist — 2010','Future Generation Art Prize — nominee — 2010'],
  exhibitions:['56th Venice Biennale — All the World’s Futures — La Town — 2015','Cao Fei — MoMA PS1 — 2016','One Hand Clapping — Solomon R. Guggenheim Museum — 2018'],
  sources:[{label:'Guggenheim — Cao Fei',url:'https://www.guggenheim.org/artwork/artist/cao-fei'},{label:'Guggenheim — Asia One',url:'https://www.guggenheim.org/artwork/38191'},{label:'MoMA PS1 — Cao Fei',url:'https://www.moma.org/calendar/exhibitions/4945'}]
 },
 'joan-fontcuberta':{
  artistId:'joan-fontcuberta',
  projectCoverage:'深化既有 Joan Fontcuberta 档案：Fauna、Sputnik，并补足其艺术家/理论家/编辑者三重角色和机构网络。',
  imageCoverage:'MACBA 与 MoMA 官方馆藏提供作品及文献入口；版权未确认的馆藏图不直接复制。',
  note:'Fontcuberta 的关键不是简单宣布“照片会骗人”，而是精确复制一套让事实获得可信度的制度语言：科学分类、博物馆陈列、档案磨损、出版物、专家身份、航天史叙事。观众相信的往往不是某一张照片，而是照片周围一整套相互担保的证据。进入数字时代后，他把同一问题继续推向软件、搜索引擎与数据库，因此早期伪科学项目是理解其后摄影实践的基础。',
  projects:[
   project({title:'Fauna',cluster:'pseudo-science / museum display / taxonomy / photography',period:'1985–1989',summary:'Fontcuberta 与 Pere Formiguera 从1985年开始构造虚构德国动物学家 Peter Ameisenhaufen 及助手 Hans von Kubert 的“失落档案”。MACBA 馆藏说明作品不只包含奇异动物照片，还包括野外研究笔记、X光、骨骼解剖、标本和动物叫声音频，并与 taxidermist 合作制造生物，再用拟拉丁学名分类。照片被故意做得略模糊，信件墨迹和画框也被老化：可信度来自一整套科学展示语法，而不是单张照片的逼真。1989年在 Barcelona Museum of Zoology 首次展示时，馆方教育部门调查发现约27%的成年大学学历观众相信这些动物真实存在。',actions:['与 Pere Formiguera 共同虚构科学家、助手、发现史和研究档案。','与动物标本制作人员合作制造不存在的生物，并以拟拉丁学名纳入分类系统。','同时生产照片、野外笔记、X光、骨骼、标本与声音，使不同媒介互相“证明”。','人为老化照片、信件与框架，再借用自然史博物馆的陈列语言增强制度可信度。'],sourceUrl:'https://www.macba.cat/en/obra/r1659-fauna/',images:[],relations:[rel('收藏','MACBA Collection — Fauna — acquired 2001','MACBA 保存该大型多媒体装置，并详细记录其伪科学结构。'),rel('展览','Projects 12: Joan Fontcuberta/Pere Formiguera — MoMA — 1988','MoMA 艺术家档案记录二人的 Projects 系列展览。'),rel('展览','Museo de Zoología de Barcelona — 1989','MACBA 记录首次展示及观众真实性调查。')]}),
   project({title:'Sputnik',cluster:'false archive / space history / publication / institutional credibility',period:'1997',summary:'Sputnik 把 Fontcuberta 的伪档案方法从自然史推进到航天史与大众传媒。重要的不只是制造一个虚构宇航员故事，而是让展览、出版物、照片和“历史资料”共同模仿冷战知识生产的外观。MACBA 文献中心保存1997年三语展览图录，记录项目于 Madrid Fundación Arte y Tecnología 在1997年5月21日至7月20日展出，并得到 Telefónica 与基金会协作。这里机构、技术企业和出版物本身都成为观众判断真实性时会依赖的外部担保。',actions:['借用航天史和冷战档案的视觉语法制造貌似可核验的历史叙事。','让摄影与文献、展览图录、机构身份共同运作，而非把骗局压在单张图像上。','以西班牙语、俄语、英语出版强化“跨国历史档案”的形式可信度。','把观众查证信息时依赖的机构权威本身纳入作品机制。'],sourceUrl:'https://www.macba.cat/en/obra/a14280-sputnik--/',images:[],relations:[rel('出版','Sputnik — exhibition catalogue — 1997','MACBA Centre d’Estudis i Documentació 保存23.3 × 17 cm、西/俄/英三语图录。'),rel('展览','Fundación Arte y Tecnología, Madrid — 1997-05-21–07-20','MACBA 文献记录确认展期。'),rel('收藏','MACBA Centre d’Estudis i Documentació','馆藏保存多个 Sputnik 图录记录，包括 Jorge Ribalta 捐赠版本。')]}),
  ],
  awards:['Hasselblad International Award in Photography — 2013'],
  exhibitions:['Projects 12: Joan Fontcuberta/Pere Formiguera — MoMA — 1988','Fauna — Museo de Zoología de Barcelona — 1989','Sputnik — Fundación Arte y Tecnología, Madrid — 1997'],
  sources:[{label:'MACBA — Joan Fontcuberta',url:'https://www.macba.cat/en/actor/joan-fontcuberta/'},{label:'MACBA — Fauna',url:'https://www.macba.cat/en/obra/r1659-fauna/'},{label:'MACBA — Sputnik',url:'https://www.macba.cat/en/obra/a14280-sputnik--/'},{label:'MoMA — Joan Fontcuberta',url:'https://www.moma.org/artists/1932-joan-fontcuberta'}]
 }
};
