import type { ArtistArchive } from './archiveData';

const rel=(kind:'展览'|'出版'|'奖项'|'收藏'|'策展',label:string,detail?:string)=>({kind,label,detail});

export const archiveExtensions341: Record<string, Partial<ArtistArchive> & { projects?: ArtistArchive['projects'] }> = {
  'theaster-gates': {
    note:'继续把 Gates 从“社会实践”拆成可验证的物质—制度生产链：他不只修复建筑或收藏旧物，而是把被判定为无用的建筑、档案、工具和城市材料重新估值，并建立制造、培训、销售、放映、研究和社区使用的持续结构。作品价值因此常常不是某个孤立物件，而是物件如何被重新流通。',
    projects:[
      {title:'Stony Island Arts Bank',cluster:'Archive / adaptive reuse / Black cultural infrastructure',period:'2015–',summary:'Gates 将芝加哥 South Side 一座1923年的废弃银行修复为约17,000平方英尺的艺术与档案空间。它长期容纳 University of Chicago 超过60,000张玻璃幻灯片、Johnson Publishing Company 的书刊资料、Frankie Knuckles 唱片收藏以及 Edward J. Williams 收集的约4,000件种族刻板图像物件。这里“收藏”不是作品说明，而成为真实保存、研究、放映与公共使用的基础设施。',actions:['取得并修复废弃银行建筑','接收面临弃置或失去机构归属的档案','为不同档案建立长期存放与研究空间','运营免费电影放映与讨论项目','让建筑修复、档案保存和公共文化活动共同持续运作'],sourceUrl:'https://www.theastergates.com/project-items/stony-island-arts-bank',images:[],relations:[rel('展览','Stony Island Arts Bank','Chicago South Side · opened 2015'),rel('收藏','Johnson Publishing Company archive','books and periodicals'),rel('收藏','Frankie Knuckles Collection','personal vinyl collection'),rel('收藏','Edward J. Williams Collection','approximately 4,000 objects')]},
      {title:'Dorchester Industries',cluster:'Manufacturing / training / circular economy',period:'ongoing',summary:'以芝加哥城市中被忽略的材料制造家具、物件和空间，同时训练参与者进入建筑工种与创意产业；产品以 Dorchester Industries 品牌出售，收益继续支持艺术家主导、社区驱动的文化更新。它使 Gates 的“再利用”从雕塑语言进入真实制造、职业培训和经济循环。',actions:['从芝加哥收集被忽略但可继续使用的材料','以协作工艺制造家具和空间物件','培训员工进入 building trades 与 creative industries','以品牌出售制作成果','把销售收益重新投入社区文化更新'],sourceUrl:'https://www.theastergates.com/project-items/dorchester-industries',images:[],relations:[rel('机构','Dorchester Industries','artist-led manufacturing and training platform')]},
      {title:'True Value',cluster:'Commodity / labor / local commerce',period:'2016',summary:'Fondazione Prada 个展把日常材料、工作工具与商业交换并置，并把展场的一部分变成持续生产的工作室/手工作坊；项目同时引导观众注意基金会周边的文化和商业地点。作品因此把“价值”同时放在材料价格、劳动经验、地方商业关系和艺术制度重新估值之间。',actions:['收集并重新语境化日常材料、工具与劳动器具','在展览期间维持工作室/工坊式生产','把附近文化与商业地点纳入项目地图','通过公开讨论连接物件价值与劳动关系'],sourceUrl:'https://www.fondazioneprada.org/project/theaster-gates-true-value/',images:[],relations:[rel('展览','Theaster Gates: True Value','Fondazione Prada, Milan · 7 Jul–25 Sep 2016')]},
      {title:'Unto Thee',cluster:'University archive / discarded material / reactivation',period:'2025–2026',summary:'Smart Museum 的芝加哥首次大型个人美术馆展以 Gates 与 University of Chicago 二十年的关系为基础，把艺术史系玻璃幻灯片、旧展示柜、Midway Studios 沾染颜料的混凝土地面、Bond Chapel 木长椅以及 Johnson Publishing Company 档案等被判定“不再需要”的材料重新组织。关键动作不是怀旧，而是反复改变这些材料的空间关系，使档案再次产生新叙事。',actions:['从大学系统接收被弃置材料和档案','保留物件既有磨损与使用历史','把旧教学/展示/宗教材料转成新装置','与绘画、陶瓷、电影和 JPC 档案并置','通过重新安装持续改变档案解释关系'],sourceUrl:'https://www.theastergates.com/exhibitions/unto-thee',images:[],relations:[rel('展览','Theaster Gates: Unto Thee','Smart Museum of Art · 23 Sep 2025–22 Feb 2026')]}
    ],
    exhibitions:['Theaster Gates: True Value, Fondazione Prada, 2016','Theaster Gates: Unto Thee, Smart Museum of Art, 2025–26'],
    sources:[{label:'Theaster Gates — Stony Island Arts Bank',url:'https://www.theastergates.com/project-items/stony-island-arts-bank'},{label:'Theaster Gates — Dorchester Industries',url:'https://www.theastergates.com/project-items/dorchester-industries'},{label:'Fondazione Prada — True Value',url:'https://www.fondazioneprada.org/project/theaster-gates-true-value/'},{label:'Theaster Gates — Unto Thee',url:'https://www.theastergates.com/exhibitions/unto-thee'}]
  },
  'wangechi-mutu': {
    note:'进一步把 Mutu 的演变从“拼贴转向雕塑”拆成具体空间政治：她把早期拼贴中被切割、重组的混合身体铸造成有重量的青铜，让这些身体进入新古典主义博物馆立面和户外景观；媒介变化因此同时改变主体拥有空间的方式。',
    projects:[
      {title:'The NewOnes, will free Us / The Seated I–IV',cluster:'Bronze / facade / caryatid / institutional architecture',period:'2019–2020',summary:'为 Metropolitan Museum of Art 首次 Fifth Avenue facade commission 制作四件青铜人物，填入1902年立面自建成以来长期空置的四个壁龛。Mutu 重新处理跨西方与非洲传统中的 caryatid / 女性承重者：人物保留坐姿、跪姿与庄严装饰，却不再实际承担建筑或男性统治者的重量。身体上的盘绕结构同时像衣物和铠甲，头部抛光圆盘等细节借鉴多种高地位非洲女性的身体装饰传统。',actions:['研究 The Met Beaux-Arts 立面与长期空置壁龛','研究跨文化 caryatid / female load-bearer 传统','塑造四个不同姿态和面部的混合人物','以青铜铸造并制作不同 patination','把盘绕结构、圆盘、延长的头颈等装饰转成身体结构','将作品安装到博物馆正立面公共空间'],sourceUrl:'https://www.metmuseum.org/exhibitions/listings/2019/facade-commission-wangechi-mutu',images:[],relations:[rel('展览','The Facade Commission: Wangechi Mutu, The NewOnes, will free Us','The Met Fifth Avenue · 9 Sep 2019–1 Nov 2020'),rel('收藏','The Metropolitan Museum of Art','The Seated I and The Seated III acquired 2020')]},
      {title:'In Two Canoe',cluster:'Bronze / water / landscape / metamorphosis',period:'2022',summary:'约15英尺长的青铜喷泉中，两个人物与舟体和周围景观逐渐连成一体：头与手卷曲成叶片，腿部像红树林根系，水在身体周围循环。与室内拼贴不同，混合身体在这里不再只是图像中的拼接，而通过重量、水循环和户外地形真正占据环境。',actions:['以双人物与舟体建立一体化雕塑结构','将叶片、根系与人体部位连续塑形','青铜铸造大型户外作品','引入循环水使身体与喷泉功能结合','依据 Storm King 草地和景观组织观看距离'],sourceUrl:'https://collections.stormking.org/Detail/objects/7669',images:[],relations:[rel('展览','Wangechi Mutu','Storm King Art Center · 21 May–7 Nov 2022')]},
      {title:'Kobe',cluster:'Basket / monument / hand / ecology',period:'2022',summary:'把通常由女性制作、用于农业和捕鱼的篮筐形态放大并铸成纪念碑式青铜；编织棕榈叶的手工纹理又与蛇鳞、龟壳等自然图案发生形式呼应。Mutu 在这里不是简单复制“非洲工艺”，而是把日常容器转换成传统公共雕塑使用的耐久材料，让劳动、手工知识与纪念碑等级发生冲突。',actions:['研究农民与渔民使用的篮筐形态','放大日常容器尺度','保留/重塑手工编织纹理','以青铜转换原本轻质植物材料','在户外景观中重新建立物件与生态关系'],sourceUrl:'https://collections.stormking.org/Detail/objects/7667',images:[],relations:[rel('展览','Wangechi Mutu','Storm King Art Center, 2022')]}
    ],
    exhibitions:['The Facade Commission: Wangechi Mutu, The NewOnes, will free Us, The Met, 2019–20','Wangechi Mutu, Storm King Art Center, 2022'],
    sources:[{label:'The Met — The NewOnes, will free Us',url:'https://www.metmuseum.org/exhibitions/listings/2019/facade-commission-wangechi-mutu'},{label:'The Met — The Seated III',url:'https://www.metmuseum.org/art/collection/search/830456'},{label:'Storm King — In Two Canoe',url:'https://collections.stormking.org/Detail/objects/7669'},{label:'Storm King — Kobe',url:'https://collections.stormking.org/Detail/objects/7667'}]
  }
};
