import type { ArtistArchive, ArchiveRelation, ArchiveImage } from './archiveData';
const rel=(kind:ArchiveRelation['kind'],label:string,detail?:string):ArchiveRelation=>({kind,label,detail});
const img=(url:string,title:string,credit:string,sourceUrl:string,sourceLabel:string):ArchiveImage=>({url,title,credit,sourceUrl,sourceLabel});

export const archiveBatch204:Record<string,ArtistArchive>={
'zanele-muholi':{
 artistId:'zanele-muholi',
 projectCoverage:'作品级深化：Faces and Phases / Somnyama Ngonyama / Muholi V；从拍摄关系、道具选择、银盐输出到雕塑材料逐件说明',
 imageCoverage:'Guggenheim、ICP 与 Tate 官方页面均提供对应作品图像并明确作品版权/credit；本站记录官方图像入口与版权信息。由于未确认机构网页图片的再发布许可与稳定原图直链，本批次不复制网页缩略图，避免把展示许可误当作再发布许可。',
 note:'Muholi 的作品不宜只被概括成“身份摄影”。Faces and Phases 的核心是长期面对具体社群成员建立档案；Somnyama Ngonyama 则把镜头转向自身，用所在环境找到的普通物件临时构造角色；近年的青铜雕塑又把摄影中的身体政治转换为有重量、可长期占据公共空间的物体。',
 projects:[
  {title:'Faces and Phases — Xana Nyilenda / “TK” Thembi Khumalo / Anele “Anza” Khaba',cluster:'community portrait / gelatin silver print / serial archive',period:'2006–',summary:'Faces and Phases 是持续扩展的黑白肖像档案。Muholi 不是寻找匿名“类型”，而是在南非黑人 lesbian / queer 社群内部持续拍摄具体的人，并以姓名、地点和年份保留其主体性。Guggenheim 馆藏中的 Xana Nyilenda, Newtown, Johannesburg（2011）为 gelatin silver print，85.2 × 60 cm；“TK” Thembi Khumalo, BB Section Umlazi Township, Durban（2012）同为 gelatin silver print，85.2 × 60.5 cm。ICP 馆藏 Anele “Anza” Khaba（2011）纸张 86.4 × 61 cm、图像 76.8 × 50.2 cm。把这些单件放回系列可看到：系列的“材料”不仅是银盐纸基，也包括长期关系、命名、地点记录与重复拍摄形成的社会档案。',actions:['具体动作：与黑人 lesbian / queer / trans 社群中的参与者建立关系并持续拍摄，而不是一次性街头抓拍；人物通常直接面对镜头，使 sitter 与 viewer 的视线关系成为画面结构。','材料 / 工艺：Guggenheim 与 ICP 馆藏记录均确认代表作使用 gelatin silver print / photo-gelatin silver；不同馆藏版本尺寸约在 85 × 60 cm 纸面范围。','编排：作品标题保留人物姓名、社区/城市与拍摄地点；当多件并列时，观看从单个人像转为持续增长的群体档案，但每个人仍保持可辨认身份。','观看：正面凝视让观众无法只把人物当作关于“受害者”的说明图；Guggenheim 明确指出系列同时面对歧视、AIDS 与 hate crimes 的历史，又拒绝把被摄者缩减为受害形象。','图像 / 版权：Guggenheim 对 Xana Nyilenda 与 TK Thembi Khumalo 页面明确标注 © Zanele Muholi；ICP 对 Anele “Anza” Khaba 提供馆藏图与尺寸。本站只链接官方页面，不复制未确认再发布许可的馆藏图。'],sourceUrl:'https://www.guggenheim.org/artwork/31939',images:[],relations:[rel('机构','Solomon R. Guggenheim Museum','Xana Nyilenda 与 TK Thembi Khumalo 馆藏作品记录'),rel('机构','International Center of Photography','Anele “Anza” Khaba 馆藏记录')]},
  {title:'Somnyama Ngonyama — Hail the Dark Lioness',cluster:'self-portrait / found props / staged persona / gelatin silver print',period:'2012–',summary:'Somnyama Ngonyama 把 Muholi 从社群肖像的摄影者变成被摄者。制作方法并不是先设计昂贵布景，而是在旅行和工作所在环境中寻找当下可得的日常物件，再把它们组织到身体、头部和服装周围，构造临时 persona 后自拍。ICP 对 Muholi 的公开谈话记录指出，这些 self-portraits 通过身体上的 spontaneous arrangements 使用不同材料和物件，每张照片回应历史事件、刻板印象或个人经验；例如在 Malmö 的一幅作品把大量白色 chopsticks 插入头发。ICP 2022 的资料明确记录 Bester I, Mayotte（2015）为 gelatin silver print。',actions:['具体动作：先观察所在地点能够取得的日常物件，再把 clothespins、chopsticks、梳子等普通物件重新组织成头饰、服装或身体周围的临时结构；道具的原有用途与殖民、劳动、种族化观看之间产生新的联系。','具体动作：Muholi 同时担任摄影者、被摄者与角色设计者，通过 self-portrait 控制姿态、凝视、道具和最终图像，而不是让外部摄影者定义黑人身体。','材料 / 工艺：系列以黑白摄影为核心；ICP 对 Bester I, Mayotte（2015）明确登记为 gelatin silver print。具体单件的纸张、尺寸和 edition 必须逐件以馆藏/画廊记录核对，不把一个版本的规格套用到整个系列。','地点机制：Aperture/ICP 的第二卷资料说明 Muholi 持续在不同国际地点拍摄，并从每个环境取得 material props；因此地点不是背景标签，而直接决定可使用的道具和 persona。','观看：高对比黑白自画像与直视镜头强化皮肤、物件和背景之间的视觉关系；但作品意义来自物件的社会历史，而不是把“深黑肤色”当成纯形式效果。','图像 / 版权：ICP 的 Bester I 页面/活动资料标注 © Zanele Muholi，并注明 Courtesy of the artist, Yancey Richardson, New York, and Stevenson Cape Town/Johannesburg；本站保留这一 credit 链，不抓取活动页缩略图。'],sourceUrl:'https://www.icp.org/perspective/shifting-the-negative-an-evening-with-zanele-muholi',images:[],relations:[rel('机构','International Center of Photography','艺术家谈话与 Bester I 图像/credit'),rel('出版','Aperture / Hail the Dark Lioness','Somnyama Ngonyama 出版与持续项目记录')]},
  {title:'Muholi V / Muholi V maquette',cluster:'bronze sculpture / rest / monument / public-body politics',period:'2023–2024',summary:'Muholi V 把摄影实践中的自我呈现转换为三维雕塑：一个独自斜躺的人物由 bolster cushions 支撑，并由 blanket 轻轻覆盖。Tate 说明大型作品 Muholi V 制于 2023；为 2024 Tate Modern 展览制作的 Muholi V maquette 是 polished bronze，25 × 12.7 × 6.5 cm，edition 21，并置于 bespoke box。选择 bronze——传统公共纪念雕塑的重要材料——使“休息、自我保存”获得纪念碑式持续性。',actions:['具体动作：把斜躺、靠垫支撑和毯子遮盖这些私人休息姿态转译为可铸造的三维人物构图。','材料：2024 Tate limited-edition maquette 明确登记 polished bronze；尺寸 25 × 12.7 × 6.5 cm，edition 21，配 bespoke box。大型 2023 Muholi V 的具体尺寸与铸造版本应继续以正式作品记录核对。','材料意义：Tate 明确把 bronze 与公共雕塑传统联系起来；Muholi 用耐久、纪念碑式材料处理 Black queer people 的 rest / self-care，而不是英雄动作。','观看：与摄影中的平面正面凝视不同，雕塑要求观众绕行身体、靠垫和毯子的体积；休息姿态因此真正占据共享空间。','版本关系：2024 maquette 是与 Tate Modern 展览同期推出的较小青铜版本，来源页面明确说明它对应更大的 2023 Muholi V；本站将二者记录为尺度和用途不同的相关版本，而非同一尺寸作品。','图像 / 版权：Tate 官方商品/edition 页面提供作品图与完整规格；本站保留官方入口，不将商品图自动复制为本站作品资产。'],sourceUrl:'https://shop.tate.org.uk/muholi-v-maquette-2024-zanele-muholi-limited-edition-21-/53101.html',images:[],relations:[rel('展览','Tate Modern — Zanele Muholi','2024 exhibition context'),rel('机构','Tate','Muholi V maquette official edition record')]}
 ],
 awards:[],
 exhibitions:['Zanele Muholi — Tate Modern 2024–2025'],
 sources:[
  {label:'Guggenheim · Xana Nyilenda, Newtown, Johannesburg',url:'https://www.guggenheim.org/artwork/31939'},
  {label:'Guggenheim · “TK” Thembi Khumalo, BB Section Umlazi Township, Durban',url:'https://www.guggenheim.org/artwork/31941'},
  {label:'ICP · Anele “Anza” Khaba, KwaThema Community Hall',url:'https://www.icp.org/browse/archive/objects/anele-anza-khaba-kwathema-community-hall-springs-johannesburg'},
  {label:'ICP · Shifting the Negative: An Evening with Zanele Muholi',url:'https://www.icp.org/perspective/shifting-the-negative-an-evening-with-zanele-muholi'},
  {label:'ICP · Somnyama Ngonyama: Hail the Dark Lioness Vol. 2',url:'https://shop.icp.org/products/zanele-muholi-hail-the-dark-lioness-vol-2'},
  {label:'Tate · Muholi V maquette, 2024',url:'https://shop.tate.org.uk/muholi-v-maquette-2024-zanele-muholi-limited-edition-21-/53101.html'}
 ]
}
};
