import type { Artist } from './data';

export const broadeningBatch5: Artist[] = [
  {
    id: 'allan-sekula',
    name: 'Allan Sekula',
    born: '1951–2013',
    base: 'Los Angeles',
    intro: '把摄影、长篇文字、录像和长期田野结合起来研究劳动、港口、全球航运与资本流动，是把概念艺术之后的摄影重新带回社会结构分析的重要人物。',
    methods: ['社会纪实', '摄影 + 文本', '长期田野', '摄影书', '影像论文', '劳动研究'],
    subjects: ['劳动', '航运', '全球化', '港口', '阶级', '摄影政治'],
    outputs: ['摄影系列', '摄影书', '录像', '文本装置'],
    institutions: ['Getty Research Institute', 'Tate', 'documenta'],
    achievements: ['Fish Story 1989–1995', 'Getty Research Institute holds Allan Sekula archive'],
    whyImportant: '他反对把纪实摄影理解成“抓住决定性瞬间”，更强调多年研究、系列、文字和经济背景共同构成意义。对于理解当代研究型摄影几乎是基础节点。',
    projects: [{
      year: '1989–1995',
      title: 'Fish Story',
      type: 'photography + text / maritime labour / globalization',
      facts: ['多年走访 Los Angeles、San Diego、New York、Glasgow、Rotterdam、Vigo、Gdańsk、Hong Kong 等港口与航运节点。', '拍摄港口工人、码头、集装箱、船只与港口城市。', '同时记录访谈、工会与航运资料，并写作长篇文本。', '把照片、文字、地图式地理关系与展览空间共同组织成持续发展的项目。'],
      reading: 'Sekula 把通常“看不见”的海运系统变成摄影对象：全球商品看似无缝流动，背后却有具体劳动、港口空间和阶级关系。'
    }],
    images: [],
    sourceLabel: 'Getty Research Institute',
    sourceUrl: 'https://www.getty.edu/research/special_collections/notable/sekula.html'
  },
  {
    id: 'martha-rosler',
    name: 'Martha Rosler',
    born: '1943',
    base: 'New York',
    intro: '以摄影蒙太奇、录像、文字和行为持续批评战争、性别、家庭空间与媒体制度，尤其关注公共政治如何进入看似私人、安全的日常生活。',
    methods: ['photomontage', '挪用', '录像', '文本', '行为', '媒体批判'],
    subjects: ['战争', '家庭', '女性', '媒体', '消费社会', '公共 / 私人'],
    outputs: ['摄影蒙太奇', '录像', '装置', '表演', '文本'],
    institutions: ['MoMA', 'Whitney Museum', 'Dia Art Foundation'],
    achievements: ['House Beautiful: Bringing the War Home 1967–1972', 'Meta-Monumental Garage Sale — MoMA 2012'],
    whyImportant: '她把原本属于不同版面的图像直接碰撞：越战新闻照片进入室内设计广告后，“远方战争”与美国中产家庭的消费安全感不再能被分开。',
    projects: [{
      year: 'c. 1967–1972',
      title: 'House Beautiful: Bringing the War Home',
      type: 'cut-and-pasted photomontage / Vietnam War / domestic advertising',
      facts: ['从 Life 等新闻媒体选择 Vietnam War 相关照片。', '从 House Beautiful 等杂志选择美国中产阶级家庭与消费广告图像。', '以手工剪切和粘贴把战场、伤亡与军人置入洁净住宅内部。', '早期曾把作品的 photocopies 带到反战示威中传播，而不只在画廊展示。'],
      reading: '蒙太奇不是为了制造超现实感，而是拆掉媒体替观众建立的“那里 / 这里”边界：战争和舒适生活属于同一个政治系统。'
    }],
    images: [],
    sourceLabel: 'MoMA',
    sourceUrl: 'https://www.moma.org/collection/works/152791'
  },
  {
    id: 'john-akomfrah',
    name: 'John Akomfrah',
    born: '1957',
    base: 'London',
    intro: '以档案影像、原创拍摄、文学文本和多屏电影处理黑人英国史、迁徙、殖民、海洋与生态，把历史材料组织成非线性的影像交响。',
    methods: ['多屏电影', '档案影像', '原创摄影', '声音蒙太奇', '文学引用', 'essay film'],
    subjects: ['迁徙', '殖民', '黑人英国', '海洋', '生态', '历史记忆'],
    outputs: ['多屏录像装置', '电影', '声音环境'],
    institutions: ['Tate', 'SFMOMA', 'Venice Biennale'],
    achievements: ['Vertigo Sea — Venice Biennale 2015', 'British Pavilion — Venice Biennale 2024'],
    whyImportant: 'Akomfrah 把 archive footage 当作可重新编曲的历史材料，而不是说明文字；多块屏幕允许不同时间、地点和政治事件同时存在。',
    projects: [{
      year: '2015',
      title: 'Vertigo Sea',
      type: 'three-screen video installation / ocean archive / migration and ecology',
      facts: ['制作三屏影像装置。', '把 BBC 自然史等 archival footage 与新拍摄、历史重演式镜头并置。', '同时处理捕鲸、奴隶贸易、海上迁徙、殖民航行与海洋生态。', '使用高度编排的音乐与声音，把三个屏幕组织成彼此回应而非单线叙事。'],
      reading: '“海”在作品里既是壮丽自然景观，也是贸易、奴隶制、迁徙和死亡的历史媒介；视觉美感因此不断被政治历史打断。'
    }],
    images: [],
    sourceLabel: 'SFMOMA',
    sourceUrl: 'https://www.sfmoma.org/exhibition/john-akomfrah/'
  },
  {
    id: 'trinh-t-minh-ha',
    name: 'Trinh T. Minh-ha',
    chineseName: '郑明河',
    born: '1952',
    base: 'Berkeley',
    intro: '以电影、写作和理论持续质疑民族志纪录片的权力关系，拒绝把镜头前的人变成被解释、被代表、被分类的“他者”。',
    methods: ['essay film', '反民族志', '非同步声音', '碎片化剪辑', '写作', '理论研究'],
    subjects: ['再现伦理', '殖民凝视', '女性', '语言', '民族志', '后殖民'],
    outputs: ['16mm 电影', '录像', '书籍', '理论文本'],
    institutions: ['MoMA', 'Berkeley Art Museum / Pacific Film Archive'],
    achievements: ['Reassemblage 1982', 'Surname Viet Given Name Nam 1989'],
    whyImportant: '她对纪录摄影/纪录电影影响很大的一点是：不要假装摄影机可以透明地“替别人说话”。镜头位置、旁白、翻译与剪辑方式都必须被当成权力结构检查。',
    projects: [{
      year: '1982',
      title: 'Reassemblage',
      type: '16mm film / counter-ethnography / Senegal',
      facts: ['在 Senegal 农村拍摄，成片约 40 分钟。', '拒绝传统民族志电影中解释风俗、建立完整知识体系的旁白方式。', '将身体、劳动、建筑、火、儿童与日常动作切成开放的视觉片段。', '通过声音与图像不完全同步、重复和停顿，使观众无法把画面快速归类成“关于某种文化的知识”。'],
      reading: '作品的核心不是“介绍 Senegal”，而是拆解介绍别人这件事本身：摄影机怎样把人变成对象，纪录片怎样制造自己无所不知的幻觉。'
    }],
    images: [],
    sourceLabel: 'MoMA',
    sourceUrl: 'https://www.moma.org/calendar/events/10587'
  },
  {
    id: 'renee-green',
    name: 'Renée Green',
    born: '1959',
    base: 'Cambridge / New York',
    intro: '通过录像、声音、书籍、档案、建筑和参与式装置研究知识如何被分类、翻译与跨文化流通，常把展厅设计成临时图书馆、办公室或研究站。',
    methods: ['档案装置', '参与式研究', '录像', '声音', '文本', '空间设计'],
    subjects: ['文化流通', '黑人离散', '翻译', '音乐', '知识制度', '记忆'],
    outputs: ['混合媒介装置', '录像', '出版物', '声音', '网站 / CD-ROM'],
    institutions: ['Dia Art Foundation', 'MoMA PS1', 'MOCA Los Angeles', 'Whitney Biennial'],
    achievements: ['Import/Export Funk Office 1992–1993', 'Whitney Biennial 1993'],
    whyImportant: '她很早就把“研究资料”本身做成可供观众浏览和使用的空间，而不是把研究藏在作品背后。档案、播放设备、书架和观众行为共同构成作品。',
    projects: [{
      year: '1992–1993',
      title: 'Import/Export Funk Office',
      type: 'participatory archive / hip-hop circulation / mixed-media installation',
      facts: ['围绕 African American diasporic culture、hip-hop 及其在美国与德国之间的流通展开。', '收集 books、magazines、records、ephemera、videos 与访谈材料。', '用 heavy-duty shelving 组成类似办公室 / 图书馆的可进入空间。', '配置 monitors、headphones、cassette players、Funk Stations 与词汇翻译牌，使观众自行浏览和聆听。', '后来继续发展 CD-ROM 与 Web 版本，追踪资料如何在数字媒介中再次流通。'],
      reading: '作品不是一套“关于 hip-hop 的展板”，而是模拟知识被进口、出口、翻译、误读和重新拥有的过程。'
    }],
    images: [],
    sourceLabel: 'Migros Museum für Gegenwartskunst',
    sourceUrl: 'https://migrosmuseum.ch/en/works/61984'
  },
  {
    id: 'carrie-mae-weems',
    name: 'Carrie Mae Weems',
    born: '1953',
    base: 'Syracuse / New York',
    intro: '通过摄影、文字、录像和表演处理家庭、黑人历史、性别与权力，经常由自己扮演既是人物又是历史见证者的角色。',
    methods: ['编排摄影', '摄影 + 文本', '自我表演', '序列', '录像'],
    subjects: ['家庭', '黑人女性', '亲密关系', '历史', '权力', '观看'],
    outputs: ['银盐摄影', '文本面板', '录像', '装置'],
    institutions: ['MoMA', 'Guggenheim', 'Getty Museum'],
    achievements: ['Kitchen Table Series 1990', 'Guggenheim retrospective 2014'],
    whyImportant: '她证明了一张桌子和一盏灯就能建立高度复杂的社会舞台：人物关系、性别角色和自我形象通过同一空间中的连续表演逐渐变化。',
    projects: [{
      year: '1990',
      title: 'Kitchen Table Series',
      type: '20 gelatin silver prints + 14 text panels / staged domestic narrative',
      facts: ['在艺术家自己的厨房中完成。', '始终使用同一张木桌和桌上方单一吊灯作为舞台。', '由 Weems 自己扮演中心人物，并让朋友、孩子、恋人等轮流进入场景。', '全系列包含 20 张 gelatin silver prints 与 14 块 silkscreen text panels。', '通过人物、镜子、化妆品、书、扑克牌、鸟笼等道具变化建立连续叙事。'],
      reading: '固定空间反而让细小变化变得清楚：谁坐在桌边、谁离开、谁看谁，都成为家庭和性别权力结构的视觉语法。'
    }],
    images: [],
    sourceLabel: 'MoMA',
    sourceUrl: 'https://www.moma.org/artists/7177-carrie-mae-weems'
  },
  {
    id: 'lorna-simpson',
    name: 'Lorna Simpson',
    born: '1960',
    base: 'Brooklyn, New York',
    intro: '以摄影与简短文本拆解黑人女性如何被语言和视觉文化分类，常故意隐藏面孔、重复身体局部，使观看者无法获得完整而舒适的“人物信息”。',
    methods: ['摄影 + 文本', '重复', 'Polaroid', '碎片化身体', '装置'],
    subjects: ['黑人女性', '性别', '刻板印象', '身体', '语言', '监控'],
    outputs: ['摄影装置', '文本牌', '录像', '绘画'],
    institutions: ['MoMA', 'Whitney Museum', 'Venice Biennale'],
    achievements: ['Guarded Conditions 1989', 'Venice Biennale 1990'],
    whyImportant: '她不靠给人物更多信息来纠正刻板印象，反而主动减少信息：背对镜头、切割身体、加入模棱两可的文字，让观众意识到自己正在怎样快速判断一个黑人女性身体。',
    projects: [{
      year: '1989',
      title: 'Guarded Conditions',
      type: '18 Polaroid prints + engraved plaques + plastic letters',
      facts: ['使用 18 张 dye diffusion color Polaroid prints。', '同一位穿白色 shift dress 的黑人女性背对镜头出现多次。', '每个身体被切分成多个摄影块，形成近似档案格或 lineup 的重复结构。', '加入 21 块 engraved plastic plaques 与 17 个 plastic letters。', '让语言提示 sex attacks / skin attacks 等身体与社会暴力关系。'],
      reading: '重复身体既像人物识别系统，也像制度档案；观众越想确认“她是谁”，就越明显地进入分类与监控的观看机制。'
    }],
    images: [],
    sourceLabel: 'Lorna Simpson Studio',
    sourceUrl: 'https://lsimpsonstudio.com/photographic-works/1989'
  },
  {
    id: 'susan-meiselas',
    name: 'Susan Meiselas',
    born: '1948',
    base: 'New York',
    intro: '以长期纪实摄影、声音访谈、回访和档案再语境化工作，持续追问摄影师在政治冲突和私人生活中如何与被拍摄者建立关系。',
    methods: ['纪实摄影', '长期田野', '声音访谈', '回访', '档案再利用', '摄影书'],
    subjects: ['革命', '战争', '女性劳动', '人权', '记忆', '摄影伦理'],
    outputs: ['摄影', '摄影书', '电影', '档案项目'],
    institutions: ['Magnum Photos', 'MoMA', 'Whitney Museum'],
    achievements: ['Nicaragua 1978–1979', 'Magnum Photos member since 1976'],
    whyImportant: '她的价值不只在“拍到历史现场”，还在之后不断回到旧照片：寻找当事人、重新记录他们如何理解图像，让摄影的后续流通也成为作品问题。',
    projects: [{
      year: '1978–1979',
      title: 'Nicaragua',
      type: 'color documentary photography / revolution / later return project',
      facts: ['1978 年 6 月至 1979 年 7 月持续记录 Sandinista revolution 与 Somoza regime 末期。', '使用彩色摄影拍摄街头冲突、普通居民、游击队员与革命后的公共场景。', '照片随后通过新闻杂志、Magnum 与摄影书广泛流通。', '之后又返回 Nicaragua，寻找照片中的人并制作 Pictures from a Revolution 等回访项目。'],
      reading: '项目把“新闻照片拍完就结束”的逻辑拉长：照片如何被记住、被政治化，以及被拍摄者后来如何看待那张照片，同样属于摄影史。'
    }],
    images: [],
    sourceLabel: 'MoMA',
    sourceUrl: 'https://www.moma.org/collection/artists/45094'
  },
  {
    id: 'shirin-neshat',
    name: 'Shirin Neshat',
    born: '1957',
    base: 'New York',
    intro: '通过黑白摄影、书法文本和双屏电影处理伊朗、流亡、性别与宗教社会中的身体分隔，常把男性与女性放在不同空间和不同屏幕中。',
    methods: ['双屏录像', '黑白影像', '编排', '书法文本', '摄影'],
    subjects: ['伊朗', '性别', '宗教', '流亡', '身体', '公共 / 私人'],
    outputs: ['双屏录像', '摄影', '电影', '装置'],
    institutions: ['MoMA', 'Venice Biennale', 'Hirshhorn Museum'],
    achievements: ['Golden Lion — Venice Biennale 1999', 'Rapture 1999'],
    whyImportant: '她把性别分隔从主题直接变成空间结构：观众必须在两个相对屏幕之间不断转头，无法一次拥有完整画面。',
    projects: [{
      year: '1999',
      title: 'Rapture',
      type: 'two-channel black-and-white video / gendered spatial division',
      facts: ['制作 13 分钟双通道黑白有声录像。', '两个屏幕相对或并置呈现男性与女性群体。', '人物被置于不同建筑、荒漠和海岸空间，通过高度编排的集体动作建立对照。', '声音与画面在两个屏幕之间形成回应，迫使观众选择观看方向。'],
      reading: '作品不是用旁白解释性别制度，而是让观看者在物理上体验“无法同时看见双方”的分隔。'
    }],
    images: [],
    sourceLabel: 'MoMA',
    sourceUrl: 'https://www.moma.org/collection/works/153240'
  },
  {
    id: 'stan-douglas',
    name: 'Stan Douglas',
    born: '1960',
    base: 'Vancouver / Los Angeles',
    intro: '以电影级场景重建、数字合成、录像和大型摄影重访被城市历史忽略的事件，让一张看似纪实的照片实际上由大量表演和技术重构完成。',
    methods: ['历史重演', '大型摄影', '电影布景', '数字合成', '录像装置'],
    subjects: ['城市冲突', '历史记忆', 'Vancouver', '阶级', '媒体', '技术'],
    outputs: ['大型摄影', '录像装置', '电影', '公共艺术'],
    institutions: ['Venice Biennale', 'National Gallery of Canada', 'International Center of Photography'],
    achievements: ['Canada Pavilion — Venice Biennale 2022', 'Abbott & Cordova, 7 August 1971'],
    whyImportant: '他的照片经常拥有新闻摄影般可信的细节，却是经过历史研究、演员调度、布景、灯光和数字拼接重建出来的。它迫使观众区分“纪实外观”与“事实生产方式”。',
    projects: [{
      year: '2008',
      title: 'Abbott & Cordova, 7 August 1971',
      type: 'staged historical panorama / public mural / Gastown Riot',
      facts: ['以 Vancouver 1971 年 Gastown Riot 为历史事件。', '研究当年的新闻与城市档案后重新搭建人物和街道场景。', '使用大量演员重演警察、抗议者与旁观者之间的冲突。', '通过分阶段拍摄与数字合成形成一张超大规模、细节密集的全景图像。', '作品后来被制成约 30 × 50 英尺的 translucent photo mural，安装在 Woodward’s complex。'],
      reading: '它像一张“现场抓拍”，但几乎所有内容都经过重建；这种矛盾让历史摄影的可信感本身成为主题。'
    }],
    images: [],
    sourceLabel: 'International Center of Photography',
    sourceUrl: 'https://www.icp.org/content/stan-douglas'
  }
];
