import type { Artist } from './data';

export const broadeningBatch6: Artist[] = [
  {
    id: 'rineke-dijkstra',
    name: 'Rineke Dijkstra',
    born: '1959',
    base: 'Amsterdam',
    intro: '以大画幅相机和正面、克制的构图拍摄青少年、产妇、斗牛士、士兵等处在身份转换中的人，让细小姿势和紧张感承担肖像意义。',
    methods: ['大画幅肖像', '正面构图', '闪光灯', '长期追踪', '录像肖像'],
    subjects: ['青春期', '身份转换', '身体', '军队', '母职', '肖像'],
    outputs: ['大型彩色摄影', '录像装置', '摄影系列'],
    institutions: ['Guggenheim', 'MoMA', 'Stedelijk Museum'],
    achievements: ['Beach Portraits 1992–2002', 'Hasselblad Award 2017'],
    whyImportant: '她的肖像几乎不靠复杂场景，反而通过统一拍摄方式放大人物无法完全控制的姿势、表情和身体状态。',
    projects: [{
      year: '1992–2002',
      title: 'Beach Portraits',
      type: 'large-format color portrait / adolescent transition',
      facts: ['在美国、欧洲等不同海滩寻找刚从水里出来或准备游泳的青少年与年轻人。', '使用大画幅相机进行正面、全身拍摄。', '常以闪光灯平衡强烈日光，使人物与空旷海岸背景都保持清晰。', '让人物自己站立而不过度指导姿势，因此身体紧张、手势和重心变化成为图像重点。'],
      reading: '背景几乎被简化成海、沙和天空后，青春期身体中那些介于自信与不安之间的小动作变得非常明显。'
    }],
    images: [],
    sourceLabel: 'Solomon R. Guggenheim Museum',
    sourceUrl: 'https://www.guggenheim.org/artwork/artist/rineke-dijkstra'
  },
  {
    id: 'wolfgang-tillmans',
    name: 'Wolfgang Tillmans',
    born: '1968',
    base: 'Berlin / London',
    intro: '把朋友、夜生活、政治现场、静物、抽象暗房实验和不同尺寸打印混在同一个展览系统里，持续拆解“什么才算值得被放大的照片”。',
    methods: ['快照', '暗房实验', '无相机摄影', '喷墨打印', '展览编排', '社会观察'],
    subjects: ['日常生活', '酷儿文化', '政治', '身体', '图像材料性', '亲密关系'],
    outputs: ['摄影', '无相机抽象图像', '展览装置', '声音'],
    institutions: ['Tate', 'MoMA', 'Guggenheim'],
    achievements: ['Turner Prize 2000', 'To look without fear — MoMA 2022–2023'],
    whyImportant: '他把摄影展从“每张照片等大、等距、装框”中解放出来：一张 A4 纸和几米大的作品可以并置，展览编辑本身成为摄影语言。',
    projects: [{
      year: '2000s–ongoing',
      title: 'Freischwimmer',
      type: 'camera-less darkroom photography / light drawing',
      facts: ['不通过相机拍摄外部对象，而直接在暗房中处理感光材料。', '通过移动光源、控制曝光与化学显影形成流动的线条和颜色。', '每件作品来源于具体暗房过程，却保留难以还原的偶然形态。', '抽象作品经常与人物、政治现场和日常照片在同一展览中并置。'],
      reading: '它说明 Tillmans 并不把摄影等同于“拍到什么”，而是把光、纸张、化学和展示关系都当成摄影。'
    }],
    images: [],
    sourceLabel: 'MoMA',
    sourceUrl: 'https://www.moma.org/calendar/exhibitions/5433'
  },
  {
    id: 'thomas-demand',
    name: 'Thomas Demand',
    born: '1964',
    base: 'Berlin / Los Angeles',
    intro: '根据新闻或档案照片，用纸和纸板按真实尺度重建事件空间，再把模型摄影并销毁，使最终照片处在事实、模型和记忆之间。',
    methods: ['纸模型', '1:1 场景重建', '再摄影', '档案图像', '雕塑', '摄影'],
    subjects: ['媒体事件', '犯罪现场', '政治', '记忆', '摄影可信度', '建筑'],
    outputs: ['大型彩色摄影', '纸模型', '动画电影'],
    institutions: ['MoMA', 'Neue Nationalgalerie', 'Fondazione Prada'],
    achievements: ['Thomas Demand — MoMA 2005', 'Room (Zimmer) 1996'],
    whyImportant: '他的照片乍看像真实室内，但所有细节都被纸模型重新制造。摄影不再证明“这里曾经存在”，反而记录一个专为拍照存在、拍完就消失的假现场。',
    projects: [{
      year: '1996',
      title: 'Room (Zimmer)',
      type: 'paper reconstruction / chromogenic photograph / mediated event',
      facts: ['以一张 L. Ron Hubbard 曾居住和工作的酒店房间照片为来源。', '用纸与纸板重新制作房间模型。', '模型保留家具和整体结构，却故意缺少闹钟数字、打字机按键等细节。', '以均匀 studio lighting 拍摄模型，最终形成大型 chromogenic print。'],
      reading: '最终照片看起来比新闻图还“干净可信”，但它其实是照片→纸模型→照片的第二次翻译，正好暴露我们为什么会相信摄影。'
    }],
    images: [],
    sourceLabel: 'MoMA',
    sourceUrl: 'https://www.moma.org/collection/works/57201'
  },
  {
    id: 'richard-mosse',
    name: 'Richard Mosse',
    born: '1980',
    base: 'New York / Ireland',
    intro: '使用原本服务军事监测或工业测量的成像技术拍摄战争、迁徙与生态危机，把技术的观看能力和伦理限制同时暴露出来。',
    methods: ['军用红外胶片', '热成像', '多屏影像', '大型摄影', '技术挪用'],
    subjects: ['战争', '迁徙', '刚果', '边境', '气候危机', '机器视觉'],
    outputs: ['大型摄影', '多屏录像', '热成像影片', '摄影书'],
    institutions: ['Venice Biennale', 'Barbican', 'SFMOMA'],
    achievements: ['Irish Pavilion — Venice Biennale 2013', 'Deutsche Börse Photography Prize 2014 shortlisted'],
    whyImportant: '他不是用“漂亮色彩”包装战争，而是故意借用军事观看技术：观众看到的异常颜色本身就来自战争机器。',
    projects: [{
      year: '2013',
      title: 'The Enclave',
      type: 'six-channel video / infrared military film / eastern Congo',
      facts: ['在 Democratic Republic of Congo 东部冲突地区拍摄。', '使用已停产的 Kodak Aerochrome infrared film，该材料原本用于军事侦察和植被识别。', '红外胶片把绿色植被转译成强烈粉红和洋红色。', '将拍摄材料组织为六屏沉浸式影像，并配置空间化声音。'],
      reading: '作品的美感和暴力不可分开：越迷人的粉红景观，越提醒观众这种颜色来自军事监测技术。'
    }],
    images: [],
    sourceLabel: 'Richard Mosse Studio',
    sourceUrl: 'https://www.richardmosse.com/projects/the-enclave'
  },
  {
    id: 'zoe-leonard',
    name: 'Zoe Leonard',
    born: '1961',
    base: 'New York',
    intro: '从城市街道、消费物、旧相机和档案式序列出发研究商品流动、城市消失与模拟摄影，同时持续关注摄影作为物件和制度的历史。',
    methods: ['街头摄影', '模拟摄影', '网格序列', '长期档案', '城市观察'],
    subjects: ['城市变化', '全球化', '商品流通', '摄影技术', '社区', '消失'],
    outputs: ['彩色摄影', '银盐摄影', '摄影装置', '摄影书'],
    institutions: ['MoMA', 'Whitney Museum', 'Hauser & Wirth'],
    achievements: ['Analogue 1998–2009', 'Whitney Museum survey 2018'],
    whyImportant: '她把一家小店、一块手写招牌和一件二手衣服的流通连到全球商品系统；同时坚持用逐渐过时的模拟摄影技术记录“过时”。',
    projects: [{
      year: '1998–2009',
      title: 'Analogue',
      type: '412 photographs / 25 chapters / urban archive and global trade',
      facts: ['从 Manhattan Lower East Side 附近逐渐消失的 mom-and-pop stores 开始拍摄。', '后来沿着二手衣服、广告和过时摄影用品的流通路线前往 Africa、Eastern Europe、Cuba、Mexico 与 Middle East。', '全项目包含 412 张照片，并以 25 个章节和 serial grids 编排。', '使用 1940s Rolleiflex、胶片、gelatin silver 与 chromogenic printing，保留负片边缘。'],
      reading: '项目的“模拟”既指模拟摄影，也指照片作为现实的 analogue；正在消失的商业空间和正在过时的摄影技术互相映照。'
    }],
    images: [],
    sourceLabel: 'MoMA',
    sourceUrl: 'https://www.moma.org/collection/works/171309'
  },
  {
    id: 'tacita-dean',
    name: 'Tacita Dean',
    born: '1965',
    base: 'Berlin / Los Angeles',
    intro: '长期坚持模拟胶片、黑板画和摄影，关注时间、偶然、消失中的技术与电影物质性，常直接在胶片和放映结构内部工作。',
    methods: ['16mm / 35mm film', '模拟特效', '黑板画', '长镜头', '胶片拼接'],
    subjects: ['时间', '消失', '电影材料', '记忆', '偶然', '自然'],
    outputs: ['胶片装置', '电影', '黑板画', '摄影'],
    institutions: ['Tate Modern', 'Royal Academy', 'National Gallery London'],
    achievements: ['FILM — Tate Modern Turbine Hall Commission 2011'],
    whyImportant: '在数字影像占据主流之后，她反而把胶片的齿孔、遮片、曝光和放映机都推到前台，让媒介自身成为主题。',
    projects: [{
      year: '2011',
      title: 'FILM',
      type: '35mm portrait-format film installation / analogue effects',
      facts: ['为 Tate Modern Turbine Hall 制作大型 35mm film installation。', '采用垂直 portrait-format projection，使投影像高大的电影胶片条。', '大量效果通过 masking、multiple exposure、glass matte painting 等模拟方法直接完成，而非后期数字合成。', '让胶片画格、颜色、孔洞和投影结构本身成为可见内容。'],
      reading: '作品像一座给模拟电影建立的临时纪念碑：观看的不只是影片里的景物，也是在看“胶片怎样让影像出现”。'
    }],
    images: [],
    sourceLabel: 'Tate',
    sourceUrl: 'https://www.tate.org.uk/whats-on/tate-modern/tacita-dean-film'
  },
  {
    id: 'anri-sala',
    name: 'Anri Sala',
    born: '1974',
    base: 'Berlin',
    intro: '以录像、声音和建筑空间研究音乐、时间与政治记忆，常把同一段音乐拆成不同演奏、延迟和空间位置，让展厅像一套可行走的剪辑系统。',
    methods: ['录像', '声音空间', '音乐重演', '同步 / 失同步', '建筑介入'],
    subjects: ['音乐', '时间', '记忆', '政治', '空间', '同步'],
    outputs: ['录像装置', '声音装置', '雕塑', '绘图'],
    institutions: ['Venice Biennale', 'New Museum', 'Centre Pompidou'],
    achievements: ['France Pavilion — Venice Biennale 2013', 'Ravel Ravel Unravel 2013'],
    whyImportant: 'Sala 把剪辑从屏幕时间扩展成真实空间：两位钢琴家、两个版本和一个 DJ 的同步失败，必须由观众在不同房间之间走动才能理解。',
    projects: [{
      year: '2013',
      title: 'Ravel Ravel Unravel',
      type: 'multi-channel video and sound / musical desynchronization',
      facts: ['邀请两位钢琴家分别演奏 Maurice Ravel 的 Piano Concerto for the Left Hand。', '两场演奏分别拍摄并在空间中以相邻屏幕与定向声音呈现。', '两个版本速度存在细微差异，因此同一作品不断产生靠近和分离。', '另一部分 Unravel 记录 DJ 尝试用唱盘手工把两段演奏重新同步。'],
      reading: '同步在这里不是技术问题，而变成作品内容：即使来自同一乐谱，两次演奏也无法真正重合。'
    }],
    images: [],
    sourceLabel: 'Anri Sala Studio',
    sourceUrl: 'https://anrisala.com/works/ravel-ravel-unravel/'
  },
  {
    id: 'paul-graham',
    name: 'Paul Graham',
    born: '1956',
    base: 'New York / Europe',
    intro: '把社会纪实摄影从单张强事件转向普通、短暂甚至几乎“没发生什么”的生活序列，以书籍和多张连续图像重新组织现实。',
    methods: ['彩色纪实', '序列摄影', '摄影书', '街头观察', '多图叙事'],
    subjects: ['阶级', '日常生活', '美国', '失业', '社会边缘', '时间'],
    outputs: ['摄影书', '彩色摄影', '展览序列'],
    institutions: ['MoMA', 'Pace Gallery', 'Deutsche Börse Photography Foundation Prize'],
    achievements: ['A Shimmer of Possibility 2004–2006', 'Deutsche Börse Photography Prize 2009'],
    whyImportant: '他把摄影的“决定性瞬间”拆开成几秒钟内的多个微小变化，让一件普通事情像短篇小说一样通过序列逐渐出现。',
    projects: [{
      year: '2004–2006',
      title: 'A Shimmer of Possibility',
      type: '12 photographic sequences / American everyday life / photobook',
      facts: ['在美国旅行中拍摄街道、草地、公交站、停车场和普通人物。', '不追求单张新闻性高潮，而经常在同一地点连续拍摄短时间内的动作变化。', '把项目分成十二个独立 photographic sequences。', '出版时每个序列以独立小册 / volume 的方式组织，使翻页速度成为观看节奏。'],
      reading: '现实并不总有“关键瞬间”；Graham 把摄影从猎取高潮转成观察时间，让极普通动作获得叙事。'
    }],
    images: [],
    sourceLabel: 'MoMA',
    sourceUrl: 'https://www.moma.org/artists/2281'
  },
  {
    id: 'collier-schorr',
    name: 'Collier Schorr',
    born: '1963',
    base: 'Brooklyn, New York',
    intro: '在肖像、时尚和历史重演之间处理青年身体、性别与国家身份，尤其长期在德国南部拍摄男性青年并借用艺术史姿势重新编码他们。',
    methods: ['肖像', '长期田野', '艺术史重演', '时尚摄影', '文本'],
    subjects: ['性别', '青春期', '德国历史', '男性身体', '身份', '凝视'],
    outputs: ['摄影', '摄影书', '杂志项目', '装置'],
    institutions: ['MoMA', 'Walker Art Center', '303 Gallery'],
    achievements: ['Forest and Fields project', 'Jens F. series'],
    whyImportant: '她故意让纪实肖像、时尚姿势和艺术史引用彼此混淆，使“一个男孩是谁”无法被国籍、性别或外貌直接固定。',
    projects: [{
      year: '2001–2005',
      title: 'Jens F.',
      type: 'portrait series / gender / art-historical reenactment',
      facts: ['长期拍摄德国青年 Jens。', '让人物在室内、自然环境与更私密的场景中反复出现。', '部分姿势与构图借鉴 Andrew Wyeth 长期描绘 Helga Testorf 的作品。', '通过把原本用于女性身体的艺术史姿势转移到年轻男性身上，模糊传统性别观看。'],
      reading: '项目既像私人肖像，又像对艺术史“谁有权被这样观看”的重演；性别因此不是人物固有标签，而是在姿势和观看中被制造。'
    }],
    images: [],
    sourceLabel: '303 Gallery',
    sourceUrl: 'https://www.303gallery.com/artists/collier-schorr'
  },
  {
    id: 'roni-horn',
    name: 'Roni Horn',
    born: '1955',
    base: 'New York / Iceland',
    intro: '以摄影、玻璃雕塑、绘图和语言研究身份、天气、水与重复，常通过几乎相同的图像并置让观看者发现“同一事物”其实不断变化。',
    methods: ['序列肖像', '重复', '成对展示', '玻璃雕塑', '文本', '长期地景研究'],
    subjects: ['身份', '天气', '水', 'Iceland', '变化', '观看'],
    outputs: ['摄影装置', '玻璃雕塑', '绘图', '艺术家书'],
    institutions: ['Guggenheim', 'Tate Modern', 'Art Institute of Chicago'],
    achievements: ['You are the Weather 1994–1996', 'Tate Modern / Whitney survey 2009'],
    whyImportant: '她让肖像从“识别一个人”转向“观察变化”：同一张脸重复一百次后，天气、湿度、表情和观看者自己的判断开始比身份更重要。',
    projects: [{
      year: '1994–1996',
      title: 'You are the Weather',
      type: '100 close-up portraits / serial installation / Iceland',
      facts: ['在 Iceland 的 hot springs 与 swimming pools 拍摄同一位女性 Margrét H. Blöndal。', '以非常接近的头肩构图重复拍摄约一百张肖像。', '人物表情只发生细微变化，而水、光和天气不断改变。', '展览时将大量照片按连续带状结构安装，使观众通过比较而非单张识别人像。'],
      reading: '当“同一个人”被重复到一百次，身份反而变得不稳定；照片之间的微差成为观看真正发生的地方。'
    }],
    images: [],
    sourceLabel: 'Roni Horn Studio',
    sourceUrl: 'https://www.ronihorn.com/'
  }
];
