import type { Artist } from './data';

export const broadeningBatch4: Artist[] = [
  {
    id: 'zineb-sedira',
    name: 'Zineb Sedira',
    born: '1963',
    base: 'London / Paris / Algiers',
    intro: '以电影、摄影、档案和空间装置处理阿尔及利亚独立史、跨地中海文化流动与个人记忆，常把旧电影、家庭故事和展览现场重新组织成可进入的电影布景。',
    methods: ['电影装置', '档案研究', '重拍', '场景重建', '摄影', '个人叙事'],
    subjects: ['阿尔及利亚', '反殖民', '电影史', '迁徙', '记忆', '地中海'],
    outputs: ['电影', '录像装置', '摄影', '空间装置'],
    institutions: ['Venice Biennale', 'Tate', 'Centre Pompidou'],
    achievements: ['France Pavilion — Venice Biennale 2022', 'Special Mention — Venice Biennale 2022'],
    whyImportant: '她把“档案研究”变成一种真正可进入的场景：观众在电影布景、旧胶片、家具和重演之间移动，历史不是被陈列，而是被再次拍摄和表演。',
    projects: [{
      year: '2022',
      title: 'Dreams Have No Titles / Les rêves n’ont pas de titre',
      type: 'film installation / archive / reconstructed cinema sets',
      facts: ['代表法国参加第 59 届 Venice Biennale。', '把法国馆内部改造成介于电影制片厂、客厅和放映空间之间的环境。', '通过 remake 与 mise en abyme 重访 1960 年代反殖民与跨地中海电影。', '在研究中重新发现并修复 Ennio Lorenzini 1964 年电影 Les Mains libres 的胶片，该片被视为早期意大利—阿尔及利亚合拍片。', '把档案材料、个人记忆与新拍摄影像并置。'],
      reading: '项目不是怀旧地“恢复一部老电影”，而是把电影史看成政治联盟与文化交换留下的物质档案，再通过布景和重演让它重新发生。'
    }],
    images: [],
    sourceLabel: 'La Biennale di Venezia',
    sourceUrl: 'https://www.labiennale.org/en/art/2022/national-participations/france'
  },
  {
    id: 'wangechi-mutu',
    name: 'Wangechi Mutu',
    born: '1972',
    base: 'Nairobi / New York',
    intro: '以拼贴、雕塑、影像和绘画拆解时尚、色情、民族志和大众媒体中的黑人女性身体，把切碎的图像重组为混合人、动物、机器和植物的身体。',
    methods: ['拼贴', '切割与粘贴', '绘画', '雕塑', '挪用图像', '混合媒介'],
    subjects: ['黑人女性', '殖民凝视', '身体', '非洲未来主义', '性别', '混种'],
    outputs: ['拼贴', '雕塑', '录像', '绘画', '装置'],
    institutions: ['MoMA', 'The Metropolitan Museum of Art', 'New Museum'],
    achievements: ['The NewOnes, will free Us — The Met Facade Commission 2019', '作品进入 MoMA collection'],
    whyImportant: '她不是用摄影杂志图像“说明身份”，而是把这些本来承担消费和殖民凝视的身体碎片切开重组，使图像来源本身成为被批判的材料。',
    projects: [{
      year: '2003',
      title: 'Yo Mama',
      type: 'collage / painted paper / cut printed imagery',
      facts: ['以纸上拼贴为基础，将印刷图像切割后重新组合。', '同时使用 ink、mica flakes、acrylic 与 pressure-sensitive film 等材料。', '在拼贴表面继续绘画，使摄影碎片与手工痕迹难以分开。', '形象受到尼日利亚反殖民与女性主义活动家 Funmilayo Anikulapo-Kuti 启发。'],
      reading: '作品把英雄肖像做成混合身体：政治人物、时尚图像、动物与机械碎片彼此侵入，拒绝让“非洲女性”被固定成单一可识别类型。'
    }],
    images: [],
    sourceLabel: 'MoMA',
    sourceUrl: 'https://www.moma.org/artists/13379'
  },
  {
    id: 'sondra-perry',
    name: 'Sondra Perry',
    born: '1986',
    base: 'New York',
    intro: '使用 chroma-key 蓝幕、3D 扫描、游戏引擎、开源软件和网络素材研究黑人身体如何被数字技术捕捉、复制、商品化和监控。',
    methods: ['chroma key', '3D 扫描', '数字动画', '网络挪用', '开源软件', '沉浸式录像'],
    subjects: ['黑人身份', '数字身体', '监控', '平台', '技术权力', '再现'],
    outputs: ['录像装置', '数字动画', '声音', '互动装置'],
    institutions: ['MoMA', 'Serpentine Galleries', 'ICA Philadelphia'],
    achievements: ['Typhoon coming on — Serpentine Sackler Gallery 2018'],
    whyImportant: '她把数字工具界面本身暴露出来：蓝幕、扫描错误、低清模型和软件痕迹不被隐藏，而成为讨论“谁被技术正确识别”的核心材料。',
    projects: [{
      year: '2018',
      title: 'Typhoon coming on',
      type: 'immersive digital installation / manipulated historical image / soundscape',
      facts: ['为 Serpentine Sackler Gallery 制作沉浸式环境。', '数字处理 J. M. W. Turner 的 The Slave Ship，使历史绘画进入不断变化的动态图像。', '结合 chroma-key 蓝幕色、数字影像与大型声音环境。', '持续使用 3D avatar、网络 found footage 与开源工具，把历史图像和当代数字基础设施连接。'],
      reading: '她没有把数字技术当透明工具，而是让压缩、失真、扫描和颜色键控都保持可见，使技术的偏差成为观看对象。'
    }],
    images: [],
    sourceLabel: 'Serpentine Galleries',
    sourceUrl: 'https://www.serpentinegalleries.org/whats-on/sondra-perry-typhoon-coming-on/'
  },
  {
    id: 'arthur-jafa',
    name: 'Arthur Jafa',
    born: '1960',
    base: 'Los Angeles',
    intro: '通过电影、摄影、挪用影像和高速蒙太奇研究黑人视觉文化，尤其关注音乐节奏如何转译成影像结构，以及暴力、欢乐、体育和流行文化怎样同时构成黑人经验。',
    methods: ['影像挪用', '蒙太奇', '音乐剪辑', '档案影像', '电影摄影'],
    subjects: ['黑人文化', '暴力', '音乐', '媒体', '美国', '集体记忆'],
    outputs: ['录像', '电影', '摄影', '装置'],
    institutions: ['MoMA', 'Hirshhorn Museum', 'Venice Biennale'],
    achievements: ['Golden Lion — Venice Biennale 2019', 'Love Is the Message, The Message Is Death 2016'],
    whyImportant: 'Jafa 的核心不是单纯搜集 viral clips，而是用接近音乐采样的方式建立影像节奏：不同来源和情绪的画面被剪成一个无法被单一叙事概括的黑人视觉经验。',
    projects: [{
      year: '2016',
      title: 'Love Is the Message, The Message Is Death',
      type: 'found-footage video / montage / music',
      facts: ['制作约 7 分 30 秒的彩色与黑白有声录像。', '拼接新闻、历史影像、体育、音乐表演、手机拍摄和警察暴力等不同来源素材。', '将欢乐、成就、宗教、日常与暴力画面高密度交替。', '使用 Kanye West 的 Ultralight Beam 作为贯穿影片的声音结构。'],
      reading: '影像没有被整理成“受害史”或“成就史”中的任何一种，而是让矛盾情绪同时存在；剪辑节奏本身承担思想。'
    }],
    images: [],
    sourceLabel: 'Hirshhorn Museum',
    sourceUrl: 'https://hirshhorn.si.edu/exhibitions/arthur-jafa-love-is-the-message-the-message-is-death/'
  },
  {
    id: 'kapwani-kiwanga',
    name: 'Kapwani Kiwanga',
    born: '1978',
    base: 'Paris',
    intro: '以人类学、殖民档案、植物、颜色和材料研究权力如何嵌入建筑、贸易与日常物质，在雕塑和空间装置中把看似中性的材料重新连接到历史制度。',
    methods: ['档案研究', '材料研究', '场域特定', '雕塑', '装置', '颜色研究'],
    subjects: ['殖民', '贸易', '权力', '建筑', '植物', '历史材料'],
    outputs: ['雕塑', '装置', '影像', '表演讲演'],
    institutions: ['Venice Biennale', 'Centre Pompidou', 'Hammer Museum'],
    achievements: ['Canada Pavilion — Venice Biennale 2024', 'Marcel Duchamp Prize 2020'],
    whyImportant: '她擅长从“微不足道”的材料追出宏观制度：一颗珠子、一种墙面颜色、一株植物都可能连接殖民贸易、监狱管理或知识分类。',
    projects: [{
      year: '2024',
      title: 'Trinket',
      type: 'site-specific installation / seed beads / global trade',
      facts: ['代表 Canada 参加第 60 届 Venice Biennale。', '以 Murano 与 Venice 长期生产的 seed beads / conterie 为核心材料。', '研究这些微小玻璃珠曾作为装饰物，也曾参与全球交换、货币与殖民贸易。', '把成千上万颗细小珠子组织成跨越 pavilion 内外的巨型场域装置。'],
      reading: '作品故意从极小尺度出发：一颗珠子看似只是装饰，但当它被放回贸易路线，就会显出货币、劳动力和殖民关系。'
    }],
    images: [],
    sourceLabel: 'La Biennale di Venezia',
    sourceUrl: 'https://www.labiennale.org/en/art/2024/canada'
  },
  {
    id: 'martine-syms',
    name: 'Martine Syms',
    born: '1988',
    base: 'Los Angeles',
    intro: '把电影、短信界面、监控、表演、出版与网络语言混合，研究黑人身份如何在手机、社交媒体、家庭影像和流行文化中被不断生产。',
    methods: ['三屏录像', '表演', '数字界面', '增强现实', '文本', '出版'],
    subjects: ['黑人身份', '监控', '社交媒体', '表演', '语言', '流行文化'],
    outputs: ['录像装置', '摄影', 'AR', '出版物', '电影'],
    institutions: ['MoMA', 'ICA London', 'Hammer Museum'],
    achievements: ['Projects 106: Martine Syms — MoMA 2017'],
    whyImportant: '她把手机界面、对话碎片、监控视角和表演并排，让当代身份不再只是“被拍摄的脸”，而成为跨屏幕持续表演和被记录的过程。',
    projects: [{
      year: '2017',
      title: 'Incense Sweaters & Ice',
      type: 'three-channel video / AR / installation',
      facts: ['为 MoMA Projects 106 制作约 69 分钟三通道彩色有声录像。', '展览同时包含彩色 window film、wall painting、steel benches 和 12 张 archival pigment prints on found posters。', '配套开发增强现实 app，使手机成为展览观看的一部分。', '故事围绕监控、网络观看与黑人女性角色如何在不同图像系统中被追踪展开。'],
      reading: '这里“多屏”不是形式炫技：角色在不同设备、视角和平台之间持续切换，使观看和被观看本身成为叙事。'
    }],
    images: [],
    sourceLabel: 'MoMA',
    sourceUrl: 'https://www.moma.org/calendar/exhibitions/3824'
  },
  {
    id: 'sammy-baloji',
    name: 'Sammy Baloji',
    born: '1978',
    base: 'Lubumbashi / Brussels',
    intro: '从刚果矿业、殖民档案和工业遗迹出发，将历史照片与当代矿区景观并置，追踪殖民资源开采如何继续塑造今天的经济与土地。',
    methods: ['档案挪用', '摄影蒙太奇', '工业景观', '殖民档案', '装置'],
    subjects: ['刚果', '矿业', '殖民', '资源开采', '劳动', '工业遗产'],
    outputs: ['摄影蒙太奇', '摄影', '装置', '录像'],
    institutions: ['Smithsonian National Museum of African Art', 'The Walther Collection', 'Venice Biennale'],
    achievements: ['Mémoire 2006', 'Prix Pictet 2019 shortlisted'],
    whyImportant: '他的蒙太奇不是把“过去与现在”做成装饰性对比，而是让殖民时期的工人身体重新出现在今天废弃的矿山里，直接显示资源史并未结束。',
    projects: [{
      year: '2006',
      title: 'Mémoire',
      type: 'archival photomontage / Katanga mining landscapes',
      facts: ['研究 Union Minière du Haut Katanga 等殖民矿业档案。', '选取殖民时期矿工、官员与工业活动的历史照片。', '重新拍摄 Katanga 当代废弃或衰败的矿山与工业设施。', '把历史人物从档案背景中切出并叠加到当代景观中。'],
      reading: '两种时间被硬性缝在一起后，工业废墟不再像“过去已经结束”的遗迹，而成为殖民经济继续作用于今天的证据。'
    }],
    images: [],
    sourceLabel: 'The Walther Collection',
    sourceUrl: 'https://www.walthercollection.com/en/collection/artists/sammy-baloji'
  },
  {
    id: 'the-otolith-group',
    name: 'The Otolith Group',
    born: 'founded 2002',
    base: 'London',
    intro: '由 Anjalika Sagar 与 Kodwo Eshun 组成，以电影散文、档案研究、声音和策展处理殖民史、气候、资本与科幻，把理论写作和影像蒙太奇结合成复杂的知识结构。',
    methods: ['essay film', '档案研究', '挪用影像', '理论写作', '声音', '策展'],
    subjects: ['殖民', '资本主义', '气候', '科幻', '黑人激进思想', '海洋'],
    outputs: ['电影', '录像装置', '出版物', '策展项目'],
    institutions: ['Tate', 'MACBA', 'Turner Prize'],
    achievements: ['Turner Prize 2010 shortlisted', 'Hydra Decapita 2010'],
    whyImportant: '他们把影像论文做到非常高密度：一个作品可以同时调用历史事件、科幻音乐、文学、金融史和艺术史，但通过剪辑保持这些知识之间的具体连接。',
    projects: [{
      year: '2010',
      title: 'Hydra Decapita',
      type: 'HD video / essay film / slavery and finance',
      facts: ['制作约 31 分钟单通道 HD 彩色有声录像。', '以电子音乐组合 Drexciya 构造的水下黑人文明神话为重要线索。', '连接 1781 年 Zong 奴隶船惨案与跨大西洋奴隶贸易历史。', '同时调用 J. M. W. Turner 的 The Slave Ship、John Ruskin 等视觉与文本材料。', '把奴隶制历史与现代金融和抽象资本联系起来。'],
      reading: '科幻神话并不是逃离历史，而是提供另一种读取海洋档案的方法：被官方记录抹除的人，可以通过音乐与虚构重新获得历史位置。'
    }],
    images: [],
    sourceLabel: 'The Otolith Group',
    sourceUrl: 'https://otolithgroup.org/index.php?m=project&id=34'
  },
  {
    id: 'wael-shawky',
    name: 'Wael Shawky',
    born: '1971',
    base: 'Alexandria',
    intro: '以木偶、电影、绘画和史料重述宗教与政治历史，尤其通过阿拉伯史料重讲十字军东征，让“谁在操纵历史叙事”直接变成可见的木偶线。',
    methods: ['木偶电影', '历史研究', '陶瓷雕塑', '表演', '绘画'],
    subjects: ['十字军', '宗教', '历史叙事', '阿拉伯世界', '权力', '神话'],
    outputs: ['电影', '木偶', '雕塑', '绘画', '装置'],
    institutions: ['MoMA PS1', 'MoMA', 'Qatar Museums'],
    achievements: ['Cabaret Crusades trilogy 2010–2014', 'MoMA PS1 exhibition 2015'],
    whyImportant: '他不是简单把欧洲历史“换成阿拉伯视角”，而是用木偶这种天然带有操纵关系的媒介，让历史文本、表演者和权力之间的控制结构直接出现在画面里。',
    projects: [{
      year: '2010–2014',
      title: 'Cabaret Crusades',
      type: 'puppet-film trilogy / historical reconstruction',
      facts: ['以 Amin Maalouf 从阿拉伯史料整理的 The Crusades Through Arab Eyes 为重要文本来源。', '第一部使用来自意大利收藏、已有约两百年历史的木制 marionettes。', '第二部为项目专门制作 ceramic figures。', '在三部影片中逐步重述 11–13 世纪 Crusades，并保留木偶操纵线在画面中的可见性。'],
      reading: '“木偶被谁操纵”成为历史书写的隐喻：事件看似被完整重演，但观众始终能看到叙述背后存在控制者。'
    }],
    images: [],
    sourceLabel: 'MoMA PS1',
    sourceUrl: 'https://www.momaps1.org/programs/76-wael-shawky-cabaret-crusades'
  },
  {
    id: 'ho-tzu-nyen',
    name: 'Ho Tzu Nyen',
    chineseName: '何子彦',
    born: '1976',
    base: 'Singapore',
    intro: '以电影、动画、算法、档案与装置研究东南亚如何被历史、地缘政治和知识分类系统不断发明，常让作品保持可变、循环和无法被固定成唯一版本。',
    methods: ['算法影像', '档案研究', '动画', '数据库', '多屏装置', '文本'],
    subjects: ['东南亚', '历史', '地缘政治', '知识分类', '殖民', '时间'],
    outputs: ['互动网站', '录像装置', '电影', '动画', '艺术家书'],
    institutions: ['Singapore Art Museum', 'Venice Biennale', 'Guggenheim'],
    achievements: ['Singapore Pavilion — Venice Biennale 2011', 'The Critical Dictionary of Southeast Asia 2012–ongoing'],
    whyImportant: '他把“地区研究”做成一个不会完成的数据库：东南亚不是固定地图，而是一组不断被算法重新连接的人物、词语、影像和声音。',
    projects: [{
      year: '2012–ongoing',
      title: 'The Critical Dictionary of Southeast Asia',
      type: 'algorithmic online project / archive / interactive audiovisual dictionary',
      facts: ['以英文字母 A–Z 组织与 Southeast Asia 有关的概念、人物和历史线索。', '持续收集网络上的 audiovisual material，并由程序系统吸收与标注。', '通过算法将文本、影像与声音不断重新组合。', '每次运行都可能生成不同关系，而不是提供固定、线性的地区史。'],
      reading: '项目拒绝给“东南亚是什么”一个最终答案；地区被呈现为不断重组的关系网络，这一点和传统百科全书式分类正好相反。'
    }],
    images: [],
    sourceLabel: 'Singapore Art Museum',
    sourceUrl: 'https://www.singaporeartmuseum.sg/art-events/exhibitions/ho-tzu-nyen-time-and-the-tiger'
  }
];
