import type { Artist, ArtworkImage, Project } from './data';
import type { ArtistArchive, ArchiveImage, ArchiveRelation } from './archiveData';

const image = (url: string, title: string, credit: string, sourceUrl: string, sourceLabel: string): ArtworkImage => ({ url, title, credit, sourceUrl, sourceLabel });
const project = (year: string, title: string, type: string, facts: string[], reading: string): Project => ({ year, title, type, facts, reading });
const img = (url: string, title: string, credit: string, sourceUrl: string, sourceLabel: string): ArchiveImage => ({ url, title, credit, sourceUrl, sourceLabel });
const rel = (kind: ArchiveRelation['kind'], label: string, detail?: string): ArchiveRelation => ({ kind, label, detail });

export const artistBatch11: Artist[] = [
  {
    id: 'sim-chi-yin', name: 'Sim Chi Yin', chineseName: '沈绮颖', born: '1978', base: 'New York / Singapore',
    intro: '以摄影、档案介入、电影、玻璃、表演和书籍重写殖民战争、家族沉默、核武与资源开采的历史叙事。',
    methods: ['研究型摄影', '档案介入', '长期研究', '影像', '表演', '摄影装置'], subjects: ['殖民', '战争记忆', '家庭史', '核武', '资源开采', '历史叙事'], outputs: ['摄影', '双频道影像', '玻璃作品', '现场表演', '艺术家书'],
    institutions: ['Venice Biennale', 'Istanbul Biennial', 'Rencontres d’Arles', 'M+', 'Getty'], achievements: ['Venice Biennale 2024 国际主展', 'Jimei x Arles Discovery Award 2020', 'Chris Hondros Award 2018'],
    whyImportant: '她非常适合研究“个人家庭史如何进入殖民史”。关键不是把旧档案陈列出来，而是反复改变档案的载体、观看方向和叙述者，让被压低的历史获得新的形式。',
    projects: [project('2015–', 'One Day We’ll Understand', '家族史 / 马来亚紧急状态 / 反档案', ['调查被家族沉默六十年的祖父历史。', '结合景观摄影、口述史、殖民档案、录像与表演。'], '把“寻找事实”与“事实永远不完整”同时保留，项目因此不断产生新的媒介版本。')],
    images: [image('https://i.imgur.com/wzQPMDM.jpeg', 'One Day We’ll Understand — performance', '© Sim Chi Yin / performance documentation', 'https://chiyinsim.com/odwuperformancepremiere/', 'Artist website / performance documentation')], sourceLabel: 'Sim Chi Yin official archive', sourceUrl: 'https://chiyinsim.com/projects/'
  },
  {
    id: 'noh-suntag', name: 'Noh Suntag', chineseName: '卢舜泽', born: '1972', base: 'South Korea',
    intro: '长期拍摄韩国分裂体制、军事基地、国家暴力、抗争与媒体观看，把“摄影者如何站在事件前”本身也变成问题。',
    methods: ['纪实摄影', '长期研究', '政治摄影', '档案', '摄影书'], subjects: ['韩国分裂', '军事', '国家暴力', '抗议', '记忆', '媒体'], outputs: ['摄影', '摄影书', '展览装置'],
    institutions: ['MMCA Korea', 'Art Sonje Center'], achievements: ['Korea Artist Prize 2014 winner', 'German Photo Book Award — State of Emergency'],
    whyImportant: 'Noh 不把政治摄影理解为“拍到决定性事件”就结束。他持续追踪同一个制度留下的球形雷达、警察相机、葬礼照片和抗议现场，让摄影本身也暴露在权力关系里。',
    projects: [project('2004–07', 'strAnge Ball', '美军雷达 / 村落抗争', ['持续拍摄平泽美军基地附近巨型雷达罩。', '把基础设施、村民与抗争置于同一视觉系统。'], '一个白色球体反复出现后，它不再只是建筑，而变成军事存在如何嵌入日常生活的视觉标记。')],
    images: [image('https://d7hftxdivxxvm.cloudfront.net/?height=1280&quality=80&resize_to=fit&src=https%3A%2F%2Fd32dm0rphc51dk.cloudfront.net%2Fc0NabPTpA7oWiuIKISYOrg%2Flarge.jpg&width=1920', 'strAnge ball #BFH1007', '© Noh Suntag', 'https://www.mmca.go.kr/eng/exhibitions/exhibitionsDetail.do?exhId=201403070000065', 'MMCA / Artsy documentation')], sourceLabel: 'MMCA Korea Artist Prize', sourceUrl: 'https://www.mmca.go.kr/eng/exhibitions/exhibitionsDetail.do?exhId=201403070000065'
  },
  {
    id: 'poulomi-basu', name: 'Poulomi Basu', born: '—', base: 'London / India',
    intro: '在摄影、电影、装置、拼贴、VR/MR 与表演之间工作，持续处理全球南方女性、国家暴力、生态与身体政治。',
    methods: ['研究型摄影', '混合媒介', '沉浸式影像', '装置', '长期项目'], subjects: ['女性', '国家暴力', '生态', '种姓', '冲突', '身体政治'], outputs: ['摄影', '电影', 'VR/MR', '装置', '摄影书'],
    institutions: ['The Photographers’ Gallery', 'V&A', 'Rencontres d’Arles', 'ICP'], achievements: ['ICP Infinity Award 2024', 'Deutsche Börse Prize 2021 shortlist', 'Rencontres d’Arles Discovery Award Jury Prize 2020'],
    whyImportant: '她适合研究摄影项目怎样扩张成一个跨媒介系统：同一政治问题可以在摄影书、空间装置、VR、电影和现场表演里以不同强度出现，而不是把新媒介当装饰。',
    projects: [project('2010–20', 'Centralia', '长期冲突研究 / 摄影书', ['长期进入印度中部冲突地区。', '结合纪实照片、电影感场景、夜间影像与档案材料。'], '作品拒绝把冲突压缩成新闻事件，而是制造一种持续、幽灵般的政治气候。')],
    images: [image('https://photoworks.org.uk/app/uploads/2020/09/%C2%A9-Poulomi-Basu-Centralia-2010%E2%80%9320-_IBP9255B.jpg', 'Centralia', '© Poulomi Basu', 'https://www.poulomibasu.com/about', 'Photoworks / artist documentation')], sourceLabel: 'Poulomi Basu official site', sourceUrl: 'https://www.poulomibasu.com/about'
  },
  {
    id: 'sohrab-hura', name: 'Sohrab Hura', born: '1981', base: 'New Delhi',
    intro: '从极私人的家庭摄影出发，逐渐进入暴力、网络图像、声音、绘画与影像，以摄影书和电影不断改变同一材料的节奏。',
    methods: ['日记式摄影', '长期项目', '摄影书', '电影', '图像编辑'], subjects: ['家庭', '母亲', '暴力', '印度社会', '记忆', '死亡'], outputs: ['摄影书', '摄影', '电影', '声音', '绘画'],
    institutions: ['MoMA', 'Magnum Photos', 'Experimenter'], achievements: ['Paris Photo–Aperture PhotoBook of the Year 2019 — The Coast', 'Oberhausen award 2018'],
    whyImportant: 'Hura 很适合研究“同一批材料为什么要做成书、电影或展览”。他会主动让电影变得激烈、让书变慢，因此媒介选择本身就是编辑判断。',
    projects: [project('2008–18', 'Sweet Life', '家庭 / 母亲 / 私人生活', ['长期拍摄母亲、家庭和家中动物。', '以多个自出版章节逐步建立私人档案。'], '最私人经验并没有被包装成普遍命题，而是通过长期相处和书籍节奏获得复杂度。')],
    images: [image('https://content.magnumphotos.com/wp-content/uploads/2016/05/cortex/lon160886-teaser-story-big.jpg', 'Life is Elsewhere', '© Sohrab Hura / Magnum Photos', 'https://www.magnumphotos.com/arts-culture/art/sohrab-hura-life-is-elsewhere/', 'Magnum Photos')], sourceLabel: 'Magnum Photos', sourceUrl: 'https://www.magnumphotos.com/photographer/sohrab-hura/'
  },
  {
    id: 'pushpamala-n', name: 'Pushpamala N', born: '1956', base: 'Bengaluru',
    intro: '把自己扮成电影女侠、民族志“原住民女性”、历史肖像与流行文化角色，通过摄影表演拆解印度女性被制造出来的图像类型。',
    methods: ['自我表演', '编排式摄影', '角色扮演', '图像挪用', '摄影叙事'], subjects: ['女性形象', '殖民', '民族志', '电影', '印度', '身份表演'], outputs: ['摄影系列', '录像', 'tableau', '摄影书'],
    institutions: ['Nature Morte', 'Chemould Prescott Road'], achievements: ['印度观念摄影与 feminist photo-performance 重要先驱'],
    whyImportant: '她不是“自拍不同造型”，而是把已经存在的电影、民族志、艺术史和殖民图像模板一一穿到自己身上，再暴露这些模板如何制造所谓真实身份。',
    projects: [project('1996–98', 'Phantom Lady or Kismet', '黑色电影 / 女侠角色 / photo-romance', ['由艺术家本人扮演蒙面女侠。', '借用早期印度 stunt film 与黑色电影视觉语法。'], '角色是一个媒介实验：一旦同一身体进入旧电影模板，模板的性别和现代性想象就被重新看见。')],
    images: [image('https://static-assets.artlogic.net/w_2400%2Ch_2400%2Cc_limit%2Cf_auto%2Cfl_lossy%2Cq_auto/artlogicstorage/chempres/images/view/8e2a7c985b0ff58e1a428c066e7bb86dj/chemouldprescottroad-pushpamala-n-phantom-lady-or-kismet-1996-98.jpg', 'Phantom Lady or Kismet', '© Pushpamala N', 'https://www.gallerychemould.com/artworks/2959-pushpamala-n-phantom-lady-or-kismet-1996-98/', 'Chemould Prescott Road')], sourceLabel: 'Pushpamala N official archive', sourceUrl: 'https://www.pushpamala.com/'
  },
  {
    id: 'joana-choumali', name: 'Joana Choumali', born: '1974', base: 'Abidjan',
    intro: '将街头摄影打印到画布后直接刺绣、拼贴和缝线，让照片在缓慢手工劳动中从事件记录变成疗愈、迁移与城市感知的表面。',
    methods: ['刺绣摄影', '街头摄影', '混合媒介', '拼贴', '长期步行'], subjects: ['创伤', '迁移', '城市', '身份', '心理健康', '科特迪瓦'], outputs: ['刺绣摄影', '摄影书', '混合媒介作品'],
    institutions: ['Prix Pictet', 'Venice Biennale', 'Zeitz MOCAA'], achievements: ['Prix Pictet 2019 winner — Ça va aller', 'POPCAP 2014 winner'],
    whyImportant: '她把后期处理变成非常慢的实体劳动。线不是图像上方的装饰，而是重新划分空间、覆盖创伤、连接不同地点；摄影和刺绣发生在不同时间层。',
    projects: [project('2016–19', 'Ça va aller', '恐袭之后 / iPhone / 手工刺绣', ['在 Grand-Bassam 恐袭三周后使用 iPhone低调拍摄。', '把照片打印到棉布，再用棉线、金属线和羊毛手工刺绣。'], '摄影是快速扫描城市，刺绣则是缓慢消化创伤；两种速度共同构成作品。')],
    images: [image('https://static-assets.artlogic.net/w_1800%2Ch_1000%2Cc_limit/exhibit-e/5f3befd5bd3ab441008b4568/0988fd2577d6fac043b813973c6c900e.jpeg', 'Untitled — Ça va aller', '© Joana Choumali', 'https://joanachoumali.com/index.php/projects/photography/ca-va-aller', 'Artist website / gallery documentation')], sourceLabel: 'Joana Choumali official site', sourceUrl: 'https://joanachoumali.com/'
  },
  {
    id: 'mame-diarra-niang', name: 'Mame-Diarra Niang', born: '1982', base: 'Paris',
    intro: '把城市、墙面、模糊身体与抽象空间作为“可塑的领土”，让地点从地理事实转成记忆、遗忘和自我不断变形的心理表面。',
    methods: ['观念摄影', '城市摄影', '抽象摄影', '编辑 / sequence', '长期项目'], subjects: ['领土', '记忆', '遗忘', '自我', '城市', '非洲都市'], outputs: ['摄影', '摄影书', '展览装置'],
    institutions: ['MoMA', 'Sharjah Biennial', 'São Paulo Biennial', 'Fondation HCB'], achievements: ['Fondation HCB solo exhibition 2024', 'Sharjah Biennial 15', 'São Paulo Biennial 33'],
    whyImportant: '她适合研究“地方摄影”如何彻底摆脱地理说明。画面可以仍来自 Dakar、Johannesburg 或其他城市，但编辑后地点被压缩成心理状态和视觉表皮。',
    projects: [project('2013–15', 'The Citadel trilogy', 'Sahel Gris / At the Wall / Metropolis', ['在不同城市寻找墙面、空地、建筑残片和色块。', '把三个系列在摄影书中组织成一套关于领土可塑性的结构。'], '地点不再是“这里是哪里”的答案，而成为自我在城市里如何不断失去、重新定位的过程。')],
    images: [image('https://cdn.sanity.io/images/t4cb1ejj/production/3eff6815058c289f52f3ad1b73d723f2cae42e9a-640x453.jpg?auto=format&dpr=2&fit=max&q=90&w=3840', 'Sahel Gris / The Citadel', '© Mame-Diarra Niang', 'https://www.stevenson.info/artist/mame-diarra-niang', 'Stevenson')], sourceLabel: 'Stevenson', sourceUrl: 'https://www.stevenson.info/artist/mame-diarra-niang'
  },
  {
    id: 'sabelo-mlangeni', name: 'Sabelo Mlangeni', born: '1980', base: 'Johannesburg',
    intro: '以长期黑白摄影进入男性宿舍、乡村酷儿社群、迁移家庭与被遗忘小镇，持续缩短摄影师与被摄者之间的社会距离。',
    methods: ['长期纪实', '黑白摄影', '亲密肖像', '社区关系', '社会景观'], subjects: ['酷儿身份', '迁移', '乡村', '劳动', '男性气质', '南非'], outputs: ['摄影系列', '摄影书', '展览'],
    institutions: ['V&A', 'Liverpool Biennial', 'Art Institute of Chicago'], achievements: ['Tollman Award for Visual Arts 2009', 'Liverpool Biennial 2012'],
    whyImportant: '他的重点不是“边缘社群题材”，而是拍摄关系本身：长时间一起生活、返回同一地方、允许人物以自己的姿态出现，使纪实照片不必靠危机瞬间成立。',
    projects: [project('2003–09', 'Country Girls', '乡村酷儿生活 / 长期关系', ['长期回到 Mpumalanga 拍摄乡村 gay community。', '以日常、家居、聚会和肖像而非单一身份符号建立系列。'], '他没有把酷儿身份拍成例外，而是先把人物放回普通生活、友谊和地方关系。')],
    images: [image('https://archive.stevenson.info/exhibitions/mlangeni/countrygirls/images/countrygirls25.jpg', 'Country Girls', '© Sabelo Mlangeni', 'https://archive.stevenson.info/exhibitions/mlangeni/countrygirls_index.html', 'Stevenson')], sourceLabel: 'Stevenson', sourceUrl: 'https://archive.stevenson.info/exhibitions/mlangeni/countrygirls_index.html'
  }
];

export const archiveBatch11New: Record<string, ArtistArchive> = {
  'sim-chi-yin': { artistId: 'sim-chi-yin', projectCoverage: '5 个研究 / 档案 / 影像 / 表演节点已完成第一轮 · 2011–2024', imageCoverage: '', note: '从地下居住空间、核武景观到家族反档案与现场表演，重点记录研究材料如何不断转换媒介。', projects: [
    { title: 'The Rat Tribe', cluster: 'underground housing / urban inequality', period: '2011–2014', summary: '长期进入北京地下室居住空间，记录被城市正式表面遮蔽的居住系统。', actions: ['长期进入地下居住空间', '环境肖像', '空间摄影', '建立住户关系'], sourceUrl: 'https://chiyinsim.com/news/', images: [], relations: [rel('展览', '15th Istanbul Biennial', '2017')] },
    { title: 'One Day We’ll Understand', cluster: 'family archive / anti-colonial war', period: '2015–', summary: '从祖父在马来亚反殖民战争中的历史出发，以景观、口述史、档案、Requiem 影像和后续介入重写家族与殖民叙事。', actions: ['家族口述史', '殖民档案研究', '景观摄影', '双频道影像', '档案再编排'], sourceUrl: 'https://chiyinsim.com/one-day-well-understand/', images: [], relations: [rel('展览', 'Rencontres d’Arles — Interventions', '2021')] },
    { title: 'Most People Were Silent / Fallout', cluster: 'nuclear landscapes / paired geographies', period: '2017–2018', summary: '在中国—朝鲜边境与美国六州拍摄核武设施、导弹基地和相关物件，以双联图削弱“敌我”地理判断。', actions: ['核设施坐标研究', '跨国旅行', '35mm digital photography', 'diptych 编辑', '影像 / 音频装置'], sourceUrl: 'https://chiyinsim.com/fallout-project/', images: [], relations: [rel('展览', 'Nobel Peace Center commission', '2017'), rel('展览', 'ICA Singapore', '2018')] },
    { title: 'Requiem — Disobedience Archive', cluster: 'Venice / anti-colonial memory / video', period: '2017 / Venice 2024', summary: '让年迈前马来亚左翼参与者以歌声重新召回战争、驱逐和社会主义记忆；2024 被重新剪为单频道进入 Venice 主展 Disobedience Archive。', actions: ['口述 / 歌唱记录', '录像与声音', '版本重剪', '历史记忆作为表演'], sourceUrl: 'https://chiyinsim.com/projects/', images: [img('https://i.imgur.com/wzQPMDM.jpeg', 'One Day We’ll Understand — performance / archive translation', '© Sim Chi Yin', 'https://chiyinsim.com/odwuperformancepremiere/', 'Artist website / performance documentation')], relations: [rel('展览', '60th Venice Biennale — International Exhibition / Disobedience Archive', '2024')] },
    { title: 'One Day We’ll Understand — live performance', cluster: 'theatre / archive / live score', period: '2024–2025', summary: '把多年视觉研究重新写成一小时现场独白，以投影、现场书写、档案影像和打击乐把研究转换成身体化叙事。', actions: ['写作脚本', '现场表演', '多屏投影', '档案影像重组', '现场音乐合作'], sourceUrl: 'https://chiyinsim.com/odwuperformancepremiere/', images: [img('https://i.imgur.com/wzQPMDM.jpeg', 'One Day We’ll Understand — stage view', '© Sim Chi Yin / performance documentation', 'https://chiyinsim.com/odwuperformancepremiere/', 'Artist website')], relations: [rel('展览', 'Esplanade Singapore', '2024'), rel('展览', 'Asia TOPA Melbourne', '2025')] }
  ], awards: ['Jimei x Arles Discovery Award 2020', 'Chris Hondros Award 2018'], exhibitions: ['Istanbul Biennial 2017 / 2022', 'Rencontres d’Arles 2021', 'Venice Biennale 2024'], sources: [{ label: 'Official projects', url: 'https://chiyinsim.com/projects/' }, { label: 'Official bio', url: 'https://chiyinsim.com/bio/' }] },
  'noh-suntag': { artistId: 'noh-suntag', projectCoverage: '6 个分裂体制 / 军事 / 记忆项目已完成第一轮 · 2004–2014', imageCoverage: '', note: '按军事基础设施、国家暴力、Gwangju 记忆和摄影行为本身建立连续项目线。', projects: [
    { title: 'strAnge Ball', cluster: 'US military base / radome / protest', period: '2004–2007', summary: '围绕平泽美军基地雷达罩与大秋里居民抗争，球体在不同距离和冲突场景中成为反复视觉标记。', actions: ['长期回访', '黑白摄影', '军事基础设施与抗议并置'], sourceUrl: 'https://www.mmca.go.kr/eng/exhibitions/exhibitionsDetail.do?exhId=201403070000065', images: [img('https://d7hftxdivxxvm.cloudfront.net/?height=1280&quality=80&resize_to=fit&src=https%3A%2F%2Fd32dm0rphc51dk.cloudfront.net%2Fc0NabPTpA7oWiuIKISYOrg%2Flarge.jpg&width=1920', 'strAnge ball #BFH1007', '© Noh Suntag', 'https://www.mmca.go.kr/eng/exhibitions/exhibitionsDetail.do?exhId=201403070000065', 'MMCA / Artsy documentation')], relations: [] },
    { title: 'State of Emergency', cluster: 'security state / divided Korea', period: '2008', summary: '将警察、军队、边界和日常空间放进同一摄影书，处理“紧急状态”如何长期化。', actions: ['社会政治事件摄影', '摄影书编辑', '跨系列并置'], sourceUrl: 'https://www.mmca.go.kr/', images: [], relations: [rel('奖项', 'German Photo Book Award', 'for State of Emergency')] },
    { title: 'Hear the Song of Gureombi', cluster: 'Jeju naval base / resistance', period: '2011', summary: '追踪济州江汀海军基地反对运动和 Gureombi 岩石被军事建设改变的过程。', actions: ['抗争现场长期拍摄', '景观 / 人物并置', '地方政治研究'], sourceUrl: 'https://www.mmca.go.kr/', images: [], relations: [] },
    { title: 'The Forgetting Machine', cluster: 'Gwangju / damaged memorial portraits', period: '2012', summary: '重新观看 1980 Gwangju 民主化运动死者与失踪者的纪念肖像，折痕、污渍与破损成为记忆被时间侵蚀的表面。', actions: ['纪念肖像再摄影', '档案研究', '保留破损表面'], sourceUrl: 'https://quod.lib.umich.edu/t/tap/7977573.0002.110/--memory-of-the-dead-and-responsibility-of-the-living-noh?rgn=main%3Bview%3Dfulltext', images: [img('https://quod.lib.umich.edu/t/tap/images/7977573.0002.110-00000005-ic.jpg', 'The Forgetting Machine — damaged memorial portrait', '© Noh Suntag', 'https://quod.lib.umich.edu/t/tap/7977573.0002.110/--memory-of-the-dead-and-responsibility-of-the-living-noh?rgn=main%3Bview%3Dfulltext', 'Trans-Asia Photography Review')], relations: [] },
    { title: 'To Survive vs. Once Arrived', cluster: 'DMZ / security tourism', period: '2012', summary: '拍摄接近 DMZ 的安全旅游、边境景观与民众观看，把分裂体制如何被日常化和观光化放在一起。', actions: ['边境田野', '旅游设施摄影', '观看行为记录'], sourceUrl: 'https://artsonje.org/en/exhibition/to-survive-vs-once-arrived/', images: [], relations: [rel('展览', 'Art Sonje Center', '2012')] },
    { title: 'Sneaky Snakes in Scenes of Incompetence', cluster: 'camera / crowd / state institution', period: '2013–2014', summary: '把政府机构、群众与现场大量相机同时纳入图像，摄影行为本身成为国家与公众关系的一部分。', actions: ['事件现场摄影', '把其他摄影者纳入画面', '大型展览编排'], sourceUrl: 'https://www.mmca.go.kr/eng/exhibitions/exhibitionsDetail.do?exhId=201403070000065', images: [], relations: [rel('奖项', 'Korea Artist Prize', 'winner 2014'), rel('展览', 'MMCA Gwacheon', '2014')] }
  ], awards: ['Korea Artist Prize 2014 winner'], exhibitions: ['Art Sonje 2012', 'MMCA Korea Artist Prize 2014'], sources: [{ label: 'MMCA Korea Artist Prize 2014', url: 'https://www.mmca.go.kr/eng/exhibitions/exhibitionsDetail.do?exhId=201403070000065' }] },
  'poulomi-basu': { artistId: 'poulomi-basu', projectCoverage: '5 个摄影 / 影像 / 沉浸式项目已完成第一轮 · 2010–2026', imageCoverage: '', note: '按 Centralia、Blood Speaks、Fireflies、Maya、Always Coming Home 追踪她从摄影书向沉浸式与表演媒介扩张。', projects: [
    { title: 'Centralia', cluster: 'conflict / indigenous resistance / book', period: '2010–2020', summary: '在印度中部冲突地区长期工作，把武装斗争、土地与女性身体组织成介于现实和末世电影之间的视觉世界。', actions: ['长期田野', '摄影', 'found footage', '夜间影像', '摄影书编辑'], sourceUrl: 'https://www.poulomibasu.com/about', images: [img('https://photoworks.org.uk/app/uploads/2020/09/%C2%A9-Poulomi-Basu-Centralia-2010%E2%80%9320-_IBP9255B.jpg', 'Centralia', '© Poulomi Basu', 'https://www.poulomibasu.com/about', 'Photoworks / artist documentation')], relations: [rel('奖项', 'Rencontres d’Arles Discovery Award Jury Prize', '2020'), rel('奖项', 'Deutsche Börse Photography Foundation Prize', 'shortlist 2021')] },
    { title: 'Blood Speaks', cluster: 'women / ritual / immersive advocacy', period: '2013–2019', summary: '围绕尼泊尔女性身体、月经禁忌和结构暴力，逐渐从摄影扩展到 VR 与跨媒体倡议。', actions: ['女性长期访谈', '摄影 / 录像', '沉浸式媒体', '公共倡议'], sourceUrl: 'https://www.poulomibasu.com/about', images: [], relations: [rel('奖项', 'Sundance New Frontiers Lab Fellowship', '2017')] },
    { title: 'Fireflies', cluster: 'film / memory / experimental moving image', period: '2022–2025', summary: '以实验影像处理身体、记忆和冲突，进一步弱化传统纪实摄影的单一证据感。', actions: ['实验电影', '声音', '表演性影像'], sourceUrl: 'https://www.poulomibasu.com/about', images: [], relations: [rel('奖项', 'Aesthetica Film Festival — Best Experimental', '2022')] },
    { title: 'Maya: The Birth of a Superhero', cluster: 'mixed reality / speculative future / gender', period: '2022–2024', summary: '通过 immersive narrative 和虚构超级英雄角色，将性别暴力、抵抗与 speculative future 连接。', actions: ['mixed reality', '角色设计', '互动叙事', '空间化影像'], sourceUrl: 'https://www.poulomibasu.com/about', images: [], relations: [rel('展览', 'V&A', '2023'), rel('展览', 'Cannes immersive competition', '2024')] },
    { title: 'Always Coming Home', cluster: 'migration / photography / sculpture / sound', period: '2025–2026', summary: '以移动影像、摄影、雕塑与声音讨论跨国身份和“回家”作为不断移动的心理状态。', actions: ['摄影', 'moving image', '雕塑', '声音装置'], sourceUrl: 'https://www.poulomibasu.com/about', images: [], relations: [rel('展览', 'Focal Point Gallery', '2025–2026'), rel('展览', 'East Quay Gallery', '2026')] }
  ], awards: ['ICP Infinity Award 2024', 'DBPFP shortlist 2021', 'Arles Discovery Award Jury Prize 2020'], exhibitions: ['V&A Centralia display 2024–2025', 'The Photographers’ Gallery 2021'], sources: [{ label: 'Official bio / project chronology', url: 'https://www.poulomibasu.com/about' }] },
  'sohrab-hura': { artistId: 'sohrab-hura', projectCoverage: '5 个家庭 / 暴力 / 摄影书 / 电影节点已完成第一轮 · 2008–2025', imageCoverage: '', note: '从私人家庭书到暴力图像与电影，重点比较同一材料在书、电影和展览中的不同节奏。', projects: [
    { title: 'Life is Elsewhere', cluster: 'mother / home / intimate archive', period: '2008–2015', summary: '长期拍摄母亲、家中生活与狗 Elsa，把疾病、亲密和日常相处组织成高度私人但不封闭的书。', actions: ['长期居家摄影', '黑白闪光', '家庭关系', '自出版'], sourceUrl: 'https://www.magnumphotos.com/arts-culture/art/sohrab-hura-life-is-elsewhere/', images: [img('https://content.magnumphotos.com/wp-content/uploads/2016/05/cortex/lon160886-teaser-story-big.jpg', 'Life is Elsewhere', '© Sohrab Hura / Magnum Photos', 'https://www.magnumphotos.com/arts-culture/art/sohrab-hura-life-is-elsewhere/', 'Magnum Photos')], relations: [rel('出版', 'Life is Elsewhere', '2015')] },
    { title: 'Sweet Life', cluster: 'photobook trilogy / private-public transition', period: '2015–2018', summary: '把 Life is Elsewhere、A Proposition for Departure 与 Look It’s Getting Sunny Outside!!! 作为连续书籍实验，私人生活逐渐连接更大的社会不安。', actions: ['自出版', '图像 sequence', '跨书籍重复 / 回声'], sourceUrl: 'https://www.magnumphotos.com/', images: [], relations: [] },
    { title: 'The Lost Head & The Bird', cluster: 'violence / found footage / film', period: '2015–', summary: '围绕宗教、性、种姓暴力与网络图像，使用摄影、found footage、声音和电影形成不断扩张的系统。', actions: ['网络 / found image 收集', '电影剪辑', '声音', '照片与绘画并置'], sourceUrl: 'https://www.magnumphotos.com/arts-culture/society-arts-culture/sohrab-hura-the-coast/', images: [], relations: [rel('奖项', 'Oberhausen', 'film award 2018')] },
    { title: 'The Coast', cluster: 'coastline / violence / book-film split', period: '2013–2019', summary: '以海岸旅行和高度紧张的闪光图像切入暴力、欲望与社会裂缝；书籍版本刻意比电影更慢。', actions: ['夜间闪光摄影', '旅行', '书籍编辑', '影像版本对照'], sourceUrl: 'https://www.magnumphotos.com/arts-culture/society-arts-culture/sohrab-hura-the-coast/', images: [img('https://indiaartfair.in/app/uploads/2022/09/Sohrab-Hura.-The-Coast-2013-2019.-Courtesy-of-experimenter.-1-900x1125.jpg', 'The Coast', '© Sohrab Hura / Experimenter', 'https://www.magnumphotos.com/arts-culture/society-arts-culture/sohrab-hura-the-coast/', 'India Art Fair / Magnum context')], relations: [rel('奖项', 'Paris Photo–Aperture PhotoBook of the Year', 'winner 2019')] },
    { title: 'Mother', cluster: 'museum exhibition / family archive re-edit', period: '2024–2025', summary: 'MoMA 个展语境重新展开母亲与家庭材料，使十多年的私人影像进入博物馆时间线。', actions: ['旧材料重编', '展览 sequence', '书与墙面版本比较'], sourceUrl: 'https://www.moma.org/', images: [], relations: [rel('展览', 'MoMA — Mother', '2024–2025'), rel('收藏', 'MoMA', 'works in collection')] }
  ], awards: ['Paris Photo–Aperture PhotoBook of the Year 2019'], exhibitions: ['MoMA — Mother 2024–2025'], sources: [{ label: 'Magnum Photos', url: 'https://www.magnumphotos.com/photographer/sohrab-hura/' }] },
  'pushpamala-n': { artistId: 'pushpamala-n', projectCoverage: '6 个 photo-performance / 角色系统节点已完成第一轮 · 1996–2014', imageCoverage: '', note: '按电影、民族志、艺术史与国家寓言的图像模板整理，而不是只把作品归为自拍。', projects: [
    { title: 'Phantom Lady or Kismet', cluster: 'photo-romance / stunt-film heroine', period: '1996–1998', summary: '艺术家扮演蒙面女侠，以黑白连续剧照借用早期印度 stunt film 和侦探电影。', actions: ['角色设计', '服装 / 道具', '外景编排', '黑白摄影 sequence'], sourceUrl: 'https://www.gallerychemould.com/artworks/2959-pushpamala-n-phantom-lady-or-kismet-1996-98/', images: [img('https://static-assets.artlogic.net/w_2400%2Ch_2400%2Cc_limit%2Cf_auto%2Cfl_lossy%2Cq_auto/artlogicstorage/chempres/images/view/8e2a7c985b0ff58e1a428c066e7bb86dj/chemouldprescottroad-pushpamala-n-phantom-lady-or-kismet-1996-98.jpg', 'Phantom Lady or Kismet', '© Pushpamala N', 'https://www.gallerychemould.com/artworks/2959-pushpamala-n-phantom-lady-or-kismet-1996-98/', 'Chemould Prescott Road')], relations: [] },
    { title: 'Golden Dreams', cluster: 'popular cinema / invented femininity', period: '2001–2002', summary: '以彩色 tableau 和电影式布景制造一套似曾相识却不存在的女性角色叙事。', actions: ['工作室 / 外景搭景', '造型', '连续 tableau'], sourceUrl: 'https://www.pushpamala.com/', images: [], relations: [] },
    { title: 'Native Women of South India: Manners and Customs', cluster: 'ethnography / colonial taxonomy / collaboration', period: '2000–2004', summary: '与 Clare Arni 合作，艺术家扮演不同“南印度女性类型”，模仿并夸张殖民民族志和工作室分类图像。', actions: ['殖民视觉档案研究', '角色扮演', '服装 / 道具', '摄影师 Clare Arni 合作', '类型学式编排'], sourceUrl: 'https://www.gallerychemould.com/artworks/3792-pushpamala-n-yogini-f-24-from-native-women-of-south-2000-2004/', images: [img('https://static-assets.artlogic.net/w_1600%2Ch_1600%2Cc_limit%2Cf_auto%2Cfl_lossy%2Cq_auto/artlogicstorage/chempres/images/view/e39dd9a599dc7a77ddd5102a979f75a5j/chemouldprescottroad-pushpamala-n-yogini-f-24-from-native-women-of-south-india-manners-and-customs-2000-2004.jpg', 'Yogini F-24', '© Pushpamala N / collaboration with Clare Arni', 'https://www.gallerychemould.com/artworks/3792-pushpamala-n-yogini-f-24-from-native-women-of-south-2000-2004/', 'Chemould Prescott Road')], relations: [] },
    { title: 'Indian Lady', cluster: 'national type / studio portrait', period: '2004', summary: '借“印度女士”作为历史摄影和大众文化中反复出现的角色模板，继续测试女性身份的可复制性。', actions: ['历史肖像引用', '自我表演', '工作室造型'], sourceUrl: 'https://www.pushpamala.com/', images: [], relations: [] },
    { title: 'Motherland', cluster: 'nation / allegory / performance', period: '2010', summary: '把“祖国母亲”的政治寓言与女性身体、服装和象征图像重新编排。', actions: ['国家图像研究', '自我表演', 'tableau'], sourceUrl: 'https://www.pushpamala.com/', images: [], relations: [] },
    { title: 'Avega: The Passion', cluster: 'religious image / historical tableau', period: '2012–2014', summary: '继续把艺术史与宗教视觉模板转成摄影表演，身体成为不同文化图像之间的接口。', actions: ['艺术史引用', '服装 / 场景复原', '摄影与录像'], sourceUrl: 'https://www.pushpamala.com/', images: [], relations: [] }
  ], awards: [], exhibitions: [], sources: [{ label: 'Pushpamala N official biography', url: 'https://www.pushpamala.com/' }, { label: 'Chemould Prescott Road', url: 'https://www.gallerychemould.com/artists/43-pushpamala-n/' }] },
  'joana-choumali': { artistId: 'joana-choumali', projectCoverage: '5 个肖像 / 刺绣摄影项目已完成第一轮 · 2013–2020', imageCoverage: '', note: '从 scarification portrait 到 iPhone + embroidery，再到清晨步行的多层纺织拼贴，重点记录摄影表面如何被手工劳动改变。', projects: [
    { title: 'Hââbré, The Last Generation', cluster: 'scarification / portrait / disappearing practice', period: '2013–2014', summary: '拍摄拥有传统 facial scarification 的最后一代人物，以正面肖像记录身体标记和个人选择。', actions: ['参与者肖像', '访谈 / 背景记录', '系列化编辑'], sourceUrl: 'https://joanachoumali.com/', images: [], relations: [rel('出版', 'Hââbré, The Last Generation', 'Fourthwall Books, 2016'), rel('奖项', 'POPCAP / LensCulture Emerging Talent', '2014')] },
    { title: 'Ça va aller', cluster: 'terror aftermath / iPhone / embroidery', period: '2016–2019', summary: '在 Grand-Bassam 袭击后三周使用 iPhone 安静拍摄城市，再把小尺寸照片打印在棉布上逐张刺绣。', actions: ['iPhone 街拍', '棉布打印', '手工刺绣', '情绪 / 城市扫描'], sourceUrl: 'https://joanachoumali.com/index.php/projects/photography/ca-va-aller', images: [img('https://static-assets.artlogic.net/w_1800%2Ch_1000%2Cc_limit/exhibit-e/5f3befd5bd3ab441008b4568/0988fd2577d6fac043b813973c6c900e.jpeg', 'Untitled — Ça va aller', '© Joana Choumali', 'https://joanachoumali.com/index.php/projects/photography/ca-va-aller', 'Artist / gallery documentation')], relations: [rel('奖项', 'Prix Pictet — Hope', 'winner 2019'), rel('出版', 'Ça va aller', 'Nazraeli Press, 2022')] },
    { title: 'Translation', cluster: 'migration / embroidered city pairings', period: '2016–2017', summary: '将不同城市 / 地点通过刺绣和覆盖连接，想象一个不受签证和边境限制的移动世界。', actions: ['街头摄影', '刺绣覆盖', '跨城市配对', '故意保留线头'], sourceUrl: 'https://joanachoumali.com/index.php/projects/photography/translation', images: [], relations: [rel('展览', 'Côte d’Ivoire Pavilion — Venice Biennale', '2017')] },
    { title: 'Alba’hian', cluster: 'dawn walks / layered textile image', period: '2018–2020', summary: '每天清晨 5–7 点步行拍摄城市，再使用拼贴、刺绣、quilting 和透明织物层叠图像。', actions: ['固定时段步行', '街头摄影', '拼贴', '刺绣', '透明纺织层'], sourceUrl: 'https://joanachoumali.com/index.php/projects/mix-media/alba-hian', images: [img('https://images.squarespace-cdn.com/content/v1/5534a426e4b0ed810ce8f891/1569491170467-7C4M08HBO00BLKNPO5WT/Joana%2BChoumali%2C%2BDREAM%2BLEFTOVERS%2B%282019%29.%2BSeries%2BALBAHIAN%2C%2B80x80cm.%2BImage%2Bcopyright%2Bthe%2Bartist%2Band%2Bcourtesy%2BGallery%2B1957%2C%2BAccra.jpg', 'Dream Leftovers — Alba’hian', '© Joana Choumali', 'https://joanachoumali.com/index.php/projects/mix-media/alba-hian', 'Artist / Nataal documentation')], relations: [] },
    { title: 'Venice 2017 — Adorn / Translation', cluster: 'national pavilion / mixed project presentation', period: '2017', summary: '在 Côte d’Ivoire Pavilion 同时呈现 Translation 与 Adorn，使 migration 与身体装饰两条线进入国家馆语境。', actions: ['项目重编', '国家馆空间展示'], sourceUrl: 'https://joanachoumali.com/index.php/about', images: [], relations: [rel('展览', '57th Venice Biennale — Côte d’Ivoire Pavilion', '2017')] }
  ], awards: ['Prix Pictet 2019 winner', 'POPCAP 2014'], exhibitions: ['Venice Biennale Côte d’Ivoire Pavilion 2017', 'Bamako 2017', 'Zeitz MOCAA 2019'], sources: [{ label: 'Official projects', url: 'https://joanachoumali.com/' }] },
  'mame-diarra-niang': { artistId: 'mame-diarra-niang', projectCoverage: '6 个领土 / 模糊 / 自我项目节点已完成第一轮 · 2013–2026', imageCoverage: '', note: '按“plasticity of territory”主线追踪从 Sahel Gris 的地理表面到近年抽象身体与波形。', projects: [
    { title: 'Sahel Gris', cluster: 'territory / Dakar outskirts / grey city', period: '2013', summary: '以 Dakar 周边灰色建筑、道路和空地为材料，把城市从地理说明转成连续表面。', actions: ['城市行走', '摄影', '颜色 / 表面编辑'], sourceUrl: 'https://www.stevenson.info/artist/mame-diarra-niang/exhibitions', images: [img('https://cdn.sanity.io/images/t4cb1ejj/production/3eff6815058c289f52f3ad1b73d723f2cae42e9a-640x453.jpg?auto=format&dpr=2&fit=max&q=90&w=3840', 'Sahel Gris', '© Mame-Diarra Niang', 'https://www.stevenson.info/artist/mame-diarra-niang', 'Stevenson')], relations: [] },
    { title: 'At The Wall / Metropolis', cluster: 'wall / urban surface / trilogy', period: '2014–2015', summary: '继续把墙、广告、建筑边界和城市碎片编辑成关于领土的抽象语法，与 Sahel Gris 组成 The Citadel trilogy。', actions: ['城市表面摄影', '系列重编', '摄影书三册结构'], sourceUrl: 'https://www.stevenson.info/artist/mame-diarra-niang/exhibitions', images: [], relations: [rel('出版', 'The Citadel: a trilogy', 'MACK, 2022')] },
    { title: 'Black Hole', cluster: 'self / abstraction / loss of coordinates', period: '2017', summary: '画面进一步脱离明确地点，以深色、模糊和身体感处理自我如何在空间里消失。', actions: ['近距离摄影', '模糊 / 抽象', '序列编辑'], sourceUrl: 'https://www.stevenson.info/artist/mame-diarra-niang/exhibitions', images: [], relations: [] },
    { title: 'Call Me When You Get There', cluster: 'blur / passage / identity', period: '2020–2021', summary: '以高速模糊、身体和不稳定空间延续“自我作为移动领土”的研究。', actions: ['移动中摄影', '失焦 / 模糊', '大尺幅输出'], sourceUrl: 'https://www.stevenson.info/artist/mame-diarra-niang/exhibitions', images: [], relations: [] },
    { title: 'Sama Guent Guii / Æther', cluster: 'memory / air / mutable self', period: '2022–2025', summary: '让图像更趋向不确定的色域、光与身体碎片，使记忆与遗忘成为画面本身的结构。', actions: ['摄影', '抽象化编辑', '空间安装'], sourceUrl: 'https://www.stevenson.info/artist/mame-diarra-niang/exhibitions', images: [], relations: [rel('展览', 'Fondation HCB — Remember to Forget', '2024')] },
    { title: 'Anatomy of a Wave', cluster: 'wave / diptych / mutable territory', period: '2025–', summary: '近年将空间和身体理解成波形与连续变化的表面，以 diptych 继续推进“领土可塑性”。', actions: ['diptych', 'archival ink print', '抽象身体 / 地景关系'], sourceUrl: 'https://www.stevenson.info/artist/mame-diarra-niang', images: [], relations: [] }
  ], awards: [], exhibitions: ['São Paulo Biennial 2018', 'Sharjah Biennial 2023', 'MoMA 2025'], sources: [{ label: 'Stevenson biography', url: 'https://www.stevenson.info/artist/mame-diarra-niang/biography' }, { label: 'Stevenson exhibitions', url: 'https://www.stevenson.info/artist/mame-diarra-niang/exhibitions' }] },
  'sabelo-mlangeni': { artistId: 'sabelo-mlangeni', projectCoverage: '5 个宿舍 / 酷儿 / 迁移 / 小镇项目已完成第一轮 · 2003–2012', imageCoverage: '', note: '按长期关系与不同社区整理，避免把所有作品都压成“边缘群体纪实”。', projects: [
    { title: 'Invisible Women', cluster: 'domestic labour / invisibility', period: '2000s / shown 2007', summary: '早期关注社会结构中被忽略的女性劳动与日常存在。', actions: ['黑白摄影', '长期观察', '环境肖像'], sourceUrl: 'https://archive.stevenson.info/exhibitions/mlangeni/athome_index.html', images: [], relations: [rel('展览', 'Warren Siebrits, Johannesburg', '2007')] },
    { title: 'Men Only', cluster: 'migrant hostel / masculinity', period: '2008–2009', summary: '进入 Johannesburg 男性宿舍拍摄移民劳动者的居住、友情和男性气质。', actions: ['宿舍长期进入', '黑白摄影', '近距离日常肖像'], sourceUrl: 'https://www.biennial.com/artists/sabelo-mlangeni/', images: [], relations: [rel('展览', 'Liverpool Biennial context', '2012')] },
    { title: 'Country Girls', cluster: 'rural queer community / intimacy', period: '2003–2009', summary: '长期拍摄 Mpumalanga 乡村 gay community，以家居、姿势和聚会描写社群内部生活。', actions: ['多年回访', '参与者关系', '黑白胶片', '日常肖像'], sourceUrl: 'https://archive.stevenson.info/exhibitions/mlangeni/countrygirls_index.html', images: [img('https://archive.stevenson.info/exhibitions/mlangeni/countrygirls/images/countrygirls25.jpg', 'Country Girls', '© Sabelo Mlangeni', 'https://archive.stevenson.info/exhibitions/mlangeni/countrygirls_index.html', 'Stevenson')], relations: [] },
    { title: 'At Home', cluster: 'rural migration / those left behind', period: '2007–2011', summary: '反复回到劳动力外流后的乡村，拍摄留下的老人、儿童、房屋和等待状态。', actions: ['返乡式长期拍摄', '景观与肖像', '黑白摄影'], sourceUrl: 'https://archive.stevenson.info/exhibitions/mlangeni/athome_index.html', images: [], relations: [rel('展览', 'Stevenson Cape Town', '2011')] },
    { title: 'Ghost Towns / My Storie', cluster: 'abandoned towns / migration / self-history', period: '2011–2012', summary: 'Ghost Towns 拍被经济迁移掏空的小镇；My Storie 在 Liverpool Biennial 进一步把 outsider 经验与个人迁移史连接。', actions: ['小镇景观摄影', '迁移历史观察', '展览级编辑'], sourceUrl: 'https://archive.stevenson.info/exhibitions/mlangeni/ghosttowns_index.html', images: [], relations: [rel('展览', 'Liverpool Biennial', 'My Storie, 2012')] }
  ], awards: ['Tollman Award for Visual Arts 2009'], exhibitions: ['Stevenson 2009–2011', 'Liverpool Biennial 2012'], sources: [{ label: 'Stevenson archive', url: 'https://archive.stevenson.info/exhibitions/mlangeni/athome_index.html' }, { label: 'Liverpool Biennial', url: 'https://www.biennial.com/artists/sabelo-mlangeni/' }] }
};
