import type { Artist } from './data';
import { artistBatch82 } from './expansionBatch82';

export const artistBatch81: Artist[] = [
  ...artistBatch82,
  {id:'njideka-akunyili-crosby',name:'Njideka Akunyili Crosby',born:'1983',base:'Nigeria / United States',intro:'以大型纸本绘画、素描、拼贴与照片转印连接尼日利亚家庭记忆、美国日常生活与离散身份，在亲密室内场景中叠合私人照片、流行文化与殖民视觉史。',methods:['照片转印','拼贴','具象绘画','档案图像叠加'],subjects:['非洲离散','家庭','亲密关系','尼日利亚','跨文化身份'],outputs:['绘画','纸本作品','拼贴','摄影转印'],institutions:['MoMA'],achievements:['And We Begin to Let Go','Ideas of Africa: Portraiture and Political Imagination · MoMA 2025–26'],whyImportant:'Akunyili Crosby把绘画与摄影档案真正融合，使离散身份不被简化为两种文化之间的选择，而表现为家庭、媒体、历史图像和日常空间持续叠加的视觉结构。',projects:[{year:'2013',title:'And We Begin to Let Go',type:'纸本绘画 / 照片转印',facts:['MoMA收藏该作。','作品将人物与密集的转印图像置于亲密室内场景。','转印来源包括家庭照片、报刊、产品目录及非洲文化图像。'],reading:'私人室内空间被历史和大众媒介图像覆盖，使亲密经验成为理解离散身份与文化混合的入口。'}],images:[],sourceLabel:'MoMA · Njideka Akunyili Crosby',sourceUrl:'https://www.moma.org/artists/44492-njideka-akunyili-crosby'},
  {id:'toyin-ojih-odutola',name:'Toyin Ojih Odutola',born:'1985',base:'Nigeria / United States',intro:'以炭笔、粉彩、铅笔和复杂线条构建黑人皮肤、虚构人物与想象社会，借肖像和连续叙事研究身份、阶级、迁徙及谁有权进入历史图像。',methods:['虚构叙事','肖像重构','密集线描','世界建构'],subjects:['黑人身份','阶级','迁徙','虚构历史','家庭'],outputs:['素描','粉彩','纸本作品','叙事系列'],institutions:['Whitney Museum of American Art'],achievements:['To Wander Determined · Whitney 2017–18'],whyImportant:'Ojih Odutola把肖像从记录真实人物转化为完整的虚构社会建构，通过黑人贵族家庭等反事实叙事重新分配历史肖像中的财富、权力和主体位置。',projects:[{year:'2017',title:'To Wander Determined',type:'大型纸本叙事系列',facts:['Whitney于2017至2018年举办其纽约首个博物馆个展。','系列虚构两个通过婚姻连接的尼日利亚贵族家庭。','作品使用炭笔、粉彩与铅笔。'],reading:'虚构并不是逃离现实，而成为改写肖像史中种族、阶级和权力分配的一种方法。'}],images:[],sourceLabel:'Whitney · Toyin Ojih Odutola',sourceUrl:'https://whitney.org/exhibitions/toyin-ojih-odutola'},
  {id:'kapwani-kiwanga',name:'Kapwani Kiwanga',born:'',base:'Canada / France',intro:'跨雕塑、装置、研究与材料实践追踪殖民主义、权力、贸易和制度历史，常从档案研究出发，让颜色、植物、建筑材料与商品承担被压抑历史的证据功能。',methods:['研究型实践','材料政治','档案研究','场域特定装置'],subjects:['殖民主义','权力','贸易','价值','制度历史'],outputs:['装置','雕塑','纺织','研究型作品'],institutions:['La Biennale di Venezia','Canada Pavilion'],achievements:['Canada Pavilion · Biennale Arte 2024','Trinket'],whyImportant:'Kiwanga把历史研究压缩进具体材料，使珠子、建筑表面和交换物不只是形式元素，而成为全球贸易、殖民权力和价值体系留下的物质证据。',projects:[{year:'2024',title:'Trinket',type:'场域特定装置',facts:['代表加拿大参加Biennale Arte 2024。','以威尼斯Murano生产并曾作为货币和交换物传播的conterie玻璃珠为核心材料。','装置覆盖加拿大馆内部、外部及庭院。'],reading:'微小玻璃珠被放大为全球贸易网络的历史见证，使美学价值与殖民交换史在同一空间相遇。'}],images:[],sourceLabel:'La Biennale di Venezia · Canada 2024',sourceUrl:'https://www.labiennale.org/en/art/2024/canada'},
  {id:'walead-beshty',name:'Walead Beshty',born:'1976',base:'United Kingdom / United States',intro:'以摄影、无相机曝光、运输过程和制度条件研究图像与艺术品如何在全球物流、展览和生产系统中形成，强调摄影既是图像也是受物理过程影响的物体。',methods:['无相机摄影','过程摄影','物流介入','制度分析'],subjects:['摄影物质性','运输','生产','全球流通','制度'],outputs:['摄影','雕塑','装置'],institutions:['MoMA','MoMA PS1'],achievements:['New Photography 2009 · MoMA','A World of Its Own: Photographic Practices in the Studio · MoMA 2014'],whyImportant:'Beshty把摄影的生成条件、运输和展示过程纳入作品本身，是从传统摄影走向后摄影、物质摄影与制度网络研究的重要连接点。',projects:[{year:'2008',title:'Three Color Curl (CMY: Irvine, California, August 19th 2008, Fuji Crystal Archive Type C)',type:'彩色摄影 / 摄影材料实验',facts:['作品由MoMA收藏。','进入MoMA关于摄影棚实践的展览脉络。'],reading:'摄影不再只是透明窗口，而被理解为由感光材料、制作条件和空间操作共同产生的对象。'}],images:[],sourceLabel:'MoMA · Walead Beshty',sourceUrl:'https://www.moma.org/artists/36980-walead-beshty'},
  {id:'cao-guimaraes',name:'Cao Guimarães',born:'1965',base:'Brazil',intro:'在电影、录像与摄影之间观察巴西日常生活、偶然事件、临时发明和微小行为，以开放式纪录方法让普通物件与边缘经验成为理解社会和感知的入口。',methods:['观察式影像','日常档案','偶然性','开放式纪录'],subjects:['巴西','日常生活','临时性','物件','感知'],outputs:['电影','录像','摄影','装置'],institutions:['MoMA','MoMA PS1'],achievements:['Gambiarras','Short films by Cao Guimarães · MoMA PS1 2011'],whyImportant:'Guimarães连接拉美实验电影、摄影与当代艺术，以对日常微观事件的持续观察替代宏大叙事，为网站补入巴西影像实践和“日常—偶然—临时发明”的方法节点。',projects:[{year:'2005–08',title:'Gambiarras',type:'摄影系列',facts:['MoMA收藏该系列多件作品。','标题指向巴西语境中临时拼装、权宜解决和日常发明。'],reading:'临时制作的物件被从实用背景中抽离出来，显示资源限制如何同时产生形式创造力和社会知识。'}],images:[],sourceLabel:'MoMA · Cao Guimarães',sourceUrl:'https://www.moma.org/artists/35152-cao-guimaraes'}
];
