import type { Artist } from './data';
import { artistBatch86 } from './expansionBatch86';

export const artistBatch85: Artist[] = [
  {id:'martha-rosler',name:'Martha Rosler',born:'1943',base:'United States',intro:'以摄影蒙太奇、录像、行为、写作和装置分析战争、家庭空间、媒体、消费文化与城市生活，把日常图像和政治批判持续连接起来。',methods:['摄影蒙太奇','图像挪用','制度批判','日常生活研究'],subjects:['战争','媒体','家庭劳动','消费文化','城市'],outputs:['摄影','拼贴','录像','行为','装置','写作'],institutions:['MoMA'],achievements:['House Beautiful: Bringing the War Home','Monumental Garage Sale'],whyImportant:'Rosler是女性主义艺术、政治摄影蒙太奇与录像艺术的重要节点，把新闻中的战争图像嵌入美国中产家庭空间，直接揭示私人生活与全球政治之间的关系。',projects:[{year:'1967–72',title:'House Beautiful: Bringing the War Home',type:'摄影蒙太奇系列',facts:['把越南战争新闻图像与美国室内家居杂志图像并置。','MoMA收藏系列中的多件作品。'],reading:'战争不再被放在遥远的新闻现场，而进入理想化家庭内部，使媒体观看与消费生活本身成为批判对象。'},{year:'1973–',title:'Monumental Garage Sale / Garage Sale',type:'参与式装置 / 行为',facts:['首个版本于1973年在加州大学圣迭戈举行。','2012年MoMA举办Meta-Monumental Garage Sale。'],reading:'以真实买卖、议价和日常物品挑战艺术品价值、消费与美术馆制度。'}],images:[],sourceLabel:'MoMA · Martha Rosler',sourceUrl:'https://www.moma.org/artists/6832-martha-rosler'},
  {id:'latoya-ruby-frazier',name:'LaToya Ruby Frazier',born:'1982',base:'United States',intro:'以自画像、家庭协作摄影和社会纪实长期记录宾夕法尼亚州Braddock等后工业社区，将家庭身体、医疗、环境污染、劳动与去工业化放在同一视觉叙事中。',methods:['社会纪实','自画像','家庭协作','长期社区研究'],subjects:['去工业化','家庭','黑人社区','医疗','环境正义','劳动'],outputs:['摄影','录像','文本'],institutions:['Whitney Museum of American Art'],achievements:['The Notion of Family','Whitney Biennial 2012'],whyImportant:'Frazier把纪实摄影的观看权重新交给被拍摄社区内部的人，通过自己、母亲与祖母共同构成的家庭影像，把私人身体与工业衰退、公共医疗和结构性不平等连接起来。',projects:[{year:'2002–',title:'The Notion of Family',type:'长期摄影系列',facts:['围绕艺术家的家庭与家乡Braddock展开。','Whitney收藏相关作品并于2012 Whitney Biennial展出。'],reading:'家庭相册被转化为社会史：身体的疾病、住宅与医院的衰败共同指向后工业城市的结构性损伤。'}],images:[],sourceLabel:'Whitney · LaToya Ruby Frazier',sourceUrl:'https://whitney.org/artists/13636'},
  {id:'an-my-le',name:'An-My Lê',born:'1960',base:'Vietnam / United States',intro:'以大画幅摄影研究战争、军事训练、景观与历史记忆，常把真实军事活动、战争重演和自然景观放在同一冷静而细节密集的画面中。',methods:['大画幅摄影','景观研究','战争重演观察','历史记忆'],subjects:['战争','军事','越南','景观','离散','历史记忆'],outputs:['摄影'],institutions:['MoMA','Whitney Museum of American Art'],achievements:['Viêt Nam','Small Wars','29 Palms'],whyImportant:'Lê拒绝把战争摄影限制为即时战场报道，而通过景观、演习和重演研究战争如何被记忆、训练和视觉化，形成连接纪实摄影、历史摄影与观念景观的重要路径。',projects:[{year:'1994–98',title:'Viêt Nam',type:'摄影系列',facts:['艺术家在离开越南多年后返回拍摄。','使用大画幅摄影强调景观中的细节。'],reading:'个人流亡记忆与当代越南景观叠合，使战争历史通过看似平静的地表重新出现。'},{year:'2003–04',title:'29 Palms',type:'摄影系列',facts:['拍摄美国海军陆战队训练场景。','Whitney收藏该系列作品。'],reading:'军事训练既是真实制度活动又像舞台排演，使战争的生产过程成为可观看对象。'}],images:[],sourceLabel:'MoMA · An-My Lê',sourceUrl:'https://www.moma.org/artists/7901-an-my-le'},
  {id:'stan-douglas',name:'Stan Douglas',born:'1960',base:'Canada',intro:'以电影、录像、摄影和复杂舞台重构研究历史事件、政治动荡、音乐与技术媒介，常通过精密布景和循环叙事制造介于档案与虚构之间的历史场景。',methods:['历史重演','舞台摄影','多屏影像','档案再构'],subjects:['政治动荡','城市','历史','音乐','技术媒介'],outputs:['摄影','电影','录像','多屏装置'],institutions:['La Biennale di Venezia'],achievements:['2011 ≠ 1848','Canada Pavilion · Biennale Arte 2022'],whyImportant:'Douglas把摄影与电影的制作机制用于重新搭建历史，使“历史如何被影像生产”成为作品核心，是当代舞台摄影、影像装置和历史再现的重要节点。',projects:[{year:'2022',title:'2011 ≠ 1848',type:'摄影 / 双通道影像装置',facts:['代表加拿大参加Biennale Arte 2022。','四幅大型摄影重构2011年伦敦、纽约、突尼斯和温哥华的社会动荡，并配合双通道录像。'],reading:'不同城市的抗议被重新制作而非直接纪实，使历史类比、媒体图像与集体行动之间的关系进入同一装置。'}],images:[],sourceLabel:'La Biennale di Venezia · Stan Douglas',sourceUrl:'https://www.labiennale.org/en/art/2022/national-participations/canada'},
  {id:'wael-shawky',name:'Wael Shawky',born:'1971',base:'Egypt',intro:'以电影、木偶、表演、绘画和雕塑重新讲述阿拉伯世界、宗教与殖民历史，通过高度编排的历史重演质疑所谓客观历史叙事。',methods:['历史重演','叙事反转','木偶剧场','研究型电影'],subjects:['阿拉伯历史','殖民主义','宗教','民族身份','历史叙事'],outputs:['电影','雕塑','表演','绘画','装置'],institutions:['La Biennale di Venezia'],achievements:['Cabaret Crusades','Drama 1882','Egypt Pavilion · Biennale Arte 2024'],whyImportant:'Shawky从阿拉伯视角重新组织十字军、殖民统治和民族国家历史，让历史不再被视为固定事实，而成为由叙述位置、表演与媒介持续生产的结构。',projects:[{year:'2010–15',title:'Cabaret Crusades',type:'电影三部曲',facts:['以木偶表演重述中世纪十字军历史。','从阿拉伯历史视角重新组织欧洲中心叙事。'],reading:'木偶的人工性强调历史本身也是被操演和讲述的结构。'},{year:'2024',title:'Drama 1882',type:'音乐电影 / 国家馆项目',facts:['代表埃及参加Biennale Arte 2024。','以1879–1882 Urabi革命及英国轰炸亚历山大为历史背景。'],reading:'以音乐剧式重演重新分配帝国史中的叙事视角。'}],images:[],sourceLabel:'La Biennale di Venezia · Wael Shawky',sourceUrl:'https://www.labiennale.org/en/art/2024/egypt'},
  {id:'teresa-margolles',name:'Teresa Margolles',born:'1963',base:'Mexico',intro:'以布料、水、玻璃、建筑介入及来自暴力现场的物质痕迹研究死亡、毒品战争、边境、迁徙与劳动，让通常被社会和媒体抽象化的死亡获得直接材料存在。',methods:['现场物质取样','痕迹艺术','长期社会研究','空间介入'],subjects:['死亡','暴力','迁徙','边境','劳动','墨西哥'],outputs:['装置','摄影','雕塑','行为','纺织'],institutions:['La Biennale di Venezia'],achievements:['Tela Venezuelana','Biennale Arte 2024'],whyImportant:'Margolles把法医、停尸房和暴力现场中的物质痕迹带入艺术空间，不依赖传统纪实图像，而以材料本身承担见证功能，是拉丁美洲政治艺术与材料性纪实的重要节点。',projects:[{year:'2019',title:'Tela Venezuelana',type:'纺织 / 痕迹作品',facts:['作品源于艺术家关于委内瑞拉—哥伦比亚边境劳动与迁徙的长期研究。','布料在尸检过程中覆盖一名于Cúcuta附近遇害的年轻委内瑞拉男性身体并留下血迹。','作品参加Biennale Arte 2024。'],reading:'布料既像匿名肖像又像无法完全解码的暴力地图，使强迫迁徙不再只是统计数据。'}],images:[],sourceLabel:'La Biennale di Venezia · Teresa Margolles',sourceUrl:'https://www.labiennale.org/en/art/2024/nucleo-contemporaneo/teresa-margolles'},
  ...artistBatch86
];
