import type { Artist } from './data';
import { artistBatch113 } from './expansionBatch113';

export const artistBatch112: Artist[] = [
{id:'deana-lawson',name:'Deana Lawson',born:'1979',base:'United States',intro:'美国摄影艺术家，以高度编排的大画幅肖像研究黑人家庭、亲密关系、身体、灵性与黑人美学，并在美国及非洲离散语境之间建立视觉联系。',methods:['编排摄影','环境肖像','跨地域田野','黑人视觉性'],subjects:['黑人家庭','亲密关系','灵性','身体','离散'],outputs:['摄影'],institutions:['Whitney Museum of American Art','Guggenheim Museum','MoMA'],achievements:['Whitney Biennial 2017','Hugo Boss Prize 2020','The Garden, Gemena, DR Congo'],whyImportant:'Lawson把纪实摄影的现场感与精密摆拍结合，主动建构黑人主体的亲密、尊严和神话性，是当代肖像摄影的重要节点。',projects:[{year:'2015',title:'The Garden, Gemena, DR Congo',type:'编排摄影',facts:['作品拍摄于刚果民主共和国Gemena。','画面中的男女并非现实情侣，而由Lawson安排成类似亚当与夏娃的姿态。'],reading:'Lawson把通常被危机新闻定义的刚果重新想象为伊甸园，以编排摄影反转外部凝视。'}],images:[],sourceLabel:'Whitney · Deana Lawson',sourceUrl:'https://whitney.org/artists/17261'},
{id:'moyra-davey',name:'Moyra Davey',born:'1958',base:'Canada / United States',intro:'加拿大出生、纽约工作的艺术家，以摄影、录像、写作和邮寄图像研究阅读、记忆、日常物件、摄影流通与私人经验。',methods:['邮寄摄影','摄影与写作','日常档案','图像流通'],subjects:['阅读','记忆','日常生活','私人空间','媒介流通'],outputs:['摄影','录像','文本','装置'],institutions:['MoMA'],achievements:['New Photography 2011','The Coffee Shop, The Library'],whyImportant:'Davey把照片折叠、邮寄并保留邮戳和运输痕迹，使摄影从单一图像变成经历时间、交换和物质磨损的对象。',projects:[{year:'2011',title:'The Coffee Shop, The Library',type:'邮寄摄影 / 网格装置',facts:['作品为MoMA New Photography 2011创作。','模拟照片被折成信封寄给朋友，再带着邮票、邮戳与地址痕迹进入展览。'],reading:'图像的运输痕迹被保留下来，使照片同时成为图像、通信物和移动过的物质对象。'}],images:[],sourceLabel:'MoMA · Moyra Davey',sourceUrl:'https://www.moma.org/artists/39770-moyra-davey'},
{id:'sophie-calle',name:'Sophie Calle',born:'1953',base:'France',intro:'法国概念艺术家、摄影家与作家，以跟踪、规则任务、私人调查、摄影与文本叙事把亲密生活、缺席、爱情、观看和自传转化为作品。',methods:['规则任务','摄影与文本','自传虚构','调查式实践'],subjects:['亲密关系','缺席','爱情','观看','私人生活'],outputs:['摄影','文本','装置','录像','书籍'],institutions:['Centre Pompidou'],achievements:['Douleur exquise','Les Aveugles','Gotham Handbook','M’as-tu vue'],whyImportant:'Calle把生活规则、私人调查和叙事结构本身变成艺术方法，持续模糊事实与虚构、作者与角色、私人经验与公共展示的边界。',projects:[{year:'1984–2003',title:'Douleur exquise',type:'摄影 / 文本 / 装置',facts:['作品围绕艺术家1984年经历的一次感情破裂建立档案。','她把自己的痛苦叙述与匿名受访者关于人生最痛苦一天的回答并置。'],reading:'私人创伤通过重复叙述、比较和逐渐消退的文字被转化为具有时间结构的公共档案。'}],images:[],sourceLabel:'Centre Pompidou · Sophie Calle',sourceUrl:'https://www.centrepompidou.fr/en/program/calendar/event/GAv4QEG'},
{id:'stan-douglas',name:'Stan Douglas',born:'1960',base:'Canada',intro:'加拿大艺术家，以电影、录像、摄影与复杂重演研究历史事件、现代主义媒介、城市空间以及历史中未实现的可能性。',methods:['历史重演','电影装置','场景建构','媒介考古'],subjects:['历史记忆','城市','政治','现代主义','替代历史'],outputs:['录像','电影','摄影','装置'],institutions:['La Biennale di Venezia'],achievements:['Canada Pavilion Venice Biennale 2022','2011 ≠ 1848'],whyImportant:'Douglas以高度制作化的摄影和电影重新搭建历史时刻，并通过循环、重演和多视角结构揭示历史叙事的不稳定性。',projects:[{year:'2022',title:'2011 ≠ 1848',type:'摄影 / 双频道录像装置',facts:['Douglas代表加拿大参加第59届威尼斯双年展。','项目把2011年前后不同城市的社会动荡与1848年革命历史之间建立比较。'],reading:'作品并不把两个年份简单等同，而通过历史重演检验群众政治、媒介与城市空间如何在不同时代重新出现。'}],images:[],sourceLabel:'La Biennale di Venezia · Stan Douglas',sourceUrl:'https://www.labiennale.org/en/art/2022/canada'},
...artistBatch113
];