import type { Artist } from './data';

const p=(year:string,title:string,type:string,facts:string[],reading:string)=>({year,title,type,facts,reading});

export const artistBatch42: Artist[] = [
  {id:'carrie-mae-weems',name:'Carrie Mae Weems',born:'1953',base:'United States',intro:'以摄影、文本、录像、表演与装置持续研究黑人历史、性别、权力与观看制度。',methods:['编排摄影','档案研究','文本与图像','表演','社会实践'],subjects:['种族','性别','历史','家庭','权力','再现政治'],outputs:['摄影','录像','装置','表演'],institutions:['MoMA'],achievements:['MoMA collection'],whyImportant:'她把私人叙事、历史档案与制度性观看连接起来，是理解黑人女性主义摄影与当代图像政治的核心艺术家。',projects:[p('1995–96','From Here I Saw What Happened and I Cried','摄影 / 文本',['以历史影像和文字重新处理黑人身体被分类、凝视与再现的历史。'],'观看重点是档案图像如何在新的文字与展示结构中改变权力关系。')],images:[],sourceLabel:'MoMA',sourceUrl:'https://www.moma.org/artists/7177'},
  {id:'sophie-calle',name:'Sophie Calle',born:'1953',base:'France',intro:'把跟踪、调查、私人生活、规则游戏、摄影与文字组织成介于现实事件和观念作品之间的叙事。',methods:['参与式艺术','规则系统','调查','摄影与文本','行为'],subjects:['亲密关系','隐私','缺席','欲望','日常生活'],outputs:['摄影','文本','艺术家书','装置','行为'],institutions:['MoMA'],achievements:['MoMA collection'],whyImportant:'她是摄影—文本—行为之间最重要的桥梁之一，作品常从一个明确规则开始，让真实生活本身成为生产图像与叙事的机制。',projects:[p('1979','The Sleepers (Les dormeurs)','参与式摄影',['邀请29人轮流在自己的床上睡觉并拍摄、记录与提问。'],'项目说明摄影可以不是记录既有事件，而是先设计条件，再让事件发生。')],images:[],sourceLabel:'MoMA',sourceUrl:'https://www.moma.org/artists/6655'},
  {id:'rineke-dijkstra',name:'Rineke Dijkstra',born:'1959',base:'Netherlands',intro:'以正面、克制的大画幅肖像与录像持续观察青春期、迁移、母职等身份转变时刻。',methods:['大画幅肖像','类型序列','长期追踪','录像肖像'],subjects:['青春期','身份','迁移','身体','成长','转变'],outputs:['摄影','录像'],institutions:['MoMA'],achievements:['MoMA collection'],whyImportant:'她把类型学式一致条件与个体身体的细微变化结合起来，是理解当代肖像如何表现身份形成过程的重要节点。',projects:[p('1992–','Beach Portraits','肖像系列',['在海滩以相对统一的正面构图拍摄青少年。'],'背景被压低为简单环境后，姿态、紧张感和身体意识成为主要信息。'),p('1994–2008','Almerisa','长期肖像',['持续多年拍摄同一位从难民中心开始进入新生活的女孩。'],'通过重复拍摄把身份变化变成时间序列。')],images:[],sourceLabel:'MoMA',sourceUrl:'https://www.moma.org/artists/8139'},
  {id:'hito-steyerl',name:'Hito Steyerl',born:'1966',base:'Germany',intro:'通过影像、装置、文本和数字图像研究战争、资本、监控、人工智能与网络时代图像的流通。',methods:['影像论文','数字图像研究','挪用','装置','批判写作'],subjects:['机器视觉','战争','资本','监控','互联网','图像政治'],outputs:['录像','多屏装置','文本','演讲'],institutions:['MoMA'],achievements:['MoMA collection'],whyImportant:'她把“图像是什么”推进到“图像如何流通、被压缩、被机器读取并参与权力运作”，是数字图像批判的重要节点。',projects:[p('2013','How Not to Be Seen: A Fucking Didactic Educational .MOV File','影像装置',['借教学影片形式讨论可见性、分辨率、监控与消失。'],'它适合放在机器视觉与平台图像方法线中，而不只是录像艺术史。')],images:[],sourceLabel:'MoMA',sourceUrl:'https://www.moma.org/artists/43752'},
  {id:'doris-salcedo',name:'Doris Salcedo',born:'1958',base:'Bogotá, Colombia',intro:'以长期访谈与研究为基础，通过家具、建筑介入和材料性雕塑处理政治暴力、失踪、哀悼与历史创伤。',methods:['长期研究','证词访谈','材料转化','场域特定','纪念性介入'],subjects:['政治暴力','失踪','哀悼','殖民','社会不公','记忆'],outputs:['雕塑','装置','公共艺术','建筑介入'],institutions:['Guggenheim','Tate Modern','documenta'],achievements:['Guggenheim retrospective 2015'],whyImportant:'她避免直接再现暴行，而把证词、缺席与日常物件转化为高度克制的物质结构，是研究创伤如何避免视觉消费的重要案例。',projects:[p('2008–10','Plegaria Muda','雕塑装置',['以成对木桌、泥土和植物构成重复结构。'],'重复与材料把个体死亡转化为持续的哀悼空间，而不是事件图解。')],images:[],sourceLabel:'Guggenheim',sourceUrl:'https://www.guggenheim.org/exhibition/doris-salcedo'},
  {id:'gabriel-orozco',name:'Gabriel Orozco',born:'1962',base:'Mexico / Paris',intro:'从日常物件、偶然行动、摄影、雕塑和绘画出发，以轻微干预改变人们对空间、运动和物的注意方式。',methods:['日常介入','现成物','摄影记录','游戏规则','空间观察'],subjects:['日常生活','运动','偶然','物质','空间','时间'],outputs:['雕塑','摄影','绘画','装置','纸上作品'],institutions:['MoMA'],achievements:['MoMA Projects 41','MoMA retrospective 2009–10'],whyImportant:'他把宏大制作降到最低，以移动、触碰、重组和偶然关系建立作品，是1990年代后全球观念艺术与日常介入的重要参照。',projects:[p('1992','Yielding Stone','行动 / 雕塑',['以与艺术家体重相当的塑形材料在城市中滚动，使其吸附街道痕迹。'],'作品的重要性在物体与城市接触的过程，而非固定造型。')],images:[],sourceLabel:'MoMA',sourceUrl:'https://www.moma.org/artists/7461'}
];
