import type { Artist } from './data';
import { artistBatch99 } from './expansionBatch99';

export const artistBatch98: Artist[] = [
{id:'hito-steyerl',name:'Hito Steyerl',born:'1966',base:'Germany',intro:'德国艺术家、电影作者与理论写作者，以录像装置研究数字图像流通、监控、战争、金融与网络化现实。',methods:['影像论文','纪录与虚构混合','媒介批判','数字图像研究'],subjects:['图像政治','监控','战争','金融','网络文化'],outputs:['录像装置','电影','写作'],institutions:['MoMA','Venice Biennale','documenta','São Paulo Biennial'],achievements:['How Not to Be Seen','Liquidity Inc.','In Free Fall'],whyImportant:'Steyerl把“图像如何流通、失真并参与权力”变成当代影像艺术的核心问题，是后互联网图像政治与影像论文的重要代表。',projects:[{year:'2013',title:'How Not to Be Seen: A Fucking Didactic Educational .MOV File',type:'录像',facts:['作品以教学录像的荒诞形式讨论高可见度时代中的隐身与隐私。','MoMA收藏该作。'],reading:'作品把数字可见性本身变成政治问题。'}],images:[],sourceLabel:'MoMA · Hito Steyerl',sourceUrl:'https://www.moma.org/artists/43752-hito-steyerl'},
{id:'dayanita-singh',name:'Dayanita Singh',born:'1961',base:'India',intro:'印度摄影艺术家，以摄影书、可移动展示结构和不断重组的图像档案重新思考摄影、出版与博物馆之间的关系。',methods:['摄影档案重组','摄影书','模块化展示','图像编辑'],subjects:['记忆','档案','印度社会','私人空间','摄影制度'],outputs:['摄影','摄影书','装置'],institutions:['MoMA'],achievements:['Museum of Chance','Museum Bhavan'],whyImportant:'Singh把摄影从单张图像推进为可编辑、可移动、可重新排列的档案与“博物馆”，扩展了摄影书和展览装置的边界。',projects:[{year:'2013',title:'Museum of Chance',type:'摄影装置 / 摄影书',facts:['MoMA收藏Museum of Chance。','项目体现其把照片作为可重新组织的档案单元的长期方法。'],reading:'摄影的意义不只来自单张作品，也来自图像之间不断变化的编辑关系。'}],images:[],sourceLabel:'MoMA · Dayanita Singh',sourceUrl:'https://www.moma.org/artists/48057-dayanita-singh'},
{id:'wolfgang-tillmans',name:'Wolfgang Tillmans',born:'1968',base:'Germany / United Kingdom',intro:'德国摄影艺术家，从朋友、夜生活、酷儿文化和日常观察延伸到无相机抽象摄影、新闻材料与空间化图像编排。',methods:['非等级图像编排','日常摄影','无相机摄影','展墙编辑'],subjects:['亲密关系','酷儿文化','夜生活','政治','真相与知识'],outputs:['摄影','装置','出版物','声音'],institutions:['MoMA','MoMA PS1'],achievements:['Truth Study Center','Freischwimmer','Wolfgang Tillmans: To look without fear'],whyImportant:'Tillmans打破委托摄影、私人快照、抽象暗房实验和政治材料之间的等级，并把展墙本身发展为摄影意义生产的结构。',projects:[{year:'2005–',title:'Truth Study Center',type:'桌面装置 / 摄影与文本',facts:['系列组合新闻文章、照片与其他材料讨论相互竞争的真相。','MoMA资料将其与Tillmans对知识、政治和摄影的研究联系起来。'],reading:'摄影不再只是观看对象，而进入新闻、论证和意识形态的知识系统。'}],images:[],sourceLabel:'MoMA · Wolfgang Tillmans',sourceUrl:'https://www.moma.org/artists/8044-wolfgang-tillmans'},
{id:'carrie-mae-weems',name:'Carrie Mae Weems',born:'1953',base:'United States',intro:'美国艺术家，以摄影、文本、录像、行为和装置研究黑人历史、性别、家庭、观看权力与档案中的种族化表征。',methods:['档案挪用','摄影与文本','自我表演','历史再框定'],subjects:['黑人历史','种族','性别','家庭','观看权力'],outputs:['摄影','录像','装置','行为'],institutions:['MoMA','Whitney Museum'],achievements:['Kitchen Table Series','From Here I Saw What Happened and I Cried'],whyImportant:'Weems把私人家庭场景与殖民/种族档案放在同一实践中，持续追问谁拥有观看、命名和书写历史的权力。',projects:[{year:'1995–1996',title:'From Here I Saw What Happened and I Cried',type:'摄影 / 文本装置',facts:['作品重新使用19世纪黑人肖像及其他档案图像，并覆盖文字与色彩。','MoMA收藏并曾以该系列设置专题展厅。'],reading:'通过重新裁切、着色和文字介入，历史照片中的观看权力被显性化。'}],images:[],sourceLabel:'MoMA · Carrie Mae Weems',sourceUrl:'https://www.moma.org/artists/7177-carrie-mae-weems'},
{id:'martha-rosler',name:'Martha Rosler',born:'1943',base:'United States',intro:'美国观念艺术家，以摄影蒙太奇、录像、文本与参与项目批判战争图像、家庭空间、消费文化和媒体政治。',methods:['摄影蒙太奇','媒介批判','文本图像组合','社会介入'],subjects:['战争','家庭劳动','消费主义','媒体','城市政治'],outputs:['摄影蒙太奇','录像','装置','文本'],institutions:['MoMA','MoMA PS1'],achievements:['House Beautiful: Bringing the War Home','The Bowery in Two Inadequate Descriptive Systems'],whyImportant:'Rosler把大众媒体、家庭杂志和政治新闻重新剪接，使看似分离的私人生活与战争、阶级和国家政治直接碰撞。',projects:[{year:'c.1967–1972',title:'House Beautiful: Bringing the War Home',type:'摄影蒙太奇系列',facts:['系列把越战新闻图像与美国室内家居杂志图像并置。','MoMA收藏系列中的多件作品。'],reading:'舒适家庭内部被战争图像侵入，揭示媒体如何把远方暴力与日常消费经验分隔。'}],images:[],sourceLabel:'MoMA · Martha Rosler',sourceUrl:'https://www.moma.org/artists/6832-martha-rosler'},
{id:'allan-sekula',name:'Allan Sekula',born:'1951–2013',base:'United States',intro:'美国摄影艺术家、作家与批评家，以长期摄影—文本调查研究劳动、港口、航运、全球资本与纪实摄影的政治结构。',methods:['摄影文本调查','批判纪实','长期田野','制度与经济分析'],subjects:['劳动','海洋物流','全球资本','阶级','港口'],outputs:['摄影','文本','录像','装置'],institutions:['MoMA'],achievements:['Fish Story','Untitled Slide Sequence'],whyImportant:'Sekula把纪实摄影从“记录事件”推进到分析资本、劳动和全球物流系统，并深刻影响社会批判摄影与摄影理论。',projects:[{year:'1989–1995',title:'Fish Story',type:'摄影 / 文本项目',facts:['MoMA收藏该系列多件关于港口、船厂、航运和劳动的照片。','项目以海洋物流作为理解全球资本主义的入口。'],reading:'通常不可见的运输网络被转化为关于劳动与资本空间组织的视觉研究。'}],images:[],sourceLabel:'MoMA · Allan Sekula',sourceUrl:'https://www.moma.org/artists/31040-allan-sekula'},
{id:'thomas-ruff',name:'Thomas Ruff',born:'1958',base:'Germany',intro:'德国摄影艺术家，杜塞尔多夫摄影谱系的重要人物，以大尺幅肖像、夜视图像、网络色情图像和科学/数字图像研究摄影的技术条件。',methods:['类型学摄影','图像再处理','数字图像挪用','技术媒介实验'],subjects:['肖像','监控技术','网络图像','建筑','摄影真实性'],outputs:['摄影','数字图像'],institutions:['MoMA','MoMA PS1'],achievements:['Portraits','Nacht','nudes'],whyImportant:'Ruff持续更换图像来源和成像技术，把摄影的“真实性”问题从相机观看扩展到夜视、网络压缩、数字处理和科学成像。',projects:[{year:'1992',title:'Nacht',type:'摄影系列',facts:['MoMA收藏Nacht 2 I。','该系列借用夜视技术的视觉语言。'],reading:'技术设备并非中性的观看工具，而会主动规定什么能够被看见以及图像如何被理解。'}],images:[],sourceLabel:'MoMA · Thomas Ruff',sourceUrl:'https://www.moma.org/artists/6982-thomas-ruff'},
...artistBatch99
];