import type { Artist } from './data';
import { artistBatch173 } from './expansionBatch173';

export const artistBatch172: Artist[] = [
{id:'doris-salcedo',name:'Doris Salcedo',born:'1958',base:'Colombia',intro:'哥伦比亚艺术家，以雕塑、建筑介入和长期证词研究处理政治暴力、失踪者、哀悼与公共记忆。',methods:['证词研究','日常物重构','纪念性装置','建筑介入'],subjects:['政治暴力','失踪','哀悼','记忆','社会不公'],outputs:['雕塑','装置','公共艺术','建筑介入'],institutions:['Guggenheim','Tate Modern','documenta','Istanbul Biennial'],achievements:['Guggenheim retrospective 2015','Shibboleth, Tate Modern 2007','documenta 11, 2002'],whyImportant:'Salcedo避免直接再现暴行，而通过家具、鞋、头发、混凝土等承载缺席者痕迹，把受害者证词转化为克制的物质纪念，是创伤、记忆与政治雕塑的重要节点。',projects:[{year:'1991–1996',title:'Atrabiliarios',type:'墙面雕塑装置',facts:['Guggenheim记录Salcedo把鞋置入墙体凹槽并以动物纤维覆盖开口，关联失踪者身份辨认与集体埋葬。'],reading:'缺席的人通过遗留物被召回，纪念不依赖英雄纪念碑，而发生在脆弱的私人痕迹中。'}],images:[],sourceLabel:'Guggenheim · Doris Salcedo',sourceUrl:'https://www.guggenheim.org/artwork/artist/doris-salcedo'},
{id:'el-anatsui',name:'El Anatsui',born:'1944',base:'Ghana / Nigeria',intro:'加纳出生、长期在尼日利亚工作的艺术家，以废弃酒瓶盖、铝片和铜线组成可变形的大型金属织物，连接材料循环、殖民贸易与非洲历史。',methods:['废弃材料转化','模块化编织','协作式制作','场域适应'],subjects:['殖民历史','贸易','消费','非洲文化','环境'],outputs:['雕塑','大型装置','金属织物'],institutions:['Guggenheim Bilbao','Venice Biennale'],achievements:['Venice Biennale participation 1990','Guggenheim Bilbao collection','Golden Lion for Lifetime Achievement, Venice 2015'],whyImportant:'Anatsui突破雕塑与织物、硬材料与柔性表面之间的边界；瓶盖同时携带消费废弃物、酒类贸易和殖民历史，使材料本身成为全球流通史的证据。',projects:[{year:'2019',title:'Rising Sea',type:'铝与铜线大型装置',facts:['Guggenheim Bilbao记录作品由铝和铜线构成，尺寸约8×14米。','馆方说明其金属雕塑使用废弃酒瓶盖，并关联殖民时期酒类贸易与奴隶贸易历史。'],reading:'远看如奢华织物，近看却暴露消费废料，使美感与资源、贸易和历史暴力同时存在。'}],images:[],sourceLabel:'Guggenheim Bilbao · El Anatsui',sourceUrl:'https://www.guggenheim-bilbao.eus/en/the-collection/artists/el-anatsui'},
{id:'william-kentridge',name:'William Kentridge',born:'1955',base:'South Africa',intro:'南非艺术家，以炭笔绘画、反复擦除动画、版画、剧场和歌剧处理种族隔离、殖民主义、记忆与历史书写。',methods:['炭笔擦除动画','逐帧重绘','剧场化叙事','历史寓言'],subjects:['种族隔离','殖民主义','记忆','权力','南非历史'],outputs:['动画电影','绘画','版画','雕塑','表演','歌剧'],institutions:['MoMA','Centre Pompidou'],achievements:['William Kentridge: Five Themes, MoMA 2010','MoMA collection'],whyImportant:'Kentridge让同一张炭笔画在擦除、重画与摄影记录中不断变化，历史因此以残痕和修订而非稳定事实出现；这种制作机制成为处理南非政治记忆的独特视觉语言。',projects:[{year:'1989–2003',title:'Drawings for Projection',type:'炭笔绘画动画系列',facts:['MoMA将Kentridge描述为以炭笔绘画动画最为知名，并在2010年Five Themes大型展览中系统呈现其创作。'],reading:'擦除留下的痕迹让时间直接沉积在画面中，使动画过程本身成为记忆如何被修改的模型。'}],images:[],sourceLabel:'MoMA · William Kentridge',sourceUrl:'https://www.moma.org/artists/7919-william-kentridge'},
{id:'otobong-nkanga',name:'Otobong Nkanga',born:'1974',base:'Nigeria / Belgium',intro:'尼日利亚出生、现居比利时的艺术家，以绘画、摄影、织毯、雕塑、行为与装置追踪矿物、土地和商品在开采、运输、消费中的社会与生态关系。',methods:['材料溯源','跨媒介研究','生态调查','身体与地景映射'],subjects:['资源开采','土地','殖民主义','生态','劳动','商品'],outputs:['装置','织毯','绘画','摄影','录像','行为','雕塑'],institutions:['Tate','Venice Biennale','Sharjah Biennial'],achievements:['From Where I Stand, Tate St Ives 2019–2020','Special Mention, Venice Biennale 2019','Nasher Prize 2025'],whyImportant:'Nkanga把矿物从地下开采到奢侈商品的链条转化为图像、物件和空间关系，让资源政治成为身体、土地、劳动和全球消费彼此连接的物质网络。',projects:[{year:'2010s',title:'The Weight of Scars',type:'织毯与材料研究',facts:['Tate资料强调Nkanga持续研究土地所有权、自然资源开采及其后果，并跨织毯、绘画、摄影、装置、录像与行为工作。'],reading:'地景的伤痕被视为资源流通留下的身体性记录，从而连接殖民历史与当代消费。'}],images:[],sourceLabel:'Tate · Otobong Nkanga',sourceUrl:'https://www.tate.org.uk/art/artists/otobong-nkanga-24421'},
{id:'yinka-shonibare',name:'Yinka Shonibare',born:'1962',base:'United Kingdom / Nigeria',intro:'英尼艺术家，以荷兰蜡染布、无头人体雕塑、摄影、电影和装置重演欧洲艺术史与帝国图像，研究殖民主义、阶级、迁徙与混合身份。',methods:['历史图像重演','文化符号错置','服装与雕塑','后殖民挪用'],subjects:['殖民主义','帝国','身份','迁徙','阶级','全球贸易'],outputs:['雕塑','装置','摄影','电影','绘画'],institutions:['Tate','Venice Biennale'],achievements:['Turner Prize nominee 2004','Nelson’s Ship in a Bottle, Fourth Plinth 2010','The British Library 2014'],whyImportant:'Shonibare用看似“非洲”的荷兰蜡染布揭示文化身份本身就是殖民贸易和跨国流通的混合产物，并以历史重演拆解欧洲权力图像。',projects:[{year:'2014',title:'The British Library',type:'大型书籍装置',facts:['Tate记录作品由6328本以彩色荷兰蜡染布包裹的精装书组成，部分书脊印有英国第一、二代移民姓名。'],reading:'图书馆从民族文化权威的象征转变为由迁徙者共同书写的国家历史。'}],images:[],sourceLabel:'Tate · Yinka Shonibare',sourceUrl:'https://www.tate.org.uk/art/artists/yinka-shonibare-cbe-2459'},
{id:'isaac-julien',name:'Isaac Julien',born:'1960',base:'United Kingdom',intro:'英国电影与影像艺术家，以电影、多屏装置和摄影研究黑人身份、酷儿历史、离散、迁徙、资本与档案人物。',methods:['多屏影像','诗性电影','档案重构','跨时空蒙太奇'],subjects:['黑人身份','酷儿历史','离散','迁徙','资本','殖民历史'],outputs:['电影','多屏影像装置','摄影'],institutions:['Tate'],achievements:['Isaac Julien: What Freedom Is To Me, Tate Britain 2023','Looking for Langston 1989'],whyImportant:'Julien把电影语言带入美术馆多屏空间，在黑人与酷儿历史研究中结合档案、精密摄影和诗性叙事，是New Queer Cinema与当代影像装置之间的重要桥梁。',projects:[{year:'1989',title:'Looking for Langston',type:'黑白电影',facts:['Tate将其描述为对Harlem Renaissance诗人Langston Hughes及黑人酷儿欲望世界的诗性探索，并指出作品后来成为New Queer Cinema的重要作品。'],reading:'历史档案与虚构场景被并置，让被主流历史压低的黑人酷儿欲望重新获得视觉空间。'}],images:[],sourceLabel:'Tate · Isaac Julien',sourceUrl:'https://www.tate.org.uk/whats-on/tate-britain/isaac-julien'},
...artistBatch173
];