import type { Artist } from './data';
import { artistBatch178 } from './expansionBatch178';

export const artistBatch177: Artist[] = [
{id:'zanele-muholi',name:'Zanele Muholi',born:'1972',base:'South Africa',intro:'南非视觉行动主义者，以摄影、自画像与长期肖像档案对抗黑人酷儿群体在南非视觉史中的缺席，并持续记录身份、性别表达与韧性。',methods:['视觉行动主义','长期肖像档案','自画像','持续性人物追踪'],subjects:['黑人酷儿身份','LGBTQIA+','种族','性别','可见性','南非社会史'],outputs:['摄影','肖像档案','自画像'],institutions:['MoMA','Tate Modern'],achievements:['MoMA collection','Zanele Muholi, Tate Modern 2024–2025'],whyImportant:'Muholi把肖像摄影明确转化为政治性的视觉档案工程，以长期合作和重复拍摄填补南非黑人酷儿历史中的系统性图像空缺，是摄影与行动主义结合的重要节点。',projects:[{year:'2006–ongoing',title:'Faces and Phases',type:'长期肖像档案',facts:['长期拍摄黑人女同性恋、跨性别与酷儿参与者，许多人物在不同年份被反复拍摄。'],reading:'作品不是一次性“记录他者”，而是在时间中建立共同体的视觉历史。'},{year:'2014–ongoing',title:'Somnyama Ngonyama',type:'自画像系列',facts:['Muholi以自身为主体制作大量高度控制的黑白自画像，回应黑人身体的刻板视觉传统与暴力历史。'],reading:'自画像成为重新夺回摄影表述权的政治工具。'}],images:[],sourceLabel:'MoMA · Zanele Muholi',sourceUrl:'https://www.moma.org/collection/artists/42455'},
{id:'dayanita-singh',name:'Dayanita Singh',born:'1961',base:'India',intro:'印度摄影艺术家，将长期摄影档案转化为可移动、可重排的“博物馆”和书籍结构，使编辑、排序、储存与展示本身成为作品。',methods:['摄影档案重组','编辑与排序','移动博物馆','摄影书实践'],subjects:['档案','家庭','印度社会','记忆','图像关系','展示制度'],outputs:['摄影','摄影装置','艺术家书','木质展示结构'],institutions:['MoMA'],achievements:['Surrounds: 11 Installations, MoMA 2019–2020','MoMA collection'],whyImportant:'Singh把摄影从单张图像推进到“摄影建筑”和不断变化的档案系统；她的作品尤其重要地证明摄影意义可以在编辑、储存和重新排列过程中持续生成。',projects:[{year:'2013',title:'Museum of Chance',type:'摄影建筑与可变装置',facts:['作品由162张喷墨照片和柚木结构组成；折叠木结构同时承担展示、档案和储存功能，照片可以不断重新排列。'],reading:'摄影不再只是拍摄行为，而成为编辑、空间组织与偶然关系生产。'}],images:[],sourceLabel:'MoMA · Museum of Chance',sourceUrl:'https://www.moma.org/collection/works/221934'},
{id:'latoya-ruby-frazier',name:'LaToya Ruby Frazier',born:'1982',base:'United States',intro:'美国摄影与影像艺术家，以自身家庭和宾夕法尼亚州布拉多克为长期现场，把自传、家庭协作摄影与社会纪实连接到去工业化、医疗、环境污染和阶级不平等。',methods:['参与式纪实','自传性摄影','家庭协作','长期社区研究'],subjects:['去工业化','家庭','黑人社区','医疗','环境污染','劳动阶级'],outputs:['摄影','录像','社会实践'],institutions:['Whitney Museum'],achievements:['Whitney Biennial 2012','Whitney collection'],whyImportant:'Frazier重新定位了美国社会纪实摄影中的作者关系：镜头不是外部观察贫困社区，而由社区内部成员、自身家庭甚至母亲和祖母共同掌握，把私人身体与工业、医疗和环境结构直接连接。',projects:[{year:'2002–ongoing',title:'The Notion of Family',type:'长期黑白摄影系列',facts:['系列围绕艺术家本人、母亲、祖母及家乡Braddock展开，记录家庭经验与当地钢铁工业衰退后的社会、经济和环境变化。'],reading:'家庭相册同时成为去工业化美国的社会史。'},{year:'2011',title:'Landscape of the Body (Epilepsy Test)',type:'双联摄影',facts:['一幅照片呈现母亲接受医疗检查，另一幅对应正在拆除的Braddock医院。'],reading:'受损身体和受损城市基础设施被并置为同一政治经济过程。'}],images:[],sourceLabel:'Whitney · LaToya Ruby Frazier',sourceUrl:'https://whitney.org/artists/13636'},
{id:'boris-mikhailov',name:'Boris Mikhailov',born:'1938',base:'Ukraine / Germany',intro:'乌克兰摄影艺术家，长期以实验摄影、手工着色、纪实与导演式图像处理苏联统治、后苏联社会、公共意识形态以及边缘群体的身体和生活。',methods:['社会纪实','导演式摄影','手工着色','序列摄影'],subjects:['后苏联社会','意识形态','贫困','边缘群体','身体','乌克兰'],outputs:['摄影','摄影书','手工着色照片'],institutions:['MoMA'],achievements:['New Photography 9, MoMA 1993','Boris Mikhailov: Case History, MoMA 2011','MoMA collection'],whyImportant:'Mikhailov是前苏联地区最关键的摄影家之一，其作品把政治制度崩解后的社会现实与摄影自身的伦理、表演性和作者权力同时推到前景。',projects:[{year:'1997–1998',title:'Case History',type:'大型彩色摄影系列',facts:['系列在Kharkiv拍摄后苏联时期处境极端脆弱的边缘人群，部分参与者接受报酬后为镜头摆拍和表演。'],reading:'作品一方面记录社会崩解，另一方面主动暴露纪实摄影中金钱、观看和摄影者权力的伦理问题。'}],images:[],sourceLabel:'MoMA · Boris Mikhailov: Case History',sourceUrl:'https://www.moma.org/calendar/exhibitions/1125'},
{id:'moyra-davey',name:'Moyra Davey',born:'1958',base:'Canada / United States',intro:'加拿大出生、纽约工作的艺术家，以摄影、电影和写作连接私人生活、文学史、精神分析与艺术史，并通过折叠、邮寄照片让图像在真实物流过程中留下痕迹。',methods:['邮寄摄影','摄影与写作结合','散文电影','蒙太奇','日常观察'],subjects:['私人生活','文学','家庭','记忆','阅读','图像流通'],outputs:['摄影','电影','写作','摄影装置'],institutions:['MoMA'],achievements:['New Photography 2011, MoMA','Moyra Davey film retrospective, MoMA 2022','MoMA collection'],whyImportant:'Davey把摄影、文本和散文电影组织成一种高度个人却又研究性的工作方法；她折叠并真正邮寄照片的实践也让图像的传播、损耗和物质痕迹成为作品结构。',projects:[{year:'2011',title:'The Coffee Shop, The Library',type:'邮寄摄影装置',facts:['照片被折叠成信封、邮寄给朋友，再带着邮票、邮戳、胶带和运输痕迹进入展览；图像来自图书馆、档案、书架与咖啡馆。'],reading:'照片既是图像也是经过现实传播系统的物件，私人阅读经验与公共空间由此连接。'}],images:[],sourceLabel:'MoMA · New Photography 2011: Moyra Davey',sourceUrl:'https://www.moma.org/interactives/exhibitions/2011/newphotography/moyra-davey/'},
...artistBatch178
];