import type { Artist } from './data';

export const artistBatch94: Artist[] = [
{id:'taryn-simon',name:'Taryn Simon',born:'1975',base:'United States',intro:'美国跨媒介艺术家，以摄影、文本、档案、分类系统和大型研究项目调查权力、制度、证据与不可见空间。',methods:['调查式摄影','类型学','档案研究','摄影与文本'],subjects:['制度','不可见空间','司法','权力','分类'],outputs:['摄影','文本','装置','出版'],institutions:['Whitney Museum','Venice Biennale'],achievements:['The Innocents','An American Index of the Hidden and Unfamiliar','A Living Man Declared Dead and Other Chapters I–XVIII'],whyImportant:'Simon把摄影的证明能力与遮蔽能力同时作为研究对象，是当代调查式摄影、文本—图像与制度研究的重要节点。',projects:[{year:'2007',title:'An American Index of the Hidden and Unfamiliar',type:'调查式摄影与文本项目',facts:['系统拍摄美国境内通常不可进入或不可见的科学、政府、医疗、安全与宗教空间。','Whitney Museum于2007年举办同名个展。'],reading:'作品通过分类和准科学展示方式追问谁拥有观看权，以及摄影如何把隐藏事物转化为知识。'}],images:[],sourceLabel:'Whitney · Taryn Simon',sourceUrl:'https://whitney.org/artists/9743'},
{id:'shirin-neshat',name:'Shirin Neshat',born:'1957',base:'Iran / United States',intro:'伊朗裔美国艺术家，以摄影、录像和电影讨论性别、宗教、政治权力、流亡与伊朗社会中的女性经验。',methods:['编排摄影','双屏影像','书法与图像','电影叙事'],subjects:['性别','伊朗','宗教','流亡','政治权力'],outputs:['摄影','录像','电影','装置'],institutions:['MoMA','MoMA PS1','Venice Biennale'],achievements:['Women of Allah','Rapture','Fervor','Passage'],whyImportant:'Neshat以高度形式化的黑白影像连接女性身体、波斯文字、宗教与政治，是全球当代艺术中讨论伊朗、流亡和性别政治的核心人物。',projects:[{year:'1999',title:'Rapture',type:'摄影与录像项目',facts:['以男女分置的空间和仪式化群体行动讨论性别结构与社会权力。','MoMA收藏该系列摄影并保存同名影像作品记录。'],reading:'作品避免把伊朗女性经验化约为单一叙事，而以空间、身体和群体关系制造持续的张力。'}],images:[],sourceLabel:'MoMA · Shirin Neshat',sourceUrl:'https://www.moma.org/artists/8349-shirin-neshat'},
{id:'mona-hatoum',name:'Mona Hatoum',born:'1952',base:'Palestine / Lebanon / United Kingdom',intro:'巴勒斯坦家庭出生于贝鲁特的艺术家，以行为、录像、雕塑和装置把家庭物件、身体与空间转化为关于流亡、暴力、监控和不安全感的场域。',methods:['陌生化','尺度转换','身体艺术','现成物转换'],subjects:['流亡','身体','暴力','监控','家庭空间'],outputs:['装置','雕塑','录像','行为'],institutions:['Tate','Centre Pompidou','Venice Biennale','Turner Prize'],achievements:['Measures of Distance','Light Sentence','Homebound','Tate Modern 2016 survey'],whyImportant:'Hatoum把熟悉的家居与身体经验转化为危险、欲望和政治不安的装置语言，是后殖民、流亡与身体政治艺术的重要人物。',projects:[{year:'1988',title:'Measures of Distance',type:'录像作品',facts:['以艺术家与母亲的影像、书信和声音组织关于距离、家庭与流亡的叙事。','其早期录像与行为实践构成后来装置艺术中身体和政治主题的重要基础。'],reading:'私人母女关系在跨国分离中成为流亡经验的尺度，使政治边界进入亲密身体关系。'}],images:[],sourceLabel:'Tate · Mona Hatoum',sourceUrl:'https://www.tate.org.uk/art/artists/mona-hatoum-2365'},
{id:'kader-attia',name:'Kader Attia',born:'1970',base:'France / Algeria / Germany',intro:'法国—阿尔及利亚艺术家，以装置、雕塑、影像与研究讨论殖民主义、现代主义、文化挪用以及“修复”作为身体和历史创伤的方法。',methods:['后殖民研究','材料隐喻','档案研究','修复理论'],subjects:['殖民主义','现代主义','创伤','修复','文化交换'],outputs:['装置','雕塑','录像','摄影'],institutions:['Guggenheim','Documenta','Lyon Biennale'],achievements:['Untitled (Ghardaïa)','The Repair from Occident to Extra-Occidental Cultures','Oil and Sugar #2'],whyImportant:'Attia以“repair/修复”连接殖民创伤、物质文化和现代主义史，揭示欧洲现代性与被殖民文化之间被遮蔽的交换关系。',projects:[{year:'2009',title:'Untitled (Ghardaïa)',type:'装置',facts:['以粗粒小麦粉塑造阿尔及利亚Ghardaïa城市模型，并并置Le Corbusier等建筑师照片与UNESCO文件。','Guggenheim将作品置于殖民主义与现代主义文化交换的语境中。'],reading:'易腐材料构成的城市模型反转了现代主义原创性的叙述，强调殖民者同样从被殖民文化吸收形式。'}],images:[],sourceLabel:'Guggenheim · Kader Attia',sourceUrl:'https://www.guggenheim.org/map/kader-attia'},
{id:'aida-muluneh',name:'Aida Muluneh',born:'1974',base:'Ethiopia',intro:'埃塞俄比亚摄影师、艺术家与文化组织者，以高度编排的彩色肖像、女性身体与非洲视觉符号讨论身份、历史和社会经验，同时建立Addis Foto Fest摄影网络。',methods:['编排摄影','象征性肖像','色彩构成','摄影生态建设'],subjects:['身份','女性','埃塞俄比亚','非洲影像','历史'],outputs:['摄影','策展','摄影节'],institutions:['Aperture','Addis Foto Fest'],achievements:['Distant Echoes','The Departure','founder of Addis Foto Fest'],whyImportant:'Muluneh不仅以鲜明的编排摄影扩展埃塞俄比亚当代视觉语言，也通过Addis Foto Fest建立跨非洲摄影教育与交流基础设施。',projects:[{year:'2010–',title:'Addis Foto Fest',type:'摄影节与平台',facts:['Muluneh于2010年创办Addis Foto Fest。','平台强调跨文化图像交流并连接非洲摄影师、教育与国际摄影网络。'],reading:'她的重要性同时存在于作品与基础设施层面：既生产图像，也改变非洲摄影被展示和连接的条件。'}],images:[],sourceLabel:'Aperture · Aida Muluneh / Addis Foto Fest',sourceUrl:'https://aperture.org/editorial/learning-addis-ababa/'}
];
