import type { Artist } from './data';
import { artistBatch103 } from './expansionBatch103';

export const artistBatch102: Artist[] = [
{id:'william-kentridge',name:'William Kentridge',born:'1955',base:'South Africa',intro:'南非艺术家，以素描、逐帧动画、版画、戏剧、歌剧与装置处理种族隔离历史、记忆、权力和社会转型。',methods:['擦除式动画','素描动画','版画','跨媒介叙事'],subjects:['种族隔离','历史记忆','权力','南非社会'],outputs:['动画','素描','版画','装置','戏剧'],institutions:['MoMA','MoMA PS1'],achievements:['Drawings for Projection','William Kentridge: Five Themes','Stair Procession'],whyImportant:'Kentridge把反复绘制与擦除留下的痕迹转化为历史记忆的形式语言，并把绘画扩展到动画、舞台和空间。',projects:[{year:'1989–',title:'Drawings for Projection',type:'素描 / 动画',facts:['以炭笔素描的连续修改、拍摄与擦除形成动画。','MoMA长期收藏并展出其动画、版画和纸上作品。'],reading:'画面中的残留痕迹让历史不以稳定事实出现，而以不断被改写又无法完全消失的记忆出现。'}],images:[],sourceLabel:'MoMA · William Kentridge',sourceUrl:'https://www.moma.org/artists/7919-william-kentridge'},
{id:'ibrahim-mahama',name:'Ibrahim Mahama',born:'1987',base:'Ghana',intro:'加纳艺术家，以旧黄麻袋、铁路遗存、档案物和大型建筑介入研究商品流通、殖民基础设施、劳动与材料记忆。',methods:['材料再利用','建筑介入','档案装置','大型协作'],subjects:['殖民主义','劳动','贸易','基础设施','材料记忆'],outputs:['装置','建筑介入','雕塑','档案'],institutions:['La Biennale di Venezia','The Whitworth'],achievements:['Parliament of Ghosts','Ghana Freedom','Red Clay'],whyImportant:'Mahama让被全球贸易消耗过的材料携带劳动与殖民经济的痕迹进入巨型公共空间，并在Tamale建立艺术基础设施。',projects:[{year:'2019',title:'Parliament of Ghosts',type:'装置 / 建筑',facts:['作品最初为Whitworth与Manchester International Festival构想。','2023威尼斯建筑双年展再次呈现，关联Gold Coast Railway遗存与加纳独立后现代主义建筑。'],reading:'废弃物、铁路档案和建筑残片成为殖民经济与独立后国家记忆的物质证词。'}],images:[],sourceLabel:'La Biennale · Ibrahim Mahama',sourceUrl:'https://www.labiennale.org/en/architecture/2023/force-majeure/ibrahim-mahama'},
{id:'shilpa-gupta',name:'Shilpa Gupta',born:'1976',base:'India',intro:'印度艺术家，以摄影、互动装置、录像、声音与文字研究边界、国家权力、审查、身份和日常政治。',methods:['互动装置','文字艺术','参与式实践','摄影'],subjects:['边界','审查','国家','身份','监控'],outputs:['装置','摄影','录像','声音','文本'],institutions:['MoMA'],achievements:['Being: New Photography 2018','For, in your tongue, I cannot fit'],whyImportant:'Gupta把政治边界和言论控制转化为观众可以身体进入的声音、文字和互动系统，使抽象权力变得可感。',projects:[{year:'2017–18',title:'For, in your tongue, I cannot fit',type:'声音 / 装置',facts:['项目围绕被监禁或因诗歌与政治表达遭压制的诗人展开。','Gupta进入MoMA 2018年Being: New Photography展览网络。'],reading:'语言在作品中同时成为被控制的对象与抵抗控制的媒介。'}],images:[],sourceLabel:'MoMA · Shilpa Gupta',sourceUrl:'https://www.moma.org/artists/68305-shilpa-gupta'},
{id:'amar-kanwar',name:'Amar Kanwar',born:'1964',base:'India',intro:'印度艺术家与电影作者，以多频道影像、档案和诗性纪录方法研究政治暴力、民主、失踪、土地冲突与抵抗。',methods:['多频道影像','诗性纪录','档案研究','证言'],subjects:['政治暴力','民主','土地','失踪','抵抗'],outputs:['录像','电影','装置','档案'],institutions:['MoMA'],achievements:['The Torn First Pages','Signals: How Video Transformed the World'],whyImportant:'Kanwar在调查纪录与诗性影像之间建立独特语言，不把政治暴力简化为新闻事件，而持续研究观看、证言与记忆的伦理。',projects:[{year:'2004–08',title:'The Torn First Pages',type:'多频道录像装置',facts:['MoMA收藏该作。','作品进入MoMA 2023年Signals: How Video Transformed the World展览脉络。'],reading:'分散的影像和文本让政治压制的历史以碎片化证言出现，而不是被压缩成单一叙事。'}],images:[],sourceLabel:'MoMA · Amar Kanwar',sourceUrl:'https://www.moma.org/artists/35340'},
{id:'apichatpong-weerasethakul',name:'Apichatpong Weerasethakul',born:'1970',base:'Thailand',intro:'泰国电影导演与艺术家，以电影、录像装置和表演交织日常、梦境、鬼魂、森林、记忆与泰国政治历史。',methods:['慢电影','非线性叙事','影像装置','梦境结构'],subjects:['记忆','鬼魂','自然','身体','泰国社会'],outputs:['电影','录像','装置','表演'],institutions:['MoMA'],achievements:['Tropical Malady','Syndromes and a Century','Uncle Boonmee Who Can Recall His Past Lives'],whyImportant:'Apichatpong把实验电影、当代艺术和东南亚地方经验连接起来，使梦、灵性、身体与政治记忆在非线性时间中共存。',projects:[{year:'2004',title:'Tropical Malady',type:'电影',facts:['MoMA馆藏并持续放映该片。','影片将现实关系与森林中的神话、鬼魂和变形经验并置。'],reading:'叙事断裂使现实与神话不再是两个世界，而成为同一经验的不同层次。'}],images:[],sourceLabel:'MoMA · Apichatpong Weerasethakul',sourceUrl:'https://www.moma.org/artists/42736-apichatpong-weerasethakul'},
{id:'el-anatsui',name:'El Anatsui',born:'1944',base:'Ghana / Nigeria',intro:'加纳出生、长期在尼日利亚工作的艺术家，以回收瓶盖、金属与木材构成可变形的大型悬挂作品，研究贸易、殖民史、消费和材料转换。',methods:['回收材料','模块化编织','大型悬挂装置','材料转换'],subjects:['贸易','殖民历史','消费','非洲历史','物质循环'],outputs:['雕塑','装置'],institutions:['La Biennale di Venezia'],achievements:['Ghana Freedom','Venice Biennale 2019 Ghana Pavilion'],whyImportant:'Anatsui把废弃消费材料转化为介于雕塑、织物和建筑表皮之间的开放形式，并让材料本身携带跨大西洋贸易与消费历史。',projects:[{year:'2019',title:'Ghana Freedom',type:'国家馆 / 大型装置',facts:['参加第58届威尼斯双年展首届加纳国家馆Ghana Freedom。','La Biennale将其与Ibrahim Mahama并列描述为通过日常物件档案形成大型装置。'],reading:'可折叠、可重新悬挂的金属表面拒绝固定形态，也让历史被理解为不断重组的物质网络。'}],images:[],sourceLabel:'La Biennale · Ghana Freedom',sourceUrl:'https://www.labiennale.org/en/art/2019/national-participations/ghana'},
...artistBatch103
];