import type { Artist } from './data';
import { artistBatch140 } from './expansionBatch140';

export const artistBatch139: Artist[] = [
{id:'mona-hatoum',name:'Mona Hatoum',born:'1952',base:'Palestine / Lebanon / UK',intro:'巴勒斯坦裔英国艺术家，以装置、雕塑、影像和表演把家居物件、身体尺度与极简形式转化为关于流亡、权力、暴力和不安的空间经验。',methods:['尺度转换','日常物陌生化','极简装置','身体政治'],subjects:['流亡','权力','暴力','身体','家园','监控'],outputs:['装置','雕塑','影像','表演'],institutions:['Tate'],achievements:['Tate Modern retrospective 2016'],whyImportant:'Hatoum把极简主义的形式语言与巴勒斯坦离散经验、身体脆弱性和政治暴力连接，使熟悉的家庭空间变成具有威胁感的权力场。',projects:[{year:'2016',title:'Mona Hatoum — Tate Modern',type:'回顾展 / 装置',facts:['Tate Modern于2016年举办Hatoum大型回顾展。','Tate资料将暴力、压迫、窥视、身体以及美与恐怖之间的张力列为其长期主题。'],reading:'她的重要性不在于直接说明政治事件，而在于通过材料、尺度和空间让政治压力转化为身体感受。'}],images:[],sourceLabel:'Tate · Mona Hatoum',sourceUrl:'https://www.tate.org.uk/whats-on/tate-modern/mona-hatoum'},
{id:'kader-attia',name:'Kader Attia',born:'1970',base:'France / Algeria / Germany',intro:'法裔阿尔及利亚艺术家，以装置、雕塑、档案与建筑研究殖民主义、现代主义、文化挪用以及“修复”如何暴露历史创伤。',methods:['后殖民研究','材料隐喻','档案研究','建筑研究'],subjects:['殖民主义','现代主义','修复','文化挪用','历史创伤'],outputs:['装置','雕塑','摄影','影像'],institutions:['Guggenheim','documenta'],achievements:['Untitled (Ghardaïa)','documenta 13'],whyImportant:'Attia把“repair/修复”发展为理解殖民创伤与文化交换的重要方法，并持续追问欧洲现代主义从殖民地吸收形式却抹去来源的问题。',projects:[{year:'2009',title:'Untitled (Ghardaïa)',type:'装置 / 建筑模型',facts:['Guggenheim记录该作以库斯库斯搭建阿尔及利亚Ghardaïa城市模型。','作品并置Le Corbusier、Fernand Pouillon照片及UNESCO文件，指向北非建筑对欧洲现代主义的影响。'],reading:'脆弱的食物模型把建筑史从形式史转化为殖民权力与知识归属的问题。'}],images:[],sourceLabel:'Guggenheim · Kader Attia',sourceUrl:'https://www.guggenheim.org/map/kader-attia'},
{id:'yto-barrada',name:'Yto Barrada',born:'1971',base:'Morocco / France',intro:'摩洛哥—法国艺术家，以摄影、电影、出版和装置研究丹吉尔、直布罗陀海峡、迁徙边界、殖民历史以及日常生活中的抵抗策略。',methods:['长期地景观察','档案研究','电影散文','日常政治'],subjects:['迁徙','边界','丹吉尔','殖民史','抵抗','城市'],outputs:['摄影','电影','装置','出版'],institutions:['MoMA'],achievements:['The Strait Project','Artist’s Choice: A Raft'],whyImportant:'Barrada把边境政治从新闻事件转向日常地景、等待和微小行为，使摄影能够记录政治限制如何渗入城市生活。',projects:[{year:'1998–',title:'The Strait Project',type:'摄影系列',facts:['MoMA资料记录Barrada于1998年开始The Strait Project。','系列研究申根制度后直布罗陀海峡边境限制对摩洛哥社会的身体、心理与政治影响。'],reading:'她不直接拍摄越境戏剧，而通过城市表面、休息者和交通符号显示边界制度留下的慢性痕迹。'}],images:[],sourceLabel:'MoMA · Yto Barrada',sourceUrl:'https://www.moma.org/artists/42323-yto-barrada'},
{id:'bouchra-khalili',name:'Bouchra Khalili',born:'1975',base:'Morocco / France',intro:'法裔摩洛哥艺术家，以影像、地图、声音与档案研究迁徙路线、公民身份、流亡者叙事和被官方历史排除的政治主体。',methods:['参与式叙事','地图绘制','口述史','影像研究'],subjects:['迁徙','公民身份','流亡','边界','劳动','政治主体'],outputs:['影像','装置','地图','声音'],institutions:['MoMA'],achievements:['The Mapping Journey Project','Speeches Series'],whyImportant:'Khalili让迁徙者亲自绘制并讲述跨境路线，改变传统纪录片中由作者替他者发言的权力结构。',projects:[{year:'2008–11',title:'The Mapping Journey Project',type:'多通道影像装置',facts:['MoMA收藏并于2016年专门展出The Mapping Journey Project。','作品由多段迁徙者在地图上描画旅程并口述经历的影像组成。'],reading:'地图从国家管理疆界的工具转变为迁徙者重新书写自身空间经验的界面。'}],images:[],sourceLabel:'MoMA · Bouchra Khalili',sourceUrl:'https://www.moma.org/artists/47100-bouchra-khalili'},
{id:'arthur-jafa',name:'Arthur Jafa',born:'1960',base:'USA',intro:'美国艺术家、电影摄影师与影像作者，以高速蒙太奇、图像档案和电影语言研究黑人经验、流行文化、暴力、欲望与视觉记忆。',methods:['影像蒙太奇','图像档案','联想剪辑','黑人视觉研究'],subjects:['黑人经验','种族','暴力','流行文化','记忆','音乐'],outputs:['影像','电影','装置','拼贴'],institutions:['MoMA'],achievements:['APEX','Love Is the Message, The Message Is Death','Artist’s Choice: Less Is Morbid'],whyImportant:'Jafa把网络影像、新闻、电影和黑人流行文化置于强烈节奏关系中，使“图像之间的间隙”成为理解黑人视觉经验的重要方法。',projects:[{year:'2013',title:'APEX',type:'影像蒙太奇',facts:['MoMA收藏APEX并将其描述为由大量历史、艺术与流行文化图像构成的八分钟影像。','作品把黑人视觉文化与异化、英雄、恐怖等主题通过快速联想连接。'],reading:'单张图像的原始语境被保留又被重新连接，意义主要在连续图像之间的碰撞中生成。'}],images:[],sourceLabel:'MoMA · Arthur Jafa',sourceUrl:'https://www.moma.org/artists/69635-arthur-jafa'},
{id:'deana-lawson',name:'Deana Lawson',born:'1979',base:'USA',intro:'美国摄影艺术家，以高度编排的大画幅肖像研究黑人家庭、亲密关系、身体、室内空间和黑人自我呈现。',methods:['编排摄影','环境肖像','大画幅摄影','家庭图像研究'],subjects:['黑人生活','家庭','亲密关系','身体','身份','室内空间'],outputs:['摄影','装置'],institutions:['MoMA','MoMA PS1'],achievements:['New Photography 2011','Deana Lawson at MoMA PS1 2022'],whyImportant:'Lawson把纪实感极强的家庭场景与精密编排结合，使私人空间成为黑人主体性、亲密关系和观看权力的复杂舞台。',projects:[{year:'2009–21',title:'Portrait practice',type:'编排肖像摄影',facts:['MoMA收藏Thai、Roxie and Raquel、Nation与Assemblage等作品。','Lawson参加MoMA New Photography 2011，并于2022年在MoMA PS1举办个展。'],reading:'她的照片看似偶遇，实际上通过姿态、室内细节和观看关系精密组织，模糊家庭快照与艺术史肖像之间的界线。'}],images:[],sourceLabel:'MoMA · Deana Lawson',sourceUrl:'https://www.moma.org/artists/38858-deana-lawson'},
{id:'ibrahim-mahama',name:'Ibrahim Mahama',born:'1987',base:'Ghana',intro:'加纳艺术家，以旧黄麻袋、铁路材料、档案和大型建筑介入研究商品流通、殖民贸易、劳动、现代主义遗产与公共教育。',methods:['材料再利用','建筑介入','劳动协作','殖民档案研究'],subjects:['贸易','劳动','殖民主义','铁路','现代主义','公共教育'],outputs:['装置','建筑介入','雕塑','档案'],institutions:['La Biennale di Venezia','The Whitworth'],achievements:['Parliament of Ghosts','Red Clay'],whyImportant:'Mahama把在全球贸易中反复流通、留下劳动痕迹的材料放大到建筑尺度，并将艺术实践进一步转化为加纳本地的文化与教育基础设施。',projects:[{year:'2019–23',title:'Parliament of Ghosts',type:'建筑装置 / 档案',facts:['La Biennale资料记录作品最初为2019年Whitworth项目，后转化为Tamale的Red Clay建筑结构。','作品从Gold Coast Railway遗迹及加纳独立后现代主义建筑出发，讨论殖民剥削与材料历史。'],reading:'被废弃的铁路和现代主义遗产不再只是历史对象，而成为建立新公共空间与知识生产方式的材料。'}],images:[],sourceLabel:'La Biennale di Venezia · Ibrahim Mahama',sourceUrl:'https://www.labiennale.org/en/architecture/2023/force-majeure/ibrahim-mahama'},
...artistBatch140
];