import type { Artist } from './data';
import { artistBatch111 } from './expansionBatch111';

export const artistBatch110: Artist[] = [
...artistBatch111,
{id:'zanele-muholi',name:'Zanele Muholi',born:'1972',base:'South Africa',intro:'南非视觉活动家与摄影艺术家，以长期肖像、自画像和社群档案对抗黑人LGBTQIA+群体在公共视觉文化中的缺席。',methods:['视觉行动主义','长期肖像档案','自画像','社群合作'],subjects:['黑人酷儿身份','性别','种族','可见性','自我表述'],outputs:['摄影','录像','档案'],institutions:['MoMA','Tate','Guggenheim'],achievements:['Faces and Phases','Somnyama Ngonyama'],whyImportant:'Muholi把肖像摄影明确转化为政治可见性和自我表述的工具，是当代非洲摄影、酷儿视觉文化与社会档案实践的关键人物。',projects:[{year:'2006–ongoing',title:'Faces and Phases',type:'长期肖像档案',facts:['系列长期记录南非黑人女同性恋、跨性别与性别非顺从者。','MoMA收藏多件2011年该系列肖像。'],reading:'项目不是一次性的身份记录，而是通过持续拍摄建立由社群自身构成的反档案。'}],images:[],sourceLabel:'MoMA · Zanele Muholi',sourceUrl:'https://www.moma.org/artists/42455-zanele-muholi'},
{id:'latoya-ruby-frazier',name:'LaToya Ruby Frazier',born:'1982',base:'United States',intro:'美国摄影与影像艺术家，从自身家庭和宾夕法尼亚州Braddock出发，把自传、社会纪实、去工业化、环境健康与阶级问题连接起来。',methods:['社会纪实','自传摄影','家庭共同拍摄','长期社区研究'],subjects:['去工业化','家庭','环境健康','阶级','黑人社区'],outputs:['摄影','录像','文本'],institutions:['Whitney Museum of American Art'],achievements:['The Notion of Family','Whitney Biennial 2012','MacArthur Fellow 2015'],whyImportant:'Frazier把传统社会纪实的观看权重新交给被影响的家庭和社区，使私人身体、工业衰退与结构性不平等进入同一视觉叙事。',projects:[{year:'2002–',title:'The Notion of Family',type:'长期黑白摄影系列',facts:['系列围绕艺术家本人、母亲、祖母及Braddock展开。','Whitney指出系列将家庭经验与当地社会、经济和环境衰退联系起来。'],reading:'家庭相册在这里成为社会史：身体损耗与工业城市的衰败被并置为同一结构性过程。'}],images:[],sourceLabel:'Whitney · LaToya Ruby Frazier',sourceUrl:'https://whitney.org/artists/13636'},
{id:'shirin-neshat',name:'Shirin Neshat',born:'1957',base:'Iran / United States',intro:'伊朗裔美国艺术家，以摄影、双频道影像与电影讨论伊朗革命之后的性别、宗教、流散、权力与个人身份。',methods:['编排摄影','双频道影像','象征性叙事','电影'],subjects:['性别','伊朗社会','宗教','流散','权力'],outputs:['摄影','录像装置','电影'],institutions:['MoMA','La Biennale di Venezia'],achievements:['Women of Allah','Rapture','Fervor','Passage'],whyImportant:'Neshat以高度形式化的黑白影像把性别政治、宗教符号与流散经验转化为空间化观看，是1990年代以来跨国影像艺术的重要节点。',projects:[{year:'1999',title:'Rapture',type:'双频道影像 / 摄影',facts:['MoMA收藏Rapture相关作品。','作品以男女群体在不同空间中的并置组织性别、社会规范与行动之间的张力。'],reading:'双屏不是简单叙事手段，而把社会性别的分隔直接变成观众身体必须面对的空间结构。'}],images:[],sourceLabel:'MoMA · Shirin Neshat',sourceUrl:'https://www.moma.org/artists/8349-shirin-neshat'},
{id:'wael-shawky',name:'Wael Shawky',born:'1971',base:'Egypt',intro:'埃及艺术家，以电影、木偶、表演、绘画和研究型历史重演重新组织阿拉伯世界、宗教与殖民历史的叙述视角。',methods:['历史重演','研究型电影','木偶剧','档案再叙事'],subjects:['历史书写','殖民主义','宗教','民族身份','阿拉伯世界'],outputs:['电影','雕塑','表演','绘画'],institutions:['La Biennale di Venezia'],achievements:['Cabaret Crusades','Al Araba Al Madfuna','Drama 1882','Egypt Pavilion Venice Biennale 2024'],whyImportant:'Shawky把历史理解为被不断表演和重写的叙事，而非稳定事实；其作品是理解当代艺术如何从非西方视角重新处理历史材料的重要案例。',projects:[{year:'2024',title:'Drama 1882',type:'音乐电影 / 历史重演',facts:['作品代表埃及参加第60届威尼斯双年展。','La Biennale说明项目以1879–1882年Urabi革命及英国殖民介入为历史起点。'],reading:'通过音乐剧式再演，历史的权威叙述被暴露为可以重新编排、重新选择视角的表演结构。'}],images:[],sourceLabel:'La Biennale · Egypt 2024',sourceUrl:'https://www.labiennale.org/en/art/2024/egypt'},
{id:'allan-sekula',name:'Allan Sekula',born:'1951–2013',base:'United States',intro:'美国摄影家、影像作者与理论写作者，以摄影、文字和长期调查研究劳动、港口、航运、全球资本主义及纪实摄影的政治结构。',methods:['摄影与文本','长期调查','批判纪实','社会地理研究'],subjects:['劳动','航运','港口','全球资本','阶级'],outputs:['摄影','文本','录像','书籍'],institutions:['MoMA'],achievements:['Fish Story','Untitled Slide Sequence'],whyImportant:'Sekula把摄影从单幅纪实图像扩展为由图像、文字、地理和政治经济研究共同组成的批判系统，对当代研究型摄影与全球化视觉研究影响深远。',projects:[{year:'1989–95',title:'Fish Story',type:'摄影 / 文本研究项目',facts:['MoMA收藏Fish Story系列多件港口、船厂和航运相关作品。','项目跨越多个港口研究海洋运输、劳动与全球经济。'],reading:'全球化通常表现为抽象数据，Sekula则沿着船舶、港口与工人的物质路线重新让资本流动变得可见。'}],images:[],sourceLabel:'MoMA · Allan Sekula',sourceUrl:'https://www.moma.org/artists/31040-allan-sekula'}
];