import type { Artist } from './data';
import { artistBatch89 } from './expansionBatch89';

export const artistBatch88: Artist[] = [
  {id:'zanele-muholi',name:'Zanele Muholi',born:'1972',base:'South Africa',intro:'自称“视觉行动者”，以摄影持续建立南非黑人 LGBTQIA+ 社群的视觉档案，并通过自画像把种族、性别、劳动和日常物件转化为政治性的观看问题。',methods:['视觉行动主义','长期肖像档案','自画像','社群协作'],subjects:['黑人酷儿身份','可见性','种族','性别','南非社会'],outputs:['摄影','影像'],institutions:['MoMA'],achievements:['Faces and Phases','Somnyama Ngonyama'],whyImportant:'Muholi把肖像摄影、社群档案与行动主义结合，使长期拍摄本身成为对黑人酷儿历史缺席和视觉不可见性的制度性回应。',projects:[{year:'2006–',title:'Faces and Phases',type:'长期肖像档案',facts:['持续拍摄黑人女同性恋者、跨性别者及酷儿社群成员。','作品强调参与者的姓名、存在和社群历史。'],reading:'系列以重复而持续的肖像生产抵抗历史档案中的系统性缺席。'},{year:'2012–',title:'Somnyama Ngonyama',type:'自画像系列',facts:['艺术家本人作为画面主体。','利用日常物件、服饰与高反差黑白影像组织角色。'],reading:'自画像成为重新控制黑人身体如何被观看、分类和再现的工具。'}],images:[],sourceLabel:'MoMA · Zanele Muholi',sourceUrl:'https://www.moma.org/collection/artists/42455'},
  {id:'sophie-calle',name:'Sophie Calle',born:'1953',base:'France',intro:'以摄影、文字、调查、跟踪、规则游戏和自传性叙事把私人生活转化为观念艺术实验，持续模糊事实、虚构、亲密关系与观看伦理之间的边界。',methods:['摄影与文字','调查式实践','规则游戏','自传与虚构混合'],subjects:['亲密关系','缺席','观看','私人生活','作者身份'],outputs:['摄影','文本','装置','书籍','录像'],institutions:['Centre Pompidou'],achievements:['Les Aveugles','Gotham Handbook','Douleur exquise'],whyImportant:'Calle把生活事件、调查程序和文本—照片组合发展为完整的方法体系，使“谁在看谁”“私人经验如何成为作品”成为当代摄影与观念艺术的重要问题。',projects:[{year:'1986',title:'Les Aveugles',type:'摄影 / 文字装置',facts:['访问先天失明者关于“美”的理解。','将回答与人物肖像及对应图像并置。'],reading:'作品让视觉图像与无法通过视觉经验获得的“美”发生结构性冲突。'},{year:'1984–2003',title:'Douleur exquise',type:'档案 / 摄影 / 文字装置',facts:['围绕艺术家1984年的失恋经历建立档案。','将自己的痛苦叙述与陌生人的痛苦经验并置。'],reading:'私人创伤通过重复叙述、比较和物质化档案被转化为一种时间性的艺术结构。'}],images:[],sourceLabel:'Centre Pompidou · Sophie Calle',sourceUrl:'https://www.centrepompidou.fr/en/program/calendar/event/GAv4QEG'},
  {id:'deana-lawson',name:'Deana Lawson',born:'1979',base:'United States',intro:'以精密编排的大尺幅肖像摄影研究黑人家庭、亲密关系、身体、仪式与自我呈现，常在真实家庭空间中与被摄者共同构造具有纪念碑感的场景。',methods:['编排肖像','场景构造','家庭空间拍摄','视觉档案拼接'],subjects:['黑人生活','家庭','亲密关系','身体','灵性'],outputs:['摄影','摄影装置'],institutions:['MoMA','MoMA PS1'],achievements:['New Photography 2011','Deana Lawson, MoMA PS1 2022','Nation'],whyImportant:'Lawson把家庭快照、正式肖像、宗教图像和艺术史式构图压缩到高度控制的摄影场景中，为黑人日常生活建立既亲密又具有纪念碑尺度的视觉空间。',projects:[{year:'2010',title:'Roxie and Raquel, New Orleans, Louisiana',type:'编排肖像摄影',facts:['作品进入MoMA收藏。','人物、室内空间和身体姿态共同形成高度控制的肖像结构。'],reading:'私人室内并非背景，而成为身份、亲密关系和自我呈现共同发生的舞台。'},{year:'2018',title:'Nation',type:'摄影作品',facts:['作品进入MoMA收藏。','属于艺术家持续研究黑人身体与视觉文化的实践。'],reading:'作品将肖像与更广泛的历史、家庭和集体身份问题连接起来。'}],images:[],sourceLabel:'MoMA · Deana Lawson',sourceUrl:'https://www.moma.org/artists/38858-deana-lawson'},
  {id:'zoe-leonard',name:'Zoe Leonard',born:'1961',base:'United States',intro:'以摄影、雕塑和装置研究城市空间、自然、性别、酷儿历史、迁徙、商品流通以及摄影机器本身的观看条件。',methods:['摄影系列','档案建构','长期城市观察','摄影装置'],subjects:['城市','性别与性','迁徙','商品流通','摄影史'],outputs:['摄影','雕塑','装置'],institutions:['Whitney Museum'],achievements:['The Fae Richards Photo Archive','Analogue','945 Madison Avenue','Zoe Leonard: Survey'],whyImportant:'Leonard把摄影同时作为社会观察、虚构档案和光学装置使用，连接酷儿历史、城市经济与摄影媒介自身的制度条件。',projects:[{year:'1996',title:'The Fae Richards Photo Archive',type:'虚构摄影档案',facts:['与电影导演Cheryl Dunye合作。','以82幅照片构造一位虚构非裔美国女同性恋演员的生命档案。'],reading:'通过制造一个“本应存在却没有留下档案”的人物，作品直接回应黑人酷儿历史的视觉缺席。'},{year:'2014',title:'945 Madison Avenue',type:'camera obscura装置',facts:['为2014 Whitney Biennial制作。','把Whitney展厅转化为大型暗箱。'],reading:'观众直接进入摄影机器内部，使视觉成为光学、时间与社会经验。'}],images:[],sourceLabel:'Whitney Museum · Zoe Leonard',sourceUrl:'https://whitney.org/artists/3594'},
  {id:'akram-zaatari',name:'Akram Zaatari',born:'1966',base:'Lebanon',intro:'以摄影档案、录像、访谈、考古式研究和再语境化方法处理黎巴嫩战争、摄影工作室历史、私人图像与记忆政治，也是Arab Image Foundation的重要共同创办者之一。',methods:['摄影档案研究','影像考古','访谈','档案再语境化'],subjects:['黎巴嫩历史','战争','记忆','摄影史','私人影像'],outputs:['摄影','录像','装置','档案项目'],institutions:['MoMA','La Biennale di Venezia'],achievements:['This Day','In This House','Letter to a Refusing Pilot','Projects 100: Akram Zaatari'],whyImportant:'Zaatari把中东摄影档案从历史材料转化为当代艺术方法，关注照片如何被拍摄、保存、隐藏、重新发现和赋予政治意义。',projects:[{year:'2003',title:'This Day (Al Yaoum)',type:'录像 / 档案研究',facts:['作品进入MoMA收藏。','以档案、历史图像和影像研究连接个人记忆与地区历史。'],reading:'历史不是固定背景，而由不断被重新组织和观看的图像材料构成。'},{year:'2013',title:'Letter to a Refusing Pilot',type:'影像装置',facts:['作品进入MoMA收藏。','2013年代表黎巴嫩参加威尼斯双年展。'],reading:'个人记忆、战争传闻与拒绝执行轰炸命令的故事被组织成关于伦理选择和历史证词的影像结构。'}],images:[],sourceLabel:'MoMA · Akram Zaatari',sourceUrl:'https://www.moma.org/artists/41278-akram-zaatari'},
  ...artistBatch89
];
