import type { Artist } from './data';

export const artistBatch109: Artist[] = [
{id:'hito-steyerl',name:'Hito Steyerl',born:'1966',base:'Germany',intro:'德国艺术家、电影作者与理论写作者，以影像装置、论文电影和数字图像研究讨论全球化、战争、监控、人工智能、图像流通与网络资本主义。',methods:['论文电影','研究型影像','数字图像批判','纪实与虚构混合'],subjects:['数字图像','战争','监控','人工智能','全球化','图像政治'],outputs:['录像','多频道影像装置','文本'],institutions:['MoMA','La Biennale di Venezia','documenta','Berlin Biennale','São Paulo Biennial'],achievements:['November','In Free Fall','How Not to Be Seen','German Pavilion Venice Biennale 2015'],whyImportant:'Steyerl把影像生产、传播和权力结构本身变成艺术材料，是理解后互联网时代图像政治、低清图像、监控与算法视觉的关键艺术家。',projects:[{year:'2004',title:'November',type:'论文电影 / 录像',facts:['作品结合研究、档案影像、采访与第一人称叙述。','MoMA馆藏记录指出作品围绕艺术家朋友Andrea Wolf及革命图像的流通过程展开。'],reading:'作品把私人记忆、政治事件和媒介传播放在同一条图像链中，追问现实如何在复制与传播中被重新编码。'}],images:[],sourceLabel:'MoMA · Hito Steyerl',sourceUrl:'https://www.moma.org/artists/43752-hito-steyerl'},
{id:'trevor-paglen',name:'Trevor Paglen',born:'1974',base:'United States',intro:'美国艺术家与地理学者，通过摄影、卫星观测、机器视觉研究和调查方法揭示军事黑箱、秘密基础设施、监控系统以及人工智能图像分类。',methods:['调查研究','远距离摄影','机器视觉研究','基础设施制图'],subjects:['监控','军事基础设施','人工智能','卫星','不可见系统'],outputs:['摄影','录像','装置','研究项目'],institutions:['MoMA','Smithsonian American Art Museum'],achievements:['The Clarke Belt','Behold These Glorious Times!','MacArthur Fellow 2017'],whyImportant:'Paglen把通常不可见的军事、情报和机器视觉基础设施转化为可观看对象，连接了当代摄影、调查艺术与AI视觉政治。',projects:[{year:'2017',title:'Behold These Glorious Times!',type:'录像 / 机器视觉研究',facts:['作品进入MoMA收藏。','MoMA将Paglen纳入New Order: Art and Technology in the Twenty-First Century。'],reading:'项目关注机器如何学习观看，使摄影从人类观看工具转向算法视觉制度的研究对象。'}],images:[],sourceLabel:'MoMA · Trevor Paglen',sourceUrl:'https://www.moma.org/artists/69988-trevor-paglen'},
{id:'wolfgang-tillmans',name:'Wolfgang Tillmans',born:'1968',base:'Germany / United Kingdom',intro:'德国摄影艺术家，以肖像、青年文化、静物、抽象暗房实验和反等级摄影装置重新组织摄影在墙面、出版物和社会生活中的关系。',methods:['非等级式图像编排','日常摄影','暗房抽象','展墙编辑'],subjects:['亲密关系','青年文化','身体','日常生活','摄影物质性'],outputs:['摄影','摄影装置','出版物','声音'],institutions:['MoMA','Tate'],achievements:['Turner Prize 2000','Freischwimmer','Truth Study Center'],whyImportant:'Tillmans把不同尺寸、题材与制作方式的照片放进同一视觉民主结构，深刻改变了1990年代以来摄影展览和图像编辑的语言。',projects:[{year:'1990s–present',title:'Installation practice',type:'摄影空间编排',facts:['MoMA描述其摄影装置为动态且反等级的空间结构。','作品可从大型喷墨打印延伸至杂志页和小尺寸照片，并利用整个展墙与建筑细节。'],reading:'摄影的重要性不再只由单张图像决定，而由图像之间不断变化的邻接关系与观看节奏产生。'}],images:[],sourceLabel:'MoMA · Wolfgang Tillmans',sourceUrl:'https://www.moma.org/artists/8044-wolfgang-tillmans'},
{id:'dayanita-singh',name:'Dayanita Singh',born:'1961',base:'India',intro:'印度摄影艺术家，以长期摄影档案、书籍和可移动木结构重新定义照片的编辑、储存、展示与叙事方式，并将其称为photo-architecture。',methods:['摄影档案编辑','模块化展示','摄影书','可变序列'],subjects:['档案','家庭与社会空间','记忆','展示制度','偶然性'],outputs:['摄影','摄影书','模块化摄影装置'],institutions:['MoMA'],achievements:['Museum of Chance','Museum Bhavan','Surrounds: 11 Installations'],whyImportant:'Singh把摄影从固定墙面图像转变成可反复编辑和重排的移动博物馆，使编辑、储存与展示本身成为摄影实践的核心。',projects:[{year:'2013',title:'Museum of Chance',type:'摄影建筑 / 可变装置',facts:['MoMA馆藏版本由162张喷墨照片与柚木结构组成。','可折叠木结构同时承担展示、档案与储存功能，照片可以不断重新排列。'],reading:'作品把摄影的意义从拍摄瞬间转向后续编辑，使同一档案通过不同组合持续产生新的叙事。'}],images:[],sourceLabel:'MoMA · Dayanita Singh',sourceUrl:'https://www.moma.org/collection/works/221934'},
{id:'gauri-gill',name:'Gauri Gill',born:'1970',base:'India',intro:'印度摄影艺术家，以长期社区合作、肖像、乡村档案与跨媒介协作处理身份、自我表述、教育、性别和印度边缘社区的日常生活。',methods:['长期合作摄影','社区共同创作','编排肖像','摄影与绘画协作'],subjects:['身份','原住民社区','乡村生活','教育','自我表述'],outputs:['摄影','摄影与绘画合作','装置'],institutions:['MoMA'],achievements:['Acts of Appearance','Notes from the Desert','Fields of Sight','Projects 108: Gauri Gill'],whyImportant:'Gill拒绝把社区成员作为被动的人类学对象，而通过多年关系和共同创作让拍摄对象参与自身视觉身份的建构，是合作型当代摄影的重要代表。',projects:[{year:'2015–ongoing',title:'Acts of Appearance',type:'合作编排摄影',facts:['Gill与印度Maharashtra的Adivasi社区及当地纸浆面具艺术家合作。','参与者制作与当代日常生活相关的新面具，并在日常活动中佩戴面具共同编排场景。'],reading:'系列让肖像中的身份成为由艺术家、面具制作者和被摄者共同表演的过程，而不是摄影师单方面定义的社会类型。'}],images:[],sourceLabel:'MoMA · Gauri Gill',sourceUrl:'https://www.moma.org/collection/works/283401'},
{id:'andreas-gursky',name:'Andreas Gursky',born:'1955',base:'Germany',intro:'德国摄影艺术家，以大型彩色摄影、远距离高视点和数字处理观察全球资本、消费、劳动、建筑与群体组织形成的巨大视觉系统。',methods:['大型摄影','高视点观察','数字图像处理','类型化空间研究'],subjects:['全球资本','消费','劳动','建筑','群体','基础设施'],outputs:['摄影'],institutions:['MoMA'],achievements:['Rhine II','99 Cent','Paris, Montparnasse','MoMA solo exhibition 2001'],whyImportant:'Gursky把纪实摄影扩展到接近历史画与抽象绘画尺度的复杂全景，使全球化经济和集体空间成为可被整体观看的视觉结构。',projects:[{year:'1999',title:'Rhine II',type:'大型彩色摄影',facts:['作品进入MoMA收藏。','其创作阶段代表Gursky将现实景观与数字处理结合形成高度压缩、秩序化的空间图像。'],reading:'作品把具体地点简化成近乎抽象的水平结构，使摄影同时保持现实索引与人工构成之间的张力。'}],images:[],sourceLabel:'MoMA · Andreas Gursky',sourceUrl:'https://www.moma.org/artists/7806-andreas-gursky'},
{id:'thomas-struth',name:'Thomas Struth',born:'1954',base:'Germany',intro:'德国摄影艺术家，以城市街道、家庭肖像、博物馆观众、宗教建筑和科技设施的系统性摄影研究人与制度化空间之间的关系。',methods:['类型学摄影','正面观察','大型摄影','长期系列'],subjects:['城市','家庭','博物馆','观看制度','科技','建筑'],outputs:['摄影'],institutions:['MoMA'],achievements:['Museum Photographs','Family Portraits','Unconscious Places'],whyImportant:'Struth把杜塞尔多夫摄影类型学扩展到城市、家庭和博物馆观看行为，使摄影成为分析社会空间、历史记忆与观看制度的精确工具。',projects:[{year:'1970s–present',title:'Unconscious Places',type:'城市摄影系列',facts:['MoMA收藏其1977年以来大量城市街道摄影。','早期作品以正面、克制的城市观察建立街道、建筑和社会结构之间的关系。'],reading:'城市在作品中不是风景背景，而是社会历史无意识被建筑和街道形式持续保存的表面。'}],images:[],sourceLabel:'MoMA · Thomas Struth',sourceUrl:'https://www.moma.org/artists/7825-thomas-struth'}
];