import type { Artist } from './data';
import { artistBatch157 } from './expansionBatch157';

export const artistBatch156: Artist[] = [
{id:'walid-raad',name:'Walid Raad',born:'1967',base:'Lebanon / United States',intro:'黎巴嫩出生的艺术家，以摄影、录像、档案、雕塑和讲演表演研究黎巴嫩战争、记忆、文件真实性以及阿拉伯世界艺术制度的形成。',methods:['虚构档案','档案重组','讲演表演','研究型摄影'],subjects:['黎巴嫩战争','记忆','档案','历史书写','艺术制度','中东政治'],outputs:['摄影','录像','装置','雕塑','表演','档案'],institutions:['MoMA','MoMA PS1'],achievements:['The Atlas Group 1989–2004','Walid Raad, MoMA 2015–16'],whyImportant:'Raad把真实研究、虚构人物和伪档案混合，使摄影文件的可信度本身成为作品问题，是当代艺术中档案虚构、战争记忆与制度批判的重要节点。',projects:[{year:'1989–2004',title:'The Atlas Group',type:'摄影 / 录像 / 虚构档案',facts:['项目持续十五年研究黎巴嫩当代历史。','作品包含虚构化摄影、录像、笔记本与讲演，同时关联真实事件和黎巴嫩影像档案研究。'],reading:'Raad并不把档案当作中立证据，而通过真假文件混合追问战争历史如何被记录、相信和重新叙述。'}],images:[],sourceLabel:'MoMA · Walid Raad',sourceUrl:'https://www.moma.org/calendar/exhibitions/1493'},
{id:'danh-vo',name:'Danh Vo',born:'1975',base:'Vietnam / Denmark / Germany',intro:'越南出生、丹麦成长的艺术家，以现成物、历史文献、私人遗物、雕塑和装置把个人迁徙史与殖民主义、民族国家、宗教和资本主义连接起来。',methods:['现成物重组','个人史与宏观历史并置','材料再语境化','碎片化复制'],subjects:['迁徙','殖民主义','民族主义','宗教','家庭记忆','资本主义'],outputs:['雕塑','装置','现成物','文献','摄影'],institutions:['Solomon R. Guggenheim Museum'],achievements:['Danh Vo: Take My Breath Away, Guggenheim 2018'],whyImportant:'Vo以私人家庭物件和历史遗物承载全球政治，使宏大历史通过具体物件和个人生命显现；他对自由女神像的碎片化复制也把国家象征转化为分散的物质系统。',projects:[{year:'2011–16',title:'We the People',type:'雕塑 / 分散式复制',facts:['作品按一比一尺度复制纽约自由女神像的铜质外壳。','约三百个独立部件被有意保持分散，从不组装成完整雕像。'],reading:'熟悉的国家象征被拆成薄铜碎片，使自由、民族身份、制造劳动与全球流通之间的关系重新变得陌生。'}],images:[],sourceLabel:'Guggenheim · Danh Vo — We the People',sourceUrl:'https://www.guggenheim.org/video/danh-vo-we-the-people-2011-16'},
{id:'cao-fei',name:'Cao Fei',born:'1978',base:'China',intro:'中国艺术家，以录像、摄影、虚拟世界、数字媒介和装置研究城市化、工厂劳动、青年文化、网络身份与技术社会。',methods:['虚拟世界构建','社会观察','角色扮演','数字叙事'],subjects:['城市化','工厂劳动','网络身份','青年文化','技术','中国社会转型'],outputs:['录像','摄影','虚拟世界','装置','数字艺术'],institutions:['MoMA','MoMA PS1','La Biennale di Venezia'],achievements:['RMB City 2007–11','Venice Biennale 2015','Cao Fei, MoMA PS1 2016'],whyImportant:'曹斐把中国高速城市化和互联网虚拟身份放在同一视觉系统中，是连接中国社会现实、电子游戏/虚拟世界和当代影像的重要艺术家。',projects:[{year:'2007–11',title:'RMB City',type:'虚拟世界 / 网络项目',facts:['项目在网络虚拟世界Second Life中持续建设。','艺术家通过化身China Tracy构造混合中国现实符号与未来想象的虚拟城市。'],reading:'城市不再只是被摄影记录的对象，而成为可进入、可扮演和持续变化的数字社会模型。'}],images:[],sourceLabel:'MoMA PS1 · Cao Fei',sourceUrl:'https://www.moma.org/calendar/exhibitions/4945'},
{id:'teresa-margolles',name:'Teresa Margolles',born:'1963',base:'Mexico / Spain',intro:'墨西哥艺术家，具有法医学学习背景，以摄影、织物、液体、建筑介入和现场材料研究死亡、毒品暴力、国家失职、边境与强迫迁徙。',methods:['法医学材料转化','现场取样','研究型装置','身体痕迹作为证据'],subjects:['死亡','毒品暴力','迁徙','边境','国家暴力','社会不平等'],outputs:['装置','摄影','织物','雕塑','现场介入'],institutions:['La Biennale di Venezia'],achievements:['Venice Biennale 2019','Venice Biennale 2024'],whyImportant:'Margolles把死亡留下的物质痕迹直接转化为作品证据，使暴力不只通过新闻图像被观看，而通过气味、液体、织物和身体痕迹进入展览空间。',projects:[{year:'2019',title:'Tela Venezolana',type:'织物 / 身体痕迹 / 研究项目',facts:['作品源自对委内瑞拉—哥伦比亚边境劳动与迁徙的长期研究。','白色织物在尸检过程中覆盖一名于Cúcuta附近遇害的年轻委内瑞拉男性身体，并留下血迹轮廓。'],reading:'织物既像匿名肖像也像无法解读的地图，让强迫迁徙中的暴力以直接物质痕迹而不是说明性图像出现。'}],images:[],sourceLabel:'La Biennale di Venezia · Teresa Margolles',sourceUrl:'https://www.labiennale.org/en/art/2024/nucleo-contemporaneo/teresa-margolles'},
...artistBatch157
];