import type { Artist } from './data';
import { artistBatch122 } from './expansionBatch122';

export const artistBatch121: Artist[] = [
{id:'hito-steyerl',name:'Hito Steyerl',born:'1966',base:'Germany',intro:'德国艺术家、电影作者与理论写作者，以影像装置、论文电影和数字图像研究处理网络社会、战争、监控、图像流通与技术权力。',methods:['论文电影','图像流通研究','档案蒙太奇','数字媒介批判'],subjects:['网络社会','战争','监控','图像政治','技术'],outputs:['录像','影像装置','电影','文字'],institutions:['MoMA','La Biennale di Venezia','documenta'],achievements:['November','How Not to Be Seen','In Free Fall','Liquidity Inc.'],whyImportant:'Steyerl把纪录片、理论写作与数字影像装置结合，是理解“贫穷图像”、网络传播和当代图像政治最关键的艺术家之一。',projects:[{year:'2004',title:'November',type:'论文电影 / 录像',facts:['作品结合库尔德电视纪录片、艺术家青少年时期拍摄的业余电影、Bruce Lee电影片段与第一人称旁白。','作品围绕艺术家友人Andrea Wolf及图像如何参与政治革命展开。'],reading:'私人记忆、政治斗争与复制图像被置于同一传播链条中，使图像本身成为历史行动者。'}],images:[],sourceLabel:'MoMA · Hito Steyerl',sourceUrl:'https://www.moma.org/artists/43752-hito-steyerl'},
{id:'zanele-muholi',name:'Zanele Muholi',born:'1972',base:'South Africa',intro:'南非视觉行动者与摄影艺术家，长期记录并共同建构南非黑人LGBTQIA+群体的肖像与生活史，同时通过高度控制的自画像研究种族、性别、观看和自我呈现。',methods:['视觉行动主义','长期肖像档案','自我表演','社区协作'],subjects:['黑人身份','酷儿生活','性别','社区','自我呈现'],outputs:['摄影','自画像','雕塑'],institutions:['Tate Modern','MoMA','Guggenheim Museum','Brooklyn Museum'],achievements:['Faces and Phases','Somnyama Ngonyama','Zanele Muholi — Tate Modern 2024–25'],whyImportant:'Muholi把摄影肖像从外部记录转为社区内部的视觉行动主义，建立持续扩展的黑人酷儿生命档案，并重新定义作者、被摄者与政治代表之间的关系。',projects:[{year:'2006–',title:'Faces and Phases',type:'长期肖像 / 社区档案',facts:['Muholi长期拍摄南非黑人女同性恋、双性恋、跨性别及其他酷儿个体。','Tate将Muholi描述为南非视觉行动者，并于2024–25举办大型个展。'],reading:'系列以持续相遇和命名对抗社会不可见性，使肖像成为共同体保存自身历史的方式。'}],images:[],sourceLabel:'Tate · Zanele Muholi',sourceUrl:'https://www.tate.org.uk/whats-on/tate-modern/zanele-muholi'},
{id:'dayanita-singh',name:'Dayanita Singh',born:'1961',base:'India',intro:'印度摄影艺术家，将摄影书、档案、可移动木结构和展览编排结合，持续研究照片如何被编辑、储存、重组并在不同展示情境中产生新的叙事。',methods:['摄影编辑','可变档案','摄影书','展示结构设计'],subjects:['档案','记忆','家庭','空间','偶然性'],outputs:['摄影','摄影书','装置','档案结构'],institutions:['MoMA'],achievements:['Museum of Chance','Museum Bhavan','File Room'],whyImportant:'Singh把摄影从单张图像扩展为可重新排列的“摄影建筑”，把编辑、收藏、存储和展示本身变成作品，是当代摄影展示机制的重要革新者。',projects:[{year:'2013',title:'Museum of Chance',type:'摄影 / 可变装置',facts:['作品包含162幅颜料喷墨照片及柚木展示结构。','铰接、可折叠的木结构同时承担展示、档案和储存功能，照片可持续重新排列。'],reading:'摄影的意义不再固定在单张照片，而在每一次编辑与重排中重新生成。'}],images:[],sourceLabel:'MoMA · Dayanita Singh',sourceUrl:'https://www.moma.org/artists/48057-dayanita-singh'},
{id:'trevor-paglen',name:'Trevor Paglen',born:'1974',base:'United States',intro:'美国艺术家、地理学者与摄影作者，以长焦摄影、卫星与基础设施研究、机器视觉和数据调查揭示通常不可见的军事、情报与监控系统。',methods:['调查研究','远距离摄影','实验地理','机器视觉研究'],subjects:['监控','军事基础设施','人工智能','数据','不可见系统'],outputs:['摄影','装置','影像','研究项目'],institutions:['Whitney Museum','Guggenheim Museum'],achievements:['An English Landscape','Limit Telephotography','Autonomy Cube','Deutsche Börse Photography Foundation Prize 2016'],whyImportant:'Paglen把摄影的可见性问题扩展到国家安全、卫星网络和AI视觉系统，使“拍摄看不见的基础设施”成为当代调查摄影与技术批判的重要方法。',projects:[{year:'2014',title:'An English Landscape (American Surveillance Base near Harrogate, Yorkshire)',type:'摄影 / 监控基础设施研究',facts:['作品为彩色显影摄影，拍摄英国约克郡附近的美国监控基地景观。','作品由Whitney Museum于2015年购藏。'],reading:'看似传统的风景摄影被转化为情报基础设施的可见证据，使田园景观与全球监控网络重叠。'}],images:[],sourceLabel:'Whitney Museum · Trevor Paglen',sourceUrl:'https://whitney.org/artists/11403'},
{id:'martha-rosler',name:'Martha Rosler',born:'1943',base:'United States',intro:'美国艺术家，以摄影蒙太奇、录像、行为、装置和写作批判战争、消费文化、家庭空间、女性角色与纪录摄影制度，将日常生活与全球政治持续并置。',methods:['摄影蒙太奇','媒介批判','女性主义介入','日常空间研究'],subjects:['战争','家庭','消费文化','女性身份','公共与私人'],outputs:['摄影','录像','装置','行为','文字'],institutions:['MoMA'],achievements:['House Beautiful: Bringing the War Home','Semiotics of the Kitchen','Meta-Monumental Garage Sale'],whyImportant:'Rosler把大众媒体中的战争图像直接嵌入美国中产家庭视觉文化，建立了女性主义摄影、媒介批判与政治蒙太奇之间极具影响力的方法谱系。',projects:[{year:'1967–72',title:'House Beautiful: Bringing the War Home',type:'摄影蒙太奇',facts:['系列把越南战争新闻照片与美国室内设计和消费广告图像拼接。','Rosler曾将作品复印件在反越战示威中传播，而不是只把它们作为画廊艺术。'],reading:'战争与舒适家庭不再是两个世界，蒙太奇暴露大众媒体如何让远方暴力进入又被日常消费景观吸收。'}],images:[],sourceLabel:'MoMA · Martha Rosler',sourceUrl:'https://www.moma.org/artists/6832-martha-rosler'},
...artistBatch122
];