import type { Artist, ArtworkImage, Project } from './data';
import type { ArtistArchive, ArchiveImage, ArchiveRelation } from './archiveData';

const image = (url: string, title: string, credit: string, sourceUrl: string, sourceLabel: string): ArtworkImage => ({ url, title, credit, sourceUrl, sourceLabel });
const project = (year: string, title: string, type: string, facts: string[], reading: string): Project => ({ year, title, type, facts, reading });
const img = (url: string, title: string, credit: string, sourceUrl: string, sourceLabel: string): ArchiveImage => ({ url, title, credit, sourceUrl, sourceLabel });
const rel = (kind: ArchiveRelation['kind'], label: string, detail?: string): ArchiveRelation => ({ kind, label, detail });

export const artistBatch9: Artist[] = [
  {
    id: 'john-stezaker', name: 'John Stezaker', born: '1949', base: 'London',
    intro: '从旧电影剧照、明星宣传照、明信片和旅行插图中切割、遮挡与拼接，让现成图像之间的偶然对应成为作品。',
    methods: ['found image', '拼贴', '挪用', '切割', '遮挡'], subjects: ['凝视', '身份', '电影', '图像记忆', '大众文化'], outputs: ['拼贴', '摄影作品', '艺术家书'],
    institutions: ['MoMA', 'Whitechapel Gallery', 'The Photographers’ Gallery'], achievements: ['Deutsche Börse Photography Prize 2012 winner'],
    whyImportant: '他几乎不需要再拍摄新照片，创作发生在寻找、切开、覆盖和两张图之间的精确对位。对理解“现成图像如何变成新的摄影作品”非常关键。',
    projects: [project('1980s–', 'Mask', '电影肖像 / 明信片拼贴', ['把风景明信片直接覆盖在旧电影明星脸上。', '尽量不缩放图像，而依靠偶然轮廓对位。'], '不是 Photoshop 合成，而是非常具体的纸张覆盖与视觉错认。')],
    images: [image('https://fadmagazine.com/wp-content/uploads/AP-STEZJ-02402-A-300.jpg', 'Mask series', '© John Stezaker', 'https://www.whitechapelgallery.org/exhibitions/john-stezaker/', 'Whitechapel Gallery / press documentation')], sourceLabel: 'Whitechapel Gallery', sourceUrl: 'https://www.whitechapelgallery.org/exhibitions/john-stezaker/'
  },
  {
    id: 'elad-lassry', name: 'Elad Lassry', born: '1977', base: 'Los Angeles',
    intro: '重新拍摄广告、教材、静物和人物，把照片与同色框、绳线、雕塑性支架连接，让“图片”和“物件”无法分开。',
    methods: ['再摄影', '工作室摄影', '挪用', '场景建构', '摄影物件'], subjects: ['大众图像', '观看机制', '商品', '身体', '摄影史'], outputs: ['摄影', '雕塑式框架', '电影', '装置'],
    institutions: ['MoMA', 'SFMOMA', 'Venice Biennale'], achievements: ['MoMA New Photography 2010', 'Venice Biennale 2011'],
    whyImportant: 'Lassry 特别适合研究“照片的边界在哪里”：框的颜色、线、墙面与照片内部一样参与作品，不再只是展示附件。',
    projects: [project('2008–', 'Studio photographs', '再摄影 / 图片物件', ['使用既有广告、动物、食物与人物图像。', '在工作室重新布置和拍摄。', '经常制作与照片颜色对应的框。'], '他让商业图像的熟悉感变得不稳定，同时把摄影重新拉回物件。')],
    images: [image('https://media.meer.com/attachments/7bff5e3f0995cee8a3589a46cb62b75c23637155/store/fill/410/615/9ab733944fa4aef4c28266b0b2a96a560805f354fd7d32008d205e120604/Elad-Lassry-Untitled-Woman-B-2015-detail-Silver-gelatin-print-wire-plastic-walnut-frame-21-1.jpg', 'Untitled (Woman B)', '© Elad Lassry', 'https://www.303gallery.com/artists/elad-lassry/biography', '303 Gallery')], sourceLabel: '303 Gallery', sourceUrl: 'https://www.303gallery.com/artists/elad-lassry/biography'
  },
  {
    id: 'felicity-hammond', name: 'Felicity Hammond', born: '1988', base: 'London',
    intro: '把房地产渲染图、城市更新宣传、AI生成图与建筑材料重新组合成摄影装置，研究未来城市如何先以图像被销售。',
    methods: ['数字合成', '研究型摄影', '摄影装置', 'AI图像', '场域特定'], subjects: ['城市开发', '房地产', 'AI', '图像生产', '基础设施'], outputs: ['摄影装置', '雕塑', '数字图像', '公共艺术'],
    institutions: ['Foam', 'The Photographers’ Gallery', 'C/O Berlin', 'Fotomuseum Winterthur'], achievements: ['Foam Talent 2016', 'Deutsche Börse longlist 2019', 'V3: Model Collapse — TPG 2025'],
    whyImportant: '她不是只批评“AI假图”，而是把建筑效果图、城市营销和生成式模型放在同一条图像生产链里，特别适合看摄影如何变成空间和材料。',
    projects: [project('2016', 'Foam Talent 2016 / Property', '房地产图像 / 摄影装置', ['以房地产效果图、开发宣传和现场摄影研究城市在建成之前如何先被图像销售。', '入选 Foam Talent 2016，作品进入 Foam Magazine #45 与该届展览体系。'], '这一节点能看到她后来 AI 与城市图像研究的前史。'), project('2024–25', 'V1–V3 / Model Collapse', '生成图像 / 摄影装置', ['收集和制造城市未来图像。', '把AI生成与实体建筑材料并置。', '以大型装置让图像从屏幕进入空间。'], 'AI 在这里不是风格滤镜，而是城市想象和资本预测系统的一部分。')],
    images: [image('https://thephotographersgallery.org.uk/sites/default/files/styles/original/public/images/BRI09710.jpg.webp?itok=nwdtRcSP', 'V3: Model Collapse — installation', '© Felicity Hammond / The Photographers’ Gallery', 'https://thephotographersgallery.org.uk/whats-on/felicity-hammond-v3-model-collapse', 'The Photographers’ Gallery')], sourceLabel: 'Artist CV', sourceUrl: 'https://www.felicityhammond.com/bio'
  },
  {
    id: 'yto-barrada', name: 'Yto Barrada', born: '1971', base: 'Tangier / New York',
    intro: '从丹吉尔海峡、迁移与边境出发，逐渐扩展到电影、植物、化石、染料、纺织和另类教育，把摄影放进更宽的研究实践。',
    methods: ['研究型摄影', '纪实摄影', '影像', '档案', '材料研究'], subjects: ['迁移', '殖民', '边境', '植物', '摩洛哥', '文化制度'], outputs: ['摄影', '电影', '雕塑', '纺织', '装置'],
    institutions: ['MoMA', 'Tate Modern', 'Venice Biennale', 'Whitney Biennial'], achievements: ['Deutsche Bank Artist of the Year 2011', 'France Pavilion Venice 2026'],
    whyImportant: '她展示了一位摄影出身艺术家如何逐渐进入更大的当代艺术体系，同时仍保持田野研究和图像观察的核心。',
    projects: [project('1998–2004', 'A Life Full of Holes: The Strait Project', '丹吉尔 / 海峡 / 迁移', ['长期拍摄丹吉尔港口、边界、等待和城市空地。', '避免直接把非法迁移者变成猎奇对象。'], '边境常常通过“等待、阻隔、看向远方”的日常空间出现，而不是事件照片。')],
    images: [image('https://palaispopulaire.db.com/contentAsset/image/7cabbc2b-fddc-420c-a0cc-a96be6dcde04', 'Belvedere 3, Tangier', '© Yto Barrada', 'https://www.sfmoma.org/watch/yto-barrada-on-how-the-strait-of-gibraltar-shapes-life-in-tangier/', 'SFMOMA / PalaisPopulaire')], sourceLabel: 'MoMA', sourceUrl: 'https://www.moma.org/collection/artists/42323'
  },
  {
    id: 'teresa-margolles', name: 'Teresa Margolles', born: '1963', base: 'Mexico City / Madrid',
    intro: '从法医与社会暴力现场出发，使用墙体、布、尘土、水、声音和摄影，让暴力留下的物质痕迹进入展览空间。',
    methods: ['研究型艺术', '现场材料', '装置', '摄影', '社会调查'], subjects: ['暴力', '死亡', '迁移', '边境', '女性', '国家失职'], outputs: ['装置', '摄影', '行为', '声音', '场域介入'],
    institutions: ['Venice Biennale', 'Tate', 'Museo Reina Sofía'], achievements: ['Mexico Pavilion Venice 2009', 'Venice 2019 special mention'],
    whyImportant: '她把“证据”从可观看的新闻照片转成材料和空间，让观众面对暴力的物质后果，而不是只消费一张事件影像。',
    projects: [project('2009', 'What Else Could We Talk About?', '墨西哥馆 / 暴力痕迹', ['把来自暴力现场的材料与展览空间联系。', '通过清洁、擦拭和物质转移让缺席者进入现场。'], '重点是痕迹如何被带进美术馆，以及这种转移产生的伦理问题。')],
    images: [image('https://news.artnet.com/app/news-upload/2019/05/29-teresa-margolles-1024x683.jpg', 'Muro Ciudad Juárez — Venice installation', '© Teresa Margolles / installation view', 'https://www.labiennale.org/en/art/2019/partecipants/teresa-margolles', 'La Biennale di Venezia / installation documentation')], sourceLabel: 'La Biennale di Venezia', sourceUrl: 'https://www.labiennale.org/en/art/2019/partecipants/teresa-margolles'
  },
  {
    id: 'ming-smith', name: 'Ming Smith', born: '1947', base: 'New York',
    intro: '以长曝光、运动模糊、深黑阴影和极强直觉拍摄黑人城市生活、音乐与家庭，让摄影接近爵士即兴和绘画。',
    methods: ['街头摄影', '长曝光', '运动模糊', '黑白摄影', '手工上色'], subjects: ['黑人生活', '音乐', '城市', '家庭', '可见性', '记忆'], outputs: ['摄影', '手工上色摄影', '摄影书', '展览'],
    institutions: ['MoMA', 'Studio Museum in Harlem', 'Aperture'], achievements: ['MoMA Projects solo 2023', 'first Black woman photographer acquired by MoMA'],
    whyImportant: '她的模糊不是技术失误，而是一种主动的运动语言；人物常处在可见与不可见之间，非常适合对照传统“清晰即真实”的摄影观。',
    projects: [project('1990s', 'Invisible Man, Somewhere, Everywhere', '可见性 / 黑白与绘画', ['以 Ralph Ellison 的“不可见”概念作为松散触发。', '部分作品在银盐照片上加入油彩。'], '摄影和绘画共同制造一种人物出现又消失的状态。')],
    images: [image('https://studiomuseum.imgix.net/images/poetics-of-form-1.jpg', 'Invisible Man, Somewhere, Everywhere', '© Ming Smith', 'https://www.moma.org/collection/works/55317', 'MoMA / Studio Museum')], sourceLabel: 'MoMA', sourceUrl: 'https://www.moma.org/collection/artists/7906'
  },
  {
    id: 'sabelo-mlangeni', name: 'Sabelo Mlangeni', born: '1980', base: 'Johannesburg',
    intro: '以长期相处和黑白摄影进入南非乡村酷儿社群、男性宿舍、家庭与小镇生活，不把暴力或贫困当作唯一叙事。',
    methods: ['长期纪实', '黑白摄影', '社区合作', '肖像', '观察式摄影'], subjects: ['酷儿生活', '社区', '乡村', '劳动', '迁移', '日常生活'], outputs: ['摄影', '摄影书', '展览'],
    institutions: ['V&A', 'Market Photo Workshop', 'Rencontres de Bamako'], achievements: ['Tollman Award for Visual Arts 2009'],
    whyImportant: '他最重要的方法是“花时间成为环境的一部分”。图像的亲密感来自长期共同生活，而不是靠镜头距离制造。',
    projects: [project('2003–09', 'Country Girls', '乡村酷儿生活 / 长期纪实', ['在 Mpumalanga 多个小镇持续六年拍摄。', '记录工作、选美、祈祷、聚会与普通生活。'], '系列拒绝把酷儿乡村生活只写成受害史，而把社群的日常、欲望和自我塑造放在中心。')],
    images: [image('https://americansuburbx.com/wp-content/uploads/2011/10/countrygirls14.jpg', 'Country Girls', '© Sabelo Mlangeni', 'https://archive.stevenson.info/exhibitions/mlangeni/countrygirls/index.htm', 'Stevenson / project documentation')], sourceLabel: 'Stevenson', sourceUrl: 'https://archive.stevenson.info/exhibitions/mlangeni/countrygirls/index.htm'
  },
  {
    id: 'susan-meiselas', name: 'Susan Meiselas', born: '1948', base: 'New York',
    intro: '从 Carnival Strippers 到 Nicaragua 和 Kurdistan，把长期关系、声音采访、历史档案与回访放入纪实摄影，使照片不断回到它所来自的社群。',
    methods: ['长期纪实', '口述史', '档案', '回访', '摄影书'], subjects: ['战争', '女性', '革命', '记忆', '人权', '社群'], outputs: ['摄影', '摄影书', '声音档案', '电影', '公共装置'],
    institutions: ['MoMA', 'Magnum Photos', 'The Photographers’ Gallery'], achievements: ['Deutsche Börse Photography Foundation Prize 2019', 'Magnum member since 1976'],
    whyImportant: '她不是把纪实理解成“到现场拍完就离开”，而是不断回去追踪照片后来如何被使用、被记忆和被当事人重新解释。',
    projects: [project('1972–75', 'Carnival Strippers', '长期纪实 / 声音采访', ['连续多个夏天跟随巡回脱衣舞表演者。', '同时拍台前、后台与日常生活。', '录制表演者和周围男性的访谈。'], '照片与声音共同让被摄者解释自己的经济与生活条件。')],
    images: [image('https://www.worldphoto.org/sites/default/files/4%20%C2%A9%20Susan%20Meiselas%20_%20Magnum%20Photos.jpg', 'Carnival Strippers', '© Susan Meiselas / Magnum Photos', 'https://www.moma.org/collection/artists/45094', 'MoMA / World Photography Organisation')], sourceLabel: 'MoMA', sourceUrl: 'https://www.moma.org/collection/artists/45094'
  }
];

export const archiveBatch9New: Record<string, ArtistArchive> = {
  'john-stezaker': { artistId: 'john-stezaker', projectCoverage: '4 个 found-image 核心项目群已完成第一轮 · 1970s–现在', imageCoverage: '', note: '按具体剪切规则拆开 Mask、Marriage、Dark Star 与 Third Person Archive。', projects: [
    { title: 'Vanishing Point / Vantage Point', cluster: 'postcard / insertion / found image', period: '1970s', summary: '将旅行明信片嵌入或覆盖既有照片，使两个原本无关的空间意外对齐。', actions: ['搜集旧印刷品', '裁切', '手工插入 / 覆盖'], sourceUrl: 'https://www.moma.org/collection/works/107986', images: [], relations: [rel('收藏', 'MoMA', 'Insert, 1979')] },
    { title: 'Marriage', cluster: 'two portraits / splice', period: '1980s–', summary: '沿面部中轴切开两张电影宣传肖像，再将不同人物拼成一个不稳定的新脸。', actions: ['明星宣传照收集', '纵向切割', '精确拼接'], sourceUrl: 'https://www.moma.org/collection/works/107988', images: [], relations: [rel('收藏', 'MoMA', 'Marriage XV, 2006')] },
    { title: 'Mask', cluster: 'portrait / landscape postcard', period: '1982–', summary: '以彩色风景明信片遮住黑白电影明星面孔，让洞穴、瀑布、桥梁替代五官。', actions: ['旧电影肖像收集', '风景明信片选择', '不缩放对位', '覆盖'], sourceUrl: 'https://www.whitechapelgallery.org/exhibitions/john-stezaker/', images: [img('https://fadmagazine.com/wp-content/uploads/AP-STEZJ-02402-A-300.jpg', 'Mask series', '© John Stezaker', 'https://www.whitechapelgallery.org/exhibitions/john-stezaker/', 'Whitechapel Gallery / press documentation')], relations: [] },
    { title: 'Third Person Archive / Dark Star', cluster: 'archive / excision / absence', period: '1990s–2000s', summary: '通过切除、孤立或留下人物空洞，把旧印刷物中的边缘人物和明星肖像重新置于中心。', actions: ['旅行插图档案', '切除人物', '重新分类', '小尺幅展示'], sourceUrl: 'https://www.whitechapelgallery.org/exhibitions/john-stezaker/', images: [], relations: [rel('奖项', 'Deutsche Börse Photography Prize', 'winner 2012')] }
  ], awards: ['Deutsche Börse Photography Prize 2012'], exhibitions: ['Whitechapel Gallery / Mudam survey 2011'], sources: [{ label: 'Whitechapel Gallery survey', url: 'https://www.whitechapelgallery.org/exhibitions/john-stezaker/' }, { label: 'MoMA artist archive', url: 'https://www.moma.org/artists/32462-john-stezaker' }] },
  'elad-lassry': { artistId: 'elad-lassry', projectCoverage: '4 个图片 / 框架 / 电影节点已完成第一轮 · 2008–2020', imageCoverage: '', note: 'Lassry 很少以封闭系列工作，因此按摄影物件、框架和电影的关键方法节点整理。', projects: [
    { title: 'Early studio pictures', cluster: 'appropriation / studio still life', period: '2008–2010', summary: '把商品、动物、人像和既有印刷图像放进非常干净的工作室摄影语法。', actions: ['既有图像搜集', '工作室布置', '重新拍摄', '同色框装'], sourceUrl: 'https://www.moma.org/artists/38028-elad-lassry', images: [], relations: [rel('展览', 'MoMA New Photography', '2010')] },
    { title: 'Colored frames and cords', cluster: 'photograph as object', period: '2010s', summary: '框的颜色、厚度以及延伸到墙面的线成为照片的一部分。', actions: ['定制彩色框', '线 / 塑料部件', '摄影与雕塑结合'], sourceUrl: 'https://www.303gallery.com/artists/elad-lassry/biography', images: [img('https://media.meer.com/attachments/7bff5e3f0995cee8a3589a46cb62b75c23637155/store/fill/410/615/9ab733944fa4aef4c28266b0b2a96a560805f354fd7d32008d205e120604/Elad-Lassry-Untitled-Woman-B-2015-detail-Silver-gelatin-print-wire-plastic-walnut-frame-21-1.jpg', 'Untitled (Woman B)', '© Elad Lassry', 'https://www.303gallery.com/artists/elad-lassry/biography', '303 Gallery')], relations: [] },
    { title: 'Films', cluster: 'motion / image syntax', period: '2010s', summary: '将人物、舞蹈和物件的摄影式布置移入电影，继续研究图像如何被读取。', actions: ['16mm / film', '场景与人物编排', '循环放映'], sourceUrl: 'https://www.303gallery.com/artists/elad-lassry/biography', images: [], relations: [] },
    { title: 'SFMOMA presentation', cluster: 'museum / photograph-object', period: '2020', summary: '将长期摄影、框架和雕塑性展示集中呈现，强化图片与物体之间的关系。', actions: ['跨作品重编', '空间安装'], sourceUrl: 'https://www.303gallery.com/artists/elad-lassry/biography', images: [], relations: [rel('展览', 'SFMOMA', '2020')] }
  ], awards: [], exhibitions: ['MoMA New Photography 2010', '54th Venice Biennale 2011', 'SFMOMA 2020'], sources: [{ label: '303 Gallery biography', url: 'https://www.303gallery.com/artists/elad-lassry/biography' }, { label: 'MoMA artist page', url: 'https://www.moma.org/artists/38028-elad-lassry' }] },
  'felicity-hammond': { artistId: 'felicity-hammond', projectCoverage: '5 个城市图像 / 生成模型 / 装置节点已完成第一轮 · 2014–2026', imageCoverage: '', note: '重点追踪房地产效果图、摄影材料和生成式AI如何被逐步引入她的空间装置。', projects: [
    { title: 'Restore to Factory Settings', cluster: 'property image / digital composite', period: '2014', summary: '以城市开发、工业遗址与宣传图像的数字拼接作为早期方法。', actions: ['城市拍摄', '数字拼接', '打印 / 空间展示'], sourceUrl: 'https://www.felicityhammond.com/bio', images: [], relations: [] },
    { title: 'Property', cluster: 'real-estate render / photobook', period: '2016–2019', summary: '研究房地产广告与CGI如何在建筑真正存在之前出售一种未来。', actions: ['房地产图像采集', '现场摄影', '数字合成', '摄影书'], sourceUrl: 'https://www.felicityhammond.com/bio', images: [], relations: [rel('出版', 'Property', 'SPBH Editions, 2019'), rel('奖项', 'Foam Talent', '2016')] },
    { title: 'Remains in Development', cluster: 'architecture / installation', period: '2021', summary: '把开发宣传、废墟和建筑材料变成立体摄影装置。', actions: ['数字图像', '建筑材料', '场域特定安装'], sourceUrl: 'https://www.felicityhammond.com/bio', images: [], relations: [rel('展览', 'C/O Berlin / Kunsthal Extra City', '2021')] },
    { title: 'V1: Content Aware', cluster: 'AI / urban image', period: '2024', summary: '将生成式图像和“内容感知”工具带入关于城市未来的研究。', actions: ['AI生成', '数字修补', '摄影装置'], sourceUrl: 'https://www.felicityhammond.com/bio', images: [], relations: [rel('展览', 'Photoworks Festival', '2024')] },
    { title: 'V3: Model Collapse', cluster: 'generative AI / material installation', period: '2025', summary: '讨论训练数据反复吞食生成图像导致的视觉退化，同时把模型输出转成实体结构。', actions: ['生成式AI', '图像再训练语境', '打印', '木构架 / 材料安装'], sourceUrl: 'https://thephotographersgallery.org.uk/whats-on/felicity-hammond-v3-model-collapse', images: [img('https://thephotographersgallery.org.uk/sites/default/files/styles/original/public/images/BRI09710.jpg.webp?itok=nwdtRcSP', 'V3: Model Collapse', '© Felicity Hammond / TPG', 'https://thephotographersgallery.org.uk/whats-on/felicity-hammond-v3-model-collapse', 'The Photographers’ Gallery')], relations: [rel('展览', 'The Photographers’ Gallery', '2025')] }
  ], awards: ['Foam Talent 2016', 'Lumen Art Prize 2018', 'Ampersand Photoworks Fellowship 2023'], exhibitions: ['C/O Berlin 2021', 'The Photographers’ Gallery 2025', 'Stills Edinburgh 2025'], sources: [{ label: 'Felicity Hammond CV', url: 'https://www.felicityhammond.com/bio' }] },
  'yto-barrada': { artistId: 'yto-barrada', projectCoverage: '5 个边境 / 植物 / 历史 / 纺织节点已完成第一轮 · 1998–2026', imageCoverage: '', note: '从摄影项目开始，向电影、化石、植物染料和纺织扩张，显示摄影如何进入完整的当代艺术研究体系。', projects: [
    { title: 'A Life Full of Holes: The Strait Project', cluster: 'Tangier / border / migration', period: '1998–2004', summary: '围绕丹吉尔和直布罗陀海峡拍摄等待、阻隔、港口与被欧洲边境制度塑造的城市生活。', actions: ['长期城市摄影', '港口 / 边界田野', '彩色中画幅'], sourceUrl: 'https://www.sfmoma.org/watch/yto-barrada-on-how-the-strait-of-gibraltar-shapes-life-in-tangier/', images: [img('https://palaispopulaire.db.com/contentAsset/image/7cabbc2b-fddc-420c-a0cc-a96be6dcde04', 'Belvedere 3', '© Yto Barrada', 'https://www.sfmoma.org/watch/yto-barrada-on-how-the-strait-of-gibraltar-shapes-life-in-tangier/', 'SFMOMA / PalaisPopulaire')], relations: [] },
    { title: 'Riffs / Tangier works', cluster: 'city / cinema / cultural infrastructure', period: '2000s–2011', summary: '摄影、电影与城市文化机构实践共同围绕丹吉尔展开，并与她共同创办的 Cinémathèque de Tanger 相互连接。', actions: ['摄影', '电影', '文化机构建设', '出版'], sourceUrl: 'https://art.state.gov/personnel/yto_barrada/', images: [], relations: [rel('奖项', 'Deutsche Bank Artist of the Year', '2011')] },
    { title: 'Faux Guide', cluster: 'fossils / geology / tourism', period: '2015', summary: '从摩洛哥化石贸易、博物学和旅游想象切入，摄影与雕塑、档案并用。', actions: ['田野研究', '物件收集', '摄影', '雕塑 / 陈列'], sourceUrl: 'https://www.fondation-vincentvangogh-arles.org/en/biographie/yto-barrada/', images: [], relations: [] },
    { title: 'The Mothership / dye garden', cluster: 'botany / textile / learning', period: '2010s–', summary: '围绕染料植物、园艺、手工知识和替代教育建立持续研究与驻留空间。', actions: ['种植染料植物', '纺织', '工作坊', '研究驻留'], sourceUrl: 'https://www.fondation-pernod-ricard.com/en/person/yto-barrada', images: [], relations: [] },
    { title: 'Comme Saturne', cluster: 'France Pavilion / textile / exhaustion', period: '2026', summary: '以羊毛、折叠、机器、颜色和 dévoré 纺织技术构造关于劳动、消耗和当代疲惫的多个环境。', actions: ['纺织', '悬挂结构', '材料侵蚀', '多空间编排'], sourceUrl: 'https://www.labiennale.org/en/art/2026/france', images: [], relations: [rel('展览', 'France Pavilion — Venice Biennale', '2026 · curator Myriam Ben Salah')] }
  ], awards: ['Deutsche Bank Artist of the Year 2011', 'Mario Merz Prize 2022'], exhibitions: ['Venice Biennale 2007 / 2011 / France Pavilion 2026', 'Whitney Biennial 2022', 'MoMA / MoMA PS1'], sources: [{ label: 'MoMA artist archive', url: 'https://www.moma.org/collection/artists/42323' }, { label: 'Venice 2026 France Pavilion', url: 'https://www.labiennale.org/en/art/2026/france' }] },
  'teresa-margolles': { artistId: 'teresa-margolles', projectCoverage: '5 个法医 / 暴力 / 边境材料项目已完成第一轮 · 2003–2024', imageCoverage: '', note: '按“痕迹如何从现场进入展场”整理，强调材料来源和伦理，而不是只看冲击性。', projects: [
    { title: 'En el aire', cluster: 'material trace / installation', period: '2003', summary: '以非常轻盈的空间形式让死亡与缺席进入观众的身体经验。', actions: ['现场来源材料处理', '空间装置', '观众参与'], sourceUrl: 'https://www.tate.org.uk/art/artists/teresa-margolles-11831', images: [], relations: [] },
    { title: 'What Else Could We Talk About?', cluster: 'Mexico Pavilion / narco-violence', period: '2009', summary: '墨西哥馆把暴力现场的物质痕迹、清洁动作和空间持续维护纳入作品。', actions: ['现场材料收集', '空间清洁 / 擦拭', '行为', '装置'], sourceUrl: 'https://www.labiennale.org/', images: [], relations: [rel('展览', 'Mexico Pavilion — Venice Biennale', '2009')] },
    { title: 'Muro Ciudad Juárez', cluster: 'wall / forensic material / border violence', period: '2010–2019', summary: '以来自 Ciudad Juárez 的墙体和建筑材料将边境暴力的物质表面带入展览。', actions: ['墙体拆取 / 运输', '原尺寸空间安装', '材料证据'], sourceUrl: 'https://www.labiennale.org/en/art/2019/partecipants/teresa-margolles', images: [img('https://news.artnet.com/app/news-upload/2019/05/29-teresa-margolles-1024x683.jpg', 'Muro Ciudad Juárez — Venice installation', '© Teresa Margolles / installation view', 'https://www.labiennale.org/en/art/2019/partecipants/teresa-margolles', 'Venice Biennale / press documentation')], relations: [rel('奖项', 'Venice Biennale special mention', '2019')] },
    { title: 'Tela Venezolana', cluster: 'migration / forensic cloth', period: '2019', summary: '以布料保存一名在委内瑞拉—哥伦比亚边境死亡青年的身体痕迹，将迁移暴力转成不可读却真实存在的材料记录。', actions: ['法医现场合作', '布料接触', '展场悬挂'], sourceUrl: 'https://www.labiennale.org/en/art/2024/nucleo-contemporaneo/teresa-margolles', images: [], relations: [rel('展览', 'Venice Biennale International Exhibition', '2024')] },
    { title: 'Recent border and transfeminicide works', cluster: 'social violence / collective remembrance', period: '2020s', summary: '持续与受暴力影响社群合作，把纪念、抗议和材料证据带入公共和机构空间。', actions: ['社群合作', '调查', '摄影 / 装置', '纪念行动'], sourceUrl: 'https://www.labiennale.org/en/art/2024/nucleo-contemporaneo/teresa-margolles', images: [], relations: [] }
  ], awards: ['Venice Biennale special mention 2019'], exhibitions: ['Mexico Pavilion — Venice 2009', 'Venice International Exhibition 2019 / 2024'], sources: [{ label: 'Venice Biennale 2019', url: 'https://www.labiennale.org/en/art/2019/partecipants/teresa-margolles' }, { label: 'Venice Biennale 2024', url: 'https://www.labiennale.org/en/art/2024/nucleo-contemporaneo/teresa-margolles' }] },
  'ming-smith': { artistId: 'ming-smith', projectCoverage: '5 个黑人城市生活 / 音乐 / 可见性节点已完成第一轮 · 1970s–2023', imageCoverage: '', note: '不按传统封闭系列硬分，而按长期拍摄主题与关键展览节点整理。', projects: [
    { title: 'Kamoinge / Harlem street work', cluster: 'Black life / street / movement', period: '1970s', summary: '在纽约街头、社区和家庭中以高反差、模糊与极低照度拍摄黑人日常。', actions: ['街头摄影', '低照度', '长曝光', '暗房打印'], sourceUrl: 'https://www.moma.org/collection/artists/7906', images: [], relations: [] },
    { title: 'Jazz portraits', cluster: 'music / movement / light', period: '1970s–', summary: '拍摄 Sun Ra、Grace Jones、Alice Coltrane 等文化人物，但强调运动、节奏和现场光而非标准名人肖像。', actions: ['现场摄影', '长曝光', '运动模糊'], sourceUrl: 'https://www.moma.org/magazine/articles/841', images: [], relations: [] },
    { title: 'Women’s Work', cluster: 'Black women / everyday life', period: '1980s', summary: '从普通劳动与生活场景处理黑人女性的韧性、姿态与日常美学。', actions: ['长期观察', '黑白摄影', '序列编辑'], sourceUrl: 'https://www.nga.gov/artists/47816-ming-smith', images: [], relations: [] },
    { title: 'Invisible Man, Somewhere, Everywhere', cluster: 'visibility / Ellison / painted photograph', period: '1991–1998', summary: '以 Ralph Ellison 的不可见性作为松散触发，用模糊、深黑和部分油彩让人物在环境中浮现与消失。', actions: ['银盐摄影', '长曝光 / 模糊', '油彩介入'], sourceUrl: 'https://www.moma.org/collection/works/55317', images: [img('https://studiomuseum.imgix.net/images/poetics-of-form-1.jpg', 'Invisible Man, Somewhere, Everywhere', '© Ming Smith', 'https://www.moma.org/collection/works/55317', 'MoMA / Studio Museum')], relations: [rel('收藏', 'MoMA', 'Invisible Man, Somewhere, Everywhere')] },
    { title: 'Projects: Ming Smith', cluster: 'archive / museum reintroduction', period: '2023', summary: 'MoMA 对其数十年档案进行重新编辑，把早期街头、音乐、家庭和实验打印放进同一脉络。', actions: ['档案重访', '跨年代编辑', '博物馆展览'], sourceUrl: 'https://www.moma.org/calendar/exhibitions/5514', images: [], relations: [rel('展览', 'MoMA', '2023')] }
  ], awards: [], exhibitions: ['Projects: Ming Smith — MoMA 2023'], sources: [{ label: 'MoMA artist archive', url: 'https://www.moma.org/collection/artists/7906' }, { label: 'Studio Museum', url: 'https://www.studiomuseum.org/artists/ming-smith' }] },
  'sabelo-mlangeni': { artistId: 'sabelo-mlangeni', projectCoverage: '5 个社群 / 劳动 / 酷儿生活项目已完成第一轮 · 2003–2020', imageCoverage: '', note: '按长期进入不同社群的时间线整理，避免把南非经验简化成暴力或贫困。', projects: [
    { title: 'Country Girls', cluster: 'rural queer life / community', period: '2003–2009', summary: '六年间在 Mpumalanga 小镇拍摄酷儿生活、选美、工作、宗教与社交。', actions: ['长期驻留 / 回访', '黑白摄影', '社群内部关系'], sourceUrl: 'https://archive.stevenson.info/exhibitions/mlangeni/countrygirls/index.htm', images: [img('https://americansuburbx.com/wp-content/uploads/2011/10/countrygirls14.jpg', 'Country Girls', '© Sabelo Mlangeni', 'https://archive.stevenson.info/exhibitions/mlangeni/countrygirls/index.htm', 'Stevenson / project documentation')], relations: [rel('出版', 'Country Girls', 'Stevenson, 2010')] },
    { title: 'Invisible Women', cluster: 'domestic workers / labour', period: '2000s', summary: '关注女性家务劳动和城市中经常不可见的工作位置。', actions: ['长期纪实', '肖像', '工作环境摄影'], sourceUrl: 'https://www.sabcart.co.za/sabelo-mlangeni/', images: [], relations: [rel('展览', 'first solo exhibition', '2007')] },
    { title: 'Men Only', cluster: 'migrant hostel / labour / intimacy', period: '2008–2009', summary: '在 Johannesburg George Goch 男性宿舍生活数周，拍摄工人日常而非预设的暴力叙事。', actions: ['驻留式拍摄', '共享日常', '黑白摄影'], sourceUrl: 'https://archive.stevenson.info/exhibitionsbs/mlangeni/index2010.htm', images: [], relations: [rel('出版', 'Men Only', 'Stevenson, 2009')] },
    { title: 'At Home / Ghost Towns', cluster: 'rural migration / waiting', period: '2010–2011', summary: '拍摄劳动力迁出后的乡村家庭和衰退小镇，把等待、空置与迁移后的空间并置。', actions: ['乡村田野', '小镇景观', '家庭与空间摄影'], sourceUrl: 'https://archive.stevenson.info/exhibitions/mlangeni/athome_index.html', images: [], relations: [rel('出版', 'At Home / Ghost Towns', '2011')] },
    { title: 'The Royal House of Allure', cluster: 'LGBTQI+ safe house / Lagos', period: '2020', summary: '围绕 Lagos 的 LGBTQI+ safe house 和其中的社群关系继续其长期酷儿生活研究。', actions: ['社群合作', '肖像与日常摄影'], sourceUrl: 'https://www.sabcart.co.za/sabelo-mlangeni/', images: [], relations: [] }
  ], awards: ['Tollman Award for Visual Arts 2009'], exhibitions: ['Rencontres de Bamako 2011', 'V&A — Figures & Fictions 2011'], sources: [{ label: 'Stevenson archive', url: 'https://archive.stevenson.info/exhibitions/mlangeni/countrygirls/index.htm' }, { label: 'SABC Art Collection', url: 'https://www.sabcart.co.za/sabelo-mlangeni/' }] },
  'susan-meiselas': { artistId: 'susan-meiselas', projectCoverage: '5 个纪实 / 回访 / 档案项目已完成第一轮 · 1972–现在', imageCoverage: '', note: '重点不是事件列表，而是摄影如何从初次拍摄走向声音、回访、电影、公共壁画与可持续档案。', projects: [
    { title: 'Carnival Strippers', cluster: 'women / labour / audio documentary', period: '1972–1975', summary: '跟随新英格兰巡回嘉年华脱衣舞表演者多个夏天，同时记录舞台、后台和她们自己的声音。', actions: ['长期跟随', '黑白摄影', '声音采访', '摄影书'], sourceUrl: 'https://www.moma.org/collection/works/177657', images: [img('https://www.worldphoto.org/sites/default/files/4%20%C2%A9%20Susan%20Meiselas%20_%20Magnum%20Photos.jpg', 'Carnival Strippers', '© Susan Meiselas / Magnum Photos', 'https://www.moma.org/collection/works/177657', 'MoMA / World Photography Organisation')], relations: [rel('出版', 'Carnival Strippers', '1976')] },
    { title: 'Nicaragua', cluster: 'revolution / color documentary', period: '1978–1979', summary: '在桑地诺革命期间持续拍摄，将街头政治、战斗和日常环境组成彩色纪实。', actions: ['战地摄影', '彩色胶片', '新闻发表', '摄影书'], sourceUrl: 'https://www.moma.org/collection/artists/45094', images: [], relations: [rel('出版', 'Nicaragua', '1981')] },
    { title: 'Pictures from a Revolution', cluster: 'return / film / subjects revisited', period: '1990–1991', summary: '带着十年前的照片返回 Nicaragua，寻找当年的被摄者，让他们重新解释照片和革命后的生活。', actions: ['携旧照片回访', '寻找被摄者', '电影访谈', '共同回看'], sourceUrl: 'https://www.moma.org/calendar/events/3225', images: [], relations: [rel('展览', 'film', '1991')] },
    { title: 'Kurdistan: In the Shadow of History', cluster: 'archive / oral history / displaced people', period: '1991–1997', summary: '搜集散落于家庭、机构和流亡社群中的照片与口述记忆，建立可持续扩充的库尔德历史档案。', actions: ['跨国档案搜集', '口述史', '历史与法医合作', '书 / 展览 / 在线档案'], sourceUrl: 'https://www.moma.org/collection/artists/45094', images: [], relations: [rel('出版', 'Kurdistan: In the Shadow of History', '1997')] },
    { title: 'Reframing documentary practice', cluster: 'archive / public return / image circulation', period: '2000s–', summary: '持续把旧作带回原址、制作公共壁画并研究经典新闻图片被不同政治力量重新使用的方式。', actions: ['社区回访', '原址壁画', '档案再编辑', '图像流通研究'], sourceUrl: 'https://www.moma.org/collection/artists/45094', images: [], relations: [rel('奖项', 'Deutsche Börse Photography Foundation Prize', 'winner 2019')] }
  ], awards: ['Deutsche Börse Photography Foundation Prize 2019'], exhibitions: ['MoMA collection exhibitions', 'The Photographers’ Gallery / Deutsche Börse 2019'], sources: [{ label: 'MoMA artist archive', url: 'https://www.moma.org/collection/artists/45094' }] }
};
