import type { Artist } from './data';
import { artistBatch168 } from './expansionBatch168';

export const artistBatch167: Artist[] = [
{id:'hito-steyerl',name:'Hito Steyerl',born:'1966',base:'Germany',intro:'德国艺术家、电影作者与理论写作者，以录像、影像装置和文本研究数字图像的生产、压缩、传播、监控与权力关系。',methods:['影像论文','研究型影像','挪用蒙太奇','媒介批判'],subjects:['数字图像','监控','战争与政治','图像流通','可见性'],outputs:['录像','影像装置','文本','数字图像'],institutions:['MoMA','Venice Biennale','documenta'],achievements:['German Pavilion, Venice Biennale 2015','documenta 12','MoMA collection'],whyImportant:'Steyerl把网络时代低清晰度、高流通性的“贫穷图像”、监控技术和全球资本主义变成影像艺术的核心问题，是当代艺术讨论数字图像政治最重要的节点之一。',projects:[{year:'2013',title:'How Not to Be Seen: A Fucking Didactic Educational .MOV File',type:'录像',facts:['MoMA收藏该作，并将Steyerl的方法概括为把纪录片、推测性虚构与第一人称叙事结合。','作品以荒诞教学片形式讨论高度可见和监控环境中的隐身问题。'],reading:'它把“如何消失”处理成数字时代的政治问题：图像既赋予可见性，也让身体进入机器识别和控制系统。'}],images:[],sourceLabel:'MoMA · Hito Steyerl',sourceUrl:'https://www.moma.org/artists/43752-hito-steyerl'},
{id:'trevor-paglen',name:'Trevor Paglen',born:'1974',base:'United States',intro:'美国艺术家与地理学者，以摄影、数据研究、人工智能、卫星与调查方法追踪通常不可见的军事基础设施、监控网络和机器视觉系统。',methods:['调查研究','远距离摄影','数据集研究','技术基础设施追踪'],subjects:['监控','军事秘密','人工智能','机器视觉','太空基础设施'],outputs:['摄影','录像','数据研究','装置'],institutions:['MoMA','Smithsonian American Art Museum'],achievements:['MoMA collection','New Order: Art and Technology in the Twenty-First Century, MoMA 2019'],whyImportant:'Paglen把摄影从记录人眼可见世界扩展到追踪秘密基地、轨道卫星和训练算法的数据集，使当代摄影直接面对机器如何观看人类的问题。',projects:[{year:'2017',title:'It Began as a Military Experiment',type:'十幅喷墨摄影',facts:['MoMA记录该作使用美国国防部1990年代用于开发人脸识别技术的数据库照片。','图像中的眼、鼻、嘴角标记显示人脸如何被转化为可供算法比较的数据。'],reading:'作品把普通肖像重新暴露为机器视觉的训练材料，让“被拍摄”与“被计算、识别和控制”发生重叠。'}],images:[],sourceLabel:'MoMA · Trevor Paglen',sourceUrl:'https://www.moma.org/artists/69988-trevor-paglen'},
{id:'taryn-simon',name:'Taryn Simon',born:'1975',base:'United States',intro:'美国跨学科艺术家，以摄影、文本、档案、分类和长期调查研究制度如何制造知识、证据、秘密与可见性。',methods:['系统调查','摄影与文本并置','档案分类','制度研究'],subjects:['证据','秘密系统','法律与权力','血缘','摄影真实性'],outputs:['摄影','文本','档案装置','出版'],institutions:['MoMA','MoMA PS1'],achievements:['The Innocents, MoMA PS1 2003','A Living Man Declared Dead and Other Chapters I–XVIII, MoMA 2012'],whyImportant:'Simon把摄影与文本、图表和系统研究置于同等位置，持续检验照片作为证据的可信度以及国家、法律和档案制度如何决定什么能够被看见和相信。',projects:[{year:'2008–2011',title:'A Living Man Declared Dead and Other Chapters I–XVIII',type:'摄影、文本与图形系统',facts:['MoMA记录Simon历时四年在全球调查并拍摄不同血缘及其相关故事。','每章由系统排列的血缘肖像、叙事文本和脚注图像构成。'],reading:'严格统一的视觉分类系统与战争、土地剥夺、法律身份等混乱现实形成张力，暴露制度分类并不等于事实本身。'}],images:[],sourceLabel:'MoMA · Taryn Simon — A Living Man Declared Dead',sourceUrl:'https://www.moma.org/explore/inside_out/2012/05/25/taryn-simon-a-living-man-declared-dead-and-other-chapters-i-xviii/'},
{id:'shirin-neshat',name:'Shirin Neshat',born:'1957',base:'Iran / United States',intro:'伊朗裔美国艺术家，以摄影、文字与多屏影像处理伊朗革命之后的性别、宗教、政治权力、流亡与文化身份。',methods:['导演式摄影','身体与文字叠加','双屏影像','象征性叙事'],subjects:['女性','伊朗','宗教','流亡','性别与权力'],outputs:['摄影','录像','电影','影像装置'],institutions:['MoMA','Venice Biennale'],achievements:['MoMA collection','International Award, Venice Biennale 1999'],whyImportant:'Neshat把女性身体、波斯文字、宗教符号与电影式空间组织结合起来，使伊朗女性身份与政治现代性进入全球当代摄影和影像艺术的重要讨论。',projects:[{year:'1993–1997',title:'Women of Allah',type:'摄影与书写',facts:['MoMA记录Neshat称该系列为自己艺术生涯的开端。','系列回应她1990年返回伊朗后面对革命后社会变化的经验，并把女性肖像、文字与武器等视觉元素并置。'],reading:'身体不是单纯身份肖像，而成为宗教、革命、性别规范与主体声音相互冲突的表面。'}],images:[],sourceLabel:'MoMA · Shirin Neshat',sourceUrl:'https://www.moma.org/artists/8349-shirin-neshat'},
{id:'alfredo-jaar',name:'Alfredo Jaar',born:'1956',base:'Chile / United States',intro:'智利艺术家、建筑师与电影作者，以摄影、文字、灯箱、建筑式装置和公共项目研究政治暴力、迁徙、种族灭绝以及媒体图像如何塑造观看伦理。',methods:['研究型装置','图像伦理批判','文本与摄影并置','公共介入'],subjects:['政治暴力','种族灭绝','迁徙','媒体再现','观看伦理'],outputs:['装置','摄影','电影','公共艺术','文本'],institutions:['MoMA'],achievements:['MoMA collection','Rwanda Project 1994–2000'],whyImportant:'Jaar的重要性在于不把灾难摄影简单等同于揭露真相，而持续设计观看的延迟、缺席和遮蔽机制，迫使观众思考谁有权展示痛苦以及图像何时会失效。',projects:[{year:'1994–2000',title:'The Rwanda Project',type:'摄影、文本与装置系列',facts:['MoMA记录Jaar在1994年卢旺达种族灭绝后赴当地，并在随后六年持续发展Rwanda Project。','早期作品Rwanda, Rwanda以公共背光广告位反复呈现“Rwanda”文字，而非直接展示暴力尸体图像。'],reading:'对灾难图像的克制并非回避事件，而是质疑媒体饱和如何让观看者对他人的痛苦失去反应。'}],images:[],sourceLabel:'MoMA · Alfredo Jaar',sourceUrl:'https://www.moma.org/artists/7477-alfredo-jaar'},
...artistBatch168
];