import type { Artist } from './data';
import { artistBatch150 } from './expansionBatch150';

export const artistBatch149: Artist[] = [
{id:'wolfgang-tillmans',name:'Wolfgang Tillmans',born:'1968',base:'Germany / United Kingdom',intro:'德国摄影艺术家，以日常生活、青年文化、身体、性别与政治为主题，同时持续实验摄影展示、无相机暗房抽象和印刷图像，使摄影从单张作品扩展为可变的空间编排。',methods:['日常观察','非等级化图像编排','暗房实验','展览空间编辑'],subjects:['青年文化','身体与性别','亲密关系','政治','图像传播'],outputs:['摄影','无相机摄影','装置','出版物','影像'],institutions:['MoMA','MoMA PS1','Tate'],achievements:['Turner Prize 2000','Wolfgang Tillmans: To look without fear, MoMA 2022–23','Freedom from the Known, MoMA PS1 2006'],whyImportant:'Tillmans打破新闻、时尚、私人快照与抽象摄影之间的等级，并把墙面安装本身发展成摄影意义生成机制，是1990年代以来当代摄影最关键的节点之一。',projects:[{year:'2005–',title:'Truth Study Center',type:'摄影 / 印刷材料 / 桌面装置',facts:['项目组合新闻文章、摄影和印刷材料，围绕当代意识形态冲突中的争议真相展开。','MoMA资料将其与Tillmans同时期对模拟暗房和无相机摄影的实验联系起来。'],reading:'作品把摄影从单纯制造图像转向比较图像、文字与公共信息如何共同塑造“真实”。'}],images:[],sourceLabel:'MoMA · Wolfgang Tillmans',sourceUrl:'https://www.moma.org/artists/8044-wolfgang-tillmans'},
{id:'rineke-dijkstra',name:'Rineke Dijkstra',born:'1959',base:'Netherlands',intro:'荷兰摄影与影像艺术家，以大画幅正面肖像持续观察青少年、产妇、士兵、难民等处于身份转换阶段的人物，通过克制背景和连续拍摄研究身体姿态、脆弱性与自我形成。',methods:['大画幅正面肖像','长期追踪','序列摄影','身份转变观察'],subjects:['青春期','身份形成','迁徙','母职','身体姿态'],outputs:['摄影','影像装置','肖像系列'],institutions:['MoMA','Guggenheim','Tate'],achievements:['MoMA collection','Hasselblad Award 2017'],whyImportant:'Dijkstra把看似传统的正面肖像变成研究身份尚未稳定时刻的方法，并通过跨年重复拍摄把时间本身纳入肖像，是当代类型学与人物摄影的重要参照。',projects:[{year:'1994–',title:'Almerisa',type:'长期肖像系列',facts:['MoMA收藏系列中1994、1996、1998等多个阶段的Almerisa肖像。','最早影像标注拍摄于荷兰Leiden的庇护中心。'],reading:'重复的正面结构让服装、姿态、身体和环境变化成为时间证据，使迁徙经验通过一个人的成长而不是新闻事件显现。'}],images:[],sourceLabel:'MoMA · Rineke Dijkstra',sourceUrl:'https://www.moma.org/artists/8139-rineke-dijkstra'},
{id:'thomas-ruff',name:'Thomas Ruff',born:'1958',base:'Germany',intro:'德国摄影艺术家、杜塞尔多夫摄影学派重要人物，从冷静的大尺幅肖像扩展到夜视、建筑、网络色情、JPEG压缩图像和天文影像，持续追问摄影真实性及技术系统如何塑造可见世界。',methods:['类型学','图像再利用','数字处理','技术图像研究'],subjects:['肖像','监视技术','互联网图像','建筑','摄影真实性'],outputs:['摄影','数字图像','档案再加工'],institutions:['MoMA','Tate'],achievements:['MoMA collection','New Order: Art and Technology in the Twenty-First Century, MoMA 2019'],whyImportant:'Ruff把摄影对象从现实世界推进到既有图像和成像技术本身，使“照片是否仍然指向真实”成为作品主题，是数字时代摄影观念转向的重要人物。',projects:[{year:'1992',title:'Nacht',type:'摄影系列',facts:['MoMA收藏Nacht 2 I。','系列使用与夜视和军事监控相关的绿色低照度视觉语言。'],reading:'技术不是中性的透明窗口；当成像系统改变，可见世界的意义和权力关系也随之改变。'}],images:[],sourceLabel:'MoMA · Thomas Ruff',sourceUrl:'https://www.moma.org/artists/6982-thomas-ruff'},
{id:'carrie-mae-weems',name:'Carrie Mae Weems',born:'1953',base:'United States',intro:'美国艺术家，以摄影、文字、影像、行为、装置和社会实践研究黑人历史、女性主体、家庭、观看权力与档案暴力，经常让自身成为见证历史的角色。',methods:['自我编排','档案挪用','文字-摄影组合','历史重构'],subjects:['黑人历史','女性主体','家庭','种族化观看','记忆'],outputs:['摄影','文字','影像','装置','行为'],institutions:['MoMA','Guggenheim'],achievements:['MacArthur Fellowship 2013','Hasselblad Award 2023','MoMA collection'],whyImportant:'Weems把私人家庭空间、博物馆档案与种族化视觉史连接起来，既质疑谁有权观看和命名，也让黑人女性从被摄影的对象转变为图像叙事的作者与历史见证者。',projects:[{year:'1990',title:'Kitchen Table Series',type:'摄影 / 文字系列',facts:['系列由20幅银盐照片和14块带文字的丝网印刷面板组成。','艺术家在固定餐桌场景中扮演主人公，与朋友、孩子、恋人和不同道具共同构成连续叙事。'],reading:'重复的家庭舞台把亲密关系、性别学习和黑人女性主体性组织成一种介于自传、戏剧和社会研究之间的摄影方法。'}],images:[],sourceLabel:'MoMA · Carrie Mae Weems',sourceUrl:'https://www.moma.org/artists/7177-carrie-mae-weems'},
...artistBatch150
];