import type { Artist } from './data';

export const artistBatch53: Artist[] = [
  { id:'hito-steyerl', name:'Hito Steyerl', born:'1966', base:'Germany', intro:'德国艺术家、电影作者与理论写作者，以影像装置、纪录片策略和网络图像研究讨论数字传播、战争、金融、监控与机器视觉。', methods:['影像论文','纪录片与虚构混合','挪用图像','数字媒介批判'], subjects:['网络图像','战争','监控','金融','机器视觉'], outputs:['录像','多屏影像装置','文本'], institutions:['MoMA','La Biennale di Venezia','documenta'], achievements:['2015 威尼斯双年展德国馆参展','documenta 12 参展'], whyImportant:'她把图像的分辨率、复制和传播本身变成政治问题，是理解后互联网影像、poor image 与机器观看的核心艺术家。', projects:[{year:'2013',title:'How Not to Be Seen: A Fucking Didactic Educational .MOV File',type:'录像',facts:['以教学录像形式讽刺高度可见与监控社会。','MoMA 收藏。'],reading:'作品把“不可见”从隐私问题转化为数字图像制度中的政治策略。'}], images:[], sourceLabel:'MoMA · Hito Steyerl', sourceUrl:'https://www.moma.org/artists/43752-hito-steyerl' },
  { id:'carrie-mae-weems', name:'Carrie Mae Weems', born:'1953', base:'United States', intro:'美国艺术家，以摄影、文字、录像、表演与装置持续研究黑人历史、女性主体、家庭空间、档案与观看权力。', methods:['编排摄影','文本与图像','档案再语境化','自我表演'], subjects:['黑人历史','女性主体','家庭','种族化观看','记忆'], outputs:['摄影','录像','装置','表演'], institutions:['MoMA','Guggenheim Museum','Whitney Museum of American Art'], achievements:['MacArthur Fellow 2013','长期进入美国重要摄影与当代艺术机构收藏展览'], whyImportant:'她把私人家庭场景与历史档案并置，使摄影中的观看权、种族与性别成为可以被重新书写的结构。', projects:[{year:'1990',title:'Kitchen Table Series',type:'摄影与文本系列',facts:['由20幅银盐照片与文本构成。','艺术家本人在固定餐桌场景中扮演核心人物。'],reading:'固定桌面成为讨论黑人女性主体、亲密关系与角色表演的舞台。'}], images:[], sourceLabel:'MoMA · Carrie Mae Weems', sourceUrl:'https://www.moma.org/artists/7177-carrie-mae-weems' },
  { id:'rineke-dijkstra', name:'Rineke Dijkstra', born:'1959', base:'Netherlands', intro:'荷兰摄影与录像艺术家，以正面、克制的大画幅肖像长期观察青春期、迁徙、母职、军旅等身份转变时刻。', methods:['大画幅肖像','长期追踪','正面凝视','系列比较'], subjects:['青春期','身份转变','迁徙','身体','成长'], outputs:['摄影','录像'], institutions:['MoMA','Guggenheim Museum','Stedelijk Museum Amsterdam'], achievements:['2017 Hasselblad Award'], whyImportant:'她证明类型化、近乎中性的拍摄结构仍能保留个体差异，并把“变化中的身份”转化为可跨时间比较的摄影方法。', projects:[{year:'1994–2008',title:'Almerisa',type:'长期肖像系列',facts:['持续拍摄一位从波斯尼亚来到荷兰的年轻女性。','MoMA 收藏该系列多件作品。'],reading:'相同作者与相近观看方式让迁徙、年龄和社会身份的变化直接显现在时间序列中。'}], images:[], sourceLabel:'MoMA · Rineke Dijkstra', sourceUrl:'https://www.moma.org/artists/8139-rineke-dijkstra' },
  { id:'wolfgang-tillmans', name:'Wolfgang Tillmans', born:'1968', base:'Germany / United Kingdom', intro:'德国摄影艺术家，以朋友、夜生活、静物、政治材料、无相机抽象摄影和非等级化墙面编排持续扩张摄影的展示边界。', methods:['非等级化编辑','墙面编排','亲密摄影','暗房实验','出版与挪用'], subjects:['亲密关系','青年文化','酷儿生活','政治','摄影物质性'], outputs:['摄影','装置','出版物','音乐'], institutions:['MoMA','Tate','MoMA PS1'], achievements:['Turner Prize 2000','MoMA 2022–2023 大型回顾展 To look without fear'], whyImportant:'他把单张照片的意义转移到图像之间的关系、尺寸、纸张和墙面节奏，对当代摄影展览编排影响极大。', projects:[{year:'2005–',title:'Truth Study Center',type:'桌面 / 墙面图像与文本装置',facts:['组合新闻材料、摄影和文本讨论相互竞争的真相。'],reading:'摄影不再只是作品单位，而成为与新闻、政治文本和展示空间共同工作的图像节点。'}], images:[], sourceLabel:'MoMA · Wolfgang Tillmans', sourceUrl:'https://www.moma.org/artists/8044-wolfgang-tillmans' },
  { id:'santu-mofokeng', name:'Santu Mofokeng', born:'1956–2020', base:'South Africa', intro:'南非摄影家，以长期黑白摄影研究城镇生活、劳动、精神性、土地与种族隔离及其遗产，并持续反思纪实摄影自身的观看方式。', methods:['长期纪实','摄影档案研究','地景摄影','反类型化观察'], subjects:['种族隔离','黑人日常','土地','精神性','历史记忆'], outputs:['摄影','摄影书','档案项目'], institutions:['The Art Institute of Chicago','Tate','Walther Collection'], achievements:['南非重要社会纪实与观念摄影代表人物'], whyImportant:'他没有把南非黑人生活压缩为新闻式苦难图像，而把日常、精神经验、地景和历史暴力放进更复杂的视觉结构。', projects:[{year:'1988–',title:'Black Photo Album / Look at Me: 1890–1950',type:'档案摄影研究',facts:['以历史家庭肖像档案研究南非黑人中产阶级自我表述。'],reading:'项目把匿名历史照片重新视为主动塑造身份的私人图像，而不是殖民档案中的被动对象。'}], images:[], sourceLabel:'Art Institute of Chicago · Santu Mofokeng', sourceUrl:'https://www.artic.edu/artworks/263921/boitumelong-township-bloemhof' },
  { id:'zanele-muholi', name:'Zanele Muholi', born:'1972', base:'South Africa', intro:'南非视觉活动家与摄影艺术家，以肖像、自画像和长期社群档案记录并庆祝黑人 LGBTQIA+ 群体，同时研究种族、性别、自我表述与摄影权力。', methods:['长期肖像档案','自画像','视觉行动主义','社群合作'], subjects:['黑人酷儿身份','性别','种族','自我表述','社群'], outputs:['摄影','录像','雕塑'], institutions:['Tate Modern','Guggenheim Museum','Stedelijk Museum Amsterdam'], achievements:['Tate Modern 2020/2024 大型个展','ICP Infinity Award 2016'], whyImportant:'Muholi 把摄影档案建设与行动主义直接结合，使被忽视社群不只是被摄影，而成为主动定义自身形象的主体。', projects:[{year:'2012–',title:'Somnyama Ngonyama',type:'自画像系列',facts:['以高反差黑白自画像和日常物件构造不同角色。','系列进入 Tate Modern 大型展览脉络。'],reading:'自画像同时回应黑人身体被观看的历史，并通过作者主动控制姿态、光线与道具夺回图像生产权。'}], images:[], sourceLabel:'Tate · Zanele Muholi exhibition', sourceUrl:'https://www.tate.org.uk/whats-on/tate-modern/zanele-muholi' },
  { id:'taryn-simon', name:'Taryn Simon', born:'1975', base:'United States', intro:'美国跨媒介艺术家，以高度系统化的摄影、文本、档案、录像与装置研究隐藏制度、分类系统、血缘、国家权力以及图像与证据之间的关系。', methods:['调查研究','摄影与文本','档案分类','制度系统可视化'], subjects:['国家权力','隐形系统','分类','血缘','证据'], outputs:['摄影','文本','录像','雕塑','装置'], institutions:['Guggenheim Museum','MoMA','Tate Modern'], achievements:['2026–2027 Guggenheim New York Rotunda 大型个展 Father Country I Do Love You'], whyImportant:'她把摄影项目做成近似数据库和调查系统，迫使观众同时阅读图像、文字与缺失信息，是研究“摄影作为知识制度”的关键节点。', projects:[{year:'2007',title:'An American Index of the Hidden and Unfamiliar',type:'摄影与文本调查',facts:['系统拍摄通常无法被公众进入或观看的美国地点、对象和制度。'],reading:'核心不是猎奇地展示秘密，而是让“谁有权看见什么”成为摄影项目自身的结构。'}], images:[], sourceLabel:'Guggenheim · Taryn Simon', sourceUrl:'https://www.guggenheim.org/exhibition/taryn-simon-father-country-i-do-love-you' }
];
