import type { Artist } from './data';
import { artistBatch105 } from './expansionBatch105';

export const artistBatch104: Artist[] = [
{id:'walid-raad',name:'Walid Raad',born:'1967',base:'Lebanon / United States',intro:'黎巴嫩出生的跨媒介艺术家，以摄影、录像、装置、表演与虚构档案研究黎巴嫩内战、历史书写、创伤记忆以及艺术制度如何生产事实。',methods:['虚构档案','伪文献建构','摄影与录像研究','讲演式表演'],subjects:['黎巴嫩内战','历史与记忆','创伤','文献真实性','艺术制度'],outputs:['摄影','录像','装置','表演','档案项目'],institutions:['MoMA','Whitney Museum of American Art'],achievements:['The Atlas Group','The Dead Weight of a Quarrel Hangs','Sweet Talk: Commissions (Beirut)','Whitney Biennial 2000','Whitney Biennial 2002'],whyImportant:'Raad把档案从历史证据转化为可被制造、表演和怀疑的结构，是当代艺术中讨论战争记忆、摄影真实性与虚构文献的关键人物。',projects:[{year:'1989–2004',title:'The Atlas Group',type:'虚构档案 / 摄影 / 录像 / 文本',facts:['以虚构研究组织的形式处理黎巴嫩当代史与内战记忆。','项目混合摄影、录像、文本、虚构人物与档案式展示。'],reading:'作品并不简单再现战争，而是追问战争如何被照片、档案、机构和叙述塑造成可以相信的历史。'},{year:'1999',title:'The Dead Weight of a Quarrel Hangs',type:'录像',facts:['作品进入Whitney Museum收藏。'],reading:'通过不稳定的文献逻辑，让影像证据本身成为被审视的对象。'}],images:[],sourceLabel:'Whitney · Walid Raad',sourceUrl:'https://whitney.org/artists/7881'},
{id:'akram-zaatari',name:'Akram Zaatari',born:'1966',base:'Lebanon',intro:'黎巴嫩艺术家、摄影家与影像研究者，通过摄影、录像、装置和档案研究图像生产、欲望、战争、监控、记忆及中东摄影史；1997年参与创立Arab Image Foundation。',methods:['档案研究','图像再语境化','摄影史研究','影像考古'],subjects:['摄影档案','战争与记忆','欲望','监控','中东图像史'],outputs:['摄影','录像','电影','装置','档案项目'],institutions:['MoMA','Centre Pompidou','Arab Image Foundation'],achievements:['Projects 100: Akram Zaatari','Objects of Study: The archive of studio Shehrazade','Letter to a Refusing Pilot'],whyImportant:'Zaatari把保存旧照片的档案工作转化为艺术方法，使摄影史、私人欲望、战争记忆和图像流通机制能够在同一结构中被重新阅读。',projects:[{year:'2006',title:'Objects of Study: The archive of studio Shehrazade',type:'摄影档案 / 装置',facts:['围绕赛达摄影师Hashem el Madani的Studio Shehrazade档案展开。','Centre Pompidou馆藏记录将其与1950至1970年代照相馆实践联系。'],reading:'私人照相馆的姿势、背景和道具成为研究社会习俗、身份表演与摄影制度的入口。'},{year:'2013',title:'Projects 100: Akram Zaatari',type:'博物馆个展',facts:['MoMA于2013年举办Projects 100专题展。'],reading:'其工作把发现、保存和重新展示图像视为同一套艺术实践。'}],images:[],sourceLabel:'MoMA · Akram Zaatari',sourceUrl:'https://www.moma.org/calendar/exhibitions/1278'},
{id:'dinh-q-le',name:'Dinh Q. Lê',born:'1968–2024',base:'Vietnam / United States',intro:'越南裔美国艺术家，以切割编织摄影、录像与装置把个人记忆、家庭经验、电影图像和越南战争的公共视觉历史交织在一起。',methods:['摄影编织','图像拼接','口述史','个人记忆与公共影像并置'],subjects:['越南战争','记忆','流散','电影再现','历史叙事'],outputs:['摄影','编织影像','录像','装置'],institutions:['MoMA','MoMA PS1'],achievements:['The Farmers and The Helicopters','Projects 93: Dinh Q. Lê','Untitled (Soldiers at Rest)'],whyImportant:'Lê把照片真正切开并重新编织，使相互冲突的私人记忆、新闻影像与好莱坞战争视觉无法被分开观看，是越南战争记忆与摄影物质性研究的重要艺术家。',projects:[{year:'2003',title:'Untitled (Soldiers at Rest)',type:'切割编织摄影',facts:['作品由切割并编织的彩色照片和亚麻胶带构成。','作品进入MoMA收藏。'],reading:'图像的物理交织对应记忆之间无法彻底分离的关系。'},{year:'2006',title:'The Farmers and The Helicopters',type:'三频道录像 / 装置',facts:['作品包含三频道录像与由农民Le Van Danh和自学机械师Tran Quoc Hai用废旧零件制作的直升机。','2010年在MoMA Projects 93展出。'],reading:'战争机器的历史形象与越南人的现实记忆、制造知识和日常经验发生碰撞。'}],images:[],sourceLabel:'MoMA · Dinh Q. Lê',sourceUrl:'https://www.moma.org/artists/26740-dinh-q-le'},
{id:'ho-tzu-nyen',name:'Ho Tzu Nyen',born:'1976',base:'Singapore',intro:'新加坡艺术家，以多频道影像、装置、动画、声音与研究型叙事重新组织东南亚历史、殖民知识、民族国家、电影史和幽灵般的历史人物。',methods:['研究型影像','多频道叙事','历史蒙太奇','推测性历史'],subjects:['东南亚历史','殖民主义','帝国','民族主义','电影史','历史幽灵'],outputs:['录像','多频道装置','电影','声音','讲演'],institutions:['MoMA'],achievements:['Hotel Aporia'],whyImportant:'Ho把历史研究转化为复杂的时间影像系统，不把东南亚历史处理成稳定事实，而是让档案、电影、神话和推测互相干扰。',projects:[{year:'2019',title:'Hotel Aporia',type:'六频道录像装置',facts:['最初为Aichi Triennale委托，在日本丰田市大正时期旅馆建筑Kirakutei展出。','作品涉及神风特攻队、京都学派、横山隆一、小津安二郎以及日本帝国时期文化生产。','MoMA于2024年呈现其电影版本。'],reading:'作品利用建筑、电影片段与书信式叙事，把帝国、民族主义和文化生产之间的历史纠葛变成循环观看结构。'}],images:[],sourceLabel:'MoMA · Ho Tzu Nyen',sourceUrl:'https://www.moma.org/calendar/events/10136'},
{id:'bouchra-khalili',name:'Bouchra Khalili',born:'1975',base:'Morocco / France',intro:'摩洛哥裔法国艺术家，以录像、摄影、地图、档案和口述叙事研究迁徙、无国籍状态、殖民历史、公民身份以及被官方历史排除者如何讲述自身。',methods:['口述史','地图叙事','档案研究','第一人称影像'],subjects:['迁徙','边界','公民身份','殖民历史','流散','政治主体性'],outputs:['录像','摄影','装置','地图','文本'],institutions:['Guggenheim'],achievements:['Hugo Boss Prize 2018 nominee'],whyImportant:'Khalili让迁徙者与边缘政治主体成为叙事者而非被观察对象，把地图、声音和影像转化为重新争取历史发言权的工具。',projects:[{year:'2018',title:'Hugo Boss Prize nomination',type:'机构网络',facts:['Khalili是Guggenheim Hugo Boss Prize 2018六位提名艺术家之一。'],reading:'这一机构节点体现其关于迁徙、政治主体和历史叙事的影像实践进入国际当代艺术核心网络。'}],images:[],sourceLabel:'Guggenheim · Bouchra Khalili',sourceUrl:'https://www.guggenheim.org/video/hugo-boss-prize-2018-nominee-bouchra-khalili'},
...artistBatch105
];