import type { Artist } from './data';
import { artistBatch137 } from './expansionBatch137';

export const artistBatch136: Artist[] = [
{id:'carrie-mae-weems',name:'Carrie Mae Weems',born:'1953',base:'USA',intro:'美国艺术家，以摄影、文字、影像、表演、装置与社会实践持续研究黑人历史、家庭、权力、性别与谁有资格进入历史图像。',methods:['摄影与文本','自我表演','档案再语境化','社会实践'],subjects:['黑人历史','家庭','种族','性别','权力','历史记忆'],outputs:['摄影','文本','影像','表演','装置'],institutions:['MoMA'],achievements:['From Here I Saw What Happened and I Cried','Kitchen Table Series'],whyImportant:'Weems把摄影从记录工具变成对历史观看制度的批判装置，并以自身身体进入图像，重新安排黑人女性作为观看者与叙述者的位置。',projects:[{year:'1995–96',title:'From Here I Saw What Happened and I Cried',type:'摄影 / 文本 / 档案',facts:['MoMA收藏该系列多件作品，并于2020–21围绕该系列举办展示。','作品通过历史图像与覆盖其上的文字重新审视种族化观看。'],reading:'关键不是简单重现档案，而是让旧图像的权力关系在新的文字和展示结构中重新变得可见。'}],images:[],sourceLabel:'MoMA · Carrie Mae Weems',sourceUrl:'https://www.moma.org/artists/7177-carrie-mae-weems'},
{id:'thomas-ruff',name:'Thomas Ruff',born:'1958',base:'Germany',intro:'德国摄影艺术家，从大幅肖像扩展到夜视、建筑、天文图像、互联网色情图像与数字生成图像，持续检验摄影在不同技术系统中的真实性。',methods:['类型学摄影','图像再处理','数字图像研究','技术媒介实验'],subjects:['摄影真实性','互联网','监控技术','建筑','天文图像'],outputs:['摄影','数字图像','印刷'],institutions:['MoMA'],achievements:['Portraits','Nacht','nudes'],whyImportant:'Ruff的重要性在于他没有固定一种摄影风格，而是不断更换成像技术和既有图像来源，把摄影本身作为技术制度来研究。',projects:[{year:'1980s–',title:'Photographic series across image technologies',type:'摄影 / 数字图像',facts:['MoMA收藏其Portrait、Nacht、nudes等系列作品。','MoMA 2019 New Order展亦将其放入21世纪艺术与技术关系中。'],reading:'不同系列共同追问的不是一个题材，而是机器、分辨率、来源和传播方式怎样改变我们对照片真实性的判断。'}],images:[],sourceLabel:'MoMA · Thomas Ruff',sourceUrl:'https://www.moma.org/artists/6982-thomas-ruff'},
{id:'thomas-demand',name:'Thomas Demand',born:'1964',base:'Germany',intro:'德国艺术家，以媒体中的既有照片为起点，用纸和纸板制作等比例场景模型，拍摄后销毁模型，在雕塑、摄影与新闻图像之间制造多重距离。',methods:['场景重建','纸模型','再摄影','媒体图像转译'],subjects:['新闻事件','政治','记忆','真实性','建筑空间'],outputs:['摄影','纸模型','影像'],institutions:['MoMA','MoMA PS1'],achievements:['Thomas Demand — MoMA 2005','Room','Kitchen'],whyImportant:'Demand把“摄影记录现实”的直觉彻底反转：照片记录的是根据另一张照片制造的模型，因此现实、媒体记忆和人工构造彼此套叠。',projects:[{year:'1993–',title:'Life-size paper reconstructions for photography',type:'模型 / 摄影',facts:['MoMA记录Demand自1993年起专门为摄影制作纸和纸板模型。','其起点通常是媒体中与政治事件相关的既有图像，完成摄影后模型不作为最终作品保留。'],reading:'最终照片看似普通空间，却与原事件隔着媒体图像、手工模型和再次摄影三层转换。'}],images:[],sourceLabel:'MoMA · Thomas Demand',sourceUrl:'https://www.moma.org/calendar/exhibitions/116'},
{id:'wangechi-mutu',name:'Wangechi Mutu',born:'1972',base:'Kenya / USA',intro:'肯尼亚裔美国艺术家，以拼贴、雕塑、影像与表演重组女性身体、植物、动物、时尚和民族志图像，构造后殖民与非洲未来主义的混合身体。',methods:['拼贴','图像挪用','混合身体建构','神话重写'],subjects:['黑人女性','殖民凝视','迁徙','身体','非洲未来主义','生态'],outputs:['拼贴','绘画','雕塑','影像','表演'],institutions:['MoMA'],achievements:['Yo Mama','One Hundred Lavish Months of Bushwhack'],whyImportant:'Mutu把西方媒体、民族志、色情和时尚中的女性形象拆开重组，使被刻板化的黑人女性身体成为能够主动生成神话与未来世界的主体。',projects:[{year:'2003',title:'Yo Mama',type:'拼贴 / 绘画',facts:['MoMA收藏Yo Mama，并指出作品向尼日利亚女性主义者Funmilayo Anikulapo-Kuti致敬。','Mutu使用墨、云母、丙烯、印刷纸与其他材料构成混合女性形象。'],reading:'拼贴不是装饰效果，而是一种拆解既有视觉分类、重新赋予身体能动性的政治方法。'}],images:[],sourceLabel:'MoMA · Wangechi Mutu',sourceUrl:'https://www.moma.org/collection/artists/28097'},
...artistBatch137
];