import type { Artist } from './data';
import { artistBatch134 } from './expansionBatch134';

export const artistBatch133: Artist[] = [
...artistBatch134,
{id:'dayanita-singh',name:'Dayanita Singh',born:'1961',base:'India',intro:'印度艺术家，以摄影为原材料，把照片、档案、书籍和可移动木制结构重新组织为不断变化的“博物馆”。',methods:['摄影编辑','档案重组','模块化展示','艺术家书'],subjects:['档案','家庭与社会空间','摄影制度','记忆','偶然性'],outputs:['摄影','装置','艺术家书','木制展示结构'],institutions:['MoMA'],achievements:['Museum of Chance','Museum Bhavan','Surrounds: 11 Installations — MoMA 2019'],whyImportant:'Singh把摄影从单张图像推进到编辑、排序、储存和展示系统，使“照片如何被组织”本身成为作品。',projects:[{year:'2013',title:'Museum of Chance',type:'摄影 / 模块化博物馆',facts:['MoMA记录作品由162幅喷墨照片与柚木结构组成。','铰接木制结构同时承担展示、档案和储存功能，照片可持续重新排列。'],reading:'作品把摄影展览从固定墙面解放出来，使编辑与重新编排成为持续发生的创作行为。'}],images:[],sourceLabel:'MoMA · Dayanita Singh',sourceUrl:'https://www.moma.org/artists/48057-dayanita-singh'},
{id:'ming-smith',name:'Ming Smith',born:'',base:'USA',intro:'美国摄影艺术家，以长曝光、运动模糊、深黑影调和手工介入表现黑人日常生活、爵士文化与城市经验。',methods:['长曝光','直觉摄影','运动模糊','手工着色'],subjects:['黑人生活','爵士','城市','可见性','记忆'],outputs:['摄影','手工着色摄影'],institutions:['MoMA','Kamoinge Workshop'],achievements:['Projects: Ming Smith — MoMA 2023','Invisible Man, Somewhere, Everywhere'],whyImportant:'Smith以模糊、阴影和身体运动拒绝摄影的清晰说明性，把黑人经验转化为具有音乐节奏和心理强度的视觉语言。',projects:[{year:'1991–1998',title:'Invisible Man, Somewhere, Everywhere',type:'摄影 / 文学回应',facts:['MoMA收藏该系列多个版本，作品回应Ralph Ellison的《Invisible Man》。','MoMA指出Smith的实践持续处理黑人经验中的可见与不可见。'],reading:'模糊的人物与黑暗空间把社会性的“不可见”转化为摄影形式，而不是把人物变成说明性的社会学对象。'}],images:[],sourceLabel:'MoMA · Ming Smith',sourceUrl:'https://www.moma.org/collection/artists/7906'},
{id:'santu-mofokeng',name:'Santu Mofokeng',born:'1956–2020',base:'South Africa',intro:'南非摄影家，以黑人日常生活、宗教、土地、历史档案与种族隔离后的景观为核心，发展出区别于传统新闻摄影的反思性纪实语言。',methods:['长期纪实','档案再摄影','社会景观','摄影序列'],subjects:['种族隔离','黑人日常生活','宗教','土地','历史记忆'],outputs:['摄影','幻灯投影','档案装置'],institutions:['MoMA','MoMA PS1','Art Institute of Chicago'],achievements:['Train Church','The Black Photo Album / Look at Me: 1890–1950','The Short Century — MoMA PS1 2002'],whyImportant:'Mofokeng把南非摄影从政治事件的即时见证扩展到精神生活、家庭影像和历史记忆，成为后种族隔离摄影的重要方法节点。',projects:[{year:'1997',title:'The Black Photo Album / Look at Me: 1890–1950',type:'档案摄影 / 幻灯投影',facts:['MoMA收藏该作品，形式为80张35毫米黑白幻灯片构成的投影。','作品通过历史黑人家庭肖像重新讨论自我呈现、阶级和殖民视觉制度。'],reading:'艺术家不重新拍摄历史，而重新组织既有私人照片，让被殖民视觉史忽略的黑人自我形象重新进入公共叙事。'}],images:[],sourceLabel:'MoMA · Santu Mofokeng',sourceUrl:'https://www.moma.org/artists/72440-santu-mofokeng'},
{id:'anouk-kruithof',name:'Anouk Kruithof',born:'1981',base:'Netherlands / International',intro:'荷兰艺术家，以摄影、图像档案、互联网图像、书籍和雕塑装置研究数字时代图像的过量生产、循环与物质性。',methods:['图像再编辑','互联网图像研究','摄影雕塑','艺术家书'],subjects:['图像过载','数字文化','传播','记忆','摄影物质性'],outputs:['摄影','装置','雕塑','艺术家书'],institutions:['Aperture'],achievements:['A Head with Wings','Paris Photo–Aperture Foundation PhotoBook Awards shortlist 2012'],whyImportant:'Kruithof代表摄影从“拍摄世界”转向处理已经存在的海量图像：选择、复制、重组和物质化成为摄影方法。',projects:[{year:'2012',title:'A Head with Wings',type:'艺术家书 / 摄影编辑',facts:['Aperture记录该书进入Paris Photo–Aperture Foundation First PhotoBook shortlist。','作品体现她把摄影书作为图像排序和材料实验空间的实践。'],reading:'摄影意义不只来自快门瞬间，也来自后续编辑、出版和物质结构。'}],images:[],sourceLabel:'Aperture · Anouk Kruithof',sourceUrl:'https://issues.aperture.org/article/2013/1/1/anouk-kruithof'},
{id:'zarina-hashmi',name:'Zarina',born:'1937–2020',base:'India / USA',intro:'印度出生、长期生活于纽约的艺术家，以版画、纸张、雕塑与极简几何处理家、边界、流亡、语言和印巴分治留下的记忆。',methods:['极简形式','版画','地图重构','文字与几何'],subjects:['家','流亡','边界','分治','记忆'],outputs:['木刻','版画','纸上作品','雕塑'],institutions:['Guggenheim','La Biennale di Venezia','Art Institute of Chicago'],achievements:['India Pavilion — Venice Biennale 2011','Zarina: Paper Like Skin'],whyImportant:'Zarina把极简主义的抽象形式与迁徙、分治和私人记忆连接，使地图、房屋平面和纸张成为离散经验的情感结构。',projects:[{year:'2015',title:'Rohingyas: Floating on the Dark Sea',type:'木刻 / 迁徙与边界',facts:['Tate记录该作品为2015年木刻，描绘空船并指向罗兴亚人的流亡处境。','Tate资料同时记录她2011年代表印度参加威尼斯双年展，并在Guggenheim等机构举办回顾展。'],reading:'极简的船形没有新闻图像的事件细节，却把迁徙、无国籍与孤立压缩为高度凝练的视觉符号。'}],images:[],sourceLabel:'Tate · Zarina',sourceUrl:'https://shop.tate.org.uk/zarina-hashmi-rohingyas-floating-on-the-dark-sea-edition-number-32-2015/50130.html'}
];