import type { Artist } from './data';
import { artistBatch181 } from './expansionBatch181';

export const artistBatch180: Artist[] = [
{id:'hito-steyerl',name:'Hito Steyerl',born:'1966',base:'Germany',intro:'德国艺术家、电影作者与理论写作者，以影像装置和论文电影研究数字图像流通、战争、监控、人工智能、全球资本与网络视觉文化。',methods:['论文电影','研究型影像','挪用图像','第一人称叙事'],subjects:['数字图像','战争','监控','网络文化','全球化','人工智能'],outputs:['录像','影像装置','文本','摄影'],institutions:['MoMA','La Biennale di Venezia','documenta'],achievements:['German Pavilion, 56th Venice Biennale 2015','documenta 12','MoMA collection'],whyImportant:'Steyerl把图像的压缩、复制、传播和算法化本身变成艺术对象，是理解后互联网图像政治、论文电影与当代影像理论的核心人物。',projects:[{year:'2004',title:'November',type:'论文电影',facts:['混合私人影像、库尔德电视素材、电影片段与第一人称旁白，追踪Andrea Wolf的图像如何从私人记忆进入政治传播。'],reading:'作品研究图像如何在革命、媒体与个人记忆之间改变意义。'},{year:'2013',title:'How Not to Be Seen: A Fucking Didactic Educational .MOV File',type:'影像装置',facts:['以教学片形式讽刺数字可见性、分辨率、监控与消失。'],reading:'在全面图像化社会中，不可见本身成为政治问题。'}],images:[],sourceLabel:'MoMA · Hito Steyerl',sourceUrl:'https://www.moma.org/artists/43752-hito-steyerl'},
{id:'alfredo-jaar',name:'Alfredo Jaar',born:'1956',base:'Chile / United States',intro:'智利裔艺术家，以摄影、装置、电影和公共项目处理种族灭绝、迁徙、政治暴力、媒体失语以及观看他人苦难的伦理。',methods:['研究型装置','摄影再语境化','公共介入','文本与光'],subjects:['卢旺达 genocide','迁徙','政治暴力','媒体','观看伦理','地缘政治'],outputs:['摄影','装置','电影','公共艺术','文本'],institutions:['MoMA','MoMA PS1'],achievements:['The Rwanda Project 1994–2000','MoMA collection'],whyImportant:'Jaar没有把政治灾难简单转化为震撼照片，而是持续追问哪些图像被看见、谁控制可见性以及观看是否可能成为伦理行动。',projects:[{year:'1994–2000',title:'The Rwanda Project',type:'长期研究项目',facts:['1994年赴卢旺达后发展出持续六年的摄影、文本、公共展示和装置项目。'],reading:'通过延迟、遮蔽和文字重新组织灾难图像，抵抗新闻摄影消费苦难的惯性。'},{year:'2002',title:'Lament of the Images',type:'装置',facts:['以背光文本和强烈白光构成空间，讨论图像从公共领域消失及其生产和控制。'],reading:'图像缺席本身成为关于权力和观看制度的证据。'}],images:[],sourceLabel:'MoMA · Alfredo Jaar',sourceUrl:'https://www.moma.org/artists/7477-alfredo-jaar'},
{id:'trevor-paglen',name:'Trevor Paglen',born:'1974',base:'United States',intro:'美国艺术家与地理学者，以摄影、调查研究和技术项目使秘密军事基础设施、卫星、监控系统、数据收集与机器视觉进入可见范围。',methods:['调查研究','远距离摄影','实验地理学','技术系统研究'],subjects:['监控','军事基础设施','卫星','数据','机器视觉','国家秘密'],outputs:['摄影','装置','研究项目','出版'],institutions:['Whitney Museum','Guggenheim'],achievements:['Deutsche Börse Photography Foundation Prize 2016','MacArthur Fellowship 2017','Whitney collection'],whyImportant:'Paglen把摄影的“看见”推进到国家与企业刻意隐藏的基础设施，并进一步研究机器如何观看世界，是监控研究、调查摄影与机器视觉艺术的重要节点。',projects:[{year:'2014',title:'An English Landscape (American Surveillance Base near Harrogate, Yorkshire)',type:'调查摄影',facts:['Whitney收藏的彩色摄影，以传统风景摄影形式指向隐藏在英国景观中的美国监控基地。'],reading:'平静风景与不可见情报网络之间形成结构性冲突。'},{year:'2000s–ongoing',title:'Limit Telephotography / surveillance infrastructures',type:'长期调查摄影',facts:['长期使用远摄技术与研究方法拍摄军事设施、卫星和监控基础设施。'],reading:'摄影成为测绘不可见权力系统的工具。'}],images:[],sourceLabel:'Whitney Museum · Trevor Paglen',sourceUrl:'https://whitney.org/artists/11403'},
{id:'aida-muluneh',name:'Aida Muluneh',born:'1974',base:'Ethiopia / international',intro:'埃塞俄比亚摄影艺术家、策展人与文化组织者，从新闻摄影转向高度构成的彩色摄影，同时建立Addis Foto Fest连接非洲与全球摄影网络。',methods:['导演式摄影','象征性色彩','视觉叙事','摄影机构建设'],subjects:['非洲女性','身份','离散','传统与现代性','非洲视觉再现'],outputs:['摄影','策展','摄影节'],institutions:['Aperture','Addis Foto Fest'],achievements:['Founder of Addis Foto Fest 2010','international photography exhibitions'],whyImportant:'Muluneh同时改变图像和摄影基础设施：她以鲜明导演式摄影挑战外部凝视，又通过Addis Foto Fest建立非洲摄影师之间以及与国际机构之间的交换网络。',projects:[{year:'2016',title:'The Departure',type:'导演式彩色摄影',facts:['Aperture关于Muluneh的资料展示该作品，并讨论她从摄影记者转向艺术摄影及返回Addis Ababa后的实践。'],reading:'高度控制的色彩、身体和符号把离散经验转化为非纪实式视觉语言。'},{year:'2010–ongoing',title:'Addis Foto Fest',type:'摄影机构项目',facts:['2010年创办Addis Foto Fest，强调通过图像进行跨文化交流并连接非洲摄影师。'],reading:'摄影生态与人才网络本身成为她实践的重要组成。'}],images:[],sourceLabel:'Aperture · Learning From Addis Ababa',sourceUrl:'https://aperture.org/editorial/learning-addis-ababa/'},
{id:'simryn-gill',name:'Simryn Gill',born:'1959',base:'Malaysia / Australia',intro:'马来西亚出生艺术家，以摄影、书籍、文字、植物和日常材料研究地点、迁徙、语言、殖民知识系统与环境变化。',methods:['摄影系列','书籍改造','材料转换','档案与文字'],subjects:['地点','语言','迁徙','植物','殖民知识','环境'],outputs:['摄影','装置','书籍作品','文字'],institutions:['MoMA','MoMA PS1','La Biennale di Venezia'],achievements:['Australian Pavilion, Venice Biennale 2013','MoMA collection'],whyImportant:'Gill不断把摄影与书籍、文字、自然材料相互转换，使分类、命名和知识制度成为关于地点与殖民历史的物质问题。',projects:[{year:'1996–1998',title:'Forest',type:'摄影与书籍项目',facts:['MoMA收藏Forest #15；Gill长期把书籍和印刷文字作为摄影及装置的来源材料。'],reading:'知识文本与植物/环境之间的边界被重新组织。'},{year:'2011–2012',title:'Where to draw the line',type:'文字作品',facts:['MoMA收藏，由九张纸上的打字文本组成。'],reading:'线、边界与语言分类被压缩为最基本的书写动作。'}],images:[],sourceLabel:'MoMA · Simryn Gill',sourceUrl:'https://www.moma.org/artists/30916-simryn-gill'},
...artistBatch181
];