import type { Artist } from './data';

export const artistBatch83: Artist[] = [
  {id:'shirin-neshat',name:'Shirin Neshat',born:'1957',base:'Iran / United States',intro:'以摄影、录像与电影研究伊朗革命之后的性别、宗教、权力、流亡与身份，在高度编排的黑白影像中结合身体、波斯文字和政治符号。',methods:['编排摄影','文字介入','双屏影像','电影叙事'],subjects:['女性','伊朗','宗教','权力','流亡'],outputs:['摄影','录像','电影','装置'],institutions:['MoMA','MoMA PS1'],achievements:['Women of Allah','Rapture'],whyImportant:'Neshat把摄影中的身体、文字和政治身份结合成高度辨识的视觉语言，是理解伊朗离散艺术、女性主义影像与跨文化身份的重要节点。',projects:[{year:'1993–97',title:'Women of Allah',type:'摄影系列',facts:['系列回应艺术家1990年重返革命后伊朗的经验。','女性身体、波斯文字与武器等符号共同出现。'],reading:'身体成为宗教、政治权力与女性主体性相互冲突的表面。'},{year:'1999',title:'Rapture',type:'摄影 / 影像',facts:['MoMA收藏该系列作品。'],reading:'以群体、空间和性别分隔组织政治寓言。'}],images:[],sourceLabel:'MoMA · Shirin Neshat',sourceUrl:'https://www.moma.org/artists/8349-shirin-neshat'},
  {id:'mona-hatoum',name:'Mona Hatoum',born:'1952',base:'Palestine / Lebanon / United Kingdom',intro:'从行为、录像发展到雕塑与大型装置，以身体、家居物件、地图和工业材料制造熟悉又危险的空间，讨论流亡、暴力、监控、边界和不稳定的归属。',methods:['尺度转换','日常物改造','身体材料','空间装置'],subjects:['流亡','身体','暴力','家园','监控'],outputs:['装置','雕塑','录像','行为','纸本'],institutions:['Tate','Centre Pompidou'],achievements:['Tate Modern survey 2016','Turner Prize 1995 shortlist'],whyImportant:'Hatoum把极简主义的形式秩序与流亡、身体和政治威胁结合，使日常家庭空间转化为不安全的心理与政治场域。',projects:[{year:'1985/1995',title:'Performance Still',type:'行为 / 摄影',facts:['记录艺术家在Brixton赤脚行走、脚踝系着靴子的街头行为。'],reading:'简单身体动作把移动、限制和公共空间中的脆弱性压缩为直接图像。'}],images:[],sourceLabel:'Tate · Mona Hatoum',sourceUrl:'https://www.tate.org.uk/art/artists/mona-hatoum-2365'},
  {id:'el-anatsui',name:'El Anatsui',born:'1944',base:'Ghana / Nigeria',intro:'以木材、金属和回收酒瓶盖构成可折叠、可重新悬挂的巨大雕塑表面，将材料循环、消费、殖民贸易、非洲与欧洲之间的商品流动转化为具有织物感的雕塑。',methods:['材料再利用','模块组装','非固定形态','场域悬挂'],subjects:['贸易','殖民历史','消费','迁移','材料循环'],outputs:['雕塑','装置','金属织物'],institutions:['Tate'],achievements:['Behind the Red Moon · Tate Modern 2023'],whyImportant:'Anatsui突破雕塑固定形态，以废弃消费材料建立可不断重新配置的巨大表面，是连接非洲当代艺术、全球贸易史和材料政治的核心人物。',projects:[{year:'2023',title:'Behind the Red Moon',type:'大型装置',facts:['Tate Modern Hyundai Commission。','由数千个金属酒瓶盖和碎片构成。','材料被压皱、压扁并缝合成大型悬挂结构。'],reading:'材料的前世把消费、跨大西洋贸易史和当代全球流通带入抽象雕塑。'}],images:[],sourceLabel:'Tate · El Anatsui: Behind the Red Moon',sourceUrl:'https://www.tate.org.uk/whats-on/tate-modern/el-anatsui'},
  {id:'danh-vo',name:'Danh Vo',born:'1975',base:'Vietnam / Denmark',intro:'以现成物、历史遗物、档案、文字和委托制作把个人难民经历与殖民主义、民族国家、宗教和全球资本主义连接起来，让物件自身的流通史成为作品。',methods:['现成物再语境化','档案研究','碎片化复制','委托制作'],subjects:['殖民主义','迁徙','国家','宗教','家庭记忆'],outputs:['雕塑','装置','文本','档案'],institutions:['Guggenheim'],achievements:['We the People','Danh Vo: Take My Breath Away · Guggenheim 2018'],whyImportant:'Vo把宏大的国家与殖民历史拆解为个人物件、家庭记忆和流通碎片，使微观传记成为阅读全球政治史的方法。',projects:[{year:'2011–16',title:'We the People',type:'雕塑项目',facts:['按一比一尺度复制纽约自由女神像的铜制外壳。','约三百个独立部件不会被重新组装成完整雕像。'],reading:'国家象征被拆成分散流通的薄铜碎片，纪念碑的完整性因此被主动取消。'},{year:'2009',title:'Oma Totem',type:'现成物雕塑',facts:['使用艺术家外祖母作为难民抵达西德后由社会福利机构获得的家电和十字架。'],reading:'家庭物件同时保存福利制度、迁徙与社会对外来者生活方式的投射。'}],images:[],sourceLabel:'Guggenheim · Danh Vo',sourceUrl:'https://www.guggenheim.org/artwork/artist/danh-vo'},
  {id:'aida-muluneh',name:'Aïda Muluneh',born:'1974',base:'Ethiopia',intro:'从新闻摄影转向高度编排的彩色肖像与观念摄影，以鲜明色块、身体绘画、服装和象征物讨论埃塞俄比亚女性、历史、身份以及外部世界如何观看非洲。',methods:['编排摄影','色彩系统','象征性肖像','文化平台建设'],subjects:['埃塞俄比亚','女性','身份','非洲表征','文化交流'],outputs:['摄影','策展','摄影节'],institutions:['Aperture'],achievements:['Addis Foto Fest founder','Departure'],whyImportant:'Muluneh不仅以强烈的编排摄影重写非洲女性形象，也通过Addis Foto Fest建设跨非洲摄影基础设施，是艺术实践与摄影生态建设相连的重要节点。',projects:[{year:'2016',title:'Departure',type:'编排摄影',facts:['Aperture在关于Muluneh与Addis Foto Fest的专题中刊载该作。'],reading:'高度控制的色彩和人物姿态主动抵抗把非洲摄影等同于新闻纪实的观看习惯。'}],images:[],sourceLabel:'Aperture · Learning From Addis Ababa',sourceUrl:'https://aperture.org/editorial/learning-addis-ababa/'}
];
