import type { Artist } from './data';
import { artistBatch104 } from './expansionBatch104';

export const artistBatch103: Artist[] = [
{id:'cao-fei',name:'Cao Fei',born:'1978',base:'China',intro:'中国艺术家，以录像、摄影、虚拟世界和装置研究快速城市化、青年亚文化、劳动、幻想与数字生活。',methods:['社会观察','虚拟世界建构','录像叙事','参与式研究'],subjects:['城市化','青年文化','劳动','数字生活','现实与幻想'],outputs:['录像','摄影','装置','虚拟项目'],institutions:['MoMA','MoMA PS1','La Biennale di Venezia'],achievements:['Whose Utopia?','RMB City','La Town','Cao Fei at MoMA PS1'],whyImportant:'曹斐把珠三角制造业、青年亚文化和早期虚拟世界并置，是理解中国全球化与数字社会经验的重要艺术家。',projects:[{year:'2006',title:'Whose Utopia?',type:'录像',facts:['在珠三角OSRAM照明工厂驻留六个月完成。','与工人合作，把他们的舞蹈、音乐等个人愿望置入生产空间。'],reading:'工业生产的标准化节奏与工人的个人幻想并置，使劳动者不再只是生产体系中的匿名角色。'},{year:'2007–11',title:'RMB City',type:'虚拟世界 / 网络项目',facts:['在Second Life中以China Tracy身份发展虚拟城市。','项目把中国现实符号与未来想象混合。'],reading:'虚拟城市成为观察现实中国城市化欲望、消费与政治符号的实验场。'}],images:[],sourceLabel:'MoMA · Cao Fei',sourceUrl:'https://www.moma.org/calendar/exhibitions/4945'},
{id:'danh-vo',name:'Danh Vo',born:'1975',base:'Vietnam / Denmark',intro:'越南出生的丹麦艺术家，以现成物、历史文献、家族物件与拆解雕塑把个人流散经验连接殖民主义、宗教、国家与资本主义历史。',methods:['现成物重置','档案研究','拆解与重组','个人史与宏观史并置'],subjects:['流散','殖民主义','国家','宗教','资本主义','家庭记忆'],outputs:['雕塑','装置','档案','文本'],institutions:['Guggenheim'],achievements:['We the People','Oma Totem','Danh Vo: Take My Breath Away'],whyImportant:'Vo让宏大的国家和殖民历史通过家庭物件、商品、文献和碎片进入作品，改变了身份政治与历史材料在当代雕塑中的关系。',projects:[{year:'2011–16',title:'We the People',type:'雕塑 / 分布式装置',facts:['按一比一比例复制自由女神像铜制外壳。','约三百个部件从未被重新组装为完整雕像，而分散展示。'],reading:'国家象征被拆成可移动碎片，使熟悉的自由图像重新变得陌生。'},{year:'2009',title:'Oma Totem',type:'现成物雕塑',facts:['使用艺术家外祖母作为难民抵达西德后由社会福利机构获得的家电与十字架。'],reading:'普通家庭用品同时记录福利国家、移民安置、宗教与私人生活。'}],images:[],sourceLabel:'Guggenheim · Danh Vo',sourceUrl:'https://www.guggenheim.org/video/danh-vo-we-the-people-2011-16'},
{id:'boris-mikhailov',name:'Boris Mikhailov',born:'1938',base:'Ukraine',intro:'乌克兰摄影家，以日常纪实、序列、手工着色与观念性摄影记录苏联及后苏联社会、私人生活、贫困与公共空间。',methods:['社会纪实','摄影序列','观念摄影','手工介入'],subjects:['苏联社会','后苏联转型','贫困','身体','日常生活'],outputs:['摄影','摄影书','系列'],institutions:['MoMA'],achievements:['Case History','New Photography 9','After the Wall'],whyImportant:'Mikhailov把地下私人摄影、社会纪实和观念方法结合起来，是理解苏联晚期与后苏联视觉经验的关键摄影家。',projects:[{year:'1997–98',title:'Case History',type:'摄影系列',facts:['MoMA于2011年举办Boris Mikhailov: Case History专题展。','其作品长期进入MoMA摄影收藏和After the Wall等展览网络。'],reading:'作品把社会转型中被公共叙事排除的人重新置于观看中心，同时保留摄影者与被摄者之间不舒适的权力关系。'}],images:[],sourceLabel:'MoMA · Boris Mikhailov',sourceUrl:'https://www.moma.org/artists/8168-boris-mikhailov'},
{id:'meschac-gaba',name:'Meschac Gaba',born:'1961',base:'Benin / Netherlands',intro:'贝宁艺术家，以装置、日常物件和参与式空间研究博物馆制度、非洲艺术分类、货币、文化价值与全球艺术体系。',methods:['虚构机构','制度批判','参与式装置','日常物件重置'],subjects:['博物馆制度','非洲身份','文化资本','货币','全球化'],outputs:['装置','参与式空间','物件'],institutions:['Tate'],achievements:['Museum of Contemporary African Art 1997–2002'],whyImportant:'Gaba没有简单把非洲艺术放入既有博物馆，而是虚构一整套博物馆结构来反问谁有权定义、展示和赋值“当代非洲艺术”。',projects:[{year:'1997–2002',title:'Museum of Contemporary African Art',type:'十二部分装置 / 虚构博物馆',facts:['作品由Draft Room、Museum Shop、Games Room、Library、Museum Restaurant等十二个部分组成。','项目在Rijksakademie时期开始，并被Tate作为重要整体项目展示与研究。'],reading:'作品把博物馆从中性的展示容器变成作品本身，从制度内部讨论文化价值如何生产。'}],images:[],sourceLabel:'Tate · Meschac Gaba',sourceUrl:'https://shop.tate.org.uk/meschac-gaba-museum-of-contemporary-african-art/14461.html'},
...artistBatch104
];