import type { Artist } from './data';

const project=(year:string,title:string,type:string,facts:string[],reading:string)=>({year,title,type,facts,reading});

export const artistBatch32: Artist[] = [
  {id:'ming-smith',name:'Ming Smith',born:'—',base:'New York',intro:'以长曝光、运动模糊、暗部层次与手工介入拍摄黑人日常、爵士文化和城市经验，让摄影获得接近音乐与绘画的节奏。',methods:['街头摄影','长曝光','运动模糊','手工上色','直觉式摄影'],subjects:['黑人生活','爵士','城市','可见性','身体','光'],outputs:['摄影','手工上色照片'],institutions:['MoMA','Kamoinge Workshop'],achievements:['Projects: Ming Smith · MoMA 2023','Kamoinge Workshop 成员'],whyImportant:'她把纪实摄影从清晰描述转向感知、节奏和模糊，并以黑人生活内部视角处理“可见与不可见”，是美国战后摄影史中长期被低估的重要节点。',projects:[project('1991–1998','Invisible Man, Somewhere, Everywhere','摄影系列',['受 Ralph Ellison《Invisible Man》启发。','通过模糊、暗部和移动处理黑人主体的可见性。'],'作品把文学、爵士式节奏和摄影曝光结合，而不是把身份简化成说明性肖像。')],images:[],sourceLabel:'MoMA · Ming Smith',sourceUrl:'https://www.moma.org/artists/7906-ming-smith'},
  {id:'lorna-simpson',name:'Lorna Simpson',born:'1960',base:'New York',intro:'把摄影、文字、档案、电影与绘画并置，以裁切、背影、分类和语言歧义拆解摄影关于身份的“客观证据”幻觉。',methods:['摄影与文本','概念摄影','档案挪用','裁切','类型学','影像装置'],subjects:['种族','性别','身份','历史记忆','身体','再现'],outputs:['摄影','文字装置','电影','绘画','拼贴'],institutions:['Whitney Museum','Venice Biennale','MoMA'],achievements:['Venice Biennale 1990','Whitney Museum mid-career survey 2007'],whyImportant:'她是1980年代以来摄影—文本实践的核心人物之一，把“照片证明什么”转化成“谁有权定义照片中的身体与历史”。',projects:[project('1991','Counting','摄影 / 文字装置',['把被裁切的黑人女性身体、历史建筑和头发图像与数字文本并置。','计数系统看似客观却不断产生历史与身体之间的歧义。'],'分类和证据语言在这里不再中立，而暴露出种族与历史如何进入观看制度。')],images:[],sourceLabel:'Whitney Museum · Lorna Simpson',sourceUrl:'https://whitney.org/artists/3452'},
  {id:'an-my-le',name:'An-My Lê',born:'1960',base:'New York',intro:'以大画幅摄影研究战争、军事训练、历史再现和景观，把冲突从新闻瞬间拉回地形、表演和长期观看。',methods:['大画幅摄影','景观摄影','长期观察','战争再现研究','类型学'],subjects:['战争','景观','越南','军事','迁徙','历史再现'],outputs:['摄影','电影','录像','纺织','装置'],institutions:['MoMA','Carnegie Museum of Art'],achievements:['An-My Lê: Between Two Rivers · MoMA 2023–2024','MacArthur Fellow 2012'],whyImportant:'她避免传统战地摄影的即时戏剧性，而观察战争如何通过训练、电影、纪念碑和地景持续被生产，是连接景观摄影与战争图像研究的重要人物。',projects:[project('2003–2004','29 Palms','大画幅摄影 / 军事景观',['在加州海军陆战队训练基地拍摄伊拉克和阿富汗部署前训练。','人物、武器和地形被放进同一高细节景观。'],'战争不是单一事件，而是一套在远离战场的土地上被预演和制造的视觉系统。')],images:[],sourceLabel:'MoMA · An-My Lê',sourceUrl:'https://www.moma.org/artists/7901-an-my-le'},
  {id:'santu-mofokeng',name:'Santu Mofokeng',born:'1956–2020',base:'South Africa',intro:'以黑白摄影长期观察南非黑人社区、宗教、土地与种族隔离后的空间记忆，拒绝把黑人经验压缩成新闻事件。',methods:['长期纪实摄影','黑白摄影','社会景观','摄影随笔','档案研究'],subjects:['南非','种族隔离','宗教','土地','黑人生活','记忆'],outputs:['摄影','摄影随笔','出版'],institutions:['MoMA','Documenta'],achievements:['documenta 11 · 2002','Train Church 系列进入 MoMA 收藏'],whyImportant:'他把反种族隔离时期的摄影从政治新闻扩展到精神生活、日常经验和景观记忆，对南非纪实摄影及“社会景观”方法影响深远。',projects:[project('1986','Train Church','纪实摄影系列',['拍摄 Johannesburg–Soweto 通勤列车中自发形成的礼拜活动。','关注歌唱、祈祷、身体和拥挤交通空间。'],'列车既是种族隔离城市结构的产物，也被乘客临时转化为精神共同体。')],images:[],sourceLabel:'MoMA · Santu Mofokeng',sourceUrl:'https://www.moma.org/artists/72440-santu-mofokeng'},
  {id:'graciela-iturbide',name:'Graciela Iturbide',born:'1942',base:'Mexico City',intro:'以长期共同生活和黑白摄影进入墨西哥不同社群，把民族志式观察转成更开放的诗性、象征和日常关系。',methods:['长期摄影','黑白摄影','参与式观察','摄影随笔','街头摄影'],subjects:['墨西哥','原住民社群','女性','仪式','日常生活','死亡'],outputs:['摄影','摄影书'],institutions:['MoMA','Centre Pompidou','Getty Museum'],achievements:['Hasselblad Award 2008','Juchitán de las mujeres · 1989'],whyImportant:'她的重要性不仅是经典黑白风格，更在于强调与被摄社群建立关系；摄影并非优先于交流，使拉丁美洲纪实摄影摆脱简单的异域民族志观看。',projects:[project('1979–1989','Juchitán de las mujeres','长期摄影 / 摄影书',['在 Oaxaca 的 Juchitán 长期拍摄 Zapotec 社群。','持续参与当地女性的市场、节庆和日常生活。'],'系列以关系和长期停留替代外来者式快速记录，并形成墨西哥摄影史的重要女性图像档案。')],images:[],sourceLabel:'MoMA · Graciela Iturbide',sourceUrl:'https://www.moma.org/artists/2844-graciela-iturbide'},
  {id:'shomei-tomatsu',name:'Shomei Tomatsu',born:'1930–2012',base:'Japan',intro:'从战后日本、美国军事基地、长崎核爆余波到冲绳，以高度主观的黑白摄影重构“战后”作为持续状态。',methods:['主观纪实','黑白摄影','摄影书','系列编辑','社会景观'],subjects:['战后日本','长崎','核爆','美国军事基地','冲绳','城市'],outputs:['摄影','摄影书'],institutions:['MoMA'],achievements:['New Japanese Photography · MoMA 1974','日本战后摄影核心人物'],whyImportant:'他改变了日本纪实摄影的语言：不是透明记录现实，而以强烈构图、近距离细节和象征把历史创伤转成主观视觉经验，并深刻影响后来的日本摄影。',projects:[project('1960s','Nagasaki / hibakusha photographs','战后摄影',['持续返回长崎拍摄核爆幸存者和城市痕迹。','把“废墟”从建筑残骸扩展到人的身体与长期心理状态。'],'他的关键判断是战争结束并不意味着“战后”结束；摄影追踪的是持续存在于人和社会中的后果。')],images:[],sourceLabel:'MoMA · Shomei Tomatsu',sourceUrl:'https://www.moma.org/artists/5892'},
  {id:'raghubir-singh',name:'Raghubir Singh',born:'1942–1999',base:'India / New York / Paris',intro:'坚持彩色摄影，以印度街道、季风、交通与公共生活建立复杂多层构图，挑战20世纪艺术摄影长期把黑白视为严肃语言的传统。',methods:['彩色摄影','街头摄影','复杂构图','长期旅行','摄影书'],subjects:['印度','公共空间','季风','交通','城市','日常生活'],outputs:['摄影','摄影书'],institutions:['MoMA','Metropolitan Museum of Art'],achievements:['Monsoon Women · MoMA collection','多部印度主题摄影书'],whyImportant:'他是把彩色摄影带入印度现代视觉经验的重要人物，以拥挤、多层和流动构图建立区别于欧美街头摄影传统的空间语言。',projects:[project('1960s–1990s','India / Monsoon photographs','彩色街头摄影',['长期在印度不同地区拍摄。','以彩色胶片处理季风、道路、车辆和公共生活。'],'色彩不是附加效果，而与印度街道的密度、运动和空间层次共同构成摄影结构。')],images:[],sourceLabel:'MoMA · Raghubir Singh',sourceUrl:'https://www.moma.org/artists/5447-raghubir-singh'}
];
