import type { Artist } from './data';
import { artistBatch141 } from './expansionBatch141';

export const artistBatch140: Artist[] = [
{id:'teresa-margolles',name:'Teresa Margolles',born:'1963',base:'Mexico',intro:'墨西哥艺术家，受过法医学训练，以来自暴力现场的物质痕迹、摄影、影像与空间装置研究死亡、失踪、边境、性别暴力与公共记忆。',methods:['法医式研究','现场取样','物质证据','反纪念碑'],subjects:['暴力','失踪','美墨边境','女性杀害','迁徙','公共记忆'],outputs:['装置','雕塑','摄影','影像'],institutions:['MoMA','MoMA PS1'],achievements:['Teresa Margolles: En el lugar de los hechos','Aproximación al lugar de los hechos'],whyImportant:'Margolles把暴力事件留下的玻璃、土壤、水与建筑碎片从证据转化为艺术材料，使结构性暴力不靠再现尸体而通过物质残留进入观看现场。',projects:[{year:'1990s–',title:'At the Scene / En el lugar de los hechos',type:'装置 / 摄影 / 影像',facts:['MoMA PS1于2026年举办其美国首个大型博物馆展，回顾三十年实践。','MoMA指出她长期从暴力与死亡现场收集物质痕迹，讨论迁徙危机、毒品战争及针对女性和女孩的系统性杀害。'],reading:'她把“现场”从被摄影再现的对象改造成材料来源，让观众面对暴力留下的真实物质后果。'}],images:[],sourceLabel:'MoMA · Teresa Margolles',sourceUrl:'https://www.moma.org/artists/72286-teresa-margolles'},
{id:'amar-kanwar',name:'Amar Kanwar',born:'1964',base:'India',intro:'印度艺术家与电影作者，以纪录影像、档案、多通道装置和诗性文本研究国家暴力、生态冲突、正义、主权与抵抗。',methods:['诗性纪录片','档案蒙太奇','多通道叙事','长期社会研究'],subjects:['国家暴力','正义','主权','生态','抵抗','记忆'],outputs:['电影','多通道影像','装置','档案'],institutions:['Guggenheim','documenta'],achievements:['The Torn First Pages','The Sovereign Forest','documenta 11/12/13'],whyImportant:'Kanwar把纪录片从事实说明扩展为“诗能否成为证据”的研究，使档案、证词、自然材料和多屏空间共同承担政治论证。',projects:[{year:'2004–08',title:'The Torn First Pages',type:'十九通道影像装置',facts:['Guggenheim收藏该十九通道装置。','作品围绕缅甸军政府的压迫与抵抗，并纪念因撕去官方宣传页而入狱的书店经营者。'],reading:'事实材料没有被简单整理成新闻叙事，而被组织成同时关于记忆、抵抗和观看伦理的空间合唱。'}],images:[],sourceLabel:'Guggenheim · Amar Kanwar',sourceUrl:'https://www.guggenheim.org/artwork/artist/amar-kanwar'},
{id:'kiluanji-kia-henda',name:'Kiluanji Kia Henda',born:'1979',base:'Angola',intro:'安哥拉艺术家，以摄影、影像、雕塑与公共介入研究殖民遗产、内战后的城市空间、纪念碑、现代性以及恐惧的建筑形式。',methods:['城市观察','历史重写','建筑摄影','物件转置'],subjects:['殖民遗产','卢安达','内战','纪念碑','恐惧','城市不平等'],outputs:['摄影','雕塑','影像','装置'],institutions:['La Biennale di Venezia'],achievements:['Biennale Arte 2024','The Geometric Ballad of Fear'],whyImportant:'Kia Henda以安哥拉城市中极具体的建筑与安全设施为入口，把后殖民历史从抽象叙事转化为可见的空间结构，并经常以幽默和虚构重写官方纪念方式。',projects:[{year:'2015–22',title:'The Geometric Ballad of Fear / A Espiral do Medo',type:'摄影 / 雕塑',facts:['2024威尼斯双年展展出这一相互关联的作品组。','项目从卢安达住宅的防护金属栅栏出发，先摄影，再将真实栅栏转化为大型雕塑。'],reading:'原本用于保护私有空间的栅栏被抽离功能后，成为社会不平等与集体恐惧的几何图像。'}],images:[],sourceLabel:'La Biennale di Venezia · Kiluanji Kia Henda',sourceUrl:'https://www.labiennale.org/en/art/2024/nucleo-contemporaneo/kiluanji-kia-henda'},
{id:'awoiska-van-der-molen',name:'Awoiska van der Molen',born:'1972',base:'Netherlands',intro:'荷兰摄影艺术家，以长期独处式地景拍摄和手工银盐暗房放大研究黑暗、时间、感知与人与自然之间非叙事性的关系。',methods:['长期地景观察','暗房手工放大','缓慢摄影','孤独式田野'],subjects:['自然','黑暗','时间','感知','孤独','地景'],outputs:['黑白摄影','银盐相纸'],institutions:['Foam'],achievements:['Blanco — Foam 2016','Deutsche Börse Photography Prize nominee 2017'],whyImportant:'Van der Molen把当代地景摄影从类型学与社会调查拉向极慢的感知经验，并让暗房制作本身成为作品时间性的组成部分。',projects:[{year:'2009–16',title:'Blanco / Sequester',type:'黑白地景摄影',facts:['Foam于2016年举办其首个大型博物馆个展Blanco。','Foam记录其大型作品为手工制作的银盐明胶相纸，并强调长期独处、反复返回现场及持续到暗房的缓慢工作过程。'],reading:'深黑并非视觉风格附加物，而是拍摄、等待和暗房控制共同生成的感知空间。'}],images:[],sourceLabel:'Foam · Awoiska van der Molen',sourceUrl:'https://www.foam.org/events/awoiska-van-der-molen'},
{id:'samuel-fosso',name:'Samuel Fosso',born:'1962',base:'Cameroon / Central African Republic / France',intro:'喀麦隆出生的摄影艺术家，以自画像、角色扮演与摄影棚表演不断变换身份，研究非洲历史、黑人身份、权力图像与摄影中的自我建构。',methods:['自画像','角色扮演','摄影棚表演','历史人物再演'],subjects:['身份','黑人历史','权力','性别呈现','非洲现代性'],outputs:['摄影','表演'],institutions:['Foam','The Walther Collection'],achievements:['Structures of Identity — Foam'],whyImportant:'Fosso把摄影棚自画像从个人记录发展为身份政治工具：同一个身体不断成为不同社会角色和历史人物，从内部拆解肖像摄影固定身份的功能。',projects:[{year:'1970s–',title:'Self-portrait practice',type:'摄影 / 表演',facts:['Foam的Structures of Identity将Fosso列为以肖像批判性研究种族、身份、地位与国籍的重要当代摄影家。','其作品与Zanele Muholi、Yto Barrada、J.D. Okhai Ojeikere等共同进入Walther Collection的身份摄影脉络。'],reading:'持续的角色转换使自画像同时成为私人舞台和历史图像的再分配机制。'}],images:[],sourceLabel:'Foam · Structures of Identity',sourceUrl:'https://www.foam.org/events/structures-of-identity'},
{id:'hoda-afshar',name:'Hoda Afshar',born:'1983',base:'Iran / Australia',intro:'伊朗出生、澳大利亚工作的摄影与影像艺术家，在纪录摄影和观念摄影交界处研究国家暴力、迁徙、拘留制度、性别与图像见证的伦理。',methods:['观念纪实','合作式影像','编排摄影','见证伦理'],subjects:['迁徙','拘留','国家暴力','女性权利','伊朗','身份'],outputs:['摄影','影像','装置'],institutions:['Foam'],achievements:['Foam Paul Huf Award 2024 special mention','In Turn'],whyImportant:'Afshar不把纪录摄影视为透明证据，而是通过编排、合作与形式实验追问谁有权制造政治事件的可见性。',projects:[{year:'2020s',title:'In Turn',type:'摄影 / 观念纪录',facts:['Foam Paul Huf Award 2024评审给予Afshar特别提名。','Foam指出In Turn回应伊朗持续的女性权利抗议，并强调她推动纪录与观念摄影边界。'],reading:'政治事件没有被压缩为新闻瞬间，而被重新组织为关于身体、团结与观看制度的视觉结构。'}],images:[],sourceLabel:'Foam · Paul Huf Award 2024',sourceUrl:'https://www.foam.org/press/fpha2024-hien-hoang'},
{id:'newsha-tavakolian',name:'Newsha Tavakolian',born:'1981',base:'Iran',intro:'伊朗摄影师与艺术家，以纪实摄影、编排肖像和多媒体项目研究伊朗社会、女性生活、战争、青年文化以及声音与可见性的关系。',methods:['长期纪实','编排肖像','声音与摄影结合','社会观察'],subjects:['伊朗','女性','青年','战争','音乐','社会生活'],outputs:['摄影','多媒体'],institutions:['Aperture'],achievements:['Listen — Aperture 224'],whyImportant:'Tavakolian连接新闻摄影与当代艺术摄影，使长期社会观察能够进入更复杂的声音、表演和身份表达结构。',projects:[{year:'2010s',title:'Listen',type:'摄影 / 声音研究',facts:['Aperture 224 Sounds专题刊载Newsha Tavakolian的Listen。','该项目被置于摄影与声音、音乐关系的专题语境中。'],reading:'作品把无法仅由静态照片表达的声音与社会身份问题引入摄影项目，使“沉默”本身成为可见主题。'}],images:[],sourceLabel:'Aperture · Sounds / Listen',sourceUrl:'https://store.aperture.org/products/aperture-224'},
...artistBatch141
];