import type { Artist } from './data';

export const artistBatch116: Artist[] = [
{id:'yto-barrada',name:'Yto Barrada',born:'1971',base:'Morocco / France',intro:'摩洛哥—法国艺术家，以摄影、电影、出版、纺织与社会文化项目研究丹吉尔、迁徙地缘政治、现代主义历史，以及在限制条件中的生存与抵抗策略。',methods:['社会观察','档案研究','摄影序列','文化空间实践'],subjects:['迁徙','丹吉尔','边境','现代主义','抵抗'],outputs:['摄影','电影','出版','纺织','装置'],institutions:['MoMA'],achievements:['A Life Full of Holes: The Strait Project','Artist’s Choice: Yto Barrada—A Raft','Cinémathèque de Tanger'],whyImportant:'Barrada把北非城市日常、边境制度与文化基础设施连接起来，使摄影不只是记录迁徙，而成为研究限制、抵抗和地方知识生产的工具。',projects:[{year:'1998–2004',title:'A Life Full of Holes: The Strait Project',type:'摄影 / 社会地理研究',facts:['系列围绕丹吉尔及直布罗陀海峡展开。','MoMA收藏Barrada多件丹吉尔相关摄影，并于2021年邀请她策划Artist’s Choice: A Raft。'],reading:'作品避开直接的边境新闻图像，通过城市空地、等待与日常细节呈现迁徙制度如何进入生活。'}],images:[],sourceLabel:'MoMA · Yto Barrada',sourceUrl:'https://www.moma.org/artists/42323-yto-barrada'},
{id:'kader-attia',name:'Kader Attia',born:'1970',base:'Algeria / France / Germany',intro:'法裔阿尔及利亚艺术家，以装置、雕塑、摄影和研究项目讨论殖民主义、现代主义、文化挪用、创伤以及“修复”在不同社会中的意义。',methods:['研究型艺术','材料隐喻','档案并置','空间装置'],subjects:['殖民主义','修复','现代主义','文化交换','创伤'],outputs:['装置','雕塑','摄影','录像'],institutions:['Guggenheim','documenta','Lyon Biennale'],achievements:['The Repair from Occident to Extra-Occidental Cultures','Untitled (Ghardaïa)','documenta 13'],whyImportant:'Attia把“修复”发展成理解殖民创伤和现代性的重要方法，同时揭示欧洲现代主义从殖民地建筑与文化吸收形式却抹除来源的权力关系。',projects:[{year:'2009',title:'Untitled (Ghardaïa)',type:'装置 / 建筑研究',facts:['作品以古斯米制作阿尔及利亚Ghardaïa城市模型。','Guggenheim资料指出Ghardaïa的建筑曾影响Le Corbusier的现代主义设计。'],reading:'脆弱的食物模型与现代主义建筑史并置，反转了通常由欧洲向殖民地传播形式的单向叙事。'}],images:[],sourceLabel:'Guggenheim · Kader Attia',sourceUrl:'https://www.guggenheim.org/map/kader-attia'},
{id:'mounira-al-solh',name:'Mounira Al Solh',born:'1978',base:'Lebanon / Netherlands',intro:'黎巴嫩艺术家，以绘画、绘图、刺绣、录像、表演与口述材料处理迁徙、战争、女性经验、语言和地中海历史，并经常把个人故事与更大的政治结构连接。',methods:['口述叙事','跨媒介拼接','神话重写','手工艺介入'],subjects:['迁徙','战争','女性','神话','黎巴嫩'],outputs:['绘画','绘图','刺绣','录像','装置'],institutions:['La Biennale di Venezia'],achievements:['A Dance with her Myth','Lebanon Pavilion Venice Biennale 2024'],whyImportant:'Al Solh把日常叙事、传统手工艺与地缘政治结合，并通过女性视角重新书写地中海神话与历史，是理解黎巴嫩及流散艺术的重要节点。',projects:[{year:'2024',title:'A Dance with her Myth',type:'多媒体装置 / 国家馆项目',facts:['作品代表黎巴嫩参加第60届威尼斯双年展。','装置结合绘画、绘图、雕塑、刺绣和录像，并重新处理Europa神话。'],reading:'古代神话不被作为固定遗产展示，而被转化为关于女性自主、自由和平等的当代政治叙事。'}],images:[],sourceLabel:'La Biennale di Venezia · Lebanon 2024',sourceUrl:'https://www.labiennale.org/en/art/2024/lebanon'},
{id:'emily-jacir',name:'Emily Jacir',born:'1970',base:'Palestine / Mediterranean',intro:'巴勒斯坦艺术家，以摄影、录像、文本、行动和档案研究移动限制、流散、边境、翻译以及巴勒斯坦个人与集体记忆。',methods:['档案研究','行动与记录','跨地域比较','文本影像'],subjects:['巴勒斯坦','迁徙','边境','流散','记忆'],outputs:['摄影','录像','文本','装置','行动'],institutions:['MoMA','MoMA PS1'],achievements:['Ramallah/New York','From Paris to Riyadh (Drawings for My Mother)','Where We Come From'],whyImportant:'Jacir把跨境移动本身变成艺术方法，通过个人行动、城市比较与档案材料具体呈现护照、国界和政治身份如何塑造日常生活。',projects:[{year:'2004–2005',title:'Ramallah/New York',type:'双频道录像 / 城市比较',facts:['作品进入MoMA馆藏并于2014年在MoMA展出。','项目通过Ramallah与New York的日常空间建立视觉对应。'],reading:'看似普通的城市细节让两个被政治叙事分开的地点进入同一观看结构，从而重新组织关于地方与流散的经验。'}],images:[],sourceLabel:'MoMA · Emily Jacir',sourceUrl:'https://www.moma.org/artists/28422-emily-jacir'},
{id:'joana-hadjithomas-khalil-joreige',name:'Joana Hadjithomas & Khalil Joreige',born:'1969 / 1969',base:'Lebanon / France',intro:'黎巴嫩艺术家组合，以摄影、电影、录像、档案和装置研究图像、记忆、战争、互联网骗局以及被遗忘或未完成的现代性历史。',methods:['档案考古','研究型影像','历史重演','图像再语境化'],subjects:['黎巴嫩','战争','记忆','现代性','技术史'],outputs:['摄影','电影','录像','装置'],institutions:['Centre Pompidou'],achievements:['Lebanese Rocket Society','The Golden Record','Wonder Beirut'],whyImportant:'Hadjithomas与Joreige通过重新发现、重演和重新组织档案，让黎巴嫩历史不再只围绕战争展开，并成为当代艺术处理缺失档案与历史想象的重要案例。',projects:[{year:'2012',title:'Lebanese Rocket Society',type:'摄影 / 电影 / 档案研究',facts:['项目研究1960至1967年黎巴嫩真实存在的火箭探索计划。','Centre Pompidou收藏该项目摄影及The Golden Record影像声音装置。'],reading:'被战争记忆覆盖的科学乌托邦重新出现，使国家历史中“本来可能发生的未来”成为可研究的对象。'}],images:[],sourceLabel:'Centre Pompidou · Lebanese Rocket Society',sourceUrl:'https://www.centrepompidou.fr/en/ressources/oeuvre/ckXyKXr'},
{id:'mona-hatoum',name:'Mona Hatoum',born:'1952',base:'Palestine / Lebanon / United Kingdom',intro:'出生于贝鲁特的巴勒斯坦艺术家，以表演、录像、雕塑和装置把家庭用品、身体尺度与极简形式转化为关于流散、暴力、监控和权力的不安空间。',methods:['日常物陌生化','尺度转换','身体介入','空间装置'],subjects:['流散','身体','暴力','家庭空间','权力'],outputs:['装置','雕塑','录像','表演'],institutions:['Tate'],achievements:['Measures of Distance','Hot Spot','Homebound','Tate Modern survey 2016'],whyImportant:'Hatoum把熟悉的家庭物件和现代主义形式变成危险、排斥或不稳定的结构，使身体经验成为理解流散、权力与空间政治的直接入口。',projects:[{year:'1988',title:'Measures of Distance',type:'录像 / 文字与身体影像',facts:['作品把艺术家母亲的影像、书信文字和声音组织在同一录像结构中。','Hatoum出生于贝鲁特的巴勒斯坦家庭，1975年后定居英国。'],reading:'私人母女通信与被迫分离的政治背景重叠，使距离既是亲密经验也是流散结构。'}],images:[],sourceLabel:'Tate · Mona Hatoum',sourceUrl:'https://www.tate.org.uk/art/artists/mona-hatoum-2365'}
];