import type { Artist } from './data';

const project=(year:string,title:string,type:string,facts:string[],reading:string)=>({year,title,type,facts,reading});

export const artistBatch31: Artist[] = [
{id:'carrie-mae-weems',name:'Carrie Mae Weems',born:'1953',base:'Syracuse / New York',intro:'以摄影、文本、录像和装置研究种族、性别、家庭与权力如何进入日常图像。',methods:['编排摄影','文本与图像','档案研究','录像','装置'],subjects:['种族','性别','家庭','权力','历史','身份'],outputs:['摄影','录像','装置','文本作品'],institutions:['MoMA','Guggenheim','Whitney Museum'],achievements:['MacArthur Fellow 2013','Hasselblad Award 2023'],whyImportant:'她把私人家庭场景与美国种族和性别政治连接起来，是理解编排摄影、文本摄影和黑人女性主义视觉实践的关键人物。',projects:[project('1990','The Kitchen Table Series','编排摄影 / 文本',['围绕一张厨房桌子建立连续的家庭与社会场景。','艺术家本人反复进入画面扮演中心人物。'],'同一个日常空间被转化成亲密关系、性别角色和权力关系的舞台。')],images:[],sourceLabel:'MoMA',sourceUrl:'https://www.moma.org/artists/7177'},
{id:'moyra-davey',name:'Moyra Davey',born:'1958',base:'New York',intro:'以日常摄影、写作、电影和邮寄折叠照片建立图像、阅读、记忆与流通之间的关系。',methods:['日常摄影','邮寄摄影','写作','电影散文','折叠'],subjects:['阅读','记忆','家庭','日常物','流通','时间'],outputs:['摄影','电影','文本','摄影书','装置'],institutions:['MoMA','Whitney Museum','Tate'],achievements:['Whitney Biennial 2012'],whyImportant:'她把照片当作会被折叠、贴邮票、运输和磨损的物件，摄影的流通过程因此直接成为作品的一部分。',projects:[project('2007–','Mailer works','邮寄摄影',['把摄影打印物折叠成可邮寄形态。','直接贴邮票、地址和胶带后通过邮政系统寄送。'],'运输留下的折痕和磨损不是损坏，而是作品继续生成的痕迹。')],images:[],sourceLabel:'MoMA',sourceUrl:'https://www.moma.org/artists/28582'},
{id:'walead-beshty',name:'Walead Beshty',born:'1976',base:'Los Angeles',intro:'通过无相机摄影、运输箱和物流系统研究艺术品如何被生产、移动、损伤和制度化。',methods:['无相机摄影','物流实验','制度研究','材料过程','运输痕迹'],subjects:['全球物流','摄影材料','艺术制度','流通','劳动'],outputs:['Photogram','雕塑','装置','文本'],institutions:['Guggenheim','Whitney Museum','Tate'],achievements:['Whitney Biennial 2008'],whyImportant:'他把机场安检、FedEx 和展览运输这些通常隐藏的基础设施直接变成作品生成机制。',projects:[project('2007–','FedEx Works','物流 / 雕塑',['透明或镜面物件按标准物流方式装箱并运输。','每次运输产生的裂痕、划痕和碰撞被完整保留。'],'艺术品不再假装独立于物流系统；运输本身持续雕刻作品。')],images:[],sourceLabel:'Guggenheim',sourceUrl:'https://www.guggenheim.org/artwork/artist/walead-beshty'},
{id:'sophie-calle',name:'Sophie Calle',born:'1953',base:'Paris / Malakoff',intro:'通过自定规则、跟踪、调查、摄影和文字，把真实生活转化为介于档案、叙事与行为之间的作品。',methods:['规则系统','调查','摄影与文本','行为','档案'],subjects:['亲密关系','陌生人','隐私','缺席','记忆','观看'],outputs:['摄影','文本','装置','书籍','录像'],institutions:['Centre Pompidou','Venice Biennale'],achievements:['France Pavilion · Venice Biennale 2007'],whyImportant:'她把“先制定规则，再让现实发生”变成一种极具影响力的创作方法，摄影在其中常作为行动和调查的证据。',projects:[project('1981–1983','L’Hôtel','摄影 / 文本 / 调查',['在威尼斯酒店担任三周客房服务员。','观察客人留下的生活痕迹并结合照片与文字记录。'],'作品同时制造亲密感与无法真正理解陌生人的距离。')],images:[],sourceLabel:'Centre Pompidou',sourceUrl:'https://www.centrepompidou.fr/en/ressources/oeuvre/cqr9Md'},
{id:'awoiska-van-der-molen',name:'Awoiska van der Molen',born:'1972',base:'Amsterdam',intro:'长期独自在偏远自然环境中缓慢拍摄，并在暗房手工制作深黑的大幅银盐照片。',methods:['长期观察','黑白摄影','暗房手工放印','慢速工作'],subjects:['自然','黑暗','时间','孤独','感知'],outputs:['银盐摄影','摄影书','展览'],institutions:['Foam','Deutsche Börse Photography Foundation'],achievements:['Deutsche Börse Photography Prize 2017 入围','Paris Photo–Aperture First PhotoBook Prize 2014 入围'],whyImportant:'她代表了一条与高速数字图像相反的摄影路径：拍摄和暗房都建立在长时间、重复返回和视觉适应上。',projects:[project('2014','Sequester','黑白风景 / 摄影书',['长期进入偏远自然环境拍摄。','作品以手工 gelatin silver / baryta prints 呈现。'],'黑暗不是单纯风格，而是要求观看者重新适应照片内部的微弱层次。')],images:[],sourceLabel:'Foam',sourceUrl:'https://www.foam.org/events/awoiska-van-der-molen'},
{id:'boris-mikhailov',name:'Boris Mikhailov',born:'1938',base:'Kharkiv / Berlin',intro:'从苏联地下摄影到后苏联社会现实，以快照、手工着色、序列和直接纪实不断挑战摄影的体面与官方叙事。',methods:['纪实摄影','快照','手工着色','系列编辑','社会观察'],subjects:['苏联','后苏联社会','贫困','身体','日常生活','政治'],outputs:['摄影','摄影书','系列装置'],institutions:['MoMA','Tate'],achievements:['Hasselblad Award 2000','Kaiser Ring 2015'],whyImportant:'他把私人快照、社会边缘人物和粗粝的摄影语言带入当代艺术，是理解东欧摄影、后苏联社会与摄影伦理的重要人物。',projects:[project('1997–1998','Case History','社会纪实 / 摄影书',['在后苏联 Kharkiv 拍摄无家可归和社会边缘群体。','以大量直接、身体化的图像构成系列。'],'作品迫使观看者面对社会转型的暴力，同时持续引发关于观看与摄影伦理的讨论。')],images:[],sourceLabel:'MoMA',sourceUrl:'https://www.moma.org/artists/8168-boris-mikhailov'}
];
