import type { Artist } from './data';
import { artistBatch120 } from './expansionBatch120';

export const artistBatch119: Artist[] = [
{id:'doris-salcedo',name:'Doris Salcedo',born:'1958',base:'Colombia',intro:'哥伦比亚艺术家，以家具、衣物、建筑介入和雕塑处理政治暴力、失踪、哀悼与幸存者证词，将私人见证转译为克制的物质结构。',methods:['证词研究','物件转化','纪念性介入','材料隐喻'],subjects:['政治暴力','失踪','哀悼','记忆','哥伦比亚冲突'],outputs:['雕塑','装置','建筑介入'],institutions:['MoMA','Tate Modern'],achievements:['Atrabilious','Widowed House','Shibboleth'],whyImportant:'Salcedo把政治暴力从新闻式再现转向缺席、痕迹与哀悼的物质经验，是拉丁美洲当代雕塑与记忆政治的核心艺术家。',projects:[{year:'1992–93',title:'Atrabilious',type:'墙面装置 / 失踪者纪念',facts:['作品以胶合板、鞋、牛膀胱和外科缝线构成六个壁龛。','旧女鞋指向哥伦比亚冲突中的失踪者，半透明膜使其呈现如旧照片或遗物般的状态。'],reading:'她不直接展示暴力场面，而让缺席者通过日常物件留下难以消除的物质痕迹。'}],images:[],sourceLabel:'MoMA · Doris Salcedo',sourceUrl:'https://www.moma.org/artists/7488-doris-salcedo'},
{id:'oscar-munoz',name:'Oscar Muñoz',born:'1951',base:'Colombia',intro:'哥伦比亚艺术家，以摄影、版画、录像和易逝材料研究肖像如何出现、消失和被记忆，持续拆解摄影作为稳定记录的假设。',methods:['图像消逝','材料实验','摄影解构','过程性图像'],subjects:['记忆','死亡','肖像','消失','再现'],outputs:['摄影','版画','录像','装置'],institutions:['MoMA'],achievements:['Narcisos','Dried Narcissus','The Game of Probabilities'],whyImportant:'Muñoz把摄影从固定图像转化成蒸发、干燥、破裂和重新组合的过程，使记忆的不稳定性直接发生在作品材料内部。',projects:[{year:'1994–ongoing',title:'Narcisos',type:'过程摄影 / 自画像实验',facts:['系列长期围绕自画像、液体表面与图像变化展开。','MoMA收藏其Narcisos in Progress及Dried Narcissus相关作品。'],reading:'肖像不再保证一个人的持续存在，而成为随材料状态不断生成和消退的临时事件。'}],images:[],sourceLabel:'MoMA · Oscar Muñoz',sourceUrl:'https://www.moma.org/artists/41797-oscar-munoz'},
{id:'graciela-iturbide',name:'Graciela Iturbide',born:'1942',base:'Mexico',intro:'墨西哥摄影家，以长期进入社区、旅行和黑白摄影观察原住民生活、仪式、性别、死亡与墨西哥社会中的象征系统，强调关系建立先于猎取图像。',methods:['长期观察','社区进入','黑白纪实','象征性瞬间'],subjects:['原住民社区','仪式','性别','死亡','墨西哥社会'],outputs:['摄影'],institutions:['MoMA'],achievements:['Mujer ángel','Juchitán de las Mujeres','Mexico'],whyImportant:'Iturbide把纪实摄影从外部民族志凝视推向长期关系与复杂象征并存的实践，是墨西哥及拉丁美洲摄影史的重要节点。',projects:[{year:'1979',title:'Mujer ángel, Desierto de Sonora',type:'黑白摄影 / 社区观察',facts:['作品拍摄于墨西哥索诺拉沙漠。','MoMA馆藏版本为银盐照片，并长期进入其摄影收藏与展览体系。'],reading:'传统服饰、荒漠与现代消费物件同时进入画面，使文化身份呈现为持续变化而非静止的民族志对象。'}],images:[],sourceLabel:'MoMA · Graciela Iturbide',sourceUrl:'https://www.moma.org/artists/2844-graciela-iturbide'},
{id:'regina-jose-galindo',name:'Regina José Galindo',born:'1974',base:'Guatemala',intro:'危地马拉行为艺术家，以自身身体作为政治暴力、性别暴力、国家权力和历史创伤的直接承载体，通过高度压缩的行为结构制造见证现场。',methods:['身体介入','极限行为','政治见证','计数结构'],subjects:['性别暴力','国家暴力','历史创伤','女性身体','危地马拉'],outputs:['行为','录像','摄影'],institutions:['La Biennale di Venezia'],achievements:['¿Quién puede borrar las huellas?','( ) Golpes','Golden Lion for Artists under 35 — Venice Biennale 2005'],whyImportant:'Galindo将中美洲内战遗产与当代针对女性的暴力直接写入身体，是拉丁美洲政治行为艺术与女性主义实践的重要代表。',projects:[{year:'2005',title:'( ) Golpes',type:'行为 / 声音',facts:['作品在第51届威尼斯双年展Arsenale实施。','艺术家隐藏在白色立方体中，以394次鞭击对应2004至2005年间危地马拉被杀害的女性数量。'],reading:'观众无法观看身体，只能听见击打声，统计数字由此转化为持续的身体时间和不可回避的听觉见证。'}],images:[],sourceLabel:'La Biennale di Venezia · ( ) Golpes',sourceUrl:'https://asac.labiennale.org/attivita/arti-visive/46441'},
...artistBatch120
];