import type { Artist } from './data';

const project = (year: string, title: string, type: string, facts: string[], reading: string) => ({ year, title, type, facts, reading });

export const artistBatch36: Artist[] = [
  { id:'nan-goldin', name:'Nan Goldin', born:'1953', base:'New York / Berlin', intro:'以朋友、恋人和自身生活为长期对象，用快照式摄影与幻灯片序列记录亲密关系、酷儿社群、暴力、失落与生存。', methods:['长期自传式摄影','快照美学','幻灯片序列','社群内部观察'], subjects:['亲密关系','酷儿社群','AIDS','家庭暴力','成瘾','记忆'], outputs:['摄影','幻灯片装置','摄影书'], institutions:['MoMA','Whitney Museum','Tate'], achievements:['The Ballad of Sexual Dependency · MoMA 2016–2017'], whyImportant:'她把私人生活的内部视角变成当代摄影的重要公共语言，并证明摄影系列可以像不断重排的日记、音乐与现场表演一样运作。', projects:[project('1980s–','The Ballad of Sexual Dependency','幻灯片 / 自传式摄影',['由数百张朋友、恋人与艺术家自身的照片组成。','作品长期以配乐幻灯片形式演出并持续重排。'],'关键不是单张经典照片，而是生活共同体如何通过连续图像获得自己的时间和叙事。')], images:[], sourceLabel:'MoMA', sourceUrl:'https://www.moma.org/artists/7532-nan-goldin' },
  { id:'martha-rosler', name:'Martha Rosler', born:'1943', base:'New York', intro:'跨摄影、拼贴、录像、表演、写作和社会实践，持续分析战争、家庭空间、性别、消费与公共生活之间的政治关系。', methods:['摄影蒙太奇','挪用','录像','社会实践','制度批判'], subjects:['战争','媒体','女性主义','家庭空间','消费','公共领域'], outputs:['摄影蒙太奇','录像','装置','表演','文本'], institutions:['MoMA','Whitney Museum','Tate'], achievements:['Meta-Monumental Garage Sale · MoMA 2012'], whyImportant:'她把大众媒体图像重新剪接成政治分析工具，是理解摄影挪用、女性主义影像与“私人空间如何连接全球政治”的基础人物。', projects:[project('1967–1972','House Beautiful: Bringing the War Home','摄影蒙太奇',['把越战新闻照片与美国室内设计和消费广告图像拼接。','早期版本曾以复印件形式在反战语境传播。'],'作品直接拆穿“远方战争”和“安稳家庭”之间的视觉隔离。')], images:[], sourceLabel:'MoMA', sourceUrl:'https://www.moma.org/artists/6832-martha-rosler' },
  { id:'allan-sekula', name:'Allan Sekula', born:'1951–2013', base:'Los Angeles', intro:'把摄影、文本、录像和长期研究结合起来，分析劳动、港口、海运、全球资本与摄影自身的政治经济。', methods:['摄影与文本','长期研究','批判纪录','档案研究','影像论文'], subjects:['劳动','全球化','海运','阶级','资本','摄影政治'], outputs:['摄影','文本','录像','摄影书','装置'], institutions:['Tate','Documenta'], achievements:['Fish Story · 1989–1995'], whyImportant:'他把纪实摄影从“拍社会问题”推进到研究图像、劳动与全球经济结构如何彼此组织，对研究型摄影和摄影理论影响极大。', projects:[project('1989–1995','Fish Story','摄影 / 文本 / 全球化研究',['围绕港口、船运和海上劳动进行多年跨国研究。','摄影与长篇文本共同构成作品。'],'海洋不再是浪漫景观，而成为全球商品流通与被隐藏劳动的基础设施。')], images:[], sourceLabel:'Tate', sourceUrl:'https://www.tate.org.uk/art/artists/allan-sekula-1928' },
  { id:'hank-willis-thomas', name:'Hank Willis Thomas', born:'1976', base:'New York', intro:'通过摄影、广告挪用、雕塑和公共艺术研究种族、体育、消费文化以及大众视觉如何制造身份。', methods:['广告挪用','摄影','文本图像','公共艺术','雕塑'], subjects:['种族','广告','体育','消费','身份','大众媒体'], outputs:['摄影','雕塑','装置','公共艺术'], institutions:['Guggenheim','Whitney Museum','International Center of Photography'], achievements:['The Writing on the Wall · 2019–'], whyImportant:'他把商业广告中看似自然的身体和消费符号重新编码，使种族与商品化机制直接显形，是连接摄影、视觉文化研究与公共艺术的重要节点。', projects:[project('2006–','Unbranded','广告档案 / 挪用摄影',['从历史广告中移除品牌标识或重新编排广告图像。','通过连续年代结构研究黑人形象与商业传播。'],'重点是广告如何在品牌之外仍携带关于种族、欲望和社会角色的编码。')], images:[], sourceLabel:'Guggenheim', sourceUrl:'https://www.guggenheim.org/artwork/artist/hank-willis-thomas' }
];
