import type { Artist } from './data';
import { artistBatch81 } from './expansionBatch81';

export const artistBatch80: Artist[] = [
  ...artistBatch81,
  {id:'bouchra-khalili',name:'Bouchra Khalili',born:'1975',base:'Morocco / France / Austria',intro:'以录像、地图、声音、摄影和版画发展协作式叙事，长期研究迁徙、无国籍状态、公民身份与被排除群体如何取得发言位置。',methods:['协作式叙事','长期倾听','地图实践','单镜头录像'],subjects:['迁徙','公民身份','无国籍','边界','政治主体性'],outputs:['录像','装置','摄影','丝网版画'],institutions:['La Biennale di Venezia'],achievements:['The Mapping Journey Project','Biennale Arte 2013','Biennale Arte 2024'],whyImportant:'Khalili把迁徙影像从替他者发言转向由参与者自行组织和表演叙事，以地图、声音和手势建立关于公民身份与政治主体性的影像语言。',projects:[{year:'2008–11',title:'The Mapping Journey Project / The Constellations Series',type:'录像装置 / 丝网版画',facts:['八段录像以固定长镜头记录参与者在地图上画出自己的迁徙路线。','Constellations Series把这些路线转译为八幅星座式丝网版画。','两组作品进入Biennale Arte 2024。'],reading:'地图不再只是国家划界工具，而成为无国籍者重新讲述自身路线、时间与归属的表面。'}],images:[],sourceLabel:'La Biennale di Venezia · Bouchra Khalili',sourceUrl:'https://www.labiennale.org/en/art/2024/nucleo-contemporaneo/bouchra-khalili'},
  {id:'mounira-al-solh',name:'Mounira Al Solh',born:'1978',base:'Lebanon / Netherlands',intro:'跨绘画、素描、刺绣、录像与装置工作，以口述历史、家庭与迁徙经验、女性处境和神话重写连接私人叙事与中东政治现实。',methods:['口述历史','叙事绘画','神话重写','跨媒介装置'],subjects:['迁徙','女性','家庭','战争','神话','中东'],outputs:['绘画','素描','刺绣','录像','雕塑','装置'],institutions:['La Biennale di Venezia','Lebanon Pavilion'],achievements:['Lebanon Pavilion · Biennale Arte 2024','A Dance with her Myth'],whyImportant:'Al Solh把个人故事、口述记忆与历史神话放进同一叙事系统，让宏观战争、流离失所与性别政治通过具体人物和手工媒介被重新讲述。',projects:[{year:'2024',title:'A Dance with her Myth',type:'多媒体装置',facts:['作为2024威尼斯双年展黎巴嫩馆参展艺术家。','装置结合绘画、素描、雕塑、刺绣与录像。','作品重新解释腓尼基公主Europa被Zeus掳走的神话。'],reading:'对Europa神话的改写把被动的女性角色转化为能够重新定义自身命运的主体，并把古代叙事连接到当代自由、平等与女性解放。'}],images:[],sourceLabel:'La Biennale di Venezia · Lebanon Pavilion 2024',sourceUrl:'https://www.labiennale.org/en/art/2024/lebanon'},
  {id:'sammy-baloji',name:'Sammy Baloji',born:'1978',base:'Democratic Republic of the Congo / Belgium',intro:'以摄影、档案拼贴、录像、雕塑和研究型装置追踪刚果采矿史、殖民主义遗产、资源开采与非洲文化物如何进入欧洲博物馆体系。',methods:['档案再利用','研究型实践','摄影拼贴','文化归还研究'],subjects:['殖民主义','采矿','资源开采','刚果','博物馆','文化归还'],outputs:['摄影','拼贴','录像','雕塑','装置'],institutions:['Centre Pompidou','La Biennale di Venezia'],achievements:['Pauwel’s Album','Biennale Architettura 2023','Biennale Arte 2026'],whyImportant:'Baloji把刚果的矿业基础设施、殖民档案与博物馆收藏史连接起来，使摄影和材料研究成为理解全球资本、资源开采及文化掠夺长期结构的工具。',projects:[{year:'2013',title:'Pauwel’s Album',type:'摄影 / 档案系列',facts:['Centre Pompidou摄影收藏保存该系列多件喷墨作品。','系列重新处理殖民时期关于刚果人物、动物与景观的影像分类。'],reading:'通过重新组织殖民档案，作品暴露摄影分类、知识生产与殖民权力之间的关系。'},{year:'2023',title:'Aequare: the Future that Never Was',type:'录像 / 档案研究装置',facts:['在Biennale Architettura 2023展出。','结合Yangambi农业中心的现场研究影像与殖民时期档案。'],reading:'殖民农业和建筑现代化被重新放回土地、生态和前殖民社会系统被改变的历史中。'}],images:[],sourceLabel:'La Biennale di Venezia · Sammy Baloji',sourceUrl:'https://www.labiennale.org/en/art/2026/sammy-baloji'},
  {id:'joana-choumali',name:'Joana Choumali',born:'',base:'Côte d’Ivoire',intro:'以肖像、街头观察、纺织与手工刺绣处理西非身份、记忆、创伤和城市经验，并持续反思殖民摄影与民族志式观看留下的视觉框架。',methods:['肖像摄影','长期观察','摄影刺绣','手工干预'],subjects:['西非','身份','记忆','传统','创伤','城市'],outputs:['摄影','摄影书','刺绣摄影','混合媒介'],institutions:['Aperture'],achievements:['Hââbré: The Last Generation'],whyImportant:'Choumali一方面记录正在消失的西非身体传统，另一方面以刺绣等手工过程重新进入摄影表面，使肖像从民族志式分类转向更具主体性、时间性和个人记忆的表达。',projects:[{year:'2013–14',title:'Hââbré: The Last Generation',type:'肖像摄影系列',facts:['在阿比让拍摄具有面部疤痕传统的西非人物。','系列讨论西非逐渐消退的面部疤痕习俗。','Aperture在非洲当代肖像与摄影书专题中讨论该项目。'],reading:'正面与背面肖像既保存身体传统，也迫使观看者反思民族志摄影如何曾经把非洲身体变成可分类的对象。'}],images:[],sourceLabel:'Aperture · Joana Choumali / African photography',sourceUrl:'https://aperture.org/editorial/marrakech-african-photography/'},
  {id:'nour-jaouda',name:'Nour Jaouda',born:'1997',base:'Libya / Egypt / United Kingdom',intro:'以拆解、染色和重新缝合织物制作雕塑性挂毯，从家族记忆、植物和迁徙经验讨论失根、韧性、毁坏与再生。',methods:['织物拆解','天然染色','重新缝合','雕塑性纺织'],subjects:['记忆','迁徙','植物','失根','韧性','再生'],outputs:['纺织','装置','雕塑性挂毯'],institutions:['La Biennale di Venezia'],achievements:['Biennale Arte 2024'],whyImportant:'Jaouda代表年轻一代把纺织从工艺边界带入当代大型装置的实践，并通过材料自身的拆解与再缝合，把迁徙和记忆转化为可触摸的结构。',projects:[{year:'2024',title:'Biennale Arte 2024 textile works',type:'手工染色纺织 / 雕塑性挂毯',facts:['2024年首次参加威尼斯双年展。','三件纺织作品由艺术家祖母在班加西的无花果树触发。','制作过程包括拆布、以土地色调染色并重新缝合。'],reading:'树木、布料和缝合共同承担记忆载体的角色；材料经历破坏与重组，对应离散经验中的失根与再生。'}],images:[],sourceLabel:'La Biennale di Venezia · Nour Jaouda',sourceUrl:'https://www.labiennale.org/en/art/2024/nucleo-contemporaneo/nour-jaouda'}
];
