import type { Artist } from './data';
import { artistBatch79 } from './expansionBatch79';

export const artistBatch78: Artist[] = [
  ...artistBatch79,
  {id:'ming-smith',name:'Ming Smith',born:'1949',base:'United States',intro:'以低照度、模糊、长曝光和富有音乐性的黑白摄影表现黑人日常生活、爵士文化与可见性问题。',methods:['街头摄影','长曝光','运动模糊','直觉式摄影'],subjects:['黑人生活','爵士','城市','可见性','日常'],outputs:['摄影','手工着色摄影'],institutions:['MoMA','Kamoinge Workshop'],achievements:['Projects: Ming Smith · MoMA 2023','Kamoinge Workshop member'],whyImportant:'Smith把技术上的模糊、暗部和运动转化为黑人经验与视觉诗性的语言，是Kamoinge传统及美国黑人摄影史的重要节点。',projects:[{year:'1991',title:'Invisible Man, Somewhere, Everywhere',type:'摄影系列',facts:['受Ralph Ellison《Invisible Man》启发，围绕被看见与不可见展开。','MoMA收藏该系列多个版本。'],reading:'画面以模糊、阴影和运动拒绝摄影必须清晰说明主体的惯例，把可见性本身变成主题。'}],images:[],sourceLabel:'MoMA · Ming Smith',sourceUrl:'https://www.moma.org/artists/7906-ming-smith'},
  {id:'santu-mofokeng',name:'Santu Mofokeng',born:'1956–2020',base:'South Africa',intro:'从南非反种族隔离时期的纪实摄影出发，长期研究黑人日常、宗教、土地、记忆与精神景观。',methods:['社会纪实','摄影散文','长期观察','黑白摄影'],subjects:['种族隔离','黑人日常','宗教','土地','记忆'],outputs:['摄影','摄影散文','出版'],institutions:['MoMA'],achievements:['Train Church','Black Photo Album / Look at Me: 1890–1950'],whyImportant:'Mofokeng把政治纪实从事件新闻推进到日常、精神经验和历史记忆，是南非摄影从抗争记录走向复杂作者性实践的关键人物。',projects:[{year:'1986',title:'Train Church',type:'黑白摄影系列',facts:['记录Johannesburg–Soweto通勤列车上形成的宗教礼拜。','MoMA收藏该系列多件作品。'],reading:'通勤基础设施被拍成临时精神空间，使种族隔离制度下的日常移动与宗教共同体重叠。'}],images:[],sourceLabel:'MoMA · Santu Mofokeng',sourceUrl:'https://www.moma.org/artists/72440-santu-mofokeng'},
  {id:'lebohang-kganye',name:'Lebohang Kganye',born:'1990',base:'South Africa',intro:'以家庭相册、口述史、剪影、戏剧布景和移动影像重构南非家庭微观史，并讨论殖民主义与种族隔离留下的记忆断裂。',methods:['档案重构','家庭相册再演','口述史','戏剧化场景'],subjects:['家庭','祖先','记忆','种族隔离','殖民主义'],outputs:['摄影','剪影装置','录像','表演'],institutions:['Foam','La Biennale di Venezia'],achievements:['Foam Paul Huf Award 2022','South Africa Pavilion · Biennale Arte 2022'],whyImportant:'Kganye把私人家庭档案转化为可表演、可搭建的历史空间，在摄影、戏剧与口述传统之间建立了鲜明的南非当代视觉语言。',projects:[{year:'2022',title:'Mosebetsi wa Dirithi',type:'摄影 / 剪影 / 戏剧化装置',facts:['作品延续其以家庭故事、南非文学和口述传统为材料的方法。','Foam 2023个展将其置于十年实践脉络中展示。'],reading:'照片不再只是过去的证据，而成为可以重新搭建、表演和填补记忆空缺的舞台。'}],images:[],sourceLabel:'Foam · Lebohang Kganye',sourceUrl:'https://www.foam.org/artists/lebohang-kganye'},
  {id:'mame-diarra-niang',name:'Mame-Diarra Niang',born:'1982',base:'France / Senegal',intro:'以摄影中的模糊、抽象与“非肖像”研究自我、记忆、遗忘以及身份不断生成的状态。',methods:['非肖像','抽象摄影','失焦','色彩实验'],subjects:['自我','记忆','遗忘','身份','梦'],outputs:['摄影','摄影系列'],institutions:['MoMA'],achievements:['Sama Guent Guii','MoMA collection'],whyImportant:'Niang主动削弱肖像的识别功能，把人物变成流动的色彩与形态，使当代黑人肖像从身份再现进一步转向不稳定的主体经验。',projects:[{year:'2021',title:'Sama Guent Guii',type:'摄影系列',facts:['标题来自Wolof语，意为“我做的这个梦”。','MoMA收藏该系列五件作品。'],reading:'人物在失焦中趋向抽象，摄影不再固定身份，而用记忆与擦除表现不断变化的自我。'}],images:[],sourceLabel:'MoMA · Mame-Diarra Niang',sourceUrl:'https://www.moma.org/artists/136899-mame-diarra-niang'},
  {id:'awoiska-van-der-molen',name:'Awoiska van der Molen',born:'1972',base:'Netherlands',intro:'以长期独处、缓慢观察和手工暗房制作拍摄无人自然景观，以极深黑白层次探索时间、黑暗与感知。',methods:['长期驻留','慢摄影','暗房手工放大','黑白景观'],subjects:['自然','孤独','时间','黑暗','感知'],outputs:['摄影','银盐手工放大'],institutions:['Foam'],achievements:['Blanco · Foam 2016','Deutsche Börse Photography Prize nominee 2017'],whyImportant:'Van der Molen把当代景观摄影从地理记录转向身体性的观看经验，并坚持以暗房工艺让黑暗、材质和观看时间成为作品结构。',projects:[{year:'2014',title:'Sequester',type:'摄影书 / 黑白景观系列',facts:['汇集其在偏远自然环境中长期工作的黑白摄影。','该书获Paris Photo–Aperture First PhotoBook Prize提名。'],reading:'无人景观和深黑银盐层次削弱具体地点，使自然更接近一种缓慢、无法立即辨识的感知经验。'}],images:[],sourceLabel:'Foam · Awoiska van der Molen',sourceUrl:'https://www.foam.org/events/awoiska-van-der-molen'},
  {id:'daisuke-yokota',name:'Daisuke Yokota',born:'1983',base:'Japan',intro:'以反复复制、扫描、暗房化学实验、无相机摄影和装置不断破坏与再生成图像，研究摄影的物质性。',methods:['暗房实验','图像再复制','无相机摄影','化学干预'],subjects:['摄影物质性','记忆','复制','时间','图像退化'],outputs:['摄影','艺术家书','装置','表演'],institutions:['Foam','SFMOMA'],achievements:['Foam Talent 2013','Foam Paul Huf Award 2016'],whyImportant:'Yokota把数字与模拟流程反复叠加，使噪点、损耗和化学偶然性成为创作主体，是日本新一代实验摄影及后摄影实践的重要节点。',projects:[{year:'2017',title:'Matter',type:'摄影装置 / 暗房实验',facts:['Foam个展包含直接曝光胶卷、现场上蜡和非传统显影实验。','展览源于其2016 Foam Paul Huf Award。'],reading:'作品把摄影从墙上的单张图像扩展为材料、化学过程、打印机器与空间共同生成的事件。'}],images:[],sourceLabel:'Foam · Daisuke Yokota',sourceUrl:'https://www.foam.org/artists/daisuke-yokota'}
];
