import type { Artist } from './data';
import { artistBatch182 } from './expansionBatch182';

export const artistBatch181: Artist[] = [
{id:'allan-sekula',name:'Allan Sekula',born:'1951–2013',base:'United States',intro:'美国摄影艺术家、写作者与批评家，以摄影、文本和长期调查研究劳动、海运、全球资本主义与摄影的政治经济。',methods:['调查摄影','摄影与文本','长期田野研究','批判写作'],subjects:['全球化','海运','劳动','资本主义','港口','摄影政治'],outputs:['摄影','文本','装置','出版'],institutions:['MoMA'],achievements:['Fish Story 1989–1995','MoMA collection'],whyImportant:'Sekula把纪实摄影从单幅社会记录推进为摄影、文字、档案与经济研究组成的系统，是理解当代调查摄影、劳动图像与全球物流视觉研究的重要节点。',projects:[{year:'1989–1995',title:'Fish Story',type:'长期摄影与文本项目',facts:['围绕港口、海员、造船与全球海运展开跨国摄影和研究，MoMA收藏系列作品。'],reading:'把通常不可见的海运劳动和全球资本流动重新放回摄影的可见空间。'}],images:[],sourceLabel:'MoMA · Allan Sekula, Fish Story',sourceUrl:'https://www.moma.org/collection/works/164233'},
{id:'taryn-simon',name:'Taryn Simon',born:'1975',base:'United States',intro:'美国艺术家，以摄影、文本、图形设计和大规模研究系统调查国家制度、分类、血缘、司法错误以及被隐藏的空间和知识。',methods:['研究型摄影','摄影与文本','系统分类','档案建构'],subjects:['制度','司法','血缘','国家秘密','分类','可见性'],outputs:['摄影','文本','装置','出版'],institutions:['MoMA','MoMA PS1','Guggenheim'],achievements:['The Innocents, MoMA PS1 2003','A Living Man Declared Dead and Other Chapters I–XVIII, MoMA 2012'],whyImportant:'Simon把摄影与文字、分类和调查研究置于同等位置，使摄影不只是图像而成为揭示制度如何生产事实、证据与不可见性的知识系统。',projects:[{year:'2002',title:'The Innocents',type:'调查摄影项目',facts:['拍摄因错误识别而被错误定罪、后经DNA证据平反的人，并于2003年在MoMA PS1展出。'],reading:'作品反向追问摄影作为证据和身份识别工具为何也会制造司法错误。'},{year:'2008–2011',title:'A Living Man Declared Dead and Other Chapters I–XVIII',type:'摄影、文本与图形系统',facts:['四年间在全球记录不同血缘及其相关故事，以肖像、文字和脚注图像组成十八章。'],reading:'血缘、国家档案与政治事件被组织成一套关于分类和命运的视觉数据库。'}],images:[],sourceLabel:'MoMA · Taryn Simon',sourceUrl:'https://www.moma.org/artists/41212-taryn-simon'},
{id:'dawoud-bey',name:'Dawoud Bey',born:'1953',base:'United States',intro:'美国摄影艺术家，以街头肖像、大画幅合作式肖像和历史景观持续研究黑人主体、社区、美国种族史以及摄影再现的伦理。',methods:['合作式肖像','街头摄影','历史重访','景观摄影'],subjects:['黑人社区','种族','美国历史','青年','记忆','可见性'],outputs:['摄影','录像','出版'],institutions:['Whitney Museum','MoMA','SFMOMA'],achievements:['Whitney Biennial 2000 and 2014','Dawoud Bey: An American Project, Whitney 2021','MacArthur Fellowship 2017'],whyImportant:'Bey把黑人日常生活的复杂性、被压抑的历史和摄影者对被摄者的伦理责任连接起来，是美国当代肖像与历史摄影的重要人物。',projects:[{year:'1975–1979',title:'Harlem, U.S.A.',type:'街头肖像系列',facts:['在Harlem近距离拍摄居民，并于1979年在Studio Museum in Harlem展出。'],reading:'以复杂个体取代对黑人社区的刻板视觉类型。'},{year:'2012',title:'The Birmingham Project',type:'历史记忆肖像',facts:['以双联肖像纪念1963年伯明翰种族暴力中遇害的六名黑人儿童。'],reading:'把历史年龄与当下身体并置，使未能活过的人生在摄影结构中重新出现。'}],images:[],sourceLabel:'Whitney Museum · Dawoud Bey',sourceUrl:'https://whitney.org/exhibitions/dawoud-bey'},
{id:'susan-meiselas',name:'Susan Meiselas',born:'1948',base:'United States',intro:'美国摄影师，以长期纪实、返回现场、口述历史与社区协作处理战争、革命、人权、性工作与库尔德历史，并持续反思新闻摄影图像离开事件后的生命。',methods:['长期纪实','返回现场','口述历史','社区协作'],subjects:['革命','战争','人权','尼加拉瓜','库尔德历史','记忆'],outputs:['摄影','书籍','电影','档案项目','公共展示'],institutions:['MoMA','Magnum Photos'],achievements:['Nicaragua 1978–1979','Kurdistan / akaKURDISTAN','MoMA collection'],whyImportant:'Meiselas不断追踪照片拍摄之后发生什么，把摄影从一次性的见证扩展为与被摄者、历史记忆和社区持续协商的长期实践。',projects:[{year:'1978–1979',title:'Nicaragua',type:'革命纪实摄影',facts:['记录尼加拉瓜反索摩查起义；1990年返回寻找照片中的人物并收集他们的证词。'],reading:'纪实图像被重新带回历史现场，与后来记忆发生碰撞。'},{year:'2004',title:'Reframing History',type:'社区公共展示',facts:['在革命二十五周年时与当地社区合作，把历史照片以大型壁画形式安装回原拍摄地点。'],reading:'照片从媒体档案重新进入事件发生的公共空间。'}],images:[],sourceLabel:'MoMA · Susan Meiselas',sourceUrl:'https://www.moma.org/collection/artists/45094'},
{id:'martha-rosler',name:'Martha Rosler',born:'1943',base:'United States',intro:'美国艺术家，以摄影蒙太奇、录像、文本和社会介入批判战争媒体、消费文化、家庭空间、性别劳动与城市政治。',methods:['摄影蒙太奇','挪用','录像表演','社会批判'],subjects:['战争','媒体','家庭空间','消费主义','女性主义','城市'],outputs:['摄影蒙太奇','录像','文本','装置'],institutions:['MoMA'],achievements:['House Beautiful: Bringing the War Home c.1967–72','MoMA collection'],whyImportant:'Rosler把新闻战争图像与消费广告和家庭内部并置，揭示遥远政治暴力如何嵌入日常消费视觉，是女性主义观念艺术、挪用摄影与媒体批判的重要先驱。',projects:[{year:'c.1967–1972',title:'House Beautiful: Bringing the War Home',type:'摄影蒙太奇系列',facts:['把越南战争新闻照片与美国富裕家庭杂志图像拼接，并曾以复印件形式在反战示威中传播。'],reading:'所谓远方战争被直接嵌入舒适客厅，暴露媒体、消费与政治暴力之间的结构联系。'}],images:[],sourceLabel:'MoMA · Martha Rosler, Bringing the War Home',sourceUrl:'https://www.moma.org/collection/works/51136'},
...artistBatch182
];