import type { Artist } from './data';

const p=(year:string,title:string,type:string,facts:string[],reading:string)=>({year,title,type,facts,reading});

export const artistBatch43: Artist[] = [
  {id:'samuel-fosso',name:'Samuel Fosso',born:'1962',base:'Central African Republic / France',intro:'以自我肖像、角色扮演与摄影棚传统重构非洲及黑人离散历史中的政治与文化形象。',methods:['自我表演','编排肖像','角色扮演','摄影棚摄影'],subjects:['身份','非洲历史','黑人离散','政治图像','表演'],outputs:['摄影','肖像系列'],institutions:['MoMA'],achievements:['MoMA collection'],whyImportant:'他把商业摄影棚的自我肖像转化为历史角色扮演，使肖像同时成为身份实验和政治图像史的再演。',projects:[p('2008','African Spirits','自我肖像系列',['艺术家扮演非洲及黑人离散政治、思想和文化人物。','MoMA 收藏该系列多件作品。'],'重点不是模仿名人，而是通过身体重新进入被广泛传播的历史肖像。')],images:[],sourceLabel:'MoMA',sourceUrl:'https://www.moma.org/artists/67095-samuel-fosso'},
  {id:'ming-smith',name:'Ming Smith',born:'—',base:'United States',intro:'以低照度、运动模糊、长曝光和富有音乐性的街头与人物摄影记录黑人生活、表演与城市经验。',methods:['街头摄影','低照度摄影','长曝光','运动模糊','肖像'],subjects:['黑人生活','城市','音乐','表演','身体','日常'],outputs:['摄影'],institutions:['Whitney Museum'],achievements:['Whitney collection','Kamoinge Workshop'],whyImportant:'她把技术上常被视为失误的模糊、暗部和运动转化为感知语言，并把黑人都市生活从新闻式记录推进到主观、诗性的摄影表达。',projects:[p('1978','Sun Ra, Space II, New York','摄影',['在低照度现场以模糊与运动表现 Sun Ra 的舞台能量。','作品进入 Whitney 收藏。'],'观看时可把模糊理解为时间和音乐性的痕迹，而非清晰度不足。')],images:[],sourceLabel:'Whitney Museum',sourceUrl:'https://whitney.org/artists/17819'},
  {id:'bouchra-khalili',name:'Bouchra Khalili',born:'1975',base:'Morocco / France / Europe',intro:'通过录像、地图、声音与档案研究迁徙、边界、公民身份以及个体如何以自己的声音叙述政治经验。',methods:['参与式影像','口述史','地图绘制','档案研究','长镜头'],subjects:['迁徙','边界','公民身份','国家','语言','抵抗'],outputs:['录像','多屏装置','摄影','档案'],institutions:['MoMA','Palais de Tokyo','documenta','Venice Biennale'],achievements:['MoMA solo presentation 2016','documenta 14','55th Venice Biennale'],whyImportant:'她把地图从国家权力的工具反转为迁徙者自述路径的界面，使声音、手势和路线共同生产政治主体性。',projects:[p('2008–11','The Mapping Journey Project','八频道录像',['八位迁徙者在地图上以手和永久记号笔描绘自己的旅程。','作品使用长镜头，并让参与者以自己的声音讲述路径。'],'地图上的官方边界与真实移动轨迹之间的冲突就是作品结构。')],images:[],sourceLabel:'MoMA',sourceUrl:'https://www.moma.org/artists/47100-bouchra-khalili'},
  {id:'kader-attia',name:'Kader Attia',born:'1970',base:'Algiers / Berlin / Paris',intro:'以装置、雕塑、档案与研究讨论殖民主义、现代主义、文化挪用以及“修复”在不同社会中的意义。',methods:['研究型装置','档案','材料转化','建筑研究','文化比较'],subjects:['殖民','现代主义','修复','文化记忆','建筑','权力'],outputs:['装置','雕塑','摄影','录像'],institutions:['Guggenheim','documenta','Lyon Biennale'],achievements:['documenta 13','Lyon Biennale 2015'],whyImportant:'他把殖民关系从图像再现推进到知识、建筑和修复观念的交换史，尤其适合连接后殖民研究与材料实践。',projects:[p('2009','Untitled (Ghardaïa)','装置',['以 couscous 塑造阿尔及利亚 Ghardaïa 城市模型。','作品关联 Le Corbusier、殖民史与现代主义建筑影响。'],'它反转“欧洲现代主义影响殖民地”的单向叙事，追踪被殖民文化对现代主义的反向影响。')],images:[],sourceLabel:'Guggenheim',sourceUrl:'https://www.guggenheim.org/map/kader-attia'},
  {id:'jo-ractliffe',name:'Jo Ractliffe',born:'1961',base:'South Africa',intro:'以摄影、版画与长期地景观察追踪南非和安哥拉战争、殖民与政治暴力如何留存在地表和日常空间中。',methods:['长期摄影','地景摄影','档案研究','版画','后冲突观察'],subjects:['战争','殖民','地景','政治暴力','记忆','南部非洲'],outputs:['摄影','版画','摄影书'],institutions:['MoMA'],achievements:['MoMA collection'],whyImportant:'她避免把暴力简化成事件现场，而研究暴力结束后仍残留在道路、空地、市场和基础设施中的历史痕迹。',projects:[p('2007','Terreno Ocupado','摄影系列',['在安哥拉拍摄内战与殖民历史之后的城市和地景。','MoMA 收藏该系列多件作品。'],'她把“后冲突”理解为一种仍可从空间结构读取的持续状态。'),p('1988','Nadir','摄影版画系列',['结合摄影、拼贴、photolithography 与 screenprint。','作品回应南非紧急状态时期的恐惧与国家暴力。'],'早期作品已经显示她如何避免直接重复新闻式抵抗图像。')],images:[],sourceLabel:'MoMA',sourceUrl:'https://www.moma.org/artists/28223-jo-ractliffe'}
];