import type { Artist } from './data';
import { artistBatch93 } from './expansionBatch93';

export const artistBatch92: Artist[] = [
{id:'trevor-paglen',name:'Trevor Paglen',born:'1974',base:'United States / Germany',intro:'美国观念艺术家与地理学者，以摄影、数据研究、人工智能和空间技术调查监控系统、军事基础设施与机器视觉。',methods:['调查式摄影','数据研究','机器视觉研究','技术系统批评'],subjects:['监控','人工智能','军事基础设施','数据','不可见系统'],outputs:['摄影','影像','装置','公共项目'],institutions:['MoMA','Smithsonian American Art Museum'],achievements:['It Began as a Military Experiment','Behold These Glorious Times!','New Order: Art and Technology in the Twenty-First Century'],whyImportant:'Paglen把摄影从记录可见世界推进到追踪通常不可见的军事、数据与算法基础设施，是当代技术图像政治的重要节点。',projects:[{year:'2017',title:'It Began as a Military Experiment',type:'档案与机器视觉摄影',facts:['从美国国防部用于早期人脸识别研究的数据库中选取十幅军事人员照片。','图像上的面部特征标记显示人脸如何被转化为可供算法处理的数据。'],reading:'作品把肖像摄影与机器识别历史连接起来，揭示视觉数据如何进入监控与控制系统。'}],images:[],sourceLabel:'MoMA · Trevor Paglen',sourceUrl:'https://www.moma.org/artists/69988-trevor-paglen'},
{id:'lorna-simpson',name:'Lorna Simpson',born:'1960',base:'United States',intro:'美国艺术家，以摄影与文字、影像、绘画和档案图像持续研究种族、性别、身份、历史记忆以及摄影表征的权力。',methods:['摄影与文字','档案再语境化','观念摄影','图像裁切'],subjects:['种族','性别','黑人身份','历史记忆','表征'],outputs:['摄影','影像','绘画','装置'],institutions:['Whitney Museum of American Art'],achievements:['Counting','2 Tracks','Lorna Simpson: 2007 Whitney survey'],whyImportant:'Simpson通过裁切身体、文字并置和分类系统的不稳定性挑战摄影的客观性，是美国观念摄影与黑人女性主义视觉文化的核心人物。',projects:[{year:'1991',title:'Counting',type:'摄影与文字作品',facts:['将女性身体、历史建筑和头发图像与计数文字组合。','作品通过图像与数量系统连接黑人历史、身体和分类机制。'],reading:'看似客观的计数与摄影证据在作品中变得含混，从而暴露分类和表征背后的历史权力。'}],images:[],sourceLabel:'Whitney · Lorna Simpson',sourceUrl:'https://whitney.org/artists/3452'},
{id:'cao-fei',name:'Cao Fei',born:'1978',base:'China',intro:'中国多媒体艺术家，以录像、摄影、虚拟世界和装置研究快速城市化、制造业、青年亚文化以及现实与数字幻想之间的关系。',methods:['社会观察','虚拟世界构建','影像叙事','流行文化挪用'],subjects:['城市化','制造业','青年文化','虚拟身份','中国社会转型'],outputs:['录像','摄影','装置','网络项目'],institutions:['MoMA','MoMA PS1','Venice Biennale'],achievements:['Whose Utopia','RMB City','COSPlayers','La Town'],whyImportant:'曹斐把中国工业化现实、青年流行文化和网络虚拟空间放在同一视觉系统中，是理解全球化之后中国新媒体艺术的重要节点。',projects:[{year:'2006',title:'Whose Utopia',type:'录像项目',facts:['围绕珠三角工厂环境与工人的现实生活和个人想象展开。','以纪录观察与表演性段落并置工业生产和个体梦想。'],reading:'作品没有把工厂只处理为劳动现场，而是追问全球制造体系中的个人欲望与想象空间。'}],images:[],sourceLabel:'MoMA PS1 · Cao Fei',sourceUrl:'https://www.moma.org/calendar/exhibitions/4945'},
{id:'tania-bruguera',name:'Tania Bruguera',born:'1968',base:'Cuba / United States',intro:'古巴艺术家，以行为、装置、社会参与和“Arte Útil”实践研究国家权力、审查、公民身份、移民与艺术的政治效力。',methods:['行为艺术','社会参与','制度介入','Arte Útil'],subjects:['政治权力','审查','公民身份','移民','人权'],outputs:['行为','装置','影像','社会项目'],institutions:['MoMA','MoMA PS1','Venice Biennale','Documenta'],achievements:['Untitled (Havana, 2000)','Cátedra Arte de Conducta','Arte Útil'],whyImportant:'Bruguera把政治从作品的表现主题转化为观众实际进入的行为和制度条件，是拉丁美洲社会参与艺术与政治行为艺术的关键人物。',projects:[{year:'2000',title:'Untitled (Havana, 2000)',type:'行为与录像装置',facts:['为第七届哈瓦那双年展创作，以甘蔗渣、录像、现场表演和黑暗空间构成感官环境。','作品讨论古巴公民与权威之间的关系，并在展出后很快遭到关闭。'],reading:'作品不只是再现政治，而通过身体、空间与观众行为直接制造权力关系的体验。'}],images:[],sourceLabel:'MoMA · Tania Bruguera',sourceUrl:'https://www.moma.org/artists/48122-tania-bruguera'},
...artistBatch93
];
