import type { Artist } from './data';

const project = (year:string,title:string,type:string,facts:string[],reading:string) => ({year,title,type,facts,reading});

export const artistBatch37: Artist[] = [
{id:'william-kentridge',name:'William Kentridge',born:'1955',base:'Johannesburg',intro:'以素描、擦除动画、版画、表演与剧场处理南非历史、种族隔离、记忆与政治暴力。',methods:['擦除动画','素描','版画','剧场','影像装置'],subjects:['南非','种族隔离','记忆','政治','历史'],outputs:['动画电影','素描','版画','装置','表演'],institutions:['MoMA','Tate','Documenta','Venice Biennale'],achievements:['MoMA · William Kentridge: Five Themes 2010'],whyImportant:'他把绘画的修改痕迹直接变成时间结构，使“擦除”既是动画方法也是历史如何被书写和抹除的隐喻。',projects:[project('1989–2003','Drawings for Projection','炭笔 / 擦除动画',['反复绘制、擦除并逐帧拍摄同一张纸。','以虚构人物连接南非社会历史。'],'画面保留擦除残迹，让历史的修改过程保持可见。')],images:[],sourceLabel:'MoMA',sourceUrl:'https://www.moma.org/artists/7919-william-kentridge'},
{id:'alfredo-jaar',name:'Alfredo Jaar',born:'1956',base:'New York',intro:'以摄影、电影、文字、灯箱和建筑性装置研究媒体如何呈现战争、灾难、迁徙与政治暴力。',methods:['研究型艺术','摄影装置','文本','灯箱','影像研究'],subjects:['媒体','战争','迁徙','种族灭绝','观看伦理'],outputs:['装置','摄影','电影','公共艺术'],institutions:['MoMA','Guggenheim','Venice Biennale','Documenta'],achievements:['Venice Biennale · Chile Pavilion 2013'],whyImportant:'他持续追问灾难是否应该被直接展示，把图像缺席、遮蔽、文字与观看延迟转化为政治性的展示方法。',projects:[project('1994–2000','The Rwanda Project','研究 / 摄影 / 装置',['在卢旺达种族灭绝后展开长期研究。','通过文字、摄影与图像缺席讨论媒体再现。'],'重点不是增加暴力图像，而是研究观看暴力图像的伦理条件。')],images:[],sourceLabel:'MoMA',sourceUrl:'https://www.moma.org/artists/7477-alfredo-jaar'},
{id:'kiki-smith',name:'Kiki Smith',born:'1954',base:'New York',intro:'从人体器官、身体脆弱性出发，逐步扩展到动物、自然、神话和女性图像，跨越雕塑、版画、摄影与艺术家书。',methods:['身体研究','铸造','版画','跨媒介叙事','材料实验'],subjects:['身体','女性','自然','动物','死亡','神话'],outputs:['雕塑','版画','摄影','艺术家书','装置'],institutions:['MoMA','Whitney Museum','Walker Art Center'],achievements:['MoMA · Kiki Smith: Prints, Books & Things 2003–04'],whyImportant:'她把身体从理想化整体拆解为器官、体液和脆弱材料，同时又把人体重新连接到动物、自然和精神性。',projects:[project('1985','Possession Is Nine-Tenths of the Law','版画 / 身体研究',['以人体不同器官构成系列。','将身体内部结构作为独立视觉对象。'],'身体不再作为完整肖像，而成为可拆解的生理与政治空间。')],images:[],sourceLabel:'MoMA',sourceUrl:'https://www.moma.org/artists/5486-kiki-smith'},
{id:'pieter-hugo',name:'Pieter Hugo',born:'1976',base:'Cape Town',intro:'以大画幅肖像和长期系列观察非洲及全球社会中的身份、权力、边缘化与摄影观看关系。',methods:['大画幅摄影','编排肖像','长期项目','类型学'],subjects:['身份','非洲','权力','边缘群体','殖民观看'],outputs:['摄影','摄影书'],institutions:['MoMA','Foam','MAXXI'],achievements:['KLM Paul Huf Award 2008'],whyImportant:'他的正面肖像不断暴露摄影者、被摄者和观众之间的不平等观看关系，也是当代非洲摄影国际传播的重要节点。',projects:[project('2005–2007','The Hyena & Other Men','长期肖像',['拍摄尼日利亚巡回表演者及其鬣狗、猴与蟒蛇。','以正式肖像结构呈现人与动物、劳动和表演关系。'],'作品的争议与价值都来自观看者如何解释陌生主体，而非简单的异域奇观。')],images:[],sourceLabel:'MoMA',sourceUrl:'https://www.moma.org/collection/works/149861'},
{id:'isaac-julien',name:'Isaac Julien',born:'1960',base:'London',intro:'以多屏电影装置连接黑人身份、酷儿文化、殖民历史、迁徙与电影史。',methods:['多屏影像','电影装置','历史研究','编排影像','蒙太奇'],subjects:['黑人身份','酷儿','迁徙','殖民','电影史'],outputs:['电影','多屏录像装置','摄影'],institutions:['Tate','MoMA','Centre Pompidou','Venice Biennale'],achievements:['Turner Prize 2001 入围'],whyImportant:'他把电影从单一银幕拆成观众需要在空间中移动才能完成的叙事结构，是多屏影像装置的重要代表。',projects:[project('2007','Western Union: Small Boats','多屏影像装置',['围绕跨地中海迁徙展开。','结合编排影像、舞蹈和纪录性材料。'],'迁徙不被压缩为新闻事件，而被转化为空间化、身体化的观看经验。')],images:[],sourceLabel:'Tate',sourceUrl:'https://www.tate.org.uk/art/artists/isaac-julien-2690'},
{id:'tacita-dean',name:'Tacita Dean',born:'1965',base:'Berlin / Los Angeles',intro:'以16mm/35mm胶片、摄影、黑板绘画与现成档案研究时间、偶然、消失中的媒介和历史痕迹。',methods:['模拟电影','长期观察','档案研究','黑板绘画','场域研究'],subjects:['时间','记忆','电影媒介','消失','偶然'],outputs:['电影','摄影','绘画','装置'],institutions:['Tate','Guggenheim','Venice Biennale'],achievements:['Turner Prize 1998 入围'],whyImportant:'在数字影像成为默认媒介后，她持续把胶片的物质性、等待和偶然性作为作品结构，是理解模拟媒介当代意义的重要艺术家。',projects:[project('2011','FILM','35mm电影 / Tate Turbine Hall',['为 Tate Modern Turbine Hall 制作大型胶片投影。','直接回应数字化时代电影胶片的物质性。'],'作品把胶片本身而非被拍对象推到观看中心。')],images:[],sourceLabel:'Tate',sourceUrl:'https://www.tate.org.uk/art/artists/tacita-dean-2675'}
];
