import type { Artist } from './data';
import { artistBatch83 } from './expansionBatch83';

export const artistBatch82: Artist[] = [
  ...artistBatch83,
  {id:'yto-barrada',name:'Yto Barrada',born:'1971',base:'Morocco / France',intro:'以摄影、电影、雕塑与出版研究丹吉尔、边境、迁徙、殖民遗产和城市变迁，把日常景观中的制度痕迹转化为政治而克制的视觉叙事。',methods:['观察摄影','档案研究','场域研究','电影'],subjects:['边境','迁徙','摩洛哥','殖民遗产','城市'],outputs:['摄影','电影','雕塑','出版'],institutions:['Tate'],achievements:['A Life Full of Holes: The Strait Project'],whyImportant:'Barrada把北非城市日常、跨海迁徙与边境制度连接起来，是理解当代马格里布摄影和研究型影像的重要节点。',projects:[{year:'1998–2004',title:'A Life Full of Holes: The Strait Project',type:'摄影项目',facts:['围绕丹吉尔与直布罗陀海峡展开。','从城市景观和日常生活观察边境与迁徙。'],reading:'边境不是抽象地图线，而通过城市空间、等待和日常行为持续显现。'}],images:[],sourceLabel:'Tate · Yto Barrada',sourceUrl:'https://www.tate.org.uk/art/artists/yto-barrada-11180'},
  {id:'walid-raad',name:'Walid Raad',born:'1967',base:'Lebanon / United States',intro:'以摄影、录像、文本、讲演与虚构档案研究黎巴嫩战争、记忆和艺术制度，长期通过The Atlas Group模糊史料、证言与艺术虚构的边界。',methods:['虚构档案','讲演表演','文本影像','制度研究'],subjects:['战争','记忆','黎巴嫩','档案','历史书写'],outputs:['摄影','录像','文本','装置','表演'],institutions:['MoMA'],achievements:['The Atlas Group','Walid Raad · MoMA 2015–16'],whyImportant:'Raad把档案从历史证据转化为需要被怀疑的叙事机制，对当代摄影中的虚构档案、战争记忆和研究型艺术影响深远。',projects:[{year:'1989–2004',title:'The Atlas Group',type:'摄影 / 录像 / 虚构档案',facts:['项目围绕黎巴嫩当代历史及战争经验。','使用照片、录像、文本和被建构的档案身份。'],reading:'作品迫使观众区分“档案看起来真实”与历史事实本身。'}],images:[],sourceLabel:'MoMA · Walid Raad',sourceUrl:'https://www.moma.org/artists/26439'},
  {id:'kader-attia',name:'Kader Attia',born:'1970',base:'Algeria / France / Germany',intro:'以装置、雕塑、摄影和研究追踪殖民主义、现代主义、文化挪用与“修复”概念，比较西方隐藏创伤的修复逻辑与保留伤痕的其他知识体系。',methods:['研究型装置','比较档案','材料隐喻','文化批判'],subjects:['殖民主义','修复','现代主义','文化挪用','创伤'],outputs:['装置','雕塑','摄影','录像'],institutions:['Guggenheim','Documenta'],achievements:['Untitled (Ghardaïa)','Documenta 13 · 2013'],whyImportant:'Attia的“repair”框架把物件修补、身体创伤和殖民历史放进同一比较体系，是后殖民材料研究和去殖民艺术的重要方法节点。',projects:[{year:'2009',title:'Untitled (Ghardaïa)',type:'装置',facts:['以couscous塑造阿尔及利亚Ghardaïa城市模型。','作品并置Le Corbusier、Fernand Pouillon相关照片与UNESCO文本。','Guggenheim指出Ghardaïa建筑曾影响Le Corbusier。'],reading:'现代主义所谓原创被重新放回殖民接触与跨文化借鉴关系中。'}],images:[],sourceLabel:'Guggenheim · Kader Attia',sourceUrl:'https://www.guggenheim.org/map/kader-attia'},
  {id:'otobong-nkanga',name:'Otobong Nkanga',born:'1974',base:'Nigeria / Belgium',intro:'跨绘画、纺织、雕塑、装置和表演研究土地、矿物、资源开采、贸易以及人与自然的相互依存，把材料流通理解为殖民史与生态关系的可见轨迹。',methods:['材料研究','生态研究','关系网络','场域装置'],subjects:['矿物','土地','资源开采','贸易','生态'],outputs:['装置','纺织','雕塑','绘画','表演'],institutions:['La Biennale di Venezia'],achievements:['Biennale Arte 2019','Biennale Arte 2026 · Central Pavilion'],whyImportant:'Nkanga把矿物、商品、能源与人的迁移放在同一关系网络中，是连接去殖民研究、生态艺术和材料政治的重要艺术家。',projects:[{year:'2019',title:'Biennale Arte 2019 presentation',type:'装置 / 跨媒介实践',facts:['参加第58届威尼斯双年展。','官方介绍强调矿物、能源、商品和人的移动与交换。'],reading:'材料从来不是孤立对象，其移动会留下生态、经济与殖民关系。'}],images:[],sourceLabel:'La Biennale di Venezia · Otobong Nkanga 2019',sourceUrl:'https://www.labiennale.org/en/art/2019/partecipants/otobong-nkanga'},
  {id:'kevin-beasley',name:'Kevin Beasley',born:'1985',base:'United States',intro:'以雕塑、声音和表演处理美国南方、黑人历史、劳动与材料记忆，常把衣物、棉花、土壤、树枝和工业机器转化为具有身体感的复合对象与声音环境。',methods:['材料组装','声音转译','过程雕塑','历史物件再语境化'],subjects:['美国南方','黑人历史','劳动','土地','身体'],outputs:['雕塑','声音装置','表演','混合媒介'],institutions:['Whitney Museum of American Art','MoMA PS1'],achievements:['Whitney Biennial 2014','A view of a landscape · Whitney 2018–19'],whyImportant:'Beasley把棉花、衣物、土壤和轧棉机等高度历史化的材料同时作为雕塑与声音来源，使美国奴隶制遗产、劳动史和身体经验通过物质本身被感知。',projects:[{year:'2012–18',title:'A view of a landscape: A cotton gin motor',type:'声音装置',facts:['核心是一台来自Alabama的轧棉机马达。','Whitney展览通过定制麦克风和隔音结构将机器声音转化为空间体验。','作品讨论历史、土地、种族与劳动。'],reading:'机器既是工业物件也是美国棉花经济历史的声学档案。'}],images:[],sourceLabel:'Whitney · Kevin Beasley: A view of a landscape',sourceUrl:'https://whitney.org/exhibitions/kevin-beasley'}
];
