import type { Artist } from './data';
import { artistBatch127 } from './expansionBatch127';

export const artistBatch126: Artist[] = [
{id:'wolfgang-tillmans',name:'Wolfgang Tillmans',born:'1968',base:'Germany / UK',intro:'德国摄影与跨媒介艺术家，从青年文化、酷儿生活和日常观察扩展到抽象暗房实验、静物、政治图像、音乐与反等级摄影装置。',methods:['日常摄影','非等级展示','暗房实验','摄影装置'],subjects:['青年文化','酷儿生活','日常','政治','感知'],outputs:['摄影','装置','录像','音乐'],institutions:['MoMA','Tate'],achievements:['Turner Prize 2000','To look without fear — MoMA 2022','Freischwimmer'],whyImportant:'Tillmans把杂志页、小幅照片、巨型喷墨和抽象暗房作品放在同一观看层级，改变了当代摄影展览如何组织图像，也把私人生活、政治与形式实验连接起来。',projects:[{year:'2022',title:'To look without fear',type:'摄影 / 装置回顾展',facts:['MoMA于2022年举办大型个展。','其安装以不同尺寸、材料和非等级墙面编排组织摄影。'],reading:'单张照片不是孤立作品，意义在图像、尺度、墙面和观看路径之间生成。'}],images:[],sourceLabel:'MoMA · Wolfgang Tillmans',sourceUrl:'https://www.moma.org/artists/8044-wolfgang-tillmans'},
{id:'walid-raad',name:'Walid Raad',born:'1967',base:'Lebanon / USA',intro:'黎巴嫩出生的艺术家，以摄影、录像、表演、虚构档案和讲演装置研究黎巴嫩内战、记忆、文件真实性以及阿拉伯世界艺术史的建构。',methods:['虚构档案','讲演表演','文件再编排','研究型实践'],subjects:['黎巴嫩内战','记忆','历史书写','艺术制度','中东'],outputs:['摄影','录像','雕塑','表演','装置'],institutions:['MoMA','MoMA PS1'],achievements:['The Atlas Group','Scratching on Things I Could Disavow','Walid Raad — MoMA 2015'],whyImportant:'Raad不是简单使用档案证明历史，而持续制造真假难辨的文件结构，迫使观众追问战争图像、记忆与制度化历史如何获得可信度。',projects:[{year:'1989–2004',title:'The Atlas Group',type:'虚构档案 / 摄影 / 录像',facts:['MoMA将其列为Raad的核心长期项目。','项目围绕黎巴嫩战争生产照片、录像、笔记与虚构人物档案。'],reading:'档案在这里不是中性的证据仓库，而是历史如何被叙述、相信和制度化的实验场。'}],images:[],sourceLabel:'MoMA · Walid Raad',sourceUrl:'https://www.moma.org/calendar/exhibitions/1493'},
{id:'akram-zaatari',name:'Akram Zaatari',born:'1966',base:'Lebanon',intro:'黎巴嫩艺术家、电影人及Arab Image Foundation共同创办者，通过摄影档案、电影、录像和装置研究图像生产、私人记忆、战争与中东摄影史。',methods:['档案研究','影像考古','再语境化','电影与装置'],subjects:['摄影史','黎巴嫩','战争','记忆','私人档案'],outputs:['摄影','电影','录像','装置'],institutions:['MoMA','Arab Image Foundation','Venice Biennale'],achievements:['Projects 100 — MoMA','Letter to a Refusing Pilot','Hashem el Madani archive research'],whyImportant:'Zaatari把保存摄影档案与重新激活档案结合起来，使中东日常摄影不只是历史资料，而成为研究欲望、社会规范、战争与图像价值变化的方法。',projects:[{year:'2013',title:'Letter to a Refusing Pilot',type:'影像 / 装置',facts:['作品代表黎巴嫩参加2013年威尼斯双年展。','MoMA Projects 100于同年系统展示其摄影、电影与档案实践。'],reading:'个人记忆、战争传闻与电影装置被并置，使“历史事实”与影像记忆之间的距离成为作品本身。'}],images:[],sourceLabel:'MoMA · Akram Zaatari',sourceUrl:'https://www.moma.org/calendar/exhibitions/1278'},
{id:'cao-fei',name:'Cao Fei 曹斐',born:'1978',base:'China',intro:'中国当代艺术家，以录像、摄影、虚拟世界和大型多媒体装置研究珠三角工业化、青年亚文化、城市化、自动化与数字生活。',methods:['社会观察','虚拟世界建构','科幻叙事','录像装置'],subjects:['工业化','青年文化','城市','自动化','虚拟现实','劳动'],outputs:['录像','摄影','数字媒体','装置'],institutions:['Guggenheim','MoMA PS1','Venice Biennale'],achievements:['COSplayers','Whose Utopia','RMB City','Asia One'],whyImportant:'曹斐把中国高速城市化和工厂劳动与动漫、游戏、Second Life和科幻连接，是理解中国社会转型如何进入数字媒介艺术的关键艺术家。',projects:[{year:'2018',title:'Asia One',type:'电影 / 多媒体装置',facts:['Guggenheim委任并收藏该项目。','作品在高度自动化物流设施中拍摄，以仅存的人类员工和机器人系统讨论自动化社会。'],reading:'工业现实被推向近未来科幻，使效率、孤独、劳动和人机关系在同一空间中显现。'}],images:[],sourceLabel:'Guggenheim · Cao Fei',sourceUrl:'https://www.guggenheim.org/artwork/artist/cao-fei'},
{id:'isaac-julien',name:'Isaac Julien',born:'1960',base:'UK / USA',intro:'英国电影与装置艺术家，以电影、多屏影像和摄影处理黑人身份、酷儿欲望、离散、迁徙、资本与历史人物，并将电影语言转化为沉浸式展览空间。',methods:['多屏电影装置','历史重演','跨媒介叙事','研究型电影'],subjects:['黑人身份','酷儿文化','离散','迁徙','殖民史','资本'],outputs:['电影','多屏录像','摄影','装置'],institutions:['Tate','MoMA'],achievements:['Looking for Langston','Ten Thousand Waves','Lessons of the Hour','What Freedom Is To Me — Tate Britain 2023'],whyImportant:'Julien把实验电影、黑人电影传统与美术馆多屏装置结合，建立了一种跨越电影史、身份政治和空间化观看的关键当代影像语言。',projects:[{year:'1989',title:'Looking for Langston',type:'电影',facts:['作品围绕Langston Hughes与Harlem Renaissance构建黑人酷儿欲望的诗性影像。','Tate 2023回顾展再次将其列为Julien的核心早期作品。'],reading:'历史不是被说明，而通过表演、档案、诗歌和欲望重新被想象与占有。'}],images:[],sourceLabel:'Tate · Isaac Julien',sourceUrl:'https://www.tate.org.uk/whats-on/tate-britain/isaac-julien'},
{id:'apichatpong-weerasethakul',name:'Apichatpong Weerasethakul',born:'1970',base:'Thailand',intro:'泰国电影与视觉艺术家，以长镜头、非线性叙事、幽灵、梦境、乡村景观和声音连接私人记忆、地方信仰、身体与泰国政治历史，并同时工作于电影、装置和表演。',methods:['慢电影','非线性叙事','声音实践','电影装置'],subjects:['记忆','幽灵','梦','乡村','身体','政治历史'],outputs:['电影','录像','装置','表演'],institutions:['MoMA','Cannes Film Festival'],achievements:['Tropical Malady','Syndromes and a Century','Uncle Boonmee Who Can Recall His Past Lives','Memoria'],whyImportant:'阿彼察邦让电影中的时间、梦、幽灵与现实互相渗透，并把东南亚地方经验带入国际当代艺术与实验电影网络，是跨电影和视觉艺术领域的重要节点。',projects:[{year:'2010',title:'Uncle Boonmee Who Can Recall His Past Lives',type:'电影',facts:['作品获2010年戛纳电影节金棕榈奖。','MoMA收藏并持续放映该片。'],reading:'轮回、森林、家庭和政治记忆不被分成现实与超自然两个世界，而作为同一经验连续体出现。'}],images:[],sourceLabel:'MoMA · Apichatpong Weerasethakul',sourceUrl:'https://www.moma.org/artists/42736-apichatpong-weerasethakul'},
...artistBatch127
];