import type { Artist } from './data';

export const artistBatch90: Artist[] = [
{id:'gauri-gill',name:'Gauri Gill',born:'1970',base:'India',intro:'印度摄影艺术家，长期与拉贾斯坦乡村及原住民社群合作，以缓慢、关系导向的摄影处理教育、迁徙、身份与地方知识。',methods:['长期田野摄影','协作摄影','黑白摄影','共同创作'],subjects:['乡村生活','教育','原住民社群','身份','地方知识'],outputs:['摄影','摄影书','装置'],institutions:['MoMA'],achievements:['Notes from the Desert','Acts of Appearance','MoMA Projects 108'],whyImportant:'Gill把长期纪实与共同创作结合，重新讨论摄影者与被摄者之间的作者权力，是南亚当代摄影的重要节点。',projects:[{year:'2015–ongoing',title:'Acts of Appearance',type:'协作摄影系列',facts:['与印度马哈拉施特拉邦Jawhar地区Adivasi艺术家合作。','参与者制作纸浆面具并在日常环境中佩戴后共同完成图像。'],reading:'面具并非单纯道具，而成为社群自我表述、身份想象与摄影协作机制的一部分。'}],images:[],sourceLabel:'MoMA · Gauri Gill',sourceUrl:'https://www.moma.org/collection/works/283400'},
{id:'lebohang-kganye',name:'Lebohang Kganye',born:'1990',base:'South Africa',intro:'约翰内斯堡艺术家，以家庭相册、口述史和南非文学为材料，把摄影扩展为剪影、戏剧场景、雕塑、表演和移动影像。',methods:['家庭档案再演','口述史','舞台化摄影','剪影装置'],subjects:['家庭记忆','种族隔离史','祖先','迁徙','虚构与记忆'],outputs:['摄影','装置','表演','影像'],institutions:['Foam','Venice Biennale'],achievements:['Foam Paul Huf Award 2022','Haufi nyana? I’ve come to take you home','South African Pavilion 2022'],whyImportant:'Kganye代表新一代非洲摄影将私人档案、口述传统与剧场机制结合的方向，使摄影成为重建被殖民历史切断的家庭记忆的方法。',projects:[{year:'2013',title:'Her Story',type:'档案再演摄影',facts:['以家庭相册和母亲的影像为起点。','通过表演把自身重新置入家庭记忆。'],reading:'过去与现在在同一图像中重叠，使家庭摄影从证据转化为可被重新表演的记忆空间。'}],images:[],sourceLabel:'Foam · Lebohang Kganye',sourceUrl:'https://www.foam.org/artists/lebohang-kganye'},
{id:'moyra-davey',name:'Moyra Davey',born:'1958',base:'Canada / United States',intro:'加拿大出生、纽约工作的艺术家，以摄影、录像、写作和文学阅读构成高度互文的实践，并把折叠、邮寄和流通过程直接变成照片的物质痕迹。',methods:['邮寄摄影','文本与图像','自传写作','影像散文'],subjects:['阅读','记忆','家庭','文学史','日常物件'],outputs:['摄影','录像','写作'],institutions:['Whitney Museum','MoMA'],achievements:['Whitney Biennial 2012','New Photography 2011','Trust Me'],whyImportant:'Davey把摄影的物质流通、阅读经验与第一人称写作结合，使照片不再只是图像，而成为被折叠、传递、阅读和重新编排的对象。',projects:[{year:'2011',title:'Trust Me',type:'邮寄摄影装置',facts:['照片被折叠并通过邮政寄送。','胶带、邮戳、折痕与书写成为作品表面的一部分。'],reading:'流通造成的损伤被保留下来，使照片的社会旅程进入作品本身。'}],images:[],sourceLabel:'Whitney Museum · Moyra Davey',sourceUrl:'https://whitney.org/artists/13630'},
{id:'santu-mofokeng',name:'Santu Mofokeng',born:'1956–2020',base:'South Africa',intro:'南非摄影家，从新闻摄影转向长期摄影散文，持续研究黑人日常生活、土地、信仰、种族隔离遗产与历史档案。',methods:['摄影散文','长期纪实','档案研究','黑白摄影'],subjects:['信仰','土地','黑人日常生活','种族隔离','历史记忆'],outputs:['摄影','幻灯装置','摄影书'],institutions:['MoMA','Documenta'],achievements:['Train Church','The Black Photo Album / Look at Me: 1890–1950','Documenta 11'],whyImportant:'Mofokeng拒绝把南非黑人经验压缩为抗争新闻图像，以日常、精神生活和历史档案扩展了反种族隔离摄影的视觉语言。',projects:[{year:'1997',title:'The Black Photo Album / Look at Me: 1890–1950',type:'档案幻灯装置',facts:['使用历史私人家庭与工作室肖像档案。','作品以80张黑白幻灯片构成。'],reading:'私人肖像证明黑人主体早已主动建构现代身份，也把被主流摄影史忽略的家庭图像转化为概念摄影档案。'}],images:[],sourceLabel:'MoMA · Santu Mofokeng',sourceUrl:'https://www.moma.org/artists/72440-santu-mofokeng'},
{id:'rosangela-renno',name:'Rosângela Rennó',born:'1962',base:'Brazil',intro:'巴西艺术家，长期收集被丢弃的照片、底片、幻灯片与公共档案，通过重新编排、放大和装置化研究遗忘、可见性与历史叙事。',methods:['挪用摄影','档案艺术','图像再编排','现成照片'],subjects:['遗忘','历史','匿名身份','监禁','视觉制度'],outputs:['摄影','装置','录像','艺术家书'],institutions:['MoMA','Aperture'],achievements:['Vulgo','Chosen Memories','Paris Photo–Aperture PhotoBook of the Year 2013'],whyImportant:'Rennó把摄影从拍摄行为转向对既有图像制度的考古，持续追问哪些照片被保存、哪些主体被遗忘以及历史如何通过图像被制造。',projects:[{year:'1990s',title:'Vulgo',type:'档案摄影系列',facts:['使用来自公共与制度档案的既有图像。','作品关注匿名化身体、识别与分类机制。'],reading:'档案中的照片脱离原有行政用途后，暴露摄影与制度性命名、可见性和遗忘之间的关系。'}],images:[],sourceLabel:'MoMA · Rosângela Rennó',sourceUrl:'https://www.moma.org/artists/45951-rosangela-renno'}
];
