import type { Artist } from './data';
import { artistBatch85 } from './expansionBatch85';

export const artistBatch84: Artist[] = [
  {id:'wangechi-mutu',name:'Wangechi Mutu',born:'1972',base:'Kenya / United States',intro:'以拼贴、雕塑、录像与行为重构黑人女性身体、非洲离散身份和神话形象，把时尚、民族志、医学与大众媒体图像拆解后重新组合为混种身体。',methods:['拼贴','图像挪用','混种身体','神话重写'],subjects:['黑人女性','非洲离散','性别','殖民表征','神话'],outputs:['拼贴','雕塑','录像','行为','版画'],institutions:['MoMA'],achievements:['Yo Mama','MamaRay'],whyImportant:'Mutu把拼贴从形式语言转化为拆解种族与性别刻板图像的工具，并以非洲未来主义和跨物种身体拓展黑人女性形象的可能性。',projects:[{year:'2003',title:'Yo Mama',type:'拼贴',facts:['作品致敬尼日利亚女性主义者Funmilayo Anikulapo-Kuti。','使用墨水、云母、丙烯、印刷纸等多种材料。'],reading:'通过重新拼接女性身体与神话符号，把既有视觉文化中的黑人女性形象改写为主动的政治主体。'},{year:'2020',title:'MamaRay',type:'青铜雕塑',facts:['MoMA收藏。','女性身体与蝠鲼等水生形态融合。'],reading:'跨物种形象把非洲离散历史、海洋和未来主义想象连接起来。'}],images:[],sourceLabel:'MoMA · Wangechi Mutu',sourceUrl:'https://www.moma.org/collection/artists/28097'},
  {id:'alfredo-jaar',name:'Alfredo Jaar',born:'1956',base:'Chile / United States',intro:'以摄影、电影、灯光、文本和建筑式装置研究新闻图像、战争、种族主义、移民与灾难中的观看伦理，持续追问图像如何让远方苦难变得可见或被忽视。',methods:['研究型装置','新闻图像再语境化','观看机制设计','文本介入'],subjects:['战争','移民','种族主义','灾难','媒体'],outputs:['装置','摄影','电影','公共艺术'],institutions:['MoMA'],achievements:['The Rwanda Project'],whyImportant:'Jaar把“如何观看他人的苦难”本身变成作品结构，是政治摄影、研究型装置与媒体伦理之间的重要桥梁。',projects:[{year:'1994–2000',title:'The Rwanda Project',type:'摄影 / 装置系列',facts:['围绕卢旺达种族灭绝及其媒体再现展开。'],reading:'作品不依赖灾难图像的直接冲击，而不断设计观看条件，迫使观众意识到图像传播与注意力政治。'}],images:[],sourceLabel:'MoMA · Alfredo Jaar',sourceUrl:'https://www.moma.org/artists/7477-alfredo-jaar'},
  {id:'doris-salcedo',name:'Doris Salcedo',born:'1958',base:'Colombia',intro:'以家具、衣物、水泥、鞋和建筑介入回应哥伦比亚长期暴力、失踪者与政治创伤，作品通常来自对受害者及家属证言的长期倾听。',methods:['证言研究','日常物改造','材料隐喻','纪念性装置'],subjects:['政治暴力','失踪','哀悼','哥伦比亚','记忆'],outputs:['雕塑','装置','公共介入'],institutions:['MoMA'],achievements:['Atrabilious','Widowed House'],whyImportant:'Salcedo不直接再现暴力场面，而让被使用过的家具、鞋与衣物成为缺席身体的替代物，建立了当代艺术中关于见证、哀悼和政治创伤的重要材料语言。',projects:[{year:'1992–93',title:'Atrabilious',type:'墙面装置',facts:['使用旧鞋、胶合板、牛膀胱和手术线。','鞋指向哥伦比亚冲突中的失踪者。'],reading:'模糊可见的旧鞋像照片或遗物，使私人失踪经验进入公共记忆。'},{year:'1995',title:'Untitled',type:'雕塑',facts:['将木制家具与水泥、钢材、衣物结合。'],reading:'日常家具被水泥封死后失去功能，以物的沉默对应暴力造成的身体缺席。'}],images:[],sourceLabel:'MoMA · Doris Salcedo',sourceUrl:'https://www.moma.org/artists/7488-doris-salcedo'},
  {id:'isaac-julien',name:'Isaac Julien',born:'1960',base:'United Kingdom',intro:'以电影和多屏影像装置研究黑人身份、酷儿历史、离散、迁徙、资本与文化记忆，将电影语言拆分到展览空间中的多个屏幕与观看路径。',methods:['多屏影像','电影叙事','档案重演','空间蒙太奇'],subjects:['黑人身份','酷儿历史','离散','迁徙','资本'],outputs:['电影','录像','多屏装置','摄影'],institutions:['Tate'],achievements:['Looking for Langston','Lessons of the Hour'],whyImportant:'Julien把黑人独立电影与当代美术馆多屏影像装置连接起来，使历史研究、身份政治和电影蒙太奇成为空间化观看经验。',projects:[{year:'1989',title:'Looking for Langston',type:'电影',facts:['围绕Harlem Renaissance与Langston Hughes相关文化记忆展开。'],reading:'通过诗性重演与档案想象重建被主流历史压低的黑人酷儿文化谱系。'}],images:[],sourceLabel:'Tate · Isaac Julien',sourceUrl:'https://www.tate.org.uk/art/artists/isaac-julien-2317'},
  {id:'amar-kanwar',name:'Amar Kanwar',born:'1964',base:'India',intro:'以电影、多屏装置、文本和档案长期研究印度次大陆的政治暴力、土地、农民运动、生态与正义，通过缓慢而诗性的影像把证言、现场和制度问题连接起来。',methods:['影像散文','长期田野研究','多屏装置','证言档案'],subjects:['土地','政治暴力','农民','生态','正义'],outputs:['电影','录像','装置','文本','档案'],institutions:['La Biennale di Venezia'],achievements:['The Lightning Testimonies','The Sovereign Forest','Biennale Arte 2015'],whyImportant:'Kanwar将纪录影像从信息传递转向持续的伦理与政治研究，是南亚研究型影像、土地政治与诗性纪录实践的重要节点。',projects:[{year:'2007',title:'The Lightning Testimonies',type:'多屏影像装置',facts:['以多屏结构处理南亚女性遭受性暴力的证言与历史。'],reading:'不同地点和时间的证言并置，使暴力不被压缩成单一事件。'},{year:'2011–',title:'The Sovereign Forest',type:'长期影像 / 档案项目',facts:['围绕印度Odisha的土地、资源与社区展开长期研究。'],reading:'影像、文本和档案共同构成关于土地权利与生态正义的开放知识空间。'}],images:[],sourceLabel:'La Biennale di Venezia · Amar Kanwar',sourceUrl:'https://www.labiennale.org/en/art/2015/biennale-arte-2015-national-participations'},
  ...artistBatch85
];
