import type { Artist } from './data';
import { artistBatch133 } from './expansionBatch133';

export const artistBatch132: Artist[] = [
...artistBatch133,
{id:'hito-steyerl',name:'Hito Steyerl',born:'1966',base:'Germany',intro:'德国艺术家、电影作者与理论写作者，以影像装置和论文电影研究数字图像、战争、监控、网络传播与后真相视觉文化。',methods:['论文电影','影像研究','挪用','数字图像批判'],subjects:['图像流通','战争','监控','互联网','可见性'],outputs:['录像','影像装置','文本'],institutions:['MoMA','Documenta','La Biennale di Venezia','Berlin Biennale'],achievements:['November','How Not to Be Seen','Liquidity Inc.','German Pavilion — Venice Biennale 2015'],whyImportant:'Steyerl把影像制作与图像理论合并，是理解“贫穷图像”、数字传播、机器视觉和当代影像政治的核心艺术家。',projects:[{year:'2013',title:'How Not to Be Seen: A Fucking Didactic Educational .MOV File',type:'录像 / 数字图像批判',facts:['MoMA收藏该作品，并将其置于Steyerl关于数字化、网络化生活的持续研究中。','作品借教学视频形式讽刺高度可见时代中的隐私、分辨率与消失。'],reading:'作品把图像技术本身变成主题：谁能被看见、如何被机器看见，以及如何从图像制度中消失。'}],images:[],sourceLabel:'MoMA · Hito Steyerl',sourceUrl:'https://www.moma.org/artists/43752-hito-steyerl'},
{id:'zanele-muholi',name:'Zanele Muholi',born:'1972',base:'South Africa',intro:'南非视觉行动者，以摄影、自画像与影像长期记录黑人LGBTQIA+社群，并通过共同呈现、尊严和自我塑造对抗歧视性视觉传统。',methods:['视觉行动主义','长期肖像','自画像','社群协作'],subjects:['黑人酷儿生活','性别','身份','种族','自我呈现'],outputs:['摄影','录像','雕塑'],institutions:['Tate Modern','MoMA','Guggenheim','Brooklyn Museum'],achievements:['Faces and Phases','Somnyama Ngonyama','Tate Modern retrospective 2024–2025'],whyImportant:'Muholi将纪实摄影、社群档案和自我表演结合，使被拍摄者不只是社会问题的例证，而成为主动塑造自身形象的主体。',projects:[{year:'2006–',title:'Faces and Phases',type:'长期肖像 / 社群档案',facts:['Tate资料指出Muholi长期记录南非黑人女同性恋、同性恋、双性恋、跨性别与间性人士的生活。','其国际实践从亲密的他者肖像延伸至强烈的自画像。'],reading:'系列以持续拍摄建立不断增长的社群视觉档案，对抗黑人酷儿主体在主流历史中的缺席。'}],images:[],sourceLabel:'Tate · Zanele Muholi',sourceUrl:'https://www.tate.org.uk/whats-on/tate-modern/zanele-muholi'},
{id:'otobong-nkanga',name:'Otobong Nkanga',born:'1974',base:'Nigeria / Belgium',intro:'尼日利亚出生、安特卫普工作的跨媒介艺术家，以绘画、纺织、雕塑、装置与行为追踪矿物、土地、商品、殖民贸易和生态关系。',methods:['材料研究','地缘调查','跨媒介装置','叙事'],subjects:['矿产','土地','殖民贸易','生态','资源流动'],outputs:['装置','纺织','雕塑','绘画','行为'],institutions:['La Biennale di Venezia'],achievements:['Venice Biennale 2019','Special Mention — Venice Biennale 2019','Venice Biennale 2026'],whyImportant:'Nkanga把材料的来源、开采、运输与人的迁移放在同一网络中，使物质本身成为理解殖民历史、全球贸易和生态关系的方法。',projects:[{year:'2019',title:'Venice Biennale 2019 presentation',type:'装置 / 材料与资源研究',facts:['La Biennale将其工作描述为处理矿物、能源、商品和人的移动与交换。','她在第58届威尼斯双年展获得特别提及。'],reading:'材料不是中性的媒介，而携带开采、劳动、殖民交换和环境影响形成的关系史。'}],images:[],sourceLabel:'La Biennale di Venezia · Otobong Nkanga',sourceUrl:'https://www.labiennale.org/en/art/2019/partecipants/otobong-nkanga'},
{id:'joan-fontcuberta',name:'Joan Fontcuberta',born:'1955',base:'Spain',intro:'西班牙摄影艺术家、作家与策展人，以伪档案、虚构科学和摄影骗局持续质疑摄影真实性、作者权威与知识制度。',methods:['伪档案','虚构纪实','挪用','制度戏仿'],subjects:['摄影真实性','科学分类','档案','作者身份','知识生产'],outputs:['摄影','出版物','装置','文本'],institutions:['MoMA'],achievements:['Fauna','Sputnik','Projects 12 — MoMA 1988'],whyImportant:'Fontcuberta把“摄影会撒谎”发展为系统方法，通过制造可信的档案与科学证据暴露摄影真实性依赖制度、文本和观看者信任。',projects:[{year:'1985–1988',title:'Fauna / Alopex Stultus',type:'伪科学档案 / 摄影',facts:['MoMA收藏Fontcuberta与Pere Formiguera合作的Alopex Stultus。','两人于1988年进入MoMA Projects 12展览。'],reading:'虚构动物被包装成科学发现，使观众意识到所谓证据的可信度来自摄影、标签和机构话语共同建构。'}],images:[],sourceLabel:'MoMA · Joan Fontcuberta',sourceUrl:'https://www.moma.org/artists/1932-joan-fontcuberta'},
{id:'trevor-paglen',name:'Trevor Paglen',born:'1974',base:'USA',intro:'美国艺术家、地理学者与作者，以长焦摄影、卫星与数据研究揭示军事基地、秘密基础设施、监控网络和机器视觉。',methods:['实验地理','调查摄影','远距离成像','数据与机器视觉研究'],subjects:['监控','军事基础设施','人工智能','卫星','不可见系统'],outputs:['摄影','装置','录像','数据项目'],institutions:['Whitney Museum','Guggenheim'],achievements:['Deutsche Börse Photography Foundation Prize 2016','MacArthur Fellowship 2017','LG Guggenheim Award 2026'],whyImportant:'Paglen把摄影的可见性问题从人物和景观推进到隐藏基础设施与机器视觉：摄影既用于揭露不可见权力，也成为被算法读取的数据。',projects:[{year:'2014',title:'An English Landscape (American Surveillance Base near Harrogate, Yorkshire)',type:'调查摄影 / 监控基础设施',facts:['Whitney收藏该2014年彩色摄影作品。','Whitney将Paglen的实践概括为涉及大规模监控与数据收集的实验地理。'],reading:'传统风景摄影的宁静外观与隐藏的监控基础设施发生冲突，使“看不见的系统”成为风景本身。'}],images:[],sourceLabel:'Whitney Museum · Trevor Paglen',sourceUrl:'https://whitney.org/artists/11403'},
{id:'laura-poitras',name:'Laura Poitras',born:'1964',base:'USA',intro:'美国电影作者、记者与艺术家，以纪录电影和沉浸式装置调查9·11之后的战争、无人机、关塔那摩、国家监控与数据政治。',methods:['调查纪录','沉浸式装置','原始文件','叙事环境'],subjects:['国家监控','反恐战争','无人机','隐私','数据'],outputs:['电影','录像','装置','摄影'],institutions:['Whitney Museum'],achievements:['Citizenfour','Astro Noise — Whitney Museum 2016','Pulitzer Prize for Public Service team 2014'],whyImportant:'Poitras把调查新闻、纪录电影和美术馆装置连接起来，使泄密文件、监控图像和个人经验在空间中形成可被观众身体经历的政治档案。',projects:[{year:'2016',title:'Astro Noise',type:'沉浸式装置 / 调查纪录',facts:['Whitney于2016年举办Poitras首个博物馆个展Astro Noise。','展览围绕大规模监控、反恐战争、无人机、关塔那摩、占领与酷刑，结合纪录素材、建筑介入和原始文件。'],reading:'调查材料不再只以新闻报道出现，而被组织为观众可以进入的空间，使数据政治转化为身体经验。'}],images:[],sourceLabel:'Whitney Museum · Laura Poitras: Astro Noise',sourceUrl:'https://whitney.org/exhibitions/laura-poitras'}
];