import type { Artist } from './data';

export const artistBatch76: Artist[] = [
  {id:'zanele-muholi',name:'Zanele Muholi',born:'1972',base:'South Africa',intro:'以摄影与自我肖像建立南非黑人 LGBTQIA+ 社群的视觉档案，并将肖像实践明确作为视觉行动主义。',methods:['长期肖像档案','协作肖像','自我表演','视觉行动主义'],subjects:['黑人酷儿社群','性别身份','可见性','南非社会','自我再现'],outputs:['摄影','自画像','出版'],institutions:['MoMA','Tate Modern'],achievements:['Faces and Phases','Somnyama Ngonyama','Zanele Muholi · Tate Modern 2024–25'],whyImportant:'Muholi把肖像从身份记录转化为社群共同书写历史的政治工具，是当代非洲摄影、酷儿视觉文化与档案实践的核心人物。',projects:[{year:'2006–',title:'Faces and Phases',type:'长期肖像档案',facts:['持续拍摄黑人女同性恋、跨性别与性别非常规者。','MoMA将其描述为针对南非黑人酷儿不可见性的持续视觉档案。'],reading:'通过姓名、地点、时间和长期重复拍摄，让被摄者拥有自身形象与历史叙事的主体位置。'}],images:[],sourceLabel:'MoMA · Zanele Muholi',sourceUrl:'https://www.moma.org/collection/artists/42455'},
  {id:'taryn-simon',name:'Taryn Simon',born:'1975',base:'United States',intro:'以摄影、文本、档案和长期调查研究法律、权力、分类系统、血缘与不可见的制度结构。',methods:['研究型摄影','摄影与文本','档案分类','长期调查'],subjects:['司法','制度','权力','血缘','不可见系统'],outputs:['摄影','文本','装置','出版'],institutions:['MoMA','MoMA PS1'],achievements:['The Innocents · MoMA PS1 2003','A Living Man Declared Dead and Other Chapters I–XVIII · MoMA 2012'],whyImportant:'Simon把摄影与调查、证据和制度分类结合，使摄影项目成为分析知识如何被生产、排序和相信的研究系统。',projects:[{year:'2002',title:'The Innocents',type:'摄影 / 文本研究',facts:['拍摄遭错误定罪后获释者及与案件有关的地点。','系列于2003年在MoMA PS1展出。'],reading:'利用摄影既可能制造误认又能成为证据的矛盾，检验司法与图像真实性之间的关系。'}],images:[],sourceLabel:'MoMA · Taryn Simon',sourceUrl:'https://www.moma.org/artists/41212-taryn-simon'},
  {id:'trevor-paglen',name:'Trevor Paglen',born:'1974',base:'United States',intro:'通过摄影、机器视觉、地图与研究追踪监控基础设施、军事秘密、卫星和人工智能图像系统。',methods:['调查研究','远距离摄影','机器视觉研究','基础设施追踪'],subjects:['监控','军事系统','人工智能','卫星','不可见基础设施'],outputs:['摄影','录像','装置','数据研究'],institutions:['MoMA'],achievements:['New Order: Art and Technology in the Twenty-First Century · MoMA 2019','216: Systems · MoMA 2022–24'],whyImportant:'Paglen把摄影的对象从可见世界扩展到国家监控、轨道基础设施和机器观看，是连接当代艺术、AI视觉与基础设施研究的重要节点。',projects:[{year:'2017',title:'Behold These Glorious Times!',type:'录像 / 机器视觉研究',facts:['作品进入MoMA馆藏。','MoMA将Paglen纳入2019年艺术与技术展New Order。'],reading:'通过机器训练图像与视觉分类揭示人工智能观看并非中性的技术过程。'}],images:[],sourceLabel:'MoMA · Trevor Paglen',sourceUrl:'https://www.moma.org/artists/69988-trevor-paglen'},
  {id:'mohamed-bourouissa',name:'Mohamed Bourouissa',born:'1978',base:'Algeria / France',intro:'以摄影、录像、合作项目和混合装置进入城市边缘社群，研究监禁、青年文化、种族化空间与社会再现。',methods:['社会介入','合作生产','研究型摄影','录像实践'],subjects:['城市边缘','监禁','青年文化','种族','社会现实'],outputs:['摄影','录像','装置','绘画'],institutions:['Centre Pompidou'],achievements:['Prix Marcel Duchamp nominee 2018','Centre Pompidou collection'],whyImportant:'Bourouissa在纪实与编排、观察与合作之间移动，使法国郊区和边缘社群不只是被观看对象，而成为共同生产图像的参与者。',projects:[{year:'2009',title:'Temps Mort',type:'录像 / 合作项目',facts:['两名囚犯按艺术家的指令用手机在九个月间记录日常片段。','作品进入Centre Pompidou馆藏。'],reading:'低分辨率手机影像将监禁中的身体、时间与作者权重新组织为协作式影像生产。'}],images:[],sourceLabel:'Centre Pompidou · Mohamed Bourouissa',sourceUrl:'https://www.centrepompidou.fr/en/ressources/personne/cGEbKjx'},
  {id:'newsha-tavakolian',name:'Newsha Tavakolian',born:'1981',base:'Iran',intro:'从新闻摄影进入概念纪实与艺术摄影，以长期项目讨论伊朗社会、女性声音、战争、审查与个人记忆。',methods:['概念纪实','新闻摄影','编排肖像','长期项目'],subjects:['伊朗社会','女性','审查','战争','记忆'],outputs:['摄影','录像','装置'],institutions:['Foam','Magnum Photos'],achievements:['Open for Business · Foam 2022','Magnum Photos member'],whyImportant:'Tavakolian连接新闻现场与概念摄影，使中东社会经验不被简化为新闻事件，而通过个人叙事、编排和档案获得更复杂的内部视角。',projects:[{year:'2010–11',title:'Listen',type:'摄影 / 概念纪实',facts:['项目围绕在伊朗受到公开独唱限制的女性歌手展开。','艺术家官网将Listen列为核心长期项目。'],reading:'通过模拟演唱、肖像与虚构唱片视觉，让被制度压低的女性声音以摄影形式重新获得可见性。'}],images:[],sourceLabel:'Newsha Tavakolian · official website',sourceUrl:'https://www.newshatavakolian.com/'},
  {id:'hassan-hajjaj',name:'Hassan Hajjaj',born:'1961',base:'Morocco / United Kingdom',intro:'以鲜艳编排肖像、时尚、设计和现成消费品图形混合摩洛哥街头文化、伦敦亚文化与全球品牌语言。',methods:['编排肖像','时尚挪用','消费符号拼贴','跨文化设计'],subjects:['摩洛哥文化','青年文化','时尚','移民身份','消费'],outputs:['摄影','装置','电影','服装','家具'],institutions:['Aperture','Fotografiska'],achievements:['VOGUE, The Arab Issue · Fotografiska New York 2021','Kesh Angels'],whyImportant:'Hajjaj用高度风格化的肖像主动反转西方对阿拉伯与穆斯林身份的视觉定型，并把摄影、时尚和街头设计置于同一混合文化系统。',projects:[{year:'2010s',title:'Kesh Angels',type:'编排摄影',facts:['以马拉喀什女性摩托骑手为主体。','人物服装、图案与消费品式边框共同构成高度设计化的肖像。'],reading:'借用时尚摄影的视觉权力，同时让当地人物、服饰和街头文化控制图像的身份叙事。'}],images:[],sourceLabel:'Aperture · Hassan Hajjaj',sourceUrl:'https://aperture.org/tag/hassan-hajjaj/'}
];
