import type { Artist } from './data';
import { artistBatch106 } from './expansionBatch106';

export const artistBatch105: Artist[] = [
{id:'yto-barrada',name:'Yto Barrada',born:'1971',base:'Morocco / France',intro:'摩洛哥裔法国艺术家，以摄影、电影、纺织、出版与装置研究丹吉尔、迁徙边界、殖民现代性、城市植物学以及抵抗与生存策略。',methods:['社会景观摄影','档案研究','电影与出版','材料与地方研究'],subjects:['丹吉尔','迁徙与边界','殖民历史','城市变化','抵抗与生存'],outputs:['摄影','电影','纺织','装置','艺术家书'],institutions:['MoMA'],achievements:['A Life Full of Holes: The Strait Project','Wallpaper – Tangier','MoMA collection'],whyImportant:'Barrada把北非城市日常、直布罗陀海峡边界政治和看似普通的景观细节连接起来，是当代摄影从社会纪实转向研究型跨媒介实践的重要人物。',projects:[{year:'1998–2004',title:'A Life Full of Holes: The Strait Project',type:'摄影 / 社会景观',facts:['围绕丹吉尔及直布罗陀海峡展开长期摄影研究。','作品将迁徙愿望、边界控制与城市日常放在同一视觉结构中。'],reading:'她不直接制造新闻式边境图像，而从等待、空地、建筑和城市细节显示迁徙政治如何进入日常。'}],images:[],sourceLabel:'MoMA · Yto Barrada',sourceUrl:'https://www.moma.org/collection/artists/42323'},
{id:'kader-attia',name:'Kader Attia',born:'1970',base:'France / Algeria',intro:'法裔阿尔及利亚艺术家，以装置、摄影、雕塑、档案与研究项目讨论殖民主义、文化异化、身份以及“修复”如何揭示西方与非西方知识体系之间的不对称。',methods:['档案研究','比较图像','材料转化','后殖民研究'],subjects:['殖民主义','修复','文化异化','身份','博物馆制度'],outputs:['装置','摄影','雕塑','录像','研究项目'],institutions:['Centre Pompidou','documenta'],achievements:['Ghost','The Repair','documenta 13'],whyImportant:'Attia把“修复”发展成理解殖民创伤、博物馆分类和现代性的重要方法，使伤痕、补丁和破损不再只是缺陷，而成为历史关系的可见证据。',projects:[{year:'2007',title:'Ghost',type:'装置 / 铝箔雕塑',facts:['由102个以女性跪姿身体翻模形成的铝箔空壳组成。','作品进入Centre Pompidou收藏。'],reading:'空心祈祷身体把宗教、排斥、脆弱性与个体消失并置。'},{year:'2012',title:'The Repair',type:'摄影投影装置',facts:['以循环投影比较被修复的非洲物件与第一次世界大战面部受伤士兵。','Centre Pompidou于2014年购藏。'],reading:'修复痕迹被用来比较不同文化如何理解损坏、完整性和历史创伤。'}],images:[],sourceLabel:'Centre Pompidou · Kader Attia',sourceUrl:'https://www.centrepompidou.fr/en/ressources/personne/c4r9A7e'},
{id:'latifa-echakhch',name:'Latifa Echakhch',born:'1974',base:'Morocco / France / Switzerland',intro:'摩洛哥出生的艺术家，通过装置、绘画、现成物和空间介入，把日常物件、个人记忆与政治象征从原有语境中抽离，形成带有舞台感和残迹感的环境。',methods:['现成物再语境化','空间装置','象征拆解','记忆材料化'],subjects:['记忆','政治符号','现代主义','舞台与残迹','身份'],outputs:['装置','绘画','雕塑','空间介入'],institutions:['Centre Pompidou'],achievements:['Prix Marcel Duchamp 2013','Senza titolo (Personaggi)','Walk in the clearing, cross it slowly and leave it fast by the right, and then come back'],whyImportant:'Echakhch以极少的材料和高度控制的空间关系拆解熟悉符号，使个人记忆、政治暗示和现代主义形式在同一个场景中保持不稳定。',projects:[{year:'2018',title:'Senza titolo (Personaggi)',type:'装置 / 现成物',facts:['使用19世纪那不勒斯人物小雕像、金属、陶瓷、树脂、纺织物与亚麻线。','作品进入Centre Pompidou收藏。'],reading:'被拆解并悬置的人物像事件发生后的舞台残迹，使装饰物转化为关于历史、暴力和记忆的线索。'},{year:'2013',title:'Prix Marcel Duchamp',type:'奖项 / 机构网络',facts:['获得2013 Prix Marcel Duchamp。','Centre Pompidou于2014至2015年为其呈现获奖个展。'],reading:'其空间实践进入法国当代艺术核心机构网络的重要节点。'}],images:[],sourceLabel:'Centre Pompidou · Latifa Echakhch',sourceUrl:'https://www.centrepompidou.fr/en/ressources/personne/z6IWfTl'},
{id:'mona-hatoum',name:'Mona Hatoum',born:'1952',base:'Palestine / Lebanon / United Kingdom',intro:'出生于贝鲁特的巴勒斯坦裔艺术家，以装置、雕塑、行为与日常物件转换研究流散、身体、家庭空间、权力和危险感。',methods:['尺度转换','日常物件陌生化','身体性装置','材料对立'],subjects:['流散','身体','家庭空间','权力','边界与危险'],outputs:['装置','雕塑','行为','录像','纸上作品'],institutions:['Tate'],achievements:['Measures of Distance','Homebound','Hot Spot'],whyImportant:'Hatoum把厨房器具、家具、地图等熟悉对象转化为具有威胁性的空间结构，使家庭、身体和地缘政治之间建立直接的感官联系，是后殖民装置艺术的重要节点。',projects:[{year:'1988',title:'Measures of Distance',type:'录像',facts:['作品把母亲身体、私人书信与流散经验叠合。'],reading:'亲密家庭交流与政治造成的距离在同一影像结构中出现。'},{year:'2006',title:'Hot Spot',type:'雕塑 / 地图',facts:['以发光网格地球形式处理全球冲突与危险。'],reading:'世界地图不再是中性的地理模型，而成为持续处于危机状态的身体。'}],images:[],sourceLabel:'Tate · Mona Hatoum',sourceUrl:'https://www.tate.org.uk/art/artists/mona-hatoum-2365'},
...artistBatch106
];