import type { Artist } from './data';
import { artistBatch92 } from './expansionBatch92';

export const artistBatch91: Artist[] = [
{id:'hank-willis-thomas',name:'Hank Willis Thomas',born:'1976',base:'United States',intro:'美国观念艺术家，以摄影、挪用、雕塑和公共艺术研究广告、种族表征、消费文化与大众图像如何塑造身份。',methods:['广告图像挪用','观念摄影','公共艺术','档案再编辑'],subjects:['种族表征','广告','消费文化','黑人身份','大众媒介'],outputs:['摄影','雕塑','装置','公共艺术'],institutions:['MoMA','MoMA PS1'],achievements:['UNBRANDED: Reflections in Black by Corporate America 1968–2008','Greater New York 2010','For Freedoms'],whyImportant:'Thomas把商业广告档案转化为对视觉文化权力的系统分析，连接摄影、黑人研究、品牌机制与公共政治参与。',projects:[{year:'2005–2008',title:'UNBRANDED: Reflections in Black by Corporate America 1968–2008',type:'挪用摄影系列',facts:['挪用面向非裔美国人或包含黑人主体的杂志广告。','数字移除品牌信息，使种族、性别与消费文化中的刻板印象成为观看重点。'],reading:'去除商标后，广告不再首先作为商品传播，而暴露大众图像如何制造并重复社会身份。'}],images:[],sourceLabel:'MoMA · Hank Willis Thomas',sourceUrl:'https://www.moma.org/artists/38739-hank-willis-thomas'},
{id:'awoiska-van-der-molen',name:'Awoiska van der Molen',born:'1972',base:'Netherlands',intro:'荷兰摄影艺术家，以长期独处和缓慢行走进入偏远自然环境，并在暗房手工制作深黑色大尺幅银盐风景照片。',methods:['长期风景摄影','暗房手工放印','黑白摄影','缓慢观察'],subjects:['自然','孤独','黑暗','时间','感知'],outputs:['摄影','摄影书'],institutions:['Foam'],achievements:['Blanco','Sequester','Deutsche Börse Photography Prize 2017 nomination'],whyImportant:'她把当代风景摄影从地理记录转向身体性的时间经验与暗房物质性，是欧洲当代黑白风景摄影的重要节点。',projects:[{year:'2009–',title:'Blanco / monochrome landscapes',type:'黑白风景摄影',facts:['长期独自在偏远自然环境中行走并反复返回。','以手工制作的大尺幅银盐照片呈现极深暗部和光线层次。'],reading:'作品弱化具体地点与昼夜线索，让风景成为关于观看时间、孤独和感知阈值的经验。'}],images:[],sourceLabel:'Foam · Awoiska van der Molen — Blanco',sourceUrl:'https://www.foam.org/events/awoiska-van-der-molen'},
{id:'broomberg-chanarin',name:'Adam Broomberg & Oliver Chanarin',born:'1970 / 1971',base:'South Africa / United Kingdom',intro:'1998至2021年合作的摄影艺术家组合，以观念摄影、档案、书籍和影像研究战争摄影、新闻制度、证据政治与图像传播。',methods:['观念摄影','档案研究','摄影书','媒介批评'],subjects:['战争','新闻图像','证据','权力','摄影制度'],outputs:['摄影','摄影书','影像','装置'],institutions:['Tate'],achievements:['Deutsche Börse Photography Foundation Prize 2014','The Day Nobody Died','War Primer 2'],whyImportant:'他们把摄影的重点从“拍到了什么”转向图像由谁生产、如何流通及如何获得证据权威，是后纪实摄影与摄影制度批评的重要组合。',projects:[{year:'2008',title:'The Day Nobody Died',type:'观念摄影项目',facts:['项目围绕艺术家进入阿富汗战争环境时对战地摄影惯例的质疑展开。','作品以摄影材料、战争现场与图像生产条件之间的关系作为核心。'],reading:'项目把摄影行为本身及其制度条件置于前景，而非继续生产传统战地新闻图像。'}],images:[],sourceLabel:'Tate · Adam Broomberg & Oliver Chanarin',sourceUrl:'https://www.tate.org.uk/art/artists/adam-broomberg-and-oliver-chanarin-15515'},
{id:'boris-mikhailov',name:'Boris Mikhailov',born:'1938',base:'Ukraine / Germany',intro:'乌克兰摄影艺术家，以快照、手工着色、文字、序列和社会纪实长期记录苏联及后苏联社会中的私人生活、贫困、身体与政治转型。',methods:['社会纪实','摄影序列','手工着色','摄影书'],subjects:['后苏联社会','贫困','身体','日常生活','政治转型'],outputs:['摄影','摄影书','装置'],institutions:['Tate','MoMA'],achievements:['Case History','Red Series','Yesterday’s Sandwich'],whyImportant:'Mikhailov将私人快照、粗粝纪实与概念性序列结合，形成理解苏联晚期和后苏联社会视觉史的关键摄影实践。',projects:[{year:'1997–1998',title:'Case History',type:'社会纪实摄影系列',facts:['在后苏联时期的哈尔科夫拍摄社会边缘群体。','以直接且具有争议性的身体图像呈现经济转型后的贫困与失序。'],reading:'系列迫使观看者面对纪实摄影中的社会不平等，同时也持续引发关于摄影者权力与观看伦理的讨论。'}],images:[],sourceLabel:'MoMA · Boris Mikhailov',sourceUrl:'https://www.moma.org/artists/3931'},
{id:'sammy-baloji',name:'Sammy Baloji',born:'1978',base:'Democratic Republic of the Congo / Belgium',intro:'刚果民主共和国艺术家，以摄影、拼贴、档案和装置研究加丹加矿业、殖民档案、资源开采、工业遗迹与当代全球经济之间的连续关系。',methods:['档案拼贴','摄影研究','场域调查','后殖民研究'],subjects:['矿业','殖民主义','资源开采','工业遗迹','记忆'],outputs:['摄影','装置','影像'],institutions:['Venice Biennale'],achievements:['Mémoire','Congo Far West','Venice Biennale participation'],whyImportant:'Baloji把殖民时期档案照片重新嵌入当代矿区与工业景观，使摄影成为追踪殖民经济如何延续进全球资源体系的方法。',projects:[{year:'2006',title:'Mémoire',type:'档案拼贴摄影系列',facts:['将殖民时期矿业档案人物与当代加丹加工业遗址并置。','通过时间错置连接殖民劳动史与矿业景观的当代遗产。'],reading:'档案人物重新进入废弃或变化后的工业空间，使被切断的劳动史与资源史重新获得可见关系。'}],images:[],sourceLabel:'La Biennale di Venezia · Sammy Baloji',sourceUrl:'https://www.labiennale.org/en/art/2015/artists/sammy-baloji'},
...artistBatch92
];
