import type { Artist } from './data';

export const artistBatch182: Artist[] = [
{id:'thomas-ruff',name:'Thomas Ruff',born:'1958',base:'Germany',intro:'德国摄影艺术家，以类型化肖像、夜视图像、互联网JPEG、数字处理与计算机生成图像持续检验摄影的真实性、技术条件与图像表面。',methods:['类型学摄影','图像挪用','数字处理','无相机摄影'],subjects:['摄影真实性','互联网图像','监控视觉','肖像','数字图像'],outputs:['摄影','数字图像','艺术家书'],institutions:['MoMA','MoMA PS1'],achievements:['Portraits 1980s','Jpegs 2000s','Inbox: Thomas Ruff, MoMA 2014'],whyImportant:'Ruff把杜塞尔多夫摄影传统推进到数字图像时代，从照相机拍摄扩展到网络图像、像素和计算机生成，使“照片如何被制造”本身成为主题。',projects:[{year:'2000s',title:'Jpegs',type:'互联网图像挪用系列',facts:['下载低分辨率JPEG并放大为巨幅照片，使像素结构显现。'],reading:'把网络流通图像的压缩、失真和传播机制变成摄影的可见材料。'}],images:[],sourceLabel:'MoMA · Thomas Ruff',sourceUrl:'https://www.moma.org/artists/6982-thomas-ruff'},
{id:'thomas-struth',name:'Thomas Struth',born:'1954',base:'Germany',intro:'德国摄影艺术家，从无人城市街景扩展到博物馆观众、家庭肖像、工业与科学设施，研究建筑、观看制度、社会关系与技术现代性。',methods:['大型摄影','类型学观察','城市调查','制度空间摄影'],subjects:['城市','博物馆','家庭','技术','建筑','观看'],outputs:['摄影','出版'],institutions:['MoMA'],achievements:['Unconscious Places','Museum Photographs','MoMA collection'],whyImportant:'Struth把类型学摄影从建筑记录扩展为对城市历史、观看行为、亲密关系与技术系统的持续研究，是杜塞尔多夫学派最重要的国际节点之一。',projects:[{year:'1970s–',title:'Unconscious Places',type:'城市摄影系列',facts:['在德国、美国、日本等地拍摄城市街道与建筑环境。'],reading:'看似中性的街景被作为战后历史、规划和社会结构留下的空间证据。'}],images:[],sourceLabel:'MoMA · Thomas Struth',sourceUrl:'https://www.moma.org/artists/7825-thomas-struth'},
{id:'candida-hofer',name:'Candida Höfer',born:'1944',base:'Germany',intro:'德国摄影艺术家，以大型、精确而通常无人出现的图书馆、博物馆、剧院和其他公共室内空间研究文化制度、建筑秩序与集体观看空间。',methods:['大型摄影','类型学摄影','建筑内部摄影','系列研究'],subjects:['文化机构','图书馆','博物馆','公共空间','建筑'],outputs:['摄影','出版'],institutions:['MoMA','MoMA PS1'],achievements:['Deutsche Bucherei Leipzig IX 1997','MoMA collection'],whyImportant:'Höfer把公共文化空间本身转化为肖像对象；人物的缺席反而强化制度如何组织知识、行为与观看，是杜塞尔多夫摄影谱系的重要女性节点。',projects:[{year:'1997',title:'Deutsche Bucherei Leipzig IX',type:'建筑内部摄影',facts:['拍摄莱比锡德国图书馆内部，作品为MoMA收藏。'],reading:'空间的重复结构、尺度和秩序成为文化制度的视觉表征。'}],images:[],sourceLabel:'MoMA · Candida Höfer',sourceUrl:'https://www.moma.org/artists/34220-candida-hofer'},
{id:'ana-mendieta',name:'Ana Mendieta',born:'1948–1985',base:'Cuba / United States',intro:'古巴出生的美国艺术家，以身体、土地、血液、火、泥土与摄影/电影记录形成“earth-body”实践，处理流亡、女性身体、归属与自然。',methods:['身体艺术','土地艺术','行为','现场介入'],subjects:['身体','流亡','土地','女性身份','自然','仪式'],outputs:['行为','摄影','电影','雕塑','土地作品'],institutions:['MoMA'],achievements:['Silueta Series 1970s–80s','MoMA collection'],whyImportant:'Mendieta把女性身体与土地直接结合，突破传统雕塑和行为艺术边界，对女性主义艺术、离散身份、生态身体实践及行为摄影均具有持续影响。',projects:[{year:'1970s–1980s',title:'Silueta Series',type:'earth-body现场行动',facts:['在土地中以身体轮廓、泥土、植物、火等形成短暂形象，并通过摄影和电影保存。'],reading:'身体既出现又消失，使归属、流亡和自然之间的关系成为作品结构。'}],images:[],sourceLabel:'MoMA · Ana Mendieta',sourceUrl:'https://www.moma.org/artists/3924-ana-mendieta'},
{id:'joan-jonas',name:'Joan Jonas',born:'1936',base:'United States',intro:'美国跨媒介艺术家，自1960年代末以来将行为、录像、镜子、面具、绘画、声音和装置结合，研究身体、神话、女性身份与媒介反馈。',methods:['录像表演','跨媒介装置','身体表演','媒介反馈'],subjects:['身体','神话','女性身份','观看','叙事','生态'],outputs:['录像','行为','装置','绘画','声音'],institutions:['MoMA'],achievements:['Vertical Roll 1972','Organic Honey’s Visual Telepathy 1972','Joan Jonas: Good Night Good Morning, MoMA 2024'],whyImportant:'Jonas是录像与行为艺术交叉史的关键先驱，把实时视频反馈、身体动作和装置空间结合，对之后的影像装置与女性主义媒介实践影响深远。',projects:[{year:'1972',title:'Vertical Roll',type:'录像行为',facts:['利用电视图像垂直滚动与身体动作之间的节奏关系构成作品。'],reading:'技术故障不再是噪声，而成为组织身体、时间和观看的结构。'}],images:[],sourceLabel:'MoMA · Joan Jonas',sourceUrl:'https://www.moma.org/artists/2930-joan-jonas'},
{id:'maria-lassnig',name:'Maria Lassnig',born:'1919–2014',base:'Austria',intro:'奥地利艺术家，以“身体意识”绘画和自画像从内部身体感觉而非外部视觉描绘身体，并同时实践动画与电影。',methods:['身体意识绘画','自画像','感知研究','动画'],subjects:['身体','自我感知','性别','衰老','主体性'],outputs:['绘画','素描','动画','电影'],institutions:['MoMA'],achievements:['Body-awareness painting','MoMA collection'],whyImportant:'Lassnig把身体图像从外观再现转向内部感觉地图，使感知本身成为绘画方法，是战后欧洲身体艺术、女性主义绘画和自画像传统的重要节点。',projects:[{year:'1971–1974',title:'Stone Lifting. A Self Portrait in Progress',type:'自画像/身体意识作品',facts:['MoMA收藏的自画像作品之一。'],reading:'身体不是固定轮廓，而是由压力、触觉和内部感觉不断重新构成。'}],images:[],sourceLabel:'MoMA · Maria Lassnig',sourceUrl:'https://www.moma.org/artists/3402-maria-lassnig'}
];