import type { Artist } from './data';

const project = (year:string,title:string,type:string,facts:string[],reading:string) => ({year,title,type,facts,reading});

export const artistBatch33: Artist[] = [
 {id:'aida-muluneh',name:'Aïda Muluneh',born:'1974',base:'Addis Ababa / global',intro:'以高度编排的色彩、身体与象征性场景重新组织非洲女性经验和埃塞俄比亚视觉文化。',methods:['编排摄影','肖像','色彩构成','象征叙事'],subjects:['女性','非洲身份','传统与现代性','身体','社会记忆'],outputs:['摄影','展览','公共影像项目'],institutions:['MoMA','Addis Foto Fest'],achievements:['Being: New Photography 2018 · MoMA'],whyImportant:'她把非洲摄影从外部纪实凝视转向由本地艺术家主动控制的舞台、身体和视觉符号，同时也是东非摄影机构网络的重要建设者。',projects:[project('2016','Distant Echoes / selected works','编排摄影',['2016年的多件作品进入MoMA收藏并在Being: New Photography 2018展出。','通过鲜明色块、身体绘饰与道具建立非写实空间。'],'重点在摄影师主动制造图像，而不是把非洲当作被记录对象。')],images:[],sourceLabel:'MoMA',sourceUrl:'https://www.moma.org/artists/68306-aida-muluneh'},
 {id:'dawoud-bey',name:'Dawoud Bey',born:'1953',base:'Chicago',intro:'从哈莱姆街头肖像到大型编排肖像和历史景观，持续研究黑人主体、观看伦理与美国历史。',methods:['肖像摄影','长期项目','合作式摄影','历史研究','景观摄影'],subjects:['黑人经验','美国历史','社群','种族','记忆','可见性'],outputs:['摄影','摄影书','展览'],institutions:['Whitney Museum','SFMOMA','Studio Museum in Harlem'],achievements:['Whitney Biennial 2014','Dawoud Bey: An American Project · Whitney 2021'],whyImportant:'他把肖像摄影明确理解为与被摄者协作的伦理实践，并进一步用摄影重新想象未被充分视觉化的黑人历史。',projects:[project('2012','The Birmingham Project','历史肖像 / 纪念',['以双联肖像纪念1963年伯明翰种族暴力中遇害的六名黑人儿童。','把与遇害者同龄的青年和他们如果活到2012年应有年龄的成年人配对。'],'摄影不是复原历史现场，而是让缺席者通过年龄与时间关系重新进入当下。')],images:[],sourceLabel:'Whitney Museum',sourceUrl:'https://whitney.org/exhibitions/dawoud-bey'},
 {id:'shirin-neshat',name:'Shirin Neshat',born:'1957',base:'New York',intro:'以摄影、录像和电影处理伊朗、性别、宗教、流亡与权力，常以身体、文字、声音和双屏结构制造对立。',methods:['编排摄影','录像装置','电影','文本介入','双屏叙事'],subjects:['伊朗','女性','宗教','权力','流亡','性别'],outputs:['摄影','录像装置','电影'],institutions:['MoMA','MoMA PS1','Venice Biennale'],achievements:['Golden Lion · Venice Biennale 1999'],whyImportant:'她是1990年代以来把摄影与多屏影像用于离散身份、性别和伊朗政治文化讨论的关键人物。',projects:[project('1999','Rapture','双屏录像装置',['以男女分置的空间和群体行动形成视觉对照。','作品进入MoMA收藏。'],'双屏并非展示两个故事，而是让性别化空间在观看现场持续冲突。')],images:[],sourceLabel:'MoMA',sourceUrl:'https://www.moma.org/artists/8349-shirin-neshat'},
 {id:'stan-douglas',name:'Stan Douglas',born:'1960',base:'Vancouver',intro:'以摄影、电影、录像与复杂重演研究历史事件、媒介技术和被压抑的社会记忆。',methods:['历史重演','电影装置','数字合成','档案研究','场景搭建'],subjects:['历史','技术','种族','城市','记忆','媒介'],outputs:['摄影','录像','电影装置','数字影像'],institutions:['MoMA','Venice Biennale','Documenta'],achievements:['Canada Pavilion · Venice Biennale 2022'],whyImportant:'他把历史摄影与电影语言推进到高度制作化的重演系统：图像看似纪录，却往往由布景、演员、档案和数字技术重新构造。',projects:[project('2012','Disco Angola','编排摄影 / 虚构历史',['把1970年代纽约地下迪斯科与安哥拉独立战争并置。','以演员、服装和历史视觉语言制造貌似档案的照片。'],'作品追问我们为何会相信某种摄影风格天然属于历史证据。')],images:[],sourceLabel:'MoMA',sourceUrl:'https://www.moma.org/artists/8153-stan-douglas'},
 {id:'yinka-shonibare',name:'Yinka Shonibare',born:'1962',base:'London',intro:'以荷兰蜡染布、无头人体雕塑、摄影、电影和装置讨论殖民主义、阶级、全球贸易与混杂身份。',methods:['历史挪用','编排摄影','雕塑装置','服装','电影'],subjects:['殖民','身份','阶级','迁移','全球化','英国历史'],outputs:['雕塑','装置','摄影','电影','公共艺术'],institutions:['Tate','Venice Biennale','Royal Academy'],achievements:['Turner Prize nominee 2004','Nelson’s Ship in a Bottle · Fourth Plinth 2010'],whyImportant:'他通过被误认为“纯非洲”的荷兰蜡染布揭示文化身份本身就是贸易、殖民和迁移长期混合的产物。',projects:[project('2014','The British Library','装置 / 迁移档案',['以数千本包覆蜡染布的书构成图书馆。','部分书脊写有英国第一、二代移民姓名。'],'把国家文化身份转化为由迁移者姓名和全球流通材料组成的可见结构。')],images:[],sourceLabel:'Tate',sourceUrl:'https://www.tate.org.uk/art/artists/yinka-shonibare-cbe-2659'}
];
