import type { Artist } from './data';

const project = (year:string,title:string,type:string,facts:string[],reading:string) => ({year,title,type,facts,reading});

export const artistBatch35: Artist[] = [
 {id:'cindy-sherman',name:'Cindy Sherman',born:'1954',base:'New York',intro:'以自己作为模特，通过服装、化妆、道具和角色扮演制造虚构人物，持续研究身份与大众媒介中的女性形象。',methods:['编排摄影','自我表演','角色扮演','挪用大众文化'],subjects:['身份','性别','电影','时尚','再现'],outputs:['摄影','大型彩色照片'],institutions:['MoMA'],achievements:['Pictures Generation 重要艺术家','MoMA 回顾展 2012'],whyImportant:'她把自拍式自我呈现转化为对电影、广告和艺术史角色模板的系统拆解，是编排摄影与身份政治的重要节点。',projects:[project('1977–1980','Untitled Film Stills','编排摄影 / 自我表演',['艺术家同时担任摄影者、模特和造型者。','借虚构电影剧照研究女性角色类型。'],'关键不是自传，而是让观众意识到身份如何被既有视觉代码制造。')],images:[],sourceLabel:'MoMA',sourceUrl:'https://www.moma.org/artists/5392-cindy-sherman'},
 {id:'jeff-wall',name:'Jeff Wall',born:'1946',base:'Vancouver',intro:'以大型灯箱摄影和高度编排的场景，把街头观察、电影制作与艺术史构图结合。',methods:['编排摄影','大型摄影','电影式制作','数字合成'],subjects:['日常生活','城市','劳动','社会关系','艺术史'],outputs:['灯箱摄影','大型摄影'],institutions:['Tate'],achievements:['大型灯箱摄影的重要先驱'],whyImportant:'他把摄影推进到接近历史画和电影制作的尺度，使“看似瞬间”的照片可以由演员、布景与长期制作重新构造。',projects:[project('1993','A Sudden Gust of Wind (after Hokusai)','编排摄影 / 数字合成',['参考葛饰北斋图像。','通过表演和多次拍摄构造一个看似偶发的瞬间。'],'它清楚展示纪实外观如何由复杂制作流程生成。')],images:[],sourceLabel:'Tate',sourceUrl:'https://www.tate.org.uk/art/artists/jeff-wall-2359'},
 {id:'thomas-ruff',name:'Thomas Ruff',born:'1958',base:'Düsseldorf',intro:'从冷静的大幅肖像扩展到夜视、网络色情、天文图像和数字压缩图像，持续研究摄影技术如何决定可见性。',methods:['类型学','图像挪用','数字处理','技术图像研究'],subjects:['肖像','互联网','监控','图像技术','摄影真实性'],outputs:['摄影','数字图像','大型打印'],institutions:['MoMA'],achievements:['杜塞尔多夫摄影学派重要成员'],whyImportant:'他的实践让摄影史从相机拍摄扩展到网络文件、监控技术和机器图像，是理解后摄影的重要桥梁。',projects:[project('1980s–1990s','Portraits','类型学肖像',['使用统一、正面的肖像结构。','弱化表情与心理叙事。'],'肖像在这里更像图像制度而不是人物性格的窗口。')],images:[],sourceLabel:'MoMA',sourceUrl:'https://www.moma.org/artists/6982-thomas-ruff'},
 {id:'thomas-struth',name:'Thomas Struth',born:'1954',base:'Berlin / New York',intro:'从无人街道、家庭肖像和博物馆观众扩展到实验室与复杂技术设施，以大画幅摄影研究社会空间和观看制度。',methods:['大画幅摄影','类型学','长期系列','空间观察'],subjects:['城市','博物馆','家庭','技术','观看'],outputs:['摄影','大型彩色照片'],institutions:['MoMA'],achievements:['杜塞尔多夫摄影学派重要成员'],whyImportant:'他把建筑、家庭、博物馆和技术系统视为社会结构的可见表面，使摄影成为观察制度如何组织人的工具。',projects:[project('1970s–','Unconscious Places','城市摄影',['系统拍摄欧洲、美国和日本城市街道。','早期作品常采用无人、正面和冷静视点。'],'城市不是背景，而是历史与社会关系留下的结构。')],images:[],sourceLabel:'MoMA',sourceUrl:'https://www.moma.org/artists/7825-thomas-struth'},
 {id:'hiroshi-sugimoto',name:'Hiroshi Sugimoto',chineseName:'杉本博司',born:'1948',base:'New York / Tokyo',intro:'以严格的大画幅黑白摄影和长曝光研究时间、记忆、历史与摄影真实性。',methods:['大画幅摄影','长曝光','系列摄影','观念摄影'],subjects:['时间','海洋','电影','历史','再现'],outputs:['银盐摄影','建筑项目','装置'],institutions:['Guggenheim'],achievements:['Theaters 与 Seascapes 成为观念摄影经典系列'],whyImportant:'他把曝光时间本身变成主题：一部电影可以压缩为一张白色银幕，一片海则把历史尺度与摄影瞬间并置。',projects:[project('1978–','Theaters','长曝光摄影',['曝光时间覆盖整部电影的放映。','银幕最终因累积光线呈现为明亮白色。'],'一张照片同时记录大量已经消失的电影时间。')],images:[],sourceLabel:'Guggenheim',sourceUrl:'https://www.guggenheim.org/teaching-materials/teaching-modern-and-contemporary-asian-art/hiroshi-sugimoto-%E6%9D%89%E6%9C%AC%E5%8D%9A%E5%8F%B8'},
 {id:'sharon-lockhart',name:'Sharon Lockhart',born:'1964',base:'Los Angeles',intro:'在摄影与结构电影之间工作，通过长期进入社区、固定镜头和轻度编排研究日常动作、劳动、儿童与观看时间。',methods:['长期田野','固定镜头','编排摄影','结构电影','社区合作'],subjects:['儿童','日常生活','劳动','社区','时间'],outputs:['摄影','16mm电影','装置'],institutions:['Walker Art Center','Whitney Biennial'],achievements:['多次参加 Whitney Biennial'],whyImportant:'她故意模糊照片与电影：照片具有表演性，电影则像持续很久的静态照片，是理解摄影时间性的重要艺术家。',projects:[project('2005','Pine Flat','摄影 / 16mm电影 / 社区项目',['在加州 Sierra Nevada 山麓社区长期工作。','以十二个固定机位十分钟段落及肖像摄影观察当地儿童。'],'作品用缓慢时间取代事件驱动的纪录片叙事。')],images:[],sourceLabel:'Walker Art Center',sourceUrl:'https://www.walkerart.org/whats-on/sharon-lockhart-pine-flat/'}
];
