import type { Artist } from './data';
import { artistBatch151 } from './expansionBatch151';

export const artistBatch150: Artist[] = [
{id:'deana-lawson',name:'Deana Lawson',born:'1979',base:'United States',intro:'美国摄影与影像艺术家，通过与陌生人的协作和精密编排的家庭室内场景，连接黑人离散经验、家庭相册、历史肖像、欲望与精神性。',methods:['编排摄影','协作肖像','室内场景建构','家族神话建构'],subjects:['黑人离散','家庭','亲密关系','身体','精神性','自我呈现'],outputs:['摄影','电影','装置'],institutions:['Guggenheim','MoMA PS1','Whitney Museum'],achievements:['Hugo Boss Prize 2020','Guggenheim exhibition Centropy 2021'],whyImportant:'Lawson把纪实摄影、家庭相册与高度控制的编排摄影融合，使黑人日常生活既保持具体社会现实，又进入尊严、欲望、神话和精神世界的复杂视觉结构。',projects:[{year:'2021',title:'Centropy',type:'摄影 / 装置',facts:['Guggenheim展览将大型摄影、全息元素与镜面框架组织为密集装置。','作品延续艺术家与陌生拍摄对象协作、精确控制室内陈设与姿态的方法。'],reading:'家庭空间不再只是纪录背景，而成为构造黑人离散共同体、记忆和不可见精神关系的舞台。'}],images:[],sourceLabel:'Guggenheim · Deana Lawson',sourceUrl:'https://www.guggenheim.org/wp-content/uploads/2021/04/guggenheim-welcome-packet-20210420.pdf'},
{id:'awoiska-van-der-molen',name:'Awoiska van der Molen',born:'1972',base:'Netherlands',intro:'荷兰摄影艺术家，以长期独处、夜间或低照度行走和暗房手工放大制作深黑的黑白自然地景，关注时间、感知、孤独与不可测量的自然经验。',methods:['长期独处','缓慢观看','暗房手工放大','低照度地景'],subjects:['自然','黑暗','时间','孤独','感知','地景'],outputs:['黑白摄影','银盐放大','摄影书'],institutions:['Foam'],achievements:['Blanco, Foam 2016','Deutsche Börse Photography Prize nominee 2017','Sequester shortlisted Paris Photo–Aperture First PhotoBook Prize'],whyImportant:'Van der Molen在数字图像高速流通的背景下坚持缓慢身体经验与手工银盐制作，把当代地景摄影重新连接到时间、黑暗和观看本身。',projects:[{year:'2009–16',title:'Blanco / Sequester',type:'黑白地景摄影',facts:['Foam于2016年举办其首个大型博物馆个展Blanco。','她长期独自在偏远自然中行走，并在暗房手工制作深黑的大幅银盐照片。'],reading:'作品主动去除人物与明确事件，使观看者面对黑暗、尺度和时间的不确定性，而不是把自然当作可快速识别的风景。'}],images:[],sourceLabel:'Foam · Awoiska van der Molen — Blanco',sourceUrl:'https://www.foam.org/events/awoiska-van-der-molen'},
{id:'hoda-afshar',name:'Hoda Afshar',born:'1983',base:'Iran / Australia',intro:'伊朗出生、澳大利亚工作的摄影与影像艺术家，在纪录与观念摄影之间研究国家暴力、边境制度、流亡、性别和图像如何塑造政治可见性。',methods:['观念纪录','协作实践','编排与证言','影像研究'],subjects:['迁徙','边境','国家暴力','女性权利','流亡','再现政治'],outputs:['摄影','影像','装置','摄影书'],institutions:['Foam'],achievements:['Foam Paul Huf Award 2024 special mention'],whyImportant:'Afshar持续质疑纪录摄影所谓透明客观的观看方式，把被摄者、证言和图像生产条件重新纳入作品，是当代政治纪录摄影向观念实践转型的重要案例。',projects:[{year:'2023–24',title:'In Turn',type:'摄影 / 观念纪录',facts:['Foam Paul Huf Award 2024评审特别提及该项目。','Foam将作品与持续发生的伊朗女性权利抗议联系起来，并指出其实践推动纪录与观念摄影边界。'],reading:'项目不是简单把抗议作为新闻事件记录，而把身体、抵抗与图像如何代表政治主体的问题同时放进摄影内部。'}],images:[],sourceLabel:'Foam · Paul Huf Award 2024',sourceUrl:'https://www.foam.org/press/fpha2024-hien-hoang'},
{id:'myriam-boulos',name:'Myriam Boulos',born:'1992',base:'Lebanon',intro:'黎巴嫩摄影师，以高度贴近身体与私人生活的日记式摄影记录贝鲁特的青年、亲密关系、街头抗议与政治危机，将个人欲望和公共革命并置。',methods:['日记式摄影','亲密纪录','第一人称叙事','街头观察'],subjects:['贝鲁特','革命','身体','亲密关系','青年','政治危机'],outputs:['摄影','摄影书','编辑项目'],institutions:['Aperture','Magnum Foundation'],achievements:['What’s Ours, Aperture 2023'],whyImportant:'Boulos把私人身体、家庭和街头政治放在同一视觉叙事中，使宏大的黎巴嫩危机通过个人生活的裂缝被经验，是新一代中东第一人称纪录实践的重要代表。',projects:[{year:'2017–20',title:'What’s Ours',type:'摄影系列 / 摄影书',facts:['Aperture于2023年出版其首部专著What’s Ours。','Aperture将其描述为对处于革命状态的贝鲁特进行尖锐、日记式描绘的作品。'],reading:'私人关系和公共政治不是两条平行线，而是在同一身体与城市空间中不断相互侵入。'}],images:[],sourceLabel:'Aperture · Myriam Boulos: What’s Ours',sourceUrl:'https://aperture.org/events/paris-photo-2023/'},
...artistBatch151
];