import type { Artist } from './data';
import { artistBatch154 } from './expansionBatch154';

export const artistBatch153: Artist[] = [
{id:'dayanita-singh',name:'Dayanita Singh',born:'1961',base:'India',intro:'印度摄影艺术家，以摄影书、可移动木制展示结构和不断重编的图像档案重新思考摄影、出版与博物馆之间的关系。',methods:['摄影书作为作品','模块化展示','档案重编','自我策展'],subjects:['档案','家庭与社会空间','博物馆制度','图像流通','记忆'],outputs:['摄影','摄影书','木制展示结构','装置'],institutions:['MoMA','MoMA PS1'],achievements:['Museum Bhavan, Steidl 2017','Museum Bhavan presentation at MoMA PS1 2018'],whyImportant:'Singh把摄影从固定墙面作品扩展为可移动、可重组、可出版和可由观众重新策展的系统，使摄影书本身成为展览空间，是当代摄影展示机制转型的重要人物。',projects:[{year:'2017–18',title:'Museum Bhavan',type:'摄影 / 出版 / 模块化博物馆',facts:['Museum Bhavan由九个可移动木制结构构成，每个结构容纳艺术家拍摄的图像。','项目又被转化为十册可携带的“口袋博物馆”，允许读者在家庭空间自行展开和策展。'],reading:'作品取消摄影书、展览和博物馆之间的固定边界，让图像的编排、移动与再策展成为摄影实践本身。'}],images:[],sourceLabel:'MoMA · Dayanita Singh: Museum Bhavan',sourceUrl:'https://www.moma.org/calendar/events/4318'},
{id:'zanele-muholi',name:'Zanele Muholi',born:'1972',base:'South Africa',intro:'南非视觉行动者与摄影艺术家，长期以肖像、自画像和影像记录并共同建构南非黑人LGBTQIA+社群的可见性、尊严与历史档案。',methods:['视觉行动主义','长期社群肖像','自画像','协作式记录'],subjects:['黑人酷儿社群','性别','身份','可见性','自我表述','南非社会'],outputs:['摄影','自画像','影像','雕塑'],institutions:['Tate Modern','MoMA','Guggenheim','Brooklyn Museum'],achievements:['Tate Modern retrospective 2024–25','ICP Infinity Award for Documentary and Photojournalism 2016'],whyImportant:'Muholi把纪实肖像明确转化为视觉行动主义：被拍摄者不是被动社会学对象，而是共同构成黑人酷儿历史、亲密关系和公共可见性的主体，是当代身份摄影的重要节点。',projects:[{year:'2006–',title:'Faces and Phases',type:'长期肖像 / 社群档案',facts:['Muholi长期记录南非黑人女同性恋、跨性别及其他酷儿社群成员。','Tate将其描述为南非视觉行动者，并于2024至2025年举办大型展览。'],reading:'连续肖像既建立个人尊严，也累积一个常被主流历史遗漏的社群档案；摄影因此同时承担见证、纪念与政治可见性的功能。'}],images:[],sourceLabel:'Tate · Zanele Muholi',sourceUrl:'https://www.tate.org.uk/whats-on/tate-modern/zanele-muholi'},
{id:'latoya-ruby-frazier',name:'LaToya Ruby Frazier',born:'1982',base:'United States',intro:'美国摄影艺术家，以家族协作、自画像和社会纪实把宾夕法尼亚工业城镇的去工业化、环境健康、种族与阶级问题连接到三代家庭经验。',methods:['协作式纪实','家族档案','自画像','长期社会调查'],subjects:['去工业化','家庭','黑人经验','环境与健康','阶级','社区'],outputs:['摄影','摄影书','影像','装置'],institutions:['Aperture','Whitney Museum','Brooklyn Museum'],achievements:['The Notion of Family, Aperture 2014','MacArthur Fellowship 2015'],whyImportant:'Frazier把经典黑白社会纪实从外部观察改造成家庭成员共同生产的内部叙事，使私人身体、家庭关系和工业资本衰退进入同一个政治结构，是当代社会纪实摄影的重要人物。',projects:[{year:'2001–14',title:'The Notion of Family',type:'黑白摄影 / 家庭协作 / 摄影书',facts:['项目以艺术家的家乡Braddock及祖母、母亲和艺术家本人三代经验为核心。','Aperture指出作品讨论美国小城镇种族主义与经济衰退的遗产，并通过家庭协作重新分配传统纪实摄影中的权力关系。'],reading:'家庭不是宏观政治的私人例外，而是工业衰退、环境压力、种族和阶级结构实际落到身体上的尺度。'}],images:[],sourceLabel:'Aperture · LaToya Ruby Frazier — The Notion of Family',sourceUrl:'https://aperture.org/editorial/aperture-congratulates-latoya-ruby-frazier/'},
{id:'arthur-jafa',name:'Arthur Jafa',born:'1960',base:'United States',intro:'美国艺术家与电影摄影师，以影像、电影剪辑、摄影和装置研究黑人视觉文化、音乐、历史创伤以及图像如何承载黑人经验的强度。',methods:['影像蒙太奇','发现影像重组','电影摄影','文化档案采样'],subjects:['黑人视觉文化','音乐','种族','历史记忆','大众媒介','美国社会'],outputs:['录像','电影','摄影','装置'],institutions:['Whitney Museum'],achievements:['Whitney Biennial 2000','Whitney collection'],whyImportant:'Jafa把电影摄影、网络流通图像、音乐和黑人文化档案压缩进高强度蒙太奇，使影像编辑本身成为研究黑人经验如何被大众媒介表现、消费和重新占有的方法。',projects:[{year:'2018',title:'akingdoncomethas',type:'录像 / 声音 / 装置',facts:['Whitney收藏该作。','作品为105分钟彩色有声录像装置。'],reading:'长时段影像与声音组织延续Jafa对黑人宗教、音乐、表演和大众图像之间情感强度的研究，并把剪辑视为文化关系的生产方式。'}],images:[],sourceLabel:'Whitney · Arthur Jafa — akingdoncomethas',sourceUrl:'https://whitney.org/collection/works/65994'},
...artistBatch154
];