import type { Artist } from './data';
import { artistBatch147 } from './expansionBatch147';

export const artistBatch146: Artist[] = [
{id:'ming-smith',name:'Ming Smith',born:'1947',base:'United States',intro:'美国摄影艺术家，以低照度、长曝光、运动模糊、手工上色与直觉式街头摄影塑造黑人生活、爵士文化和城市经验的诗性视觉。',methods:['直觉摄影','长曝光','运动模糊','手工上色'],subjects:['黑人生活','城市','爵士','身体','光与运动'],outputs:['摄影','银盐照片','手工上色摄影'],institutions:['MoMA'],achievements:['Kamoinge Workshop member','Projects: Ming Smith, MoMA 2023'],whyImportant:'Smith把纪实摄影从信息记录推向身体、光线和运动的感知经验，也是Kamoinge重要成员，为黑人摄影史与实验性街头摄影建立关键连接。',projects:[{year:'1990–91',title:'Invisible Man',type:'摄影系列',facts:['系列受Ralph Ellison小说Invisible Man启发。','MoMA收藏系列相关作品，并记录其对可见性、黑人环境与绘画性摄影的探索。'],reading:'模糊和暗部不是信息缺失，而是把“被看见/不可见”的社会经验转化为摄影形式。'}],images:[],sourceLabel:'MoMA · Ming Smith',sourceUrl:'https://www.moma.org/collection/artists/7906'},
{id:'wangechi-mutu',name:'Wangechi Mutu',born:'1972',base:'Kenya / United States',intro:'肯尼亚出生、往返内罗毕与纽约工作的艺术家，以拼贴、雕塑、影像和装置混合人体、植物、动物、时尚图像与本土材料，讨论殖民遗产、黑人女性身体、生态与混杂身份。',methods:['拼贴','身体重构','神话建构','材料混合'],subjects:['后殖民','黑人女性身体','性别','生态','身份','神话'],outputs:['拼贴','雕塑','影像','装置','绘画'],institutions:['Whitney Museum'],achievements:['Whitney Biennial 2019','Sentinels'],whyImportant:'Mutu以混杂身体和跨媒介材料语言挑战殖民观看与黑人女性身体的异域化，同时把非洲未来主义、生态与后殖民身份带入国际当代艺术核心讨论。',projects:[{year:'2019',title:'Sentinels',type:'雕塑 / 装置',facts:['作品参加2019 Whitney Biennial。','艺术家使用玻璃纤维人体模型部件、树枝、根系及来自肯尼亚的材料建构守卫般人物。'],reading:'身体被重新组装为连接土地、历史和后殖民文化断裂的混合生命。'}],images:[],sourceLabel:'Whitney · Wangechi Mutu, Sentinels',sourceUrl:'https://whitney.org/media/42360'},
{id:'wael-shawky',name:'Wael Shawky',born:'1971',base:'Egypt',intro:'埃及艺术家，以电影、木偶戏、绘画和装置重新叙述十字军历史、宗教与权力关系，尤其关注历史如何因叙述位置不同而被制造和操纵。',methods:['历史重演','木偶剧场','叙事重构','档案再解释'],subjects:['十字军','历史书写','宗教','权力','东西方叙事'],outputs:['电影','木偶','绘画','装置'],institutions:['MoMA','MoMA PS1'],achievements:['Cabaret Crusades'],whyImportant:'Shawky通过从阿拉伯史料重新讲述十字军并使用高度人工化的木偶剧场，使历史叙事的控制、立场和神话化过程直接成为作品主题。',projects:[{year:'2010–15',title:'Cabaret Crusades',type:'电影 / 木偶剧场',facts:['系列以木偶重新叙述十字军历史。','MoMA曾举办Wael Shawky: Cabaret Crusades展览，首部使用约200年历史的意大利木偶，后续使用定制陶瓷人物。'],reading:'明显可见的木偶线把历史人物同时变成被权力、作者和叙事操纵的角色。'}],images:[],sourceLabel:'MoMA · Wael Shawky',sourceUrl:'https://www.moma.org/artists/41664-wael-shawky'},
{id:'tania-bruguera',name:'Tania Bruguera',born:'1968',base:'Cuba / United States',intro:'古巴行为与社会实践艺术家，把移民、公民身份、审查、国家权力和政治参与直接转化为公共行动、制度实验与参与式作品。',methods:['行为艺术','社会实践','参与式行动','制度介入'],subjects:['移民','公民身份','权力','审查','政治参与'],outputs:['行为','公共项目','装置','社会实践'],institutions:['Guggenheim','Tate Modern','MoMA'],achievements:['The Francis Effect','Immigrant Movement International'],whyImportant:'Bruguera把艺术从政治议题的“再现”推进到真实政治行动和制度实验，是理解Arte Útil、参与式艺术以及艺术与公民权利边界的关键人物。',projects:[{year:'2014',title:'The Francis Effect',type:'社会实践 / 公共行动',facts:['项目在Guggenheim开展公众签名行动。','明信片请求教皇给予无证移民梵蒂冈公民身份，项目收集逾万份签名。'],reading:'作品的媒介不是政治事件的图像，而是公众参与、签名和真实制度诉求本身。'}],images:[],sourceLabel:'Guggenheim · The Francis Effect',sourceUrl:'https://www.guggenheim.org/articles/map/map-alfredo-jaar-comes-times-square-tania-bruguera-appears-guggenheim-sheela-gowda-journeys-brazil'},
...artistBatch147
];