import type { Artist } from './data';
import { artistBatch124 } from './expansionBatch124';

export const artistBatch123: Artist[] = [
{id:'aida-muluneh',name:'Aïda Muluneh',born:'1974',base:'Ethiopia',intro:'埃塞俄比亚摄影艺术家与策展人，以高度编排的彩色摄影、身体绘制和象征性场景讨论非洲女性经验、身份、社会议题与非洲图像的自我表述。',methods:['编排摄影','色彩构成','象征性叙事','身体表演'],subjects:['女性','身份','非洲表述','社会与环境议题'],outputs:['摄影','影像'],institutions:['MoMA','Smithsonian National Museum of African Art'],achievements:['Distant Echoes','The Departure','Being: New Photography 2018'],whyImportant:'Muluneh以强烈色彩、身体与非洲视觉文化建立区别于西方新闻摄影传统的当代非洲摄影语言，同时通过策展和摄影平台推动非洲摄影生态。',projects:[{year:'2016',title:'Distant Echoes / The Departure',type:'编排摄影',facts:['MoMA收藏Muluneh于2016年创作的The Departure、Morning Bride、City Life等作品。','她参加MoMA 2018年Being: New Photography展览。'],reading:'人物、身体绘制和高度控制的色彩不再只是肖像元素，而成为讨论身份、记忆与社会处境的符号系统。'}],images:[],sourceLabel:'MoMA · Aïda Muluneh',sourceUrl:'https://www.moma.org/artists/68306-aida-muluneh'},
{id:'samuel-fosso',name:'Samuel Fosso',born:'1962',base:'Cameroon / Central African Republic / France',intro:'喀麦隆出生的摄影艺术家，以戏剧化自画像持续扮演政治人物、流行文化角色与虚构身份，把西非照相馆传统转化为关于黑人身份、权力和图像史的表演性摄影。',methods:['自画像','角色扮演','工作室摄影','历史图像重演'],subjects:['黑人身份','政治历史','媒体图像','自我表述'],outputs:['摄影','宝丽来'],institutions:['SFMOMA','Maison Européenne de la Photographie','The Menil Collection'],achievements:['African Spirits','SIXSIXSIX','The Man with a Thousand Faces'],whyImportant:'Fosso把自拍从私人身份记录转化为历史与政治角色的表演场，使摄影中的身份不再被视为固定事实，而成为可以被扮演、引用和重新占有的结构。',projects:[{year:'2008',title:'African Spirits',type:'摄影 / 表演性自画像',facts:['Fosso在系列中扮演Angela Davis、Martin Luther King Jr.、Patrice Lumumba、Kwame Nkrumah、Malcolm X等20世纪黑人解放人物。','作品重新演绎这些人物已进入公共记忆的标志性照片。'],reading:'艺术家不是简单模仿名人，而是通过自己的身体重新进入黑人政治图像史。'}],images:[],sourceLabel:'Samuel Fosso · official site',sourceUrl:'https://samuelfosso.com/'},
{id:'kiluanji-kia-henda',name:'Kiluanji Kia Henda',born:'1979',base:'Angola / Portugal',intro:'安哥拉艺术家，以摄影、录像、行为和装置研究殖民主义、安哥拉独立后的政治记忆、非洲现代主义与城市未来想象，经常以幽默和虚构改写公共纪念空间。',methods:['编排摄影','历史虚构','公共空间介入','纪念碑重构'],subjects:['殖民主义','后殖民身份','现代主义','城市','集体记忆'],outputs:['摄影','录像','行为','装置'],institutions:['Tate Modern','Centre Pompidou','Venice Biennale','Gwangju Biennale','São Paulo Biennial'],achievements:['Homem Novo','A City Called Mirage','Rusty Mirage'],whyImportant:'Kia Henda把殖民纪念碑、城市建筑和国家现代化想象变成可重新编排的视觉材料，是理解安哥拉及葡语非洲后殖民当代艺术的重要节点。',projects:[{year:'2010–12',title:'Homem Novo (New Man)',type:'摄影 / 行为 / 公共纪念碑介入',facts:['艺术家让当地文化人物站上殖民时代雕像被移除后留下的空基座并进行摄影。','其跨媒介实践长期围绕安哥拉殖民历史、独立与现代主义展开。'],reading:'空基座从权力留下的缺口转变为新的身体可以暂时占据和重新书写历史的位置。'}],images:[],sourceLabel:'ISCP · Kiluanji Kia Henda',sourceUrl:'https://iscp-nyc.org/resident/kiluanji-kia-henda'},
{id:'lebohang-kganye',name:'Lebohang Kganye',born:'1990',base:'South Africa',intro:'南非艺术家，以摄影、剪影、拼贴、装置和表演重新进入家庭相册与口述历史，在私人记忆、种族隔离后的家庭迁徙和虚构叙事之间建立舞台化影像。',methods:['家庭档案重演','摄影拼贴','剪影装置','自我表演'],subjects:['家庭记忆','种族隔离遗产','迁徙','身份','口述史'],outputs:['摄影','装置','影像','剪影'],institutions:['Aperture','Tate Modern'],achievements:['Ke Lefa Laka','Her-story','A World in Common'],whyImportant:'Kganye把家庭相册从静态证据转成可以进入、表演和重新编排的空间，使私人档案成为处理南非历史断裂和代际记忆的方法。',projects:[{year:'2013',title:'Ke Lefa Laka',type:'摄影 / 家庭档案重演',facts:['系列源于艺术家对家庭历史与已故母亲影像的研究。','她通过把自己的表演性影像与家庭照片并置或融合，制造跨越时间的共同场景。'],reading:'摄影不再证明“过去发生过什么”，而成为后代与无法重新抵达的家庭过去建立关系的舞台。'}],images:[],sourceLabel:'Aperture · Lebohang Kganye',sourceUrl:'https://aperture.org/editorial/lebohang-kganye/' },
...artistBatch124
];