import type { Artist } from './data';
import { artistBatch90 } from './expansionBatch90';

export const artistBatch89: Artist[] = [
{id:'rineke-dijkstra',name:'Rineke Dijkstra',born:'1959',base:'Netherlands',intro:'以正面、大尺幅肖像和持续多年重访同一人物的方式研究青春期、身份转变、迁徙与社会角色。',methods:['大尺幅肖像','长期重访','类型化背景','录像肖像'],subjects:['青春期','身份转变','迁徙','社会角色'],outputs:['摄影','录像'],institutions:['MoMA'],achievements:['Beach Portraits','Almerisa','Olivier'],whyImportant:'Dijkstra把看似中性的肖像结构转化为观察人物在时间和制度环境中变化的方法，是当代肖像摄影的重要节点。',projects:[{year:'1994–2008',title:'Almerisa',type:'长期肖像系列',facts:['从荷兰庇护中心开始持续拍摄同一位女孩。','MoMA收藏该系列多个时间节点。'],reading:'同一人物的反复出现把肖像从瞬间记录变成关于迁徙、成长和社会身份的时间结构。'}],images:[],sourceLabel:'MoMA · Rineke Dijkstra',sourceUrl:'https://www.moma.org/artists/8139-rineke-dijkstra'},
{id:'graciela-iturbide',name:'Graciela Iturbide',born:'1942',base:'Mexico',intro:'长期在墨西哥及其他地区进行黑白摄影，通过与当地社群共同生活和持续观察处理原住民文化、仪式、性别、死亡与日常象征。',methods:['长期田野摄影','黑白摄影','社群观察','象征性纪实'],subjects:['原住民社群','仪式','性别','死亡','墨西哥文化'],outputs:['摄影','摄影书'],institutions:['MoMA'],achievements:['Juchitán de las Mujeres','Mujer ángel'],whyImportant:'Iturbide将纪实摄影从快速捕捉转向关系建立与长期在场，使墨西哥社会现实与具有开放解释空间的象征图像并存。',projects:[{year:'1979–1989',title:'Juchitán de las Mujeres',type:'长期摄影项目',facts:['在瓦哈卡Juchitán持续拍摄。','关注当地女性、社会生活与仪式。'],reading:'项目避免把社群简化为民族志对象，而通过长期关系形成复杂的社会肖像。'}],images:[],sourceLabel:'MoMA · Graciela Iturbide',sourceUrl:'https://www.moma.org/collection/artists/2844'},
{id:'ming-smith',name:'Ming Smith',born:'1947',base:'United States',intro:'以富于运动感、低照度、慢快门和实验暗房语言的黑白摄影记录黑人城市生活、音乐、表演与日常经验，是Kamoinge Workshop的重要成员。',methods:['街头摄影','慢快门','低照度摄影','实验暗房'],subjects:['黑人生活','音乐','城市','表演','日常经验'],outputs:['摄影'],institutions:['Whitney Museum'],achievements:['Kamoinge Workshop','Sun Ra, Space II','America Seen through Stars and Stripes'],whyImportant:'Smith把黑人纪实传统与高度主观、诗性的摄影语言结合，拓宽了美国战后街头摄影和黑人视觉文化的历史叙事。',projects:[{year:'1970s–1980s',title:'Black cultural life photographs',type:'摄影实践',facts:['持续拍摄纽约黑人文化与音乐场景。','Whitney收藏包括Sun Ra等作品。'],reading:'模糊、运动和暗部不是技术缺陷，而成为身体经验和城市节奏的视觉语言。'}],images:[],sourceLabel:'Whitney Museum · Ming Smith',sourceUrl:'https://whitney.org/artists/17819'},
{id:'shigeko-kubota',name:'Shigeko Kubota',born:'1937–2015',base:'Japan / United States',intro:'日本战后前卫与Fluxus的重要参与者，随后成为录像艺术先驱，将显示器、雕塑结构、身体行动和录像图像结合。',methods:['录像雕塑','Fluxus行动','表演','媒介混合'],subjects:['身体','技术','记忆','艺术史','媒介'],outputs:['录像','雕塑','表演','装置'],institutions:['MoMA'],achievements:['Vagina Painting','Duchampiana: Nude Descending a Staircase','Shigeko Kubota: Liquid Reality'],whyImportant:'Kubota把录像从屏幕播放转化为空间化雕塑媒介，同时连接日本前卫、Fluxus与早期录像艺术史。',projects:[{year:'1976',title:'Duchampiana: Nude Descending a Staircase',type:'录像雕塑',facts:['将录像显示器嵌入阶梯式雕塑结构。','作品重新处理杜尚的艺术史图像。'],reading:'电子图像与实体结构结合，使录像成为可被身体绕行和观看的空间对象。'}],images:[],sourceLabel:'MoMA · Shigeko Kubota',sourceUrl:'https://www.moma.org/artists/3277-shigeko-kubota'},
{id:'nalini-malani',name:'Nalini Malani',born:'1946',base:'India',intro:'印度当代艺术先驱，以绘画、反向绘画、影子剧场、录像与大型装置处理分治记忆、宗教暴力、女性主义和神话的重新书写。',methods:['录像装置','影子剧场','反向绘画','神话重写'],subjects:['印度分治','宗教暴力','女性主义','神话','记忆'],outputs:['绘画','录像','装置','艺术家书'],institutions:['Centre Pompidou'],achievements:['Unity in Diversity','Hieroglyphs, Lohar Chawl'],whyImportant:'Malani把南亚政治历史、女性主义和跨媒介实验连接起来，是印度录像与装置艺术发展中的关键人物。',projects:[{year:'2003',title:'Unity in Diversity',type:'混合媒介录像装置',facts:['作品回应2002年古吉拉特邦针对穆斯林少数群体的暴力。','结合录像、历史照片、家具和灯具。'],reading:'国家统一的视觉修辞与现实中的宗教暴力被置于同一家庭式空间中发生冲突。'}],images:[],sourceLabel:'Centre Pompidou · Nalini Malani',sourceUrl:'https://www.centrepompidou.fr/en/ressources/oeuvre/c4ELngX'},
{id:'coco-fusco',name:'Coco Fusco',born:'1960',base:'United States',intro:'古巴裔美国跨学科艺术家、作家与策展人，通过表演、录像、摄影和批评写作研究种族、性别、权力、殖民展示机制与政治暴力。',methods:['表演','录像','制度批评','批评写作'],subjects:['种族','性别','殖民主义','权力','政治暴力'],outputs:['表演','录像','摄影','装置','写作'],institutions:['Whitney Museum'],achievements:['Whitney Biennial 2008','Whitney Biennial 2022','Your Eyes Will Be an Empty Word'],whyImportant:'Fusco把表演艺术与殖民观看史、种族化身体和当代政治制度连接，是身份政治与制度批评的重要跨学科实践者。',projects:[{year:'2021',title:'Your Eyes Will Be an Empty Word',type:'录像作品',facts:['作品被Whitney收藏。','进入Whitney Biennial 2022相关机构网络。'],reading:'作品延续艺术家对死亡、政治历史和观看制度的长期研究。'}],images:[],sourceLabel:'Whitney Museum · Coco Fusco',sourceUrl:'https://whitney.org/artists/10369'},
...artistBatch90
];
