import type { Artist } from './data';

const project = (year:string,title:string,type:string,facts:string[],reading:string)=>({year,title,type,facts,reading});

export const artistBatch38: Artist[] = [
 {id:'andreas-gursky',name:'Andreas Gursky',born:'1955',base:'Düsseldorf',intro:'以大尺幅、高视点与数字处理拍摄全球化社会的建筑、消费、劳动与群体空间。',methods:['大画幅摄影','高视点','数字合成','类型学观察'],subjects:['全球化','消费','建筑','群体','资本','基础设施'],outputs:['摄影','大型彩色照片'],institutions:['MoMA','Tate','Centre Pompidou'],achievements:['MoMA 美国首次回顾展 2001'],whyImportant:'他把杜塞尔多夫学派的冷静观察推进到全球资本与信息时代，以极高密度的大尺幅图像重构摄影的空间尺度。',projects:[project('1999','Rhine II','大型彩色摄影',['莱茵河景观被数字处理为高度简化的水平结构。','将纪实摄影与数字重构结合。'],'重要之处在于摄影不再被限定为忠实记录，而可以通过数字删减构造一种更强的现实模型。')],images:[],sourceLabel:'MoMA',sourceUrl:'https://www.moma.org/artists/7806-andreas-gursky'},
 {id:'candida-hofer',name:'Candida Höfer',born:'1944',base:'Cologne',intro:'长期以严格、正面的建筑摄影研究图书馆、博物馆、剧院等公共文化空间。',methods:['建筑摄影','类型学','大画幅摄影','系列研究'],subjects:['公共空间','制度','建筑','知识','文化机构'],outputs:['摄影','大型彩色照片'],institutions:['Documenta','Venice Biennale','Centre Pompidou'],achievements:['German Pavilion · Venice Biennale 2003'],whyImportant:'她把通常作为背景的文化机构空间本身变成主体，延续并改变了 Becher 学派的类型学方法。',projects:[project('1980s–ongoing','Libraries / Public Interiors','建筑类型学摄影',['长期拍摄图书馆、博物馆、歌剧院与历史室内空间。','通常避免人物成为画面主体。'],'通过重复观看不同制度空间，建筑如何组织知识、权威和公共行为变得可见。')],images:[],sourceLabel:'艺术家官网',sourceUrl:'https://www.candida-hofer.com/'},
 {id:'walid-raad',name:'Walid Raad',born:'1967',base:'New York / Beirut',intro:'通过摄影、录像、文本、表演和虚构档案研究黎巴嫩战争、记忆以及艺术史如何被建构。',methods:['虚构档案','研究型艺术','摄影','表演讲座','文本'],subjects:['战争','黎巴嫩','记忆','档案','艺术制度','历史书写'],outputs:['摄影','录像','装置','表演'],institutions:['MoMA','Documenta','Venice Biennale'],achievements:['MoMA comprehensive survey 2015–2016'],whyImportant:'他让档案本身变得不可靠，通过事实与虚构的交叉迫使观众重新判断历史证据是如何被制造和相信的。',projects:[project('1989–2004','The Atlas Group','虚构档案 / 摄影 / 录像',['以一个虚构研究机构的形式生产与整理黎巴嫩战争相关文件。','材料混合历史事实、摄影、录像与虚构叙述。'],'项目的核心不是揭露一个真相，而是研究战争历史为何总要通过有缺陷的媒介与叙事才能被理解。')],images:[],sourceLabel:'MoMA',sourceUrl:'https://www.moma.org/artists/35285-walid-raad'},
 {id:'wangechi-mutu',name:'Wangechi Mutu',born:'1972',base:'Nairobi / New York',intro:'以拼贴、雕塑、影像与表演重构黑人女性身体，并连接非洲离散、生态、神话与未来主义。',methods:['拼贴','图像挪用','混合媒介','雕塑','影像'],subjects:['黑人女性','身体','非洲离散','性别','殖民','生态','未来主义'],outputs:['拼贴','雕塑','录像','装置','表演'],institutions:['MoMA','New Museum','Venice Biennale'],achievements:['Metropolitan Museum façade commission 2019'],whyImportant:'她通过拆解时尚、色情、民族志等既有图像重新制造身体，使拼贴成为反击种族和性别视觉范式的方法。',projects:[project('2003','Yo Mama','拼贴 / 女性主义',['以 Funmilayo Anikulapo-Kuti 为原型重构女性英雄形象。','使用印刷图像、绘画和拼贴形成混合身体。'],'身体不是固定身份，而成为可以拆解并重新组装文化刻板印象的战场。')],images:[],sourceLabel:'MoMA',sourceUrl:'https://www.moma.org/collection/artists/28097'},
 {id:'rirkrit-tiravanija',name:'Rirkrit Tiravanija',born:'1961',base:'New York / Bangkok / Berlin',intro:'以做饭、共享空间、建筑和共同活动把艺术作品转化为人与人发生关系的社会场域。',methods:['参与式艺术','关系美学','社会实践','建筑介入','共同活动'],subjects:['社群','参与','日常生活','公共空间','交换'],outputs:['装置','社会项目','表演','建筑'],institutions:['Guggenheim','MoMA','Venice Biennale','Secession'],achievements:['Hugo Boss Prize finalist 2004','Utopia Station · Venice Biennale 2003 co-curator'],whyImportant:'他是关系美学最具代表性的艺术家之一，把作品从可观看的物件转向由参与者共同完成的社会情境。',projects:[project('2002','Untitled 2002 (he promised)','参与式装置',['依据 Schindler House 建造开放结构。','空间容纳烧烤、按摩、DJ、电影与讨论等公共活动。'],'艺术家提供条件而不规定结果，作品真正的材料是参与者之间发生的关系。')],images:[],sourceLabel:'Guggenheim',sourceUrl:'https://www.guggenheim.org/exhibition/rirkrit-tiravanija-untitled-2002-he-promised'},
 {id:'willem-de-rooij',name:'Willem de Rooij',born:'1969',base:'Berlin',intro:'以摄影、电影、纺织、现成物与展览编排研究图像政治、殖民史和观看制度。',methods:['展览编排','图像研究','摄影','电影','挪用'],subjects:['殖民','图像政治','观看制度','身份','历史'],outputs:['摄影','电影','装置','纺织作品'],institutions:['Stedelijk Museum','Venice Biennale','KW Institute'],achievements:['Dutch Pavilion · Venice Biennale 2005 (with Jeroen de Rijke)'],whyImportant:'他的实践把策展、展示和图像选择本身转化为艺术方法，使作品之间的关系与展示制度成为内容。',projects:[project('2010','Intolerance','展览 / 图像研究',['将自身作品与历史材料置于同一展示结构。','研究图像分类、文化归属与殖民历史。'],'展示不是中性的容器，而是生产意义与权力关系的机制。')],images:[],sourceLabel:'艺术家官网',sourceUrl:'https://www.willemderooij.com/'},
 {id:'hassan-hajjaj',name:'Hassan Hajjaj',born:'1961',base:'London / Marrakech',intro:'将街头肖像、时尚、摩洛哥视觉文化和消费包装组合成高密度摄影与装置。',methods:['编排肖像','时尚摄影','图像拼贴','装置','流行文化挪用'],subjects:['摩洛哥','离散身份','时尚','青年文化','消费','街头文化'],outputs:['摄影','录像','装置','设计'],institutions:['Victoria and Albert Museum','Maison Européenne de la Photographie'],achievements:['长期进入国际摄影与当代艺术机构收藏和展览网络'],whyImportant:'他拒绝把北非视觉文化固定成民族志对象，以时尚、品牌包装和街头姿态制造主动、混杂的当代身份。',projects:[project('2000s–ongoing','Kesh Angels','编排肖像',['拍摄穿着鲜艳服饰的马拉喀什女性摩托车骑手。','以消费品包装构成作品边框。'],'作品把时尚摄影的控制力交还给被拍摄者的姿态与地方流行文化。')],images:[],sourceLabel:'艺术家官网',sourceUrl:'https://www.hassanhajjaj.com/'},
 {id:'viviane-sassen',name:'Viviane Sassen',born:'1972',base:'Amsterdam',intro:'在艺术与时尚摄影之间工作，以强烈阴影、身体切割、色彩与抽象空间重新组织人物和环境。',methods:['编排摄影','身体抽象','色彩实验','阴影','时尚摄影'],subjects:['身体','身份','非洲经验','欲望','抽象','记忆'],outputs:['摄影','摄影书','装置'],institutions:['Foam','MoMA','Maison Européenne de la Photographie'],achievements:['Prix de Rome 2007'],whyImportant:'她模糊时尚摄影与自主艺术摄影之间的界线，使身体通过阴影、遮挡和几何关系从肖像身份中脱离出来。',projects:[project('2007–2011','Flamboya','摄影系列 / 摄影书',['在东非多个地点拍摄人物、身体与环境。','通过强烈阴影和构图把人物转成近似抽象形状。'],'系列同时涉及艺术家童年记忆、非洲观看经验以及摄影中身体如何被形式化。')],images:[],sourceLabel:'艺术家官网',sourceUrl:'https://www.vivianesassen.com/'}
];
