import type { Artist } from './data';
import { artistBatch87 } from './expansionBatch87';

export const artistBatch86: Artist[] = [
  {id:'carrie-mae-weems',name:'Carrie Mae Weems',born:'1953',base:'United States',intro:'以摄影、文本、录像、表演与装置持续研究黑人历史、女性主体、家庭关系、观看权力与档案政治，并经常让自己的身体成为历史的见证者。',methods:['编排摄影','档案挪用','文本与图像','自我表演'],subjects:['黑人历史','女性主体','家庭','种族表征','观看权力'],outputs:['摄影','文本','录像','表演','装置'],institutions:['MoMA'],achievements:['Kitchen Table Series','From Here I Saw What Happened and I Cried'],whyImportant:'Weems把私人家庭空间、黑人女性主体与摄影史中的种族化观看连接起来，是当代摄影中重新讨论谁观看、谁被观看以及谁有权书写历史的关键人物。',projects:[{year:'1990',title:'Kitchen Table Series',type:'摄影与文本系列',facts:['由20幅银盐照片和14块丝网印刷文本面板构成。','艺术家本人在固定厨房桌场景中扮演核心人物。'],reading:'同一家庭空间通过人物、姿态和关系变化成为讨论性别、亲密关系与黑人女性主体性的舞台。'},{year:'1995–96',title:'From Here I Saw What Happened and I Cried',type:'档案摄影再构',facts:['重新使用19世纪及其他来源的非裔美国人历史照片。','通过裁切、着色与玻璃文字重新框定档案。'],reading:'作品直接追问摄影、科学分类与种族权力如何共同塑造黑人身体的历史图像。'}],images:[],sourceLabel:'MoMA · Carrie Mae Weems',sourceUrl:'https://www.moma.org/artists/7177-carrie-mae-weems'},
  {id:'wolfgang-tillmans',name:'Wolfgang Tillmans',born:'1968',base:'Germany / United Kingdom',intro:'跨越肖像、夜生活、静物、政治图像、抽象无相机摄影与展览安装，把摄影理解为可在杂志、墙面、印刷物和公共空间之间不断迁移的图像系统。',methods:['非等级图像编排','展墙安装','暗房实验','无相机摄影'],subjects:['亲密关系','酷儿文化','夜生活','政治','真相与媒体'],outputs:['摄影','摄影装置','印刷品','声音','录像'],institutions:['MoMA','Tate'],achievements:['Truth Study Center','Wolfgang Tillmans: To look without fear'],whyImportant:'Tillmans打破纪实、时尚、私人快照与抽象摄影之间的等级，同时把照片尺寸、纸张、墙面距离和传播渠道本身变成作品，是1990年代以来摄影展示方式转型的核心人物。',projects:[{year:'1990s–',title:'Installation / wall works',type:'摄影装置',facts:['将不同尺寸、装裱方式和来源的照片直接组合于展墙。','MoMA收藏并展出其跨越1980年代以来的大量作品。'],reading:'照片不再只是单张图像，而通过彼此邻接形成不断变化的视觉关系网络。'},{year:'2005–',title:'Truth Study Center',type:'桌面装置 / 图像研究',facts:['组合新闻文章、照片与其他印刷材料。','围绕政治、意识形态与争议性真相展开。'],reading:'把摄影从视觉记录推进到关于知识、媒体和公共真相如何形成的研究。'}],images:[],sourceLabel:'MoMA · Wolfgang Tillmans',sourceUrl:'https://www.moma.org/artists/8044-wolfgang-tillmans'},
  {id:'yinka-shonibare',name:'Yinka Shonibare',born:'1962',base:'United Kingdom / Nigeria',intro:'以雕塑、摄影、电影、绘画和装置研究殖民主义、帝国历史、阶级与混合身份，标志性的荷兰蜡染布被用于揭示所谓民族文化本身的跨国贸易历史。',methods:['历史重演','文化符号挪用','材料再语境化','后殖民研究'],subjects:['殖民主义','帝国','身份','迁徙','阶级','全球贸易'],outputs:['雕塑','摄影','电影','绘画','装置'],institutions:['Tate'],achievements:['Turner Prize nominee 2004','Nelson’s Ship in a Bottle','The British Library'],whyImportant:'Shonibare通过看似“非洲”的蜡染布揭示文化身份背后的殖民贸易和全球流动，并以无头人体、历史服饰和公共雕塑重新编码英国帝国视觉传统。',projects:[{year:'2010',title:'Nelson’s Ship in a Bottle',type:'公共雕塑',facts:['为伦敦Trafalgar Square Fourth Plinth委任创作。','以HMS Victory为模型并使用标志性蜡染布制作船帆。'],reading:'英国海军英雄纪念体系被跨国纺织材料重新编码，使帝国史与全球贸易同时显现。'},{year:'2014',title:'The British Library',type:'装置',facts:['由数千本包覆彩色蜡染布的书组成。','部分书脊以金字写有第一、二代移民姓名。'],reading:'“英国性”被呈现为由迁徙、殖民历史与文化混合共同建构的开放档案。'}],images:[],sourceLabel:'Tate · Yinka Shonibare',sourceUrl:'https://www.tate.org.uk/art/artists/yinka-shonibare-cbe-2067'},
  {id:'joan-jonas',name:'Joan Jonas',born:'1936',base:'United States',intro:'从1960年代末以来以表演、录像、镜子、绘画、声音和装置探索身体、女性身份、神话、观看与媒介反馈，是录像艺术和跨媒介表演的重要先驱。',methods:['现场表演','录像反馈','身体实验','神话再写'],subjects:['身体','女性身份','神话','观看','自然','记忆'],outputs:['表演','录像','装置','绘画','声音'],institutions:['MoMA'],achievements:['Vertical Roll','Organic Honey’s Visual Telepathy','Joan Jonas: Good Night Good Morning'],whyImportant:'Jonas很早就把摄像机、监视器、镜子与现场身体放入同一反馈系统，奠定了后来表演录像、女性主义影像与多媒体装置的重要语言。',projects:[{year:'1972',title:'Vertical Roll',type:'单通道录像',facts:['利用模拟电视画面垂直滚动的技术故障作为视觉结构。','艺术家的身体动作与屏幕节奏相互作用。'],reading:'媒介故障不再是噪音，而成为身体如何被电子图像切割和重新组织的形式。'},{year:'1972',title:'Organic Honey’s Visual Telepathy',type:'表演 / 录像',facts:['围绕艺术家创造的Organic Honey角色展开。','结合面具、镜子、摄像机与表演。'],reading:'自我观看与角色扮演把女性身份呈现为由镜头、表演和反馈不断生产的结构。'}],images:[],sourceLabel:'MoMA · Joan Jonas',sourceUrl:'https://www.moma.org/artists/2930-joan-jonas'},
  ...artistBatch87
];
