import type { Artist } from './data';
import { artistBatch80 } from './expansionBatch80';

export const artistBatch79: Artist[] = [
  ...artistBatch80,
  {id:'samuel-fosso',name:'Samuel Fosso',born:'1962',base:'Cameroon / Central African Republic / Nigeria / France',intro:'以高度编排的自画像、服装与角色扮演研究身份、泛非政治史和黑人视觉再现。',methods:['自画像','角色扮演','编排摄影','工作室肖像'],subjects:['身份','泛非主义','黑人历史','政治人物','自我再现'],outputs:['摄影','表演性摄影'],institutions:['MoMA'],achievements:['African Spirits','Ideas of Africa: Portraiture and Political Imagination · MoMA 2025–26'],whyImportant:'Fosso把商业照相馆的自我表演发展为政治性的身份摄影，通过亲自化身历史人物重新掌握黑人形象的生产权。',projects:[{year:'2008',title:'African Spirits',type:'编排自画像系列',facts:['Fosso化身非洲及非洲侨民政治、思想与文化人物。','MoMA收藏该系列多件大尺幅银盐照片。'],reading:'作品借重演经典肖像讨论历史图像如何制造政治记忆，同时让艺术家的身体成为跨代际身份媒介。'}],images:[],sourceLabel:'MoMA · Samuel Fosso',sourceUrl:'https://www.moma.org/artists/67095-samuel-fosso'},
  {id:'moyra-davey',name:'Moyra Davey',born:'1958',base:'Canada / United States',intro:'在摄影、电影与写作之间工作，以书籍、家庭生活、文学史和图像流通研究私人经验如何进入公共叙事。',methods:['摄影与写作','邮寄摄影','散文电影','蒙太奇'],subjects:['书籍','家庭','文学','私人生活','图像流通'],outputs:['摄影','电影','写作','装置'],institutions:['MoMA'],achievements:['New Photography 2011 · MoMA','Moyra Davey film retrospective · MoMA 2022'],whyImportant:'Davey把照片作为可折叠、邮寄和留下流通痕迹的物体，并把摄影与散文电影、阅读和自传结合，是当代摄影“图像—文本—物”的关键节点。',projects:[{year:'2011',title:'The Coffee Shop, The Library',type:'摄影装置',facts:['照片被折成信封邮寄，再带着邮戳、胶带和折痕展出。','为MoMA New Photography 2011创作。'],reading:'照片既是图像也是经历运输的物件，公共空间、私人阅读与图像传播因此叠合。'}],images:[],sourceLabel:'MoMA · Moyra Davey',sourceUrl:'https://www.moma.org/artists/39770-moyra-davey'},
  {id:'viviane-sassen',name:'Viviane Sassen',born:'1972',base:'Netherlands',intro:'以强烈色彩、几何阴影、身体切割和超现实编排连接时尚摄影与艺术摄影，并持续处理欧洲与非洲之间复杂的观看关系。',methods:['编排摄影','色彩实验','几何阴影','身体抽象'],subjects:['身体','梦','记忆','非洲','身份'],outputs:['摄影','装置','出版'],institutions:['MoMA'],achievements:['New Photography 2011 · MoMA','Parasomnia'],whyImportant:'Sassen把时尚摄影的形式控制与超现实身体语言引入当代艺术摄影，同时使自身在肯尼亚的童年记忆和作为欧洲观看者的位置成为作品张力。',projects:[{year:'2010',title:'Parasomnia',type:'摄影系列',facts:['作品在多个未具体标明的非洲国家拍摄。','MoMA New Photography 2011展出该系列。'],reading:'人物、阴影与空间被压缩成近乎梦境的形态，地点识别被主动削弱，使记忆与陌生感取代纪实说明。'}],images:[],sourceLabel:'MoMA · Viviane Sassen',sourceUrl:'https://www.moma.org/artists/39781-viviane-sassen'},
  {id:'boris-mikhailov',name:'Boris Mikhailov',born:'1938',base:'Ukraine / Germany',intro:'长期以摄影研究苏联意识形态、后苏联社会转型、贫困、身体与个人在政治结构中的位置。',methods:['社会纪实','编排摄影','序列摄影','观念摄影'],subjects:['苏联','后共产主义','贫困','身体','意识形态'],outputs:['摄影','摄影书','系列装置'],institutions:['MoMA'],achievements:['Case History · MoMA 2011','New Photography 9 · MoMA 1993'],whyImportant:'Mikhailov是前苏联地区最重要的摄影家之一，把私人身体、黑色幽默与社会崩解并置，使政治历史不再只是宏观事件而落实到具体人的脆弱处境。',projects:[{year:'1997–98',title:'Case History',type:'彩色摄影系列',facts:['在乌克兰哈尔科夫拍摄后苏联社会边缘群体。','MoMA于2011年举办该系列在美国博物馆的首次深入展示。'],reading:'作品以极具争议的近距离观看面对贫困、裸体和表演，迫使观看者同时思考社会崩解与摄影伦理。'}],images:[],sourceLabel:'MoMA · Boris Mikhailov',sourceUrl:'https://www.moma.org/artists/8168-boris-mikhailov'},
  {id:'gillian-wearing',name:'Gillian Wearing',born:'1963',base:'United Kingdom',intro:'以摄影、录像、面具、公众参与和自我扮演研究个人身份、公共形象与私人陈述之间的裂缝。',methods:['参与式实践','摄影与文本','角色扮演','面具'],subjects:['身份','公共空间','私人表达','家庭','社会角色'],outputs:['摄影','录像','雕塑','公共艺术'],institutions:['Tate','Turner Prize'],achievements:['Turner Prize 1997','Signs that say what you want them to say and not Signs that say what someone else wants you to say'],whyImportant:'Wearing让普通人在公共空间直接书写私人想法，并不断借面具和角色扮演扰动肖像的真实性，是英国观念摄影和参与式影像的重要节点。',projects:[{year:'1992–93',title:'Signs that say what you want them to say and not Signs that say what someone else wants you to say',type:'参与式摄影系列',facts:['邀请街头陌生人在纸上写下自己想说的话并持牌面对镜头。','作品成为其早期代表性摄影实践。'],reading:'标准街头肖像与手写陈述之间常出现反差，使社会外表与私人心理的距离直接进入照片。'}],images:[],sourceLabel:'Tate · Gillian Wearing',sourceUrl:'https://www.tate.org.uk/art/artists/gillian-wearing-obe-2648'}
];
