import type { Artist, ArtworkImage, Project } from './data';

const image = (url: string, title: string, credit: string, sourceUrl: string, sourceLabel: string): ArtworkImage => ({
  url,
  title,
  credit,
  sourceUrl,
  sourceLabel,
});

const project = (year: string, title: string, type: string, facts: string[], reading: string): Project => ({
  year,
  title,
  type,
  facts,
  reading,
});

export const artistBatch13: Artist[] = [
  {
    id: 'aida-muluneh',
    name: 'Aïda Muluneh',
    chineseName: '阿伊达·穆鲁内',
    born: '1974',
    base: 'Addis Ababa / Côte d’Ivoire',
    intro: '以高度编排的身体、面部彩绘、服装、道具和强烈色块，把非洲女性经验、迁移、记忆与水资源问题压缩进象征性场景。',
    methods: ['编排式摄影', '肖像', '场景建构', '身体绘画', '色彩系统'],
    subjects: ['非洲女性', '迁移', '记忆', '水资源', '身份', '未来'],
    outputs: ['摄影系列', '大型彩色摄影', '公共委托', '展览'],
    institutions: ['Smithsonian National Museum of African Art', 'Somerset House', 'WaterAid'],
    achievements: ['European Union Africa Photography Encounters Prize 2010', 'Water Life — Somerset House 2019'],
    whyImportant: '她适合研究强视觉怎样承担社会议题：颜色、身体涂绘和道具不是装饰，而是一套可反复使用的叙事语法。',
    projects: [
      project('2018', 'Water Life', '委托 / 水资源 / 编排肖像', ['在埃塞俄比亚 Afar 地区拍摄。', '使用身体彩绘、服装、容器和管道等道具。', '以十二幅编排肖像回应女性取水负担。'], '要同时看现场问题和画面规则：项目没有复制新闻摄影，而是把水资源结构转换成可读的颜色与姿势。'),
    ],
    images: [
      image('https://cdn.media.amplience.net/i/canon/canon-pro-aida-muluneh-wateraid-project-8?bg=rgb%28255%2C255%2C255%29&fmt=jpg&fmt.options=interlaced&w=1200', 'Access, Water Life', '© Aïda Muluneh', 'https://www.canon-europe.com/pro/stories/aida-muluneh-wateraid-project/', 'Canon Europe / WaterAid project'),
    ],
    sourceLabel: 'Aïda Muluneh Studio',
    sourceUrl: 'https://aidamuluneh.com/collections/',
  },
  {
    id: 'asako-narahashi',
    name: 'Asako Narahashi',
    chineseName: '楢桥朝子',
    born: '1959',
    base: 'Tokyo',
    intro: '从水中面向陆地拍摄，让熟悉的日本海岸、机场和富士山在浪涌、倾斜地平线与瞬间遮挡中变得不稳定。',
    methods: ['景观摄影', '水中拍摄', '快照', '长期项目', '摄影书'],
    subjects: ['水', '岛屿', '日本景观', '距离', '身体感知', '灾难之后'],
    outputs: ['彩色摄影', '摄影书', '杂志', '展览'],
    institutions: ['SFMOMA', 'Tokyo Photographic Art Museum', 'Images Vevey'],
    achievements: ['Photography Society of Japan Newcomer Award 1998', 'Higashikawa New Photographer Award 2008'],
    whyImportant: '她没有依靠复杂后期制造陌生感，而是改变摄影师身体的位置。站在水里、等待浪把相机推高或遮住镜头，观看方式就被重新组织。',
    projects: [
      project('2001–2008', 'half awake and half asleep in the water', '水中景观 / 身体位置', ['从海水或湖水中朝陆地拍摄。', '让相机贴近水面，保留浪涌造成的偶然遮挡和倾斜。', '把机场、城市与富士山从岸外重新观看。'], '制作方法很具体：先改变身体和相机的位置，再让水的运动参与构图。'),
    ],
    images: [
      image('https://static-assets.artlogic.net/w_1200%2Cc_limit%2Cf_auto%2Cfl_lossy%2Cq_auto/ws-ibashogallery/usr/images/exhibitions/main_image_override/55/045.jpg', 'Mount Fuji from the water', '© Asako Narahashi', 'https://ibashogallery.com/artists/65-asako-narahashi/', 'IBASHO Gallery'),
    ],
    sourceLabel: 'SFMOMA',
    sourceUrl: 'https://www.sfmoma.org/artist/Asako_Narahashi/',
  },
  {
    id: 'kikuji-kawada',
    name: 'Kikuji Kawada',
    chineseName: '川田喜久治',
    born: '1933',
    base: 'Tokyo',
    intro: '把战争遗迹、污迹、国家符号、天象和都市表面编进高反差摄影与复杂摄影书，持续处理战后记忆如何附着于物质表面。',
    methods: ['摄影书', '档案摄影', '类型化摄影', '黑白摄影', '序列编辑'],
    subjects: ['战争记忆', '日本', '国家符号', '时间', '天象', '历史痕迹'],
    outputs: ['摄影书', '黑白摄影', '彩色摄影', '展览'],
    institutions: ['SFMOMA', 'Museum of Fine Arts Boston', 'Tokyo Photographic Art Museum'],
    achievements: ['The Map / Chizu first edition 1965', 'Higashikawa Domestic Photographer Award 2011'],
    whyImportant: '《地图》说明摄影书的意义来自图像、折页、纸张、顺序与尺度的共同工作。单张照片只是材料，书的结构才是作品的完整语法。',
    projects: [
      project('1959–1965', 'Chizu / The Map', '战争遗迹 / 摄影书', ['拍摄广岛原爆圆顶馆的污迹与墙面。', '加入遗物、军人肖像、堡垒、垃圾和国旗等图像。', '与设计师杉浦康平以折页和高密度印刷组织成摄影书。'], '阅读重点是图像如何被书籍结构压迫、遮蔽和反复打开，而不只是把它当作广岛纪实。'),
    ],
    images: [
      image('https://d1hhug17qm51in.cloudfront.net/www-media/2018/08/25113730/2002.65.10_01_b02-Large-TIFF_4000-pixels-long-scaled.jpg', 'Hinomaru — The Japanese National Flag, The Map', '© Kikuji Kawada', 'https://www.sfmoma.org/artwork/2002.65.10/', 'SFMOMA'),
    ],
    sourceLabel: 'Museum of Fine Arts Boston',
    sourceUrl: 'https://www.mfa.org/exhibition/kawada-kikuji-chizu-the-map',
  },
  {
    id: 'yinka-shonibare',
    name: 'Yinka Shonibare',
    born: '1962',
    base: 'London / Lagos',
    intro: '以荷兰蜡染布、无头人体模型、艺术史场景、图书与电影重演殖民史，追问“非洲”“欧洲”和文化真实性是怎样被制造的。',
    methods: ['历史重演', '挪用', '场景建构', '纺织', '装置', '雕塑'],
    subjects: ['殖民', '文化身份', '阶级', '迁移', '全球化', '艺术史'],
    outputs: ['雕塑装置', '摄影', '电影', '图书馆装置', '公共艺术'],
    institutions: ['Tate', 'Venice Biennale', 'Smithsonian National Museum of African Art'],
    achievements: ['Turner Prize 2004 shortlisted', 'Venice Biennale 2007 African Pavilion'],
    whyImportant: '他的关键不只是“使用非洲布”，而是让一种本身横跨印尼、荷兰和西非贸易史的材料进入欧洲经典图像，使所谓文化来源变得无法被简单归类。',
    projects: [
      project('2001', 'The Swing (after Fragonard)', '艺术史重演 / 雕塑装置', ['制作等身无头玻璃钢人体模型。', '依据 Fragonard 的洛可可绘画重新设计姿势和秋千。', '用荷兰蜡染棉布制作服装并加入人工植物。'], '作品通过材料来源、无头身体和经典绘画姿势，让阶级享乐与殖民贸易进入同一空间。'),
    ],
    images: [
      image('https://cdn.kastatic.org/ka-perseus-images/b4d59520442a9b606fcbee9a274b3f8236694679.jpg', 'The Swing (after Fragonard), 2001', '© Yinka Shonibare', 'https://yinkashonibare.com/artwork/the-swing-after-fragonard-2001/', 'Artist website / installation documentation'),
    ],
    sourceLabel: 'Yinka Shonibare Studio',
    sourceUrl: 'https://yinkashonibare.com/',
  },
  {
    id: 'otobong-nkanga',
    name: 'Otobong Nkanga',
    born: '1974',
    base: 'Antwerp',
    intro: '把土地、矿物、身体、贸易与资源开采之间的关系转换成织毯、雕塑、声音、文字和空间装置，持续追踪物质从地层到商品再到身体的路径。',
    methods: ['研究型装置', '织毯', '数字织造', '雕塑', '声音', '文本'],
    subjects: ['土地', '资源开采', '生态', '身体', '贸易', '修复'],
    outputs: ['大型织毯', '装置', '雕塑', '声音作品', '表演'],
    institutions: ['MoMA', 'Tate', 'Centre Pompidou', 'Stedelijk Museum Amsterdam'],
    achievements: ['Otobong Nkanga: Cadence — MoMA 2024–2025'],
    whyImportant: '她把生态问题从“拍受损景观”推进成物质网络：矿物如何被开采、运输、加工、消费，最后又如何回到身体与政治关系里。媒介选择本身就是研究的一部分。',
    projects: [
      project('2024', 'Cadence', '织毯 / 雕塑 / 声音 / 文本环境', ['为 MoMA Marron Family Atrium 制作场域特定装置。', '在 TextielLab 使用数字织造技术制作巨型多联织毯。', '同时使用天然与合成纤维。', '把织毯、雕塑、声音与文本组织成一个包围观众的环境。'], '重点不只是“生态主题”，而是她把不同材料的来源、加工方式和观看尺度连接成一条物质链。'),
    ],
    images: [],
    sourceLabel: 'MoMA',
    sourceUrl: 'https://www.moma.org/calendar/exhibitions/5742',
  },
  {
    id: 'kader-attia',
    name: 'Kader Attia',
    born: '1970',
    base: 'Paris / Berlin',
    intro: '长期围绕“Repair / 修复”研究殖民、战争、现代主义和文化物件：不是把修复理解成恢复原状，而是研究伤口、补丁和缺失如何成为历史证据。',
    methods: ['档案研究', '比较图像', '幻灯投影', '装置', '雕塑', '文本研究'],
    subjects: ['殖民', '修复', '战争创伤', '现代主义', '博物馆', '文化归还'],
    outputs: ['装置', '幻灯投影', '雕塑', '影像', '研究平台'],
    institutions: ['MoMA', 'Venice Biennale', 'documenta', 'Hayward Gallery'],
    achievements: ['Open Your Eyes — MoMA collection', '长期发展“Repair”研究框架'],
    whyImportant: '他非常适合放在“研究型艺术”节点：一件作品常常来自跨博物馆、军事档案和殖民史材料的并置。所谓修复不是美化，而是让伤痕保持可见。',
    projects: [
      project('2010', 'Open Your Eyes', '双幻灯投影 / 修复研究', ['制作两组、共 160 张 35mm 黑白和彩色幻灯片。', '在博物馆库房拍摄被修补的非西方器物。', '从军事档案中调取第一次世界大战面部受伤士兵肖像。', '把器物修补与人体重建并列，并穿插关于现代主义与修复的文字。'], '作品不是说明“两个文化都在修东西”，而是比较西方追求隐藏伤痕的修复逻辑与让补丁保持可见的其他修复传统。'),
    ],
    images: [],
    sourceLabel: 'MoMA',
    sourceUrl: 'https://www.moma.org/collection/works/156765',
  },
  {
    id: 'tania-bruguera',
    name: 'Tania Bruguera',
    born: '1968',
    base: 'Havana / New York',
    intro: '把政治权力、移民、人权和公共行为直接组织成现场情境，强调作品不是“表现政治”，而是让观众在身体层面进入政治关系。',
    methods: ['行为艺术', 'Arte de Conducta', '现场表演', '社会介入', '装置', '制度实验'],
    subjects: ['国家权力', '公民身份', '移民', '人权', '审查', '集体身体'],
    outputs: ['行为', '沉浸式装置', '录像', '社会项目', '教育项目'],
    institutions: ['MoMA', 'Havana Biennial', 'MoMA PS1'],
    achievements: ['Untitled (Havana, 2000) — Havana Biennial 2000 / MoMA collection', 'MoMA solo presentation 2018'],
    whyImportant: '她把观众从“看政治作品的人”变成情境的一部分。气味、黑暗、等待、身体距离和现场表演都承担政治意义，因此非常适合研究规则、空间和参与怎样共同构成作品。',
    projects: [
      project('2000', 'Untitled (Havana, 2000)', '甘蔗渣 / 录像 / 现场表演 / 沉浸装置', ['在哈瓦那 Cabaña Fortress 的黑暗隧道中铺设数英寸厚的甘蔗渣。', '在空间尽头悬挂播放 Fidel Castro 影像的小型黑白显示器。', '安排四名裸体男性在黑暗中持续执行有限动作。', '利用发酵甘蔗的气味、低能见度和不平地面改变观众身体经验。'], '甘蔗既连接加勒比奴隶经济，也把政治权力变成嗅觉和触觉经验；作品的关键是让国家叙事进入身体。'),
    ],
    images: [],
    sourceLabel: 'MoMA',
    sourceUrl: 'https://www.moma.org/collection/works/193143',
  },
  {
    id: 'walid-raad',
    name: 'Walid Raad',
    born: '1967',
    base: 'New York / Beirut',
    intro: '通过摄影、录像、虚构档案、讲演与装置研究黎巴嫩战争记忆、影像证据的可信度，以及历史如何被档案制度和叙事方式制造出来。',
    methods: ['虚构档案', '摄影', '录像', '讲演表演', '文本', '机构批判'],
    subjects: ['战争记忆', '档案', '证据', '历史建构', '中东', '艺术制度'],
    outputs: ['摄影系列', '录像', '装置', '表演讲演', '档案项目'],
    institutions: ['MoMA', 'MoMA PS1'],
    achievements: ['Walid Raad — MoMA survey 2015–2016', 'The Atlas Group 1989–2004'],
    whyImportant: '他不是简单地“伪造历史”，而是利用真假难辨的档案结构逼观众检查自己为什么相信照片、文件和机构标签。对研究档案艺术和 AI 时代的图像可信度尤其重要。',
    projects: [
      project('1989–2004', 'The Atlas Group', '虚构机构 / 战争档案 / 摄影与录像', ['建立名为 The Atlas Group 的档案框架。', '把照片、录像、笔记和叙述组织成带有作者、日期和来源说明的“档案文件”。', '在真实历史、个人记忆和建构叙事之间故意保持不稳定关系。', '通过展览和讲演不断重新解释这些文件。'], '观看重点不是猜“哪一张是真的”，而是观察档案格式如何自动生产可信度，以及战争记忆如何在叙述中被重写。'),
    ],
    images: [],
    sourceLabel: 'MoMA',
    sourceUrl: 'https://www.moma.org/calendar/exhibitions/1493',
  },
  {
    id: 'akram-zaatari',
    name: 'Akram Zaatari',
    born: '1966',
    base: 'Beirut',
    intro: '以摄影档案、家庭影像、录像、口述史和考古式研究处理黎巴嫩影像史，让旧照片既作为历史证据，也作为被不断重新解释和再表演的物件。',
    methods: ['档案研究', '口述史', '录像', '摄影', '旧影像再语境化', '装置'],
    subjects: ['黎巴嫩', '战争', '记忆', '摄影史', '家庭档案', '影像保存'],
    outputs: ['录像装置', '摄影', '档案项目', '电影', '出版物'],
    institutions: ['MoMA', 'Arab Image Foundation', 'Venice Biennale'],
    achievements: ['Projects 100: Akram Zaatari — MoMA 2013', 'Letter to a Refusing Pilot 2013'],
    whyImportant: '他展示了档案不是储存过去的静态仓库，而是可以通过剪辑、口述、重拍、放映装置重新激活。对于你网站里“摄影—档案—历史”这条线非常关键。',
    projects: [
      project('2013', 'Letter to a Refusing Pilot', '录像 / 16mm / 座椅 / 同步灯光装置', ['制作 34 分钟彩色有声录像。', '加入 1982 年材料改制的 16mm 黑白无声短片。', '在展场配置电影院座椅与八个圆形座位。', '以同步灯光设计控制观看节奏。', '把个人记忆、战争传闻和影像证据组织成一封跨时间的“信”。'], '项目把一个战争故事拆成不同媒介和观看位置，使“记得什么、谁来证明、图像能否作证”成为作品本身。'),
    ],
    images: [],
    sourceLabel: 'MoMA',
    sourceUrl: 'https://www.moma.org/collection/works/284440',
  },
  {
    id: 'mishka-henner',
    name: 'Mishka Henner',
    born: '1976',
    base: 'Manchester',
    intro: '从 Google Earth、Street View、数据库和公开网络图像中取材，以搜索、截图、拼接和再打印揭示工业、军事与平台影像怎样塑造我们对世界的可见性。',
    methods: ['网络挪用', '卫星图像', 'Google Earth', '截图拼接', '数据库研究', '再打印'],
    subjects: ['平台视觉', '工业农业', '能源', '监控', '审查', '图像基础设施'],
    outputs: ['大幅摄影', '摄影书', '装置', '网络项目'],
    institutions: ['MoMA', 'The Metropolitan Museum of Art', 'National Gallery of Art'],
    achievements: ['Ocean of Images: New Photography 2015 — MoMA', 'Feedlots 2012–2013'],
    whyImportant: '他把“摄影师必须站在现场”这一点彻底拆开：拍摄动作可能已经由卫星和平台完成，艺术家的工作变成寻找、理解、拼接和重新定义这些机器图像。',
    projects: [
      project('2012–2013', 'Feedlots', '卫星图像 / 工业农业 / 大幅拼接', ['从 Google Earth 等公开卫星影像中寻找美国大型 cattle feedlots。', '研究围栏、排污沟、粪尿潟湖与工业养殖结构。', '从高分辨率卫星界面截取数百张局部图像。', '把大量截图拼接成高细节的大幅图像并输出。'], '关键动作不是“航拍”，而是从机器已经生成的全球图像里识别工业系统，再通过拼接和尺度让不可见的结构变得可读。'),
    ],
    images: [],
    sourceLabel: 'Mishka Henner Studio',
    sourceUrl: 'https://mishkahenner.com/feedlots',
  },
  {
    id: 'santu-mofokeng',
    name: 'Santu Mofokeng',
    born: '1956–2020',
    base: 'Johannesburg',
    intro: '从南非城镇生活、通勤、精神信仰与风景出发，把纪实摄影从单一“反种族隔离斗争图像”扩展到日常经验、历史幽灵和不可见精神世界。',
    methods: ['摄影散文', '黑白摄影', '长期观察', '景观摄影', '档案重访'],
    subjects: ['南非', '通勤', '精神性', '城镇生活', '土地', '种族隔离历史'],
    outputs: ['黑白摄影', '摄影散文', '摄影书', '展览'],
    institutions: ['MoMA', 'SFMOMA', 'Foam', 'Jeu de Paume', 'Venice Biennale'],
    achievements: ['Chasing Shadows retrospective — Jeu de Paume 2011', 'German Pavilion — Venice Biennale 2013'],
    whyImportant: 'Mofokeng 重要的一点是拒绝让黑人生活只在“冲突新闻”里出现。他把通勤中的祈祷、风景中的历史痕迹和精神经验都当成同等重要的现实。',
    projects: [
      project('1986', 'Train Church', '通勤 / 精神性 / 摄影散文', ['在 Johannesburg–Soweto 通勤列车上拍摄临时形成的教会仪式。', '记录唱歌、拍手、按手祈祷、身体摆动和拥挤车厢。', '把危险而压迫的通勤空间与共同体的精神仪式放在同一序列。'], '它不是把宗教当奇观，而是显示同一节车厢如何同时承担劳动迁移、恐惧、日常生活和精神共同体。'),
    ],
    images: [],
    sourceLabel: 'Santu Mofokeng Foundation',
    sourceUrl: 'https://santumofokengfoundation.com/santu-mofokeng-photography-train-church',
  },
  {
    id: 'hoda-afshar',
    name: 'Hoda Afshar',
    born: '1983',
    base: 'Melbourne',
    intro: '在纪实、摆拍与协作之间工作，持续追问摄影如何再现被边缘化的人，以及摄影机自身怎样与国家权力、边境制度和观看等级发生关系。',
    methods: ['协作式摄影', '摆拍纪实', '录像', '肖像', '声音', '文本'],
    subjects: ['移民', '边境', '拘留制度', '身份', '国家权力', '再现伦理'],
    outputs: ['摄影系列', '双屏录像', '声音', '摄影书', '展览'],
    institutions: ['MoMA', 'National Gallery of Victoria', 'Art Gallery of South Australia', 'KADIST'],
    achievements: ['Remain 2018 — MoMA / Australian institutional collections', 'Hoda Afshar: Remain — UQ Art Museum 2019–2020'],
    whyImportant: '她没有把被拘留者继续当作新闻摄影中的“对象”，而是让参与者用摆拍、语言、诗歌和声音参与自我叙述。对研究摄影伦理和协作式纪录非常重要。',
    projects: [
      project('2018', 'Remain', 'Manus Island / 协作影像 / 双屏录像与肖像', ['前往 Papua New Guinea 的 Manus Island。', '与在拘留中心关闭后仍滞留岛上的无国籍男性协作。', '让参与者通过摆拍图像、文字、诗歌、歌声和口述讲述个人与共同经历。', '制作双通道彩色有声录像，并同时形成肖像摄影。', '把热带景观的视觉美感与暴力、等待和失去自由的叙述并置。'], '关键不是替他们“发声”，而是改变纪录片的权力结构：被拍摄者参与决定怎样讲述自己的处境。'),
    ],
    images: [],
    sourceLabel: 'UQ Art Museum',
    sourceUrl: 'https://art-museum.uq.edu.au/hoda-afshar-remain',
  },
  {
    id: 'jo-ractliffe',
    name: 'Jo Ractliffe',
    born: '1961',
    base: 'Cape Town',
    intro: '通过战争结束后的空地、道路、市场、边境和军事遗迹追踪南部非洲冲突的后果，强调历史往往通过看似普通的地貌和基础设施继续存在。',
    methods: ['景观摄影', '长期田野', '黑白摄影', '战后地景研究', '摄影书'],
    subjects: ['安哥拉', '南非', '战争余波', '土地占领', '基础设施', '记忆'],
    outputs: ['摄影系列', '摄影书', '展览'],
    institutions: ['MoMA', 'The Metropolitan Museum of Art'],
    achievements: ['The Aftermath of Conflict — The Met 2015', 'Terreno Ocupado 2007–2008'],
    whyImportant: '她把战争摄影从爆炸和士兵移到“战争之后还剩什么”：空地、废墟、市场和道路变成历史证据。适合放进你网站里的景观—政治—记忆线。',
    projects: [
      project('2007–2008', 'Terreno Ocupado', 'Luanda / 战后地景 / 土地占领', ['在安哥拉内战结束约五年后进入 Luanda 拍摄。', '记录棚户区、空地、道路摊位、市场和城市边缘。', '把殖民、独立战争、内战与战后全球贸易留下的痕迹放在同一城市表面中。', '以银盐照片和后续展览打印组织系列。'], '她不把“废墟”当视觉风格，而是追踪土地如何被占领、遗弃、再次开发，历史怎样继续写在城市结构里。'),
    ],
    images: [],
    sourceLabel: 'The Metropolitan Museum of Art',
    sourceUrl: 'https://www.metmuseum.org/exhibitions/listings/2015/jo-ractliffe',
  },
  {
    id: 'mame-diarra-niang',
    name: 'Mame-Diarra Niang',
    born: '1982',
    base: 'Paris / Dakar',
    intro: '把身体、模糊、失焦、屏幕再摄影和地点经验转成“非肖像”，用她所谓的“territory plasticity / 领土的可塑性”研究自我如何在记忆与遗忘中不断重组。',
    methods: ['非肖像', '抽象摄影', '屏幕再摄影', '失焦', '色彩', '摄影书'],
    subjects: ['自我', '黑人身体', '记忆', '遗忘', '领土', '身份流动'],
    outputs: ['摄影系列', '摄影书', '展览', '装置'],
    institutions: ['MoMA', 'Fondation Henri Cartier-Bresson', 'Zeitz MOCAA', 'The Walther Collection'],
    achievements: ['Remember to Forget — Fondation Henri Cartier-Bresson 2024', 'Sama Guent Guii — MoMA collection'],
    whyImportant: '她有意拒绝清晰、可识别、可消费的人像，把模糊和抽象当成对身份固定化的抵抗。对于“摄影如何不再负责证明一个人是谁”这条线非常重要。',
    projects: [
      project('2021', 'Sama Guent Guii', '非肖像 / 抽象身体 / 记忆与遗忘', ['制作被她称为“non-portraits / 非肖像”的人体图像。', '让人物轮廓在颜色、模糊和抽象处理中聚散。', '避免把黑人身体重新固定为清晰可识别的类型。', '把系列放进关于记忆、擦除和自我变化的长期研究。'], '作品不是“故意拍糊”这么简单；模糊承担的是方法论功能：让身份从被识别的对象转成持续变化的领土。'),
    ],
    images: [],
    sourceLabel: 'Mame-Diarra Niang Studio',
    sourceUrl: 'https://www.mamediarraniang.com/about',
  },
];
