import type { Artist } from './data';
import { artistBatch101 } from './expansionBatch101';

export const artistBatch100: Artist[] = [
{id:'rineke-dijkstra',name:'Rineke Dijkstra',born:'1959',base:'Netherlands',intro:'荷兰摄影与录像艺术家，以正面、克制的肖像和跨时间重复拍摄研究青春期、迁徙、身份转变以及个体面对镜头时的自我呈现。',methods:['长期肖像','类型学式拍摄','重复拍摄','正面肖像'],subjects:['青春期','身份转变','迁徙','身体','成长'],outputs:['摄影','录像'],institutions:['MoMA'],achievements:['Beach Portraits','Almerisa','New Photography 13'],whyImportant:'Dijkstra把传统正面肖像转化为研究身份变化和时间性的工具，尤其通过同一对象的长期重复拍摄让社会身份与身体变化进入摄影结构。',projects:[{year:'1994–',title:'Almerisa',type:'长期肖像系列',facts:['MoMA收藏多件Almerisa肖像，最早记录包括1994年莱顿庇护中心。','作品在不同年份持续拍摄同一人物。'],reading:'固定而克制的肖像结构使时间、迁徙与成长本身成为作品的核心变量。'}],images:[],sourceLabel:'MoMA · Rineke Dijkstra',sourceUrl:'https://www.moma.org/artists/8139-rineke-dijkstra'},
{id:'deana-lawson',name:'Deana Lawson',born:'1979',base:'United States',intro:'美国摄影艺术家，以高度编排又保持家庭空间亲密感的肖像研究黑人生活、家庭、性、灵性与自我表征。',methods:['编排肖像','环境肖像','亲密空间建构','黑人视觉研究'],subjects:['黑人家庭','亲密关系','灵性','性','黑人美学'],outputs:['摄影','装置'],institutions:['Whitney Museum','Guggenheim'],achievements:['The Garden, Gemena, DR Congo','Sons of Cush','Whitney Biennial 2017'],whyImportant:'Lawson把家庭内部空间、身体姿态与精密场景控制结合起来，使黑人肖像同时具有私人亲密性、仪式感和历史性。',projects:[{year:'2015',title:'The Garden, Gemena, DR Congo',type:'摄影',facts:['Whitney收藏该作。','Whitney将Lawson的实践概括为围绕亲密、家庭、灵性、性与黑人美学展开。'],reading:'作品体现她如何让具体人物和家庭空间进入更广阔的黑人视觉文化与亲密关系研究。'}],images:[],sourceLabel:'Whitney · Deana Lawson',sourceUrl:'https://whitney.org/artists/17261'},
{id:'an-my-le',name:'An-My Lê',born:'1960',base:'Vietnam / United States',intro:'越南出生的美国摄影艺术家，以大画幅风景摄影研究战争、军事训练、历史记忆、流亡经验与景观之间的复杂关系。',methods:['大画幅摄影','景观研究','军事空间观察','历史与当下并置'],subjects:['战争','景观','流亡','美国军事','历史记忆'],outputs:['摄影'],institutions:['MoMA','MoMA PS1'],achievements:['29 Palms','Small Wars','Silent General','Between Two Rivers'],whyImportant:'Lê没有把战争仅处理为新闻事件，而是把景观作为历史、军事表演和帝国政治发生的舞台，使战争摄影转向对空间与表征机制的长期研究。',projects:[{year:'2003–04',title:'29 Palms',type:'摄影系列',facts:['系列拍摄加州Twentynine Palms军事训练场准备部署至阿富汗和伊拉克的部队。','MoMA收藏29 Palms: Infantry Platoon (Machine Gunners)与Mortar Impact等作品。'],reading:'训练场既是真实军事空间也是对未来战争的预演，景观因此成为战争表演性与美国军事权力的观察界面。'}],images:[],sourceLabel:'MoMA · An-My Lê',sourceUrl:'https://www.moma.org/artists/7901-an-my-le'},
{id:'catherine-opie',name:'Catherine Opie',born:'1961',base:'United States',intro:'美国摄影艺术家，以肖像、社群记录和风景摄影持续研究酷儿身份、身体、家庭、归属与美国社会景观。',methods:['社群肖像','身份表演','环境摄影','摄影史引用'],subjects:['酷儿社群','性别','身体','家庭','归属'],outputs:['摄影'],institutions:['MoMA','MoMA PS1'],achievements:['Being and Having','Dyke','Mike and Sky'],whyImportant:'Opie把酷儿社群内部的亲密关系与传统肖像史连接，使摄影成为建立社群历史、可见性和自我表征的重要机制。',projects:[{year:'1991',title:'Being and Having',type:'肖像摄影系列',facts:['系列由13幅肖像组成，被摄者来自艺术家的女同性恋与酷儿社群。','人物以假胡须表演男性气质，MoMA收藏该系列。'],reading:'作品把性别理解为可表演和可重新编码的视觉结构，同时把朋友与社群写入正式肖像史。'}],images:[],sourceLabel:'MoMA · Catherine Opie',sourceUrl:'https://www.moma.org/artists/8190-catherine-opie'},
{id:'lyle-ashton-harris',name:'Lyle Ashton Harris',born:'1965',base:'United States',intro:'美国艺术家，以摄影、自画像、表演、档案和拼贴研究黑人身份、酷儿经验、性别表演、欲望与文化记忆。',methods:['自我表演','摄影肖像','档案拼贴','身份建构'],subjects:['黑人身份','酷儿经验','性别','欲望','文化记忆'],outputs:['摄影','拼贴','版画','装置'],institutions:['MoMA','MoMA PS1'],achievements:['Miss America','The Watering Hole','Ombre à l’Ombre'],whyImportant:'Harris把黑人性、酷儿身份和性别表演放入自画像与档案实践中，连接1990年代身份政治与后来更复杂的个人—公共记忆研究。',projects:[{year:'1996',title:'The Watering Hole',type:'摄影系列',facts:['MoMA收藏The Watering Hole系列多件彩色摄影作品。','该系列进入MoMA摄影收藏与展览网络。'],reading:'系列把身体、欲望和观看关系组织为连续图像，使身份不再是固定标签而成为表演和关系结构。'}],images:[],sourceLabel:'MoMA · Lyle Ashton Harris',sourceUrl:'https://www.moma.org/artists/42969-lyle-ashton-harris'},
{id:'shirana-shahbazi',name:'Shirana Shahbazi',born:'1974',base:'Iran / Germany / Switzerland',intro:'伊朗出生的摄影艺术家，以静物、风景、几何构成和不同复制方式拆解摄影图像的类别、表面与物质性。',methods:['工作室摄影','图像再生产','几何构成','类型混合'],subjects:['摄影表面','图像类别','风景','静物','抽象'],outputs:['摄影','装置'],institutions:['MoMA'],achievements:['New Photography 2012','Composition series','Bird series'],whyImportant:'Shahbazi在具象摄影、抽象构成和展示系统之间不断切换，使摄影不只是记录工具，而成为研究复制、色彩、尺度与图像分类的物质对象。',projects:[{year:'2012',title:'New Photography 2012',type:'展览 / 摄影实践',facts:['Shahbazi参加MoMA New Photography 2012。','MoMA收藏其Bird、Composition、Klausen Pass等不同类型作品。'],reading:'并置风景、静物与抽象构成削弱传统摄影类别边界，使观看者转而关注摄影作为表面、颜色和复制物的状态。'}],images:[],sourceLabel:'MoMA · Shirana Shahbazi',sourceUrl:'https://www.moma.org/artists/28426-shirana-shahbazi'},
...artistBatch101
];