import type { Artist } from './data';
import { artistBatch131 } from './expansionBatch131';

export const artistBatch130: Artist[] = [
...artistBatch131,
{id:'walead-beshty',name:'Walead Beshty',born:'1976',base:'UK / USA',intro:'英国出生、洛杉矶工作的艺术家与写作者，以无相机摄影、暗房程序、运输过程和制度条件研究摄影的物质性、流通与生产。',methods:['无相机摄影','暗房实验','程序性创作','制度研究'],subjects:['摄影物质性','流通','劳动','偶然性','艺术制度'],outputs:['摄影','雕塑','装置','写作'],institutions:['MoMA','MoMA PS1','Guggenheim','Tate','Whitney Museum'],achievements:['New Photography 2009 — MoMA','A World of Its Own — MoMA 2014','Three Color Curl'],whyImportant:'Beshty把摄影从“拍摄对象”转向曝光、化学、运输与展示条件本身，是理解后数码时代摄影物质性和生产系统的重要节点。',projects:[{year:'2008–2009',title:'Color photograms',type:'无相机摄影 / 暗房实验',facts:['MoMA记录其大型彩色photogram在全黑暗房中直接对彩色相纸进行青、品红、黄光多次曝光。','作品以程序与偶然操作讨论化学摄影的媒介性质。'],reading:'图像不是外部世界的再现，而是曝光行为、材料与制作规则留下的直接痕迹。'}],images:[],sourceLabel:'MoMA · Walead Beshty',sourceUrl:'https://www.moma.org/artists/36980-walead-beshty'},
{id:'leslie-hewitt',name:'Leslie Hewitt',born:'1977',base:'USA',intro:'美国艺术家，以摄影、雕塑和装置重新组织家庭照片、书籍、杂志与日常物件，研究黑人历史、个人记忆、档案与摄影对象之间的关系。',methods:['档案重组','静物摄影','挪用','摄影雕塑'],subjects:['黑人历史','家庭记忆','档案','日常物','时间'],outputs:['摄影','雕塑','装置'],institutions:['MoMA'],achievements:['Riffs on Real Time','New Photography 2009 — MoMA'],whyImportant:'Hewitt把家庭档案和印刷文化从“历史证据”转化为可重新编排的物质对象，使摄影、记忆与黑人历史的关系进入空间和形式结构。',projects:[{year:'2002–2005',title:'Riffs on Real Time',type:'摄影 / 档案静物',facts:['MoMA收藏该系列十件作品。','系列通过重新摆放照片、书籍和日常材料形成新的摄影静物关系。'],reading:'档案不再只是过去的储藏室，而成为可以在当下重新排序和解释的物质。'}],images:[],sourceLabel:'MoMA · Leslie Hewitt',sourceUrl:'https://www.moma.org/artists/32621-leslie-hewitt'},
{id:'sara-vanderbeek',name:'Sara VanDerBeek',born:'1976',base:'USA',intro:'美国摄影艺术家，通过工作室构造、档案图像、雕塑与摄影研究女性再现、博物馆收藏、现代主义视觉语言和图像传播。',methods:['工作室构造','档案研究','摄影雕塑','挪用'],subjects:['女性再现','博物馆','现代主义','图像史','收藏制度'],outputs:['摄影','雕塑','装置'],institutions:['MoMA'],achievements:['New Photography 2009 — MoMA','Women & Museums'],whyImportant:'VanDerBeek把摄影史和博物馆收藏机制重新放入工作室构造中，适合作为摄影如何研究自身制度历史的一条关键方法线。',projects:[{year:'2019',title:'Women & Museums',type:'摄影 / 博物馆研究',facts:['MoMA收藏Women & Museums I、II、III、V。','该系列将女性、馆藏对象与摄影再现的问题置于同一结构中。'],reading:'作品让博物馆不再只是展示地点，而成为决定哪些身体和物件如何被观看的生产机制。'}],images:[],sourceLabel:'MoMA · Sara VanDerBeek',sourceUrl:'https://www.moma.org/artists/33981-sara-vanderbeek'},
{id:'kapwani-kiwanga',name:'Kapwani Kiwanga',born:'1978',base:'Canada / France',intro:'加拿大出生、法国工作的跨媒介艺术家，借人类学研究、材料调查、建筑与装置追踪殖民主义、贸易、自然资源和权力系统被隐藏的历史。',methods:['研究型艺术','材料政治','场域特定装置','后殖民研究'],subjects:['殖民主义','贸易','权力','自然资源','价值系统'],outputs:['装置','雕塑','电影','行为'],institutions:['La Biennale di Venezia','National Gallery of Canada','Haus der Kunst'],achievements:['Biennale Arte 2022','Canada Pavilion — Biennale Arte 2024','Trinket'],whyImportant:'Kiwanga把历史研究压缩进沙、植物、玻璃珠等具体材料，使全球贸易与殖民权力通过物质和空间而非说明文本被感知。',projects:[{year:'2024',title:'Trinket',type:'场域特定装置 / 加拿大馆',facts:['Kiwanga代表加拿大参加第60届威尼斯双年展。','装置大量使用源自Murano贸易史的conterie玻璃珠，讨论价值、交换和全球经济关系。'],reading:'微小珠子既是视觉材料也是贸易历史的见证物，材料自身承担了殖民经济史。'}],images:[],sourceLabel:'La Biennale di Venezia · Canada 2024',sourceUrl:'https://www.labiennale.org/en/art/2024/canada'},
{id:'mame-diarra-niang',name:'Mame-Diarra Niang',born:'1982',base:'France / Senegal / South Africa',intro:'法国出生、具有塞内加尔与非洲城市经验的摄影艺术家，以抽象化城市景观、色彩和摄影书研究地点、身体、记忆、失落与归属的不稳定关系。',methods:['主观地景','抽象摄影','摄影书序列','城市漫游'],subjects:['地点','身体','失落','归属','非洲城市','记忆'],outputs:['摄影','摄影书'],institutions:['Aperture','Stevenson'],achievements:['The Citadel: a trilogy','Sahel Gris','Metropolis'],whyImportant:'Niang拒绝把非洲地点固定成社会学说明，以身体感知和抽象城市表面处理地点，使非洲摄影进入更主观、更不稳定的空间经验。',projects:[{year:'2022',title:'The Citadel: a trilogy',type:'摄影书 / 地点研究',facts:['Aperture在2022年专文讨论由MACK出版的The Citadel: a trilogy。','三部曲从Sahel Gris等系列出发，把失落、达喀尔经验与地点感知组织为跨越具体地理的摄影结构。'],reading:'地点并非身份的稳定证明，而是身体不断进入、离开和重新想象的空间。'}],images:[],sourceLabel:'Aperture · Mame-Diarra Niang',sourceUrl:'https://archive.aperture.org/article/2022/3/3/mame-diarra-niang'},
{id:'dinh-q-le',name:'Dinh Q. Lê',born:'1968',base:'Vietnam / USA',intro:'越南出生的跨媒介艺术家，以摄影编织、档案、录像与研究重新处理越南战争的官方叙事、家庭记忆和全球媒体图像。',methods:['档案研究','摄影编织','口述历史','历史重构'],subjects:['越南战争','记忆','国家历史','媒体图像','流亡'],outputs:['摄影','录像','装置','档案'],institutions:['Guggenheim','MoMA'],achievements:['Light and Belief: Voices and Sketches of Life from the Vietnam War','From Vietnam to Hollywood'],whyImportant:'Lê把战争史从西方媒体的经典影像中拆开，并重新引入越南人的私人记忆、战地艺术家与地方档案，是东南亚后殖民记忆艺术的重要节点。',projects:[{year:'2012',title:'Light and Belief: Voices and Sketches of Life from the Vietnam War',type:'档案 / 录像 / 绘画研究',facts:['Guggenheim资料记录该项目汇集近百件越战时期艺术家素描并配合对十二位战争艺术家的纪录访谈。','项目关注战争前线中的日常生活而非单一英雄叙事。'],reading:'历史通过被忽略的素描和个人声音重新出现，抵抗战争图像被少数经典媒体照片垄断。'}],images:[],sourceLabel:'Guggenheim · Dinh Q. Lê',sourceUrl:'https://www.guggenheim.org/articles/author/zoebutt'},
{id:'ho-tzu-nyen',name:'Ho Tzu Nyen',born:'1976',base:'Singapore',intro:'新加坡艺术家、电影作者与写作者，以电影、录像装置、算法系统和历史研究重新编排东南亚历史、神话、殖民知识与国家叙事。',methods:['历史研究','影像装置','数据库叙事','神话重构'],subjects:['东南亚历史','殖民主义','神话','国家叙事','知识生产'],outputs:['电影','录像装置','写作','数字系统'],institutions:['Centre Pompidou','La Biennale di Venezia'],achievements:['The Cloud of Unknowing','Singapore Pavilion — Venice Biennale 2011','The Critical Dictionary of Southeast Asia'],whyImportant:'Ho把东南亚历史视为不断被图像、神话和知识系统重写的网络，其数据库与影像方法连接当代艺术、电影和数字研究。',projects:[{year:'2011',title:'The Cloud of Unknowing',type:'录像装置',facts:['Centre Pompidou记录该作品及Ho代表新加坡参加2011威尼斯双年展的关系。','作品以电影式影像和装置空间处理云、历史与不确定性。'],reading:'历史不是线性说明，而像云一样在图像、典故和观看者之间不断改变形状。'}],images:[],sourceLabel:'Centre Pompidou · Ho Tzu Nyen',sourceUrl:'https://www.centrepompidou.fr/en/program/calendar/event/cdyjBpg'}
];