import type { Artist } from './data';
import { artistBatch102 } from './expansionBatch102';

export const artistBatch101: Artist[] = [
{id:'moyra-davey',name:'Moyra Davey',born:'1958',base:'Canada / United States',intro:'加拿大出生、纽约工作的摄影与影像艺术家，以照片、文字、录像和邮寄系统研究阅读、记忆、日常物件与图像流通。',methods:['摄影与文本','邮寄摄影','网格式编排','散文影像'],subjects:['阅读','记忆','日常物件','图像流通','私人空间'],outputs:['摄影','录像','艺术家书','装置'],institutions:['MoMA'],achievements:['The Coffee Shop, The Library','Triptychs','New Photography 2011'],whyImportant:'Davey把摄影从单张图像扩展到阅读、书写、折叠、邮寄和重新展示的循环，使照片的物质旅程成为作品结构。',projects:[{year:'2011',title:'The Coffee Shop, The Library',type:'摄影 / 邮寄装置',facts:['作品为MoMA New Photography 2011创作。','照片被折成信封邮寄，展示时保留邮票、邮戳与地址等旅行痕迹。'],reading:'图像内容与照片作为物件的流通历史被合并，摄影因此同时成为通信、档案和展示系统。'}],images:[],sourceLabel:'MoMA · Moyra Davey',sourceUrl:'https://www.moma.org/artists/39770-moyra-davey'},
{id:'samuel-fosso',name:'Samuel Fosso',born:'1962',base:'Cameroon / Central African Republic / France',intro:'喀麦隆出生的摄影艺术家，以高度编排的自画像扮演不同社会、政治与历史身份，研究非洲表征、权力、殖民记忆与身份建构。',methods:['自我表演','编排自画像','角色扮演','摄影棚实践'],subjects:['非洲身份','殖民历史','权力','性别表演','刻板印象'],outputs:['摄影'],institutions:['Centre Pompidou'],achievements:['Tati series','Le Chef','African Spirits'],whyImportant:'Fosso把自拍从私人自我呈现转化为集体历史和政治角色的表演场，通过身体主动改写西方摄影史中的非洲刻板形象。',projects:[{year:'1997',title:'Tati',type:'编排自画像系列',facts:['Centre Pompidou收藏Tati系列多件作品，包括Le Chef、La Bourgeoise、Le Marin和La Femme américaine libérée des années 70。','艺术家在系列中扮演多种身份并利用服装、姿态和摄影棚布景重构角色。'],reading:'每一次变装既是个人表演也是对殖民视觉类型、阶级与性别编码的批判。'}],images:[],sourceLabel:'Centre Pompidou · Samuel Fosso',sourceUrl:'https://www.centrepompidou.fr/en/ressources/personne/ccaG66'},
{id:'santu-mofokeng',name:'Santu Mofokeng',born:'1956–2020',base:'South Africa',intro:'南非摄影艺术家，以长期纪实、档案再研究与社会景观摄影讨论种族隔离、黑人日常、宗教、土地和历史记忆。',methods:['长期纪实','档案再研究','社会景观','序列摄影'],subjects:['种族隔离','黑人日常','宗教','土地','历史记忆'],outputs:['摄影','幻灯装置'],institutions:['MoMA'],achievements:['Train Church','The Black Photo Album / Look at Me: 1890–1950'],whyImportant:'Mofokeng把反种族隔离摄影从新闻见证推进到对黑人主体性、私人影像档案和精神生活的复杂研究，是南非摄影史的重要节点。',projects:[{year:'1997',title:'The Black Photo Album / Look at Me: 1890–1950',type:'档案摄影 / 幻灯装置',facts:['MoMA收藏该作，形式为80张35毫米黑白幻灯片的投影。','项目重新组织历史黑人家庭与工作室肖像档案。'],reading:'作品让被殖民历史中黑人主体主动塑造自身形象的私人照片重新进入公共历史。'}],images:[],sourceLabel:'MoMA · Santu Mofokeng',sourceUrl:'https://www.moma.org/artists/72440-santu-mofokeng'},
{id:'ming-smith',name:'Ming Smith',born:'',base:'United States',intro:'美国摄影艺术家，以长曝光、运动模糊、低光和直觉式街头摄影捕捉黑人生活、爵士文化、身体运动以及光影的诗性。',methods:['长曝光','低光摄影','运动模糊','直觉式街头摄影'],subjects:['黑人生活','爵士','城市','身体运动','光影'],outputs:['摄影'],institutions:['MoMA','Whitney Museum'],achievements:['Kamoinge Workshop','Sun Ra, Space II, New York','Working Together'],whyImportant:'Smith将黑人纪实摄影与实验性的光、运动和模糊结合，使社会经验不只作为信息被记录，也成为节奏、能量与感知经验。',projects:[{year:'1978',title:'Sun Ra, Space II, New York',type:'摄影',facts:['Whitney收藏该作。','Smith长期以低光、慢速曝光和身体控制拍摄音乐表演与黑人文化现场。'],reading:'模糊并非技术失误，而成为表现音乐、身体能量和空间流动的方法。'}],images:[],sourceLabel:'MoMA · Ming Smith',sourceUrl:'https://www.moma.org/collection/artists/7906'},
{id:'rosa-barba',name:'Rosa Barba',born:'1972',base:'Italy / Germany',intro:'意大利出生、柏林工作的艺术家，以16mm/35mm电影、投影机雕塑、声音、文本和现场表演研究电影装置、时间、语言与景观。',methods:['扩展电影','投影机雕塑','现场表演','媒介自反'],subjects:['电影机制','时间','语言','景观','技术过时'],outputs:['电影','装置','雕塑','表演'],institutions:['MoMA','MoMA PS1'],achievements:['The Ocean of One’s Pause','White Museum','Aggregate States of Matters'],whyImportant:'Barba把电影从透明的叙事媒介重新变成机械、光线、声音和空间共同工作的物质系统，是当代扩展电影的重要实践者。',projects:[{year:'2010–',title:'White Museum',type:'投影 / 扩展电影系列',facts:['White Museum系列以投影机把空白电影光束投向不同空间与景观。','2016年MoMA PS1呈现White Museum – Live，将70mm投影机与现场打击乐同步。'],reading:'没有传统影像内容的投影让机器、光束、建筑和时间本身成为电影。'}],images:[],sourceLabel:'MoMA · Rosa Barba',sourceUrl:'https://www.moma.org/artists/133225-rosa-barba'},
...artistBatch102
];