import type { Artist } from './data';

export const artistBatch95: Artist[] = [
{id:'pipilotti-rist',name:'Pipilotti Rist',born:'1962',base:'Switzerland',intro:'瑞士录像与装置艺术家，以饱和色彩、身体、流行音乐和沉浸式投影重构观看空间。',methods:['沉浸式影像','身体表演','空间投影','流行文化挪用'],subjects:['身体','性别','欲望','感知','日常'],outputs:['录像','影像装置','声音','公共艺术'],institutions:['MoMA','MoMA PS1','Venice Biennale'],achievements:["I'm Not the Girl Who Misses Much",'Ever Is Over All','Pour Your Body Out (7354 Cubic Meters)'],whyImportant:'Rist把单频道录像扩展为包围身体的感官环境，是女性主义录像、流行视觉语言与沉浸式影像装置之间的关键人物。',projects:[{year:'1986',title:"I'm Not the Girl Who Misses Much",type:'单频道录像',facts:['以加速、减速、色彩失真和音乐处理艺术家自身表演。','作品进入MoMA媒体与行为艺术收藏。'],reading:'早期作品已把身体、自我表演和技术失真结合，预示她后来对沉浸式影像空间的持续探索。'}],images:[],sourceLabel:'MoMA · Pipilotti Rist',sourceUrl:'https://www.moma.org/artists/8297-pipilotti-rist'},
{id:'wangechi-mutu',name:'Wangechi Mutu',born:'1972',base:'Kenya / United States',intro:'肯尼亚裔美国艺术家，以拼贴、雕塑、影像和装置创造女性与动物、植物、机器混合的身体，讨论种族、性别、殖民史、迁徙与非洲未来主义。',methods:['拼贴','混合身体','材料组合','神话重写'],subjects:['黑人女性','后殖民主义','迁徙','身体','非洲未来主义'],outputs:['拼贴','雕塑','录像','装置'],institutions:['MoMA','New Museum','Venice Biennale'],achievements:['Yo Mama','One Hundred Lavish Months of Bushwhack','Histology','MamaRay'],whyImportant:'Mutu通过杂志、民族志、医学与时尚图像的重新组合，拆解西方视觉文化对黑人女性身体的表征，并建立极具影响力的混合生命视觉体系。',projects:[{year:'2003',title:'Yo Mama',type:'大型拼贴',facts:['以印刷纸、绘画和合成材料塑造混合女性身体。','MoMA指出作品向尼日利亚女性主义者Funmilayo Anikulapo-Kuti致意。'],reading:'作品把政治历史、女性主义与幻想身体结合，使拼贴成为重新组织身份和历史图像的工具。'}],images:[],sourceLabel:'MoMA · Wangechi Mutu',sourceUrl:'https://www.moma.org/collection/artists/28097'},
{id:'tacita-dean',name:'Tacita Dean',born:'1965',base:'United Kingdom / Germany / United States',intro:'英国艺术家，以16毫米胶片、黑板画、摄影与版画处理时间、记忆、消失的技术、海洋和历史偶然性。',methods:['模拟胶片','长期观察','档案叙事','黑板绘画'],subjects:['时间','记忆','失落历史','海洋','媒介消逝'],outputs:['16mm电影','绘画','摄影','版画'],institutions:['MoMA','Tate','Royal Academy'],achievements:['The Green Ray','FILM','Banewl','T&I'],whyImportant:'Dean坚持以模拟胶片的物质时间对抗数字影像的即时性，并将事实、传说与偶然事件组织成关于记忆和媒介消逝的诗性研究。',projects:[{year:'1999–2001',title:'The Sun Quartet',type:'16毫米电影系列',facts:['包括Banewl与The Green Ray等作品。','MoMA收藏系列中的多部16毫米电影。'],reading:'她以等待自然现象发生的方式把拍摄本身变成关于时间、偶然和胶片物质性的实践。'}],images:[],sourceLabel:'MoMA · Tacita Dean',sourceUrl:'https://www.moma.org/collection/works/110983'},
{id:'mika-rottenberg',name:'Mika Rottenberg',born:'1976',base:'Argentina / Israel / United States',intro:'阿根廷出生、纽约工作的录像与装置艺术家，以荒诞生产线、女性身体和机械空间研究劳动、商品、全球供应链与资本主义生产机制。',methods:['荒诞叙事','空间装置','身体与机器并置','生产链模拟'],subjects:['劳动','女性身体','商品','资本主义','全球化'],outputs:['录像','装置','雕塑','绘画'],institutions:['Whitney Museum','Venice Biennale'],achievements:['Cheese','NoNoseKnows','Cosmic Generator','Whitney Biennial 2008'],whyImportant:'Rottenberg把身体劳动和商品生产转译成封闭、滑稽又令人不安的影像机器，是讨论全球资本主义、劳动和身体商品化的重要当代艺术家。',projects:[{year:'2008',title:'Whitney Biennial 2008',type:'机构展览节点',facts:['Rottenberg参加2008年Whitney Biennial。','Whitney收藏其录像、绘画及相关作品。'],reading:'她的实践把雕塑空间与影像中的虚构生产系统连接，使观看者仿佛进入资本主义生产链内部。'}],images:[],sourceLabel:'Whitney · Mika Rottenberg',sourceUrl:'https://whitney.org/artists/11241'},
{id:'isaac-julien',name:'Isaac Julien',born:'1960',base:'United Kingdom',intro:'英国电影与装置艺术家，以多屏影像、电影语言和档案研究讨论黑人身份、酷儿经验、迁徙、殖民历史与全球资本。',methods:['多屏电影装置','档案重构','电影化编排','跨时空叙事'],subjects:['黑人身份','酷儿','迁徙','殖民主义','记忆'],outputs:['电影','多屏录像','摄影','装置'],institutions:['Tate','MoMA','Venice Biennale'],achievements:['Looking for Langston','Western Union: Small Boats','Ten Thousand Waves','Lessons of the Hour'],whyImportant:'Julien把电影、摄影与美术馆多屏装置连接起来，以高度编排的视觉语言重构黑人、酷儿与迁徙历史，是当代移动影像的重要节点。',projects:[{year:'1989',title:'Looking for Langston',type:'电影',facts:['以诗性黑白影像回应Langston Hughes与哈莱姆文艺复兴。','作品成为黑人酷儿电影与艺术史的重要参照。'],reading:'作品通过档案、诗歌和编排场景重新想象被主流历史压低的黑人同性欲望与文化记忆。'}],images:[],sourceLabel:'Tate · Isaac Julien',sourceUrl:'https://www.tate.org.uk/art/artists/isaac-julien-1226'}
];
