import type { Artist } from './data';
import { artistBatch76 } from './expansionBatch76';

export const artistBatch75: Artist[] = [
  ...artistBatch76,
  {id:'hito-steyerl',name:'Hito Steyerl',born:'1966',base:'Germany',intro:'以录像、影像装置、写作与理论研究数字图像的流通、监控、战争、资本和网络社会。',methods:['影像论文','研究型录像','媒介批判','理论写作'],subjects:['数字图像','监控','战争','资本','网络社会'],outputs:['录像','影像装置','文本'],institutions:['MoMA','La Biennale di Venezia','documenta'],achievements:['German Pavilion · 56th Venice Biennale 2015','Surrounds: 11 Installations · MoMA 2019'],whyImportant:'Steyerl把影像生产、传播基础设施与政治经济连接起来，是当代数字影像理论和研究型影像艺术的核心人物。',projects:[{year:'2013',title:'How Not to Be Seen: A Fucking Didactic Educational .MOV File',type:'录像',facts:['以教学录像形式讽刺数字时代的可见性与隐身问题。','作品进入MoMA馆藏。'],reading:'把监控、分辨率与图像政治转化为既幽默又尖锐的媒介批判。'}],images:[],sourceLabel:'MoMA · Hito Steyerl',sourceUrl:'https://www.moma.org/artists/43752-hito-steyerl'},
  {id:'carrie-mae-weems',name:'Carrie Mae Weems',born:'1953',base:'United States',intro:'通过摄影、文本、录像、表演与装置研究黑人历史、女性主体、家庭关系以及档案和观看中的权力。',methods:['摄影与文本','自我表演','档案挪用','社会研究'],subjects:['黑人历史','女性主义','家庭','种族','观看权力'],outputs:['摄影','文本','录像','装置','表演'],institutions:['MoMA','Guggenheim'],achievements:['Kitchen Table Series','From Here I Saw What Happened and I Cried · MoMA collection'],whyImportant:'Weems把私人生活、黑人女性主体与摄影档案的制度历史连接起来，是美国当代摄影和身份政治艺术的重要节点。',projects:[{year:'1990',title:'Kitchen Table Series',type:'摄影 / 文本',facts:['由20幅银盐照片与14块丝网文本组成。','艺术家本人作为反复出现的主体。'],reading:'以固定家庭场景讨论性别表演、亲密关系和黑人女性主体性。'}],images:[],sourceLabel:'MoMA · Carrie Mae Weems',sourceUrl:'https://www.moma.org/artists/7177-carrie-mae-weems'},
  {id:'dayanita-singh',name:'Dayanita Singh',born:'1961',base:'India',intro:'以摄影书、档案和可移动“博物馆”重新组织摄影图像，使编辑、排序、展示和出版成为作品本身。',methods:['摄影档案','摄影书','移动博物馆','图像编辑'],subjects:['档案','记忆','家庭','印度社会','摄影制度'],outputs:['摄影','艺术家书','装置'],institutions:['MoMA'],achievements:['Museum of Chance · MoMA collection','Surrounds: 11 Installations · MoMA 2019'],whyImportant:'Singh突破单幅摄影与固定展墙，把摄影理解为可不断重排的档案、书籍和空间系统，是南亚当代摄影的重要人物。',projects:[{year:'2013',title:'Museum of Chance',type:'摄影 / 移动博物馆',facts:['作品来自其长期摄影档案。','MoMA收藏相关作品。'],reading:'通过不断变化的编辑和陈列，让摄影的意义由图像之间的关系持续生成。'}],images:[],sourceLabel:'MoMA · Dayanita Singh',sourceUrl:'https://www.moma.org/artists/48057-dayanita-singh'},
  {id:'thomas-ruff',name:'Thomas Ruff',born:'1958',base:'Germany',intro:'从大型肖像到夜视、天文、互联网图像与数字处理，持续检验摄影的技术条件和图像真实性。',methods:['类型学摄影','图像挪用','数字处理','技术实验'],subjects:['肖像','互联网图像','监控','摄影真实性','技术'],outputs:['摄影','数字图像'],institutions:['MoMA','MoMA PS1'],achievements:['New Order: Art and Technology in the Twenty-First Century · MoMA 2019','MoMA collection'],whyImportant:'Ruff把杜塞尔多夫类型学传统推进到数字图像、网络和机器视觉时代，是摄影媒介自反研究的重要桥梁。',projects:[{year:'1980s–90s',title:'Portraits',type:'摄影',facts:['以正面、均匀光线和大尺幅制作人物肖像。','MoMA收藏其1989年Portrait。'],reading:'主动压低心理叙事，使肖像成为关于摄影表面、身份和观看方式的实验。'}],images:[],sourceLabel:'MoMA · Thomas Ruff',sourceUrl:'https://www.moma.org/artists/6982-thomas-ruff'},
  {id:'wolfgang-tillmans',name:'Wolfgang Tillmans',born:'1968',base:'Germany / United Kingdom',intro:'从青年文化、亲密肖像和政治议题到无相机抽象摄影，以非等级化墙面编排重新定义摄影展览。',methods:['日常摄影','墙面编排','无相机摄影','编辑实践'],subjects:['亲密关系','青年文化','酷儿生活','政治','抽象'],outputs:['摄影','装置','出版'],institutions:['Tate'],achievements:['Turner Prize 2000','Tate Modern exhibitions'],whyImportant:'Tillmans把私人快照、杂志文化、抽象实验和展览编排置于同一视觉系统，对1990年代以来摄影展示方式影响深远。',projects:[{year:'1990s–',title:'Installation / wall constellations',type:'摄影装置',facts:['将不同尺寸照片、喷墨打印和杂志页面组合在墙面。','其早期实践与欧洲俱乐部文化和i-D杂志密切相关。'],reading:'取消传统摄影作品之间的等级，让展墙本身成为编辑和意义生产空间。'}],images:[],sourceLabel:'Tate · Wolfgang Tillmans',sourceUrl:'https://www.tate.org.uk/art/artists/wolfgang-tillmans-2747'}
];
