import type { Artist } from './data';

const project = (year:string,title:string,type:string,facts:string[],reading:string)=>({year,title,type,facts,reading});

export const artistBatch34: Artist[] = [
 {id:'mikhael-subotzky',name:'Mikhael Subotzky',born:'1981',base:'Johannesburg',intro:'以长期摄影、电影、拼贴与装置研究南非监狱、城市空间、社会分层以及摄影观看机制。',methods:['长期纪实','类型学','影像研究','拼贴','装置'],subjects:['南非','监狱','城市','阶级','监控','观看'],outputs:['摄影','电影','装置','摄影书'],institutions:['Magnum Photos','MoMA','Tate'],achievements:['Deutsche Börse Photography Prize 2015'],whyImportant:'他把社会纪实推进为复杂的空间与图像系统，使建筑、制度、视线和社会结构能够在同一摄影项目中被比较。',projects:[project('2008–2011','Ponte City','长期摄影 / 档案研究',['与 Patrick Waterhouse 合作研究约翰内斯堡 Ponte City 大楼。','结合住户、建筑细节、档案和城市历史。'],'从单一建筑切入后种族隔离时代城市结构。')],images:[],sourceLabel:'Magnum Photos',sourceUrl:'https://www.magnumphotos.com/photographer/mikhael-subotzky/'},
 {id:'mishka-henner',name:'Mishka Henner',born:'1976',base:'Manchester',intro:'大量使用 Google Earth、Street View、网络数据库和卫星图像，把自动化视觉基础设施转化为摄影项目。',methods:['网络挪用','卫星图像','Google Street View','图像采样','数据库研究'],subjects:['监控','能源','平台','景观','军事','图像生产'],outputs:['摄影书','打印','网络项目','装置'],institutions:['MoMA','Centre Pompidou','Photographers Gallery'],achievements:['Deutsche Börse Photography Prize 2013 入围'],whyImportant:'他的实践把摄影作者从相机操作者转向图像系统的搜索者和编辑者，是理解平台摄影、机器视觉和现成数字图像的重要节点。',projects:[project('2012','Feedlots','卫星图像 / 景观研究',['利用公开卫星图像定位美国大型养牛场。','把工业农业基础设施转化为俯视景观。'],'摄影对象与拍摄者都被平台基础设施重新定义。')],images:[],sourceLabel:'艺术家官网',sourceUrl:'https://mishkahenner.com/'},
 {id:'susan-meiselas',name:'Susan Meiselas',born:'1948',base:'New York',intro:'以长期纪实摄影、口述史和档案协作处理战争、人权、地方历史与影像如何回到其原始社群。',methods:['长期纪实','参与式档案','口述史','摄影书','历史研究'],subjects:['战争','人权','地方记忆','女性','革命','影像伦理'],outputs:['摄影','摄影书','档案项目','装置'],institutions:['Magnum Photos','Whitney Museum','International Center of Photography'],achievements:['Hasselblad Award 1994','Deutsche Börse Photography Prize 2019'],whyImportant:'她不仅记录事件，也持续追问照片之后发生什么：图像如何被传播、重新解释并返回被摄者和当地社会。',projects:[project('1978–1979','Nicaragua','战争纪实 / 长期档案',['记录尼加拉瓜革命前后社会与政治冲突。','此后多次返回当地追踪照片、地点和人物的后续生命。'],'把经典新闻摄影转化为持续几十年的影像记忆研究。')],images:[],sourceLabel:'Magnum Photos',sourceUrl:'https://www.magnumphotos.com/photographer/susan-meiselas/'},
 {id:'mona-hatoum',name:'Mona Hatoum',born:'1952',base:'London',intro:'从行为和录像扩展到大型装置与雕塑，以日常物件、地图和身体尺度处理流亡、边界、权力与不安。',methods:['装置','现成物转化','行为','录像','尺度转换'],subjects:['流亡','边界','身体','家庭空间','权力','冲突'],outputs:['装置','雕塑','录像','行为'],institutions:['Tate','Centre Pompidou','Venice Biennale','Documenta'],achievements:['Turner Prize 1995 入围','Joan Miró Prize 2011'],whyImportant:'她能把极普通的家庭物件变成威胁性的空间结构，使政治经验不靠说明文字而直接进入身体尺度和观看经验。',projects:[project('1996','Measures of Distance','录像 / 身体与流亡',['以艺术家母亲的影像、阿拉伯文字和母女通信构成作品。','私人关系与迁徙经验叠合。'],'身体、语言和距离共同成为离散经验的结构。')],images:[],sourceLabel:'Tate',sourceUrl:'https://www.tate.org.uk/art/artists/mona-hatoum-2365'},
 {id:'shirana-shahbazi',name:'Shirana Shahbazi',born:'1974',base:'Zurich',intro:'在静物、肖像、风景、抽象几何和不同复制技术之间切换，研究摄影图像如何在媒介转换中改变意义。',methods:['编排摄影','图像转译','静物','抽象摄影','复制'],subjects:['图像语言','颜色','物件','风景','再现','摄影材料'],outputs:['摄影','壁画','装置','摄影书'],institutions:['MoMA','Barbican','Swiss Pavilion Venice Biennale'],achievements:['瑞士馆 Venice Biennale 2005'],whyImportant:'她拒绝固定摄影类型，把纪实、商业静物、抽象和手工复制放在同一体系里，非常适合研究摄影分类如何被拆散。',projects:[project('2002–ongoing','Flowers, Fruits & Portraits','摄影 / 图像转译',['持续拍摄静物、人物和风景并改变输出形式。','部分照片被转译为绘画或大型展示。'],'重点是同一图像在不同物质和展示语境中的变化。')],images:[],sourceLabel:'MoMA',sourceUrl:'https://www.moma.org/artists/26949'},
 {id:'gillian-wearing',name:'Gillian Wearing',born:'1963',base:'London',intro:'通过摄影、录像、面具和参与式表演研究公众形象、私人身份以及人们如何向镜头讲述自己。',methods:['参与式摄影','录像访谈','面具','角色扮演','社会实验'],subjects:['身份','公共空间','家庭','自我表演','社会关系','匿名性'],outputs:['摄影','录像','雕塑','公共艺术'],institutions:['Tate','Guggenheim','Venice Biennale'],achievements:['Turner Prize 1997'],whyImportant:'她把肖像摄影从艺术家观察对象改造成被摄者主动展示、隐藏和重写身份的协商过程。',projects:[project('1992–1993','Signs that say what you want them to say','参与式街头肖像',['邀请街头陌生人在纸上写下自己想说的话。','将文字牌与持牌者共同拍摄。'],'肖像的意义由外表与自我陈述之间的落差产生。')],images:[],sourceLabel:'Tate',sourceUrl:'https://www.tate.org.uk/art/artists/gillian-wearing-obe-2648'},
 {id:'wafaa-bilal',name:'Wafaa Bilal',born:'1966',base:'New York',intro:'以互动装置、网络行为、摄影和游戏处理伊拉克战争、监控、远程暴力、迁徙与身体政治。',methods:['互动艺术','网络行为','游戏艺术','身体介入','装置'],subjects:['战争','伊拉克','监控','远程暴力','迁徙','身体'],outputs:['互动装置','录像','摄影','游戏','行为'],institutions:['MoMA','New Museum','Venice Biennale'],achievements:['The 3rd I · 2010–2011'],whyImportant:'他把网络参与和战争中的远程观看放进同一结构，让观众不只是观看政治暴力，而被迫意识到自己的操作位置。',projects:[project('2007','Domestic Tension','网络互动行为',['艺术家在画廊居住一个月。','网络用户可远程控制彩弹枪向空间射击。'],'把远程战争、屏幕观看和参与者责任压缩进一个互动系统。')],images:[],sourceLabel:'艺术家官网',sourceUrl:'https://wafaabilal.com/'},
 {id:'simryn-gill',name:'Simryn Gill',born:'1959',base:'Sydney / Port Dickson',intro:'以摄影、书籍、植物材料和现成物研究地点、语言、殖民分类与环境变化。',methods:['摄影系列','书籍介入','材料转化','分类研究','场域观察'],subjects:['地点','殖民','语言','植物','环境','迁徙'],outputs:['摄影','装置','雕塑','艺术家书'],institutions:['Tate','Documenta','Venice Biennale'],achievements:['Australia Pavilion · Venice Biennale 2013','documenta 12 · 2007'],whyImportant:'她把摄影与植物、书籍和地点研究连接起来，展示分类系统如何塑造我们对自然、文化与地域的理解。',projects:[project('1999–2003','Dalam','摄影系列 / 室内空间',['拍摄马来西亚不同家庭的室内空间。','人物缺席但物件和布置保留生活痕迹。'],'通过内部空间讨论地方、文化与现代性的混合状态。')],images:[],sourceLabel:'Tate',sourceUrl:'https://www.tate.org.uk/art/artists/simryn-gill-2675'}
];
