import type { Artist } from './data';

const project = (year: string, title: string, type: string, facts: string[], reading: string) => ({ year, title, type, facts, reading });

export const artistBatch28: Artist[] = [
  { id:'otobong-nkanga', name:'Otobong Nkanga', born:'1974', base:'Antwerp / Kano', intro:'以土地、矿物和全球资源流通为核心，把绘画、雕塑、摄影、织毯、表演与研究组织成跨媒介系统。', methods:['研究型艺术','材料研究','地图化','表演','跨媒介装置'], subjects:['土地','采掘','殖民','资源','生态','劳动'], outputs:['装置','雕塑','织毯','摄影','绘画','表演'], institutions:['Tate','Documenta','Sharjah Biennial','Venice Biennale'], achievements:['Sharjah Biennial Prize 2019','Lise Wilhelmsen Art Award 2019'], whyImportant:'她把矿物从材料变成政治关系，追踪开采、加工、运输、消费与欲望之间的链条，是理解生态与全球资本网络的重要艺术家。', projects:[project('2015–ongoing','Carved to Flow','材料 / 资源网络 / 社会项目',['从肥皂及其原料的生产与流通出发。','把材料、劳动、土地和经济网络连接起来。'],'重点不是单一物件，而是物质如何携带地理、劳动和权力关系。')], images:[], sourceLabel:'Otobong Nkanga 官方网站', sourceUrl:'https://www.otobong-nkanga.com/' },
  { id:'sammy-baloji', name:'Sammy Baloji', born:'1978', base:'Lubumbashi / Brussels', intro:'从刚果加丹加地区的殖民档案、矿业遗产和城市空间出发，以摄影蒙太奇、录像与装置让历史剥削进入当代景观。', methods:['档案再语境化','摄影蒙太奇','田野研究','后殖民研究','空间装置'], subjects:['殖民','矿业','刚果','工业遗产','劳动','记忆'], outputs:['摄影','拼贴','录像','装置'], institutions:['Documenta','Venice Biennale','Sharjah Biennial','Villa Medici'], achievements:['Prince Claus Award 2009','documenta 14 · 2017','Venice Biennale · 2015'], whyImportant:'他把殖民时期的矿业档案与今天的废墟和城市景观叠合，使历史成为仍在塑造资源、劳动与空间的现实结构。', projects:[project('2006','Mémoire','档案摄影 / 蒙太奇',['将殖民时期矿业档案人物嵌入当代工业遗址。','连接加丹加采矿史与当下景观。'],'档案不是说明过去，而被重新放回其后果仍然存在的地点。')], images:[], sourceLabel:'Triennale Art & Industrie', sourceUrl:'https://triennale.fr/en/artistes/sammy-baloji' },
  { id:'bouchra-khalili', name:'Bouchra Khalili', born:'1975', base:'Berlin / Casablanca', intro:'以电影、录像、地图、摄影与出版研究迁徙、公民身份、反殖民斗争和被国家叙事排除的声音。', methods:['影像访谈','参与式叙事','地图化','档案研究','概念纪录片'], subjects:['迁徙','公民身份','边界','反殖民','记忆政治','自我表述'], outputs:['录像','电影','装置','摄影','出版'], institutions:['MoMA','Jeu de Paume','Palais de Tokyo','MACBA'], achievements:['The Mapping Journey Project · MoMA 个展 2016'], whyImportant:'她把替他人发声改造成让主体自己构造叙事：地图、声音和镜头成为迁徙者重新描述自身路径与政治位置的工具。', projects:[project('2008–2011','The Mapping Journey Project','八频道录像 / 迁徙地图',['八位迁徙者在地图上亲手画出跨境路线。','镜头主要聚焦手、地图和声音而非传统肖像。'],'地图从国家管理工具转成个人叙述与反地图实践。')], images:[], sourceLabel:'MoMA', sourceUrl:'https://www.moma.org/artists/47100-bouchra-khalili' },
  { id:'akram-zaatari', name:'Akram Zaatari', born:'1966', base:'Beirut', intro:'围绕黎巴嫩战后社会、影像流通与摄影档案展开电影、录像、摄影、装置和写作实践，也是 Arab Image Foundation 联合创办人。', methods:['档案研究','影像考古','口述史','再语境化','电影研究'], subjects:['黎巴嫩','战争','摄影史','身体','媒介','社会关系'], outputs:['电影','录像','摄影装置','书籍','档案项目'], institutions:['Arab Image Foundation','Centre Pompidou','Tate','Venice Biennale','Documenta'], achievements:['Lebanon Pavilion · Venice Biennale 2013','dOCUMENTA(13) · 2012'], whyImportant:'他是档案作为当代艺术方法的关键人物之一：不把旧照片当作透明历史证据，而研究照片怎样被生产、保存、交换和重新解释。', projects:[project('1999–ongoing','The Madani Project','摄影档案研究',['长期研究西顿摄影师 Hashem el Madani 的商业照相馆档案。','从姿势、委托关系和社会习俗理解摄影实践。'],'重点从旧照片拍了什么转向一个社会如何通过照相馆学习呈现自己。')], images:[], sourceLabel:'MACBA', sourceUrl:'https://www.macba.cat/en/actor/akram-zaatari/' },
  { id:'newsha-tavakolian', name:'Newsha Tavakolian', born:'1981', base:'Tehran', intro:'从新闻摄影进入更具编排和概念性的视觉实践，持续处理伊朗女性、社会压力、战争余波与私人情绪。', methods:['纪实摄影','编排式摄影','长期观察','肖像','影像叙事'], subjects:['伊朗','女性','审查','战争','日常生活','情绪'], outputs:['摄影','录像','摄影书','电影'], institutions:['Magnum Photos','Victoria and Albert Museum','LACMA','British Museum'], achievements:['Carmignac Photojournalism Award 2014','Prince Claus Award · Principal Laureate 2015'], whyImportant:'她连接了新闻摄影与当代摄影：既保留现实社会的具体压力，又通过编排、象征和系列结构突破单张新闻图片的说明逻辑。', projects:[project('2010','Listen','编排肖像 / 女性与审查',['拍摄在伊朗无法公开独唱的女性歌手。','结合肖像与想象中的唱片封面。'],'把不能被听见转化为视觉结构，摄影同时记录限制并制造一个虚构的公开空间。')], images:[], sourceLabel:'Newsha Tavakolian 官方网站', sourceUrl:'https://www.newshatavakolian.com/about' },
  { id:'joana-choumali', name:'Joana Choumali', born:'1974', base:'Abidjan', intro:'以摄影为基础并直接在照片表面刺绣，把缓慢的手工劳动、记忆和西非城市经验叠加在摄影瞬间之上。', methods:['街头摄影','刺绣摄影','混合媒介','日常观察','手工介入'], subjects:['阿比让','记忆','创伤','日常生活','城市','疗愈'], outputs:['摄影','刺绣照片','混合媒介作品'], institutions:['Bamako Encounters','Zeitz MOCAA','Musée du Quai Branly'], achievements:['Prix Pictet 2019'], whyImportant:'她把摄影的瞬间与刺绣的慢时间放在同一表面：图像不再是完成品，而是可以被身体劳动继续书写的对象。', projects:[project('2016–2019','Ça va aller','手机摄影 / 刺绣',['在 Grand-Bassam 袭击后以手机记录城市日常。','之后在打印照片上进行手工刺绣。'],'刺绣不是装饰，而是在创伤之后用缓慢动作重新接触和处理图像。')], images:[], sourceLabel:'Joana Choumali 官方网站', sourceUrl:'https://www.joanachoumali.com/index.php/about' },
  { id:'mame-diarra-niang', name:'Mame-Diarra Niang', born:'1982', base:'Paris', intro:'以摄影探索领土的可塑性、记忆与遗忘，常通过运动模糊、身体和不稳定空间让身份保持流动。', methods:['实验肖像','运动模糊','系列编辑','空间研究','摄影书'], subjects:['身体','黑人身份','记忆','遗忘','领土','自我'], outputs:['摄影','摄影书','装置'], institutions:['Fondation Henri Cartier-Bresson','Zeitz MOCAA','MoMA'], achievements:['Remember to Forget · Fondation Henri Cartier-Bresson 2024'], whyImportant:'她拒绝把身份变成稳定、可识别的肖像信息，通过模糊和系列结构让自我表现为持续变化的领土。', projects:[project('2013–2022','The Citadel: a trilogy','摄影三部曲 / 摄影书',['围绕地点、身体与心理领土组织三个相互关联的系列。','2022 年由 MACK 以三卷本形式出版。'],'地点从地理坐标转成不断被记忆、时间和身体重新塑造的心理结构。')], images:[], sourceLabel:'Stevenson', sourceUrl:'https://www.stevenson.info/artist/mame-diarra-niang/biography' },
  { id:'dineo-seshee-bopape', name:'Dineo Seshee Bopape', born:'1981', base:'Johannesburg', intro:'以土壤、砖、木材、声音、录像和现成物构成密集装置，处理土地、殖民记忆、黑人女性经验与精神性。', methods:['材料装置','场域特定','录像拼贴','声音','仪式性实践'], subjects:['土地','殖民','黑人女性','记忆','暴力','精神性'], outputs:['装置','雕塑','录像','声音','摄影'], institutions:['Tate','Palais de Tokyo','Sharjah Biennial','Venice Biennale'], achievements:['Sharjah Biennial Prize 2017','Future Generation Art Prize 2017'], whyImportant:'她把土地同时作为真实材料、历史证据和精神媒介；土、声音、建筑和身体共同承载殖民历史与修复问题。', projects:[project('2016–2017','sa ____ ke lerole, (sa lerole ke ___)','土壤 / 建筑性装置',['以压实泥土、砖块和建筑结构组织空间。','土地材料直接进入展览而非仅被再现。'],'材料同时指向家园、剥夺、历史和身体记忆。')], images:[], sourceLabel:'Tate', sourceUrl:'https://www.tate.org.uk/art/artists/dineo-seshee-bopape-21409' }
];
