import type { Artist } from './data';

export const artistBatch134: Artist[] = [
{id:'latoya-ruby-frazier',name:'LaToya Ruby Frazier',born:'1982',base:'USA',intro:'美国摄影与媒体艺术家，从家族内部长期记录宾夕法尼亚州布拉多克的去工业化、环境污染、医疗与阶级问题，并把私人身体经验连接到结构性经济史。',methods:['长期纪实','家族协作','自我表述','社会调查'],subjects:['去工业化','环境正义','黑人家庭','医疗','阶级'],outputs:['摄影','录像','文本','装置'],institutions:['Whitney Museum of American Art'],achievements:['The Notion of Family','Whitney Biennial 2012'],whyImportant:'Frazier从被影响的家庭和社区内部重写社会纪实传统，反转外部摄影者替弱势群体发言的权力结构。',projects:[{year:'2002–',title:'The Notion of Family',type:'长期摄影 / 家族与工业城市',facts:['Whitney记录该系列围绕艺术家的家乡Braddock及其家族展开。','作品把钢铁工业衰退后的经济、社会与环境危机和家庭身体并置。'],reading:'家族照片在这里既是私人史，也是去工业化美国的结构性证据。'}],images:[],sourceLabel:'Whitney Museum · LaToya Ruby Frazier',sourceUrl:'https://whitney.org/exhibitions/2012-biennial/latoya-ruby-frazier'},
{id:'an-my-le',name:'An-My Lê',born:'1960',base:'Vietnam / USA',intro:'越南出生的美国摄影艺术家，以大型摄影持续研究战争、军事训练、历史重演、纪念碑与景观之间的关系。',methods:['大型景观摄影','历史重演观察','军事空间研究','系列摄影'],subjects:['战争','军事','景观','历史记忆','纪念碑'],outputs:['摄影','影像'],institutions:['Whitney Museum of American Art'],achievements:['29 Palms','The Silent General','Whitney Biennial 2017'],whyImportant:'Lê不直接追逐战场新闻事件，而拍摄训练、重演、电影布景和纪念碑，使战争如何被想象、表演和写入景观成为摄影主题。',projects:[{year:'2015–2017',title:'The Silent General',type:'摄影 / 历史与当下',facts:['Whitney收藏该系列作品，并记录其从电影《Free State of Jones》的战争场景延伸到新奥尔良南方邦联纪念碑争议。','系列将过去、现在与未来的历史循环放在同一视觉结构中。'],reading:'真实历史、电影重演和公共纪念碑并置后，摄影不再只是记录事件，而成为观察历史如何持续进入当下的方法。'}],images:[],sourceLabel:'Whitney Museum · An-My Lê',sourceUrl:'https://whitney.org/artists/9860'},
{id:'moyra-davey',name:'Moyra Davey',born:'1958',base:'Canada / USA',intro:'加拿大出生、纽约工作的艺术家，以摄影、写作、录像和邮寄系统连接阅读、日常物件、记忆与图像流通。',methods:['摄影与写作','邮寄摄影','图像网格','日常观察'],subjects:['阅读','日常物件','记忆','流通','私人公共空间'],outputs:['摄影','录像','文本','艺术家书'],institutions:['MoMA'],achievements:['New Photography 2011 — MoMA','The Coffee Shop, The Library'],whyImportant:'Davey把照片折叠、邮寄并保留邮戳与磨损，使图像的移动、交换和物质经历成为作品的一部分。',projects:[{year:'2011',title:'The Coffee Shop, The Library',type:'摄影 / 邮寄与网格',facts:['MoMA为New Photography 2011记录该作品。','照片被折成信封寄给朋友，再带着邮票、邮戳和运输痕迹进入展示。'],reading:'图像不是无摩擦的信息，而是会旅行、受损并积累关系的物质对象。'}],images:[],sourceLabel:'MoMA · Moyra Davey',sourceUrl:'https://www.moma.org/interactives/exhibitions/2011/newphotography/moyra-davey/index.html'},
{id:'boris-mikhailov',name:'Boris Mikhailov',born:'1938',base:'Ukraine / Germany',intro:'乌克兰摄影家，以实验性序列、手工处理与直接社会观察记录苏联晚期及后苏联社会、贫困、身体和公共生活。',methods:['社会纪实','摄影序列','实验摄影','直接肖像'],subjects:['后苏联社会','贫困','身体','公共生活','政治转型'],outputs:['摄影','摄影书'],institutions:['MoMA'],achievements:['Case History','New Photography 9 — MoMA 1993','Boris Mikhailov: Case History — MoMA 2011'],whyImportant:'Mikhailov把社会纪实与粗粝、主观甚至令人不适的视觉关系结合，成为理解东欧从苏联晚期到资本主义转型的重要摄影节点。',projects:[{year:'1997–1998',title:'Case History',type:'摄影 / 后苏联社会',facts:['MoMA收藏该系列彩色摄影，并于2011年举办Boris Mikhailov: Case History展览。','系列集中处理苏联解体后社会边缘群体与新的贫困现实。'],reading:'作品拒绝把社会转型抽象成政治概念，而让身体、尊严和观看伦理直接进入摄影关系。'}],images:[],sourceLabel:'MoMA · Boris Mikhailov',sourceUrl:'https://www.moma.org/artists/8168-boris-mikhailov'},
{id:'sammy-baloji',name:'Sammy Baloji',born:'1978',base:'DR Congo / Belgium',intro:'刚果（金）艺术家，以摄影拼贴、档案、雕塑和影像追踪加丹加矿业、殖民历史、资源开采、博物馆分类与文化归还。',methods:['档案拼贴','材料研究','殖民史调查','挪用与再语境化'],subjects:['矿产','殖民主义','资源开采','博物馆','文化归还'],outputs:['摄影','拼贴','雕塑','影像','装置'],institutions:['La Biennale di Venezia'],achievements:['Biennale Architettura 2023','Biennale Arte 2026'],whyImportant:'Baloji把刚果矿产史与殖民视觉档案、民族志博物馆和当代全球资源网络连接，使摄影成为研究物质政治与殖民余波的工具。',projects:[{year:'2026',title:'Biennale Arte 2026 presentation',type:'雕塑 / 拼贴 / 殖民资源史',facts:['La Biennale记录Baloji在中央馆展示三件雕塑与十六件拼贴版画。','作品扫描并放大刚果艺术品，同时引入铀晶体结构，连接放射性、暴力开采与原子武器史。'],reading:'传统器物、科学扫描与矿物结构相遇后，博物馆收藏史被重新放回资源开采和殖民权力关系中。'}],images:[],sourceLabel:'La Biennale di Venezia · Sammy Baloji',sourceUrl:'https://www.labiennale.org/en/art/2026/sammy-baloji'},
{id:'lebohang-kganye',name:'Lebohang Kganye',born:'1990',base:'South Africa',intro:'南非视觉艺术家，以家族相册、口述史、摄影蒙太奇、表演、剪影、动画和空间装置重构个人与集体记忆。',methods:['家族档案重演','摄影蒙太奇','口述史','剧场化叙事'],subjects:['家庭','记忆','种族隔离','殖民历史','家与迁徙'],outputs:['摄影','蒙太奇','装置','动画','拼布'],institutions:['Foam','La Biennale di Venezia'],achievements:['Foam Paul Huf Award 2022','South African Pavilion — Venice Biennale 2022'],whyImportant:'Kganye把私人家庭照片从静态档案转化成可表演、可搭景、可动画化的记忆空间，是南非新一代扩展摄影的重要代表。',projects:[{year:'2013',title:'Ke Lefa Laka: Her-Story',type:'摄影蒙太奇 / 家族档案',facts:['Foam将该项目列为其过去十年实践的重要组成，并记录其使用私人相册和家庭微观历史。','她把档案照片、自产图像与表演结合，处理记忆与想象之间的空缺。'],reading:'艺术家不是把家庭档案当作固定事实，而通过重新扮演和蒙太奇让缺失的家庭记忆再次被协商。'}],images:[],sourceLabel:'Foam · Lebohang Kganye',sourceUrl:'https://www.foam.org/artists/lebohang-kganye'}
];