import type { Artist } from './data';
import { artistBatch116 } from './expansionBatch116';

export const artistBatch115: Artist[] = [
{id:'cao-fei',name:'Cao Fei',born:'1978',base:'China',intro:'中国多媒体艺术家，以录像、摄影、虚拟世界和装置研究快速城市化、工厂劳动、青年亚文化以及数字生活中现实与幻想的交叠。',methods:['社会观察','虚拟世界建构','协作表演','纪录与虚构混合'],subjects:['城市化','工厂劳动','青年文化','数字身份','未来想象'],outputs:['录像','摄影','装置','虚拟环境'],institutions:['MoMA','MoMA PS1','La Biennale di Venezia'],achievements:['Whose Utopia','RMB City','COSPlayers','La Town'],whyImportant:'Cao Fei把珠三角工业现实、网络文化和虚拟世界放进同一套影像语言，是理解中国全球化、数字社会与后互联网艺术的重要艺术家。',projects:[{year:'2006',title:'Whose Utopia',type:'录像 / 工厂协作项目',facts:['作品在珠三角OSRAM照明工厂六个月驻留期间拍摄。','艺术家记录生产过程，并与工人合作在工厂内发展舞蹈、音乐等表演。'],reading:'作品把标准化生产线与工人的私人愿望并置，使劳动者不只是工业系统中的匿名身体。'}],images:[],sourceLabel:'MoMA · Cao Fei',sourceUrl:'https://www.moma.org/artists/35159-cao-fei'},
{id:'walid-raad',name:'Walid Raad',born:'1967',base:'Lebanon / United States',intro:'黎巴嫩艺术家，以摄影、录像、文本、档案和讲演式装置研究黎巴嫩战争、历史书写、记忆以及艺术制度如何生产事实。',methods:['虚构档案','研究型艺术','讲演表演','摄影文本'],subjects:['战争','记忆','档案','历史书写','艺术制度'],outputs:['摄影','录像','文本','装置','表演'],institutions:['MoMA','MoMA PS1'],achievements:['The Atlas Group','Scratching on Things I Could Disavow','MoMA Walid Raad 2015–2016'],whyImportant:'Raad把档案的可信度本身变成作品对象，通过真实材料与虚构叙事的混合改变了当代艺术处理战争、证据和历史记忆的方式。',projects:[{year:'1989–2004',title:'The Atlas Group',type:'虚构档案 / 摄影录像研究',facts:['The Atlas Group围绕黎巴嫩当代历史与战争建立摄影、录像、笔记和虚构文件体系。','MoMA在2015–2016年举办Walid Raad大型个展。'],reading:'作品迫使观看者不断判断文件、作者和历史叙述的真实性，从而把档案制度本身暴露出来。'}],images:[],sourceLabel:'MoMA · The Atlas Group/Walid Raad',sourceUrl:'https://www.moma.org/artists/27369-the-atlas-group-walid-raad'},
{id:'akram-zaatari',name:'Akram Zaatari',born:'1966',base:'Lebanon',intro:'黎巴嫩艺术家、影像研究者，以摄影档案、录像、访谈和考古式调查研究战争、地方摄影史、私人记忆与图像的流通。',methods:['档案研究','口述史','影像考古','摄影再语境化'],subjects:['战争','摄影史','记忆','黎巴嫩','图像档案'],outputs:['摄影','录像','装置','书籍'],institutions:['MoMA'],achievements:['This Day','In This House','Letter to a Refusing Pilot','Projects 100: Akram Zaatari'],whyImportant:'Zaatari把地方照相馆和私人照片视为社会历史的知识系统，使保存、再观看和重新组织既有图像成为当代摄影的重要创作方法。',projects:[{year:'2013',title:'Letter to a Refusing Pilot',type:'录像 / 装置',facts:['作品进入MoMA馆藏艺术家记录的重要作品序列。','项目从战争时期一名拒绝轰炸目标的飞行员故事出发处理个人记忆与历史。'],reading:'私人传闻、战争史和影像证据被放在一起，使英雄叙事转化为关于记忆如何形成的调查。'}],images:[],sourceLabel:'MoMA · Akram Zaatari',sourceUrl:'https://www.moma.org/artists/41278-akram-zaatari'},
{id:'bouchra-khalili',name:'Bouchra Khalili',born:'1975',base:'Morocco / France',intro:'法裔摩洛哥艺术家，以录像、地图、声音和档案让移民与流散者以自己的语言叙述跨越边境的路径，并研究公民身份、国家与政治主体性。',methods:['第一人称证言','地图绘制','长镜头','档案研究'],subjects:['迁徙','边境','公民身份','流散','政治主体'],outputs:['录像','装置','摄影','文本'],institutions:['MoMA','Palais de Tokyo','documenta','La Biennale di Venezia'],achievements:['The Mapping Journey Project','Foreign Office','Speeches Series','55th Venice Biennale'],whyImportant:'Khalili拒绝替迁徙者发言，而让声音、手势和路线成为主体自我表述的形式，是当代艺术处理中介、边界和公民身份的重要方法范例。',projects:[{year:'2008–2011',title:'The Mapping Journey Project',type:'八频道录像装置',facts:['八段录像均围绕一张地图、一只手、一支永久性记号笔和一个人的声音展开。','参与者在地图上画出自己跨越国界的真实迁徙路径。'],reading:'国家边界与个人移动轨迹直接叠加，让抽象地图转化为由具体身体和声音重新书写的政治空间。'}],images:[],sourceLabel:'MoMA · Bouchra Khalili',sourceUrl:'https://www.moma.org/artists/47100-bouchra-khalili'},
{id:'mika-rottenberg',name:'Mika Rottenberg',born:'1976',base:'Israel / United States',intro:'以色列出生艺术家，以荒诞录像、雕塑和建筑式装置构造封闭生产系统，研究女性身体、劳动、商品、全球供应链与价值生产。',methods:['荒诞叙事','空间装置','劳动编排','虚构生产系统'],subjects:['劳动','身体','商品','全球化','生产'],outputs:['录像','装置','雕塑','摄影'],institutions:['MoMA','MoMA PS1'],achievements:["Mary's Cherries",'Tropical Breeze','Day Labor','Greater New York 2005'],whyImportant:'Rottenberg把身体动作、商品生产和装置空间接成看似合理却荒谬的生产链，使全球资本主义中的劳动与价值关系获得强烈的物理形态。',projects:[{year:'2004',title:"Mary's Cherries",type:'录像 / 摄影装置',facts:['MoMA馆藏版本包含彩色有声录像和数字C-prints。','作品以人工化的工作空间和身体劳动构造荒诞生产流程。'],reading:'身体既像生产机器又无法完全被生产逻辑吸收，使劳动制度的荒谬性被视觉化。'}],images:[],sourceLabel:'MoMA · Mika Rottenberg',sourceUrl:'https://www.moma.org/artists/28956-mika-rottenberg'},
{id:'ho-tzu-nyen',name:'Ho Tzu Nyen',born:'1976',base:'Singapore',intro:'新加坡艺术家，以多频道影像、算法系统、动画和讲演研究东南亚历史、殖民知识、帝国、民族主义以及历史人物与图像的循环再现。',methods:['研究型影像','多频道装置','历史重组','算法叙事'],subjects:['东南亚历史','殖民主义','帝国','民族主义','知识生产'],outputs:['录像','多频道装置','动画','讲演表演'],institutions:['MoMA','Aichi Triennale'],achievements:['Hotel Aporia','The Critical Dictionary of Southeast Asia','The Cloud of Unknowing'],whyImportant:'Ho把历史研究转化为可递归、可重组的影像系统，为东南亚当代艺术提供了不同于线性民族史的复杂历史模型。',projects:[{year:'2019',title:'Hotel Aporia',type:'六频道录像装置',facts:['作品受Aichi Triennale委任，最初安装在日本丰田市一座大正时代旅馆建筑中。','作品连接神风飞行员、京都学派、横山隆一与小津安二郎等战争时期人物和材料。'],reading:'建筑、电影史和帝国意识形态相互覆盖，使日本战争史与新加坡经验进入同一套跨区域历史结构。'}],images:[],sourceLabel:'MoMA · An Evening with Ho Tzu Nyen',sourceUrl:'https://www.moma.org/calendar/events/10136'},
...artistBatch116
];