import type { Artist } from './data';

export const artistBatch52: Artist[] = [
  { id:'zoe-leonard', name:'Zoe Leonard', born:'1961', base:'United States', intro:'美国艺术家，以摄影、雕塑和长期序列研究城市空间、商品流通、观看制度、性别与酷儿政治。', methods:['长期摄影','类型学','档案式序列','制度批判'], subjects:['城市','商品流通','观看制度','酷儿政治','时间'], outputs:['摄影','雕塑','装置'], institutions:['MoMA','MoMA PS1','Whitney Museum of American Art'], achievements:['MoMA 2015 Analogue 个展','多届 Whitney Biennial 参展'], whyImportant:'她把街头观察、摄影的物质性和社会经济结构结合，是从身份政治进入城市图像制度研究的重要节点。', projects:[{year:'1998–2009',title:'Analogue',type:'长期摄影系列',facts:['记录纽约等地小型商店、橱窗与商品流通。','2015 年在 MoMA 展出。'],reading:'可观察全球化如何通过最普通的街角商业空间留下视觉痕迹。'}], images:[], sourceLabel:'MoMA · Zoe Leonard', sourceUrl:'https://www.moma.org/artists/34219-zoe-leonard' },
  { id:'trevor-paglen', name:'Trevor Paglen', born:'1974', base:'United States', intro:'美国艺术家、地理学者，以摄影、卫星追踪、研究和人工智能项目揭示通常不可见的军事、监控与机器视觉基础设施。', methods:['调查研究','远距离摄影','技术系统可视化','机器视觉研究'], subjects:['监控','军事基础设施','人工智能','隐形权力','太空'], outputs:['摄影','录像','雕塑','数据与工程项目'], institutions:['Smithsonian American Art Museum','Whitney Museum of American Art','Guggenheim Museum'], achievements:['2016 Deutsche Börse Photography Foundation Prize','2017 MacArthur Fellow'], whyImportant:'他把摄影从记录可见世界推进到研究机器如何观看以及国家基础设施如何主动隐藏自身，对 AI 图像研究尤其关键。', projects:[{year:'2018',title:'Sites Unseen',type:'摄影 / AI / 雕塑调查',facts:['Smithsonian American Art Museum 举办中期回顾展。','展览连接早期秘密军事设施摄影与人工智能图像项目。'],reading:'核心不是拍到秘密地点本身，而是研究什么机制决定某些东西不可见。'}], images:[], sourceLabel:'Smithsonian American Art Museum · Trevor Paglen', sourceUrl:'https://americanart.si.edu/exhibitions/paglen' },
  { id:'mikhael-subotzky', name:'Mikhael Subotzky', born:'1981', base:'South Africa', intro:'南非艺术家，以摄影、录像和装置长期研究监狱、城市建筑、社会分层与后种族隔离时代的空间结构。', methods:['长期纪实','建筑类型学','合作研究','序列与网格'], subjects:['监狱','城市','社会分层','后种族隔离','观看'], outputs:['摄影','录像','装置','摄影书'], institutions:['MoMA','Centre Pompidou','National Gallery of Art'], achievements:['MoMA New Photography 2008','Deutsche Börse Photography Prize 2015（与 Patrick Waterhouse）'], whyImportant:'他把社会纪实与高度结构化的展示系统结合，使单一地点成为研究权力、城市和观看关系的复杂模型。', projects:[{year:'2008–2014',title:'Ponte City',type:'摄影 / 档案 / 装置',facts:['与 Patrick Waterhouse 合作研究约翰内斯堡 Ponte City。','项目通过门、窗、电视等类型学图像组织建筑内部生活。'],reading:'建筑不是背景，而是一套能把城市历史、阶级与私人生活压缩在一起的结构。'}], images:[], sourceLabel:'MoMA · Mikhael Subotzky', sourceUrl:'https://www.moma.org/artists/30365-mikhael-subotzky' },
  { id:'shilpa-gupta', name:'Shilpa Gupta', born:'1976', base:'India', intro:'孟买跨媒介艺术家，通过互动装置、声音、文字、录像和公共介入研究边界、审查、监控、国家权力与身份。', methods:['互动装置','文本与声音','公共介入','参与式研究'], subjects:['边界','审查','监控','身份','国家权力'], outputs:['装置','录像','声音','行为','公共艺术'], institutions:['Tate','Guggenheim Museum','Centre Pompidou','M+'], achievements:['参加第58届威尼斯双年展（2019）'], whyImportant:'她把地缘政治边界转化为观众能够身体进入的声音、文字与空间机制，是南亚当代政治艺术的重要节点。', projects:[{year:'2017–2018',title:'For, in your tongue, I cannot fit',type:'声音装置',facts:['围绕因政治立场遭监禁或压制的诗人展开。','以多声道声音与悬吊麦克风形成空间化文本。'],reading:'作品把审查从抽象政治概念转化成谁能够发声、谁被迫沉默的身体经验。'}], images:[], sourceLabel:'Shilpa Gupta · official biography', sourceUrl:'https://shilpagupta.com/about/' },
  { id:'el-anatsui', name:'El Anatsui', born:'1944', base:'Ghana / Nigeria', intro:'加纳出生、长期在尼日利亚工作的雕塑家，以瓶盖、铜线、木材和其他材料构成可变形的大型雕塑，连接贸易、消费、殖民历史与材料循环。', methods:['材料转换','模块化编织','现成物再利用','场域适应'], subjects:['贸易','消费','殖民历史','环境','材料记忆'], outputs:['雕塑','大型装置'], institutions:['Tate Modern','Centre Pompidou','La Biennale di Venezia'], achievements:['2015 Venice Biennale Golden Lion for Lifetime Achievement','2023 Tate Modern Hyundai Commission'], whyImportant:'他改变了雕塑关于固定形态和贵重材料的传统想象，同时把跨大西洋贸易与消费史嵌入材料本身。', projects:[{year:'2023',title:'Behind the Red Moon',type:'Turbine Hall 场域装置',facts:['为 Tate Modern Hyundai Commission 创作。','延续以回收瓶盖等材料形成巨大柔性结构的方法。'],reading:'材料的来源、重复劳动与可变悬挂方式共同构成作品意义，而不只是表面的织物视觉效果。'}], images:[], sourceLabel:'Tate · El Anatsui Hyundai Commission', sourceUrl:'https://www.tate.org.uk/press/press-releases/el-anatsui-to-be-next-hyundai-commission-artist-for-tate-moderns-turbine-hall' },
  { id:'aida-muluneh', name:'Aida Muluneh', born:'1974', base:'Ethiopia / Côte d’Ivoire', intro:'埃塞俄比亚摄影艺术家、策展人与文化组织者，以高度编排的色彩摄影、身体绘画和象征系统讨论女性经验、非洲身份、环境与社会议题。', methods:['编排摄影','色彩系统','身体绘画','象征叙事'], subjects:['非洲身份','女性','环境','社会议题','自我表述'], outputs:['摄影','策展与摄影平台'], institutions:['MoMA','Smithsonian National Museum of African Art'], achievements:['2007 Bamako Encounters European Union Prize','Addis Foto Fest 创办人'], whyImportant:'她既扩展非洲编排摄影的视觉语言，也通过 Addis Foto Fest 等平台直接建设非洲摄影的制度网络。', projects:[{year:'2016',title:'Distant Echoes',type:'编排摄影系列',facts:['以鲜明色块、身体姿态和象征物构成非写实场景。'],reading:'不要只把颜色视为风格；它与身体、文化符号和作者主动控制非洲形象生产的权力有关。'}], images:[], sourceLabel:'Aida Muluneh · official biography', sourceUrl:'https://aidamuluneh.com/about/' }
];
