import type { Artist } from './data';
const project=(year:string,title:string,type:string,facts:string[],reading:string)=>({year,title,type,facts,reading});
export const artistBatch45: Artist[] = [
{id:'latoya-ruby-frazier',name:'LaToya Ruby Frazier',born:'1982',base:'United States',intro:'以摄影、录像和社会参与实践记录去工业化、环境不平等、医疗与劳动问题，并把家庭史和公共历史连接起来。',methods:['长期纪实','合作式肖像','社会参与','家庭档案'],subjects:['劳动','环境正义','医疗','家庭','去工业化'],outputs:['摄影','录像','摄影书','装置'],institutions:['MoMA','Whitney Museum','Carnegie Museum of Art'],achievements:['MacArthur Fellow 2015','The Notion of Family · Aperture'],whyImportant:'她把私人家庭档案、工业城市结构与社会正义放进同一长期摄影实践，是当代社会纪实从“观察他人”走向合作与共同见证的重要节点。',projects:[project('2001–2014','The Notion of Family','长期摄影 / 家庭与工业城市',['围绕宾夕法尼亚 Braddock 的家庭、医疗与工业衰退展开。','将自画像、家庭成员和城市环境并置。'],'私人身体与工业结构被放在同一历史中阅读。')],images:[],sourceLabel:'MoMA',sourceUrl:'https://www.moma.org/artists/40327'},
{id:'alec-soth',name:'Alec Soth',born:'1969',base:'Minneapolis',intro:'以大画幅摄影和长途旅行建立人物、地景与偶遇之间的松散叙事，是当代美国摄影书和公路摄影的重要人物。',methods:['大画幅摄影','公路摄影','长期项目','序列编辑'],subjects:['美国社会','孤独','地方','梦想','日常'],outputs:['摄影','摄影书'],institutions:['Magnum Photos','San Francisco Museum of Modern Art','Walker Art Center'],achievements:['Sleeping by the Mississippi · 2004'],whyImportant:'他把纪实摄影从事件说明转向开放的文学式序列，使人物、物件和风景通过摄影书编辑产生意义。',projects:[project('1999–2004','Sleeping by the Mississippi','公路摄影 / 摄影书',['沿密西西比河旅行拍摄人物、室内与地景。','作品通过序列而非单一事件构成美国社会肖像。'],'理解摄影书如何把松散图像组织成叙事的经典案例。')],images:[],sourceLabel:'Alec Soth 官方网站',sourceUrl:'https://alecsoth.com/photography/projects/sleeping-by-the-mississippi'},
{id:'roe-ethridge',name:'Roe Ethridge',born:'1969',base:'New York',intro:'在商业委托、时尚摄影、私人快照和艺术摄影之间循环使用图像，研究照片如何跨语境改变价值。',methods:['商业摄影挪用','再语境化','编辑','静物摄影','肖像'],subjects:['消费','图像流通','日常','时尚','作者性'],outputs:['摄影','摄影书','展览装置'],institutions:['MoMA','Whitney Museum'],achievements:['New Photography 2010 · MoMA'],whyImportant:'他模糊商业图像和艺术图像的等级，使同一套摄影语言可以在广告、杂志、家庭生活和美术馆之间迁移。',projects:[project('2000s–','Le Luxe / ongoing photographic practice','商业与私人图像混编',['将委托照片与个人照片并置。','通过重复和再编辑改变原图用途。'],'重点是图像进入不同制度后如何重新获得意义。')],images:[],sourceLabel:'MoMA',sourceUrl:'https://www.moma.org/artists/27384'},
{id:'collier-schorr',name:'Collier Schorr',born:'1963',base:'United States',intro:'以摄影、绘画与档案材料研究青春、性别表演、身份和历史记忆，长期在艺术摄影与时尚图像之间工作。',methods:['肖像','编排摄影','档案研究','文本与图像'],subjects:['性别','青春','身份','历史记忆','身体'],outputs:['摄影','摄影书','绘画','装置'],institutions:['MoMA','Whitney Museum'],achievements:['Whitney Biennial 2002'],whyImportant:'她让肖像成为身份表演而非固定分类，并把青年身体、历史图像与时尚摄影的观看机制联系起来。',projects:[project('1990s–2000s','Forest and Fields','肖像 / 历史与身份',['在德国南部长期拍摄青年与地方景观。','作品将当代肖像与历史、军装和民族身份的视觉记忆并置。'],'肖像中的身份被处理成可以被穿戴、表演和重新阅读的结构。')],images:[],sourceLabel:'MoMA',sourceUrl:'https://www.moma.org/artists/26675'},
{id:'paul-graham',name:'Paul Graham',born:'1956',base:'United Kingdom / United States',intro:'以彩色摄影把社会纪实从明确事件转向日常时间、微小动作与观看过程，影响了英国新彩色摄影及后续摄影书实践。',methods:['彩色纪实','序列摄影','摄影书','日常观察'],subjects:['社会阶级','失业','公共空间','时间','日常'],outputs:['摄影','摄影书'],institutions:['MoMA','Tate'],achievements:['Deutsche Börse Photography Prize 2009'],whyImportant:'他证明政治和社会结构不一定需要戏剧性事件来表现，也可以存在于等待、路边、办公室和身体微动作中。',projects:[project('2004–2006','a shimmer of possibility','摄影序列 / 日常时间',['在美国日常环境中拍摄微小事件。','以多张图像和时间间隔构成短篇视觉叙事。'],'把决定性瞬间改造成持续观看和时间展开。')],images:[],sourceLabel:'MoMA',sourceUrl:'https://www.moma.org/artists/2282'},
{id:'mitch-epstein',name:'Mitch Epstein',born:'1952',base:'New York',intro:'以大型彩色摄影长期研究美国社会、能源系统、公共空间与环境政治。',methods:['大画幅摄影','社会地景','长期研究','彩色摄影'],subjects:['能源','环境','美国社会','权力','基础设施'],outputs:['摄影','摄影书'],institutions:['MoMA','Whitney Museum','Tate'],achievements:['Prix Pictet 2011'],whyImportant:'他的实践把基础设施从背景提升为政治主体，让电厂、住宅、公共空间和环境后果在同一画面体系中出现。',projects:[project('2003–2009','American Power','社会地景 / 能源研究',['长期拍摄美国能源生产及其周边社区。','把工业基础设施与日常生活并置。'],'能源系统被视觉化为塑造景观、政治与生活的网络。')],images:[],sourceLabel:'Mitch Epstein 官方网站',sourceUrl:'https://mitchepstein.net/american-power'}
];