import type { Artist } from './data';
import { artistBatch142 } from './expansionBatch142';

export const artistBatch141: Artist[] = [
{id:'dayanita-singh',name:'Dayanita Singh',born:'1961',base:'India',intro:'印度摄影艺术家，以摄影书、档案和可移动的模块化展示结构重新思考照片如何被编辑、储存、出版与展览。',methods:['档案编辑','摄影书','模块化展示','图像再编排'],subjects:['档案','家庭','印度社会','记忆','摄影制度'],outputs:['摄影','摄影书','装置','档案'],institutions:['MoMA'],achievements:['Museum of Chance','Surrounds: 11 Installations — MoMA'],whyImportant:'Singh把摄影从单张图像推进到“如何让照片流动”的制度研究：书、墙、柜体和临时博物馆都成为摄影作品的一部分。',projects:[{year:'2013',title:'Museum of Chance',type:'摄影 / 模块化装置',facts:['MoMA收藏Museum of Chance。','作品进入MoMA 2019–20年的Surrounds: 11 Installations。'],reading:'照片不再拥有唯一固定顺序，而能够在不同展示结构中持续重组，挑战摄影展览和摄影书的边界。'}],images:[],sourceLabel:'MoMA · Dayanita Singh',sourceUrl:'https://www.moma.org/artists/48057-dayanita-singh'},
{id:'mikhael-subotzky',name:'Mikhael Subotzky',born:'1981',base:'South Africa',intro:'南非摄影与影像艺术家，以长期社会调查、肖像、建筑和空间序列研究监狱、城市隔离、暴力以及后种族隔离社会结构。',methods:['长期社会调查','建筑摄影','肖像','空间序列'],subjects:['监狱','城市','阶级','暴力','后种族隔离'],outputs:['摄影','影像','装置'],institutions:['MoMA'],achievements:['New Photography 2008 — MoMA','Beaufort West','Pollsmoor Prison'],whyImportant:'Subotzky把南非纪实摄影传统推进到空间和制度分析，让监狱、住宅、街道和人的身体共同显现社会结构。',projects:[{year:'2004–08',title:'Pollsmoor / Beaufort West',type:'长期摄影项目',facts:['MoMA收藏其Pollsmoor Maximum Security Prison与Beaufort West系列多件作品。','MoMA在2008年New Photography展中展出Subotzky。'],reading:'作品通过长期进入具体社区与制度空间，让社会问题从抽象政治概念变成建筑、人物与日常关系。'}],images:[],sourceLabel:'MoMA · Mikhael Subotzky',sourceUrl:'https://www.moma.org/artists/30365-mikhael-subotzky'},
{id:'doris-salcedo',name:'Doris Salcedo',born:'1958',base:'Colombia',intro:'哥伦比亚艺术家，以雕塑、装置、建筑介入和证词研究回应失踪、政治暴力、哀悼、殖民主义与社会创伤。',methods:['证词研究','物件转化','反纪念碑','建筑介入'],subjects:['失踪','政治暴力','哀悼','殖民主义','社会创伤'],outputs:['雕塑','装置','公共艺术','建筑介入'],institutions:['Guggenheim','MoMA','Tate'],achievements:['Doris Salcedo — Guggenheim 2015','Shibboleth','Atrabiliarios'],whyImportant:'Salcedo避免直接再现暴行，而把受害者证词和家具、鞋、头发、花瓣等材料转化为关于缺席和哀悼的空间经验，是当代反纪念碑实践的重要节点。',projects:[{year:'1991–96',title:'Atrabiliarios',type:'墙面装置',facts:['Guggenheim将其列为Salcedo早期重要系列。','MoMA收藏相关作品，材料包括鞋、动物膜与手术线，鞋作为失踪者的替代性痕迹。'],reading:'作品不展示暴力发生的瞬间，而通过日常物件留下的空缺让失踪持续存在于观看现场。'}],images:[],sourceLabel:'Guggenheim · Doris Salcedo',sourceUrl:'https://www.guggenheim.org/artwork/artist/doris-salcedo'},
{id:'otobong-nkanga',name:'Otobong Nkanga',born:'1974',base:'Nigeria / Belgium',intro:'尼日利亚出生、比利时工作的跨媒介艺术家，以绘画、织物、装置、雕塑与表演研究矿物、土地、资源开采、贸易网络、生态与殖民历史。',methods:['材料研究','资源链追踪','生态叙事','跨媒介装置'],subjects:['矿物','土地','开采','贸易','殖民主义','生态'],outputs:['装置','织物','雕塑','绘画','表演'],institutions:['La Biennale di Venezia'],achievements:['Biennale Arte 2019','Biennale Arte 2026 Central Pavilion'],whyImportant:'Nkanga把矿石、植物、商品和人的移动放在同一关系网络中，使全球贸易与殖民史通过材料自身的路径变得可感。',projects:[{year:'2019–26',title:'Material and ecological installations',type:'装置 / 雕塑 / 织物',facts:['La Biennale 2019指出其作品持续处理矿物、能源、商品与人的移动和交换。','2026威尼斯双年展中央馆中，她使用当地砖、植物、石材与Murano玻璃构造人与自然相遇的空间。'],reading:'材料并非被动媒介，而是携带地质时间、劳动、贸易与殖民交换历史的行动者。'}],images:[],sourceLabel:'La Biennale di Venezia · Otobong Nkanga',sourceUrl:'https://www.labiennale.org/en/art/2026/otobong-nkanga'},
{id:'hito-steyerl',name:'Hito Steyerl',born:'1966',base:'Germany',intro:'德国艺术家、电影作者与理论家，以论文电影、数字影像和沉浸式装置研究图像流通、战争技术、监控、人工智能、资本与网络视觉文化。',methods:['论文电影','档案蒙太奇','数字图像研究','推测性叙事'],subjects:['图像政治','人工智能','战争','监控','资本','互联网'],outputs:['影像','装置','文本','数字媒体'],institutions:['MoMA','La Biennale di Venezia','documenta'],achievements:['How Not to Be Seen','In Free Fall','Biennale Arte 2019'],whyImportant:'Steyerl把“数字图像如何生产和流通”本身变成艺术对象，是连接当代艺术、网络文化、影像理论和AI政治最关键的艺术家之一。',projects:[{year:'2013',title:'How Not to Be Seen: A Fucking Didactic Educational .MOV File',type:'影像 / 数字媒体',facts:['MoMA收藏该作品，并将Steyerl与纪录电影、表演和影像实践关联。','其作品持续混合纪录方法、推测小说与第一人称叙事来研究网络化数字社会。'],reading:'她不是单纯使用新技术，而是追问技术决定谁可见、图像怎样流通以及视觉制度如何参与权力生产。'}],images:[],sourceLabel:'MoMA · Hito Steyerl',sourceUrl:'https://www.moma.org/artists/43752-hito-steyerl'},
{id:'dinh-q-le',name:'Dinh Q. Lê',born:'1968–2024',base:'Vietnam / United States',intro:'越南裔美国艺术家，以摄影编织、档案、影像与装置研究越南战争、集体记忆、好莱坞图像以及个人记忆和官方历史之间的冲突。',methods:['摄影编织','档案重组','记忆蒙太奇','合作影像'],subjects:['越南战争','记忆','历史','媒体图像','迁徙'],outputs:['摄影','装置','影像','编织图像'],institutions:['MoMA','MoMA PS1'],achievements:['Projects 93: Dinh Q. Lê — MoMA','The Farmers and The Helicopters'],whyImportant:'Lê把新闻、电影和私人照片切割后重新编织，使相互竞争的历史图像在同一表面发生冲突，成为东南亚记忆政治的重要实践。',projects:[{year:'2006',title:'The Farmers and The Helicopters',type:'影像装置 / 合作项目',facts:['作品由Dinh Q. Lê与多位越南艺术家合作完成并进入MoMA收藏。','MoMA于2010–11年举办Projects 93: Dinh Q. Lê。'],reading:'战争不再只有官方档案或美国电影的单一视觉版本，而被当地记忆、技术物件和多重叙事重新组织。'}],images:[],sourceLabel:'MoMA · Dinh Q. Lê',sourceUrl:'https://www.moma.org/artists/26740-dinh-q-le'},
...artistBatch142
];