import type { Artist } from './data';
import { artistBatch145 } from './expansionBatch145';

export const artistBatch144: Artist[] = [
{id:'mame-diarra-niang',name:'Mame-Diarra Niang',born:'1982',base:'France / Senegal / Côte d’Ivoire',intro:'法国出生、具有塞内加尔与科特迪瓦背景的摄影、影像与表演艺术家，从城市空间、迁徙经验和黑人身体出发，逐渐把摄影推向模糊、抽象与“非肖像”，研究身份如何由记忆、遗忘与外部凝视共同塑造。',methods:['抽象摄影','非肖像','城市漫游','身体与空间研究'],subjects:['身份','黑人身体','记忆','城市','迁徙','自我建构'],outputs:['摄影','影像','表演','摄影书'],institutions:['MoMA','Centre Pompidou'],achievements:['Sama Guent Guii','The Citadel'],whyImportant:'Niang把关于非洲城市和黑人身体的摄影从地理记录推进到抽象、自我与感知问题，是连接非洲城市摄影、摄影书与当代抽象摄影的重要节点。',projects:[{year:'2021',title:'Sama Guent Guii',type:'抽象摄影 / 非肖像',facts:['MoMA收藏该系列多件作品，并于2025–26在馆藏展212: What Is Parasite and What Is Kin?中展出。','艺术家把这些模糊人物称为non-portraits，以抽象处理不断变化的自我。'],reading:'身体不再被固定成可识别身份，而成为记忆、擦除和外部凝视不断重组的场域。'}],images:[],sourceLabel:'MoMA · Mame-Diarra Niang',sourceUrl:'https://www.moma.org/artists/136899-mame-diarra-niang'},
{id:'sohrab-hura',name:'Sohrab Hura',born:'1981',base:'India',intro:'印度艺术家，从纪实摄影出发扩展至电影、绘画、素描、写作与艺术家书，持续质疑摄影的证据性、观看他人痛苦的伦理，以及图像在宣传、社交媒体和个人记忆中的多重生命。',methods:['反纪实实践','图像再循环','摄影书编排','跨媒介叙事'],subjects:['家庭','暴力','克什米尔','媒体宣传','图像政治','记忆'],outputs:['摄影','电影','绘画','素描','写作','摄影书'],institutions:['MoMA PS1','MoMA','Aperture'],achievements:['Sohrab Hura: Mother','The Coast','Aperture PhotoBook of the Year 2019'],whyImportant:'Hura把纪实摄影内部的伦理危机转化为方法：重复、故障、挪用和跨媒介再编排使同一图像不断改变意义，是南亚后纪实与图像政治的重要实践。',projects:[{year:'2013–20',title:'The Coast',type:'摄影 / 影像 / 艺术家书',facts:['Aperture的2019 PhotoBook Awards将The Coast评为PhotoBook of the Year。','项目以印度南端宗教节庆为起点，通过重复、虚构短篇与不安的影像序列质疑所谓完美图像及纪实真实性。'],reading:'摄影不再只是记录事件，而成为检验暴力、叙事和观看者如何共同制造现实感的装置。'}],images:[],sourceLabel:'Aperture · Sohrab Hura',sourceUrl:'https://aperture.org/editorial/for-sohrab-hura-photography-is-a-way-of-feeling-visible/'},
{id:'sarker-protick',name:'Sarker Protick',born:'1986',base:'Bangladesh',intro:'孟加拉摄影与影像艺术家、音乐人和教育者，以长期研究、摄影、影像与声音处理河流侵蚀、家庭记忆、殖民铁路、孟加拉分治及资源开采，关注时间如何沉积在地景和建筑遗迹中。',methods:['长期地景研究','历史档案关联','长曝光摄影','声音与影像编排'],subjects:['时间','记忆','孟加拉','殖民主义','河流','铁路','生态'],outputs:['摄影','影像','声音','装置'],institutions:['Foam','Chobi Mela','C/O Berlin'],achievements:['Foam Talent 2021','Awngar','Leen'],whyImportant:'Protick以极安静的视觉语言连接河流、废墟、铁路和煤矿，把摄影的时间性与孟加拉殖民及后殖民历史结合，是南亚研究型地景摄影的重要节点。',projects:[{year:'2022–25',title:'Awngar (Ash to Ash)',type:'摄影 / 影像 / 历史研究',facts:['Foam介绍该项目通过铁路、煤矿和工业遗迹追踪英国殖民时期基础设施与资源开采的持续后果。','项目在2025年于C/O Berlin展出。'],reading:'铁路既是现代化基础设施，也是帝国资源抽取留下的空间骨架；静止地景因此成为殖民历史仍在现在运作的证据。'}],images:[],sourceLabel:'Foam · Sarker Protick — AWNGAR',sourceUrl:'https://www.foam.org/articles/from-the-archive-sarker-protick'},
{id:'namsa-leuba',name:'Namsa Leuba',born:'1982',base:'Switzerland / Guinea',intro:'瑞士—几内亚摄影艺术家，以高度编排的肖像、服装、色彩和身体姿态研究非洲身份、仪式、时尚及西方观看方式，主动让艺术摄影、时尚摄影与人类学式表征发生冲突。',methods:['编排肖像','时尚语言挪用','仪式再语境化','色彩与身体造型'],subjects:['黑人身体','非洲身份','仪式','时尚','西方凝视','表征'],outputs:['摄影','时尚影像','装置'],institutions:['Aperture','Rencontres d’Arles'],achievements:['The New Black Vanguard','Ya Kala Ben'],whyImportant:'Leuba把非洲仪式与时尚图像的视觉机制放在同一舞台上，既利用又扰动西方观看黑人身体的传统，是当代黑人时尚摄影进入艺术机构网络的重要代表。',projects:[{year:'2011–ongoing',title:'Ya Kala Ben',type:'编排摄影',facts:['Aperture指出该系列把几内亚村落的驱邪和仪式性元素转化为具有表演感的编排图像。','Leuba也是Aperture策划的The New Black Vanguard核心十五位摄影师之一。'],reading:'作品故意让仪式、时尚和西方审美相互摩擦，使“非洲身份”不再是被动的人类学对象，而成为主动建构的视觉表演。'}],images:[],sourceLabel:'Aperture · Namsa Leuba',sourceUrl:'https://aperture.org/editorial/armory-namsa-leuba/'},
{id:'monica-de-miranda',name:'Mónica de Miranda',born:'1976',base:'Portugal / Angola',intro:'葡萄牙—安哥拉艺术家与研究者，以摄影、影像、装置、档案、植物和参与式实践研究殖民历史、迁徙、土地、生态与黑人主体，并把花园和土壤转化为记忆、教育与集体行动空间。',methods:['研究型艺术','活档案','生态装置','参与式实践'],subjects:['殖民主义','迁徙','土地','生态','黑人主体','记忆','边界'],outputs:['摄影','影像','装置','雕塑','表演','档案'],institutions:['La Biennale di Venezia — Portugal Pavilion'],achievements:['Greenhouse — Portugal Pavilion 2024','Creole Garden'],whyImportant:'de Miranda把后殖民摄影研究进一步扩展为生态、教育和集体行动，将土壤本身作为帝国暴力、迁徙轨迹与抵抗历史的载体。',projects:[{year:'2024',title:'Greenhouse',type:'装置 / 活档案 / 集体项目',facts:['Mónica de Miranda与Sónia Vaz Borges、Vânia Gala共同代表葡萄牙参加第60届威尼斯双年展。','La Biennale将项目概括为Garden、Living Archive、Schools与Assemblies四个行动，并以土壤、土地、边界、迁徙身体和帝国记忆为核心。'],reading:'花园不只是生态隐喻，而成为历史研究、身体实践、教育和公共集会同时发生的反殖民基础设施。'}],images:[],sourceLabel:'La Biennale di Venezia · Portugal 2024',sourceUrl:'https://www.labiennale.org/en/art/2024/portugal'},
{id:'poulomi-basu',name:'Poulomi Basu',born:'1983',base:'India / United Kingdom',intro:'印度跨媒介艺术家、摄影师与行动者，以摄影、电影、装置、拼贴、VR/MR和表演研究身体与权力系统，长期关注南亚女性、原住民社群、战争、月经政治、生态与性别正义。',methods:['视觉行动主义','跨媒介纪实','虚构与纪实混合','沉浸式叙事'],subjects:['性别','身体政治','战争','原住民','生态','南亚','权力结构'],outputs:['摄影','电影','装置','VR','MR','拼贴','表演'],institutions:['Victoria and Albert Museum','Rencontres d’Arles','Autograph'],achievements:['Centralia','Blood Speaks','Rencontres d’Arles Discovery Award Jury Prize 2020'],whyImportant:'Basu把社会纪实转化为摄影、电影、沉浸技术和行动主义共同工作的系统，代表当代摄影从“见证”进一步进入政策介入、身体政治和推想叙事。',projects:[{year:'2010–20',title:'Centralia',type:'摄影 / 电影 / 摄影书 / docu-fiction',facts:['Centralia研究印度中部原住民社群与国家之间长期而少被报道的冲突，并有意识地混合现实与虚构。','该项目获得Rencontres d’Arles Discovery Award Jury Prize，并进入2021 Deutsche Börse Photography Foundation Prize短名单。'],reading:'项目拒绝把冲突压缩成单一新闻事实，而是用不稳定的真假关系讨论国家、宣传和摄影如何共同塑造“真实”。'}],images:[],sourceLabel:'Poulomi Basu · official',sourceUrl:'https://www.poulomibasu.com/about'},
...artistBatch145
];