import type { Artist } from './data';
import { artistBatch78 } from './expansionBatch78';

export const artistBatch77: Artist[] = [
  ...artistBatch78,
  {id:'sophie-calle',name:'Sophie Calle',born:'1953',base:'France',intro:'以摄影、文本、跟踪、规则和参与式行动把私人生活、亲密关系与观察伦理转化为叙事实验。',methods:['规则型实践','参与式行动','摄影与文本','自传叙事'],subjects:['私人生活','亲密关系','监视','缺席','记忆'],outputs:['摄影','文本','艺术家书','装置'],institutions:['MoMA'],achievements:['The Sleepers (Les dormeurs)','Exquisite Pain'],whyImportant:'Calle把生活事件、行为规则和摄影文本组合成作品，是当代摄影跨向概念艺术、自传与参与式实践的重要节点。',projects:[{year:'1979',title:'The Sleepers (Les dormeurs)',type:'摄影 / 行为 / 文本',facts:['邀请29人轮流在她的床上睡眠并进行摄影和问卷记录。','MoMA将该作置于其对公共与私人边界的持续研究中。'],reading:'作品把亲密空间转化为由规则组织的观察系统，使摄影同时成为证据、日记和行为记录。'}],images:[],sourceLabel:'MoMA · Sophie Calle',sourceUrl:'https://www.moma.org/artists/6655-sophie-calle'},
  {id:'rineke-dijkstra',name:'Rineke Dijkstra',born:'1959',base:'Netherlands',intro:'以正面、大画幅肖像和长期重复拍摄研究青春期、身份转变、母职与个体在镜头前的自我呈现。',methods:['类型学肖像','长期跟踪','正面凝视','重复拍摄'],subjects:['青春期','身份转变','母职','难民','个体性'],outputs:['摄影','录像'],institutions:['MoMA','Guggenheim'],achievements:['Beach Portraits','Almerisa series'],whyImportant:'Dijkstra在类型学的统一形式与个体细微差异之间建立张力，重塑了1990年代以来当代肖像摄影的观看方式。',projects:[{year:'1994–2008',title:'Almerisa',type:'长期肖像系列',facts:['持续拍摄一名从波斯尼亚来到荷兰的年轻难民Almerisa。','MoMA馆藏包含该系列多个时间节点。'],reading:'固定而克制的肖像结构让身份、身体和社会位置随时间发生的变化成为作品本身。'}],images:[],sourceLabel:'MoMA · Rineke Dijkstra',sourceUrl:'https://www.moma.org/artists/8139-rineke-dijkstra'},
  {id:'deana-lawson',name:'Deana Lawson',born:'1979',base:'United States',intro:'以高度编排的大画幅摄影研究黑人家庭、亲密关系、身体、灵性与跨大西洋黑人身份。',methods:['编排肖像','场景建构','扩展家庭相册','大画幅摄影'],subjects:['黑人身份','家庭','亲密关系','身体','灵性'],outputs:['摄影','装置'],institutions:['Whitney Museum','Guggenheim'],achievements:['Whitney Biennial 2017','Hugo Boss Prize 2020'],whyImportant:'Lawson把家庭快照的亲密感与严格场景建构结合，主动生产具有尊严、欲望与神圣性的黑人主体图像。',projects:[{year:'2015',title:'The Garden, Gemena, DR Congo',type:'编排摄影',facts:['在刚果民主共和国Gemena拍摄。','两位并非现实伴侣的被摄者被编排为近似伊甸园中的第一对人类。'],reading:'作品反转把非洲持续呈现为危机现场的视觉惯例，以亲密和神圣性重新组织黑人身体的观看。'}],images:[],sourceLabel:'Whitney · Deana Lawson',sourceUrl:'https://whitney.org/artists/17261'},
  {id:'akram-zaatari',name:'Akram Zaatari',born:'1966',base:'Lebanon',intro:'以摄影档案、录像、装置与再语境化研究黎巴嫩历史、战争记忆、影像流通和中东摄影史。',methods:['档案研究','再语境化','口述与影像史','拾得影像'],subjects:['黎巴嫩历史','战争','记忆','摄影史','影像流通'],outputs:['摄影','录像','装置','出版'],institutions:['MoMA','Arab Image Foundation'],achievements:['Projects 100: Akram Zaatari · MoMA 2013','Letter to a Refusing Pilot · 2013'],whyImportant:'作为Arab Image Foundation创办者之一，Zaatari把保存摄影档案与艺术实践结合，成为中东影像史、记忆政治和档案转向的关键人物。',projects:[{year:'2013',title:'Letter to a Refusing Pilot',type:'录像 / 装置',facts:['作品进入MoMA艺术家档案。','围绕战争、个人记忆与历史叙述展开。'],reading:'Zaatari不把档案视为固定证据，而通过重新编排影像与叙事揭示历史如何被记住和重构。'}],images:[],sourceLabel:'MoMA · Akram Zaatari',sourceUrl:'https://www.moma.org/artists/41278-akram-zaatari'},
  {id:'ibrahim-mahama',name:'Ibrahim Mahama',born:'1987',base:'Ghana',intro:'以旧黄麻袋、铁路材料、档案和大型建筑介入研究劳动、商品流通、殖民基础设施与加纳现代史。',methods:['材料再利用','大型建筑介入','社会协作','档案研究'],subjects:['劳动','殖民主义','贸易','基础设施','加纳历史'],outputs:['装置','建筑介入','档案','绘画'],institutions:['La Biennale di Venezia','The Whitworth'],achievements:['Ghana Pavilion · Biennale Arte 2019','Parliament of Ghosts'],whyImportant:'Mahama把承载可可与商品运输历史的材料扩展为纪念性空间，使全球贸易、劳动痕迹和殖民基础设施成为可进入的物质档案。',projects:[{year:'2019',title:'Parliament of Ghosts',type:'大型装置 / 建筑',facts:['最初为The Whitworth与Manchester International Festival构想。','2023威尼斯建筑双年展官方页面指出作品涉及殖民剥削与Gold Coast Railway遗存。'],reading:'废弃材料和现代主义基础设施残片被重新组织为公共空间，让国家现代化的幽灵历史进入当下。'}],images:[],sourceLabel:'La Biennale di Venezia · Ibrahim Mahama',sourceUrl:'https://www.labiennale.org/en/architecture/2023/force-majeure/ibrahim-mahama'}
];
