import type { Artist } from './data';
import { artistBatch129 } from './expansionBatch129';

export const artistBatch128: Artist[] = [
{id:'deana-lawson',name:'Deana Lawson',born:'1979',base:'USA',intro:'美国摄影艺术家，以中大画幅摄影在家庭室内、街区与跨大西洋黑人离散社群中构造高度编排又保留生活质感的肖像，研究身体、亲密关系、仪式、家庭与黑人视觉文化。',methods:['编排肖像','中大画幅摄影','亲密空间研究','黑人视觉文化'],subjects:['黑人生活','家庭','身体','亲密关系','仪式','离散'],outputs:['摄影','摄影书','装置'],institutions:['Aperture','Whitney Museum','MoMA'],achievements:['Deana Lawson: An Aperture Monograph','2018 Whitney Biennial','Being: New Photography 2018'],whyImportant:'Lawson把纪实传统与导演式场景结合，使黑人家庭空间、身体和日常物件同时成为现实生活与象征结构；她是当代编排肖像和黑人摄影的重要节点。',projects:[{year:'2015',title:'The Garden',type:'编排肖像摄影',facts:['作品属于Lawson持续发展的亲密肖像语言。','Aperture指出她使用中大画幅相机并通过环境、姿态、物件与衣着构造高度结构化的场景。'],reading:'肖像并非透明记录，而是在真实关系与导演式安排之间形成关于黑人主体性的视觉空间。'}],images:[],sourceLabel:'Aperture · Deana Lawson',sourceUrl:'https://aperture.org/event/deana-lawson-at-dover-street-market/'},
{id:'daisuke-yokota',name:'Daisuke Yokota',born:'1983',base:'Japan',intro:'日本实验摄影艺术家，以反复复制、扫描、暗房处理、无相机摄影和材料实验改变影像，使摄影从单一图像扩展成纸张、胶片、化学反应、装置与表演。',methods:['暗房实验','图像再处理','无相机摄影','材料实验'],subjects:['摄影物质性','记忆','时间','图像退化','复制'],outputs:['摄影','摄影书','装置','录像','行为'],institutions:['Foam'],achievements:['Foam Talent 2013','Foam Paul Huf Award 2016','Matter — Foam 2017'],whyImportant:'Yokota继承又推进Provoke之后日本实验摄影传统，把复制误差、化学过程和摄影材料本身变成作品，是理解后数码时代摄影物质性的重要节点。',projects:[{year:'2017',title:'Matter',type:'摄影 / 装置',facts:['Foam展览由三个强调摄影触觉和材料性的装置组成。','其中包括直接曝光胶卷形成的长幅打印以及非常规暗房化学实验。'],reading:'摄影不再只是图像，而成为可以被曝光、打印、打蜡、悬挂和持续改变的物质。'}],images:[],sourceLabel:'Foam · Daisuke Yokota',sourceUrl:'https://www.foam.org/events/daisuke-yokota'},
{id:'cristina-de-middel',name:'Cristina de Middel',born:'1975',base:'Spain / Brazil',intro:'西班牙摄影艺术家，以摄影、档案、虚构叙事和自制道具质疑新闻摄影的真实性机制及西方对非洲等地区的刻板视觉叙事。',methods:['虚构纪实','编排摄影','档案重构','摄影书叙事'],subjects:['新闻摄影','非洲再现','历史','虚构与真实','殖民凝视'],outputs:['摄影','摄影书','装置','档案'],institutions:['Foam','Magnum Photos'],achievements:['The Afronauts','Foam exhibition 2013'],whyImportant:'De Middel把真实历史材料与明显虚构的摄影场景并置，使“纪实摄影是否天然真实”本身成为作品主题，是当代摄影从报道向推想叙事转向的重要案例。',projects:[{year:'2012–2013',title:'The Afronauts',type:'摄影 / 档案 / 摄影书',facts:['项目取材于1964年赞比亚曾提出的太空计划。','Foam指出作品将编排摄影、打字信件复制件与老照片复制品结合。'],reading:'作品用想象完成一段失败的历史，同时反问西方新闻图像如何生产关于非洲的单一叙事。'}],images:[],sourceLabel:'Foam · Cristina De Middel',sourceUrl:'https://www.foam.org/events/cristina-de-middel'},
{id:'awoiska-van-der-molen',name:'Awoiska van der Molen',born:'1972',base:'Netherlands',intro:'荷兰摄影艺术家，长期独自在偏远自然环境中缓慢工作，以大幅手工银盐黑白照片研究黑暗、光、时间和非人的景观经验。',methods:['长期景观摄影','缓慢观察','暗房手工放印','单色摄影'],subjects:['自然','黑暗','孤独','时间','感知'],outputs:['摄影','摄影书','银盐放印'],institutions:['Foam'],achievements:['Blanco — Foam 2016','Deutsche Börse Photography Prize nominee 2017','Sequester'],whyImportant:'Van der Molen代表当代摄影中与快速数字生产相反的一条路线：长期进入地点并通过暗房和深黑银盐影调，让景观成为关于时间和感知的经验，而非地理记录。',projects:[{year:'2016',title:'Blanco',type:'摄影展 / 长期景观项目',facts:['Foam将其称为艺术家的首个大型博物馆个展。','展览集中呈现她的大幅手工银盐照片，作品来自长期独处和反复进入偏远景观的过程。'],reading:'极少的人类痕迹与深黑影调让观看从辨认地点转向感受时间、光线和空间。'}],images:[],sourceLabel:'Foam · Awoiska van der Molen',sourceUrl:'https://www.foam.org/events/awoiska-van-der-molen'},
{id:'bieke-depoorter',name:'Bieke Depoorter',born:'1986',base:'Belgium',intro:'比利时摄影师与艺术家，以长期进入陌生人的私人空间、共同编辑和持续回访的方法研究摄影者与被摄者之间的关系、同意、作者权和纪实摄影伦理。',methods:['长期纪实','亲密协作','共同编辑','摄影书实践'],subjects:['陌生人','家庭空间','亲密关系','作者权','纪实伦理'],outputs:['摄影','摄影书','出版'],institutions:['Foam','Magnum Photos','Aperture'],achievements:['Magnum full member 2016','Ou Menya','As it May Be','Agata'],whyImportant:'Depoorter把摄影者与被摄者之间的关系本身推到作品中心，使纪实摄影不只是获取图像，而成为持续协商、反馈和共同建构意义的过程。',projects:[{year:'2011–2017',title:'As it May Be',type:'摄影 / 参与式编辑 / 摄影书',facts:['Depoorter长期以亲密进入家庭和陌生人生活的方式工作。','Foam记录其出版包括Ou Menya、I am About to Call it a Day、As it May Be与Agata。'],reading:'作品的重要性不只在照片内容，也在摄影者如何获得进入私人生活的许可，以及被摄者如何重新回应图像。'}],images:[],sourceLabel:'Foam · Bieke Depoorter',sourceUrl:'https://www.foam.org/artists/bieke-depoorter'},
{id:'paul-mpagi-sepuya',name:'Paul Mpagi Sepuya',born:'1982',base:'USA',intro:'美国摄影艺术家，以工作室镜面、相机、旧照片、布料与亲密关系构造单次曝光中的碎片化肖像，研究酷儿凝视、欲望、摄影工作室和图像生产过程。',methods:['镜面构图','碎片化肖像','工作室自反','协作肖像'],subjects:['酷儿身份','欲望','观看','亲密关系','摄影工作室'],outputs:['摄影','摄影书','装置'],institutions:['Foam','Aperture','MoMA','Whitney Museum','Guggenheim Museum'],achievements:['Double Enclosure — Foam 2018','Being: New Photography 2018','2019 Whitney Biennial','Dark Room A–Z'],whyImportant:'Sepuya让镜子、相机、摄影者身体和旧照片同时进入画面，使肖像既表现亲密社群，也揭示摄影观看本身如何被建构，是当代酷儿摄影的重要节点。',projects:[{year:'2016–2021',title:'Dark Room',type:'工作室摄影系列',facts:['Aperture将该系列描述为建立在协作式、网络化的工作室与肖像实践之上。','Foam指出Sepuya常把镜子、旧照片、身体碎片和相机在镜头前组合，并非依赖数字拼贴。'],reading:'摄影工作室不再隐藏在最终图像之后，而成为关系、欲望和观看权力被公开展示的现场。'}],images:[],sourceLabel:'Aperture · Paul Mpagi Sepuya',sourceUrl:'https://aperture.org/press-release/paul-sepuya-dark-room-a-z/'},
...artistBatch129
];