import type { Artist } from './data';
import { artistBatch75 } from './expansionBatch75';

export const artistBatch74: Artist[] = [
  ...artistBatch75,
  {id:'martha-rosler',name:'Martha Rosler',born:'1943',base:'United States',intro:'以摄影蒙太奇、录像、文本与装置批判战争图像、家庭空间、性别角色与媒体政治。',methods:['摄影蒙太奇','制度批判','录像实践','文本研究'],subjects:['战争','媒体','家庭空间','女性主义','城市'],outputs:['摄影','拼贴','录像','装置','文本'],institutions:['MoMA'],achievements:['MoMA collection','Signals: How Video Transformed the World · MoMA 2023'],whyImportant:'Rosler把大众媒体图像与日常家庭空间直接碰撞，是女性主义艺术、政治摄影蒙太奇和媒体批判的重要节点。',projects:[{year:'c.1967–72',title:'House Beautiful: Bringing the War Home',type:'摄影蒙太奇',facts:['将越战新闻图像与美国室内家居杂志图像并置。','MoMA收藏该系列多件作品。'],reading:'把遥远战争重新嵌入消费社会的家庭内部，揭示媒体观看与政治距离。'}],images:[],sourceLabel:'MoMA · Martha Rosler',sourceUrl:'https://www.moma.org/artists/6832-martha-rosler'},
  {id:'cao-fei',name:'Cao Fei',born:'1978',base:'China',intro:'以录像、虚拟世界、网络项目与装置研究中国城市化、工厂劳动、青年亚文化及数字身份。',methods:['录像研究','虚拟世界建构','社会观察','数字叙事'],subjects:['城市化','劳动','青年文化','虚拟身份','中国'],outputs:['录像','装置','网络艺术','摄影'],institutions:['MoMA','MoMA PS1','La Biennale di Venezia'],achievements:['Cao Fei · MoMA PS1 2016','56th Venice Biennale · 2015'],whyImportant:'曹斐连接中国高速现代化与互联网虚拟空间，是理解中国当代影像、数字身份和后互联网实践的重要人物。',projects:[{year:'2006',title:'Whose Utopia',type:'录像',facts:['作品拍摄珠三角工厂环境与工人的个人愿望。','MoMA收藏并于2020–21设置专题展厅。'],reading:'工业生产线与工人的想象并置，使全球制造体系中的个体经验进入影像。'}],images:[],sourceLabel:'MoMA · Cao Fei',sourceUrl:'https://www.moma.org/artists/35159-cao-fei'},
  {id:'jeff-wall',name:'Jeff Wall',born:'1946',base:'Canada',intro:'以大型灯箱摄影和高度编排的场景重新连接摄影、电影、绘画史与日常生活，并提出“near documentary”等方法。',methods:['编排摄影','大型灯箱','历史图像重演','近纪实'],subjects:['日常生活','城市','绘画史','叙事','社会关系'],outputs:['摄影','灯箱装置'],institutions:['MoMA'],achievements:['Jeff Wall · MoMA 2007'],whyImportant:'Wall把摄影推进到电影制作与历史绘画式场景建构的尺度，对当代编排摄影及摄影与绘画关系影响深远。',projects:[{year:'1999–2000',title:'After “Invisible Man” by Ralph Ellison, the Prologue',type:'编排摄影 / 灯箱',facts:['依据Ralph Ellison小说序章构造场景。','作品进入MoMA馆藏。'],reading:'文学、电影布景与摄影在单一大型图像中结合，使摄影成为精密建构的叙事空间。'}],images:[],sourceLabel:'MoMA · Jeff Wall',sourceUrl:'https://www.moma.org/artists/7826-jeff-wall'},
  {id:'andreas-gursky',name:'Andreas Gursky',born:'1955',base:'Germany',intro:'以大尺幅、高视点和数字处理摄影观察全球资本、消费、建筑、物流与群体空间。',methods:['大尺幅摄影','高视点','数字图像处理','空间类型学'],subjects:['全球化','消费','资本','建筑','群体'],outputs:['摄影'],institutions:['MoMA'],achievements:['Andreas Gursky · MoMA 2001','MoMA collection'],whyImportant:'Gursky把全球资本主义的巨大空间结构转化为可被整体观看的摄影表面，是杜塞尔多夫摄影谱系和大型当代摄影的核心人物。',projects:[{year:'1999',title:'Rhine II',type:'摄影',facts:['作品创作于1999年。','MoMA艺术家档案列有该作品。'],reading:'通过严格的水平结构和图像处理，将现实风景转化为关于秩序、尺度与摄影建构性的图像。'}],images:[],sourceLabel:'MoMA · Andreas Gursky',sourceUrl:'https://www.moma.org/artists/7806-andreas-gursky'},
  {id:'allan-sekula',name:'Allan Sekula',born:'1951–2013',base:'United States',intro:'以摄影、文本、电影和长期研究追踪港口、海运、劳动与全球资本流动，持续批判传统纪实摄影与摄影档案制度。',methods:['摄影论文','长期调查','批判纪实','摄影与文本'],subjects:['劳动','海运','全球化','港口','资本'],outputs:['摄影','文本','电影','装置'],institutions:['MoMA','MoMA PS1'],achievements:['Fish Story','Allan Sekula: Geography Lesson · MoMA PS1 1987'],whyImportant:'Sekula把摄影从单张纪实图像扩展为政治经济研究和摄影论文，是研究型摄影、劳动影像与全球物流视觉研究的关键先驱。',projects:[{year:'1988–95',title:'Fish Story',type:'摄影 / 文本研究',facts:['长期拍摄港口、船舶、造船工人与海运基础设施。','MoMA收藏该系列多件作品。'],reading:'以海洋运输揭示全球资本看似不可见的物质基础和劳动网络。'}],images:[],sourceLabel:'MoMA · Allan Sekula',sourceUrl:'https://www.moma.org/artists/31040-allan-sekula'}
];
