import type { Artist } from './data';

const project = (year:string,title:string,type:string,facts:string[],reading:string) => ({year,title,type,facts,reading});

export const artistBatch39: Artist[] = [
 {id:'teresa-margolles',name:'Teresa Margolles',born:'1963',base:'Mexico City',intro:'以法医经验、现场研究和物质痕迹处理墨西哥及跨国暴力，把死亡现场的残余转化为摄影、雕塑和场域装置。',methods:['法医研究','场域研究','物质取样','社会参与','纪念性装置'],subjects:['暴力','边境','失踪','女性谋杀','迁徙','公共记忆'],outputs:['装置','雕塑','摄影','录像','行为'],institutions:['MoMA','MoMA PS1','Venice Biennale'],achievements:['MoMA PS1 · En el lugar de los hechos 2026–2027','Mexico Pavilion · Venice Biennale 2009'],whyImportant:'她把纪念从象征性再现转向暴力留下的真实物质痕迹，使摄影与装置成为追踪结构性暴力、失踪和公共记忆的研究工具。',projects:[project('2016','Pista de Baile','摄影 / 城市暴力档案',['在被拆除的跨性别夜生活场所遗址上制作肖像。','作品进入 MoMA 摄影收藏。'],'人物、建筑遗迹和城市暴力被压在同一图像中。')],images:[],sourceLabel:'MoMA',sourceUrl:'https://www.moma.org/artists/72286-teresa-margolles'},
 {id:'oscar-munoz',name:'Oscar Muñoz',born:'1951',base:'Cali',intro:'持续让肖像在水、热、灰尘和易逝表面上出现与消失，以摄影过程研究记忆、死亡与图像的不稳定性。',methods:['实验摄影','丝网印刷','易逝材料','过程艺术','影像'],subjects:['记忆','死亡','肖像','消失','时间','再现'],outputs:['摄影','装置','录像','版画'],institutions:['MoMA','Lugar a Dudas'],achievements:['作品进入 MoMA 收藏','2005 年创办 Lugar a Dudas'],whyImportant:'他把摄影从固定图像变成持续生成和消失的事件，是拉丁美洲实验摄影中连接材料、时间与记忆的重要节点。',projects:[project('1994–ongoing','Narcisos','过程摄影 / 水面图像',['肖像图像在水和材料变化中逐渐变形、沉积。','MoMA 收藏 Narcisos in Progress 及 Dried Narcissus。'],'图像的消失并非损坏，而是作品讨论记忆和死亡的核心机制。')],images:[],sourceLabel:'MoMA',sourceUrl:'https://www.moma.org/artists/41797-oscar-munoz'},
 {id:'hoda-afshar',name:'Hoda Afshar',born:'1983',base:'Melbourne',intro:'伊朗出生、澳大利亚工作的摄影与影像艺术家，通过合作式肖像和长期研究质疑摄影在殖民、国家控制与可见性政治中的作用。',methods:['合作式摄影','研究型摄影','编排肖像','录像','摄影伦理'],subjects:['迁徙','难民','酷儿身份','殖民观看','国家暴力','可见性'],outputs:['摄影','录像','摄影书','装置'],institutions:['Art Gallery of New South Wales'],achievements:['Art Gallery of NSW 收藏'],whyImportant:'她不是简单替边缘群体制造“可见性”，而是持续追问谁有权观看、哪些信息应该隐藏，以及相机本身如何参与权力关系。',projects:[project('2016','Behold','摄影 / 酷儿空间',['在伊朗一处浴室与寻求庇护的同性恋男性合作拍摄。','通过背向镜头、蒸汽和颗粒控制身份暴露。'],'作品把摄影伦理直接变成画面的可见与不可见结构。')],images:[],sourceLabel:'Art Gallery of New South Wales',sourceUrl:'https://www.artgallery.nsw.gov.au/collection/works/6.2024.1/'},
 {id:'latifa-echakhch',name:'Latifa Echakhch',born:'1974',base:'Vevey / Martigny',intro:'摩洛哥出生的法瑞艺术家，以现成物、绘画、声音和空间装置拆解民族象征、政治图像与集体记忆。',methods:['场域装置','现成物','绘画','声音','解构'],subjects:['记忆','民族身份','政治象征','迁徙','时间','集体经验'],outputs:['装置','雕塑','绘画','声音'],institutions:['Venice Biennale','Swiss Pavilion'],achievements:['Swiss Pavilion · Venice Biennale 2022'],whyImportant:'她常从熟悉的政治或文化符号出发，再通过破坏、空置和空间编排让符号失去原来的确定意义。',projects:[project('2022','The Concert','Swiss Pavilion / 空间装置',['为第59届威尼斯双年展瑞士馆创作。','结合短暂性雕塑、编排灯光与 Alexandre Babel 的节奏结构。'],'展览把时间、身体、声音和毁坏组织成一个整体环境。')],images:[],sourceLabel:'La Biennale di Venezia',sourceUrl:'https://www.labiennale.org/en/art/2022/switzerland'},
 {id:'shadi-ghadirian',name:'Shadi Ghadirian',born:'1974',base:'Tehran',intro:'以编排摄影把伊朗历史视觉语言与当代日常物件并置，讨论女性身份、现代性和社会角色。',methods:['编排摄影','肖像','历史图像挪用','静物'],subjects:['女性','伊朗','现代性','身份','日常生活'],outputs:['摄影','摄影系列'],institutions:['Victoria and Albert Museum','British Museum'],achievements:['作品进入多家国际公共收藏'],whyImportant:'她以极清晰的视觉冲突连接传统肖像格式和当代生活，使伊朗女性经验避免被单一的西方新闻图像框架定义。',projects:[project('1998–1999','Qajar','编排肖像',['借用卡扎尔时期摄影棚肖像语言。','人物同时携带自行车、收音机等现代物件。'],'时代错置让现代性、传统和女性角色同时进入一张照片。')],images:[],sourceLabel:'Shadi Ghadirian official website',sourceUrl:'https://shadighadirian.com/'},
 {id:'emily-jacir',name:'Emily Jacir',born:'1972',base:'Mediterranean / Palestine',intro:'以摄影、录像、文本、行动和档案研究巴勒斯坦的迁徙、行动自由、失去的地点与历史记忆。',methods:['研究型艺术','档案','摄影','录像','参与式行动'],subjects:['巴勒斯坦','迁徙','边界','记忆','行动自由','流亡'],outputs:['摄影','录像','装置','文本','行为'],institutions:['Venice Biennale','Guggenheim'],achievements:['Golden Lion for an artist under 40 · Venice Biennale 2007','Hugo Boss Prize 2008'],whyImportant:'她把政治限制转化为具体行动规则和个人叙述，使边界与迁徙不只是主题，而直接决定作品怎样被制作。',projects:[project('2002–2003','Where We Come From','参与式行动 / 摄影文本',['询问无法自由进入巴勒斯坦地区的人希望她替他们完成什么。','利用自身行动自由完成请求并记录过程。'],'作品把护照与移动权限的不平等变成创作结构。')],images:[],sourceLabel:'Guggenheim',sourceUrl:'https://www.guggenheim.org/artwork/artist/emily-jacir'},
 {id:'wael-shawky',name:'Wael Shawky',born:'1971',base:'Alexandria / Philadelphia',intro:'以电影、木偶、绘画和表演重新讲述历史叙事，尤其关注十字军、神话与历史如何在不同文化中被制造。',methods:['历史重演','木偶电影','绘画','表演','叙事研究'],subjects:['历史','十字军','神话','宗教','叙事权力'],outputs:['电影','装置','绘画','雕塑','表演'],institutions:['Venice Biennale','MoMA PS1'],achievements:['Egypt Pavilion · Venice Biennale 2024'],whyImportant:'他不把历史当成可直接恢复的事实，而通过高度人工化的木偶和舞台暴露历史本身也是不断被讲述和重写的结构。',projects:[project('2010–2015','Cabaret Crusades','木偶电影三部曲',['依据阿拉伯历史材料重新叙述十字军。','以不同类型木偶和舞台制作历史场景。'],'人工舞台强化了历史叙事的建构性。')],images:[],sourceLabel:'Wael Shawky official website',sourceUrl:'https://www.waelshawky.com/'},
 {id:'regina-jose-galindo',name:'Regina José Galindo',born:'1974',base:'Guatemala City',intro:'以自己的身体进行高强度行为和录像实践，直接处理危地马拉内战、性别暴力、种族与国家权力。',methods:['行为艺术','身体艺术','录像','政治介入'],subjects:['国家暴力','女性','战争','种族','身体','权力'],outputs:['行为','录像','摄影','装置'],institutions:['Venice Biennale'],achievements:['Golden Lion for a young artist · Venice Biennale 2005'],whyImportant:'她让身体成为政治暴力的测量单位，通过简单但高压的动作把抽象制度暴力转化为观众无法回避的身体经验。',projects:[project('2003','¿Quién puede borrar las huellas?','行为 / 公共空间',['从危地马拉国会走向国家宫。','反复将脚浸入装有人血的盆中留下足迹。'],'以身体行走把政治抗议和内战记忆直接写入城市空间。')],images:[],sourceLabel:'Regina José Galindo official website',sourceUrl:'https://www.reginajosegalindo.com/' }
];
