import type { Artist } from './data';

export const artistBatch93: Artist[] = [
{id:'walid-raad',name:'Walid Raad',born:'1967',base:'Lebanon / United States',intro:'黎巴嫩艺术家，以摄影、录像、档案虚构、雕塑与表演研究黎巴嫩战争记忆、影像证据的真实性以及阿拉伯世界艺术制度。',methods:['档案虚构','调查式艺术','摄影与文本','表演讲座'],subjects:['战争记忆','历史书写','影像证据','黎巴嫩','艺术制度'],outputs:['摄影','录像','装置','表演'],institutions:['MoMA','MoMA PS1'],achievements:['The Atlas Group','My neck is thinner than a hair','Scratching on things I could disavow','Walid Raad: MoMA 2015 survey'],whyImportant:'Raad把档案的可信度本身变成作品对象，以事实、虚构和制度研究之间的不稳定关系重写战争与艺术史，是中东当代艺术和档案实践的关键人物。',projects:[{year:'1989–2004',title:'The Atlas Group',type:'档案与跨媒介项目',facts:['以照片、录像、文本和虚构档案研究黎巴嫩当代战争历史。','通过真假难辨的文件追问公共影像、记忆与历史叙述如何形成。'],reading:'项目不是简单保存战争档案，而是让观众意识到所谓证据本身也由叙事、机构与观看习惯塑造。'}],images:[],sourceLabel:'MoMA · Walid Raad',sourceUrl:'https://www.moma.org/artists/35285-walid-raad'},
{id:'yto-barrada',name:'Yto Barrada',born:'1971',base:'Morocco / France',intro:'摩洛哥—法国艺术家，以摄影、电影、出版、纺织和社会项目研究丹吉尔、迁徙边界、殖民现代性、自然史以及抵抗与生存策略。',methods:['社会观察','地缘政治摄影','档案研究','跨媒介叙事'],subjects:['迁徙','边界','丹吉尔','殖民历史','抵抗'],outputs:['摄影','电影','纺织','出版','装置'],institutions:['MoMA','Venice Biennale'],achievements:['A Life Full of Holes: The Strait Project','School of the Strait','Artist’s Choice: Yto Barrada—A Raft'],whyImportant:'Barrada从直布罗陀海峡和丹吉尔的日常景观出发，把摄影中的细微观察连接到迁徙政治、殖民历史与抵抗策略，是北非当代摄影的重要节点。',projects:[{year:'1998–2004',title:'A Life Full of Holes: The Strait Project',type:'摄影项目',facts:['围绕丹吉尔与直布罗陀海峡展开长期摄影。','通过城市空间、等待和日常细节讨论欧洲边境与迁徙欲望。'],reading:'她避免把迁徙简化成新闻事件，而从边境城市的日常结构呈现地缘政治如何进入生活。'}],images:[],sourceLabel:'MoMA · Yto Barrada',sourceUrl:'https://www.moma.org/collection/artists/42323'},
{id:'dinh-q-le',name:'Dinh Q. Lê',born:'1968–2024',base:'Vietnam / United States',intro:'越南裔美国艺术家，以摄影编织、录像与装置处理越南战争、流散记忆、好莱坞影像与个人和集体历史之间的冲突。',methods:['摄影编织','档案挪用','影像装置','记忆研究'],subjects:['越南战争','流散','战争记忆','大众媒介','历史'],outputs:['摄影','录像','装置'],institutions:['MoMA','MoMA PS1'],achievements:['The Farmers and The Helicopters','Untitled (movie grid)','Projects 93: Dinh Q. Lê'],whyImportant:'Lê把家庭照片、新闻与电影图像交织，让战争的私人记忆与全球大众媒介叙事发生冲突，是越南及离散摄影史的重要人物。',projects:[{year:'2006',title:'The Farmers and The Helicopters',type:'多频道录像与装置',facts:['与多位越南合作者共同制作，结合直升机影像与越南人的战争记忆。','2010年成为MoMA Projects 93核心作品。'],reading:'作品把美国战争视觉符号与越南当地人的口述和经验并置，改变谁有权讲述战争历史的问题。'}],images:[],sourceLabel:'MoMA · Dinh Q. Lê',sourceUrl:'https://www.moma.org/artists/26740-dinh-q-le'},
{id:'bouchra-khalili',name:'Bouchra Khalili',born:'1975',base:'Morocco / France / Germany',intro:'法裔摩洛哥艺术家，以录像、地图、声音和档案研究迁徙者的路线、公民身份、国家边界、反殖民历史与政治主体的自我叙述。',methods:['口述史','地图叙事','长镜头','档案研究'],subjects:['迁徙','边界','公民身份','反殖民历史','政治主体'],outputs:['录像','装置','摄影','出版'],institutions:['MoMA','Palais de Tokyo','MACBA','Documenta','Venice Biennale'],achievements:['The Mapping Journey Project','Foreign Office','Speeches Series'],whyImportant:'Khalili让迁徙者以自己的声音和手势绘制路线，将地图从国家管理工具转化为第一人称政治叙事，是当代迁徙影像的重要节点。',projects:[{year:'2008–2011',title:'The Mapping Journey Project',type:'八频道录像装置',facts:['八位迁徙者在地图上用永久记号笔描绘实际旅程，同时以自己的声音讲述路线。','作品以固定长镜头、地图、手和声音构成，并于2016年在MoMA展出。'],reading:'地图上的国界被个人路线重新书写，抽象地缘政治因此转化为具体的身体经验和主体发声。'}],images:[],sourceLabel:'MoMA · Bouchra Khalili',sourceUrl:'https://www.moma.org/artists/47100-bouchra-khalili'},
{id:'sabelo-mlangeni',name:'Sabelo Mlangeni',born:'1980',base:'South Africa',intro:'南非摄影师，以长期黑白摄影关注乡村与城市社区、劳动、亲密关系、酷儿生活和南非社会空间。',methods:['长期纪实','社区摄影','黑白摄影','参与式观察'],subjects:['社区','劳动','酷儿生活','乡村','南非社会'],outputs:['摄影','摄影书'],institutions:['Aperture'],achievements:['Country Girls','Men Only','Ghost Towns','Aperture Platform Africa'],whyImportant:'Mlangeni以长期进入社区而非新闻式旁观建立影像关系，在后种族隔离时代南非摄影中连接社会纪实、亲密性与酷儿可见性。',projects:[{year:'2003–2009',title:'Country Girls',type:'长期摄影系列',facts:['长期拍摄南非乡村地区的黑人酷儿与跨性别社群。','以日常生活、友谊和自我呈现取代猎奇式观看。'],reading:'系列的重要性在于让被边缘化的主体以生活关系而不是社会问题标签进入摄影史。'}],images:[],sourceLabel:'Aperture · Platform Africa / Sabelo Mlangeni',sourceUrl:'https://store.aperture.org/products/aperture-227'}
];
