import type { Artist } from './data';

export const artistBatch137: Artist[] = [
{id:'wolfgang-tillmans',name:'Wolfgang Tillmans',born:'1968',base:'Germany / UK',intro:'德国摄影艺术家，从青年文化、亲密肖像、静物和政治现场扩展到无相机抽象摄影与墙面编排，持续改变摄影如何进入展览空间。',methods:['日常观察','墙面编排','无相机摄影','跨尺度展示'],subjects:['青年文化','亲密关系','酷儿生活','政治','日常物','抽象'],outputs:['摄影','喷墨印刷','摄影装置'],institutions:['Tate'],achievements:['if one thing matters, everything matters','Turner Prize 2000'],whyImportant:'Tillmans把看似随手的生活图像、杂志页面、大幅照片和抽象暗房实验放在同一视觉系统中，使摄影展览本身成为编辑与意义生产的方法。',projects:[{year:'1995–97',title:'if one thing matters, everything matters',type:'摄影 / 展示编排',facts:['Tate资料记录该时期作品，并指出其展示常混合喷墨印刷、照片与杂志页面。','其题材横跨亲密静物、朋友肖像、政治议题与青年文化。'],reading:'重要的不只是单张照片，而是不同尺度、来源和题材在墙面上的关系。'}],images:[],sourceLabel:'Tate · Wolfgang Tillmans',sourceUrl:'https://www.tate.org.uk/art/artists/wolfgang-tillmans-2747'},
{id:'rineke-dijkstra',name:'Rineke Dijkstra',born:'1959',base:'Netherlands',intro:'荷兰摄影与影像艺术家，以正面、克制的大画幅肖像长期观察青少年、母亲、斗牛士、士兵与移民等处在身份转换中的人物。',methods:['大画幅肖像','长期跟踪','类型式拍摄','影像肖像'],subjects:['青春期','身份转变','迁徙','身体','成长'],outputs:['摄影','影像'],institutions:['MoMA'],achievements:['Beach Portraits','Almerisa'],whyImportant:'Dijkstra把类型学的稳定形式用于高度不稳定的人生阶段，使细微姿态、身体紧张和时间变化成为肖像的核心内容。',projects:[{year:'1994–',title:'Almerisa',type:'长期肖像摄影',facts:['MoMA收藏Almerisa从荷兰庇护中心开始的多张长期肖像。','系列通过重复拍摄呈现人物在迁徙与成长中的变化。'],reading:'固定的拍摄结构让时间本身进入肖像，而不是依靠戏剧化叙事说明身份。'}],images:[],sourceLabel:'MoMA · Rineke Dijkstra',sourceUrl:'https://www.moma.org/artists/8139-rineke-dijkstra'},
{id:'jeff-wall',name:'Jeff Wall',born:'1946',base:'Canada',intro:'加拿大艺术家，以大型灯箱透明片和精密编排摄影把电影式场景、街头观察、艺术史构图与广告展示技术结合。',methods:['场景编排','电影式摄影','艺术史转译','灯箱展示'],subjects:['城市生活','社会关系','日常事件','艺术史','劳动'],outputs:['摄影','灯箱'],institutions:['MoMA'],achievements:['Milk','Restoration','MoMA retrospective 2007'],whyImportant:'Wall使摄影重新进入大型历史画的尺度与构图传统，同时保留摄影对现代城市偶发事件的敏感，成为编排摄影的重要基准。',projects:[{year:'1970s–',title:'Large-scale lightbox photographs',type:'编排摄影 / 灯箱',facts:['MoMA指出Wall自1970年代末发展大型背光透明片，并把古典绘画的构图丰富性与商业灯箱结合。','MoMA于2007年举办其大型回顾展。'],reading:'作品常看似瞬间抓拍，实际可能经过复杂重演，因此摄影的纪实感和人为构造同时存在。'}],images:[],sourceLabel:'MoMA · Jeff Wall',sourceUrl:'https://www.moma.org/collection/artists/7826'},
{id:'walid-raad',name:'Walid Raad',born:'1967',base:'Lebanon / USA',intro:'黎巴嫩艺术家，以摄影、影像、文本、表演和虚构档案研究黎巴嫩内战、公共文件的真实性、记忆叙事以及阿拉伯世界艺术史的建构。',methods:['虚构档案','摄影与文本','讲演表演','制度虚构'],subjects:['战争','记忆','档案','真实性','阿拉伯艺术史'],outputs:['摄影','影像','文本','雕塑','表演'],institutions:['MoMA','MoMA PS1'],achievements:['The Atlas Group','Walid Raad — MoMA 2015'],whyImportant:'Raad没有把档案当作中立证据，而是通过真假难辨的文件和叙述暴露战争历史、机构权威与记忆生产本身如何被建构。',projects:[{year:'1989–2004',title:'The Atlas Group',type:'虚构档案 / 摄影 / 影像',facts:['MoMA将The Atlas Group/Walid Raad列入馆藏与展览体系。','2015年MoMA回顾展强调其对公共摄影和影像文件真实性、冲突记忆及阿拉伯艺术史建构的研究。'],reading:'关键不在辨认哪份文件是真的，而在意识到我们判断历史真实性所依赖的制度和叙事机制。'}],images:[],sourceLabel:'MoMA · Walid Raad',sourceUrl:'https://www.moma.org/calendar/exhibitions/1493'},
{id:'cao-fei',name:'Cao Fei',born:'1978',base:'China',intro:'中国艺术家，以摄影、影像、数字媒体、虚拟世界和大型装置研究珠三角城市化、青年亚文化、劳动、自动化以及现实与虚拟生活的交叠。',methods:['社会观察','虚拟世界建构','影像叙事','数字媒体实验'],subjects:['城市化','青年文化','劳动','自动化','虚拟现实','技术'],outputs:['摄影','影像','数字媒体','多媒体装置'],institutions:['Guggenheim','MoMA PS1','La Biennale di Venezia'],achievements:['COSplayers','Whose Utopia','RMB City','Asia One'],whyImportant:'曹斐把中国高速城市化与互联网、游戏和自动化放在同一叙事中，是理解21世纪中国社会经验与数字生活关系的关键艺术家。',projects:[{year:'2018',title:'Asia One',type:'影像 / 多媒体装置',facts:['Guggenheim委托并收藏Asia One。','作品在中国高度自动化物流设施中拍摄，以近未来叙事研究自动化对人与社会关系的影响。'],reading:'工业现场并非单纯纪录对象，而被转化为关于机器替代、孤独和未来劳动的虚构空间。'}],images:[],sourceLabel:'Guggenheim · Cao Fei',sourceUrl:'https://www.guggenheim.org/artwork/artist/cao-fei'},
{id:'yinka-shonibare',name:'Yinka Shonibare',born:'1962',base:'UK / Nigeria',intro:'英尼艺术家，以荷兰蜡染布、雕塑、摄影、电影和装置重新编排殖民史、帝国、阶级、迁徙与文化身份。',methods:['历史重演','材料挪用','服装与雕塑','后殖民转译'],subjects:['殖民主义','帝国','迁徙','文化身份','阶级','全球贸易'],outputs:['雕塑','装置','摄影','电影','绘画'],institutions:['Tate'],achievements:['The British Library','Nelson’s Ship in a Bottle','Turner Prize nominee 2004'],whyImportant:'Shonibare利用常被误认作“非洲传统”的荷兰蜡染布所携带的跨洲贸易史，把身份的混杂性直接嵌入材料本身。',projects:[{year:'2014',title:'The British Library',type:'装置',facts:['Tate资料记录作品由6328本以彩色Dutch wax print包覆的精装书构成。','部分书脊以金字标示英国第一、二代移民等姓名。'],reading:'图书馆在这里既是知识制度，也是关于英国身份如何由迁徙和帝国历史共同构成的物质地图。'}],images:[],sourceLabel:'Tate · Yinka Shonibare',sourceUrl:'https://www.tate.org.uk/art/artists/yinka-shonibare-cbe-1938'}
];