import type { Artist } from './data';
import { artistBatch118 } from './expansionBatch118';

export const artistBatch117: Artist[] = [
{id:'wangechi-mutu',name:'Wangechi Mutu',born:'1972',base:'Kenya / United States',intro:'肯尼亚裔美国艺术家，以拼贴、绘画、雕塑、电影与表演构造混合身体和未来神话，持续研究女性身体、种族表征、殖民历史与生态不平等。',methods:['图像拼贴','身体重构','神话改写','材料混合'],subjects:['女性身体','种族','殖民主义','神话','生态'],outputs:['拼贴','绘画','雕塑','电影','表演'],institutions:['The Metropolitan Museum of Art','Whitney Biennial'],achievements:['The NewOnes, will free Us','My Strength Lies','The Met Facade Commission 2019'],whyImportant:'Mutu把杂志图像、非洲与欧洲雕塑传统和科幻式身体结合，形成讨论黑人女性身体、权力和未来想象的重要视觉语言。',projects:[{year:'2019',title:'The NewOnes, will free Us',type:'公共雕塑 / 建筑介入',facts:['为The Met首届外立面委任创作四件青铜人物。','作品重新解释非洲与西方艺术史中的女性承重像传统。'],reading:'她让原本承担建筑或权力重量的女性形象摆脱支撑角色，把博物馆的新古典主义立面转化为关于自主、种族与性别权力的现场。'}],images:[],sourceLabel:'The Met · Wangechi Mutu',sourceUrl:'https://www.metmuseum.org/es/perspectives/wangechi-mutu-facade'},
{id:'el-anatsui',name:'El Anatsui',born:'1944',base:'Ghana / Nigeria',intro:'加纳出生、长期工作于尼日利亚的艺术家，以木材、陶土和大量回收酒瓶盖制作可变形的大型雕塑装置，连接贸易、殖民历史、消费与材料循环。',methods:['材料转换','重复单元','手工连接','非固定形态'],subjects:['贸易','殖民历史','消费','迁徙','材料记忆'],outputs:['雕塑','装置','金属织物','木雕'],institutions:['Tate Modern','La Biennale di Venezia'],achievements:['Behind the Red Moon','Ghana Freedom — Venice Biennale 2019'],whyImportant:'Anatsui把废弃瓶盖发展成既像织物又像纪念碑的雕塑语言；作品每次安装都可重新塑形，使材料的全球流通史与雕塑自身的不固定性结合。',projects:[{year:'2023',title:'Behind the Red Moon',type:'大型雕塑装置 / Tate Modern委任',facts:['作品由数以千计的金属酒瓶盖与碎片连接构成。','项目延续艺术家对跨大西洋奴隶贸易中商品与人口迁移历史的研究。'],reading:'瓶盖从消费废料变成巨大悬挂结构，材料本身携带酒精贸易、殖民交换与当代循环经济的多重历史。'}],images:[],sourceLabel:'Tate · El Anatsui — Behind the Red Moon',sourceUrl:'https://shop.tate.org.uk/hyundai-commission-2023-el-anatsui-behind-the-red-moon/28591.html'},
{id:'ibrahim-mahama',name:'Ibrahim Mahama',born:'1987',base:'Ghana',intro:'加纳艺术家，以旧黄麻袋、铁路遗物、档案和建筑尺度装置研究商品流通、殖民基础设施、劳动以及材料所携带的社会记忆，并在Tamale建立文化与教育空间。',methods:['材料档案','建筑包覆','再利用','社会基础设施'],subjects:['劳动','殖民主义','贸易','铁路','材料记忆'],outputs:['装置','纺织','建筑介入','档案'],institutions:['La Biennale di Venezia','The Whitworth'],achievements:['Out of Bounds','Parliament of Ghosts','Ghana Freedom — Venice Biennale 2019'],whyImportant:'Mahama把全球商品运输中磨损的材料转化为巨型公共表面，同时把艺术生产延伸到文化基础设施建设，是理解当代非洲材料政治与社会实践的重要节点。',projects:[{year:'2019',title:'Parliament of Ghosts',type:'装置 / 建筑与档案研究',facts:['最初为The Whitworth及Manchester International Festival构思。','作品从Gold Coast铁路基础设施与加纳独立后现代主义建筑遗迹出发，并后来转化进入Tamale的Red Clay空间。'],reading:'废弃铁路与建筑残余不只是历史证物，而成为重新讨论殖民资源系统、独立后的现代主义理想和未来公共文化空间的材料。'}],images:[],sourceLabel:'La Biennale di Venezia · Ibrahim Mahama',sourceUrl:'https://www.labiennale.org/en/architecture/2023/force-majeure/ibrahim-mahama'},
{id:'dinh-q-le',name:'Dinh Q. Lê',born:'1968–2024',base:'Vietnam / United States',intro:'越南裔美国艺术家，以摄影编织、录像和装置把私人记忆、新闻图像与好莱坞战争影像交织，研究越南战争如何被个人经验和全球视觉文化反复重写。',methods:['摄影编织','档案重组','口述历史','影像并置'],subjects:['越南战争','记忆','电影','历史叙事','流散'],outputs:['摄影','录像','装置','编织图像'],institutions:['MoMA','MoMA PS1'],achievements:['The Farmers and The Helicopters','Projects 93: Dinh Q. Lê','Untitled (movie grid)'],whyImportant:'Lê让战争记忆在个人证词与大众电影之间发生冲突，揭示历史并不是稳定图像，而是在私人经验、国家叙事和娱乐工业之间不断被重新生产。',projects:[{year:'2006',title:'The Farmers and The Helicopters',type:'三频道录像 / 雕塑装置',facts:['作品结合越南当地居民对战争直升机的回忆与西方电影片段。','装置同时展出由当地农民与自学机械师利用零件手工制造的直升机。'],reading:'同一架直升机既可以是战争恐惧的象征，也能成为民间工程与未来愿望的对象，作品因此打破单一的战争记忆。'}],images:[],sourceLabel:'MoMA · Dinh Q. Lê',sourceUrl:'https://www.moma.org/calendar/exhibitions/1058'},
{id:'tuan-andrew-nguyen',name:'Tuan Andrew Nguyen',born:'1976',base:'Vietnam / United States',intro:'越南裔美国艺术家，以电影、雕塑、档案研究和合作项目处理战争遗产、殖民主义、迁徙、跨国记忆以及物件承载历史和疗愈可能性的方式。',methods:['研究型电影','口述历史','档案重构','跨国叙事'],subjects:['殖民主义','战争','迁徙','记忆','跨国团结'],outputs:['电影','录像','雕塑','装置'],institutions:['MoMA'],achievements:['The Specter of Ancestors Becoming','Crimes of Solidarity','The Farmers and The Helicopters'],whyImportant:'Nguyen把越南经验放进更广泛的法国殖民网络与跨国迁徙史中，使战争记忆从民族国家框架扩展到非洲—亚洲之间被忽略的历史联系。',projects:[{year:'2019',title:'The Specter of Ancestors Becoming',type:'电影 / 跨国历史研究',facts:['项目研究法国殖民时期被部署到印度支那的西非士兵及其后代历史。','作品关注殖民战争中形成却常被官方历史忽略的跨国亲密关系与团结。'],reading:'越南与塞内加尔不再是两条分离历史，而通过殖民军队、家庭和后代记忆进入同一个跨洲网络。'}],images:[],sourceLabel:'MoMA · Tuan Andrew Nguyen',sourceUrl:'https://www.moma.org/artists/37485-tuan-andrew-nguyen'},
...artistBatch118
];