import type { Artist } from './data';
import { artistBatch119 } from './expansionBatch119';

export const artistBatch118: Artist[] = [
{id:'shahzia-sikander',name:'Shahzia Sikander',born:'1969',base:'Pakistan / United States',intro:'巴基斯坦裔美国艺术家，从南亚细密画传统出发，将手绘、版画、壁画与数字动画结合，持续重写宗教图像、性别、身份和殖民视觉传统。',methods:['传统重写','图像叠层','跨文化挪用','数字动画'],subjects:['身份','性别','宗教图像','殖民历史','文化混杂'],outputs:['绘画','素描','版画','动画','装置'],institutions:['MoMA','MoMA PS1'],achievements:['No Parking Anytime','The Turban Field','Scenes for a New Heritage'],whyImportant:'Sikander不是简单复兴细密画，而是把这种历史媒介转化为可进入全球当代艺术、女性主义与后殖民讨论的动态视觉系统。',projects:[{year:'2001',title:'No Parking Anytime',type:'版画组作 / 图像重构',facts:['作品组结合照相凹版、蚀刻、飞尘与chine collé等版画方法。','图像把穆斯林与印度教神话、个人故事、文学引用和日常幽默并置。'],reading:'她让传统图像不再属于固定民族或宗教身份，而成为不断复制、变形和重新编码的视觉语言。'}],images:[],sourceLabel:'MoMA · Shahzia Sikander',sourceUrl:'https://www.moma.org/artists/8197-shahzia-sikander'},
{id:'nalini-malani',name:'Nalini Malani',born:'1946',base:'India',intro:'印度影像艺术先驱之一，以绘画、录像、反向玻璃绘画、影子戏与多频道装置处理印巴分治、迁徙、女性主义、暴力和记忆。',methods:['影像叠加','影子投射','擦除动画','神话重写'],subjects:['印巴分治','女性主义','暴力','记忆','核威胁'],outputs:['录像','绘画','装置','动画','摄影'],institutions:['MoMA','Stedelijk Museum'],achievements:['Dream Houses','Memory: Record/Erase','Gamepieces'],whyImportant:'Malani从1960年代实验电影一路发展到沉浸式video/shadow play，是南亚女性主义影像与装置史的重要先驱，并把私人迁徙经验连接到国家暴力和全球战争记忆。',projects:[{year:'2003/2009',title:'Gamepieces',type:'四频道录像 / 影子戏装置',facts:['作品由四频道录像与六个绘有图像的Lexan圆筒组成。','创作背景与1998年印度和巴基斯坦核试验有关，并使用广岛、长崎原爆影像。'],reading:'旋转、投影和稍纵即逝的影子使观看者无法稳定掌握图像，记忆本身因此成为作品的结构。'}],images:[],sourceLabel:'MoMA · Nalini Malani',sourceUrl:'https://www.moma.org/artists/32825-nalini-malani'},
{id:'amar-kanwar',name:'Amar Kanwar',born:'1964',base:'India',intro:'印度艺术家与电影作者，以纪录影像、档案、文字和多频道装置研究政治暴力、生态冲突、司法、主权与抵抗，并不断测试纪录片事实与诗性证据之间的边界。',methods:['纪录片重构','档案蒙太奇','多频道叙事','诗性证据'],subjects:['政治暴力','司法','生态','主权','抵抗'],outputs:['电影','录像','多频道装置','档案'],institutions:['Solomon R. Guggenheim Museum','documenta'],achievements:['The Torn First Pages','The Sovereign Forest','A Night of Prophecy'],whyImportant:'Kanwar把纪录片从信息传递扩展成关于证据、观看伦理和政治记忆的空间实践，是南亚研究型影像艺术的重要节点。',projects:[{year:'2004–08',title:'The Torn First Pages',type:'十九频道录像装置',facts:['作品分三部分并以十九频道录像构成。','项目围绕缅甸军政府的压迫与反抗，并向因撕去国家宣传页而入狱的书店经营者致意。'],reading:'大量真实记录被组织成同时发生的影像合唱，使档案不只是过去的证据，也成为持续抵抗的现场。'}],images:[],sourceLabel:'Guggenheim · Amar Kanwar',sourceUrl:'https://www.guggenheim.org/artwork/artist/amar-kanwar'},
{id:'bani-abidi',name:'Bani Abidi',born:'1971',base:'Pakistan / Germany',intro:'巴基斯坦艺术家，以录像、摄影、声音和装置观察国家权力、边境、安全设施、官僚制度与日常生活之间荒诞而具体的关系。',methods:['制度观察','日常政治','类型学','虚构场景'],subjects:['国家权力','边境','安全','官僚制度','城市生活'],outputs:['录像','摄影','声音','装置'],institutions:['MoMA','Solomon R. Guggenheim Museum'],achievements:['Reserved','Security Barriers A–L','No Country'],whyImportant:'Abidi常从不起眼的城市设施、等待和行政动作切入政治，使宏大的国家与边境问题转化成可以被直接观看的日常结构。',projects:[{year:'2008',title:'Security Barriers A–L',type:'摄影 / 安全设施类型学',facts:['MoMA馆藏包含该系列A至L多种Security Barrier类型。','作品把城市中的安全隔离设施作为连续视觉类型呈现。'],reading:'当安全设施被从背景中抽出并连续观看，反恐、阶级区隔和国家权力便以物件设计的形式显现出来。'}],images:[],sourceLabel:'MoMA · Bani Abidi',sourceUrl:'https://www.moma.org/artists/35392-bani-abidi'},
{id:'shilpa-gupta',name:'Shilpa Gupta',born:'1976',base:'India',intro:'孟买艺术家，以互动装置、影像、声音、物件与参与式方法研究边境、国家、监控、言论限制和个体如何被政治分类系统塑造。',methods:['参与式装置','尺度转换','文本介入','制度批判'],subjects:['边境','国家','监控','恐惧','身份'],outputs:['装置','雕塑','影像','声音','网络项目'],institutions:['Solomon R. Guggenheim Museum','Tate Modern'],achievements:['1:14.9','No Country: Contemporary Art for South and Southeast Asia'],whyImportant:'Gupta把抽象的边境长度、国家安全与身份制度转换成身体可以感知的材料和尺度，是印度当代艺术中研究边界政治与参与媒介的重要艺术家。',projects:[{year:'2011–12',title:'1:14.9',type:'雕塑 / 边境尺度转换',facts:['作品以手绕聚酯线、木制展柜、玻璃和黄铜铭牌构成。','艺术家以14.9比1的比例把约80英里线缠绕成团，对应印巴边境的巨大尺度。'],reading:'无法被身体直接把握的国家边界被压缩成一个封闭线团，地缘政治因此转化为重量、密度和限制的物理经验。'}],images:[],sourceLabel:'Guggenheim · Shilpa Gupta / No Country',sourceUrl:'https://www.guggenheim.org/press-release/mediareleasenocountry'},
...artistBatch119
];