import type { Artist } from './data';
import { artistBatch167 } from './expansionBatch167';

export const artistBatch166: Artist[] = [
{id:'yto-barrada',name:'Yto Barrada',born:'1971',base:'Morocco / France',intro:'法裔摩洛哥艺术家，以摄影、电影、雕塑、出版与研究型项目长期处理丹吉尔、直布罗陀海峡、迁徙地缘政治、现代主义历史与地方知识。',methods:['研究型摄影','档案研究','地缘政治观察','跨媒介叙事'],subjects:['迁徙','丹吉尔','边界','殖民与现代主义历史','地方知识'],outputs:['摄影','电影','雕塑','出版'],institutions:['MoMA'],achievements:['MoMA collection','Artist’s Choice: Yto Barrada—A Raft, MoMA 2021–2022'],whyImportant:'Barrada把看似平静的城市景观、物件和地方故事转化为边界制度与迁徙政治的视觉线索，同时不断扩展摄影与研究、电影和策展之间的关系，是北非当代艺术与摄影的重要节点。',projects:[{year:'2001',title:'School of the Strait',type:'彩色摄影',facts:['MoMA收藏该作，作品属于Barrada围绕丹吉尔及直布罗陀海峡展开的摄影实践。','MoMA将她的持续关注概括为丹吉尔、化石、现代主义历史以及迁徙地缘政治。'],reading:'海峡不只是风景，而是欧洲与非洲之间由欲望、流动限制和政治边界共同形成的空间。'}],images:[],sourceLabel:'MoMA · Yto Barrada',sourceUrl:'https://www.moma.org/artists/42323-yto-barrada'},
{id:'dawoud-bey',name:'Dawoud Bey',born:'1953',base:'United States',intro:'美国摄影艺术家，以街头肖像、大画幅肖像和历史场所摄影持续研究黑人主体、社区、美国民权历史以及摄影如何让过去重新进入当下。',methods:['长期社会肖像','历史研究','场所重访','导演式肖像'],subjects:['黑人生活','社区','民权运动','历史记忆','青少年'],outputs:['摄影','肖像','大型摄影装置'],institutions:['Whitney Museum of American Art','MoMA'],achievements:['Whitney Biennial 2014','Dawoud Bey: An American Project, Whitney 2021','MoMA collection'],whyImportant:'Bey从Harlem街头摄影出发，把黑人日常主体置于美术馆摄影史中心；后期又以严格研究和重构连接民权暴力、地下铁路等历史，使肖像和历史景观成为跨代记忆工具。',projects:[{year:'2012',title:'The Birmingham Project',type:'黑白肖像双联画',facts:['Whitney记录该系列回应1963年伯明翰种族主义暴力中遇害的六名非裔美国年轻人。','作品将与遇害者当年同龄的年轻人与假如他们活到2012年应有年龄的成年人并置。'],reading:'双联画拒绝只把遇害者冻结在死亡时刻，而用年龄对应制造被暴力夺走的人生时间。'}],images:[],sourceLabel:'Whitney · Dawoud Bey',sourceUrl:'https://whitney.org/exhibitions/2014-biennial/dawoud-bey'},
{id:'cristina-de-middel',name:'Cristina de Middel',born:'1975',base:'Spain / Brazil',intro:'西班牙摄影艺术家，从新闻摄影转向在纪实与虚构之间工作的建构摄影，以档案、摆拍、道具和摄影书质疑新闻摄影的真实性惯例及西方对非洲等地区的固定叙事。',methods:['纪实与虚构混合','场景建构','档案再叙事','摄影书'],subjects:['媒体再现','非洲想象','真实性','历史逸闻','殖民视觉'],outputs:['摄影','摄影书','档案材料','装置'],institutions:['Foam'],achievements:['The Afronauts, Foam 2013','Foam Collection'],whyImportant:'De Middel把摄影的“可信度”本身变成题材：她不是简单虚构，而是从真实历史出发制造可见的替代叙事，直接挑战新闻摄影把复杂地区压缩为贫困与冲突刻板印象的机制。',projects:[{year:'2012',title:'The Afronauts',type:'建构摄影与档案混合项目',facts:['项目源于1964年赞比亚教师Edward Makuka Nkoloso提出的太空计划。','Foam指出De Middel以想象重建这一故事，并混合摆拍摄影、打字信件复制件和旧照片复制品。'],reading:'真实历史与明显的人造道具并置，使观众无法再把摄影自动等同于事实，也暴露西方媒体塑造“非洲现实”的方式。'}],images:[],sourceLabel:'Foam · Cristina De Middel — The Afronauts',sourceUrl:'https://www.foam.org/events/cristina-de-middel'},
{id:'santu-mofokeng',name:'Santu Mofokeng',born:'1956–2020',base:'South Africa',intro:'南非摄影艺术家，以细腻的黑白摄影记录种族隔离时期及其后的黑人日常生活、宗教实践、土地、精神性与历史记忆，反对把黑人经验简化为新闻事件或政治符号。',methods:['社会纪实','长期观察','摄影散文','精神性研究'],subjects:['种族隔离','黑人日常生活','宗教','土地','记忆'],outputs:['黑白摄影','摄影散文','档案'],institutions:['MoMA'],achievements:['MoMA collection','Train Church works in MoMA collection'],whyImportant:'Mofokeng扩展了反种族隔离摄影的语言：他既记录结构性压迫，又坚持日常生活、信仰、模糊性与主体内部经验不能被政治新闻图像完全解释，是南非摄影史从新闻纪实转向复杂作者性实践的重要人物。',projects:[{year:'1986',title:'Train Church',type:'黑白摄影系列',facts:['MoMA收藏该系列多幅作品，包括Commotion、Exhortations、Hands in Worship与Overcome/Spiritual Ecstasy。','作品拍摄约翰内斯堡—索韦托通勤列车上形成的宗教礼拜。'],reading:'被种族隔离制度塑造的通勤空间被乘客临时转化为精神共同体，使压迫性的基础设施与自主信仰实践出现在同一图像结构中。'}],images:[],sourceLabel:'MoMA · Santu Mofokeng',sourceUrl:'https://www.moma.org/artists/72440-santu-mofokeng'},
...artistBatch167
];