import type { Artist } from './data';
import { artistBatch163 } from './expansionBatch163';

export const artistBatch162: Artist[] = [
{id:'thomas-ruff',name:'Thomas Ruff',born:'1958',base:'Germany',intro:'德国摄影艺术家，杜塞尔多夫艺术学院贝歇夫妇学生，以类型学肖像、夜视图像、网络JPEG、天文图像和数字处理持续检验摄影的客观性、分辨率与图像流通机制。',methods:['类型学摄影','图像挪用','数字放大','摄影媒介分析'],subjects:['肖像','数字图像','监视','战争图像','网络传播'],outputs:['摄影','数码打印','挪用图像'],institutions:['MoMA'],achievements:['MoMA collection','Portraits series','Jpegs series'],whyImportant:'Ruff把贝歇学派的系统性方法推进到数字时代：从拒绝心理解释的正面肖像，到把低分辨率网络JPEG放大至像素结构可见，使摄影的真实性问题转向图像如何被技术生产、压缩与传播。',projects:[{year:'2004',title:'Jpegs',type:'网络图像挪用 / 大型摄影',facts:['系列不依靠相机拍摄，而使用包括互联网下载在内的压缩JPEG文件。','MoMA指出系列包含战争、灾难与风景图像，并通过巨幅输出使像素结构显现。'],reading:'当图像被放大到信息结构本身暴露时，摄影不再只是所指对象，而成为关于数字图像如何构成与传播的研究。'}],images:[],sourceLabel:'MoMA · Thomas Ruff',sourceUrl:'https://www.moma.org/collection/works/149384'},
{id:'rineke-dijkstra',name:'Rineke Dijkstra',born:'1959',base:'Netherlands',intro:'荷兰摄影与录像艺术家，以大型正面肖像和持续跟拍研究青春期、生产、军事训练、移民等人生过渡状态，以及镜头前主体如何在自我呈现与脆弱之间摆动。',methods:['系列肖像','正面凝视','长期跟拍','过渡状态观察'],subjects:['青春期','身份形成','移民','身体','成长','社会角色'],outputs:['摄影','录像'],institutions:['Guggenheim'],achievements:['Guggenheim retrospective 2012','Venice Biennale 1997 and 2001','Beaches series'],whyImportant:'Dijkstra更新了当代肖像摄影：她减少环境信息，让摄影者、被摄者与观看者之间的关系成为作品核心，并通过多年重复拍摄让身份显现为时间中的变化过程而非固定类型。',projects:[{year:'1992–2002',title:'Beach Portraits',type:'大型彩色肖像摄影',facts:['系列从美国海岸延伸至波兰、乌克兰等欧洲地点。','Guggenheim指出这些青春期人物处于成年边缘，极少环境信息强化了摄影者与主体之间的交换。'],reading:'海滩既提供近乎中性的背景，也让身体姿态、紧张感与自我意识成为身份过渡的细微证据。'}],images:[],sourceLabel:'Guggenheim · Rineke Dijkstra',sourceUrl:'https://www.guggenheim.org/exhibition/rineke-dijkstra-a-retrospective'},
{id:'thomas-struth',name:'Thomas Struth',born:'1954',base:'Germany',intro:'德国摄影艺术家，从城市街道、家庭肖像和博物馆观众扩展至工业、科技与科学研究设施，以大画幅和严格观察研究建筑空间、社会结构、历史记忆与观看制度。',methods:['大画幅观察','城市类型研究','制度空间摄影','系列摄影'],subjects:['城市','建筑','博物馆','家庭','科技','历史记忆'],outputs:['摄影','大型彩色摄影','黑白摄影'],institutions:['MoMA'],achievements:['MoMA collection','Museum Photographs','Unconscious Places'],whyImportant:'Struth把城市空间和制度空间当作社会历史的可见结构：早期空街并非中性建筑记录，而是战后政治经济转型留下的空间痕迹；其后对博物馆和科技设施的研究进一步扩展了摄影对现代制度的观察。',projects:[{year:'1970s–1990s',title:'Unconscious Places / city streets',type:'城市摄影',facts:['MoMA馆藏包括纽约、杜塞尔多夫、东京、法兰克福等城市街景。','MoMA将这些无人街景与二战后德国、日本和美国的经济社会转型联系起来。'],reading:'城市立面、道路和空白公共空间被处理成集体历史的间接肖像。'}],images:[],sourceLabel:'MoMA · Thomas Struth',sourceUrl:'https://www.moma.org/collection/works/49442'},
{id:'hellen-van-meene',name:'Hellen van Meene',born:'1972',base:'Netherlands',intro:'荷兰摄影艺术家，以自然光、小尺幅方形构图和精密导演式摆拍描绘青春期女孩，将看似私密的瞬间与高度控制的服装、姿态、色彩和视线组织结合。',methods:['导演式肖像','自然光','姿态控制','小尺幅构图'],subjects:['青春期','女孩','身体','身份形成','内省'],outputs:['摄影','彩色摄影'],institutions:['Guggenheim'],achievements:['Guggenheim collection'],whyImportant:'Van Meene提供了与Dijkstra不同的青春期肖像路径：不是正面、纪念碑式凝视，而是通过偏转视线、自然光和近距离导演形成似乎偶然却经过严格设计的心理空间。',projects:[{year:'1999',title:'Untitled',type:'导演式彩色肖像',facts:['Guggenheim馆藏作品为方形彩色摄影。','馆方指出她虽使用自然光和普通环境，却控制服装、道具、姿态与凝视等画面元素。'],reading:'照片表面的脆弱与私密感并非抓拍所得，而是摄影控制与主体不确定状态之间的张力。'}],images:[],sourceLabel:'Guggenheim · Hellen van Meene',sourceUrl:'https://www.guggenheim.org/artwork/10235'},
...artistBatch163
];