import type { Artist, ArtworkImage, Project } from './data';
import type { ArtistArchive, ArchiveImage, ArchiveRelation } from './archiveData';

const image = (url: string, title: string, credit: string, sourceUrl: string, sourceLabel: string): ArtworkImage => ({ url, title, credit, sourceUrl, sourceLabel });
const project = (year: string, title: string, type: string, facts: string[], reading: string): Project => ({ year, title, type, facts, reading });
const img = (url: string, title: string, credit: string, sourceUrl: string, sourceLabel: string): ArchiveImage => ({ url, title, credit, sourceUrl, sourceLabel });
const rel = (kind: ArchiveRelation['kind'], label: string, detail?: string): ArchiveRelation => ({ kind, label, detail });

export const artistBatch12: Artist[] = [
  {
    id: 'catherine-opie', name: 'Catherine Opie', born: '1961', base: 'Los Angeles',
    intro: '从酷儿社群肖像、城市基础设施到家庭和名人私宅，持续研究身份如何通过姿势、建筑、家庭空间与摄影类型被制造。',
    methods: ['肖像', '长期项目', '类型化摄影', '场景建构', '城市摄影'], subjects: ['酷儿身份', '家庭', '城市', '社区', '身体', '美国社会'], outputs: ['摄影系列', '大型彩色肖像', '摄影书', '影像'],
    institutions: ['MoMA', 'Guggenheim', 'MOCA Los Angeles'], achievements: ['Guggenheim retrospective 2008', 'MoMA collection'],
    whyImportant: 'Opie 把身份政治做得非常具体：背景颜色、相机距离、服饰、社区关系和肖像类型都在生产身份，而不是靠文字宣布主题。',
    projects: [project('1991', 'Being and Having', '酷儿肖像 / 性别表演', ['拍摄朋友以假胡须等方式表演男性气质。', '使用统一黄色背景和近距离头像格式。'], '重复格式让性别表演的差异从脸、胡须、饰物和凝视中逐渐显现。')],
    images: [image('https://artlogic-res.cloudinary.com/w_800%2Ch_500%2Cc_limit%2Cf_auto%2Cfl_lossy/artlogicstorage/thomasdane/images/view/55ac651f9efbfd929da89638304551c1j.jpg', 'Being and Having, 1991', '© Catherine Opie', 'https://www.moma.org/collection/works/407659', 'MoMA / Thomas Dane documentation')], sourceLabel: 'MoMA', sourceUrl: 'https://www.moma.org/artists/8190-catherine-opie'
  },
  {
    id: 'larry-sultan', name: 'Larry Sultan', born: '1946–2009', base: 'California',
    intro: '把家庭相册、机构档案、摆拍和纪实摄影混在一起，反复研究家庭、郊区与摄影如何制造可信的故事。',
    methods: ['家庭档案', 'found image', '长期纪实', '编排式摄影', '摄影书'], subjects: ['家庭', '郊区', '男性气质', '劳动', '真实性', '美国梦'], outputs: ['摄影系列', '摄影书', '档案项目'],
    institutions: ['SFMOMA', 'LACMA'], achievements: ['Larry Sultan: Here and Home retrospective'],
    whyImportant: '他非常适合研究纪实与编排不是二选一：同一项目里可以同时存在家庭快照、电影截帧、父母文字和摄影师重新安排的场景。',
    projects: [project('1983–1992', 'Pictures from Home', '家庭 / 档案 / 摆拍', ['长期拍摄父母。', '加入家庭快照、家庭录像截图与父母评论。'], '家庭历史不是被发现出来的，而是在不同版本的影像与文字冲突中被制造出来。')],
    images: [image('https://www.larrysultan.com/wp-content/uploads/2013/06/SULPFH1986_Bankbox2_ConversationOnBed-1024x807.jpg', 'Conversation on Bed, Pictures from Home', '© Estate of Larry Sultan', 'https://www.larrysultan.com/gallery/pictures-from-home/conversation-on-bed/', 'Larry Sultan Estate')], sourceLabel: 'SFMOMA', sourceUrl: 'https://www.sfmoma.org/artist/Larry_Sultan/'
  },
  {
    id: 'sherrie-levine', name: 'Sherrie Levine', born: '1947', base: 'New York',
    intro: '直接重拍、复制和再制作艺术史中的既有作品，以挪用挑战原创性、作者身份和现代主义艺术史的权威。',
    methods: ['挪用', '再摄影', '复制', '制度批判', '物件再制作'], subjects: ['作者身份', '原创性', '艺术史', '女性主义', '图像所有权'], outputs: ['摄影', '雕塑', '绘画', '装置'],
    institutions: ['MoMA', 'Whitney Museum', 'Tate'], achievements: ['Whitney Biennial 1985 / 1989 / 2008 / 2014', 'Sherrie Levine: Mayhem — Whitney 2011'],
    whyImportant: '她把“这张照片是谁拍的”变成作品本身的问题。对后摄影、AI图像、再创作和版权讨论都仍然非常关键。',
    projects: [project('1981', 'After Walker Evans', '再摄影 / 挪用', ['从展览图录中的 Walker Evans 作品复制并重新摄影。', '以自己的名字重新展示。'], '创作动作极少，但它直接把原创、作者和摄影史的权力关系暴露出来。')],
    images: [image('https://cdn.sanity.io/images/juzvn5an/release-adp/78387ec01ecb90e6fd43a12f6d78d1d5379fd944-809x1000.png?w=3840', 'After Walker Evans: 4, 1981', '© Sherrie Levine', 'https://www.davidzwirner.com/artworks/sherrie-levine-after-walker-evans-4-33ae5', 'David Zwirner')], sourceLabel: 'Whitney Museum', sourceUrl: 'https://whitney.org/artists/2978'
  },
  {
    id: 'hans-peter-feldmann', name: 'Hans-Peter Feldmann', born: '1941–2023', base: 'Düsseldorf',
    intro: '把明信片、杂志图、家庭照片和日常物件当作巨大视觉档案，通过收集、分类、序列和重复削弱“杰作”的等级。',
    methods: ['found image', '收集', '分类学', '艺术家书', '挪用'], subjects: ['大众图像', '日常生活', '时间', '记忆', '价值', '图像过剩'], outputs: ['摄影系列', '艺术家书', '装置', '物件'],
    institutions: ['MoMA', 'Guggenheim'], achievements: ['Hugo Boss Prize 2010', 'documenta 5 / 6'],
    whyImportant: 'Feldmann 是理解“艺术家不一定负责拍摄，而可以负责选择、排序和观看制度”的关键人物，也直接连接 Joachim Schmid、Umbrico 等后来的 found-image 实践。',
    projects: [project('2001', '100 Years', '肖像 / 年龄分类', ['拍摄 101 位亲友，从 8 个月到 100 岁。', '统一尺寸并按年龄顺序展示。'], '非常简单的规则把个人肖像变成一条完整生命周期。')],
    images: [image('https://cdn.contemporaryartlibrary.org/store/image/57608/imagefile/xlarge-ff73d7789a3c99e691fb6bb9beb0ea43.jpg', '$100,000 Hugo Boss Prize installation', '© Hans-Peter Feldmann', 'https://www.contemporaryartlibrary.org/project/hans-peter-feldmann-at-guggenheim-new-york-6826', 'Contemporary Art Library / Guggenheim installation')], sourceLabel: 'MoMA', sourceUrl: 'https://www.moma.org/artists/8045-hans-peter-feldmann'
  },
  {
    id: 'alfredo-jaar', name: 'Alfredo Jaar', born: '1956', base: 'New York / Santiago',
    intro: '用摄影、文字、光、建筑和极度克制的装置研究新闻图像、战争、资源开采与“哪些事件被看见”的政治。',
    methods: ['研究型艺术', '文本 + 图像', '档案', '空间装置', '图像批判'], subjects: ['媒体', '战争', '殖民', '资源', '可见性', '人权'], outputs: ['装置', '摄影', '灯光', '公共艺术', '影像'],
    institutions: ['MoMA', 'Venice Biennale'], achievements: ['Venice Biennale 2026 International Exhibition'],
    whyImportant: '他经常故意不给观众“足够的照片”，用遮蔽、延迟、文字和光迫使观看者意识到新闻图像的伦理与分配机制。',
    projects: [project('1994–2000', 'The Rwanda Project', '长期研究 / 图像伦理', ['长期研究卢旺达大屠杀及媒体再现。', '以照片、文字、灯箱和缺席图像形成多个子项目。'], '不是寻找一张最惨烈的图片，而是研究为什么世界已经看到图像却仍然无动于衷。')],
    images: [image('https://goodman-gallery.com/_next/image?q=75&url=https%3A%2F%2Fd32637ifygiesu.cloudfront.net%2Fartists%2Falfredo-jaar%2Fthe-silence-of-nduwayezu-134391%2Falfredo-jaar-the-silence-of-nduwayezu-134391-61186-front-10.jpg&w=4480', 'The Silence of Nduwayezu', '© Alfredo Jaar', 'https://alfredojaar.net/projects/1997/the-rwanda-project/the-silence-of-nduwayezu/', 'Alfredo Jaar Studio / Goodman Gallery')], sourceLabel: 'Alfredo Jaar Studio', sourceUrl: 'https://alfredojaar.net/'
  },
  {
    id: 'vandy-rattana', name: 'Vandy Rattana', born: '1980', base: 'Phnom Penh / Taipei',
    intro: '从柬埔寨景观中的战争痕迹出发，逐渐转向电影、诗与私人记忆，把历史暴力放进看似平静的土地和家庭叙事。',
    methods: ['长期纪实', '景观摄影', '影像', '口述史', '诗性叙事'], subjects: ['战争记忆', '柬埔寨', '土地', '家庭', '创伤', '历史'], outputs: ['摄影系列', '录像', '电影', '出版'],
    institutions: ['Guggenheim', 'Singapore Biennale', 'Busan Biennale'], achievements: ['documenta 13 context', 'Guggenheim collection'],
    whyImportant: 'Bomb Ponds 的力量来自“什么都没发生”的景观：战争痕迹被自然和农业重新覆盖，历史必须通过研究和叙事重新进入照片。',
    projects: [project('2009', 'Bomb Ponds', '战争遗址 / 景观摄影', ['寻找美国轰炸留下并已积水、被农田吸收的弹坑。', '拍摄景观并记录幸存者证词。'], '照片故意平静，使不可见历史和当下日常发生冲突。')],
    images: [image('https://www.guggenheim.org/wp-content/uploads/2013/09/map_NC_VR_still_902.jpg', 'Bomb Ponds', '© Vandy Rattana', 'https://www.guggenheim.org/video/vandy-rattanas-bomb-ponds-photographs-and-video', 'Guggenheim')], sourceLabel: 'Vandy Rattana Studio', sourceUrl: 'https://vandyrattana.com/bio/'
  },
  {
    id: 'sunil-gupta', name: 'Sunil Gupta', born: '1953', base: 'London / New Delhi',
    intro: '四十多年持续从酷儿生活、迁徙、种族与 HIV 经验出发，把私人身体和公共空间连接成可见的社会历史。',
    methods: ['长期摄影', '肖像', '文本 + 摄影', '自传摄影', '社会纪实'], subjects: ['酷儿身份', '迁徙', 'HIV', '亲密关系', '印度', '英国'], outputs: ['摄影系列', '摄影书', '展览', '公共委托'],
    institutions: ['Tate', 'The Photographers’ Gallery'], achievements: ['Tate Photography monograph', 'major retrospective From Here to Eternity'],
    whyImportant: 'Gupta 的项目能看到身份议题如何在几十年里不断改变视觉形式：从街头情侣，到亲密关系肖像，再到把自己的医疗过程直接纳入摄影。',
    projects: [project('1986–1987', 'Exiles', '酷儿公共空间 / 新德里', ['在新德里公共地点拍摄男同性恋者。', '图像与个人叙述和城市地标共同构成系列。'], '亲密关系被放在高度公共、国家象征性的空间里，因此私人和政治无法分开。')],
    images: [image('https://www.outtraveler.com/media-library/subversive-pics-of-male-intimacy-challenged-1980s-india.jpg?id=33003062&width=980', 'Exiles, 1986–87', '© Sunil Gupta', 'https://www.outtraveler.com/photography/india-male-intimacy-pics', 'Out Traveler / project documentation')], sourceLabel: 'Tate Photography', sourceUrl: 'https://shop.tate.org.uk/tate-photography-sunil-gupta/29818.html'
  },
  {
    id: 'ana-mendieta', name: 'Ana Mendieta', born: '1948–1985', base: 'Cuba / United States',
    intro: '通过身体表演、土地、火、血、植物和 Super 8 电影，把自身轮廓短暂嵌入自然，持续处理流亡、性别与身体归属。',
    methods: ['行为', '身体印迹', '土地艺术', '自我表演', '影像记录'], subjects: ['身体', '流亡', '土地', '女性主义', '身份', '仪式'], outputs: ['摄影', 'Super 8 电影', '行为记录', 'earth-body work'],
    institutions: ['MoMA'], achievements: ['MoMA collection — 34 works online'],
    whyImportant: '她特别适合提醒摄影研究者：照片有时不是最终作品，而是短暂行为和土地介入留下的证据。',
    projects: [project('1973–1980', 'Silueta Series', 'earth-body / 行为记录', ['用泥土、草、火、血、花与身体轮廓制造短暂痕迹。', '以照片和 Super 8 记录会消失的行为。'], '摄影在这里承担保存和传播，而真正的动作发生在身体与土地之间。')],
    images: [image('https://4.bp.blogspot.com/-KJfMsXzrmtA/VS1syDvetjI/AAAAAAAAAIo/ajOQiDqCyyU/s1600/ana-mendieta-untitled-silueta-series-1978.jpg', 'Untitled, Silueta Series, 1978', '© The Estate of Ana Mendieta Collection, LLC', 'https://www.moma.org/collection/works/55939', 'MoMA / image documentation')], sourceLabel: 'MoMA', sourceUrl: 'https://www.moma.org/artists/3924-ana-mendieta'
  }
];

export const archiveBatch12New: Record<string, ArtistArchive> = {
  'catherine-opie': { artistId: 'catherine-opie', projectCoverage: '5 个肖像 / 社区 / 城市 / 私宅项目已完成第一轮 · 1991–2011', imageCoverage: '', note: '从酷儿社群肖像到城市基础设施和名人私宅，按摄影类型变化整理，不把她缩成单一“身份摄影”。', projects: [
    { title: 'Being and Having', cluster: 'queer portrait / gender performance', period: '1991', summary: '十三幅紧凑头像以统一黄色背景呈现朋友对男性气质的表演。', actions: ['朋友社群合作', '假胡须 / 服装', '统一背景', '近距离彩色肖像'], sourceUrl: 'https://www.moma.org/collection/works/407659', images: [img('https://artlogic-res.cloudinary.com/w_800%2Ch_500%2Cc_limit%2Cf_auto%2Cfl_lossy/artlogicstorage/thomasdane/images/view/55ac651f9efbfd929da89638304551c1j.jpg', 'Being and Having', '© Catherine Opie', 'https://www.moma.org/collection/works/407659', 'MoMA / Thomas Dane documentation')], relations: [rel('收藏', 'MoMA', '13-part work')] },
    { title: 'Portraits', cluster: 'queer community / formal portrait', period: '1993–1997', summary: '将朋友、伴侣与洛杉矶酷儿社群成员以高度正式的肖像语法拍摄，令身体改造、姿态和背景成为自我定义的一部分。', actions: ['中大画幅肖像', '纯色 / 华丽背景', '社群关系式拍摄'], sourceUrl: 'https://www.thomasdanegallery.com/artists/239-catherine-opie/biography/', images: [], relations: [] },
    { title: 'Freeways / Mini-malls', cluster: 'city infrastructure / typology', period: '1994–1998', summary: '转向洛杉矶高速路和商业建筑，以小尺幅黑白和类型化观看处理城市基础设施。', actions: ['城市巡游', '无人物建筑摄影', '类型式序列'], sourceUrl: 'https://art.state.gov/personnel/catherine_opie/', images: [], relations: [] },
    { title: 'Domestic', cluster: 'queer family / home / road trip', period: '1995–1998', summary: '跨美国拍摄女同性恋家庭与居家生活，使家庭肖像从边缘身份进入普通日常。', actions: ['跨州旅行', '家庭协作', '环境肖像', '室内自然光'], sourceUrl: 'https://www.thomasdanegallery.com/artists/239-catherine-opie/biography/', images: [], relations: [] },
    { title: '700 Nimes Road', cluster: 'indirect portrait / possessions / celebrity home', period: '2010–2011', summary: '在 Elizabeth Taylor 的住所拍摄房间、衣服、鞋、珠宝与纪念物，以物件建立没有人物出现的肖像。', actions: ['六个月进入私宅', '房间与物件摄影', '跨尺度编辑', '不直接拍摄人物'], sourceUrl: 'https://www.moca.org/exhibition/catherine-opie-700-nimes-road', images: [img('https://www.moca.org/storage/app/uploads/public/56b/001/549/thumb_1232_1120_0_0_0_auto.jpg', '700 Nimes Road — installation', '© Catherine Opie / MOCA installation', 'https://www.moca.org/exhibition/catherine-opie-700-nimes-road', 'MOCA Los Angeles')], relations: [rel('展览', 'MOCA Pacific Design Center', '2016')] }
  ], awards: [], exhibitions: ['Guggenheim retrospective 2008', '700 Nimes Road — MOCA 2016'], sources: [{ label: 'MoMA artist archive', url: 'https://www.moma.org/artists/8190-catherine-opie' }, { label: 'Thomas Dane biography', url: 'https://www.thomasdanegallery.com/artists/239-catherine-opie/biography/' }] },
  'larry-sultan': { artistId: 'larry-sultan', projectCoverage: '4 个奠基性项目已完成第一轮 · 1975–2009', imageCoverage: '', note: '按 SFMOMA 回顾展的四个核心项目整理：从机构档案挪用到家庭、成人影像郊区和日工摆拍。', projects: [
    { title: 'Evidence', cluster: 'institutional archive / found image', period: '1975–1977', summary: '与 Mike Mandel 从政府、企业、科研机构档案中挑选原本服务特定功能的照片，去掉说明重新编成书。', actions: ['进入机构档案', 'found photographs', '去除原说明', '重新 sequence'], sourceUrl: 'https://www.larrysultan.com/gallery/evidence/', images: [], relations: [rel('展览', 'SFMOMA', '1977'), rel('出版', 'Evidence', '1977')] },
    { title: 'Pictures from Home', cluster: 'family archive / staged documentary', period: '1983–1992', summary: '十年拍摄父母，并加入家庭快照、录像截图和父母对摄影师叙事的反驳。', actions: ['长期回家拍摄', '编排与观察并用', '家庭录像截帧', '父母文字 / 采访'], sourceUrl: 'https://www.sfmoma.org/artwork/93.228/', images: [img('https://www.larrysultan.com/wp-content/uploads/2013/06/SULPFH1986_Bankbox2_ConversationOnBed-1024x807.jpg', 'Conversation on Bed', '© Estate of Larry Sultan', 'https://www.larrysultan.com/gallery/pictures-from-home/conversation-on-bed/', 'Larry Sultan Estate')], relations: [rel('出版', 'Pictures from Home', '1992')] },
    { title: 'The Valley', cluster: 'suburb / adult-film set / staged reality', period: '1997–2003', summary: '在 San Fernando Valley 被租作成人影片片场的普通住宅中拍摄，关注摄影棚设备、演员与家庭空间之间的错位。', actions: ['进入成人影片拍摄现场', '大画幅彩色摄影', '避开主要表演而拍外围空间'], sourceUrl: 'https://www.sfmoma.org/press/release/sfmoma-presents-upcoming-photography-exhibition-l/', images: [img('https://www.christies.com/img/LotImages/2023/NYR/2023_NYR_21966_0059_000%28larry_sultan_boxers_mission_hills_1999020823%29.jpg?mode=max', 'Boxers, Mission Hills, 1999', '© Estate of Larry Sultan', 'https://onlineonly.christies.com.cn/s/photographs/larry-sultan-1946-2009-59/178957', 'Christie’s artwork record')], relations: [rel('展览', 'SFMOMA', '2004')] },
    { title: 'Homeland', cluster: 'day labour / suburban landscape / reenactment', period: '2006–2009', summary: '雇佣日工在北加州郊区重新表演普通家庭与休闲动作，讨论家、劳动与公共空间之间的边界。', actions: ['与日工合作', '郊区选景', '动作编排', '大画幅摄影'], sourceUrl: 'https://www.sfmoma.org/artist/Larry_Sultan/', images: [], relations: [] }
  ], awards: [], exhibitions: ['Larry Sultan: Here and Home — LACMA / SFMOMA', 'The Valley — SFMOMA 2004'], sources: [{ label: 'SFMOMA retrospective', url: 'https://www.sfmoma.org/exhibition/larry-sultan-here-and-home/' }, { label: 'Larry Sultan Estate', url: 'https://www.larrysultan.com/' }] },
  'sherrie-levine': { artistId: 'sherrie-levine', projectCoverage: '5 个挪用 / 再制作节点已完成第一轮 · 1979–2011', imageCoverage: '', note: '从照片再摄影到雕塑复制，追踪“after”如何从摄影史扩展到整个现代艺术史。', projects: [
    { title: 'President Collages', cluster: 'magazine image / collage / Pictures Generation', period: '1979', summary: '早期使用大众印刷图像拼贴，已经把“现成视觉文化”而非原创拍摄当作材料。', actions: ['杂志图像搜集', '裁切', '拼贴'], sourceUrl: 'https://www.davidzwirner.com/artists/sherrie-levine', images: [], relations: [] },
    { title: 'After Edward Weston', cluster: 'rephotography / canon', period: '1980', summary: '从 Weston 的经典人体摄影复制并重新摄影，把摄影大师的作者权威转成可再生产的图像。', actions: ['艺术史复制图选择', '再摄影', '重新署名 / 展示'], sourceUrl: 'https://www.davidzwirner.com/artists/sherrie-levine', images: [], relations: [] },
    { title: 'After Walker Evans', cluster: 'rephotography / authorship', period: '1981', summary: '从展览图录复制 Walker Evans 的大萧条时期照片并作为自己的作品重新展示。', actions: ['图录复制', '再摄影', '统一打印', '系列呈现'], sourceUrl: 'https://whitney.org/artists/2978', images: [img('https://cdn.sanity.io/images/juzvn5an/release-adp/78387ec01ecb90e6fd43a12f6d78d1d5379fd944-809x1000.png?w=3840', 'After Walker Evans: 4', '© Sherrie Levine', 'https://www.davidzwirner.com/artworks/sherrie-levine-after-walker-evans-4-33ae5', 'David Zwirner')], relations: [rel('收藏', 'Whitney Museum', 'After Walker Evans works')] },
    { title: 'Fountain (After Marcel Duchamp)', cluster: 'readymade / bronze reproduction', period: '1991', summary: '把 Duchamp 的 urinal readymade 重新铸造成高度抛光的青铜雕塑，让复制对象再次变成昂贵独特物。', actions: ['艺术史对象复制', '青铜铸造', '表面抛光'], sourceUrl: 'https://www.davidnolangallery.com/artworks/17603-sherrie-levine-fountain-after-marcel-duchamp-1991/', images: [img('https://static-assets.artlogic.net/w_1600%2Ch_1600%2Cc_limit%2Cf_auto%2Cfl_lossy%2Cq_auto/artlogicstorage/davidnolangallery/images/view/cebe42239ec6302b205b1b54e1729dcbj/davidnolangallery-sherrie-levine-fountain-after-marcel-duchamp-1991.jpg', 'Fountain (After Marcel Duchamp)', '© Sherrie Levine', 'https://www.davidnolangallery.com/artworks/17603-sherrie-levine-fountain-after-marcel-duchamp-1991/', 'David Nolan Gallery')], relations: [] },
    { title: 'Crystal Skull / Mayhem', cluster: 'replication / museum survey', period: '2010–2011', summary: '透明水晶头骨与跨三十年作品在 Whitney 的 Mayhem 中并置，把复制扩展到雕塑、物件与展示制度。', actions: ['物件复制', '材料转换', '跨年代展览编辑'], sourceUrl: 'https://whitney.org/artists/2978', images: [], relations: [rel('展览', 'Sherrie Levine: Mayhem — Whitney', '2011–2012')] }
  ], awards: [], exhibitions: ['Whitney Biennial 1985 / 1989 / 2008 / 2014', 'Mayhem — Whitney 2011'], sources: [{ label: 'Whitney Museum', url: 'https://whitney.org/artists/2978' }, { label: 'David Zwirner', url: 'https://www.davidzwirner.com/artists/sherrie-levine' }] },
  'hans-peter-feldmann': { artistId: 'hans-peter-feldmann', projectCoverage: '4 个图像档案 / 分类 / 价值项目已完成第一轮 · 1968–2011', imageCoverage: '', note: '从廉价图片小册子到 101 人年龄分类和把奖金贴满墙，强调他的核心是搜集、规则与重新赋值。', projects: [
    { title: 'Bilder / small image books', cluster: 'found image / artist book / archive', period: '1968–1970s', summary: '把明信片、报刊和日常图片按非常简单的题目做成廉价小册子，让图像分类本身成为作品。', actions: ['found image 搜集', '按题目分类', '低成本印刷', '编号小册子'], sourceUrl: 'https://www.moma.org/calendar/exhibitions/4832', images: [], relations: [] },
    { title: 'All the Clothes of a Woman', cluster: 'inventory / everyday archive', period: '1973', summary: '以连续照片把一名女性的全部衣物转成平铺式视觉清单。', actions: ['日常物件收集', '逐件摄影', '序列 / 清单'], sourceUrl: 'https://www.guggenheim.org/exhibition/hans-peter-feldmann', images: [], relations: [] },
    { title: '100 Years', cluster: 'age / portrait / taxonomy', period: '2001', summary: '拍摄 101 位亲友，年龄从 8 个月到 100 岁，并按年龄顺序连续展示。', actions: ['亲友招募', '统一黑白肖像', '按年龄排序', '101张连续安装'], sourceUrl: 'https://www.moma.org/calendar/exhibitions/4832', images: [], relations: [rel('展览', 'MoMA PS1', '2004–2005'), rel('收藏', 'MoMA', '101 prints')] },
    { title: '$100,000 installation', cluster: 'prize money / institutional value', period: '2011', summary: '把 Hugo Boss Prize 的十万美元兑换为一美元纸币并覆盖 Guggenheim 展厅墙壁和柱子。', actions: ['奖金兑换成纸币', '逐张固定', '覆盖完整展厅表面'], sourceUrl: 'https://www.contemporaryartlibrary.org/project/hans-peter-feldmann-at-guggenheim-new-york-6826', images: [img('https://cdn.contemporaryartlibrary.org/store/image/57608/imagefile/xlarge-ff73d7789a3c99e691fb6bb9beb0ea43.jpg', '$100,000 installation', '© Hans-Peter Feldmann', 'https://www.contemporaryartlibrary.org/project/hans-peter-feldmann-at-guggenheim-new-york-6826', 'Contemporary Art Library')], relations: [rel('奖项', 'Hugo Boss Prize', 'winner 2010'), rel('展览', 'Guggenheim Museum', '2011')] }
  ], awards: ['Hugo Boss Prize 2010'], exhibitions: ['documenta 5 / 6', 'Utopia Station — Venice Biennale 2003', 'MoMA PS1 2004–05', 'Guggenheim 2011'], sources: [{ label: 'MoMA — 100 Years', url: 'https://www.moma.org/calendar/exhibitions/4832' }, { label: 'MoMA artist archive', url: 'https://www.moma.org/artists/8045-hans-peter-feldmann' }] },
  'alfredo-jaar': { artistId: 'alfredo-jaar', projectCoverage: '5 个媒体 / 战争 / 资源政治项目已完成第一轮 · 1985–2026', imageCoverage: '', note: '按图像“出现—被遮蔽—被替代—完全缺席”的变化整理，重点不是装置风格而是每次如何控制观众获得信息。', projects: [
    { title: 'Gold in the Morning', cluster: 'Chile / gold mining / labour', period: '1985', summary: '在巴西 Serra Pelada 金矿拍摄劳动与资源开采，并将影像放入更大的经济和殖民关系中。', actions: ['矿区田野', '摄影', '文字 / 地缘经济研究'], sourceUrl: 'https://alfredojaar.net/', images: [], relations: [] },
    { title: 'The Rwanda Project', cluster: 'genocide / media representation / long-term research', period: '1994–2000', summary: '六年间制作一系列彼此不同的装置，持续研究卢旺达大屠杀如何被媒体看见、忽略和消费。', actions: ['现场研究', '新闻档案', '文字 / 照片 / 灯箱', '系列化子项目'], sourceUrl: 'https://alfredojaar.net/projects/1997/the-rwanda-project/the-silence-of-nduwayezu/', images: [img('https://goodman-gallery.com/_next/image?q=75&url=https%3A%2F%2Fd32637ifygiesu.cloudfront.net%2Fartists%2Falfredo-jaar%2Fthe-silence-of-nduwayezu-134391%2Falfredo-jaar-the-silence-of-nduwayezu-134391-61186-front-10.jpg&w=4480', 'The Silence of Nduwayezu', '© Alfredo Jaar', 'https://alfredojaar.net/projects/1997/the-rwanda-project/the-silence-of-nduwayezu/', 'Alfredo Jaar Studio / Goodman Gallery')], relations: [] },
    { title: 'Lament of the Images', cluster: 'image absence / text / light', period: '2002', summary: '先让观众阅读关于图像控制和档案的文字，再进入只有强光而没有照片的空间。', actions: ['研究新闻图片制度', '文字灯箱', '空间遮蔽', '强光替代图像'], sourceUrl: 'https://www.moma.org/artists/2933-alfredo-jaar', images: [], relations: [rel('收藏', 'MoMA', 'Lament of the Images')] },
    { title: 'The Sound of Silence', cluster: 'photojournalism / architecture / timed sequence', period: '2006', summary: '观众进入封闭光箱，通过定时文本和闪光了解 Kevin Carter 影像的生产、获奖与伦理后果。', actions: ['建筑式暗室', '定时文字 sequence', '闪光 / 单张新闻图像', '观看时间控制'], sourceUrl: 'https://alfredojaar.net/', images: [], relations: [] },
    { title: 'The End of the World', cluster: 'critical minerals / immersive red environment', period: '2023–2026', summary: '把关键矿物与全球技术供应链压缩成极小物件置于巨大的红色空间中，2026 进入威尼斯国际主展。', actions: ['关键矿物研究', '材料压缩 / 小型物件', '红色灯光环境', '尺度反差'], sourceUrl: 'https://www.labiennale.org/en/art/2026/61st-exhibition', images: [img('https://static-assets.artlogic.net/w_1200%2Cc_limit%2Cf_auto%2Cfl_lossy%2Cq_auto/ws-artlogicwebsite1524/usr/images/exhibitions/main_image_override/72/005.jpeg', 'La Fin du Monde / The End of the World — installation', '© Alfredo Jaar', 'https://prvbgallery.com/exhibitions/', 'Galerie La Patinoire Royale Bach')], relations: [rel('展览', 'Venice Biennale — International Exhibition', '2026')] }
  ], awards: [], exhibitions: ['Venice Biennale 2026 — In Minor Keys'], sources: [{ label: 'Alfredo Jaar Studio', url: 'https://alfredojaar.net/' }, { label: 'MoMA artist archive', url: 'https://www.moma.org/artists/2933-alfredo-jaar' }] },
  'vandy-rattana': { artistId: 'vandy-rattana', projectCoverage: '4 个景观 / 战争记忆 / 影像节点已完成第一轮 · 2009–2019', imageCoverage: '', note: '从 Bomb Ponds 的景观证据转向 Monologue 三部曲，记录摄影如何逐渐让位于诗、旁白和电影时间。', projects: [
    { title: 'Bomb Ponds', cluster: 'US bombing / landscape / testimony', period: '2009', summary: '寻找柬埔寨乡村仍可辨认的轰炸坑并拍摄，同时记录幸存者对美国轰炸的记忆。', actions: ['田野寻找弹坑', '中远景景观摄影', '幸存者采访', '摄影 + 录像'], sourceUrl: 'https://www.guggenheim.org/video/vandy-rattanas-bomb-ponds-photographs-and-video', images: [img('https://www.guggenheim.org/wp-content/uploads/2013/09/map_NC_VR_still_902.jpg', 'Bomb Ponds', '© Vandy Rattana', 'https://www.guggenheim.org/video/vandy-rattanas-bomb-ponds-photographs-and-video', 'Guggenheim')], relations: [rel('收藏', 'Guggenheim', 'Bomb Ponds')] },
    { title: 'Surface', cluster: 'urban change / Phnom Penh', period: '2012', summary: '继续从地表和城市空间寻找政治、开发与记忆留下的可见变化。', actions: ['城市田野', '摄影', '空间观察'], sourceUrl: 'https://vandyrattana.com/bio/', images: [], relations: [rel('展览', 'SA SA BASSAC', '2012')] },
    { title: 'MONOLOGUE', cluster: 'Khmer Rouge / family grave / film-poem', period: '2015', summary: '围绕从未见过的姐姐和祖母被掩埋的无名土地展开个人独白，让两棵芒果树成为私人和国家历史的地标。', actions: ['家庭历史研究', '地点回访', '单频道电影', '诗 / 旁白'], sourceUrl: 'https://vandyrattana.com/bio/', images: [], relations: [rel('展览', 'Jeu de Paume / CAPC', '2015')] },
    { title: 'Monologue Trilogy', cluster: 'memory / landscape / moving image', period: '2015–2019', summary: 'MONOLOGUE、Funeral 与 …far away, over there, the ocean 组成三部曲，以自然景观、诗和虚构叙事处理死亡与历史沉默。', actions: ['三部短片', '诗性旁白', '景观长镜头', '跨片重复意象'], sourceUrl: 'https://vandyrattana.com/bio/', images: [], relations: [rel('展览', 'Singapore Biennale', '2019')] }
  ], awards: [], exhibitions: ['documenta 13', 'Singapore Biennale 2019', 'Busan Biennale 2020', 'Carnegie International 2022'], sources: [{ label: 'Vandy Rattana biography', url: 'https://vandyrattana.com/bio/' }, { label: 'Guggenheim — Bomb Ponds', url: 'https://www.guggenheim.org/video/vandy-rattanas-bomb-ponds-photographs-and-video' }] },
  'sunil-gupta': { artistId: 'sunil-gupta', projectCoverage: '5 个酷儿 / 迁徙 / HIV 项目已完成第一轮 · 1976–2022', imageCoverage: '', note: '沿 New York、London、Delhi 与个人 HIV 经验整理，强调不同历史阶段如何改变拍摄关系和文本结构。', projects: [
    { title: 'Christopher Street', cluster: 'New York / queer street life', period: '1976', summary: '在纽约 Christopher Street 拍摄同性恋解放后的街头社交和公共空间。', actions: ['街头摄影', '社群内部视角', '黑白摄影'], sourceUrl: 'https://shop.tate.org.uk/tate-photography-sunil-gupta/29818.html', images: [], relations: [] },
    { title: 'Lovers: Ten Years On', cluster: 'long-term couples / portrait', period: '1984–1986', summary: '寻找并拍摄长期同性伴侣，把持续关系而不是出柜危机作为主题。', actions: ['伴侣招募', '环境肖像', '关系叙事'], sourceUrl: 'https://hymancollection.org/artists/217-sunil-gupta/overview/', images: [], relations: [] },
    { title: 'Exiles', cluster: 'Delhi / public intimacy / text-photo', period: '1986–1987', summary: '在新德里公共地标拍摄男同性恋者，并以文字将当时法律和私人生活压进同一空间。', actions: ['新德里公共地点选景', '双人肖像', '文本 / 个人叙述'], sourceUrl: 'https://shop.tate.org.uk/tate-photography-sunil-gupta/29818.html', images: [img('https://www.outtraveler.com/media-library/subversive-pics-of-male-intimacy-challenged-1980s-india.jpg?id=33003062&width=980', 'Exiles', '© Sunil Gupta', 'https://www.outtraveler.com/photography/india-male-intimacy-pics', 'Out Traveler / project documentation')], relations: [] },
    { title: 'From Here to Eternity', cluster: 'HIV / self / healthcare', period: '1999', summary: '确诊 HIV 后将自己的治疗、医院和南伦敦生活直接纳入摄影，身体成为医疗制度和私人经验的交点。', actions: ['自传摄影', '医疗空间', '自我身体', '暗房打印'], sourceUrl: 'https://hymancollection.org/artists/217-sunil-gupta/overview/', images: [], relations: [] },
    { title: 'Songs of Deliverance', cluster: 'healthcare / queer belonging / commission', period: '2022', summary: '以医院委托继续讨论公共医疗系统如何进入酷儿生活、照护和归属。', actions: ['医院委托', '肖像 / 空间摄影', '公共展览'], sourceUrl: 'https://www.imperialcharity.org.uk/arts/exhibitions/sunil-gupta-songs-of-deliverance', images: [], relations: [rel('展览', 'Imperial Health Charity hospitals', '2022')] }
  ], awards: [], exhibitions: ['From Here to Eternity — major retrospective contexts'], sources: [{ label: 'Tate Photography', url: 'https://shop.tate.org.uk/tate-photography-sunil-gupta/29818.html' }, { label: 'Hyman Collection overview', url: 'https://hymancollection.org/artists/217-sunil-gupta/overview/' }] },
  'ana-mendieta': { artistId: 'ana-mendieta', projectCoverage: '5 个身体表演 / earth-body / 电影节点已完成第一轮 · 1972–1981', imageCoverage: '', note: '按身体从“被变形的脸”逐渐转向土地中的缺席轮廓整理，同时把照片和 Super 8 视为行为记录而不是唯一成品。', projects: [
    { title: 'Facial Cosmetic Variations', cluster: 'face / performance / photography', period: '1972', summary: '通过假发、化妆、姿势与面部操作把自己的脸连续改变，摄影记录每种身份状态。', actions: ['自我表演', '化妆 / 假发', '连续彩色肖像'], sourceUrl: 'https://www.moma.org/collection/works/55679', images: [img('https://www.meer.com/attachments/093817dcc0b2041eef0abb657a1ac06637765205/store/fill/860/645/3ffa1ac7d536d470da21ac5f22c13e2ec58d0517f28465f0f9353c068c7b/Ana-Mendieta-Untitled-Facial-Cosmetic-Variations-1972.jpg', 'Facial Cosmetic Variations', '© The Estate of Ana Mendieta Collection, LLC', 'https://www.moma.org/collection/works/55679', 'MoMA / Meer image documentation')], relations: [rel('收藏', 'MoMA', 'four chromogenic prints')] },
    { title: 'Glass on Body Imprints', cluster: 'body distortion / glass / performance', period: '1972', summary: '将脸和身体压在透明玻璃上，让肉体被压力变形，再用相机正面记录。', actions: ['玻璃施压', '身体表演', '摄影记录'], sourceUrl: 'https://www.moma.org/artists/3924-ana-mendieta', images: [], relations: [] },
    { title: 'Silueta Series', cluster: 'earth-body / absence / ritual', period: '1973–1980', summary: '以身体或身体轮廓在泥土、沙、草、火、花等环境中留下短暂印迹，再用照片和电影保存。', actions: ['身体轮廓制作', '自然材料', '火 / 水 / 血等过程', '照片与Super 8记录'], sourceUrl: 'https://www.moma.org/collection/works/55939', images: [img('https://4.bp.blogspot.com/-KJfMsXzrmtA/VS1syDvetjI/AAAAAAAAAIo/ajOQiDqCyyU/s1600/ana-mendieta-untitled-silueta-series-1978.jpg', 'Untitled, Silueta Series, 1978', '© The Estate of Ana Mendieta Collection, LLC', 'https://www.moma.org/collection/works/55939', 'MoMA / image documentation')], relations: [rel('收藏', 'MoMA', 'photograph and film records')] },
    { title: 'Ocean Bird (Washup)', cluster: 'film / body / ocean / metamorphosis', period: '1974', summary: '以羽毛覆盖身体并在海边行动，电影记录身体、动物形象和海浪之间的变形过程。', actions: ['身体覆盖羽毛', '海岸行为', 'Super 8拍摄'], sourceUrl: 'https://www.moma.org/calendar/galleries/5778', images: [], relations: [rel('展览', 'Three Films by Ana Mendieta — MoMA', '2024–2026')] },
    { title: 'Gunpowder Works / Birth', cluster: 'fire / trace / earth-body', period: '1981', summary: '用火药在土地或石材上制造瞬间燃烧和残留痕迹，身体由实际出现进一步转向缺席的轮廓。', actions: ['火药布置', '点燃', '地表痕迹', '摄影 / 电影记录'], sourceUrl: 'https://www.moma.org/artists/3924-ana-mendieta', images: [], relations: [] }
  ], awards: [], exhibitions: ['Three Films by Ana Mendieta — MoMA 2024–2026'], sources: [{ label: 'MoMA artist archive', url: 'https://www.moma.org/artists/3924-ana-mendieta' }, { label: 'MoMA — Three Films', url: 'https://www.moma.org/calendar/galleries/5778' }] }
};
